- lib/web_ui/dev/felt
Changing user limits on MacOs.
> [web] changing user limits for macos

- lib/ui/dart_runtime_hooks.cc
> Enable HTTP and socket profiling dart:io service extensions for Flutter

- .cirrus.yml
See https://github.com/flutter/flutter/issues/52263
TBR: @chinmaygarde
> Disable shell benchmarks

- flow/layers/image_filter_layer.cc
- flow/layers/image_filter_layer_unittests.cc
Reverts flutter/engine#16960
The change caused golden file failures in flutter/flutter
> Revert "Fix bounds of image_filter_layer"

- shell/platform/darwin/ios/rendering_api_selection.mm
Fixes https://github.com/flutter/flutter/issues/52356
> Update the Metal backend selection to use iOS 10.0 and A7 as the version floor.

- shell/platform/glfw/flutter_glfw.cc
Fixes a regression from https://github.com/flutter/engine/pull/16944
> Fix copy/paste mistake in GLFW asset path resolution

- shell/platform/darwin/ios/framework/Source/accessibility_text_entry.mm
relevant issue: https://github.com/flutter/flutter/issues/52487
> Removed a text input trait that causes VoiceOver to be incorrect when tapping a text input.

- lib/ui/window.dart
- testing/dart/locale_test.dart
Fixes https://github.com/flutter/flutter/issues/43607
> Add empty string check to Locale toString

- runtime/service_protocol.cc
- runtime/service_protocol.h
- shell/common/persistent_cache.cc
- shell/common/persistent_cache.h
- shell/common/shell.cc
- shell/common/shell.h
- shell/common/shell_test.cc
- shell/common/shell_test.h
- shell/common/shell_unittests.cc
Fixes https://github.com/flutter/flutter/issues/53114
> Add service protocol to get SkSLs

- lib/web_ui/dev/browser_lock.yaml
changing the chrome version for linux to the latest version.
> change chrome version

- shell/platform/android/io/flutter/plugin/platform/SingleViewPresentation.java
Fixes https://github.com/flutter/flutter/issues/53444
> Use the private presentation window type for platform view windows

- ci/check_gn_format.py
'--dry-run false' doesn't work. Not specifying --dry-run is enough.
Also correct the gn path.
> Correct --dry-run hint

- fml/raster_thread_merger.cc
- fml/raster_thread_merger.h
- lib/ui/compositing/scene_host.cc
- lib/ui/painting/picture.cc
- shell/common/shell.cc
This follows the comments in https://github.com/flutter/engine/pull/17408
> GPU to raster rename, patch 2

- shell/common/canvas_spy.cc
- shell/common/canvas_spy.h
- testing/mock_canvas.cc
- testing/mock_canvas.h
API staging is complete - these defines have been removed.
> Finish removing deprecated SkCanvas virtuals

- shell/platform/darwin/ios/platform_view_ios.h
- shell/platform/darwin/ios/platform_view_ios.mm
Relevant issue: https://github.com/flutter/flutter/issues/53681
> Started clearing out the semantics information in Dart as well as deleting the AccessibilityBridge.

- tools/fuchsia/merge_and_upload_debug_symbols.py
This reverts commit 03d5e500037fb091c9f044a067fca84466a191e5.
This is causing "Linux Fuchsia" failures
> Revert "[tools][fuchsia] Do not tar debug symbol CIPD uploads (#17275)"

- shell/platform/darwin/ios/framework/Headers/FlutterEngine.h
- shell/platform/darwin/ios/framework/Headers/FlutterHeadlessDartRunner.h
- shell/platform/darwin/ios/framework/Headers/FlutterViewController.h
Closes https://github.com/flutter/flutter/issues/39516
> Small updates to objcdocs

- shell/platform/android/io/flutter/app/FlutterFragmentActivity.java
- shell/platform/android/io/flutter/embedding/android/FlutterFragmentActivity.java
Upstream change google-internal
> onRequestPermissionsResult now require calling super on AndroidX master

- tools/fuchsia/merge_and_upload_debug_symbols.py
This reverts commit 4b69cf2c49db43ec89bb5004d1f4b767194c4fea.
> Revert "[tools][fuchsia] Do not tar debug symbol CIPD uploads (#17506)"

- shell/platform/darwin/ios/framework/Source/SemanticsObject.h
- shell/platform/darwin/ios/framework/Source/accessibility_bridge.mm
> Added missing declaration (only showed up in g3 builds).

- shell/common/rasterizer.cc
Working theory is that adding async events with begin times
in the past causes the timeline to skip some events.
See: https://github.com/flutter/flutter/issues/54095
> Remove SceneDisplayLag trace event temporarily

- testing/fuchsia/run_tests.sh
Adding logs and date time in between steps will simplify finding the
steps that are failing during the fuchsia tests.
https://github.com/flutter/flutter/issues/54253
> Add logs between fuchsia test steps.

- tools/fuchsia/merge_and_upload_debug_symbols.py
Fuchsia is the main consumer of these CIPD packages and - to simplify
its infrastructure - it is migrating its SDK partners over to producing
a CIPD package containing a flat .build-id directory.
This change also updates the CIPD package so that the .build-id
directory is placed at the root.
Bug: fxbug.dev/41443
> [tools][fuchsia] Reland 'Do not tar debug symbol CIPD uploads'

- fml/log_settings.cc
- fml/log_settings.h
- shell/common/persistent_cache.cc
- shell/common/persistent_cache.h
- shell/common/persistent_cache_unittests.cc
- shell/common/run_configuration.cc
- shell/common/shell.cc
- shell/common/shell_test.cc
- shell/common/shell_test.h
- shell/common/shell_unittests.cc
- testing/fuchsia/run_tests.sh
Fixes https://github.com/flutter/flutter/issues/53117
Test added:
- ShellTest.CanLoadSkSLsFromAsset
> Read SkSLs from asset

- shell/platform/linux/fl_dart_project.cc
- shell/platform/linux/fl_view.cc
- shell/platform/linux/public/flutter_linux/fl_dart_project.h
- shell/platform/linux/public/flutter_linux/fl_view.h
> Move Linux shell docstrings to headers

- .github/auto_assign.yml
> Remove franciscojma86 from autoassign

- tools/fuchsia/fuchsia_libs.gni
Fixes: https://github.com/flutter/flutter/issues/43926
> [fuchsia] Remove redundant libs

- shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm
- shell/platform/darwin/ios/framework/Source/FlutterTextInputPluginTest.m
Fixes https://github.com/flutter/flutter/issues/55081
> Fix a typo so that the secure input view is properly initialized

- testing/fuchsia/run_tests.sh
Bug:
https://github.com/flutter/flutter/issues/50249
https://github.com/flutter/flutter/issues/55165
> Pass amber-files directory to tests.

- shell/common/persistent_cache.cc
- shell/common/persistent_cache.h
- shell/common/persistent_cache_unittests.cc
Fixes https://github.com/flutter/flutter/issues/55219
> Read SkSL from json asset

- shell/common/rasterizer.cc
Reverts flutter/engine#17878
This breaks our devicelab tests.
@flar has more details of why it fails.
TBR: @flar
> Revert "[tracing] SceneDisplayLag is a synchronous event"

- testing/fuchsia/run_tests.sh
Bug:
https://bugs.fuchsia.dev/p/fuchsia/issues/detail?id=47081
> Reenable flutter scenic test to identify crashes and follow up on fixes.

- testing/scenario_app/ios/Scenarios/ScenariosUITests/TextSemanticsFocusTest.m
related issue: https://github.com/flutter/flutter/issues/55778
> Bumped up the timeout for testAccessibilityFocusOnTextSemanticsProducesCorrectIosViews

- shell/platform/android/io/flutter/embedding/android/FlutterView.java
- shell/platform/android/test/io/flutter/embedding/android/FlutterViewTest.java
PR from @lidongze91 https://github.com/flutter/engine/pull/17748. 
Added tests. 
Fixes https://github.com/flutter/flutter/issues/54911.
> remove top padding when system UI in fullscreen mode

- testing/scenario_app/ios/Scenarios/ScenariosUITests/TextSemanticsFocusTest.m
Flaking https://ci.chromium.org/p/flutter/builders/prod/Mac%20iOS%20Engine/4974
related issue: https://github.com/flutter/flutter/issues/55778
> skip TextSemanticsFocusTest for flake

- lib/web_ui/test/text/line_breaker_test.dart
This is the first PR in a sequence to implement https://github.com/flutter/flutter/issues/45932.
> [web] First batch of unit tests for line breaker

- lib/web_ui/dev/browser.dart
- lib/web_ui/dev/test_platform.dart
- lib/web_ui/pubspec.yaml
- web_sdk/web_engine_tester/pubspec.yaml
Fixes https://github.com/flutter/flutter/issues/56289
> [web] Upgrade the test package to remove the dependency on package_resolver

- flow/layers/opacity_layer.cc
- flow/layers/opacity_layer_unittests.cc
This fixes https://github.com/flutter/flutter/issues/56722
> Restore integer snapping on OpacityLayer

- testing/fuchsia/run_tests.sh
This reverts commit efdc0994a064160d4331c5ec89e24e5ac4a7f641.
> Revert "Re-enable Fuchsia tests (#18342)"

- lib/web_ui/lib/src/engine/surface/picture.dart
- lib/web_ui/test/engine/surface/scene_builder_test.dart
Fixes https://github.com/flutter/flutter/issues/57105
> release previous canvas when picture is not painted

- testing/fuchsia/run_tests.sh
seems like flow tests are leaving devices in a bad state.
> Disable flow tests.

- testing/ios/IosUnitTests/IosUnitTests.xcodeproj/project.pbxproj
- testing/ios/IosUnitTests/build_and_run_tests.sh
- testing/ios/IosUnitTests/run_tests.sh
Also make some ergonomic improvements to the scripts to be runnable from any location.
> Add ocmock to iOS unit tests xcode project

- testing/fuchsia/run_tests.sh
See: https://github.com/flutter/flutter/issues/57273
> [fuchsia] Remove log dumping to prevent timeouts

- shell/platform/embedder/embedder_external_view_embedder.cc
- shell/platform/fuchsia/flutter/vulkan_surface_producer.cc
- vulkan/vulkan_swapchain.cc
This has no functional change but the pure flush() calls are being removed and replaced with flushAndSubmit calls.
> Update flutter skia flush calls to new flush and submit api

- lib/web_ui/lib/src/engine/dom_renderer.dart
- lib/web_ui/lib/src/engine/window.dart
Related issue: https://github.com/flutter/flutter/issues/55892
> [web] Implement setPreferredOrientation

- lib/ui/semantics.dart
- lib/web_ui/lib/src/ui/semantics.dart
Also covers counterparts of these calls in web_ui.
> null-annotate native calls in lib/ui/semantics.dart

- e2etests/web/regular_integration_tests/test_driver/target_platform_android_e2e.dart
- e2etests/web/regular_integration_tests/test_driver/target_platform_ios_e2e.dart
- e2etests/web/regular_integration_tests/test_driver/target_platform_macos_e2e.dart
- lib/web_ui/dev/integration_tests_manager.dart
fix the issue in the test and remove them from the blacklist for chrome.
I thought this was a setup issue in the harness, so I added them to blacklist. Looks like it was a small issue on the tests.
> [web] remove target tests from the blacklist

- lib/web_ui/lib/src/engine/dom_renderer.dart
- lib/web_ui/lib/src/engine/window.dart
- lib/web_ui/lib/src/ui/window.dart
- lib/web_ui/test/engine/window_test.dart
Fixes https://github.com/flutter/flutter/issues/54669
Fixes https://github.com/flutter/flutter/issues/48886
Here's the new gallery after I changed my Chrome default language to Russian:
> Implement `local`, `locales`, and `onLocaleChanged` for the web

- shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm
- shell/platform/darwin/ios/framework/Source/FlutterTextInputPluginTest.m
Fixes: https://github.com/flutter/flutter/issues/57160
The framework caches the last `TextEditingValue` sent from the engine. The ios text input plugin needs to echo the `TextEditingValue` back on selection only changes, so the framework can properly update the cache.
> Echo text selection changes and marked text selection changes back to framework

- DEPS
- ci/licenses_golden/licenses_fuchsia
- shell/platform/fuchsia/dart-pkg/zircon/sdk_ext/handle_waiter.cc
Fixes https://github.com/flutter/flutter/issues/57542
> Roll the Fuchsia SDK and update the path to the async API header

- lib/web_ui/lib/src/engine/compositor/painting.dart
- lib/web_ui/lib/src/engine/compositor/vertices.dart
- lib/web_ui/lib/src/engine/shader.dart
- lib/web_ui/lib/src/ui/painting.dart
- lib/web_ui/lib/src/ui/window.dart
Also fixing the indices argument passed to the MakeSkVertices. CanvasKit changed the signature of this method so we updated the Flutter side to match (otherwise indices don't work).
> Adding ImageShader support for CanvasKit

- DEPS
- shell/platform/fuchsia/dart-pkg/zircon/BUILD.gn
- shell/platform/fuchsia/dart-pkg/zircon/sdk_ext/handle_waiter.cc
fixes deps for zircon/sdk_ext as well
fixes https://github.com/flutter/flutter/issues/57607
> [fuchsia] Fix Mac SDK roll failure

- shell/common/rasterizer.cc
See: https://github.com/flutter/flutter/issues/56598
> [fuchsia] Remove SceneDisplayLag event on Fuchsia

- lib/web_ui/lib/src/engine/compositor/initialization.dart
Fixes https://github.com/flutter/flutter/issues/56938
> Update CanvasKit to 0.15.0

- shell/platform/fuchsia/flutter/component.cc
- shell/platform/fuchsia/flutter/component.h
- shell/platform/fuchsia/flutter/engine.cc
- shell/platform/fuchsia/flutter/engine.h
Tested: Manual test via workstation product
BUG: 50875
> fuchsia: Implement CreateViewWithViewProvider

- shell/platform/fuchsia/flutter/component.cc
- shell/platform/fuchsia/flutter/component.h
- shell/platform/fuchsia/flutter/engine.cc
- shell/platform/fuchsia/flutter/engine.h
Reverts flutter/engine#18280
Pushed some WIP code on accident
> Revert "fuchsia: Implement CreateViewWithViewProvider"

- lib/web_ui/lib/src/engine/bitmap_canvas.dart
- lib/web_ui/lib/src/engine/surface/picture.dart
Related issue: https://github.com/flutter/flutter/issues/48373
> [web] Fix child removal after reuse by other BitmapCanvas

- shell/platform/fuchsia/flutter/component.cc
- shell/platform/fuchsia/flutter/component.h
- shell/platform/fuchsia/flutter/engine.cc
- shell/platform/fuchsia/flutter/engine.h
The last commit was a bad push -- this one compiles.
Tested: Manual test via workstation product
BUG: 50875
> Reland "fuchsia: Implement CreateViewWithViewProvider (#18280)"

- .cirrus.yml
- .clang-tidy
- ci/licenses_golden/licenses_flutter
- ci/lint.dart
- ci/lint.sh
- tools/licenses/lib/main.dart
relevant issue: https://github.com/flutter/flutter/issues/50486
> created a linter that runs clang-tidy

- testing/ios/IosUnitTests/README.md
- testing/run_tests.py
- testing/scenario_app/README.md
- testing/scenario_app/build_and_run_android_tests.sh
- testing/scenario_app/build_and_run_ios_tests.sh
- testing/scenario_app/ios/Scenarios/Scenarios.xcodeproj/project.pbxproj
- testing/scenario_app/run_android_tests.sh
- testing/scenario_app/run_ios_tests.sh
Doing it in 3 steps. Going to change LUCI before cleaning up more.
> Make the testing process on different platforms more consistent

- .github/PULL_REQUEST_TEMPLATE.md
Mostly based on the framework template https://github.com/flutter/flutter/blob/master/.github/PULL_REQUEST_TEMPLATE.md
> Add an engine PR template

- lib/ui/semantics.dart
- lib/web_ui/lib/src/ui/semantics.dart
Reverts flutter/engine#18552
The failure that the PR had on presubmit is now breaking the tree.
> Revert "null-annotate SemanticsUpdateBuilder.updateNode"

- shell/platform/android/io/flutter/embedding/engine/FlutterEngine.java
- shell/platform/android/io/flutter/embedding/engine/FlutterJNI.java
- shell/platform/android/io/flutter/plugin/platform/PlatformViewsController.java
- shell/platform/android/platform_view_android_jni.cc
- shell/platform/android/platform_view_android_jni.h
- shell/platform/android/test/io/flutter/embedding/engine/FlutterJNITest.java
Reverts flutter/engine#18786
cc @cg021
> Revert "onDisplayPlatformView JNI"

- lib/web_ui/dev/firefox.dart
Firefox sometimes gives a popup related to "corrupt profile" and asks if a new profile should be created (happened on local Mac). This might create a flake in the future on LUCI bots
In order to prevent these type of popups give a profile when opening firefox. Preferences are taken from: https://github.com/dart-lang/test/blob/master/pkgs/test/lib/src/runner/browser/firefox.dart
> [web] Adding profile parameter to firefox

- lib/web_ui/lib/src/engine/html_image_codec.dart
- lib/web_ui/lib/src/ui/painting.dart
The web version of https://github.com/flutter/engine/pull/18374
https://github.com/flutter/flutter/issues/53661
> add nullability annotations to lib/web_ui painting.dart

- lib/ui/painting.dart
- lib/web_ui/lib/src/ui/canvas.dart
https://github.com/flutter/flutter/issues/53661
> add nullability annotations to lib/ui/painting.dart

- lib/web_ui/lib/src/engine/compositor/canvas.dart
- lib/web_ui/lib/src/engine/compositor/canvas_kit_canvas.dart
- lib/web_ui/lib/src/engine/compositor/color_filter.dart
- lib/web_ui/lib/src/engine/compositor/fonts.dart
- lib/web_ui/lib/src/engine/compositor/initialization.dart
- lib/web_ui/lib/src/engine/compositor/painting.dart
- lib/web_ui/lib/src/engine/compositor/path.dart
- lib/web_ui/lib/src/engine/compositor/surface.dart
- lib/web_ui/lib/src/engine/compositor/text.dart
- lib/web_ui/lib/src/engine/compositor/util.dart
- lib/web_ui/lib/src/engine/compositor/vertices.dart
- lib/web_ui/lib/src/engine/shader.dart
- Fix SkColor, it migrated to a Float32List
- Fix deprecated shader calls
Fixes https://github.com/flutter/flutter/issues/58014
Fixes https://github.com/flutter/flutter/issues/56938
> Roll CanvasKit to 0.16.1

- shell/platform/linux/fl_basic_message_channel_test.cc
- shell/platform/linux/fl_binary_messenger_test.cc
- shell/platform/linux/fl_dart_project.cc
- shell/platform/linux/fl_dart_project_test.cc
- shell/platform/linux/fl_engine.cc
- shell/platform/linux/fl_method_channel_test.cc
- shell/platform/linux/public/flutter_linux/fl_dart_project.h
- shell/platform/linux/public/flutter_linux/fl_view.h
- shell/platform/linux/testing/mock_engine.cc
> Support AOT mode in GTK shell

- fml/trace_event.cc
- fml/trace_event.h
Fixes https://github.com/flutter/flutter/issues/58816
> Disable event tracing templates in release mode

- flow/layers/backdrop_filter_layer_unittests.cc
- flow/layers/clip_path_layer_unittests.cc
- flow/layers/clip_rect_layer_unittests.cc
- flow/layers/clip_rrect_layer_unittests.cc
- flow/layers/color_filter_layer_unittests.cc
- flow/layers/container_layer_unittests.cc
- flow/layers/image_filter_layer_unittests.cc
- flow/layers/layer_tree_unittests.cc
- flow/layers/opacity_layer.cc
- flow/layers/opacity_layer_unittests.cc
- flow/layers/picture_layer_unittests.cc
- flow/layers/shader_mask_layer_unittests.cc
- flow/layers/transform_layer_unittests.cc
- flow/mutators_stack_unittests.cc
- flow/scene_update_context.h
- flow/testing/mock_layer_unittests.cc
- lib/ui/compositing/scene_builder.cc
- shell/platform/embedder/tests/embedder_unittests.cc
- shell/platform/fuchsia/flutter/vulkan_surface.h
> SkMatrix::MakeFoo is deprecated, use SkMatrix::Foo instead

- ci/licenses_golden/licenses_flutter
- shell/platform/linux/BUILD.gn
- shell/platform/linux/fl_platform_plugin.cc
- shell/platform/linux/fl_platform_plugin.h
- shell/platform/linux/fl_view.cc
> Add FlPlatformPlugin

- shell/platform/android/android_context_gl.cc
- shell/platform/android/android_context_gl.h
- shell/platform/android/android_surface_gl.cc
- shell/platform/android/android_surface_gl.h
Relands #18849  - The fix is 7d67ce3
> Reland: Add RAII wrapper for EGLSurface

- shell/platform/darwin/ios/framework/Source/FlutterViewControllerTest.mm
refactor from PR: https://github.com/flutter/engine/pull/18816 …
> updated FlutterViewControllerTest tests names

- shell/platform/android/io/flutter/plugin/platform/PlatformViewsController.java
Reverts flutter/engine#19226
Logs: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8876739012789413280/+/steps/android_lint/0/steps/dart_bin_main.dart/0/stdout?format=raw
cc @jason-simmons
> Revert "Implement PlatformViewsController.createOverlaySurface"

- flutter_frontend_server/lib/server.dart
- Added a --experimental--emit-debug-metadata flag to Flutter frontend server
- False by default
- Passed to the frontend server in the SDK
- Introduced in change https://dart-review.googlesource.com/c/sdk/+/150181 …
> Added experimental-emit-debug-metadata flag to flutter frontend server

- shell/platform/android/io/flutter/plugin/platform/PlatformViewsController.java
Includes fixes to android_lint errors
> Reland "Implement PlatformViewsController.createOverlaySurface"

- lib/web_ui/lib/src/engine/assets.dart
This adds more logging for when assets fail to load in an unexpected way. …
> Add more logging for when assets fail to load

- shell/platform/darwin/ios/framework/Source/FlutterPlatformViews_Internal.h
- shell/platform/fuchsia/flutter/platform_view_unittest.cc
https://github.com/flutter/engine/pull/19003 accidentally broke this.
> Fix broken mac/fuchsia compiles

- web_sdk/BUILD.gn
Re-attempt at https://github.com/flutter/engine/pull/19162 which seems to be stuck on a bad framework revision
> update web compilation rules for null-safety

- shell/platform/android/external_view_embedder/external_view_embedder.cc
- shell/platform/android/external_view_embedder/external_view_embedder_unittests.cc
- shell/platform/android/external_view_embedder/surface_pool.cc
- shell/platform/android/external_view_embedder/surface_pool.h
- shell/platform/android/io/flutter/embedding/android/FlutterImageView.java
- shell/platform/android/io/flutter/embedding/android/FlutterView.java
- shell/platform/android/io/flutter/embedding/engine/FlutterJNI.java
- shell/platform/android/io/flutter/plugin/platform/PlatformViewsController.java
- shell/platform/android/jni/jni_mock.h
- shell/platform/android/jni/platform_view_android_jni.h
- shell/platform/android/platform_view_android_jni_impl.cc
- shell/platform/android/platform_view_android_jni_impl.h
Issue: https://github.com/flutter/flutter/issues/58291
Helps https://github.com/flutter/flutter/issues/59904
> Basic support for resizing overlay surfaces in hybrid composition

- ci/licenses_golden/tool_signature
- lib/ui/geometry.dart
- lib/ui/painting.dart
- lib/ui/plugins.dart
- lib/ui/text.dart
- lib/ui/window.dart
- lib/web_ui/dev/utils.dart
- lib/web_ui/lib/src/engine/color_filter.dart
- lib/web_ui/lib/src/engine/compositor/embedded_views.dart
- lib/web_ui/lib/src/engine/compositor/image_filter.dart
- lib/web_ui/lib/src/engine/shader.dart
- lib/web_ui/lib/src/engine/text/paragraph.dart
- lib/web_ui/lib/src/engine/text/ruler.dart
- lib/web_ui/lib/src/engine/text_editing/text_editing.dart
- lib/web_ui/lib/src/ui/geometry.dart
- lib/web_ui/lib/src/ui/painting.dart
- lib/web_ui/lib/src/ui/text.dart
- lib/web_ui/lib/src/ui/window.dart
- lib/web_ui/test/engine/profiler_test.dart
- lib/web_ui/test/text/line_breaker_test.dart
- shell/platform/fuchsia/dart-pkg/zircon/lib/src/handle.dart
- tools/licenses/lib/cache.dart
* use `operator ==(Object other)` instead of `operator ==(dynamic other)`. In NNBD you can not override `operator ==(dynamic other)` by `operator ==(Object other)` (that is usually used in framework). Moreover `Object.==` changed its parameter type in 2.9.
* make `operator ==` follow the style guide.
None
None
[C++, …
> Operator equals

- DEPS
This will allow https://dart-review.googlesource.com/c/sdk/+/152860/7/DEPS to cleanly roll.
No tests …
> add collection rev variable to DEPS so it gets rolled by the auto roller

- lib/ui/compositing/scene_host.cc
- lib/ui/compositing/scene_host.h
- shell/platform/fuchsia/dart_runner/kernel/libraries.json
- shell/platform/fuchsia/dart_runner/kernel/libraries.yaml
- shell/platform/fuchsia/flutter/kernel/libraries.json
- shell/platform/fuchsia/flutter/kernel/libraries.yaml
- shell/platform/fuchsia/runtime/dart/utils/handle_exception.cc
- shell/platform/fuchsia/runtime/dart/utils/handle_exception.h
- shell/platform/fuchsia/runtime/dart/utils/mapped_resource.h
Fix paths in source and yaml files to minimize changes in google3 for building flutter runner.
> Fix paths in source and yaml files

- ci/licenses_golden/licenses_flutter
- lib/web_ui/lib/src/engine.dart
- lib/web_ui/lib/src/engine/compositor/canvaskit_api.dart
- lib/web_ui/lib/src/engine/compositor/initialization.dart
- lib/web_ui/pubspec.yaml
- lib/web_ui/test/canvaskit/canvaskit_api_test.dart
- web_sdk/libraries.json
- web_sdk/libraries.yaml
- web_sdk/sdk_rewriter.dart
Adds some initial CanvasKit bindings that use the `@JS` annotation instead of `dart:js`.
> First batch of CanvasKit bindings using @JS

- shell/platform/fuchsia/flutter/BUILD.gn
> Revert "fuchsia:  Fix profile build"

- BUILD.gn
- shell/platform/fuchsia/dart_runner/BUILD.gn
- shell/platform/fuchsia/flutter/BUILD.gn
- shell/platform/fuchsia/flutter/engine_flutter_runner.gni
- tools/fuchsia/build_fuchsia_artifacts.py
Revert ##19399 and #18625 to fix a Google internal test for this release.
> Flutter 1.20 candidate.3

- BUILD.gn
- shell/platform/fuchsia/dart_runner/BUILD.gn
- shell/platform/fuchsia/flutter/BUILD.gn
- shell/platform/fuchsia/flutter/engine_flutter_runner.gni
- tools/fuchsia/build_fuchsia_artifacts.py
> Push fuchsia reverts to 1.20-candidate.4

- CONTRIBUTING.md
> kick flaky fuchsia build

- tools/const_finder/.dart_tool/package_config.json
- tools/const_finder/BUILD.gn
- tools/run_third_party_dart.py
Unblocks roll of null-safe meta
> switch const finder to package_config

- flow/view_holder.h
Changes to fix build errors in google3.
> Changes to fix build errors in google3.

- shell/platform/android/android_context_gl.h
> Fixes typo in android_context_gl.h

- shell/platform/darwin/ios/BUILD.gn
- shell/platform/embedder/BUILD.gn
https://github.com/flutter/engine/pull/19583 broke these builders inadvertently
> Fix Mac / iOS builds

- testing/fuchsia/run_tests.sh
#19212  Description
This is to replace the dev_finder with device-finder.
fxb/55369
N/A
- [ x ] I read the [contributor guide] and followed the process outlined there for submitting PRs.
- [ x ] I read and followed the [C++, Objective-C, Java style guides] for the engine.
- [ x ] I read the [tree hygiene] wiki page, which explains my responsibilities.
- [ x ] I updated/added relevant documentation.
- [ x ] All existing and new tests are passing.
- [ x ] I am willing to follow-up on review comments in a timely manner.
Did any tests fail when you ran them? Please …
> Remove reference to dev_finder.

- tools/fuchsia/build_fuchsia_artifacts.py
- tools/fuchsia/merge_and_upload_debug_symbols.py
This reverts commit 56bb3c5b335820c9ee97ec82cd63a5a471bbc604.
> Revert "ensure we do not double publish to CIPD (#19724)"

- shell/platform/embedder/embedder.cc
- shell/platform/embedder/embedder.h
- shell/platform/embedder/platform_view_embedder.cc
- shell/platform/embedder/platform_view_embedder.h
- shell/platform/embedder/tests/embedder_config_builder.cc
- shell/platform/embedder/tests/embedder_config_builder.h
- shell/platform/embedder/tests/embedder_test_context.cc
- shell/platform/embedder/tests/embedder_test_context.h
- shell/platform/embedder/tests/embedder_unittests.cc
Desktop side work for https://github.com/flutter/flutter/issues/47087
Creates the callback that desktop embedders should implement.
Each platform's implementation will come in separate PRs.
> Desktop embedder ComputePlatformResolvedLocale entrypoint

- shell/platform/android/io/flutter/embedding/android/AndroidTouchProcessor.java
- shell/platform/android/io/flutter/embedding/android/FlutterView.java
- shell/platform/android/io/flutter/embedding/android/MotionEventTracker.java
- shell/platform/android/io/flutter/embedding/engine/mutatorsstack/FlutterMutatorView.java
- shell/platform/android/io/flutter/plugin/platform/PlatformViewsController.java
- shell/platform/android/io/flutter/view/FlutterView.java
- shell/platform/android/test/io/flutter/plugin/platform/PlatformViewsControllerTest.java
- flutter/flutter#61200
- 1832613
> 1.20.0-7.2.pre engine cherrypicks

- shell/platform/android/io/flutter/embedding/engine/FlutterJNI.java
- shell/platform/android/io/flutter/plugin/platform/PlatformViewsController.java
- shell/platform/android/test/io/flutter/plugin/platform/PlatformViewsControllerTest.java
- App crashes when turning TalkBack on in hybrid composition · Issue #61761 · flutter/flutter 
- 12847e899e080104365f93843c25a3b3b5648895
> 1.20.0-7.2.pre: CP 12847e899e080104365f93843c25a3b3b5648895

- lib/web_ui/dev/goldens_lock.yaml
- lib/web_ui/lib/src/engine/surface/path/path.dart
- lib/web_ui/test/golden_tests/engine/canvas_arc_golden_test.dart
Fixes scaling of conic points when arcTo is called with negative sweep angle.
Fixes: https://github.com/flutter/flutter/issues/61859
Added golden test to canvas_arc_golden_test.dart
> [web] Fixes arc scaling when counter clockwise

- lib/web_ui/dev/felt
Tree is still red: https://ci.chromium.org/p/flutter/g/engine/console
This is a PR with no code changes to rerun the tests after recipe changes are in: https://flutter-review.googlesource.com/c/recipes/+/4664
> Add a todo to felt (PR to rerun the tree)

- shell/platform/android/io/flutter/plugin/platform/PlatformViewsController.java
- shell/platform/android/test/io/flutter/plugin/platform/PlatformViewsControllerTest.java
https://github.com/flutter/flutter/issues/62079
> 1.20.0 CP: Remove android view from the Mutator stack (#19972)

- common/settings.cc
- common/settings.h
- shell/common/persistent_cache.cc
- shell/common/persistent_cache.h
- shell/common/persistent_cache_unittests.cc
- shell/common/shell.cc
- shell/common/switches.cc
- shell/common/switches.h
- shell/platform/android/io/flutter/app/FlutterActivityDelegate.java
- shell/platform/android/io/flutter/embedding/engine/FlutterShellArgs.java
For https://github.com/flutter/flutter/issues/39526
> Add purge-persistent-cache

- shell/common/persistent_cache.cc
Fixes https://github.com/flutter/flutter/issues/62468
> Remove confusing logs

- shell/platform/android/io/flutter/embedding/android/FlutterView.java
Fixes https://github.com/flutter/flutter/issues/61558
> Add missing MouseCursorPlugin destroy call

- shell/platform/android/io/flutter/embedding/engine/systemchannels/PlatformChannel.java
https://github.com/flutter/flutter/issues/62143
> Add ALERT SoundType enum value

- tools/fuchsia/build_fuchsia_artifacts.py
Also update them to build the default flutter and fuchsia_tests targets instead of the specific shell target only
> Fix targets param in build_fuchsia_artifacts

- shell/platform/android/io/flutter/embedding/android/FlutterView.java
- shell/platform/android/io/flutter/embedding/engine/FlutterJNI.java
- shell/platform/android/io/flutter/embedding/engine/renderer/FlutterRenderer.java
- shell/platform/android/io/flutter/plugin/platform/PlatformViewsController.java
- shell/platform/android/io/flutter/view/FlutterView.java
- shell/platform/android/test/io/flutter/plugin/platform/PlatformViewsControllerTest.java
fix for Wait until first frame rendered back on SurfaceView/TextureView (https://github.com/flutter/flutter/issues/62455)
> 1.20 CP: Wait before switching surfaces (#20100)

- shell/platform/linux/fl_renderer.h
- shell/platform/linux/fl_text_input_plugin.h
Fix some parameter names.
None, trivial fix.
No tests changed. …
> Fix parameter names

- testing/fuchsia/run_tests.sh
https://github.com/flutter/flutter/issues/61768 to re-enable
> Disable flaky fuchsia test

- DEPS
- tools/gn
Reverts flutter/engine#20156
Try to fix the LUCI Fuchsia build.
> Revert "Add preliminary Windows arm64 plumbing"

- shell/platform/linux/fl_basic_message_channel.cc
- shell/platform/linux/fl_binary_messenger.cc
- shell/platform/linux/fl_engine.cc
- shell/platform/linux/fl_json_method_codec.cc
- shell/platform/linux/fl_method_channel.cc
- shell/platform/linux/fl_method_codec.cc
- shell/platform/linux/fl_renderer.cc
- shell/platform/linux/fl_standard_message_codec.cc
- shell/platform/linux/fl_standard_method_codec.cc
- shell/platform/linux/fl_text_input_plugin.cc
- shell/platform/linux/fl_value.cc
- shell/platform/linux/fl_view.cc
Update code style to pass clang-tidy checks
No related issues, the linter checks didn't exist at the time this code was written.
No tests added. …
> Update code style to pass clang-tidy checks

- BUILD.gn
- ci/licenses_golden/licenses_flutter
- shell/platform/android/BUILD.gn
- shell/platform/android/platform_view_android.cc
- shell/platform/android/platform_view_android.h
- shell/platform/android/platform_view_android_delegate/BUILD.gn
- shell/platform/android/platform_view_android_delegate/platform_view_android_delegate.cc
- shell/platform/android/platform_view_android_delegate/platform_view_android_delegate.h
- shell/platform/android/platform_view_android_delegate/platform_view_android_delegate_unittests.cc
- testing/run_tests.py
CP https://github.com/flutter/engine/pull/19623 to fix https://github.com/flutter/flutter/issues/60926
BUILD.gn had one manual resolution
* fix FlutterViewUpdateCustomAccessibilityActions uses correct string list
* add test to ci
* format
* add license file
* fix test
* fix lint
*Replace this paragraph with a description of what this PR is doing. If you're
modifying existing behavior, describe the existing behavior, how this PR is
changing it, and what motivated the change.*
*Replace this paragraph with a list of issues related to this PR from our [issue
database]. Indicate, which of these issues are resolved or fixed by this PR.
There should be at least one issue listed here.*
*Replace this with a list of the tests that you added as part of this PR. A
change …
> 1.20 CP: fix FlutterViewUpdateCustomAccessibilityActions uses correct string list

- ci/lint.sh
We are using Dart features that aren't available on dart stable yet.
I tested it manually by uploaded a diff to a cc file. …
> Switched the linter to use the dart that comes with the engine.

- shell/common/serialization_callbacks.cc
See https://github.com/flutter/flutter/issues/62845
> Fix the reversal of behavior in SerializeTypefaceWithData and WithoutData

- lib/web_ui/lib/src/engine/compositor/canvaskit_api.dart
- lib/web_ui/lib/src/engine/compositor/fonts.dart
- lib/web_ui/lib/src/engine/compositor/initialization.dart
- lib/web_ui/lib/src/engine/compositor/text.dart
Rolls CanvasKit to `0.17.3` and starts using `TypefaceFontProvider` and 
Fixes https://github.com/flutter/flutter/issues/62595 …
> Roll CanvasKit to 0.17.3.

- fml/file.cc
- shell/common/BUILD.gn
- shell/common/shell_unittests.cc
- testing/fuchsia/run_tests.sh
- vulkan/vulkan_application.cc
Fixes https://github.com/flutter/flutter/issues/53399
> Fix broken shell_unittests on Fuchsia

- shell/platform/fuchsia/flutter/BUILD.gn
> Fix broken symbols on Fuchsia embedder

- shell/platform/common/cpp/client_wrapper/byte_buffer_streams.h
- shell/platform/common/cpp/client_wrapper/include/flutter/byte_streams.h
- shell/platform/fuchsia/flutter/BUILD.gn
Cherry-picked #20317 and #20459
> Flutter 1.21 candidate.10

- ci/dev/README.md
- ci/dev/try_builders.json
This is part of https://github.com/flutter/flutter/issues/63437.
> Add enabled flag for try builders

- ci/licenses_golden/licenses_flutter
- lib/ui/window.dart
- lib/web_ui/lib/src/ui/window.dart
- shell/platform/darwin/ios/framework/Headers/Flutter.h
- shell/platform/darwin/ios/framework/Headers/FlutterEngine.h
- shell/platform/darwin/ios/framework/Headers/FlutterViewController.h
- shell/platform/darwin/ios/framework/Source/FlutterEngine.mm
- shell/platform/darwin/ios/framework/Source/FlutterEngineTest.mm
- shell/platform/darwin/ios/framework/Source/FlutterEngine_Internal.h
- shell/platform/darwin/ios/framework/Source/FlutterEngine_Test.h
- shell/platform/darwin/ios/framework/Source/FlutterViewController.mm
- shell/platform/darwin/ios/framework/Source/FlutterViewControllerTest.mm
- testing/ios/IosUnitTests/IosUnitTests.xcodeproj/project.pbxproj
- testing/run_tests.py
- testing/scenario_app/ios/Scenarios/Scenarios.xcodeproj/project.pbxproj
- testing/scenario_app/ios/Scenarios/Scenarios/FlutterEngine+ScenariosTest.m
- testing/scenario_app/ios/Scenarios/ScenariosTests/FlutterEngineTest.m
- testing/scenario_app/ios/Scenarios/ScenariosTests/FlutterViewControllerInitialRouteTest.m
- testing/scenario_app/ios/Scenarios/ScenariosTests/FlutterViewControllerTest.m
- testing/scenario_app/ios/Scenarios/ScenariosTests/ScenariosTests.m
- testing/scenario_app/lib/src/initial_route_reply.dart
- testing/scenario_app/lib/src/scenarios.dart
Reland of https://github.com/flutter/engine/pull/19684
Fix flutter/flutter#59895
> Refactor initial route code take 2

- shell/platform/android/io/flutter/plugin/platform/PlatformViewsController.java
- shell/platform/android/test/io/flutter/plugin/platform/PlatformViewsControllerTest.java
This reverts commit 9333b7c1d0ac7b2ae97998df116fcb0f99b1f26f.
This PR was causing issues with the benchmark tests, see https://github.com/flutter/flutter/pull/63969
[tree …
> Revert "Create PlatformView instance right after method channel call from Dart (#20500)"

- ci/dev/try_builders.json
Add presubmit android scenarios task.
Bug:
https://github.com/flutter/flutter/issues/55326
N/A …
> Add android scenarios presubmit task.

- ci/dev/try_builders.json
Reverts flutter/engine#20581 some changes in the scenarios recipe broke existing functionality.
> Revert "Add android scenarios presubmit task."

- ci/dev/try_builders.json
> Reland: Add android scenarios presubmit task.

- ci/dev/prod_builders.json
Builders are read from a json file to get their last builds using
buildbucket and calculate the tree status. Some builders were not being
used for the tree status validation allowing rollers to land changes
even though some builders were failing.
Bug:
https://github.com/flutter/flutter/issues/64061
N/A
[C++, …
> Adds all the engine builders to the file used to validate tree status.

- common/settings.h
- flow/surface.cc
- flow/surface.h
- shell/common/rasterizer.cc
- shell/common/switches.cc
- shell/common/switches.h
- shell/gpu/gpu_surface_gl.cc
- shell/gpu/gpu_surface_gl.h
- shell/platform/android/android_shell_holder.cc
- shell/platform/android/android_shell_holder.h
- shell/platform/android/android_surface_gl.cc
- shell/platform/android/android_surface_software.cc
- shell/platform/android/io/flutter/embedding/engine/loader/ApplicationInfoLoader.java
- shell/platform/android/io/flutter/embedding/engine/loader/FlutterApplicationInfo.java
- shell/platform/android/io/flutter/embedding/engine/loader/FlutterLoader.java
- shell/platform/android/test/io/flutter/embedding/engine/PluginComponentTest.java
- shell/platform/android/test/io/flutter/embedding/engine/loader/ApplicationInfoLoaderTest.java
- testing/scenario_app/android/app/src/main/AndroidManifest.xml
Reverts flutter/engine#20722
There are some failures associated with this PR. Some targets in g3 and https://cirrus-ci.com/task/6187072195133440
cc @cyanglaz
> Revert "Enable hybrid composition by default on Android"

- testing/fuchsia/run_tests.sh
- Add link to the SDK version of this script
- Both scripts are very similar and should be updated at the same time
Cleanup while working on https://github.com/flutter/flutter/issues/57044
This PR only adds documentation
> [fuchsia] Link to SDK version of script

- shell/platform/android/embedding_bundle/build.gradle
- shell/platform/android/io/flutter/embedding/android/FlutterView.java
- shell/platform/android/test/io/flutter/embedding/android/FlutterViewTest.java
- testing/scenario_app/android/app/build.gradle
Work in progress.
Fixes https://github.com/flutter/flutter/issues/56592
Initial implementation of updated padding computation for API >= 30 to avoid hacks/heuristics.
> Use Android R (API 30) getInsets() to compute padding

- shell/platform/android/io/flutter/embedding/engine/loader/FlutterLoader.java
- shell/platform/darwin/ios/framework/Source/FlutterDartProject.mm
Breaks internal tests b/166589071
> Revert "Pass platform configuration to Dart VM for insecure socket policy"

- shell/common/shell_unittests.cc
2nd attempt to fix race condition.  This patch waits for the [first frame](https://github.com/flutter/engine/blob/5f49a954999fa60a9e26fa0fca9dbc13a3257b92/shell/common/shell.cc#L1034 ) before performing the assertion. 
I was unable to reproduce the failure with or without this patch. I tried running `shell_unittests  --gtest_shuffle --gtest_repeat=-1` for ~10 mins.
Related flutter/flutter#64906
> Wait for first frame before checking layer tree

- lib/ui/painting/image_decoder_unittests.cc
- shell/common/rasterizer.h
- shell/common/shell.cc
- shell/common/shell.h
- shell/common/shell_io_manager.cc
- shell/common/shell_io_manager.h
- shell/platform/fuchsia/flutter/vsync_waiter.cc
- shell/platform/fuchsia/flutter/vsync_waiter.h
Member variables should appear before the |WeakPtrFactory|.
None.
None. …
> Member variables should appear before the |WeakPtrFactory|.

- DEPS
Updates Android SDK to use latest API 30 revision 3.
> Update Android SDK to 30r3

- lib/web_ui/lib/src/engine/browser_location.dart
- lib/web_ui/lib/src/engine/history.dart
- lib/web_ui/lib/src/engine/test_embedding.dart
- lib/web_ui/lib/src/engine/window.dart
- lib/web_ui/test/engine/history_test.dart
- lib/web_ui/test/engine/navigation_test.dart
- lib/web_ui/test/window_test.dart
Refactor the existing BrowserHistory class and implements a new class to handle the router widget.
Fixes https://github.com/flutter/flutter/issues/64494
TBD after people agree with this approach …
> Implement browser history class for router widget

- shell/platform/android/android_context_gl.h
> Fix comment indentation

- lib/web_ui/dev/felt
autoninja is included as part of depot_tools and automatically
determines the optimal thread count.
Also applies quoting on the affected lines.
> [felt] Use autoninja instead of hardcoding threads

- lib/web_ui/dev/README.md
- lib/web_ui/dev/build.dart
Migrate to autoninja which works out the ideal level of parallelism.
> [felt] Eliminate ninja-jobs argument

- README.md
There was a problem with GoB that made all the builders fail on old
commits. As the last commit was successful we need to force a new
execution to unblock the tree.
https://github.com/flutter/flutter/issues/65803
N/A
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/master/CONTRIBUTING.md#styl …
> Force builders to run.

- shell/platform/android/io/flutter/plugin/platform/PlatformPlugin.java
- shell/platform/android/test/io/flutter/plugin/platform/PlatformPluginTest.java
- Fix NPE in PlatformPlugin.getClipboardData()
https://github.com/flutter/flutter/issues/63766
I added the following tests: `platformPlugin_getClipboardData()` in [PlatformPluginTest.java](https://github.com/hamdikahloun/engine/blob/hamdikahloun-patch-1/shell/platform/android/test/io/flutter/plugin/platform/PlatformPluginTest.java) …
> Fix NPE in PlatformPlugin.getClipboardData()

- e2etests/web/regular_integration_tests/lib/text_editing_main.dart
- e2etests/web/regular_integration_tests/test_driver/text_editing_integration.dart
Integration test to make sure selectable text works end-to-end with the web engine.
> [web] Integration test for selectable text

- tools/fuchsia/fuchsia_libs.gni
> avoid hard coding OS

- shell/platform/android/io/flutter/app/FlutterActivity.java
- shell/platform/android/io/flutter/app/FlutterActivityDelegate.java
- shell/platform/android/io/flutter/app/FlutterFragmentActivity.java
- shell/platform/android/io/flutter/app/FlutterPluginRegistry.java
- shell/platform/android/io/flutter/plugin/common/PluginRegistry.java
- shell/platform/android/io/flutter/view/FlutterMain.java
- shell/platform/android/io/flutter/view/FlutterNativeView.java
- shell/platform/android/io/flutter/view/FlutterView.java
> Revert "Deprecate Android v1 embedding classes"

- shell/platform/darwin/ios/framework/Headers/FlutterPlugin.h
This was causing compilation errors when extra checks are enabled in g3. It also seems remaining code does not specify semicolon so updating for consistency.
None
None …
> Remove spurious semicolon

- lib/web_ui/lib/src/engine/alarm_clock.dart
- lib/web_ui/lib/src/engine/canvaskit/canvaskit_canvas.dart
- lib/web_ui/lib/src/engine/canvaskit/fonts.dart
- lib/web_ui/lib/src/engine/text_editing/text_editing.dart
- lib/web_ui/lib/src/engine/window.dart
A minor null safety clean-up in `alarm_clock.dart`, `canvaskit_canvas.dart`, `fonts.dart`, `text_editing.dart`, and `window.dart`.
> web: make a few variables non-null

- shell/platform/linux/fl_engine.cc
Fix segfault if engine is disposed with an uncompleted task. Solve by keeping a reference to the FlEngine until a source completes.
This is not something that probably happens in read applications, but I detected it happening when adding some tests (which create/destroy FlEngine objects and GMainLoops a lot).
N/A
No additional tests added. Should be well exercised by the current tests.
[testing the …
> Fix segfault if engine is disposed with an uncompleted task.

- shell/platform/android/io/flutter/plugin/common/StandardMessageCodec.java
- shell/platform/android/test/io/flutter/plugin/common/StandardMessageCodecTest.java
- tools/android_lint/baseline.xml
Fixes https://github.com/flutter/flutter/issues/65619
> Fix boolean value checks in StandardMessageCodec

- tools/fuchsia/build_fuchsia_artifacts.py
- tools/gn
Adds a flag to turn off git hash versioning
Without this flag, it is excessively tedious to build Dart SDK
for local testing on Fuchsia, since Fuchsia runner will reject
a Dart SDK without a matching version.
* https://github.com/flutter/flutter/issues/64574
N/A …
> Git versioning flag

- shell/platform/fuchsia/flutter/accessibility_bridge.cc
- shell/platform/fuchsia/flutter/accessibility_bridge.h
- shell/platform/fuchsia/flutter/accessibility_bridge_unittest.cc
- shell/platform/fuchsia/flutter/platform_view.cc
The previous pr was reverted due to a bad merge.
https://github.com/flutter/flutter/issues/65218 …
> Reland Apply dpr transform to fuchsia accessibility bridge

- lib/web_ui/lib/src/engine/bitmap_canvas.dart
- lib/web_ui/lib/src/engine/canvaskit/canvaskit_api.dart
- lib/web_ui/lib/src/engine/canvaskit/surface.dart
In https://dart-review.googlesource.com/c/sdk/+/163841, dart's flow
analysis is being changed so that an assignment like this:
T? x = <non-nullable value>;
causes `x` to be immediately promoted to type `T`.  This exposed two
instances in which a variable was unnecessarily given a nullable type.
To avoid warnings, we need to fix these two types before
https://dart-review.googlesource.com/c/sdk/+/163841 can land.
- https://github.com/dart-lang/sdk/issues/43099
- https://github.com/dart-lang/sdk/issues/43100
This PR must be landed in order to make progress on fixing the above two issues.
N/A, since there is no behavioral change.
Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review …
> Remove unnecessary `?`s from web_ui.

- shell/platform/fuchsia/flutter/session_connection.cc
> [fuchsia] fix typo

- flow/flow_run_all_unittests.cc
- fml/backtrace.cc
- third_party/txt/tests/txt_run_all_unittests.cc
Fixes https://github.com/flutter/flutter/issues/66998
> Fix windows popup when unit tests have failures

- flow/layers/checkerboard_layertree_unittests.cc
Fix test compile errors introduced by https://github.com/flutter/engine/pull/20997
https://github.com/flutter/engine/pull/20997
N/A
> fuchsia: Fix test compile

- flow/layers/child_scene_layer.cc
- flow/layers/layer.h
- flow/layers/opacity_layer.cc
- flow/layers/opacity_layer_unittests.cc
This old hack I added is just causing issues (black-flashes) now that Fuchsia's scene graph has been restructured.
Test: Ran internal shell and tests
https://b.corp.google.com/issues/169326124
> fuchsia: Remove Opacity hole-punch

- lib/ui/semantics.dart
- lib/ui/semantics/semantics_node.h
Minor documentation details/breadcrumbs from debugging https://github.com/flutter/flutter/issues/61631 and https://github.com/flutter/flutter/issues/36307
Related framework PR: https://github.com/flutter/flutter/pull/63192
N/A
N/A …
> Minor documentation details/breadcrumbs

- shell/common/persistent_cache.cc
- shell/common/persistent_cache.h
- shell/common/persistent_cache_unittests.cc
- shell/common/shell_test.cc
- shell/common/shell_test.h
Otherwise, the persistent cache may hold invalid directories and make
subsequent store fail.
The newly added unit tests would fail without the fix.
> Do not remove directories in purge

- shell/platform/embedder/embedder.cc
Fixes https://github.com/flutter/flutter/issues/67554
> Avoid leaking the FlutterEngineAOTData structure in FlutterEngineCollectAOTData.

- lib/web_ui/dev/driver_version.yaml
- lib/web_ui/pubspec.yaml
@yjbanov made this change yesterday: https://github.com/flutter/web_installers/commit/58081a8b2fbf234e9c8da86fce28adfefe3c2093
we need to make a similar change for the engine repo.
> chrome driver for chrome 86

- DEPS
See https://github.com/flutter/flutter/issues/63581
> Roll ICU to 146cb611fb2c1f53e63c2e59bd735d7a8ac6ec8c

- shell/platform/darwin/macos/framework/Source/FlutterEngine.mm
Caught by go/xcode-version-build-status-failure
> Fix filesystem access prior to macOS 10.15

- DEPS
- ci/licenses_golden/licenses_fuchsia
Reverts flutter/engine#21814
```
Tue Oct 13 22:25:32 UTC 2020 START:fml_tests ---------------------------------------
+ fuchsia_ctl test -f fml_tests-0.far -t fml_tests -a '--gtest_filter=-MessageLoop.TimeSensistiveTest_*:FileTest.CanTruncateAndWrite:FileTest.CreateDirectoryStructure' --identity-file /etc/botanist/keys/id_rsa_infra --timeout-seconds 300 --packages-directory packages
+ ./fuchsia_ctl -d shore-jolly-shiny-glad test -f fml_tests-0.far -t fml_tests -a '--gtest_filter=-MessageLoop.TimeSensistiveTest_*:FileTest.CanTruncateAndWrite:FileTest.CreateDirectoryStructure' --identity-file /etc/botanist/keys/id_rsa_infra --timeout-seconds 300 --packages-directory packages
Using packages/amber-files as repo to serve to fd5d:df07:5e35:0:1955:3d6a:200a:cf0c...
Running packages/pm serve …
```
> Revert "Roll Fuchsia Linux SDK from gdo4mZ5oI... to 41fVbRhb0..."

- lib/web_ui/lib/src/engine/canvaskit/canvas.dart
- lib/web_ui/lib/src/engine/canvaskit/canvaskit_api.dart
- lib/web_ui/lib/src/engine/canvaskit/initialization.dart
- lib/web_ui/lib/src/engine/canvaskit/path.dart
- lib/web_ui/lib/src/engine/canvaskit/picture_recorder.dart
- lib/web_ui/lib/src/engine/canvaskit/text.dart
- lib/web_ui/test/canvaskit/canvaskit_api_test.dart
* Adds support for StrutStyle in ParagraphStyle.
Adds support for the following in TextStyle:
* decoration color
* decoration style
* text baseline
* letter spacing
* word spacing
* height
* locale
* shadows
* font features
* Adds support for addPlaceholder in ParagraphBuilder
Fixes https://github.com/flutter/flutter/issues/63690
Fixes https://github.com/flutter/flutter/issues/63616
Fixes https://github.com/flutter/flutter/issues/63144
Fixes https://github.com/flutter/flutter/issues/61277
Fixes https://github.com/flutter/flutter/issues/61240
Fixes https://github.com/flutter/flutter/issues/58491
Fixes https://github.com/flutter/flutter/issues/67993
Updated `canvaskit_api_test.dart` to use the new SkRects.
Before you create this PR confirm that it meets all requirements listed below by …
> Add more TextStyle support to Paragraph in CanvasKit mode

- lib/ui/painting/image_decoder.cc
See https://github.com/flutter/flutter/issues/67855
> Check for null images in ImageFromCompressedData

- shell/platform/android/platform_view_android.cc
- shell/platform/android/platform_view_android.h
Fixes https://github.com/flutter/flutter/issues/68446
> Fix the initialization of AndroidSurfaceFactoryImpl

- shell/platform/linux/fl_text_input_plugin.cc
This PR fixes a few small memory leaks in FlTextInputPlugin. All three cases
are creating temporary FlValue instances for lookups and comparison without
ever releasing them.
\-
I updated the following tests:
StringEqual and StringNotEqual in fl_value_test.cc. …
> Fix memory leaks in FlTextInputPlugin

- lib/ui/text.dart
https://github.com/flutter/flutter/issues/68562
> [null-safety] fix soundness of Paragraph._addPlaceholder

- shell/platform/darwin/ios/framework/Source/FlutterViewController.mm
Related PR: https://github.com/flutter/engine/pull/20972 cc @gspencergoog
N/A.
N/A. …
> [iOS] Fixes leaks of presses key message

- ci/dev/prod_builders.json
Add framework web tests to prod build bots.
> add web framework tests to the prod builder

- testing/benchmark/generate_metrics.sh
- testing/benchmark/upload_metrics.sh
Move metrics scripts out of cirrus yaml file. This is in preparation to move the metrics task to LUCI.
Bug:
https://github.com/flutter/flutter/issues/67579
N/A
[CLA]: …
> Add metrics scripts in preparation to move the builder to LUCI.

- tools/const_finder/test/fixtures/.dart_tool/package_config.json
Adds a package config file to the const finder test fixtures to unblock the null safety flag removal change.
Otherwise these fixtures get opted in to null safety and some constants are missing (presumably because they are invalid).
https://github.com/dart-lang/sdk/issues/43872
No tests …
> add a package config file to const finder test fixtures

- lib/web_ui/pubspec.yaml
- web_sdk/web_test_utils/pubspec.yaml
Fixes build and unblocks null safety
> [null-safety] update path version

- e2etests/web/regular_integration_tests/pubspec.yaml
Match the constraint with what flutter/flutter uses
> Update constraint to latest integration test

- .cirrus.yml
- ci/licenses_golden/licenses_flutter
it appears LUCI is currently not running ci/licenses.sh
> bring back build_test to ensure we validate licenses

- lib/web_ui/dev/web_engine_analysis.sh
This changes the web_ui analysis from using the `dartanalyzer` command to using the newer, `dart analyze` command. 
- none
This is a minor infra change.
[CLA]: …
> use the dart analyze command to analyze source

- lib/web_ui/lib/src/engine/canvaskit/fonts.dart
> fix _getArrayBuffer signature

- lib/web_ui/lib/src/ui/painting.dart
Fixes Future<Codec?> nullability failure due to function signature.
https://github.com/flutter/flutter/issues/69571
Filed issue https://github.com/flutter/flutter/issues/69590 to add test as part of existing image rendering test image_loading_main.dart. …
> [web] Fix nullability issue with Image.network

- lib/web_ui/lib/src/engine/dom_canvas.dart
- lib/web_ui/lib/src/engine/dom_renderer.dart
- lib/web_ui/lib/src/engine/html/backdrop_filter.dart
- lib/web_ui/lib/src/engine/html/clip.dart
- lib/web_ui/lib/src/engine/html/offset.dart
- lib/web_ui/lib/src/engine/html/opacity.dart
- lib/web_ui/lib/src/engine/html/picture.dart
- lib/web_ui/lib/src/engine/html/transform.dart
- lib/web_ui/lib/src/engine/mouse_cursor.dart
- lib/web_ui/lib/src/engine/text/paragraph.dart
- lib/web_ui/lib/src/engine/text/ruler.dart
- lib/web_ui/lib/src/engine/vector_math.dart
- lib/web_ui/test/canvas_test.dart
- lib/web_ui/test/dom_renderer_test.dart
- lib/web_ui/test/golden_tests/engine/scuba.dart
- Dom canvas now uses flt-picture instead of creating extra dom-canvas node.
- computeDensity now uses isIdentityOrTranslation() to fix regression in update_many_child_layers benchmark.
```
═════════════════════════╡ ••• Final A/B results ••• ╞══════════════════════════
Score	Average A (noise)	Average B (noise)	Speed-up
bench_update_many_child_layers.html.drawFrameDuration.average	8641.60 (1.38%)	2418.36 (2.71%)	3.57x	
bench_update_many_child_layers.html.drawFrameDuration.outlierRatio	1.80 (5.63%)	1.10 (1.48%)	1.64x
bench_update_many_child_layers.html.totalUiFrame.average	28969.70 (0.66%)	9189.70 (1.25%)	3.15x
```
- Micro optimizations around global final domRenderer that does extra lazyinit lookup.
- Micro optimizations around style setting:
```
Before:
apply$0: function() {
var t1 = …
```
> [web] Improve dom canvas speed. Fix density calculation regression in recomputeTransformClip

- lib/ui/painting.dart
Fixed [flutter#69367](https://github.com/flutter/flutter/issues/69367)
> Update painting.dart 

- DEPS
- ci/licenses_golden/licenses_third_party
This change will make it easier to roll further changes into
Fuchsia.
Issue: https://github.com/flutter/flutter/issues/70007
https://github.com/flutter/flutter/issues/70007
N/A
[CLA]: …
> Roll ICU to 715ec351c0bcdd6b2d22f36e7d33b8e2ec519846

- tools/fuchsia/build_fuchsia_artifacts.py
This adds licesnse files to the Fuchsia CIPD artifacts.
https://b.corp.google.com/issues/169676435
https://bugs.fuchsia.dev/p/fuchsia/issues/detail?id=42986
N/A
> fuchsia: Add licenses to CIPD

- DEPS
Update buildroot to include a fuchsia toolchain fix.
https://github.com/flutter/buildroot/pull/411
N/A
> fuchsia: Update buildroot

- lib/web_ui/lib/src/engine/text/measurement.dart
The `_measureSubstring` function is used by the existing `CanvasTextMeasurementService` to measure chunks of text. Before this PR, the function received a `ParagraphGeometricStyle` argument. But the new rich text measurement doesn't use geometric style, so in order to reuse this function, we need to remove the geometric style argument.
All canvas-based measurement tests go through this function in one way or another. I'm relying on those tests to catch any issues (and they did catch a few issues that I fixed).
> [web] Refactor _measureSubstring to better suit rich text measurement

- tools/generate_package_config/bin/generate_from_legacy.dart
For https://github.com/flutter/flutter/issues/70349
> Default to 2.7 when generating the package config

- lib/ui/painting.dart
- lib/ui/painting/image_filter.cc
- lib/ui/painting/image_filter.h
- lib/web_ui/lib/src/engine/bitmap_canvas.dart
- lib/web_ui/lib/src/engine/canvaskit/canvas.dart
- lib/web_ui/lib/src/engine/canvaskit/canvaskit_api.dart
- lib/web_ui/lib/src/engine/canvaskit/color_filter.dart
- lib/web_ui/lib/src/engine/canvaskit/image_filter.dart
- lib/web_ui/lib/src/engine/canvaskit/painting.dart
- lib/web_ui/lib/src/engine/color_filter.dart
- lib/web_ui/lib/src/engine/html/color_filter.dart
- lib/web_ui/lib/src/ui/painting.dart
- lib/web_ui/test/canvaskit/canvaskit_api_test.dart
- lib/web_ui/test/canvaskit/filter_test.dart
- testing/dart/image_filter_test.dart
Exposing `SkImageFilters::Compose` and `SkImageFilters::ColorFilter` so we can use a `ColorFilter` in a `BackdropFilter`, and compose the color filter with a gaussian blur filter. `UIAlertController`'s backdrop increases the background saturation by 50% before applies a gaussian blur to the background. Couldn't find a way to do the saturation boost using blend modes so I'm resorting to color filters.
https://github.com/flutter/flutter/issues/29483
https://github.com/flutter/flutter/issues/50183
ImageFilter - from color filters 
ImageFilter - color filter composition
Did any tests fail …
> Exposing ColorFilter to ImageFilter conversion and Compose()

- shell/platform/android/android_context_gl.cc
- shell/platform/android/android_context_gl.h
- shell/platform/android/android_surface_gl.cc
- shell/platform/android/android_surface_gl.h
- shell/platform/android/android_surface_software.cc
- shell/platform/android/android_surface_software.h
- shell/platform/android/android_surface_vulkan.cc
- shell/platform/android/android_surface_vulkan.h
- shell/platform/android/context/android_context.h
- shell/platform/android/external_view_embedder/external_view_embedder.cc
- shell/platform/android/external_view_embedder/external_view_embedder.h
- shell/platform/android/external_view_embedder/external_view_embedder_unittests.cc
- shell/platform/android/external_view_embedder/surface_pool.cc
- shell/platform/android/external_view_embedder/surface_pool.h
- shell/platform/android/external_view_embedder/surface_pool_unittests.cc
- shell/platform/android/platform_view_android.cc
- shell/platform/android/platform_view_android.h
This also clarifies the ownership of android context.
> [android] Platform view creates external view embedder

- shell/common/fixtures/shell_test.dart
- shell/platform/embedder/fixtures/main.dart
This resolves local issues I see compiling fixtures.
I have no idea why this works on CI and not in my local environment.
> Opt in fixtures to nullsafety

- shell/platform/android/io/flutter/plugin/platform/PlatformPlugin.java
- shell/platform/android/test/io/flutter/plugin/platform/PlatformPluginTest.java
Add `systemNavigationBarDividerColor` for Android P and above .
https://github.com/flutter/flutter/issues/69528
`setNavigationBarDividerColor()`
[CLA]: …
> [Android] Add systemNavigationBarDividerColor

- lib/web_ui/lib/src/engine/canvaskit/canvaskit_api.dart
- lib/web_ui/lib/src/engine/canvaskit/color_filter.dart
- lib/web_ui/lib/src/engine/canvaskit/fonts.dart
- lib/web_ui/lib/src/engine/canvaskit/image.dart
- lib/web_ui/lib/src/engine/canvaskit/image_filter.dart
- lib/web_ui/lib/src/engine/canvaskit/initialization.dart
- lib/web_ui/lib/src/engine/canvaskit/mask_filter.dart
- lib/web_ui/lib/src/engine/canvaskit/shader.dart
- lib/web_ui/lib/src/engine/canvaskit/vertices.dart
- lib/web_ui/test/canvaskit/canvaskit_api_test.dart
Rolls CanvasKit to version 0.19.0
Updated `canvaskit_api_test.dart` to reflect new names.
[handling …
> Migrate to CanvasKit 0.19.0

- DEPS
`flutter_internal` needs public access. @godofredoc
> Use flutter public package for the time being

- shell/common/shell_unittests.cc
With this patch, I ran the tests about 600 iterations and didn't get a failure.
Note: I don't have a linux machine and I ran the tests on my mac.
Fixes https://github.com/flutter/flutter/issues/66056
ShellTest.SkipAndSubmitFrame …
> Re-enable ShellTest.SkipAndSubmitFrame

- shell/platform/android/io/flutter/FlutterInjector.java
Initially added in https://github.com/flutter/engine/pull/20789
> Replace support libraries for AndroidX

- shell/platform/android/io/flutter/embedding/engine/FlutterEngineConnectionRegistry.java
Update the log tag for FlutterEngineConnectionRegistry to be 23 characters. See https://stackoverflow.com/q/28168622
N/A …
> Update the log tag for FlutterEngineConnectionRegistry to be 23 characters

- shell/platform/android/android_context_gl.h
- shell/platform/android/context/android_context.h
Fixes https://github.com/flutter/flutter/issues/70938
> Make AndroidContext::IsValid virtual

- flow/embedded_views.cc
- flow/embedded_views.h
- shell/common/rasterizer.cc
- shell/common/rasterizer_unittests.cc
- shell/common/shell_test_external_view_embedder.cc
- shell/common/shell_test_external_view_embedder.h
- shell/platform/android/external_view_embedder/external_view_embedder.cc
- shell/platform/android/external_view_embedder/external_view_embedder.h
- shell/platform/android/external_view_embedder/external_view_embedder_unittests.cc
- shell/platform/darwin/ios/framework/Source/FlutterPlatformViews.mm
- shell/platform/darwin/ios/framework/Source/FlutterPlatformViewsTest.mm
- shell/platform/darwin/ios/framework/Source/FlutterPlatformViews_Internal.h
- shell/platform/darwin/ios/ios_external_view_embedder.h
- shell/platform/darwin/ios/ios_external_view_embedder.mm
- shell/platform/embedder/embedder_external_view_embedder.cc
- shell/platform/embedder/embedder_external_view_embedder.h
- shell/platform/fuchsia/flutter/fuchsia_external_view_embedder.cc
- shell/platform/fuchsia/flutter/fuchsia_external_view_embedder.h
- shell/platform/fuchsia/flutter/platform_view_unittest.cc
CP for fixing https://github.com/flutter/flutter/issues/69642
> started providing the GPU sync switch to external view embedders

- shell/platform/darwin/ios/framework/Source/FlutterPlatformViews.mm
- shell/platform/darwin/ios/framework/Source/FlutterPlatformViewsTest.mm
- shell/platform/darwin/ios/framework/Source/FlutterPlatformViews_Internal.h
- shell/platform/darwin/ios/ios_external_view_embedder.mm
- testing/scenario_app/ios/Scenarios/Scenarios.xcodeproj/project.pbxproj
- testing/scenario_app/ios/Scenarios/Scenarios/AppDelegate.m
- testing/scenario_app/ios/Scenarios/Scenarios/ContinuousTexture.h
- testing/scenario_app/ios/Scenarios/Scenarios/ContinuousTexture.m
- testing/scenario_app/ios/Scenarios/ScenariosUITests/PlatformViewUITests.m
- testing/scenario_app/lib/src/platform_view.dart
- testing/scenario_app/lib/src/scenarios.dart
This is a CP of https://github.com/flutter/engine/commit/74d40c101f5dd4ab06ec834e42cc8ec9a21f5c9c
> PlatformViewsController: clear composition_order_ in the beginning of each frame.

- DEPS
Avoids the need for patches + manual roll for https://dart-review.googlesource.com/c/sdk/+/174382/1.
none …
> add file package to deps in prep for glob update

- DEPS
https://dart-review.googlesource.com/c/sdk/+/174382 added `package:file` to the DEPS in Dart.
In order to prevent these manual DEPS file fixes in the future, we should make https://github.com/flutter/buildroot/blob/master/tools/dart/create_updated_flutter_deps.py deal with new dependencies. (Tracked in https://github.com/flutter/flutter/issues/71474.)
Adds `package:file` to the DEPS file, in correspondence to https://dart-review.googlesource.com/c/sdk/+/174382.
Failing Dart Flutter HHH build: https://ci.chromium.org/ui/p/dart/builders/ci.sandbox/flutter-engine-linux/12295/overview
No new tests, this fixes the build. …
> Add package:file to DEPS

- DEPS
- benchmarking/benchmarking.h
- third_party/txt/benchmarks/paint_record_benchmarks.cc
- third_party/txt/benchmarks/paragraph_benchmarks.cc
- third_party/txt/benchmarks/paragraph_builder_benchmarks.cc
- third_party/txt/benchmarks/skparagraph_benchmarks.cc
- third_party/txt/benchmarks/styled_runs_benchmarks.cc
- third_party/txt/benchmarks/txt_run_all_benchmarks.cc
Roll benchmark to google/benchmark@bf585a2789e30585b4e3ce6baf11ef2750b54677
Roll buildroot to flutter/buildroot@084f0d394f5b8fab6ddc2edb4837e20209a726a0
/cc @liyuqian FYI
> Roll buildroot and benchmark

- shell/common/switches.cc
For https://github.com/flutter/flutter/issues/71178 , so that the test can include more verbose logging.
> Add trace kernel flag to allowlist 

- lib/web_ui/lib/src/engine/canvaskit/text.dart
Memoize the fallback SkPaint in paragraph. Creating a new object every time leaks it.
> memoize the fallback SkPaint in paragraph

- flow/embedded_view_params_unittests.cc
- flow/layers/checkerboard_layertree_unittests.cc
- flow/layers/opacity_layer_unittests.cc
- flow/layers/picture_layer_unittests.cc
- flow/layers/shader_mask_layer_unittests.cc
- flow/layers/transform_layer_unittests.cc
- lib/ui/painting/image_decoder.cc
- shell/common/canvas_spy.cc
- shell/common/canvas_spy.h
- shell/platform/android/external_view_embedder/external_view_embedder_unittests.cc
- testing/mock_canvas.cc
- testing/mock_canvas.h
Opt into new virtuals for SkCanvas -- SkMatrix is out, SkM44 is in
This involved updating lots of MockCanvas plumbing. No logical changes, just using the new types.
(would be really helpful to find ways to test flutter w/o relying on SkCanvas' internal virtuals)
skbug.com/11004
Use newer factories for matrices -- MakeFoo -> Foo
Start to use SkSamplingOptions (instead of deprecated SkFilterQuality)
skbug.com/7650
[contributor guide]: …
> opt into new Skia APIs

- ci/licenses_golden/licenses_flutter
- lib/web_ui/lib/src/engine.dart
- lib/web_ui/lib/src/engine/text/canvas_paragraph.dart
- lib/web_ui/lib/src/engine/text/layout_service.dart
- lib/web_ui/lib/src/engine/text/paragraph.dart
- lib/web_ui/test/text/layout_service_helper.dart
- lib/web_ui/test/text/layout_service_plain_test.dart
This is the first in a sequence of PRs to implement rich text measurement. It performs measurement of rich text that doesn't contain ellipsis nor placeholders. The place for handling ellipsis and placeholders is marked with TODOs inside the code, and will be added in subsequent PRs.
> [web] Initial rich measurement implementation

- shell/platform/android/io/flutter/plugin/platform/PlatformPlugin.java
- shell/platform/android/test/io/flutter/plugin/platform/PlatformPluginTest.java
Fixes https://github.com/flutter/flutter/issues/71683
> Handle null platform plugin delegate for v1 embedding

- testing/elf_loader.cc
Log was spammy.
Resolves https://github.com/flutter/flutter/issues/71696
> Remove spammy ELF load log

- shell/platform/darwin/ios/framework/Source/FlutterPlatformViewsTest.mm
SkMatrix is deprecating some of its factories. This must moves flutter tests to the new ones.
No expected change in runtime. …
> Update sites to use new SkMatrix factories

- lib/web_ui/lib/src/engine/text/layout_service.dart
- lib/web_ui/test/text/layout_service_plain_test.dart
Handle overflow ellipsis and maxLines in rich paragraphs.
> [web] Handle overflow and maxLines in rich text

- lib/web_ui/lib/src/engine/text/layout_service.dart
- lib/web_ui/test/text/layout_service_plain_test.dart
Fix edge cases of text overflow and ellipsis.
I unskipped some tests and added some in `test/text/layout_service_plain_test.dart `.
> [web] Fix edge cases when force-breaking lines

- shell/platform/android/io/flutter/plugin/editing/InputConnectionAdaptor.java
- shell/platform/android/test/io/flutter/plugin/editing/InputConnectionAdaptorTest.java
[previous build](https://github.com/flutter/engine/pull/22449)
Fixes merge conflicts and cherrypicks b4d4e30c0a9c9d6ba3e3b99e43fd161d235894cb into this release branch.
* Linux/Mac Web Engine
* flutter/flutter#53371
* Mac iOS Engine
* This is due to running the master channel recipe flutter/flutter#53371
* The upstream change that broke this was https://flutter-review.googlesource.com/c/recipes/+/6960
* Linux Android AOT Engine
* Upstream issue https://github.com/flutter/flutter/issues/70633, fixed on the branch by the cherrypick https://github.com/flutter/engine/pull/22938
> [flutter_release] Flutter 1.22.5 engine cherry-pick

- lib/web_ui/lib/src/engine/text/canvas_paragraph.dart
- lib/web_ui/test/text/canvas_paragraph_builder_test.dart
Use the same default text styles in the new rich text implementation.
> [web] Default styles for rich text

- shell/platform/linux/fl_mouse_cursor_plugin.cc
- shell/platform/linux/fl_plugin_registrar.cc
Replace g_object_weak_ref with g_object_add_weak_pointer
In these cases it is simpler to use the latter. Newer code is using this method.
None
Existing tests will exercise this code.
[CLA]: …
> Replace g_object_weak_ref with g_object_add_weak_pointer

- shell/platform/fuchsia/flutter/compositor_context.cc
- shell/platform/fuchsia/flutter/compositor_context.h
- shell/platform/fuchsia/flutter/engine.cc
- shell/platform/fuchsia/flutter/vulkan_surface_producer.cc
- shell/platform/fuchsia/flutter/vulkan_surface_producer.h
This reverts commit 062cbd8cc8026ac8cdda48a29dc60e50535877b5.
accidentally landed this without review so reverting. will resubmit new pull request
> Revert "Freiling warmup memory (#22984)"

- shell/platform/linux/fl_platform_plugin.cc
Implement SystemSound.play (alert sounds).
https://github.com/flutter/flutter/issues/62143
No tests added. …
> Implement SystemSound.play

- lib/web_ui/dev/browser_lock.yaml
> upgrade Firefox to 83

- lib/web_ui/lib/src/engine/text/canvas_paragraph.dart
- lib/web_ui/lib/src/engine/text/paragraph.dart
- lib/web_ui/test/text/canvas_paragraph_builder_test.dart
Added tests for rich paragraph DOM generation and caught a couple bugs 🙂
> [web] Tests for rich paragraph DOM

- DEPS
Rolls the fuchsia toolchain from
3aa8e071dd1ae7e9fb9e28fa9fcdb9f9fdb7aa06 to 2c0536b76b35fa592ac7b4a0e4bb176eaf55af75
> Roll fuchsia toolchain

- shell/platform/darwin/ios/ios_external_texture_gl.mm
- shell/platform/darwin/ios/ios_external_texture_metal.mm
Update ios to use non-deprecated version of SkImage::MakeFromYUVATextures …
> Update ios to use new YUVA texture SkImage factory

- fml/platform/android/jni_util.cc
- fml/platform/android/jni_util.h
- shell/platform/android/android_shell_holder.cc
- shell/platform/android/android_shell_holder.h
Fixes https://github.com/flutter/flutter/issues/72568
> Call JavaVM::AttachCurrentThread only once per thread

- third_party/accessibility/ax/platform/ax_unique_id_unittest.cc
*Replace this paragraph with a description of what this PR is doing. If you're
modifying existing behavior, describe the existing behavior, how this PR is
changing it, and what motivated the change.*
https://github.com/flutter/flutter/issues/73512
*Replace this with a list of the tests that you added as part of this PR. A
change in behaviour with no test covering it will likely get reverted
accidentally sooner or later. PRs must include tests for all
changed/updated/fixed behaviors. See [testing the engine] for instructions on
writing and running engine tests.*
Did any tests fail when you …
> disable UnassignedIdsAreReused flaky test

- DEPS
- tools/fuchsia/clang.gni
- tools/fuchsia/fuchsia_libs.gni
- tools/fuchsia/parse_manifest.py
Cherrypick 0419f1d46ab0233ffe48f98f31eabf403f6224a3.
> Revert "bump fuchsia toolchain to clang-12" (#23456)

- shell/common/canvas_spy.cc
- shell/common/canvas_spy.h
- testing/mock_canvas.cc
- testing/mock_canvas.h
See skbug.com/7650
imageset virtual now takes sampling-options as a parameter
> Update virtual to take sampling

- shell/platform/linux/fl_engine_test.cc
See https://github.com/flutter/flutter/issues/73517
> Skip the FlEngineTest.SettingsPlugin test

- flow/layers/shader_mask_layer_unittests.cc
*Skia would like to delete MakeImprovedNoise as it isn't tested nor used by any client other
than in these unit tests.
This only modifies existing tests. …
> Use Fractal rather than Improved noise in shader mask flow unit test

- common/graphics/persistent_cache.cc
The old SkBase64::decode interface required the user to delete the result of SkBase64::getData. Use the newer SkBase64::Decode interface which makes the memory ownership more obvious.
> Fix leak when parsing base64.

- shell/platform/linux/fl_renderer.cc
- shell/platform/linux/fl_view.cc
Fix slow scroll speed in Wayland.
https://github.com/flutter/flutter/issues/71385
No tests changed. …
> Fix slow scroll speed in Wayland.

- lib/web_ui/dev/goldens_lock.yaml
- lib/web_ui/lib/src/engine/canvaskit/layer.dart
- lib/web_ui/lib/src/engine/canvaskit/util.dart
- lib/web_ui/test/canvaskit/canvas_golden_test.dart
Switch to directional shadows. This PR must land _after_ https://github.com/flutter/engine/pull/23348.
Fixes the web part of https://github.com/flutter/flutter/issues/51237
Added a new test in `canvaskit/canvas_golden_test.dart`.
> Switch to directional shadows

- DEPS
- tools/fuchsia/clang.gni
- tools/fuchsia/fuchsia_libs.gni
- tools/fuchsia/parse_manifest.py
Attempting to land the bump to clang 12 after fixing the crashes that were causing fuchsia CQ tests to fail.
https://github.com/flutter/flutter/issues/73515
> Reland - bump fuchsia toolchain to clang 12

- lib/web_ui/lib/src/engine/web_experiments.dart
- lib/web_ui/test/engine/web_experiments_test.dart
- lib/web_ui/test/golden_tests/engine/canvas_golden_test.dart
Original PR: https://github.com/flutter/engine/pull/23162
Reverted in: https://github.com/flutter/engine/pull/23651
The issue that caused the revert was fixed in: https://github.com/flutter/engine/pull/23653
> [web] Reland: Enable the new rich paragraph implementation

- lib/web_ui/lib/src/engine/web_experiments.dart
- lib/web_ui/test/engine/web_experiments_test.dart
- lib/web_ui/test/golden_tests/engine/compositing_golden_test.dart
> Revert "[web] Enable the new rich paragraph implementation"

- .github/PULL_REQUEST_TEMPLATE.md
This is part of a general simplification effort for our contributor docs.
> Sync the pull request template with the flutter/flutter version

- runtime/dart_vm.cc
This PR enables some timeline traces unconditionally on startup if other flags controlling tracing are not supplied.
Related https://github.com/flutter/flutter/issues/70794
> Unconditionally enable some tracing on startup

- shell/platform/fuchsia/dart_runner/kernel/libraries.json
- shell/platform/fuchsia/dart_runner/kernel/libraries.yaml
- shell/platform/fuchsia/flutter/kernel/libraries.json
- shell/platform/fuchsia/flutter/kernel/libraries.yaml
Cherry pick 920a33a0fc3a1d9913d889a77593161e175f1863
> Cherry pick 920a33a0fc3a1d9913d889a77593161e175f1863

- testing/scenario_app/ios/Scenarios/Scenarios.xcodeproj/xcshareddata/xcschemes/Scenarios.xcscheme
Skip rotation test as this is flaking for the stable branch.
> [flutter_releases] Flutter 1.22.6 Engine Infra Cherrypick

- flutter_frontend_server/lib/server.dart
- flutter_frontend_server/test/to_string_test.dart
This is basically a follow-up to https://github.com/flutter/engine/pull/22585
> Use ToStringTransformer from dart frontend_server

- shell/platform/windows/angle_surface_manager.cc
- shell/platform/windows/angle_surface_manager.h
This adds a bunch of additional logging to AngleSurfaceManager to help debug initialisation issues better.
> Increase logging in AngleSurfaceManager

- shell/platform/android/android_surface_software.cc
Also, pass sampling options explicitly, since SkFilterQuality is deprecated
> drawBitmap is deprecated, use drawImage

- shell/platform/android/io/flutter/embedding/android/FlutterActivity.java
- shell/platform/android/io/flutter/embedding/android/FlutterFragment.java
- shell/platform/android/test/io/flutter/embedding/android/FlutterActivityTest.java
- shell/platform/android/test/io/flutter/embedding/android/FlutterFragmentTest.java
> Make activity/fragment leftover from an attach/detach race slightly safer

- tools/generate_package_config/pubspec.yaml
Cherrypick https://github.com/flutter/engine/commit/cb86ca0b5d9ed42e64ad53012975a0fe31e00d2a to fix beta builds.
> Pin the package_config package

- sky/tools/create_ios_framework.py
This adds support for arm64 simulator builds to `create_ios_framework.py`.
Some caveats:
- Fat frameworks can only support a single instance of a particular architecture, as they do not distinguish between a "simulator" arm64 binary and a "device" arm64 binary. As a result, the `Flutter.framework` will still only contain ios-{arm64,armv7} and simulator-x64.
- The XCFramework supports the above, so if you pass `--simulator-arm64-out-dir` as well it will ensure that's put appropriately in the `Flutter.xcframework`.
- I've renamed `--simulator-out-dir` to `--simulator-x64-out-dir` and aliased it to the former name. It is still a required parameter, but the arm64 is not (yet) required.
```
Georges-Mac-mini:src george$ ./flutter/sky/tools/create_ios_framework.py --dst test --arm64-out-dir …
```
> Add support for arm64 simulator builds to create_ios_framework.py

- shell/platform/android/io/flutter/view/FlutterCallbackInformation.java
Fixes https://github.com/flutter/flutter/issues/73937
> Remove NonNull annotation on FlutterCallbackInformation.lookupCallbackInformation

- DEPS
> Revert "Roll buildroot to 739be241578e7f12773eedb713df7fe3b0ec917b"

- shell/platform/fuchsia/flutter/README.md
Updates the readme file for the runner. This is a no-op change to test out build trigger on the fuchsia_f1 branch.
> [shell][fuchsia] Update README.md

- lib/web_ui/dev/goldens_lock.yaml
- lib/web_ui/lib/src/engine/canvaskit/initialization.dart
- lib/web_ui/test/canvaskit/canvaskit_api_test.dart
- lib/web_ui/test/canvaskit/surface_test.dart
Reverts flutter/engine#24249
This is blocking the roller
> Revert "Roll CanvasKit to 0.23"

- shell/platform/darwin/macos/framework/Source/FlutterGLCompositor.h
- shell/platform/darwin/macos/framework/Source/FlutterGLCompositor.mm
- shell/platform/darwin/macos/framework/Source/FlutterMetalRenderer.mm
- shell/platform/darwin/macos/framework/Source/FlutterOpenGLRenderer.mm
https://github.com/flutter/flutter/issues/75564 …
> Fix retain cycles in MacOS embedder

- ci/licenses_golden/licenses_flutter
- shell/platform/darwin/macos/BUILD.gn
- shell/platform/darwin/macos/framework/Source/FlutterEmbedderExternalTextureUnittests.mm
- shell/platform/darwin/macos/framework/Source/FlutterEngine.mm
- shell/platform/darwin/macos/framework/Source/FlutterOpenGLRendererTest.mm
- shell/platform/darwin/macos/framework/Source/FlutterRenderingBackend.h
- shell/platform/darwin/macos/framework/Source/FlutterRenderingBackend.mm
- shell/platform/darwin/macos/framework/Source/FlutterView.mm
- shell/platform/darwin/macos/framework/Source/FlutterViewController.mm
- tools/gn
Fixes: https://github.com/flutter/flutter/issues/74058
> [macos] Make metal the default rendering backend on macOS >= 10.14

- shell/platform/android/io/flutter/app/FlutterActivityDelegate.java
`disable-service-auth-codes` set repeatedly.
line 289 vs 326 when #9378
> Delete multi set args parameter from intent

- lib/web_ui/test/golden_tests/engine/shader_mask_golden_test.dart
https://github.com/flutter/flutter/issues/76713
> Skip flaky webkit shadermask test

- lib/ui/compositing/scene_builder.cc
This two lines of code was add in #6256 and now is useless since line 205-207 was deleted in some commit.
> remove useless code in lib/ui/compositing/scene_builder.cc

- shell/platform/darwin/macos/framework/Source/FlutterFrameBufferProvider.mm
https://github.com/flutter/flutter/issues/76920
- [X ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ X] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [ X] I listed at least one issue that this PR fixes in the description above.
- [ X] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on
- [X ] I updated/added relevant documentation (doc comments with `///`).
- [X ] I signed the [CLA]. …
> Switch to correct OpenGL context before deleting framebuffers.

- shell/platform/darwin/macos/framework/Source/FlutterRenderingBackend.mm
- shell/platform/embedder/embedder_external_texture_metal.mm
> Guard metal rendering behind SHELL_ENABLE_METAL

- shell/platform/linux/fl_view.cc
This PR fixes flutter/flutter#77710.
The high CPU consumption is caused by reordering `GdkWindow`s in draw function, which will schedule redraw of entire `GtkWindow` later, leading to a 'dead loop'. …
> [Linux] Fix high CPU consumption

- third_party/accessibility/ax/platform/ax_platform_node_base.cc
This is from @cbracken. Pulls in the upstream code impl from https://source.chromium.org/chromium/chromium/src/+/master:ui/accessibility/platform/ax_platform_node_base.cc;l=93?q=GetInstanceCountForTesting&ss=chromium
> Implement AXPlatformNodeBase::GetInstanceCountForTesting

- DEPS
- ci/licenses_golden/licenses_third_party
- sky/packages/sky_engine/LICENSE
Roll Angle to pick up https://github.com/google/angle/commit/06d194e2ae7b1d7e0eda0c0c911eff92dec7d3d1
https://github.com/flutter/flutter/issues/70196
https://github.com/flutter/flutter/issues/14967 …
> Roll Angle to pick up UWP support

- shell/platform/darwin/macos/framework/Source/FlutterEmbedderExternalTextureUnittests.mm
- shell/platform/darwin/macos/framework/Source/FlutterExternalTextureMetal.mm
- testing/scenario_app/ios/Scenarios/Scenarios/ContinuousTexture.m
This also adds a test for the said failure
Fixes: https://github.com/flutter/flutter/issues/78056
> [macos] [metal] Fix use after free in FlutterExternalTextureMetal

- third_party/accessibility/base/numerics/BUILD.gn
- third_party/accessibility/base/numerics/safe_math_shared_impl.h
The header wasn't used so it does not trigger error. However, our internal build has stricter rule, and is causing error. …
> fix numeric dependencies

- lib/ui/painting.dart
See https://github.com/flutter/engine/pull/24877
See https://github.com/flutter/flutter/issues/78429
> Complete Picture.toImage futures with an exception if the image is null

- BUILD.gn
- third_party/accessibility/BUILD.gn
- third_party/accessibility/ax/BUILD.gn
- third_party/accessibility/ax/ax_active_popup.cc
- third_party/accessibility/ax/ax_active_popup.h
- third_party/accessibility/ax/platform/uia_registrar_win.cc
- third_party/accessibility/base/BUILD.gn
- third_party/accessibility/base/compiler_specific.h
- third_party/accessibility/base/test/gtest_util.h
- third_party/accessibility/base/win/atl.h
- third_party/accessibility/base/win/enum_variant.cc
- third_party/accessibility/base/win/scoped_bstr.cc
- third_party/accessibility/base/win/scoped_bstr.h
- third_party/accessibility/base/win/scoped_bstr_unittest.cc
- third_party/accessibility/base/win/scoped_safearray.h
- third_party/accessibility/base/win/scoped_safearray_unittest.cc
- third_party/accessibility/base/win/scoped_variant.cc
- third_party/accessibility/base/win/scoped_variant.h
- third_party/accessibility/base/win/scoped_variant_unittest.cc
- third_party/accessibility/base/win/variant_util.h
- third_party/accessibility/base/win/variant_vector.cc
- third_party/accessibility/base/win/variant_vector.h
- third_party/accessibility/gfx/BUILD.gn
- third_party/accessibility/gfx/range/range.cc
- third_party/accessibility/gfx/range/range.h
- third_party/accessibility/gfx/range/range_unittest.cc
This is the full set of modifications needed to get the following `base/` classes to build in Flutter. Work done by both me and @cbracken.
> Modifications to imported a11y base classes to build in Flutter

- .cirrus.yml
Updates the cirrus engine secret in preparation to disable old service account keys.
Bug: https://github.com/flutter/flutter/issues/77624 …
> Use new cirrus secrets for engine.

- lib/ui/text/asset_manager_font_provider.cc
- third_party/txt/src/txt/font_collection.cc
See https://github.com/flutter/flutter/issues/77913
> Do not return a Minikin font collection if the SkFontStyleSet is unable to create any typefaces

- third_party/accessibility/base/string_utils.h
Uses `std::unique_ptr`, so should include `memory`
[engine presubmit flakes …
> Add missing include to string_utils.h

- lib/web_ui/dev/chrome.dart
- lib/web_ui/dev/firefox.dart
- lib/web_ui/dev/test_platform.dart
- lib/web_ui/dev/test_runner.dart
- lib/web_ui/lib/src/engine.dart
- lib/web_ui/lib/src/engine/bitmap_canvas.dart
- lib/web_ui/lib/src/engine/window.dart
- lib/web_ui/test/color_test.dart
- lib/web_ui/test/engine/path_metrics_test.dart
- lib/web_ui/test/engine/surface/path/path_iterator_test.dart
- lib/web_ui/test/engine/surface/path/path_winding_test.dart
- lib/web_ui/test/engine/ulps_test.dart
- lib/web_ui/test/golden_tests/engine/color_filter_golden_test.dart
- lib/web_ui/test/lerp_test.dart
- lib/web_ui/test/path_test.dart
- lib/web_ui/test/text/line_breaker_test.dart
In preparation for https://github.com/dart-lang/sdk/issues/35234.
> Remove ignores that are not ignoring anything

- testing/scenario_app/run_ios_tests.sh
Because of the weird tricks that are happening to make scenario app tests work I ran into problems where they were running locally with old versions of the engine.  Cleaning out the test before hand seems to have solved the issue for me.
related issue: https://github.com/flutter/flutter/issues/78907 …
> started cleaning scenario tests before running them

- shell/platform/android/io/flutter/view/AccessibilityBridge.java
- shell/platform/android/test/io/flutter/view/AccessibilityBridgeTest.java
Previous pr was reverted due to internal lint error and framework post submit integration test.
The only change from the previous pr is fixing the lint, which is in the second commit.
This is the second step of https://github.com/flutter/flutter/issues/77965#issuecomment-809639712
https://github.com/flutter/flutter/issues/77965
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/master/CONTRIBUTING.md#styl …
> Reland "Fixes android voice access delete text, redo, and undo action"

- lib/web_ui/lib/src/engine/canvaskit/canvaskit_api.dart
- lib/web_ui/lib/src/engine/canvaskit/text.dart
- lib/web_ui/test/canvaskit/canvaskit_api_test.dart
Adds `computeLineMetrics` to `Paragraph` in the CanvasKit backend for the Flutter web engine.
Fixes https://github.com/flutter/flutter/issues/78957 …
> Implement computeLineMetrics

- shell/platform/windows/angle_surface_manager.cc
- shell/platform/windows/angle_surface_manager.h
- shell/platform/windows/flutter_window_win32.cc
- shell/platform/windows/flutter_window_win32.h
- shell/platform/windows/flutter_window_winuwp.cc
- shell/platform/windows/flutter_window_winuwp.h
- shell/platform/windows/flutter_windows_engine.cc
- shell/platform/windows/flutter_windows_engine.h
- shell/platform/windows/flutter_windows_engine_unittests.cc
- shell/platform/windows/flutter_windows_view.cc
- shell/platform/windows/flutter_windows_view.h
- shell/platform/windows/flutter_windows_win32.cc
- shell/platform/windows/testing/engine_embedder_api_modifier.h
- shell/platform/windows/testing/mock_window_binding_handler.h
- shell/platform/windows/window_binding_handler.h
Fixes https://github.com/flutter/flutter/issues/76132
Tests to come.
> Support software rendering fallback on Win32

- lib/web_ui/dev/goldens_lock.yaml
- lib/web_ui/lib/src/engine/pointer_binding.dart
- lib/web_ui/lib/src/engine/pointer_converter.dart
- lib/web_ui/lib/src/engine/text/layout_service.dart
- lib/web_ui/test/engine/pointer_binding_test.dart
- lib/web_ui/test/golden_tests/engine/canvas_paragraph/placeholders_test.dart
- lib/web_ui/test/text/layout_service_rich_test.dart
- https://github.com/flutter/engine/commit/d10ad468ab46a49bbfecf8fa735338bd6a502485
- https://github.com/flutter/engine/commit/c1ada6714064d88b1544eb820cf1e665524ac280
- Original author @mdebbar 
- https://github.com/flutter/engine/commit/7d7b6451c4c9fc80fcfb54f8704db8982b23ca2a
- Original author @mdebbar 
- Linux & Mac Web Engine goldens diffs, same as [previous build](https://github.com/flutter/engine/pull/25055)
- build_and_test_linux_unopt_debug timed out after an hour, ignoring as the LUCI build succeeded.
> [flutter_releases] Flutter Stable 2.0.4 Engine Cherrypicks

- ci/licenses_golden/licenses_flutter
- shell/platform/windows/BUILD.gn
- shell/platform/windows/display_helper_winuwp.cc
- shell/platform/windows/display_helper_winuwp.h
- shell/platform/windows/flutter_window_winuwp.cc
- shell/platform/windows/flutter_window_winuwp.h
- shell/platform/windows/game_pad_cursor_winuwp.cc
- shell/platform/windows/game_pad_cursor_winuwp.h
- shell/platform/windows/game_pad_winuwp.cc
- shell/platform/windows/game_pad_winuwp.h
Adds an emulated mouse cursor for devices that don't typically have a traditional mouse.  Enables mouse-like user interactions by using gamepad devices. 
https://github.com/flutter/flutter/issues/76092
https://github.com/flutter/flutter/issues/14967
Unit tests blocked by: https://github.com/flutter/flutter/issues/70197 label added
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/master/CONTRIBUTING.md#s …
> Windows UWP: Add support for emulated mouse cursor for targets such as XBOX

- testing/scenario_app/README.md
Update scenario test tutorial.
[Discord]: …
> [iOS][Test] Update scenario test tutorial

- third_party/tonic/filesystem/filesystem/path_win.cc
In UWP, GetFinalPathNameByHandle requires the app to declare appropriate
capabilities in the app's package manifest. Some of these capabilities are not
permitted in shipping apps on the app store, but may be fine for
development/debugging scenarios. If we can't resolve the full path due to
insufficient access, but have verified the handle is valid, return the original
path.
This gets hot reload requests working in the UWP embedder.
Related: https://github.com/flutter/flutter/issues/65559
Related: https://github.com/flutter/flutter/issues/79609 …
> Add fallback for GetAbsoluteFilePath in UWP

- runtime/dart_isolate.cc
See https://github.com/flutter/flutter/issues/79498
> Remove the DartIsolate::PostMessage timeline event

- shell/platform/windows/client_wrapper/flutter_engine.cc
- shell/platform/windows/client_wrapper/testing/stub_flutter_windows_api.cc
- shell/platform/windows/flutter_windows.cc
- shell/platform/windows/public/flutter_windows.h
FlutterDesktopEngineCreate is part of our C API. We were using a C++
reference type instead of a C-compatible pointer type.
This is a breaking change to anyone calling this directly; we believe
this should affect few people because the Windows template only uses the
`FlutterEngine` wrapper in
`shell/platform/windows/client_wrapper/include/flutter/flutter_engine.h`.
Fixes https://github.com/flutter/flutter/issues/75465
[C++, …
> Fix parameter type in FlutterDesktopEngineCreate

- lib/web_ui/dev/goldens_lock.yaml
- lib/web_ui/lib/src/engine/canvaskit/layer.dart
- lib/web_ui/test/canvaskit/shader_mask_golden_test.dart
Fixes shadermask target rectangle.
Related issue: https://github.com/flutter/flutter/issues/78959
Added shader_mask_golden_test
> [web] Fix shadermask rendering using CanvasKit

- shell/platform/darwin/ios/ios_context_metal.mm
Additional retain of `FlutterDarwinContextMetal` leads Metal leaks. From the very simple page, memory leaks 15M+ for each new engine.
Repro steps:
1. Open a new Flutter VC with the newly created engine.
2. Pop the opened Flutter VC.
3. Repeat steps 1 and 2.
https://user-images.githubusercontent.com/5061845/113437575-6edcf600-9419-11eb-9dfe-305a540712d2.MP4
Before:
After:
cc. @iskakaushik @chinmaygarde  …
> [iOS] Fixes context memory leaks when using Metal

- ci/dev/prod_builders.json
- ci/dev/try_builders.json
This enables Windows UWP builds in pre/post-submit.
Issue: https://github.com/flutter/flutter/issues/78627 …
> Add Windows UWP CI builders

- shell/platform/darwin/graphics/FlutterDarwinContextMetal.h
- shell/platform/darwin/graphics/FlutterDarwinContextMetal.mm
- shell/platform/darwin/macos/framework/Source/FlutterExternalTextureMetal.mm
- shell/platform/embedder/embedder_surface_metal.mm
Fixes: https://github.com/flutter/flutter/issues/79648
> [macos] Release the copied pixel buffer after texture creation

- shell/platform/darwin/macos/framework/Source/FlutterMetalSurfaceManagerTest.mm
- shell/platform/darwin/macos/framework/Source/FlutterRenderingBackend.h
- shell/platform/darwin/macos/framework/Source/FlutterRenderingBackend.mm
- shell/platform/darwin/macos/framework/Source/FlutterResizableBackingStoreProvider.h
- shell/platform/darwin/macos/framework/Source/FlutterResizableBackingStoreProvider.mm
- shell/platform/darwin/macos/framework/Source/FlutterSurfaceManager.h
- shell/platform/darwin/macos/framework/Source/FlutterSurfaceManager.mm
- shell/platform/darwin/macos/framework/Source/FlutterView.mm
https://github.com/flutter/flutter/issues/80160 …
> FlutterView: Use default backing layer

- lib/web_ui/dev/goldens_lock.yaml
- lib/web_ui/lib/src/engine/canvaskit/canvaskit_api.dart
- lib/web_ui/lib/src/engine/canvaskit/shader.dart
- lib/web_ui/lib/src/ui/painting.dart
- lib/web_ui/test/canvaskit/canvaskit_api_test.dart
- lib/web_ui/test/canvaskit/linear_gradient_golden_test.dart
Fixes matrix parameter not being passed to canvaskit.
https://github.com/flutter/flutter/issues/79980
Added golden tests.
> [web] Fix linear gradient transformation matrix

- shell/platform/android/io/flutter/embedding/engine/FlutterEngine.java
There's some old language in the class doc.
> change the Android FlutterEngine class doc around multiple engines

- lib/web_ui/test/golden_tests/engine/backdrop_filter_golden_test.dart
- lib/web_ui/test/golden_tests/engine/canvas_arc_golden_test.dart
- lib/web_ui/test/golden_tests/engine/canvas_blend_golden_test.dart
- lib/web_ui/test/golden_tests/engine/canvas_clip_path_test.dart
- lib/web_ui/test/golden_tests/engine/canvas_context_test.dart
- lib/web_ui/test/golden_tests/engine/screenshot.dart
- lib/web_ui/test/golden_tests/golden_failure_smoke_test.dart
- lib/web_ui/test/golden_tests/golden_success_smoke_test.dart
https://github.com/flutter/flutter/issues/80533
> migrate tests to nullsafe

- ci/licenses_golden/licenses_flutter
- shell/platform/darwin/macos/BUILD.gn
- shell/platform/darwin/macos/framework/Source/FlutterCompositor.h
- shell/platform/darwin/macos/framework/Source/FlutterCompositor.mm
- shell/platform/darwin/macos/framework/Source/FlutterGLCompositor.h
- shell/platform/darwin/macos/framework/Source/FlutterGLCompositor.mm
This refactors the existing FlutterGLCompositor into a base class, FlutterCompositor, which provides the methods for future use with the Embedder API's FlutterCompositor API.
This paves the way for a future FlutterMetalCompositor.
https://github.com/flutter/flutter/issues/80396
The existing tests for FlutterGLCompositor cover this as it's a straight refactor with no new functionality. 
- [x ] I listed at least one issue that this PR fixes in the description above. …
> Add FlutterCompositor base class

- .cirrus.yml
@jmagman 
See https://github.com/flutter/flutter/pull/80484
> Remove --dartdocs in preparation for removal from tool

- flutter_frontend_server/test/to_string_test.dart
fixes: https://github.com/flutter/flutter/issues/80728
> Library and Class ctor from the next dart roll requires fileUri

- shell/platform/fuchsia/flutter/BUILD.gn
- shell/platform/fuchsia/flutter/meta/flutter_aot_product_runner.cmx
- shell/platform/fuchsia/flutter/meta/flutter_aot_runner.cmx
- shell/platform/fuchsia/flutter/meta/flutter_jit_product_runner.cmx
- shell/platform/fuchsia/flutter/meta/flutter_jit_runner.cmx
- shell/platform/fuchsia/flutter/meta/flutter_runner_scenic_tests.cmx
- shell/platform/fuchsia/flutter/meta/flutter_runner_tests.cmx
- shell/platform/fuchsia/flutter/vulkan_surface.cc
- shell/platform/fuchsia/flutter/vulkan_surface.h
- shell/platform/fuchsia/flutter/vulkan_surface_pool.cc
- shell/platform/fuchsia/flutter/vulkan_surface_pool.h
- testing/fuchsia/meta/fuchsia_test.cmx
Cherry pick this revert to the dev branch.
> Revert "[fuchsia] Use scenic allocator service (#25385)" (#25655)

- shell/platform/android/BUILD.gn
- shell/platform/android/io/flutter/embedding/android/FlutterView.java
- shell/platform/android/test/io/flutter/TestUtils.java
- shell/platform/android/test/io/flutter/Utils.java
- shell/platform/android/test/io/flutter/embedding/android/FlutterViewTest.java
- shell/platform/android/test/io/flutter/plugin/localization/LocalizationPluginTest.java
Fixes https://github.com/flutter/flutter/issues/80980
This workaround is based off the work the Jetpack compose team did [here]( https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/ui/ui/src/androidMain/kotlin/androidx/compose/ui/platform/AndroidComposeView.android.kt;l=917-925?q=AndroidComposeView.android.kt).
> Fix accessibility of embedded views in Android 9 and below

- lib/web_ui/lib/src/engine/canvaskit/initialization.dart
This release adds `textHeightBehavior` and more `TextHeightStyle`s which enable us to address https://github.com/flutter/flutter/issues/77083 and https://github.com/flutter/flutter/issues/74337 …
> Roll CanvasKit to 0.26.0

- ci/licenses_golden/licenses_flutter
- shell/platform/darwin/macos/BUILD.gn
- shell/platform/darwin/macos/framework/Source/FlutterMetalCompositor.h
- shell/platform/darwin/macos/framework/Source/FlutterMetalCompositor.mm
This adds a stub implementation of FlutterCompositor for Metal rendering. No tests as there's no functionality yet.
> Add a stub implementation of FlutterMetalCompositor

- lib/web_ui/lib/src/engine/html/canvas.dart
- lib/web_ui/test/golden_tests/engine/canvas_draw_image_golden_test.dart
Fixes https://github.com/flutter/flutter/issues/78068
> Fix html version of drawImageNine

- DEPS
- ci/dev/prod_builders.json
- ci/dev/try_builders.json
We now build against a specific Windows SDK rather than whatever happens
to be installed on the host machine.
This also rolls the buildroot to include change
flutter/buildroot#448, which generates the WinRT
headers from the CIPD Windows SDK.
This also re-enables the UWP builder.
Fixes https://github.com/flutter/flutter/issues/81994
Fixes https://github.com/flutter/flutter/issues/82009
Covered by existing tests. …
> Add dependency on Windows SDK CIPD package

- shell/platform/windows/BUILD.gn
String conversion between UTF-8 and UTF-16 encodings is useful even in
the absence of other common Windows functionality.
This is pre-factoring for uwptool, which adds an adb-like helper tool
for install, uninstall, and launch of UWP applications for Windows
platforms.
See: https://github.com/flutter/flutter/issues/81756
Build refactoring. Covered by existing tests. …
> Extract Windows string_conversion target

- lib/web_ui/lib/src/engine/html/shaders/shader.dart
> Remove debug print

- shell/platform/fuchsia/flutter/fuchsia_external_view_embedder.cc
The new external_view_embedder-based renderer for Fuchsia has a subtle bug where the background layer uses an opacity of 0.996.  This can throw off the value of very bright pixels and cause screenshot tests to fail, although it is invisible to the naked eye.
Also makes a minor cleanup around using and clearing the "first_layer" variable.
Tests: Verified using internal tests (see buganizer link)
Fixes: https://buganizer.corp.google.com/issues/187737558
Fixes: https://bugs.fuchsia.dev/p/fuchsia/issues/detail?id=76503
> fuchsia: Fix first_layer handling

- shell/platform/linux/fl_view_private.h
The code had an invalid GIR annotation. …
> Fix GIR transfer annotation

- tools/fuchsia/fuchsia_archive.gni
- tools/fuchsia/gen_package.py
fxbug.dev/76633
Outputs a json version of the package manifest. This PR is in preparation for incremental package serving from the engine repo.
> output fuchsia json package manifest

- tools/fuchsia/fuchsia_archive.gni
- tools/fuchsia/gen_package.py
> Revert "output fuchsia json package manifest"

- shell/platform/darwin/common/buffer_conversions.h
- shell/platform/darwin/common/buffer_conversions.mm
- shell/platform/darwin/ios/framework/Source/platform_message_router.mm
issue: https://github.com/flutter/flutter/issues/81559
depends on: https://github.com/flutter/engine/pull/25867
locally tested 
**before:**
```
flutter: BasicMessageChannel/StandardMessageCodec/Flutter->Host/Small: 153.3 µs
BasicMessageChannel/StandardMessageCodec/Flutter->Host/Large: 1246.7 µs
BasicMessageChannel/BinaryCodec/Flutter->Host/Large: 143.2 µs
BasicMessageChannel/BinaryCodec/Flutter->Host/1MB: 1218.6 µs
```
**after:**
```
flutter: BasicMessageChannel/StandardMessageCodec/Flutter->Host/Small: 152.7 µs
BasicMessageChannel/StandardMessageCodec/Flutter->Host/Large: 1192.5 µs
BasicMessageChannel/BinaryCodec/Flutter->Host/Large: 150.2 µs
BasicMessageChannel/BinaryCodec/Flutter->Host/1MB: 761.2 µs
```
If you need help, consider asking for advice on …
> Platform channels, eliminate objc copies

- shell/platform/windows/uwptool_main.cc
- shell/platform/windows/uwptool_utils.cc
- shell/platform/windows/uwptool_utils.h
Installs the package pointed to by a URI, as well as its dependencies.
Related: https://github.com/flutter/flutter/issues/82085
Fixes: https://github.com/flutter/flutter/issues/82399 …
> Add uwptool install command

- lib/ui/text.dart
This PR fix breaking tests in `Enable avoid_escaping_inner_quotes lint` PR (flutter/flutter#81153)
Related issue flutter/flutter#77436
flutter PR flutter/flutter#81153
Because of docs change, no tests …
> Enable avoid_escaping_inner_quotes lint

- fml/message_loop.h
- fml/message_loop_impl.h
- fml/message_loop_task_queues.h
- fml/platform/android/message_loop_android.h
- fml/task_runner.h
- fml/wakeable.h
fixes https://github.com/flutter/flutter/issues/82744 …
> updated the documentation for message loops a bit

- DEPS
- ci/analyze.sh
- ci/licenses_golden/tool_signature
- testing/scenario_app/compile_android_aot.sh
- testing/scenario_app/compile_android_jit.sh
- testing/scenario_app/compile_ios_aot.sh
- testing/scenario_app/compile_ios_jit.sh
- testing/scenario_app/pubspec.yaml
- tools/licenses/lib/main.dart
Towards https://github.com/flutter/flutter/issues/82134
> Use 'pub get --offline' for scenario_app deps

- lib/web_ui/lib/src/engine/canvaskit/canvaskit_api.dart
- lib/web_ui/lib/src/engine/canvaskit/image.dart
- lib/web_ui/lib/src/engine/canvaskit/initialization.dart
- lib/web_ui/test/canvaskit/canvaskit_api_test.dart
- lib/web_ui/test/canvaskit/image_test.dart
- lib/web_ui/test/canvaskit/shader_test.dart
Fixes https://github.com/flutter/flutter/issues/81679
> roll CanvasKit 0.27.0

- shell/platform/fuchsia/flutter/runner.cc
> [vm_service] Add vm service port to inspect.

- lib/io/dart_io.cc
- lib/ui/hooks.dart
- testing/dart/http_allow_http_connections_test.dart
- testing/dart/http_disallow_http_connections_test.dart
- testing/dart/window_hooks_integration_test.dart
- testing/run_tests.py
This reverts commit c7ef259e14d7fc93892c5389ef363589d27ac6cb as dart sdk with corresponding
changes has landed in internal repo.
> Reland "Provide better messaging when user attempts to use non-secure http connection. (#26226)"

- .ci.yaml
Bug: https://github.com/flutter/flutter/issues/72391 …
> Add Linux Framework Smoke Tests to pre/post submit.

- .ci.yaml
Reverts flutter/engine#26418, the flutter checkout is trying to use the engine commit sha.
> Revert "Add Linux Framework Smoke Tests to pre/post submit."

- shell/platform/fuchsia/dart-pkg/zircon/test/handle_test.dart
Synchronize file for changes requested in https://fxrev.dev/534547.
> Add todo to handle_test.

- fml/thread_local.cc
See: https://github.com/flutter/flutter/issues/83510
> Better logging `pthread_setspecific`

- tools/fuchsia/devshell/lib/vars.sh
- tools/fuchsia/devshell/serve.sh
- tools/fuchsia/fuchsia_debug_symbols.gni
Additionally, finish soft transition: fxbug.dev/76223.
CC: @naudzghebre, @arbreng
> Add debug symbols (symbol-index) to serve.sh for Fuchsia.

- lib/web_ui/lib/src/engine/navigation/history.dart
- lib/web_ui/lib/src/engine/window.dart
- lib/web_ui/test/window_test.dart
framework pr: https://github.com/flutter/flutter/pull/83509
related https://github.com/flutter/flutter/issues/80546 …
> support history entry replace in multi entries browser history

- shell/platform/android/io/flutter/embedding/engine/FlutterShellArgs.java
- shell/platform/android/test/io/flutter/embedding/engine/FlutterShellArgsTest.java
See https://github.com/flutter/flutter/issues/83263
> Add trace-skia-allowlist to the Android intent flags

- lib/web_ui/dev/test_runner.dart
Fixes https://github.com/flutter/flutter/issues/82873
> suppress output from intentionally failing tests

- .ci.yaml
For https://github.com/flutter/infra/pull/465 and https://flutter-review.googlesource.com/c/recipes/+/14040
> Add Unopt builders to ci config

- ci/licenses_golden/licenses_flutter
- shell/platform/darwin/macos/BUILD.gn
- shell/platform/darwin/macos/framework/Source/FlutterBackingStoreData.h
- shell/platform/darwin/macos/framework/Source/FlutterBackingStoreData.mm
- shell/platform/darwin/macos/framework/Source/FlutterCompositor.h
- shell/platform/darwin/macos/framework/Source/FlutterCompositor.mm
- shell/platform/darwin/macos/framework/Source/FlutterEngine.mm
- shell/platform/darwin/macos/framework/Source/FlutterEngineTest.mm
- shell/platform/darwin/macos/framework/Source/FlutterEngine_Internal.h
- shell/platform/darwin/macos/framework/Source/FlutterGLCompositor.h
- shell/platform/darwin/macos/framework/Source/FlutterGLCompositor.mm
- shell/platform/darwin/macos/framework/Source/FlutterMetalCompositor.h
- shell/platform/darwin/macos/framework/Source/FlutterMetalCompositor.mm
- shell/platform/darwin/macos/framework/Source/FlutterMetalCompositorUnittests.mm
- shell/platform/darwin/macos/framework/Source/fixtures/flutter_desktop_test.dart
This adds support for Metal compositing on macOS.
https://github.com/flutter/flutter/issues/81320
> Add support for compositing using Metal on macOS

- ci/licenses_golden/licenses_flutter
- fml/platform/android/jni_util.cc
- fml/platform/android/jni_util.h
- lib/ui/BUILD.gn
- lib/ui/dart_ui.cc
- lib/ui/fixtures/ui_test.dart
- lib/ui/semantics.dart
- lib/ui/semantics/semantics_node.h
- lib/ui/semantics/semantics_update_builder.cc
- lib/ui/semantics/semantics_update_builder.h
- lib/ui/semantics/semantics_update_builder_unittests.cc
- lib/ui/semantics/string_attribute.cc
- lib/ui/semantics/string_attribute.h
- lib/web_ui/lib/src/engine/semantics/semantics.dart
- lib/web_ui/lib/src/ui/semantics.dart
- shell/platform/android/io/flutter/embedding/engine/FlutterJNI.java
- shell/platform/android/io/flutter/view/AccessibilityBridge.java
- shell/platform/android/jni/jni_mock.h
- shell/platform/android/jni/platform_view_android_jni.h
- shell/platform/android/platform_view_android_delegate/platform_view_android_delegate.cc
- shell/platform/android/platform_view_android_delegate/platform_view_android_delegate_unittests.cc
- shell/platform/android/platform_view_android_jni_impl.cc
- shell/platform/android/platform_view_android_jni_impl.h
- shell/platform/android/test/io/flutter/view/AccessibilityBridgeTest.java
- shell/platform/darwin/ios/framework/Source/SemanticsObject.h
- shell/platform/darwin/ios/framework/Source/SemanticsObject.mm
- shell/platform/darwin/ios/framework/Source/SemanticsObjectTest.mm
The previous PR was reverted due to post submit failure and is now fixed. There is no change from previous PR
related https://github.com/flutter/flutter/issues/79318 …
> Reland "Add API to the engine to support attributed text (#25373)"

- lib/ui/painting.dart
> Add the images for TileMode.decal

- DEPS
To pick up https://github.com/flutter/buildroot/pull/459
> Roll buildroot to 91b3d1f3a878a6d6ce0749a233d5d467c4daaf41

- lib/web_ui/lib/src/engine/navigation/history.dart
Adds documentation requested in https://github.com/flutter/engine/pull/26456#discussion_r643387250 …
> Docuements the new flag in BrowserHistory.setRouteName

- lib/web_ui/lib/src/engine/text_editing/text_editing.dart
- lib/web_ui/test/text_editing_test.dart
fixes https://github.com/flutter/flutter/issues/83618
> fix a LateInitializationError

- lib/web_ui/lib/src/engine/canvaskit/embedded_views.dart
- lib/web_ui/lib/src/engine/canvaskit/surface_factory.dart
- lib/web_ui/test/canvaskit/common.dart
- lib/web_ui/test/engine/surface/path/path_iterator_test.dart
- lib/web_ui/test/engine/surface/path/path_winding_test.dart
- lib/web_ui/test/path_test.dart
In each library where an import is removed, the library uses some elements
provided by the import, BUT there is another import which provides all of the
same elements, and at least one more which the library uses.
In this change, we remove the imports which can be simply removed in favor of
the other already present imports.
See https://github.com/dart-lang/sdk/issues/44569 for more information.
https://github.com/flutter/flutter/issues/74381 is _improved_ by this issue. Not fixed.
[Contributor …
> Remove "unnecessary" imports.

- DEPS
To pick up https://github.com/flutter/buildroot/pull/460
> Roll buildroot to 823808de422a8912bcec8a06f548da96d72cc682

- DEPS
This reverts commit d03c3f66103826f13cf8560a0c6380adac0e1e72.
> Revert "Roll Fuchsia Mac SDK from e0WQ49xxD... to p4LZtOVnJ... (#26632)"

- shell/common/skia_event_tracer_impl.cc
Fixes https://github.com/flutter/flutter/issues/83835
> Add a filterKey argument to Skia shader trace events

- shell/common/switches.cc
See https://github.com/flutter/flutter/issues/78500
> Enable Skia shader trace events by default

- .ci.yaml
- DEPS
- ci/licenses_golden/licenses_skia
Cherrypick skia to 7391511f7be3
> Cherrypick skia to 7391511f7be3

- lib/web_ui/dev/test_platform.dart
- lib/web_ui/dev/test_runner.dart
Several fixes for the test runner in `felt`:
- Tell `dart2js` to compile straight into the `build/` directory instead of compiles into the source tree, then moving the files.
- Remove obsolete Dart 1 features from `BrowserPlatform`:
- remove `pub serve` features.
- replace "secret" URL prefix with file handlers that don't allow serving files outside the sources and pubspec dependencies.
- remove support for `/packages/` directory
- Teach the shelf server to serve all the necessary files needed for debugging
> [web] test runner fixes: build, sourcemaps, Dart 1-isms

- lib/web_ui/dev/browser.dart
- lib/web_ui/pubspec.yaml
- lib/web_ui/test/text_editing_test.dart
- web_sdk/web_engine_tester/pubspec.yaml
- Make text_editing_test.dart null-safe.
- Upgrade `test` dependency (the old version had a NNBD bug that sometimes breaks stack traces in failing tests)
> [web] text_editing_test.dart nnbd; bump test dep

- lib/web_ui/test/canvaskit/vertices_test.dart
- lib/web_ui/test/engine/image/html_image_codec_test.dart
- lib/web_ui/test/engine/semantics/accessibility_test.dart
- lib/web_ui/test/engine/semantics/semantics_test.dart
- lib/web_ui/test/engine/services/serialization_test.dart
- lib/web_ui/test/engine/surface/frame_timings_test.dart
- lib/web_ui/test/engine/surface/platform_view_test.dart
- lib/web_ui/test/engine/surface/shaders/normalized_gradient_test.dart
- lib/web_ui/test/engine/surface/shaders/shader_builder_test.dart
- lib/web_ui/test/golden_tests/engine/canvas_draw_image_golden_test.dart
- lib/web_ui/test/golden_tests/engine/canvas_rect_golden_test.dart
- lib/web_ui/test/golden_tests/engine/canvas_rrect_golden_test.dart
- lib/web_ui/test/golden_tests/engine/canvas_stroke_joins_golden_test.dart
- lib/web_ui/test/golden_tests/engine/canvas_stroke_rects_golden_test.dart
- lib/web_ui/test/golden_tests/engine/canvas_winding_rule_test.dart
- lib/web_ui/test/golden_tests/engine/clip_op_golden_test.dart
- lib/web_ui/test/golden_tests/engine/conic_golden_test.dart
- lib/web_ui/test/golden_tests/engine/shadow_golden_test.dart
- lib/web_ui/test/text/font_collection_test.dart
- lib/web_ui/test/text/font_loading_test.dart
Migrate more web tests to null safety.
> [web] more null-safe tests

- ci/builders/mac_ios_engine.json
- ci/builders/mac_ios_engine_profile.json
- ci/builders/mac_ios_engine_release.json
These files will be used to describe builds as builders, testers, and
generators. They will be used by the engine recipe v2 which will do
automatic sharding to sub-builds.
Bug: https://github.com/flutter/flutter/issues/84462
[CLA]: …
> Configuration files to describe engine builds.

- lib/web_ui/lib/src/engine/picture.dart
- lib/web_ui/test/canvaskit/image_test.dart
- lib/web_ui/test/engine/image_to_byte_data_test.dart
- lib/web_ui/test/engine/pointer_binding_test.dart
- lib/web_ui/test/engine/recording_canvas_test.dart
- lib/web_ui/test/engine/surface/scene_builder_test.dart
- lib/web_ui/test/engine/surface/surface_test.dart
- lib/web_ui/test/engine/window_test.dart
- lib/web_ui/test/golden_tests/engine/canvas_paragraph/general_test.dart
- lib/web_ui/test/golden_tests/engine/compositing_golden_test.dart
- lib/web_ui/test/golden_tests/engine/gradient_golden_test.dart
- lib/web_ui/test/golden_tests/engine/multiline_text_clipping_golden_test.dart
- lib/web_ui/test/golden_tests/engine/path_to_svg_golden_test.dart
- lib/web_ui/test/golden_tests/engine/recording_canvas_golden_test.dart
- lib/web_ui/test/golden_tests/engine/scuba.dart
- lib/web_ui/test/golden_tests/engine/text_overflow_golden_test.dart
- lib/web_ui/test/golden_tests/engine/text_style_golden_test.dart
- lib/web_ui/test/text/measurement_test.dart
- lib/web_ui/test/text/word_breaker_test.dart
- lib/web_ui/test/text_test.dart
- lib/web_ui/tool/unicode_sync_script.dart
Migrate remaining tests to null safety
> [web] last batch of test null safety

- lib/web_ui/pubspec.yaml
- web_sdk/pubspec.yaml
- web_sdk/sdk_rewriter.dart
- web_sdk/test/api_conform_test.dart
- web_sdk/web_engine_tester/lib/golden_tester.dart
- web_sdk/web_engine_tester/pubspec.yaml
- web_sdk/web_test_utils/pubspec.yaml
Migrate the rest of web_sdk code to null safety and synchronize the Dart SDK version constraints for all web code.
> [web] migrate web_sdk to null safety

- flow/layers/container_layer.cc
- flow/layers/container_layer.h
- flow/layers/layer.h
Fixes https://github.com/flutter/flutter/issues/84564 …
> Make Layer::AssignOldLayer non virtual

- lib/spirv/lib/spirv.dart
- lib/spirv/lib/src/constants.dart
- lib/spirv/lib/src/transpiler.dart
- lib/spirv/lib/src/types.dart
- lib/spirv/pubspec.yaml
- lib/spirv/test/exception_shaders/assemble.py
- testing/dart/spirv_exception_test.dart
Part of an effort to migrate all tests in this repo to nnbd
> Migrate spirv to nnbd

- lib/web_ui/lib/src/engine/platform_dispatcher.dart
Fixes https://github.com/flutter/flutter/issues/84524
> Fix JSON map type declaration for SystemChrome.setApplicationSwitcherDescription arguments

- shell/platform/linux/fl_text_input_plugin.cc
`TextInputType.none` makes it possible to disable the virtual keyboard for certain TextFields, and lays the foundations for custom in-app virtual keyboards (flutter/flutter#76072).
Ref: flutter/flutter#83567
[CLA]: …
> Linux: add support for TextInputType.none

- tools/fuchsia/copy_debug_symbols.py
Per gn documentation, the output timestamp can remain the same if all outputs remain the same, resulting in large time savings since dependent targets don't need to be rebuilt.
See: https://gn.googlesource.com/gn/+/HEAD/docs/reference.md#target-declarations-action_declare-a-target-that-runs-a-script-a-single-time-outputs
Currently, `copy_debug_symbols.py` updates timestamps unconditionally, resulting in slower incremental and no-op builds.
We change its current behavior to not update the timestamps if the debug symbols will not change.
Local testing indicates around a `20s` improvement for no-op and incremental builds:
- Control: http://go/paste/4800062489100288
- Experiment: http://go/paste/5727928869453824
See https://fxbug.dev/79001.
CC: @naudzghebre
> [build] Speed up incremental & no-op builds.

- testing/run_tests.py
Reverts #26812
Reland changes to scripts after https://flutter-review.googlesource.com/c/recipes/+/14760 has landed.
> Remove gn. ninja commands from test runner.

- ci/analyze.sh
Reland of https://github.com/flutter/engine/pull/26752
> Remove analyze script

- lib/ui/semantics/semantics_node.h
- shell/platform/darwin/ios/framework/Source/SemanticsObject.h
- shell/platform/darwin/ios/framework/Source/SemanticsObject.mm
- shell/platform/darwin/ios/framework/Source/SemanticsObjectTest.mm
- shell/platform/darwin/ios/framework/Source/accessibility_bridge.mm
This reverts commit 53e4dcf1bc582ca72754904a12b5738e8f382b90.
Internal test failure …
> Revert "Issues/80711 reland (#26813)"

- .cirrus.yml
Issue: https://github.com/flutter/flutter/issues/84667
> Update cirrus gcloud credentials

- tools/const_finder/lib/const_finder.dart
- tools/const_finder/pubspec.yaml
- tools/const_finder/test/const_finder_test.dart
- tools/const_finder/test/fixtures/lib/consts.dart
- tools/const_finder/test/fixtures/lib/consts_and_non.dart
- tools/const_finder/test/fixtures/pkg/package.dart
Migrates const finder to null safety. Also fixes a couple analysis issues.
> Const finder NNBD

- tools/luci/build.py
Small fixes to the script added in https://github.com/flutter/engine/pull/26889 that became apparent only when actually trying to trigger a rebuild.
> Fix tools/luci/build.py script

- fml/BUILD.gn
- fml/backtrace.cc
- fml/paths.cc
- fml/paths.h
- fml/platform/android/paths_android.cc
- fml/platform/darwin/paths_darwin.mm
- fml/platform/fuchsia/paths_fuchsia.cc
- fml/platform/linux/paths_linux.cc
- fml/platform/win/paths_win.cc
See https://github.com/flutter/flutter/issues/83286
> Symbolize crash backtraces using the Abseil debugging library

- DEPS
- tools/fuchsia/copy_debug_symbols.py
- tools/fuchsia/copy_path.py
- tools/fuchsia/gather_flutter_runner_artifacts.py
- tools/fuchsia/make_build_info.py
These scripts are failing when trying to use python3. These changes should be compatible with python2 and python3.
> Make fuchsia python scripts work with python3

- shell/common/rasterizer.cc
Fixes https://github.com/flutter/flutter/issues/83951
> Log an error in DoMakeRasterSnapshot if Skia can not create a GPU render target

- flow/diff_context.cc
- flow/diff_context.h
- flow/gl_context_switch_unittests.cc
- flow/paint_region.cc
- flow/paint_region.h
- flow/testing/diff_context_test.cc
- flow/testing/diff_context_test.h
> Add missing license headers

- tools/githooks/bin/main.dart
- tools/githooks/lib/src/pre_push_command.dart
- tools/githooks/pubspec.yaml
This PR also fixes a bug in which the exit code of the process on failure wasn't non-zero.
> Use package:clang_tidy in git pre-push hook

- .ci.yaml
> Update ci.yaml documentation link

- lib/web_ui/dev/build.dart
- lib/web_ui/dev/felt.dart
- lib/web_ui/dev/macos_info.dart
- lib/web_ui/dev/test_runner.dart
- lib/web_ui/dev/utils.dart
- lib/web_ui/dev/watcher.dart
* make processes interruptible
* make --watch compatible with Windows:
* add 'q' shortcut to quit (Ctrl + C on Windows is wonky)
* use package:path for cross-platform path processing
> [web] felt --watch fixes

- DEPS
Update Fuchsia roll to include latest fidlc flag changes.
> Roll Fuchsia from 275038b8be7196927b0f71770701f3c2c3744860 to 86a2f5264f8dc496dccdd4060e4bad4c33eef552

- lib/web_ui/lib/src/engine.dart
- lib/web_ui/lib/src/engine/assets.dart
- lib/web_ui/lib/src/engine/host_node.dart
- lib/web_ui/lib/src/engine/platform_dispatcher.dart
- lib/web_ui/lib/src/engine/semantics/text_field.dart
- lib/web_ui/lib/src/engine/text/font_collection.dart
- lib/web_ui/lib/src/engine/text_editing/autofill_hint.dart
- lib/web_ui/lib/src/engine/text_editing/input_type.dart
- lib/web_ui/lib/src/engine/text_editing/text_capitalization.dart
- lib/web_ui/lib/src/engine/text_editing/text_editing.dart
- lib/web_ui/test/text_editing_test.dart
Make text editing parts into libs.
The PR is a little large, but it's mostly making private properties public so they could be accessed outside of their files.
> [web] Librarify text editing files

- lib/web_ui/test/canvaskit/canvas_golden_test.dart
For https://github.com/flutter/flutter/issues/85700
> Skip failing web golden tests

- shell/platform/darwin/graphics/FlutterDarwinContextMetal.mm
Update include path.
[Discord]: …
> Update include path in FlutterDarwinContextMetal.mm

- ci/licenses_golden/licenses_flutter
- shell/platform/android/BUILD.gn
- shell/platform/android/io/flutter/util/ViewUtils.java
- shell/platform/android/io/flutter/view/AccessibilityBridge.java
- shell/platform/android/io/flutter/view/FlutterView.java
- shell/platform/android/test/io/flutter/util/ViewUtilsTest.java
- shell/platform/android/test/io/flutter/view/AccessibilityBridgeTest.java
fixes https://github.com/flutter/flutter/issues/67835 …
> Fixes inset padding in android accessibility bridge

- common/settings.h
> Revert "enable DisplayList by default"

- ci/licenses_golden/licenses_flutter
- lib/web_ui/lib/src/engine.dart
- lib/web_ui/lib/src/engine/browser_detection.dart
- lib/web_ui/lib/src/engine/dom_renderer.dart
- lib/web_ui/lib/src/engine/keyboard_binding.dart
- lib/web_ui/lib/src/engine/platform_dispatcher.dart
- lib/web_ui/lib/src/engine/semantics.dart
- lib/web_ui/lib/src/engine/semantics/accessibility.dart
- lib/web_ui/lib/src/engine/semantics/checkable.dart
- lib/web_ui/lib/src/engine/semantics/image.dart
- lib/web_ui/lib/src/engine/semantics/incrementable.dart
- lib/web_ui/lib/src/engine/semantics/label_and_value.dart
- lib/web_ui/lib/src/engine/semantics/live_region.dart
- lib/web_ui/lib/src/engine/semantics/scrollable.dart
- lib/web_ui/lib/src/engine/semantics/semantics.dart
- lib/web_ui/lib/src/engine/semantics/semantics_helper.dart
- lib/web_ui/lib/src/engine/semantics/tappable.dart
- lib/web_ui/lib/src/engine/semantics/text_field.dart
- lib/web_ui/lib/src/engine/text_editing/text_editing.dart
- lib/web_ui/lib/src/engine/util.dart
- lib/web_ui/test/engine/semantics/accessibility_test.dart
- lib/web_ui/test/engine/semantics/semantics_helper_test.dart
- lib/web_ui/test/engine/semantics/semantics_test.dart
- lib/web_ui/test/engine/semantics/semantics_tester.dart
Make semantics part files into libs.
> [web] Librarify semantics files

- common/settings.h
> Revert "(Reland) enable DisplayList mechanism over SkPicture by default"

- shell/platform/android/io/flutter/plugin/platform/PlatformPlugin.java
- shell/platform/android/test/io/flutter/plugin/platform/PlatformPluginTest.java
Android 12 introduces a toast message that appears when an app reads the content on the clipboard. Currently, whenever there is a `TextField` widget, the app reads from the clipboard passively to determine whether the clipboard is empty and whether the "Paste" button should be shown. To avoid unintended access, both the Flutter engine and the Flutter framework need to be updated to use the appropriate API to check whether the clipboard is empty.
Slightly breaking change: Previously, if the clipboard contains an empty string, `clipboardHasStrings` returns `false`, but Without actually accessing clipboard data (preferred behavior), it is not possible to distinguish between empty and non-empty string contents. 
This is a pre-requisite for fixing b/192897521 and flutter/flutter#74139
The …
> Avoid passive clipboard read on Android

- web_sdk/BUILD.gn
Uses correct extensions on Dart SDK executables.
> Fix prebuilt Dart SDK use on Windows

- lib/web_ui/lib/src/engine/canvaskit/canvaskit_api.dart
- lib/web_ui/lib/src/engine/canvaskit/painting.dart
- lib/web_ui/test/canvaskit/canvaskit_api_test.dart
Filter quality has been replaced by shaders and is a noop. It will be removed from Skia entirely.
> [web] remove no longer used setFilterQuality

- build/dart/rules.gni
- testing/scenario_app/lib/main.dart
- testing/scenario_app/lib/src/animated_color_square.dart
- testing/scenario_app/lib/src/bogus_font_text.dart
- testing/scenario_app/lib/src/channel_util.dart
- testing/scenario_app/lib/src/initial_route_reply.dart
- testing/scenario_app/lib/src/locale_initialization.dart
- testing/scenario_app/lib/src/platform_echo_mixin.dart
- testing/scenario_app/lib/src/platform_view.dart
- testing/scenario_app/lib/src/poppable_screen.dart
- testing/scenario_app/lib/src/scenario.dart
- testing/scenario_app/lib/src/scenarios.dart
- testing/scenario_app/lib/src/send_text_focus_semantics.dart
- testing/scenario_app/lib/src/touches_scenario.dart
- testing/scenario_app/pubspec.yaml
Reverts flutter/engine#27362
Analysis failures: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Unopt/636/overview
> Revert "NNBD migration for scenario_app"

- .ci.yaml
This makes it possible to generated the luci config builders from this file.
https://github.com/flutter/flutter/issues/84998
Related infra CL: https://flutter-review.googlesource.com/c/infra/+/15360
> [ci.yaml] Add platform_args, properties, recipe, and timeout information

- build/dart/rules.gni
- testing/scenario_app/lib/main.dart
- testing/scenario_app/lib/src/animated_color_square.dart
- testing/scenario_app/lib/src/bogus_font_text.dart
- testing/scenario_app/lib/src/channel_util.dart
- testing/scenario_app/lib/src/initial_route_reply.dart
- testing/scenario_app/lib/src/locale_initialization.dart
- testing/scenario_app/lib/src/platform_echo_mixin.dart
- testing/scenario_app/lib/src/platform_view.dart
- testing/scenario_app/lib/src/poppable_screen.dart
- testing/scenario_app/lib/src/scenario.dart
- testing/scenario_app/lib/src/scenarios.dart
- testing/scenario_app/lib/src/send_text_focus_semantics.dart
- testing/scenario_app/lib/src/touches_scenario.dart
- testing/scenario_app/pubspec.yaml
Changes from last time in 7ea096d
Analysis passes locally now.
This was missed last time because presubmits failed to run, and I failed to notice how many failed to run before submitting.
> Scenario nnbd

- .ci.yaml
https://github.com/flutter/flutter/issues/86427
> [ci.yaml] Add Linux Android Scenarios postsubmit

- .ci.yaml
https://github.com/flutter/flutter/issues/84998
https://github.com/flutter/flutter/issues/85491
In the future, it would allow changes like https://flutter-review.googlesource.com/c/infra/+/15101 to be tracked in the engine repo.
> [ci.yaml] Add xcode property to ci.yaml

- .ci.yaml
https://github.com/flutter/flutter/issues/86427
> [ci.yaml] Mark Linux Android Scenarios as flaky

- shell/platform/windows/window_win32.cc
- shell/platform/windows/window_win32_unittests.cc
Fixes https://github.com/flutter/flutter/issues/86217 …
> Fix duplicated keys with CONTROL key toggled

- lib/web_ui/dev/watcher.dart
Adds a doc comment on `PipelineStatus`.
> [web] dartdoc for PipelineStatus

- flow/layers/picture_layer.cc
- flow/layers/picture_layer.h
- flow/layers/picture_layer_unittests.cc
- flow/skia_gpu_object.h
- flow/skia_gpu_object_unittests.cc
- lib/ui/painting/gradient.h
- lib/ui/painting/image.cc
- lib/ui/painting/image.h
- lib/ui/painting/image_decoder.cc
- lib/ui/painting/image_decoder_unittests.cc
- lib/ui/painting/image_shader.cc
- lib/ui/painting/picture.cc
- lib/ui/painting/picture.h
- lib/ui/painting/single_frame_codec.cc
This will reduce confusion with sk_sp::get() which returns a raw pointer
> Rename SkiaGPUObject::get() to skia_object()

- .ci.yaml
https://github.com/flutter/flutter/issues/85803
> [ci.yaml] Fix osx_sdk cache name

- tools/python/python3_action.gni
- tools/python/run_python3_action.py
Ninja runs `action` scripts using the default python interpretter, and
most flutter build scripts that use python currently require python2. In
order to support python3 scripts as well, the `python3_action` invokes a
wrapper python2-based script via GN `action` target, and the wrapper
invokes the python3 interpretter with the given script.
This new target is required to support flutter/engine#26880, but is
broken out to a separate PR (by request) to support other more immediate
use cases.
Regarding flutter/flutter#53002: Note that this is a *temporary workaround* for python3 scripts, while python2 is still required. Once python3 is the default, the `python3_action` targets can be changed to simply `action`, and …
> Adds python3_action GN target

- shell/platform/darwin/macos/framework/Source/FlutterEngineTest.mm
Backfill tests for https://github.com/flutter/engine/pull/21789
https://github.com/flutter/flutter/issues/32986
> Add a unit test for dart entrypoint args on macOS

- shell/platform/embedder/embedder.cc
Fixes https://github.com/flutter/flutter/issues/86600 …
> MacOS: Fix external texture not working in OpenGL mode

- shell/platform/darwin/macos/framework/Source/FlutterSurfaceManager.h
- shell/platform/darwin/macos/framework/Source/FlutterSurfaceManager.mm
Fixes https://github.com/flutter/flutter/issues/85971 …
> MacOS: Release backbuffer surface when idle

- shell/platform/embedder/fixtures/main.dart
- shell/platform/embedder/tests/embedder_unittests.cc
Add unit test case to reproduce the shutdown crash demonstrated in
https://github.com/dart-lang/sdk/issues/46275
> Add embedder unit test that reproduces https://github.com/dart-lang/sdk/issues/46275

- .ci.yaml
https://github.com/flutter/flutter/issues/85803
This is for https://flutter-review.googlesource.com/c/infra/+/15660 to minimize the diff
> [ci.yaml] Fix timeouts + properties

- shell/platform/fuchsia/flutter/engine.cc
- shell/platform/fuchsia/flutter/engine.h
This is follow-up clean-up for #26193
> Replace array<fml::Thread, 3> with ThreadHost.

- .ci.yaml
https://github.com/flutter/flutter/issues/85803
> [ci.yaml] JSON encode subshards key

- shell/platform/fuchsia/dart_runner/meta/common.shard.cml
- shell/platform/fuchsia/dart_runner/meta/dart_aot_product_runner.cmx
- shell/platform/fuchsia/dart_runner/meta/dart_aot_runner.cmx
- shell/platform/fuchsia/dart_runner/meta/dart_jit_product_runner.cmx
- shell/platform/fuchsia/dart_runner/meta/dart_jit_runner.cmx
- shell/platform/fuchsia/flutter/meta/flutter_aot_product_runner.cmx
- shell/platform/fuchsia/flutter/meta/flutter_aot_runner.cmx
- shell/platform/fuchsia/flutter/meta/flutter_jit_product_runner.cmx
- shell/platform/fuchsia/flutter/meta/flutter_jit_runner.cmx
cmx: $FUCHSIA_DIR/scripts/style/json-fmt.py
cml: $FUCHSIA_DIR/out/default/host-tools/formatjson5 --replace
> Reformat manifests

- shell/platform/fuchsia/dart_runner/meta/common.shard.cml
- shell/platform/fuchsia/dart_runner/meta/dart_aot_product_runner.cmx
- shell/platform/fuchsia/dart_runner/meta/dart_aot_runner.cmx
- shell/platform/fuchsia/dart_runner/meta/dart_jit_product_runner.cmx
- shell/platform/fuchsia/dart_runner/meta/dart_jit_runner.cmx
- shell/platform/fuchsia/flutter/meta/flutter_aot_product_runner.cmx
- shell/platform/fuchsia/flutter/meta/flutter_aot_runner.cmx
- shell/platform/fuchsia/flutter/meta/flutter_jit_product_runner.cmx
- shell/platform/fuchsia/flutter/meta/flutter_jit_runner.cmx
fuchsia.net.NameLookup is transitioning to fuchsia.net.name.Lookup.
@zanderso
> Add fuchsia.net.name.Lookup

- .ci.yaml
https://github.com/flutter/flutter/issues/86566
> [flutter_release] Cherry-pick tip of tree ci.yaml changes to beta

- ci/licenses_golden/licenses_flutter
- shell/platform/darwin/macos/BUILD.gn
- shell/platform/darwin/macos/framework/Source/FlutterFrameBufferProviderUnittests.mm
Backfill unit test for https://github.com/flutter/engine/pull/22656
> Add a unit test for FlutterFrameBufferProvider

- shell/platform/fuchsia/flutter/engine.cc
- shell/platform/fuchsia/flutter/vulkan_surface.cc
- vulkan/vulkan_interface.h
Improved logging and error handling for boot lockup debugging
> [fuchsia] boot lockup debugging improvements

- .ci.yaml
Also removes an unused generic timeout
https://github.com/flutter/flutter/issues/85803
> [ci.yaml] Extend windows host engine timeout

- build/generate_coverage.py
- testing/run_tests.py
This modifies the run_tests.py and generate_coverage.py scripts to allow us to run the engine unittests with coverage reports enabled. In particular, passing `--coverage` to `run_tests.py` will now run the engine unittests through `generate_coverage.py` and output the HTML files in a directory called `coverage` in the build output directory (e.g. `host_debug_unopt`).
https://github.com/flutter/flutter/issues/86385
> Update test scripts for coverage

- .ci.yaml
https://github.com/flutter/flutter/issues/86892
After this lands, it can populate the LUCI configs with the current expected info. Afterwards, we can look at upgrading to JDK 11.
> [ci.yaml] Explicitly define open jdk dependency

- DEPS
To pick up https://github.com/flutter/buildroot/pull/486
> Roll buildroot to d28c48674b65936cf32063da51ef1445af82ac75

- lib/web_ui/lib/src/engine/html/path/path_utils.dart
- lib/web_ui/lib/src/engine/html/shaders/vertex_shaders.dart
- lib/web_ui/lib/src/engine/text/word_breaker.dart
- lib/web_ui/lib/src/ui/hash_codes.dart
https://github.com/dart-lang/sdk/issues/46663
> Prepare for updated avoid_classes_with_only_static_members lint

- .ci.yaml
* Backported some .ci.yaml fixes
* Removed all non Fuchsia builders
https://github.com/flutter/flutter/issues/87075
> [flutter_release] Fuchsia f5 release branch

- flow/frame_timings.cc
- flow/frame_timings_recorder_unittests.cc
This might be a solution to https://github.com/flutter/flutter/issues/87137 but further monitoring will be required to verify that assessment.
In the meantime, these changes represent actual bugs in the code.
> Frame timings clone fix

- .ci.yaml
- testing/fuchsia/test_suites.yaml
This also triggers our CI builders.
See [this](https://docs.google.com/document/d/1ydFabRGxvaTKHUuao_h2ut2UUq4Xu6LVCbzHw6L6a6w/edit?resourcekey=0-wcfOoZobWLQj1LH6_V-sdQ#) for more context.
> Update infra configuration files.

- DEPS
This updates all buildroot Python scripts that were still on Python 2 to
Python 3. …
> Roll buildroot to 6cee685b6bed193471aa7eaffae1fdc56cef0060

- ci/builders/windows_android_aot_engine.json
This is a configuration required to separate builds from tests in the
engine repo. …
> Add configuration for windows android aot.

- lib/web_ui/lib/src/ui/platform_dispatcher.dart
- lib/web_ui/test/gesture_settings_test.dart
...And port the mobile tests to web.
Part of https://github.com/flutter/flutter/issues/87322
> Fix nullability of GestureSettings on ViewConfig

- shell/platform/windows/system_utils_winuwp.cc
This PR fixes a typo from #27311.
https://github.com/flutter/engine/pull/27311#discussion_r675960603
> Fix a typo in https://github.com/flutter/engine/pull/27311

- lib/ui/text.dart
This just fixes a couple of minor analyzer errors in the sample code so that they won't break the build when I fix the analyzer in the flutter repo.
> Fix sample analyzer errors in text.dart

- ci/builders/web_engine.json
This is part of the implementation of build/test separation. …
> Engine build configuration for web engine.

- DEPS
https://github.com/flutter/buildroot/pull/498
> Bump buildroot version

- ci/builders/mac_ios_engine.json
- ci/builders/mac_ios_engine_profile.json
- ci/builders/mac_ios_engine_release.json
- ci/builders/windows_host_engine.json
Web engine required more complex generator configurations which forced
us change the generator values from list to a dict. …
> Update builder configurations to apply the new generators format.

- tools/gn
Reverts flutter/engine#27975
Reverting for https://github.com/flutter/flutter/issues/88205
/cc @a-siva
> Revert "Enable Dart compressed pointers for 64-bit mobile targets"

- DEPS
- ci/licenses_golden/tool_signature
- tools/licenses/lib/main.dart
> Revert "Add bundletool to DEPS and remove outdated header comment"

- .ci.yaml
This allows us to run it on presubmit (first propagate the builder, then schedule it)
> [ci.yam] Enable roller dry on presubmit

- .ci.yaml
> Revert "[ci.yaml] Promote roller to blocking"

- lib/web_ui/dev/web_engine_analysis.sh
This is to minimize the number of environment variables being passed to
scripts from recipes. …
> Define WEB_UI_DIR using ENGINE_PATH.

- DEPS
Reverts flutter/engine#28200
For https://github.com/flutter/flutter/issues/88531
@arbreng
> Revert "Roll Fuchsia Mac SDK from 9xK8HkMEI... to EZSVwdQoz..."

- DEPS
- ci/licenses_golden/licenses_fuchsia
Reverts flutter/engine#28201
For https://github.com/flutter/flutter/issues/88531
@arbreng
> Revert "Roll Fuchsia Linux SDK from ZSqn1OAt7... to czYvw1Rk3..."

- DEPS
This eliminates use of third_party/gyp. …
> Roll buildroot to 53a65e1c400c29e14e1f3e59be7a3c7327b204ee

- testing/run_tests.py
Re: https://flutter-review.googlesource.com/c/recipes/+/16364
> Add supported platforms assert for `run_tests.py` suppression flag

- shell/platform/android/io/flutter/view/AccessibilityBridge.java
- shell/platform/android/test/io/flutter/view/AccessibilityBridgeTest.java
fixes https://github.com/flutter/flutter/issues/88587 …
> Makes empty scrollable not focusable in Talkback

- DEPS
- ci/licenses_golden/licenses_third_party
See https://github.com/flutter/engine/pull/27920
> Roll Wuffs to 0.3.0-beta.8

- DEPS
Retrying the rolls:
https://github.com/flutter/engine/pull/28183
https://github.com/flutter/engine/pull/28185
> Manual roll of Clang for Linux and Mac

- shell/platform/android/io/flutter/embedding/engine/systemchannels/TextInputChannel.java
- shell/platform/android/test/io/flutter/FlutterTestSuite.java
- shell/platform/android/test/io/flutter/embedding/engine/systemchannels/TextInputChannelTest.java
- tools/android_lint/project.xml
Fixes https://github.com/flutter/flutter/issues/88703
> Add missing result for the TextInput.setEditableSizeAndTransform method handler on Android

- tools/gn
Reverts flutter/engine#28388
Reverting for the failure noted in b/198357814
> Revert "Turn compressed pointers on Android for 64 bit architectures."

- shell/platform/fuchsia/dart_runner/meta/dart_aot_product_runner.cmx
- shell/platform/fuchsia/dart_runner/meta/dart_aot_runner.cmx
- shell/platform/fuchsia/dart_runner/meta/dart_jit_product_runner.cmx
- shell/platform/fuchsia/dart_runner/meta/dart_jit_runner.cmx
- shell/platform/fuchsia/flutter/meta/flutter_aot_product_runner.cmx
- shell/platform/fuchsia/flutter/meta/flutter_aot_runner.cmx
- shell/platform/fuchsia/flutter/meta/flutter_jit_product_runner.cmx
- shell/platform/fuchsia/flutter/meta/flutter_jit_runner.cmx
This protocol is replaced with fuchsia.net.name.Lookup.
@arbreng
> Remove fuchsia.net.NameLookup

- fml/memory/weak_ptr.h
Fixes https://github.com/flutter/flutter/issues/89099
> Correct outdated weak_ptr docs

- ci/licenses_golden/licenses_flutter
- shell/platform/darwin/ios/BUILD.gn
- shell/platform/darwin/ios/framework/Source/FlutterSemanticsScrollView.h
- shell/platform/darwin/ios/framework/Source/FlutterSemanticsScrollView.mm
- shell/platform/darwin/ios/framework/Source/SemanticsObject.h
- shell/platform/darwin/ios/framework/Source/SemanticsObject.mm
- shell/platform/darwin/ios/framework/Source/SemanticsObjectTest.mm
- shell/platform/darwin/ios/framework/Source/accessibility_bridge.mm
- shell/platform/darwin/ios/framework/Source/accessibility_bridge_test.mm
fixes https://github.com/flutter/flutter/issues/89613 …
> Fixes accessibility issue that bridge fails to clean up FlutterScrollableSemanticsObject

- lib/web_ui/lib/src/engine/canvaskit/embedded_views.dart
Fixes https://github.com/flutter/flutter/issues/90013 …
> [canvaskit] Don't assign overlays when overlays are disabled

- flow/display_list_canvas_unittests.cc
This should fix the problems with rolling in the latest Skia fixes as seen in https://github.com/flutter/engine/pull/28592
> prepare drawPoints MaskFilter test for Skia bug fix

- DEPS
- ci/licenses_golden/licenses_third_party
> Cherry-pick #28230 to fuchsia_f6

- tools/download_dart_sdk.py
The multiprocessing package relies on the win32 `WaitForMultipleObjects`
call, which supports waiting on a maximum of MAXIMUM_WAIT_OBJECTS
(defined by Windows to be 64) handles, processes in this case. To avoid
hitting this, we limit ourselves to 60 handles (since there are a couple
extra processes launched for the queue reader and thread wakeup reader).
When left unspecified, the multiprocessing module defaults this value to
`os.cpu_count()`, so this error is triggered only on machines with > 60
cores.
See: https://bugs.python.org/issue2690
Bug: https://github.com/flutter/flutter/issues/90085 …
> Limit download_dart_sdk task pool size on Windows

- lib/web_ui/test/channel_buffers_test.dart
- shell/testing/observatory/launcher.dart
- testing/dart/channel_buffers_test.dart
We would like to land https://dart-review.googlesource.com/c/sdk/+/190360, and need to fix existing violations.
> Fix UNNECESSARY_TYPE_CHECK_TRUE

- tools/fuchsia/devshell/serve.sh
> [fuchsia] Replace amberctl in serve.sh with pkgctl

- examples/glfw/main.dart
Gave it a run today and noticed it was broken.
> Fix GLFW embedder example for current flutter libs/Dart SDK

- .ci.yaml
Fixes https://github.com/flutter/flutter/issues/90220
> Use Gradle cache

- lib/web_ui/lib/src/engine/canvaskit/surface_factory.dart
Fixes the following lints triggered by flutter/engine#28675:
```
Analyzing web_ui...
info - lib/src/engine/canvaskit/surface_factory.dart:8:8 - The import of '../util.dart' is unnecessary as all of the used elements are also provided by the import of '../../engine.dart'. Try removing the import directive. - unnecessary_import
info - lib/src/engine/canvaskit/surface_factory.dart:9:8 - The import of 'embedded_views.dart' is unnecessary as all of the used elements are also provided by the import of '../../engine.dart'.  Try removing the import directive. - unnecessary_import
info - lib/src/engine/canvaskit/surface_factory.dart:10:8 - The import of 'surface.dart' is unnecessary as all of the used elements are also provided by the import of '../../engine.dart'. Try removing the import …
```
> Eliminate unnecessary canvaskit imports

- shell/platform/android/io/flutter/embedding/engine/dart/DartExecutor.java
Fixes https://github.com/flutter/flutter/issues/90182
> Make DartExecutor.IsolateServiceIdListener public

- shell/platform/fuchsia/flutter/BUILD.gn
- shell/platform/fuchsia/flutter/engine.cc
- shell/platform/fuchsia/flutter/engine.h
- shell/platform/fuchsia/flutter/meta/flutter_aot_product_runner.cmx
- shell/platform/fuchsia/flutter/meta/flutter_aot_runner.cmx
- shell/platform/fuchsia/flutter/meta/flutter_jit_product_runner.cmx
- shell/platform/fuchsia/flutter/meta/flutter_jit_runner.cmx
Tested by using the `fx mem` command to verify that the state changes behave properly. https://pastebin.com/ttAWbLeQ
Fixes fxb/85052
> [Fuchsia] Notify Shell when memory becomes low.

- DEPS
- ci/licenses_golden/licenses_third_party
- third_party/accessibility/BUILD.gn
Please see the linked issue for details.
Fixes: https://github.com/flutter/flutter/issues/90146
Note, originally there was a problem with commit 3f443830bd52d3aa5fab3c1aa2b6d0848bb5039d.  Trying to fix that I discovered a slew of issues in `gn` and `//flutter/third_party`, which are now fixed and the resulting change to `flutter/engine` is below:
- Updates gn to commit 0153d369bbccc908f4da4993b1ba82728055926a to take
in the fix at https://gn-review.googlesource.com/c/gn/+/12220 which
prevented the correct treatment of target refactoring.
- Updates ICU to commit 2b50fa94b07b601293d7c1f791e853bba8ffbb84 to
correct the target naming, which should now work thanks to the
previous update to gn.  See
https://gn-review.googlesource.com/c/gn/+/12220 for the details of
that bug.
- Fixed the …
> [icu] Update the ICU library to 2b50fa94b07b601293d7c1f791e853bba8ffbb84

- tools/fuchsia/devshell/branch_from_fuchsia.sh
- tools/fuchsia/devshell/lib/vars.sh
- tools/fuchsia/devshell/sync_to_fuchsia.sh
Example usage:
```
cd $ENGINE_DIR/flutter
$ tools/fuchsia/devshell/sync_to_fuchsia.sh
$ tools/fuchsia/devshell/branch_from_fuchsia.sh my_branch
```
> [fuchsia] Small shell scripts for workflow.

- .ci.yaml
Point to Cocoon's main branch, and enable Linux Benchmarks to also run on main
https://github.com/flutter/flutter/issues/90476
> [ci.yaml] add main references

- DEPS
- ci/licenses_golden/licenses_fuchsia
For https://github.com/flutter/flutter/issues/91049
> Revert Fuchsia SDK to version from 9/23

- ci/builders/mac_ios_engine.json
- ci/builders/mac_ios_engine_profile.json
- ci/builders/mac_ios_engine_release.json
- ci/builders/web_engine.json
- ci/builders/windows_android_aot_engine.json
- ci/builders/windows_host_engine.json
This is adding a top level builds list to differentiate it from remote
tests. …
> Update builder configs.

- shell/platform/fuchsia/dart_runner/dart_component_controller_v2.cc
- shell/platform/fuchsia/dart_runner/dart_runner.cc
- shell/platform/fuchsia/dart_runner/dart_runner.h
Bug: fxb/79871
Implements the ComponentRunner protocol for the Dart runner, making the Dart runner compatible with CF v2.
> [fuchsia] Dart Runner for CF v2 components.

- .ci.yaml
- DEPS
- ci/licenses_golden/licenses_fuchsia
Cherry pick to reland internal roll, see b/201674786
> Cherry-pick Fuchsia revert

- shell/platform/fuchsia/flutter/flatland_connection.cc
- shell/platform/fuchsia/flutter/flatland_connection.h
- shell/platform/fuchsia/flutter/tests/flatland_connection_unittests.cc
Fixes some racy behavior in FlatlandConnection. Regression tests included in change
This PR includes a number of changes from other authors that havent landed yet. Once those changes land I will rebase this PR on top of them.
> [fuchsia][flatland] Fix for AwaitVsync race

- .ci.yaml
CP a couple ci.yaml changes and trigger the builder to rebuild.
> Attempt to bump to Flutter 2.5 builders.

- .ci.yaml
This reverts commit 8630e52edf86751166fd2fc02712854787a48de2.
> Revert "Attempt to bump to Flutter 2.5 builders. (#29025)"

- lib/web_ui/dev/browser_lock.yaml
- lib/web_ui/dev/common.dart
> Roll Chrome to major version 96

- .ci.yaml
This also reverts commit 64a78fa9548b68c82be43d4999f94c1d0bb6ac62.
> Kick Builds

- shell/platform/fuchsia/flutter/integration_flutter_tests/BUILD.gn
> fuchsia: fix build

- tools/font-subset/main.cc
Reverts flutter/engine#29266
breaking Google version dependency b/204512325
> Revert "Update to match harfbuzz subsetting 3.0.0 api."

- shell/platform/fuchsia/dart_runner/BUILD.gn
- shell/platform/fuchsia/flutter/flutter_runner_fakes.h
Outdated Fuchsia layer cake concept. https://fuchsia.dev/fuchsia-src/contribute/open_projects/srcs/layer_cake_deprecation
> [fuchsia] Remove remaining references to Topaz.

- DEPS
- shell/platform/android/io/flutter/plugin/platform/PlatformPlugin.java
- shell/platform/android/test/io/flutter/plugin/platform/PlatformPluginTest.java
- shell/platform/android/test_runner/build.gradle
- tools/androidx/files.json
- tools/cipd/android_embedding_bundle/build.gradle
Relands https://github.com/flutter/engine/pull/29060
This PR requires to update the Bazel rules in g3 (@renyu FYI)
> Reland "Set system bar appearance using WindowInsetsController"

- shell/platform/darwin/ios/BUILD.gn
- shell/platform/darwin/ios/framework/Source/FlutterSemanticsScrollView.h
- shell/platform/darwin/ios/framework/Source/FlutterSemanticsScrollView.mm
- shell/platform/darwin/ios/framework/Source/SemanticsObject.mm
- shell/platform/darwin/ios/framework/Source/accessibility_bridge_test.mm
This fixes the crash part of https://github.com/flutter/flutter/issues/92853
Does not fix the focus getting trapped.
/cc @chunhtai fyi
> Fix invalid access of weakly owned ptr in iOS a11y bridge

- shell/platform/android/io/flutter/embedding/engine/dart/DartMessenger.java
- shell/platform/android/io/flutter/plugin/common/BinaryMessenger.java
- shell/platform/android/test/io/flutter/embedding/engine/dart/DartMessengerTest.java
fixes https://github.com/flutter/flutter/issues/92858 …
> Made DartMessenger use the injected executor service for executing message handlers

- shell/platform/darwin/ios/framework/Source/FlutterChannelKeyResponder.mm
> [iOS] Fixes press key message leaks

- shell/platform/embedder/embedder.cc
Several arrays pointers on semantics update objects were being passed as
the address of the 0th element; however, this is undefined behaviour in the
case where the array length is 0.
We already test for this in embedder_a11y_unittests.cc and the associated fixture:
https://github.com/flutter/engine/blob/58aa404da70f131637f387265b68f7949725c3a0/shell/platform/embedder/fixtures/main.dart#L182-L184
We didn't catch this since we don't currently run the embedder tests on
Windows. They will be re-enabled in a followup, which will fix
https://github.com/flutter/flutter/issues/36294.
Issue: flutter/flutter#93338 …
> Fix UB in semantics updates

- shell/platform/android/platform_view_android.cc
I forgot to remove this when I fixed the bug.
> Remove outdated TODO

- testing/fuchsia/meta/test_suite.cml
Adding the tests facets to this file since the ui_tests are not hermetic.
> Add test facets to test_suites.cml

- lib/spirv/README.md
The control flow bullet point was misleading to me. If I had not known before that `if`, `for`, etc. are unsupported, I might have read it as:
> aside from function calls and `return`, `if`, `while`, `for`, etc.
As in all of the listed keywords are exceptions - when in reality it is only `return` that is an exception.
Furthermore, there were some commas in line 31 that are not grammatically correct (afaic). Both of the commas are not allowed because the two clauses after the commas are **not** independent clauses from the one before. It is also not an Oxford comma because there are only two words in the series. …
> Improve SPIR-V README wording

- shell/platform/android/test/io/flutter/embedding/engine/dart/DartMessengerTest.java
Probably accidentally removed in #29377
[Discord]: …
> Add test annotation

- shell/platform/darwin/ios/framework/Source/SemanticsObject.h
- shell/platform/darwin/ios/framework/Source/SemanticsObject.mm
- shell/platform/darwin/ios/framework/Source/SemanticsObjectTest.mm
- shell/platform/darwin/ios/framework/Source/accessibility_bridge.mm
Cherry pick:
* https://github.com/flutter/engine/commit/0b3ac9431351b01b8770352dc4251e71cfde634e …
> Cherrypick of PR flutter/engine/pull/29531

- .github/workflows/mirror.yml
This is because now the default branch is main.
Bug: https://github.com/flutter/flutter/issues/90476 …
> Reverse the order of mirroring.

- .github/workflows/mirror.yml
Bug: https://github.com/flutter/flutter/issues/90476 …
> Reverse order of branch mirroring.

- shell/platform/linux/fl_gl_area.cc
- shell/platform/linux/fl_renderer_gl.cc
Acquire context reference at the correct time for FlGlArea.
- [] I listed at least one issue that this PR fixes in the description above.
- [] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on
> Acquire context reference at the correct time for FlGlArea.

- DEPS
This pulls in the updated `metrics_center` package that filters out extraneous fields in the benchmark `context`.
https://github.com/flutter/flutter/issues/93575
Tests are in the packages repo.
> Roll flutter_packages to a19eca7fe2660c71acf5928a275deda1da318c50

- shell/platform/fuchsia/flutter/flatland_platform_view.cc
- shell/platform/fuchsia/flutter/flatland_platform_view.h
- shell/platform/fuchsia/flutter/focus_delegate.cc
- shell/platform/fuchsia/flutter/focus_delegate.h
This change adds a path for setting focus on flatland with minimal disruption to the path used by GFX.
Will add tests before landing, just wanted to get it up in case people wanted to work off of it.
> [fuchsia][flatland] route ViewRefs properly for Focus

- shell/platform/fuchsia/flutter/flatland_platform_view.cc
- shell/platform/fuchsia/flutter/flatland_platform_view.h
- shell/platform/fuchsia/flutter/focus_delegate.cc
- shell/platform/fuchsia/flutter/focus_delegate.h
Reverts flutter/engine#29542
This was landed on master branch during the migration of master branch to main. Reverting and relanding on main.
> Revert "[fuchsia][flatland] route ViewRefs properly for Focus"

- DEPS
- lib/web_ui/dev/canvaskit_lock.yaml
- lib/web_ui/lib/src/engine/canvaskit/canvaskit_api.dart
- lib/web_ui/lib/src/engine/canvaskit/font_fallbacks.dart
- lib/web_ui/lib/src/engine/canvaskit/fonts.dart
- lib/web_ui/lib/src/engine/configuration.dart
> Roll to CanvasKit 0.31.0

- shell/platform/android/io/flutter/plugin/common/BasicMessageChannel.java
- shell/platform/android/io/flutter/plugin/common/MethodChannel.java
> Mentioned that replies can be invoked on any thread

- shell/platform/android/platform_view_android_jni_impl.cc
See https://github.com/flutter/flutter/issues/93975
> Release the JNI reference to the FlutterJNI class in GetDisplayRefreshRate

- .ci.yaml
- flow/layers/physical_shape_layer.cc
- flow/layers/physical_shape_layer_unittests.cc
- shell/platform/darwin/ios/framework/Source/FlutterViewController.mm
- shell/platform/darwin/ios/framework/Source/FlutterViewControllerTest.mm
> Cherrypick #29783 and #29862 to flutter-2.8-candidate.7

- .ci.yaml
The yaml doesn't require escaping the backslash (we only need to do this in Dart strings).
https://github.com/flutter/flutter/issues/84356
> [ci.yaml] Fix release branch regex

- DEPS
- shell/platform/android/io/flutter/embedding/android/FlutterView.java
- shell/platform/android/io/flutter/embedding/android/WindowInfoRepositoryCallbackAdapterWrapper.java
- shell/platform/android/test/io/flutter/embedding/android/FlutterViewTest.java
- shell/platform/android/test_runner/build.gradle
- tools/androidx/files.json
- tools/cipd/android_embedding_bundle/README.md
- tools/cipd/android_embedding_bundle/build.gradle
- tools/cipd/android_embedding_bundle/generate.sh
`androidx.window:window-java` is a beta dependency. 
The latest version includes a few changes that are necessary in order to roll Flutter into g3.
cc @andreidiaconu
> Bump androidx.window:window-java

- lib/web_ui/dev/test_runner.dart
> [web] remove unused --unit-tests-only flag

- shell/platform/linux/fl_view.cc
Helper functions first, then callbacks/implementations, then public functions.
Add function comments.
Use consistent function naming.
Remove unnecessary protoypes.
Make a function static that wasn't.
> Update functions to be consistent with other code.

- .github/workflows/mirror.yml
This is to protect master branch properly not allowing the autosubmit
bot to land PRs in master. …
> Update the token used by mirroring workflows.

- lib/web_ui/pubspec.yaml
Pick up https://github.com/flutter/web_installers/pull/29 to support upgrading iOS simulator devices and SDK on builder.
https://github.com/flutter/flutter/issues/85555 …
> Roll web_installers simulators package

- lib/ui/painting.dart
- lib/ui/text.dart
Removes some TODOs fixed by https://github.com/flutter/flutter/pull/94424
> Remove todos

- .ci.yaml
These are left over from the migration from starlark to yaml. Now that we can test in presubmit if these are necessary, we have higher confidence in landing this PR.
> [ci.yaml] Remove default properties

- lib/ui/painting.dart
The following suggestions. For clarity, the text has been improved over when it was suggested.
https://github.com/flutter/flutter/issues/93190
- Added description about paint parameter of Canvas.drawVertice method.
- Added description of Vertices-class constructor parameters.
I'm not a native English speaker, so I'm sorry if it's strange English.
If there is a mistake in the English grammar I wrote, it is difficult for me to correct it. …
> [Proposal] Improve Canvas Documentation

- .ci.yaml
> Revert "[ci.yaml] Remove default properties"

- .ci.yaml
- DEPS
Bug: https://github.com/flutter/flutter/issues/94492 …
> Fail loudly with verbose logs when failing to download dart sdk.

- shell/platform/darwin/ios/ios_context_gl.mm
- shell/platform/darwin/ios/ios_external_texture_gl.h
- shell/platform/darwin/ios/ios_external_texture_gl.mm
fix https://github.com/flutter/flutter/issues/94715
> Fix wrong context when use platfromview

- .ci.yaml
The `flutter` tool enforces a minimum of Xcode 12.3 as of https://github.com/flutter/flutter/pull/93094.  Use that version in engine builders to support arm64 mac host builds.
https://github.com/flutter/flutter/issues/84453#issuecomment-961599885
Note: this may cause slow builds until the Xcode caches have been populated.
Successful `led` test runs:
[Mac Web Engine](https://ci.chromium.org/raw/build/logs.chromium.org/flutter/led/magder_google.com/61b07a8f18553785ac948373c5ffaa9b62eb8d1b61c551eefa55328197b889d2/+/build.proto?server=chromium-swarm.appspot.com)
[Mac Unopt](https://ci.chromium.org/raw/build/logs.chromium.org/flutter/led/magder_google.com/55dccb4dd0d0e41e9c771587d98c7050f82c2eadd284b40e67fa798ef7a78d1e/+/build.proto?server=chromium-swarm.appspot.com)
[Mac iOS …
> Upgrade builder configuration to Xcode 12.3

- display_list/BUILD.gn
- display_list/display_list_ops.h
No change in functionality. The TU is empty.
> Ensure the TU that makes sure diplay_list_ops cleanly actually compiles.

- lib/ui/painting.dart
- lib/web_ui/lib/src/engine/html/path/path.dart
* https://github.com/flutter/flutter/issues/83690
> Improve documentation for arcToPoint's rotation units.

- runtime/dart_isolate.cc
- runtime/dart_vm.cc
- shell/common/shell_unittests.cc
fix issue: https://github.com/flutter/flutter/issues/74520 
> Remove AOT specific gates for isolate groups

- DEPS
- ci/licenses_golden/licenses_fuchsia
Reverts flutter/engine#30792
This roll broke the Fuchsia build, closing the engine tree.
@akbiggs
> Revert "Roll Fuchsia Linux SDK from DS-3oCidC... to 3-zk7OPWY..."

- shell/common/platform_view.cc
- shell/common/platform_view.h
Related PR: https://github.com/flutter/engine/pull/3112
> Remove obsolete 'PlatformView::size_' member variable

- shell/gpu/gpu_surface_metal.mm
fix https://github.com/flutter/flutter/issues/93160
> Add a trace to GpuSurfaceMetal around canvas flushing

- shell/platform/darwin/ios/framework/Source/SemanticsObject.mm
- shell/platform/darwin/ios/framework/Source/SemanticsObjectTest.mm
fixes https://github.com/flutter/flutter/issues/96485 …
> Started updating the native switch if it isn't enabled.

- shell/platform/darwin/ios/framework/Source/FlutterChannelKeyResponderTest.mm
- shell/platform/darwin/ios/framework/Source/FlutterEmbedderKeyResponderTest.mm
- shell/platform/darwin/ios/framework/Source/FlutterKeyboardManagerTest.mm
fixes https://github.com/flutter/flutter/issues/96682
test exempt, just edits tests …
> disabled ios 13.4+ tests on earlier devices

- shell/platform/android/io/flutter/embedding/android/FlutterActivity.java
- shell/platform/android/io/flutter/embedding/android/FlutterActivityAndFragmentDelegate.java
- shell/platform/android/io/flutter/embedding/android/FlutterFragment.java
- shell/platform/android/test/io/flutter/embedding/android/FlutterActivityTest.java
- shell/platform/android/test/io/flutter/embedding/android/FlutterAndroidComponentTest.java
- shell/platform/android/test/io/flutter/embedding/android/FlutterFragmentTest.java
Rework based on review comments: https://github.com/flutter/engine/pull/30126#discussion_r765875835
Fixes: https://github.com/flutter/flutter/issues/93905
/cc @dnfield @blasten  …
> Export |ExclusiveAppComponent<Activity>| from FlutterActivity/FlutterFragment class

- shell/platform/android/io/flutter/plugin/common/BinaryMessenger.java
> Minor doc improvements to `BinaryMessenger`

- shell/common/shell.cc
- shell/platform/darwin/ios/framework/Source/FlutterViewController.mm
Fixes: https://github.com/flutter/flutter/issues/95467
/cc @gaaclarke  …
> Check weak pointer to avoid potential use-after-free crash

- lib/web_ui/dev/canvaskit_roller.dart
Related to https://github.com/dart-lang/sdk/issues/48010
> Preserve write permissions when uploading canvaskit to CIPD

- fml/synchronization/count_down_latch_unittests.cc
> Re-enable Fuchsia CanWait test

- DEPS
- shell/platform/fuchsia/flutter/tests/fakes/scenic/fake_resources.cc
- shell/platform/fuchsia/flutter/tests/fakes/scenic/fake_resources.h
- shell/platform/fuchsia/flutter/tests/fakes/scenic/fake_session.cc
- shell/platform/fuchsia/flutter/tests/fakes/scenic/fake_session.h
- tools/fuchsia/sdk/sdk_targets.gni
This should unblock the SDK roller
> fuchsia: Fix potential SDK errors

- flow/testing/gl_context_switch_test.cc
- flow/testing/gl_context_switch_test.h
- lib/ui/ui_dart_state.cc
- lib/ui/ui_dart_state.h
- lib/ui/window/platform_configuration_unittests.cc
- runtime/test_font_data.cc
- runtime/test_font_data.h
Cleanup some more code which not unused for a long time.
> Cleanup unused code in the UIDartState and other tests.

- third_party/txt/src/skia/paragraph_skia.cc
See https://github.com/flutter/flutter/issues/97298
> Invalidate the ParagraphSkia line metrics caches when redoing layout

- .github/workflows/scorecards-analysis.yml
As a general rule github workflows should not run on forks of engine
repositories.
Bug: https://github.com/flutter/flutter/issues/97599 …
> Do not run score cards in forks of engine.

- DEPS
To pick up https://github.com/flutter/buildroot/pull/545
> Roll buildrot

- DEPS
- lib/web_ui/dev/canvaskit_lock.yaml
- lib/web_ui/lib/src/engine/configuration.dart
This brings the following:
* Fixes https://github.com/flutter/flutter/issues/97103
* Fixes https://github.com/flutter/flutter/issues/95259
> [web] roll CanvasKit to 0.33.0

- shell/platform/darwin/ios/framework/Source/FlutterViewController.mm
- shell/platform/darwin/ios/framework/Source/FlutterViewControllerTest.mm
Weak ptr should be checked for validity before use. Let's add it for protection~ …
> [iOS] Add FlutterViewController weak pointer check before use

- lib/ui/painting.dart
This is an additional patch to the previously submitted patch.
Thanks to @flar for suggestions for making it better.
https://github.com/flutter/engine/pull/30069
- This patch improves the documentation for the Vertices.raw constructor.
Also, this time, when I Fetch upstream from the browser (flutter / engine), I got an Actions error saying "GitHub token env var is not set.", But I haven't solved it.
I'm not sure what this is because I don't use Actions,
Please let me know if you have any problems with this patch.
If the patch is okay, ignore my problem with Actions.
Thank you.
[Tree …
> [Update][Proposal] Improve Canvas Documentation

- shell/testing/observatory/launcher.dart
- testing/android_systrace_test.py
See https://github.com/dart-lang/sdk/issues/46756
> Change support for VM service message from "Dart VM Service listening" to "The Dart VM Service is listening"

- DEPS
- testing/run_tests.py
- tools/gn
This needs https://github.com/flutter/impeller/pull/7 to disable the playgrounds by default.
> Adds impeller_unittests to run_tests.py

- shell/platform/darwin/ios/framework/Source/accessibility_bridge.mm
https://github.com/flutter/flutter/issues/98138 …
> Fix AccessibilityBridge crash due to invalid access during ReplaceSemanticsObject

- fml/platform/android/jni_util.cc
General UTF8/UTF16 string conversion utility functions were recently
added to FML. This migrates calls in the Android JNI utils to the common
implementations.
No additional tests added since we're just dropping one implementation
of UTF8/UTF16 functions and making use of an equivalent set that already
has unit tests of its own. The rest of the Android-related code is
already covered by existing unit tests.
Issue: https://github.com/flutter/flutter/issues/98061
Related PR: https://github.com/flutter/engine/pull/31334 …
> [fml] Use common FML string encoding utils

- third_party/accessibility/ax/platform/ax_platform_node_win_unittest.cc
Chrome's implementation of UI Automation support was only
partially-complete at the time we forked //third_party/accessibility. We
don't use UIA in Flutter, but rely instead entirely on the MSAA
accessiblity implementation.
Disabling these tests for now, rather than deleting, since we'll need to
make a decision on whetheer to port the updates from the Chromium tree,
or write our own simpler UIA implementation.
Issue: https://github.com/flutter/flutter/issues/98427
Related issue: https://github.com/flutter/flutter/issues/94782 …
> [win32] Disable a11y UIA unit tests

- .ci.yaml
.ci.yaml entries for the recipe added in https://flutter-review.googlesource.com/c/recipes/+/26820
@godofredoc is there anything needed other than adding the recipe and this change? Don't I have to say somewhere that this runs in both pre- and post- submit?
> Add Linux/Mac clang-tidy builds to .ci.yaml

- build/archives/BUILD.gn
- common/config.gni
- web_sdk/BUILD.gn
This is required to separate the the linux builds and tests. …
> GN targets to create flutter_web_sdk.

- build/archives/BUILD.gn
- web_sdk/BUILD.gn
Fuchsia targets are trying to package web_engine sdk but some of the
dependencies do not exist for that platform. We are filtering out
packaging of web engine if the platform is fuchsia. This change does not
have any impact as this are new targets that are not being used yet. …
> Fix gn problem impacting fuchsia builds.

- .ci.yaml
Run Mac Web Engine in the recipe cq tests to ensure the functionality is not brocken on changes to recipe modules. …
> Run mac web engine in recipes cq

- DEPS
- ci/licenses_golden/tool_signature
- tools/licenses/lib/main.dart
Buildroot PR: https://github.com/flutter/buildroot/pull/549
Wired this up against my in-progress [imgui backend for impeller](https://github.com/bdero/impeller/commit/b4c3ce758b2b2dc76063965e9dbe9f03f85ae3cc).
> Add Dear ImGui as a test only dependency

- .ci.yaml
This is required to delete the engine recipes from the root folder.
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-b …
> Use web_engine recipe from the engine folder.

- runtime/dart_vm.cc
This is for an internal release. Tracking bug: b/220976275
> [Cherrypick] Revert mark idle (#31487)

- shell/platform/android/io/flutter/plugin/common/PluginRegistry.java
Fixes an issue captured in g3.
Internal bug: http://b/220435069
> Fix nullable annotation

- build/archives/BUILD.gn
- common/config.gni
- tools/font-subset/BUILD.gn
- tools/font-subset/test.py
- web_sdk/BUILD.gn
* https://github.com/flutter/engine/pull/31556
* https://github.com/flutter/engine/pull/31615
* https://github.com/flutter/engine/pull/31575
> [Cherrypick] Changes related to Build+Test separation

- DEPS
- ci/licenses_golden/licenses_third_party
- ci/licenses_golden/tool_signature
- tools/licenses/lib/main.dart
This version includes support for fonts using the COLR table for
multi-colored glyphs.
> Roll FreeType to a version based on 2.11.1

- BUILD.gn
This will allow us to optimize builds by explicitly calling only the targets
that are required. …
> Separate unittest to its own group.

- DEPS
Reverts flutter/engine#31785
Reverting for https://github.com/flutter/flutter/issues/99488
> Revert "Roll Clang Linux from Fn7lDYhKD... to TaKxaPCe0..."

- DEPS
Reverts flutter/engine#31784
Reverting for https://github.com/flutter/flutter/issues/99488
> Revert "Roll Clang Mac from gi-ivU51h... to VvkT0LU62..."

- DEPS
Reverts flutter/engine#31783
Reverting for https://github.com/flutter/flutter/issues/99488
> Revert "Roll Clang Windows from 25xTI5-Mi... to _iKVo3b3j..."

- .ci.yaml
- ci/builders/linux_host_engine.json
This is the full refactoring of the linux host engine build relying
entirely on artifacts generated by gn and ninja and using the engine v2
recipes. …
> Add linux_host_engine builder to staging.

- ci/builders/windows_host_engine.json
This is to complete the implementation of windows host engine separating builds from tests.
[breaking …
> Adding archives to the windows host engine.

- lib/snapshot/libraries.json
- lib/snapshot/libraries.yaml
- shell/platform/fuchsia/dart_runner/kernel/libraries.json
- shell/platform/fuchsia/dart_runner/kernel/libraries.yaml
- shell/platform/fuchsia/flutter/kernel/libraries.json
- shell/platform/fuchsia/flutter/kernel/libraries.yaml
Add the newly added `Finalizer` and `NativeFinalizer` patch files to all the Flutter patch file lists.
* https://github.com/dart-lang/sdk/commit/7c04f35043d52b348061a4af110e18928916c955
This ensures we can land VM recognized classes in those patch files in the face of version skew in G3.
* [example failure](https://dart-in-g3-qa-prod.corp.google.com/dg3/Home#/cbuild/find/b4d06c9084a90185005b1ac5f0b2733d90118c17).
Prior art:
* https://github.com/flutter/engine/pull/31133
* https://github.com/flutter/engine/pull/23808
* https://github.com/flutter/engine/pull/23954
Does not add the files to golden in this PR, because the auto-roller already did that. …
> Add VM `Finalizer` patch files

- fml/message_loop_task_queues.cc
> Add include to header for coming libc++ updates

- ci/licenses_golden/licenses_third_party
https://github.com/flutter/flutter/issues/99526
To open the tree again.
> Update licenses_third_party hash

- build/archives/BUILD.gn
- build/zip_bundle.gni
- shell/platform/darwin/macos/BUILD.gn
This is to separate the mac builds from tests and archives. …
> Generate MacOS framework with GN + Ninja.

- display_list/display_list.h
Fixes https://github.com/flutter/flutter/issues/99795 …
> SaveLayerOptions explicit copy operator

- tools/dia_dll.py
Fixes:
* https://github.com/flutter/flutter/issues/99746
> [windows] Add dia_dll version for VS2022.

- display_list/types.h
- third_party/txt/src/txt/paragraph.h
I would like to land this CL in Skia that tidy up how we include things. This is part of an effort to reduce compile time by reducing header/include bloat (https://crbug.com/242216).
https://skia-review.googlesource.com/c/skia/+/517678
I tested this locally by patching in the above CL into third_party/skia and compiling on Linux. Our autoroller and Canary jobs will verify the fix before landing into Skia and rolling into flutter-engine.
> Fix Skia includes

- shell/platform/linux/fl_accessible_node.cc
Note that ATK_ROLE_CHECK_BOX is not perfect as this will also be used for switches and radio buttons but we don't have sufficient information from Flutter to determine this.
Fixes https://github.com/flutter/flutter/issues/98895
> Set a11y roles for checks, toggles and sliders.

- .ci.yaml
This is to start using 32 cores machines for clang tidy builders.
Bug: https://github.com/flutter/flutter/issues/98529 …
> Add top level cores dimension for Linux builders.

- .ci.yaml
- ci/licenses_golden/licenses_third_party
for release purpose. following steps in https://g3doc.corp.google.com/company/teams/flutter/release/workflows.md?cl=head to validate infra config. added a new line
> [release] validate infra configs in flutter engine

- runtime/runtime_controller.cc
- runtime/runtime_controller.h
- shell/common/engine.cc
- shell/common/shell_unittests.cc
fixes https://github.com/flutter/flutter/issues/98013 …
> Fixed image generator registry usage with spawn.

- lib/web_ui/lib/src/engine/canvaskit/surface.dart
- lib/web_ui/test/canvaskit/vertices_test.dart
Sane as https://github.com/flutter/engine/pull/31922/files but off by default for experimentation.
https://github.com/flutter/flutter/issues/100392
> allow experimentally opting into MSAA on canvaskit

- .ci.yaml
Part of https://github.com/flutter/flutter/issues/100334#issuecomment-1072606810
> Add deps to builder `web_engine_framework`

- shell/platform/android/io/flutter/plugin/platform/PlatformViewsController.java
- shell/platform/android/test/io/flutter/plugin/platform/PlatformViewsControllerTest.java
Fixes http://b/225327795
`PlatformView#getView()` is nullable
> Handle case where platform view getView() returns null

- examples/glfw/.gitignore
run.sh creates a new Flutter app that shouldn't be committed.
> [examples] Ignore myapp from run.sh.

- lib/ui/window.dart
Seems no need for issue since just typo …
> Fix simple typo: `or or`

- tools/gn
For https://github.com/flutter/flutter/issues/93871
/cc @a-siva
> Adds a gn script flag to select mallinfo2 when building the Dart VM

- shell/platform/android/io/flutter/plugin/platform/PlatformPlugin.java
- shell/platform/android/test/io/flutter/plugin/platform/PlatformPluginTest.java
This reverts PR #30931.
[Discord]: …
> Revert "Remove usages of Android's OnSystemUiVisibilityChangeListener"

- ci/licenses_golden/licenses_flutter
- shell/platform/android/AndroidManifest.xml
- shell/platform/android/BUILD.gn
- shell/platform/android/io/flutter/app/FlutterActivity.java
- shell/platform/android/io/flutter/app/FlutterActivityDelegate.java
- shell/platform/android/io/flutter/app/FlutterActivityEvents.java
- shell/platform/android/io/flutter/app/FlutterApplication.java
- shell/platform/android/io/flutter/app/FlutterFragmentActivity.java
- shell/platform/android/io/flutter/plugin/common/PluginRegistry.java
- shell/platform/android/io/flutter/view/FlutterView.java
- shell/platform/android/test_runner/src/main/AndroidManifest.xml
- testing/android_background_image/android/app/src/main/AndroidManifest.xml
- testing/scenario_app/android/app/src/main/AndroidManifest.xml
- tools/android_lint/project.xml
Reverts flutter/engine#32074, Failing framework multidex tests. Will reland after fixing.
> Revert "Delete io.flutter.app android v1 embedding"

- DEPS
The buildroot change is removing checked in binaries. …
> Roll buildroot to 9e885103f1b4019314e001cf68153c23936d2783.

- DEPS
Picks up:
- https://github.com/flutter/impeller/pull/100
- https://github.com/flutter/impeller/pull/99
- https://github.com/flutter/impeller/pull/101
> Roll impeller to 0ce2e789fc0852d6d9ee63fb68097327447cd7d8

- build/zip.py
Some artifacts require symlinks which is not supported by default by the python module. This PR adds functionality to manipulate the file properties to prevent resolving the symlinks. …
> Add symlink support to zip script

- build/archives/BUILD.gn
- common/config.gni
- shell/platform/darwin/macos/BUILD.gn
- shell/platform/embedder/BUILD.gn
- sky/tools/gen_snapshots.py
- sky/tools/macos_snapshots.gni
This is to move the logic to generate the macos snapshots to gn + ninja. …
> Targets to generate macos gen snapshot.

- .ci.yaml
- lib/web_ui/dev/browser_lock.yaml
Fixes https://github.com/flutter/flutter/issues/99698
Fixes https://github.com/flutter/flutter/issues/85555
Blocking https://github.com/flutter/flutter/issues/94078 …
> Update builders to Xcode 13 and macOS 12

- .ci.yaml
https://github.com/flutter/flutter/issues/99885
https://github.com/flutter/flutter/issues/97303
> [ci.yaml] Test web engine on Mac 12

- .github/workflows/scorecards-analysis.yml
This is required to fix the current failures caused by checks not being
request-able which are currently blocking rolls. …
> Remove the on_pull event from scorecards workflow.

- flow/layers/color_filter_layer.cc
- flow/layers/color_filter_layer.h
- flow/layers/color_filter_layer_unittests.cc
- flow/layers/container_layer.cc
- flow/layers/container_layer.h
- flow/layers/container_layer_unittests.cc
- flow/layers/image_filter_layer.cc
- flow/layers/image_filter_layer.h
- flow/layers/image_filter_layer_unittests.cc
- flow/layers/layer.h
- flow/layers/opacity_layer.cc
- flow/layers/opacity_layer.h
- flow/layers/opacity_layer_unittests.cc
- flow/raster_cache.cc
- flow/raster_cache.h
- flow/raster_cache_key.h
- flow/raster_cache_unittests.cc
- flow/testing/mock_raster_cache.cc
- flow/testing/mock_raster_cache.h
Reverts flutter/engine#31875 for https://github.com/flutter/flutter/issues/101152
cc @ColdPaleLight
> Revert "Add a way to raster cache the children of a Layer"

- tools/gn
Fixes https://github.com/flutter/flutter/issues/101000
> Expose a flag from tools/gn to disable deprecated API warnings

- tools/fuchsia/build_fuchsia_artifacts.py
Relanding https://github.com/flutter/engine/pull/31692. I've tested this time to make sure it works.
> [fuchsia] Support --no-prebuilt-dart-sdk in build_fuchsia_artifacts.

- shell/platform/darwin/ios/framework/Source/FlutterViewController.mm
Fixes https://github.com/flutter/flutter/issues/101209
> Always initialize the _weakFactory in FlutterViewController

- lib/ui/painting/vertices.cc
- testing/dart/canvas_test.dart
> [Cherrypick] assertion failure on empty indices in ui.Vertices constructor (#32434)

- .ci.yaml
> Revert "Update Web Engine to use Mac-12."

- shell/platform/darwin/graphics/FlutterDarwinExternalTextureMetal.mm
- shell/platform/darwin/ios/ios_external_texture_gl.mm
The Skia team is cleaning up our headers. This PR is required to land https://skia-review.googlesource.com/c/skia/+/526416
See issue https://bugs.chromium.org/p/skia/issues/detail?id=13052
This is hopefully the last of the changes needed for SkColorSpace
> [skia] More SkColorspace include fixes

- DEPS
* [win32] Suppress win32 swiftshader warnings (flutter/buildroot#562)
* [win32] Use clang cflags on Windows builds (flutter/buildroot#561)
Issue: https://github.com/flutter/flutter/issues/59199 …
> Roll buildroot to 60d942d91bf97e9c9f0876fb54d6cfba77c17dfb

- testing/test_gl_surface.cc
Skia's src files are not stable and may change constantly, flutter should not ever including them. …
> Don't use Skia internal src file GrGLDefines.

- DEPS
To pick up https://github.com/flutter/impeller/pull/131
> Roll Impeller to deab73b33a15261852c380eaa3c843bb5918e5f8

- shell/platform/linux/BUILD.gn
- shell/platform/linux/fl_binary_messenger_test.cc
- shell/platform/linux/testing/mock_binary_messenger.cc
- shell/platform/linux/testing/mock_binary_messenger.h
This is a preparation step split off from #32618 that will eventually fix light
vs. dark theme detection on Linux (flutter/flutter#101438).
GMock doesn't support mocking plain C-functions but GTypeInterface calls
can be forwarded to a mock object in a way that looks a lot like mocking
plain C-functions:
```c
testing::flutter::MockBinaryMessenger mock;
FlBinaryMessenger* messenger = fl_binary_messenger_new_mock(mock);
EXPECT_CALL(mock, fl_binary_messenger_send_on_channel(...)).WillOnce(...);
do_something(messenger);
``` …
> [Linux] add (Fl)MockBinaryMessenger for GMock

- shell/platform/android/io/flutter/plugin/common/StandardMessageCodec.java
Fixes https://github.com/flutter/flutter/issues/101991 …
> Fix nullability annotation in writeValue

- sky/tools/create_ios_framework.py
Reland of https://github.com/flutter/engine/pull/32638
Related https://github.com/flutter/flutter/issues/97327
> Reland: Ignore armv7 in ios framework script

- .ci.yaml
- ci/builders/mac_host_engine.json
This is part of the migration of engine recipes to v2. …
> Add mac_host_engine v2 builder.

- .ci.yaml
> [ci-fuchsia] Add "clobber" property to Linux Fuchsia

- shell/platform/android/test/io/flutter/embedding/android/FlutterViewTest.java
- shell/platform/android/test/io/flutter/embedding/engine/mutatorsstack/FlutterMutatorViewTest.java
[RuntimeEnvironment#systemContext](http://robolectric.org/javadoc/4.7/org/robolectric/RuntimeEnvironment.html#systemContext) was deprecated, and it's recommended to use `ApplicationProvider#getApplicationContext`. 
[CLA]: …
> Migrate RuntimeEnvironment#sytemContext to ApplicatoinProvider#getApplicationContext

- DEPS
- ci/licenses_golden/licenses_third_party
This rolls ANGLE to the most recent commit that compiles cleanly before
the build was refactored to support SwANGLE on ChromeCast, which
requires some buildroot tweaking to build with Flutter.
Issue: https://github.com/flutter/flutter/issues/102117 …
> Roll ANGLE to 90d18b0391065b7ecc556ccfce1201aa6392e22d

- DEPS
Contains:
* Add build variables required to roll ANGLE (flutter/buildroot#565)
Issue: https://github.com/flutter/flutter/issues/102117 …
> Roll buildroot to 2c41cfc742586b44984595960fc161c30252d8d6

- lib/web_ui/test/canvaskit/image_golden_test.dart
Add a test that reproduces https://skbug.com/12721. This PR does not contain a fix. The fix has to be made in Skia.
> [web] add test that repros https://skbug.com/12721

- DEPS
To pick up https://github.com/flutter/buildroot/pull/566
> Roll buildroot to 79aa4b0233325e6590dcd45a9af1526d9d2ad13b

- build/archives/BUILD.gn
To match https://flutter-review.googlesource.com/c/recipes/+/29300
> Add impeller artifacts to artifacts target

- DEPS
- ci/licenses_golden/licenses_skia
Speculative revert to fix https://github.com/flutter/flutter/issues/102711.
> Revert Skia roll to c8830b9f4c72

- .ci.yaml
Removes the Windows UWP Engine target from CI.
UWP support was removed from the tool in:
https://flutter-review.googlesource.com/c/recipes/+/29500
UWP support will be removed from the recipe in:
https://flutter-review.googlesource.com/c/recipes/+/29500
UWP infra will be removed in a future patch.
Issue: https://github.com/flutter/flutter/issues/102172 …
> Remove Windows UWP Engine target

- DEPS
- ci/licenses_golden/licenses_skia
- ci/licenses_golden/licenses_third_party
- ci/licenses_golden/tool_signature
- sky/packages/sky_engine/LICENSE
- tools/licenses/lib/main.dart
Fixes https://github.com/flutter/flutter/issues/102806.
Should unblock the roll once https://skia-review.googlesource.com/c/skia/+/535356 lands.
> Add vulkanmemoryallocator dependency for Skia; roll Skia to 4230297004

- DEPS
- ci/licenses_golden/licenses_skia
- display_list/display_list_ops.h
- display_list/display_list_unittests.cc
- sky/packages/sky_engine/LICENSE
Resolves https://github.com/flutter/flutter/issues/102858
> Roll Skia and update display list tests

- fml/file_unittest.cc
- fml/platform/win/file_win.cc
In the Posix implementation of this API, when both a base directory and an absolute path are provided, the base directory is ignored. This is because they are implemented with the `*at()` family of functions. See for example https://linux.die.net/man/2/openat.
This PR provides the same behavior on Windows.
Prior to this PR, the behavior is pasting the absolute path on the end of the absolute path of the base directory, which is causing impellerc to fail to write its output in tests on Windows.
> [fml] Handle absolute paths on Windows

- flow/compositor_context.h
- shell/common/engine.h
- shell/common/platform_view.h
- shell/common/pointer_data_dispatcher.h
- shell/common/shell.h
I am getting onboard with engine codebase by reading through the header files. It's pretty well documented and very helpful. 
NA …
> Fixed a few typos in comments

- BUILD.gn
This is to be able to call the archive artifacts. …
> Add archives to //flutter build file.

- sky/tools/create_ios_framework.py
This is needed to re-land https://flutter-review.googlesource.com/c/recipes/+/29060
> Make armv7 arg to iOS framework script optional

- lib/web_ui/lib/src/engine/canvaskit/canvaskit_api.dart
- lib/web_ui/lib/src/engine/canvaskit/initialization.dart
- lib/web_ui/lib/src/engine/dom.dart
Reverts flutter/engine#32936
Breaks roll.
> Revert "[web] Migrate Flutter Web DOM usage to JS static interop - 3"

- fml/log_settings.cc
> [flutter_releases] Remove reference to FX_LOG_ALL (#33027) 

- .ci.yaml
- ci/builders/linux_android_aot_engine.json
This is part of the migration of the engine builds to recipes v2. …
> Add linux_android_aot_engine using recipes v2.

- .ci.yaml
Fixes: https://github.com/flutter/flutter/issues/103158
> Replace dimension `mac_model: Macmini8,1` with `cpu: x86`

- .ci.yaml
- ci/builders/linux_arm_host_engine.json
This is part of the migration of engine builders to the recipes v2. …
> Add engine v2 linux arm host engine.

- ci/licenses_golden/licenses_flutter
- lib/web_ui/lib/src/engine.dart
- lib/web_ui/lib/src/engine/canvaskit/embedded_views.dart
- lib/web_ui/lib/src/engine/canvaskit/font_fallbacks.dart
- lib/web_ui/lib/src/engine/canvaskit/fonts.dart
- lib/web_ui/lib/src/engine/dom.dart
- lib/web_ui/lib/src/engine/svg.dart
- lib/web_ui/lib/src/engine/util.dart
- lib/web_ui/test/canvaskit/image_golden_test.dart
- lib/web_ui/test/canvaskit/initialization_test.dart
This is CL 7 in a series of CLs to migrate Flutter Web DOM usage to the new JS static interop API.
> [web] Migrate Flutter Web DOM usage to JS static interop - 7.

- .ci.yaml
- ci/builders/linux_android_debug_engine.json
This is part of the migration of builders to the engine v2 recipes. …
> Add linux android debug engine builder.

- flow/layers/opacity_layer.cc
- flow/layers/opacity_layer_unittests.cc
- fml/log_settings.cc
- shell/platform/android/io/flutter/plugin/platform/PlatformViewsController.java
- shell/platform/android/test/io/flutter/plugin/platform/PlatformViewsControllerTest.java
> Flutter 2.13 candidate.10

- lib/spirv/lib/src/instructions.dart
> Fix typo in SPIR-V transpiler error

- build/archives/BUILD.gn
I think this is right, though I haven't found it locally yet.
> add new tester to archives

- lib/web_ui/lib/src/engine/canvaskit/embedded_views.dart
- lib/web_ui/lib/src/engine/canvaskit/image_web_codecs.dart
- lib/web_ui/lib/src/engine/dom.dart
- lib/web_ui/lib/src/engine/embedder.dart
- lib/web_ui/lib/src/engine/html/backdrop_filter.dart
- lib/web_ui/lib/src/engine/html/clip.dart
- lib/web_ui/lib/src/engine/html/color_filter.dart
- lib/web_ui/lib/src/engine/html/image_filter.dart
- lib/web_ui/lib/src/engine/html/offset.dart
- lib/web_ui/lib/src/engine/html/opacity.dart
- lib/web_ui/lib/src/engine/html/picture.dart
- lib/web_ui/lib/src/engine/html/platform_view.dart
- lib/web_ui/lib/src/engine/html/scene.dart
- lib/web_ui/lib/src/engine/html/shader_mask.dart
- lib/web_ui/lib/src/engine/html/surface.dart
- lib/web_ui/lib/src/engine/html/transform.dart
- lib/web_ui/lib/src/engine/mouse_cursor.dart
- lib/web_ui/lib/src/engine/platform_views/slots.dart
- lib/web_ui/lib/src/engine/text/paragraph.dart
- lib/web_ui/lib/src/engine/util.dart
- lib/web_ui/test/canvaskit/canvas_golden_test.dart
- lib/web_ui/test/canvaskit/initialization_services_vs_ui_test.dart
- lib/web_ui/test/engine/platform_views/content_manager_test.dart
- lib/web_ui/test/engine/platform_views/slots_test.dart
- lib/web_ui/test/engine/surface/platform_view_test.dart
- lib/web_ui/test/engine/surface/surface_test.dart
- lib/web_ui/test/engine/util_test.dart
This is CL 12 in a series of CLs to migrate Flutter Web DOM usage to the new JS static interop API.
> [web] Migrate Flutter Web DOM usage to JS static interop - 12.

- DEPS
- ci/licenses_golden/licenses_third_party
Updates the ICU dep to match the revision used by Fuchsia.
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-c …
> Update ICU dep to match Fuchsia

- tools/githooks/setup.py
The git installed by depot_tools on Windows is only available as git.bat from Python.
The shell auto-replaces git by git.bat, but that doesn't happen when running from Python.
The git installed by depot_tools may be the only git installed on Windows.
Without this fix, gclient sync does not work on Windows for me
[Contributor …
> Use git.bat from depot_tools in githooks setup on Windows

- lib/web_ui/lib/src/engine/dom.dart
- lib/web_ui/lib/src/engine/embedder.dart
- lib/web_ui/lib/src/engine/html/backdrop_filter.dart
- lib/web_ui/lib/src/engine/html/offset.dart
- lib/web_ui/lib/src/engine/html/opacity.dart
- lib/web_ui/lib/src/engine/html/transform.dart
- lib/web_ui/lib/src/engine/mouse_cursor.dart
- lib/web_ui/lib/src/engine/text/paragraph.dart
- lib/web_ui/lib/src/engine/util.dart
- lib/web_ui/test/engine/util_test.dart
This is CL 11 in a series of CLs to migrate Flutter Web DOM usage to the new JS static interop API.
> [web] Migrate Flutter Web DOM usage to JS static interop - 11.

- DEPS
Roll https://github.com/flutter/buildroot/pull/574
Part of https://github.com/flutter/flutter/issues/101959 …
> Roll buildroot to target minimum iOS 11

- lib/web_ui/lib/src/engine/canvas_pool.dart
- lib/web_ui/lib/src/engine/canvaskit/embedded_views.dart
- lib/web_ui/lib/src/engine/dom.dart
- lib/web_ui/lib/src/engine/html/backdrop_filter.dart
- lib/web_ui/lib/src/engine/html/clip.dart
- lib/web_ui/lib/src/engine/html/color_filter.dart
- lib/web_ui/lib/src/engine/html/image_filter.dart
- lib/web_ui/lib/src/engine/html/offset.dart
- lib/web_ui/lib/src/engine/html/opacity.dart
- lib/web_ui/lib/src/engine/html/picture.dart
- lib/web_ui/lib/src/engine/html/platform_view.dart
- lib/web_ui/lib/src/engine/html/scene.dart
- lib/web_ui/lib/src/engine/html/shader_mask.dart
- lib/web_ui/lib/src/engine/html/shaders/image_shader.dart
- lib/web_ui/lib/src/engine/html/shaders/shader.dart
- lib/web_ui/lib/src/engine/html/surface.dart
- lib/web_ui/lib/src/engine/html/transform.dart
- lib/web_ui/lib/src/engine/platform_views/slots.dart
- lib/web_ui/test/engine/platform_views/content_manager_test.dart
- lib/web_ui/test/engine/platform_views/slots_test.dart
- lib/web_ui/test/engine/surface/platform_view_test.dart
- lib/web_ui/test/engine/surface/surface_test.dart
This is CL 13 in a series of CLs to migrate Flutter Web DOM usage to the new JS static interop API.
> [web] Migrate Flutter Web DOM usage to JS static interop - 13.

- shell/platform/fuchsia/dart_runner/BUILD.gn
Cherry pick to support Fuchsia in google team
> [flutter_releases] fix missing forward of defines in dart_runner build (#33412)

- lib/web_ui/lib/src/engine/assets.dart
- lib/web_ui/lib/src/engine/canvaskit/embedded_views.dart
- lib/web_ui/lib/src/engine/dom.dart
- lib/web_ui/lib/src/engine/engine_canvas.dart
- lib/web_ui/lib/src/engine/html/bitmap_canvas.dart
- lib/web_ui/lib/src/engine/html/dom_canvas.dart
- lib/web_ui/lib/src/engine/html/render_vertices.dart
- lib/web_ui/lib/src/engine/html/surface_stats.dart
- lib/web_ui/lib/src/engine/text/canvas_paragraph.dart
- lib/web_ui/lib/src/engine/text/paragraph.dart
- lib/web_ui/test/canvaskit/surface_test.dart
- lib/web_ui/test/text/canvas_paragraph_builder_test.dart
- lib/web_ui/test/text_test.dart
This is CL 15 in a series of CLs to migrate Flutter Web DOM usage to the new JS static interop API.
> [web] Migrate Flutter Web DOM usage to JS static interop - 15.

- tools/fuchsia/dart/dart_component.gni
- tools/fuchsia/dart/kernel/dart_kernel.gni
Add dart_component build rule that mirrors the build rule in fuchsia to be used in building fuchsia dart components.
> [dart_component] Add dart_component build rule.

- shell/platform/fuchsia/dart_runner/tests/startup_integration_test/BUILD.gn
- shell/platform/fuchsia/dart_runner/tests/startup_integration_test/hello_world/BUILD.gn
- shell/platform/fuchsia/dart_runner/tests/startup_integration_test/hello_world/main.dart
- shell/platform/fuchsia/dart_runner/tests/startup_integration_test/hello_world/meta/hello-world.cml
[dart_component][hello_world] Add a hello world dart component.
> [dart_component][hello_world] Add a hello world dart component.

- shell/common/shell_test_platform_view_metal.mm
- shell/gpu/gpu_surface_metal_skia.h
- shell/gpu/gpu_surface_metal_skia.mm
- shell/platform/darwin/ios/framework/Source/FlutterEnginePlatformViewTest.mm
- shell/platform/darwin/ios/ios_context.h
- shell/platform/darwin/ios/ios_context.mm
- shell/platform/darwin/ios/ios_context_gl.mm
- shell/platform/darwin/ios/ios_context_metal_impeller.mm
- shell/platform/darwin/ios/ios_context_metal_skia.h
- shell/platform/darwin/ios/ios_context_metal_skia.mm
- shell/platform/darwin/ios/ios_context_software.mm
- shell/platform/darwin/ios/ios_surface_metal_skia.mm
- shell/platform/darwin/ios/platform_view_ios.mm
- shell/platform/embedder/embedder_surface_metal.mm
Reverts flutter/engine#33461 @dkwingsmt 
Fixes https://github.com/flutter/flutter/issues/104154
> Revert "Enable MSAA behind a command line flag for iOS"

- shell/platform/android/platform_view_android.cc
@CaseyHillers @zanderso @chinmaygarde 
For b/233045685
> Guard impeller references in platform_view_android.cc for google build

- lib/ui/painting.dart
- testing/dart/fragment_shader_test.dart
Fixes https://github.com/flutter/flutter/issues/104084 by avoid a Timer.
> [dart:ui] dont create Timers in FragmentShader

- .ci.yaml
> Swap engine builds from Debian to Ubuntu.

- lib/web_ui/lib/src/engine/dom.dart
- lib/web_ui/lib/src/engine/engine_canvas.dart
- lib/web_ui/lib/src/engine/html/bitmap_canvas.dart
- lib/web_ui/lib/src/engine/html/clip.dart
- lib/web_ui/lib/src/engine/html/debug_canvas_reuse_overlay.dart
- lib/web_ui/lib/src/engine/html/dom_canvas.dart
- lib/web_ui/lib/src/engine/html/picture.dart
- lib/web_ui/lib/src/engine/html/scene.dart
- lib/web_ui/lib/src/engine/html/scene_builder.dart
- lib/web_ui/lib/src/engine/platform_dispatcher.dart
- lib/web_ui/lib/src/engine/svg.dart
- lib/web_ui/test/engine/surface/scene_builder_test.dart
- lib/web_ui/test/html/bitmap_canvas_golden_test.dart
- lib/web_ui/test/html/compositing/backdrop_filter_golden_test.dart
- lib/web_ui/test/html/compositing/color_filter_golden_test.dart
- lib/web_ui/test/html/compositing/compositing_golden_test.dart
- lib/web_ui/test/html/drawing/canvas_draw_image_golden_test.dart
- lib/web_ui/test/html/drawing/canvas_draw_picture_golden_test.dart
- lib/web_ui/test/html/recording_canvas_golden_test.dart
- lib/web_ui/test/html/screenshot.dart
- lib/web_ui/test/html/shaders/shader_mask_golden_test.dart
- lib/web_ui/test/html/shadow_golden_test.dart
- lib/web_ui/test/matchers.dart
This is CL 19 in a series of CLs to migrate Flutter Web DOM usage to the new JS static interop API.
> [web] Migrate Flutter Web DOM usage to JS static interop - 19.

- sky/tools/create_ios_framework.py
CP: https://github.com/flutter/engine/commit/baece8460e9512d2a9809bc0af3c8af93e0d477b
> Make armv7 arg to iOS framework script optional (#33090)

- impeller/archivist/archive.h
Fix internal build.
[Discord]: …
> [impeller] Include <functional> in a header file where std::function is used.

- fml/message_loop_task_queues_merge_unmerge_unittests.cc
- fml/message_loop_task_queues_unittests.cc
- shell/platform/embedder/tests/embedder_unittests_gl.cc
Found while working on https://github.com/flutter/engine/pull/33603.
Covered by existing asan and leak detection tests.
> Fixes a few asan errors

- lib/web_ui/lib/src/engine/dom.dart
- lib/web_ui/lib/src/engine/engine_canvas.dart
- lib/web_ui/lib/src/engine/html/bitmap_canvas.dart
- lib/web_ui/lib/src/engine/util.dart
This is CL 20 in a series of CLs to migrate Flutter Web DOM usage to the new JS static interop API.
> [web] Migrate Flutter Web DOM usage to JS static interop - 20.

- testing/run_tests.py
This PR runs each dart or flutter_tester invocation from a separate process.
> Run run_tests.py Dart tests in parallel

- shell/platform/linux/fl_accessible_node.h
> [Linux] fix typos in FlAccessibleNode docs

- impeller/tools/build_metal_library.py
- impeller/tools/impeller.gni
Fixes building pipeline libraries on simulators.
> [Impeller] Compile simulator specific Metal shader variants.

- shell/platform/fuchsia/dart_runner/dart_test_component_controller_v2.cc
- shell/platform/fuchsia/dart_runner/dart_test_component_controller_v2.h
Pass name of the test dart component to test_manager via test_case.
> Dart test runner: Set test suite name.

- lib/web_ui/dev/steps/run_tests_step.dart
- lib/web_ui/dev/test_platform.dart
- lib/web_ui/pubspec.yaml
- testing/skia_gold_client/README.md
- testing/skia_gold_client/lib/skia_gold_client.dart
- testing/skia_gold_client/pubspec.yaml
- web_sdk/web_test_utils/lib/image_compare.dart
- web_sdk/web_test_utils/pubspec.yaml
This allows the Android tests to also use the Skia Gold client on LUCI.
> Move Skia gold client to shared location

- .ci.yaml
The builder config is fragile when dependencies are not pinned to specific versions. Any upstream changes may cause breakage. We should create a test to validate all .ci.yaml dependencies are pinned. This also requires that we pin specific versions for all dependencies.
https://github.com/flutter/flutter/issues/101712 …
> Add versions to all the dependencies so they are pinned.

- display_list/display_list.h
- display_list/display_list_builder.cc
- display_list/display_list_builder.h
- display_list/display_list_canvas_dispatcher.cc
- display_list/display_list_canvas_dispatcher.h
- display_list/display_list_canvas_recorder.cc
- display_list/display_list_canvas_unittests.cc
- display_list/display_list_complexity_gl.cc
- display_list/display_list_complexity_gl.h
- display_list/display_list_complexity_metal.cc
- display_list/display_list_complexity_metal.h
- display_list/display_list_dispatcher.h
- display_list/display_list_image_filter.cc
- display_list/display_list_image_filter.h
- display_list/display_list_ops.h
- display_list/display_list_unittests.cc
- display_list/display_list_utils.cc
- display_list/display_list_utils.h
- impeller/display_list/display_list_dispatcher.cc
- impeller/display_list/display_list_dispatcher.h
- testing/display_list_testing.cc
- testing/display_list_testing.h
Fixes https://github.com/flutter/flutter/issues/105465
> add backdrop option to DisplayList::saveLayer

- lib/ui/painting/single_frame_codec.cc
- testing/dart/codec_test.dart
- testing/dart/image_dispose_test.dart
Fixes https://github.com/flutter/flutter/issues/105315
> Return an error if a SingleFrameCodec's cached decoded image has been disposed

- tools/gn
@zanderso 
This causes gn to emit warnings on non-mac platforms
> Do not set `use_ios_simulator` unconditionally

- .github/dependabot.yml
Dependabot updates in the engine have been running for some time
successfully and we are ready to land them automatically. I'm also
reducing the frequency to weekly. …
> Auto-land dependabot changes that pass all the tests.

- testing/run_tests.py
Fixes https://github.com/flutter/flutter/issues/105567 …
> Create iOS simulator before running IosUnitTests

- fml/platform/win/file_win.cc
- impeller/blobcat/blobcat_main.cc
- impeller/compiler/impellerc_main.cc
Fixes https://github.com/flutter/flutter/issues/105709
> Use std::filesystem to compute output paths in blobcat and impellerc

- lib/web_ui/lib/src/engine/dom.dart
> [flutter_releases][web] Fix typo in JS interop method. (#33947)

- ci/builders/linux_android_aot_engine.json
- ci/builders/linux_android_debug_engine.json
- ci/builders/linux_arm_host_engine.json
- ci/builders/linux_host_engine.json
This is required to start testing the gn artifacts with the integration
tests of flutter framework. …
> Start uploading artifacts to GCS.

- DEPS
Rolls in https://github.com/flutter/buildroot/pull/582.
cc @[azaslavsky](https://github.com/azaslavsky)
> Update DEPS to c1724ec7dc85b3a9137.

- lib/ui/window/pointer_data_packet_converter.cc
- lib/ui/window/pointer_data_packet_converter_unittests.cc
- shell/platform/darwin/ios/framework/Source/FlutterViewController.mm
- shell/platform/darwin/ios/framework/Source/FlutterViewControllerTest.mm
- testing/scenario_app/ios/Scenarios/ScenariosUITests/iPadGestureTests.m
Start sending PointerPanZoom events from iPadOS when the trackpad is used
Fixes https://github.com/flutter/flutter/issues/23604
> iPad trackpad gestures

- ci/builders/linux_android_debug_engine.json
The build was outdated and not generating all the expected artifacts.
This version included all the artifacts currently being generated and
uploaded from recipes.
[CLA]: …
> Update linux android debug engine configs.

- .ci.yaml
Context: https://github.com/flutter/flutter/issues/99885
> Bump xcode to version 13 for Mac Web Engine

- ci/builders/linux_android_aot_engine.json
This config was missed during the translation to recipes_v2. …
> Adds arm64-profile config.

- build/archives/BUILD.gn
- ci/builders/linux_android_aot_engine.json
- ci/builders/linux_android_debug_engine.json
- shell/platform/android/BUILD.gn
It is currently saved in the root folder when the flutter tool tries to
download it from linux-arm64/ folder. …
> Move flutter_patched_sdk to the correct location.

- impeller/display_list/display_list_unittests.cc
Fixes: https://github.com/flutter/flutter/issues/106218
> Fix test argument due to an api change

- build/archives/BUILD.gn
The zip file was not including the directory name because it was missing
an slash. …
> Add slash to separate directories.

- ci/builders/linux_android_aot_engine.json
- ci/builders/linux_host_engine.json
- shell/platform/android/BUILD.gn
- shell/platform/linux/BUILD.gn
* Adds a slash at the end of abi jars path.
* Generates abi files for android_profile arm64.
[breaking …
> Fixes for gn artifacts.

- lib/ui/painting/image_shader.cc
> Fix include path for internal build

- lib/web_ui/lib/src/engine/canvas_pool.dart
- lib/web_ui/lib/src/engine/canvaskit/image_web_codecs.dart
- lib/web_ui/lib/src/engine/dom.dart
- lib/web_ui/lib/src/engine/embedder.dart
- lib/web_ui/lib/src/engine/host_node.dart
- lib/web_ui/lib/src/engine/html/render_vertices.dart
- lib/web_ui/lib/src/engine/platform_dispatcher.dart
- lib/web_ui/lib/src/engine/platform_views/content_manager.dart
- lib/web_ui/lib/src/engine/safe_browser_api.dart
- lib/web_ui/lib/src/engine/text/measurement.dart
- lib/web_ui/lib/src/engine/text_editing/text_editing.dart
- lib/web_ui/test/embedder_test.dart
- lib/web_ui/test/engine/host_node_test.dart
- lib/web_ui/test/engine/semantics/semantics_test.dart
- lib/web_ui/test/engine/semantics/semantics_tester.dart
- lib/web_ui/test/engine/semantics/text_field_test.dart
- lib/web_ui/test/html/bitmap_canvas_golden_test.dart
- lib/web_ui/test/text_editing_test.dart
This is CL 36 in a series of CLs to migrate Flutter Web DOM usage to the new JS static interop API.
> [web] Migrate Flutter Web DOM usage to JS static interop - 36.

- ci/builders/linux_android_aot_engine.json
it was using a release path for a profile build. …
> Fix path in android aot configuration.

- lib/web_ui/lib/src/engine/dom.dart
- lib/web_ui/lib/src/engine/embedder.dart
- lib/web_ui/lib/src/engine/host_node.dart
- lib/web_ui/lib/src/engine/html/color_filter.dart
- lib/web_ui/lib/src/engine/html/shader_mask.dart
- lib/web_ui/lib/src/engine/mouse_cursor.dart
- lib/web_ui/lib/src/engine/platform_dispatcher.dart
- lib/web_ui/lib/src/engine/semantics/semantics.dart
- lib/web_ui/lib/src/engine/text_editing/composition_aware_mixin.dart
- lib/web_ui/lib/src/engine/text_editing/text_editing.dart
- lib/web_ui/test/canvaskit/embedded_views_test.dart
- lib/web_ui/test/canvaskit/h5vcc_test.dart
- lib/web_ui/test/composition_test.dart
- lib/web_ui/test/embedder_test.dart
- lib/web_ui/test/engine/pointer_binding_test.dart
- lib/web_ui/test/engine/semantics/semantics_test.dart
- lib/web_ui/test/html/shaders/shader_mask_golden_test.dart
- lib/web_ui/test/matchers.dart
This is CL 37 in a series of CLs to migrate Flutter Web DOM usage to the new JS static interop API.
> [web] Migrate Flutter Web DOM usage to JS static interop - 37.

- ci/builders/linux_host_engine.json
- ci/builders/mac_ios_engine.json
- ci/builders/mac_ios_engine_profile.json
> Fix mac_ios builders and archive paths in linux host.

- .github/dependabot.yml
This will use the new bot for auto submitting dependabot PRs.
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breakin …
> Use autosubmit instead of "waiting for tree to go green" for dependabot.

- ci/licenses_golden/licenses_flutter
- display_list/BUILD.gn
- display_list/display_list_utils.cc
- display_list/display_list_utils_unittests.cc
fix https://github.com/flutter/flutter/issues/100176
> Make DisplayList DispatchHelpers prevent against extra restore calls

- shell/platform/android/test/README.md
- shell/platform/android/test/io/flutter/plugin/platform/PlatformViewsControllerTest.java
- shell/platform/android/test_runner/build.gradle
- shell/platform/android/test_runner/src/main/resources/robolectric.properties
This reverts commit 28575318be4cfa1bb01279ac2702d0aa5d3e765b.
> Revert "Bump Robolectric to 4.8.1 (#33024)"

- ci/builders/mac_ios_engine_release.json
The ios_release_arm version was removed and ios_debug_arm64 was added. …
> Update gn + ninja commands for mac_ios_release.

- DEPS
- tools/gn
This is to help investigate https://github.com/flutter/flutter/issues/87952
The new GN flag is added in https://github.com/flutter/buildroot/pull/584
> Adds a flag to the gn script to build with -fstack-protector

- shell/platform/linux/BUILD.gn
gen_snapshot is required as part of flutter_gtk. …
> Add gen_snapshot to flutter_gtk.

- display_list/display_list_image_filter.h
- display_list/display_list_image_filter_unittests.cc
- flow/layers/backdrop_filter_layer.cc
- flow/layers/backdrop_filter_layer.h
- flow/layers/backdrop_filter_layer_unittests.cc
- lib/ui/compositing/scene_builder.cc
Relands https://github.com/flutter/engine/pull/34146
> Reland "render BackdropFilter layers directly to DisplayListBuilder"

- lib/web_ui/lib/src/engine/dom.dart
- lib/web_ui/lib/src/engine/util.dart
- lib/web_ui/test/canvaskit/embedded_views_test.dart
- lib/web_ui/test/embedder_test.dart
- lib/web_ui/test/engine/platform_dispatcher_test.dart
- lib/web_ui/test/engine/profiler_test.dart
- lib/web_ui/test/engine/window_test.dart
- lib/web_ui/test/html/bitmap_canvas_golden_test.dart
- lib/web_ui/test/html/canvas_context_golden_test.dart
- lib/web_ui/test/html/compositing/compositing_golden_test.dart
- lib/web_ui/test/html/drawing/canvas_draw_color_golden_test.dart
- lib/web_ui/test/html/shaders/gradient_golden_test.dart
- lib/web_ui/test/html/shaders/shader_mask_golden_test.dart
- lib/web_ui/test/path_test.dart
- lib/web_ui/test/text/font_collection_test.dart
- lib/web_ui/test/text/font_loading_test.dart
- lib/web_ui/test/window_test.dart
This is CL 40 in a series of CLs to migrate Flutter Web DOM usage to the new JS static interop API.
> [web] Migrate Flutter Web DOM usage to JS static interop - 40.

- lib/web_ui/lib/src/engine/dom.dart
- lib/web_ui/test/composition_test.dart
- lib/web_ui/test/engine/pointer_binding_test.dart
- lib/web_ui/test/engine/semantics/accessibility_test.dart
- lib/web_ui/test/engine/semantics/semantics_test.dart
- lib/web_ui/test/engine/semantics/semantics_tester.dart
- lib/web_ui/test/engine/semantics/text_field_test.dart
- lib/web_ui/test/keyboard_test.dart
- lib/web_ui/test/text_editing_test.dart
- lib/web_ui/test/text_test.dart
- lib/web_ui/test/title_test.dart
This is CL 43 in a series of CLs to migrate Flutter Web DOM usage to the new JS static interop API
> [web] Migrate Flutter Web DOM usage to JS static interop - 43.

- DEPS
- ci/licenses_golden/licenses_third_party
See https://github.com/flutter/flutter/issues/106118
> Roll FreeType

- lib/web_ui/lib/src/engine/dom.dart
- sky/packages/sky_engine/BUILD.gn
- sky/packages/sky_engine/lib/_embedder.yaml
- web_sdk/sdk_rewriter.dart
- web_sdk/test/js_access_test.dart
- web_sdk/test/sdk_rewriter_test.dart
- web_sdk/web_engine_tester/lib/golden_tester.dart
- web_sdk/web_engine_tester/lib/static/host.dart
This is CL 44 in a series of CLs to migrate Flutter Web DOM usage to the new JS static interop API
> [web] Migrate Flutter Web DOM usage to JS static interop - 44. 

- DEPS
Roll the buildroot deps to https://github.com/flutter/buildroot/commit/0813fd008b5c01fbd8170a68482fd19fd00768b4
> Roll buildroot deps.

- tools/gn
- commit: flutter/engine@8cee666b4
> [flutter_releases] Flutter stable 3.0.4 Engine Cherrypicks

- impeller/compiler/switches.cc
Fixes an internal compilation warning.
> Remove unused variable

- impeller/compiler/switches.cc
> [cherry pick] cp `Remove unused variable (#34390)` to 3.2-candidate.3

- .ci.yaml
https://github.com/flutter/flutter/issues/99885
> Migrate Mac Web Engine to Mac 12

- ci/builders/linux_android_aot_engine.json
There were some missing artifacts and the json file was formatted with
python -m json.tool.
[breaking …
> Updates linux_android_aot to include all the required artifacts.

- build/archives/BUILD.gn
- shell/platform/android/BUILD.gn
Generates a gen_snapshot archive for windows. The reason it is a separate target is that names and paths are completely different and adding them to the same target will be confusing.
[CLA]: …
> Add gen_snapshot for windows.

- shell/platform/darwin/macos/framework/Source/FlutterMenuPluginTest.mm
See:
https://github.com/flutter/flutter/issues/106589 and https://github.com/flutter/flutter/issues/106588
> Disables flaky test FlutterMenuPluginTest.TestSetMenu

- display_list/display_list_unittests.cc
- display_list/display_list_utils.h
Fixes: https://github.com/flutter/flutter/issues/106793
> fix empty bounds for flat sets of drawPoints

- ci/builders/windows_host_engine.json
This is to start testing the gn generated artifacts for windows. …
> Start uploading windows artifacts to gcs.

- DEPS
Roll the flutter buildroot DEPS flutter/buildroot with https://github.com/flutter/buildroot/pull/587
> Roll buildroot DEPS

- .ci.yaml
New Fuchsia release branch that we need to cherrypick a change into.
> [fuchsia] Enable Linux Fuchsia builders for fuchsia_r49.

- shell/platform/fuchsia/dart_runner/dart_test_component_controller_v2.cc
- shell/platform/fuchsia/dart_runner/dart_test_component_controller_v2.h
Support stdout/stderr logging to current execution window by passing handles to the dart process and the test_manager.
> [dart_test_runner] Stdout/stderr logging to current execution window.

- shell/common/switches.cc
Since this is no longer supported in switches.cc
> delete dl flag from allowlist

- shell/platform/android/android_shell_holder.cc
See https://github.com/flutter/engine/pull/34568
> Set the IO thread on Android to normal priority

- flow/raster_cache.cc
fix https://github.com/flutter/flutter/issues/107622
> Tweak the condition of 'FML_DCHECK' to solve the issue caused by round-off error

- fml/message_loop_impl.h
- fml/message_loop_task_queues.cc
- fml/message_loop_task_queues.h
- fml/message_loop_task_queues_merge_unmerge_unittests.cc
- fml/shared_thread_merger.h
fixes:https://github.com/flutter/flutter/issues/105589
> remove lock and use raw ptr for MessageLoopTaskQueues

- impeller/entity/contents/clip_contents.cc
- impeller/entity/contents/clip_contents.h
- impeller/entity/contents/contents.cc
- impeller/entity/contents/contents.h
- impeller/entity/entity.cc
- impeller/entity/entity.h
- impeller/entity/entity_pass.cc
- impeller/entity/entity_unittests.cc
Also changed it to take an ISize for better testability.
> [Impeller] Cover ShouldRender in tests.
