flutter/engine

- impeller/README.md
- impeller/docs/blending.md
Fixes https://github.com/flutter/flutter/issues/105563.
I focused on explaining the whole "pipeline blend" vs "advanced blend" situation and didn't put the equations in-line since it would mostly just be repeating the W3 doc, but I can do so if desirable (perhaps in a follow-up?)
> [Impeller] Document blending/color management

- DEPS
Fixes: https://github.com/flutter/flutter/issues/108237
> Upgrade perfetto/trace_to_text dependency to v25.0 which supports Apple Silicon

- lib/snapshot/BUILD.gn
- sky/tools/create_macos_gen_snapshots.py
Fixes: https://github.com/flutter/flutter/issues/108238
> use host_cpu in BUILD.gn to determine where to find gen_snapshot

- impeller/aiks/aiks_unittests.cc
- impeller/display_list/display_list_dispatcher.cc
tiny patch for https://github.com/flutter/engine/pull/34875
> [Impeller] Fix issue that radial gradient colors not being passed to contents

- shell/platform/android/io/flutter/plugin/platform/PlatformViewWrapper.java
- shell/platform/android/test/io/flutter/plugin/platform/PlatformViewWrapperTest.java
Part of https://github.com/flutter/flutter/issues/108136
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-cha …
> [cherry-pick] Use PorterDuff blend mode when below Android 29 (#34800)

- shell/common/shell_io_manager.cc
- tools/gn
Depends on https://skia-review.googlesource.com/c/skia/+/562341
> Don't compile the Skia GL backend on iOS.

- tools/gn
This is a continuation PR per https://github.com/flutter/engine/pull/34894#pullrequestreview-1050226019
https://github.com/flutter/flutter/issues/108478 …
> Update python3 reference to vpython3

- tools/gn.bat
This PR aims to match functionality in flutter/engine as seen here: https://github.com/flutter/engine/commit/d3dc61495d7011fa6fec6a03721d7e1151d0a9ca
> We believe this will reduce flakiness on the Windows bots by limiting
the interaction of the global Python install and the self-contained
hermetic vpython that ships with depot_tools.
and solves a broader issue described [here].(https://github.com/flutter/flutter/issues/108474)
This is a continuation PR per https://github.com/flutter/engine/pull/34894#pullrequestreview-1050226019
https://github.com/flutter/flutter/issues/108479
[Tree …
> Update reference to python3 with vpython3

- lib/snapshot/BUILD.gn
Cleanup following https://github.com/flutter/engine/pull/34870
> Compute rather than hardcode the host output suffix

- ci/builders/mac_host_engine.json
Artifacts for profiles other than debug include the profile name as part
of the path. …
> Fix paths of mac_host_engine artifacts.

- analysis_options.yaml
To mirror https://github.com/flutter/flutter/pull/108652.
> Enable conditional_uri_does_not_exist

- impeller/compiler/compiler.cc
- impeller/compiler/compiler.h
- impeller/compiler/compiler_test.cc
- impeller/compiler/compiler_test.h
- impeller/compiler/compiler_unittests.cc
- impeller/fixtures/BUILD.gn
- impeller/fixtures/sample.frag
See: https://github.com/flutter/flutter/issues/108739
> [impeller] Set binding base for fragment shaders

- tools/gn
Fixes https://github.com/flutter/flutter/issues/108485
> Fix detection of Mac target specification as a host build.

- DEPS
Pulls in some dependabot commits that were added to ToT there.
> Roll buildroot to 0881a07a.

- DEPS
See https://github.com/flutter/flutter/issues/108388
> Roll Abseil

- sky/tools/create_macos_framework.py
This is required for generic build configurations where full paths are
not available. …
> Add support relative path support to create_macos_framework.

- analysis_options.yaml
Upstream issue https://github.com/dart-lang/sdk/issues/49563 is fixed and the fix rolled into the engine.
> Remove ffi_native_unexpected_number_of_parameters ignore

- sky/tools/create_macos_framework.py
This is to move the zipping logic from recipes back to the engine. …
> Zip the dsym artifacts.

- ci/builders/mac_host_engine.json
This includes global generators to create the dSYM files using multiple
subbuilds.
Bug: https://github.com/flutter/engine/pull/35075 …
> Update the mac_host_engine configuration.

- shell/common/BUILD.gn
Cf. 08416ceee0699b38874a13bb4539f97dfce6d566.
Bug: https://github.com/flutter/flutter/issues/90425
Bug: https://github.com/flutter/flutter/issues/103386
> Remove architecture restriction from //flutter/testing:opengl.

- ci/builders/mac_host_engine.json
This is to start testing the gn artifacts for mac with flutter/flutter
tests. …
> Update mac artifacts to gcs.

- .ci.yaml
- ci/builders/mac_android_aot_engine.json
This is the configuration file for mac android aout engine using recipes
v2. …
> Adds mac_android_aot_engine.

- tools/fuchsia/gn-sdk/pm_tool.gni
Fixes [fxb/105705](https://bugs.fuchsia.dev/p/fuchsia/issues/detail?id=105705)
> [Fuchsia] Specify the target API level in pm_tool.gni

- lib/ui/painting.dart
See https://github.com/flutter/flutter/pull/108500
> We decided not to support bare ellipsis in the API docs.

- flow/embedded_views.cc
- flow/embedded_views.h
- flow/layers/layer.h
- flow/layers/layer_tree.cc
- flow/layers/layer_tree_unittests.cc
- flow/layers/platform_view_layer.cc
- flow/testing/mock_embedder.cc
- flow/testing/mock_embedder.h
- shell/common/rasterizer_unittests.cc
- shell/common/shell_test_external_view_embedder.cc
- shell/common/shell_test_external_view_embedder.h
- shell/platform/android/external_view_embedder/external_view_embedder.cc
- shell/platform/android/external_view_embedder/external_view_embedder.h
- shell/platform/android/external_view_embedder/external_view_embedder_unittests.cc
- shell/platform/darwin/ios/framework/Source/FlutterPlatformViews.mm
- shell/platform/darwin/ios/framework/Source/FlutterPlatformViews_Internal.h
- shell/platform/darwin/ios/ios_external_view_embedder.h
- shell/platform/darwin/ios/ios_external_view_embedder.mm
- shell/platform/embedder/embedder_external_view_embedder.cc
- shell/platform/embedder/embedder_external_view_embedder.h
- shell/platform/fuchsia/flutter/flatland_external_view_embedder.cc
- shell/platform/fuchsia/flutter/flatland_external_view_embedder.h
- shell/platform/fuchsia/flutter/gfx_external_view_embedder.cc
- shell/platform/fuchsia/flutter/gfx_external_view_embedder.h
- shell/platform/fuchsia/flutter/platform_view_unittest.cc
- shell/platform/fuchsia/flutter/tests/flatland_external_view_embedder_unittests.cc
- shell/platform/fuchsia/flutter/tests/flatland_platform_view_unittest.cc
- shell/platform/fuchsia/flutter/tests/gfx_external_view_embedder_unittests.cc
- shell/testing/tester_main.cc
Fixes: https://github.com/flutter/flutter/issues/104025
Labelling a WIP for now until I can test on Android, but I was able to get an embedded Google Map to show underneath the flutter navigation layers on iPhone with this code. Theoretically it will also work for Android.
> Embedders use DisplayListBuilder for compositing

- sky/tools/create_full_ios_framework.py
This is to simplify the migration to engine_v2 recipes and can potentially simplify the existing recipes moving most of the logic to the engine repository.
[CLA]: …
> Adds a script the generates and bundle the ios artifacts.

- testing/dart/observatory/vmservice_methods_test.dart
Might have forked before we started analyzing this
> fix analysis error

- impeller/aiks/aiks_unittests.cc
- impeller/entity/entity.cc
- impeller/entity/entity.h
- impeller/entity/entity_pass.cc
- impeller/entity/entity_pass.h
Fix https://github.com/flutter/flutter/issues/106051
> [Impeller] EntityPass should cover the whole screen for some blend modes

- impeller/compiler/reflector.cc
- impeller/compiler/reflector.h
- impeller/compiler/runtime_stage_data.cc
- impeller/compiler/runtime_stage_data.h
- impeller/compiler/spirv_sksl.cc
- impeller/runtime_stage/runtime_stage.cc
- impeller/runtime_stage/runtime_stage.fbs
- impeller/runtime_stage/runtime_stage.h
- lib/ui/fixtures/shaders/general_shaders/BUILD.gn
- lib/ui/fixtures/shaders/general_shaders/uniform_arrays.frag
- lib/ui/painting/fragment_program.cc
- testing/dart/fragment_shader_test.dart
Part of https://github.com/flutter/flutter/issues/93800
> Adds support for uniform arrays to FragmentPrograms

- tools/gen_objcdoc.sh
Reverts flutter/engine#35190
Blocking the roll to framework: https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20docs_test/15215/overview
> Revert "Updates objectc script to accept relative paths."

- common/graphics/texture.cc
- common/graphics/texture.h
- flow/compositor_context.cc
- flow/compositor_context.h
- flow/layers/layer.h
- flow/layers/layer_tree.cc
- flow/layers/layer_tree_unittests.cc
- flow/layers/performance_overlay_layer_unittests.cc
- flow/layers/texture_layer.cc
- flow/layers/texture_layer_unittests.cc
- flow/raster_cache_unittests.cc
- flow/skia_gpu_object.h
- flow/skia_gpu_object_unittests.cc
- flow/testing/layer_test.h
- flow/testing/mock_raster_cache.cc
- flow/testing/mock_raster_cache.h
- lib/ui/BUILD.gn
- lib/ui/painting/display_list_deferred_image_gpu.cc
- lib/ui/painting/display_list_deferred_image_gpu.h
- lib/ui/painting/image_encoding.cc
- lib/ui/painting/picture.cc
- lib/ui/snapshot_delegate.h
- shell/common/fixtures/shell_test.dart
- shell/common/rasterizer.cc
- shell/common/rasterizer.h
- shell/common/shell.cc
- shell/common/shell_unittests.cc
Reverts flutter/engine#35073
Caused redness in tree
> Revert "Collect textures from toImageSync safely"

- impeller/renderer/allocator.cc
- impeller/renderer/allocator.h
- impeller/renderer/backend/metal/allocator_mtl.h
- impeller/renderer/backend/metal/allocator_mtl.mm
- impeller/renderer/backend/metal/device_buffer_mtl.h
- impeller/renderer/backend/metal/device_buffer_mtl.mm
Fixes https://github.com/flutter/flutter/issues/108996
> [Impeller] Enable support for Apple Silicon Macs and tvOS devices.

- tools/gen_objcdoc.sh
Reverts flutter/engine#35265
With https://github.com/flutter/flutter/pull/109316 already landed we are ready to reland the change.
> "Reland" "Updates objectc script to accept relative paths.""

- ci/licenses_golden/licenses_flutter
- impeller/playground/backend/vulkan/playground_impl_vk.cc
- impeller/playground/backend/vulkan/playground_impl_vk.h
- impeller/renderer/backend/vulkan/BUILD.gn
- impeller/renderer/backend/vulkan/context_vk.cc
- impeller/renderer/backend/vulkan/context_vk.h
- impeller/renderer/backend/vulkan/formats_vk.h
- impeller/renderer/backend/vulkan/surface_producer_vk.cc
- impeller/renderer/backend/vulkan/surface_producer_vk.h
- impeller/renderer/backend/vulkan/surface_vk.cc
- impeller/renderer/backend/vulkan/surface_vk.h
- impeller/renderer/backend/vulkan/swapchain_vk.cc
- impeller/renderer/backend/vulkan/swapchain_vk.h
- impeller/renderer/surface.h
SurfaceVK still needs to be fully wired up.
> [Impeller] [vulkan] Setup surface producer, and wireup swapchain sync objects

- impeller/renderer/backend/metal/render_pass_mtl.mm
- impeller/renderer/formats.h
Fixes https://github.com/flutter/flutter/issues/109277
> [Impeller] Get rid of redundant viewport and scissor bindings.

- impeller/display_list/display_list_dispatcher.cc
- impeller/display_list/display_list_unittests.cc
- impeller/entity/contents/solid_stroke_contents.cc
- impeller/geometry/path.cc
- impeller/geometry/point.h
fixes https://github.com/flutter/flutter/issues/109077
> [Impeller] Render axis-aligned Caps for zero length lines in Impeller

- shell/platform/android/io/flutter/plugin/platform/PlatformViewsController.java
- shell/platform/android/test/io/flutter/plugin/platform/PlatformViewsControllerTest.java
Fixes [flutter/flutter#105229](https://github.com/flutter/flutter/issues/105229)
fixes [flutter/flutter#70639](https://github.com/flutter/flutter/issues/70369) …
> Fix PlatformView multiple pointer crash caused by toMotionEvent

- shell/platform/fuchsia/flutter/tests/fakes/focuser.h
Replace superclass with _TestBase variant.
[*List which issues are fixed by this PR. You must list at least one issue.*](https://github.com/flutter/flutter/issues/109569)
> [fuchsia] Adjust FakeFocuser inheritance

- sky/tools/create_full_ios_framework.py
The code path dealing with release information was not implementing the
relative paths calculation correctly. …
> Fixes the output path for release dsym.

- impeller/renderer/allocator.h
- impeller/renderer/backend/gles/allocator_gles.cc
- impeller/renderer/backend/gles/allocator_gles.h
- impeller/renderer/backend/metal/allocator_mtl.h
- impeller/renderer/backend/metal/allocator_mtl.mm
- impeller/renderer/backend/vulkan/allocator_vk.cc
- impeller/renderer/backend/vulkan/allocator_vk.h
- lib/ui/painting/image_decoder_impeller.cc
- lib/ui/painting/image_decoder_impeller.h
- lib/ui/painting/image_decoder_unittests.cc
fixes https://github.com/flutter/flutter/issues/108929
> [Impeller] Clamp texture decompression to maximum supported texture size.

- impeller/entity/contents/filters/gaussian_blur_filter_contents.cc
Builds on https://github.com/flutter/engine/pull/35422.
Removes a hack that allows zero sigma to work. This was no longer behaving well because the blur filter now always uses linear sampling for the final blit.
Before:
After:
> [Impeller] When the blur sigma approaches zero, passthrough

- impeller/display_list/display_list_dispatcher.cc
Perusing the code makes it look like these are remaining to do.
> [Impeller] Update code comments about DL methods that Flutter doesn't expose.

- impeller/aiks/aiks_unittests.cc
fix https://github.com/flutter/flutter/issues/109648
> [Impeller] Fix Metal validation failures on CanRenderTiledTexture/Metal

- sky/tools/create_full_ios_framework.py
A follow up from https://github.com/flutter/engine/pull/35417#discussion_r948318336 to better write file paths to configs in generator script.
> [gn + codesign] use join to concatenate 

- impeller/geometry/geometry_unittests.cc
- impeller/geometry/point.h
Used by https://github.com/flutter/engine/pull/35491.
> [Impeller] Add Point::AngleTo

- ci/licenses_golden/licenses_flutter
- shell/platform/common/BUILD.gn
- shell/platform/common/incoming_message_dispatcher_unittests.cc
> Backfilled unit tests for IncomingMessageDispatcher.

- ci/builders/mac_host_engine.json
The original target was refactored to remove a lot of boilerplate. …
> Update target used to generate mac flutter framework.

- flow/raster_cache.cc
- flow/raster_cache_unittests.cc
Fixes https://github.com/flutter/flutter/issues/110002
- X ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on
[CLA]: …
> Ensure raster cache doesn't bleed over to adjacent physical pixels

- lib/ui/compositing.dart
- lib/web_ui/lib/compositing.dart
- testing/dart/compositing_test.dart
Forgot to deprecate this after deprecating the framework side APIs.
> deprecate pushPhysicalLayer

- shell/platform/android/io/flutter/view/AccessibilityBridge.java
- shell/platform/android/test/io/flutter/view/AccessibilityBridgeTest.java
> Support BoldText for a11y in android 

- sky/tools/create_macos_framework.py
This is to move the zipping logic to the repository under test. …
> Zip FlutterMacOS.framework.

- impeller/entity/entity_pass.cc
Fixes texture corruption happening in GLES.
> [Impeller] Add fallback in EntityPass for backends that don't support offscreen MSAA

- testing/symbols/pubspec.yaml
- testing/symbols/verify_exported.dart
Migrate testing/symbols to null safety. 
Contributes to https://github.com/flutter/flutter/issues/110020 …
> Migrate testing/symbols to null safety

- shell/platform/darwin/common/framework/Headers/FlutterCodecs.h
> Fixed the nullability annotation on codec `writeValue:`

- impeller/entity/contents/filters/gaussian_blur_filter_contents.cc
https://www.desmos.com/calculator/pne3q7ctq3
> Make blur image size falloff less aggressive

- impeller/renderer/backend/gles/surface_gles.cc
fix https://github.com/flutter/flutter/issues/110844
> [Impeller] Make 'SurfaceGLES::WrapFBO' pass attachment validation

- shell/platform/darwin/common/framework/Headers/FlutterCodecs.h
See also: 
- https://github.com/flutter/engine/pull/35814#issuecomment-1235707485
- b/244680558 …
> Revert "Fixed the nullability annotation on codec `writeValue:` (#35814)

- shell/platform/fuchsia/flutter/tests/integration/README.md
- tools/fuchsia/devshell/run_integration_test.sh
Tested: `run_integration_tests.sh embedder --no-lto`
> [fuchsia] Add script for running integration tests

- impeller/geometry/geometry_unittests.cc
- impeller/geometry/matrix.h
- impeller/geometry/scalar.h
This utility checks if each basis vector is aligned to unique axes. I wrote this as part of an experimental change to turn off anti aliasing in some cases.
> [Impeller] Add utility to check if a Matrix is aligned

- impeller/entity/contents/filters/color_matrix_filter_contents.cc
- impeller/entity/entity_unittests.cc
- impeller/entity/shaders/color_matrix_color_filter.frag
fix https://github.com/flutter/flutter/issues/111012
Color matrix 
```
FilterContents::ColorMatrix matrix = {
0, 0, 0, 0, 0,  //
1, 0, 0, 0, 0,  //
0, 0, 0, 0, 0,  //
0, 0, 0, 1, 0,  //
};
```
> [Impeller] Make color matrix filter work as expected

- README.md
The build badge was created by cirrus that is not used on engine repo anymore. …
> Remove build badge and add scorecards badge.

- shell/platform/android/io/flutter/embedding/android/FlutterActivity.java
- shell/platform/android/test/io/flutter/embedding/android/FlutterActivityTest.java
- shell/platform/android/test_runner/build.gradle
Reverts flutter/engine#35678
See b/244800049
> Revert "Support basic back navigation in Android 13/API 33"

- sky/tools/create_macos_gen_snapshots.py
- testing/symbols/verify_exported.dart
Update script to handle the process of creating the zip file. …
> Zip gen snapshot

- DEPS
Includes:
* Enable native Windows on Arm build (flutter/buildroot#612)
Issue: https://github.com/flutter/flutter/issues/62597 …
> Roll buildroot to a237fca3756ea1580ab05b0c3f6f8fde722731ef

- ci/licenses_golden/licenses_flutter
- impeller/display_list/display_list_dispatcher.cc
- impeller/display_list/display_list_unittests.cc
- impeller/entity/BUILD.gn
- impeller/entity/contents/filters/filter_contents.cc
- impeller/entity/contents/filters/filter_contents.h
- impeller/entity/contents/filters/inputs/filter_contents_filter_input.cc
- impeller/entity/contents/filters/inputs/filter_input.cc
- impeller/entity/contents/filters/inputs/filter_input.h
- impeller/entity/contents/filters/matrix_filter_contents.cc
- impeller/entity/contents/filters/matrix_filter_contents.h
This is missing some stuff like the sampling mode which I plan to add in a follow-up. For the local matrix filter I'll probably just add an option to `MatrixFilterContents` as well.
> [Impeller] Implement matrix filter

- shell/platform/embedder/embedder.cc
- shell/platform/embedder/tests/embedder_unittests.cc
Fixes https://github.com/flutter/flutter/issues/111189
> Populate dart_library_sources_kernel in the embedder library in JIT mode

- shell/platform/android/io/flutter/embedding/android/FlutterActivity.java
- shell/platform/android/test/io/flutter/embedding/android/FlutterActivityTest.java
- shell/platform/android/test_runner/build.gradle
Alongside triaging the larger roll. cherry pick for a smaller roll CL that cover ~30 commits.
> [cherry pick] Revert "Support basic back navigation in Android 13/API 33" (#36001)

- impeller/base/version.cc
- impeller/base/version.h
CP of https://github.com/flutter/engine/pull/36009 for https://github.com/flutter/flutter/issues/110936
> [Impeller] Avoid using the major and minor variable names. (#36009)

- flow/compositor_context.cc
- flow/compositor_context.h
- flow/diff_context.cc
- flow/diff_context.h
- flow/layers/clip_shape_layer.h
- flow/layers/color_filter_layer.cc
- flow/layers/display_list_layer.cc
- flow/layers/display_list_layer_unittests.cc
- flow/layers/image_filter_layer.cc
- flow/layers/opacity_layer.cc
- flow/layers/opacity_layer_unittests.cc
- flow/layers/shader_mask_layer.cc
- flow/raster_cache.cc
- flow/raster_cache_util.h
- flow/testing/diff_context_test.cc
- flow/testing/diff_context_test.h
> add pixel snapping conditional on presence of raster cache (#35981)

- impeller/aiks/aiks_unittests.cc
- impeller/entity/contents/tiled_texture_contents.cc
- impeller/entity/shaders/tiled_texture_fill.frag
Follow up from https://github.com/flutter/engine/pull/36100
> [Impeller] add alpha to tiled texture

- lib/ui/natives.dart
- testing/dart/observatory/vmservice_methods_test.dart
Fixes https://github.com/flutter/flutter/issues/111408
> [Impeller] expose renderer choice in service extensions

- lib/ui/platform_dispatcher.dart
- shell/platform/android/io/flutter/embedding/engine/FlutterJNI.java
- shell/platform/android/io/flutter/embedding/engine/dart/DartMessenger.java
- shell/platform/android/io/flutter/embedding/engine/dart/PlatformMessageHandler.java
- shell/platform/android/platform_message_handler_android.cc
- shell/platform/android/platform_message_handler_android.h
- shell/platform/android/platform_view_android_jni_impl.cc
This provides all the work for handling platform channels in the Dart->Host direction for Android.  For more details and integration tests see the framework PR.
Integration tests exist in the framework PR.
companion framework PR: https://github.com/flutter/flutter/pull/111279
companion engine PR (iOS): https://github.com/flutter/engine/pull/35174
issue: https://github.com/flutter/flutter/issues/13937 …
> Started handling messages from background isolates for Android

- shell/platform/android/io/flutter/plugin/platform/SingleViewPresentation.java
- testing/scenario_app/android/BUILD.gn
- testing/scenario_app/android/app/src/androidTest/java/dev/flutter/scenariosui/PlatformViewWithSurfaceViewBadContextUiTest.java
- testing/scenario_app/android/app/src/main/java/dev/flutter/scenarios/PlatformViewsActivity.java
- testing/scenario_app/android/app/src/main/java/dev/flutter/scenarios/SurfacePlatformViewFactory.java
- testing/scenario_app/lib/src/platform_view.dart
Cherry-picks https://github.com/flutter/engine/pull/35997 to the stable branch.
> CP 3.3: Remove context assertion from Android platform views using Virtual Display

- ci/licenses_golden/licenses_flutter
- impeller/aiks/paint.cc
- impeller/display_list/display_list_unittests.cc
- impeller/entity/BUILD.gn
- impeller/entity/contents/clip_contents.cc
- impeller/entity/contents/color_source_contents.cc
- impeller/entity/contents/color_source_contents.h
- impeller/entity/contents/linear_gradient_contents.cc
- impeller/entity/contents/radial_gradient_contents.cc
- impeller/entity/contents/solid_color_contents.cc
- impeller/entity/contents/solid_color_contents.h
- impeller/entity/contents/solid_fill_utils.cc
- impeller/entity/contents/solid_fill_utils.h
- impeller/entity/contents/sweep_gradient_contents.cc
- impeller/entity/contents/tiled_texture_contents.cc
fix https://github.com/flutter/flutter/issues/111314
> [Impeller] Make 'DrawPaint' support color sources

- shell/platform/fuchsia/flutter/flatland_external_view_embedder.cc
- shell/platform/fuchsia/flutter/flatland_external_view_embedder.h
- shell/platform/fuchsia/flutter/tests/fakes/scenic/fake_flatland_types.h
- shell/platform/fuchsia/flutter/tests/flatland_external_view_embedder_unittests.cc
This CL populates the newly added Inset field with the occlusion hint information.
Bug: fxb/71846
> [fuchsia] Use the newly added View Inset field

- lib/web_ui/lib/src/engine/canvaskit/canvaskit_api.dart
- lib/web_ui/lib/src/engine/canvaskit/renderer.dart
- lib/web_ui/lib/src/engine/canvaskit/text.dart
- lib/web_ui/test/canvaskit/font_variation_golden_test.dart
See https://github.com/flutter/flutter/issues/33709
> Variable font support for the Flutter Web CanvasKit renderer

- sky/tools/create_macos_framework.py
The symlinks are pointing to themselves. …
> Add path to current versions in the symlinks.

- ci/licenses_golden/licenses_flutter
- shell/platform/embedder/BUILD.gn
- shell/platform/embedder/embedder_exports.lst
- testing/symbols/verify_exported.dart
See https://github.com/flutter/flutter/issues/106453
> Use a linker script to export only the required symbols in the Linux embedder library

- shell/platform/android/test/README.md
> Mention the need to rebuild before running tests

- third_party/tonic/converter/dart_converter.h
Well I come again... Again fix one single word typo... Hope there exist a lighter method to do so!
[testing the …
> Fix typo again

- .ci.yaml
Adds Mac iOS Engine target to flutter/recipes CQ. This will ensure that changes to flutter/recipes pass on the Mac iOS Engine target before landing.
The recipes code has a temporary workaround to resolve a P0 related to Mac iOS Engine. A proper workaround has been readied, but the Mac iOS Engine target fails to build and test when run as an individual tryjob in a CL. This is because running it individually does not pass it the necessary config. This change will make the Mac iOS Engine target run for every flutter/recipes CL and with proper config, which will let us validate changes that affect it.
https://github.com/flutter/flutter/issues/111226
https://github.com/flutter/flutter/issues/111193
If you need help, consider asking for advice on the …
> Enable Mac iOS Engine in recipes tests

- shell/platform/fuchsia/flutter/flatland_external_view_embedder.cc
- shell/platform/fuchsia/flutter/tests/fakes/scenic/fake_flatland.cc
- shell/platform/fuchsia/flutter/tests/fakes/scenic/fake_flatland.h
- shell/platform/fuchsia/flutter/tests/fakes/scenic/fake_flatland_types.cc
- shell/platform/fuchsia/flutter/tests/fakes/scenic/fake_flatland_types.h
- shell/platform/fuchsia/flutter/tests/flatland_external_view_embedder_unittests.cc
> Revert "fxbug.dev/94000: Set Opacity and Scale Flatland Values for Flatland Embedder"

- ci/licenses_golden/licenses_flutter
- lib/ui/platform_dispatcher.dart
- shell/common/platform_message_handler.h
- shell/common/shell.cc
- shell/common/shell_unittests.cc
- shell/platform/android/platform_message_handler_android.h
- shell/platform/darwin/ios/platform_message_handler_ios.h
- shell/platform/embedder/BUILD.gn
- shell/platform/embedder/platform_view_embedder.cc
- shell/platform/embedder/platform_view_embedder.h
- shell/platform/embedder/platform_view_embedder_unittests.cc
framework pr: https://github.com/flutter/flutter/pull/110882
issue: https://github.com/flutter/flutter/issues/13937 …
> Isolate platform channels for desktop

- lib/ui/dart_ui.cc
- lib/ui/painting.dart
- lib/ui/painting/fragment_program.cc
- lib/ui/painting/fragment_shader.cc
- lib/ui/painting/fragment_shader.h
- lib/web_ui/lib/painting.dart
- testing/dart/fragment_shader_test.dart
- testing/dart/observatory/shader_reload_test.dart
This is part of the transition to `FragmentShader`.
> Removes FragmentProgram.shader()

- impeller/geometry/geometry_unittests.cc
- impeller/geometry/matrix.h
This PR is for issue: https://github.com/flutter/flutter/issues/111165 …
> [Impeller] Add matrix makerow and makecolumn.

- shell/platform/fuchsia/dart-pkg/fuchsia/pubspec.yaml
- shell/platform/fuchsia/dart_runner/embedder/pubspec.yaml
- shell/platform/fuchsia/dart_runner/vmservice/pubspec.yaml
- shell/platform/fuchsia/flutter/kernel/pubspec.yaml
Enables null safety in compiler.dart and dart_profiler_symbols.dart
Contributes to https://github.com/flutter/flutter/issues/110016, https://github.com/flutter/flutter/issues/110020
No changes were required for these directories besides upgrading the SDK version …
> [fuchsia] enable dart null safety for fuchsia .dart files (part 2)

- shell/platform/fuchsia/flutter/runner.cc
Adds logic to write trace profiles for v2 Fuchsia components
Issue: https://bugs.fuchsia.dev/p/fuchsia/issues/detail?id=88389 …
> [fuchsia] Write trace profiles for v2 Fuchsia components

- DEPS
- ci/licenses_golden/licenses_third_party
Part of a two-step ICU library update.
Issue: https://github.com/flutter/flutter/issues/112227
> [icu] Update icu to 3e03346162e9bdd41850a1184d2713da4add719e

- lib/ui/platform_dispatcher.dart
- runtime/dart_plugin_registrant_unittests.cc
- runtime/fixtures/dart_tool/flutter_build/dart_plugin_registrant.dart
fixes https://github.com/flutter/flutter/issues/112240 …
> Made sure to call the plugin registrant when registering a background isolate

- lib/ui/painting/image_decoder_impeller.cc
> [Impeller] Generate mipmaps for UI images

- impeller/display_list/display_list_unittests.cc
- impeller/entity/shaders/color_matrix_color_filter.frag
> [Impeller] Clamp the resulting color of color matrix filters

- flutter_frontend_server/bin/starter.dart
- flutter_frontend_server/lib/server.dart
- flutter_frontend_server/pubspec.yaml
Remove the @dart language versioning from all the files so that this code runs in strong null safe mode.
> Make flutter frontend server null safe

- BUILD.gn
- impeller/aiks/aiks_unittests.cc
- impeller/geometry/geometry_unittests.cc
- impeller/tools/impeller.gni
All tests are passing with https://github.com/flutter/engine/pull/36404.
> [Impeller] Enable impeller_unittests on Windows

- impeller/compiler/compiler.cc
- impeller/compiler/compiler_unittests.cc
- impeller/compiler/impellerc_main.cc
- impeller/compiler/runtime_stage_data.cc
- impeller/compiler/switches.cc
- impeller/compiler/types.cc
- impeller/compiler/types.h
Fixes https://github.com/flutter/flutter/issues/112241
> [Impeller] Removes unused --flutter-spirv option from the compiler.

- build/archives/BUILD.gn
artifacts.zip is expected to include multiple files in the debug configuration but only gen_snapshot in all the others. This PR is adding that logic to the archive gn target.
Bug: https://github.com/flutter/flutter/issues/112187 …
> Add gen_snapshot only for non debug versions of artifacts.

- impeller/renderer/backend/vulkan/context_vk.cc
- impeller/renderer/backend/vulkan/render_pass_vk.cc
Fixes: https://github.com/flutter/flutter/issues/112392
> [Impeller] Flip the viewport on vulkan

- DEPS
- ci/licenses_golden/licenses_third_party
- ci/licenses_golden/tool_signature
- tools/licenses/lib/licenses.dart
- tools/licenses/lib/main.dart
Buildroot PR: https://github.com/flutter/buildroot/pull/627
> [Impeller] Update buildroot with json.hpp and tinygltf

- ci/builders/linux_host_engine.json
Spirv rules were removed here:
https://github.com/flutter/engine/commit/825e457449a7dbe23709a49591ca733d616069d3. …
> Remove spirv target.

- lib/snapshot/BUILD.gn
Adds doc comments to lib/snapshot/BUILD.gn prior to refactoring.
Issue: https://github.com/flutter/flutter/issues/103386 …
> Adds documentation for core snapshot targets

- shell/platform/fuchsia/flutter/flatland_external_view_embedder.cc
Currently, the hit-region is size FLT_MAX which is susceptible to numerical overflow when rotating or translating (or any other modification to the value). This reduces the size so that issues do not occur. This is a short-term solution, with perhaps a better solution down the pipeline accounted for in Flatland itself.
Issue Fixed: https://github.com/flutter/flutter/issues/111292
> [flatland] Reduce size of hit-region.

- lib/snapshot/BUILD.gn
Cleans up the logic for building gen_snapshot for macOS hosts. Also adds a bit more documentation to the snapshot-related build targets.
Previously:
* `gen_snapshot` targeting macOS (on both x64, and arm64) were generated via the `create_macos_gen_snapshots` target.
* `gen_snapshot` arm/arm64 builds (on a macOS host) were generated via the `create_arm_gen_snapshot` target. The reason why this covers only arm/arm64 is simply that those are the only platforms we generate iOS/Android AOT builds for. x64 iOS implies a simulator build, but we only support debug builds for the iOS simulator, which aren't AOT builds, and thus don't require gen_snapshot.
These two conditions overlap in the case of arm64 (but not x64) target builds. This patch separates the two cases cleanly. A later patch will …
> [macOS] Deduplicate gen_snapshot creation targets

- ci/builders/mac_host_engine.json
artifacts.zip file was not being generated for mac arm64. …
> Add artifacts.zip for mac_arm64.

- sky/tools/create_macos_gen_snapshots.py
create_macos_gen_snapshots.py uses `xcrun bitcode_strip` to copy gen_snapshot from its build directory to a `suffixed gen_snapshot_arm64` or `gen_snapshot_armv7`, while stripping the bitcode segment, if any.
This simplifies the python invocation to use `subprocess.check_call`, and also guarantees the process exits with failure in such a situation -- we weren't checking the return value of `generate_gen_snapshot`. This also makes it consistent with the macOS-specific variant of this code (`gen_snapshots.py`).
This is cleanup for issues encountered while working on merging macOS/iOS gen_snapshot tooling.
Issue: https://github.com/flutter/flutter/issues/103386
If you need help, consider asking for …
> [macOS] Clean up gen_snapshot copy invocation

- flutter_frontend_server/bin/starter.dart
- flutter_frontend_server/lib/server.dart
- flutter_frontend_server/pubspec.yaml
Make flutter frontend server null safe.
Merging of this PR needs to be coordinated with @CaseyHillers
> Make Flutter frontend server Null safe.

- lib/web_ui/lib/src/engine/canvaskit/noto_font.dart
- lib/web_ui/test/canvaskit/fallback_fonts_golden_test.dart
Fixes https://github.com/flutter/flutter/issues/77212 …
> [canvaskit] Fix bug in fallback font binary search

- impeller/compiler/shader_lib/impeller/color.glsl
- impeller/display_list/display_list_unittests.cc
- impeller/entity/shaders/linear_to_srgb_filter.frag
- impeller/entity/shaders/srgb_to_linear_filter.frag
This PR fixed the issue https://github.com/flutter/flutter/issues/112456
Before fix:
After fix: …
> [Impeller] Make 'linearToSrgbGamma' and 'srgbToLinearGamma' work as  expected

- ci/builders/mac_host_engine.json
The fonts artifact was not being generated for arm64 and some devicelab tests were failing.
[breaking …
> Generate fonts.zip for arm64.

- shell/common/rasterizer_unittests.cc
- shell/platform/android/android_egl_surface.cc
Fixes stuttery scrolling on 3.3
> Revert egl presentation time (#36485)

- lib/snapshot/BUILD.gn
This migrates the `create_arm_gen_snapshot` target used to create a copy of gen_snapshot suffixed with its target CPU architecture using the same `strip_bitcode` macro used for the equivalent target used for desktop gen_snapshot.
In a followup patch, these will be merged to a single target. They currently still have incompatible output paths.
Issue: https://github.com/flutter/flutter/issues/103386
Issue: https://github.com/flutter/flutter/issues/107884
[Flutter …
> Use strip_bitcode for create_arm_gen_snapshot

- lib/web_ui/dev/steps/run_tests_step.dart
- lib/web_ui/dev/test_runner.dart
This PR makes it possible to use `felt test -w ...files` again.
> [web] Fix 'felt test' watch mode

- DEPS
Includes:
* Enable SIMD support for Windows on ARM (93ab170)
Issue: https://github.com/flutter/flutter/issues/62597 …
> Roll libpng to 93ab170cb436a244c3b3278c0f13ee82c60145a7

- .ci.yaml
This is to start making changes impacting recipes_v2 block that tree. …
> Move Linux host engine recipes_v2 to prod.

- DEPS
Includes:
* Enable NEON on all Flutter-supported ARM platforms (9187b6e)
Issue: https://github.com/flutter/flutter/issues/62597 …
> Roll libpng to 9187b6e12756317f6d44fc669ac11dfc262bd192

- .ci.yaml
The builder has been ready for a few weeks and has been fully tested in staging. …
> Move mac_host_engine to prod.

- .ci.yaml
New capacity has already been added to support running engine_v2 builders in addition to the old builds but we will move them in small batches to ensure their healthiness in at par with old builds. …
> Move Linux_arm and Linux_aot engine v2 builders to prod.

- lib/ui/window/platform_message_response_dart_port.cc
Dart will copy the contents of a Dart_CObject.as_typed_data buffer
See https://github.com/dart-lang/sdk/issues/49827
> Avoid making an extra copy of PlatformMessageResponseDartPort data

- .ci.yaml
- build/copy_info_plist.py
- ci/builders/mac_ios_engine.json
- ci/builders/mac_ios_engine_profile.json
- ci/builders/mac_ios_engine_release.json
- shell/platform/darwin/ios/BUILD.gn
- shell/platform/embedder/BUILD.gn
- tools/gn
Deprecate `--bitcode` flags without removing them, until recipe can be updated.  This does not cover removing the `strip_bitcode` logic https://github.com/flutter/engine/pull/36510.
https://ci.chromium.org/p/flutter/builders/try/Mac%20iOS%20Engine%20Release/628
Flutter projects no longer build with bitcode: https://github.com/flutter/flutter/issues/111776 and https://github.com/flutter/flutter/issues/107883
Part of https://github.com/flutter/flutter/issues/107884
Recipe side at https://flutter-review.googlesource.com/c/recipes/+/34583 …
> Stop compiling iOS with bitcode

- lib/web_ui/lib/src/engine/canvaskit/picture.dart
- lib/web_ui/test/canvaskit/canvaskit_api_test.dart
- lib/web_ui/test/canvaskit/image_golden_test.dart
- lib/web_ui/test/canvaskit/image_test.dart
- lib/web_ui/test/canvaskit/layer_test.dart
- lib/web_ui/test/canvaskit/picture_test.dart
- lib/web_ui/test/canvaskit/scene_test.dart
Addresses most issues of https://github.com/flutter/flutter/issues/109265 …
> [canvaskit] Allow Picture.readPixels when in CPU-only mode

- ci/builders/mac_ios_engine_profile.json
Fix typo in json from https://github.com/flutter/engine/pull/36596 for v2 recipes not running in PRs.
https://ci.chromium.org/p/flutter/builders/staging/Mac%20mac_ios_engine_profile/6682 …
> Remove trailing json comma in mac_ios_engine_profile.json

- impeller/renderer/backend/metal/device_buffer_mtl.mm
- impeller/typographer/backends/skia/text_render_context_skia.cc
Reverts flutter/engine#36466
Probably caused simulator problems discussed in b/249121691
> Revert "[Impeller] Use fast path for CPU generated textures where possible"

- DEPS
Pick up https://github.com/flutter/buildroot/pull/634
Fixes https://github.com/flutter/flutter/issues/107885 …
> Roll buildroot for bitcode property removal

- .ci.yaml
There were three different issues identified as when running this build in prod. We are moving it back to staging while we fix the issues to prevent impacting the tree greeness.
Bug: https://github.com/flutter/flutter/issues/113068
Bug: https://github.com/flutter/flutter/issues/113066
Bug: https://github.com/flutter/flutter/issues/113065 …
> Move mac_host_engine to bringup.

- DEPS
Also move some of the github dependencies to use dart mirrors.
Bug: https://github.com/flutter/flutter/issues/113052 …
> Update the list of allowed hosts.

- lib/web_ui/lib/src/engine/text/canvas_paragraph.dart
- lib/web_ui/test/text/canvas_paragraph_test.dart
fixes https://github.com/flutter/flutter/issues/113234 …
> Apply text affinity fix to html rendering

- DEPS
The repository on fuchsia.googlesource.com has been deleted
> Pull libcxx from llvm.googlesource.com

- testing/scenario_app/ios/Scenarios/Scenarios.xcodeproj/project.pbxproj
- testing/scenario_app/ios/Scenarios/Scenarios/Info_Impeller.plist
- testing/scenario_app/run_ios_tests.sh
Create a copy of the Info.plist with `FLTEnableImpeller` set to true. Run the scenario tests a second time pointed at that Info.plist.
https://ci.chromium.org/p/flutter/builders/try/Mac%20Unopt/19565
> 2022-10-06 17:13:22.112348-0700 Scenarios[6347:1178387] [VERBOSE-2:ios_context_metal_impeller.mm(22)] Using the Impeller rendering backend.
Skip two tests failing only with impeller: https://github.com/flutter/flutter/issues/113250 and https://github.com/flutter/flutter/issues/113251
Fixes https://github.com/flutter/flutter/issues/113057 …
> Run iOS Scenario apps with Skia and Impeller

- lib/web_ui/lib/src/engine/canvaskit/embedded_views.dart
- lib/web_ui/lib/src/engine/canvaskit/picture.dart
- lib/web_ui/lib/src/engine/canvaskit/surface_factory.dart
- lib/web_ui/test/canvaskit/h5vcc_test.dart
- lib/web_ui/test/canvaskit/surface_factory_test.dart
- lib/web_ui/test/canvaskit/surface_test.dart
Fixes https://github.com/flutter/flutter/issues/113094 …
> [canvaskit] Maintain a Surface dedicated to Picture.toImage

- DEPS
Reverts flutter/engine#36765
This time the autoroller has been stopped.
> Revert "Roll Clang from 039b969b32b6 to f85c1f3b7c0b"

- DEPS
- ci/licenses_golden/licenses_third_party
- tools/gn
- vulkan/vulkan_interface.h
Fixes https://github.com/flutter/flutter/issues/112248
> Roll vulkan-deps

- tools/activate_emsdk.py
Fixes https://github.com/flutter/flutter/issues/110897 …
> Suppress stdout when activating emsdk

- fml/memory/weak_ptr.h
Constructing a WeakPtr from a TaskRunnerAffineWeakPtr is undesirable because the resulting WeakPtr will get default WeakPtr thread checking behavior.
See https://github.com/flutter/engine/pull/36772
> Change TaskRunnerAffineWeakPtr to no longer be a subclass of WeakPtr

- ci/licenses_golden/licenses_flutter
- impeller/display_list/display_list_dispatcher.cc
- impeller/entity/BUILD.gn
- impeller/entity/contents/runtime_effect_contents.cc
- impeller/entity/contents/runtime_effect_contents.h
- impeller/entity/entity_unittests.cc
- impeller/entity/shaders/position_no_color.vert
- impeller/fixtures/BUILD.gn
- impeller/fixtures/runtime_stage_example.frag
- impeller/playground/playground.cc
- impeller/playground/playground.h
- impeller/renderer/backend/metal/shader_library_mtl.mm
- impeller/runtime_stage/BUILD.gn
- impeller/runtime_stage/runtime_types.cc
- impeller/runtime_stage/runtime_types.h
- lib/ui/painting/fragment_program.cc
Reland with param fix. Reverted in https://github.com/flutter/engine/pull/36883
> [Impeller] Reland RuntimeEffectContents

- lib/ui/painting/multi_frame_codec.cc
Fix an include path to make it consistent with other include paths.
> Fixes an include path

- shell/platform/darwin/ios/framework/Source/FlutterViewController.mm
> [iOS] Add autorelease for window scene geometry preferences object

- .ci.yaml
Linux builders have been stable and we also need the mac_host_builder running on presubmit to calculate GoB quotas and request increases.
Metrics collection for the try service account is rolling out today and we will be monitoring the quotas.
Bug: https://github.com/flutter/flutter/issues/113213 …
> Move linux aot and mac host engine v2 builders to prod.

- shell/platform/android/test/README.md
- shell/platform/android/test/io/flutter/plugin/platform/PlatformViewsControllerTest.java
- shell/platform/android/test_runner/build.gradle
- shell/platform/android/test_runner/src/main/resources/robolectric.properties
Reverts flutter/engine#34272
Speculative revert for https://github.com/flutter/flutter/issues/114036
cc @utzcoz @jason-simmons
> Revert "Re-landing Robolectric 4.8.1"

- lib/web_ui/dev/build.dart
> [web] Fix typos in `felt build` help docs

- DEPS
- shell/platform/windows/window_proc_delegate_manager_unittests.cc
- tools/dia_dll.py
*This reapplies https://github.com/flutter/engine/pull/36538 which was reverted by https://github.com/flutter/engine/pull/36606 as it uncovered https://github.com/flutter/flutter/issues/113728.*
Use Visual Studio 2019 to build the engine.
This is a requirement to roll ANGLE as it is affected by an STL bug if built using Visual Studio 2017: [angleproject#7693](https://bugs.chromium.org/p/angleproject/issues/detail?id=7693)
Depends on: https://github.com/flutter/buildroot/pull/643
Part of: https://github.com/flutter/flutter/issues/110948 …
> [Windows] Move to Visual Studio 2019

- impeller/compiler/compiler.cc
This is required by: https://github.com/flutter/flutter/pull/114214
> [Impeller] Provide graphics backend defines to runtime stage shaders

- shell/platform/linux/fl_key_embedder_responder.cc
- shell/platform/linux/fl_key_embedder_responder_test.cc
This PR adds a check to avoid Shift + AltLeft throwing an exception on Linux.
The issue occurs because Shift + AltLeft is usually configured to be MetaLeft key.
The exception is thrown because the GDK event received by the engine code has its keyval pointing to MetaLeft but its keycode pointing to either Shift or Alt (depending on which was last pressed). As engine code use keycode to lookup the physical key and keyval to lookup the logical key, this results in a FlutterKeyEvent with a mismatch between logical and physical keys which leads to wrong key event being sent.
The fix here relies on two steps:
- for each key event, check if the physical key (deduced from the keycode) is the same as one of the known modifier primary physical key.
- if it is, use the logical key (deduced from the …
> [Lixux] fix pressing Shift+AltLeft throws

- .ci.yaml
This will allow the release_builder recipe to run these tasks.
Bug:b/232552448
- [] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on writing and running engine tests.
[Tree …
> Add release_builder:True property for Linux linux* builders.

- testing/dart/fragment_shader_test.dart
- testing/run_tests.py
RE: https://github.com/flutter/engine/pull/37123/files/45b1f900741ffbf45c9b69adb6de6087bff742af..608492938456bbdf829cf7ae5cc043f1790541bf#diff-0057703d136857f3c1b53aeae59d04eab619f4016dd150460ab74fb6d00f6c7b
> use shader utils for JSON test

- DEPS
CP: 85f6a6fc604df2943d6f061c4ba95d2485131737
[Discord]: …
> CP: Adds a release_candidate variable to DEPS. (#36978)

- tools/gn
In [angle@54dfb62](https://github.com/google/angle/commit/54dfb62c24ddd0fb825c874ad00ddbbd769fa2bc), ANGLE made the "force context check" flag off by default [to improve performance](https://chromium-review.googlesource.com/c/angle/angle/+/2809855). Disabling this flag uncovered several bugs in ANGLE's D3D11 renderer that can cause [Flutter 3.3.0+ to crash](https://github.com/flutter/flutter/issues/110311). This change re-enables the "force context check" flag, bringing Flutter back to the last known good state used by Flutter 3.0.5 and earlier.
Fixes https://github.com/flutter/flutter/issues/110311
Per the ANGLE team:
> This flag is to allow our D3D11 backend to be multithreaded at the cost of additional synchronization. If flutter is using ANGLE from multiple threads on Windows, you …
> [ANGLE] Re-enable ANGLE's "force context check" build flag

- ci/licenses_golden/licenses_flutter
- impeller/compiler/shader_lib/flutter/runtime_effect.glsl
- impeller/fixtures/ink_sparkle.frag
- impeller/fixtures/simple.vert
- lib/ui/fixtures/shaders/general_shaders/uniforms_sorted.frag
In support of https://github.com/flutter/flutter/pull/114214.
> [Impeller] Add FlutterFragCoord to impellerc shader lib

- DEPS
- ci/licenses_golden/licenses_skia
https://github.com/flutter/flutter/issues/114174
> [CP] Roll skia to 93643

- ci/licenses_golden/licenses_flutter
- shell/gpu/BUILD.gn
- shell/gpu/gpu_surface_vulkan_impeller.cc
- shell/gpu/gpu_surface_vulkan_impeller.h
- vulkan/vulkan_native_surface_android.h
- vulkan/vulkan_swapchain.cc
This is the base class that holds the reference to the ContextVK and is going to be used by Android implementation.
> [Impeller] Implement GPU Surface Vulkan for Impeller

- impeller/renderer/backend/vulkan/context_vk.cc
- impeller/renderer/backend/vulkan/context_vk.h
This is going to be used for creating a surface from Android native window.
> [Impeller] Context VK can create vulkan surface from Android Native Window

- shell/common/pipeline.h
> Remove unused variable `depth_`

- impeller/compiler/BUILD.gn
- impeller/compiler/shader_lib/BUILD.gn
- impeller/compiler/shader_lib/flutter/BUILD.gn
- impeller/compiler/shader_lib/impeller/BUILD.gn
- impeller/tools/impeller.gni
This allows shader lib includes to work when specifying a local engine.
> [Impeller] Copy shaders lib to output directory

- .ci.yaml
https://github.com/flutter/flutter/issues/114722
> Run Linux Web Engine builds on 32-core bots

- DEPS
- tools/gn
Engine side of https://github.com/flutter/buildroot/pull/645
> Narrow the scope of the Windows Android arm hack

- lib/web_ui/test/canvaskit/image_golden_test.dart
This is a regression test for https://github.com/flutter/flutter/issues/94895 …
> [canvaskit] Add test for image readPixels

- DEPS
- lib/web_ui/dev/canvaskit_lock.yaml
- lib/web_ui/lib/src/engine/configuration.dart
> Roll CanvasKit to 0.37.1

- shell/platform/android/io/flutter/embedding/android/FlutterView.java
> Fixes a typo.

- impeller/compiler/spirv_sksl.cc
Fixes https://github.com/flutter/flutter/issues/110961
> [Impeller] error earlier on uint types

- flutter_frontend_server/test/fixtures/.dart_tool/package_config.json
Update language version in flutter_frontend_server/test/fixtures package in preparation for the Dart VM running by default in sound null safe mode.
> Update language version in flutter_frontend_server/test/fixtures package

- lib/web_ui/test/text_editing_test.dart
Reverts flutter/engine#37642
Failing tests https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Web%20Engine/14151/overview
> Revert "[web] Update text editing test skips"

- .ci.yaml
This is to open the tree while downloading firefox is fixed.
Bug: https://github.com/flutter/flutter/issues/115404 …
> Mark Linux Web Engine Bringup.

- impeller/playground/backend/vulkan/playground_impl_vk.cc
- shell/platform/android/android_surface_vulkan_impeller.cc
Otherwise looking these up fails at runtime.
> [Impeller] register modern shaders on Vulkan too

- lib/ui/painting.dart
Fixes https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20analyze/45095/overview
> fix docs analysis error on setImageSampler

- .clang-tidy
Turn on checks:
- [darwin-avoid-spinlock](https://clang.llvm.org/extra/clang-tidy/checks/darwin/avoid-spinlock.html)
- [darwin-dispatch-once-nonstatic](https://clang.llvm.org/extra/clang-tidy/checks/darwin/dispatch-once-nonstatic.html) …
> Turn on darwin-* clang-tidy checks

- impeller/scene/geometry.cc
- impeller/scene/geometry.h
- impeller/scene/material.cc
- impeller/scene/material.h
- impeller/scene/scene.cc
- impeller/scene/scene_context.cc
- impeller/scene/scene_context.h
- impeller/scene/scene_encoder.cc
- impeller/scene/scene_encoder.h
- impeller/scene/static_mesh_entity.cc
* Render pass.
* Resolve pipelines
* Encode commands.
* Placeholder texture with lifetime of the scene.
> [Impeller Scene] Command encoding

- .github/workflows/scorecards-analysis.yml
Using the 20.04 version of ubuntu rather than `latest` in order to resolve the setup-python action issue seen here https://github.com/flutter/engine/actions/runs/3569403428/jobs/5999334521#step:3:9
Following other approaches from the bug here https://github.com/actions/setup-python/issues/162
This change is only for the vulnerability scanning job because that job has the setup-python action causing failure. …
> Ubuntu Version For Vulnerability Scanning

- shell/platform/android/android_egl_surface.cc
CP of https://github.com/flutter/engine/pull/37493
> [CP] Remove glitches when scrolling on old Android TV devices (#37493)

- shell/platform/darwin/ios/framework/Source/FlutterPlatformViews.mm
CP of https://github.com/flutter/engine/pull/37107 into flutter-3.7-candidate.1 for https://github.com/flutter/flutter/issues/114784
> [CP] PlatformViews needs clipRect (#37107)

- DEPS
Buildroot bump for https://github.com/flutter/buildroot/pull/654.
> Bump buildroot

- impeller/entity/contents/text_contents.cc
- impeller/typographer/backends/skia/text_frame_skia.cc
- impeller/typographer/backends/skia/text_render_context_skia.cc
- impeller/typographer/font.h
- impeller/typographer/glyph.h
- impeller/typographer/text_frame.cc
- impeller/typographer/typographer_unittests.cc
CP of https://github.com/flutter/engine/pull/38024.
> [CP] [Impeller] Pack 👏 the 👏 atlas 👏 (#38024)

- lib/web_ui/lib/src/engine/canvaskit/embedded_views.dart
- lib/web_ui/test/canvaskit/embedded_views_test.dart
This is the CP PR for https://github.com/flutter/flutter/issues/116574 into 3.3 stable
> [CP] Fixed visibility of embedded views in safari (google map, video, camera preview etc)

- lib/ui/painting.dart
Fixes https://github.com/flutter/flutter/issues/107929
> [ui] add link to website for fragment shaders

- flow/layers/clip_path_layer_unittests.cc
- flow/layers/clip_rect_layer_unittests.cc
- flow/layers/clip_rrect_layer_unittests.cc
- flow/layers/clip_shape_layer.h
- flow/layers/opacity_layer.cc
- flow/layers/opacity_layer_unittests.cc
- flow/layers/platform_view_layer_unittests.cc
- flow/testing/mock_embedder.cc
- flow/testing/mock_embedder.h
This is a cherry-pick PR for https://github.com/flutter/engine/pull/38159 into the beta branch candidate.
> [CP] Remove LayerStateStack premature culling

- impeller/scene/animation/animation_player.h
context: https://b.corp.google.com/issues/264388135
quick PR to unblock flutter roll.
> [flutter roll] quick fix to import map

- .ci.yaml
- shell/platform/fuchsia/flutter/gfx_external_view_embedder.cc
Cherry-pick fix for b/262417298 into fuchsia_r51a release
> Remove strict equality check for SkMatrix comparison (#38665)

- DEPS
Rolls flutter/packages to 25454e63851fe7933f04d025606e68c1eac4fe0f
> Roll flutter/packages to 25454e

- lib/web_ui/lib/src/engine/html/bitmap_canvas.dart
- lib/web_ui/lib/src/engine/html/clip.dart
- lib/web_ui/lib/src/engine/html/dom_canvas.dart
- lib/web_ui/test/html/drawing/canvas_lines_golden_test.dart
> Revert "fix canvas drawLine bugs"

- impeller/scene/animation/animation_clip.h
We use a different STL too apparently.
> Add include to make g3 happy

- lib/web_ui/lib/src/engine/semantics/tappable.dart
- lib/web_ui/test/engine/semantics/semantics_test.dart
CP : [641623a](https://github.com/flutter/engine/commit/641623a512cda97b9383cbe1eea1fcdcb79a39b9)
b/265930899
cherry picks https://github.com/flutter/engine/pull/38958
fixes https://github.com/flutter/flutter/issues/118651.
this cherrypick was requested by family link team
> [release +  cherry pick] wrap focus() in a post update callback (#38958)

- impeller/aiks/aiks_unittests.cc
- impeller/entity/entity_pass.cc
Cherry-pick of https://github.com/flutter/engine/commit/0d79533876c7e10ad28bca48d65ba4419f444dee into `flutter-3.7-candidate.1`
> [Impeller] Fix back-to-back clip restoration (#38964)

- impeller/display_list/display_list_unittests.cc
- impeller/display_list/display_list_vertices_geometry.cc
Cherry-pick of https://github.com/flutter/engine/commit/dd8c259bb4ea92e2382616304dd7028293f5f620 into `flutter-3.7-candidate.1`
> [CP] [Impeller] Account for the transform in DLVerticesGeometry coverage

- shell/platform/fuchsia/flutter/tests/integration/embedder/flutter-embedder-test.cc
> [fuchsia] Migrate to new RealmBuilder API

- impeller/compiler/spirv_sksl.cc
unblock misguided attempts to build impellerc from source
> [impellerc] remove coffset usage

- shell/platform/fuchsia/dart_runner/meta/common.shard.cml
- shell/platform/fuchsia/flutter/meta/common.shard.cml
Aligns with https://fuchsia-review.git.corp.google.com/c/fuchsia/+/792471
> [fuchsia] Diagnostics directory rights are R*

- impeller/display_list/display_list_unittests.cc
- impeller/entity/geometry.cc
- impeller/geometry/path.cc
- impeller/geometry/path.h
- impeller/geometry/path_component.cc
- impeller/geometry/path_component.h
Cherry-pick of https://github.com/flutter/engine/commit/c068a3675ac360e4b5e1acd6c8ee0f445324fd3b for `flutter-3.7-candidate.1`.
> [CP] [Impeller] Use analytical normals for stroke caps

- impeller/entity/contents/text_contents.cc
- impeller/entity/shaders/glyph_atlas.frag
- impeller/entity/shaders/glyph_atlas.vert
- impeller/geometry/geometry_unittests.cc
- impeller/geometry/matrix.h
CP of https://github.com/flutter/engine/commit/5405f2c26e85a3280f4e1b0ecce3ec7c7f097d46 followed by https://github.com/flutter/engine/commit/55bb8deaf7f47ac6a5fc6fe98f95b7eab8e0214a into `flutter-3.7-candidate.1`
> [CP][Impeller] Switch to nearest sampling for the text atlas

- tools/fuchsia/build_fuchsia_artifacts.py
Missed in https://github.com/flutter/engine/pull/39133
The tree is closed on this here https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Fuchsia/18752/overview
> Python compatibility fix

- build/archives/BUILD.gn
dll.exp, dll.lib and dll.pdb files are missing from the gn generated artifacts.zip.
Bug: https://github.com/flutter/flutter/issues/119663 …
> Add missing file to artifacts.zip and win platform.

- build/archives/BUILD.gn
This file was missing on release and profile versions.
Bug: https://github.com/flutter/flutter/issues/119887 …
> Add gen_snapshot to windows flutter artifact.

- impeller/geometry/geometry_unittests.cc
- impeller/geometry/size.h
CP of https://github.com/flutter/engine/commit/6a92731d2edcb72dca0dc161de1da1e20a8210d8 for https://github.com/flutter/flutter/issues/119245 into `flutter-3.7-candidate.1`
> [CP] [Impeller] ensure 1x1 has mipcount of 1 (#39182)

- ci/builders/linux_android_debug_engine.json
- ci/builders/linux_host_engine.json
- ci/builders/mac_host_engine.json
- ci/builders/mac_ios_engine.json
- ci/builders/mac_ios_engine_profile.json
- ci/builders/mac_ios_engine_release.json
- ci/builders/windows_host_engine.json
Python2 has already been deprecated and the the python binary removed from path. …
> Migrate engine_v2_builds to python3.

- .ci.yaml
This is in preparation to support builds on mac m1 machines.
[Discord]: …
> Use jdk 11 in the engine.

- tools/fuchsia/build_fuchsia_artifacts.py
CP:  957412921cda4db78e0bc426329df2168625810c
[Discord]: …
> CP: Python compatibility fix (#39286)

- impeller/entity/entity_pass.cc
CP of https://github.com/flutter/engine/commit/dbf401f974c40f7a35188fe181368436eb1a0545 to fix https://github.com/flutter/flutter/issues/119289 on `flutter-3.7-candidate.1`
> [CP] [Impeller] Don't ceil subpass texture sizes (#39336)

- shell/platform/fuchsia/flutter/tests/integration/mouse-input/mouse-input-test.cc
> Disable mouse-input-test

- impeller/docs/faq.md
This PR fixes two grammatical issue in `faq.md` that bothered me enough to create this PR.
> [Impeller] Fix grammatical issues in faq.md.

- impeller/entity/contents/clip_contents.cc
- impeller/entity/entity_unittests.cc
Resolves https://github.com/flutter/flutter/issues/120220.
> [Impeller] Fix unsafe access for clip stencil coverage

- .ci.yaml
Windows arm, Linux Fuchsia FEMU and Linux Fuchsia FEMU arm64 have been passing consistently.
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-c …
> Remove bringup from builds.

- shell/platform/darwin/macos/framework/Source/FlutterTextInputPluginTest.mm
This just extracts arguments to the TextInputClient.setClient async method call into an NSDictionary local to reduce the deep indentation of the formatted code.
While the bulk of these calls are identical and could be extracted to a utility function, or a class extension method like `handleDefaultSetClientCall`, the point of these tests is to exercise FlutterTextInputPlugin, and the message protocol over the channel are precisely what's  being tested, so it makes sense to keep these explicit.
Followup patch to https://github.com/flutter/engine/pull/39632.
Issue: https://github.com/flutter/flutter/issues/120252
[Tree …
> [macOS] Improve TextInputPlugin test readability

- impeller/entity/geometry.cc
The compiler probably does this anyway, but unless I'm misreading the code and still waking up I'm pretty sure this is what we actually want.
> Remove extraneous if

- sky/tools/create_macos_framework.py
> Revert "[gn + codesign] mac code sign configuration for FlutterMacOS.framework.zip"

- impeller/entity/contents/clip_contents.cc
- impeller/entity/entity_unittests.cc
This is the CP PR for https://github.com/flutter/flutter/issues/120220.
> [CP][Impeller] Fix unsafe access for clip stencil coverage (#39595)

- shell/platform/linux/fl_engine_private.h
Fix some copy/paste errors on function documentation.
> Fix documentation of FlEngineOnPreEngineRestartHandler

- impeller/playground/playground.cc
Good things will come of this. ;)
https://user-images.githubusercontent.com/919017/220572652-2637f1ab-f01e-493d-917f-681ec6aea373.mov
> [Impeller] Add root dockspace to playgrounds

- shell/common/shell_unittests.cc
Fixes https://github.com/flutter/flutter/issues/121096
> Fix a race in ShellTest.PushBackdropFilterToVisitedPlatformViews

- lib/ui/platform_dispatcher.dart
- lib/web_ui/lib/platform_dispatcher.dart
Follow-up to https://github.com/flutter/engine/pull/39737.
To be submitted after https://github.com/flutter/flutter/pull/121152.
> Deprecate WindowPadding

- testing/README.md
- testing/run_tests.py
Adds some testing hints for developers so that it's easier to find the testing Wiki.
> Add testing hints

- lib/ui/painting.dart
https://github.com/flutter/engine/pull/34649 introduced some doc references that dartdoc cannot resolve. This PR attempts to fix them.
> Fix shader doc references

- sky/tools/create_macos_gen_snapshots.py
> Fix pylint errors

- .ci.yaml
These builds have been passing consistently for several weeks.
[Discord]: …
> Remove bringup from fuchsia builds.

- shell/platform/linux/fl_view.cc
By convention, use `self` for the pointer to the current object. Fixes this inconsistency in FlView.
> Fix FlView self variables using non-standard names.

- web_sdk/BUILD.gn
This should fix the current engine -> framework roll.
> Don't include other files outside the flutter_web_sdk.

- ci/licenses_golden/excluded_files
- shell/platform/darwin/macos/README.md
Describes how to build and test the macOS embedder.
[Discord]: …
> [macOS] Add README.md for macOS embedder

- common/settings.h
- shell/common/switches.cc
- shell/common/switches.h
- shell/common/switches_unittests.cc
- shell/platform/darwin/ios/framework/Source/FlutterDartProject.mm
- shell/platform/darwin/ios/framework/Source/FlutterEngine.mm
- shell/platform/darwin/ios/framework/Source/FlutterEnginePlatformViewTest.mm
- shell/platform/darwin/ios/framework/Source/FlutterEngineTest.mm
- shell/platform/darwin/ios/framework/Source/FlutterEngine_Internal.h
- shell/platform/darwin/ios/framework/Source/FlutterEngine_Test.h
- shell/platform/darwin/ios/framework/Source/FlutterTextureRegistryRelayTest.mm
First patch for iOS Embedder api migration.
The iOS Embedder API implementation is going to be hidden behind this flag during the migration. 
This PR introduced:
1. A command line flag `enable-embedder-api`, which can also be used for Android when we want to migrate it to embedder API.
2. An info.plist flag `FLTEnableIOSEmbedderAPI`, which is used on iOS.
Both flag acts the same on iOS and either one of them being true should run iOS embedder with the embedder API.
This flag defaults to false.
First step of https://github.com/flutter/flutter/issues/112232 …
> [ios] add setting flag to enable embedder api.

- .ci.yaml
- ci/builders/linux_web_engine.json
- lib/web_ui/dev/felt
- lib/web_ui/dev/felt.bat
* Use felt wrapper instead of felt.dart
* Remove gclient and and autoninja from felt wrappers.
* Add the config to .ci.yaml.
Bug: https://github.com/flutter/flutter/issues/119036
[breaking …
> Web engine build config cleanup.

- ci/licenses_golden/excluded_files
- ci/licenses_golden/licenses_flutter
- shell/platform/fuchsia/flutter/BUILD.gn
- shell/platform/fuchsia/flutter/component_v1.cc
- shell/platform/fuchsia/flutter/component_v1.h
- shell/platform/fuchsia/flutter/component_v1_unittest.cc
- shell/platform/fuchsia/flutter/meta/aot_product_runtime
- shell/platform/fuchsia/flutter/meta/aot_runtime
- shell/platform/fuchsia/flutter/meta/flutter_aot_product_runner.cmx
- shell/platform/fuchsia/flutter/meta/flutter_aot_runner.cmx
- shell/platform/fuchsia/flutter/meta/flutter_jit_product_runner.cmx
- shell/platform/fuchsia/flutter/meta/flutter_jit_runner.cmx
- shell/platform/fuchsia/flutter/meta/jit_product_runtime
- shell/platform/fuchsia/flutter/meta/jit_runtime
- shell/platform/fuchsia/flutter/runner.cc
- shell/platform/fuchsia/flutter/runner.h
- tools/fuchsia/flutter/flutter_build_config.gni
Reverts flutter/engine#39732, haven't root-caused this yet but it's breaking an internal roller.
> Revert "[fuchsia] Remove CFv1 support"

- shell/common/rasterizer.cc
- testing/dart/canvas_test.dart
Should help with https://github.com/flutter/flutter/issues/121485
> Improve error messaging when render target cannot be created

- impeller/geometry/geometry_unittests.cc
- impeller/geometry/path.cc
- impeller/geometry/point.h
- impeller/geometry/size.h
- impeller/geometry/vector.h
- impeller/playground/playground.cc
- impeller/typographer/backends/skia/text_frame_skia.cc
Found these while cleaning out my git stash. :)
> [Impeller] Add rounding utils to all geometry primitives

- testing/dart/assets_test.dart
- testing/dart/color_test.dart
- testing/dart/observatory/skp_test.dart
- testing/dart/observatory/tracing_test.dart
- testing/dart/observatory/vmservice_methods_test.dart
- testing/dart/platform_view_test.dart
- testing/dart/pubspec.yaml
- testing/dart/text_test.dart
- testing/dart/window_test.dart
> Remove single window assumption from testing/dart

- lib/web_ui/lib/src/engine/canvaskit/canvaskit_canvas.dart
- lib/web_ui/lib/src/engine/canvaskit/vertices.dart
Fixes https://github.com/flutter/flutter/issues/121557
> Apply the buffer offset when converting a vertex color Int32List to a Uint32List

- ci/builders/linux_android_aot_engine.json
These artifacts were missing in the engine v2 builds.
[Discord]: …
> Add analyze_snapshot to android_aot builder.

- lib/web_ui/lib/src/engine/canvaskit/canvaskit_api.dart
- lib/web_ui/lib/src/engine/canvaskit/text_fragmenter.dart
- lib/web_ui/test/canvaskit/text_fragmenter_test.dart
Pass the malloced array to CanvasKit instead of passing the underlying typed array.
> [web] Use CK's malloced array correctly

- .ci.yaml
This speeds up builds that have regressed adding 15+ minutes to the execution time.
Bug: https://github.com/flutter/flutter/issues/122211 …
> Use 32 cores in Linux Host and Web Engine.

- .ci.yaml
For https://github.com/flutter/flutter/issues/122743
> Move Fuchsia FEMU to bringup due to flakes

- ci/builders/windows_android_aot_engine.json
Part of https://github.com/flutter/flutter/issues/122751
> Add drone dimensions to `windows_android_aot_engine`

- lib/web_ui/lib/src/engine/browser_detection.dart
- lib/web_ui/lib/src/engine/canvaskit/canvaskit_api.dart
- lib/web_ui/lib/src/engine/canvaskit/text.dart
- lib/web_ui/lib/src/engine/canvaskit/text_fragmenter.dart
- lib/web_ui/test/canvaskit/canvaskit_api_test.dart
First landed here: https://github.com/flutter/engine/pull/40154
Then reverted here: https://github.com/flutter/engine/pull/40329
> Reland "[web] Better way to detect CanvasKit variant (#40154)"

- impeller/scene/importer/importer_unittests.cc
Resolves https://github.com/flutter/flutter/issues/122829
I think this asset was re-exported and I forgot to re-run the importer tests at the time.
> [Impeller] Update scene importer tests

- ci/builders/linux_web_engine.json
> Compile tests as generator.

- tools/gn
Follow-up to Skia's change http://review.skia.org/649523
- [ x ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on writing and running engine tests.
- [ x ] All existing and new tests are passing. …
> Use skia_enable_ganesh instead of legacy GN arg

- impeller/aiks/aiks_unittests.cc
- impeller/entity/contents/text_contents.cc
- impeller/renderer/backend/gles/sampler_gles.cc
- impeller/renderer/backend/metal/formats_mtl.h
- impeller/renderer/backend/vulkan/formats_vk.h
- impeller/renderer/formats.h
- impeller/renderer/renderer_unittests.cc
- impeller/renderer/sampler_descriptor.h
- impeller/scene/geometry.cc
Reverts flutter/engine#40460
Landing TBR. Some sort of commit ordering issue and this broke the build
> Revert "[Impeller] change default sampler descriptor to use nearest mip level and remove kNone"

- ci/builders/linux_android_debug_engine.json
The build is not producing any artifacts and its output is not used for anything. …
> Remove unopt build from linux_android debug.

- .ci.yaml
CP:  686552f9444af6b169fbe522fc1987d99be88586
[Discord]: …
> CP: Run windows_arm build only on main branch. (#40546)

- ci/builders/linux_web_engine.json
Global tests for the web engine builder.
Bug: https://github.com/flutter/flutter/issues/121900
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking …
> Add web engine global tests.

- build/archives/BUILD.gn
This is to ensure artifacts are generated in the correct location for mac arm64 cpus. …
> Use target platform name when generating artifacts.

- lib/web_ui/lib/src/engine/canvaskit/canvaskit_api.dart
- lib/web_ui/lib/src/engine/canvaskit/text.dart
- lib/web_ui/test/canvaskit/canvaskit_api_test.dart
Reverts flutter/engine#40538
Seems to have broken canvaskit tests
> Revert "[web] Migrate canvaskit_api to JS types."

- impeller/entity/entity_pass.cc
- impeller/entity/entity_pass.h
Documenting to make stuff less confusing. TBH, I keep having to remind myself about why some of this stuff is here. 😅
> [Impeller] Document tricky bits in EntityPass, make positioning less confusing

- sky/packages/sky_engine/BUILD.gn
- sky/packages/sky_engine/lib/_embedder.yaml
Reverts flutter/engine#40597
May have broken the build.
> Revert "[web] Add `js_types` sources to build."

- lib/web_ui/README.md
- lib/web_ui/dev/canvaskit_lock.yaml
- lib/web_ui/dev/canvaskit_roller.dart
- lib/web_ui/lib/src/engine/configuration.dart
Reverts flutter/engine#40470 as it is causing local flutter web development (b/275455289)
> Revert "Reland "Default the CanvasKit base URL to local artifacts.""

- lib/web_ui/lib/src/engine/canvaskit/canvaskit_api.dart
- lib/web_ui/lib/src/engine/canvaskit/fonts.dart
- lib/web_ui/lib/src/engine/canvaskit/text.dart
- lib/web_ui/test/canvaskit/canvaskit_api_test.dart
Reverts flutter/engine#40673
Causing breakages here: https://github.com/flutter/flutter/pull/123582
> Revert "[canvaskit] Use FontCollection API from CanvasKit to mitigate caching issues"

- lib/web_ui/lib/src/engine/canvaskit/canvaskit_api.dart
- lib/web_ui/lib/src/engine/canvaskit/text.dart
- lib/web_ui/test/canvaskit/canvaskit_api_test.dart
> Reland "[web] Migrate canvaskit_api to JS types."

- shell/platform/android/io/flutter/embedding/android/FlutterFragmentActivity.java
Upstream change from cl/516851539
https://github.com/flutter/flutter/issues/123687
> Suppress warning for missing super call onBackPressed cl/516851539

- common/settings.h
- shell/common/switches.cc
- shell/common/switches.h
- shell/platform/android/android_surface_vulkan_impeller.cc
- shell/platform/android/android_surface_vulkan_impeller.h
- shell/platform/android/io/flutter/embedding/engine/FlutterShellArgs.java
- shell/platform/android/platform_view_android.cc
- shell/platform/android/platform_view_android.h
- shell/platform/android/test/io/flutter/embedding/engine/loader/FlutterLoaderTest.java
Fixes https://github.com/flutter/flutter/issues/123799
> [Impeller] Enable vulkan validations via a flag on Android.

- impeller/compiler/compiler.cc
- impeller/compiler/compiler_unittests.cc
- impeller/compiler/types.cc
- impeller/compiler/types.h
Fixes https://github.com/flutter/flutter/issues/123705
> [Impeller] Un-ifdef vulkan code in impellerc

- DEPS
- third_party/canvaskit/BUILD.gn
Reverts flutter/engine#40808
Regresses benchmarks: https://flutter-flutter-perf.skia.org/e/?numCommits=100&queries=test%3Dweb_benchmarks_canvaskit
> Revert "Re-enable LTO and roll buildroot to enable `sINLINING_LIMIT`"

- impeller/tools/malioc_diff.py
Fixes https://github.com/flutter/flutter/issues/123872
> Fix pretty list printer to handle nulls

- impeller/aiks/aiks_unittests.cc
- impeller/golden_tests/golden_playground_test_mac.cc
issue: https://github.com/flutter/flutter/issues/123790
[Discord]: …
> [Impeller] migrated more golden images

- impeller/compiler/shader_lib/impeller/color.glsl
- impeller/compiler/shader_lib/impeller/texture.glsl
- impeller/entity/contents/filters/morphology_filter_contents.cc
- impeller/entity/shaders/color_matrix_color_filter.frag
- impeller/entity/shaders/color_matrix_color_filter.vert
- impeller/entity/shaders/linear_to_srgb_filter.frag
- impeller/entity/shaders/linear_to_srgb_filter.vert
- impeller/entity/shaders/morphology_filter.frag
- impeller/entity/shaders/morphology_filter.vert
- impeller/entity/shaders/runtime_effect.vert
- impeller/entity/shaders/yuv_to_rgb_filter.frag
- impeller/entity/shaders/yuv_to_rgb_filter.vert
- impeller/tools/malioc.json
Work towards https://github.com/flutter/flutter/issues/115044
> [Impeller] convert filters to half precision

- ci/licenses_golden/licenses_flutter
- impeller/renderer/backend/vulkan/BUILD.gn
- impeller/renderer/backend/vulkan/command_encoder_vk.cc
- impeller/renderer/backend/vulkan/command_encoder_vk.h
- impeller/renderer/backend/vulkan/command_pool_vk.cc
- impeller/renderer/backend/vulkan/context_vk.cc
- impeller/renderer/backend/vulkan/context_vk.h
- impeller/renderer/backend/vulkan/fence_waiter_vk.cc
- impeller/renderer/backend/vulkan/queue_vk.cc
- impeller/renderer/backend/vulkan/queue_vk.h
- impeller/renderer/backend/vulkan/swapchain_impl_vk.cc
- impeller/renderer/backend/vulkan/vk.h
Fixes https://github.com/flutter/flutter/issues/123883
> [Impeller] Add external synchronization to Vulkan queues access.

- impeller/geometry/path_component.cc
- impeller/tessellator/tessellator.h
- impeller/typographer/font.h
These are patches in @iamralpht's Aiks fork of impeller-cmake.
> [Impeller] Build fixes for impeller-cmake

- ci/builders/mac_host_engine.json
This is to ensure the engine v2 build include everything from the legacy builder in addition to the new tests added to engine_v2. …
> Sync Mac Host Engine with its engine v2 counterpart.

- ci/builders/mac_host_engine.json
Reverts flutter/engine#40856
Failure on https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20mac_host_engine/2864/overview
> Revert "Sync Mac Host Engine with its engine v2 counterpart."

- impeller/aiks/aiks_unittests.cc
- impeller/golden_tests/golden_playground_test_mac.cc
This brings over the last of the tests mentioned in https://github.com/flutter/engine/pull/40804#issuecomment-1492516301 …
> [Impeller] More impeller goldens from aiks_unittests

- impeller/compiler/code_gen_template.h
- impeller/compiler/reflector.cc
- impeller/compiler/spirv_compiler.cc
- impeller/core/shader_types.h
- impeller/renderer/backend/vulkan/capabilities_vk.cc
- impeller/renderer/backend/vulkan/debug_report_vk.cc
- impeller/renderer/backend/vulkan/descriptor_pool_vk.cc
- impeller/renderer/backend/vulkan/formats_vk.h
Fixes https://github.com/flutter/flutter/issues/123744
> [Impeller] Enable SSBOs in the Vulkan backend.

- shell/common/snapshot_controller_skia.cc
Just "Snpashot" -> "Snapshot" ;) Came across this when digging source code for a jank. …
> Fix super tiny typo

- impeller/aiks/aiks_unittests.cc
issue: https://github.com/flutter/flutter/issues/124277
[Discord]: …
> [Impeller] adjusted the rotated text test to have an opaque background and account for screen scale

- sky/tools/create_macos_framework.py
CP: ccc32758588c8801eb4cddd1cf842e4c5800bbf4
[Discord]: …
> CP: codesign metadata for FlutterMacOS.framework.zip

- sky/tools/create_macos_framework.py
CP: ccc32758588c8801eb4cddd1cf842e4c5800bbf4
[Discord]: …
> (Reland) codesign metadata for FlutterMacOS.framework.zip

- impeller/entity/contents/content_context.h
- impeller/renderer/backend/gles/pipeline_library_gles.cc
* Fix a typo in GLES fragment shader error checking
* Assert if a pipeline future returns null
> [Impeller] Some fixes to shader pipeline validation

- .ci.yaml
This will move linux_desktop build to run using the prod pool resources but will not upload artifacts to the prod bucket yet. …
> Promote linux_desktop build to prod.

- .ci.yaml
- ci/builders/mac_ios_engine.json
> Reland "Migrate ios_builders to engine_v2."

- .ci.yaml
- DEPS
- ci/builders/mac_impeller_cmake_example.json
- ci/impeller_cmake_build_test.py
This PR adds an engine CI configuration that downloads the impeller-cmake-example and builds it.
> Add script to test impeller-cmake-example

- shell/platform/darwin/ios/framework/Source/SemanticsObject.mm
- shell/platform/darwin/ios/framework/Source/SemanticsObjectTest.mm
- shell/platform/darwin/ios/framework/Source/accessibility_bridge.mm
- shell/platform/darwin/ios/framework/Source/accessibility_bridge_test.mm
fixes https://github.com/flutter/flutter/issues/42793
[Discord]: …
> Makes iOS VoiceOver treat radio buttons as regualr buttons

- lib/ui/dart_ui.gni
- sky/packages/sky_engine/BUILD.gn
- sky/packages/sky_engine/lib/_embedder.yaml
Reverts flutter/engine#40846
This broke the engine -> framework roll.
> Revert "Include `ui_web` API files in sky_engine."

- shell/platform/fuchsia/flutter/BUILD.gn
- shell/platform/fuchsia/flutter/engine.cc
- shell/platform/fuchsia/flutter/engine.h
- shell/platform/fuchsia/flutter/meta/common.shard.cml
- shell/platform/fuchsia/flutter/meta/flutter_aot_product_runner.cmx
- shell/platform/fuchsia/flutter/meta/flutter_aot_runner.cmx
- shell/platform/fuchsia/flutter/meta/flutter_jit_product_runner.cmx
- shell/platform/fuchsia/flutter/meta/flutter_jit_runner.cmx
Implement thread priorities using the Fuchsia media profile provider API to enable system / product configuration of host threads.
Bug: b/275114261
> [Fuchsia] Implement thread priorities.

- impeller/aiks/aiks_unittests.cc
- impeller/typographer/backends/skia/text_frame_skia.cc
CP for https://github.com/flutter/engine/pull/41101
> [CP][Impeller] Improve accuracy of glyph spacing (#41101)

- .ci.yaml
These builds are very slow and they don't add value in the context of recipes tests. …
> Do not run clang tidy on recipes cq.

- .ci.yaml
- ci/builders/mac_host_engine.json
> Revert "Migrate mac_host_engine to engine v2 builds."

- impeller/entity/contents/anonymous_contents.h
This is just a copy paste error...
> [Impeller] Remove ContentContextOptions declarations from AnonymousContents

- .ci.yaml
- ci/builders/mac_host_engine.json
> Revert "Reland  "Migrate mac_host_engine to engine v2 builds.""

- impeller/typographer/backends/skia/text_frame_skia.cc
> [CP] [Impeller] Remove glyph pixel rounding during text frame conversion (#41285)

- ci/builders/windows_arm_host_engine.json
This will start uploading the arm artifacts to the production bucket without the experimental namespace. …
> Upload windows arm artifacts to production bucket.

- .ci.yaml
- ci/builders/mac_host_engine.json
This reverts commit f6e64a87407f3b728258999f3f53512b68393d55.
[Discord]: …
> re-land "Migrate mac_host_engine to engine v2 builds." (#41233)"

- .ci.yaml
- ci/builders/mac_host_engine.json
> Revert "re-land "Migrate mac_host_engine to engine v2 builds." (#41233)""

- ci/builders/linux_android_aot_engine.json
- ci/builders/linux_android_debug_engine.json
- ci/builders/linux_arm_host_engine.json
- ci/builders/linux_host_desktop_engine.json
- ci/builders/linux_host_engine.json
- ci/builders/mac_android_aot_engine.json
- ci/builders/mac_host_engine.json
- ci/builders/mac_impeller_cmake_example.json
- ci/builders/mac_unopt.json
- ci/builders/windows_arm_host_engine.json
- ci/builders/windows_host_engine.json
Tests property is optional, empty tests property can be safely removed from the build configurations.
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-b …
> Remove empty tests properties.

- impeller/entity/contents/solid_color_contents.cc
- impeller/entity/contents/solid_color_contents.h
- impeller/entity/entity_unittests.cc
> Revert "[impeller] convert src over to src for solid color"

- display_list/display_list.h
Fixes https://github.com/flutter/flutter/issues/125428
Note that these are lint-type fixes and so there are no tests for them.
> hide DisplayList::DisposeOps and other lint suggestions

- ci/builders/linux_host_desktop_engine.json
The desktop artifacts are generated using gn+ninja in both the legacy and engine v2 builds. This change is making the engine v2 the primary build.
This change needs to land before https://flutter-review.googlesource.com/c/recipes/+/43340 which is removing the desktop artifacts from the legacy builder to avoid trying to upload the same artifacts multiple times.
There will be some propagation time, 1 or 2 commits where the artifacts will try to be uploaded twice making the legacy Linux Host Engine build fail and recover automatically with the auto-retry. …
> Migrate desktop artifacts to engine v2.

- .ci.yaml
- ci/builders/linux_android_debug_engine.json
Legacy and engine v2 builds artifacts are identical. This PR is moving the legacy build to staging and starts uploading engine v2 artifacts to production. …
> Migrate Android Engine Debug to Engine V2.

- .ci.yaml
This moves the legacy linux unopt build to staging and the engine v2 version to production.
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-ch …
> Replace legacy linux unopt with engine v2.

- .ci.yaml
- ci/builders/linux_fuchsia.json
Engine V2 configuration for fuchsia builds.
[Discord]: …
> Linux fuchsia engine v2 config.

- tools/gn
Unit tests have been fixed by @flar, so the staging flag can be removed.
Unlocks progress on https://skbug.com/9283 …
> Remove staging flag

- .ci.yaml
This build has been running on prod for a few days already and it is ready to get moved to prod.
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaki …
> Move linux fuchsia engine v2 build to prod.

- .ci.yaml
- ci/builders/standalone/linux_license.json
CP: fc56c86741c84ff839c11c2788e0f72b7515fdd7
[Discord]: …
> CP: Add linux license engine v2 build. (#41797)

- .ci.yaml
- ci/builders/standalone/windows_unopt.json
CP: 9420c500a9e58bf60f7af3c54e8639f2320a7882
[Discord]: …
> CP: Windows unopt configuration. (#41785)

- .ci.yaml
> Revert "Move linux_license to engine v2."

- tools/fuchsia/merge_and_upload_debug_symbols.py
CP: 8eb58b753eafb4610a0927e9b21f288f212a383a
[Discord]: …
> CP: Allow default out_dir for fuchsia symbols upload.

- .ci.yaml
- ci/builders/linux_host_engine.json
CP:  9322c14c1d59a3c957f34f3f25c9f15b3c5a3016
[Discord]: …
> CP: Migrate linux_host_engine to engine v2.

- .ci.yaml
- ci/builders/linux_unopt.json
CP:  b649d58312ded377ed02d70173c6cb6a85b0fea8
[Discord]: …
> CP: Migrate linux unopt to engine_v2

- .ci.yaml
- ci/builders/linux_android_aot_engine.json
CP: ee65be7d8fb1345b3eff3505a9e7c8dc66a2f2f7
[Discord]: …
> CP: Migrate Linux Android AOT Engine to engine V2. (#41638)

- .ci.yaml
- ci/builders/linux_android_debug_engine.json
CP:  59c316ef41c45f2593909ec01032cf0d581922a0
[Discord]: …
> CP: Migrate Android Engine Debug to Engine V2. (#41687)

- impeller/tools/malioc_diff.py
CP:  ee65be7d8fb1345b3eff3505a9e7c8dc66a2f2f7
[Discord]: …
> CP: Add relative path support for malioc_diff.

- lib/ui/platform_dispatcher.dart
fixes [https://github.com/flutter/flutter/issues/126082](https://github.com/flutter/flutter/issues/126082) 
[CLA]: …
> fix: platform_dispatcher documentation typo

- .ci.yaml
Relands https://github.com/flutter/engine/pull/41863
> Reland "Move linux_license to engine v2.""

- .ci.yaml
- ci/builders/mac_clang_tidy.json
CP: 0df6740f4ac49d2cb202a4a179facc0dd3e6706b
[Discord]: …
> CP: Migrate mac host clang tidy to engine v2. (#41824)

- .ci.yaml
CP: 9ee91b8bdd1de9db86c3dcfeb463e82ce2bfa1f4
[Discord]: …
> CP: Move linux_license to engine v2. (#41863)

- .ci.yaml
CP: b2497815adf80a26b67bf2cfd08ad0addad82410
[Discord]: …
> CP: Reland "Move linux_license to engine v2."" (#41983)

- flow/rtree.cc
fixes https://github.com/flutter/flutter/issues/126864
[Discord]: …
> Include SkRect in rtree.

- impeller/display_list/display_list_dispatcher.cc
- impeller/geometry/geometry_unittests.cc
- impeller/geometry/matrix.cc
- impeller/geometry/matrix.h
CP of https://github.com/flutter/engine/pull/41995.
> [CP] [Impeller] Ignore the Z basis when scaling text (#41995)

- .ci.yaml
CP: 995cdaaf9e15e5ea308864b9541a674ed6322906
[Discord]: …
> CP: Clobber caches in licenses test. (#41942)

- .ci.yaml
CP: 27e0a736c4f96dd28e1d68ba8506196eb535d98d
[Discord]: …
> CP: Add drone_dimensions as top level target property. (#42064)

- .ci.yaml
CP: 3b9ff4118eac467d7896a144fb53d2b6006fc4bc
[Discord]: …
> CP: Move clang tidy v2 build to prod. (#41985)

- .ci.yaml
CP: 46544b1b5c05911ad2ee4edbcb4a197b70d19fec
[Discord]: …
> CP: Replace Windows Unopt with the engine v2 version. (#41861)

- impeller/aiks/aiks_unittests.cc
- impeller/entity/contents/filters/blend_filter_contents.cc
- impeller/entity/contents/framebuffer_blend_contents.cc
- impeller/entity/shaders/blending/advanced_blend.glsl
- impeller/entity/shaders/blending/ios/framebuffer_blend.glsl
- impeller/tools/malioc.json
cp of https://github.com/flutter/engine/pull/41972
> [CP] [Impeller] Fix issue about saveLayer ignoring opacity of paint with advanced blend mode #41972

- lib/ui/painting/image_decoder_impeller.cc
This might help with https://github.com/flutter/flutter/issues/126768#issuecomment-1554469333
> [Impeller] use host image upload path on simulator

- impeller/aiks/aiks_unittests.cc
- impeller/entity/contents/runtime_effect_contents.cc
- impeller/golden_tests/golden_playground_test.h
- impeller/golden_tests/golden_playground_test_mac.cc
- impeller/golden_tests/golden_playground_test_stub.cc
Cherry pick for https://github.com/flutter/flutter/issues/127123
> [CP] Runtime effect clip fix

- .ci.yaml
Engine PR to match https://github.com/flutter/flutter/pull/127218
> Roll goldctl to f808dcff91b221ae313e540c09d79696cd08b8de

- DEPS
Changes since last roll
```
5cab8e0 Keep dictionary items sorted when updating dart deps. (#730)
1f35873 Forward inputs from wasm libraries. (#729)
```
> Roll buildroot to 5cab8e095066d8f3de063943af26b7336aa52662

- impeller/compiler/shader_lib/impeller/gaussian.glsl
- impeller/entity/entity_unittests.cc
- impeller/entity/shaders/gaussian_blur/gaussian_blur.glsl
- impeller/entity/shaders/rrect_blur.frag
CP for https://github.com/flutter/engine/pull/42069
> [CP] [Impeller] Use 32 bit Gaussian function in the 2-pass blur (#42069)

- .ci.yaml
These builders will generate CAS caches to optimize engine checkouts.
Bug: https://github.com/flutter/flutter/issues/127433 …
> Add builders for second level cache of builders.

- impeller/aiks/aiks_unittests.cc
- impeller/entity/contents/filters/gaussian_blur_filter_contents.cc
CP for https://github.com/flutter/engine/pull/42154
> [CP] [Impeller] Limit blur kernel to 1000x1000 pixels (#42154)

- impeller/entity/contents/filters/blend_filter_contents.cc
> [Impeller] Safely access snapshot in the pipeline blend filter

- .ci.yaml
Follow up of https://github.com/flutter/engine/pull/42339
Fixes: https://github.com/flutter/flutter/issues/127709
> Fix ci yaml roller caused by incorrect format

- impeller/aiks/canvas.cc
- impeller/display_list/display_list_unittests.cc
- impeller/entity/contents/vertices_contents.cc
CP of https://github.com/flutter/engine/pull/42293
> [CP] [Impeller] fix UV and color blending. (#42293)

- shell/platform/darwin/ios/ios_surface_metal_impeller.mm
- shell/platform/darwin/ios/ios_surface_metal_skia.mm
CP for https://github.com/flutter/engine/pull/41085.
> [CP] [Impeller] Make Metal layers readable (#41085)

- impeller/typographer/typographer_unittests.cc
- testing/run_tests.py
fixes https://github.com/flutter/flutter/issues/127714
[Discord]: …
> [Impeller] Fixed TypographerTest.MaybeHasOverlapping

- lib/ui/painting/image_generator_apng.cc
Related to #127701
When landing a seemingly unrelated CL, clang-tidy started failing with:
```
❌ Failures for clang-tidy on /b/s/w/ir/cache/builder/src/flutter/lib/ui/painting/image_generator_apng.cc:
/b/s/w/ir/cache/builder/src/flutter/lib/ui/painting/image_generator_apng.cc:57:10: error: unchecked access to optional value [bugprone-unchecked-optional-access,-warnings-as-errors]
return images_[image_index].frame_info.value();
^
/b/s/w/ir/cache/builder/src/flutter/lib/ui/painting/image_generator_apng.cc:154:13: error: unchecked access to optional value [bugprone-unchecked-optional-access,-warnings-as-errors]
switch (frame.frame_info->blend_mode) {
^
/b/s/w/ir/cache/builder/src/flutter/lib/ui/painting/image_generator_apng.cc:526:7: error: unchecked access to optional value …
```
> Fix bugprone-unchecked-optional-access errors in image_generator_apng

- DEPS
- ci/licenses_golden/excluded_files
Rolls ANGLE to https://github.com/google/angle/commit/e21ecd1b59f768a78b09823f6b6156d84e50d62b.
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breakin …
> Manually roll ANGLE

- ci/licenses_golden/licenses_flutter
- fml/BUILD.gn
- fml/concurrent_message_loop.cc
- fml/concurrent_message_loop.h
- fml/concurrent_message_loop_factory.cc
- fml/platform/darwin/concurrent_message_loop_factory.mm
See https://github.com/flutter/flutter/issues/127482
> Wrap concurrent message loop tasks in an autorelease pool on iOS/Mac platforms

- .ci.yaml
CP: b6aec5629bed21c6ee5305485f56a00876dae098
[Discord]: …
> CP: Add cpu as drone dimension to mac ios build. (#42514)

- impeller/aiks/aiks_unittests.cc
- impeller/entity/contents/linear_gradient_contents.cc
- impeller/entity/contents/radial_gradient_contents.cc
- impeller/entity/contents/sweep_gradient_contents.cc
- impeller/entity/contents/tiled_texture_contents.cc
- impeller/entity/entity_unittests.cc
fix issue https://github.com/flutter/flutter/issues/128327
without patch 
with patch
> [Impeller] Fix the rendering issue when the tile mode of gradient is set to 'decal'

- .github/labeler.yml
- .github/workflows/labeler.yml
https://github.com/flutter/flutter/issues/126002
> [labeler] Add engine workflow

- flow/layers/layer_raster_cache_item.cc
CP PR for https://github.com/flutter/engine/pull/42592
> [CP] Fix raster cache optional value check logic (#42592)

- .ci.yaml
- ci/builders/standalone/linux_benchmarks.json
This configuration migrates benchmarks to engine_v2.
[Discord]: …
> Benchmarks configurations for engine v2.

- .ci.yaml
Benchmarks has been migrated to engine v2 and it is ready to replace the legacy version. …
> Replace benchmarks with its v2 version.

- impeller/entity/shaders/linear_gradient_ssbo_fill.frag
- impeller/tools/malioc.json
Fixes https://github.com/flutter/flutter/issues/128603
We were hitting a nan issue. GLSL has different relaxed precision semantics than vulkan does, and didn't hit it for some reason.
> [Impeller] Fix vulkan gradient nan issue.

- .ci.yaml
> Reland "Move linux clang tidy to engine_v2.""

- .ci.yaml
- ci/builders/standalone/linux_android_emulator.json
Migrates emulator tests to engine v2.
[Discord]: …
> Create v2 configuration for emulator tests.

- shell/platform/fuchsia/dart_runner/dart_runner.cc
- shell/platform/fuchsia/flutter/runner.cc
> Add missing includes

- ci/builders/linux_android_debug_engine.json
followup to https://github.com/flutter/engine/pull/42724
[Discord]: …
> Renamed validation layers build

- ci/builders/linux_android_aot_engine.json
The generation and archiving of this artifact was missed during the engine v2 migration.
Bug: https://github.com/flutter/flutter/issues/128907 …
> Add missing artifact to the android_arm64_profile config.

- ci/builders/linux_android_aot_engine.json
CP: 80252cb81d17246348de304a00a6ee4174fbb82c
[Discord]: …
> CP: Add missing artifact to the android_arm64_profile config. (#42858)

- DEPS
Reverts flutter/engine#42718
This is causing a breakage for Fuchsia (see b/286634225)
> Revert "Roll Clang from 6d667d4b261e to 7f374b6902fa"

- lib/ui/channel_buffers.dart
- lib/ui/platform_dispatcher.dart
- lib/ui/window.dart
- testing/dart/channel_buffers_test.dart
- testing/dart/observatory/vmservice_methods_test.dart
- testing/dart/text_test.dart
- testing/scenario_app/lib/main.dart
- testing/scenario_app/lib/src/platform_echo_mixin.dart
- testing/scenario_app/lib/src/platform_view.dart
- testing/scenario_app/lib/src/poppable_screen.dart
- testing/scenario_app/lib/src/scenario.dart
> Revert "Add deprecations to PlatformMessage stuff"

- .ci.yaml
- ci/builders/mac_host_engine.json
- ci/builders/mac_ios_engine.json
CP: 83bf87f7cefdcd41f468fcb9192565a227edc487
CP: 15ac3c1e9104889f8541f1ad1aff1de4fdcc89e6 …
> CP: Fixes to enable dart internal generation of artifacts

- lib/ui/painting.dart
This is now failing the engine roll for some reason https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20analyze/58456/overview
> Fix prefer_final_in_foreach analysis errors

- impeller/renderer/backend/gles/blit_pass_gles.cc
- impeller/renderer/backend/gles/render_pass_gles.cc
> Differentiate two `EncodeCommandsInReactor` with the same name

- .ci.yaml
- ci/builders/mac_host_engine.json
- ci/builders/mac_ios_engine.json
CP: 83bf87f7cefdcd41f468fcb9192565a227edc487
CP: 15ac3c1e9104889f8541f1ad1aff1de4fdcc89e6
> CP: Fixes to enable dart internal generation of artifacts (#42927)

- DEPS
Rolling:
- https://github.com/flutter/buildroot/pull/746
- https://github.com/flutter/buildroot/pull/747
- https://github.com/flutter/buildroot/pull/748
> Roll buildroot to 6e71c38443c0bf9d8954c87bf69bb4e019f44f94

- ci/builders/linux_unopt.json
The test was not migrated to v2.
Bug: https://github.com/flutter/flutter/issues/127759 …
> Add missing android lint to linux_unopt.

- shell/platform/fuchsia/flutter/meta/common.shard.cml
Missed in c6251a69a09a974e7e832e9661b4d817f9187573.
> Add tmp storage capability to flutter runner

- shell/platform/linux/fl_event_channel.cc
- shell/platform/linux/fl_event_channel_test.cc
https://github.com/flutter/flutter/issues/126209
> Allow event channels to reuse names

- .github/workflows/mirror.yml
> Revert "Remove master mirroring workflow."

- ci/licenses_golden/excluded_files
- impeller/aiks/BUILD.gn
- impeller/aiks/aiks_unittests.cc
- impeller/aiks/canvas.cc
- impeller/aiks/testing/context_mock.h
- impeller/aiks/testing/context_spy.cc
- impeller/aiks/testing/context_spy.h
- impeller/entity/contents/contents.h
- impeller/entity/contents/solid_color_contents.cc
- impeller/entity/contents/solid_color_contents.h
- impeller/entity/entity_pass.cc
- impeller/entity/entity_pass.h
- impeller/entity/geometry/cover_geometry.cc
- impeller/entity/geometry/cover_geometry.h
- impeller/entity/geometry/geometry.h
- impeller/entity/geometry/rect_geometry.cc
- impeller/entity/geometry/rect_geometry.h
- impeller/renderer/command_buffer.h
- impeller/renderer/render_pass.h
- testing/scenario_app/android/app/build.gradle
design doc: https://docs.google.com/document/d/1Lqf1BRn4uCcUfv9dZlDyAgdSMeQ3FTnPgPjKF9yQ3MI/edit
fixes: https://github.com/flutter/flutter/issues/129292 …
> [Impeller] Collapse DrawRects into clear colors optimization

- shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm
- shell/platform/darwin/ios/framework/Source/FlutterViewControllerTest.mm
Fixes [flutter/flutter#126560](https://github.com/flutter/flutter/issues/126560)
> [iOS] Fix FlutterViewController retain cycle

- shell/platform/android/io/flutter/plugin/platform/PlatformViewsController.java
- shell/platform/android/test/io/flutter/plugin/platform/PlatformViewsControllerTest.java
Eagerly remove the PlatformView from the view hierarchy on Android.
Fixes [#107297](https://github.com/flutter/flutter/issues/107297)
> Eagerly remove the PlatformView from the view hierarchy on Android

- shell/platform/linux/fl_method_channel.cc
As noticed in https://github.com/flutter/flutter/issues/126209
> Fix leak when switching channels

- impeller/renderer/backend/vulkan/surface_vk.cc
Even on the Pixel 6 pro device which supports memoryless textures, I can observe creating the memoryless texture sometimes takes a few hundred microseconds, possibly due to stalls in the driver allocating the texture metadata. Lets just unconditionally cache this texture to avoid making the driver do more work.
Here is an example of this happening:
https://github.com/flutter/flutter/issues/129392
> [Impeller] Unconditionally cache swapchain msaa texture.

- shell/platform/darwin/ios/framework/Source/FlutterViewController.mm
- shell/platform/darwin/ios/framework/Source/FlutterViewControllerTest.mm
Cherry picks https://github.com/flutter/engine/commit/cf67f834cf16089d45be2341e5198af9da5adc5f
The original commit is a re-land of https://github.com/flutter/engine/commit/a5ff3629dfecd81d7322c40de7edaab24ee3d21f, the revert (https://github.com/flutter/engine/commit/3ade212082fa48e9b32f7b6008ef0c9a2a7c5c67) was not in the beta branch, so this cherry-pick becomes a direct fix forward.
Fixes https://github.com/flutter/flutter/issues/130284 …
> [CP][iOS][Keyboard] Fix crash when FlutterEngine destroys at the same time with keyboard animation vsync callback

- impeller/entity/inline_pass_context.cc
Cherry pick of https://github.com/flutter/engine/commit/189f823e7b4103b6b438a57b4601455b3073b75a
> [CP] Check for a null command buffer in InlinePassContext::EndPass

- flow/compositor_context.cc
- flow/compositor_context.h
- flow/embedded_views.h
- flow/layers/layer.h
- flow/layers/layer_tree.cc
- flow/layers/layer_tree_unittests.cc
- flow/layers/platform_view_layer.cc
- flow/surface_frame.cc
- flow/surface_frame.h
- shell/common/rasterizer.cc
This code no longer does anything.
> Delete unused display list/SkPicture code

- impeller/aiks/aiks_unittests.cc
- impeller/aiks/canvas.cc
- impeller/aiks/canvas.h
- impeller/display_list/dl_dispatcher.cc
- impeller/entity/contents/color_source_text_contents.cc
- impeller/entity/contents/color_source_text_contents.h
- impeller/entity/contents/content_context.h
- impeller/entity/contents/contents.h
- impeller/entity/contents/text_contents.cc
- impeller/entity/contents/text_contents.h
- impeller/entity/entity.cc
- impeller/entity/entity.h
- impeller/entity/entity_pass.cc
- impeller/entity/entity_pass.h
- impeller/entity/entity_unittests.cc
- impeller/typographer/backends/skia/text_frame_skia.cc
- impeller/typographer/backends/skia/text_frame_skia.h
- impeller/typographer/backends/skia/text_render_context_skia.cc
- impeller/typographer/backends/skia/text_render_context_skia.h
- impeller/typographer/font.h
- impeller/typographer/font_glyph_pair.h
- impeller/typographer/lazy_glyph_atlas.cc
- impeller/typographer/lazy_glyph_atlas.h
- impeller/typographer/text_frame.cc
- impeller/typographer/text_frame.h
- impeller/typographer/text_render_context.cc
- impeller/typographer/text_render_context.h
- impeller/typographer/typographer_unittests.cc
Reverts  https://github.com/flutter/engine/pull/43533
Cause of https://github.com/flutter/flutter/issues/130476
I was trying to add a test for this but it's taking me a while to get a working test so here's the revert.
> Revert https://github.com/flutter/engine/pull/43533

- lib/ui/window.dart
See https://github.com/flutter/flutter/issues/11697
> Add more points to [MediaQuery].

- shell/platform/darwin/ios/framework/Source/FlutterAppDelegate.mm
- shell/platform/darwin/ios/framework/Source/FlutterEngine.mm
- shell/platform/darwin/ios/framework/Source/accessibility_bridge.mm
- shell/platform/darwin/ios/platform_view_ios.mm
See https://github.com/flutter/engine/pull/43661
> More fixes for the new clang-tidy roll on iOS targets

- DEPS
Reverts flutter/engine#43673
Reverting for b/291462180
> Revert "Roll Clang from 6d667d4b261e to ebd0b8a0472b"

- .ci.yaml
This is blocking the beta release as the builder is running unnecessarily.
> [ci.yaml] Skip windows arm on releases

- impeller/renderer/backend/gles/description_gles.cc
Follow-up fix for https://github.com/flutter/engine/pull/43727.
Fixes the GL playground on MacOS.
> [Impeller] Fix GL_NUM_EXTENSIONS check for desktop GL

- display_list/benchmarking/dl_complexity_gl.h
- display_list/benchmarking/dl_complexity_metal.h
Test removing picture complexity based raster caching.
> [engine] disable picture complexity raster caching

- impeller/entity/contents/filters/filter_contents.cc
- impeller/entity/contents/filters/filter_contents.h
- impeller/entity/contents/filters/inputs/contents_filter_input.cc
- impeller/entity/contents/filters/inputs/contents_filter_input.h
- impeller/entity/contents/filters/inputs/filter_contents_filter_input.cc
- impeller/entity/contents/filters/inputs/filter_contents_filter_input.h
- impeller/entity/contents/filters/inputs/filter_input.cc
- impeller/entity/contents/filters/inputs/filter_input.h
Resolves https://github.com/flutter/flutter/issues/131012.
> [Impeller] Propagate PopulateGlyphAtlas through filters.

- display_list/benchmarking/dl_complexity_gl.h
- display_list/benchmarking/dl_complexity_metal.h
> Revert "[engine] disable picture complexity raster caching"

- shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.h
- shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm
- shell/platform/darwin/ios/framework/Source/FlutterTextInputPluginTest.mm
Fixes https://github.com/flutter/flutter/issues/129061
> [iOS] TextInputPlugin should batch TextEditingDeltas and dispatch on the next runLoop

- .ci.yaml
- ci/builders/linux_web_engine.json
- lib/web_ui/dev/browser_lock.yaml
- lib/web_ui/dev/generate_builder_json.dart
Update the version of Chrome we use for unit tests to 115.
> Roll Chrome to 115

- lib/ui/window.dart
[The issue](https://github.com/dart-lang/linter/issues/4562) has been resolved. …
> Remove a temporary lint ignore

- impeller/aiks/aiks_unittests.cc
- impeller/entity/entity_pass.cc
fixes https://github.com/flutter/flutter/issues/131576
[Discord]: …
> [Impeller] Made the clear optimization handle backdrop filters.

- impeller/renderer/backend/metal/texture_mtl.mm
Fixes https://github.com/flutter/flutter/issues/131682
> [Impeller] Fix leak of wrapped TextureMTL objects in the Metal embedder API

- .ci.yaml
> Add drone dimensions

- shell/platform/android/io/flutter/embedding/engine/renderer/FlutterRenderer.java
- shell/platform/android/io/flutter/view/TextureRegistry.java
> Add @Keep annotations to avoid dead code elimination of classes only referenced by JNI

- .ci.yaml
In order to avoid new tasks from not being scheduled we are not going to backfill the autoroller because it can sometimes play transactions out of order causing issues with tasks that are scheduled but not known.
Part of https://github.com/flutter/flutter/issues/127063 …
> Mark the ci.yaml roller task so it is not backfilled.

- impeller/aiks/aiks_unittests.cc
- impeller/entity/contents/filters/matrix_filter_contents.cc
- impeller/entity/entity_pass.cc
Cherry-pick of https://github.com/flutter/engine/pull/43990.
> [CP][Impeller] Use basis of effect transform in MatrixFilter.

- impeller/renderer/backend/metal/texture_mtl.mm
Fixes https://github.com/flutter/flutter/issues/131682
> [CP][Impeller] Fix leak of wrapped TextureMTL objects in the Metal embedder API (#44245)

- impeller/typographer/font_glyph_pair.h
This change makes the glyph hash 39% faster (66ms vs 107ms).  The glyph hash function occupies the most CPU time on the raster thread when scrolling around the main screen for the Flutter Gallery …
> [Impeller] improved glyph hashing performance

- shell/platform/darwin/macos/framework/Source/FlutterEngineTest.mm
Adds testing that verifies that the engine is not retained via the FlutterTextureRegistry that is returned from the FlutterTextureRegistrar returned by the engine.
This also simplifies the existing test for a retain cycle via the FlutterBinaryMessenger by avoiding manually casting the binary messenger to a FlutterBinaryMessengerRelay, or knowing any of its implementation details.
Issue: https://github.com/flutter/flutter/issues/116445 …
> [macOS] Improve engine retain cycle testing

- shell/platform/glfw/flutter_glfw.cc
- SKIA requires at least GLES version 2.0
[Discord]: …
> Request GLES version 2 interface.

- shell/platform/android/io/flutter/view/AccessibilityBridge.java
- shell/platform/android/test/io/flutter/view/AccessibilityBridgeTest.java
Reverts flutter/engine#44452
Failing the roll to the framework on FTL tests: https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20firebase_android_embedding_v2_smoke_test/58307/overview
> Revert "Android a11y bridge sets importantness"

- examples/glfw/run.sh
- examples/glfw_drm/run.sh
- examples/vulkan_glfw/run.sh
Partial work towards https://github.com/flutter/flutter/issues/132245.
> Update `examples/**` to provide `--local-engine-host`.

- impeller/entity/contents/content_context.cc
- impeller/entity/contents/texture_contents.cc
- shell/platform/android/hardware_buffer_external_texture_gl.cc
- shell/platform/android/hardware_buffer_external_texture_gl.h
- shell/platform/android/hardware_buffer_external_texture_vk.cc
- shell/platform/android/platform_view_android.cc
- Implement Impeller/GLES code paths.
- A couple of fixes for EXTERNAL_OES textures via bdero@
> Add support for HardwareBuffer backed Android Platform Views under Impeller/GLES

- lib/web_ui/skwasm/image.cpp
- lib/web_ui/skwasm/surface.cpp
Follow-up to https://github.com/flutter/engine/pull/44334
[Discord]: …
> Migrate more GL calls of GrBackend*

- shell/platform/android/hardware_buffer_external_texture.cc
- shell/platform/android/hardware_buffer_external_texture_gl.cc
- shell/platform/android/ndk_helpers.cc
- shell/platform/android/platform_view_android.cc
- shell/platform/android/platform_view_android_jni_impl.cc
For Google3, this makes it easier since we only need to make one source transform (from `#include "flutter` -> `#include "third_party` instead of requiring a source transform for every root directory in this repo. …
> Namespace imports with flutter

- README.md
Adds the SLSA L1 compliance badge for the engine.
[Discord]: …
> Add SLSA L1 badge

- .ci.yaml
This is part of the cleanup of the migration to engine v2 builds.
Bug: https://github.com/flutter/flutter/issues/132600 …
> Remove duplicated v1 builds.

- shell/platform/darwin/ios/ios_surface_metal_impeller.mm
This got missed when setting this to always be `YES`.
> [Impeller] Update docstring on layer.presentsWithTransaction

- impeller/docs/vulkan_threading.md
Moving bits and pieces of the presentation this morning into docs so we can keep them up to date.
> [Impeller] Document threading configuration with Vulkan.

- impeller/docs/android.md
Fixes https://github.com/flutter/flutter/issues/132716
> [Impeller] Initial Android Impeller docs on backend selection and platform views.

- impeller/README.md
- impeller/docs/android.md
Also add cross-references to some docs from the main README.
> [Impeller] Document rendering backend selection on Android.

- impeller/aiks/canvas.cc
- impeller/entity/contents/text_contents.cc
- impeller/entity/contents/text_contents.h
- impeller/entity/entity_unittests.cc
- impeller/typographer/backends/skia/text_frame_skia.cc
- impeller/typographer/text_frame.cc
- impeller/typographer/text_frame.h
…and copies)
While investigating https://github.com/flutter/flutter/issues/131620 I tried many things to squeeze the logic to make text batching faster.  It didn't pan out but here are a handful of tweaks that make a tiny difference that I don't want to lose.
[CLA]: …
> [Impeller] Tiny optimizations for text rendering (avoiding extra ops and copies).

- impeller/renderer/backend/metal/command_buffer_mtl.mm
Cherry pick for https://github.com/flutter/flutter/issues/132982
> [Impeller] Remove sync switch (#44885)

- lib/web_ui/dev/test_platform.dart
- lib/web_ui/test/engine/platform_dispatcher/application_switcher_description_test.dart
Fixes https://github.com/flutter/flutter/issues/39159
> Make web tests start with an empty title

- lib/ui/text.dart
- lib/web_ui/lib/text.dart
- testing/dart/text_test.dart
This should aid with implementing the framework side of https://github.com/flutter/flutter/issues/105120 This should also address https://github.com/flutter/flutter/issues/28543.
> FontVariation.lerp, custom FontVariation constructors, and more documentation

- lib/ui/text.dart
- lib/web_ui/lib/text.dart
- testing/dart/text_test.dart
Reverts flutter/engine#43750
Looks like this is having trouble rolling into the framework: https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20analyze/62845/overview
> Revert "FontVariation.lerp, custom FontVariation constructors, and more documentation"

- ci/builders/mac_android_aot_engine.json
- ci/builders/mac_host_engine.json
- ci/builders/mac_ios_engine.json
- ci/builders/mac_unopt.json
https://github.com/flutter/flutter/issues/133301
> Revert ios cpu changes

- docs/Doxyfile.template
- tools/gen_docs.py
Add quotes are the Doxygen configuration values that may have spaces, since otherwise Doxygen strips them.
> Add quotes around Doxygen configuration values

- DEPS
[CP] b/294820516
https://stackoverflow.com/questions/76852785/how-to-fix-itms-90338-non-public-api-usage-issue-after-review
> [CP] Revert clang back to 5d667d4b261e81f325756fdfd5bb43b3b3d2451d (#44442)

- impeller/renderer/backend/vulkan/render_pass_vk.cc
We call allocateAndBindDescriptorSets once for every cmd rendered, so this time can bubble up quite a bit. From the traces I've gathered map emplacement (emplace_unique_key_args) and std::vector growth (__push_back_slow_path) contribute the most to this trace.
I think we have physical limits on the number of descriptors we can bind, though I'm not sure if we enforce that anywhere?
> [Impeller] avoid hashing and std::vector growth when binding descriptor sets.

- impeller/aiks/aiks_unittests.cc
- impeller/aiks/canvas.cc
- impeller/aiks/paint.cc
- impeller/aiks/paint.h
- impeller/entity/contents/color_source_contents.cc
- impeller/entity/contents/color_source_contents.h
- impeller/entity/contents/filters/gaussian_blur_filter_contents.cc
- impeller/entity/contents/solid_color_contents.cc
- impeller/entity/contents/solid_color_contents.h
- impeller/golden_tests/golden_playground_test_mac.cc
3.14 cherry-pick for https://github.com/flutter/engine/pull/43519.
> [CP] 3.14: [Impeller] Fix mask blurs and the Gaussian blur coverage hint. (#45079)

- ci/analyze.sh
- ci/licenses_golden/excluded_files
- ci/pylint.sh
- impeller/tessellator/dart/lib/tessellator.dart
- tools/gen_web_locale_keymap/pubspec.yaml
- tools/pub_get_offline.py
Also adds a test to ensure that all packages are accounted for.
> Clean up engine repo Dart code

- DEPS
https://github.com/bdero/impeller-cmake-example/commit/142507046e11f593b54d94af328998bbe45a88ef
> Bump impeller-cmake-example to head

- shell/platform/fuchsia/flutter/vulkan_surface.cc
- shell/platform/fuchsia/flutter/vulkan_surface_producer.cc
Follow-up to https://github.com/flutter/engine/pull/45325
No functional change.
> Migrate Fuchsia VK calls of GrBackend*

- impeller/aiks/aiks_unittests.cc
The current goldens are changing a lot, this should be stabler. though not sure if it looks quite right.
> [Impeller] Better demonstrate blur and draw picture?

- shell/platform/darwin/ios/ios_surface_metal_impeller.mm
Cherry pick of fix for https://github.com/flutter/flutter/issues/133147
> Revert unconditional CATransaction.

- DEPS
- ci/licenses_golden/excluded_files
- ci/licenses_golden/licenses_fuchsia
- ci/licenses_golden/tool_signature
- tools/licenses/lib/paths.dart
For https://github.com/flutter/flutter/issues/134042
> Roll Fuchsia with license script fix

- lib/web_ui/skwasm/surface.cpp
Follow-up to https://github.com/flutter/engine/pull/45644 …
> Update skwasm build to use safer flush call

- ci/builders/mac_ios_engine.json
Some builds in ci can happen on arm machines, see https://github.com/flutter/engine/pull/45664/files#r1322197862 …
> [iOS] move arm64 builds to arm machines

- .github/dependabot.yml
This is to autofix problems like: https://github.com/flutter/engine/security/dependabot …
> Auto update dependencies for web_ui.

- impeller/aiks/color_filter.cc
- impeller/aiks/color_filter.h
- impeller/aiks/color_source.cc
- impeller/aiks/image_filter.cc
- impeller/aiks/paint.cc
- impeller/aiks/paint.h
- impeller/entity/contents/filters/blend_filter_contents.cc
- impeller/entity/contents/filters/blend_filter_contents.h
- impeller/entity/contents/filters/color_filter_contents.cc
- impeller/entity/contents/filters/color_filter_contents.h
- impeller/entity/contents/filters/color_matrix_filter_contents.cc
- impeller/entity/contents/filters/linear_to_srgb_filter_contents.cc
- impeller/entity/contents/filters/srgb_to_linear_filter_contents.cc
Part of https://github.com/flutter/flutter/issues/134681.
> [Impeller] Add AbsorbOpacity enum.

- sky/tools/create_macos_framework.py
CP: 0cf5971438b45d8054a6d6fe14f9547abed39747 …
> CP: Fix permissions on macos artifacts (#45598)

- DEPS
> Bump impeller-cmake to HEAD.

- lib/web_ui/skwasm/contour_measure.cpp
This is needed as Skia refactors its #includes internally. …
> Add missing include of SkPath

- ci/builders/linux_fuchsia.json
The cipd packages were all being uploaded and tagged with git:HEAD.
Bug: https://github.com/flutter/flutter/issues/126461 …
> Apply the right tag for linux fuchsia cipd packages.

- impeller/aiks/aiks_unittests.cc
- impeller/entity/contents/framebuffer_blend_contents.cc
Fixes https://github.com/flutter/flutter/issues/134930
> [Impeller] Apply the entity transformation when rendering FramebufferBlendContents

- impeller/tessellator/tessellator.cc
- impeller/tessellator/tessellator.h
issue: https://github.com/flutter/flutter/issues/125749
This removes a global mutable variable, instead giving each tesellator its own struct.  I suspect the root cause of the linked  issue is memory corruption but this is good cleanup anyways.  If for some reason libTess2 is mutating that global variable at cleanup, that could be the source of this problem and this would fix the issue. …
> [Impeller] removed global mutable variable for tessellation allocation function pointers

- DEPS
It was added to the Dart SDK DEPS file here: https://github.com/dart-lang/sdk/commit/04fe6d62fcfc227813aab2ea0bfb7816648c7cac
> Add package:tar to DEPS

- .ci.yaml
With some recent changes led builds can only run if they use -real-build. The migration of fuchsia builds to use -real-build as involved as migrating it to engine v2 and we are implementing the second one. …
> Remove linux fuchsia from recipes cq.

- ci/builders/linux_arm_host_engine.json
- ci/builders/linux_host_desktop_engine.json
- ci/builders/linux_host_engine.json
Part of https://github.com/flutter/flutter/issues/132701
> Switch goma to reclient for Linux host engine targets

- ci/builders/linux_android_aot_engine.json
- ci/builders/linux_fuchsia.json
- ci/builders/linux_unopt.json
Part of https://github.com/flutter/flutter/issues/132701
> Switch goma to reclient for Linux fuchsia/unopt/android_aot

- lib/web_ui/lib/src/engine/navigation/history.dart
I have hit this assertion error many times in tests and this message would be helpful for debugging.
> Add description to assert in `history.dart`

- DEPS
Filed https://github.com/flutter/flutter/issues/135463 to track adding support for auto-updating this dependency as part of the SDK roll.
> Add package:tar to DEPS to fix broken 3H configurations

- lib/ui/painting.dart
The first line is important since it is pulled out into https://api.flutter.dev/flutter/dart-ui/ColorFilter-class.html.  The existing wording is very confusing about what the input actually is.
[CLA]: …
> Clean up the docstring for ColorFilter.matrix

- DEPS
> Bump impeller-cmake to head

- shell/platform/android/io/flutter/plugin/platform/PlatformViewsController.java
* Causing flickering in web views
* Follow up of cl/569435819 for Google to unblock the rolls
> Disable enableHardwareBufferRenderingTarget

- impeller/entity/entity_unittests.cc
- impeller/entity/geometry/point_field_geometry.cc
Fixes https://github.com/flutter/flutter/issues/134068
> [Impeller] Apply the transform to PointFieldGeometry coverage

- DEPS
Pulls in the changes to format GN files.
> Update buildroot to 5d60bd2.

- impeller/renderer/backend/gles/proc_table_gles.cc
- impeller/renderer/backend/gles/render_pass_gles.cc
These tracing functions aren't free!
> [Impeller] Add IMPELLER_DEBUG around group.

- DEPS
> [Impeller] Bump impeller-cmake

- impeller/renderer/backend/gles/gles.h
- impeller/renderer/backend/gles/proc_table_gles.h
- impeller/renderer/backend/gles/sampler_gles.cc
- impeller/renderer/backend/metal/sampler_library_mtl.mm
Fixes https://github.com/flutter/flutter/issues/136153
> [Impeller] Specify default border color for texture wrap mode that clamps.

- shell/platform/darwin/ios/framework/Source/FlutterView.h
- shell/platform/darwin/ios/framework/Source/FlutterView.mm
- shell/platform/darwin/ios/framework/Source/FlutterViewTest.mm
Addresses: https://github.com/flutter/flutter/issues/130828
> Replace deprecated [UIScreen mainScreen] in FlutterView.mm

- impeller/renderer/backend/vulkan/gpu_tracer_vk.cc
Cleanups that seem to reduce occurance of SIGBUS crash, which It turns out I did not in fact fix.
> [Impeller] Vulkan GPU tracer cleanups

- impeller/entity/entity_unittests.cc
- impeller/entity/geometry/point_field_geometry.cc
CP for https://github.com/flutter/flutter/issues/136372
> [CP][Impeller] Apply the transform to PointFieldGeometry coverage (#46428)

- impeller/aiks/aiks_unittests.cc
- impeller/entity/entity_pass.cc
CP for https://github.com/flutter/flutter/issues/136373
> [CP][Impeller] Fixed subpass filter coverage with image filters (#46431).

- impeller/aiks/trace_serializer.cc
helped debug https://github.com/orgs/flutter/projects/21/views/1?pane=issue&itemId=41416077 …
> [Impeller] added trace statements for colorsources

- DEPS
Progress towards https://github.com/flutter/flutter/issues/113052
> Shift some engine DEPS from github to mirrors

- fml/synchronization/sync_switch.h
Fixes the following:
https://github.com/flutter/engine/commit/6b262a0529bea8c58eb763fe15bd8d647dd07641 results in the following error appearing internally when compiling for Android:
```
In file included from fml/synchronization/sync_switch.cc:5:
./fml/synchronization/sync_switch.h:74:34: error: implicit instantiation of undefined template 'std::vector<fml::SyncSwitch::Observer *>'
mutable std::vector<Observer*> observers_;
^
<...>: note: template is declared here
class _LIBCPP_TEMPLATE_VIS vector;
^
1 error generated.
```
b/306266542
[Tree …
> Add missing import

- DEPS
See also:
- https://github.com/flutter/engine/pull/45869
- https://github.com/flutter/buildroot/pull/788
b/300573112
> Update buildroot to remove `-Wno-c99-designator`

- impeller/aiks/aiks_unittests.cc
Not sure how this ended up left off. …
> [Impeller] added missing openplayground

- ci/builders/linux_android_aot_engine.json
The FTL tests were not migrated during the v2 migration.
Bug: https://github.com/flutter/flutter/issues/136767 …
> Adds firebase test lab tests.

- DEPS
https://github.com/flutter/flutter/issues/137557
> Update package:equatable pin

- DEPS
A typo has been fixed.
- Issue fix: Fixes a typo.
[CLA]: …
> [Typo fixed] in DEPS

- impeller/docs/benchmarks.md
This md references `new_gallery_impeller_ios__transition_perf` which is no longer updated. …
> [Impeller] updated ios benchmark link

- .ci.yaml
- ci/builders/linux_fuchsia.json
- tools/fuchsia/upload_to_symbol_server.py
This is the last missing piece to migrate fuchsia to engine v2 and will allow us to remove more of the old recipe versions.
Bug: https://github.com/flutter/flutter/issues/135189
[CLA]: …
> Upload debug symbols in engine v2 fuchsia build.

- impeller/renderer/command.h
- impeller/renderer/render_pass.cc
> [Impeller] removed operator overload (c++ style violation)

- shell/platform/android/io/flutter/embedding/android/KeyData.java
This was introduced in https://github.com/flutter/engine/pull/47315. Internally, this lint breaks the build with the following error:
```
shell/platform/android/io/flutter/embedding/android/KeyData.java:78: Error: DeviceType is an enum, which should be immutable, but field DeviceType.value is not final [ImmutableEnum]
private long value;
~~~~~~~~~~~~~~~~~~~
```
See also https://errorprone.info/bugpattern/ImmutableEnumChecker.
Fixes: b/309552840 …
> Fix ImmutableEnum lint

- lib/ui/hooks.dart
- lib/ui/platform_dispatcher.dart
- lib/ui/window.dart
- lib/web_ui/lib/src/engine/platform_dispatcher.dart
- lib/web_ui/lib/src/engine/window.dart
- lib/web_ui/lib/window.dart
- shell/common/fixtures/shell_test.dart
Relands #47825 with a doc fix (see second commit).
> Reland "Remove physical geometry"

- impeller/geometry/path.cc
- impeller/geometry/path.h
- impeller/geometry/path_builder.cc
- impeller/geometry/path_builder.h
This will simplify the Path internals cleanup that I'd like to land as a part of https://github.com/flutter/flutter/issues/138004
> [Impeller] Remove unused/untested Path APIs.

- build/secondary/third_party/libcxxabi/BUILD.gn
See https://github.com/flutter/flutter/issues/138117
> Add a libcxxabi module that provides support for C++ thread-local storage

- display_list/effects/dl_color_source.h
All changes were made automatically (i.e. with `--fix`).
> Make `display_list/...` compatible with `.clang_tidy`.

- .ci.yaml
Bug: https://github.com/flutter/flutter/issues/135189
Bug: https://github.com/flutter/flutter/issues/132600
Bug: https://github.com/flutter/flutter/issues/126461 …
> Migrate fuchsia to engine v2 builds.

- shell/platform/darwin/macos/framework/Source/FlutterChannelKeyResponderTest.mm
Runs all FlutterChannelKeyResponderTest tests in an AutoReleasepoolTest, which ensures all allocations are cleaned up.
Also replaces the use of OCMock in FlutterChannelKeyResponderTest with a fake FlutterBasicMessageChannel subclass. This avoids unnecessary use of OCMock in the tests, which has been responsible for flakiness in some tests, in particular where the mock is used across threads. This test was not problematic, but the fake makes the tests more readable.
Issue: https://github.com/flutter/flutter/issues/104789
Issue: https://github.com/flutter/flutter/issues/127441
Issue: https://github.com/flutter/flutter/issues/124840 …
> [macOS] Clean up allocations in key responder tests

- lib/web_ui/lib/src/engine/embedder.dart
- lib/web_ui/lib/src/engine/initialization.dart
- lib/web_ui/lib/src/engine/window.dart
- lib/web_ui/test/engine/routing_test.dart
- lib/web_ui/test/engine/surface/platform_view_test.dart
- lib/web_ui/test/engine/window_test.dart
Part of https://github.com/flutter/flutter/issues/134443
Part of https://github.com/flutter/flutter/issues/117098
> [web] Move `EmbeddingStrategy` and `DimensionsProvider` out of `FlutterViewEmbedder`

- testing/scenario_app/android/app/src/main/java/dev/flutter/scenarios/TestActivity.java
This test is run on Firebase Test Lab, and crashes have been reported on CI if this task executes when the activity is in a destroyed state.
See https://github.com/flutter/flutter/issues/138451
> In the scenario game loop test, cancel the results writer task if the activity has been destroyed

- lib/ui/compositing/scene_builder.h
All changes were made automatically (i.e. with `--fix`).
> Make `lib/ui/compositing/...` compatible with `.clang_tidy`.

- lib/ui/semantics.dart
- shell/platform/android/io/flutter/view/AccessibilityBridge.java
I found 3 small typos :)
Supersedes #47929
> Fix a few typos

- DEPS
- ci/licenses_golden/excluded_files
- ci/licenses_golden/licenses_flutter
Captures changes to expose vulkan relaxed rules when compiling GLSL shaders.
> Roll shaderc to google/shaderc@37e25539ce199ecaf19fb7f7d27818716d36686d

- impeller/tessellator/tessellator.cc
- impeller/tessellator/tessellator.h
- impeller/tessellator/tessellator_unittests.cc
Fixes  https://github.com/flutter/flutter/issues/138598
Cherry pick request: https://github.com/flutter/flutter/issues/139146
> [CP][Impeller] revert non-zero tessellation optimization. (#48234)

- impeller/core/shader_types.h
ext_res_0 ?!! its just `binding` but for Metal.
> [Impeller] Document what some of this shader metadata is.

- .github/labeler.yml
- .github/workflows/labeler.yml
* Manually roll labeler action to 5.0.0
* Fix formatting to match `labeler.yml` requirements for 5.0.0
[breaking …
> Update labeler to 5.0.0, fix yaml format for labeler 5.0.0

- impeller/entity/contents/filters/gaussian_blur_filter_contents.cc
A tiny tweak that should be better math since the sigma will scale based on the actual scale amount considering we have to scale down to discrete boundaries for the downsampled texture.  I also turned on linear sampling while I was at it to try to calm down the jitters.  I think it looks better at small sigmas.
test: This is covered by existing golden tests (when we turn this on).
[C++, …
> [Impeller] started taking into account integer gaps in blur sigma, turned on linear filter

- .github/labeler.yml
https://github.com/flutter/flutter/issues/139511
The initial formatting that landed just prevented it from failing, but it turns out the new format is completely overhauled.
[CLA]: …
> Fix labeler not actually doing any labeling

- DEPS
Previously attempted by https://github.com/flutter/engine/pull/48563 but failed because of fixes needed in https://github.com/flutter/engine/pull/48693
> Update clang revision from 00396e6a1a0b7 to b3a9e8f7c0afb00.

- impeller/entity/contents/filters/directional_gaussian_blur_filter_contents.cc
- impeller/entity/contents/filters/gaussian_blur_filter_contents.cc
- impeller/entity/contents/filters/gaussian_blur_filter_contents.h
- impeller/entity/contents/filters/gaussian_blur_filter_contents_unittests.cc
fixes `AiksTests.CanRenderBackdropBlurHugeSigma/Metal`
I also tweaked the existing quadratic equation to make sure the minima is at 500 and `f(0) = 1`. …
> [Impeller] Clamp new blur sigma

- impeller/entity/entity_unittests.cc
> [Impeller] made the blur entity test able to use the new blur

- ci/builders/linux_web_engine.json
- lib/web_ui/dev/generate_builder_json.dart
Update macOS web tests to run on macOS 13 and arm64. Changed so test is consistent OS and architecture, which will cause less discrepancy in goldens.
Fixes https://github.com/flutter/flutter/issues/139924. …
> Allow tests to run on macOS 13

- .ci.yaml
- ci/builders/mac_android_aot_engine.json
- ci/builders/mac_host_engine.json
- ci/builders/mac_ios_engine.json
- ci/builders/mac_unopt.json
mac_toolchain has been updated to no longer have 2 minute slowdown (https://github.com/flutter/flutter/issues/138109), so unpin to use the latest version. …
> Unpin mac_toolchain version

- lib/web_ui/lib/src/engine/mouse/cursor.dart
- lib/web_ui/lib/src/engine/platform_dispatcher.dart
- lib/web_ui/test/engine/mouse/cursor_test.dart
This is a temporary workaround to get mouse cursor working in multi-view (until https://github.com/flutter/flutter/issues/140226 is resolved).
> [web] Set cursor property on body

- impeller/aiks/aiks_unittests.cc
- impeller/aiks/paint_pass_delegate.cc
- impeller/entity/contents/clip_contents.cc
- impeller/entity/contents/clip_contents.h
- impeller/entity/contents/contents.cc
- impeller/entity/contents/contents.h
- impeller/entity/entity.cc
- impeller/entity/entity_pass.cc
- impeller/entity/entity_pass.h
- impeller/entity/entity_unittests.cc
This PR cherry-picks the following two commits:
https://github.com/flutter/engine/commit/2dbc5d2c576ae3e80b23c28e3f4989e79821b41d
https://github.com/flutter/engine/commit/0b0fab8215362f50a034d108ad11fbb8e93c3fce
to address https://github.com/flutter/flutter/issues/139571
> [CP] Fix for AnimatedOpacity affects blended color overlay render

- testing/litetest/lib/src/test_suite.dart
- testing/litetest/test/litetest_test.dart
Fixes https://github.com/flutter/flutter/issues/140481
Before this fix, if all tests are skipped, the `onDone` callback never fires, which means the recieve port never closes, which means the process just hangs indefinitely (and the success message is never printed).
> Make sure to finish the suite if all tests are skipped

- impeller/aiks/aiks_unittests.cc
- impeller/core/shader_types.h
- impeller/entity/contents/runtime_effect_contents.cc
- impeller/entity/entity_unittests.cc
- impeller/fixtures/BUILD.gn
- impeller/golden_tests/golden_playground_test.h
- impeller/playground/playground.h
- impeller/playground/playground_test.h
- impeller/renderer/backend/gles/buffer_bindings_gles.cc
- impeller/runtime_stage/runtime_stage_unittests.cc
Makes fragment programs work for OpenGLES backend.
Fixes https://github.com/flutter/flutter/issues/113715
Fixes https://github.com/flutter/flutter/issues/105538
I cannot find a dedicated issue for this, but there probably is someone somewhere and I don't want to file a new one for it.
> Start wiring up fragment program for OpenGLES

- ci/licenses_golden/excluded_files
- impeller/aiks/BUILD.gn
- impeller/aiks/aiks_path_unittests.cc
- impeller/aiks/aiks_unittests.cc
issue: https://github.com/flutter/flutter/issues/140106
tests: refactor of code …
> [Impeller] pulled out the path unit tests to their own file

- README.md
https://github.com/flutter/flutter/issues/140460
> Add Flutter CI status to README

- fml/logging_unittests.cc
This test reads back logged messages on Fuchsia to verify that FML logging has the log sink setup correctly. However, it relies on internal implementation details of the Fuchsia log packet format, which recently changed (to support structured logging) and it broke this test. Since there isn't a supported way to parse structured log packets outside of the Fuchsia repository, I'm removing this test to unblock the SDK roll.
flutter/flutter#140950
b/315973146 …
> [fuchsia] Remove LoggingSocketTest.UseSyslogOnFuchsia test

- impeller/entity/contents/filters/gaussian_blur_filter_contents.cc
- impeller/entity/contents/filters/gaussian_blur_filter_contents_unittests.cc
This is an optimization where we chop off samples at the end since they contribute < 1.56% of the solution. …
> [Impeller] new blur: chop off blur extremities

- impeller/entity/contents/solid_color_contents.cc
- impeller/entity/contents/vertices_contents.cc
- impeller/entity/geometry/round_rect_geometry.cc
Copying the shared ptr when we don't need to results in us incrementing/decrementing the ref count which isn't free.
> [Impeller] dont accidentally copy shared ptr.

- .ci.yaml
- .gitignore
- DEPS
- ci/builders/linux_android_emulator.json
- ci/builders/linux_unopt.json
- ci/builders/mac_unopt.json
- ci/builders/standalone/linux_benchmarks.json
- tools/gn
Relands https://github.com/flutter/engine/pull/49416
> Relands: Refactors RBE support

- ci/builders/standalone/linux_license.json
- ci/licenses_golden/excluded_files
Last piece to fix: https://github.com/flutter/flutter/issues/141461
> Add gclient_variables back for linux_license and fix the excluded files

- impeller/entity/entity_pass.cc
> [Impeller] Eliminate some shared_ptr copying from EntityPass::Render

- .ci.yaml
This will remove some of the stress on x64 machines and will help to get faster builds on dart-internal.
[breaking …
> CP: Use any mac machine available for orchestrator run. (#49845)

- ci/licenses_golden/licenses_flutter
- display_list/testing/dl_test_surface_metal.cc
- impeller/aiks/aiks_unittests.cc
- impeller/golden_tests/BUILD.gn
- impeller/golden_tests/golden_playground_test_mac.cc
- impeller/golden_tests/golden_tests.cc
- impeller/golden_tests/metal_screenshot.h
- impeller/golden_tests/metal_screenshot.mm
- impeller/golden_tests/metal_screenshotter.h
- impeller/golden_tests/metal_screenshotter.mm
- impeller/golden_tests/screenshot.h
- impeller/golden_tests/screenshotter.h
- impeller/golden_tests/vulkan_screenshotter.cc
- impeller/golden_tests/vulkan_screenshotter.h
- impeller/golden_tests/vulkan_screenshotter.mm
- impeller/playground/backend/vulkan/playground_impl_vk.cc
- impeller/renderer/backend/vulkan/formats_vk.h
- impeller/renderer/backend/vulkan/surface_context_vk.cc
- impeller/renderer/backend/vulkan/surface_context_vk.h
- impeller/renderer/backend/vulkan/texture_vk.h
fixes https://github.com/flutter/flutter/issues/141705 …
> [Impeller] adds vulkan golden images

- impeller/renderer/backend/vulkan/render_pass_vk.cc
Tested: currently broken test!
> [Impeller] null check vertex buffer.

- DEPS
> Update buildroot for fidl_binding_deps() support in the Fuchsia SDK

- impeller/entity/geometry/geometry.cc
Follow up to https://github.com/flutter/engine/pull/49910#pullrequestreview-1840067150.
> Fix a typo in `geometry.cc#ComputeUVGeometryForRect`.

- impeller/aiks/aiks_unittests.cc
- impeller/golden_tests/BUILD.gn
- impeller/golden_tests/golden_playground_test.h
- impeller/golden_tests/golden_playground_test_mac.cc
- impeller/golden_tests/vulkan_screenshotter.h
- impeller/golden_tests/vulkan_screenshotter.mm
- impeller/playground/playground.cc
- impeller/playground/playground.h
fixes https://github.com/flutter/flutter/issues/142052 …
> [Impeller] Share vulkan playground across goldens

- DEPS
Final migration away from github + fuchsia, cleanup references. 
New mirrors stood up at https://flutter.googlesource.com/third_party/ocmock/, https://flutter.googlesource.com/third_party/protobuf/, 
https://flutter.googlesource.com/third_party/protobuf-gn/ and all three are verified to be publically readable.
Addresses b/316411022
[Flutter Style …
> Fuchsia + ocmock mirror migration

- impeller/golden_tests/golden_playground_test_mac.cc
fixes https://github.com/flutter/flutter/issues/142017 …
> [Impeller] turned on vulkan validation for all but one golden test

- impeller/typographer/lazy_glyph_atlas.cc
This is from the google3 roll. Adding this cuts down on noise for rollers.
> Add include suggested by clang-tidy

- shell/common/rasterizer.cc
- testing/scenario_app/ios/Scenarios/ScenariosTests/FlutterViewControllerTest.m
> Followups to screenshot patch

- .ci.yaml
Last step of https://github.com/flutter/flutter/issues/141688
> Move Mac builder_cache to prod

- impeller/aiks/aiks_unittests.cc
- impeller/aiks/canvas.cc
- impeller/aiks/canvas.h
- impeller/entity/contents/solid_rrect_blur_contents.cc
- impeller/entity/contents/solid_rrect_blur_contents.h
- impeller/entity/entity_unittests.cc
- impeller/entity/shaders/rrect_blur.frag
- impeller/tools/malioc.json
Cherry-picks https://github.com/flutter/engine/pull/49994 into release candidate 3.19
> [CP] [Impeller] allow non-square corner radii for fast blurs

- testing/run_tests.py
fixes https://github.com/flutter/flutter/issues/142657 …
> [Impeller] added an assert that goldens are generated

- shell/platform/android/io/flutter/embedding/engine/FlutterJNI.java
Related https://github.com/flutter/flutter/issues/83596
> Provide a more helpful error message in the case of UnsatisfiedLinkError

- impeller/golden_tests/vulkan_screenshotter.mm
- testing/run_tests.py
followup from https://github.com/flutter/engine/pull/50146 …
> [Impeller] updated todos from opengles golden work

- .ci.yaml
For https://github.com/flutter/flutter/issues/142811
> Move linux_fuchsia to staging

- ci/builders/linux_fuchsia.json
- shell/platform/fuchsia/dart_runner/embedder/BUILD.gn
- shell/platform/fuchsia/dart_runner/kernel/BUILD.gn
- shell/platform/fuchsia/dart_runner/vmservice/BUILD.gn
- shell/platform/fuchsia/flutter/kernel/BUILD.gn
- testing/fuchsia/run_tests.py
- testing/fuchsia/test_suites.yaml
Reverts flutter/engine#50058 for https://github.com/flutter/flutter/issues/142811
> Revert "[Fuchsia] Execute most of the testing/fuchsia/test_suites.yaml on debug and release builds"

- impeller/aiks/aiks_unittests.cc
- impeller/core/allocator.cc
- impeller/entity/contents/contents.cc
> [Impeller] blur: removed ability to request out of bounds mip_counts

- CONTRIBUTING.md
> Fixed CONTRIBUTING.md markdown lints

- .github/workflows/engine-cp.yml
context: https://github.com/flutter/engine/pull/50265#pullrequestreview-1868207906
minor fix to license year.
> [github actions] update license year

- third_party/txt/src/txt/platform_mac.mm
This fixes Core Foundation object leaks.
----
Unrelated, just as exciting: Today is the last day before the Chinese New Year, and I wish everyone a Happy New Year of the Dragon, Xin Nian Kuai Le! :)
[CLA]: …
> Fix Core Foundation object leaks.

- CONTRIBUTING.md
fixes https://github.com/flutter/flutter/issues/143087 …
> Updated CONTRIBUTING.md to have a testing section

- impeller/renderer/backend/vulkan/context_vk.cc
- impeller/renderer/backend/vulkan/context_vk.h
see https://github.com/flutter/engine/pull/50484
> [Impeller] Remove the unused Vulkan queue submit task runner

- lib/ui/painting.dart
Closes https://github.com/flutter/flutter/issues/142937.
> Make `dart:ui#Paint` `final` to allow changes/disallow implementing.

- .ci.yaml
- ci/builders/linux_android_emulator.json
Partial work towards https://github.com/flutter/flutter/issues/143351.
I filed https://github.com/flutter/flutter/issues/143374 about the state of the docs, it was hard to figure this out.
> Run Skia and Impeller OpenGLES on APIv28.

- impeller/docs/benchmarks.md
Looks like we changed devices sometime in august.  This mostly switches comparisons from using Samsung galaxy 10 to pixel 7 pro. …
> [Impeller] Updated benchmarks

- shell/platform/darwin/ios/framework/Source/FlutterViewController.mm
- shell/platform/darwin/ios/framework/Source/FlutterViewControllerTest.mm
This reverts commit 472df4138488eea7220967be29808398e6e8f545.
Reverts https://github.com/flutter/engine/pull/50364
fixes https://github.com/flutter/flutter/issues/143642
[test-exempt]: …
> Revert "Fix iOS password autofill prompt dismissal causes layout to resize (#50364)"

- ci/builders/linux_android_emulator.json
- ci/builders/linux_android_emulator_api_33.json
- ci/builders/linux_android_emulator_opengles.json
- ci/builders/linux_clang_tidy.json
- ci/builders/linux_host_desktop_engine.json
- ci/builders/mac_clang_tidy.json
- ci/builders/mac_unopt.json
- tools/gn
- tools/pkg/engine_build_configs/bin/check.dart
This is expected to help with https://github.com/flutter/flutter/issues/132807
> Make global builds uniquely named per platform

- CONTRIBUTING.md
I am open to suggestions for other things to write under "Skia Gold".
> Clean up contributing formatting, add a Skia gold callout

- .ci.yaml
For https://github.com/flutter/flutter/issues/142010
> Change "Linux mac_unopt" to "Mac mac_unopt"

- .ci.yaml
Second half of https://github.com/flutter/flutter/issues/142010
> Remove 'bringup: true' from 'Mac mac_unopt'

- .ci.yaml
Follow-up from https://github.com/flutter/engine/pull/50954
> Move linux_android_emulator_skia builder to prod

- flow/frame_timings.cc
- flow/frame_timings.h
- lib/ui/painting/image_dispose_unittests.cc
- lib/ui/window/platform_configuration.cc
- lib/ui/window/platform_configuration.h
- runtime/runtime_controller.cc
- runtime/runtime_controller.h
- runtime/runtime_delegate.h
- shell/common/animator.cc
- shell/common/animator.h
- shell/common/animator_unittests.cc
- shell/common/engine.cc
- shell/common/engine.h
- shell/common/engine_unittests.cc
- shell/common/fixtures/shell_test.dart
- shell/common/input_events_unittests.cc
- shell/common/rasterizer.cc
- shell/common/shell_test.cc
- shell/common/shell_test.h
- shell/common/shell_unittests.cc
- testing/dart/platform_view_test.dart
This reverts commit 81035b7d56efd2d2b6c1ebd99d7cbe72cc683f90.
Reason: Internal test failure blocking roll
OCL:610420483:BASE:610486571:1708978396098:f2c3c31 …
> Revert "Reland 4: Multiview pipeline (#50931)"

- sky/tools/create_macos_framework.py
Process (including stripping) FlutterMacOS.framework before creating it as an xcframework.
Should fix https://github.com/flutter/flutter/issues/144251. …
> Process FlutterMacOS.framework before creating xcframework

- ci/builders/mac_clang_tidy.json
Reverting for build time regression: https://github.com/flutter/engine/pull/51057#issuecomment-1969647657
> Revert to goma on mac_clang_tidy builder

- DEPS
- ci/licenses_golden/excluded_files
- ci/licenses_golden/licenses_third_party
Our abseil dependency is a clone of Chromium's, located at: https://chromium.googlesource.com/chromium/src/third_party/
which is a downstream copy of the source of truth, located at: https://github.com/abseil/abseil-cpp
This rolls to Chromium commit 185f27671ca28c0f25d9d7a15b6e621f69972706, then reapplies jsimmons@google.com's commits, in chronological order:
* 9ec8f453a42aad2f11a1760fe4ce6014a124edc2
* f92f9effc89af7692436c3b9fbb3a67f2239d893
* 61833f2c057a2b1993d871e8c51156aed1dd4354
Preparation for: https://github.com/flutter/flutter/issues/144201
Part of: https://github.com/flutter/flutter/issues/67373 …
> Roll abseil-cpp to 1db3bdd4eb208bef55c77f22aa94991e52225230

- testing/scenario_app/bin/utils/adb_logcat_filtering.dart
- testing/scenario_app/test/adb_log_filter_test.dart
- testing/scenario_app/test/src/fake_adb_logcat.dart
Closes https://github.com/flutter/flutter/issues/144346.
> The `adb logcat` filtering will continue until morale improves.

- lib/web_ui/lib/ui_web/src/ui_web/initialization.dart
Fixes https://github.com/flutter/flutter/issues/143976
> [web] Drop noisy prints from bootstrapping logic

- shell/platform/fuchsia/flutter/component_v2.h
Bug: https://fxbug.dev/42078310
> [fuchsia] Prepare for @transitional removal

- impeller/entity/contents/content_context.h
Turn the page, wash your hands.
Addresses the following issues:
* https://github.com/flutter/flutter/issues/143077
* https://github.com/flutter/flutter/issues/137714
* https://github.com/flutter/flutter/issues/138460
* https://github.com/flutter/flutter/issues/123671
* https://github.com/flutter/flutter/issues/141961
* https://github.com/flutter/flutter/issues/134432
Previous attempt:
- https://github.com/flutter/engine/pull/50856
- reverted with https://github.com/flutter/engine/pull/51191
- fixed with https://github.com/flutter/engine/pull/51198
> [Impeller] Enable depth buffer clipping & Stencil-then-Cover path rendering.

- shell/platform/linux/fl_texture_registrar_test.cc
For https://github.com/flutter/flutter/issues/138197
> Disable flaky linux desktop test

- ci/builders/mac_host_engine.json
https://github.com/flutter/flutter/issues/144700
> Skip impeller goldens on release branches

- impeller/aiks/aiks_blur_unittests.cc
- impeller/aiks/aiks_unittests.cc
issue: https://github.com/flutter/flutter/issues/140106 …
> [Impeller] moved tests to aiks_blur_unittests, added warning

- .ci.yaml
Reverts flutter/engine#50893
Necessary to bring infra back online.
> [g3 roll] Revert "Remove unused drone_dimension field" (#51214)

- ci/builders/mac_host_engine.json
The tests are not running when they should be: https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20Engine%20Drone/760676/overview
> Revert test if changes to golden tests

- DEPS
To pick up https://github.com/flutter/buildroot/pull/834
> Roll buildroot to e9df434539745202fa5f9b729fe5f82e5de3f025

- testing/dart/observatory/tracing_test.dart
For https://github.com/flutter/flutter/issues/144394
> Remove flaky check from observatory/tracing_test.dart

- testing/scenario_app/bin/run_android_tests.dart
Attempt to work around the minor 1px differences from https://github.com/flutter/flutter/issues/145058
> [scenario app] make image matching fuzzier.

- impeller/docs/renderdoc_frame_capture.md
I still haven't figured out how to make this work, but here's some additional details that I did figure out!
> Add details to renderdoc_frame_capture.md

- impeller/docs/renderdoc_frame_capture.md
Now that I have it working, here's everything I learned.
> More renderdoc_frame_capture.md updates

- shell/platform/android/io/flutter/embedding/engine/loader/FlutterLoader.java
follow up to https://github.com/flutter/engine/pull/51534#discussion_r1532301441 …
> Add even more logging for UnsatisfiedLinkError

- tools/golden_tests_harvester/bin/golden_tests_harvester.dart
- tools/golden_tests_harvester/lib/golden_tests_harvester.dart
- tools/golden_tests_harvester/test/golden_tests_harvester_test.dart
fixes https://github.com/flutter/flutter/issues/145413 …
> [golden_test_harvester]: Put back sending the dimensions to the SkiaGoldClient

- ci/licenses_golden/excluded_files
- impeller/aiks/BUILD.gn
- impeller/aiks/aiks_blend_unittests.cc
- impeller/aiks/aiks_unittests.cc
> [Impeller] split out aiks blend tests

- .ci.yaml
Further work towards https://github.com/flutter/flutter/issues/141641.
> Rename `Mac clangd` to `Linux mac_clangd`

- testing/scenario_app/android/app/src/main/java/dev/flutter/scenarios/ExternalTextureFlutterActivity.java
- testing/scenario_app/android/app/src/main/java/dev/flutter/scenarios/TestableFlutterActivity.java
- testing/scenario_app/bin/run_android_tests.dart
- testing/scenario_app/lib/main.dart
- testing/scenario_app/tool/deflake_android_tests.sh
Work towards https://github.com/flutter/flutter/issues/145988.
... as well as handle `sigTerm` (perhaps would help us actually write out logs? we'll see)
> Add more Java and Dart logging to `scenario_app` (for now)

- testing/scenario_app/android/app/src/main/AndroidManifest.xml
- testing/scenario_app/android/app/src/main/java/dev/flutter/scenarios/TestActivity.java
- testing/scenario_app/lib/main.dart
All of this appears to be completely unused and untested, and I don't see value in fixing it.
> Remove unused and untested timeline data branch for `scenario_app`

- .ci.yaml
- ci/builders/linux_android_emulator_debug_on_ci.json
Trying to reproduce https://github.com/flutter/flutter/issues/145988 outside of texture tests.
/cc @ricardoamador
> Run the `DrawSolidBlueScreenTest` 5x in a row in bringup builds.

- ci/builders/linux_android_emulator.json
- ci/builders/linux_android_emulator_skia.json
Similar to https://github.com/flutter/engine/pull/51838.
> Use internal retries for SurfaceTexture and Impeller tests too.

- testing/scenario_app/android/app/src/main/java/dev/flutter/scenarios/TextPlatformViewFactory.java
I am now investigating why this is needed.
> [scenarios] dont do a weird invalidate on TextView.

- testing/scenario_app/android/app/src/androidTest/java/dev/flutter/scenariosui/ScreenshotUtil.java
- testing/scenario_app/bin/run_android_tests.dart
Use the screenshotUtil signal to have the runner take a screenshot with adb. Block the screenshotter until this has completed.
> [scenarios] Use adb to take screenshot, block on screenshot operation.

- impeller/core/host_buffer.cc
- impeller/core/host_buffer.h
Remove some autos, make some things const refs, move some shared_ptrs.
> [Impeller] cleanup auto usage in host_buffer

- shell/common/animator.cc
- testing/dart/observatory/tracing_test.dart
- testing/dart/serialized_test_suite.dart
Fixes https://github.com/flutter/flutter/issues/145853
> Generate only one "Frame Request Pending" event for each pending call to BeginFrame

- tools/engine_tool/lib/src/commands/build_command.dart
- tools/engine_tool/lib/src/commands/query_command.dart
- tools/engine_tool/lib/src/commands/run_command.dart
- tools/engine_tool/lib/src/commands/test_command.dart
The multiline string literal retains the newlines.
> [et] Fixup help text a bit

- ci/builders/linux_android_aot_engine.json
- ci/builders/linux_android_debug_engine.json
- ci/builders/linux_android_emulator.json
- ci/builders/linux_android_emulator_skia.json
- ci/builders/linux_arm_host_engine.json
- ci/builders/linux_clang_tidy.json
- ci/builders/linux_fuchsia.json
- ci/builders/linux_host_desktop_engine.json
- ci/builders/linux_host_engine.json
- ci/builders/linux_unopt.json
- ci/builders/linux_unopt_debug_no_rbe.json
- ci/builders/local_engine.json
- ci/builders/mac_android_aot_engine.json
- ci/builders/mac_clang_tidy.json
- ci/builders/mac_host_engine.json
- ci/builders/mac_impeller_cmake_example.json
- ci/builders/mac_ios_engine.json
- ci/builders/mac_unopt.json
- ci/builders/mac_unopt_debug_no_rbe.json
- ci/builders/standalone/linux_benchmarks.json
- ci/builders/standalone/linux_license.json
- ci/builders/standalone/windows_unopt.json
- ci/builders/windows_android_aot_engine.json
- ci/builders/windows_arm_host_engine.json
- ci/builders/windows_host_engine.json
- tools/engine_tool/lib/src/commands/command.dart
- tools/pkg/engine_build_configs/lib/src/build_config.dart
- tools/pkg/engine_build_configs/test/build_config_test.dart
- tools/pkg/engine_build_configs/test/fixtures.dart
Step 4 of https://github.com/flutter/flutter/issues/145263
Hopefully these descriptions will be more useful than the list of GN args.
> Adds human readable descriptions to build configs

- .ci.yaml
- ci/builders/local_engine.json
- shell/platform/android/BUILD.gn
- testing/android/native_activity/native_activity_apk.py
Finishes part 2 of https://github.com/flutter/flutter/issues/145263.
This required fixing a python script to use the version of Java obtained through the DEPS file rather than one assumed to exist in the environment.
> Run local_engine.json builds in prod

- impeller/entity/contents/clip_contents.cc
- impeller/entity/contents/clip_contents.h
Follow-up for https://github.com/flutter/engine/pull/51992.
This is now dead code.
> [Impeller] Remove stencil clipping logic.

- shell/platform/android/io/flutter/embedding/engine/renderer/FlutterRenderer.java
Fixes https://github.com/flutter/flutter/issues/146465
This callback needs to run on the platform main thread. Since it was just constructing a handler, that would callback from whatever thread it was created from. Update this to specifically create a main thread handler.
> [Android] post image task to main handler.

- ci/builders/local_engine.json
Last-ish part of https://github.com/flutter/flutter/issues/145263
> Adds iOS builds to local_engine.json

- testing/run_tests.py
Fixes https://github.com/flutter/flutter/issues/143330
> Enable gtest-parallel for Impeller unit tests

- ci/builders/mac_host_engine.json
- impeller/aiks/aiks_blend_unittests.cc
- impeller/aiks/aiks_unittests.cc
- impeller/golden_tests/golden_playground_test_mac.cc
- impeller/playground/backend/metal/playground_impl_mtl.mm
- impeller/playground/playground_test.cc
- lib/ui/painting/image_encoding_impeller.cc
- shell/platform/darwin/ios/framework/Source/FlutterMetalLayer.mm
- shell/platform/darwin/ios/framework/Source/FlutterOverlayView.mm
- shell/platform/darwin/ios/framework/Source/FlutterView.mm
relands https://github.com/flutter/engine/pull/52019
Patch addresses the compilation problem noted in https://github.com/flutter/engine/pull/52019#issuecomment-2058006113
[CLA]: …
> Relands "[Impeller] moved to bgra10_xr (#52019)"

- testing/pkg_test_demo/pubspec.yaml
`package:web_socket` is used by newer versions `package:web_socket_channel`. …
> Add a dependency on `package:web_socket` in pkg_demo_test

- .ci.yaml
> Remove TODO I will never do: `runIfNot` is deprecated.

- docs/rbe/rbe.md
issue https://github.com/flutter/flutter/issues/147739 …
> Updated RBE documentation for default credentials.

- impeller/renderer/backend/vulkan/swapchain/ahb/ahb_swapchain_impl_vk.cc
The reference to these was garbage in the submit info.
> [Impeller] In the AHB swapchain, make the wait stages be non-temporaries.

- impeller/README.md
- impeller/docs/glossary.md
Fixes https://github.com/flutter/flutter/issues/107609
> [Impeller] Start a glossary.

- ci/builders/local_engine.json
Adds --no-lto.
This reverts commit 1fe835b85f5c23f500268b82dfd043c9f0eb8ca1.
> Reland "Add host_profile_arm64 and host_release_arm64 local engine configurations."

- analysis_options.yaml
related issue https://github.com/Dart-Code/Dart-Code/issues/5101 …
> updated analysis exclusion

- DEPS
Roll buildroot to pick up https://github.com/flutter/buildroot/pull/854
> Roll buildroot to 70a42312a688

- impeller/playground/README.md
- lib/ui/compositing.dart
- lib/ui/geometry.dart
- lib/ui/painting.dart
Reverts flutter/engine#52623
Reason for revert is noted on the PR.
> Revert "Various documentation improvements (#52600)"

- impeller/typographer/rectangle_packer.cc
- impeller/typographer/rectangle_packer.h
- impeller/typographer/typographer_unittests.cc
Fixes https://github.com/flutter/flutter/issues/148251
Work towards https://github.com/flutter/flutter/issues/138798
The rectangle packer was only filling up the top and right edge of each rectangle, making the atlas super inefficient.
> [Impeller] rectangle packer actually packs.

- shell/platform/fuchsia/dart_runner/tests/startup_integration_test/dart_aot_runner/meta/dart-aot-runner-integration-test.cml
- shell/platform/fuchsia/dart_runner/tests/startup_integration_test/dart_jit_runner/meta/dart-jit-runner-integration-test.cml
- shell/platform/fuchsia/flutter/meta/common.shard.cml
- shell/platform/fuchsia/flutter/tests/integration/mouse-input/meta/mouse-input-test.cml
- shell/platform/fuchsia/flutter/tests/integration/mouse-input/mouse-input-view/meta/mouse-input-view.cml
Route fuchsia.sysmem2.Allocator everywhere that
fuchsia.sysmem.Allocator is routed.
fixes flutter/flutter#146858
> [fuchsia][sysmem2] route fuchsia.sysmem2.Allocator

- DEPS
- lib/web_ui/dev/roll_fallback_fonts.dart
- lib/web_ui/lib/src/engine/font_fallback_data.dart
- lib/web_ui/test/ui/fallback_fonts_golden_test.dart
This PR adds the "Noto Serif Tibetan" fallback font to Flutter Web, so it can render Dzongkha, and other languages in Tibetan script.
(In order to add this fallback font, an automated script is run which updates the versions and glyphs of other fallback fonts at the same time)
(Bundle uploaded to CIPD)
* Fixes https://github.com/flutter/flutter/issues/148797
* Added unit test for font resolution with sample text
* Manually, in localhost, using the sample Dzongkha test from the Noto site:
```
དེ་ཡང་ འཛམ་གླིང་ནང་གི་ཞི་བདེ་དང་དྲང་ཁྲིམས། དེ་ལས་དལ་དབང་ཚུ་གི་གཞི་འགྱམ་གཙོ་བོ་དེ་
``` …
> [web] Adds Noto Serif Tibetan fallback font.

- impeller/renderer/backend/vulkan/debug_report_vk.cc
Workaround for https://github.com/flutter/flutter/issues/149111
> [Impeller] Suppress SPIRV validation errors in latest Vulkan SDK.

- lib/ui/painting.dart
- lib/web_ui/lib/painting.dart
- testing/dart/painting_test.dart
https://github.com/flutter/flutter/issues/148253
> Switch to FilterQuality.medium for images

- CONTRIBUTING.md
`engine_dev_setup` moved to markdown
[C++, …
> Update CONTRIBUTING.md links

- lib/ui/painting/image_encoding_unittests.cc
fixes: https://github.com/flutter/flutter/issues/148851
depends on: 
- https://skia-review.googlesource.com/c/skcms/+/861638
- https://skia-review.googlesource.com/c/skia/+/861516
[CLA]: …
> [Impeller] added test for bgra10xr png encoding

- tools/gn
> Remove the DBC interpreter flag.

- ci/builders/linux_web_engine.json
- lib/web_ui/dev/common.dart
- lib/web_ui/dev/generate_builder_json.dart
- lib/web_ui/dev/package_lock.yaml
Just updating Chrome For Testing because we're about six versions out of date now.
> Update Chrome to 125.

- ci/builders/linux_web_engine.json
- lib/web_ui/dev/generate_builder_json.dart
Temporary solution for https://github.com/flutter/flutter/issues/150023 …
> Temporarily run Linux linux_web_engine Mac tests on Mac-13 only

- shell/platform/android/io/flutter/plugin/common/StandardMessageCodec.java
corrects StandardMessageCodec return nullability annotation.
> Update StandardMessageCodec.readValue to be @Nullable

- lib/web_ui/lib/src/engine/dom.dart
- lib/web_ui/lib/src/engine/keyboard_binding.dart
- lib/web_ui/lib/src/engine/platform_dispatcher/view_focus_binding.dart
- lib/web_ui/lib/src/engine/pointer_binding.dart
- lib/web_ui/lib/src/engine/text_editing/text_editing.dart
- lib/web_ui/test/engine/text_editing_test.dart
Relands: [**Fix focus management for text fields** (#51009)](https://github.com/flutter/engine/pull/51009) by:
* Reverting commit: https://github.com/flutter/engine/commit/cf3ac2d0f5c68b9979c1b7e24a43d41b4d06e5ef (https://github.com/flutter/engine/pull/53502).
* Keeping the new `ViewFocusBinding` disabled, as [suggested](https://github.com/flutter/engine/pull/51009#discussion_r1649500122). …
> [web] Reland "Fix focus management for text fields (#51009)"

- DEPS
- impeller-cmake: https://github.com/bdero/impeller-cmake/pull/25
- impeller-cmake-example: https://github.com/bdero/impeller-cmake-example/pull/23
> Bump impeller-cmake-example

- impeller/entity/contents/filters/gaussian_blur_filter_contents.cc
- impeller/entity/contents/filters/gaussian_blur_filter_contents.h
This is a refactor, no functional change.
We have a few issues in flight that talk about improving the blur.  This attempts to clean everything up a bit to make it easier for us to change.
issues: 
- https://github.com/flutter/flutter/issues/150713
- https://github.com/flutter/flutter/issues/150722
- https://github.com/flutter/flutter/issues/150720 …
> [impeller] Cleanup blur

- shell/platform/darwin/ios/framework/Source/FlutterUndoManagerPlugin.mm
- shell/platform/darwin/ios/framework/Source/FlutterUndoManagerPluginTest.mm
When `FlutterUndoManagerPlugin` deallocated, it is supposed to deregister itself from the `NSUndoManager` stack.
However, during dealloc `_undoManagerDelegate.undoManager` is nil (`_undoManagerDelegate` = the engine, and `undoManager` was its view controller's `undoManager`, which was already gone).
Since `_undoManagerDelegate.undoManager` is nil, it doesn't actually call `-[NSUndoManager removeAllActionsWithTarget]`. In the add-to-app scenario, after the view controller pops back to the native view, and "undo" is invoked, the undo action for the `FlutterUndoManagerPlugin` is handled, but it already dealloced so crash.
Fixes https://github.com/flutter/flutter/issues/150408 …
> Remove FlutterUndoManagerPlugin handlers from undo manager on dealloc

- ci/licenses_golden/excluded_files
- ci/licenses_golden/tool_signature
- tools/licenses/lib/paths.dart
This directory consistes of patches that Chromium's maintainers of the Chromium ICU fork have already applied to the ICU source code.
Usually these are fix-forwards that have been applied to the ICU library after it has been released.
The patch files are kept to ensure that the patches are applied if we ever need to create a new branch, or update the major ICU version.
The patch files specifically do *not* get used during the build process.
Issues: https://github.com/flutter/flutter/issues/151116
[test-exempt]: …
> [icu] Ignores the dir `flutter/third_party/icu/patches`

- ci/builders/local_engine.json
We have these configs for Linux & macOS.
> Add a host_debug_unopt local engine config for Windows.

- impeller/compiler/impellerc_main.cc
- impeller/entity/entity_pass.cc
- impeller/geometry/rect.h
- impeller/golden_tests/golden_playground_test.h
- impeller/golden_tests/golden_playground_test_mac.cc
- impeller/golden_tests/vulkan_screenshotter.mm
- impeller/playground/playground.h
- impeller/renderer/backend/gles/blit_command_gles.cc
- impeller/renderer/backend/gles/pipeline_library_gles.cc
- impeller/renderer/backend/gles/proc_table_gles.h
- impeller/renderer/backend/gles/render_pass_gles.cc
- impeller/renderer/backend/metal/compute_pass_mtl.mm
- impeller/renderer/backend/metal/pipeline_library_mtl.mm
- impeller/renderer/backend/metal/render_pass_mtl.mm
- impeller/renderer/backend/vulkan/capabilities_vk.cc
- impeller/renderer/backend/vulkan/context_vk.cc
- impeller/renderer/backend/vulkan/swapchain/swapchain_vk.cc
- impeller/typographer/backends/skia/text_frame_skia.cc
- impeller/typographer/backends/skia/typographer_context_skia.cc
There are still tons of TODOs without issues assigned to them that I'm having a harder time tracking them down. But this cleanup is easy.
> [Impeller] Cleanup stale TODOs and fixup the format of others.

- tools/android_sdk/packages.txt
This file should always be kept in sync with what we are actually using, but it seems to currently be out of sync. …
> Align `tools/android_sdk/packages.txt` with what is uploaded to CIPD

- build/archives/BUILD.gn
The existing comment on gen_snapshot is unclear. Adds comments where they were missing. Saves future readers some digging through git blame. …
> Add doc comments to build/archives/BUILD.gn

- DEPS
To pick up https://github.com/flutter/buildroot/pull/876
> Roll buildroot to 327906297b49980748ea1956019829e7c434a03e

- shell/platform/darwin/ios/framework/Source/FlutterMetalLayer.mm
Re-enabled now that the retain cycle is fixed.
> [iOS] enable FlutterMetalLayer.

- DEPS
To pick up https://github.com/flutter/buildroot/pull/879
> Roll buildroot to e92499322525306bd637eb79d1e6dd507d5f3062

- CONTRIBUTING.md
Link to engine setup was broken so here's the fix
> [wiki] Fix link to engine dev setup

- impeller/renderer/backend/vulkan/android/ahb_texture_source_vk.cc
- impeller/renderer/backend/vulkan/sampler_vk.cc
Fixes https://github.com/flutter/flutter/issues/152579
This now matches Skia OpenGL behavior with SurfaceTexture.
> [Impeller] Use linear sampling to sample from AHB textures in Vulkan.

- shell/platform/android/android_context_gl_impeller_unittests.cc
Previously this was using a zero EGLConfig handle in tests which use an AndroidContextGLImpeller that creates EGL surfaces.  This apparently worked with older emulators, but the API 35 system image requires a real EGLConfig.
See https://github.com/flutter/flutter/pull/152498
> Update flutter_shell_native_unittests for compatibility with Android API 35 emulators

- ci/licenses_golden/excluded_files
- flutter_frontend_server/pubspec.yaml
- impeller/tessellator/dart/pubspec.yaml
- pubspec.yaml
- shell/vmservice/BUILD.gn
- shell/vmservice/pubspec.yaml
Closes https://github.com/flutter/flutter/issues/147883.
> Migrate the remaining real pub packages to pub workspaces.

- analysis_options.yaml
- runtime/fixtures/dart_tool/flutter_build/dart_plugin_registrant.dart
- runtime/fixtures/runtime_test.dart
- shell/testing/observatory/launcher.dart
- shell/testing/observatory/service_client.dart
- shell/testing/observatory/test.dart
Towards https://github.com/flutter/flutter/issues/152636.
I also deleted some code that was TODO'd 10 years ago.
> Cleanup dart analyze diagnostics in ignored directories.

- shell/platform/embedder/fixtures/main.dart
Towards https://github.com/flutter/flutter/issues/152636.
Most of these were via `dart --fix`.
> Remove pre-existing diagnostics with no behavioral changes.

- ci/licenses_golden/excluded_files
- impeller/aiks/aiks_unittests.cc
- impeller/display_list/BUILD.gn
- impeller/display_list/aiks_dl_runtime_effect_unittests.cc
Part of https://github.com/flutter/flutter/issues/142054
> [Impeller] move more aiks tests to DL.

- lib/web_ui/lib/src/engine/canvaskit/embedded_views.dart
- lib/web_ui/lib/src/engine/canvaskit/path.dart
- lib/web_ui/lib/src/engine/layers.dart
- lib/web_ui/lib/src/engine/scene_builder.dart
- lib/web_ui/lib/src/engine/scene_painting.dart
- lib/web_ui/lib/src/engine/scene_view.dart
- lib/web_ui/lib/src/engine/skwasm/skwasm_impl/path.dart
- lib/web_ui/lib/src/engine/skwasm/skwasm_impl/raw/raw_path.dart
- lib/web_ui/lib/src/engine/skwasm/skwasm_impl/raw/raw_skstring.dart
- lib/web_ui/skwasm/path.cpp
- lib/web_ui/skwasm/string.cpp
- lib/web_ui/test/engine/scene_view_test.dart
- lib/web_ui/test/ui/platform_view_test.dart
This implements platform view clipping for the Skwasm renderer.
This fixes https://github.com/flutter/flutter/issues/133466
> [skwasm] Implement platform view clipping.

- DEPS
Contains:
* [macOS] Fix COPY step on macOS 15 Sequoia (flutter/buildroot#884)
* Bump actions/upload-artifact from 4.3.4 to 4.3.5 (flutter/buildroot#882)
* Bump github/codeql-action from 3.25.14 to 3.25.15 (flutter/buildroot#880)
* Bump ossf/scorecard-action from 2.3.3 to 2.4.0 (flutter/buildroot#881)
Issue: https://github.com/flutter/flutter/issues/152978 …
> Roll buildroot to 6ef931b950d5b9477dba0e278b7006ae327e12f7

- shell/gpu/gpu_surface_vulkan.cc
- shell/platform/embedder/embedder.cc
See https://skia.googlesource.com/skia/+/5fb01f00262bbbef99571953fb5a987b0bed4d45
> Directly include the Skia header that defines GrVkImageInfo

- shell/platform/android/io/flutter/plugin/platform/PlatformViewsController.java
- shell/platform/android/test/io/flutter/plugin/platform/PlatformViewsControllerTest.java
Testing
FYI @jason-simmons 
"Fixes" https://github.com/flutter/flutter/issues/152691
> [android] workaround for HC bug.

- shell/platform/fuchsia/flutter/vulkan_surface.cc
See https://skia.googlesource.com/skia/+/5fb01f00262bbbef99571953fb5a987b0bed4d45
> Fix include of GrVkImageInfo header for the Fuchsia build

- .ci.yaml
These are passing consistently.
> Move API level 34 scenario app tests back to prod

- shell/platform/embedder/embedder.cc
- shell/platform/windows/compositor_opengl.cc
- shell/platform/windows/compositor_opengl.h
Issue: https://github.com/flutter/flutter/issues/150546
Cherry pick issue: https://github.com/flutter/flutter/issues/153321
> [CP][Windows] Improve texture format logic

- build/config/fuchsia/gn_configs.gni
- tools/fuchsia/build_fuchsia_artifacts_test.py
> [fuchsia] Use Fuchsia API 22

- ci/licenses_golden/licenses_skia
- skia/BUILD.gn
These are no longer under the `src/ports` directory in Skia and are in `tools/`. But it appears that Flutter does not actually quire them. …
> Remove SkOSLibrary files from build and license scripts

- .ci.yaml
- ci/builders/linux_fuchsia.json
- ci/builders/linux_fuchsia_tests.json
Temporary workaround for https://github.com/flutter/flutter/issues/152186.
> [CP] Move Fuchsia tests to a separate config file (#54591)

- .ci.yaml
Follow up to https://github.com/flutter/engine/pull/54591
> Shift linux_fuchsia_tests from staging to prod

- DEPS
Trivial comment update to kick off CI. 
See: https://github.com/flutter/flutter/issues/153716
> Flutter 3.25 beta engine build

- lib/web_ui/dev/test_platform.dart
- lib/web_ui/lib/src/engine/html/bitmap_canvas.dart
- lib/web_ui/lib/src/engine/text_editing/text_capitalization.dart
See https://dart.googlesource.com/sdk.git/+/045d26bc74209f5acc6466669f89686344e83de2
> Remove unnecessary breaks in default clauses of switch statements

- .ci.yaml
Investigating https://github.com/flutter/flutter/issues/152186#issuecomment-2307201291
> Explicitly set the linux_fuchsia orchestrator to an 8 core machine.

- shell/platform/linux/fl_renderer.cc
- shell/platform/linux/fl_renderer.h
- shell/platform/linux/fl_renderer_test.cc
- shell/platform/linux/fl_view.cc
This means when rendering the correct layers are rendered for a view.
> Store a set of layers per view.

- impeller/entity/contents/filters/gaussian_blur_filter_contents.cc
Fixes https://github.com/flutter/flutter/issues/154046
Use three different command buffers when it would be   possible to combine the operations into a single buffer. From testing and user bug reports (see https://github.com/flutter/flutter/issues/154046 ), this sometimes causes deviceLost errors on older Adreno devices. Breaking  the work up into three different command buffers seems to prevent this crash.
I suspect this is due to some internal timeouts we may be hitting in the adreno driver.
> [Impeller] Use multiple command buffers for blur submission.

- common/config.gni
Corruption should be fixed by https://github.com/flutter/engine/pull/55036
> [Impeller] reland experimental canvas.

- testing/run_tests.py
Work towards https://github.com/flutter/flutter/issues/154268.
> Remove the last `--disable-dart-dev` in the engine.

- shell/gpu/gpu_surface_gl_impeller.cc
- shell/gpu/gpu_surface_metal_impeller.mm
- shell/gpu/gpu_surface_vulkan_impeller.cc
If we don't reset host buffer then leak
> [Impeller] Fix memory leak I introduced by fixing memory leak.

- impeller/entity/save_layer_utils.cc
Doubled comment, remove extra words!
> [Impeller] fix comment on savelayer utils.

- flutter_frontend_server/test/to_string_test.dart
- lib/ui/lerp.dart
- lib/ui/painting.dart
- lib/web_ui/lib/lerp.dart
- lib/web_ui/lib/painting.dart
- lib/web_ui/test/ui/color_test.dart
- lib/web_ui/test/ui/filters_test.dart
- lib/web_ui/test/ui/paint_test.dart
- lib/web_ui/test/ui/text_style_test.dart
- testing/dart/color_test.dart
- testing/dart/image_filter_test.dart
- testing/dart/text_test.dart
Reverts flutter/engine#54981
This is causing failures in customer tests that need to be updated: https://github.com/flutter/flutter/pull/155107/checks?check_run_id=30069840819
> Revert "Update Color to do all calculations with floating point components"

- shell/platform/android/test/README.md
- shell/platform/android/test/io/flutter/embedding/android/FlutterViewTest.java
- **add test back with no other changes**
- **Add legacy test and setup shadow**
2 and 3 of 5 flutter/flutter/issues/154746
Improved legacy testing by validating a fullscreen and non fullscreen codepaths. 
Added `.git-blame-ignore-revs` because git was failing to give blame values with that file missing. I dont think I added a global config anywhere but adding an empty file should not cause a problem.
> flutter view add test 2

- impeller/display_list/aiks_dl_blur_unittests.cc
- impeller/entity/contents/filters/gaussian_blur_filter_contents.cc
fixes https://github.com/flutter/flutter/issues/155075 …
> Fixed solid blur style math

- shell/platform/darwin/ios/framework/Source/FlutterPlatformViewsTest.mm
- shell/platform/darwin/ios/framework/Source/platform_views_controller.mm
A user reported hitting a null check error in this code. Add some null checks.
> [iOS] sprinkle some null checks on BringLayersIntoView.

- sky/packages/sky_engine/BUILD.gn
Fixes https://github.com/flutter/flutter/issues/151171
> Copy Dart SDK vm_shared sources into the sky_engine package

- impeller/core/host_buffer.cc
fixes https://github.com/flutter/flutter/issues/155555 …
> Added assert for host buffer allocation.

- lib/web_ui/lib/src/engine.dart
- lib/web_ui/lib/src/engine/canvaskit/embedded_views.dart
- lib/web_ui/lib/src/engine/canvaskit/layer.dart
- lib/web_ui/lib/src/engine/canvaskit/layer_tree.dart
- lib/web_ui/lib/src/engine/canvaskit/layer_visitor.dart
- lib/web_ui/lib/src/engine/canvaskit/overlay_scene_optimizer.dart
- lib/web_ui/lib/src/engine/canvaskit/rasterizer.dart
- lib/web_ui/test/canvaskit/embedded_views_test.dart
- lib/web_ui/test/ui/scene_builder_test.dart
This enhances the overlay optimization by delaying combining pictures to get tighter bounds for the pictures that make up the scene, enabling more sophisticated optimization since we can determine if they intersect with platform views on a per-picture basis.
Fixes https://github.com/flutter/flutter/issues/149863
On a Macbook in Chrome in an example app with an infinite scrolling grid of platform views, this brings the ratio of dropped frames from 93% to 55% (roughly 4 fps to 30 fps).
This is a reland of https://github.com/flutter/engine/pull/54878 with a fix for scenes with pictures that are eventually entirely clipped out. …
> Reland "[canvaskit] Further improve overlay optimization by splitting pictures"

- lib/ui/painting.dart
issue: https://github.com/flutter/flutter/issues/155803 …
> updated Color docstring to address equality

- ci/builders/local_engine.json
Make it explicit that it's an unopt engine for consistency with the other unopt build descriptions.
Fixup to: https://github.com/flutter/engine/pull/55493 …
> Improved description for ios_debug_sim_unopt_arm64

- fml/message_loop_task_queues.cc
This issue was found with memory sanitizer.
Commit f2f09b69691403d08fac3cb56e00bfc619a371af introduced a change that leads to use-after-free condition.
In function MessageLoopTaskQueues::GetNextTaskToRun:
1) Call is made to PeekNextTaskUnlocked(queue_id);. Returned value contains a reference to to an object of const DelayedTask& taken from an std::queue container as returned by primary_task_queue_.top().
2) Variable TaskSource::TopTask top now contains a reference to this object.
3) Function queue_entries_.at(top.task_queue_id)->task_source->PopTask(...) which in turn calls pop() method on std::queue.
4) Object of type DelayedTask on top of the queue gets deleted.
5) top.task.GetTaskSourceGrade() is called later with top.task refering to an already deleted object.
*Replace this paragraph …
> fix use_of_uninitialized_value in message_loop_task_queues.cc

- BUILD.gn
Fixes https://github.com/flutter/flutter/issues/156012
> [Impeller] Build standalone library on Android.

- shell/platform/darwin/ios/BUILD.gn
- shell/platform/darwin/ios/framework/Source/FlutterPlatformPlugin.mm
Migrates from manual reference counting to automatic reference counting. Migrates ivars to property syntax. Makes a minor update to a doc comment.
No semantic changes, therefore not changes to tests. …
> iOS: Migrate FlutterPlatformPlugin to ARC

- lib/ui/platform_dispatcher.dart
- lib/ui/window.dart
Added docs to `FrameCallback` and `FrameData`
> Added Dart docs

- impeller/geometry/matrix.h
- impeller/geometry/matrix_unittests.cc
Fixes https://github.com/flutter/flutter/issues/155450
> [Impeller] Fix handling of perspective matrices in Matrix::Translate

- docs/monorepo/engine_binary_hashing.md
aka "dude, where's my engine?"
> Record notes on hashing artifacts in a monorepo

- impeller/renderer/backend/gles/reactor_gles.cc
- impeller/renderer/backend/gles/reactor_gles.h
- impeller/renderer/backend/gles/texture_gles.cc
- impeller/renderer/backend/gles/texture_gles.h
- impeller/toolkit/interop/impeller.cc
- impeller/toolkit/interop/impeller.h
- impeller/toolkit/interop/impeller_unittests.cc
- impeller/toolkit/interop/texture.cc
- impeller/toolkit/interop/texture.h
Fixes https://github.com/flutter/flutter/issues/156013
> [Impeller] libImpeller: Allow wrapping external texture handles.

- impeller/toolkit/interop/impeller.cc
- impeller/toolkit/interop/impeller.h
- impeller/toolkit/interop/impeller_unittests.cc
- impeller/toolkit/interop/texture.cc
- impeller/toolkit/interop/texture.h
Fixes https://github.com/flutter/flutter/issues/156359
cc @lyceel
> [Impeller] libImpeller: Allow fetching OpenGL texture handle.

- BUILD.gn
- ci/builders/linux_android_debug_engine.json
- ci/builders/linux_host_engine.json
- ci/builders/mac_host_engine.json
- ci/builders/windows_host_engine.json
- impeller/toolkit/interop/BUILD.gn
Fixes https://github.com/flutter/flutter/issues/156358
> [Impeller] libImpeller: Publish SDK artifacts.

- DEPS
Pick up the change that repeats failed gn_run_binary.py execution
> Roll buildroot to pick up change to --time executions

- ci/builders/linux_arm_host_engine.json
- ci/builders/windows_arm_host_engine.json
Should have been a part of https://github.com/flutter/engine/commit/ff07e57c67051f3b3dbb6d9a694fcbdfed90082b but I missed these.
> [Impeller] libImpeller: Upload missing arm artifacts.

- impeller/entity/contents/contents.cc
- impeller/entity/contents/contents.h
- impeller/entity/contents/filters/filter_contents.cc
- impeller/entity/contents/filters/filter_contents.h
- impeller/entity/contents/filters/inputs/contents_filter_input.cc
- impeller/entity/contents/filters/inputs/contents_filter_input.h
- impeller/entity/contents/filters/inputs/filter_contents_filter_input.cc
- impeller/entity/contents/filters/inputs/filter_contents_filter_input.h
- impeller/entity/contents/filters/inputs/filter_input.cc
- impeller/entity/contents/filters/inputs/filter_input.h
- impeller/entity/contents/filters/inputs/filter_input_unittests.cc
- impeller/entity/contents/filters/inputs/placeholder_filter_input.cc
- impeller/entity/contents/filters/inputs/placeholder_filter_input.h
- impeller/entity/contents/filters/inputs/texture_filter_input.cc
- impeller/entity/contents/filters/inputs/texture_filter_input.h
- impeller/entity/contents/filters/matrix_filter_contents.cc
- impeller/entity/contents/filters/matrix_filter_contents.h
- impeller/entity/contents/filters/matrix_filter_contents_unittests.cc
All of these filter graph methods are not used or only used to test themselves in a limited unit test. Delete!
> [Impeller] delete a bunch of dead filter code.

- shell/platform/linux/fl_key_channel_responder.cc
- shell/platform/linux/fl_keyboard_handler.cc
- shell/platform/linux/fl_keyboard_handler_test.cc
- shell/platform/linux/fl_scrolling_manager_test.cc
- shell/platform/linux/fl_socket_accessible.cc
Remove empty dispose methods and convert finalize methods to dispose for consistency.
> Fix dispose methods that didn't chain the parent.

- impeller/playground/playground.cc
- impeller/renderer/backend/gles/blit_command_gles.cc
- impeller/renderer/backend/gles/blit_pass_gles.cc
- impeller/renderer/backend/gles/blit_pass_gles.h
- impeller/renderer/backend/metal/blit_pass_mtl.h
- impeller/renderer/backend/metal/blit_pass_mtl.mm
- impeller/renderer/backend/vulkan/blit_pass_vk.cc
- impeller/renderer/backend/vulkan/blit_pass_vk.h
- impeller/renderer/blit_command.h
- impeller/renderer/blit_pass.cc
- impeller/renderer/blit_pass.h
- impeller/renderer/blit_pass_unittests.cc
- impeller/renderer/testing/mocks.h
- impeller/typographer/backends/skia/typographer_context_skia.cc
Part of https://github.com/flutter/flutter/issues/156641
> [Impeller] Add miplevel to Buffer->Texture blit.

- DEPS
- pubspec.yaml
- web_sdk/pubspec.yaml
The SoT repository for `package:file` has changed from google/file.dart to dart-lang/tools; this PR updates the DEPS file and the hard-coded paths in the two pubspec.yaml files.
- https://github.com/dart-lang/tools/issues/674 …
> update the repo references for package:file

- analysis_options.yaml
- ci/licenses_golden/tool_signature
- tools/licenses/lib/patterns.dart
Follow-up from https://github.com/flutter/engine/pull/55927
> Add back unnecessary_parenthesis lint

- lib/gpu/render_pass.cc
- testing/dart/gpu_test.dart
Resolves https://github.com/flutter/flutter/issues/157324
Fix a silly off-by-one that I didn't catch because none of the tests are using `DeviceBuffer` directly. 🤦
> [Flutter GPU] Fix conditional when checking DeviceBuffer bounds.

- docs/monorepo/engine_binary_hashing.md
> Typo in engine_binary_hashing.md

- shell/platform/darwin/macos/BUILD.gn
Cherry-pick the beta branch privacy location fix https://github.com/flutter/engine/pull/55938 back to master so this doesn't regress in the next beta.
This is for https://github.com/flutter/flutter/issues/157016 on master.  Can be merged once the framework test https://github.com/flutter/flutter/pull/157318 merges. …
> Fix macos xcprivacy manifest copy location

- DEPS
- pubspec.yaml
- shell/platform/fuchsia/dart/BUILD.gn
- web_sdk/pubspec.yaml
Update the deps and pubspec files for the new SoT locations for:
- package:matcher (dart-lang/test)
- package:collection (dart-lang/core)
- package:boolean_selector (dart-lang/tools)
See also issue https://github.com/dart-lang/sdk/issues/56591.  …
> [deps] update deps and pubspecs for the new locations of package:matcher, package:collection, and package:boolean_selector

- impeller/display_list/dl_dispatcher.cc
- impeller/display_list/dl_dispatcher.h
fixes https://github.com/flutter/flutter/issues/157526 …
> renamed TextFrameDispatcher to FirstPassDispatcher

- impeller/renderer/backend/vulkan/driver_info_vk.cc
- impeller/renderer/backend/vulkan/driver_info_vk_unittests.cc
Fixes https://github.com/flutter/flutter/issues/155185
> [Impeller] disable Adreno 506.

- tools/pkg/engine_build_configs/lib/src/build_config_runner.dart
- tools/pkg/engine_build_configs/test/build_config_runner_test.dart
fixes https://github.com/flutter/flutter/issues/157735 …
> Made et compilation errors relative to the CWD

- .ci.yaml
See https://ci.chromium.org/ui/p/flutter/builders/luci.flutter.prod/Linux%20local_engine_builds.
> Add `timeout` to `local_engine`.

- impeller/renderer/backend/metal/surface_mtl.mm
- shell/gpu/BUILD.gn
- shell/gpu/gpu_surface_metal_impeller.h
- shell/gpu/gpu_surface_metal_impeller.mm
- shell/gpu/gpu_surface_metal_skia.h
- shell/gpu/gpu_surface_metal_skia.mm
- shell/gpu/gpu_surface_noop.mm
- shell/platform/darwin/graphics/FlutterDarwinContextMetalSkia.mm
Migrates Objective-C code in shell/gpu to ARC.
Migrate `sk_cfp::reset(__bridge_retained ptr)` to `sk_cfp::retain(__bridge ptr)`. `reset` `CFRelease`s the previously held pointer and sets the pointer to the new pointer. `retain` `CFRetain`s the new pointer prior to setting it.
No changes to tests since this makes no semantic changes. …
> iOS,macOS: migrate shell/gpu to ARC

- shell/platform/embedder/BUILD.gn
- shell/platform/embedder/embedder_surface_metal_impeller.mm
- shell/platform/embedder/embedder_surface_metal_skia.mm
Migrate Skia and Impeller surface translation units to ARC.
No changes to tests since no semantic changes. …
> Embedder: migrate Metal surfaces to ARC

- impeller/renderer/backend/gles/buffer_bindings_gles.cc
- impeller/renderer/backend/gles/buffer_bindings_gles.h
- impeller/renderer/backend/gles/capabilities_gles.cc
- impeller/renderer/backend/gles/capabilities_gles.h
- impeller/renderer/backend/gles/proc_table_gles.h
Fixes https://github.com/flutter/flutter/issues/143387
Will be tested in https://github.com/flutter/flutter/pull/157888
> [Impeller] make desktop GL render.

- tools/engine_tool/test/build_plan_test.dart
Closes https://github.com/flutter/flutter/issues/157870.
Looks a lot better - I even noticed a few places where I was doing unnecessary (copy/pasted) configuration.
> `1 file changed, 240 insertions(+), 768 deletions(-)`
> Further de-duplicate and refactor `build_plan_test`.

- DEPS
Remove unused repo deps; these are now brought in as part of dart-lang/tools. This is for dart-lang repos `browser_launcher`, `clock`, `bazel_worker`, `cli_util`, `csslib`, `html`, and `json_rpc_2`.
No pubspecs (pubspec.yaml, web_sdk/pubspec.yaml) needed to be updated as part of this change.
Issues:
- https://github.com/dart-lang/sdk/issues/56591 …
> [deps] removed unused deps (dart-lang browser_launcher, clock, bazel_worker, cli_util, csslib, html, json_rpc_2

- impeller/renderer/backend/vulkan/driver_info_vk.cc
- impeller/renderer/backend/vulkan/driver_info_vk_unittests.cc
Fixes https://github.com/flutter/flutter/issues/155185
> [CP][Impeller] disable Adreno 506. (#56210)

- shell/platform/darwin/macos/framework/Source/FlutterViewController.mm
Previously, if `layout_data` was not nil, we failed to `CFRelease` `source`. However, if `layout_data` was nil, we dif free source, then immediately set it to a new CoreFoundation object, which we then failed to free.
We now use `fml::CFRef` which just does the right thing.
Finally, we were returning `(__brdige_transfer)CFRetain(layout_data)` but `__bridge_transfer` releases the transferred object at the end of the enclosing expression, so this is equivalent to `(__bridge)layout_data`, which is what we now do.
No tests since this is a refactor with no semantic changes, other than fixing an internal leak. …
> macOS: fix leak in CurrentKeyboardLayout

- fml/platform/darwin/cf_utils_unittests.mm
Eliminates the use of statics in CFTest.SupportsCustomRetainRelease (introduced in https://github.com/flutter/engine/pull/56463), "clever" as it was. …
> fml: Improve CFTest.SupportsCustomRetainRelease test

- BUILD.gn
- testing/BUILD.gn
- testing/run_tests.py
Years ago, @chinmaygarde created TestMetalSurface and wrote a unit test for it in ed30d77ab9d16706829adc8214d1fe1949696d5d.
And some things that should not have been forgotten were lost. History became legend. Legend became myth. And for four and a half years, the test passed out of all knowledge. Until, when chance came, it ensnared a new bearer. The test came to the creature @cbracken, who took it deep into the tunnels of the GN build files. And there it consumed him. The test brought to @cbracken unnatural long life. For 500 hours, it poisoned his mind. And in the gloom of @cbracken's cave, it waited. Darkness crept back into the forests of the world. Rumour grew of a shadow in the East - whispers of a nameless fear. And the Test of Unit perceived its time had now come.
If you need …
> iOS,macOS: Build/test test_metal_surface_unittests

- shell/platform/darwin/common/framework/Source/FlutterNSBundleUtils.h
- shell/platform/darwin/common/framework/Source/FlutterNSBundleUtils.mm
- shell/platform/darwin/ios/framework/Source/FlutterPlatformPlugin.mm
A couple string constants had been incorrectly declared `const NSString*` rather than `NSString* const`. The former is a pointer to an immutable string, but (a) the pointer can be reassigned and (b) the default NSString implementation is immutable. The latter is an immutable pointer to a string, which is what we want, since we don't want developers reassinging our constants to other values.
Also updates an identifier name to pass lint rules.
No changes to tests since this is "tested" by the compiler.
[test-exempt]: …
> iOS,macOS: Fix string constant declarations

- shell/platform/linux/fl_text_input_handler.cc
Without this if a channel method call was in progress and then the handler was destroyed the call could attempt to access the destroyed handler. This is possible as the handler is recreated on engine restart.
However, in this case the result is not used so no invalid memory access would occur. Adding the cancellable fixes any future change where this would no longer be the case.
> Add missing cancellable to text input handler

- impeller/docs/benchmarks.md
The urls that use keys seem to atrophy quickly …
> Updated some impeller benchmark urls

- impeller/renderer/backend/gles/buffer_bindings_gles.cc
* removes usages of auto
* adds a std::vector::reserve
* renames improperly named local variable …
> Cleaned up BufferBindingsGLES::BindUniformBuffer

- third_party/tonic/filesystem/filesystem/file.cc
Internal bug: b/380745221
The use of `malloc` in L70:
https://github.com/flutter/engine/blob/ce1eb371eafa791d3d25e5a031bfc47885859c4d/third_party/tonic/filesystem/filesystem/file.cc#L70
Results in the following error, after an update to the internal toolchain. For some reason, this error only appears when targeting Linux.
```
tonic/filesystem/filesystem/file.cc:70:28: error: use of undeclared identifier 'malloc'
70 |   uint8_t* ptr = (uint8_t*)malloc(file_size);
|                            ^
1 error generated.
```
This PR fixes it by including the header file. …
> Add missing import for malloc

- shell/platform/darwin/graphics/FlutterDarwinContextMetalSkia.mm
fixes https://github.com/flutter/flutter/issues/159433
test exempt: no functional change, removes unused code …
> removed unused variable for skia initialization

- flow/paint_region.h
- fml/cpu_affinity.cc
- fml/cpu_affinity.h
- fml/synchronization/sync_switch.cc
- impeller/core/runtime_types.h
- impeller/geometry/path.h
- impeller/geometry/size.h
- impeller/typographer/rectangle_packer.cc
- impeller/typographer/rectangle_packer.h
- runtime/dart_service_isolate.h
- shell/platform/glfw/flutter_glfw.cc
- third_party/tonic/filesystem/filesystem/file.h
- vulkan/vulkan_surface.h
Fixes builds of engine with libstdc++13 and libstdc++14.
closes https://github.com/flutter/flutter/issues/159513 …
> IWYU: add some missing includes failing with libstdc++13/14

- lib/web_ui/lib/src/engine/canvaskit/embedded_views.dart
- lib/web_ui/test/canvaskit/embedded_views_test.dart
See https://github.com/flutter/flutter/issues/153678
> Dispose pictures created in HtmlViewEmbedder.submitFrame

- lib/ui/painting/rrect.cc
A flaw in https://github.com/flutter/engine/pull/57153 - SkRRect would normalize the rect (make it right-side up), a feature that Flutter code takes advantage of. We need to do that manually when we ingest a round rect from Flutter.
> Normalize round rect bounds when coming from Flutter

- docs/impeller/Flutter-GPU.md
> Flutter-GPU.md: Fix spelling

- shell/platform/android/surface_texture_external_texture.cc
This was removed at ToT but needs to also be cherry picked into 3.27
> [CP] Remove incorrect fml check.
