ci/licenses_golden/licenses_flutter, fml/BUILD.gn, fml/command_line.h, fml/platform/posix/command_line_posix.cc, fml/platform/win/command_line_win.cc, impeller/compiler/impellerc_main.cc
CP to 3.3 stable branch
Fixes https://github.com/flutter/flutter/issues/112497
=> CP: Convert the ImpellerC command line arguments to UTF-8 on Windows #36335

tools/fuchsia/build_fuchsia_artifacts.py
The `--skip-remove-buckets` parameter allows for scenarios where multiple runtimes need to exist in the default bucket directory. This wasn't possible with the previous workflow, which cleaned the bucket if the script was run.
This allows for both debug/JIT and profile/AOT to be built in the [flutter recipes](https://flutter.googlesource.com/recipes/+/refs/heads/main/recipes/engine/femu_test.py#76) without needing to build all runtimes (eg. passing in `all` to the `--runtime-mode` argument)
=> Add skip-remove-buckets parameter

shell/platform/darwin/macos/framework/Source/FlutterViewController.mm, shell/platform/darwin/macos/framework/Source/FlutterViewControllerTest.mm
macOS rotation values increase counterclockwise rather than the expected clockwise. So they have been inverted in polarity.
=> Fix reversed macOS trackpad rotation

tools/clang_tidy/lib/clang_tidy.dart, tools/clang_tidy/lib/src/git_repo.dart, tools/clang_tidy/lib/src/options.dart, tools/clang_tidy/test/clang_tidy_test.dart
This PR adds a flag to the clang-tidy wrapper script that causes it to lint the files that are changed in the HEAD commit. This will let us avoid linting every file on every commit on prod CI.
In particular, in presubmit, we'll be able to remove the `--lint-all` flag. In post-submit, we'll remove the `lint-all` flag, and use the `--lint-head` flag instead, and only when certain files are changed, like the `DEPS` file, we'll continue passing `--lint-all`.
Related: https://github.com/flutter/flutter/issues/105068
=> Adds a --lint-head flag to the clang-tidy script

shell/common/rasterizer_unittests.cc, shell/platform/android/android_egl_surface.cc
Partial revert of https://github.com/flutter/engine/pull/33881/files
From bisection, this feature is causing the jank observed in https://github.com/flutter/flutter/issues/112503
=> Revert egl presentation time

lib/web_ui/lib/src/engine/canvaskit/layer.dart, lib/web_ui/test/canvaskit/layer_test.dart
viewEmbedder is null when screenshotting. Fixed by not rendering the platform view when screenshotting. 
fixes https://github.com/flutter/flutter/issues/101720
=> dont throw on null view embedder

DEPS
Includes:
* Add json.hpp and tinygltf configuration (flutter/buildroot#627)
* Bump ossf/scorecard-action from 2.0.3 to 2.0.4 (flutter/buildroot#630)
* fix Visual Studio toolchain detection (flutter/buildroot#628)
Issue: https://github.com/flutter/flutter/issues/62597 …
=> Roll buildroot to 64d07cbd3d9fa0c15f06c8e24c3bdbf5a9a06329

third_party/accessibility/ax/platform/ax_platform_node_win_unittest.cc, third_party/accessibility/ax/platform/test_ax_node_wrapper.cc, third_party/accessibility/ax/platform/test_ax_node_wrapper.h
The accessibility tests use global state to override hit test results. This global state wasn't cleaned in between test runs, causing `IAccessibleHitTest` to have unexpected results whenever it ran after [`IAccessibleHitTestDoesNotLoopForever`](https://github.com/flutter/engine/blob/5fafbc1b3a4a57f029c7b2d74a1498302c0e1ccf/third_party/accessibility/ax/platform/ax_platform_node_win_unittest.cc#L492-L518).
Fixes: https://github.com/flutter/flutter/issues/98302 …
=> Fix the `AXPlatformNodeWinTest.IAccessibleHitTest` test

flow/layers/clip_shape_layer.h, flow/layers/color_filter_layer.cc, flow/layers/display_list_layer.cc, flow/layers/image_filter_layer.cc, flow/layers/layer_raster_cache_item.cc, flow/layers/opacity_layer.cc, flow/layers/opacity_layer_unittests.cc, flow/layers/shader_mask_layer.cc, flow/layers/shader_mask_layer_unittests.cc, flow/raster_cache.cc, flow/testing/mock_layer.cc
Don't snap during pre-roll. This doesn't fix all of the issues, but does make things more consistent
=> Dont snap in pre-roll (#36173)

.ci.yaml
This PR splits running clang-tidy into two shards each for Linux and macOS.
Related recipe change: https://flutter-review.googlesource.com/c/recipes/+/34420
Related issue: https://github.com/flutter/flutter/issues/105068
=> Shard clang-tidy builders

.ci.yaml
Move the new sharded clang-tidy builders to prod, and remove the old unsharded builders.
Related https://github.com/flutter/flutter/issues/105068
=> Remove bringup from new clang-tidy builds

impeller/renderer/allocator.cc, impeller/renderer/allocator.h, impeller/renderer/backend/gles/device_buffer_gles.cc, impeller/renderer/backend/gles/device_buffer_gles.h, impeller/renderer/backend/metal/allocator_mtl.h, impeller/renderer/backend/metal/allocator_mtl.mm, impeller/renderer/backend/metal/device_buffer_mtl.h, impeller/renderer/backend/metal/device_buffer_mtl.mm, impeller/renderer/backend/vulkan/device_buffer_vk.cc, impeller/renderer/backend/vulkan/device_buffer_vk.h, impeller/renderer/buffer_view.h, impeller/renderer/device_buffer.cc, impeller/renderer/device_buffer.h, impeller/renderer/host_buffer.cc, impeller/renderer/renderer_unittests.cc
This is pulled out from work related to compute and glyph atlases - this makes sense as its own PR and shouldn't get reverted if either of those patches have to get reverted.
Adds a way to view the buffer on `BufferView`. If a `DeviceBuffer` is `StorageMode::kHostVisible`, fills that with the appropriate pointer - otherwise it's nullptr. 
This is useful for reading back data from compute or for having a faster path to send CPU allocated data as a texture to the GPU in some cases (fewer copies).
=> [Impeller] Make kHostVisible DeviceBuffers actually be host visible.

impeller/fixtures/sample.comp, impeller/geometry/vector.h, impeller/renderer/compute_unittests.cc
This is built on top of changes from https://github.com/flutter/engine/pull/36466
Not ready for review, but updates the compute unit test to actually complete the computation and read its result(s). Fixes some bugs in there.
=> [Impeller] update compute unit test to actually read back the data, fix bugs in it

web_sdk/sdk_rewriter.dart, web_sdk/test/sdk_rewriter_test.dart
Remove a conditional that was put in place as a temporary workaround during the librarification of the web engine. Now that the engine is fully librarified, the conditional is no longer necessary.
=> [web] Remove unnecessary code from sdk_rewriter

shell/platform/darwin/macos/framework/Source/FlutterEngine.mm, shell/platform/darwin/macos/framework/Source/FlutterMetalRenderer.h, shell/platform/darwin/macos/framework/Source/FlutterMetalRenderer.mm, shell/platform/darwin/macos/framework/Source/FlutterMetalRendererTest.mm, shell/platform/darwin/macos/framework/Source/FlutterOpenGLRenderer.h, shell/platform/darwin/macos/framework/Source/FlutterOpenGLRenderer.mm, shell/platform/darwin/macos/framework/Source/FlutterOpenGLRendererTest.mm, shell/platform/darwin/macos/framework/Source/FlutterRenderer.h
This PR refactors `FlutterMetalRenderer` and `FlutterOpenGLRenderer` by extracting the presenting methods to the base class, `FlutterRenderer`.
Part of [the multiwindow project](https://github.com/flutter/flutter/issues/30701): This change removes redundant design and makes it easier to adapt renderers to multiple view controllers, paving the road to multi-window. …
=> [macOS] Unify FlutterRenderers' presenting callbacks

lib/web_ui/lib/src/engine/html/color_filter.dart, lib/web_ui/lib/src/engine/html/shader_mask.dart, lib/web_ui/test/engine/surface/surface_test.dart
Prevent attempt to remove an already removed resource element by nulling it out after removal.
Fixes https://github.com/flutter/flutter/issues/104305
Fixes a similar unreported issue with the shader mask layer.
=> [web] fix HTML ColorFilter and ShaderMask layer lifecycle

impeller/entity/contents/text_contents.cc, impeller/renderer/renderer_unittests.cc, impeller/renderer/vertex_buffer_builder.h
Attempt to reduce the amount of working being done during text drawing by lifting up per vertex calculations out of the inner loop. Additionally reduce the size of this buffer by using an index buffer.
https://github.com/flutter/flutter/issues/109949
=> [Impeller] lift calculations out of per vertex iteration, use index buffer

lib/ui/text.dart
This PR removes the reduntant call to `_getLineBoundary()` in `getLineBoundary()`.
test-exempt: removed redundant call.
=> Remove reduntant call to _getLineBoundary

lib/web_ui/lib/src/engine/canvaskit/color_filter.dart, lib/web_ui/lib/src/engine/canvaskit/image_filter.dart, lib/web_ui/test/canvaskit/color_filter_golden_test.dart, lib/web_ui/test/canvaskit/filter_test.dart
two issues fixed for canvaskit: 
1) ColorFilter.mode with a color opacity of zero would throw 
2) ImageFilter.blur with sigmaX and sigmaY of zero would throw 
fixed by returning the identity matrix in both cases. Mimics NOP behavior, where the filter does nothing. 
This is a temporary fix. Will create a better performing fix to handle the above listed edge cases so that we don't have to do the extra work of returning the identity matrix
see https://github.com/flutter/flutter/issues/89433
=> Fix filter null exceptions

DEPS, shell/platform/windows/window_proc_delegate_manager_unittests.cc, tools/dia_dll.py
Use Visual Studio 2019 to build the engine.
This is a requirement to roll ANGLE as it is affected by an STL bug if built using Visual Studio 2017: [angleproject#7693](https://bugs.chromium.org/p/angleproject/issues/detail?id=7693)
Depends on: https://github.com/flutter/buildroot/pull/632
Part of: https://github.com/flutter/flutter/issues/110948 …
=> [Windows] Move to Visual Studio 2019

shell/platform/darwin/ios/framework/Source/FlutterViewController.mm, shell/platform/darwin/ios/framework/Source/accessibility_bridge.mm, shell/platform/darwin/ios/framework/Source/accessibility_bridge_test.mm
Instead of loading the `viewController.view` in `~AccessibilityBridge`, which crashed if the view was not already loaded, use `viewIfLoaded`.
Fixes https://github.com/flutter/flutter/issues/112545 …
=> Guard accessibility_bridge UIView access

shell/platform/darwin/ios/BUILD.gn, shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm, shell/platform/darwin/ios/framework/Source/FlutterTextInputPluginTest.mm
This is what iOS 16 does when transforming 2 Korean characters into 1 (for example ㅇ ㅏ) right after a unicode composed character (emoji etc):
1. The keyboard deletes the emoji.
2. The keyboard API inserts the composed character back.
3. The keyboard API inserts the transformed Korean character. 
However, in iOS 16.0, there is a bug that in step 2, only the first unicode is inserted, which creates an incomplete or different composed character. 
To workaround this issue, this PR:
1. Cache the deleted composed character.
5. Detects when iOS only adds the first unicode of the composed character, then replaced the first unicode with the cached input.
The issue is caused by an iOS bug and this PR only provides a workaround, we should revert this workaround when the issue is fixed by iOS.
fixes …
=> Workaround iOS text input crash for emoji+Korean text

DEPS, shell/platform/windows/window_proc_delegate_manager_unittests.cc, tools/dia_dll.py
Reverts flutter/engine#36538
as it appears to have broken the tree: https://discord.com/channels/608014603317936148/613398423093116959/1026995839278792754
Failure:
1. https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20platform_channel_sample_test_windows/1804/overview
2. https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8801195816777587809/+/u/run_platform_channel_sample_test_windows/test_stdout
<details>
<summary>Logs...</summary>
```
[platform_channel_sample_test_windows] [STDOUT] stdout: [ +127 ms] executing: C:\b\s\w\ir\x\w\recipe_cleanup\tmpr1awka7t\flutter sdk\bin\cache\dart-sdk\bin\dart.exe C:\b\s\w\ir\x\w\recipe_cleanup\tmpr1awka7t\flutter sdk\examples\platform_channel\test_driver\button_tap_test.dart -rexpanded
[platform_channel_sample_test_windows] …
```
=> Revert "[Windows] Move to Visual Studio 2019"

impeller/entity/contents/solid_stroke_contents.cc, impeller/entity/contents/solid_stroke_contents.h, impeller/entity/shaders/solid_stroke.vert
This is another step towards making the stroke path algorithm compatible with the deferred geometry design. (See also https://flutter.dev/go/impeller-geometry#heading=h.fymtgh4bhdl2)
Took some funky screenshots along the way:
=> [impeller] Record final stroke vertex positions directly instead of using a separate normal attribute

benchmarking/benchmarking.cc, flow/flow_run_all_unittests.cc, fml/command_line.h, impeller/blobcat/blobcat_main.cc, impeller/compiler/impellerc_main.cc, shell/testing/tester_main.cc, testing/run_all_unittests.cc, third_party/txt/benchmarks/txt_run_all_benchmarks.cc, third_party/txt/tests/txt_run_all_unittests.cc
Should fix https://github.com/flutter/flutter/issues/112819
I have not tested this on a windows machine though. @sealesj would you be able to kick off a LED run with this patched in for one of your failing windows tests?
=> Avoid using non-UTF-8 encoded argv more often

impeller/entity/contents/solid_stroke_contents.cc
I noticed the geometry was extremely dense in a frame capture.
Videos of the new round cap smoothing behavior:
https://user-images.githubusercontent.com/919017/194152274-128b2bb8-a322-4b67-8269-29dc1890cd58.mov
https://user-images.githubusercontent.com/919017/194152289-3f276b08-64bc-4c38-b8fa-eacc8ff02f29.mov
=> [Impeller] Make stroke round cap/join smoothing way less aggressive

lib/ui/dart_ui.cc, lib/ui/painting.dart, lib/ui/painting/immutable_buffer.cc, lib/ui/painting/immutable_buffer.h, lib/ui/ui_dart_state.cc, lib/ui/ui_dart_state.h, lib/web_ui/lib/painting.dart, runtime/runtime_controller.cc, shell/common/engine.cc, testing/dart/assets_test.dart
Fixes https://github.com/flutter/flutter/issues/112958
Loads the file bytes in a background worker, allowing very large files to be loaded without causing visible UI jank. Works around issues where dart:io struggles to load bytes on certain platforms above a given size
=> Add ImmutableBuffer.fromFilePath

BUILD.gn, DEPS
Pick up https://github.com/flutter/buildroot/pull/636. Remove `use_xcode` usage.
https://github.com/flutter/flutter/issues/112992
=> Roll buildroot to use Fuchsia toolchain for iOS arm simulator

ci/licenses_golden/licenses_flutter, shell/platform/windows/BUILD.gn, shell/platform/windows/flutter_windows_engine.cc, shell/platform/windows/flutter_windows_engine.h, shell/platform/windows/flutter_windows_engine_unittests.cc, shell/platform/windows/system_utils.cc, shell/platform/windows/system_utils.h, shell/platform/windows/system_utils_unittests.cc, shell/platform/windows/windows_registry.cc, shell/platform/windows/windows_registry.h
The function currently used in `GetPreferredLanguages` on Windows does not necessarily return all the languages included in the list of preferred languages set in the user's settings. By attempting to get these values from the registry first, we can obtain all these languages in order. These are eventually parsed and used as the `PlatformConfiguration`'s locales.
[flutter/flutter#112717](https://github.com/flutter/flutter/issues/112717) …
=> Get user's preferred languages from registry

.ci.yaml
The release builder used to need to run the oldest version of Xcode that the tool supported, because of clang version constraints.  https://github.com/flutter/flutter/issues/107884 removed bitcode from the engine, so all builders should be able to use the latest version of Xcode
Fixes https://github.com/flutter/flutter/issues/112994
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#s …
=> Use Xcode 14 for all builders

ci/builders/mac_ios_engine_release.json, sky/tools/create_full_ios_framework.py, sky/tools/create_ios_framework.py
Eliminates the `--strip-bitcode` flag from the `create_ios_framework.py` and `create_full_ios_framework.py` scripts.
Issue: https://github.com/flutter/flutter/issues/107884 …
=> [iOS] Eliminate framework bitcode stripping flag

tools/gn
Removed from recipe scripts as of https://flutter-review.googlesource.com/c/recipes/+/34583
Cleanup to https://github.com/flutter/engine/pull/36596 …
=> Remove deprecated --bitcode flag

lib/ui/window/pointer_data.h
The code referenced by the comment lives here now (and no longer in `hooks.dart`): https://github.com/flutter/engine/blob/04bd25bcb0b6b267ea6f927f94465bc2fb699d5a/lib/ui/platform_dispatcher.dart#L374
That move happened in https://github.com/flutter/engine/pull/21932, but this reference wasn't updated.
=> Fix kPointerDataFieldCount reference

DEPS, ci/licenses_golden/licenses_third_party, testing/symbols/verify_exported.dart
Bitcode has been removed from the engine https://github.com/flutter/flutter/issues/107884
Revert https://github.com/flutter/engine/pull/35873.  Instead of using mirror at https://flutter.googlesource.com/third_party/libcxxabi/ with patch https://flutter.googlesource.com/third_party/libcxxabi/+/483f071ff4780a8884f32d97d2d262fbe9f1ae18, use llvm libcxxabi version.
See https://github.com/flutter/flutter/issues/110140 for more details.
~~Once this merges https://flutter.googlesource.com/third_party/libcxxabi/ can probably be deleted.~~ keep the fork around so older commits can be built.
[Tree …
=> Use llvm version of libcxxabi instead of patched mirror

DEPS
Includes:
* Bump github/codeql-action from 2.1.26 to 2.1.27 (flutter/buildroot#637)
* [Win] Enable control flow guard compiler option (flutter/buildroot#638)
Issue: https://github.com/flutter/flutter/issues/113119
[CLA]: …
=> Roll buildroot to c5de0c1ef5ff5f4fd8f6ce99674accb534643d75

lib/web_ui/pubspec.yaml
There is a vulnerability in package:http in versions older than 13.3. This updates to the latest. …
=> [web] Roll http dependency to 13.5

impeller/entity/contents/filters/blend_filter_contents.cc
Fix frame failure for advanced blends when there's no source snapshot available.
This is currently causing the ColorWheel playground to fail when the source alpha is set to 0 for the savelayer because invisible images have no coverage (which is from an optimization I landed a while back for Wondrous). The correct behavior is to just forward the destination color along.
=> [Impeller] Fix failure case for advanced blend when source snapshot has no coverage

impeller/entity/contents/content_context.cc
Before, modulate was just clearing out the pass due to the zero alpha factors. The color is `src * dst`, which is correct. This patch sets the alpha to also be `src * dst`.
Skia on left, Impeller on right:
=> [Impeller] Fix modulate blend mode

impeller/aiks/aiks_unittests.cc
Wipe out the backdrop using a savelayer with kSource and adjustable alpha. This reveals an alpha management problem for advanced blends that's been hiding just out of view.
The default color shouldn't be poking through unevenly here. Pipeline blends are behaving as expected with the backdrop alpha.
=> [Impeller] Add backdrop alpha to colorwheel playground

impeller/aiks/aiks_unittests.cc, impeller/entity/contents/filters/blend_filter_contents.cc, impeller/entity/entity_pass.cc, impeller/entity/shaders/blending/advanced_blend.glsl
Fixes https://github.com/flutter/flutter/issues/110672.
This fixes the major issue found in https://github.com/flutter/engine/pull/36656:
Jonah's test app (left is Skia, right is Impeller):
2 remaining issues:
* Modulate is definitely wrong.
* Linear sampling needs to be offset by half a texel (notice the light colored pixel line above the image).
=> [Impeller] Do SourceOver alpha compositing for advanced blends; write results to the pass with kSource

impeller/geometry/path.cc
Incrementally reserving vector capacity leads to quadradic behavior in polyline creation. I think that reserve only ensures that vector has the specified capacity, it doesn't trigger the normal doubling of the storage space. Each time a polyline component is converted and we request the vector to reserve . Because it won't have resized more than the prior component required, we force the existing vector to copy all of the previous components to allocate the backing memory. This is roughly N2 in the number of components.
By removing this reserve and letting the normal vector allocation strategy run, we get the expected linear-ish behavior.
With fix, this frame takes ~20ms to render. Without the fix, it takes ~180ms. Adding too many more rects and it won't finish.
Example app:
```dart
// …
```
=> [Impeller] fix quadradic behavior in polyline creation

lib/ui/platform_dispatcher.dart, lib/ui/window.dart, lib/web_ui/lib/platform_dispatcher.dart, lib/web_ui/lib/src/engine/platform_dispatcher.dart, lib/web_ui/lib/window.dart, shell/platform/embedder/fixtures/main.dart, testing/scenario_app/lib/src/locale_initialization.dart
In an effort to move from a single-rooted flutter view to multiple views in a flutter app, `dart::ui` should be able to dispatch semantics tree updates to selected views. This PR deprecates semantics APIs that assume one flutter view per app. 
This patch will be succeeded by framework changes that migrate from the deprecated APIs. After, the deprecated APIs will be removed in a subsequent PR.
This is a partial fix to https://github.com/flutter/flutter/issues/112221. that issue will be fully fixed when all 3 PRs are landed. …
=> Deprecate single semantics tree assumption from platform dispatcher

shell/platform/fuchsia/flutter/meta/common.shard.cml
* Add a `use` for the `root-ssl-certificates` to ensure BoringSSL can read the certificates at /config/ssl
* Reformat manifest with `cmc format`
Fixes `HandshakeException`s when establishing a secure connection:
```
HandshakeException: Handshake error in client (OS Error:
CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(handshake.cc:393))
<asynchronous suspension>
```
Depends on changes that offer this directory to the runners, e.g. https://fxrev.dev/737597
Bug: https://fxbug.dev/111712
=> [fuchsia] Use root-ssl-certificates in v2 runner manifests

lib/web_ui/lib/src/engine/dom.dart
This cl is to streamline number semantics in the dom shim.
For the time being `num`s are left in place.
=> [web] Remove explicit `int` types from `dom.dart`.

lib/ui/fixtures/ui_test.dart, lib/ui/window/platform_configuration.cc
* Return errors from the HandlePlatformMessage call in PlatformConfigurationNativeApi::SendPortPlatformMessage
* Clear the PlatformDispatcher onError handler installed by one of the tests. This handler can cause an infinite loop if a later test throws an exception.
* Wait for completion of async tests.
=> Fix multiple issues affecting HooksTest.HooksUnitTests

lib/ui/painting/picture.cc
Original comment:
> ... So we flatten the layer tree into a picture and use that as the thread transport mechanism.
However, looking at the whole code:
<details>
```c++
Dart_Handle Picture::RasterizeToImage(sk_sp<DisplayList> display_list,
std::shared_ptr<LayerTree> layer_tree,
uint32_t width,
uint32_t height,
Dart_Handle raw_image_callback) {
if (Dart_IsNull(raw_image_callback) || !Dart_IsClosure(raw_image_callback)) {
return tonic::ToDart("Image callback was invalid");
}
if (width == 0 || height == 0) {
return tonic::ToDart("Image dimensions for scene were invalid.");
}
auto* dart_state = UIDartState::Current();
auto image_callback = std::make_unique<tonic::DartPersistentValue>(
dart_state, raw_image_callback);
auto unref_queue = dart_state->GetSkiaUnrefQueue();
auto ui_task_runner = …
```
=> Update comments that seem to contradict the code and may confuse the reader

impeller/compiler/code_gen_template.h, impeller/compiler/reflector.cc, impeller/compiler/reflector.h, impeller/compiler/runtime_stage_data.cc, impeller/compiler/runtime_stage_data.h, impeller/fixtures/sample.comp, impeller/geometry/point.h, impeller/renderer/backend/gles/buffer_bindings_gles.cc, impeller/renderer/backend/metal/compute_pass_mtl.h, impeller/renderer/backend/metal/compute_pass_mtl.mm, impeller/renderer/compute_pass.cc, impeller/renderer/compute_pass.h, impeller/renderer/compute_unittests.cc, impeller/renderer/host_buffer.h, impeller/renderer/renderer_unittests.cc, impeller/renderer/shader_types.h, impeller/runtime_stage/runtime_types.h, lib/ui/fixtures/shaders/general_shaders/uniform_arrays.frag, lib/ui/painting/fragment_program.cc, testing/dart/fragment_shader_test.dart
This PR does a few things:
- Adds a UintPoint32 and a IPoint32 to handle uvec2/ivec2 members, and updates the reflector to know about these.
- Turns structs that have dynamically sized arrays (aka flexible arrays) into template classes that take a size parameter.
- This allows for stack allocation instead of forcing heap allocation.
- This allows for structs that have more than just the array member in GLSL.
- This requires updating `HostBuffer::EmplaceStorageBuffer`
- Turns the array_elements member of the struct definition into an optional so that callsites can decide what to do if there's no array elements instead of forcing them to always think there's at least 1.
- Updates the compute test/sample.comp to use these features.
- Updates a bug in the way we handled array sizes. …
=> [Impeller] Improvements for SSBO codegen

DEPS
Reverts flutter/engine#36739
This is causing the flutter tree to break. A longer term fix will need to be employed, but this is to return the tree to green for now while a longer term fix is implemented.
https://ci.chromium.org/p/flutter/builders/prod/Linux_android%20list_text_layout_impeller_perf__e2e_summary/1728
=> Revert "Roll Clang from 039b969b32b6 to f85c1f3b7c0b"

shell/platform/android/io/flutter/plugin/platform/PlatformViewsController.java, shell/platform/android/io/flutter/plugin/platform/SingleViewPresentation.java, shell/platform/android/test/io/flutter/plugin/platform/PlatformViewsControllerTest.java
Bypasses the step of wrapping the `Context` provided to the platform view factory when Hybrid Composition has been requested (i.e., when using `initExpensiveAndroidView`). This was added to the Hybrid Composition codepath in https://github.com/flutter/engine/pull/35233 when the creation flow was unified; it was intended to be a no-op for HC, but turns out not to have been, as described in https://github.com/flutter/flutter/issues/113449
This effectively reverts just the HC-specific part of https://github.com/flutter/engine/pull/35233 without affecting the other codepaths (so doesn't require reverting other changes built on that for TLHC mode).
Fixes b/249389618
See also https://github.com/flutter/flutter/issues/113449 …
=> Don't wrap Context for Android Hybrid Composition

ci/licenses_golden/licenses_flutter, display_list/BUILD.gn, display_list/display_list_color_source.cc, display_list/display_list_color_source.h, display_list/display_list_color_source_unittests.cc, display_list/display_list_runtime_effect.cc, display_list/display_list_runtime_effect.h, impeller/runtime_stage/runtime_stage.cc, impeller/runtime_stage/runtime_stage.h, lib/ui/painting.dart, lib/ui/painting/fragment_program.cc, lib/ui/painting/fragment_program.h
This change gets the `impeller::RuntimeStage` accessible from the Impeller dispatcher.
I'm gonna land the actual `ColorSourceContents` impl in a separate patch. There is some complexity to work through with sampler uniforms mapping to color sources. I plan to land an initial version with partial support for `DlImageColorSource` inputs only (ignoring the effect matrix). We'll also need to provide a standard way for users to handle stuff like the y flip in their shaders such that it doesn't disrupt the Skia shaders -- I have some ideas for abstracting some of this complexity away from users.
=> [Impeller] Add DlRuntimeEffect, pipe RuntimeStage through the DL

lib/ui/compositing/scene.cc, lib/ui/painting/display_list_deferred_image_gpu_impeller.cc, lib/ui/painting/display_list_deferred_image_gpu_impeller.h, lib/ui/painting/display_list_deferred_image_gpu_skia.cc, lib/ui/painting/display_list_deferred_image_gpu_skia.h, lib/ui/painting/image_encoding.cc, lib/ui/painting/picture.cc, lib/ui/ui_dart_state.cc, lib/ui/ui_dart_state.h, runtime/runtime_controller.cc, runtime/runtime_controller.h, shell/common/engine.cc, shell/common/engine.h, shell/common/engine_unittests.cc, shell/common/shell.cc, shell/common/shell.h
Fixes https://github.com/flutter/flutter/issues/113437
I hope someone who knows C++ better can explain this to me, I would not have expected this to cause problems (maybe it's related to unopt builds? it can only show up in an unopt build).
What's happening before this patch is that when threads get merged, the checks from `fml::WeakPtr` are getting used instead of `fml::TaskRunnerAffineWeakPtr`, which is what `SnapshotDelegate` is. I don't get why the upcast causes that.
@stuartmorgan fyi
=> Always use fml::TaskRunnerAffineWeakPtr for SnapshotDelegate

fml/string_conversion.cc, fml/string_conversion.h, impeller/playground/backend/vulkan/playground_impl_vk.cc, impeller/renderer/backend/vulkan/context_vk.cc
There are additional instance extensions that need to be enabled for this. Having any one of them is sufficient on each of these platforms. There were also some `VALIDATION_LOG`s that would fail in the process of picking a valid physical device, this would incorrectly exit early when there were multiple devices and a latter device is valid.
Also improves logging for playground when glfw fails to get a surface.
=> [Impeller] Add WSI support for Vulkan on Linux and Windows

impeller/renderer/backend/vulkan/context_vk.cc
Example:
```
Warning: Validation Performance Warning: [ UNASSIGNED-CoreValidation-Shader-OutputNotConsumed ] Object 0: handle = 0x980b0000000002e, type = VK_OBJECT_TYPE_SHADER_MODULE; | MessageID = 0x609a13b | vertex shader writes to output location 1.0 which is not consumed by fragment shader. Enable VK_KHR_maintenance4 device extension to allow relaxed interface matching between input and output vectors.
```
In cases like these where SPIRV-Cross optimizes away unused uniforms in fragment shaders, there isn't an easy way to detect and not drop these. Current constraints mean that `VK_KHR_maintenance4` can not be guaranteed to be available. So we log and continue.
=> [Impeller] Do not terminate on performance related validation failures

impeller/tools/build_metal_library.py
Fixes https://github.com/flutter/flutter/issues/113358
=> [Impeller] Specify the min simulator version.

shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm, shell/platform/darwin/ios/framework/Source/FlutterTextInputPluginTest.mm, testing/ios/IosUnitTests/IosUnitTests.xcodeproj/xcshareddata/xcschemes/IosUnitTests.xcscheme
Hot fixing: https://github.com/flutter/flutter/issues/111494
PR: https://github.com/flutter/engine/pull/36295 and #34508
CP issue: https://github.com/flutter/flutter/issues/112963
https://github.com/flutter/engine/pull/36621 plus cherry pick #34508 …
=> [CP] Workaround iOS text input crash for emoji+Korean text

impeller/base/validation.cc
This ensures that the scenario tests with Impeller enabled will fail when there are validation errors like the ones fixed by https://github.com/flutter/engine/pull/36809
=> [Impeller] Make validation errors fatal in non-release builds.

shell/platform/glfw/flutter_glfw.cc
See cl/480168500 for the original internal proposal.
> In C++20, u8string returns values utilizing the new type `char8_t` in place of char. Most uses of u8string here just end up calling c_str after. One other turns it back into a path, so why convert twice? And the last is for debug printing with <<, which is not defined for char8_t.
=> Stop using u8string which breaks in C++20

tools/fuchsia/devshell/build_and_copy_to_fuchsia.sh, tools/fuchsia/devshell/run_integration_test.sh, tools/fuchsia/devshell/run_unit_tests.sh, tools/fuchsia/gn-sdk/symbol_index.gni
The standalone symbol-index tool was deprecated and replaced with an ffx tool.
=> [fuchsia] Fix debug symbol registration.

lib/web_ui/lib/src/engine/canvaskit/canvaskit_api.dart, lib/web_ui/lib/src/engine/dom.dart, lib/web_ui/test/canvaskit/canvaskit_api_tt_on_test.dart
Adds a small JS-Interop layer to use the TrustedTypes API from the flutter/engine code, and use it to download the CanvasKit JS.
Adds a test that runs the canvaskit_api tests with TT enabled.
Fixes https://github.com/flutter/flutter/issues/112654
* Unit test included
* Deployed test app: https://dit-tests.web.app
[testing the …
=> [web] Use TrustedTypes to load canvaskit (where available)

lib/ui/painting/image_decoder_impeller.cc, lib/ui/painting/image_decoder_impeller.h, lib/ui/painting/multi_frame_codec.cc, lib/ui/painting/multi_frame_codec.h
As title, support multiframe on impeller. issue: https://github.com/flutter/flutter/issues/112214 …
=> [Impeller] Support multi-frame codecs

lib/web_ui/lib/src/engine/dom.dart, lib/web_ui/test/engine/pointer_binding_test.dart
This PR adds modifiers accessors (`altKey`, `ctrlKey`, `metaKey`, `shiftKey`) to `DomTouchEventExtension`, as defined in the current W3C specification: https://www.w3.org/TR/touch-events/#attributes-2
Those accessors are needed to implement https://github.com/flutter/engine/pull/36724.
See this review comment: https://github.com/flutter/engine/pull/36724#pullrequestreview-1141539192.
Fixes https://github.com/flutter/flutter/issues/113605
Update 3 tests
=> Add DOM TouchEvent modifiers accessors

shell/platform/fuchsia/flutter/flatland_platform_view.cc
This CL fixes the bug in pointer injector delegate where the viewRef is incorrectly cloned in the flatland platform view, causing an invalid viewRef to be passed in the Fidl request.
Test: flutter-embedder-test
=> [fuchsia][scenic] Fix invalid viewRef error in pointer injection.

shell/platform/darwin/ios/framework/Source/FlutterViewController.mm, shell/platform/darwin/ios/framework/Source/FlutterViewControllerTest.mm
On iOS 16:
```
BUG IN CLIENT OF UIKIT: Setting UIDevice.orientation is not supported. Please use UIWindowScene.requestGeometryUpdate(_:)
```
Fixes https://github.com/flutter/flutter/issues/111587 …
=> Use iOS 16 APIs to rotate orientation

shell/platform/android/io/flutter/view/AccessibilityBridge.java
08-16 06:23:59.641 23012 23012 E flutter : [ERROR:flutter/fml/platform/android/jni_util.cc(182)] java.lang.IllegalArgumentException: array == null
at android.opengl.Matrix.multiplyMM(Native Method)
at io.flutter.view.AccessibilityBridge$SemanticsNode.updateRecursively(Unknown Source:28)
at io.flutter.view.AccessibilityBridge$SemanticsNode.updateRecursively(Unknown Source:240)
at io.flutter.view.AccessibilityBridge$SemanticsNode.updateRecursively(Unknown Source:240)
at io.flutter.view.AccessibilityBridge$SemanticsNode.updateRecursively(Unknown Source:240)
at io.flutter.view.AccessibilityBridge$SemanticsNode.updateRecursively(Unknown Source:240)
at io.flutter.view.AccessibilityBridge$SemanticsNode.access$4900(Unknown Source:0)
at io.flutter.view.AccessibilityBridge.updateSemantics(Unknown …
=> Fix array == null error in AccessibilityBridge

shell/platform/darwin/macos/framework/Source/FlutterView.mm
Fixes https://github.com/flutter/flutter/issues/111425 …
=> [macOS] Fix mouse cursor being replaced by AppKit

lib/ui/window/pointer_data_packet_converter_unittests.cc
Well, just 1-char typo that I come across... …
=> Fix 1-char typo

shell/platform/windows/fixtures/main.dart, shell/platform/windows/flutter_windows_engine_unittests.cc
Adds an integration test for windows platform channels.  This is preliminary groundwork to implementing background platform channels for windows.
issue: https://github.com/flutter/flutter/issues/91635 …
=> Added integration test for platform channels on windows.

fml/platform/win/paths_win.cc
The directory path of the flutter_tester executable is used to locate the ICU data file when launching tests on Windows.  Opening the ICU file was failing if Flutter is installed in a directory path containing non-ASCII characters.
=> Convert the executable directory path to UTF-8 on Windows

impeller/aiks/canvas.cc
This does crash the existing tests but I didn't run them when landing the original PR 😢
=> [Impeller] fix null geometry

impeller/entity/shaders/position.vert, impeller/entity/shaders/position_color.vert, impeller/renderer/backend/vulkan/pipeline_library_vk.cc
This eliminates the `v_position` output for `position.vert` and `position_color.vert`.
=> [Impeller] Eliminate unused shader output

shell/platform/android/test/README.md, shell/platform/android/test/io/flutter/plugin/platform/PlatformViewsControllerTest.java, shell/platform/android/test_runner/build.gradle, shell/platform/android/test_runner/src/main/resources/robolectric.properties
Re-landing https://github.com/flutter/engine/pull/33024 …
=> Re-landing Robolectric 4.8.1

shell/platform/darwin/macos/framework/Headers/FlutterDartProject.h
This is causing issue when `-Wobjc-property-no-attribute` is turned on.
Since LLVM 3.1, `strong` has been the default value so this change is effectively a no-op, but improves readability.
Context: b/254864882
[CLA]: …
=> Add strong qualifier to dartEntrypointArguments.

shell/platform/common/client_wrapper/event_channel_unittests.cc, shell/platform/common/client_wrapper/include/flutter/event_channel.h
Updating the engine to Visual Studio 2019 was reverted as it [broke the framework tree](https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20platform_channel_sample_test_windows/1804/overview). The root cause is that the `EventChannel`'s handler [stores](https://github.com/flutter/engine/blob/7d18d7007affdb9e6063076f4616bbaa124ad6b5/shell/platform/common/client_wrapper/include/flutter/event_channel.h#L168) and [mutates](https://github.com/flutter/engine/blob/7d18d7007affdb9e6063076f4616bbaa124ad6b5/shell/platform/common/client_wrapper/include/flutter/event_channel.h#L92) data on the `EventChannel` itself. This is problematic as the `EventChannel`'s and the handler's lifetimes are decoupled (the `EventChannel` does not own its handler). If the `EventChannel` is destroyed, the …
=> Prevent stack corruption when using C++ `EventChannel`

lib/web_ui/lib/src/engine/canvaskit/surface.dart, lib/web_ui/test/canvaskit/embedded_views_test.dart
When we delete a Surface context (for example because it has resized) we must make sure that it is the current context or Skia might throw an exception while deleting resources associated with that context.
Fixes https://github.com/flutter/flutter/issues/91881 …
=> [canvaskit] Make the context current before disposing it

tools/gn
This removes the embedded font in CanvasKit. Since we always provide Roboto font, this is not required.
With this change, we remove 69.9 kb from the gzipped canvaskit.wasm (from 2296455 bytes to 2224892 bytes).
Fixes https://github.com/flutter/flutter/issues/112397 …
=> [canvaskit] Don't bundle an embedded font

impeller/aiks/canvas.cc, impeller/aiks/paint.cc, impeller/aiks/paint.h, impeller/entity/entity_unittests.cc, impeller/entity/geometry.cc, impeller/entity/geometry.h
Avoid polyline generation and tessellation when we are given a rect via canvas.drawRect. This improves the raster time of a frame made of thousands of rects to about 1/3 of the original time.
Before
After
Demo code
```dart
// Copyright 2014 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
void main() {
runApp(
const MaterialApp(
home: Scaffold(
body: Center(
child: Benchmark(),
)
),
)
);
}
class Benchmark extends StatefulWidget {
const Benchmark({super.key});
@override
State<Benchmark> createState() => _BenchmarkState();
}
class _BenchmarkState extends State<Benchmark> {
bool showQR = false;
@override
if (!showQR) { …
```
=> [Impeller] specialize the geometry for drawRect

.clang-tidy, ci/lint.sh, impeller/renderer/render_target.cc, impeller/renderer/render_target.h, impeller/typographer/backends/skia/text_render_context_skia.cc, impeller/typographer/typographer_unittests.cc, lib/ui/compositing/scene.cc, lib/ui/painting/image_encoding.cc, lib/ui/painting/immutable_buffer.cc, lib/ui/painting/multi_frame_codec.cc, lib/ui/ui_dart_state.cc, shell/platform/embedder/tests/embedder_test_compositor.cc, shell/platform/embedder/tests/embedder_test_compositor.h, shell/platform/embedder/tests/embedder_test_compositor_gl.cc, shell/platform/embedder/tests/embedder_test_compositor_metal.cc, shell/platform/embedder/tests/embedder_test_compositor_vulkan.cc, shell/platform/embedder/tests/embedder_test_context.cc, shell/platform/embedder/tests/embedder_test_context.h, shell/platform/embedder/tests/embedder_test_context_gl.cc, shell/platform/embedder/tests/embedder_test_context_software.cc, shell/platform/embedder/tests/embedder_test_context_software.h, shell/platform/embedder/tests/embedder_unittests.cc, shell/platform/embedder/tests/embedder_unittests_metal.mm, shell/platform/embedder/tests/embedder_unittests_util.cc, shell/platform/embedder/tests/embedder_unittests_util.h, tools/clang_tidy/lib/clang_tidy.dart, tools/clang_tidy/lib/src/command.dart, tools/clang_tidy/lib/src/options.dart, tools/clang_tidy/test/clang_tidy_test.dart
Fixed up some new violations to the "move const values" lint and the "unnecessary value" lint and made it an error on CI for host_debug on mac.
**If this fails in Post submit checks let me know, it's possible a violation was introduced between authoring and landing the check** …
=> Turned "unnecessary value" and "move of const" lints to errors on mac

impeller/entity/contents/vertices_contents.cc, impeller/entity/contents/vertices_contents.h, impeller/entity/geometry.cc, impeller/entity/geometry.h
As @dnfield notes in https://github.com/flutter/engine/pull/36914/files/02e0643cad37becd84e03f21e9ca6f431de6f1ed#r1002228848 , we're picking up a lot of TODOs from me in this file. most of these methods aren't really useful, except for the special case of vertices geometry. While we might find a use for them in the future, for now lets move them to the subclass?
=> [Impeller] move Geometry methods only used in VerticesContents to VerticesGeometry

shell/platform/android/test/io/flutter/embedding/android/FlutterFragmentActivityTest.java, shell/platform/android/test/io/flutter/embedding/engine/FlutterJNITest.java, shell/platform/android/test/io/flutter/plugin/platform/PlatformViewsControllerTest.java
Remove duplicated _ from Android's test methods' name. It's a minor cleanup PR.
=> Remove duplicated _ from Android's test methods' name

build/dart/BUILD.gn
Keep the fuchsia build from trying to build the dart sdk when it imports `//flutter/build/dart/BUILD.gn`.
This fixes the broken hhh builds: https://ci.chromium.org/p/dart/g/flutter-hhh-web/console
=> Keep the fuchsia build from trying to build the dart sdk

shell/platform/android/android_image_generator.cc
The type |long| is equal to int32_t in 32bit app, but int64_t in 64bit app. 
The type |jlong| is always equal to int64_t.
CallStaticObjectMethod uses "J" to request a jlong type which needs 8 byte data but given |long| value which provides 4 byte data in 32bit mode will trigger java value error and at last a wrong pointer to AndroidImageGenerator object.
=> [android] Fix crash if decode .heic image in 32bit mode android app.

shell/platform/fuchsia/flutter/tests/integration/embedder/parent-view/pubspec.yaml, shell/platform/fuchsia/flutter/tests/integration/text-input/text-input-view/lib/text_input_view.dart, shell/platform/fuchsia/flutter/tests/integration/text-input/text-input-view/pubspec.yaml, shell/platform/fuchsia/flutter/tests/integration/touch-input/touch-input-view/lib/touch-input-view.dart, shell/platform/fuchsia/flutter/tests/integration/touch-input/touch-input-view/pubspec.yaml
Resolves errors seen in issue [113943](https://github.com/flutter/flutter/issues/113943)
=> Update pubspec.yaml for parent-view and touch-input-view

lib/web_ui/lib/src/engine/canvaskit/font_fallbacks.dart, lib/web_ui/lib/src/engine/canvaskit/fonts.dart, lib/web_ui/lib/src/engine/fonts.dart, lib/web_ui/lib/src/engine/initialization.dart, lib/web_ui/lib/src/engine/text/font_collection.dart, lib/web_ui/test/canvaskit/canvaskit_api_test.dart, lib/web_ui/test/canvaskit/skia_font_collection_test.dart, lib/web_ui/test/engine/image_to_byte_data_test.dart, lib/web_ui/test/html/canvas_clip_path_golden_test.dart, lib/web_ui/test/html/canvas_context_golden_test.dart, lib/web_ui/test/html/canvas_reuse_golden_test.dart, lib/web_ui/test/html/compositing/backdrop_filter_golden_test.dart, lib/web_ui/test/html/compositing/canvas_blend_golden_test.dart, lib/web_ui/test/html/compositing/canvas_image_blend_mode_golden_test.dart, lib/web_ui/test/html/compositing/canvas_mask_filter_golden_test.dart, lib/web_ui/test/html/compositing/color_filter_golden_test.dart, lib/web_ui/test/html/compositing/compositing_golden_test.dart, lib/web_ui/test/html/compositing/dom_mask_filter_golden_test.dart, lib/web_ui/test/html/drawing/canvas_draw_color_golden_test.dart, lib/web_ui/test/html/drawing/canvas_draw_picture_golden_test.dart, lib/web_ui/test/html/drawing/draw_vertices_golden_test.dart, lib/web_ui/test/html/path_metrics_golden_test.dart, lib/web_ui/test/html/path_transform_golden_test.dart, lib/web_ui/test/html/screenshot.dart, lib/web_ui/test/html/shaders/image_shader_golden_test.dart, lib/web_ui/test/html/shaders/linear_gradient_golden_test.dart, lib/web_ui/test/html/shaders/radial_gradient_golden_test.dart, lib/web_ui/test/html/shaders/shader_mask_golden_test.dart, lib/web_ui/test/text/font_collection_test.dart
refactored `FontCollection` for both canvaskit and html. 
With the refactor, it becomes possible to download fonts concurrently with wasm, resolving issue: https://github.com/flutter/flutter/issues/105929
Each font needs to be 1) downloaded and 2) registered before it can be used. 
Previously, this process was done in one function call: `registerFonts()`
Now, downloading fonts happens in two separate function calls:
1) `downloadAsetFonts(AssetManager assetmanager)` to download fonts
2) `registerDownloadedFonts()` to register fonts 
Breaking the previous `registerFonts()` into the two aforementioned steps allows the following functions to be called concurrently:
1) download fonts with `downloadAsetFonts(AssetManager assetmanager)`
2) download wasm with `canvaskit = await …
=> download fonts concurrently with wasm

shell/platform/fuchsia/dart/BUILD.gn
The latest version of args is using Dart 2.18 language features.
See https://github.com/flutter/flutter/issues/113943
=> Update the language version used by Fuchsia's wrapper for the Dart args package

display_list/display_list_color_source.cc, display_list/display_list_color_source.h, display_list/display_list_color_source_unittests.cc, impeller/display_list/display_list_dispatcher.cc, impeller/entity/contents/runtime_effect_contents.cc, impeller/entity/contents/runtime_effect_contents.h, impeller/entity/entity_unittests.cc, lib/ui/painting/fragment_program.cc, lib/ui/painting/fragment_program.h, lib/ui/painting/fragment_shader.cc
`ReusableFragmentShader` has a lifetime that lasts longer than a frame, and the uniforms can be continually changed on the UI thread. So take a copy (intention immutable) of the uniforms before handing it to the DL for consumption on the render thread.
* Closes https://github.com/flutter/flutter/issues/113714 because the copy in the dispatcher has been removed.
* Fixes this iOS stuttering issue: https://github.com/flutter/engine/pull/36866#issuecomment-1284692335
* Fixes crash when setting a sampler in this example: https://github.com/zanderso/fragment_shader_example/compare/main...bdero:fragment_shader_example:bdero/sampler
=> [Impeller] Copy uniforms before appending them to the DisplayList

shell/platform/fuchsia/flutter/flatland_external_view_embedder.cc, shell/platform/fuchsia/flutter/flatland_external_view_embedder.h
This CL adds support for "intercept_all_input" flag in flutter_runner_config for flatland.
Test: This code path will be tested once the flatland config is enabled for flutter embedder tests. This patch is a prereq for the test to roll.
[CLA]: …
=> [fuchsia][scenic] Add input shield flag support in Flatland.

shell/platform/windows/fixtures/main.dart, shell/platform/windows/flutter_windows_engine_unittests.cc
alternative to https://github.com/flutter/engine/pull/37010
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking- …
=> Fixed race in incorrect windows platform channel test.

lib/ui/painting/image_generator.h, lib/ui/painting/image_generator_registry_unittests.cc, lib/ui/painting/multi_frame_codec.cc, shell/common/shell_unittests.cc, shell/platform/android/android_image_generator.cc
The Skia team is cleaning up the #includes inside our public headers. These changes keep Flutter Engine from depending on transitive dependencies that are being removed.
- [ x ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on
- [ x ] I updated/added relevant documentation (doc comments with `///`).
If you need help, consider asking for advice on …
=> Add necessary #includes for SkCodecAnimation.h

shell/platform/windows/direct_manipulation.cc, shell/platform/windows/direct_manipulation.h, shell/platform/windows/direct_manipulation_unittests.cc, shell/platform/windows/flutter_windows_view.cc, shell/platform/windows/flutter_windows_view.h, shell/platform/windows/testing/mock_window_binding_handler_delegate.h, shell/platform/windows/window_binding_handler_delegate.h
Generate PointerScrollInertiaCancel event on Win32 when DirectManipulation inertia is prematurely ended. This should correspond to a trackpad touch. 
Part of https://github.com/flutter/flutter/issues/106979
=> Scroll inertia cancel for Win32

shell/common/animator.cc
- Removes the `VsyncSchedulingOverhead` event, since that event didn't always make sense - it records long scary bars in frames where the schedule frame did not originate from the framework, and it's not clear to me how this is useful to our users - see https://github.com/flutter/engine/pull/20229
- Only emit `Frame Request pending` if we're going to call `BeginFrame`.
- Emit an event when we re-use the last layer tree.
Fixes https://github.com/flutter/flutter/issues/113957
=> Cleanup animator tracing

shell/platform/android/io/flutter/view/AccessibilityBridge.java, shell/platform/android/test/io/flutter/view/AccessibilityBridgeTest.java
Fixes https://github.com/flutter/flutter/issues/113457 …
=> Fixes Android text field to use hint text for accessibility

impeller/entity/entity_unittests.cc, impeller/playground/playground.cc, impeller/playground/playground.h, impeller/playground/playground_test.cc, impeller/playground/playground_test.h, impeller/runtime_stage/runtime_stage_playground.cc, impeller/runtime_stage/runtime_stage_playground.h, impeller/runtime_stage/runtime_stage_unittests.cc
I accidentally landed a second routine that does the same thing!
=> [Impeller] Move RuntimeStage fixture loading to PlaygroundTest

impeller/aiks/aiks_unittests.cc, impeller/display_list/display_list_unittests.cc, impeller/entity/entity_unittests.cc, impeller/playground/playground.cc, impeller/renderer/renderer_unittests.cc
Sets a default window position for all playgrounds. Gets rid of a silly hack to size an ImGui window that I did many moons ago and ended up getting copied dozens of times.
ImGui does a pretty good job with the autoresizing calculation, so somewhere along the line I started to have the windows size themselves.
=> [Impeller] Autoresize playground imgui windows

impeller/geometry/geometry_unittests.cc, impeller/geometry/vector.h
And cover existing ones with tests. Noticed these were missing while debugging some playground issues.
=> [Impeller] Add stream ops to Vector3 and Vector4

ci/licenses_golden/licenses_flutter, impeller/compiler/shader_lib/impeller/constants.glsl, impeller/compiler/shader_lib/impeller/gaussian.glsl, impeller/entity/shaders/border_mask_blur.frag, impeller/entity/shaders/gaussian_blur.frag
Remove the uniform refs from the gaussian functions and toss them into the shader lib.
In prep for rrect approximation improvements. Here's a sneak peak (the circles on the right are falling back to the regular gaussian blur for some reason, which currently looks sloppy with a high kernel size):
=> [Impeller] Move gaussian functions into the shader library

shell/platform/android/test/io/flutter/embedding/engine/mutatorsstack/FlutterMutatorViewTest.java
This test is flaking on every run. Reverting to an older robolectric did not solve the issue.
Related https://github.com/flutter/flutter/issues/114036
=> Removes FlutterMutatorViewTest.sendAccessibilityEvents

lib/ui/semantics.dart
As part of [flutter/flutter #107866](https://github.com/flutter/flutter/issues/107866), more functionality for testing semantics was added. Part of this was `simulatedAccessibilityTraversal`, which is dependent on knowing what flags are important for accessibility. The comments noting what need to be updated when SemanticsFlags are changed now include the relevant field to update for tests to remain accurate as well.
Relates to [flutter/flutter #107866](https://github.com/flutter/flutter/issues/107866)
=> Adds direction to SemanticsFlag that ensures `flutter_test` is up to date with the latest flags

impeller/display_list/display_list_dispatcher.cc, impeller/entity/contents/runtime_effect_contents.cc, impeller/entity/contents/runtime_effect_contents.h
This gets image samplers working by simply pulling the image and sampling info directly out of the color source, but we can add a path that supports properly rendering color source inputs quite easily later depending on what we end up deciding to do with the API.
=> [Impeller] Implement support for RuntimeEffect samplers

.ci.yaml
The quota problem has been fixed as well as the issues identified with the first builder moved to prod. …
=> Move 2 mac ios engine v2 builders to prod.

shell/platform/darwin/macos/framework/Source/FlutterMenuPluginTest.mm
Re-enables the TestSetMenu test.
The workaround in https://github.com/flutter/flutter/issues/104748#issuecomment-1159336728 is applied in this PR.
Fixes https://github.com/flutter/flutter/issues/104748 …
=> Macos re-enable TestSetMenu

shell/platform/android/io/flutter/view/AccessibilityBridge.java, shell/platform/android/test/io/flutter/view/AccessibilityBridgeTest.java
Reverts flutter/engine#36846
Tree red on: https://github.com/flutter/flutter/issues/114161#issuecomment-1293838714
=> Revert "Fixes Android text field to use hint text for accessibility"

impeller/compiler/shader_lib/impeller/gaussian.glsl, impeller/entity/contents/rrect_shadow_contents.cc, impeller/entity/shaders/rrect_blur.frag
This switches the rounded rect blur approximation from using only a distance field to a hybrid sampling approach.
1. The X direction blur is computed by taking the X-only distance field and mapping it through the analytical Gaussian integral (which uses an erf approximation).
2. Step 1 is sampled with 5 evenly spaced samples over a 3*sigma kernel size in the Y direction.
This makes the rounded rect shadows nearly indistinguishable from the fully numerical Gaussian blur in most cases, while keeping the per-fragment overhead constant.
This was largely inspired by the ideas in this article: https://madebyevan.com/shaders/fast-rounded-rectangle-shadows/
Future work:
* Remove the slight discontinuity around the edges by adjusting either the radius per sigma ratio or the Gaussian integral.
* …
=> [Impeller] Improved rounded rect shadow approximation

.github/PULL_REQUEST_TEMPLATE.md
Just one char fix :)
Before this fix, it looks like the following on github, with a bug newline: …
=> Fix incorrect newline in pull request template

lib/web_ui/dev/steps/compile_tests_step.dart, lib/web_ui/dev/steps/run_tests_step.dart, lib/web_ui/dev/test_platform.dart, lib/web_ui/dev/utils.dart, lib/web_ui/lib/src/engine/canvaskit/painting.dart, lib/web_ui/test/ui/color_test.dart, lib/web_ui/test/ui/utils.dart
This change creates the 'ui' test subdirectory, which is for tests using pure `dart:ui` API which we want to test with all renderers. …
=> [web] Allow tests to run with multiple renderers

shell/platform/darwin/BUILD.gn, shell/platform/darwin/common/BUILD.gn, shell/platform/darwin/common/framework/Headers/FlutterChannels.h, shell/platform/darwin/common/framework/Headers/FlutterCodecs.h, shell/platform/darwin/common/framework/Source/FlutterChannels.mm, shell/platform/darwin/common/framework/Source/FlutterCodecs.mm, shell/platform/darwin/common/framework/Source/FlutterStandardCodec.mm, shell/platform/darwin/ios/framework/Source/FlutterRestorationPluginTest.mm
The "framework_shared" target was built with arc, there is no blocker to move it to arc besides some standard mrc to arc code changes.
Code changes includes:
1. Make retain properties to be either "Strong" or "Copy" (I made properties to be copy when I think they should have been copy)
2. Make non-retain properties "Assign"
3. Remove all dealloc method, remove all retains call, remove all autorelease call
4. Make strong instance variables weak before being accessed in the block
This helps the iOS embedder migration work, after this lands, we can now freely move shared code from macOS to "framework_shared"
part of https://github.com/flutter/flutter/issues/112232 …
=> Migrate darwin common "framework_shared" target to ARC

impeller/compiler/reflector.cc, impeller/fixtures/sample.comp, impeller/playground/BUILD.gn, impeller/playground/compute_playground_test.cc, impeller/playground/compute_playground_test.h, impeller/playground/playground.cc, impeller/playground/playground.h, impeller/renderer/compute_unittests.cc
Updates the compute test to add a struct
Updates compiler reflector to support structs in buffers
Updates compute playground tests to not setup a renderer/attempt to setup a renderer.
=> [Impeller] Support user defined structs in buffers, clean up compute tests

ci/licenses_golden/licenses_flutter, shell/platform/windows/BUILD.gn, shell/platform/windows/accessibility_alert.cc, shell/platform/windows/accessibility_alert.h, shell/platform/windows/accessibility_root_node.cc, shell/platform/windows/accessibility_root_node.h, shell/platform/windows/fixtures/main.dart, shell/platform/windows/flutter_window.cc, shell/platform/windows/flutter_window.h, shell/platform/windows/flutter_window_unittests.cc, shell/platform/windows/flutter_windows_engine.cc, shell/platform/windows/flutter_windows_engine.h, shell/platform/windows/flutter_windows_engine_unittests.cc, shell/platform/windows/flutter_windows_view.cc, shell/platform/windows/flutter_windows_view.h, shell/platform/windows/testing/mock_window_binding_handler.h, shell/platform/windows/window.cc, shell/platform/windows/window.h, shell/platform/windows/window_binding_handler.h
The platform message used to trigger announcements/alerts by the Framework was previously ignored on Windows, as there was no channel to accept it, nor method to announce it. This PR receives the message to announce a message to the screen reader. The former root node of the Window is now wrapped by a parent node which may also create an alert node as a sibling, and can then notify a `EVENT_SYSTEM_ALERT` event pointing to this alert node to read out an alert.
You may test this by running the code sample in the linked issue with either Windows Narrator or NVDA.
Addresses https://github.com/flutter/flutter/issues/113059 …
=> Announce alerts through SemanticsService on Windows

shell/platform/fuchsia/flutter/flatland_platform_view.cc, shell/platform/fuchsia/flutter/tests/flatland_platform_view_unittest.cc
This PR fixes a bug identified after DPR feature was added in flatland where currently we do not multiple the logical size of the view by the pixel ratio.
This change is getting tested in input tests like mouse-input-test, touch-input-test
[CLA]: …
=> [fuchsia][scenic] Fix logical size in flatland platform view.

impeller/aiks/canvas.cc, impeller/aiks/canvas.h, impeller/display_list/display_list_dispatcher.cc
Also, only copy the paint state when it needs to be modified.
Also also, I filed https://github.com/flutter/flutter/issues/114184 to document that we need to make this not apply when the paint color source isn't solid color (this feature predates color sources and geometry).
Of course, the slow blur's downsampling behavior clearly still needs some fixing up too, as can be observed below ;)
Before:
After:
=> [Impeller] Use the fast rrect blur path for blurred circles/circular shadows

impeller/renderer/backend/metal/device_buffer_mtl.mm, testing/run_tests.py
Fix https://github.com/flutter/flutter/issues/114110
Enable metal validation when running impeller unittests .. or try to anyway.
=> [Impeller] Set resourceOptions/storageMode on MTLTextures created from MTLBuffers.

lib/ui/fixtures/ui_test.dart, runtime/fixtures/dart_tool/flutter_build/dart_plugin_registrant.dart, runtime/fixtures/no_dart_plugin_registrant_test.dart, runtime/fixtures/runtime_test.dart, shell/common/fixtures/shell_test.dart, shell/platform/darwin/macos/framework/Source/fixtures/flutter_desktop_test.dart, shell/platform/embedder/fixtures/main.dart, shell/platform/fuchsia/dart-pkg/fuchsia/lib/fuchsia.dart, shell/platform/fuchsia/dart-pkg/zircon/lib/src/handle.dart, shell/platform/fuchsia/dart-pkg/zircon/lib/src/handle_disposition.dart, shell/platform/fuchsia/dart-pkg/zircon/lib/src/handle_waiter.dart, shell/platform/fuchsia/dart-pkg/zircon/lib/src/system.dart, shell/platform/fuchsia/dart_runner/embedder/builtin.dart, shell/platform/windows/fixtures/main.dart, shell/platform/windows/testing/windows_test_context.h, third_party/tonic/tests/fixtures/tonic_test.dart
The old `native "<name>"` syntax is being replaced with external functions that
have a `@pragma("external-name", "<name>")`.
See https://github.com/dart-lang/sdk/issues/28791
=> Remove usages of deprecated old `native "<name>"` syntax.

DEPS
This is used to avoid trying to download experimental dependencies as part of the release candidate branches.
Bug: https://github.com/flutter/flutter/issues/113931 …
=> Adds a release_candidate variable to DEPS.

lib/ui/compositing.dart
I see this assert fail when working on my own app today (unrelated to flutter_smooth; work on stable channel). With identity hashcode, we can surely know more about which layer violates.
- [
- x] I signed the [CLA].
[CLA]: …
=> Let `_debugCheckNotUsedAsOldLayer` provide hashcode in addition to runtime type

lib/web_ui/lib/src/engine/semantics/label_and_value.dart, lib/web_ui/lib/src/engine/semantics/semantics.dart, lib/web_ui/test/engine/semantics/semantics_test.dart, lib/web_ui/test/matchers.dart
This fixes the following issues with ARIA labels, groups, and heading:
- Replace `<flt-semantics-value>` with `role="text"`. The text role works better in Safari, and the extra element causes the AT to read the same label multiple times. (fixes https://github.com/flutter/flutter/issues/91914)
- Use explicit `role="group"` for nodes with children. This communicates the label to the user as a group of elements, enabling enter/exit group gestures.
- Do not use `role="heading"` for nodes with children, because that prevents the AT from reaching child nodes.
This change does not fix the issue with Chrome reading "group" or "empty group" on text labels. I could not find a way to simultaneously control the positioning/sizing of an element _and_ have it be treated as text. Using actual text in …
=> [web:a11y] fix group vs label relationship

shell/platform/android/io/flutter/view/AccessibilityBridge.java, shell/platform/android/test/io/flutter/view/AccessibilityBridgeTest.java
fixes https://github.com/flutter/flutter/issues/113457
The previous pr is reverted due to it causes crash on device with android api < 26. This pr fixes by adding a guard around the original pr. The change is in the second commit. …
=> Reland fixes Android text field to use hint text for accessibility

.ci.yaml, ci/lint.sh, shell/platform/darwin/ios/framework/Source/FlutterViewControllerTest.mm
Only run clang-tidy builders in presubmit when C, C++, ObjC, or ObjC++ files change.  Also run if the `DEPS` or CI files change.  Run on `Linux Android clang-tidy` if any python files change, since that's the shortest-running builder.  All builds will always run in post-submit.
To test the globs, the first commit https://github.com/flutter/engine/pull/36887/commits/586b9e16b8518a499e1b1c05e8a1ef2a7f2cc5f8 added a comment to a `.mm` file, and `Mac Host clang-tidy` did not include `.ci.yaml`.  It was correctly scheduled just because of the extension: 
https://ci.chromium.org/p/flutter/builders/try/Mac%20Host%20clang-tidy/760 …
=> Only run clang-tidy in presubmit when C, C++, ObjC, or ObjC++ files change

shell/platform/darwin/ios/framework/Source/FlutterView.mm, shell/platform/darwin/macos/framework/Headers/FlutterViewController.h, shell/platform/darwin/macos/framework/Source/FlutterEngineTest.mm, shell/platform/darwin/macos/framework/Source/FlutterView.h, shell/platform/darwin/macos/framework/Source/FlutterView.mm, shell/platform/darwin/macos/framework/Source/FlutterViewController.mm, shell/platform/darwin/macos/framework/Source/fixtures/flutter_desktop_test.dart
The background color of a macOS application defaults to the system's window default. This patch makes the default color black. More discussion is required to engineer an API that is suitable for clients that need to override this default behavior. …
=> [macOS] Make the default background color black.

shell/platform/darwin/BUILD.gn, shell/platform/darwin/common/BUILD.gn, shell/platform/darwin/common/framework/Headers/FlutterCodecs.h, shell/platform/darwin/common/framework/Source/FlutterChannels.mm, shell/platform/darwin/common/framework/Source/FlutterCodecs.mm, shell/platform/darwin/common/framework/Source/FlutterStandardCodec.mm, shell/platform/darwin/ios/framework/Source/FlutterRestorationPluginTest.mm
Reverts https://github.com/flutter/engine/pull/37049 that causes a regression: https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_ios%20channels_integration_test_ios/7695/overview …
=> Revert "Migrate darwin common "framework_shared" target to ARC (#37049)"

impeller/compiler/impellerc_main.cc, impeller/compiler/reflector.cc, impeller/compiler/reflector.h, impeller/compiler/runtime_stage_data.cc, impeller/compiler/runtime_stage_data.h, impeller/compiler/types.cc, impeller/compiler/types.h, impeller/runtime_stage/runtime_stage.cc, impeller/runtime_stage/runtime_stage.fbs, impeller/runtime_stage/runtime_stage.h, lib/ui/painting/fragment_program.cc
The backend is chosen at runtime, so the shaders bundled with an app must include both SkSL and the platform specific shader.
Related https://github.com/flutter/flutter/issues/114197
=> [Impeller] Always include SkSL in .iplr files

shell/platform/darwin/ios/framework/Source/FlutterViewController.mm, shell/platform/darwin/ios/framework/Source/FlutterViewControllerTest.mm
This reverts commit 69f2bc881f466871605289571f913a75f700a4c4.
Googlers, see b/256523098. tl;dr is internally our build isn't ready to support XCode 14
=> Revert "Use iOS 16 APIs to rotate orientation (#36874)"

ci/licenses_golden/licenses_flutter, shell/platform/android/BUILD.gn, shell/platform/android/io/flutter/plugin/platform/AccessibilityEventsDelegate.java, shell/platform/android/io/flutter/plugin/platform/PlatformOverlayView.java, shell/platform/android/io/flutter/plugin/platform/PlatformViewsController.java, shell/platform/android/io/flutter/view/AccessibilityBridge.java, shell/platform/android/test/io/flutter/plugin/platform/AccessibilityEventsDelegateTest.java, shell/platform/android/test/io/flutter/plugin/platform/PlatformOverlayViewTest.java, shell/platform/android/test/io/flutter/plugin/platform/PlatformViewsControllerTest.java, shell/platform/android/test/io/flutter/view/AccessibilityBridgeTest.java, tools/android_lint/project.xml
Configure overlay views for Hybrid Composition Android platform views to forward the hover events used for Talkback exploration to the underlying Flutter view that knows about the virtual accessibility tree, so that tapping on items that are in the overlay view will focus them for Talkback.
HC portion of https://github.com/flutter/flutter/issues/101887 …
=> Forward a11y events from Hybrid Composition overlays

ci/builders/mac_ios_engine.json
To match https://flutter.googlesource.com/recipes/+/refs/heads/main/recipes/engine/engine.py#1443
=> Enable goma for arm64 iOS simulator build in engine_v2 recipe

lib/ui/plugins/callback_cache.cc
If we don't use callback cache, every time we start the app, the log prints "Runner[667:97662] [VERBOSE0:callback_cache.cc(136)] Could not parse callback cache, aborting restore", which may lead to misleading.
[CLA]: …
=> [iOS] Not log callback cache info if cache is empty

lib/web_ui/lib/src/engine/text_editing/text_editing.dart, lib/web_ui/test/composition_test.dart, lib/web_ui/test/text_editing_test.dart
Currently there's an issue in which keyboard shortcuts (shift + arrow keys) don't autoscroll on web inputs and textfields. Delegating these keyboard actions to the framework fixes this issue and allows for a more consistent UX for web. 
As part of that change, the `EditableState` class needs to be able to handle flipped base and extent offsets, as well as have sensible defaults for composing offsets.
Part 1 of fix for https://github.com/flutter/flutter/issues/107707
Framework changes PR: https://github.com/flutter/flutter/pull/114264
=> [web] Changes to EditableState to be able to handle Framework text selection shortcuts 

lib/ui/painting/image_decoder_unittests.cc, third_party/txt/tests/render_test.cc
In <https://skia-review.googlesource.com/c/skia/+/597559>, Skia is changing an #include to a forward declare in a public header. This requires some Flutter files to include that file directly instead of depending on the (now removed) transitive include.
While I was fixing up these files, I made a few pre-emptive fixes of these missing includes.
- [ x  ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on …
=> Fix Skia includes of SkEncodedImageFormat et al

DEPS, ci/licenses_golden/licenses_third_party, ci/licenses_golden/tool_signature, tools/gn, tools/licenses/lib/patterns.dart
This change updates ANGLE to a version that contains [angle#3906325](https://chromium-review.googlesource.com/c/angle/angle/+/3906325), which fixes the COM error reported in  https://github.com/flutter/flutter/issues/110948. This also updates vulkan-deps and shaderc as these are dependencies of ANGLE.
Part of https://github.com/flutter/flutter/issues/110948 …
=> Roll ANGLE, vulkan-deps, and shaderc

lib/web_ui/lib/src/engine/dom.dart, lib/web_ui/lib/src/engine/text_editing/text_editing.dart, lib/web_ui/test/text_editing_test.dart
When `(forced-colors: active)` is enabled in Chrome settings, it messes with the trasnparent styles that we set on text fields. This PR adds `forced-color-adjust: none;` to prevent that.
=> [web] Prevent (forced-colors: active) from making the invisible text fields visible

tools/clang_tidy/lib/clang_tidy.dart, tools/clang_tidy/test/clang_tidy_test.dart
Previously we would print out errors twice (or thrice if you had `--verbose`).  Also we were printing out the invocation which isn't necessary now that the `--verbose` flag does that.  Users want to know the filename and a quick description of the errors.
issue: https://github.com/flutter/flutter/issues/113848
[testing the …
=> Clang-tidy: cleaned up the output.

impeller/renderer/backend/gles/shader_library_gles.cc, impeller/renderer/backend/gles/shader_library_gles.h, impeller/renderer/backend/metal/shader_library_mtl.h, impeller/renderer/backend/metal/shader_library_mtl.mm, impeller/renderer/backend/vulkan/shader_library_vk.cc, impeller/renderer/backend/vulkan/shader_library_vk.h, impeller/renderer/shader_library.h, impeller/runtime_stage/runtime_stage_unittests.cc
* I haven't comprehensively verified that this doesn't leak GPU resources.
* For Metal, since `GetFunction` searches through the libraries to find a matching function if one doesn't exist in the function map, I do the same and delete the library if found. I think we should tighten this up at some point by either back shader keys to specific libraries, or perhaps separate `RegisterFunction` libraries into their own list distinct from those passed in through the ctor.
=> [Impeller] Add ability to unregister shaders

shell/platform/darwin/BUILD.gn, shell/platform/darwin/common/BUILD.gn, shell/platform/darwin/common/framework/Headers/FlutterCodecs.h, shell/platform/darwin/common/framework/Source/FlutterChannels.mm, shell/platform/darwin/common/framework/Source/FlutterChannelsTest.m, shell/platform/darwin/common/framework/Source/FlutterCodecs.mm, shell/platform/darwin/common/framework/Source/FlutterStandardCodec.mm, shell/platform/darwin/ios/framework/Source/FlutterRestorationPluginTest.mm
This PR relands https://github.com/flutter/engine/pull/37049
The original PR wrongly added weak modifies to the codec object that needs to be strongly captured by the block. See https://github.com/flutter/engine/pull/37049/files#r1010821732
The changes in this PR beyond 37049 including: 
1. Removed the __weak modifier in https://github.com/flutter/engine/pull/37049/files#r1010822618 and https://github.com/flutter/engine/pull/37049/files#r1010821732
2, New unit tests have been added in this PR to ensure the bug is caught in engine.
part of https://github.com/flutter/flutter/issues/112232 …
=> reland "Migrate darwin common "framework_shared" target to ARC #37049"

flow/layers/display_list_layer_unittests.cc, flow/layers/display_list_raster_cache_item.cc
This problem was discovered when some of the benchmarks changed under the LayerStateStack mechanism, it looks like the code in DLRCI::PrerollFinalize was mutating the preroll context cull_rect when it was just wanting to check for intersection due to the use of the wrong `SkRect` method (`intersect` instead of `intersects`). This meant that we would be less likely to cache other DLLayers inside the same sub-tree. Only a layer that saved and restored the cull_rect such as the clip layers or the transform layer would protect against this issue.
This problem will be fixed when the LayerStateStack code eventually goes in as a side effect of relegating the culling to the LSS object, but this PR will introduce the fix earlier so that any benchmarks can be rebased to the new behavior. Then when …
=> fix use of intersect/intersects in DisplayListRasterCacheItem

ci/builders/mac_ios_engine_profile.json, ci/builders/mac_ios_engine_release.json
The configurations were passing no-goma explicitly to the gn command which was disabling the use of goma.
Bug: https://github.com/flutter/flutter/issues/114477 …
=> Build ios with goma.

lib/web_ui/README.md
I was failing to build the web engine locally with `felt build` until I realized that I needed to add the `--host` flag.  It's mentioned in the output for `felt build --help`, which is how I found it, but it doesn't seem to be mentioned in the web engine README.  So this PR adds it.
I'm unfamiliar with the situation behind the `--host` flag, so if this docs change is irrelevant or should go somewhere else, please close or let me know where else I should update.
=> Update docs to mention `felt build --host`

lib/ui/ui_dart_state.cc, testing/dart/isolate_test.dart
Fixes https://github.com/flutter/flutter/issues/114138
=> Enter a scope before calling Dart APIs in ThrowIfUIOperationsProhibited

impeller/aiks/paint.cc, impeller/display_list/display_list_unittests.cc
It seems to apply the color filter first, and then apply the image filter.
See this example for details
https://fiddle.skia.org/c/5e62809886613c144f50fa99f1954850 …
=> [Impeller] Correct the ordering of filters in 'Paint::WithFilters'

tools/gn, web_sdk/BUILD.gn
Also produce explicit variants with different dart defines set.
This fixes everything in https://github.com/flutter/flutter/issues/99161 except we are still using `kernel_worker` instead of `compile_platform`.
This also is part of a fix for https://github.com/flutter/flutter/issues/113966. The follow-on for the flutter tool should make it so that `flutter build web --local-engine=wasm_release` should work.
=> Produce both ddc and dart2js platform files.

ci/licenses_golden/licenses_flutter, impeller/renderer/backend/vulkan/context_vk.cc, impeller/renderer/backend/vulkan/context_vk.h, impeller/renderer/backend/vulkan/pipeline_library_vk.cc, impeller/renderer/backend/vulkan/surface_producer_vk.cc, impeller/renderer/context.cc, impeller/renderer/context.h, impeller/renderer/pipeline_builder.h, shell/platform/android/BUILD.gn, shell/platform/android/android_surface_vulkan_impeller.cc, shell/platform/android/android_surface_vulkan_impeller.h, shell/platform/android/platform_view_android.cc, tools/gn
- This enables preliminary support for Impeller + Vulkan on Android.
- Pending multiple fidelity fixes and adding a preference for Vulkan.
- Also noteworthy is https://github.com/flutter/flutter/issues/114531
=> [Impeller] Wire-up AndroidSurfaceImpellerVulkan

impeller/compiler/spirv_sksl.cc
SPIRV_CROSS_THROW can be configured to either throw an exception or print a message and abort. We don't enable exceptions, so the latter is the only choice. For now, though this has two additional problems:
* The message is only printed in unopt/debug builds
* The abort is caught by our own exception handler in fml/backtrace.h which adds a nasty stack trace.
Long-term, we might consider sending a patch to change this behavior. In the short term, we can improve the messages we add by using a differen macro
Before:
```
$impellerc --sksl --iplr --sl=shaders/hello.glsl --spirv=shaders/hello.glsl.spirv --input=shaders/hello.glsl --input-type=frag --include=examples/hello_world/shaders
[ERROR:flutter/fml/backtrace.cc(108)] Caught signal SIGABRT during program execution.
Frame 0: 0x102fce3b8 …
```
=> [Impeller] dont call SPIRV_CROSS_THROW in SkSL backend

impeller/compiler/spirv_sksl.cc
Fixes https://github.com/flutter/flutter/issues/114536
=> [Impeller] validate that SkSL has no user supplied inputs

.ci.yaml
This is also removing the environment variable as it is not needed anymore. …
=> Move the two remaining engine v2 builds to prod.

shell/platform/darwin/ios/framework/Source/FlutterPlatformViews.mm, shell/platform/darwin/ios/framework/Source/FlutterPlatformViewsTest.mm, shell/platform/darwin/ios/framework/Source/FlutterPlatformViews_Internal.h, shell/platform/darwin/ios/framework/Source/FlutterPlatformViews_Internal.mm
Keeps visual effect view alive and reuse them when possible.
Fixes https://github.com/flutter/flutter/issues/114443 …
=> Make iOS PlatformView to reuse VisualEffectView when possible.

impeller/display_list/display_list_unittests.cc
This demonstrates remaining shadow quality issues caused by the gaussian blur downsampling curve.
=> [Impeller] Add non-rrect polygon to shadow test

lib/web_ui/dev/build.dart, tools/gn
Doing a `felt build` (without `--host`) causes high cpu usage for some people (including me and @htoor3). This is because our build tries to use `goma` with a high parallelization factor that all ends up happening in the local machine because `goma` doesn't support `emscripten` yet.
This PR disables `goma` for wasm/web builds.
=> [web] Improve CPU usage when building wasm_release

impeller/entity/contents/runtime_effect_contents.cc, impeller/entity/entity_unittests.cc, impeller/runtime_stage/runtime_stage.cc, impeller/runtime_stage/runtime_stage.h
This is a quick and dirty way to get hot reloading working for runtime stage shaders in Impeller.
I'm still trying to work out how we should manage accessing the Impeller context held by the surface for https://github.com/flutter/flutter/issues/113719, so this is a simple/low risk stopgap to get hot reload working in the meantime.
Making hot reload actually work with `flutter run/attach` is blocked on https://github.com/flutter/flutter/issues/114654.
=> [Impeller] Replace existing shaders when a new RuntimeStage arrives through the dispatcher

lib/web_ui/lib/src/engine/text_editing/text_editing.dart, lib/web_ui/test/text_editing_test.dart
This PR prevents new line key event from being dispatched when `TextField.textInputAction` is not `TextInputAction.newline` and the text field is not multiline.
Fixes https://github.com/flutter/flutter/issues/113559
Since https://github.com/flutter/engine/pull/33428, web engine does not prevent new line key events.
~~Here, I choose to prevent it whether the field is multiline or not.~~
For a **single line field** (the default text input action is `TextInputAction.done`):
- before this PR, the action is performed and the keyboard event is not prevented. If the action changes focus to another field (`TextInputAction.next` for instance), the newly focused field inserts the new line (see https://github.com/flutter/flutter/issues/113559).
- after this PR, the action is performed and the …
=> Fix TextField performing both new line and input action

testing/scenario_app/ios/Scenarios/ScenariosUITests/UnobstructedPlatformViewTests.m
This was previously testing the same overlay view twice in a row.  Instead, first test the first overlay size and then the second. …
=> Fix typo in overlay platform view iOS test

impeller/entity/contents/clip_contents.cc, impeller/entity/contents/content_context.cc, impeller/entity/contents/content_context.h, impeller/entity/contents/contents.cc, impeller/entity/contents/linear_gradient_contents.cc, impeller/entity/contents/radial_gradient_contents.cc, impeller/entity/contents/rrect_shadow_contents.cc, impeller/entity/contents/runtime_effect_contents.cc, impeller/entity/contents/solid_color_contents.cc, impeller/entity/contents/sweep_gradient_contents.cc, impeller/entity/contents/text_contents.cc, impeller/entity/contents/tiled_texture_contents.cc, impeller/entity/contents/vertices_contents.cc, impeller/entity/entity_unittests.cc, impeller/playground/imgui/imgui_impl_impeller.cc, impeller/renderer/backend/gles/render_pass_gles.cc, impeller/renderer/backend/metal/render_pass_mtl.mm, impeller/renderer/backend/vulkan/formats_vk.h, impeller/renderer/backend/vulkan/pipeline_library_vk.cc, impeller/renderer/command.h, impeller/renderer/pipeline_descriptor.cc, impeller/renderer/pipeline_descriptor.h, impeller/renderer/renderer_unittests.cc
This is the correct abstraction for Vulkan as we need this during primitive assembly. We also know this ahead of time so its useful to just wire it in.
Fixes https://github.com/flutter/flutter/issues/106379
=> Move primitive type to pipeline descriptor

DEPS
Reverts flutter/engine#37076
A number of users on m1 macs can't build ios configurations as the binaries are immediately killed with -9. Revert until we figure this out
https://bugs.fuchsia.dev/p/fuchsia/issues/detail?id=113913
=> Revert "Roll Clang from a93d03310e2c to bca75abc01f3"

BUILD.gn
https://github.com/flutter/buildroot/pull/645 and https://github.com/flutter/engine/pull/37125 will cause the android arm64 gen_snapshot to be generated under `clang_x64` similar to other cross-builds. That would break the CI recipe. Instead, this PR copies the `gen_snapshot` for all configs to a standard location so that we can do a soft transition.
=> Copy Windows gen_snapshot to a standard location

shell/platform/windows/direct_manipulation.cc, shell/platform/windows/direct_manipulation.h, shell/platform/windows/direct_manipulation_unittests.cc, shell/platform/windows/window.cc, shell/platform/windows/window.h
Increase polling rate from 60 Hz to 240 Hz or 4 times the monitor refresh rate. It seems like the polling rate does not match 1:1 with the returned updates, eventually leading to scrolls with missing framework momentum. This was because the gap between updates was too large (above 40 ms), so the velocity tracker in the framework returned an estimate of zero.
Also fix an issue introduced in #34452, where the transition to using inertia means that repeated swipes had no opportunity to reset the transform matrix. Now pan zoom updates will compare with the gesture data at pan zoom start time. Eventually, once swipes stop, the matrix will be reset to zero.
Fixes https://github.com/flutter/flutter/issues/114082
=> Increase Win32 trackpad polling rate, fix repeated swipes issue

ci/licenses_golden/tool_signature, tools/licenses/lib/main.dart
This recursive self-call will get flagged in the upcoming linter release.
See: https://dart-review.googlesource.com/c/sdk/+/264961 …
=> fix recursive self calls

impeller/compiler/impellerc_main.cc, impeller/compiler/switches.cc, impeller/compiler/utilities.cc, impeller/compiler/utilities.h
Without having reproduced the problem yet, I'm hoping this will fix the Windows test failure in https://github.com/flutter/flutter/pull/114214. Either way, this refactor simplifies an ugly aspect of the code.
This moves our "works everywhere" solution for utf8-respecting paths to a utility method, and passes include input paths through it.
History of how we got here:
https://github.com/flutter/engine/pull/36158
https://github.com/flutter/engine/pull/36223
=> [Impeller] Process ImpellerC include paths the same way as output paths

impeller/compiler/impellerc_main.cc, impeller/compiler/switches.cc, impeller/compiler/types.cc, impeller/compiler/types.h
Fixes new engine build issues I'm running into on Windows today:
```
[6880/7798] ACTION //flutter/lib/ui/fixtures/shaders/suppo...pile_supported_op_shaders(//build/toolchain/win:clang_x64)
FAILED: gen/flutter/lib/ui/fixtures/shaders/supported_op_shaders/iplr/145_OpMatrixTimesVector.frag.iplr
C:/Users/bdero/.vpython-root/cf506f/Scripts/python.exe ../../build/gn_run_binary.py impellerc.exe --input=../../flutter/lib/ui/fixtures/shaders/supported_op_shaders/145_OpMatrixTimesVector.frag --include=../../flutter/lib/ui/fixtures/shaders/supported_op_shaders --include=C:/Users/bdero/projects/flutter/engine/src/flutter/impeller/compiler/shader_lib --depfile=gen/flutter/lib/ui/fixtures/shaders/supported_op_shaders/iplr/145_OpMatrixTimesVector.frag.d --sksl …
```
=> [Impeller] Apply the Windows friendly path solution for remaining ImpellerC paths

impeller/geometry/geometry_unittests.cc, impeller/geometry/matrix.h
Simple utility to inverse translate by a position, snap the forward basis to face a target, and lock the up and right basis/yaw to align with an up vector. Useful for building camera transforms.
=> [Impeller] Add Matrix::LookAt

.ci.yaml
This property was previously hardcoded in the recipe.
This is a pre-requisite for https://flutter-review.googlesource.com/c/recipes/+/35661
Bug: https://github.com/flutter/flutter/issues/114656 …
=> Move gclient var property to ci.yaml

lib/ui/platform_dispatcher.dart, lib/web_ui/lib/platform_dispatcher.dart, lib/web_ui/lib/src/engine/platform_dispatcher.dart
=> Revert "Remove deprecated calls to updateSemantics in `PlatformDispatcher`"

shell/platform/embedder/embedder.cc, shell/platform/embedder/embedder.h, shell/platform/embedder/tests/embedder_a11y_unittests.cc, shell/platform/embedder/tests/embedder_config_builder.cc, shell/platform/embedder/tests/embedder_test_context.cc, shell/platform/embedder/tests/embedder_test_context.h, shell/platform/windows/flutter_windows_engine.cc, shell/platform/windows/flutter_windows_engine_unittests.cc
This introduces a new embedder API to notify the embedder of semantic updates, and, migrates Windows to this new embedder API. The Linux and macOS migrations will be done in follow-up changes.
Part of https://github.com/flutter/flutter/issues/114201
In the old embedder API, the engine breaks up a batch of semantic updates and sends each update individually to the embedder. This is problematic as there may be dependencies across these updates, so the ordering of these updates is crucial to prevent crashes (see https://github.com/flutter/flutter/issues/103808 and https://github.com/flutter/engine/pull/35792). In other words, there was an implicit contract between the embedder and the engine on the ordering of these updates.
The new embedder API just sends the entire batch of semantic …
=> [Embedder API] Introduce new semantics update callback and migrate Windows

ci/lint.sh
This helps with migrating new linter checks that have fixes implemented.  Turning this on allows the bots to print out the diff that can be patched locally across all platform CI checks.
issue: https://github.com/flutter/flutter/issues/113848 …
=> clang-tidy: Added an environment variable that allows fix to print the     generated diff.

.ci.yaml
The json translation of gclient_vars is failing because it can't parse the boolean value as True.
Bug: https://github.com/flutter/flutter/issues/114656 …
=> Fix boolean json property.

display_list/display_list_utils.cc, testing/scenario_app/run_ios_tests.sh
When the accumulator is an `RTreeBoundsAccumulator` rather than a `RectBoundsAccumulator` just accumulating the bounds results in incorrect results as the `rtree` would need to be aware of the constituent non-overlapping rectangles. This would work fine for `RectBoundsAccumulator` as it would just adjust its bounds based on the passed rects.
Fixes: https://github.com/flutter/flutter/issues/113251
=> Add rects to accumulator rather than bounds

shell/platform/fuchsia/dart_runner/tests/startup_integration_test/dart_aot_runner/meta/dart-aot-runner-integration-test.cml, shell/platform/fuchsia/dart_runner/tests/startup_integration_test/dart_jit_runner/meta/dart-jit-runner-integration-test.cml, shell/platform/fuchsia/flutter/tests/integration/embedder/meta/flutter-embedder-test.cml, shell/platform/fuchsia/flutter/tests/integration/mouse-input/meta/mouse-input-test.cml, shell/platform/fuchsia/flutter/tests/integration/text-input/meta/text-input-test.cml, shell/platform/fuchsia/flutter/tests/integration/touch-input/meta/touch-input-test.cml
Reverts flutter/engine#37395
link to failure resulting in revert: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Fuchsia%20FEMU/12755/overview
=> Revert "Sdk roll failure - add facet to allowlist test_manager and other packages."

display_list/display_list_utils.cc, testing/scenario_app/run_ios_tests.sh
This reverts commit 306b0fe9ccb17a129e16cb3e682206538ce5b359.
=> Revert "Add rects to accumulator rather than bounds (#37435)"

tools/clang_tidy/lib/src/options.dart, tools/clang_tidy/test/clang_tidy_test.dart
fixes failure: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8798099822610209889/+/u/test:_lint_host_debug/stdout
That resulted in revert: https://flutter-review.git.corp.google.com/c/recipes/+/35742 …
=> Clang-tidy: Fixed math on shard-id validator.

ci/licenses_golden/licenses_flutter, impeller/compiler/BUILD.gn, impeller/compiler/switches.cc, impeller/compiler/switches_unittests.cc, impeller/compiler/utilities.h
Should fix the Windows-only customer test failure in https://github.com/flutter/flutter/pull/114214.
It turns out that we were mangling includes with non-ascii unicode characters due to double encoding because:
1. `fml::CommandLine` already converts utf16 paths to utf8 on Windows, and
2. `path::u8string()` assumes the underlying path encoding is the native path encoding (and in this case it wasn't, because the paths were already encoded as utf8).
=> [Impeller] Don't double-convert include path encodings in ImpellerC

display_list/display_list_unittests.cc, display_list/display_list_utils.cc, display_list/display_list_utils.h, testing/scenario_app/run_ios_tests.sh
When the accumulator is an `RTreeBoundsAccumulator` rather than a `RectBoundsAccumulator` just accumulating the bounds results in incorrect results as the `rtree` would need to be aware of the constituent non-overlapping rectangles. This would work fine for `RectBoundsAccumulator` as it would just adjust its bounds based on the passed rects.
Fixes: https://github.com/flutter/flutter/issues/113251
=> [Reland] Add rects to accumulator rather than bounds (#37435)

impeller/entity/contents/clip_contents.cc
This was wrongly removed in https://github.com/flutter/engine/pull/37315/ where I assumed that this was overwritten by geometry_result a few lines below, but there is indeed a pipeline created earlier in line:100.
Fixes: https://github.com/flutter/flutter/issues/114870
=> Use traingle strip for difference clip

ci/licenses_golden/licenses_flutter, shell/platform/common/client_wrapper/core_implementations.cc, shell/platform/common/client_wrapper/testing/stub_flutter_api.cc, shell/platform/common/public/flutter_messenger.h, shell/platform/embedder/embedder.cc, shell/platform/glfw/flutter_glfw.cc, shell/platform/windows/flutter_desktop_messenger.h, shell/platform/windows/flutter_windows.cc, shell/platform/windows/flutter_windows_engine.cc, shell/platform/windows/flutter_windows_engine.h, shell/platform/windows/flutter_windows_engine_unittests.cc, shell/platform/windows/public/flutter_windows.h, shell/platform/windows/window_state.h
This makes it so platform message handlers on Windows can invoke their replies from any thread.  The reason this is possible is:
* There is little actual work that is happening on the thread invoking the reply.  It has mostly to do with manipulating resources uniquely assigned to the message and thread hopping to the ui thread.
* We've introduced a lock that makes sure the dispatcher used to handle messages isn't deleted while the background thread is invoking the reply.
* We decoupled the FlutterDesktopMessenger from the Engine so that the FlutterDesktopMessenger can outlive the Engine but be in an invalid state.  (This surfaced a bug that already existed in the implementation since a reply could always have outlasted an engine).
issue: https://github.com/flutter/flutter/issues/93945 …
=> Implemented threadsafe platform channel replies on windows

lib/web_ui/lib/src/engine/canvaskit/canvaskit_api.dart, lib/web_ui/lib/src/engine/text/font_collection.dart
Per https://github.com/dart-lang/sdk/issues/49941, synthetic constructors will be disallowed on @staticInterop classes. Functionally, they are lowered to the same code.
Also fixes an erroneous call to the DomHTMLStyleConstructor instead of the relevant factory method.
Migration needed to fix https://github.com/dart-lang/sdk/issues/49941
These factories were added because they were caught by the flutter trybots (https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8798044738469408369/+/u/build_host_debug/stdout).
=> Add external factories for @staticInterop classes instead of synthetic constructor

shell/platform/android/platform_view_android.cc
This is to enable building in google3.
See also: b/258506856
=> [Impeller] Include AndroidSurfaceVulkanImpeller behind a flag.

impeller/entity/contents/tiled_texture_contents.cc
It is a duplicate of the following line of code.
https://github.com/flutter/engine/blob/2ac9c73f664c0a20dc7dedb345a9b8199db6d82f/impeller/entity/contents/tiled_texture_contents.cc#L81
=> [Impeller] Remove duplicate code in 'TiledTextureContents'

.clang-tidy, ci/lint.sh, impeller/renderer/backend/vulkan/pipeline_library_vk.cc, shell/platform/darwin/ios/framework/Source/FlutterPlatformViews.mm
fixes: https://github.com/flutter/flutter/issues/113848
[Discord]: …
=> Turned on performance-move-const-arg everywhere.

lib/web_ui/dev/analyze.dart, lib/web_ui/dev/felt.bat, lib/web_ui/dev/felt.dart
Adds a `felt analyze` command, which CI can invoke instead of directly invoking dart itself.
=> Felt analyze

.ci.yaml
This will run the specified jobs under the release builder recipe in dart-internal.
Bug:b/232552448
- [] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on writing and running engine tests. …
=> Adding release_build:true to Mac builds.

.gitignore, DEPS, ci/licenses_golden/tool_signature, third_party/ninja/README.flutter, tools/licenses/lib/main.dart
Install CIPD ninja using DEPS
This is required to deprecate ninja binary in depot_tools. 
See https://crbug.com/1340825 and chromium/src's CL https://crrev.com/c/3869740 for more contexts.
=> Install CIPD ninja using DEPS

shell/platform/darwin/macos/framework/Source/AccessibilityBridgeMac.mm
Now that the macOS embedders have all been updated to use a minimum macOS SDK of 10.14, eliminate the remaining `@available` checks dependent on that version.
This is one in a series of post-10.14 cleanup patches.
No tests are added since the code removed was a workaround for macOS 10.13. We now build with both a minimum SDK and deployment target of 10.14, and as such the workaround was already disabled at compile-time, making this change effectively a no-op.
Issue: https://github.com/flutter/flutter/issues/114445 …
=> [macOS] Eliminate macOS 10.14 availability check

DEPS
The dot at the end got picked up when clicking on the link.
This is purely a comment change so no new tests added. …
=> chore: fix Dart SDK DEPS file link in DEPS

lib/ui/window/platform_configuration.cc, lib/ui/window/platform_configuration.h, runtime/runtime_controller.cc, shell/common/fixtures/shell_test.dart, shell/common/shell_unittests.cc
This is to ensure that smoother animations take precedence over idle notifications that trigger GC work.
=> Do not call Dart_NotifyIdle when in Dart_PerformanceMode_Latency

impeller/entity/contents/runtime_effect_contents.cc
Fixes https://github.com/flutter/flutter/issues/115031
Textures were fine, but without blending enabled we always seemed to clear the screen. Even a fully transparent output from a shader would be black. This seems to fix things visually.
=> [Impeller] enable blending on RuntimeEffectsContents

testing/run_tests.py, tools/const_finder/bin/main.dart, tools/const_finder/lib/const_finder.dart, tools/const_finder/pubspec.yaml, tools/const_finder/test/const_finder_test.dart, tools/const_finder/test/fixtures/lib/denylist.dart, tools/const_finder/test/fixtures/lib/static_icon_provider.dart
Part of https://github.com/flutter/flutter/issues/57181
This updates the `const_finder` to recognize an annotation with the class name `StaticIconProvider`, which will lead to all constant references within that class being ignored. This will be a no-op for non-web Flutter builds, however will allow partial tree-shaking for Flutter for web builds (see https://github.com/flutter/flutter/issues/57181#issuecomment-1295418012 for why some unused icons will still be retained).
A follow-up framework/tool PR will be required to start calling const_finder during web builds, passing it the web dill and adding the annotation to the `Icons` class in https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/icons.dart.
I locally confirmed that a dill file created as part of …
=> extend const_finder to allow skipping particular classes

flow/surface_frame.cc, shell/common/rasterizer.cc, shell/gpu/gpu_surface_metal_impeller.mm, shell/platform/darwin/ios/framework/Source/FlutterPlatformViews.mm
Added a few trace lines that clarified some things for me while taking a look at https://github.com/flutter/flutter/issues/114712.
=> [Impeller] Add some traces around impeller rendering

lib/ui/painting.dart
Its a bit confusing how the sampler/float index exactly maps to the order of uniforms in the shader program. Add some API docs to attempt to explain this, along with a code snippet.
=> [dart:ui] add documentation to FragmentShader setSampler/setFloat

lib/ui/painting.dart
Reverts flutter/engine#37503
TBR @zanderso 
Forgot that we don't run docs analysis in flutter/engine
=> Revert "[dart:ui] add documentation to FragmentShader setSampler/setFloat"

impeller/typographer/backends/skia/text_render_context_skia.cc, impeller/typographer/typographer_unittests.cc
Might help slightly, still need to pay the cost of reupload though
=> [Impeller] reuse texture if size and type matches

impeller/display_list/display_list_unittests.cc, impeller/entity/contents/filters/gaussian_blur_filter_contents.cc
The parameterization of the downsampling curve continues. The curve was already nonlinear -- this change just sets the approach value to 0.05. A 95% max downsample seems to be more or less the sweet spot. At some point we may want to make the curve sliiightly less aggressive and set the decay to maybe 4.5 or 5.0 as the downsample is still slightly noticeable towards the half way point of the curve. I'll leave that as an exercise for another day.
https://user-images.githubusercontent.com/919017/201461622-1cd7a7df-e21c-4e8f-9837-1f202aca4715.mov
Before:
After:
The reason for the background weirdness in the after image is a bug with cover geometry I just found and will fix shortly.
=> [Impeller] Add a limit to the Gaussian blur downsampling curve

impeller/aiks/aiks_unittests.cc, impeller/entity/contents/clip_contents.cc, impeller/entity/contents/linear_gradient_contents.cc, impeller/entity/contents/radial_gradient_contents.cc, impeller/entity/contents/runtime_effect_contents.cc, impeller/entity/contents/solid_color_contents.cc, impeller/entity/contents/sweep_gradient_contents.cc, impeller/entity/contents/tiled_texture_contents.cc, impeller/entity/contents/vertices_contents.cc, impeller/entity/geometry.cc, impeller/entity/geometry.h
* Gives the responsibility of building the vertex transform to Geometry.
* Fix an issue where the entity transform is getting applied for cover geometry instead of always covering the whole render target.
* Enables more optimizations in the future revolving around GPU geometry reuse.
Before:
After:
(This is also visible in a few other playgrounds.)
=> [Impeller] Fix DrawPaint regression

shell/platform/darwin/macos/framework/Source/FlutterViewController.mm, shell/platform/darwin/macos/framework/Source/FlutterViewControllerTest.mm
In macOS Ventura, the momentum end event is received before the `touchesBegan:`, so the old method doesn't function. Now we store the time of momentum change events and check upon `touchesBegan:` if one happened recently, this will handle both Ventura and older macOS versions. It also handles an issue seen in low power mode where the event sequence was different.
Fixes [#112333](https://github.com/flutter/flutter/issues/112333)
=> Fix inertia cancel event on macOS Ventura

impeller/entity/contents/runtime_effect_contents.cc
Otherwise a sampler uniform early in the uniforms list will cause all subsequent float uniforms to be off by one.
Fixes https://github.com/flutter/flutter/issues/115246
=> [Impeller] dont include sampler offset in float offset

impeller/aiks/aiks_unittests.cc, impeller/aiks/canvas.cc, impeller/display_list/display_list_unittests.cc
My intention with this test was to repro https://github.com/flutter/flutter/issues/114184, but this also demonstrates other known fidelity problems:
* The top two RRects (using the Color ColorSource) are rendering correctly.
* The bottom two are supposed to both be blurred linear gradients.
=> [Impeller] Add playground to demonstrate mask blur + color source application problems

shell/platform/darwin/macos/framework/Source/FlutterEngine.mm, shell/platform/darwin/macos/framework/Source/FlutterEngineTest.mm
Move the macOS embedder to use the new update semantics embedder API introduced by https://github.com/flutter/engine/pull/37129.
Part of https://github.com/flutter/flutter/issues/114201 …
=> [macOS] Move to new update semantics embedder API

shell/common/vsync_waiter.cc, shell/common/vsync_waiter_fallback.cc, shell/platform/android/vsync_waiter_android.cc, shell/platform/darwin/ios/framework/Source/vsync_waiter_ios.mm
Reverts flutter/engine#36775
Caused https://github.com/flutter/flutter/issues/115161
=> Revert "Fix wrong `VSYNC` event"

lib/web_ui/lib/src/engine/assets.dart, lib/web_ui/lib/src/engine/browser_detection.dart, lib/web_ui/lib/src/engine/canvaskit/canvas.dart, lib/web_ui/lib/src/engine/canvaskit/canvaskit_api.dart, lib/web_ui/lib/src/engine/canvaskit/image.dart, lib/web_ui/lib/src/engine/canvaskit/image_wasm_codecs.dart, lib/web_ui/lib/src/engine/canvaskit/image_web_codecs.dart, lib/web_ui/lib/src/engine/canvaskit/surface.dart, lib/web_ui/lib/src/engine/canvaskit/text.dart, lib/web_ui/lib/src/engine/canvaskit/util.dart, lib/web_ui/lib/src/engine/configuration.dart, lib/web_ui/lib/src/engine/dom.dart, lib/web_ui/lib/src/engine/embedder.dart, lib/web_ui/lib/src/engine/html/scene.dart, lib/web_ui/lib/src/engine/html/surface_stats.dart, lib/web_ui/lib/src/engine/html_image_codec.dart, lib/web_ui/lib/src/engine/keyboard_binding.dart, lib/web_ui/lib/src/engine/picture.dart, lib/web_ui/lib/src/engine/platform_dispatcher.dart, lib/web_ui/lib/src/engine/pointer_binding.dart, lib/web_ui/lib/src/engine/safe_browser_api.dart, lib/web_ui/lib/src/engine/semantics/scrollable.dart, lib/web_ui/lib/src/engine/text/font_collection.dart, lib/web_ui/lib/src/engine/text/line_breaker.dart, lib/web_ui/lib/src/engine/text/measurement.dart, lib/web_ui/lib/src/engine/text/ruler.dart, lib/web_ui/lib/src/engine/text_editing/text_editing.dart, lib/web_ui/lib/src/engine/window.dart, lib/web_ui/test/engine/surface/scene_builder_test.dart, lib/web_ui/test/engine/surface/surface_test.dart
While ints can flow to JS on all backends, Dart2Wasm does not currently support returning ints from JS. The reason is because there is really no way to support this in the general case. This CL does not change any public APIs, but rather instead we introduce tiny trampolines to handle the conversion.
=> [web] Avoid returning `int` from js interop classes.

lib/ui/painting/image_filter.cc, testing/dart/canvas_test.dart
When constructing the `DlColorFilterImageFilter`, it doesn't tolerate nullptr. But if Skia decides the color filter is a no-op, we're giving it nullptr.
It might be useful to have something in DL to signify no-op, or otherwise optimize these away, but it's probably a micro-optimization if anything and we should at least avoid crashing.
fixes https://github.com/flutter/flutter/issues/115143
=> Avoid segfault when converting no-op ColorFilter to ImageFilter

build/archives/BUILD.gn, common/config.gni, tools/gn
This is required to enable engine_v2 recipes for windows platform. …
=> Archive windows gen_snapshot.exe.

impeller/aiks/canvas.cc, impeller/aiks/paint.h, impeller/display_list/display_list_dispatcher.cc
Resolves https://github.com/flutter/flutter/issues/114184.
~~This also reveals a different bug: It appears that the fast BorderMaskBlur filter is being used instead of the regular Gaussian blur.~~ ~~I think this is also a regression but there hasn't been a playground that reproduces it until now.~~ 
Actually, this isn't a regression -- we always apply the BorderMaskBlur filter for non-solid color sources. This is correct behavior for images, but I need to check over how Skia behaves with the rest of the color sources now that they're all mostly implemented.
Before
After
=> [Impeller] Only apply the rrect blur fast path for solid Colors

lib/web_ui/lib/src/engine/assets.dart, lib/web_ui/lib/src/engine/browser_detection.dart, lib/web_ui/lib/src/engine/canvaskit/canvas.dart, lib/web_ui/lib/src/engine/canvaskit/canvaskit_api.dart, lib/web_ui/lib/src/engine/canvaskit/image.dart, lib/web_ui/lib/src/engine/canvaskit/image_wasm_codecs.dart, lib/web_ui/lib/src/engine/canvaskit/image_web_codecs.dart, lib/web_ui/lib/src/engine/canvaskit/surface.dart, lib/web_ui/lib/src/engine/canvaskit/text.dart, lib/web_ui/lib/src/engine/canvaskit/util.dart, lib/web_ui/lib/src/engine/configuration.dart, lib/web_ui/lib/src/engine/dom.dart, lib/web_ui/lib/src/engine/embedder.dart, lib/web_ui/lib/src/engine/html/scene.dart, lib/web_ui/lib/src/engine/html/surface_stats.dart, lib/web_ui/lib/src/engine/html_image_codec.dart, lib/web_ui/lib/src/engine/keyboard_binding.dart, lib/web_ui/lib/src/engine/picture.dart, lib/web_ui/lib/src/engine/platform_dispatcher.dart, lib/web_ui/lib/src/engine/pointer_binding.dart, lib/web_ui/lib/src/engine/safe_browser_api.dart, lib/web_ui/lib/src/engine/semantics/scrollable.dart, lib/web_ui/lib/src/engine/text/font_collection.dart, lib/web_ui/lib/src/engine/text/line_breaker.dart, lib/web_ui/lib/src/engine/text/measurement.dart, lib/web_ui/lib/src/engine/text/ruler.dart, lib/web_ui/lib/src/engine/text_editing/text_editing.dart, lib/web_ui/lib/src/engine/window.dart, lib/web_ui/test/engine/surface/scene_builder_test.dart, lib/web_ui/test/engine/surface/surface_test.dart
Reverts flutter/engine#37336
Breaks web engine tests
=> Revert "[web] Avoid returning `int` from js interop classes."

lib/web_ui/dev/steps/run_tests_step.dart, lib/web_ui/test/canvaskit/canvaskit_api_test.dart, lib/web_ui/test/canvaskit/fragment_program_test.dart, lib/web_ui/test/canvaskit/path_test.dart, lib/web_ui/test/canvaskit/surface_test.dart, lib/web_ui/test/text_editing_test.dart
Combines the results of all test batches into one result.
We have a bug where only the last batch results are counted. …
=> Combine results of all the test batches.

shell/platform/darwin/macos/framework/Source/FlutterEngineTest.mm
Reorders the native callback registration before the engine is run. If the callback is registered after the engine runs then there is a race.
Fixes https://github.com/flutter/flutter/issues/115245#issuecomment-1314406399 …
=> Register native callback before running engine.

ci/builders/windows_android_aot_engine.json
This enables archives generation of gen_snapshot for windows AOT. …
=> Add archives to android aot engine.

impeller/compiler/compiler.cc, impeller/compiler/compiler_test.cc, impeller/compiler/compiler_test.h, impeller/compiler/compiler_unittests.cc, impeller/compiler/impellerc_main.cc, impeller/compiler/switches.cc, impeller/compiler/switches.h, impeller/compiler/switches_unittests.cc, impeller/compiler/types.cc, impeller/compiler/types.h, impeller/fixtures/BUILD.gn, impeller/fixtures/multiple_stages.hlsl
Allows for multiple stages to be defined in one HLSL shader.
=> [Impeller] Add ability to set the entry-point name for HLSL shaders

lib/web_ui/dev/steps/run_tests_step.dart
We're having some periodic flakes of this part of the test suite on the Safari webdriver only. I suspect it has to do with only having a single unit test in the suite, but I'm not positive. Let's just disable this for now, I filed a follow-on issue for deeper investigation later: https://github.com/flutter/flutter/issues/115312
=> Skip the skwasm unit test suite on Safari since it is flaky.

.ci.yaml
Reducing the number of mac releaase builder builds, since we do not have enough capacity to process all the builds.
Bug:b/232552448
- [] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on writing and running engine tests. …
=> Removing some builds from mac release builder.

testing/dart/compositing_test.dart
Fixes a relatively benign bug in a unit test that relies on overly conservative bounds checking in Skia. As we move to more accurate bounds culling tests this unit test will fail to have its Scene painted at all since the bounds of the scene are outside the image space. These changes now request an image that actually contains the scene.
=> update Scene.toImageSync test to use proper bounds in the request

lib/web_ui/test/text_editing_test.dart
This fixes the text editing tests that regressed as a result of test results not being reported properly.
Partially addresses https://github.com/flutter/flutter/issues/115327
[breaking …
=> [web] Update text editing test skips

.ci.yaml
The osx_sdk version isn't getting propagated to the sub-builds, so adding a property to pass it in.
Bug:b/232552448 …
=> Adding sdk_version to mac builds for dart-internal.

shell/common/shell_io_manager.cc
A few PRs have been running into this failing lint check. For example: https://github.com/flutter/engine/pull/37656
=> Fix lingering linter error

ci/licenses_golden/licenses_flutter, impeller/aiks/BUILD.gn, impeller/aiks/aiks_unittests.cc, impeller/aiks/canvas.cc, impeller/aiks/canvas.h, impeller/aiks/color_source_factory.cc, impeller/aiks/color_source_factory.h, impeller/aiks/paint.cc, impeller/aiks/paint.h, impeller/display_list/BUILD.gn, impeller/display_list/conversion_utilities.cc, impeller/display_list/conversion_utilities.h, impeller/display_list/display_list_color_source_factory.cc, impeller/display_list/display_list_color_source_factory.h, impeller/display_list/display_list_dispatcher.cc
This couples the type enum and resolution logic for color sources into explicit factories with the intention of making ColorSource-related bugs easier to avoid.
* Wrap DL color sources without Aiks->DisplayList dependencies.
* Removes some redundant checks in Aiks.
* Makes `setColorSource` fanout easier to navigate.
=> [Impeller] Refactor ColorSource resolution to use explicit factory types

lib/web_ui/dev/analyze.dart, lib/web_ui/dev/felt, lib/web_ui/dev/felt.bat, lib/web_ui/dev/felt.dart, lib/web_ui/dev/steps/compile_tests_step.dart, lib/web_ui/dev/steps/run_tests_step.dart, lib/web_ui/test/canvaskit/canvaskit_api_test.dart, lib/web_ui/test/canvaskit/fragment_program_test.dart, lib/web_ui/test/canvaskit/path_test.dart, lib/web_ui/test/canvaskit/surface_test.dart, lib/web_ui/test/text_editing_test.dart, tools/clang_tidy/lib/clang_tidy.dart, tools/clang_tidy/lib/src/options.dart, tools/clang_tidy/test/clang_tidy_test.dart
CP: 583c71ce495a692ca803599b12d41e7dcf2c35de
CP: de0b58e827742e3ddea7b36d49a8f6a3678ef90a
CP: 3a622e17ad66af5bb77a96c87c58ebadabbac036
CP: f48be34914251d26e04f474df26669db9766ceda
CP: 12dabe83da199276844dc6961e9cba54ae97a59a
CP: 6563c5843174bc1135d767412d6ca72da5a42d0b
CP: 31ee286845155a5d6f754406eaba27a7c4553aba …
=> Clang tidy and web engine cherrypicks

ci/licenses_golden/licenses_flutter, impeller/aiks/BUILD.gn, impeller/aiks/aiks_unittests.cc, impeller/aiks/canvas.cc, impeller/aiks/canvas.h, impeller/aiks/color_source_factory.cc, impeller/aiks/color_source_factory.h, impeller/aiks/paint.cc, impeller/aiks/paint.h, impeller/display_list/BUILD.gn, impeller/display_list/conversion_utilities.cc, impeller/display_list/conversion_utilities.h, impeller/display_list/display_list_color_source_factory.cc, impeller/display_list/display_list_color_source_factory.h, impeller/display_list/display_list_dispatcher.cc, impeller/display_list/display_list_unittests.cc
This reverts commit d721647766ddf697d26f05f4ac56d4142ef77742.
Relands https://github.com/flutter/engine/pull/37656, but with with a missing null check (reverted in https://github.com/flutter/engine/pull/37673)
=> [Impeller] Reland: Refactor color source resolution to use explicit factory types

flow/layers/backdrop_filter_layer_unittests.cc
SkImageFilters::Paint() is deprecated and will be removed in https://skia-review.googlesource.com/c/skia/+/604917.
These unit tests are the last known usage of ::Paint(), but since they are just solid colors, the migration is very straightforward to switch to SkShader::Color().
https://bugs.chromium.org/p/skia/issues/detail?id=13927 …
=> Use SkImageFilters::Shader instead of ::Paint

shell/platform/embedder/embedder.cc, shell/platform/embedder/fixtures/main.dart, shell/platform/embedder/tests/embedder_a11y_unittests.cc
[PR #37192](https://github.com/flutter/engine/pull/37129) accidentally removed the tooltip property when creating `FlutterSemanticsNode` in the embedder. This PR adds it back so that tooltips are again used by a11y. …
=> Add back tooltip to Embedder

impeller/renderer/backend/vulkan/command_buffer_vk.cc, lib/ui/painting/image_decoder_impeller.cc, shell/platform/android/android_surface_vulkan_impeller.cc, shell/platform/android/android_surface_vulkan_impeller.h
1. When context is null, this is unlikely.
2. When one of the components obtained from context are null, e.g, blit-pass, command-buffer, etc.
=> Fix potential null-pointer de-references

.ci.yaml
Windows engine_v2 are now generating the expected artifacts and ready to be moved to the production environment. …
=> Move windows engine_v2 to prod.

lib/web_ui/README.md, lib/web_ui/dev/browser_lock.yaml, lib/web_ui/dev/browser_roller.dart, lib/web_ui/dev/chrome.dart, lib/web_ui/dev/firefox.dart
Engine-side piece for https://github.com/flutter/flutter/issues/115404
[Discord]: …
=> Roll Firefox to CIPD with `dev/browser_roller.dart`

tools/const_finder/test/fixtures/.dart_tool/package_config.json, tools/const_finder/test/fixtures/lib/box.dart, tools/const_finder/test/fixtures/lib/consts.dart, tools/const_finder/test/fixtures/lib/consts_and_non.dart, tools/const_finder/test/fixtures/lib/target.dart
Migrate const_finder tests to be null safe.
=> Migrate const_finder tests to be null safe

impeller/renderer/backend/vulkan/allocator_vk.cc, impeller/renderer/backend/vulkan/formats_vk.h
Fixes https://github.com/flutter/flutter/issues/115461
=> [Impeller] Fix glyph atlas uploads and renders

lib/ui/painting.dart
TLDR: `Shader` (oops) to `ui.FragmentShader`. I tested this by patching the docs changes into flutter/flutter and manually running the failing test:
```
jonahwilliams-macbookpro3:flutter jonahwilliams$ dart --enable-asserts dev/bots/analyze_snippet_code.dart --verbose
Found 0 snippet code errors.
```
=> [ui] reland add docs to FragmentShader

lib/web_ui/lib/src/engine/safe_browser_api.dart, lib/web_ui/lib/src/engine/text/font_collection.dart
support or IE11 and old Edge has been removed. Removed FontFace Polyfills as well 
fixes: https://github.com/flutter/flutter/issues/115013
=> delete fontface polyfill

runtime/runtime_controller.cc, runtime/runtime_controller.h, shell/common/engine.cc, shell/common/engine.h, shell/common/fixtures/shell_test.dart, shell/common/shell.cc, shell/common/shell_unittests.cc
Add call to Dart_NotifyDestroyed when the flutter view is destroyed.
=> Add call to Dart_NotifyDestroyed when the flutter view is destroyed.

.clang-tidy, display_list/display_list_image_filter_unittests.cc, flow/raster_cache_unittests.cc, shell/platform/embedder/tests/embedder_unittests.cc
Turn on `google-readability-avoid-underscore-in-googletest-name` clang-tidy warning and fix violations.
https://google.github.io/googletest/faq.html#why-should-test-suite-names-and-test-names-not-contain-underscore
Example:
```
/b/s/w/ir/cache/builder/src/flutter/shell/platform/embedder/tests/embedder_unittests.cc:1641:1: error: avoid using "_" in test name "SoftwareRenderingPixelFormats_draw_solid_red_kRGB565" according to Googletest FAQ [google-readability-avoid-underscore-in-googletest-name,-warnings-as-errors]
SW_PIXFMT_TEST_F(draw_solid_red, kRGB565, (uint16_t)0xF800);
^
/b/s/w/ir/cache/builder/src/flutter/shell/platform/embedder/tests/embedder_unittests.cc:1634:10: note: expanded from macro 'SW_PIXFMT_TEST_F'
SoftwareRenderingPixelFormats_##dart_entrypoint##_##pixfmt) {    \
^
note: …
```
=> Turn on clang tidy error for underscores in Google tests

shell/platform/embedder/embedder_exports.lst, testing/symbols/verify_exported.dart
Fixes https://github.com/flutter/flutter/issues/114657
=> Add semantics constants to the exported symbols list for the embedder library

impeller/typographer/backends/skia/text_render_context_skia.cc, impeller/typographer/typographer_unittests.cc
Reverts flutter/engine#37527
Fixes https://github.com/flutter/flutter/issues/115580
=> Revert "[Impeller] reuse texture if size and type matches"

vulkan/procs/vulkan_interface.h
Eliminates an undef of VK_USE_PLATFORM_METAL_EXT that works around some unguarded `@available` checks for macOS 10.13. Our minimum macOS SDK is now macOS 10.14 so we can safely assume Metal support since it's a requirement for macOS 10.14.
No test changes since this should only affect the graphics backend used in tests; the tests themselves should be the same regardless of which backend is in use.
Issue: https://github.com/flutter/flutter/issues/114445
[C++, …
=> [macOS] Eliminate Vulkan hack for macOS < 10.14

.clang-tidy, tools/clang_tidy/lib/src/command.dart, tools/clang_tidy/test/clang_tidy_test.dart
`lint.sh` was running `clang-tidy` but only failing on the warnings explicitly treated as errors.  That means it was running more checks than it was reporting, but not giving any additional information.
Treat all clang-tidy warnings as errors.  This will also prevent checks being added that aren't _really_ being reported. 
Remove `performance-move-const-arg` and `performance-unnecessary-value-param` checks because they produce errors that were never surfaced and would need to be fixed before these checks are re-added.
It looks like this improved `Mac Host clang-tidy` time, but the rest are about the same.
- [Linux Android clang-tidy](https://ci.chromium.org/p/flutter/builders/try/Linux%20Android%20clang-tidy)
- [Linux Host clang-tidy](https://ci.chromium.org/p/flutter/builders/try/Linux%20 …
=> Only run clang-tidy warning checks reported as errors

shell/platform/darwin/macos/framework/Source/FlutterCompositorUnittests.mm, shell/platform/darwin/macos/framework/Source/FlutterSurfaceManagerTest.mm
Removes a few unncessary references to Metal in the macOS embedder. Now that Metal is the only supported rendering implementation for the macOS embedder, specifying a class as a Metal variant is redundant.
Issue: https://github.com/flutter/flutter/issues/108304
Issue: https://github.com/flutter/flutter/issues/114445 …
=> [macOS] Cleanup unnecessary references to Metal

lib/web_ui/lib/src/engine/canvaskit/path_metrics.dart, lib/web_ui/test/canvaskit/path_test.dart
This fixes the Path tests that regressed as a result of test results not being reported properly.
The test for checking that `metrics.toList()` can be called multiple times is invalid because according to the [docs](https://api.flutter.dev/flutter/dart-ui/PathMetrics-class.html): "This iterable does not memoize. Callers who need to traverse the list multiple times, or who need to randomly access elements of the list, should use [toList](https://api.flutter.dev/flutter/dart-core/Iterable/toList.html) on this object."
Partially addresses https://github.com/flutter/flutter/issues/115327 …
=> [canvaskit] Fix Path tests

impeller/renderer/backend/vulkan/allocator_vk.cc, impeller/renderer/backend/vulkan/allocator_vk.h, impeller/renderer/backend/vulkan/device_buffer_vk.cc, impeller/renderer/backend/vulkan/device_buffer_vk.h, impeller/renderer/backend/vulkan/render_pass_vk.cc, impeller/renderer/backend/vulkan/render_pass_vk.h, impeller/renderer/backend/vulkan/texture_vk.cc, impeller/renderer/backend/vulkan/texture_vk.h
Upload to staging buffer and then copy the buffer to texture, this ensure that tiling is respected and the image is shown as intended, without this change the image would be shown as random chunks.
=> [Impeller] Fix texture upload pipeline in Vulkan

lib/ui/painting/multi_frame_codec.cc
Fixes https://github.com/flutter/flutter/issues/113014
=> Do not abort if a MultiFrameCodec is unable to allocate a bitmap buffer

shell/platform/fuchsia/flutter/flatland_external_view_embedder.cc, shell/platform/fuchsia/flutter/flatland_external_view_embedder.h, shell/platform/fuchsia/flutter/tests/fakes/scenic/fake_flatland.cc, shell/platform/fuchsia/flutter/tests/fakes/scenic/fake_flatland_types.cc, shell/platform/fuchsia/flutter/tests/fakes/scenic/fake_flatland_types.h, shell/platform/fuchsia/flutter/tests/flatland_external_view_embedder_unittests.cc
This change enables the screen reader to interact with flutter overlays on flatland (PR #33852 made the same change for GFX).
fxbug.dev/104956 …
=> [fuchsia][a11y] Set explicit hit regions in flatland embedder

runtime/runtime_controller.cc, runtime/runtime_controller.h, shell/common/animator.cc, shell/common/animator.h, shell/common/animator_unittests.cc, shell/common/engine.cc, shell/common/engine.h, shell/common/engine_unittests.cc, shell/common/shell.cc, shell/common/shell.h, shell/common/shell_test.cc, shell/common/shell_test.h, shell/common/shell_unittests.cc
This patch also eliminates some extraneous tracing that is happening every frame. It is possible to get the same trace calls by enabling the API stream if needed.
Also refactors the NotifyIdle callsites to just always work in TimeDeltas rather than converting back and forth between them and TimePoints, which I think reads more clearly.
Also refactors the way the delayed task gets posted to hopefully be a little more safe/clear.
This patch does not "solve" the problem of when we call notify idle and then immediately start pumping frames, e.g. when we get a super cheap frame and then follow it up with a transition.
=> Make NotifyIdle reject close and past deadlines.

shell/platform/darwin/macos/framework/Source/FlutterTextInputPluginTest.mm, shell/platform/darwin/macos/framework/Source/FlutterTextInputSemanticsObject.mm, shell/platform/darwin/macos/framework/Source/FlutterTextInputSemanticsObjectTest.mm
The crash happens because there is a dangling pointer when the FlutterTextPlatformNode is deleted but the main event loop has a retain on the FlutterTextField.  I'm not sure how problematic this is in practice but it affected tests.
fixes https://github.com/flutter/flutter/issues/115599 …
=> Made FlutterTextField that outlive FlutterTextPlatformNode not crash

.ci.yaml
https://github.com/flutter/engine/pull/37658 put `Linux Web Engine` to `bringup: true`, and this results in the building not running in `try`.
Recipes CQ is based on latest `SUCCESS` try build, and unfortunately the latest old `SUCCESS` build regressed and is not passing (https://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/flutter-try-builder_chops-service-accounts.iam.gserviceaccount.com/c6142507bd4bf04bd0a33fb0b14b15d9c0e61dd4c3437765894d7e9405292a57/+/build.proto?server=chromium-swarm.appspot.com).
This PR skips the builder in CQ to unblock recipes workflow (https://flutter-review.git.corp.google.com/c/recipes/+/35962).
=> Remove `Linux Web Engine` from recipes CQ

impeller/compiler/shader_lib/impeller/transform.glsl, impeller/entity/contents/text_contents.cc, impeller/entity/shaders/glyph_atlas.frag, impeller/entity/shaders/glyph_atlas.vert, impeller/entity/shaders/glyph_atlas_sdf.frag, impeller/entity/shaders/glyph_atlas_sdf.vert, impeller/fixtures/struct_def_bug.vert, impeller/typographer/backends/skia/text_render_context_skia.cc
Fixes https://github.com/flutter/flutter/issues/114563.
* Rename overloaded terminology in the shaders (glyph, atlas glyph, glyph atlas, etc.. are now "source" and "destination").
* Add 2 pixels of padding for every glyph drawn to the atlas.
* Don't Ceil the source glyph size.
* Don't shift the source rect right/down by `1/atlas size`.
* Remove 0.5 from the start and end of the source and destination rects -- this gets nearest sampling to nearly work as expected. Remaining problems are detailed below.
There are two problems remaining:
* The reason we need linear sampling right now because we don't snap the source rect to the pixel grid of the destination framebuffer when drawing glyphs. This means the sampling range of each for each texel from the source image is `+/- 0.5 +/- epsilon^n`, …
=> [Impeller] Fix glyph sampling overlap

flutter_frontend_server/pubspec.yaml
The CL in [0] added package:ffi as dependency to package:compiler. Since flutter_frontend_server needs all dependencies as path dependencies, we need to add package:ffi there via path.
[0] https://dart-review.googlesource.com/c/sdk/+/269640
=> Add package:ffi as path dependency to flutter_frontend_server

shell/platform/darwin/ios/ios_surface_metal_impeller.mm
Fixes https://github.com/flutter/flutter/issues/115664
I copied these lines from the Skia implementation and verified that it fixes the issue. Is there some way to write a test?
=> [Impeller] Present Impeller contents in a transaction when there is a platform view

flow/layers/image_filter_layer.cc, flow/layers/image_filter_layer.h, flow/layers/image_filter_layer_unittests.cc, lib/ui/compositing.dart, lib/ui/compositing/scene_builder.cc, lib/ui/compositing/scene_builder.h, lib/web_ui/lib/compositing.dart, lib/web_ui/lib/src/engine/canvaskit/layer.dart, lib/web_ui/lib/src/engine/canvaskit/layer_scene_builder.dart, lib/web_ui/lib/src/engine/html/image_filter.dart, lib/web_ui/lib/src/engine/html/scene_builder.dart
Enables a fix in the framework that would address https://github.com/flutter/flutter/issues/111855
An offset parameter is added to the ImageFilterLayer so that the accumulated offset in `_ImageFilterRenderObject.paint` can paint the children with a zero offset.
This code is backwards compatible and will have no effect until the associated framework PR (https://github.com/flutter/flutter/pull/113673) is merged. This PR must merge before that PR can merge.
The fix has been verified locally using both PRs in conjunction.
=> Add optional offset parameter to ImageFilterLayer

shell/platform/darwin/macos/framework/Headers/FlutterDartProject.h, shell/platform/darwin/macos/framework/Headers/FlutterViewController.h, shell/platform/darwin/macos/framework/Source/FlutterEmbedderKeyResponder.mm, shell/platform/darwin/macos/framework/Source/FlutterKeyPrimaryResponder.h, shell/platform/darwin/macos/framework/Source/FlutterKeyboardManagerTest.mm, shell/platform/darwin/macos/framework/Source/FlutterTextInputPluginTest.mm
This adds explicit strong/copy Objective-C property annotations where they were previously implied on NSObject properties and fixes on case where it was previously improperly specified.
Issue: b/254864882
This corrects an annotation introduced in https://github.com/flutter/engine/pull/36929. …
=> [macOS] Add explicit weak/strong/copy annotations

shell/platform/linux/fl_key_embedder_responder.cc, shell/platform/linux/fl_key_embedder_responder.h, shell/platform/linux/fl_keyboard_manager.cc, shell/platform/linux/fl_keyboard_manager.h, shell/platform/linux/fl_keyboard_manager_test.cc, shell/platform/linux/fl_view.cc
This PR implements modifier keys states synchronization based on pointer events.
It is the Linux implemention for https://github.com/flutter/flutter/issues/115066.
https://github.com/flutter/flutter/issues/115066
Adds 1 test.
=> [Linux] Synthesize modifier keys events on pointer events

impeller/compiler/spirv_sksl.cc
This is a temporary fix to unblock the internal roll.
* This call has been deprecated in the upstream dep
* https://github.com/KhronosGroup/SPIRV-Cross/pull/2062
https://github.com/flutter/flutter/issues/115785
=> [impeller] Remove declare_undefined_values

lib/ui/dart_ui.cc, lib/ui/painting.dart, lib/ui/painting/fragment_shader.cc, lib/ui/painting/fragment_shader.h, lib/web_ui/lib/painting.dart, lib/web_ui/lib/src/engine/canvaskit/painting.dart, lib/web_ui/lib/src/engine/html/painting.dart
`setImageSampler` guarantees we don't need an additional texture/render pass per-sampler. It's possible for users to emulate the functionality of `setSampler` in-shader.
The intention is to do the following before the stable branch cut:
1. Land this and roll into the framework.
1. Migrate stuff in the framework from `setSampler` to `setImageSampler`.
1. Remove `setSampler`.
I filed https://github.com/flutter/flutter/issues/115794 along the way.
=> Add setImageSampler (for replacing setSampler)

impeller/compiler/spirv_sksl.cc
Reverts flutter/engine#37829
This breaks impellerc unless spirv-cross is also rolled forward.
=> Revert "[impeller] Remove declare_undefined_values"

lib/web_ui/lib/src/engine/assets.dart, lib/web_ui/lib/src/engine/browser_detection.dart, lib/web_ui/lib/src/engine/canvaskit/canvas.dart, lib/web_ui/lib/src/engine/canvaskit/canvaskit_api.dart, lib/web_ui/lib/src/engine/canvaskit/image.dart, lib/web_ui/lib/src/engine/canvaskit/image_wasm_codecs.dart, lib/web_ui/lib/src/engine/canvaskit/image_web_codecs.dart, lib/web_ui/lib/src/engine/canvaskit/surface.dart, lib/web_ui/lib/src/engine/canvaskit/text.dart, lib/web_ui/lib/src/engine/canvaskit/util.dart, lib/web_ui/lib/src/engine/configuration.dart, lib/web_ui/lib/src/engine/dom.dart, lib/web_ui/lib/src/engine/embedder.dart, lib/web_ui/lib/src/engine/html/scene.dart, lib/web_ui/lib/src/engine/html/surface_stats.dart, lib/web_ui/lib/src/engine/html_image_codec.dart, lib/web_ui/lib/src/engine/keyboard_binding.dart, lib/web_ui/lib/src/engine/picture.dart, lib/web_ui/lib/src/engine/platform_dispatcher.dart, lib/web_ui/lib/src/engine/pointer_binding.dart, lib/web_ui/lib/src/engine/safe_browser_api.dart, lib/web_ui/lib/src/engine/semantics/scrollable.dart, lib/web_ui/lib/src/engine/text/line_breaker.dart, lib/web_ui/lib/src/engine/text/measurement.dart, lib/web_ui/lib/src/engine/text/ruler.dart, lib/web_ui/lib/src/engine/text_editing/text_editing.dart, lib/web_ui/lib/src/engine/window.dart, lib/web_ui/test/canvaskit/image_golden_test.dart, lib/web_ui/test/engine/surface/scene_builder_test.dart, lib/web_ui/test/engine/surface/surface_test.dart
=> Reland "[web] Avoid returning int from js interop classes."

lib/ui/dart_ui.cc, lib/ui/painting.dart, lib/ui/painting/fragment_shader.cc, lib/ui/painting/fragment_shader.h, lib/web_ui/lib/painting.dart, lib/web_ui/lib/src/engine/canvaskit/painting.dart, lib/web_ui/lib/src/engine/html/painting.dart, testing/dart/fragment_shader_test.dart
Followup to https://github.com/flutter/engine/pull/37821.
I actually didn't find any setSampler usage in the framework, so just removing it before the engine roll finishes. 🤔 Am I missing anything?
=> Remove setSampler from FragmentShader

shell/platform/fuchsia/flutter/flatland_external_view_embedder.cc, shell/platform/fuchsia/flutter/flatland_external_view_embedder.h, shell/platform/fuchsia/flutter/tests/fakes/scenic/fake_flatland_types.h, shell/platform/fuchsia/flutter/tests/flatland_external_view_embedder_unittests.cc
This CL processes the clip nodes that might be a part of MutatorStack. We use the same strategy as Gfx code by adding parent transforms.
Bug: fxb/115348
=> [fuchsia] Set nested clip nodes for Flatland

shell/platform/darwin/macos/framework/Source/FlutterEngine.mm, shell/platform/darwin/macos/framework/Source/FlutterEngineTest.mm, shell/platform/darwin/macos/framework/Source/FlutterEngineTestUtils.h, shell/platform/darwin/macos/framework/Source/FlutterEngineTestUtils.mm, shell/platform/darwin/macos/framework/Source/fixtures/flutter_desktop_test.dart
issue: https://github.com/flutter/flutter/issues/93945
[Discord]: …
=> Made platform message responses thread-safe for macos.

.clang-tidy
Turn on checks:
- [objc-assert-equals](https://clang.llvm.org/extra/clang-tidy/checks/objc/assert-equals.html)
- [objc-avoid-nserror-init](https://clang.llvm.org/extra/clang-tidy/checks/objc/avoid-nserror-init.html)
- [objc-dealloc-in-category](https://clang.llvm.org/extra/clang-tidy/checks/objc/dealloc-in-category.html)
- [objc-forbidden-subclassing](https://clang.llvm.org/extra/clang-tidy/checks/objc/forbidden-subclassing.html)
- [objc-missing-hash](https://clang.llvm.org/extra/clang-tidy/checks/objc/missing-hash.html)
- [objc-nsdate-formatter](https://clang.llvm.org/extra/clang-tidy/checks/objc/nsdate-formatter.html)
- [objc-property-declaration](https://clang.llvm.org/extra/clang-tidy/checks/objc/property-declaration.html)
- [objc-super-self](https://clang.llvm.org/extra/clang-tidy/che …
=> Turn on objc-* clang-tidy checks

lib/web_ui/lib/src/engine/dom.dart, lib/web_ui/test/canvaskit/image_golden_test.dart
DomProgressEvent should have a non-synthetic constructor that accepts a String to match the MDN definition:
https://developer.mozilla.org/en-US/docs/Web/API/ProgressEvent/ProgressEvent. It should also have a JS name that points to ProgressEvent. Lastly, image_golden_test is modified to use the parameter values from before the static interop migration:
https://github.com/flutter/engine/blame/9cb49937575fa9b6774e9dc471ce638e151ccf47/lib/web_ui/test/canvaskit/image_golden_test.dart
Enables https://github.com/dart-lang/sdk/issues/49941
=> Fix DomProgressEvent constructor

lib/web_ui/lib/src/engine/dom.dart
I was exploring around this code when I found canvaskit variable names where they shouldn't be.
Rename `trustedCanvasKitUrl` => `trustedUrl`.
=> [web] Use generic variable name for trusted url

lib/web_ui/lib/src/engine/semantics/text_field.dart, lib/web_ui/test/engine/semantics/text_field_test.dart
Fixes https://github.com/flutter/flutter/issues/115099
=> Call focus on input after detecting a tap

lib/ui/painting/image_decoder_impeller.cc
fix https://github.com/flutter/flutter/issues/115907
=> [Impeller] Implement 'ui.decodeImageFromPixels'

shell/platform/fuchsia/flutter/engine.cc, shell/platform/fuchsia/flutter/flatland_connection.cc, shell/platform/fuchsia/flutter/flatland_external_view_embedder.cc, shell/platform/fuchsia/flutter/flatland_platform_view.cc
This CL just updates some Flatland bugs from the umbrella bug to more granular ones.
Bug: fxb/94000
=> [fuchsia] Update bug numbers

impeller/tools/build_metal_library.py, impeller/tools/impeller.gni
We used to add workarounds for https://github.com/flutter/flutter/issues/106066.
However, that issue has been resolved. But the workarounds made it so that unopt local engine builds would build inconsistent shaders. Also, the mac builds would specify the iOS as well mac shader standards to the compiler. The mac target also never got a min OS version.
The script has been cleaned up for readability.
=> [Impeller] Cleanup shader generation and specify min macOS version.

impeller/compiler/switches.cc
Part of a speculative fix I'm making for https://github.com/flutter/flutter/issues/115433. If the path is already absolute, don't convert again. probably does nothing. 🤷
=> [impellerc] speculative fix for include errors with impellerc shader lib

shell/platform/android/BUILD.gn
Embeds mac codesign metadata in android artifacts. TLDR: metadata is embedded at top level as opposed to attached to leaf nodes.
The metadata isn't attached to the leaf nodes of build rules, because of the different gen_snapshot_(host tool chain) variations. As pointed out by Zach, in engine v1, not all andriod snapshots are generated through android build rules. For example, windows android snapshots are copied to a common path `"$root_build_dir/gen_snapshot/gen_snapshot.exe"`, and used out of the android gn file. In engine v2, all android snapshots are generated via the shell/platform/android build rules, and therefore it is good to embed a top level metadata. Since we only care about mac codesign metadata, windows gen snapshot entry points might not be relevant.
=> [gn] embed mac codesign metadata in android artifacts

impeller/renderer/backend/vulkan/command_buffer_vk.cc, impeller/renderer/backend/vulkan/command_buffer_vk.h, impeller/renderer/backend/vulkan/context_vk.cc, impeller/renderer/backend/vulkan/context_vk.h, impeller/renderer/backend/vulkan/fenced_command_buffer_vk.cc, impeller/renderer/backend/vulkan/render_pass_vk.cc
This ensures that the command pool is not accessed from multiple threads at the same time. This fixes the validation errors:
```
Check failed: false. Error[337425955][UNASSIGNED-Threading-MultipleThreads] : Validation Error: [ UNASSIGNED-Threading-MultipleThreads ] Object 0: handle = 0x59ffe0000000003d, type = VK_OBJECT_TYPE_COMMAND_POOL; | MessageID = 0x141cb623 | THREADING ERROR : vkFreeCommandBuffers(): object of type VkCommandPool is simultaneously used in thread 471586061488 and thread 471275924656'
```
=> Create a unique command pool per render pass

ci/licenses_golden/licenses_flutter, impeller/playground/BUILD.gn, impeller/playground/backend/gles/playground_impl_gles.cc, impeller/playground/backend/metal/playground_impl_mtl.mm, impeller/playground/backend/vulkan/playground_impl_vk.cc, impeller/scene/BUILD.gn, impeller/scene/scene.cc, impeller/scene/scene.h, impeller/scene/scene_context.cc, impeller/scene/scene_context.h, impeller/scene/scene_unittests.cc, impeller/scene/shaders/BUILD.gn, impeller/scene/shaders/geometry.vert, impeller/scene/shaders/unlit.frag
Getting rolling on this again.
* Add an unlit shader
* Wire up the shader bundle in the playground for the playground
* Add a SceneContext that mirrors ContentContext because the pattern is great: If it ain't broke, don't fix it (also want to keep it kinda close for now to keep refactors for shader pipeline features mindless).
=> [Impeller Scene] Wire up pipelines

DEPS
We've added a dependency on `package:intl` in `package:dartdev`:
* https://github.com/dart-lang/sdk/commit/1dd71b412f585bbe0353bebaa44f65d6d938cd1e
`package:intl` was not being checked out in the Flutter DEPS file, causing the builds to fail.
This PR adds `package:intl` as DEPS in Flutter.
cc @devoncarew
=> [deps] Add `package:intl`

impeller/renderer/backend/gles/buffer_bindings_gles.cc
This showed up as a hotspot in profiles.
=> [Impeller] Remove use of stringstream in NormalizeUniformKey.

impeller/geometry/path.cc
This method was visible in profiles.
=> [Impeller] Performance improvement for Path::GetMinMaxCoveragePoints.

lib/web_ui/lib/src/engine/keyboard_binding.dart, lib/web_ui/test/keyboard_converter_test.dart
The macOS system has some different rules for keyboard:
1. macOS considers CapsLock key down event "enabling the lock", while CapsLock up "disabling the lock" - instead of the usual "pressing/releasing the key".
2. Command-LetterKey does not have a key up event. 
Web on macOS already has special rules to handle them.
However, we recently realized that iOS has the same rules. This PR applies these rules to Web on iOS as well.
This PR also fixes a test that incorrectly uses `OperatingSystem.linux` to test key guarding. …
=> [Keyboard] Enable special CapsLock handling and key guarding for Web on iOS

DEPS
Roll https://github.com/flutter/buildroot/pull/652
Fixes https://github.com/flutter/flutter/issues/112928 …
=> Roll buildroot to prevent excessive dirtying on Xcode 14

shell/platform/embedder/embedder_external_view_embedder.h
Fixes a one character typo spotted in the doc comment for the avoid_backing_store_cache parameter to the EmbedderExternalViewEmbedder ctor.
Spotted during a code review. …
=> Fix typo on avoid_backing_store_cache param doc

ci/licenses_golden/licenses_flutter, shell/platform/windows/BUILD.gn, shell/platform/windows/cursor_handler.cc, shell/platform/windows/cursor_handler.h, shell/platform/windows/cursor_handler_unittests.cc, shell/platform/windows/flutter_window.cc, shell/platform/windows/flutter_window.h, shell/platform/windows/testing/mock_window_binding_handler.h, shell/platform/windows/window_binding_handler.h
This PR adds an additional interface to set custom cursor on windows, which fixes issues mentioned below.
Currently,  Customizing `MouseCursor` on windows is not working, the customed mouse will restore to arrow once it moves. See https://github.com/flutter/flutter/issues/31952#issuecomment-1056115014 
https://github.com/flutter/flutter/issues/99484
for details. Variable `current_cursor_` in `cursor handler` will not update when we set our custom cursors, and we cannot change this field to prevent the cursor from restoring due to lacking of interface.
The reason is that cursor handler on windows has no interface to change current cursor to custom cursor, only support setting windows self-contained icons.  
Changes:
- add new function handled by method channel of …
=> feat: add custom cursor interface on windows

shell/platform/android/android_egl_surface.cc
*This PR fixes the issues with glitches on old TV devices.*
[*Glitches when scrolling on weak Android TV devices.*](https://github.com/flutter/flutter/issues/113314) …
=> Remove glitches when scrolling on old Android TV devices

shell/platform/linux/fl_binary_messenger.cc, shell/platform/linux/fl_binary_messenger_private.h, shell/platform/linux/fl_binary_messenger_test.cc, shell/platform/linux/fl_engine.cc, shell/platform/linux/public/flutter_linux/fl_binary_messenger.h
This makes it so platform channel messages can be responded to from any thread.  Most of the work has already been implemented under the hood.  This had to add support for the linux embedder.  The important thing is that this switched the BinaryMessenger's weak reference to the engine to a GWeakRef which is thread-safe.  This guarantees that the engine is not deleted while we are using it to dispatch the response to the ui thread.
issue: https://github.com/flutter/flutter/issues/93945 …
=> Made responses to platform methods threadsafe in linux

.ci.yaml, lib/web_ui/dev/browser_lock.yaml
Rolls the Firefox version used in tests to 106.0. This is an upgrade from the ancient 83.0.
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-ch …
=> [web] Update Firefox to 106.0

impeller/entity/contents/text_contents.cc, impeller/typographer/backends/skia/text_frame_skia.cc, impeller/typographer/backends/skia/text_render_context_skia.cc, impeller/typographer/font.h, impeller/typographer/glyph.h, impeller/typographer/text_frame.cc, impeller/typographer/typographer_unittests.cc
...with individual glyph bounds.
Before:
1024 x 1024
After:
512 x 512
=> [Impeller] Pack 👏 the 👏 atlas 👏

.ci.yaml
Downloads EMSDK for the host builders.
[Discord]: …
=> Download EMSDK for host builders to build wasm_release

lib/web_ui/README.md
We don't do Dart snapshots anymore (since https://github.com/flutter/engine/pull/37639).
=> [web] Remove outdated information in web_ui/README

shell/common/animator.cc
Animation::Render -> Animator::Render. Spotted during some code archaeology during a review.
No test change there's no functional change. …
=> Fix typo in Animator comment

lib/web_ui/test/canvaskit/canvaskit_api_test.dart, lib/web_ui/test/canvaskit/fragment_program_test.dart
This fixes the fragment shader tests that regressed as a result of test results not being reported properly.
`skip: !isRuntimeEffectAvailable` doesn't work here because even when it *is* available (when running against a locally-built CanvasKit), the test is skipped anyway. I suspect that the skip checks are done before CanvasKit is initialized.
Partially addresses https://github.com/flutter/flutter/issues/115327 …
=> [canvaskit] Fix Shader program tests

lib/web_ui/test/canvaskit/surface_test.dart
This fixes the Path tests that regressed as a result of test results not being reported properly.
Partially addresses https://github.com/flutter/flutter/issues/115327 …
=> [canvaskit] Fix Surface test

flow/layers/display_list_raster_cache_item.cc, lib/ui/compositing.dart, lib/ui/geometry.dart, lib/ui/painting.dart, lib/web_ui/lib/canvas.dart, lib/web_ui/lib/src/engine/html/render_vertices.dart, testing/dart/BUILD.gn, testing/dart/compositing_test.dart, testing/dart/painting_test.dart, testing/dart/path_test.dart
* Remove nonsensical (and I think unnecessary?) comment.
* Document willChangeHint, isComplexHint
* Fix grammer in Rect docs
* Remove runtimeType.toString twice
* Add detail to ImageShader constructor docs.
* Document Vertices and drawVertices!
* Update checks in Vertices constructors (and add tests).
* Fix some typos.
* Minor other doc improvements.
* Fold in @jonahwilliams' performance improvement from https://github.com/flutter/engine/pull/38041
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#styl …
=> Documentation and other cleanup in dart:ui, plus a small performance improvement

lib/web_ui/lib/src/engine/initialization.dart, lib/web_ui/lib/src/engine/semantics/accessibility.dart, lib/web_ui/test/engine/semantics/accessibility_test.dart
Use permanent live regions for a11y announcements because NVDA and JAWS do not interpret newly created elements as a content change. Instead, they prefer to see an existing live region change content over time.
Fixes https://github.com/flutter/flutter/issues/116364
=> [web] use a permanent live region for a11y announcements

shell/gpu/gpu_surface_metal_delegate.h, shell/gpu/gpu_surface_metal_skia.mm, shell/platform/embedder/embedder.cc, shell/platform/embedder/fixtures/main.dart, shell/platform/embedder/tests/embedder_test_context_metal.cc, shell/platform/embedder/tests/embedder_test_context_metal.h, shell/platform/embedder/tests/embedder_unittests_metal.mm
This ensures `FlutterMetalTexture.destruction_callback` gets called.
`FlutterRendererConfig.get_next_drawable_callback` holds a callback used by the embedder API to request a drawable; in the case of Metal, this drawable is a FlutterMetalTexture.
`FlutterMetalTexture.destruction_callback` should be called when it's safe to release resources associated with the `FlutterMetalTexture`. This callback is not currently invoked for textures returned via `FlutterRendererConfig.get_next_drawable_callback`; instead we unpack the returned struct and pass it on.
In the compositor codepath, we do create an `SkSurface` that triggers the destruction callback, here:
https://github.com/flutter/engine/blob/303e26e96561d9b76f2344e97a5fc32eb6dfdb9a/shell/platform/embedder/embedder.cc#L868-L881
Issue: …
=> [embedder] Ensure FlutterMetalTexture cleanup call

impeller/geometry/geometry_unittests.cc, impeller/geometry/matrix.h, impeller/renderer/renderer_unittests.cc
=> [Impeller] Make perspective transform resolve to left handed clip space

impeller/scene/camera.cc, impeller/scene/camera.h, impeller/scene/scene.cc, impeller/scene/scene_encoder.cc, impeller/scene/scene_encoder.h, impeller/scene/scene_entity.cc, impeller/scene/scene_entity.h, impeller/scene/scene_unittests.cc, impeller/scene/static_mesh_entity.cc, impeller/scene/static_mesh_entity.h
It ain't much yet, but it's something!
=> [Impeller Scene] Wire up camera

shell/platform/windows/flutter_windows_engine.cc, shell/platform/windows/flutter_windows_engine.h, shell/platform/windows/flutter_windows_view.cc, shell/platform/windows/flutter_windows_view.h, shell/platform/windows/platform_handler.cc, shell/platform/windows/platform_handler.h, shell/platform/windows/platform_handler_unittests.cc
The Windows `PlatformHandler` is a singleton, however, it is owned by the view. This makes the `PlatformHandler` owned by the engine to prepare for a multi-view world. …
=> [Windows] Make the engine own the `PlatformHandler`

impeller/compiler/switches.cc
Also, resolve the source language before attempting to open the directory, to prevent the source language error message from showing up incorrectly.
=> [ImpellerC] Print the working directory that was tried when failing to open

DEPS, ci/licenses_golden/licenses_third_party, impeller/playground/widgets.h
The GLFW backend in the ImGui docking branch relies on `glfwGetMonitorWorkarea`, which was introduced later than the hash we're running. I tried to perform this GLFW upgrade earlier when I first added ImGui as a test dependency, but ran into some trouble. Things seem to be going more smoothly this time, but we'll see if I can get it passing on all targets. 🤷‍♂️
=> Update glfw to head and imgui to the docking branch

testing/xvfb.py
See https://github.com/flutter/flutter/issues/116130
=> Disable an extension in Xvfb to work around errors seen when running Impeller/Vulkan unit tests

shell/platform/android/test_runner/build.gradle
Add gradle options to enable showing `System.out.println` statements in android java tests. 
This helps with debugging and an audit of existing usages shows that it will not increase logspam. 
"message 2" 
This is a mitigation for https://github.com/flutter/flutter/issues/116603  …
=> Add gradle option to allow/show System.out.print logs

lib/web_ui/test/canvaskit/canvas_golden_test.dart
Triaging https://github.com/flutter/flutter/issues/93257 I couldn't reproduce the issue. It looks like zero font size was fixed. I couldn't find a test for it, so adding a test in this PR.
=> [web:canvaskit] test zero font size

lib/web_ui/pubspec.yaml
Other web_ui package dependences are incompatible with analyzer-5.3.0
=> Pin the analyzer package version in lib/web_ui

impeller/fixtures/BUILD.gn, impeller/scene/BUILD.gn, impeller/scene/geometry.cc, impeller/scene/geometry.h, impeller/scene/importer/importer_gltf.cc, impeller/scene/importer/importer_unittests.cc, impeller/scene/importer/scene.fbs, impeller/scene/importer/scenec_main.cc, impeller/scene/scene_unittests.cc, impeller/scene/shaders/geometry.vert, impeller/scene/shaders/unlit.frag, impeller/tools/impeller.gni
=> [Impeller Scene] Render imported meshes

lib/web_ui/lib/src/engine/semantics/accessibility.dart, lib/web_ui/lib/src/engine/semantics/live_region.dart, lib/web_ui/test/engine/semantics/semantics_test.dart
=> Use announce function in live region

shell/platform/darwin/ios/framework/Source/FlutterSpellCheckPlugin.mm, shell/platform/darwin/ios/framework/Source/FlutterSpellCheckPluginTest.mm
Corrects locale format for spell check.
According to [docs](https://developer.apple.com/documentation/uikit/uitextchecker/1621029-rangeofmisspelledword), the format should look like `[language designator]_[region designator]` where the language designator is a "ISO 639-1" standard code and the region designator is a "ISO 3166-1 standard, a two-letter, capitalized code" ([source](https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPInternational/LanguageandLocaleIDs/LanguageandLocaleIDs.html)). I used [this PR](https://github.com/flutter/flutter/pull/116222) to discover and test the fix manually. …
=> [iOS] Change locale format for spell check

lib/ui/painting/canvas.cc, lib/ui/painting/canvas.h, lib/ui/painting/picture.h, lib/ui/painting/picture_recorder.cc, lib/ui/painting/picture_recorder.h, lib/ui/text/paragraph.cc
Fixes: https://github.com/flutter/flutter/issues/116670
The Paragraph code was the last known use of the DisplayListCanvasRecorder that was held by the PictureRecorder/Canvas objects. Now that the text code talks directly to the DisplayListBuilder, this vestigial object can be removed in favor of allocating a DisplayListBuilder directly.
This is a deletion of code paths that are no longer used so no new unit tests are needed as long as it passes existing tests.
=> Remove dlCanvasRecorder from flutter::PictureRecorder

shell/platform/windows/BUILD.gn, shell/platform/windows/cursor_handler_unittests.cc
Add more tests for the Windows cursor plugin.
=> [Windows] Add more cursor plugin tests

shell/platform/android/android_egl_surface.cc
CP of https://github.com/flutter/engine/commit/1603fa1bb41271366dceedaaf0663715576e18f2 to 3.3 stable.
=> [CP] Remove glitches when scrolling on old Android TV devices (#37493)

ci/builders/mac_ios_engine_release.json
Autoninja is being deprecated and this is removing engine v2 configurations. …
=> Remove autoninja.

shell/platform/embedder/tests/embedder_test_context_metal.cc, shell/platform/embedder/tests/embedder_test_context_metal.h, shell/platform/embedder/tests/embedder_unittests_metal.mm
This is a minor cleanup that exposes the test metal surface to tests via EmbedderTestContextMeta::GetTestMetalSurface for parity with the GetTestMetalContext method which exposes the test metal context. This eliminates the need for the more specific GetTextureInfo method since the texture info is accessible via the test context.
This is a test refactoring with no semantic differences to the engine.
Issue: https://github.com/flutter/flutter/issues/116381
[C++, …
=> [embedder] Expose metal surface from test context

lib/ui/painting/canvas.cc, lib/ui/painting/canvas.h, lib/ui/painting/picture.h, lib/ui/painting/picture_recorder.cc, lib/ui/painting/picture_recorder.h, lib/ui/text/paragraph.cc
Reverts flutter/engine#38127
It looks like some internal down-stream testing was affected, but we can't figure out why it was dependent on the libtxt code. I'll hold off on this code removal until we've successfully weaned down-stream code off of dependencies.
=> Revert "Remove dlCanvasRecorder from flutter::PictureRecorder"

tools/gen_objcdoc.sh
Eliminates the --module-version flag to jazzy when generating Obj-C docs. This was hardcoded to 1.0.0. Since we have no knowledge of which Flutter version a given engine build will be part of, eliminate it altogether on the basis that it's better to have no version than the wrong version.
Before:
After: …
=> [tools] Eliminate version on Obj-C docs

impeller/aiks/canvas.cc, impeller/display_list/display_list_unittests.cc
=> [Impeller] Use DrawPath instead of Rect geometry when the paint style is stroke

ci/builders/mac_ios_engine_release.json
CP of https://github.com/flutter/engine/pull/38136 into the 3.7 branch, which is needed for further cherry-picks.
=> [CP] Remove autoninja. (#38136)

lib/web_ui/lib/src/engine/canvaskit/canvaskit_api.dart
Instead of dealing with the JS Promise, let `js_util` convert it to a Future for us.
=> [web] Use js_util.promiseToFuture with CanvasKitInit()

flow/layers/clip_path_layer_unittests.cc, flow/layers/clip_rect_layer_unittests.cc, flow/layers/clip_rrect_layer_unittests.cc, flow/layers/clip_shape_layer.h, flow/layers/opacity_layer.cc, flow/layers/opacity_layer_unittests.cc, flow/layers/platform_view_layer_unittests.cc, flow/testing/mock_embedder.cc, flow/testing/mock_embedder.h
The LayerStateStack introduced some aggressive clip and opacity culling to the Paint methods of some layers. Unfortunately, PlatformViews require that their Paint method is called if their Preroll method is called. Since we Preroll all layers regardless of culling, then we must Paint all PlatformViewLayers regardless of culling. The culling introduced by the LayerStateStack did not check if there was a PlatformView in the subtree before returning early, so this PR eliminates those optimizations.
=> Fix premature LayerStateStack layer culling

tools/const_finder/lib/const_finder.dart, tools/const_finder/pubspec.yaml, tools/const_finder/test/const_finder_test.dart, tools/const_finder/test/fixtures/.dart_tool/package_config.json, tools/const_finder/test/fixtures/lib/static_icon_provider.dart, tools/const_finder/test/fixtures/lib/target.dart
Fixes https://github.com/flutter/flutter/issues/116807
Skip non-const locations that are:
1. within the target class (in production, this will be `IconData`
2. within a procedure that is:
a. static
b. a method
c. named `_#new#tearOff`
=> [const_finder] Ignore constructor invocations from generated tear-off declarations

impeller/scene/importer/importer_gltf.cc, impeller/scene/importer/importer_unittests.cc, impeller/scene/importer/vertices_builder.cc, impeller/scene/importer/vertices_builder.h
GLTF geometry follows a right-handed coordinate system where +z is model "front" and +y is model "top". Impeller has a left-handed clip space. Inverting Z is the simplest and most predictable conversion with respect to a default camera orientation such that model "right" is towards the right side of the viewport (+x in Impeller clip space) and model "top" is towards the top of the viewport (+y in Impeller clip space).
Also refactors the VerticesBuilder to support more specific behaviors (we'll need more AttributeWriter procs soon, like for tangents).
Before:
After:
=> [Impeller Scene] Convert vertex positions to match Impeller's clip space orientation

impeller/compiler/switches_unittests.cc, impeller/compiler/types.cc, impeller/compiler/utilities.cc, impeller/compiler/utilities.h
Fixes https://github.com/flutter/flutter/issues/116863
=> [Impeller] Fix asset names used for the generated entrypoint name can contain invalid identifiers for the target language

impeller/renderer/backend/metal/pipeline_library_mtl.mm
Makes the PSO construction not use a worker since the theory is that device teardown in the test harness is tickling a race condition in the Metal framework.
Fixes https://github.com/flutter/flutter/issues/114872 (speculatively).
Following up in https://github.com/flutter/flutter/issues/116919.
=> [Impeller] Speculatively attempt to fix Metal PSO construction errors on host targets.

impeller/compiler/switches.cc
Fixes typo in Impeller compiler help, where the argument `input-type` is incorrectly shown as `input-kind`
Fixes https://github.com/flutter/flutter/issues/116865
=> [Impeller] Fix typo in compiller help

impeller/scene/geometry.cc, impeller/scene/geometry.h, impeller/scene/material.cc, impeller/scene/material.h, impeller/scene/mesh.cc, impeller/scene/mesh.h, impeller/scene/node.cc, impeller/scene/node.h, impeller/scene/scene_context.cc, impeller/scene/scene_unittests.cc
Utils to run flatbuffer validation and unpack nodes from ipscenes.
=> [Impeller Scene] Node deserialization

ci/licenses_golden/licenses_flutter, fml/BUILD.gn, fml/platform/win/file_win.cc, fml/platform/win/file_win_unittests.cc
Use shared mode when requesting read access and exclusive mode for write access
=> Clarify file sharing flags in FML filesystem APIs on Windows

shell/platform/darwin/ios/framework/Source/FlutterViewController.mm, shell/platform/darwin/ios/framework/Source/FlutterViewControllerTest.mm
Previous to iOS 16, there was a hack in place to explicitly set the device orientation.  In iOS 16 there's now an API to set the orientation "preferences" (portrait only, all but upside down, etc), and the OS decides if the screen needs rotation after the preference is set, which was adopted in https://github.com/flutter/engine/pull/36874.  Instead of checking the current orientation and only setting the preference if that orientation isn't included in the preference, instead always set it and let the OS do its thing.
iOS 16 orientation code introduced in https://github.com/flutter/engine/pull/36874
Fixes https://github.com/flutter/flutter/issues/116711 …
=> Always set orientation preferences on iOS 16+

DEPS, ci/licenses_golden/licenses_skia, flutter_vma/flutter_skia_vma.cc, flutter_vma/flutter_skia_vma.h
This roll changed a VulkanMemoryAllocator API
=> Manual roll of Skia from 971c342c3030 to 280ac8882cff

.ci.yaml
Prod bots are all 12 cores:
https://chromium-swarm.appspot.com/botlist?c=id&c=task&c=cores&c=os&c=status&d=asc&f=pool%3Aluci.flutter.prod&f=os%3AMac-12&f=cpu%3Ax86&f=device_type%3Anone&k=cores&s=id
Try bots are mostly 12 cores:
https://chromium-swarm.appspot.com/botlist?c=id&c=task&c=cores&c=os&c=status&d=asc&f=os%3AMac-12&f=cpu%3Ax86&f=device_type%3Anone&f=pool%3Aluci.flutter.try&k=pool&s=id
Staging is 50-50 (would be used if this bot ever marked flaky):
https://chromium-swarm.appspot.com/botlist?c=id&c=task&c=cores&c=os&c=status&d=asc&f=os%3AMac-12&f=cpu%3Ax86&f=device_type%3Anone&f=pool%3Aluci.flutter.staging&k=pool&s=id
Fixes https://github.com/flutter/flutter/issues/116931 …
=> Run Mac Host clang-tidy on 12 cores

lib/web_ui/lib/src/engine/canvaskit/painting.dart, lib/web_ui/test/canvaskit/fragment_program_test.dart
Ensure that vec2, vec3, et cetera are mapped to multiple floats. Test would have failed if it was running
=> [web] correct float count in runtime effect

testing/dart/image_dispose_test.dart
These will get flagged w/ the latest linter.
See [try failure](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8794866247739072257/+/u/analyze_flutter_plugins/stdout) and [linter roll PR](https://dart-review.googlesource.com/c/sdk/+/275044).
[CLA]: …
=> Fix new `unnecessary_parenthesis` diagnostics.

impeller/renderer/backend/metal/pipeline_library_mtl.mm
Reverts flutter/engine#38229
The errors are still happening and https://github.com/flutter/flutter/issues/114872 has been re-opened for further investigation.
=> Revert "[Impeller] Speculatively attempt to fix Metal PSO construction errors on host targets."

impeller/renderer/backend/metal/pipeline_library_mtl.mm
=> Reland "[Impeller] Speculatively attempt to fix Metal PSO construction errors on host targets."

shell/platform/darwin/BUILD.gn, shell/platform/darwin/common/BUILD.gn, shell/platform/darwin/common/framework/Headers/FlutterCodecs.h, shell/platform/darwin/common/framework/Source/FlutterChannels.mm, shell/platform/darwin/common/framework/Source/FlutterChannelsTest.m, shell/platform/darwin/common/framework/Source/FlutterCodecs.mm, shell/platform/darwin/common/framework/Source/FlutterStandardCodec.mm, shell/platform/darwin/ios/framework/Source/FlutterRestorationPluginTest.mm
Relands https://github.com/flutter/engine/pull/37219, which was reverted at https://github.com/flutter/engine/pull/37320 due to a benchmark regression. https://github.com/flutter/flutter/issues/114697
There is no change in this PR compares to https://github.com/flutter/engine/pull/37219
The benchmark regression is due to a performance regression caused by ARC, specifically here: https://github.com/flutter/engine/blob/main/shell/platform/darwin/common/framework/Source/FlutterStandardCodec.mm#L458-L464 . 
This regression is unavoidable and been discussed at several places online: https://jimmymandersson.medium.com/understanding-arcs-effect-on-your-apps-performance-377e39076a88
I create two simple sample test cases comparing ARC and ARC in performance and the result shows (from my machine) …
=> Reland "Migrate darwin common "framework_shared" target to ARC #37049" 

impeller/renderer/backend/metal/pipeline_library_mtl.mm
This is a benign condition but the validation logs could be fatal since https://github.com/flutter/engine/commit/8744c93c4d5. Don't crash in these situations.
=> [Impeller] Remove validation log when the pipeline library is collected before pipeline is setup.

testing/run_tests.py
Fixes https://github.com/flutter/flutter/issues/114872 Followup in https://github.com/flutter/flutter/issues/117122
=> [Impeller] Disable impeller_unittests.

shell/platform/windows/flutter_window.cc, shell/platform/windows/flutter_window.h, shell/platform/windows/flutter_window_unittests.cc, shell/platform/windows/flutter_windows_view.cc, shell/platform/windows/flutter_windows_view.h, shell/platform/windows/keyboard_handler_base.h, shell/platform/windows/keyboard_key_channel_handler.cc, shell/platform/windows/keyboard_key_channel_handler.h, shell/platform/windows/keyboard_key_embedder_handler.cc, shell/platform/windows/keyboard_key_embedder_handler.h, shell/platform/windows/keyboard_key_embedder_handler_unittests.cc, shell/platform/windows/keyboard_key_handler.cc, shell/platform/windows/keyboard_key_handler.h, shell/platform/windows/keyboard_key_handler_unittests.cc, shell/platform/windows/keyboard_unittests.cc, shell/platform/windows/keyboard_utils.h, shell/platform/windows/testing/mock_window.h, shell/platform/windows/testing/mock_window_binding_handler_delegate.h, shell/platform/windows/window.cc, shell/platform/windows/window.h, shell/platform/windows/window_binding_handler_delegate.h, shell/platform/windows/window_unittests.cc
This PR implements modifier keys states synchronization based on pointer events.
It is the Windows implementation for https://github.com/flutter/flutter/issues/115066.
Win32 mouse events only expose flags for Shift and Control, so only those two modifiers are sync.
https://github.com/flutter/flutter/issues/115066
Adds 4 tests.
=> [Windows] Synthesize modifier keys events on pointer events

shell/platform/linux/fl_dart_project.cc, shell/platform/linux/fl_dart_project_test.cc, shell/platform/linux/public/flutter_linux/fl_dart_project.h
Support setting a custom asset directory and ICU data path.
Fixes: https://github.com/flutter/flutter/issues/117103
Issue: https://github.com/flutter/flutter/issues/117102 …
=> [linux] Allow overriding asset, ICU data path

lib/web_ui/pubspec.yaml, web_sdk/pubspec.yaml, web_sdk/web_engine_tester/pubspec.yaml
Dependency to package test is updated in order to pick up the latest package matcher, which no longer uses a deprecated CyclicInitializationError class from dart:core which was recently removed from Dart SDK.
Issue: https://github.com/dart-lang/sdk/issues/49529
=> Update web_sdk -> package test dependency to get updated package matcher

DEPS, ci/licenses_golden/excluded_files, ci/licenses_golden/licenses_fuchsia
There's a licenses failure that the SDK roll isn't taking care of for some reason ([example failure](https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20License/8073/overview)). Manually rolling with the change to resolve.
=> [fuchsia] Manually roll Fuchsia Linux SDK.

lib/ui/platform_dispatcher.dart
The `PlatformDispatcher.onError` referenced the implementation of the `compute` method. This is no longer up to date, since `compute` is now making use of the Dart method to spawn an Isolate.
[Flutter Style …
=> Remove `PlatformDispatcher.onError` reference to the `compute` method

display_list/display_list_builder.cc, display_list/display_list_canvas_recorder.cc, display_list/display_list_unittests.cc
Fixes: https://github.com/flutter/flutter/issues/117121
While implementing display list render culling I noticed that the clip bounds methods on DLCanvasRecorder were not set up correctly. This PR will make sure that the clip bounds are updated both for the initial cull rect and the subsequent calls to clipRect/RRect/Path.
=> make sure DisplayListCanvasRecorder updates clip bounds methods

shell/platform/android/io/flutter/embedding/android/FlutterActivity.java, shell/platform/android/io/flutter/embedding/android/FlutterActivityAndFragmentDelegate.java, shell/platform/android/io/flutter/embedding/android/FlutterFragment.java, shell/platform/android/io/flutter/embedding/engine/FlutterEngine.java, shell/platform/android/io/flutter/embedding/engine/FlutterEngineConnectionRegistry.java, shell/platform/android/io/flutter/embedding/engine/FlutterEngineGroup.java, shell/platform/android/io/flutter/embedding/engine/plugins/FlutterPlugin.java, shell/platform/android/io/flutter/embedding/engine/plugins/shim/ShimPluginRegistry.java, shell/platform/android/test/io/flutter/embedding/android/FlutterActivityAndFragmentDelegateTest.java, shell/platform/android/test/io/flutter/embedding/engine/FlutterEngineConnectionRegistryTest.java, shell/platform/android/test/io/flutter/embedding/engine/FlutterEngineTest.java
Also started made the group accessible to plugins.  There are a few important plugins that spawn new engines that run in the background, this will allow them to share the isolate group across the whole app.  I avoided deprecating FlutterEngine constructors until we get wider acceptance from the team.
issue: https://github.com/flutter/flutter/issues/115507 …
=> Started using FlutterEngineGroups by default on Android 

shell/platform/darwin/macos/framework/Source/FlutterThreadSynchronizer.mm
=> Add missing include to FlutterThreadSynchronizer

ci/licenses_golden/licenses_flutter, shell/platform/darwin/BUILD.gn, shell/platform/darwin/common/BUILD.gn, shell/platform/darwin/common/framework/Source/FlutterStandardCodec.mm, shell/platform/darwin/common/framework/Source/FlutterStandardCodecHelper.c, shell/platform/darwin/common/framework/Source/FlutterStandardCodecHelper.h, shell/platform/darwin/common/framework/Source/FlutterStandardCodec_Internal.h, shell/platform/darwin/common/framework/Source/flutter_standard_codec_unittest.mm
No functional change, just an improvement in 19% increase codec reading speed.  The gains were using a CFData create function that avoids a copy for a temporary data object until it is converted to a string, avoiding some objc_msgSend, avoiding some retain/release, and avoiding the objc recursion if we know the next object we are reading can be read in C.
before:
after:
tests:
- performance benchmark will be covered by the platform_channel_benchmarks
- integration tests exist for channels
implementation of investigation @cyanglaz and I did on https://github.com/flutter/engine/pull/37883 …
=> Sped up reading with FlutterStandardCodec.

shell/platform/android/io/flutter/embedding/android/FlutterActivity.java, shell/platform/android/io/flutter/embedding/android/FlutterActivityAndFragmentDelegate.java, shell/platform/android/io/flutter/embedding/android/FlutterFragment.java, shell/platform/android/io/flutter/embedding/engine/FlutterEngine.java, shell/platform/android/io/flutter/embedding/engine/FlutterEngineConnectionRegistry.java, shell/platform/android/io/flutter/embedding/engine/FlutterEngineGroup.java, shell/platform/android/io/flutter/embedding/engine/plugins/FlutterPlugin.java, shell/platform/android/io/flutter/embedding/engine/plugins/shim/ShimPluginRegistry.java, shell/platform/android/test/io/flutter/embedding/android/FlutterActivityAndFragmentDelegateTest.java, shell/platform/android/test/io/flutter/embedding/engine/FlutterEngineConnectionRegistryTest.java, shell/platform/android/test/io/flutter/embedding/engine/FlutterEngineTest.java
This reverts commit 47a358c5e8fc4a6deb057f738ce1e3432eb9c98f.
This commit caused a regression in the entrypoint_dart_registrant test.
=> Revert "Started using FlutterEngineGroups by default on Android  (#37822)"

impeller/playground/compute_playground_test.cc, impeller/playground/playground.cc, impeller/playground/playground_test.cc
Also removed the Q key from the escape event because WASD QE cam. ;)
=> [Impeller] Remove 30fps cap from playgrounds

shell/platform/fuchsia/flutter/tests/integration/embedder/flutter-embedder-test.cc, shell/platform/fuchsia/flutter/tests/integration/touch-input/embedding-flutter-view/BUILD.gn, shell/platform/fuchsia/flutter/tests/integration/touch-input/embedding-flutter-view/lib/embedding-flutter-view.dart, shell/platform/fuchsia/flutter/tests/integration/touch-input/touch-input-test.cc, shell/platform/fuchsia/flutter/tests/integration/touch-input/touch-input-view/lib/touch-input-view.dart, shell/platform/fuchsia/flutter/tests/integration/utils/portable_ui_test.cc, shell/platform/fuchsia/flutter/tests/integration/utils/portable_ui_test.h
This PR removes touch-based tests from the embedder integration test and ports them over to the touch-input integration test
=> Port touch-based tests from embedder integration test

lib/ui/hooks.dart, lib/ui/platform_dispatcher.dart, lib/ui/window/platform_configuration.cc, lib/ui/window/platform_configuration.h, lib/web_ui/lib/platform_dispatcher.dart, lib/web_ui/lib/src/engine/platform_dispatcher.dart, runtime/runtime_controller.cc, runtime/runtime_controller.h, shell/common/engine.cc, shell/common/engine.h, shell/common/platform_view.cc, shell/common/platform_view.h, shell/common/shell.cc, shell/common/shell.h, shell/platform/android/io/flutter/embedding/engine/FlutterJNI.java, shell/platform/android/io/flutter/embedding/engine/renderer/FlutterRenderer.java, shell/platform/embedder/embedder.cc, shell/platform/embedder/embedder.h, shell/platform/embedder/embedder_engine.cc, shell/platform/embedder/embedder_engine.h
Previously, the embedder API incorrectly documented this as an action ID, but it's actually the semantics node ID. This fixes the docs and renames the parameter to clarify its purpose.
This callback is registered in the framework render bindings:
https://github.com/flutter/flutter/blob/9102f2fe0bd26db6074ac4a17785296cd341ecb9/packages/flutter/lib/src/rendering/binding.dart#L43
Handled by `_handleSemanticsAction`:
https://github.com/flutter/flutter/blob/9102f2fe0bd26db6074ac4a17785296cd341ecb9/packages/flutter/lib/src/rendering/binding.dart#L360-L366
Which invokes `SemanticsOwner.performAction`, where the node is looked up by ID:
https://github.com/flutter/flutter/blob/9102f2fe0bd26db6074ac4a17785296cd341ecb9/packages/flutter/lib/src/semantics/semantics.dart#L3258-L3277
If you need help, …
=> Clarify dispatch semantics action id parameter

display_list/display_list.cc, display_list/display_list.h, display_list/display_list_builder.cc, display_list/display_list_builder.h
SkAutoTMalloc is not a public Skia API
=> Remove DisplayList's dependency on SkAutoTMalloc

shell/platform/windows/flutter_windows.cc, shell/platform/windows/flutter_windows_unittests.cc, shell/platform/windows/public/flutter_windows.h
Cherry pick commit https://github.com/flutter/engine/commit/2148fc003077f611bdf668e3631ad7f9b763333a to `3.7-candidate.1`. 
Original issue: https://github.com/flutter/flutter/issues/116753
Cherry pick issue: https://github.com/flutter/flutter/issues/116932
=> [CP] [Windows] Fix headless mode crash

impeller/aiks/canvas.cc, impeller/display_list/display_list_unittests.cc
This is the CP PR for https://github.com/flutter/engine/pull/38146. See https://github.com/gskinnerTeam/flutter-wonderous-app/issues/53
=> [CP] [Impeller] Use DrawPath instead of Rect geometry when the paint style is stroke

shell/platform/darwin/common/framework/Source/FlutterStandardCodec.mm, shell/platform/darwin/common/framework/Source/FlutterStandardCodecHelper.c, shell/platform/darwin/common/framework/Source/FlutterStandardCodecHelper.h
This improves encoding time 18% (based on the platform channel large benchmark).
This follows up on the investigation done in https://github.com/flutter/engine/pull/37883.  After this lands we should be almost back where we were before the ARC migration.
This includes the following optimizations:
1) A big win was made from avoiding `[NSNull null]` since it caused alot of ARC activity
1) Iterating over maps doesn't require looking up the values now
1) NSStrings in utf8 format will get read from directly (I'm not sure how this compares with objc logic)
1) For common datatypes no arc should be used (e.g. a List with Strings and Ints)
1) For common datatypes recursion happens with c function invocations instead of objc_msgSend
There is no functional change here, just performance change. …
=> Sped up FlutterStandardCodec writing speed.

shell/platform/darwin/ios/framework/Source/FlutterCallbackCache.mm, shell/platform/darwin/ios/framework/Source/FlutterFakeKeyEvents.mm, shell/platform/darwin/ios/framework/Source/accessibility_bridge.mm, shell/platform/darwin/macos/framework/Source/FlutterSurfaceManager.mm, shell/platform/darwin/macos/framework/Source/FlutterThreadSynchronizer.mm
Eliminates raw C asserts in the macOS and iOS embedders, replacing them with `FML_DCHECK` for consistency with the rest of the codebase.
No semantic change so no changes to tests.
[breaking …
=> [macOS, iOS] Migrate from assert to FML_DCHECK

ci/licenses_golden/licenses_flutter, shell/platform/darwin/BUILD.gn, shell/platform/darwin/common/BUILD.gn, shell/platform/darwin/common/framework/Source/FlutterStandardCodecHelper.cc
Even though the file is pure C code, it's useful to use a C++ or Objective-C++ filename in order to use FML (assertions) in the implementation. 
Three implementation changes:
* Since the file is now C++, some implicit void* conversions now require an explicit cast.
* A malloc/free of a buffer has been replaced with a std::vector.
* An `assert()` was changed to `FML_DCHECK` for consistency with the rest of the embedder.
No test changes since there are no semantic changes. 
Existing tests are in:
https://github.com/flutter/engine/blob/main/shell/platform/darwin/common/framework/Source/flutter_standard_codec_unittest.mm …
=> Use FML_DCHECK in place of assert in codec utils

impeller/scene/node.cc, impeller/scene/scene_unittests.cc
The included test crashes without the fix.
https://user-images.githubusercontent.com/919017/208228212-a8d1a323-251b-4b70-819d-032613b3ef1e.mov
I also put some test camera code inline, gonna move it into a reusable utility when we need it again in a playground.
=> [Impeller Scene] Fix crasher for nodes with no meshes

impeller/playground/compute_playground_test.cc, impeller/playground/compute_playground_test.h, impeller/playground/playground.cc, impeller/playground/playground.h, impeller/playground/playground_test.cc, impeller/playground/playground_test.h
PlaygroundTest isn't the right abstraction for time utils like this.
=> [Impeller] Move GetSecondsElapsed to Playground

lib/web_ui/lib/src/engine/canvaskit/image.dart, lib/web_ui/test/canvaskit/image_golden_test.dart
`toByteData` for browsers that support web codecs [returned the original unmodified pixels ](https://github.com/flutter/engine/blob/e6e6a02106c6ee1ff5d3f71e0e0c378f80759728/lib/web_ui/lib/src/engine/canvaskit/image_web_codecs.dart#L441). However, those unmodified pixels for the following videoFrame formats: I420, I422, I444 were not encoded to the correct format, for any format requested. Those returned unmodified pixels were not usable with `decodeImageFromPixels`
The fix is to use canvaskit to encode the image for the above videoFrame formats instead of web codecs. 
Fixes: https://github.com/flutter/flutter/issues/116721 …
=> Use canvaskit `toByteData` for unsupported videoFrame formats

lib/ui/painting.dart
=> [CP] add link to website for FragmentProgram (#38273)

display_list/display_list_matrix_clip_tracker.h
This is a followup to 3626c487a610eff4 which adds more potentially-missing includes from display_list_matrix_clip_tracker.h
We are actively cleaning up our public API includes, and this aims to prevent future breakages.
=> Add more missing includes of Skia headers

flutter_vma/flutter_skia_vma.cc
Skia plans to remove this from the public API.
[Discord]: …
=> Remove usage of SkToBool

shell/platform/android/io/flutter/embedding/android/FlutterActivity.java, shell/platform/android/io/flutter/embedding/android/FlutterActivityAndFragmentDelegate.java, shell/platform/android/io/flutter/embedding/android/FlutterFragment.java, shell/platform/android/io/flutter/embedding/engine/FlutterEngine.java, shell/platform/android/io/flutter/embedding/engine/FlutterEngineConnectionRegistry.java, shell/platform/android/io/flutter/embedding/engine/FlutterEngineGroup.java, shell/platform/android/io/flutter/embedding/engine/plugins/FlutterPlugin.java, shell/platform/android/io/flutter/embedding/engine/plugins/shim/ShimPluginRegistry.java, shell/platform/android/test/io/flutter/embedding/android/FlutterActivityAndFragmentDelegateTest.java, shell/platform/android/test/io/flutter/embedding/engine/FlutterEngineConnectionRegistryTest.java, shell/platform/android/test/io/flutter/embedding/engine/FlutterEngineTest.java
relands: https://github.com/flutter/engine/pull/37822
revert pr: https://github.com/flutter/engine/pull/38351
The fix is in a separate commit in the PR.  I just factored out some logic for creating engines from groups from elsewhere that takes into account the entrypoint.  It's a bit tricky since it isn't clear how the engine was getting those things.
There already is a test that covers this. …
=> reland: Started using FlutterEngineGroups by default on Android

impeller/scene/geometry.cc, impeller/scene/importer/importer_gltf.cc, impeller/scene/importer/importer_unittests.cc, impeller/scene/importer/scene.fbs, impeller/scene/importer/vertices_builder.cc, impeller/scene/importer/vertices_builder.h, impeller/scene/node.cc, impeller/scene/node.h, impeller/scene/scene.cc, impeller/scene/scene_unittests.cc
Preparation for landing animations and PBR materials. Nodes are boxed again.
=> [Impeller Scene] Add animation/PBR descriptions to ipscene

ci/licenses_golden/licenses_flutter, shell/platform/darwin/macos/BUILD.gn, shell/platform/darwin/macos/framework/Source/FlutterCompositor.mm, shell/platform/darwin/macos/framework/Source/FlutterView.mm, shell/platform/darwin/macos/framework/Source/FlutterViewTest.mm
This fixes problem introduced in https://github.com/flutter/engine/pull/37789.
CALayer scale is used to position surfaces, but the scale is not updated when backing window properties change.
Implementing CALayer's delegate (FlutterView) [layer:shouldInheritContentsScale:fromWindow:] takes care of this.
Fixes https://github.com/flutter/flutter/issues/117247 …
=> [macOS] Update FlutterView layer scale when backing properties change

impeller/compiler/shader_lib/impeller/constants.glsl, impeller/compiler/shader_lib/impeller/gaussian.glsl, impeller/entity/contents/rrect_shadow_contents.cc, impeller/entity/shaders/rrect_blur.frag
Address the RRect blur discontinuities brought up in https://github.com/flutter/flutter/issues/116584 by increasing the radius per sigma ratio from sqrt(3) to 2 (~15%). Upon close examination, I noticed that Skia's blurs appear to extend out about this much further.
To offset the additional GPU load, I applied a couple of speed-ups I've been meaning to get around to:
* Decrease the number of samples from 5 to 4.
* Use a faster approximation for the Gaussian integral. For this I just grabbed the logistic function and fit it as close to the Gaussian integral as possible. It's very close! I recall seeing one of Skia's blur paths use a sigmoid like this to populate a LUT a while back... this might be why some of Skia's blurs look a bit softer/lighter than ours in some places.
Blue is the old …
=> [Impeller] RRect blur improvements

impeller/playground/imgui/imgui_impl_impeller.cc, impeller/renderer/pipeline_descriptor.cc, impeller/renderer/pipeline_descriptor.h
Went through the playgrounds today. This fixes many failing playgrounds which started failing after I landed https://github.com/flutter/engine/pull/38118/files#diff-489549033945b523bbdb56af7684a119c7a2eaacf01a52270bd1f11404125a1aR266-R267.
That change unsets the depth/stencil attachments on the render target before drawing with the ImGui pipeline.
=> [Impeller] Remove depth/stencil attachments from imgui pipeline

display_list/display_list_unittests.cc
A DisplayList unit test started failing on M1 Macs after https://github.com/flutter/engine/pull/38349 most likely due to a slight difference in the way that Apple Silicon performs some floating point operations.
Since the exact floating point precision bounds aren't a required part of the test (the bug being tested was that the bounds used to be completely empty), I switched the test to use a min/max bounds that sandwich the desired output bounds so that the test would be resistant to changes in floating point computations.
=> Fix floating point rounding issue in unit test bounds check

ci/licenses_golden/excluded_files, display_list/BUILD.gn, display_list/display_list.cc, display_list/display_list.h, display_list/display_list_builder.cc, display_list/display_list_builder.h, display_list/display_list_ops.h, display_list/display_list_rtree.cc, display_list/display_list_rtree.h, display_list/display_list_rtree_unittests.cc, display_list/display_list_test_utils.cc, display_list/display_list_unittests.cc, display_list/display_list_utils.cc, display_list/display_list_utils.h, flow/embedded_views.cc
Fixes: https://github.com/flutter/flutter/issues/92740
This PR uses an R-Tree (when computed by the Builder) to cull the dispatching of a DisplayList similar to what is done in SkPicture objects when constructed with a bbox factory.
Some additional changes:
- DlRTree no longer depends on the Skia bbox hierarchy base class
- DlRTree now uses a more streamlined approach to managing its data now that it is not relying on a generic superclass
- basic tests of R-Tree culling added, and some unit tests. Is something more sophisticated warranted?
- the code that tags rectangles with the rendering op index is currently executed post-`Push` which means the rectangles need to be tagged with `op_index_ - 1`. I eventually want to move the bounds calculations to before the `Push` calls and then …
=> Display list R-Tree culling

display_list/display_list.cc
Some downstream compilers will check for virtual destructors on virtual classes.
=> add virtual destructor to new virtual Culler class

shell/platform/fuchsia/flutter/gfx_external_view_embedder.cc
Adds more logging around the matrix check to understand a crash.
=> [fuchsia] Debugging code for crash.

ci/licenses_golden/licenses_flutter, impeller/aiks/aiks_unittests.cc, impeller/aiks/paint.h, impeller/display_list/display_list_dispatcher.cc, impeller/entity/BUILD.gn, impeller/entity/contents/color_source_contents.cc, impeller/entity/contents/color_source_contents.h, impeller/entity/contents/content_context.cc, impeller/entity/contents/content_context.h, impeller/entity/contents/scene_contents.cc, impeller/entity/contents/scene_contents.h, impeller/geometry/rect.h, impeller/scene/scene.cc, impeller/scene/scene.h, impeller/scene/scene_encoder.cc, impeller/scene/scene_encoder.h, impeller/scene/scene_unittests.cc, shell/platform/android/android_surface_gl_impeller.cc, shell/platform/android/android_surface_vulkan_impeller.cc, shell/platform/darwin/graphics/FlutterDarwinContextMetalImpeller.mm
This adds a `ColorSourceContents` which renders an Impeller Scene to a texture and blits it to the current layer respecting the geometry, blend mode, and clip stack.
I also added commented code in the display list dispatcher that can be uncommented once the `DlSceneColorSource` has been implemented.
=> [Impeller Scene] Add ColorSourceContents for drawing a node

shell/platform/fuchsia/flutter/flatland_connection.cc, shell/platform/fuchsia/flutter/flatland_connection.h, shell/platform/fuchsia/flutter/tests/flatland_connection_unittests.cc, shell/platform/fuchsia/flutter/tests/flatland_external_view_embedder_unittests.cc
This CL processes the Flatland's presentation callback to set the correct Vsync times for frame end.
Bug: fxb/114588
=> [fuchsia] Set presentation end times based on Flatland feedback

shell/platform/fuchsia/flutter/flatland_connection.cc, shell/platform/fuchsia/flutter/flatland_connection.h
This CL adds a trace flow event that starts from Flutter and ends at Scenic.
=> [fuchsia] Add trace flow for Flatland::Present

shell/platform/windows/BUILD.gn, shell/platform/windows/flutter_windows_engine_unittests.cc, shell/platform/windows/platform_handler_unittests.cc, shell/platform/windows/testing/flutter_windows_engine_builder.cc, shell/platform/windows/testing/flutter_windows_engine_builder.h, shell/platform/windows/testing/windows_test_context.cc, shell/platform/windows/testing/windows_test_context.h
This introduces `FlutterWindowsEngineBuilder` which can be used to create a `FlutterWindowsEngine` with the desired configuration for testing purposes.
=> [Windows] Add engine builder to simplify tests

lib/web_ui/lib/src/engine/semantics/text_field.dart, lib/web_ui/test/engine/semantics/text_field_test.dart
Reverts flutter/engine#38271.
fails education tests. context: https://buganizer.corp.google.com/issues/263966258
would be great if web team could help take a look. Thank you!
=> [flutter roll] Revert "[web] Don't overwrite editing state with semantic updates"

ci/licenses_golden/licenses_flutter, impeller/scene/geometry.cc, impeller/scene/geometry.h, impeller/scene/importer/importer_gltf.cc, impeller/scene/importer/importer_unittests.cc, impeller/scene/importer/vertices_builder.cc, impeller/scene/importer/vertices_builder.h, impeller/scene/pipeline_key.h, impeller/scene/scene_context.cc, impeller/scene/shaders/BUILD.gn, impeller/scene/shaders/skinned.vert
Imports joint indices and weights and serves skinned mesh primitives through a placeholder vertex shader. I'll be adding skin import/joint sampling in a later patch.
A fun bug along the way:
https://user-images.githubusercontent.com/919017/209919475-36e1478d-ae5e-448f-a821-92311d7d3d77.mov
=> [Impeller Scene] Import skinned mesh vertex data

ci/licenses_golden/licenses_flutter, impeller/scene/BUILD.gn, impeller/scene/animation/animation.cc, impeller/scene/animation/animation.h, impeller/scene/animation/animation_clip.cc, impeller/scene/animation/animation_clip.h, impeller/scene/animation/animation_player.cc, impeller/scene/animation/animation_player.h, impeller/scene/animation/property_resolver.cc, impeller/scene/animation/property_resolver.h, impeller/scene/node.cc, impeller/scene/node.h, impeller/scene/scene_unittests.cc
Depends on https://github.com/flutter/engine/pull/38583, which adds animation import to SceneC.
This patch adds property-driving animation. So far, I've only implemented support for transform-related properties (translation/rotation/scale) for the purpose of skeletal animation playback, but other properties can be easily added later (e.g. morph target weights, material properties).
For the actual transform property channels, I added keyframe lerping timelines, but `PropertyResolver` is _not_ necessarily a timeline -- specialized curve-driven resolvers can easily be added later (e.g. sine waves, parameterized springs).
The "Two Triangles" playground now runs the imported "Metronome" animation, which is manipulating the bone transforms. However, this doesn't result in any visible change …
=> [Impeller Scene] Animation binding and playback

shell/platform/windows/cursor_handler.cc, shell/platform/windows/cursor_handler.h, shell/platform/windows/cursor_handler_unittests.cc, shell/platform/windows/flutter_windows_engine.cc, shell/platform/windows/flutter_windows_engine.h, shell/platform/windows/flutter_windows_view.cc, shell/platform/windows/flutter_windows_view.h
The Windows `CursorHandler` is a singleton, however, it is owned by the view. This makes the `CursorHandler` owned by the engine to prepare for a multi-view world. …
=> [Windows] Make the engine own the cursor plugin

shell/platform/common/accessibility_bridge.cc, shell/platform/common/accessibility_bridge.h, shell/platform/common/accessibility_bridge_unittests.cc, shell/platform/common/flutter_platform_node_delegate.cc, shell/platform/common/flutter_platform_node_delegate.h, shell/platform/windows/flutter_platform_node_delegate_windows.cc, shell/platform/windows/flutter_platform_node_delegate_windows.h
For UIA implementation, we must have an `AXPlatformTreeManager` to  manage the trees of platform nodes. the `AccessibilityBridge` already serves a similar purpose.
Part of https://github.com/flutter/flutter/issues/116219 …
=> Make `AccessibilityBridge` a `AXPlatformTreeManager`

ci/licenses_golden/licenses_flutter, impeller/base/BUILD.gn, impeller/base/timing.h, impeller/scene/animation/animation.cc, impeller/scene/animation/animation.h, impeller/scene/animation/animation_clip.cc, impeller/scene/animation/animation_clip.h, impeller/scene/animation/animation_player.cc, impeller/scene/animation/animation_player.h, impeller/scene/animation/property_resolver.cc, impeller/scene/animation/property_resolver.h
Follow-up to https://github.com/flutter/engine/pull/38595. 32 bit floats are plenty precise for the animation system, so I just kept the use of float-backed seconds everywhere to keep the conversions to a minimum.
=> [Impeller Scene] Use std::chrono for animation durations

testing/test_dart_native_resolver.h, third_party/accessibility/ax/ax_table_info.h
Add `#include <string>` to headers that reference `std::string` but did not include them explicitly. This fixes some of the build errors that prevents Visual Studio 17.4+ from building the Flutter engine.
Part of https://github.com/flutter/flutter/issues/117932
[CLA]: …
=> [Windows] Fix missing includes when building using Visual Studio 17.4

impeller/scene/material.cc
Quick fix to make material base colors take precedent when present over vertex colors by default for imported models.
Before:
After:
=> [Impeller Scene] Fix material/vertex color overlapping

third_party/accessibility/ax/platform/ax_platform_node_win.cc, third_party/accessibility/ax/platform/ax_platform_node_win_unittest.cc
For UIA implementation, this will enable `AXPlatformNodeWin` to provide the appropriate text patterns, which will be necessary for more complicated screen reader interop such as narrating the selection.
Part of https://github.com/flutter/flutter/issues/116219 …
=> Add `TextProvider` and `TextEdit` patterns to `AXPlatformNodeWin`

third_party/accessibility/ax/ax_node_position_unittest.cc, third_party/accessibility/ax/ax_range_unittest.cc, third_party/accessibility/ax/ax_role_properties.cc
Chromium does not use `kTextField` or `kLabel` for text leaf nodes; we do. Adds these roles to the `IsText` helper method.
Part of https://github.com/flutter/flutter/issues/116219 …
=> Consider more `ax::mojom::Role`s as text

lib/ui/platform_dispatcher.dart, lib/ui/window.dart, lib/web_ui/lib/platform_dispatcher.dart, lib/web_ui/lib/src/engine/platform_dispatcher.dart, lib/web_ui/lib/src/engine/window.dart, lib/web_ui/lib/window.dart, lib/web_ui/test/engine/platform_dispatcher_test.dart, testing/dart/BUILD.gn, testing/dart/platform_dispatcher_test.dart, testing/scenario_app/lib/src/scenario.dart
Removes `FlutterView` to support multi-window.
Fixes https://github.com/flutter/flutter/issues/112204
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-b …
=> Remove single view assumptions from `window.dart`

.ci.yaml
We ended up needing a second cherrypick branch for the R51 release as the first release candidate was abandoned. This was the convention the Fuchsia team settled on for their branch name that we are trying to match.
=> [fuchsia] Enable CI for branches like `fuchsia_r51a`.

shell/platform/common/accessibility_bridge.cc, shell/platform/common/accessibility_bridge_unittests.cc, shell/platform/windows/accessibility_bridge_windows.cc, shell/platform/windows/accessibility_bridge_windows_unittests.cc
When the text selection of a node is changed, we should only set the AX tree's selection to that of the focused node. Currently, we set it for every node in the update, which means that whichever node happens to be last will have the selection that actually persists, even if it is not the focused node. The order of nodes when iterating through an update is meaningless. The focused flag is added to one unit test as well.
Part of https://github.com/flutter/flutter/issues/116219
[Tree …
=> Limit selection change to focused node on Windows

shell/platform/fuchsia/flutter/flatland_external_view_embedder.cc, shell/platform/fuchsia/flutter/tests/fakes/scenic/fake_flatland.cc, shell/platform/fuchsia/flutter/tests/fakes/scenic/fake_flatland.h, shell/platform/fuchsia/flutter/tests/fakes/scenic/fake_flatland_types.h, shell/platform/fuchsia/flutter/tests/flatland_external_view_embedder_unittests.cc
fxbug.dev/118729
This patchset uses the new "infinite" hit region offered by Flatland. It makes the input interceptor less error prone. 
Issue 118006
- [x I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
=> [fuchsia][scenic] Use infinite hit region

.ci.yaml, build/archives/BUILD.gn, ci/builders/windows_arm_host_engine.json, shell/platform/embedder/BUILD.gn, shell/platform/windows/client_wrapper/BUILD.gn, web_sdk/BUILD.gn
This PR adds support for windows-arm64 artifacts, using new infrastructure that will be used from January 2023, and replacing https://flutter.googlesource.com/recipes/.
I checked locally that targets are correctly built and expected zips are there 👍.
All packages can be cross compiled from an x64 machine.
Unittests are disabled, as they require an arm64 machine.
Solves this issue: https://github.com/flutter/flutter/issues/115983
[testing the …
=> Add CI builder for windows-arm64.

display_list/display_list_builder.cc
Skia is planning to remove include/core/SkMath.h from the public API.
This was the only usage of those functions that I could find. …
=> Inline usage of SkIsPow2

shell/platform/common/accessibility_bridge.cc, shell/platform/common/accessibility_bridge_unittests.cc
The line breaking attribute is currently unused, but will be needed for UIA text for Windows a11y. To keep all consecutive objects from being merged into one for screen readers, nodes will be marked as line breaking temporarily by default.
Part of https://github.com/flutter/flutter/issues/118184 …
=> Mark nodes as `kIsLineBreakingObject` by default, TODO further distinctions

DEPS, ci/licenses_golden/excluded_files, ci/licenses_golden/licenses_skia
Landing this roll manually because it seems to have failed in error and the latest hash has introduced some other errors.
related issue: https://github.com/flutter/flutter/issues/118280
https://skia.googlesource.com/skia.git/+log/b8c0a78a2378..e1f3980272f3
2023-01-09 johnstiles@google.com Add support for diagonal matrix contructors in RP codegen. 2023-01-09 jcgregorio@google.com Reboot Android devices after running a task. 2023-01-09 johnstiles@google.com Coalesce adjacent push_zeros ops. 2023-01-09 jvanverth@google.com [graphite] More steps to Recording replay for text. 2023-01-09 robertphillips@google.com Clean up compilation settings 2023-01-09 kjlubick@google.com Clear special surfaces with red color on debug tests 2023-01-09 robertphillips@google.com [graphite] Centralize Graphite …
=> Roll Skia from b8c0a78a2378 to e1f3980272f3 (24 revisions)

shell/platform/embedder/tests/embedder_gl_unittests.cc
fixes https://github.com/flutter/flutter/issues/118280
[Discord]: …
=> removed forbidden skia include

lib/ui/painting/image_descriptor.h, lib/ui/painting/image_generator.cc, lib/ui/painting/image_generator.h
`third_party/skia/src/codec/SkCodecImageGenerator.h` is not an official part of the Skia public API (yet?) and as of https://skia-review.googlesource.com/c/skia/+/627988 the Skia gn rules differentiate between public and private sources.
Because Flutter *directly* uses Skia's GN rules, we need to disable `gn check` for this one include (all other uses of private API are already guarded by `// nogncheck`
One of the two places that included `SkCodecImageGenerator.h` appeared not to need it. I cleaned up the Skia includes in both of those files.
```
$ git grep '#include "third_party/skia/src'
impeller/typographer/backends/skia/text_frame_skia.cc:#include "third_party/skia/src/core/SkStrikeSpec.h"    // nogncheck
impeller/typographer/backends/skia/text_frame_skia.cc:#include …
```
=> Cleanup Skia includes in image_generator/descriptor

shell/gpu/gpu_surface_metal_delegate.h, shell/gpu/gpu_surface_metal_skia.h, shell/platform/darwin/graphics/FlutterDarwinExternalTextureMetal.mm, testing/test_metal_context.h
Fixes https://github.com/flutter/flutter/issues/118330
Removes unnecessary includes of what is now a private Skia header file.
No tests because this is just a source compatibility change and is covered by existing unit tests.
=> delete include of private GrMtlTypes header

shell/platform/fuchsia/flutter/tests/integration/mouse-input/mouse-input-test.cc, shell/platform/fuchsia/flutter/tests/integration/text-input/text-input-test.cc, shell/platform/fuchsia/flutter/tests/integration/touch-input/touch-input-test.cc
`AddLocalChild(LocalComponent*)` is deprecated.
It was replaced by:
`AddLocalChild(LocalComponentFactory)`, which is a type alias for a lambda that returns a `std::unique_ptr<LocalComponentImpl>`.
This change addresses problems that arised due to object lifetime management of the components, and allows RealmBuilder to model the component lifecycle of local components in a way that's more consistent with other components.
The RealmBuilder-built `Realm` now owns the lifetime of the local components, instead of the client, and those objects are valid until the `Realm` is destroyed.
Bug: fxbug.dev/109804
*List which issues are fixed by this PR. You must list …
=> [fuchsia] Replace deprecated AddLocalChild

lib/web_ui/lib/src/engine/html/bitmap_canvas.dart, lib/web_ui/lib/src/engine/html/clip.dart, lib/web_ui/lib/src/engine/html/dom_canvas.dart, lib/web_ui/test/html/drawing/canvas_lines_golden_test.dart
There were several bugs with `canvas.drawLine` when using DOM rendering ([this codepath](https://github.com/flutter/engine/blob/main/lib/web_ui/lib/src/engine/html/bitmap_canvas.dart#L412-L416)):
- did not correctly render with negative `ui.Offsets` passed as parameters
- did not respect `paint.strokeCap`
- did not respect `paint.strokeWidth` for horizontal and vertical lines
according to the [api docs for `canvas.drawLine`](https://api.flutter.dev/flutter/dart-ui/Canvas/drawLine.html), rendering of lines should be the same regardless of the `paint.style`.
Previously, however, failing to set `paint.style` to type `stroke` (either by omission or setting the `paint.style` to `fill`) would cause us to use DOM rendering as specified by [this …
=> fix canvas drawLine bugs

examples/glfw/CMakeLists.txt, examples/glfw/run.sh
fixes https://github.com/flutter/flutter/issues/117406
[Discord]: …
=> fixed glfw example for arm64

shell/platform/darwin/macos/framework/Source/FlutterEngineTest.mm, shell/platform/darwin/macos/framework/Source/FlutterThreadSynchronizer.mm
Fixes https://github.com/flutter/flutter/issues/118315
[Discord]: …
=> [macOS] Do not block raster thread when shutting down

shell/common/rasterizer.cc, shell/common/rasterizer_unittests.cc, shell/gpu/gpu_surface_metal_skia.mm
Fix:
- https://github.com/flutter/flutter/issues/118088
The code 
```C++
auto frame = surface_->AcquireFrame(layer_tree.frame_size());
```
**could be very time-consuming sometimes. I think we should record it into raster time**. So that we can observe this correctly using **DevTools or `addTimingCallback` of framework side.**
**About why this operation will be time-consuming, see PR below (Still WIP & Needs triage)**
- https://github.com/flutter/engine/pull/38551
**Before patch:**
https://user-images.githubusercontent.com/49340347/210971082-6fc1c547-7c08-4ace-a8a2-2f57d97b6402.mp4
**After patch:**
https://user-images.githubusercontent.com/49340347/210971039-0b0b39a7-fc36-4c51-8a21-5ade027a122b.mp4
=> Correct FrameTimingRecorder's raster start time.

shell/platform/windows/accessibility_bridge_windows.cc, shell/platform/windows/flutter_platform_node_delegate_windows.cc, shell/platform/windows/flutter_windows.cc, shell/platform/windows/keyboard_key_embedder_handler.cc, shell/platform/windows/keyboard_key_handler.cc, shell/platform/windows/keyboard_manager.cc, shell/platform/windows/keyboard_unittests.cc, shell/platform/windows/keyboard_utils.cc, shell/platform/windows/keyboard_utils.h, shell/platform/windows/platform_handler.cc, shell/platform/windows/testing/test_binary_messenger.h, shell/platform/windows/testing/test_keyboard.cc, shell/platform/windows/text_input_manager.cc
Now that the embedders depend on FML, migrate assertions to FML_DCHECK, which allows for an explanatory log message to be emitted along with the assertion.
The log strings will slightly increase the size of debug binaries, but will not affect release binaries.
No tests since no semantic changes are made. …
=> [windows] Use FML_DCHECK in place of C assert

shell/platform/windows/flutter_window.h, shell/platform/windows/flutter_windows.cc, shell/platform/windows/flutter_windows_engine.cc, shell/platform/windows/flutter_windows_texture_registrar_unittests.cc, shell/platform/windows/flutter_windows_view_unittests.cc, shell/platform/windows/keyboard_key_embedder_handler.cc
In cd1a1cb I replaced use of direct writes to cerr and replaced them with FML_LOG calls but may have missed removing some iostream #includes, or they may have been missed in previous cleanups. This removes any remaining #includes of iostream that are unused.
No tests since no changes to semantics. …
=> [windows] Eliminate unnecessary iostream imports

lib/web_ui/lib/src/engine/canvaskit/canvaskit_api.dart, lib/web_ui/lib/src/engine/canvaskit/renderer.dart, lib/web_ui/test/canvaskit/canvaskit_api_test.dart, lib/web_ui/test/canvaskit/fragment_program_test.dart
Fixes https://github.com/flutter/flutter/issues/114260
=> [web] remove runtime effect check

lib/web_ui/lib/src/engine/canvaskit/canvaskit_api.dart, lib/web_ui/lib/src/engine/canvaskit/surface.dart, lib/web_ui/lib/src/engine/dom.dart, lib/web_ui/test/canvaskit/canvaskit_api_test.dart
Fixes https://github.com/flutter/flutter/issues/117934
Now the only expensive part is some style recalc/relayout whenever the canvas is eventually resized.
#After
=> [web] cache sample and stencil params

impeller/aiks/aiks_unittests.cc, impeller/display_list/display_list_dispatcher.cc, impeller/entity/contents/color_source_contents.cc, impeller/entity/contents/color_source_contents.h, impeller/entity/contents/scene_contents.cc, impeller/entity/contents/tiled_texture_contents.cc, impeller/entity/contents/tiled_texture_contents.h, impeller/entity/shaders/tiled_texture_fill.vert
Makes the UVs relative to the geometry origin. Discovered this issue while implementing Impeller Scene widgets.
=> [Impeller] Map UVs correctly for TiledTextureContents

lib/web_ui/lib/src/engine/semantics/tappable.dart, lib/web_ui/test/engine/semantics/semantics_test.dart
=> Wrap focus() in a post update callback in tappable

lib/web_ui/lib/src/engine/html/bitmap_canvas.dart, lib/web_ui/lib/src/engine/html/clip.dart, lib/web_ui/lib/src/engine/html/dom_canvas.dart, lib/web_ui/test/html/drawing/canvas_lines_golden_test.dart
There were several bugs with `canvas.drawLine` when using DOM rendering ([this codepath](https://github.com/flutter/engine/blob/main/lib/web_ui/lib/src/engine/html/bitmap_canvas.dart#L412-L416)):
- did not correctly render with negative `ui.Offsets` passed as parameters
- did not respect `paint.strokeCap`
- did not respect `paint.strokeWidth` for horizontal and vertical lines
according to the [api docs for `canvas.drawLine`](https://api.flutter.dev/flutter/dart-ui/Canvas/drawLine.html), rendering of lines should be the same regardless of the `paint.style`.
Previously, however, failing to set `paint.style` to type `stroke` (either by omission or setting the `paint.style` to `fill`) would cause us to use DOM rendering as specified by [this …
=> reland fix canvas drawLine bugs

impeller/aiks/aiks_unittests.cc, impeller/entity/entity_pass.cc
Because we treat the stencil buffer like a heightmap, clip restores work by flattening out everything above a certain height on the stencil buffer. This means when we have a group of contiguous clip restore entities, we can just render the last one and get identical results -- this is what we do.
We track a stack of stencil coverage rectangles to cull draw calls that obviously won't impact any pixels due to the stencil heightmap. The code that handles popping this stack assumed that the restore would always be `current_stencil_depth - 1`, which is wrong -- a single clip restore entity may reduce the stencil height by any amount, and so we need to do the same for the stencil coverage stack.
=> [Impeller] Fix contiguous clip restoration

lib/web_ui/lib/src/engine/semantics/text_field.dart, lib/web_ui/lib/src/engine/text_editing/text_editing.dart, lib/web_ui/test/engine/semantics/text_field_test.dart
=> Fix iOS safari keyboard issue when semantics is enabled

lib/ui/experiments/scene.dart
This pattern makes the node cache easier to use and more predictable in the context of an immutable widget tree. Using `Future.then` always (sometimes?) results in a new microtask that executes later, even if the value has already been resolved -- this would sometimes cause node resolution callbacks to not be executed before the node is needed, resulting in already loaded models not being drawn/flickering under some conditions.
=> [Impeller Scene] Add ability to synchronously fetch loaded ipscene nodes

display_list/display_list_builder.cc
These are both private Skia APIs and should not be directly used.
See skbug.com/13983 as the tracking bug for tightening down private APIs. …
=> Remove use of SkTAddOffset and sk_careful_memcpy

lib/web_ui/lib/src/engine/canvaskit/surface.dart
Potentially fixes https://github.com/flutter/flutter/issues/118633
The glcontext being 0 indicates we are going to use software rendering, so don't try to look up gl parameters.
=> [web] dont look up webgl params if no GPU is available

ci/licenses_golden/excluded_files, impeller/fixtures/BUILD.gn, impeller/playground/imgui/BUILD.gn, impeller/tools/BUILD.gn, impeller/tools/impeller.gni, impeller/tools/malioc.gni, impeller/tools/malioc_diff.py, tools/gn
This PR adds logic to the GN build to analyze shaders and output the analysis results in the build output directory unconditionally when the build is configured with the path to `malioc` using the `--malioc-path` flag passed to the `gn` script. `malioc` is quite fast, so this does not affect build times.
This PR also adds a script `impeller/tools/malioc_diff.py` that detects before/after changes in the results of `malioc`'s analysis, or generate a analysis results golden file. In a subsequent PR, the plan is to check in such a golden file, and then compare shader analysis results on PRs/commits against the golden file in CI.
=> Shader analysis with malioc

impeller/display_list/display_list_unittests.cc, impeller/display_list/display_list_vertices_geometry.cc
Happened across this bug while smoke testing Gallery.
Before:
After:
=> [Impeller] Account for the transform in DLVerticesGeometry coverage

shell/platform/android/external_view_embedder/external_view_embedder.cc
The SkPicture has been removed
[Discord]: …
=> Remove unused variables and import

shell/platform/linux/fl_engine.cc, shell/platform/linux/fl_engine_test.cc
Flutter locales use the BCP-47 format (https://www.rfc-editor.org/rfc/bcp/bcp47.txt), and Unix locales use a POSIX format. There is not a perfect mapping between them, see https://wiki.openoffice.org/wiki/LocaleMapping
The current implementation is not correctly setting the appropriate optional fields, so remove that.
There are likely some Unix locales that should set these fields, but these are best fixed by adding special cases for them as they are discovered.
Fixes: https://github.com/flutter/flutter/issues/111341
=> Fix invalid Unix locale to Flutter locale (BCP-47) mapping

fml/platform/win/wstring_conversion.cc, fml/platform/win/wstring_conversion.h, fml/platform/win/wstring_conversion_unittests.cc, third_party/accessibility/ax/BUILD.gn, third_party/accessibility/ax/ax_node_position_unittest.cc, third_party/accessibility/ax/platform/ax_platform_node_textprovider_win_unittest.cc, third_party/accessibility/ax/platform/ax_platform_node_textrangeprovider_win.cc, third_party/accessibility/ax/platform/ax_platform_node_win.cc, third_party/accessibility/base/string_utils.cc, third_party/accessibility/base/string_utils.h
In third_party/accessibility, for string conversion, we use a mix of:
* FML
* third_party/accessibility base string utility functions
* static functions local to the translation unit itself
This moves all conversions between UTF16 and wide strings to FML. Note that this implementation is only safe on platforms where:
* the size of wchar_t and char16_t are the same
* the encoding of wchar_t and char16_t are both UTF-16 which is the case for Windows, hence why these functions are implemented in a Windows-specific translation unit (wstring_conversion).
Issue: https://github.com/flutter/flutter/issues/118811 …
=> Extract WideToUTF16String/UTF16StringToWide to FML

fml/platform/win/wstring_conversion.cc, fml/platform/win/wstring_conversion.h, fml/platform/win/wstring_conversion_unittests.cc, third_party/accessibility/ax/BUILD.gn, third_party/accessibility/ax/ax_node_position_unittest.cc, third_party/accessibility/ax/platform/ax_platform_node_textprovider_win_unittest.cc, third_party/accessibility/ax/platform/ax_platform_node_textrangeprovider_win.cc, third_party/accessibility/ax/platform/ax_platform_node_win.cc, third_party/accessibility/base/string_utils.cc, third_party/accessibility/base/string_utils.h
=> Revert "Extract WideToUTF16String/UTF16StringToWide to FML"

impeller/aiks/aiks_unittests.cc, impeller/entity/entity_pass.cc
Just noticed this while carefully reviewing the stencil coverage stack again today. This is much more rare/a subset of the original issue that was fixed by https://github.com/flutter/engine/pull/38964, but could still result in lots of draw calls getting culled. Slightly modified the playground to detect this case too.
Before
After
=> [Impeller] Check the correct stencil coverage when deciding whether to elide a restore

shell/platform/darwin/macos/framework/Source/FlutterEmbedderKeyResponder.h, shell/platform/darwin/macos/framework/Source/FlutterEmbedderKeyResponder.mm, shell/platform/darwin/macos/framework/Source/FlutterEmbedderKeyResponderTest.mm, shell/platform/darwin/macos/framework/Source/FlutterKeyboardManager.h, shell/platform/darwin/macos/framework/Source/FlutterKeyboardManager.mm, shell/platform/darwin/macos/framework/Source/FlutterViewController.mm, shell/platform/darwin/macos/framework/Source/FlutterViewControllerTest.mm
This PR implements modifier keys states synchronization based on pointer events.
It is the MacOS implementation for https://github.com/flutter/flutter/issues/115066.
https://github.com/flutter/flutter/issues/115066
Adds 1 test.
=> [macos] Synthesize modifier keys events on pointer events

impeller/entity/contents/filters/blend_filter_contents.cc, impeller/entity/contents/filters/color_filter_contents.cc, impeller/entity/contents/filters/color_filter_contents.h, impeller/entity/entity_pass.cc, impeller/entity/entity_unittests.cc, impeller/entity/shaders/blending/advanced_blend.glsl
Fixes https://github.com/flutter/flutter/issues/118903
Both pipeline and advanced blends internally used the order dst, src, src, however the ColorFilterContents::MakeFilter would jumble the order and the only usage in the engine compensated for this.
(Of course, still need to double check)
=> [impeller] change input order in ColorFilterContents::MakeBlend

shell/platform/darwin/ios/framework/Source/FlutterPlatformViews.mm, shell/platform/darwin/ios/framework/Source/FlutterPlatformViewsTest.mm, shell/platform/darwin/ios/framework/Source/FlutterPlatformViews_Internal.h, shell/platform/darwin/ios/framework/Source/FlutterPlatformViews_Internal.mm
The maskViews are constructed and destructed every frame for every PlatformView on the screen. It slows down the performance quite a lot.
This PR adds a pool that caches maximum of 5 maskViews. These maskViews are reused every frame.
If there are more than 5 maskViews required in a frame, extra maskViews are constructed and destructed each frame. (This scenario is very unlikely in real life application)
Part of https://github.com/flutter/flutter/issues/116640 …
=> [ios_platform_view] MaskView pool to reuse maskViews.

lib/ui/painting.dart, lib/web_ui/lib/painting.dart, testing/dart/codec_test.dart
This adds a new `instantiateImageCodecWithSize` method, which can be used to decode an image into a size, where the target size isn't known until the caller is allowed to inspect the image descriptor.
This enables the use case of loading an image whose aspect ratio isn't known at load time, and which needs to be resized to fit within a bounding box while also maintaining its original aspect ratio.
https://github.com/flutter/flutter/issues/118543
=> Add more flexible image loading API

lib/ui/hash_codes.dart
Part of https://github.com/flutter/flutter/issues/118837.
Related to https://github.com/flutter/flutter/pull/118849.
Dart 3 drops support for non-null safe code, so we can finally turn on the unnecessary_null_comparison lint and remove the unnecessary checks it flags.
=> Remove unnecessary null checks in doc snippet

impeller/entity/contents/runtime_effect_contents.cc, impeller/entity/entity_unittests.cc, impeller/fixtures/runtime_stage_example.frag
Fixes https://github.com/flutter/flutter/issues/118847
When reading from the uniform buffer account for vec2/3/4 uniforms being larger than a single float.
=> [Impeller] uniform offsets account for size

shell/platform/embedder/embedder.cc, shell/platform/embedder/tests/embedder_config_builder.cc
Vulkan embedder was incorrectly querying vkGetInstanceProcAddr without the vk prefix. Tests would not catch this because embedder tests were assuming that get_instance_proc_address_callback is only ever called to obtain vkGetInstanceProcAddr, and so just returned that function unconditionally.
Fixes: https://github.com/flutter/flutter/issues/118956
=> [embedder] Fix getting vkGetInstanceProcAddr

lib/ui/hash_codes.dart
Follow-up to https://github.com/flutter/engine/pull/39071.
Missing `!` was discovered in failing engine roll https://github.com/flutter/flutter/pull/119037.
=> Fix doc analyzer breakage

flutter_frontend_server/pubspec.yaml
In a follow-up change in Dart SDK, package:compiler (a dependency of flutter_frontend_server) will start using package:mmap
=> Add mmap dependency to flutter_frontend_server

lib/ui/compositing.dart, lib/ui/dart_ui.cc, lib/ui/experiments/scene.dart, lib/ui/isolate_name_server.dart, lib/ui/natives.dart, lib/ui/painting.dart, lib/ui/platform_dispatcher.dart, lib/ui/semantics.dart, lib/ui/text.dart, lib/ui/window.dart, third_party/tonic/tests/fixtures/tonic_test.dart
Migrates `@FfiNative` to `@Native`.
* https://github.com/flutter/flutter/issues/118794 …
=> Migrate `@FfiNative` to `@Native`

shell/platform/common/client_wrapper/include/flutter/method_channel.h, shell/platform/common/public/flutter_messenger.h, shell/platform/windows/flutter_windows.cc
The previous `MethodCall` documentation made it seem like you *must* unregister handlers. This is not  necessary during engine shutdown as that causes a crash after https://github.com/flutter/engine/pull/36909. This attempts to improve the comments & crashes for clarity.
See the conversation in https://github.com/flutter/engine/pull/38941
New crash messages:
```
[FATAL:flutter/shell/platform/windows/flutter_windows.cc(301)] Check failed: FlutterDesktopMessengerIsAvailable(messenger). Messenger must reference a running engine to set a callback
```
```
[FATAL:flutter/shell/platform/windows/flutter_windows.cc(268)] Check failed: FlutterDesktopMessengerIsAvailable(messenger). Messenger must reference a running engine to send a message
```
Addresses …
=> Improve crashes if messenger APIs are used incorrectly

impeller/entity/contents/text_contents.cc, impeller/entity/shaders/glyph_atlas.frag, impeller/entity/shaders/glyph_atlas.vert
Resolves https://github.com/flutter/flutter/issues/118613.
* Remove residual position offsets. These were used to help mitigate the infamous glyph overlap problem, which has since been solved.
* Always pixel snap the source position.
* Switch from linear sampling to nearest sampling.
Before (top), after (bottom):
Before:
After:
=> [Impeller] Switch to nearest sampling for the text atlas

impeller/entity/contents/text_contents.cc, impeller/geometry/geometry_unittests.cc, impeller/geometry/matrix.h
Follow-up to https://github.com/flutter/engine/pull/39104.
Before:
After:
=> [Impeller] Linear sample atlas glyphs when the CTM isn't translation/scale only

BUILD.gn, lib/snapshot/BUILD.gn, shell/platform/android/BUILD.gn
To unblock the Dart SDK -> Engine roll.
=> Only build analyze_snapshot on Linux host

impeller/aiks/aiks_unittests.cc, impeller/compiler/shader_lib/impeller/transform.glsl
Resolves https://github.com/flutter/flutter/issues/117428.
Whoops, forgot to account for the Z basis.
Before:
After:
=> [Impeller] Make text glyph offsets respect the current transform

flow/layers/image_filter_layer.cc, flow/layers/image_filter_layer_unittests.cc
When ImageFilter is drawn from raster-cache, the offset is in effect getting applied twice, so the resulting content is in the wrong position. Since the offset is baked into the raster-cache entry, it shouldn't be applied if drawing from there.
Fixes [#111863](https://github.com/flutter/flutter/issues/111863)
=> Fix position of ImageFilter layer when raster-cached

impeller/renderer/backend/vulkan/context_vk.cc, impeller/renderer/backend/vulkan/swapchain_details_vk.cc, impeller/tools/impeller.gni
* Disables modern features as SSBOs are wired on Vulkan yet.
* Sub-optimal presentation mode must not be a fatal issue.
* Allow for shader outputs not to be consumed.
=> Get the vulkan backend working again

shell/platform/darwin/macos/framework/Headers/FlutterEngine.h, shell/platform/darwin/macos/framework/Headers/FlutterViewController.h, shell/platform/darwin/macos/framework/Source/AccessibilityBridgeMacTest.mm, shell/platform/darwin/macos/framework/Source/FlutterCompositor.h, shell/platform/darwin/macos/framework/Source/FlutterEngine.mm, shell/platform/darwin/macos/framework/Source/FlutterEngineTest.mm, shell/platform/darwin/macos/framework/Source/FlutterPlatformNodeDelegateMacTest.mm, shell/platform/darwin/macos/framework/Source/FlutterTextInputPluginTest.mm, shell/platform/darwin/macos/framework/Source/FlutterTextInputSemanticsObjectTest.mm, shell/platform/darwin/macos/framework/Source/FlutterView.h, shell/platform/darwin/macos/framework/Source/FlutterViewController.mm, shell/platform/darwin/macos/framework/Source/FlutterViewControllerTest.mm, shell/platform/darwin/macos/framework/Source/FlutterViewController_Internal.h, shell/platform/darwin/macos/framework/Source/FlutterViewProvider.h
Reland https://github.com/flutter/engine/pull/38981. 
Fixed a test that was introduced in https://github.com/flutter/engine/pull/37870 but used the legacy convention.  …
=> Reland "[macOS] Formalize FlutterViewController's initialization flow, and prohibit replacing"

impeller/display_list/display_list_unittests.cc, impeller/entity/geometry.cc, impeller/geometry/path.cc, impeller/geometry/path.h, impeller/geometry/path_component.cc, impeller/geometry/path_component.h
Resolves https://github.com/flutter/flutter/issues/118945.
* Instead of using the direction from/to the start/end points of the contour for a cap normal, use the curve's analytical start/end tangent for perfect results.
* Append points to draw the `Cap::kButt` cap, since it may no longer align perfectly with the last line segment direction.
* This also fixes similar slightly wrong results for closed path shapes such as ovals when using `Cap::kButt`.
Before:
https://user-images.githubusercontent.com/919017/214541644-6f8b0414-4c50-4d50-aafe-1b100dace66e.mov
After:
https://user-images.githubusercontent.com/919017/214541675-207324f2-af59-4c21-bc14-68c720bfd0c8.mov
=> [Impeller] Use the start/end tangent of contours to compute stroke contour cap normals

ci/compatibility_helper.py, ci/firebase_testlab.py, ci/scan_flattened_deps.py, testing/run_tests.py
Python 2 is going to be deprecated so we are making infrastructure code python 2 and python 3 compatible. Changes on the recipes side have already been merged.
TODO find/add issue. …
=> Update infrastructure python code to be compatible with python 2 and python 3

impeller/compiler/compiler.cc, impeller/entity/contents/runtime_effect_contents.cc, testing/dart/fragment_shader_test.dart
Part of https://github.com/flutter/flutter/issues/119173. The runtime IPLR contains all of the infromation to handle samplers without remaping. Its just a bit awkward to use at this point.
As a follow up will make location data take into account this offset and delete the flag (after rolling into tool).
Separately, we should investigate if enabling vulkan regressed any other functionality on macOS.
=> [Impeller] partially remove remap sampler support

shell/platform/linux/fl_view.cc
This PR contains the engine-side changes required for changing the Linux app template to show the window after registering plugins (flutter/flutter#118269).
Currently, `FlView` assumes that it gets realized before its size gets allocated. If we change the order in the app template, the view gets added to a layout first and then realized. Make sure to call `handle_geometry_changed()` from both and check the pre-conditions for `fl_renderer_wait_for_frame()` to ensure that the first frame is rendered regardless of the order of `size-allocate` and `realize`.
This makes it possible to change [my_application.cc](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/templates/app_shared/linux.tmpl/my_application.cc.tmpl) as follows:
```diff
diff --git a/linux/my_application.cc …
```
=> [Linux][FlView] fix rendering on startup when shown after plugin registration

shell/platform/darwin/macos/framework/Source/FlutterTextInputPlugin.mm, shell/platform/darwin/macos/framework/Source/FlutterTextInputPluginTest.mm
TextInputPlugin must be visible and in view hierarchy for emoji picker to work. This is trivial change that moves it completely outside of visible area.
Fixes https://github.com/flutter/flutter/issues/118504
[testing the …
=> [macos] Move TextInputPlugin outside of visible area

shell/platform/darwin/macos/framework/Source/FlutterTextInputPlugin.mm, shell/platform/darwin/macos/framework/Source/FlutterTextInputPluginTest.mm
Reverts flutter/engine#39031
Seems responsible for the test failure on CI here: https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20Production%20Engine%20Drone/23111/overview
=> Revert "[macos] Move TextInputPlugin outside of visible area"

shell/platform/embedder/embedder.h, shell/platform/embedder/pixel_formats.cc, shell/platform/embedder/tests/embedder_assertions.h, shell/platform/embedder/tests/embedder_config_builder.h, shell/platform/embedder/tests/embedder_test_backingstore_producer.cc, shell/platform/embedder/tests/embedder_test_backingstore_producer.h, shell/platform/embedder/tests/embedder_unittests.cc
Renames the `FlutterSoftwarePixelFormat` enum values of `flutter_embedder.h`:
```
kGray8 --> kFlutterSoftwarePixelFormatGray8
kRGB565 --> kFlutterSoftwarePixelFormatRGB565
...
```
Fixes https://github.com/flutter/flutter/issues/118247. …
=> properly namespace flutter software pixel formats

shell/platform/fuchsia/flutter/tests/integration/utils/portable_ui_test.cc
See https://fxrev.dev/793422.
Missed in d85ec02b0d25f8b3c2a45d1879846bbe9d19ab33.
=> [fuchsia] Migrate to new RealmBuilder API

impeller/geometry/geometry_unittests.cc, impeller/geometry/size.h
Fixes https://github.com/flutter/flutter/issues/119245
Before mipcount of 1x1 image would be 0, resulting in invalid texture
=> [Impeller] ensure 1x1 has mipcount of 1

examples/vulkan_glfw/CMakeLists.txt, examples/vulkan_glfw/src/main.cc
Fix a just outright syntax error in CMakeLists of vulkan_glfw and specify a missing include for std::chrono stuff.
Fixes: https://github.com/flutter/flutter/issues/118957
=> Fix Vulkan embedder example

impeller/compiler/impellerc_main.cc, impeller/compiler/source_options.h, impeller/compiler/switches.cc, impeller/compiler/switches.h, impeller/tools/impeller.gni, lib/ui/fixtures/shaders/BUILD.gn
Usage removed in https://github.com/flutter/flutter/pull/119346
=> [impellerc] remove remaining remap sampler support

testing/ios/IosUnitTests/Tests/FlutterEngineConfig.xcconfig
When running `IosUnitTests`, default to the arm64 simulator engine variant when running on an arm64 simulator.
https://github.com/flutter/flutter/wiki/Testing-the-engine#xctest-unit-tests
Resolves to:
https://developer.apple.com/documentation/xcode/adding-a-build-configuration-file-to-your-project?changes=_8#Apply-a-setting-conditionally-to-a-platform-or-architecture
Inspired by https://github.com/flutter/flutter/issues/119373 …
=> Use arm64 engine variant on simulators in iOS unit tests

testing/scenario_app/run_ios_tests.sh
Similar to https://github.com/flutter/engine/blob/f03b123740acd6d6a888439e3cea3e3384711249/examples/glfw/run.sh#L4-L8
https://github.com/flutter/engine/pull/38426
Fixes https://github.com/flutter/flutter/issues/119373 …
=> Default to running the scenario tests on an arm iOS simulator variant on an Apple Silicon host Mac

lib/web_ui/dev/build.dart, tools/gn
Doing `felt build --build-canvaskit-chromium` will cause the Chromium variant of CanvasKit to be built.
Fixes https://github.com/flutter/flutter/issues/118744
=> [web] Expose felt flag for building CanvasKit Chromium

impeller/entity/contents/runtime_effect_contents.cc, impeller/entity/entity_unittests.cc, impeller/fixtures/runtime_stage_example.frag
Cherry-pick PR of https://github.com/flutter/engine/commit/42eec6280719394db1b30bf3284b3fc7780588cb for `flutter-3.7-candidate.1`
=> [CP] [Impeller] uniform offsets account for size (#39077)

shell/platform/windows/flutter_window_unittests.cc
Removes dead code in the `FlutterWindow` unit tests. …
=> [Windows] Remove dead code from FlutterWindow tests

shell/platform/windows/keyboard_unittests.cc
This makes the Windows keyboard tests use the new `FlutterWindowsEngineBuilder` to create an engine to test against. This will make testing easier when the keyboard & text plugins are moved up from the view to the engine. …
=> [Windows] Use 'FlutterWindowsEngineBuilder' in keyboard unit tests

shell/platform/darwin/macos/framework/Headers/FlutterEngine.h, shell/platform/darwin/macos/framework/Source/AccessibilityBridgeMacTest.mm, shell/platform/darwin/macos/framework/Source/FlutterEngine.mm, shell/platform/darwin/macos/framework/Source/FlutterEngineTest.mm, shell/platform/darwin/macos/framework/Source/FlutterEngine_Internal.h, shell/platform/darwin/macos/framework/Source/FlutterPlatformNodeDelegateMacTest.mm, shell/platform/darwin/macos/framework/Source/FlutterTextInputPluginTest.mm, shell/platform/darwin/macos/framework/Source/FlutterTextInputSemanticsObjectTest.mm, shell/platform/darwin/macos/framework/Source/FlutterViewController.mm, shell/platform/darwin/macos/framework/Source/FlutterViewController_Internal.h
This PR moves `AccessibilityBridgeMac` from `FlutterEngine` to `FlutterViewController`.
Currently, whether `FlutterEngine` has a non-null `AccessibilityBridge` only depends on the value of `semanticsEnabled`. The `_bridge` is initialized the moment `semanticsEnabled` turns true, even if `viewController` is null. Similarly, setting the view controller to null does not affect `_bridge` either. This is problematic because conceptually an `AccessibilityBridge` manages the a11y information for one view. Accessibility information does not make much sense without a view.
By moving the `AccessibilityBridge` into `FlutterViewController`, the lifecycles of these 2 classes are tied. The bridge exists only when the view controller exists _and_ semantics has been enabled. This is important because …
=> [macOS] Move A11yBridge to FVC

tools/fuchsia/merge_and_upload_debug_symbols.py
Update python subprocess checkout output code to transform output to string for regex check in CheckCIPDPackageExists method. …
=> Python 3 code updates for str and byte operations

shell/platform/fuchsia/dart_runner/meta/common.shard.cml, shell/platform/fuchsia/flutter/meta/common.shard.cml
This reverts commit 225ae87334a5df010dc21b2c2dc7063cd65e2265.
The related CL https://fuchsia-review.git.corp.google.com/c/fuchsia/+/792471 is being reverted as well: https://fuchsia-review.git.corp.google.com/c/fuchsia/+/794843
=> Revert "[fuchsia] Diagnostics directory rights are R* (#39203)"

lib/web_ui/dev/utils.dart
TLDR: this fixes the breakages in the web engine build. such as https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Web%20Engine/15016/overview
long story:
Web failure
We are trying to land 8 engine cherry picks, but linux web engine was failing on the release branches with a deprecation warning
Casey pointed me to Zach on post submit failures. Zach added me to flutter web channel, and connected me with Yegor. 
At first the error was thought to be a flake or a recipe version mismatch. Examining build history and recipe versions were fruitless. 
The cherry picked engine pr doesn’t relate to the web failure, so initially the failure was suspected to be caused by dart changes on the release branch. And Zach connected us with Siva. we examined dart commits between dart main -> dev -> …
=> [flutter release + cherry pick] @alwaysThrows is deprecated. Return `Never` instead. (#39269)

impeller/aiks/aiks_unittests.cc, impeller/entity/entity_pass.cc
CP of https://github.com/flutter/engine/commit/730e88fb67878fbfdb9bb60545fecdb2990bc9fd for `flutter-3.7-candidate.1`
=> [CP] [Impeller] Check the correct stencil coverage when deciding whether to elide a restore

impeller/aiks/aiks_unittests.cc, impeller/compiler/shader_lib/impeller/transform.glsl
CP of https://github.com/flutter/engine/commit/30c02e4c8b01380f6e1457af141c694d02798fd7 for `flutter-3.7-candidate.1`
=> [CP] [Impeller] Make text glyph offsets respect the current transform

.ci.yaml
This is in preparation for changes that will use `--local-web-sdk` instead of `--local-engine` for the web framework tests.
=> Download emsdk for web framework tests.

flow/layers/image_filter_layer.cc, flow/layers/image_filter_layer_unittests.cc
* Fix position of ImageFilter layer when raster-cached
* Move integral transform and add tests
* Don't round in Preroll …
=> Fix position of ImageFilter layer when raster-cached (#38567)

lib/web_ui/test/matchers.dart
=> [web] Remove unused test helper: expectPageHtml

lib/web_ui/lib/src/engine/html/path_to_svg_clip.dart, lib/web_ui/test/html/canvas_clip_path_golden_test.dart
When using DOM rendering with HTML renderer, specifying `path.fillType` to `evenOdd` had no effect.
Fixed so that we account for the `fillType` param for a path. 
fixes: https://github.com/flutter/flutter/issues/81637 …
=> clipPath to use fillType param

runtime/platform_data.h, shell/common/shell.h
Follow-up to https://github.com/flutter/engine/pull/38453, part of https://github.com/flutter/flutter/issues/112204 …
=> [Shell] Update stale comments after multi-view

tools/gn
This is needed to use arm64 macs in CI, and for the reasons noted in the comment.
=> Use the x64 toolchain when building host artifacts on arm64 mac

shell/platform/windows/flutter_windows_engine.cc, shell/platform/windows/settings_plugin.cc, shell/platform/windows/settings_plugin.h, shell/platform/windows/settings_plugin_unittests.cc
`MaterialApp` has a `highContrastTheme` and a `highContrastDarkTheme`. Currently, on windows, which of these to use is based on whether or not dark mode for apps is enabled. However, the app dark mode setting is independent of the high contrast theme, which may be black or white. Now, check the high contrast theme to determine which `MaterialApp` theme to use when high contrast mode is enabled.
[flutter/flutter#75883](https://github.com/flutter/flutter/issues/75883) …
=> Use Windows high contrast black/white theme with `MaterialApp` themes

DEPS
This is to integrate exp, pdb and lib file to win library outputs.
Bug: https://github.com/flutter/flutter/issues/119663 …
=> Roll buildroot to #75f75b73.

tools/gn
The engine's Visual Studio integration is currently broken. See: https://groups.google.com/a/chromium.org/g/chromium-dev/c/027jM6DLkIk
> For Developers who build on Windows, instead of calling “ninja.exe”, please call “ninja” to resolve the [depot_tools/ninja.bat](https://crsrc.org/d/ninja.bat) wrapper.
Note that the Visual Studio integration won't be fixed until [depot_tools#4215121](https://chromium-review.googlesource.com/c/chromium/tools/depot_tools/+/4215121) lands.
Part of: https://github.com/flutter/flutter/issues/119760 …
=> [Windows] Use 'ninja' instead of 'ninja.exe'

lib/web_ui/test/engine/view_embedder/dimensions_provider/custom_element_dimensions_provider_test.dart
This fixes https://github.com/flutter/flutter/issues/119757
=> Don't rely on timings for dimension_provider unit test.

lib/web_ui/lib/src/engine/text/canvas_paragraph.dart, lib/web_ui/test/text/canvas_paragraph_builder_test.dart
Handling RTL text in the HTML renderer was introduced by https://github.com/flutter/engine/pull/26811.
It seems that there is a missing piece related to mirrored characters (see https://www.w3.org/International/articles/inline-bidi-markup/uba-basics#mirroring).
This PR adds this feature by relying on the HTML “dir” attribute.
Here is a simplified sample (compared to the one in https://github.com/flutter/flutter/issues/108431) to illustrate the issue:
<details>
<summary>Code sample</summary>
```dart
void main() {
runApp(const MyApp());
}
const MyApp({Key? key}) : super(key: key);
@override
return const MaterialApp(
title: 'Flutter Demo',
home: MyHomePage(), …
```
=> [Web][HTML] Add mirrored characters support for RTL languages

impeller/entity/entity_pass.cc
"Resolves" https://github.com/flutter/flutter/issues/119289.
Rather than expanding the layer to account for subpixel offsets, cut away partially covered edge pixels of subpass textures. This is a tiny fidelity compromise to behave more like Skia does for filtered savelayers.
Impeller before:
https://user-images.githubusercontent.com/919017/216296837-19593b7c-05af-4477-955b-819183973a6f.mov
Impeller after:
https://user-images.githubusercontent.com/919017/216294182-46f90dd6-aed2-4106-9514-432789b10452.mov
This isn't a perfect result, but it at least closely matches the behavior of Skia.
Skia:
https://user-images.githubusercontent.com/919017/216294269-310c4a83-19b4-485b-9c1f-f55edbe0d65b.mov
=> [Impeller] Don't ceil subpass texture sizes

DEPS
The protobuf GN templates that the Dart SDK uses produce depfiles with multiple outputs. This was only supported in `ninja 1.10.0` (https://github.com/ninja-build/ninja/issues/1184#issuecomment-579804128)
=> Bump ninja version to 1.11.1

impeller/entity/contents/clip_contents.cc, impeller/entity/contents/clip_contents.h, impeller/entity/contents/linear_gradient_contents.cc, impeller/entity/contents/radial_gradient_contents.cc, impeller/entity/contents/runtime_effect_contents.cc, impeller/entity/contents/solid_color_contents.cc, impeller/entity/contents/sweep_gradient_contents.cc, impeller/entity/contents/tiled_texture_contents.cc
I'm hoping this'll eliminate much of the delta in https://github.com/flutter/flutter/issues/119881#issuecomment-1414812797.
Up until now, clip restores have always just covered the whole render target. But in some cases (like with overdraw prevention when drawing stroke paths), the restore area may be comparatively tiny. In the reduced test case linked above, this is a worst case scenario, because each dash takes up only a tiny sliver of pixels, and the interleaving restores repeatedly hammer the raster pipeline by stencil checking the whole screen.
Frame capture times haven't been historically reliable for me, but I seem to be getting a consistent order of magnitude difference on my iPhone 12 mini.
As an aside, I may come back around and try to refactor the overdraw prevention bits for …
=> [Impeller] Use minimal coverage for stencil restores after overdraw prevention

DEPS
This updates buildroot to https://github.com/flutter/buildroot/commit/39b486f75e13b0b9b07f4480fc4c9fac3cfc8759
=> Roll buildroot to 39b486f7

third_party/accessibility/ax/platform/ax_platform_node_win.cc, third_party/accessibility/ax/platform/ax_platform_node_win.h, third_party/accessibility/ax/platform/ax_platform_node_win_unittest.cc
When a checkbox has its state changed, fire a UIA property change event for the toggle state property, so that screen readers can read the updated state.
Part of https://github.com/flutter/flutter/issues/119350. I still need to confirm what the appropriate behavior should be when hitting NVDA+UP when focusing on a checkbox before I can potentially close that issue.
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#st …
=> Fire UIA event on Checkbox state change

shell/platform/fuchsia/flutter/component_v1.cc, shell/platform/fuchsia/flutter/component_v2.cc
fdio_service_connect no longer provides rights. Since we need the READABLE right when opening the debug/ctrl/diagnostics directories, this change uses fdio_open_at.
This change also fixes the Clone to remove specific rights and instead use CLONE_SAME_RIGHTS.
Verified locally that we no longer get ACCESS_DENIED on the diagnostics directory when opening in component manager. …
=> [fuchsia] fdio_service_connect no longer provides rights which we need

shell/platform/darwin/ios/framework/Source/VsyncWaiterIosTest.mm, shell/platform/darwin/ios/framework/Source/vsync_waiter_ios.h, shell/platform/darwin/ios/framework/Source/vsync_waiter_ios.mm
When there are PlatformViews on the screen (threads merged), Flutter engine cannot consistently hit 120 fps, especially when the PlatformView is animating (scrolling etc), thus producing janks. 
This PR locks the refresh rate to 80fps to avoid janks.
Fixes https://github.com/flutter/flutter/issues/116640 …
=> [ios] Lock refresh rate to 80fps when threads are merged

impeller/typographer/backends/skia/text_frame_skia.cc, impeller/typographer/backends/skia/text_render_context_skia.cc, impeller/typographer/font.h
Resolves: https://github.com/flutter/flutter/issues/119489
These options are more like implementation hacks we use to tickle Skia into rendering text the way we want. They're not generally applicable to fonts/typefaces, and so I'm working on a patch that just makes us hold onto a backend-specific font resource instead of decomposing/reconstructing from metrics. In the meantime, this patch fixes the most egregious rendering error.
I had some trouble getting a repro of this issue in a playground, but I'll add one in a follow-up if I end up getting one working.
Before:
After:
=> [Impeller] Retain embolden/skew font properties when rendering text glyphs

shell/platform/darwin/ios/framework/Source/FlutterView.mm, shell/platform/darwin/ios/framework/Source/FlutterViewTest.mm
To Fix
- https://github.com/flutter/flutter/issues/103847
This looks crazy. 
I think that the view's background color is something related with CoreAnimation and `CAMetalDrawable` also related with it. And the thing draw's on it. Change it to a color not nil maybe have something to do with present behavior. So just set it to UIColor.clearcolor which is the same visually but can help reduce junk a lot.
Below video is tested on iPhone 13 Pro with local compiled engine in debug mode.
After this change the constant junk will reduce a lot on iOS.
https://user-images.githubusercontent.com/49340347/216589281-9a0b4b02-af44-419d-b186-a571e84b9022.mp4
https://user-images.githubusercontent.com/49340347/216589285-18b7d207-cae9-4d70-b219-3fc589251742.mp4
=> [iOS] Ensure FlutterView's background color is not nil to avoid CAMetalLayer nextDrawable being time-consuming

tools/fuchsia/fuchsia_archive.gni, tools/fuchsia/fuchsia_libs.gni
Fixes issue with missing .so files being thrown when attempting to run integration tests with ASAN enabled
=> [fuchsia] Add output_path property to customize output path of .so files

impeller/typographer/backends/skia/text_frame_skia.cc, impeller/typographer/backends/skia/text_render_context_skia.cc, impeller/typographer/font.h
Resolves https://github.com/flutter/flutter/issues/119234.
Resolves https://github.com/flutter/flutter/issues/119805.
I think what's going on here is that Skia applies a curve to the antialiased edges of text based on its color (see [this old chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=898928), for example). Since we were asking Skia to draw white text, it biased the edges towards being more saturated.
By flipping the paint color from white to black, Skia's antialiasing behaves like we're drawing black text, which does the opposite.
This makes black text on a white background look almost identical to Skia, but note that white text now looks a bit too thin (seems like a better outcome than making the text too thick?).
For a more perfect solution, we can incorporate …
=> [Impeller] Make dark text appear less emboldened

shell/platform/windows/client_wrapper/BUILD.gn
This is to place the files in the correct files. $source variable is being overridden with the full path. It also includes missing header files.
Bug: https://github.com/flutter/flutter/issues/120058 …
=> Fix cpp-wrappers archive.

shell/platform/windows/flutter_windows_view_unittests.cc, shell/platform/windows/keyboard_unittests.cc
The `FlutterWindowsViewTest.RestartClearsKeyboardState` test used to verify that restarting the engine reset the keyboard's state. This test was broken some time ago but still passed. This change fixes the test.
[CLA]: …
=> [Windows] Fix the 'engine restart resets keyboard' test

impeller/aiks/aiks_unittests.cc, impeller/entity/shaders/glyph_atlas.frag
Fixes https://github.com/flutter/flutter/issues/119672
=> [impeller] ensure full color glyphs respect alpha

shell/platform/darwin/ios/framework/Source/SemanticsObject.h, shell/platform/darwin/ios/framework/Source/SemanticsObject.mm, shell/platform/darwin/ios/framework/Source/SemanticsObjectTest.mm, shell/platform/darwin/ios/framework/Source/accessibility_bridge.mm, shell/platform/darwin/ios/framework/Source/accessibility_bridge_test.mm
issue: https://github.com/flutter/flutter/issues/113377
The issue is that for overlapping semantics  (e.g. a stack)
Before IOS 16, the focus goes to the smallest object.
In IOS 16, the focus goes to the top-left object.
This is an IOS bug and we can reproduce it by writing an sample IOS application with UIAccessibilityElement.
Under the hood, iOS calls a private method -[UIViewAccessibility _accessibilityHitTest:withEvent:] is used to determine which element is hit tested.
This PR is to override this private method to change the focus behavior and fix the issues. …
=> Override _accessibilityHitTest to fix IOS 16 semantics issues 

shell/platform/common/accessibility_bridge.cc, shell/platform/common/accessibility_bridge.h, shell/platform/common/accessibility_bridge_unittests.cc, shell/platform/windows/flutter_windows_view_unittests.cc
Today, the root accessibility semantics node is guaranteed to have ID 0. In a multi-window world, each view will have its own semantics tree, but semantic node IDs will be globally unique. In other words, the semantics tree's root will no longer be guaranteed to have ID 0.
This change removes the "root ID is 0" assumption from the Windows embedder. Note that other embedders (macOS, iOS, Fuchsia, etc...) also need updates, which will be done in follow-up PRs.
Part of https://github.com/flutter/flutter/issues/119391
<details>
<summary>Manual test...</summary>
Apply the framework patch below, run an app, and verify the accessibility works as expected:
```diff
diff --git a/packages/flutter/lib/src/semantics/semantics.dart b/packages/flutter/lib/src/semantics/semantics.dart
index …
```
=> [Windows] Remove accessibility root assumptions

shell/platform/darwin/ios/framework/Source/FlutterView.mm, shell/platform/darwin/ios/framework/Source/FlutterViewTest.mm
Cherry-pick of https://github.com/flutter/engine/pull/39359 by @luckysmg.
https://github.com/flutter/flutter/issues/120130
=> Cherry-pick Avoid animation jank by setting FlutterViewController backgroundColor to clearColor

shell/platform/darwin/macos/framework/Source/FlutterTextInputPlugin.mm, shell/platform/darwin/macos/framework/Source/FlutterTextInputPluginTest.mm
By default, autocomplete is enabled during text input on macOS. On Macs with the touchbar enabled, the current text input and any suggested autocompletions are listed in the touchbar.
This adds support for disabling autocomplete when autofill is disabled, when obscureText is set in the text input configuration, and when the autofill hint type is "password" or "username". When an AutofillGroup is in use, we disable autocomplete for all fields within the group when any of the fields disables autocomplete.
While OS-level autocomplete support is far more robust on iOS, this behaviour matches out enable/disable state management behaviour on that platform.
Issue: https://github.com/flutter/flutter/issues/119824 …
=> [macOS] Support text input autocomplete

impeller/display_list/display_list_unittests.cc, impeller/entity/geometry.cc, impeller/entity/geometry.h
Fix:
- https://github.com/flutter/flutter/issues/119810
**Before:**
**After:**
**Before:**
https://user-images.githubusercontent.com/49340347/217441198-563c7e12-900b-40a2-bdc9-1304950978ef.mp4
**After:**
https://user-images.githubusercontent.com/49340347/217441215-0febf1bf-7399-41c9-a1bb-0faa20d8c835.mp4
=> [Impeller] Fix stroke cap drawing not correct.

shell/platform/android/io/flutter/embedding/android/FlutterActivityAndFragmentDelegate.java, shell/platform/android/io/flutter/embedding/engine/systemchannels/NavigationChannel.java, shell/platform/android/io/flutter/view/FlutterView.java, shell/platform/android/test/io/flutter/embedding/android/FlutterActivityAndFragmentDelegateTest.java, shell/platform/darwin/ios/framework/Source/FlutterAppDelegate.mm, shell/platform/darwin/ios/framework/Source/FlutterAppDelegateTest.mm
Related https://github.com/flutter/flutter/issues/100624
The end goal is to send entire uri to the framework without introducing breaking change. The pushRoute API takes a fixed string that contains everything after the authority and is hard to extend. Therefore migrate both embedding to more flexible pushRouteInformation API …
=> Migrate iOS and Android to use pushRouteInformation

impeller/display_list/display_list_dispatcher.cc, impeller/entity/contents/contents.cc, impeller/entity/contents/contents.h, impeller/entity/contents/filters/blend_filter_contents.cc, impeller/entity/contents/filters/filter_contents.cc, impeller/entity/contents/filters/filter_contents.h, impeller/entity/contents/filters/inputs/contents_filter_input.cc, impeller/entity/contents/texture_contents.cc, impeller/entity/contents/texture_contents.h, impeller/renderer/sampler_descriptor.cc, impeller/renderer/sampler_descriptor.h, impeller/renderer/snapshot.h
Resolves https://github.com/flutter/flutter/issues/118614.
Resolves https://github.com/gskinnerTeam/flutter-wonderous-app/issues/69.
* Add a `Contents::RenderToSnapshot` sampler descriptor param, so that `TextureContents::RenderToSnapshot` can apply the right sampler settings even when it's unable to passthrough.
* Make the blend filter apply the snapshot's sampling mode when rendering. Then, use nearest sampling for the final render (since the blend filter absorbs the transform).
* Treat the Cubic DL sampling mode as Linear instead of falling back to Nearest. Impeller doesn't support `kCubic` sampling (and perhaps we shouldn't).
* Make a default snapshot SamplerDescriptor have a clear label so that it's easy to spot in GPU captures.
=> [Impeller] Fix sampling management problems

shell/platform/darwin/ios/framework/Source/FlutterPlatformViews.mm, shell/platform/darwin/ios/framework/Source/FlutterPlatformViewsTest.mm, shell/platform/darwin/ios/framework/Source/FlutterPlatformViews_Internal.h, shell/platform/darwin/ios/framework/Source/FlutterPlatformViews_Internal.mm
Relands https://github.com/flutter/engine/pull/38989 because the revert didn't affect the benchmark. 
https://flutter-flutter-perf.skia.org/e/?queries=arch%3Dintel%26branch%3Dmaster%26device_type%3DiPhone_11%26host_type%3Dmac%26sub_result%3Daverage_gpu_usage%26test%3Dbackdrop_filter_perf_ios__timeline_summary&selected=commit%3D33260%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DiPhone_11%252Cdevice_version%253Dnone%252Chost_type%253Dmac%252Csub_result%253Daverage_gpu_usage%252Ctest%253Dbackdrop_filter_perf_ios__timeline_summary%252C
=> Reland "[ios_platform_view] MaskView pool to reuse maskViews."

shell/platform/darwin/ios/framework/Source/FlutterEngineTest.mm
https://github.com/flutter/flutter/issues/120239
Maybe we were just barely hitting the timeout before? Could be worth trying.
=> increase first frame timeout

shell/platform/windows/BUILD.gn, shell/platform/windows/testing/mock_window.h, shell/platform/windows/window.h, shell/platform/windows/window_unittests.cc
Enable returning a UIA object from Window's `OnGetObject`. Previously, the region of code that returns this object was gated by an unactivated `#ifdef`, which was the only thing stopping the WIP UIA implementation from being used.
https://github.com/flutter/flutter/issues/120365 …
=> Enable UIA in Window

shell/platform/darwin/macos/framework/Source/FlutterTextInputPlugin.mm, shell/platform/darwin/macos/framework/Source/FlutterTextInputPluginTest.mm
TextInputPlugin must be visible and in view hierarchy for emoji picker to work. This is trivial change that moves it completely outside of visible area.
Fixes https://github.com/flutter/flutter/issues/118504 …
=> Reland "[macos] Move TextInputPlugin outside of visible area"

.ci.yaml
`no_bitcode` and `jazzy_version` are no longer used in recipes.  Remove them.
https://flutter-review.googlesource.com/c/recipes/+/38093
=> Remove unused .ci.yaml properties

shell/platform/windows/flutter_windows_engine.cc, shell/platform/windows/flutter_windows_engine.h, shell/platform/windows/flutter_windows_view.cc, shell/platform/windows/flutter_windows_view.h, shell/platform/windows/keyboard_unittests.cc, shell/platform/windows/testing/engine_modifier.h, shell/platform/windows/testing/flutter_windows_engine_builder.cc, shell/platform/windows/testing/flutter_windows_engine_builder.h, shell/platform/windows/text_input_plugin.cc, shell/platform/windows/text_input_plugin.h, shell/platform/windows/text_input_plugin_unittest.cc
The keyboard & text input plugins are singletons, however, they are currently owned by the view. This change makes them shared by the `FlutterWindowsEngine` to prepare for a multi-view world.
Type | Category | Notes
-- | -- | --
`KeyboardManager` | 1 per window | Receives Windows messages for key events. If the message isn't handled by Flutter, it redispatches the message back to Windows and then ignores Windows's redelivery of the message.<br/><br/>The `KeyboardManager` is owned by the `Window`, but in the future it will be refactored to be owned by the `FlutterWindowsView`. Currently it cannot be 1 per engine as redispatched messages' state must be tracked separately for each `Window`.
`KeyboardKeyHandler` | 1 per engine | …
=> [Windows] Prepare keyboard & text input plugins for multi-view

shell/platform/darwin/ios/framework/Source/FlutterPlatformViews.mm, shell/platform/darwin/macos/framework/Source/FlutterPlatformViewController.mm
For native targets, an `int` in Dart maps to a signed 64-bit integer representation.
Related issue: https://github.com/flutter/flutter/issues/120256 …
=> [ios] Convert `int` in Dart to `long long` in Objective-C

lib/ui/isolate_name_server.dart, lib/ui/natives.dart, lib/ui/painting.dart, lib/ui/plugins.dart
This was discovered when investigating which classes could potentially be used as a mixin and may need a mixin class modifier in Dart 3. These classes came up as potential mixin candidates even though they really shouldn't be candidates.
Part of https://github.com/flutter/flutter/issues/118837.
=> Fix classes that shouldn't be extended/instantiated/mixedin

flow/embedded_views.h, flow/layers/backdrop_filter_layer.cc, shell/common/shell_unittests.cc, shell/platform/darwin/ios/framework/Source/FlutterPlatformViews.mm, shell/platform/darwin/ios/framework/Source/FlutterPlatformViewsTest.mm
BackdropFilter above PlatformView was using the `local_cull_rect` as the area to filter. But if there was a transform above the BackdropFilter this doesn't put it in the right place. I changed it to `device_cull_rect` instead. It kind of breaks the stack/push metaphor but the `filter_rect` doesn't really fit within the context of the mutators stack (as it comes from a completely different stack).
=> Fix position of BackdropFilter above PlatformView

ci/licenses_golden/licenses_flutter, fml/endianness.h, lib/ui/BUILD.gn, lib/ui/painting/image_decoder_unittests.cc, lib/ui/painting/image_generator.cc, lib/ui/painting/image_generator.h, lib/ui/painting/image_generator_apng.cc, lib/ui/painting/image_generator_apng.h, lib/ui/painting/image_generator_registry.cc, lib/ui/painting/image_generator_registry_unittests.cc, lib/ui/painting/multi_frame_codec.cc, shell/common/shell_unittests.cc, shell/platform/android/android_image_generator.cc, shell/platform/android/android_image_generator.h
Adds a multiframe image decoder that demuxes APNG streams into regular PNG-compliant streams. The actual color decoding is done by Skia's existing PNG decoder.
A single lazy pass is performed over the full stream as the frames are decoded for the first time.
Resolves https://github.com/flutter/flutter/issues/37247.
=> Add Animated PNG demuxer

impeller/renderer/backend/metal/context_mtl.mm, impeller/tools/build_metal_library.py, impeller/tools/impeller.gni
Towards fixing https://github.com/flutter/flutter/issues/120326. This allows you to specify the sources for the Impeller Metal Library. The user is meant to navigate to `out/<engine_variant>/shaders/entity.metallibsym` when Xcode prompts for sources (you only
need to do this once).
Shader debugging with line by line profiling is still not a turnkey operation though. This works fine on macOS. But on iOS, I had to bump up the min iOS version level to iOS 12 for the sources to show up and specify `-g` to the `metal` compiler for line by line profiling. The performance of the shaders was identical after the changes though so I suspect engine developers will patch in these flags locally to develop and debug shaders. Or develop on macOS.
=> [Impeller] Generate a Metal library symbols file for shader debugging.

lib/ui/painting/image_filter.cc, testing/dart/canvas_test.dart
Fixes https://github.com/flutter/flutter/issues/120278
=> Ignore invalid filters when constructing an image compose filter

shell/platform/darwin/macos/framework/Headers/FlutterEngine.h, shell/platform/darwin/macos/framework/Headers/FlutterPluginRegistrarMacOS.h, shell/platform/darwin/macos/framework/Headers/FlutterViewController.h, shell/platform/darwin/macos/framework/Source/FlutterCompositor.mm, shell/platform/darwin/macos/framework/Source/FlutterCompositorTest.mm, shell/platform/darwin/macos/framework/Source/FlutterEngine.mm, shell/platform/darwin/macos/framework/Source/FlutterEngineTest.mm, shell/platform/darwin/macos/framework/Source/FlutterEngine_Internal.h, shell/platform/darwin/macos/framework/Source/FlutterKeyboardManager.mm, shell/platform/darwin/macos/framework/Source/FlutterRenderer.mm, shell/platform/darwin/macos/framework/Source/FlutterRendererTest.mm, shell/platform/darwin/macos/framework/Source/FlutterViewController.mm, shell/platform/darwin/macos/framework/Source/FlutterViewEngineProvider.mm, shell/platform/darwin/macos/framework/Source/FlutterViewEngineProviderTest.mm, shell/platform/darwin/macos/framework/Source/FlutterViewProvider.h
Reverts flutter/engine#37976 due to breakage b/268583456
=> Revert "[macOS] Make FlutterEngine support multiple views"

impeller/entity/entity_pass.cc
This makes clip restores a bit cheaper by only covering the area that's actually impacted by the restore as opposed to the whole pass texture. I don't think this is making much of a difference in our usual testing apps, but it's also not hard to construct somewhat pathological cases where the current behavior is surprisingly slow (not dissimilar to https://github.com/flutter/engine/pull/39358).
=> [Impeller] Use minimal coverage for EntityPass clip restores

lib/web_ui/lib/src/engine/canvaskit/embedded_views.dart, lib/web_ui/test/canvaskit/embedded_views_test.dart
This PR fixes a couple of edge case with the canvaskit platform view embedder where if an app would have an "invisible" platform view as its first platform view in the scene, it would prevent "visible" views from being composited at the right spot of the DOM.
The issue is fixed by:
* Simplifying the logic to determine whether a canvaskit overlay is needed (it's now only triggered by visible platform views) in the preroll/composite stages.
The above introduces a new corner case, for apps that only contain invisible platform views, that is fixed by:
* Excluding platform view groups without any visible platform view from the "viewsNeedingOverlays" computation when updating the overlays in the submitFrame stage.
* Fixes https://github.com/flutter/flutter/issues/118452
* Unit tests are updated …
=> [web] Fixes invisible platform view compositing edge cases.

shell/platform/darwin/ios/framework/Source/FlutterEngine.mm, shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm
The framework side of this was reverted long ago and still hasn't been relanded (https://github.com/flutter/flutter/pull/115296).  The result is that scribble does not currently work.  This PR will add back the original method channel calls so that it works in the meantime until the framework PR can be relanded.
=> Revert "Remove deprecated TextInputClient scribble method code"

display_list/display_list_matrix_clip_tracker.h, flow/diff_context.cc, flow/diff_context.h, flow/layers/backdrop_filter_layer.cc, flow/layers/backdrop_filter_layer_unittests.cc, flow/layers/clip_shape_layer.h, flow/layers/color_filter_layer.cc, flow/layers/display_list_layer.cc, flow/layers/image_filter_layer.cc, flow/layers/opacity_layer.cc, flow/layers/physical_shape_layer.cc, flow/layers/shader_mask_layer.cc
Fixes https://github.com/flutter/flutter/issues/116198 …
=> Use DisplayListMatrixClipTracker in DiffContext

impeller/entity/contents/content_context.cc, impeller/entity/contents/content_context.h, impeller/entity/contents/contents.cc, impeller/entity/contents/scene_contents.cc, impeller/entity/entity_pass.cc, impeller/playground/imgui/imgui_impl_impeller.cc, impeller/renderer/pipeline_descriptor.cc, impeller/renderer/pipeline_descriptor.h, impeller/renderer/render_target.cc, impeller/renderer/render_target.h
Removes the stencil from non-layer offscreen passes and configure pipelines accordingly.
This doesn't make much of a difference on iOS, but will be a much bigger deal for desktop and at least removes a bunch of unnecessary resource noise from frame captures.
=> [Impeller] Don't use unnecessary stencil attachments

shell/platform/darwin/macos/framework/Source/FlutterTextInputPlugin.mm
Adds marks to cleanly separate the sections of TextInputPlugin when viewing in XCode and other IDEs that recognise #pragma mark. This file is getting pretty long.
No tests since this is a cleanup with no functional changes. …
=> [macOS] Add XCode marks for TextInputPlugin

impeller/entity/contents/content_context.cc, impeller/entity/contents/content_context.h, impeller/entity/contents/contents.cc, impeller/renderer/render_target.cc, impeller/renderer/render_target.h
These values always match in practice today, but with the advent of wide gamut support, pipelines with different color attachment formats will need to be built. If you drag a Flutter app from a standard monitor to a wide gamut monitor, the pass textures may change formats to better support the color space.
Either way, any mismatch between a pass attachment and the pipeline layout is a bug 100% of the time, and this change just makes it so the color attachment format will always match the render pass.
=> [Impeller] Source the pipeline color attachment pixel format from RenderPass textures

shell/platform/darwin/macos/framework/Headers/FlutterEngine.h, shell/platform/darwin/macos/framework/Headers/FlutterPluginRegistrarMacOS.h, shell/platform/darwin/macos/framework/Headers/FlutterViewController.h, shell/platform/darwin/macos/framework/Source/FlutterCompositor.mm, shell/platform/darwin/macos/framework/Source/FlutterCompositorTest.mm, shell/platform/darwin/macos/framework/Source/FlutterEngine.mm, shell/platform/darwin/macos/framework/Source/FlutterEngineTest.mm, shell/platform/darwin/macos/framework/Source/FlutterEngine_Internal.h, shell/platform/darwin/macos/framework/Source/FlutterKeyboardManager.mm, shell/platform/darwin/macos/framework/Source/FlutterRenderer.mm, shell/platform/darwin/macos/framework/Source/FlutterRendererTest.mm, shell/platform/darwin/macos/framework/Source/FlutterViewController.mm, shell/platform/darwin/macos/framework/Source/FlutterViewEngineProvider.mm, shell/platform/darwin/macos/framework/Source/FlutterViewEngineProviderTest.mm, shell/platform/darwin/macos/framework/Source/FlutterViewProvider.h
Reland https://github.com/flutter/engine/pull/37976. This reland reverted the change of a property into a method, which caused compiling errors in Swift. …
=> Reland [macOS] Make FlutterEngine support multiple views

impeller/entity/contents/contents.cc, impeller/entity/contents/contents.h, impeller/entity/contents/filters/blend_filter_contents.cc, impeller/entity/contents/filters/blend_filter_contents.h, impeller/entity/contents/filters/border_mask_blur_filter_contents.cc, impeller/entity/contents/filters/border_mask_blur_filter_contents.h, impeller/entity/contents/filters/color_matrix_filter_contents.cc, impeller/entity/contents/filters/color_matrix_filter_contents.h, impeller/entity/contents/filters/filter_contents.cc, impeller/entity/contents/filters/filter_contents.h, impeller/entity/contents/filters/gaussian_blur_filter_contents.cc, impeller/entity/contents/filters/gaussian_blur_filter_contents.h, impeller/entity/contents/filters/linear_to_srgb_filter_contents.cc, impeller/entity/contents/filters/linear_to_srgb_filter_contents.h, impeller/entity/contents/filters/local_matrix_filter_contents.cc, impeller/entity/contents/filters/local_matrix_filter_contents.h, impeller/entity/contents/filters/matrix_filter_contents.cc, impeller/entity/contents/filters/matrix_filter_contents.h, impeller/entity/contents/filters/morphology_filter_contents.cc, impeller/entity/contents/filters/morphology_filter_contents.h, impeller/entity/contents/filters/srgb_to_linear_filter_contents.cc, impeller/entity/contents/filters/srgb_to_linear_filter_contents.h, impeller/entity/contents/filters/yuv_to_rgb_filter_contents.cc, impeller/entity/contents/filters/yuv_to_rgb_filter_contents.h
This is a pass collapse optimization I've been meaning to get around to.
By outputting a deferred rendering command, filters are given full control over how its results should be applied to the parent pass; whether a subpass is necessary is entirely up to the filter.
This PR is a pure refactor that shouldn't change anything about how we render. Note that thanks to our other texture passthrough optimizations, this does _not_ introduce an extra pass when filters are chained. I plan to land the actual pass removals in follow-ups.
=> [Impeller] Return entities from filters instead of snapshots

lib/ui/painting/canvas.cc, lib/ui/painting/canvas.h, lib/ui/painting/picture_recorder.cc, lib/ui/painting/picture_recorder.h
Now that the text and paragraph code no longer depends on an SkCanvas interface as of https://github.com/flutter/engine/pull/39499, the code that produces an SkCanvas object for a ui.Canvas object can be removed.
This is a dead code removal PR which should not need tests - the build stages will test the change.
=> remove use of SkCanvas and DLCanvasRecorder from ui.Canvas native code

impeller/fixtures/BUILD.gn, impeller/fixtures/stage1.comp, impeller/fixtures/stage2.comp, impeller/renderer/backend/metal/compute_pass_mtl.mm, impeller/renderer/compute_unittests.cc
Adding multiple kernels to a single compute pass was only running the last one - the call to actually dispatch the method was nested improperly and only being invoked for the final command in the buffer.
Adds a test covering this situation, including sharing data between the kernel functions and verifying the output of both.
=> [Impeller] Fix multi-function compute

lib/ui/platform_dispatcher.dart, lib/ui/pointer.dart, lib/ui/window/pointer_data.h, lib/ui/window/pointer_data_packet_converter.cc, lib/ui/window/pointer_data_packet_converter_unittests.cc, lib/web_ui/lib/pointer.dart, shell/common/input_events_unittests.cc, shell/platform/android/io/flutter/embedding/android/AndroidTouchProcessor.java, shell/platform/darwin/ios/framework/Source/FlutterViewController.mm, shell/platform/darwin/ios/framework/Source/FlutterViewControllerTest.mm, shell/platform/embedder/embedder.cc, shell/platform/embedder/embedder.h
Reverts flutter/engine#39267
This change is causing the framework to fail its analysis checks because a switch over the PointerSignalKind is no longer exhaustive due to the addition of stylusAuxiliaryAction.
=> Revert "Add support for double tap action from Apple Pencil 2"

impeller/renderer/backend/gles/buffer_bindings_gles.cc
Also fix a typo in the function name
=> [Impeller] Avoid stringstream usage in CreateUniformMemberKey

shell/platform/embedder/fixtures/main.dart, shell/platform/embedder/tests/embedder_gl_unittests.cc
The test assumes that the fixture app has scheduled a specific number of frames.  The fixture should stop scheduling after that point.
See https://github.com/flutter/flutter/issues/106589
=> Fix a flake in EmbedderTest.CompositorRenderTargetsNotRecycledWhenAvoidsCacheSet

testing/run_tests.py
`impeller_unittests` are flaking on `flutter-3.7-candidate.1` cherry picks https://github.com/flutter/engine/pull/39545#issuecomment-1428607969
These tests were turned off in https://github.com/flutter/engine/pull/38307 to address this flake https://github.com/flutter/flutter/issues/114872.  Cherry-pick turning off the tests into the release branch.
Request at https://github.com/flutter/flutter/issues/120640
=> [cp][Impeller] Disable impeller_unittests

impeller/tools/malioc.gni
`$root_gen_dir` isn't guaranteed to exist when GN runs this, and the script won't create it before trying to write to the file. So, this PR changes the output path to one that is guaranteed to exist.
=> Fix build output path of the shader analysis core list

impeller/entity/contents/content_context.cc, impeller/renderer/render_target.h
This fixes the problem noted in this comment: https://github.com/flutter/flutter/issues/120586#issuecomment-1428023566
A breakage was introduced in https://github.com/flutter/engine/pull/39537 that affects `Picture::ToImage` and `Picture::RenderToTexture`. Because the default behavior was changed to remove the stencil, these utilities end up trying to render an `EntityPass` to a `RenderTarget` with no configured stencil attachment.
This fix inverts the default behavior and explicitly removes the stencil from `ContentContext::MakeSubpass` instead.
=> [Impeller] Make RenderTarget::CreateOffscreen utilities add a stencil by default

impeller/aiks/paint.cc, impeller/display_list/display_list_unittests.cc
According to Skia's documentation and implementation, mask filters are ignored for saved layers. So I guess Impeller needs to be consistent with it.
https://github.com/google/skia/blob/main/include/core/SkCanvas.h#L604-L605
https://github.com/google/skia/blob/main/src/core/SkCanvas.cpp#L1114
=> [Impeller] Ignore the mask filter when saving layer

shell/platform/darwin/macos/framework/Source/FlutterTextInputPlugin.mm, shell/platform/darwin/macos/framework/Source/FlutterTextInputPluginTest.mm
macOS supports three autofill types: username, password, and oneTimeCode. Apply these content types when the equivalent Flutter autofill hints are set.
Note that enabling autocomplete of username and password in applications will still require setting the "Autofill Credential Provider" and "Associated Domains" entitlements, and for the FlutterTextInputPlugin to be updated to use an NSSecureTextInput input type.
Issue: https://github.com/flutter/flutter/issues/120252
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-rep …
=> [macOS] Set textfield autofill type

impeller/renderer/backend/gles/texture_gles.cc, impeller/renderer/backend/metal/formats_mtl.h, impeller/renderer/backend/metal/formats_mtl.mm, impeller/renderer/backend/vulkan/formats_vk.h, impeller/renderer/formats.h, impeller/renderer/render_target.cc, shell/platform/darwin/ios/framework/Source/FlutterView.mm
issue: https://github.com/flutter/flutter/issues/117182
integration test: https://github.com/flutter/flutter/pull/120131
I spent some time trying to make BGR10_XR work but I couldn't figure it out, so I punted on it for now.  Getting smaller textures is more important for now. …
=> Added wide gamut colors to offscreen buffers

.ci.yaml
The emulator flakes appear to have been addressed.
There is a still a test flaking like here https://ci.chromium.org/ui/p/flutter/builders/staging/Linux%20Fuchsia%20FEMU/532/overview, but it is at a much lower rate, and from chat, I think it will soon be fixed by an upcoming Fuchsia SDK roll.
=> Remove "bringup: true" from "Linux Fuchsia FEMU"

lib/ui/platform_dispatcher.dart, lib/ui/pointer.dart, lib/ui/window/pointer_data.h, lib/ui/window/pointer_data_packet_converter.cc, lib/ui/window/pointer_data_packet_converter_unittests.cc, lib/web_ui/lib/pointer.dart, shell/common/input_events_unittests.cc, shell/platform/android/io/flutter/embedding/android/AndroidTouchProcessor.java, shell/platform/darwin/ios/framework/Source/FlutterViewController.mm, shell/platform/darwin/ios/framework/Source/FlutterViewControllerTest.mm, shell/platform/embedder/embedder.cc, shell/platform/embedder/embedder.h
Reverts flutter/engine#39607, which was a revert of https://github.com/flutter/engine/pull/39267 because an introduction of a new PointerSignalKind broke a few framework tests. 
This breakage is addressed in this framework prep PR which has merged. https://github.com/flutter/flutter/pull/120731
=> Add support for double tap action from Apple Pencil 2

lib/web_ui/dev/test_platform.dart, lib/web_ui/lib/src/engine/assets.dart, lib/web_ui/lib/src/engine/canvaskit/font_fallbacks.dart, lib/web_ui/lib/src/engine/canvaskit/fonts.dart, lib/web_ui/lib/src/engine/canvaskit/image.dart, lib/web_ui/lib/src/engine/dom.dart, lib/web_ui/lib/src/engine/platform_dispatcher.dart, lib/web_ui/lib/src/engine/text/font_collection.dart, lib/web_ui/lib/src/engine/util.dart, lib/web_ui/test/canvaskit/image_golden_test.dart, lib/web_ui/test/canvaskit/image_test.dart, lib/web_ui/test/canvaskit/skia_font_collection_test.dart, lib/web_ui/test/engine/dom_http_fetch_test.dart, lib/web_ui/test/text/font_loading_test.dart, web_sdk/web_engine_tester/lib/golden_tester.dart
Consolidate all of web engine HTTP code into a single `httpFetch` function that provides a standard way for handling errors:
- Provide `httpFetch` and a few specialize convenience functions around it for making HTTP calls.
- Provide a standard set of mock classes for mocking HTTP requests in unit tests.
- Migrate all of our code to `httpFetch` (fonts, assets, network images,
=> [web] consolidate network code into httpFetch

impeller/entity/entity_unittests.cc, impeller/geometry/geometry_unittests.cc, impeller/geometry/matrix.h
Fix 
- https://github.com/flutter/flutter/issues/120272
**We should cover `zfar = +infinity` and `znear = -infinity`. 
So the `zScale` in `MakeOrthographic` should be `1 / (infinity - (-infinity)) = 1 / infinity = 0`**
<details>
<summary>Dart sample code</summary>
```dart
void main() {
runApp(const MyApp());
}
const MyApp({super.key});
@override
return MaterialApp(
title: 'Flutter Demo',
theme: ThemeData.light(useMaterial3: true),
home: const MyHomePage(),
);
}
}
class MyHomePage extends StatelessWidget {
const MyHomePage({super.key});
@override
return Scaffold(
body: Center(
child: Transform(
transform: Matrix4.identity() // perspective …
```
=> [Impeller] Fix render transform is not correct.

shell/platform/darwin/ios/framework/Source/FlutterViewController.mm
While investigating a safe area padding issue, I noticed this dead code.  Usage was removed in https://github.com/flutter/engine/pull/34919/files#diff-365b13daa5168d36d5824f220bc472a4a90f4685761947f8daf9dc76e7f8d962L1216.
Delete it. …
=> Delete dead statusBarPadding iOS code

impeller/entity/contents/gradient_generator.h, impeller/entity/contents/linear_gradient_contents.cc, impeller/entity/contents/radial_gradient_contents.cc, impeller/entity/contents/sweep_gradient_contents.cc
Fix https://github.com/flutter/flutter/issues/120817 by doing what the nice shader validation error message says
=> [Impeller] align SSBOs to 16 bytes to fix iOS shader validation issue.

flow/embedded_views.h, flow/testing/mock_embedder.cc, flow/testing/mock_embedder.h, shell/common/rasterizer_unittests.cc, shell/common/shell_test_external_view_embedder.cc, shell/common/shell_test_external_view_embedder.h, shell/platform/android/external_view_embedder/external_view_embedder.cc, shell/platform/android/external_view_embedder/external_view_embedder.h, shell/platform/darwin/ios/framework/Source/FlutterPlatformViews.mm, shell/platform/darwin/ios/framework/Source/FlutterPlatformViews_Internal.h, shell/platform/darwin/ios/ios_external_view_embedder.h, shell/platform/darwin/ios/ios_external_view_embedder.mm, shell/platform/embedder/embedder_external_view_embedder.cc, shell/platform/embedder/embedder_external_view_embedder.h, shell/platform/fuchsia/flutter/flatland_external_view_embedder.cc, shell/platform/fuchsia/flutter/flatland_external_view_embedder.h, shell/platform/fuchsia/flutter/gfx_external_view_embedder.cc, shell/platform/fuchsia/flutter/gfx_external_view_embedder.h, shell/platform/fuchsia/flutter/platform_view_unittest.cc, shell/platform/fuchsia/flutter/tests/flatland_platform_view_unittest.cc, shell/testing/tester_main.cc
Related issue: https://github.com/flutter/flutter/issues/120256
[Discord]: …
=> Uses `int64_t` instead of `int` for the |view_id| parameter.

ci/licenses_golden/licenses_flutter, shell/platform/darwin/macos/BUILD.gn, shell/platform/darwin/macos/framework/Source/FlutterCompositor.h, shell/platform/darwin/macos/framework/Source/FlutterCompositor.mm, shell/platform/darwin/macos/framework/Source/FlutterMutatorView.h, shell/platform/darwin/macos/framework/Source/FlutterMutatorView.mm, shell/platform/darwin/macos/framework/Source/FlutterMutatorViewTest.mm
This implements support for platform view mutators currently provided through the embedder API, namely:
- Opacity
- Clip Rect
- Clip RRect
- Transform
- Clipping to paths (currently only round rect supported - see below) is done through `CAShapeLayer` masks, which avoids the need for rasterizing mask layer. 
- Clipping to round rectangle will only clip to path if one or more more corners are intersected by the view. Otherwise it behaves as if clipped by regular rectangle.
Clipping to arbitrary path is not currently supported by embedder API. However once there is a way to represent it in the embedder API it should be fairly straightforward to add to `FlutterMutatorView`.
Fixes https://github.com/flutter/flutter/issues/118142
If you need help, consider asking for advice on the #hackers-new …
=> [macOS] Implement platform view mutators

lib/ui/dart_ui.cc, lib/ui/platform_dispatcher.dart, lib/ui/window.dart, lib/ui/window/platform_configuration.cc, lib/ui/window/platform_configuration.h, lib/web_ui/lib/platform_dispatcher.dart, lib/web_ui/lib/src/engine/platform_dispatcher.dart, lib/web_ui/lib/src/engine/window.dart, lib/web_ui/test/window_test.dart, runtime/runtime_controller.cc, runtime/runtime_controller.h, runtime/runtime_delegate.h, shell/common/engine.cc, shell/common/engine.h, shell/common/engine_unittests.cc, shell/platform/embedder/fixtures/main.dart, shell/platform/embedder/tests/embedder_unittests.cc
This introduces `PlatformDispatcher.implicitView` (see https://github.com/flutter/flutter/issues/120306).
This is a low-level primitive for the framework's bootstrapping. Most code, including the framework after bootstrapping, will use `View.of(context)` instead of this new API. This new primitive will let us deprecate the `window` global.
Goals:
1. **Enable multi-window**. The `PlatformDispatcher.implicitView` is nullable. If `null`, the app must create a window to get a view it can draw into.
2. **Backwards compatibility**. For "single window" apps, `PlatformDispatcher.instance.implicitView` should behave as similar to `window` as possible.
1. The `PlatformDispatcher.instance.implicitView.viewId` should be `0`.
1. The `PlatformDispatcher.instance.implicitView` must be available …
=> [dart:ui] Introduce `PlatformDispatcher.implicitView`

shell/platform/darwin/macos/framework/Headers/FlutterDartProject.h, shell/platform/darwin/macos/framework/Source/FlutterDartProject.mm, shell/platform/darwin/macos/framework/Source/FlutterDartProject_Internal.h, shell/platform/darwin/macos/framework/Source/FlutterEngine.mm, shell/platform/darwin/macos/framework/Source/FlutterEngineTest.mm, shell/platform/darwin/macos/framework/Source/FlutterEngine_Internal.h
Support for using dart:mirrors has been deprecated for nearly two years. this removes support for enabling mirrors from the embedder as documented in the deprecation comment. This was primarily added as a workaround for an internal tooling usecase, which no longer exists.
Issue: https://github.com/flutter/flutter/issues/120924 …
=> [macOS] Eliminate mirrors support

display_list/display_list.cc, display_list/display_list.h, flow/layers/display_list_layer_unittests.cc, flow/layers/display_list_raster_cache_item.cc, flow/raster_cache.cc, flow/raster_cache.h, flow/testing/mock_raster_cache.cc
Fixes https://github.com/flutter/flutter/issues/120455
There is a small chance that the new FML_DCHECK will trigger in examples that we haven't seen yet, but that would point out more problems like this one that need to be fixed anyway.
This would be a good candidate to cherry-pick to any release that shipped with the original code in https://github.com/flutter/engine/pull/34562.
=> Cached DisplayList opacity inheritance fix

lib/ui/painting/image_generator_apng.cc
This is blocking the internal roll as the internal APIs aren't available.
Follow up from https://github.com/flutter/engine/pull/31098
=> Migrate skia png codec call to public interface

shell/platform/linux/fl_dart_project.cc, shell/platform/linux/fl_dart_project_private.h, shell/platform/linux/fl_dart_project_test.cc, shell/platform/linux/fl_engine.cc, shell/platform/linux/fl_engine_private.h, shell/platform/linux/fl_engine_test.cc, shell/platform/linux/public/flutter_linux/fl_dart_project.h
Support for using dart:mirrors has been deprecated for nearly two years. this removes support for enabling mirrors from the embedder as documented in the deprecation comment. This was primarily added as a workaround for an internal tooling usecase, which no longer exists.
Issue: https://github.com/flutter/flutter/issues/120924 …
=> [linux] Eliminate mirrors support

.ci.yaml
This configuration exposed Fuchsia issues that were not surfaced in any other environment when it was enabled prematurely last week. This change adds a `bringup: true` builder for the new configuration. When it stabilizes, `enable_cso` will become the default, and the `bringup: true` builder can be deleted.
`enable_cso` was added here https://flutter-review.git.corp.google.com/c/recipes/+/39400.
=> Adds a Linux Fuchsia FEMU config that enables CSO

impeller/renderer/backend/vulkan/allocator_vk.cc, impeller/renderer/backend/vulkan/blit_command_vk.cc, impeller/renderer/backend/vulkan/commands_vk.cc, impeller/renderer/backend/vulkan/commands_vk.h, impeller/renderer/backend/vulkan/render_pass_vk.cc, impeller/renderer/backend/vulkan/render_pass_vk.h, shell/platform/android/platform_view_android.cc
fix: https://github.com/flutter/flutter/issues/120134
=> [impeller] support generating mip-maps on Vulkan

impeller/entity/contents/content_context.cc, impeller/entity/contents/content_context.h, impeller/entity/contents/runtime_effect_contents.cc, impeller/playground/backend/metal/playground_impl_mtl.mm, impeller/renderer/backend/gles/context_gles.cc, impeller/renderer/backend/metal/context_mtl.mm, impeller/renderer/backend/metal/surface_mtl.mm, impeller/renderer/backend/vulkan/context_vk.cc, impeller/renderer/context.cc, impeller/renderer/device_capabilities.cc, impeller/renderer/device_capabilities.h, impeller/renderer/formats.h, impeller/renderer/pipeline_builder.h, impeller/renderer/render_target.cc, impeller/runtime_stage/runtime_stage_unittests.cc
fixes: https://github.com/flutter/flutter/issues/120498
=> [Impeller] Device default attachment pixel formats

ci/builders/mac_ios_engine.json
This provides greater reusability of subbuilds saving an approximate of 6 bots per run. …
=> Integrate ios_engine debug, profile and release.

shell/platform/darwin/macos/framework/Source/AccessibilityBridgeMac.h, shell/platform/darwin/macos/framework/Source/FlutterPlatformNodeDelegateMac.h, shell/platform/darwin/macos/framework/Source/FlutterTextInputSemanticsObject.h
Applies the FML_DISALLOW_COPY_AND_ASSIGN to non-POD types in the macOS embedder. Specifically the following three accessibility-related classes:
* FlutterPlatformNodeDelegateMac
* FlutterTextPlatformNode
* AccessibilityBridgeMac
No new tests since no semantic change. Only has the compile-time effect of preventing copying of classes intended to be move-only. …
=> [macOS] Mark move-only classes as such

.ci.yaml
Currently, clang tidy targets do not run on presubmit checks if python files are modified.
This PR triggers lint check on presubmits when python files are changed.
=> [lint + clang tidy] add lint check for python file changes

lib/ui/fixtures/ui_test.dart, lib/ui/platform_dispatcher.dart, lib/ui/window.dart, lib/web_ui/lib/platform_dispatcher.dart, lib/web_ui/lib/src/engine/view_embedder/dimensions_provider/custom_element_dimensions_provider.dart, lib/web_ui/lib/src/engine/view_embedder/dimensions_provider/dimensions_provider.dart, lib/web_ui/lib/src/engine/view_embedder/dimensions_provider/full_page_dimensions_provider.dart, lib/web_ui/lib/src/engine/window.dart, lib/web_ui/lib/window.dart, lib/web_ui/test/engine/view_embedder/dimensions_provider/custom_element_dimensions_provider_test.dart, lib/web_ui/test/engine/view_embedder/dimensions_provider/full_page_dimensions_provider_test.dart
`WindowPadding` is a view concept. Let's rename it to `ViewPadding` to avoid any confusion that this is related to the window concept that the multi-window support will introduce.
=> Rename WindowPadding to ViewPadding

impeller/aiks/aiks_unittests.cc, impeller/aiks/paint.cc, impeller/aiks/paint.h, impeller/display_list/display_list_dispatcher.cc
Fixes https://github.com/flutter/flutter/issues/109739
Before:
After:
=> [Impeller] Implement invert colors flag.

shell/platform/darwin/ios/framework/Source/FlutterView.mm, shell/platform/darwin/ios/ios_surface_metal_impeller.mm
fixes https://github.com/flutter/flutter/issues/120641
integration tests: https://github.com/flutter/flutter/pull/120914 …
=> Started using bgr10_xr for opaque surfaces.

shell/platform/darwin/ios/framework/Source/FlutterPlatformViews.mm, shell/platform/darwin/ios/framework/Source/FlutterPlatformViewsTest.mm, testing/ios/IosUnitTests/Tests/FlutterEngineConfig.xcconfig, testing/scenario_app/ios/Scenarios/Scenarios/AppDelegate.m, testing/scenario_app/ios/Scenarios/ScenariosUITests/PlatformViewGestureRecognizerTests.m, testing/scenario_app/lib/src/platform_view.dart, testing/scenario_app/lib/src/scenarios.dart
Note: Added integration test [here](https://github.com/flutter/flutter/pull/120844), but needs engine roll of this PR in order to pass that test. 
It turns out that the rendering Z order was correct, but the touch behavior is incorrect. So instead of setting the `zPosition`, we actually change subview order in the view hierarchy, which works for both z order and touch behavior. 
Added a unit test for this particular issue. The existing scenario/screenshot tests should already be sufficient. 
https://github.com/flutter/flutter/issues/118366
- [x ] I read and followed the [Flutter …
=> [platform_view] fix overlapping platform view not touchable

lib/ui/painting/image_decoder_impeller.cc, lib/ui/painting/image_decoder_unittests.cc
This is the bug that was found in the wide gamut memory audit.
A skia bug was filed: https://bugs.chromium.org/p/skia/issues/detail?id=14137 …
=> Updated the wide-gamut constant and added a unit test for it.

shell/platform/common/alert_platform_node_delegate.h, shell/platform/darwin/common/buffer_conversions.mm
Rather than explicitly delete the copy constructor and operator=, use the standard FML_DISALLOW_COPY_AND_ASSIGN macro used elsewhere across the codebase. Also ensure that files using this macro #include the correct FML header directly, rather than relying on a transitive include.
No test changes/additions since this patch introduces no semantic changes. …
=> [common] Use FML macro to prevent copy/assignment

shell/platform/android/io/flutter/view/AccessibilityBridge.java
unblock b/267110800
They ran into the assertion without repro. Not entirely sure how that is possible. I added some more log and make it a non-crash to unblock the customer. …
=> Add more log when receiving semantics node not part of update

impeller/typographer/font_glyph_pair.h, impeller/typographer/glyph.h, impeller/typographer/typographer_unittests.cc
Fixes https://github.com/flutter/flutter/issues/121128
While I don't have an exact repro, this was almost certainly caused by the hash/eq implementations not taking the glyph type into account.
=> [Impeller] ensure glyph type contributes to FontGlyphPair hash/eq

shell/platform/darwin/ios/framework/Source/FlutterPlatformViews.mm
This problem was introduced by https://github.com/flutter/engine/pull/37107 where a clipRect call is being executed on the raw canvas of a frame. Since these frames can be cached, that clipRect will persist to future app frames and interfere with the over-view rendering.
This problem was caught during a PR that happened to cause the test case created for https://github.com/flutter/engine/pull/39630 to use a stale frame. It looks like that issue is a race condition so it would be hard to create a specific test case that demonstrates this fix.
=> save/restore around clipping the (potentially cached) frame canvas

ci/licenses_golden/excluded_files, impeller/BUILD.gn, impeller/fixtures/dart_tests.dart, impeller/renderer/BUILD.gn, impeller/renderer/renderer_dart_unittests.cc
This took a bit of tinkering, but once I figured out the fixture/dart kernel situation and got everything to happen in the right order, the minimal solution turned out to be pretty simple.
=> [Impeller] Wire up a playground that can run Dart

impeller/renderer/backend/gles/render_pass_gles.cc, impeller/renderer/backend/metal/formats_mtl.h, impeller/renderer/backend/metal/render_pass_mtl.mm, impeller/renderer/backend/vulkan/formats_vk.h, impeller/renderer/backend/vulkan/pipeline_library_vk.cc, impeller/renderer/formats.h, impeller/renderer/pipeline_descriptor.cc, impeller/renderer/pipeline_descriptor.h, impeller/renderer/renderer_unittests.cc
Allows for good wireframe drawing. I've reached for line strips when using playgrounds to interactively debug geometry issues many times in the past. But for stroke paths, this is often insufficient for visualizing problems with joins, caps, and disconnected contours.
https://user-images.githubusercontent.com/919017/220804041-62079a6e-e8ca-40b6-a266-01b7f2201647.mov
=> [Impeller] Add PolygonMode to render layer

lib/web_ui/dev/steps/compile_tests_step.dart
Instead of hardcoding the list of canvaskit files to copy, let's copy all js and wasm files that are built locally. This is necessary to pick up the chromium variant of canvaskit (see: https://github.com/flutter/engine/pull/39796).
=> [web] Copy everything under the local canvaskit folder

lib/ui/platform_dispatcher.dart
This PR replaces obsolete comments, referencing the non-existing `ScreenConfiguration` type, in `ViewConfiguration` and replaces them with copied/pasted comments from windows.dart.
Fixes https://github.com/flutter/flutter/issues/120961
Documentation only.
=> Remove obsolete references in ViewConfiguration documentation

lib/ui/platform_dispatcher.dart, lib/web_ui/lib/platform_dispatcher.dart, testing/dart/platform_dispatcher_test.dart
* Updated PlatformDispatcher to use PlatformConfiguration to back `nativeSpellCheckServiceDefined` and `brieflyShowPassword`
* Updated web PlatformDispatcher/Configuration to match new API
Resolves [#120840](https://github.com/flutter/flutter/issues/120840)
=> Match PlatformConfiguration properties to PlatformDispatcher ones

lib/ui/painting.dart, lib/ui/platform_dispatcher.dart, lib/ui/text.dart, lib/ui/window.dart, lib/web_ui/lib/platform_dispatcher.dart
Also removes the unused `PlatformConfigurationChangedCallback` typedef.
=> Fix references in docs

lib/ui/platform_dispatcher.dart, lib/web_ui/lib/platform_dispatcher.dart
This reverts commit cad5eec1b52c9f9cf064151d9b9c99412b531660.
=> Revert "Match PlatformConfiguration properties to PlatformDispatcher ones (#39685)"

flow/layers/display_list_layer_unittests.cc
This enhancement to one of the unittests was blocked by https://github.com/flutter/flutter/issues/102331 that is now fixed.
=> uncomment a DL raster cache unittest enhancement now that it is feasible

shell/platform/windows/flutter_windows_engine.cc, shell/platform/windows/flutter_windows_view.cc, shell/platform/windows/flutter_windows_view_unittests.cc, shell/platform/windows/testing/mock_window_binding_handler.cc, shell/platform/windows/testing/mock_window_binding_handler.h
`FlutterWindowsView` owns both the `FlutterWindowsEngine` and `WindowBindingHandler` as unique pointers, so each is released upon its destruction. However, in the brief time between the release of the handler and the engine, the engine may attempt to call a method that expects the handler to exist.
Solve this by unsetting the engine's view from `FlutterWindowsView::~FlutterWindowsView`, which should complete before destructing its members. Include a unit test to verify that the view is unset by the time the handler is released.
https://github.com/flutter/flutter/issues/121189 …
=> Unregister the FlutterWindowsView on its destruction

display_list/display_list.h, display_list/display_list_benchmarks.cc, display_list/display_list_benchmarks.h, display_list/display_list_blend_mode.h, display_list/display_list_builder.cc, display_list/display_list_builder.h, display_list/display_list_canvas_dispatcher.cc, display_list/display_list_canvas_dispatcher.h, display_list/display_list_canvas_unittests.cc, display_list/display_list_complexity_gl.cc, display_list/display_list_complexity_gl.h, display_list/display_list_complexity_helper.h, display_list/display_list_complexity_metal.cc, display_list/display_list_complexity_metal.h, display_list/display_list_dispatcher.h, display_list/display_list_flags.h, display_list/display_list_ops.h, display_list/display_list_unittests.cc, display_list/display_list_utils.cc, display_list/display_list_utils.h, display_list/testing/dl_test_snippets.cc, display_list/testing/dl_test_snippets.h, display_list/types.h, impeller/display_list/display_list_dispatcher.cc, impeller/display_list/display_list_dispatcher.h, testing/display_list_testing.cc, testing/display_list_testing.h
This is pretty simple "obsolete code" fallout from removing DisplayListCanvasRecorder. Some of the DisplayList ops were only ever captured on a theoretical basis from an SkCanvas object. Since we no longer capture from SkCanvas, we can delete the methods and objects that aren't directly recordable from our own DisplayList APIs. These include:
- DLBuilder::setAttributesFromPaint(SkPaint)
- DL::setBlender (we only use the BlendMode enum, not custom blender objects)
- DL::drawPicture (no more SkPictures in the ui.Canvas/flow layers work flow)
- DL::drawSkVertices (no longer need to capture opaque SkVertices objects)
- DL::drawLattice (only ever appeared as a general form of drawImageNine)
The 1000 lines are almost all straight deletions, and maybe some comment updates to no longer discuss …
=> delete DL ops no longer needed after removing SkCanvasRecorder

impeller/typographer/backends/skia/text_render_context_skia.cc, impeller/typographer/typographer_unittests.cc
Fixes https://github.com/flutter/flutter/issues/121128
If a new glyph fit into the old atlas but the type changed we incorrectly reused the old atlas. make sure it is recreated if the type changes
=> [Impeller] dont append to existing atlas if type changed

shell/platform/darwin/ios/framework/Source/FlutterView.mm
As of Xcode 14.1, the pixel format we use isn't supported by the simulator.
If you try to execute with that pixel format in the simulator the metal api validation will crash.  Without validation you'll get a black screen or crash.  I've tested Safari on the simulator and it didn't render wide gamut colors either, so I don't think it works for any pixel format although it does report it's displays gamut is not sRGB. …
=> Turned off wide gamut color pixel format for the simulator

impeller/entity/contents/texture_contents.cc, impeller/entity/geometry.cc, impeller/entity/geometry.h, impeller/geometry/geometry_benchmarks.cc, impeller/geometry/geometry_unittests.cc, impeller/geometry/path.cc, impeller/geometry/path.h, impeller/renderer/renderer_unittests.cc, impeller/tessellator/tessellator_unittests.cc
Fixes https://github.com/flutter/flutter/issues/121540
See also https://github.com/dnfield/flutter_svg/issues/830 which has screenshots.
This patch mainly does two things:
- Makes sure that we pass a non-default tolerance value when creating a polyline for strokes. Previously, we calculated a tolerance but the method we called dropped the value on the floor (see first line of `StrokePathGeometry::CreateSolidStrokeVertices`). An "unused parameter" check wouldn't have caught this, since we use the parameter later in the method.
- Removes the stroke width from the calculation of the tolerance. This is error prone because a stroke_width of 0 means hairline for Flutter, but div by zero results in badness. I am not seeing any benefits when looking at this at various scales/high stroke widths.
- …
=> [Impeller] Change Path::CreatePolyline from tolerance to scale, and make it required

impeller/display_list/display_list_unittests.cc
Updated for the recent rename of drawPaint in the DL builder.
=> [Impeller] Fix test failure for IMPELLER_ENABLE_3D

shell/platform/fuchsia/flutter/pointer_injector_delegate.cc, shell/platform/fuchsia/flutter/pointer_injector_delegate.h, shell/platform/fuchsia/flutter/pointer_injector_delegate_unittest.cc
fxbug.dev/121767
Remove logspam when the child view gets torn down unexpectedly.
(https://github.com/flutter/flutter/issues/121433)
=> [fuchsia] Avoid log spam

tools/gn
This flag was removed from skia in https://skia-review.googlesource.com/c/skia/+/647796
=> Remove unused flag `skia_canvaskit_enable_particles`

impeller/renderer/backend/gles/context_gles.cc, impeller/renderer/backend/metal/context_mtl.mm, impeller/renderer/backend/vulkan/context_vk.cc, impeller/renderer/device_capabilities.cc, impeller/renderer/device_capabilities.h
We're not using texture->texture blits anywhere yet, but there are a couple of paths that will benefit from this in EntityPass. For the GL backend, it's GLES3 only, so we need to fallback to slower paths when it's not available.
=> [Impeller] Add texture->texture blits to device capabilities

impeller/tools/build_metal_library.py
My previous commit was exiting with an unhelpful error that did not contain the failure output. This prints the failure output more nicely.
=> Actually print out if xcrun metal fails

build/archives/BUILD.gn, lib/snapshot/BUILD.gn, sky/tools/create_macos_gen_snapshots.py
context: https://github.com/flutter/engine/pull/36026 moved gensnapshot to generators.
This PR deletes the meta data embedding previously done through BUILD.gn files for gen snapshot, and moves the logic to the generator script.
=> [gn + codesign] move snapshot meta data to generators

impeller/entity/entity_pass.cc, impeller/renderer/backend/metal/blit_pass_mtl.mm, impeller/renderer/renderer_unittests.cc
Use a blit for the root pass copy when available in the backend.
=> [Impeller] Use blit for root pass copy

testing/README.md, testing/run_tests.py
Adds some testing hints for developers so that it's easier to find the testing Wiki.
Re-landing #39868 with corrected pylint suggestion (now that the bots correctly run pylint in presubmit).
=> Reland: Add testing hints (#39868)

lib/ui/painting/image_decoder_impeller.cc
I can verify this with an integration test, but is that fact that we created mipmaps observable through the impeller API so I can write a simpler unittest?
Fixes https://github.com/flutter/flutter/issues/121015
=> [Impeller] dont create mipmap when mipcount == 1

lib/ui/text.dart
Fixes https://github.com/flutter/flutter/issues/121422.
`dart:ui` is now dartdoc-clean again. Sadly, we don't have a good way of enforcing on CI that it stays that way (https://github.com/dart-lang/dartdoc/issues/2278).
=> fix references to Text widget

shell/platform/embedder/embedder.h
Update the embedder API's documentation to recommend arrays of pointers to structures instead of arrays to structures.
Violations of this new guidance:
1. [`FlutterSemanticsUpdate`](https://github.com/flutter/engine/blob/137caa761540ed7d46b29eddd321997fb0d6d389/shell/platform/embedder/embedder.h#L1152-L1158) - Tracked by https://github.com/flutter/flutter/issues/121176
2. [`FlutterFrameBufferWithDamageCallback`](https://github.com/flutter/engine/blob/137caa761540ed7d46b29eddd321997fb0d6d389/shell/platform/embedder/embedder.h#L439-L447) - Adding members to `FlutterRect` will break the ABI, tracked by https://github.com/flutter/flutter/issues/121347
3. [`FlutterEngineNotifyDisplayUpdate`](https://github.com/flutter/engine/blob/137caa761540ed7d46b29eddd321997fb0d6d389/shell/platform/embedder/ …
=> [Embedder API] Add 'array of pointers' guidance

lib/ui/painting.dart, lib/web_ui/lib/src/engine/color_filter.dart
Just fixing a typo I noticed while looking through `ColorFilter` docs: https://api.flutter.dev/flutter/dart-ui/ColorFilter/ColorFilter.matrix.html
[breaking …
=> Fix typo in ColorFilter docs

impeller/aiks/aiks_unittests.cc
I added this caching because I wanted to make testing advanced blends easier, but this test happens to be useful for testing lots of draw calls.
=> [Impeller] Add checkbox for toggling the ColorWheel cache

display_list/display_list_canvas_unittests.cc, display_list/display_list_flags.h, display_list/display_list_ops.h, display_list/display_list_paint.cc, display_list/display_list_paint.h, display_list/display_list_paint_unittests.cc, display_list/dl_canvas.h, display_list/skia/dl_sk_canvas.cc, display_list/testing/dl_test_snippets.cc, display_list/testing/dl_test_snippets.h
Just a note that this PR may have a slight negative impact on the "display list builder" benchmarks as it adds a couple of new op variants to the list of DL test snippets which are used to measure the builder performance.
This PR adds new testing variants to the display_list_rendertests test suite. Previously we tested that the following graphics flows produced the same results graphically:
1. SkCanvas rendering to an SkSurface
2. ~DisplayListBuilder rendering, dispatched to an SkCanvas~ (replaced by # 6 below)
3. ~SkCanvas rendering captured into a DL~ (no longer represents an active Flutter work-flow)
4. SkPicture from # 1 and DL from ~# 2~ (now from # 6 below) that were recorded at 1x, rendered at 2x
The new rendering variations that are now added to the above are:
5. DlCanvas talking …
=> add DlCanvas(SkCanvas) vs DlCanvas(Builder) variants to DL rendertests

impeller/entity/contents/content_context.cc, impeller/entity/contents/content_context.h, impeller/entity/contents/contents.cc, impeller/entity/contents/filters/blend_filter_contents.cc, impeller/entity/contents/filters/border_mask_blur_filter_contents.cc, impeller/entity/contents/filters/color_matrix_filter_contents.cc, impeller/entity/contents/filters/gaussian_blur_filter_contents.cc, impeller/entity/contents/filters/linear_to_srgb_filter_contents.cc, impeller/entity/contents/filters/morphology_filter_contents.cc, impeller/entity/contents/filters/srgb_to_linear_filter_contents.cc, impeller/entity/contents/filters/yuv_to_rgb_filter_contents.cc
Force a label to be provided when using the offscreen pass utility. Right now, offscreen resources created by contents/filters all get the same names. This has always been a minor headache, but a couple of days ago this caused me quite a bit of friction when xcode decided to start incorrectly showing black textures for all of the pass previews.
=> [Impeller] Uniquely label offscreen resources

impeller/entity/contents/content_context.cc, impeller/entity/contents/content_context.h, impeller/entity/contents/contents.cc, impeller/entity/contents/filters/blend_filter_contents.cc, impeller/entity/contents/filters/border_mask_blur_filter_contents.cc, impeller/entity/contents/filters/color_matrix_filter_contents.cc, impeller/entity/contents/filters/gaussian_blur_filter_contents.cc, impeller/entity/contents/filters/linear_to_srgb_filter_contents.cc, impeller/entity/contents/filters/morphology_filter_contents.cc, impeller/entity/contents/filters/srgb_to_linear_filter_contents.cc, impeller/entity/contents/filters/yuv_to_rgb_filter_contents.cc
=> Revert "[Impeller] Uniquely label offscreen resources"

display_list/display_list.cc, display_list/display_list.h, flow/layers/display_list_layer_unittests.cc, flow/layers/display_list_raster_cache_item.cc, flow/raster_cache.cc, flow/raster_cache.h, flow/testing/mock_raster_cache.cc
This is the CP PR for https://github.com/flutter/flutter/issues/120985
=> [CP] Cached DisplayList opacity inheritance fix (#39690)

impeller/entity/contents/atlas_contents.cc, impeller/entity/contents/content_context.cc, impeller/entity/contents/content_context.h, impeller/entity/contents/contents.cc, impeller/entity/contents/filters/blend_filter_contents.cc, impeller/entity/contents/filters/border_mask_blur_filter_contents.cc, impeller/entity/contents/filters/color_matrix_filter_contents.cc, impeller/entity/contents/filters/gaussian_blur_filter_contents.cc, impeller/entity/contents/filters/linear_to_srgb_filter_contents.cc, impeller/entity/contents/filters/morphology_filter_contents.cc, impeller/entity/contents/filters/srgb_to_linear_filter_contents.cc, impeller/entity/contents/filters/yuv_to_rgb_filter_contents.cc
This broke the build due to conflicting merges. Revert commit: f2499194c22dd4633d9291bd3e93a4badd648c29.
=> [Impeller] Reland uniquely label offscreen resources

impeller/aiks/aiks_context.cc, impeller/aiks/aiks_context.h, impeller/aiks/aiks_playground.cc, impeller/entity/contents/content_context.cc, impeller/entity/contents/content_context.h, impeller/entity/entity_playground.cc
... in the Entities and Aiks playgrounds. Works on all backends.
WASD gets used for fly camera controls in Impeller Scene playgrounds, so I used `Z` to sorta match the Blender shortcut. Before I add more playground features I'm going to come up with a better way to package playground tool logic between the different kinds of playgrounds. All Entities tools should be usable in the Aiks and DL playgrounds, etc. And there needs to be a GUI that stuff like this can hook into. We shouldn't just add a million shortcuts and call it a day.
https://user-images.githubusercontent.com/919017/222307409-f4c1fcb1-b21b-4b3a-8499-c69cf02d1b80.mov
`EntityPass` is really good about not clearing attachments unnecessarily, and so uninitialized data shows up in these cases. We can add stuff to be smarter about …
=> [Impeller] Press `z` to toggle wireframe

.ci.yaml
Reverts flutter/engine#39736
The actual fix was related to glob behavior in https://github.com/flutter/cocoon/pull/2506.
We don't need `*.py` to run in both `Linux Host clang-tidy` and `Linux Android clang-tidy`, so remove the former.
=> Revert "[lint + clang tidy] add lint check for python file changes"

flow/paint_utils.cc, impeller/image/backends/skia/compressed_image_skia.cc, lib/ui/painting/image_decoder_skia.cc
In https://skia-review.googlesource.com/c/skia/+/651420 we are cleaning up #includes in our public headers.
This PR fixes the missing includes in Flutter that were a result of transitive #includes. …
=> Fix includes of SkBitmap/SkImage

lib/web_ui/lib/src/engine/browser_detection.dart, lib/web_ui/lib/src/engine/canvaskit/canvaskit_api.dart, lib/web_ui/lib/src/engine/canvaskit/renderer.dart, lib/web_ui/lib/src/engine/canvaskit/text.dart
This PR splits the decision making into two variables:
1. `browserSupportsCanvasKitChromium`: This only takes effect in `auto` mode. If it's true, then we try to download the Chromium variant first, and fallback to the full variant. _**(This is currently still hardcoded to false so users don't get the Chromium variant just yet)**_
2. `canvasKitVariant`: After CanvasKit is successfully downloaded, this variable contains the variant that was downloaded. This allows us to control what CanvasKit APIs to use depending on which CanvasKit variant we are using.
Required by https://github.com/flutter/engine/pull/39984
=> [web] Remember which variant of CanvasKit is being used

examples/glfw_drm/FlutterEmbedderGLFW.cc
This change fixes double free bug.
=> Fix double free or corruption exception (GLFW_drm example)

CODEOWNERS, shell/platform/embedder/BUILD.gn, shell/platform/embedder/embedder.cc, shell/platform/embedder/tests/embedder_frozen.h, shell/platform/embedder/tests/embedder_frozen_unittests.cc
The embedder API defines an ABI that must maintain both forward and backward compatibility. Some parts of the embedder API - like `FlutterSemanticsNode` or `FlutterSemanticsCustomAction` - must not change to guarantee forward ABI compatibility (see https://github.com/flutter/flutter/issues/121176 and https://github.com/flutter/flutter/issues/121347). This subset of the embedder API is "frozen".
This introduces tests that detect changes to the "frozen" subset of the embedder API. These are similar to golden tests:
1. `embedder_frozen.h` contains a snapshot of the expected "frozen" API
2. `embedder_frozen_unittests.cc` verifies the actual embedder API matches the expected "frozen" API.
Part of https://github.com/flutter/flutter/issues/121176
See …
=> [Embedder API] Freeze parts of API for ABI stability

shell/common/rasterizer.cc
kResubmit (along with kSkipAndRetry) indicate that ScopedFrame::Raster did not actually paint the frame.
Fixes https://github.com/flutter/flutter/issues/121678
=> Do not end the frame in the raster cache if ScopedFrame::Raster returns kResubmit

lib/ui/window.dart
The docs for MediaQueryData in the framework depend on this.
=> Restore the ViewConfiguration.displayFeatures doc template

lib/web_ui/lib/src/engine/initialization.dart, lib/web_ui/test/window_test.dart
Type checking is not well defined with JS interop. A safer approach is to type check JS values in JS using js_util. This CL implements such an explicit test.
=> [web] Add explicit JS type test for `JsStrategy`.

impeller/entity/entity_pass.cc, impeller/entity/entity_pass.h, impeller/entity/entity_playground.cc, impeller/entity/entity_playground.h, impeller/entity/entity_unittests.cc, impeller/entity/inline_pass_context.cc, impeller/entity/inline_pass_context.h
Discovered during investigation of opacity optimizations, currently OnRender will unconditionally end the current pass - but this is incorrect if we're merged into the parent pass. Detect this case and ensure that the collapsed child gets the same render target and render pass.
=> [Impeller] fix subpass collapse pass ending logic

shell/platform/windows/accessibility_bridge_windows.cc, shell/platform/windows/flutter_windows_engine.cc, shell/platform/windows/flutter_windows_engine.h, shell/platform/windows/flutter_windows_view.cc, shell/platform/windows/flutter_windows_view_unittests.cc
Today, the root accessibility semantics node is guaranteed to have ID 0. In a multi-window world, each view will have its own semantics tree, but semantic node IDs will be globally unique. In other words, the semantics tree's root will no longer be guaranteed to have ID 0.
This change removes another "root ID is 0" assumption from the Windows embedder that was missed in https://github.com/flutter/engine/pull/39441:
1. Remove a hardcoded ID `0` when getting the native root `IAccessible` object
2. Move logic to get the native root `IAccessible` object from `FlutterWindowsView` to `AccessibilityBridgeWindows`
Part of https://github.com/flutter/flutter/issues/119391 …
=> [Windows] Remove another accessibility root ID assumption

ci/builders/linux_host_engine.json, ci/builders/linux_web_engine.json, ci/builders/web_engine.json
Initial configuration for web engine builds using engine_v2 recipes. The implementation will be executed in multiple steps to allow to land fixes to recipes and web engine tooling along the way.
These are the expected steps:
* 1) Base build configuration - wasm build with the tests/generators running on it.
* 2) Test sub-subbuilds implementations
* 3) Tests sub-builds on multiple platforms
This PR covers i).
Bug: https://github.com/flutter/flutter/issues/119036 …
=> Add web_engine build configuration.

lib/web_ui/dev/steps/compile_tests_step.dart, third_party/canvaskit/BUILD.gn, web_sdk/BUILD.gn
This allows the flutter web server to easily find all variants of CanvasKit under one folder.
=> [web] Copy canvaskit_chromium/* to canvaskit/chromium/*

shell/platform/windows/BUILD.gn, shell/platform/windows/window_unittests.cc
Revert building with UIA by default on Windows. Making this separate PR instead of reverting the original to hopefully keep the testing logic for ensuring it is enabled for when we are ready to re-enable, just leaving it disabled for now.
https://github.com/flutter/flutter/issues/121907 …
=> [Windows] Revert UIA

flow/instrumentation.cc, flow/instrumentation.h
Previously this was comparing a float overlay rectangle size with an integer cache bitmap size.  This could result in mismatches if the overlay width is not an integer.
=> Always use integers to hold the size of the performance overlay cache bitmap

impeller/aiks/aiks_unittests.cc, impeller/typographer/backends/skia/text_frame_skia.cc
Resolves https://github.com/flutter/flutter/issues/121531.
Round glyph positions relative to the text run origin so that individual characters in the run will snap to the pixel grid together. Note that as the atlas changes, there may still be a subpixel/antialiasing jitter, but this should be much less apparent than the full 1 pixel jitter that this patch fixes. 
Before:
https://user-images.githubusercontent.com/919017/222868028-9cc38097-92c8-47e1-9b2b-1bcbb5d82a94.mov
After:
https://user-images.githubusercontent.com/919017/222868013-654b7598-07e7-4ae2-a985-e785747bc7af.mov
=> [Impeller] Round glyph locations per-run to fix per-glyph jitter

ci/licenses_golden/licenses_flutter, shell/platform/linux/BUILD.gn, shell/platform/linux/fl_platform_plugin.cc, shell/platform/linux/fl_platform_plugin_test.cc
Assuming copy/paste error as original commit has it returning a not implemented error. Noticed when editing adjacent code, hadn't seen it being a problem in practice.
=> Fix incorrect response to platform SystemSound.play

shell/platform/darwin/ios/framework/Source/FlutterDartProject.mm, shell/platform/darwin/ios/framework/Source/FlutterDartProjectTest.mm, shell/platform/darwin/ios/framework/Source/FlutterDartProject_Internal.h
`+[NSBundle bundleWithIdentifier]` is slow, and scales to the size of the app. This call during startup significantly affects the startup of `customer: chalk`. 
This implementation searches within the `privateFrameworksURL` where the default bundle is expected to be located. When tested internally, this improves startup of `customer: chalk` by 30% - see http://shortn/_WcifhO48X6.
It also falls back to `+[NSBundle bundleWithIdentifier]` so there is no functional change in behavior for customers that may be using alternate build systems.
Fix flutter/flutter#37826
If you need help, …
=> Optimize search for the default bundle

lib/web_ui/lib/src/engine/canvaskit/picture.dart, lib/web_ui/test/canvaskit/canvas_golden_test.dart
This undoes the optimization made in https://github.com/flutter/engine/pull/38573, and adds a test-case that would have failed when that optimization was made. The issue is that CanvasKit loses track of which resources belong to which context that leads to WebGL errors followed by UI corruption.
Fixes https://github.com/flutter/flutter/issues/121758
=> [canvaskit] read pixels back in Picture.toImage

shell/platform/darwin/macos/framework/Source/FlutterApplication.mm
In https://github.com/flutter/engine/pull/39836, There were some includes that VSCode added that didn't have the correct path, although they do compile in the engine repo, they cause problems when rolled to Google's internal repo because they don't have the correct prefix.
For future archaeologists, the setting to stop clangd from inserting headers that it doesn't really know how to insert properly is:
```json
"clangd.arguments": [
"--header-insertion=never"
],
```
=> Fix imports for FlutterApplication

impeller/display_list/display_list_unittests.cc
fix https://github.com/flutter/flutter/issues/122064
Related PR: https://github.com/flutter/engine/pull/39762 which modified 'saveLayer' to 'SaveLayer'
=> [Impeller] Fix the test 'Play/DisplayListTest.CanDrawBackdropFilter/Metal'

shell/platform/darwin/macos/framework/Source/FlutterApplication.mm
Fix imports for FlutterApplication …
=> [roll + cherry pick] Fix imports for FlutterApplication (#40100)

.ci.yaml
The build has been passing consistently and removing bringup will allow to validate changes to the build in presubmit.
Bug: https://github.com/flutter/flutter/issues/119036 …
=> Remove bringup from web engine build.

DEPS
The new Dart SDK dependency on the dart-lang/tools repo needs to be manually added to engine DEPS.
The new package includes a unified_analytics package used by the analysis server. The builds of Flutter engine with a prebuilt Dart SDK do not require it, but any builds of Flutter engine that build the Dart SDK do need this package.
The package was added to Dart DEPS in
https://dart-review.googlesource.com/c/sdk/+/283921
The package started being used in the SDK build process in commit https://dart-review.googlesource.com/c/sdk/+/286600
=> Add new Dart package dependency on dart-lang/tools

shell/platform/embedder/embedder_surface_vulkan.cc, shell/platform/embedder/embedder_surface_vulkan.h
This fixes a couple of files where the include path started with "shell/" instead of "flutter/shell/". This is for consistency with other includes.
=> Fix some includes missing "flutter/" prefix.

shell/platform/linux/fl_gl_area.cc, shell/platform/linux/fl_gl_area.h, shell/platform/linux/fl_view.cc, shell/platform/linux/public/flutter_linux/fl_view.h
Further simplification from https://github.com/flutter/engine/pull/39467
=> Use a single FlGLArea

lib/web_ui/dev/build.dart, lib/web_ui/dev/environment.dart
When there's a problem in CanvasKit, it's useful to have an easy way to make a profile build. Now passing `--profile` to `felt build` will build everything in profile mode including CanvasKit. The output is located at `wasm_profile` instead of the usual `wasm_release`.
While I'm at it, I also added a target for the `archive`.
=> [web][felt] Add 'archive' target + 'profile' mode

shell/platform/darwin/ios/framework/Source/FlutterPlatformViews.mm, shell/platform/darwin/ios/framework/Source/FlutterPlatformViewsTest.mm
It turns out that in the benchmark test, `BringLayersIntoView` is called every frame, even if view hierarchy stays the same, resulting in unnecessary subview reordering. 
For example, let's say we have subviews array `[v1, v2, v3]`: 
`[v1, v2, v3]` (initial config, v3 is the top) 
=> `addSubview(v1)` brings v1 to top, it becomes `[v2, v3, v1]` 
=> `addSubview(v2)` brings v2 to top, it becomes `[v3, v1, v2]`
=> `addSubview(v3)` brings v3 to top, it becomes `[v1, v2, v3]`
The fix is simply *to check if the view hierarchy stays the same, and avoid manipulating the subviews if not necessary.*
It used to be fine before https://github.com/flutter/engine/pull/39527, because we simply set the zPosition, which is much less costly. However, we should probably investigate whether we can avoid …
=> [platform_view]fix regression for addSubview when re-ordering

fml/concurrent_message_loop.cc, fml/concurrent_message_loop.h, lib/ui/painting.dart, lib/ui/painting/immutable_buffer.cc, shell/common/fixtures/shell_test.dart, shell/common/shell_unittests.cc
Reverts flutter/engine#39918
Reverting for framework device lab failure https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_android%20microbenchmarks/9292/overview
=> Revert "[engine] move asset mapping copy to background thread"

shell/platform/android/BUILD.gn
inputs = [ "android_exports.lst" ]
was missing from the flutter_shell_native rule, which meant if you edited android_exports.lst it would not notice and would not rebuild/relink.
- [x ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on writing and running engine tests.
- [x ] I updated/added relevant documentation (doc comments with `///`).
- [ x] I signed the [CLA].
- [ x] All existing and new tests are …
=> Add missing inputs declaration

lib/web_ui/lib/src/engine/canvaskit/text.dart, lib/web_ui/lib/src/engine/canvaskit/text_fragmenter.dart, lib/web_ui/test/canvaskit/canvaskit_api_test.dart
In tests, when we use the `SkParagraphBuilder` APIs directly (bypassing our `CkParagraphBuilder`) then we need to explicitly pass any client ICU data that it needs.
=> [web] Fix SkParagraphBuilder tests for the chromium variant

testing/scenario_app/ios/Runner/GeneratedPluginRegistrant.h, testing/scenario_app/ios/Runner/GeneratedPluginRegistrant.m, testing/scenario_app/lib/main.dart, testing/scenario_app/lib/src/animated_color_square.dart, testing/scenario_app/lib/src/bogus_font_text.dart, testing/scenario_app/lib/src/get_bitmap_scenario.dart, testing/scenario_app/lib/src/initial_route_reply.dart, testing/scenario_app/lib/src/locale_initialization.dart, testing/scenario_app/lib/src/platform_echo_mixin.dart, testing/scenario_app/lib/src/platform_view.dart, testing/scenario_app/lib/src/poppable_screen.dart, testing/scenario_app/lib/src/scenario.dart, testing/scenario_app/lib/src/scenarios.dart, testing/scenario_app/lib/src/texture.dart, testing/scenario_app/lib/src/touches_scenario.dart, testing/scenario_app/pubspec.yaml
=> Remove single-window assumption from scenario_app

shell/platform/linux/fl_view.cc
Handling of keyboard focus for Flutter text fields appears to have regressed with https://github.com/flutter/engine/pull/39473, which removed the call to `gtk_widget_set_can_focus`
=> Make the Linux GTK widget focusable

shell/platform/android/io/flutter/embedding/android/FlutterActivityAndFragmentDelegate.java, shell/platform/android/test/io/flutter/embedding/android/FlutterActivityAndFragmentDelegateTest.java
fixes b/271100292
Edit: Fixes https://github.com/flutter/flutter/issues/121244. …
=> Android: Made sure we get the initial route from the intent.

shell/platform/common/accessibility_bridge.cc, shell/platform/common/accessibility_bridge.h, shell/platform/common/accessibility_bridge_unittests.cc, shell/platform/common/flutter_platform_node_delegate_unittests.cc, shell/platform/darwin/macos/framework/Source/AccessibilityBridgeMacTest.mm, shell/platform/darwin/macos/framework/Source/FlutterPlatformNodeDelegateMacTest.mm, shell/platform/darwin/macos/framework/Source/FlutterViewController.mm, shell/platform/windows/accessibility_bridge_windows_unittests.cc, shell/platform/windows/flutter_windows_engine.cc, shell/platform/windows/flutter_windows_view_unittests.cc
This updates `AccessibilityBridge::AddFlutterSemanticsNodeUpdate` and `AccessibilityBridge::AddFlutterSemanticsCustomActionUpdate` to accept references instead of pointers as null isn't an acceptable input and these aren't out parameters.
This code is shared by both the macOS and Windows embedders but not the Linux embedder.
Part of: https://github.com/flutter/flutter/issues/121176 …
=> [Desktop] Use references for semantics update

impeller/fixtures/stroke.comp, impeller/playground/compute_playground_test.cc, impeller/playground/compute_playground_test.h, impeller/renderer/BUILD.gn, impeller/renderer/compute_subgroup_unittests.cc, impeller/renderer/compute_unittests.cc
Some minor cleanup around buffer creation.
Adds code to existing test to make the heart cubics actually render.
This shows some problems especially around cusps when you bump up the stroke width, which I'll look at in a separate patch.
=> [Impeller] Render a compute generated stroke

shell/platform/embedder/embedder.h, shell/platform/embedder/tests/embedder_frozen.h, shell/platform/embedder/tests/embedder_frozen_unittests.cc
Part of https://github.com/flutter/flutter/issues/121176
Fixes https://github.com/flutter/flutter/issues/121347
Imagine the following change:
<details>
<summary>Bad change...</summary>
```diff
typedef struct {
/// The size of this struct. Must be sizeof(A).
size_t struct_size;
int one;
+ int two;
} A;
typedef struct {
/// The size of this struct. Must be sizeof(B).
size_t struct_size;
A a;
int three;
} B;
```
</details>
Adding a member to struct `A` would change the memory layout of struct `B`; this breaks ABI compatibility. The structs' `struct_size` does not protect against this ABI break. Instead, struct `B` should've nested struct `A` by pointer:
<details>
<summary>Good change...</summary>
```diff
typedef struct {
/// The size of this struct. Must be sizeof(A).
size_t struct_size;
int …
```
=> [Embedder API] Lock nested structs for ABI stability

analysis_options.yaml
Part of https://github.com/flutter/flutter/issues/118837.
This is in preparation for Dart 3. Some case expressions that are valid in Dart 2.19 and below will become an error or have changed semantics when a library is upgraded to 3.0. This lint bans those expressions in order to ease migration to Dart 3.0.
Luckily, we didn't have any offenders in the code base.
=> Enable invalid_case_patterns lint
