flutter/engine

shell/platform/android/io/flutter/plugin/editing/TextInputPlugin.java
Fixes https://github.com/flutter/flutter/issues/10748
=> Call Selection.removeSelection if the framework has cleared the selection

shell/common/switches.cc, shell/common/switches.h
Reverts flutter/engine#3781
Need to update to a newer version of the FTL at the same time.
=> Revert "Update switches to use StringView."

lib/ui/painting.dart
There doesn't seem to be any need for this limitation.
cc @abarth
=> Allow infinite cull rects.

BUILD.gn, DEPS, common/settings.h, lib/ui/BUILD.gn, lib/ui/text/paragraph.cc, lib/ui/text/paragraph.h, lib/ui/text/paragraph_builder.cc, lib/ui/text/paragraph_builder.h, lib/ui/text/paragraph_impl.cc, lib/ui/text/paragraph_impl.h, lib/ui/text/paragraph_impl_blink.cc, lib/ui/text/paragraph_impl_blink.h, lib/ui/text/paragraph_impl_txt.cc, lib/ui/text/paragraph_impl_txt.h, shell/common/shell.cc, shell/common/switches.h, shell/platform/android/io/flutter/app/FlutterActivityDelegate.java, sky/packages/sky_engine/LICENSE, travis/licenses_golden/licenses_flutter, travis/licenses_golden/licenses_lib
This reverts commit d2c77f973dd3880d83f37842faf4742ab911c47f. Gary has
landed https://fuchsia-review.googlesource.com/#/c/35230/ for Fuchsia.
=> Reland "Initial integration of libtxt with Flutter alongside Blink."

shell/platform/android/io/flutter/app/FlutterActivityDelegate.java
See https://github.com/flutter/flutter/issues/10813
=> Set the initial route before launching the Dart app

shell/common/engine.cc, shell/platform/darwin/ios/framework/Source/FlutterViewController.mm
plus small bugfix in engine.cc.
=> Send AppLifecycleState notifications on FlutterViewController lifecycle events.

shell/platform/darwin/ios/framework/Source/FlutterViewController.mm
=> Fix compile error in FlutterViewController

shell/platform/android/io/flutter/app/FlutterActivity.java
Fixes https://github.com/flutter/flutter/issues/10571
=> Remove FlutterActivity#onFlutterReady()

shell/platform/android/io/flutter/plugin/editing/TextInputPlugin.java
If restartInput is called twice in quick succession, then the IME may output
warnings related to usage of the obsolete connection resulting from the first
call.
Fixes https://github.com/flutter/flutter/issues/10730
=> Do not call restartInput twice when setting a new text input client.

shell/platform/android/io/flutter/view/AccessibilityBridge.java
Fixes https://github.com/flutter/flutter/issues/10855
=> Revert to API level 16 compatible variant of AccessibilityNodeInfo.addAction

DEPS, sky/packages/sky_engine/LICENSE, tools/licenses/lib/main.dart, travis/licenses_golden/licenses_lib
Also fix the license script to not use "lib" as a library name.
=> Roll tonic to pick up my crash fixes

flow/compositor_context.h, flow/layers/layer.h, flow/layers/layer_tree.cc, flow/layers/picture_layer.cc, flow/raster_cache.cc, flow/raster_cache.h, flow/raster_cache_unittests.cc, lib/ui/painting/image_decoding.cc, shell/common/platform_view.cc, shell/gpu/gpu_surface_gl.cc, shell/gpu/gpu_surface_gl.h, shell/platform/android/android_context_gl.cc, shell/platform/android/android_context_gl.h, shell/platform/android/android_surface_gl.cc, shell/platform/android/android_surface_gl.h, shell/platform/darwin/ios/ios_gl_context.h, shell/platform/darwin/ios/ios_gl_context.mm, shell/platform/darwin/ios/ios_surface_gl.h, shell/platform/darwin/ios/ios_surface_software.mm
Reverts flutter/engine#3818
Simple problem - missed updating test code to match PrerollContext related API changes. I'll prepare an updated version on Monday.
=> Revert "Reland "Run Flutter on iOS and Android with color correct Skia""

content_handler/runtime_holder.cc
Fixes https://github.com/flutter/flutter/issues/10569
=> Convert Fuchsia event timestamps to microseconds

DEPS
I'm hoping this fixes the build. If not, I'll start rolling back.
=> upgrade buildroot to pick up analyzer fixes

flow/compositor_context.h, flow/layers/layer.h, flow/layers/layer_tree.cc, flow/layers/picture_layer.cc, flow/raster_cache.cc, flow/raster_cache.h, flow/raster_cache_unittests.cc, lib/ui/painting/image_decoding.cc, shell/common/platform_view.cc, shell/gpu/gpu_surface_gl.cc, shell/gpu/gpu_surface_gl.h, shell/platform/android/android_context_gl.cc, shell/platform/android/android_context_gl.h, shell/platform/android/android_surface_gl.cc, shell/platform/android/android_surface_gl.h, shell/platform/darwin/ios/ios_gl_context.h, shell/platform/darwin/ios/ios_gl_context.mm, shell/platform/darwin/ios/ios_surface_gl.h, shell/platform/darwin/ios/ios_surface_software.mm
Another attempt at #3818, #3776. This is identical to the #3818, plus compile fixes for the test code that I forgot to update. Now both host and target builds succeed.
=> Reland "Run Flutter on iOS and Android with color correct Skia

lib/ui/painting/image.cc, lib/ui/painting/image.h, lib/ui/painting/picture.cc, lib/ui/painting/picture.h, lib/ui/text/paragraph.cc, lib/ui/text/paragraph.h
Fixes https://github.com/flutter/flutter/issues/11007
=> Report size estimates to Dart for Image/Picture/Paragraph objects

shell/platform/android/io/flutter/view/AccessibilityBridge.java
See also https://github.com/flutter/engine/pull/3701
=> Fix a11y scroll direction

content_handler/runtime_holder.cc
Fixes https://github.com/flutter/flutter/issues/10061
=> Send text input action events on Fuchsia

DEPS, lib/snapshot/BUILD.gn, travis/licenses_golden/licenses_dart
Roll Dart to f445c318184b30b3db997ac27f357bcb5d45670a.
Fuchsia issue TO-365
=> GN: Use a depfile when generating the core snapshot.

shell/platform/android/io/flutter/plugin/editing/TextInputPlugin.java
See https://github.com/flutter/flutter/issues/11041
=> Do not try to apply selections outside the length of the text

DEPS, tools/gn, travis/licenses_golden/licenses_dart
Roll Dart VM to daa38a2ea21d290e45adb509dc60418b22ec7eba for fix to Thumb profile sample collection.
=> Changes to get the profiler working for C code on Android.

DEPS, travis/licenses_golden/licenses_dart
Fixes https://github.com/flutter/flutter/issues/11100.
=> Roll Dart to 1bfd01c1f7a57fed039ce8ab95df2a5f14cf63b6

runtime/dart_init.cc, runtime/dart_service_isolate.cc
=> Allow SIGQUIT to toggle the vm-service server a la command line Dart.

content_handler/vulkan_rasterizer.cc
=> [content handler] Fix waiting for GPU.

shell/platform/android/io/flutter/plugin/editing/TextInputPlugin.java
See https://github.com/flutter/flutter/issues/11168
=> Enable text autocorrect on Android with a flag to disable it

shell/platform/darwin/ios/framework/Source/FlutterViewController.mm
Related to https://github.com/flutter/engine/pull/3870.
=> Fix engine on iOS

flow/compositor_context.h, flow/layers/layer.h, flow/layers/layer_tree.cc, flow/layers/picture_layer.cc, flow/raster_cache.cc, flow/raster_cache.h, flow/raster_cache_unittests.cc, lib/ui/painting/image_decoding.cc, shell/common/platform_view.cc, shell/gpu/gpu_surface_gl.cc, shell/gpu/gpu_surface_gl.h, shell/platform/android/android_context_gl.cc, shell/platform/android/android_context_gl.h, shell/platform/android/android_surface_gl.cc, shell/platform/android/android_surface_gl.h, shell/platform/darwin/ios/ios_gl_context.h, shell/platform/darwin/ios/ios_gl_context.mm, shell/platform/darwin/ios/ios_surface_gl.h, shell/platform/darwin/ios/ios_surface_software.mm
This reverts commit 2d9155e174d83e9646c951dbbc85fe1eda8b20e9.
Fixes flutter/flutter#11169 (regression with semitransparent images)
=> Revert "Reland "Run Flutter on iOS and Android with color correct Skia (#3826)"

shell/platform/android/io/flutter/plugin/editing/TextInputPlugin.java
See https://github.com/flutter/engine/pull/3866
=> Invert the autocorrect flag

shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm
Adds handling for the autocorrect field on TextField on iOS devices.
=> Set iOS text field autocorrection type

shell/platform/android/io/flutter/view/AccessibilityBridge.java
Fixes https://github.com/flutter/flutter/issues/1662 for Android, was already working on iOS.
=> Wire up SemanticsAction Increase and Decrease on Android

DEPS, travis/licenses_golden/licenses_lib
=> Bump FTL to 81aa1ca480c99caffbc2965deb0a6f7ac7f59f1c

shell/common/platform_view_service_protocol.cc
Reverts flutter/engine#3892 to un-break fuchsia
=> Revert "Switch to new encode API on SkPixelSerializer"

lib/ui/BUILD.gn, lib/ui/painting/utils.cc, lib/ui/painting/utils.h, travis/licenses_golden/licenses_flutter
See https://github.com/dart-lang/sdk/issues/29971
=> Accumulate a batch of Skia objects that will be destructed later on the IO thread

shell/common/platform_view_service_protocol.cc
Reverts flutter/engine#3894
Fuchsia has rolled to a point that has this API, so we can proceed with switching over.
=> Revert "Revert "Switch to new encode API on SkPixelSerializer""

build/flutter_app.gni
This is needed for https://fuchsia-review.googlesource.com/c/37541
=> Use shared library output from shared toolchain

flow/compositor_context.h, flow/layers/layer.h, flow/layers/layer_tree.cc, flow/layers/picture_layer.cc, flow/raster_cache.cc, flow/raster_cache.h, flow/raster_cache_unittests.cc, lib/ui/painting/image_decoding.cc, shell/common/platform_view.cc, shell/gpu/gpu_surface_gl.cc, shell/gpu/gpu_surface_gl.h, shell/platform/android/android_context_gl.cc, shell/platform/android/android_context_gl.h, shell/platform/android/android_surface_gl.cc, shell/platform/android/android_surface_gl.h, shell/platform/darwin/ios/ios_gl_context.h, shell/platform/darwin/ios/ios_gl_context.mm, shell/platform/darwin/ios/ios_surface_gl.h, shell/platform/darwin/ios/ios_surface_software.mm
=> Reland (again) "Run Flutter on iOS and Android with color correct Skia"

shell/platform/android/vsync_waiter_android.cc
=> Enable the “Highlight Vsync” option in the timeline viewer on Android.

fml/trace_event.cc, fml/trace_event.h
The signatures are the same as the trace events in Fuchsia.
=> Add support for flow traces in fml/trace_event.

synchronization/pipeline.h
=> Visualize pipeline items in the various stages as trace flows.

lib/ui/geometry.dart
Will make debugging layer trees with PhysicalLayers easier.
=> Cleaner RRect.toString

lib/ui/painting/image_decoding.cc
=> Visualize image decoding and texture upload using trace flows.

shell/common/engine.cc
#https://github.com/flutter/flutter/issues/11246
=> Always schedule a frame on app did become active

DEPS, travis/licenses_golden/licenses_third_party
Verified roll in Fuchsia made by https://fuchsia.googlesource.com/manifest/+/11c555660772d10c7e4ae772cdfcbf43a0f06bec.
=> Roll Skia revision to 89d9d95570227533e4a87b41e5a7ed9fad4dd04a.

content_handler/BUILD.gn, content_handler/runtime_holder.cc, lib/ui/compositing/scene_host.cc
This is the Flutter side of: https://fuchsia-review.googlesource.com/q/topic:ianloic-handle_table
=> Use the tonic::HandleTable.

tools/licenses/lib/patterns.dart
See https://github.com/flutter/engine/pull/3881
=> Simplify a license script regex that was not completing on a Skia source file

lib/ui/painting.dart, lib/ui/window.dart
fyi @abarth a lot of these docs are basically your words massaged into doc form.
=> More documentation, mainly around saveLayer.

lib/ui/window.dart, shell/platform/darwin/ios/framework/Source/FlutterViewController.mm
Fixes https://github.com/flutter/flutter/issues/11421
=> Extend iOS's drawing time to viewWillAppear <-> viewDidDisappear

shell/platform/android/io/flutter/plugin/editing/InputConnectionAdaptor.java
Fixes https://github.com/flutter/flutter/issues/11437
=> Check for an empty selection in deleteSurroundingText

shell/platform/android/io/flutter/plugin/editing/InputConnectionAdaptor.java
Fixes https://github.com/flutter/flutter/issues/11352
=> Support sendKeyEvent for arrow keys

DEPS
This updates our compilers, GN and Ninja binaries.
=> Update builtools and buildroot revisions.

tools/licenses/lib/main.dart
On linux the licenses tools progress reporting was cluttering the screen with extra characters and sometimes was missing the last progress update.
=> Upgrade progress reporting in licenses tool

DEPS, travis/licenses_golden/licenses_dart
This contains the fix for the critical HTTP bug.
/cc @jason-simmons @zanderso
=> roll Dart to 21eddc429e9c7260de00a9af7cad94baba830f59

DEPS, travis/licenses_golden/licenses_third_party
Buildroot update includes .gitignore change.
=> Add Google Benchmark (from Fuchsia) to DEPS.

BUILD.gn, DEPS, travis/licenses_golden/licenses_dart
This reverts commit a5bac1ee09668f4687dc81c74bcf8adcad85cd7c.
This broke Windows build, reverting while investigating.
=> Revert "Build standalone dart sdk as part of Flutter engine. (#3954)"

DEPS, lib/snapshot/BUILD.gn, runtime/BUILD.gn, shell/common/BUILD.gn, sky/packages/sky_engine/BUILD.gn, travis/licenses_golden/licenses_dart
This PR adjusts some Flutter GN build files to account for Dart switching from *_sources.gypi to *_sources.gni for source file lists.
=> Fixes for gypi -> gni change in Dart

shell/platform/android/io/flutter/app/FlutterActivityDelegate.java
Add a flutter specific flag for extending the splash screen.
Checking for Android theme attributes alone might be ambiguous because themes other than a specific launch splash theme may also contain windowBackground drawables. 
https://github.com/flutter/flutter/issues/8127
=> Add an explicit configurable check for whether to extend the splash screen

DEPS, runtime/dart_init.cc, travis/licenses_golden/licenses_dart
- Roll Dart to 491390eeaa7974f44a8931d10a899c39c0df8dda
- Register the EmbedderInformationCallback
=> Roll Dart to 491390eeaa7974f44a8931d10a899c39c0df8dda

lib/ui/painting.dart
Fixes https://github.com/flutter/flutter/issues/11586
=> Allow infinity values in the Dart wrappers for Skia Canvas

frontend_server/lib/server.dart
Forgot to add comment as @Hixie suggested, adding it now.
=> Missed one feedback item from https://github.com/flutter/engine/pull/3982

content_handler/runtime_holder.cc, flow/BUILD.gn, flow/export_node.cc, flow/export_node.h, lib/snapshot/fuchsia_compilation_trace.txt, lib/ui/BUILD.gn, lib/ui/compositing.dart, lib/ui/compositing/scene_host.cc, lib/ui/compositing/scene_host.h, runtime/dart_vm_entry_points_fuchsia.txt, shell/platform/android/io/flutter/view/FlutterView.java
This is part of this set of changes: https://fuchsia-review.googlesource.com/q/topic:%22ianloic-new_bindings%22
=> Update to new Dart FIDL bindings API.

lib/ui/text.dart, lib/ui/text/paragraph_builder.cc, sky/engine/core/rendering/style/RenderStyleConstants.h, sky/engine/platform/text/TextDirection.h
=> Pass TextDirection to ParagraphBuilder.

shell/platform/android/io/flutter/app/FlutterActivityDelegate.java
https://github.com/flutter/flutter/issues/8147
=> Let Android have a fade animation too when removing the splash screen

shell/platform/darwin/ios/framework/Headers/FlutterAppDelegate.h, shell/platform/darwin/ios/framework/Source/FlutterAppDelegate.mm
https://github.com/flutter/flutter/issues/11349
=> Let the FlutterAppDelegate's messenger be customizable if the rootViewController isn't a FlutterViewController

shell/platform/android/io/flutter/view/AccessibilityBridge.java
=> Traverse children from top left to bottom right for a11y

lib/ui/semantics.dart, lib/ui/semantics/semantics_node.h, lib/ui/semantics/semantics_update_builder.cc, lib/ui/semantics/semantics_update_builder.h, shell/platform/android/io/flutter/view/AccessibilityBridge.java, shell/platform/android/platform_view_android.cc, shell/platform/darwin/ios/framework/Source/accessibility_bridge.mm
This just pushes textDirection data from the Dart side to the native side. It doesn't do anything with it.
cc @goderbauer
=> Implement i18n features in the a11y API.

runtime/dart_vm_entry_points_fuchsia.txt
This is the Flutter equivalent of https://fuchsia.cl/56646
=> Add new entry points for dart:fidl.internal

tools/licenses/lib/main.dart, travis/licenses.sh, travis/licenses_golden/licenses_flutter, travis/licenses_golden/licenses_garnet, travis/licenses_golden/licenses_lib
See https://github.com/flutter/engine/pull/4043
=> Update the license script for the Garnet tree

shell/platform/android/io/flutter/view/AccessibilityBridge.java
/cc @jason-simmons 
Usage example: https://github.com/flutter/flutter/pull/11909
=> Wire up basic a11y channel for a11y events

DEPS, travis/licenses_golden/licenses_dart
Roll dart to pick kernel serialization fixes.
=> Roll dart dep

tools/gn
Fixes https://github.com/flutter/flutter/issues/11952
=> Set the is_official_build flag that disables GR_TEST_UTILS in Skia

shell/platform/android/io/flutter/view/AccessibilityBridge.java
Adaptations for https://github.com/flutter/flutter/pull/11909.
=> refactor accessibility channel to use StandardMessageCodec

shell/platform/darwin/desktop/flutter_window.mm, shell/platform/darwin/ios/ios_gl_context.mm
These seemed to have slipped through the cracks in the previous two renaming commits.
=> More renaming of FTL->FXL

.travis.yml, CONTRIBUTING.md, travis/format.sh
This will require https://github.com/flutter/engine/pull/4088 to be submitted before travis is happy.
=> Enforce clang-format for c-like sources on Travis

tools/licenses/README.md
=> Clarify licenses/README.md

tools/licenses/README.md
=> More clarification about license script

lib/ui/ui_dart_state.h, runtime/dart_controller.cc, runtime/dart_controller.h, runtime/dart_init.cc, runtime/runtime_controller.cc, runtime/runtime_controller.h
https://github.com/flutter/flutter/issues/12089 prevents engine roll
=> Reverting to unblock engine roll

DEPS
Makes it easy to upload a Dart change from a Flutter client.
=> DEPS: Change the URL for Dart to the new Gerrit instance.

lib/ui/geometry.dart
This will make it easier to implement BorderRadius RTL in a manner consistent with EdgeInsets.
=> Add operators to Radius

content_handler/BUILD.gn, content_handler/accessibility_bridge.cc, content_handler/accessibility_bridge.h, content_handler/runtime_holder.cc, content_handler/runtime_holder.h, travis/licenses_golden/licenses_flutter
Add a class to track onscreen text via SemanticsNodes from the
accessibility layer, and report this text to the ContextEngine.
=> Report onscreen text to Fuchsia context engine.

content_handler/accessibility_bridge.cc
It's not an error to be unable to connect to the context service.
=> Remove spurious error message

shell/platform/android/io/flutter/plugin/editing/InputConnectionAdaptor.java
Apparently I made an accidental paste into the source.
=> Fixing accidental paste.

shell/platform/android/io/flutter/view/AccessibilityBridge.java
Framework changes: https://github.com/flutter/flutter/pull/12263
=> Send scroll progress with a11y event TYPE_VIEW_SCROLLED

build/flutter_app.gni, content_handler/BUILD.gn, flow/BUILD.gn, lib/snapshot/BUILD.gn, lib/ui/BUILD.gn, lib/ui/compositing.dart
These libraries are in Topaz now.
=> Update paths to Fuchsia libraries

shell/platform/android/io/flutter/view/AccessibilityBridge.java
Required for https://github.com/flutter/flutter/issues/12275.
=> Proper horizontal a11y scrolling on Android

frontend_server/lib/server.dart
Fixes [dartbug.com/30869](dartbug.com/30869)
=> Switch from FlutterTarget to FlutterFastaTarget

DEPS, frontend_server/lib/server.dart, travis/licenses_golden/licenses_dart
* Switch from FlutterFastaTarget to FlutterTarget as FlutterFastaTarget was removed.
=>  Roll Dart to 9ee73fe322ce3875a6b1f16ba16d64b11c680e90

DEPS, lib/snapshot/BUILD.gn, travis/licenses_golden/licenses_dart
This change broke the Fuchsia build.
Reverts flutter/engine#4180
=> Revert "Roll dart to pick up change where platform.dill was removed"

frontend_server/lib/server.dart, frontend_server/test/server_test.dart
This is needed to support Flutter app restart request.
=> Add reset method to reset incremental compiler.

CONTRIBUTING.md
...if the environment is already setup
/cc @jason-simmons @chinmaygarde
=> CONTRIBUTING.md: suggest skipping intro

BUILD.gn, lib/snapshot/BUILD.gn
This reverts commit 83224fb6012c893b78c75e87184d3877c088394a.
=> Revert "Change kernel platform generation dependency name (#4189)"

content_handler/app.cc
Reverts flutter/engine#4182
Causes flutter_runner crash.
=> Revert "Set ui, io, and gpu thread names."

BUILD.gn, lib/snapshot/BUILD.gn
Removed bad change that required the revert.
=> Resubmit fix dep

DEPS, travis/licenses_golden/licenses_dart
This picks up a change that fixes preview-dart-2 tests
=> Roll dart to 87538ffd7eca3405d13e46dcf3a20dcdcde9761e

shell/platform/android/android_surface.h, shell/platform/android/android_surface_gl.cc, shell/platform/android/android_surface_gl.h, shell/platform/android/android_surface_software.cc, shell/platform/android/android_surface_software.h, shell/platform/android/android_surface_vulkan.cc, shell/platform/android/android_surface_vulkan.h, shell/platform/android/platform_view_android.h
This was used by AndroidSurfaceSoftware but is now obsolete
=> Remove AndroidSurface::SetFlutterView

lib/ui/painting.dart
Fixes https://github.com/flutter/flutter/issues/12513
=> Remove unnecessary assert in drawAtlas

shell/common/engine.cc, shell/common/engine.h, shell/common/switches.h, shell/platform/android/io/flutter/view/FlutterMain.java
First step of removing FLX. There will be a companion PR in flutter adding the snapshot file to the data dir.
cc @tvolkert
=> Read snapshot directly from data dir instead of FLX

shell/platform/android/io/flutter/view/AccessibilityBridge.java
Will follow-up with compatible iOS change
=> Support accessibility announcements in the Android AccessibilityBridge

BUILD.gn
This declaration makes it easier for Fuchsia to include Flutter in the system
image.
=> Add Fuchsia package() declaration

tools/gen_objcdoc.sh
See: https://github.com/realm/jazzy/issues/791
=> Use iphonesimulator SDK for Obj-C doc generation

sky/engine/wtf/PageAllocator.cpp
madvise returns zero on success
=> Invert the error code check on madvise

shell/platform/android/io/flutter/plugin/editing/TextInputPlugin.java, shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm
Changes made to the engine for Android and iOS keyboard behavior i.e.
a) Capitalization at beginning of a sentence
b) Capitalization after a period
=> Native keyboard behavior update for multiline input

lib/ui/semantics.dart, lib/ui/semantics/semantics_node.h, shell/platform/android/io/flutter/view/AccessibilityBridge.java, shell/platform/darwin/ios/framework/Source/accessibility_bridge.mm
First step for fixing https://github.com/flutter/flutter/issues/11992
=> Add a semantic isButton flag

lib/ui/semantics.dart
Missed that part in 3d013382e650e7272f6a0ee84f39c4d9ea5a85bb
=> Add isButton to SemanticsFlags.values

shell/common/engine.cc
This is a small fix for my previous CL.
=> Pass missing parameter.

lib/ui/semantics.dart, lib/ui/semantics/semantics_node.h, lib/ui/semantics/semantics_update_builder.cc, lib/ui/semantics/semantics_update_builder.h, shell/platform/android/io/flutter/view/AccessibilityBridge.java, shell/platform/android/platform_view_android.cc, shell/platform/darwin/ios/framework/Source/accessibility_bridge.mm
Required for https://github.com/flutter/flutter/issues/12271.
=> Support for accessibility label and hint

lib/ui/text/paragraph_impl_txt.cc, third_party/txt/src/txt/paragraph.cc, third_party/txt/src/txt/paragraph.h, third_party/txt/tests/paragraph_unittests.cc
* rename glyph_position_x to glyph_lines
* use round instead of roundf
* return a range start/end struct in Paragraph::GetWordBoundary
=> libtxt: some cleanup

lib/ui/painting.dart, testing/dart/color_test.dart
Will remove from Material's ThemeData after
=> Add luminance getter to Color

lib/ui/semantics.dart, lib/ui/semantics/semantics_node.h, lib/ui/semantics/semantics_update_builder.cc, lib/ui/semantics/semantics_update_builder.h, shell/platform/darwin/ios/framework/Source/accessibility_bridge.mm
=> Announce the correct new value after increase/decrease action on iOS

shell/common/platform_view_service_protocol.cc, shell/common/platform_view_service_protocol.h
This will replace the one in the diagnostic server
=> Add an SkPicture screenshot handler to the service protocol

shell/common/engine.cc
Fixes https://github.com/flutter/flutter/issues/12739
=> Fix regression - configure asset bundle

shell/platform/embedder/BUILD.gn, shell/platform/embedder/embedder.cc, shell/platform/embedder/fixtures/simple_main.dart, shell/platform/embedder/tests/embedder_unittests.cc, travis/licenses_golden/licenses_flutter
Does not terminate shell threads on embedder shutdown.
=> Test that the embedder can be launched and shut down correctly.

lib/ui/text.dart, lib/ui/text/paragraph_builder.cc, lib/ui/text/paragraph_builder.h
Fixes https://github.com/flutter/flutter/issues/12772
=> Validate UTF-16 input in ParagraphBuilder::addText

sky/engine/platform/fonts/linux/FontPlatformDataLinux.cpp, third_party/txt/src/txt/paragraph.cc
Fixes https://github.com/flutter/flutter/issues/12820
=> Request slight hinting when rendering glyphs with Skia

shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm
https://github.com/flutter/flutter/issues/12781
Make sure at no moment is the selected text range incompatible with the current text
=> Make the text selection code more defensive

lib/ui/BUILD.gn, lib/ui/dart_ui.cc, lib/ui/painting.dart, lib/ui/painting/codec.cc, lib/ui/painting/codec.h, lib/ui/painting/frame_info.cc, lib/ui/painting/frame_info.h, testing/dart/codec_test.dart, travis/licenses_golden/licenses_flutter
https://github.com/flutter/flutter/issues/204
=> Decode animation frames and pass FrameInfos to dart

lib/ui/painting/codec.cc, lib/ui/painting/codec.h, testing/dart/codec_test.dart
https://github.com/flutter/flutter/issues/204
=> Implement a SingleFrameCodec and return it for non animated images

DEPS, tools/licenses/lib/main.dart, travis/licenses_golden/licenses_flutter, travis/licenses_golden/licenses_topaz
Update to moved repository.
Issue https://github.com/flutter/flutter/issues/9998
=> Roll tonic to da66b94839f788a0bffc34fd9bdfef3360af8c18.

content_handler/session_connection.h, content_handler/vulkan_rasterizer.cc, flow/debug_print.cc, flow/layers/layer.h, flow/layers/layer_tree.cc, flow/layers/layer_tree.h, flow/layers/picture_layer.cc, flow/raster_cache.cc, flow/raster_cache.h, flow/raster_cache_key.h, flow/scene_update_context.h
Plumb through Scenic display metrics to use during
Preroll.
=> Fix low-res rasterized images on Fuchsia.

shell/common/animator.cc, shell/common/animator.h, shell/common/engine.cc
Fixes https://github.com/flutter/flutter/issues/12886
=> Allow rendering of frames in a paused animator during a change to screen dimensions

lib/ui/geometry.dart, testing/dart/rect_test.dart
Adding two functions to make the Rect API more balanced.
Rect.expand will return the bounding box of the union of the current rect and the supplied rect.
Rect.longestSide will return the max of the width and the height.
=> Adding Rect.expand and Rect.longestSide

DEPS, travis/licenses_golden/licenses_third_party
Latest skia includes a bug fix that makes the upcoming color space work simpler.
=> Roll skia to 0658f7

lib/ui/painting/codec.cc
https://github.com/flutter/flutter/issues/204
=> Load animation frames to GPU textures from the IO thread

shell/platform/android/io/flutter/plugin/common/EventChannel.java
Fixes https://github.com/flutter/flutter/issues/12956
=> Make EventChannel survive hot restart

shell/platform/darwin/ios/framework/Headers/FlutterChannels.h, shell/platform/darwin/ios/framework/Source/FlutterChannels.mm
Fixes https://github.com/flutter/flutter/issues/12956
Cf. https://github.com/flutter/engine/pull/4350
=> Align iOS event channel semantics to Android counterpart

shell/platform/android/io/flutter/view/FlutterView.java
Fixes https://github.com/flutter/flutter/issues/12996
=> Delete the native view when destroying the FlutterView

shell/platform/embedder/embedder.cc, shell/platform/embedder/embedder.h, shell/platform/embedder/platform_view_embedder.cc, shell/platform/embedder/platform_view_embedder.h
This updated the native embedder API in a non-ABI breaking way.
=> Allow embedders to respond to platform messages from the Dart application.

tools/licenses/lib/main.dart
Fixes an errrant tab and unnecessary braces.
=> Minor formatting fix in license script

flow/compositor_context.cc, flow/compositor_context.h, shell/common/null_rasterizer.cc, shell/common/null_rasterizer.h, shell/common/platform_view.cc, shell/common/platform_view.h, shell/common/rasterizer.h, shell/gpu/gpu_rasterizer.cc, shell/gpu/gpu_rasterizer.h
Reverts flutter/engine#4348
This broke iOS
=> Revert "Move texture registry ownership to platform view"

lib/ui/painting/codec.cc
fixes https://github.com/flutter/flutter/issues/13147
=> More informative error message for image decoding failure.

shell/common/engine.cc
Fixes https://github.com/flutter/flutter/issues/13183
=> Set a pending dimension change in the animator only if the viewport's physical width/height changed

lib/ui/semantics.dart, shell/platform/android/io/flutter/view/AccessibilityBridge.java, shell/platform/android/io/flutter/view/FlutterView.java
Also contains refactoring of Flags and Actions in Accessibility Bridge as well as fixes to input focus handling, which are required for cursor movement to work.
Still left to do:
* https://github.com/flutter/flutter/issues/13389
* https://github.com/flutter/flutter/issues/13390
* https://github.com/flutter/flutter/issues/13391
Fixes https://github.com/flutter/flutter/issues/12785.
=> A11y cursor movements for text fields on Android

shell/platform/android/io/flutter/plugin/editing/TextInputPlugin.java
Fixes https://github.com/flutter/flutter/issues/13398
=> Do not report a cursor location if there is no active selection

shell/platform/android/io/flutter/view/FlutterView.java
Fixes https://github.com/flutter/flutter/issues/13481
=> Check for a detached FlutterNativeView before sending messages

lib/ui/hooks.dart, lib/ui/window.dart, lib/ui/window/window.cc, lib/ui/window/window.h, runtime/runtime_controller.cc, runtime/runtime_controller.h, shell/common/engine.cc, shell/common/engine.h, shell/common/platform_view.cc, shell/common/platform_view.h, shell/platform/android/io/flutter/view/AccessibilityBridge.java, shell/platform/android/io/flutter/view/FlutterView.java, shell/platform/android/platform_view_android.cc, shell/platform/android/platform_view_android.h, shell/platform/android/platform_view_android_jni.cc
Framework change in https://github.com/flutter/flutter/pull/13490.
Required for https://github.com/flutter/flutter/issues/13391.
=>  Add parameters to SemanticActions; implement extend selection for a11y

lib/ui/hooks.dart, lib/ui/window.dart, lib/ui/window/window.cc, lib/ui/window/window.h, runtime/runtime_controller.cc, runtime/runtime_controller.h, shell/common/engine.cc, shell/common/engine.h, shell/common/platform_view.cc, shell/common/platform_view.h, shell/platform/android/io/flutter/view/AccessibilityBridge.java, shell/platform/android/io/flutter/view/FlutterView.java, shell/platform/android/platform_view_android.cc, shell/platform/android/platform_view_android.h, shell/platform/android/platform_view_android_jni.cc
Reverts flutter/engine#4444
Bots are failing, need to investigate.
TBR @zanderso
=> Revert " Add parameters to SemanticActions; implement extend selection for a11y"

frontend_server/lib/server.dart
It was using `CompilerOptions.onError` which gets `CompilerMessage` and formatting the error with `message.span(message.message)`.
However it turns out that `CompilerMessage.span` is filled incorrectly (and not tested anywhere) so all errors were reported as if they occur on line 1 column XYZ, where XYZ is offset from the start of the file.
This obviously made compiler errors completely unreadable. 
Switch to redirecting Fasta output via `Zone`, because Fasta error reporting is actually tested by golden files and is perfectly readable.
=> Fix frontend_server error reporting.

third_party/txt/src/txt/paragraph.cc, third_party/txt/src/txt/paragraph.h
Also includes some cleanup of the BidiRun struct
=> libtxt: fix the paragraph level text direction passed to the ICU bidi API

shell/common/engine.cc
=> Fix spawnFunction on iOS in debug mode.

runtime/dart_init.cc
=> Fix formatting

content_handler/BUILD.gn, content_handler/runtime_holder.cc, content_handler/runtime_holder.h
This adds a ClipboardPtr to RuntimeHolder that is used to handle
Clipboard.setData and Clipboard.getData.
=> Add clipboard actions to Fuchsia.

lib/ui/semantics.dart, lib/ui/semantics/semantics_node.h, shell/platform/android/io/flutter/view/AccessibilityBridge.java, shell/platform/darwin/ios/framework/Source/accessibility_bridge.mm
First step for https://github.com/flutter/flutter/issues/11993.
=> Add SemanticsFlag.isDisabled

CONTRIBUTING.md
This isn't a step we have our users do, so best that we don't do it either.
=> Remove mention of adb from instructions

shell/platform/android/android_external_texture_gl.cc, shell/platform/android/android_external_texture_gl.h, shell/platform/android/platform_view_android_jni.cc, shell/platform/android/platform_view_android_jni.h
Trying to use scoped ref again!
=> Apply texture transform on Android 

shell/common/shell.cc
This fixes windows build breakage.
=> Fix windows build by using lambda capture workaround

sky/engine/platform/SharedBuffer.cpp
SkTypes.h no longer includes SkMalloc.h
=> Add missing include for sk_malloc_throw

lib/ui/semantics.dart, lib/ui/semantics/semantics_node.h, shell/platform/android/io/flutter/view/AccessibilityBridge.java, shell/platform/darwin/ios/framework/Source/accessibility_bridge.mm
For https://github.com/flutter/flutter/issues/11993.
=> Split SemanticsFlags.isDisabled into two

shell/platform/android/io/flutter/view/AccessibilityBridge.java
Fixes https://github.com/flutter/flutter/issues/13896
=> API version check for AccessibilityNodeInfo.setEditable call

lib/ui/semantics.dart
To align with `SemanticsAction`.
=> Rename SemanticsFlags to SemanticsFlag

lib/ui/geometry.dart, testing/dart/geometry_test.dart
Since we've got a vector class, and it has a getter for the magnitude,
why not also a getter for the angle.
=> Offset.direction

DEPS, travis/licenses_golden/licenses_third_party
Fixes https://github.com/flutter/flutter/issues/13742
=> Roll Skia to 579f094f1259931c30dfd1623e8e22d74b4a7531

assets/directory_asset_bundle.cc, assets/directory_asset_bundle.h, content_handler/application_controller_impl.cc, content_handler/runtime_holder.cc, content_handler/runtime_holder.h
=> Revert "Run Fuchsia apps without flx"

lib/ui/painting/image_filter.cc
Fixes https://github.com/flutter/flutter/issues/13280
=> When blurring, clamp to image's edge pixels, not to black

lib/ui/semantics.dart, shell/platform/android/io/flutter/view/AccessibilityBridge.java
Required for https://github.com/flutter/flutter/issues/14071.
=> Properly identify CheckBox and RadioButton on Android

assets/directory_asset_bundle.cc, assets/directory_asset_bundle.h, content_handler/application_controller_impl.cc, content_handler/runtime_holder.cc, content_handler/runtime_holder.h
New version of #4538 including review comments and fixes for Windows build problem.
=> Run Fuchsia apps without flx

frontend_server/BUILD.gn, frontend_server/lib/server.dart, frontend_server/test/server_test.dart
This reverts commit 86430be68a8294fa6ef3002ee5aba27a50ce3ca6 as it breaks Windows engine buildbot.
@jensjoha , can't add you as a reviewer for some reason. Perhaps you need to be added as a contributor to flutter/engine.
=> Revert "Train frontend_server snapshot (#4512)"

shell/platform/android/io/flutter/view/AccessibilityBridge.java
E.g. when the user changes a CheckBox or a RadioButton from checked to unchecked and vice versa TalkBack now announces the new state.
Fixes https://github.com/flutter/flutter/issues/14092
=> Announce when checked status changes on Android

DEPS, travis/licenses_golden/licenses_third_party
Fixes https://github.com/flutter/flutter/issues/10284
=> Roll Skia to a9c8a05608fe32520a0899016fc28bb1f5ead355

lib/ui/painting.dart, lib/ui/painting/image_filter.cc, lib/ui/painting/image_filter.h
Fixes https://github.com/flutter/flutter/issues/14082
=> Wrapper for matrix image filters

shell/platform/android/io/flutter/view/AccessibilityBridge.java
Also refactors event sending after semantic updates. 
Fixes https://github.com/flutter/flutter/issues/13392.
=> a11y: Echo letters and words typed into TextField back on Android

shell/platform/android/io/flutter/plugin/platform/PlatformPlugin.java
Fixes https://github.com/flutter/flutter/issues/14093
=> Convert other Android clipboard formats into text

flow/paint_utils.cc
Skia is trimming some of these transitive includes
=> Include SkBitmap and SkPaint

lib/ui/semantics.dart, lib/ui/semantics/semantics_node.h, lib/ui/semantics/semantics_update_builder.cc, lib/ui/semantics/semantics_update_builder.h, shell/platform/android/io/flutter/view/AccessibilityBridge.java, shell/platform/android/platform_view_android.cc
Framework-side change will follow shortly.
=> Add a11y support for selected text on Android

shell/platform/darwin/ios/framework/Source/FlutterViewController.mm
Fixes https://github.com/flutter/flutter/issues/13702.
/cc @goderbauer
=> use Human Interface Guidelines for a11y and non-a11y text sizes

lib/ui/semantics.dart, shell/platform/android/io/flutter/view/AccessibilityBridge.java
See https://github.com/flutter/flutter/pull/14275 for framework side change.
Also includes some minor clean-ups for consistency. 
Required for https://github.com/flutter/flutter/issues/13469.
=> Adds a11y action for selecting text (and moving cursor)

lib/ui/semantics.dart, shell/platform/android/io/flutter/view/AccessibilityBridge.java
Required for https://github.com/flutter/flutter/issues/13501.
=> Add semantic actions for copy, cut, and paste

shell/platform/darwin/ios/framework/Source/flutter_main_ios.mm
Follow up to https://github.com/flutter/engine/pull/4532#discussion_r164221448.
=> Lookup FTLAssetsPath when deducing assets path on ios

shell/platform/darwin/ios/framework/Source/FlutterViewController.mm
This reverts commit 89b6d435205d9bcdf8dde965dd1b0432482407c5.
Apparently the clang toolchain is still hitting issues. Will give this
another go after the next clang toolchain update.
=> Revert "Use @available checks for iOS 11 features (#4596)"

DEPS
=> Update buildtools to Fuchsia HEAD

shell/platform/android/io/flutter/view/AccessibilityBridge.java
... which caused trouble for a11y "select all".
=> Remove unnecessary trim

DEPS, travis/licenses_golden/licenses_garnet
This reverts commit 47cae4d8ed5b57c4d6defb794d253e6db5e1b38f.
This reverts commit 9b9de0e559baee3b298bf01b4d3e160a0543b534.
=> Revert "Update //garnet (#4611)"

content_handler/application_controller_impl.cc, content_handler/runtime_holder.cc, content_handler/session_connection.cc, content_handler/vulkan_rasterizer.cc, sky/engine/platform/fonts/fuchsia/FontCacheFuchsia.cpp
This change will make it easier to transition to FIDL2.
=> [fuchsia] Update FIDL1 C++ bindings to match FIDL2 interface

content_handler/vulkan_surface.cc
We need to handle the error case properly.
=> [fuchsia] Fix crash from my recent CL

content_handler/application_controller_impl.cc, content_handler/runtime_holder.cc, content_handler/runtime_holder.h, lib/ui/ui_dart_state.cc, lib/ui/ui_dart_state.h, runtime/runtime_controller.cc, runtime/runtime_controller.h
=> Revert "[fuchsia] Enable running from source packages"

DEPS, content_handler/application_controller_impl.cc, content_handler/runtime_holder.cc, content_handler/runtime_holder.h, lib/ui/ui_dart_state.cc, lib/ui/ui_dart_state.h, runtime/runtime_controller.cc, runtime/runtime_controller.h, travis/licenses_golden/licenses_topaz
This relands https://github.com/flutter/engine/pull/4629 with a
tonic roll to fix the build.
=> Reland: [fuchsia] Enable running from source packages

shell/platform/darwin/desktop/BUILD.gn
This is to unbreak mac engine build
=> Remove xibs

flutter_kernel_transformers/lib/track_widget_constructor_locations.dart, flutter_kernel_transformers/pubspec.yaml, frontend_server/BUILD.gn, frontend_server/lib/server.dart, travis/analyze.sh, travis/licenses_golden/licenses_flutter
Run an optional kernel transform to rewrite all calls to create widgets to track the location the call was made from.
=> Track widget creation locations.

DEPS, lib/ui/text/text_box.cc, lib/ui/text/text_box.h, travis/licenses_golden/licenses_topaz
Fixes https://github.com/flutter/flutter/issues/14555
=> Roll Topaz/Tonic and call Dart_NewListOfType for TextBox lists

content_handler/runtime_holder.cc
Instead of inferring the package name from the app uri, this CL reads the package name out of a config file in the namespace at pkg/data/dart-pkg/contents.
This goes along with:
https://fuchsia-review.googlesource.com/c/build/+/122111
and
https://fuchsia-review.googlesource.com/c/topaz/+/123243
=> [Fuchsia] Reads a config file when running from source

shell/gpu/gpu_surface_gl.cc, shell/gpu/gpu_surface_gl.h, shell/platform/darwin/ios/ios_surface_gl.h, shell/platform/darwin/ios/ios_surface_gl.mm
Fixes https://github.com/flutter/flutter/issues/14565
=> On iOS, render to an offscreen surface to avoid renderbuffer slowdown

DEPS, travis/licenses_golden/licenses_third_party
This picks up fixes in the FE
- [https://github.com/dart-lang/sdk/issues/31984](url) - mixin issue
- [https://github.com/dart-lang/sdk/issues/32068](url) Resolve type arguments of redirecting factories invocations
Additional fixes it picks up
- hot reload fails when instance fields are added with no iniitlaizers
=> Roll Dart to version 0fd6aa87a37023d9691cf50866214c1235dab2d1

shell/platform/android/android_surface_software.cc, shell/platform/android/android_surface_software.h
Fixes https://github.com/flutter/flutter/issues/14709
=> Use an alpha type that matches the color type in Android software rendering

DEPS, tools/gn, travis/licenses_golden/licenses_third_party
Includes fix for the Dart version string.
=> Roll Dart to 0d5cf900b021bf5c9fa593ffa12b15bcd1cc5fe0

content_handler/runtime_holder.cc
Right now can't tell right from left button.
=> Wire pointer buttons for fuchsia

DEPS, travis/licenses_golden/licenses_third_party
https://github.com/flutter/flutter/issues/14751
=> Rev Dart to 0d5cf900b021bf5c9fa593ffa12b15bcd1cc5fe0

shell/common/shell.cc, shell/common/switches.h, shell/platform/android/io/flutter/app/FlutterActivityDelegate.java
https://github.com/flutter/flutter/issues/14519
=> Add flag to skip call to SkGraphics::Init()

shell/common/shell.cc, shell/common/switches.h
https://github.com/flutter/flutter/issues/14519
=> Respect Switch::SkiaDeterministicRendering in all runtime modes

shell/platform/darwin/ios/framework/Source/accessibility_bridge.mm
=> fix naming of static function intToComparisonResult

content_handler/application_controller_impl.cc
=> Remove use of ApplicationLaunchInfo::ServiceProvider from content handler

content_handler/app.cc, content_handler/app.h, content_handler/application_controller_impl.cc, content_handler/application_controller_impl.h, content_handler/rasterizer.h, content_handler/runtime_holder.cc, content_handler/runtime_holder.h, content_handler/session_connection.cc, content_handler/session_connection.h, content_handler/vulkan_rasterizer.cc, content_handler/vulkan_rasterizer.h
This rename is to prepare for the migration to FIDL2.
=> [fuchsia] Rename fidl namespace to f1dl

frontend_server/lib/server.dart
This is needed to fix dependency handling in builds which involve kernel compilation.
=> Add an option '--depfile' to produce ninja-style depfile for the generated kernel.

shell/platform/android/io/flutter/plugin/platform/PlatformPlugin.java, shell/platform/darwin/ios/framework/Source/FlutterPlatformPlugin.mm
https://github.com/flutter/flutter/issues/13710
Primarily drove nomenclature off of iOS APIs since iOS is a bit more opinionated about haptic types. The Android consts are based off of Nexus 5X.
=> Add more haptic feedback varieties

shell/platform/android/io/flutter/view/AccessibilityBridge.java
Fixes https://github.com/flutter/flutter/issues/14987, but why?
=> Fix traversal order for a11y scrolling

tools/licenses/lib/filesystem.dart
.emf-files are binary media files in Microsoft enhanced mediaformat.
=> Skip over .emf-files.

content_handler/vulkan_surface.cc
=> Revert "Update initialization for GrVkAlloc for Skia change"

DEPS, travis/licenses_golden/licenses_third_party
This reverts commit 25b25e5a89a5767e9e004606c574e7a02ecdb528 as it causes https://github.com/dart-lang/sdk/issues/32421
=> Revert "Roll dart to a4c69b772950c65cd73e6a84e550cc9f46083504. (#4744)"

README.md
Keep the tone humble, but it's been two years since the last update, and we've improved vastly in quality, feature-completeness and readiness for real users.
=> Updated status tone to reflect beta availability

lib/ui/semantics.dart, lib/ui/semantics/semantics_node.h, shell/platform/android/io/flutter/view/AccessibilityBridge.java, shell/platform/darwin/ios/framework/Source/accessibility_bridge.mm
Required for https://github.com/flutter/flutter/issues/15178.
=> Add SemanticsFlag for Header

runtime/dart_init.cc
Fixes https://github.com/flutter/flutter/issues/14947
=> Do not free the buffer owned by the kernel_data vector

content_handler/application_controller_impl.cc
=> Rename 'service request' to 'directory request'

shell/common/shell.cc, shell/common/switches.h
This reverts commit 1b7325ca6825a1305d5521a5c0abe6fb32688dea.
=> Revert "Enable libtxt as the default text renderer (#4751)"

flow/export_node.h, fml/message_loop_impl.cc, fml/message_loop_impl.h, lib/ui/painting/resource_context.cc, lib/ui/painting/utils.cc, lib/ui/painting/utils.h, shell/common/shell.cc, shell/common/shell.h, synchronization/pipeline.h
We're going to remove fxl::Mutex soon.
=> Switch from fxl::Mutex to std::mutex

content_handler/app.cc, content_handler/runtime_holder.cc, content_handler/runtime_holder.h
* AssetProvider
* libtxt
@abarth @jason-simmons
=> Updates for Fuchsia roll.

content_handler/vulkan_surface.cc, content_handler/vulkan_surface.h
This updates the content handler for the change in https://fuchsia-review.googlesource.com/c/zircon/+/130312
=> [async] Update includes of async headers to new path

DEPS, sky/packages/sky_engine/LICENSE, travis/licenses_golden/licenses_third_party
This reverts commit 9a9814312b3086884d6bb1a079c5bea0a7c4244f as it causes https://github.com/flutter/flutter/issues/15368.
=> Revert "Roll dart to c080951d45e79cd25df98036c4be835b284a269c. (#4767)"

shell/common/shell.cc, shell/common/switches.h
This reverts commit d9fcdfb676fcec50b0bdf6e57731b511fa922b46.
=> Revert "Enable libtxt as the default text renderer"

DEPS, travis/licenses_golden/licenses_garnet
To pickup this fix: https://fuchsia-review.googlesource.com/c/garnet/+/131115
=> Roll Garnet.

shell/platform/android/io/flutter/view/AccessibilityBridge.java
For Android.
Fixes https://github.com/flutter/flutter/issues/15263.
=> Send TYPE_VIEW_SELECTED event for changes to SemanticsFlag.isSelected

shell/platform/android/io/flutter/plugin/common/StandardMessageCodec.java, shell/platform/android/io/flutter/plugin/common/StandardMethodCodec.java, shell/platform/darwin/ios/framework/Headers/FlutterCodecs.h, shell/platform/darwin/ios/framework/Source/FlutterStandardCodec.mm, shell/platform/darwin/ios/framework/Source/FlutterStandardCodec_Internal.h
Companion flutter/flutter PR: https://github.com/flutter/flutter/pull/15414
=> Make standard codecs extensible

DEPS, travis/licenses_golden/licenses_third_party
=> Roll skia and update licenses

lib/ui/semantics.dart, shell/platform/android/io/flutter/view/AccessibilityBridge.java
Required for https://github.com/flutter/flutter/issues/15274.
=> Support password fields on Android for a11y

lib/ui/window.dart
=> Document Window.defaultRouteName a little better.

DEPS, travis/licenses_golden/licenses_third_party
roll Dart to version 2f68e82526d59b679a522e25db224d8c7e23d280
=> - roll Dart to 2f68e82526d59b679a522e25db224d8c7e23d280

shell/platform/android/io/flutter/plugin/editing/TextInputPlugin.java, shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm
Fixes https://github.com/flutter/flutter/issues/14916.
Requires https://github.com/flutter/flutter/pull/15846.
=> Support for decimal and signed numeric keyboard

DEPS, travis/licenses_golden/licenses_third_party
Should fix: https://github.com/flutter/flutter/issues/15944
=> Rolled Dart SDK to e3051175192c83fafa3636c0f16d804734bb285a

shell/platform/android/io/flutter/app/FlutterApplication.java
This provides improved code inspection, making it easier for developers to figure out what might be going wrong if they override this and don't call super, like I just did. :-)
=> Add @CallSuper annotation to onCreate().

lib/ui/painting.dart, lib/ui/painting/gradient.cc, lib/ui/painting/gradient.h
More details here:
https://github.com/flutter/flutter/issues/16134
=> Allow setting transform on radial gradients.

shell/platform/android/platform_view_android.cc
Fixes https://github.com/flutter/flutter/issues/16143
=> Provide a texture registry to the compositor context used for screenshots

DEPS, travis/licenses_golden/licenses_third_party
=> Revert "Roll dart to 4bcf8ad411bd90da16d44ad399bf350e8423eac9"

DEPS, travis/licenses_golden/licenses_third_party
09e1766e6c [vm] Omnibus memory leaks.
eb3669717c [fasta] Make ConstnessEvaluator evaluate potential constness
e448d18591 Allow empty flutter: sections in pubspec files.
=> Roll Dart to version 09e1766e6caa537e1271fbce04ebcbf8212b6569

sky/tools/create_ios_framework.py
This adds support for --armv7-out-dir and renames --device-out-dir to
--arm64-out-dir for clarity. It preserves --device-out-dir as a fallback
until the bot recipe has been updated to use --arm64-out-dir.
=> Add armv7 support to create_ios_framework script

sky/tools/create_ios_framework.py
This enforces that iOS Flutter.framework builds include arm64, armv7,
and x86_64 (simulator) architectures. This change also eliminates the
previous --device-out-dir option, which has been replaced by
--arm64-out-dir.
=> Require armv7 in create_ios_framework.py

lib/snapshot/fuchsia_compilation_trace.txt, lib/ui/text.dart, lib/ui/text/paragraph_builder.cc, lib/ui/text/paragraph_builder.h, third_party/txt/src/txt/paragraph.cc, third_party/txt/src/txt/paragraph_style.cc, third_party/txt/src/txt/paragraph_style.h, third_party/txt/src/txt/text_style.cc, third_party/txt/src/txt/text_style.h
Fixes https://github.com/flutter/flutter/issues/12630
=> libtxt: support for locale-specific text styles

lib/ui/window.dart, shell/platform/android/io/flutter/app/FlutterActivity.java, shell/platform/android/io/flutter/app/FlutterActivityDelegate.java, shell/platform/android/io/flutter/app/FlutterActivityEvents.java, shell/platform/android/io/flutter/app/FlutterFragmentActivity.java, shell/platform/android/io/flutter/view/FlutterNativeView.java, shell/platform/android/io/flutter/view/FlutterView.java
Reverts flutter/engine#4848 Since this depends on multiple shell CL
=> Revert "Do not pause rendering when android activity loses focus"

content_handler/vulkan_surface_producer.cc
=> [fuchsia] Fix build

third_party/txt/src/txt/asset_data_provider.cc, third_party/txt/src/txt/asset_font_style_set.cc, third_party/txt/src/txt/font_collection.cc
Fixes https://github.com/flutter/flutter/issues/16526
=> libtxt: fix leaks in Skia object reference counting

third_party/txt/src/txt/paragraph_style.cc
This should fix https://github.com/flutter/flutter/issues/16400.
I'd be happy to add tests or try to test it locally but I couldn't find how to run engine tests in the contributing guide (only flutter tests).
=> Promote line height in text style created from paragraph style

shell/common/rasterizer.cc, shell/platform/darwin/ios/framework/Source/FlutterView.mm
Fixes snapshotting of textures uploaded on the IO thread and resident only on the GPU. Does **not** fix snapshotting of scenes with external textures.
Fixes https://github.com/flutter/flutter/issues/16412. The engine refactor removed all the various places the engine used to screenshot layer trees and moved them to a single spot on the rasterizer. This patch fixes that call to handle IO thread uploaded textures.
=> If the rasterizer has a valid surface context, use that to create a snapshotting render target.

DEPS, flutter_kernel_transformers/pubspec.yaml, frontend_server/pubspec.yaml, tools/licenses/pubspec.lock, travis/licenses_golden/licenses_third_party
=> Revert "Roll Dart to fe606f890b0a311da802c78b0af414a3c2087a79"

shell/platform/android/platform_message_response_android.cc
Message responses with null payload should be distinguished from those with empty payload.
The PR introduces a bit of code duplication which I'm not sure how to remove in the most idiomatic way. But it seems to make Flutter's channel_integration_test green on Android.
=> Fix Android platform channels regression

shell/platform/darwin/ios/framework/Source/FlutterViewController.mm
Fixes https://github.com/flutter/flutter/issues/11652.
Required for https://github.com/flutter/flutter/issues/11004.
=> Enable 'Speak Screen' and 'Switch Control' for iOS

CONTRIBUTING.md
giving -C twice silently only builds one directory
=> Correct ninja command instruction

shell/platform/embedder/embedder.cc
"flutter build bundle" in Dart 2 mode now builds an assets directory
containing the application and platform kernels along with the app's other
assets.
With this patch, embedders can run these bundles by setting
FlutterProjectArgs.assets_path to the bundle directory.  In this scenario,
FlutterProjectArgs.main_path and packages_path will be ignored.
=> Configure kernel paths in the embedder if the asset directory contains the kernel assets

shell/platform/android/io/flutter/view/FlutterMain.java
See https://github.com/flutter/flutter/issues/16748
and https://github.com/flutter/flutter/issues/16456
=> Prevent multiple calls to FlutterMain.startInitialization

shell/platform/darwin/ios/framework/Source/accessibility_bridge.mm
Fixes https://github.com/flutter/flutter/issues/14570 (together with https://github.com/flutter/flutter/pull/16253)
/cc @goderbauer
=> ios: remove geometric order; it will be supplied by framework

lib/ui/dart_runtime_hooks.cc, lib/ui/dart_runtime_hooks.h, runtime/dart_isolate.cc, runtime/dart_isolate.h
See https://github.com/flutter/flutter/issues/16846
=> Use the default microtask scheduler on all isolates except the UI isolate

lib/ui/dart_runtime_hooks.cc, lib/ui/natives.dart, runtime/dart_vm_entry_points.txt
Bug: https://github.com/flutter/flutter/issues/17118
=> Define Uri.base as CWD to match the standalone Dart VM.

shell/platform/android/io/flutter/plugin/platform/PlatformPlugin.java, shell/platform/darwin/ios/framework/Source/FlutterPlatformPlugin.mm
=> Revert "Enables system chrome customization on Android O and greater"

shell/common/rasterizer.cc
Fixes https://github.com/flutter/flutter/issues/16412
=> Use the rasterizer's compositor context and texture registry to capture screenshots

DEPS, travis/licenses_golden/licenses_third_party
To try to isolate regressions identified in golden file testing
=> Roll Skia back to d8a189fca3cdfa064de75a280d5af34cc5026bbe

lib/ui/painting/paint.cc, lib/ui/painting/paint.h, lib/ui/text.dart, lib/ui/text/paragraph_builder.cc, lib/ui/text/paragraph_builder.h, third_party/txt/src/txt/paragraph.cc, third_party/txt/src/txt/paragraph.h, third_party/txt/src/txt/text_style.h
Fixes https://github.com/flutter/flutter/issues/11961
=> Provide an SkPaint that describes the background of a text style

DEPS, travis/licenses_golden/licenses_third_party
=> Revert "Roll skia cb8b5d110..e0dc9432d (15 commits)"

shell/common/rasterizer.cc
Fixes https://github.com/flutter/flutter/issues/17448
=> Bypass the raster cache when screenshotting

DEPS, travis/licenses_golden/licenses_third_party
It introduced https://github.com/dart-lang/sdk/issues/33095
=> Revert 37e20af6a324cd4cfa1324b8c644712ef8224359

third_party/txt/src/minikin/LineBreaker.cpp, third_party/txt/src/minikin/LineBreaker.h, third_party/txt/src/txt/paragraph.cc, third_party/txt/src/txt/paragraph.h, third_party/txt/src/txt/paragraph_style.cc, third_party/txt/src/txt/paragraph_style.h
In introduced a regression in text layout: https://github.com/flutter/flutter/issues/17502
=> Revert f6359e4111d37652409e2392fdb3cb72f1119c2a

shell/platform/android/android_shell_holder.cc
The GPU thread calls into Java via JNI in order to update external textures.
Fixes https://github.com/flutter/flutter/issues/17329
=> Detach from JNI before exiting the GPU thread.

lib/ui/painting.dart
Fixes https://github.com/flutter/flutter/issues/17497
=> Allow Canvas.saveLayer without bounds

content_handler/engine.cc
Follows the same pattern followed for termination in response to isolate shutdown.
=> Perform termination in response to session errors on the platform thread.

DEPS, content_handler/BUILD.gn, runtime/dart_isolate.cc, runtime/dart_vm.cc, runtime/dart_vm.h, runtime/dart_vm_unittests.cc, shell/common/BUILD.gn, shell/testing/BUILD.gn, travis/licenses_golden/licenses_third_party, travis/licenses_golden/licenses_topaz
Update engine for removal of Dart_ReadKernelBinary and refactored build targets.
Roll buildroot to 58918cd1f892f8caf7bd50f92a7ef0697ed26464 for updated GN for Windows.
=> Roll Dart to a5c11d7d0329432ca37e35bb249b20f60aa0aa31.

shell/common/shell.cc
iOS does not allow usage of OpenGL ES APIs when the app has been moved to the
background.  With this change, the shell will wait until pending IO thread tasks
complete and the Skia unref queue is drained before proceeding with shutdown.
See https://github.com/flutter/flutter/issues/17511
=> Drain any pending work on the IO thread before shutting down the platform view

lib/ui/painting.dart, lib/ui/painting/gradient.cc, lib/ui/painting/gradient.h
This reverts commit 919e8c211f518f17dbd298d9f8e39091b9e3897f as it breaks flutter gradient_test.
=> Revert "Support for TwoPointConical gradients (#5275)"

flow/layers/picture_layer.cc
https://github.com/flutter/flutter/issues/17448
=> Clear the raster cache result when bypassing raster cache.

lib/ui/painting/vertices.cc
Fixes https://github.com/flutter/flutter/issues/9226
=> Add debug asserts to using SkVertices::Builder

flow/debug_print.cc
Skia toString() is not maintained; the debugger that used it has been replaced. 
Replace usage with equivalent implementation.
=> remove Skia toString() use

runtime/BUILD.gn, shell/platform/android/io/flutter/view/FlutterMain.java, shell/testing/BUILD.gn
This reverts commit e0d4c4641386b8a81c7e9c3bc1a32172d81a785d.
=> Revert "Don't link the core snapshot in the Android engine. (#5348)"

AUTHORS, shell/platform/android/io/flutter/plugin/editing/InputConnectionAdaptor.java, shell/platform/android/io/flutter/view/FlutterView.java
Fixes flutter/flutter#11177
Also fixes flutter/flutter#7943 and fixes flutter/flutter#9347
> @slightfoot **Waits patiently for a merge.**
> I can't wait to be able to type things into TextField from my actual keyboard rather than using the silly on-screen soft keyboard.. such a pain.
=> Fixed support for physical keyboards on Android. flutter/flutter#11177

shell/platform/darwin/ios/framework/Headers/FlutterPlugin.h, shell/platform/darwin/ios/framework/Source/FlutterAppDelegate.mm
This callback is necessary for receiving [Firebase Dynamic Links](https://firebase.google.com/docs/dynamic-links/ios/receive).
=> Added application callback

shell/platform/darwin/ios/framework/Headers/FlutterPlugin.h, shell/platform/darwin/ios/framework/Source/FlutterAppDelegate.mm
=> Revert "Added application callback"

shell/gpu/gpu_surface_gl.cc, shell/platform/embedder/embedder.cc, shell/platform/embedder/tests/embedder_unittests.cc
Contains the compiler specific issues addressed by @ds84182 in https://github.com/flutter/engine/pull/4730.
The GL header issues and linker flags were addressed earlier in the engine and buildroot in separate patches.
=> Fix build issues for the embedder on Windows.

fml/platform/win/file_win.cc
Contains the Windows specific file handling issues addressed by @ds84182 in #4730. Adding a unit test in a subsequent commit.
=> Fix file flags for directories and backslashes in paths on Windows.

AUTHORS
=> Add myself to AUTHORS, as requested

shell/platform/darwin/ios/framework/Headers/FlutterPlugin.h, shell/platform/darwin/ios/framework/Source/FlutterAppDelegate.mm
Needed for receiving dynamic links
=> Correctly added application callback for dynamic links

common/settings.h, runtime/dart_isolate.h, runtime/dart_isolate_unittests.cc, runtime/runtime_controller.cc, runtime/runtime_controller.h, shell/common/engine.cc
The Fuchsia embedder wants to specify the application name in the field for the advisory URI. This allows embedders to specify whatever they want.
=> Allow embedders to specify a custom advisory URI and entrypoint.

DEPS, travis/licenses_golden/licenses_third_party
3b6caa3517b Split UnresolvedNameGenerator
f50873d3451 [fuchsia] Renaming component FIDL to fuchsia.sys.
13987b073d6 Add Forest method to access the name of a variable
declaration
3b86f823d0a [vm/corelib] Remove GrowableArrayMarker hack.
88127f10e4f Clean up num#toStringAsPrecision docs
1eb1885c62d tools/addlatexhash.dart: Remove unused import
03cb46a2290 [vm/perf] Fix JITDUMP integration.
9d9eff44c99 Support sharing function signatures in deferred parts for
fast startup
ae9f5d2a1b1 Add Forest API for logical expressions
66c590d3ad3 Add json/utf8 BOM support in changelog.
d116e62d76d Improve catch parameter recovery
aa8e2ee178d Revert "[vm] Add tests for determinism of script and AppJIT
snapshots."
ec47e524bc9 Switch to non-alpha versions for analyzer/front_end/kernel.
aac0478fada [vm] Add …
=> Dart SDK roll for 2018/05/30

shell/platform/android/io/flutter/app/FlutterActivityDelegate.java
This already works on all other platforms.
=> Parse --verbose-logging flag from intent and pass to the engine as args.

lib/ui/natives.dart
Fixes analyzer issues introduced in #5443 
I unfortunately merged #5395 before noticing that the Linux bot was failing on analysis - this should fix that, and may be quicker than trying to revert both of the other PRs.
=> make analyzer happy

third_party/txt/src/txt/paragraph.cc, third_party/txt/src/txt/paragraph.h
Fixes https://github.com/flutter/flutter/issues/18483
=> libtxt: fix the adjustment of code unit runs for line justification

lib/ui/painting/image_encoding.cc
Fixes https://github.com/flutter/flutter/issues/18323
=> On snapshot, perform a device to host transfer for images resident on the GPU.

vulkan/vulkan_window.cc, vulkan/vulkan_window.h
Skia is moving to make GrVkBackendContext non ref counted and this is the first step towards making the change.
@brianosman @chinmaygarde
=> Nosksp backend context

shell/platform/android/io/flutter/app/FlutterActivityDelegate.java
These are making some of the tests that are sensitive to output flakey.
=> Remove spurious log messages

lib/ui/painting.dart, lib/ui/painting/codec.cc
Fixes https://github.com/flutter/flutter/issues/9184
=> Create images from uncompressed pixel data

shell/platform/android/platform_view_android_jni.cc
This accounts for changes made in https://github.com/flutter/engine/pull/5556
=> Add explicit casts to pointer data members on Android.

shell/gpu/gpu_surface_gl.cc
Part of fixing https://bugs.chromium.org/p/skia/issues/detail?id=7741
=> Get rid of an include of an internal Skia header in GPU Surface GL.

DEPS, shell/platform/android/io/flutter/view/FlutterMain.java
See https://github.com/flutter/flutter/issues/18514
=> Load the ICU data file asset from the "flutter_shared" path

shell/common/engine.h
Required by the Fuchsia embedder
=> Make Engine::GetFontCollection public

runtime/dart_isolate.cc, runtime/dart_isolate.h
Required by https://dart-review.googlesource.com/c/sdk/+/60202
=> No-copy kernel loading.

lib/ui/painting.dart, lib/ui/painting/codec.cc
See https://github.com/flutter/flutter/issues/9184
=> Add a rowBytes parameter to decodeImageFromPixels

shell/common/rasterizer.cc, shell/common/skia_event_tracer_impl.cc
Part of fixing https://bugs.chromium.org/p/skia/issues/detail?id=7741
=> Remove remaining uses of Skia private header includes.

shell/platform/android/io/flutter/view/FlutterView.java
Fixes https://github.com/flutter/flutter/issues/17665
=> Ensure a11y state is communicated back to flutter

flow/export_node.cc, flow/export_node.h, flow/layers/clip_path_layer.cc, flow/layers/clip_rect_layer.cc, flow/layers/clip_rrect_layer.cc, flow/layers/layer.h, flow/layers/layer_tree.cc, flow/layers/layer_tree.h, flow/scene_update_context.cc, flow/scene_update_context.h
TEST=Compiled and ran flutter app on Fuchsia, verified it rendered and responded to input.
=> [fuchsia] Rename scenic_lib => scenic

shell/platform/android/io/flutter/plugin/editing/InputConnectionAdaptor.java, shell/platform/android/io/flutter/plugin/editing/TextInputPlugin.java, shell/platform/darwin/ios/framework/Source/FlutterTextInputDelegate.h, shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm, shell/platform/darwin/ios/framework/Source/FlutterViewController.mm
Support all keyboard actions for iOS and Android. (#11344)
There is a corresponding framework PR:
https://github.com/flutter/flutter/pull/18855
=> Support all keyboard actions. (#11344)

flow/BUILD.gn
The gn label for this target changed.
=> [fuchsia] Update gn label for fuchsia.ui.scenic

shell/platform/darwin/ios/framework/Source/FlutterAppDelegate.mm
Unfortunately this doesn't build on non beta versions of xcode.  But I need a beta version of xcode the build on my test device, not sure what the best solution here is.
=> revert change to app delegate that wont build on earlier Xcode

lib/ui/painting/image_encoding.cc
Fixes https://github.com/flutter/flutter/issues/19214
=> Convert lazy SkImages to raster images when extracting pixel data

lib/ui/semantics.dart
_how embarassing_ :face_with_head_bandage:
=> fix typo in interop code

travis/format.sh
So we'll no longer need https://github.com/flutter/engine/pull/5734 and https://github.com/flutter/engine/pull/5708
=> Add trailing spaces presubmit check

lib/ui/hooks.dart, lib/ui/window.dart, lib/ui/window/window.cc, lib/ui/window/window.h, runtime/runtime_controller.cc, runtime/runtime_controller.h, shell/common/engine.cc, shell/common/engine.h, shell/common/platform_view.cc, shell/common/platform_view.h, shell/common/shell.cc, shell/common/shell.h, shell/platform/android/io/flutter/view/FlutterView.java, shell/platform/android/platform_view_android_jni.cc, shell/platform/darwin/ios/framework/Source/FlutterViewController.mm, shell/platform/darwin/ios/platform_view_ios.h, shell/platform/darwin/ios/platform_view_ios.mm
=> Revert "Add assistiveTechnologyEnabled flag to window"

DEPS, travis/licenses_golden/licenses_third_party
Causes Windows & Mac bot to fail.
=> Revert "Switch to Fuchsia's ICU (#5744)"

shell/common/animator.h, shell/common/platform_view.h, shell/common/vsync_waiter.h, shell/platform/android/vsync_waiter_android.cc, shell/platform/android/vsync_waiter_android.h
Fixes https://github.com/flutter/flutter/issues/19159
=> Handle Android vsync callbacks that occur after the VsyncWaiter has been deleted

DEPS, travis/licenses_golden/licenses_third_party
This reverts commit 1a66f895ba930450a7430acb9538d340d1cbce7f.
=> Revert "Roll Dart to 937ee2e8ca4b76499e24cd463f07bfb736bccd74. (#5745)"

shell/platform/android/io/flutter/plugin/platform/PlatformViewsController.java, shell/platform/android/io/flutter/plugin/platform/SingleViewPresentation.java, shell/platform/android/io/flutter/plugin/platform/VirtualDisplayController.java
https://github.com/flutter/flutter/issues/19030
=> Add touch events to the platform views method channel API.

shell/platform/android/io/flutter/plugin/editing/TextInputPlugin.java, shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm
Fixes https://github.com/flutter/flutter/issues/9363
=> Add text capitalization support to ios and android

travis/format.sh
The new approach follows https://github.com/flutter/flutter/pull/19412 which is suggested by Cirrus in https://github.com/cirruslabs/cirrus-ci-docs/issues/17
=> Make git diff range more robust in format.sh

flow/layers/clip_path_layer.cc, flow/layers/clip_path_layer.h, flow/layers/clip_rect_layer.cc, flow/layers/clip_rect_layer.h, flow/layers/clip_rrect_layer.cc, flow/layers/clip_rrect_layer.h, flow/layers/default_layer_builder.cc, flow/layers/default_layer_builder.h, flow/layers/layer.h, flow/layers/layer_builder.h, flow/layers/physical_shape_layer.cc, flow/layers/physical_shape_layer.h, lib/ui/compositing/scene_builder.cc, lib/ui/compositing/scene_builder.h
So we're consistent across flutter/flutter and flutter/engine
=> Rename clip mode to clip behavior

lib/ui/compositing.dart
The is a follow up of https://github.com/flutter/engine/pull/5853
=> Rename clip to clipBehavior in compositing.dart

tools/licenses/analysis_options.yaml, tools/licenses/lib/filesystem.dart, tools/licenses/lib/licenses.dart, tools/licenses/lib/main.dart, travis/analyze.sh
* remove screaming constants
* fix broken .analysis_options and rename to analysis_options.yaml
* run analyzer on CI for license script
=> Update license script & analyze it on CI

DEPS, sky/packages/sky_engine/LICENSE, tools/licenses/lib/main.dart, travis/licenses_golden/licenses_third_party
This will enable us to switch to the new minimal ICU data configuration in a follow-up PR.
=> Roll ICU to 62.1 and harfbuzz to 1.8.4

shell/platform/android/io/flutter/plugin/platform/VirtualDisplayController.java
In Android O removing the ViewTreeObserver.onDrawListener from the
listener call crashes. Instead we post a runnable to remove it.
=> Delay the removal of the onDrawListener.

third_party/txt/src/txt/paragraph.cc
Fixes https://github.com/flutter/flutter/issues/20824
=> Clear the line baselines when doing each pass of layout

shell/platform/android/io/flutter/plugin/platform/PlatformViewFactory.java, shell/platform/android/io/flutter/plugin/platform/PlatformViewsController.java, shell/platform/android/io/flutter/plugin/platform/SingleViewPresentation.java, shell/platform/android/io/flutter/plugin/platform/VirtualDisplayController.java
This allows plugins to pass extra parameters from the Dart side to the
platform view constructor.
flutter/flutter#19030
=> Allow passing extra creation parameters for embedded Android views.

flow/compositor_context.cc, flow/compositor_context.h, flow/layers/layer.h, flow/layers/layer_tree.cc, flow/layers/picture_layer.cc, flow/raster_cache.cc, flow/raster_cache.h, shell/common/rasterizer.cc, shell/common/surface.h, shell/gpu/gpu_surface_gl.cc, shell/gpu/gpu_surface_gl.h, shell/gpu/gpu_surface_software.cc, shell/gpu/gpu_surface_software.h, shell/gpu/gpu_surface_vulkan.cc, shell/gpu/gpu_surface_vulkan.h, shell/platform/darwin/ios/ios_surface_software.h, shell/platform/embedder/embedder.cc, shell/platform/embedder/embedder.h, shell/platform/embedder/platform_view_embedder.cc, shell/platform/embedder/platform_view_embedder.h
This is an addition to the embedder API. No API/ABI breaking changes.
=> Allow embedders to set the root surface transformation.

DEPS, ci/licenses_golden/licenses_third_party
Fixes https://github.com/flutter/flutter/issues/21003
=> Roll Tonic

shell/platform/android/io/flutter/plugin/editing/InputConnectionAdaptor.java
=> entering a character with a selection deletes the selection

DEPS
=> Roll buildroot to 35959f6255c341eee550884ed69afd6b2891bd53

ci/licenses_golden/licenses_flutter, shell/platform/embedder/BUILD.gn, shell/platform/embedder/embedder.cc, shell/platform/embedder/embedder.h, shell/platform/embedder/embedder_surface.cc, shell/platform/embedder/embedder_surface.h, shell/platform/embedder/embedder_surface_gl.cc, shell/platform/embedder/embedder_surface_gl.h, shell/platform/embedder/embedder_surface_software.cc, shell/platform/embedder/embedder_surface_software.h, shell/platform/embedder/platform_view_embedder.cc, shell/platform/embedder/platform_view_embedder.h
This updates the embedder API but does not make any breaking API/ABI changes.
=> Allow embedders to specify software renderer configs.

shell/platform/android/io/flutter/view/FlutterView.java
Otherwise the callbacks may be called after FlutterNativeView is destroyed and is null.
Also defensively check for whether the texture is already released in the callback because the callback may be called from another thread by a stale reference (see the comment).
This closes https://github.com/flutter/flutter/issues/20951.
=> Unregister onFrameAvailable callbacks when a TextureEntry is released

shell/platform/android/io/flutter/plugin/editing/InputConnectionAdaptor.java
Fixes flutter/flutter#21449
ping @jslavitz
=> Fixes negative end selection offset.

shell/version/BUILD.gn
=> Pull $flutter_root:config into shell/engine/version:version

flow/scene_update_context.cc
=> [fuchsia] Plumb root_surface_transformation in scene_update_context

common/settings.cc, common/settings.h, lib/snapshot/BUILD.gn, runtime/dart_isolate.cc, runtime/dart_isolate.h, runtime/dart_isolate_unittests.cc, runtime/dart_service_isolate.cc, runtime/dart_service_isolate.h, runtime/dart_vm.cc, runtime/dart_vm.h, runtime/dart_vm_unittests.cc, shell/common/engine.cc, shell/common/engine.h, shell/common/isolate_configuration.cc, shell/common/isolate_configuration.h, shell/common/shell.cc, shell/common/switches.cc, shell/common/switches.h, shell/platform/android/flutter_main.cc, shell/platform/android/io/flutter/view/FlutterMain.java, shell/platform/android/platform_view_android_jni.cc, shell/platform/darwin/ios/framework/Source/FlutterDartProject.mm, shell/platform/embedder/embedder.cc, shell/testing/tester_main.cc
This reverts commit 4c2448d1591a5fab033de3885ad34d1fdf5474f1.
=> Revert "Some cleanups enabled by removing support for Dart. (#5621)"

common/settings.cc, common/settings.h, lib/snapshot/BUILD.gn, runtime/dart_isolate.cc, runtime/dart_isolate.h, runtime/dart_isolate_unittests.cc, runtime/dart_service_isolate.cc, runtime/dart_service_isolate.h, runtime/dart_vm.cc, runtime/dart_vm.h, runtime/dart_vm_unittests.cc, shell/common/engine.cc, shell/common/engine.h, shell/common/isolate_configuration.cc, shell/common/isolate_configuration.h, shell/common/shell.cc, shell/common/switches.cc, shell/common/switches.h, shell/platform/android/flutter_main.cc, shell/platform/android/io/flutter/view/FlutterMain.java, shell/platform/android/platform_view_android_jni.cc, shell/platform/darwin/ios/framework/Source/FlutterDartProject.mm, shell/platform/embedder/embedder.cc, shell/testing/observatory/test.dart, shell/testing/tester_main.cc
This reverts commit e3133e0e3f7cbbd57fa930c11f3640561d691eba.
Reverts https://github.com/flutter/engine/pull/6216.
=> Revert "Reapply "Some cleanups enabled by removing support for Dart 1" (#6216)"

lib/ui/text/asset_manager_font_provider.cc, lib/ui/text/font_collection.cc
This function now takes an sk_sp
=> Update to newer Skia font API

DEPS, sky/tools/create_ios_framework.py
Stripping will reduce binary size.
Dsym also required for https://github.com/flutter/flutter/issues/12012.
=> Prepare for stripping and dsyming Flutter.framework

flow/layers/backdrop_filter_layer.cc, flow/layers/color_filter_layer.cc, flow/layers/layer.cc, flow/layers/layer.h, flow/layers/opacity_layer.cc, flow/layers/shader_mask_layer.cc
Fixes https://github.com/flutter/flutter/issues/20859
=> Ensure that Layer::AutoSaveLayer objects are not immediately destructed

DEPS, ci/licenses_golden/licenses_third_party
4eb879133a (HEAD, origin/master, origin/HEAD) Revert "[vm/compiler] Restrict !(x>y) -> (x<=y) to integral x,y"
4611ebaec5 Rename class when the refactoring is invoked on the class name in an instance creation.
71ad670754 Provide quickfixes for imprecise integer literals.
a27bafc306 Check that the concrete member in the class has same type as the super-invoked member in the mixin.
0d71b8aa40 Revert "[vm] Add a timeline stream for recording the zone high watermark."
96a190020e Remove dart2js non-strong platforms
bfeb270b21 [tests] Try dartkb with different vm flags
ba5a4bd8c4 Add periodic output to test.py so test infrastructure doesn't time out.
2cd277a085 Update bazel_worker package to v0.1.14.
7d3ee69e15 Corrects two typoes in the error messages for overrides.
cdb9336fc0 [vm/tfa] Use …
=> Roll Dart to 4eb879133a06c86869dc54cecf904f4b1d46c47b

third_party/txt/src/txt/paragraph.cc
maxIntrinsicWidth represents the width of the paragraph if no word wrap is
applied.  This can be calculated by summing the width of all runs within each
block of text delimited by a hard line break.  maxIntrinsicWidth is the
maximum width among the blocks in the paragraph.
Fixes https://github.com/flutter/flutter/issues/21965
=> Compute maxIntrinsicWidth based on the width of styled runs added to the line breaker

shell/platform/darwin/ios/framework/Source/FlutterViewController.mm
On the iPhone X, raising the keyboard sets a bottom physical inset equal
to the keyboard height, however we previously did not zero out the bottom
physical padding. This was incorrect; when a soft keyboard is present,
it 'consumes' the safe area inset for the home indicator widget,
eliminating the need for the app to handle this at all.
=> Remove bottom safe-area padding when keyboard up

shell/platform/darwin/ios/framework/Source/FlutterViewController.mm
When a XIB is used as a launch screen (UILaunchStoryboardName), now the `splashScreenView` property doesn't crash and returns a properly instantiated view.
=> Add Xib splashscreen support

shell/platform/darwin/ios/framework/Source/FlutterDartProject.mm
To make "Engine run configuration was invalid." failures (e.g.
https://github.com/flutter/flutter/issues/20777) a bit easier to
diagnose, add some more logging to `FlutterDartProject` to verify
that snapshot assets were properly bundled.
=> Add logging if FlutterDartProject fails to load the application kernel snapshot

shell/platform/darwin/ios/framework/Source/FlutterAppDelegate.mm
=> Revert "Fix a compilation problem when using iPhoneOS12.0sdk(Xcode10) && clang version 7.0.0."

shell/platform/android/io/flutter/view/FlutterView.java
Use a screen height ratio to determine if the keyboard is onscreen or not. This is used because Android does not provide a deterministic API to detect this.
We remove the padding when the keyboard is closed and the inset is due to the hidden navigation bar, otherwise, we apply the full keyboard inset.
=> Keyboard inset detection heuristic to distinguish when to include bottom inset.

DEPS
Updated script automates changing of DEPS file in place.
=> [buildroot] Roll buildroot to pick up updated created_updated_flutter_deps.py

shell/platform/darwin/ios/framework/Source/FlutterAppDelegate.mm
This pr should be part of https://github.com/flutter/engine/pull/6279
I add some conditional directives so that it could handle both the new api prototype(ios12) and the old one.
=> V0.8.2 fix compile problem with xcode10

shell/common/persistent_cache.cc
So tool_tests-windows won't fail.
=> Change log level from ERROR to WARNING

lib/ui/compositing.dart, lib/ui/compositing/scene_builder.cc, lib/ui/compositing/scene_builder.h
For https://github.com/flutter/flutter/pull/21619#discussion_r220390088 and https://github.com/flutter/flutter/issues/21756
=> Add pushOffset to SceneBuilder

DEPS
=> Roll buildroot to 96d2493887daabe6877142caa8504a2f964b0e7e

testing/symbols/verify_exported.dart
It is now working properly on the bots.
=> Make verify_exports fail on failures again

lib/ui/dart_ui.cc, lib/ui/dart_ui.h, runtime/dart_isolate.cc
Fixes https://github.com/flutter/flutter/issues/22478
=> Do not register UI-related native functions in secondary isolates

shell/platform/android/io/flutter/view/AccessibilityBridge.java
Basic math escaped me at the time. Manually confirmed to work in flutter_gallery.
=> Correct issues in visible children determination

shell/platform/android/io/flutter/view/AccessibilityBridge.java
Fixes https://github.com/flutter/flutter/issues/22995
=> Add version check for dismissable

third_party/txt/src/minikin/FontCollection.cpp, third_party/txt/src/txt/paragraph.cc
Discovered when building internally
=> Add missing imports for unicode/utf16.h

DEPS, ci/licenses_golden/licenses_third_party
077be25 Support for IsolateMirror.loadUri/kImportTag.
dd971f4 Update file_loader after Dart API updates
=> Roll tonic to 077be256142ede39a271385907faadf4fcc62a4d.

DEPS, shell/platform/embedder/BUILD.gn, tools/gn
Updates buildroot to https://github.com/flutter/buildroot/pull/180.
=> Allow specifying custom toolchains and sysroots for host builds.

shell/common/BUILD.gn, shell/common/shell_unittests.cc, shell/gpu/BUILD.gn, shell/gpu/gpu.gni
Also adds a failing test for https://github.com/flutter/flutter/issues/21398 that will be address in a subsequent patch.
=> Ensure that the platform view is created and destroyed when running the shell unittests.

lib/ui/ui_dart_state.h, lib/ui/window.dart, lib/ui/window/window.cc, lib/ui/window/window.h, runtime/runtime_controller.cc, runtime/runtime_controller.h
An integration test will be added to the framework's repo as a followup.
Addresses flutter/flutter#22009
=> Programmatically set the root isolate's debug name

assets/asset_manager.cc, flow/layers/platform_view_layer.cc, fml/log_level.h, lib/ui/painting/codec.cc, lib/ui/painting/image_encoding.cc, runtime/dart_isolate.cc, runtime/dart_vm.cc, runtime/runtime_controller.cc, shell/common/engine.cc, shell/common/isolate_configuration.cc, shell/common/rasterizer.cc, shell/common/shell.cc, shell/gpu/gpu_surface_gl.cc, shell/platform/embedder/embedder_engine.cc, shell/platform/embedder/embedder_surface_gl.cc, shell/platform/embedder/embedder_surface_software.cc, shell/platform/embedder/platform_view_embedder.cc, shell/testing/tester_main.cc
@jason-simmons came up with this idea :)
=> Handle Windows headers defining ERROR to 0 in log levels.

examples/hello_flutter/lib/main.dart
In comments, replaced `...using using...` with just `...using...`
=> Fixed typo

lib/ui/hooks.dart, lib/ui/pointer.dart, lib/ui/window/pointer_data.cc, lib/ui/window/pointer_data.h, shell/platform/android/io/flutter/view/FlutterView.java
Required by https://github.com/flutter/flutter/pull/23797
=> Propagate positions of secondary pointers in UP events on Android

flow/scene_update_context.cc
This fixes a Fuchsia build breakage cause by #6726 and #6603.
=> Update scene_update_context to match recent PaintContext changes.

DEPS, ci/licenses_golden/licenses_third_party, third_party/txt/src/minikin/Layout.cpp
This will require a 1px golden files update in the framework to roll.
=> Roll update to harfbuzz to 2.1.0

shell/platform/android/io/flutter/view/FlutterView.java
This also removes unused imports and sorts imports correctly
=> Fix String comparison as if Java were Dart.

DEPS, ci/licenses_golden/licenses_skia
This reverts commit e011d544b4e3ff0c2af5babddacdbb1f677f7cca.
=> Revert "Roll src/third_party/skia 06a477c3300d..dd650c40d148 (11 commits) (#6801)"

shell/platform/darwin/ios/framework/Source/FlutterObservatoryPublisher.mm
Fixes https://github.com/flutter/flutter/issues/24194
/cc @devoncarew
=> Fix log on simulator for iOS

lib/ui/window.dart
Add documentation for latest changes to localization.
=> Add docs for not passing empty-strings into Locale

flow/layers/opacity_layer.cc
This fixes https://github.com/flutter/flutter/issues/23890
I'll add unit tests to flutter/flutter shortly.
=> Respect offset in OpacityLayer's paint bounds

fml/thread_local.cc, fml/thread_local.h
Follow-up to https://github.com/flutter/engine/pull/6833.
=> Fix Windows Engine Bot

shell/common/rasterizer.cc
Fixes https://github.com/flutter/flutter/issues/24160
=> Clean up stale cache entries in Skia's GrContext

lib/ui/dart_runtime_hooks.cc, lib/ui/plugins.dart
=> Don't allow for creation of CallbackHandle objects for anonymous closures

ci/licenses_golden/licenses_flutter, shell/platform/darwin/ios/ios_gl_render_target.h, shell/platform/darwin/ios/ios_gl_render_target.mm, sky/packages/sky_engine/LICENSE
These sneaked in between https://github.com/flutter/engine/pull/6757 and https://github.com/flutter/engine/pull/6759.
=> Fix license headers

DEPS, ci/licenses_golden/licenses_third_party, sky/packages/sky_engine/LICENSE, tools/licenses/lib/main.dart
Requires https://github.com/flutter/buildroot/pull/190 to be rolled in.
=> Compile libcxx and libcxxabi for Android

DEPS, ci/licenses_golden/licenses_skia
https://github.com/flutter/flutter/issues/24402
https://github.com/flutter/flutter/issues/24289
https://github.com/flutter/flutter/issues/24391
https://github.com/flutter/flutter/issues/24517
https://github.com/flutter/flutter/issues/23900
=> Roll Skia to 988f54e4689b3d9fb6d5220e02b418f5cfa2b6db

DEPS, ci/licenses_golden/licenses_skia
flutter/flutter#24402
flutter/flutter#24289
flutter/flutter#24517
=> Roll Skia to 57d29eaf2ed7518983d9e91fd5219f4cfc181f88

third_party/txt/benchmarks/paint_record_benchmarks.cc, third_party/txt/benchmarks/paragraph_benchmarks.cc, third_party/txt/src/txt/font_skia.cc
Old unnoticed changes (Paint->Font) for txt_benchmarks and making changes for removed SK_SUPPORT_LEGACY_TEXTENCODINGENUM
=>  SK_SUPPORT_LEGACY_TEXTENCODINGENUM

DEPS, ci/licenses_golden/licenses_third_party, sky/packages/sky_engine/LICENSE, tools/licenses/lib/main.dart
This reverts commit 983d70eb3efc6c4c616f6d7b166451267f581d7c.
This will require https://github.com/flutter/buildroot/pull/193.
=> Reland "Compile libcxx and libcxxabi for Android (#6886)"

DEPS, ci/licenses_golden/licenses_third_party, sky/packages/sky_engine/LICENSE, tools/licenses/lib/main.dart
This reverts commit a8d5582 and rolls buildroot forward to include fix for android_x64.
=>  Reland "Compile libcxx and libcxxabi for Android (#6886)"

shell/platform/darwin/ios/framework/Source/FlutterEngine.mm, shell/platform/darwin/ios/framework/Source/FlutterTextInputDelegate.h, shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm
Adds engine support for iOS force cursor https://github.com/flutter/flutter/issues/17030, (https://github.com/flutter/flutter/issues/20693, https://github.com/flutter/flutter/issues/5445).
=> Adds force cursor support

ci/licenses_golden/licenses_flutter, vulkan/BUILD.gn, vulkan/vulkan_swapchain.h, vulkan/vulkan_swapchain_stub.cc
Stub out VulkanSwapchain.
Test:Fuchsia release *and* debug builds
=> [vulkan] Fix Fuchsia build

shell/platform/darwin/ios/framework/Source/FlutterStandardCodec.mm
Consistently handle Int32/Int64 types on both 32-bit and 64-bit versions
of iOS.  Drop usage of the obsolete hex string encoding for BigInt types.
Fixes https://github.com/flutter/flutter/issues/21313
=> Simplify conversion of numeric types in the message codec on iOS

shell/platform/darwin/ios/framework/Source/accessibility_bridge.mm
Fixes https://github.com/flutter/flutter/issues/22206
=> Fix destruction of the child object list in the iOS accessibility bridge

tools/licenses/lib/main.dart
Extracts _collectLicensesForComponent() from main, which collects the
licenses for the specified component (e.g. flutter, third_party, skia).
This is pre-factoring related to a fix for flutter/flutter#25519.
=> Extract function to collect licenses for component

lib/ui/window.dart
Correct funciton to function in a doc comment.
=> Fix misspelling in doc comments

.cirrus.yml, shell/platform/android/io/flutter/plugin/common/PluginRegistry.java, shell/platform/android/io/flutter/view/FlutterMain.java, tools/gen_javadoc.py
This unbreaks the build.  
I still get a bunch of warnings locally, but I assume if I fix those it will cause more headaches for @matthew-carroll's efforts - I only touched the ones that are now getting registered as errors locally.
=> Fix javadoc for Android-28

shell/common/rasterizer.cc, shell/common/rasterizer.h, shell/common/shell.cc, shell/common/shell.h
See https://github.com/flutter/flutter/issues/25244
=> Add a system message channel for controlling the Skia resource cache size

lib/ui/natives.dart
Fixes https://github.com/flutter/engine/pull/5443#issuecomment-448704175
=> Document native functions for compilation trace

lib/ui/painting.dart, lib/ui/text.dart, lib/ui/text/paragraph_builder.cc, lib/ui/text/paragraph_builder.h, third_party/txt/src/txt/font_collection.cc, third_party/txt/src/txt/font_collection.h, third_party/txt/src/txt/paragraph.cc, third_party/txt/src/txt/paragraph.h, third_party/txt/src/txt/paragraph_style.cc, third_party/txt/src/txt/styled_runs.h, third_party/txt/src/txt/text_style.cc, third_party/txt/src/txt/text_style.h, third_party/txt/tests/paragraph_unittests.cc
This adds the `fontFamilyFallback` field to TextStyle and passes it to minikin.
=> Support user-provided font-fallback.

shell/platform/android/io/flutter/view/FlutterView.java
This adds support for passing ACTION_HOVER_MOVE events to the framework, in preparation for supporting mouse hover events on Android and ChromeOS.
=> Add hover event support to the engine

shell/platform/embedder/assets/EmbedderInfo.plist
Fix: https://github.com/flutter/flutter/issues/26625
See https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/understanding_utis/understand_utis_conc/understand_utis_conc.html#//apple_ref/doc/uid/TP40001319-CH202-CHDHIJDE
=> Edit the bundleid so that it conform to UIT specifications.

third_party/txt/src/txt/paint_record.h, third_party/txt/src/txt/paragraph.h
=> IWYU, esp. since SkFontMetrics.h is leaving SkPaint.h

DEPS, ci/licenses_golden/licenses_third_party, common/settings.h, lib/ui/hooks.dart, lib/ui/ui_dart_state.cc, lib/ui/ui_dart_state.h, lib/ui/window/window.cc, runtime/dart_isolate.cc, runtime/dart_isolate.h
=> Re-land "Wrap the user entrypoint function in a zone with native exception callback. (#7512)"

DEPS
=> Roll buildroot to b4d21cb2a64d63218c8d99533d9c14e99201e8d8

LICENSE, ci/licenses_golden/licenses_flutter
Replaces previous attempt in https://github.com/flutter/engine/pull/7438
This time, followed https://github.com/flutter/engine/blob/master/tools/licenses/README.md
=> Update license to sync with flutter/flutter

DEPS
Fixes https://github.com/flutter/flutter/issues/27144
=> Update buildtools to c9e5400c9e03a0cfb7313d14fde38525399a7715

tools/gen_objcdoc.sh
LUCI doesn't put jazzy on the system path, the way the recipe is set up it puts it in $GEM_HOME.
I could update the recipe, but it seems like it'd be better for us to respect GEM_HOME here.
=> Check in GEM_HOME for jazzy

flow/layers/physical_shape_layer.cc, flow/scene_update_context.cc, flow/scene_update_context.h
For https://github.com/flutter/flutter/issues/23535
When this lands/rolls into Fuchsia, a manual roll with https://fuchsia-review.googlesource.com/c/topaz/+/241557 is needed.
=> Retained rendering in Fuchsia PhysicalShapeLayer

flow/BUILD.gn
This target is now in //sdk/fidl.
=> [fuchsia] Update path to fuchsia.ui.scenic

lib/stub_ui/BUILD.gn, lib/stub_ui/window.dart
Also ensure we copy the correct libraries.json into flutter_patched_sdk
=> Add onPlatformBrightnessChanged/platformBrightness to stub ui window.

flow/raster_cache.cc, flow/raster_cache.h
This decreases worst_frame_rasterizer_time_millis from 30ms to 10ms when
we enabled picture raster cache in tiles_scroll (i.e., lower the
threshold from 10 to 5).
Once this gets merged, we can reland https://github.com/flutter/engine/pull/7687
=> Throttle picture raster cache

third_party/txt/src/txt/paragraph.cc, third_party/txt/src/txt/paragraph.h, third_party/txt/tests/paragraph_unittests.cc
Fixes https://github.com/flutter/flutter/issues/25567
=> libtxt: support justification of RTL text

tools/gn
This code path isn't stable yet.
Fixes flutter/flutter#27718
Reopens flutter/flutter#23838
=> Don't use WUFFs

ci/licenses.sh, ci/licenses_golden/licenses_flutter, shell/platform/android/BUILD.gn, shell/platform/android/io/flutter/util/BSDiff.java, shell/platform/android/io/flutter/view/ResourceExtractor.java
Also see https://github.com/flutter/flutter/pull/27754 for compression support in the flutter tool.
=> Support for binary decompression of dynamic patches.

third_party/txt/tests/paragraph_unittests.cc
New tests were added after cirrus ran, so this fixes those.
=> Fix tests that were committed after cirrus ran

DEPS, shell/platform/embedder/BUILD.gn, shell/platform/embedder/tests/embedder_unittests.cc, testing/testing.gni
Also extend the embedder unit tests to cover AOT execution
=> Remove the Dart JIT snapshot data from AOT builds of the embedder library

lib/stub_ui/natives.dart, lib/ui/hooks.dart, lib/ui/natives.dart
This slightly reduces Flutter Gallery code size after https://dart-review.googlesource.com/c/sdk/+/93225 (-0.04%).
=> Remove unnecessary entry-point closurization.

lib/stub_ui/natives.dart, lib/ui/hooks.dart, lib/ui/natives.dart
Reverts flutter/engine#7876
Relands https://github.com/flutter/engine/pull/7827
Fixes https://github.com/flutter/flutter/issues/28176
/cc @sjindel-google @chinmaygarde
=> Reland "Remove unnecessary entry-point closurization."

shell/common/persistent_cache.cc, shell/common/persistent_cache.h, shell/platform/embedder/embedder.cc, shell/platform/embedder/embedder.h
Fixes https://github.com/flutter/flutter/issues/28278
=> Embedder API for setting the persistent cache path

shell/platform/android/io/flutter/view/ResourceExtractor.java, shell/platform/android/platform_view_android_jni.cc
This will help further changes when we pull other artifacts into the bundle.
=> Make the layout of dynamic patch bundle similar to APK.

shell/platform/android/io/flutter/view/FlutterMain.java, shell/platform/android/io/flutter/view/ResourceExtractor.java
Also see https://github.com/flutter/flutter/pull/28349
=> Dynamic patching support for native code libraries.

shell/platform/embedder/embedder.h
occured -> occurred
preceeded -> preceded
=> Fix two typos in embedder.h

.cirrus.yml, tools/gen_objcdoc.sh
We don't currently test building for ios as part of our presubmits.  We should.
=> Build engine for iOS on presubmit

shell/platform/android/io/flutter/embedding/engine/android/FlutterSurfaceView.java, shell/platform/android/io/flutter/embedding/engine/android/FlutterTextureView.java, shell/platform/android/io/flutter/embedding/engine/android/FlutterView.java, shell/platform/android/io/flutter/embedding/engine/renderer/FlutterRenderer.java
Android Embedding PR15: Add Viewport Metrics to FlutterView
=> Android Embedding PR15: Add Viewport Metrics to FlutterView

shell/platform/darwin/ios/framework/Source/FlutterPlatformViews.mm
Remove an extra statement introduced in https://github.com/flutter/engine/commit/36ca5740c7e39e25d7ac22c755e66525b92fbb56
=> [platform_views]remove an unnecessary extra statement.

BUILD.gn
Remove extra sources and snapshots now that we're on fullsdk
=> remove extra source files

lib/ui/pointer.dart, lib/ui/window/pointer_data.h, shell/platform/android/io/flutter/view/FlutterView.java
Reverts flutter/engine#8065
TBR @stuartmorgan
=> Revert "add signal to pointer kinds"

tools/android_lint/bin/main.dart
The HTML report can still be generated by passing in an `--html` flag
to the tool.
This will make errors easier to debug in CI.
/cc @matthew-carroll
=> Android linter prints to the console by default

flow/raster_cache.cc, flow/raster_cache.h, fml/trace_event.cc, fml/trace_event.h
Reverts flutter/engine#8094. This is [breaking Windows](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8919246351262911008/+/steps/build_host_debug_unopt/0/stdout).
=> Revert "Add support for trace counters with variable arguments and instrument the raster cache."

shell/platform/android/io/flutter/view/FlutterView.java
Bugfix #29203: NPE in getAccessibilityProvider in old FlutterView.
=> Bugfix #29203: NPE in getAccessibilityProvider in old FlutterView.

lib/ui/text.dart
=> Fix indexing error in dart:ui TextStyle.toString

DEPS, ci/licenses_golden/licenses_skia
To fix jagged curves in screenshot tests on roll.
=> [Skia] Rollback Skia to 29d5dec9a0783a033b921dc483fb98d565d684f6

.cirrus.yml
Reverts flutter/engine#8150; Cirrus CI should not be the issue here.
=> Revert "Disable build_ios task due to lack of credits."

flow/raster_cache.cc, flow/raster_cache.h, fml/trace_event.cc, fml/trace_event.h, tools/gn
This reverts commit bc901324faf5a24f9220cc7ecbcf5b97b96ae09f and fixes the issue discovered on Windows builds.
=> Reland "Add support for trace counters with variable arguments and instrument the raster cache."

flow/layers/clip_rect_layer.cc
Otherwise, we'll have issues such as https://github.com/flutter/flutter/issues/29070
=> Clip to clip_rect instead of paint bounds

shell/platform/android/io/flutter/view/AccessibilityBridge.java
Removed `Activity` reference from `AccessibilityBridge` by using a `View` for insets instead of the `Activity` (#18115)
Based on manual testing, this appears to return the same results that the `Activity` `decorView` approach was originally returning.
Playing with a device, I was able to once get the insets to be null.  It is possible that the same thing could happen with the existing implementation.  I think if rotate the device at just the right time then we can catch this logic when the view isn't attached to anything.  So I added a null check.  I think the best we can do is fizzle if it's null, but we would catch a new set of insets on the next rotation, so it shouldn't be a serious issue.
CC @amirh because you're working in `AccessibilityBridge` right now.
=> Removed Activity reference from AccessibilityBridge by using a View for insets instead of the Activity

shell/platform/android/platform_view_android.cc
Fixes https://github.com/flutter/flutter/issues/29679
=> Use the GPU thread for Android surface on-screen context lifecycle operations

lib/ui/painting.dart, lib/ui/text.dart
This PR adjusts a doc fix that was submitted last week: #8265 
Ref: [#22859](https://github.com/flutter/flutter/issues/22859) in *flutter/flutter*
=> Fixing links between higher and lower classes.

lib/snapshot/BUILD.gn, runtime/BUILD.gn, shell/platform/android/BUILD.gn, shell/platform/darwin/ios/BUILD.gn, shell/platform/embedder/BUILD.gn
=> Move libdart selection into its own target in //flutter/runtime.

shell/platform/android/io/flutter/embedding/android/AndroidTouchProcessor.java
Fixes https://github.com/flutter/flutter/issues/30122
=> Check for hover motion events in AndroidTouchProcessor

shell/platform/android/io/flutter/embedding/engine/systemchannels/TextInputChannel.java
Fixes https://github.com/flutter/flutter/issues/29798
=> Handle null values in TextInputConfiguration.actionLabel JSON

ci/licenses_golden/licenses_flutter, runtime/BUILD.gn, runtime/dart_isolate_unittests.cc, runtime/dart_vm_unittests.cc, runtime/fixtures/simple_main.dart, runtime/runtime_test.cc, runtime/runtime_test.h, testing/thread_test.cc, testing/thread_test.h
Previously, only the most basic tests were run in AOT mode.
=> Allow running runtime_unittests in AOT mode.

tools/gen_javadoc.py
Added new Android embedding packages to javadoc generation.
=> Added new Android embedding packages to javadoc generation.

lib/io/dart_io.cc, lib/ui/dart_runtime_hooks.cc, lib/ui/dart_ui.cc, lib/ui/plugins/callback_cache.cc, lib/ui/window/platform_message_response_dart.cc
Bug: https://github.com/flutter/flutter/issues/30407
=> Remove use of DART_CHECK_VALID.

ci/docker/windows_build/prepare_windows_server_2016_core.ps1
To make it clearer what the next step is after the script run.
=> More detailed comments for engine build windows VM

shell/platform/android/io/flutter/embedding/android/FlutterActivity.java, shell/platform/android/io/flutter/embedding/android/FlutterFragment.java, shell/platform/android/io/flutter/embedding/android/FlutterSurfaceView.java
Android Embedding PR24: Allow FlutterActivity to provide an engine, also adjust FlutterFragment timing to avoid Activity launch lag.
=> Android Embedding PR24: Allow FlutterActivity to provide an engine, also adjust FlutterFragment timing to avoid Activity launch lag.

ci/licenses_golden/licenses_flutter, common/settings.h, runtime/BUILD.gn, runtime/dart_isolate.cc, runtime/dart_isolate.h, runtime/dart_lifecycle_unittests.cc, runtime/dart_vm.cc, runtime/dart_vm.h, runtime/dart_vm_lifecycle.cc, runtime/dart_vm_lifecycle.h, runtime/fixtures/simple_main.dart, runtime/runtime_test.cc, shell/common/isolate_configuration.cc, shell/common/isolate_configuration.h, shell/platform/android/platform_view_android_jni.cc
This reverts commit 800ea0a40397d53311715e0de94f0340195bfcea.
=> Enable shutting down all root isolates in a VM.

ci/licenses_golden/licenses_flutter, flow/BUILD.gn, flow/export_node.cc, flow/export_node.h, flow/layers/child_scene_layer.cc, flow/layers/child_scene_layer.h, flow/scene_update_context.cc, flow/scene_update_context.h, flow/view_holder.cc, flow/view_holder.h, fml/command_line.h, lib/stub_ui/lib/compositing.dart, lib/ui/BUILD.gn, lib/ui/compositing.dart, lib/ui/compositing/scene_builder.cc, lib/ui/compositing/scene_builder.h, lib/ui/compositing/scene_host.cc, lib/ui/compositing/scene_host.h, lib/ui/dart_ui.cc
This allows using the new Views API from Flutter programs on Fuchsia.
=> [scene_host] Add Views V2 support

shell/platform/android/io/flutter/view/FlutterView.java
This can occur when the FlutterView is instantiated inside a Fragment.
=> Support ContextWrapper when instantiating a FlutterView.

shell/platform/android/io/flutter/view/FlutterMain.java
Android Embedding PR26: Offer an async version of FlutterMain's ensure initialization complete.
This PR addresses a request from @mjohnsullivan that we be able to run `FlutterMain.ensureInitializationComplete()` in an async manner with a callback.
Achieving this is not 100% possible because the behavior within `FlutterMain.ensureInitializationComplete()` requires that it be run on the Main thread. However, it appears that the waiting call within `ensureInitializationComplete()` does not need to be on the Main thread. Therefore, this PR essentially does the waiting on a background thread and then runs the important part of `ensureInitializationCompleter()` on the Main thread.
=> Android Embedding PR26: Offer an async version of FlutterMain's ensure initialization complete.

lib/snapshot/fuchsia_compilation_trace.txt
=> [scenic] Remove unused mozart.internal

shell/common/skia_event_tracer_impl.cc
When running on Fuchsia, "fml/trace_event.h" sends trace events towards
Fuchsia's tracing system, rather than its own |fml::tracing::*| one.  Do
the same thing for |FlutterEventTracer|, in order to unlock category
"skia" trace events when running on Fuchsia.
The reason this was not working before is because |FlutterEventTracer|
was directly using |fml::tracing::*| functions, rather than the
TRACE_EVENT_* macros.
In the future, we can look into having the skia event tracer enabled by
default on Fuchsia, controlling the presence of Skia events by
enabling/disabling the "skia" category, once we measure the performance
cost of doing so.
=> Route FlutterEventTracer events to Fuchsia tracing for Fuchsia

shell/platform/android/io/flutter/app/FlutterActivityDelegate.java
android.app.UiModeManager is unused in FlutterActivityDelegate.
=> Remove unused import in FlutterActivityDelegate

flow/layers/transform_layer.cc, flow/layers/transform_layer.h
To catch issues like https://github.com/flutter/flutter/issues/30586
We'll also upload a test in the framework that will trigger this DCHECK
if https://github.com/flutter/engine/pull/8467 were reverted.
=> Check that TransformLayer has a finite matrix

BUILD.gn, shell/platform/common/cpp/client_wrapper/BUILD.gn, shell/platform/common/cpp/client_wrapper/encodable_value_unittests.cc, shell/platform/common/cpp/client_wrapper/standard_message_codec_unittests.cc, shell/platform/glfw/client_wrapper/BUILD.gn, testing/run_tests.sh
Builds the unit test on all platforms, and adds them to the aggregate test script.
=> Add desktop shell unittests to test script

ci/licenses_golden/licenses_flutter, flow/BUILD.gn, flow/layers/container_layer.cc, flow/layers/physical_shape_layer.cc, flow/layers/physical_shape_layer.h, flow/layers/physical_shape_layer_unittests.cc
Reland "Add a unit test for PhysicalShapeLayer (#8616)"
This reverts commit 91b71070f55ffc38c432babc7d9bb68ac2720d8d.
The only change is the namespace.
=> Reland elevation test

ci/licenses_golden/licenses_flutter, fml/mapping.cc, fml/mapping.h, runtime/BUILD.gn, runtime/dart_isolate.cc, runtime/dart_snapshot.cc, runtime/dart_snapshot.h, runtime/dart_snapshot_buffer.cc, runtime/dart_snapshot_buffer.h, runtime/dart_vm.cc
=> Revert "Remove DartSnapshotBuffer and dry up snapshot resolution logic."

lib/stub_ui/lib/geometry.dart, lib/stub_ui/lib/painting.dart, lib/ui/compositing.dart, lib/ui/geometry.dart, lib/ui/painting.dart, testing/dart/rect_test.dart
This broke RRect.contains - needs further refinement.
Will land TBR to unblock the roll.  /cc @cbracken @jason-simmons
=> Revert Rect/RRect 64 bit

flow/layers/clip_path_layer.cc, flow/layers/opacity_layer.h, flow/scene_update_context.cc
We also rename all MZ-* bugs to SCN-*.
SCN-580 #comment
=> [scenic] Purge references to Mozart

flow/layers/transform_layer.cc, lib/ui/compositing.dart, lib/ui/painting.dart, testing/dart/compositing_test.dart
Fixes https://github.com/flutter/flutter/issues/31650
=> Check the matrix in pushTransform

lib/ui/painting/paint.cc
Update call-sites to convert their inputs to match this.
=> colormatrix is now 0...1

shell/platform/android/io/flutter/plugin/platform/PlatformViewsController.java
Address nits in: https://github.com/flutter/engine/pull/8704
=> VirtualDisplay size constraint - add a comment explaining the reason

DEPS
=> Roll buildroot to pull in Fuchsia SDK related updates.

lib/ui/semantics.dart, lib/ui/semantics/semantics_update_builder.cc
These should help with figuring out https://github.com/flutter/engine/pull/8776#discussion_r280658300 and hopefully https://github.com/flutter/flutter/issues/31139
@jonahwilliams - can you think of any other asserts that might belong here, particularly for the screen rotation bug?
=> Add asserts to semantics.dart

lib/ui/semantics.dart
Will land TBR @jonahwilliams @cbracken  to fix the build.
This is crashing a unit test in post submit because this parameter can be null.
=> fix assert

shell/platform/glfw/flutter_glfw.cc
Uses an invisible GLFW window to provide a background resource context
for the Flutter engine to upload textures.
Fixes #31941
=> Provide a resource context in the GLFW shell

lib/stub_ui/lib/src/ui/window.dart
This is required by the web engine implementation
=> Make sure Window.dpr still has a setter

lib/stub_ui/lib/src/ui/canvas.dart, lib/ui/painting.dart
Fixes https://github.com/flutter/flutter/issues/32323
Unfortunately, this API is inconsistent and it seems too late to correct it - unless we really think this is worth a breaking change.
=> Update skew Docs

shell/platform/android/io/flutter/embedding/engine/dart/DartExecutor.java, shell/platform/android/io/flutter/embedding/engine/dart/DartMessenger.java, shell/platform/android/io/flutter/plugin/common/BasicMessageChannel.java, shell/platform/android/io/flutter/plugin/common/BinaryMessenger.java, shell/platform/android/io/flutter/plugin/common/EventChannel.java, shell/platform/android/io/flutter/plugin/common/MethodChannel.java, shell/platform/android/io/flutter/plugin/platform/PlatformViewsController.java, shell/platform/android/io/flutter/view/FlutterNativeView.java, shell/platform/android/io/flutter/view/FlutterView.java
Add @UiThread to MethodChannel and related classes/calls (#32642).
Requested by internal customer due to threading failures in tests.
=> Add @UiThread to MethodChannel and related classes/calls (#32642).

DEPS, fml/BUILD.gn, shell/platform/darwin/BUILD.gn, shell/platform/darwin/common/BUILD.gn, shell/platform/darwin/ios/BUILD.gn, shell/platform/darwin/macos/BUILD.gn, third_party/txt/BUILD.gn
Depends on https://github.com/flutter/buildroot/pull/251 being rolled in.
=> Avoid disabling sources assignment filters are these have been removed.

lib/stub_ui/lib/src/ui/text.dart, lib/ui/text.dart, third_party/txt/src/txt/paragraph.cc, third_party/txt/src/txt/paragraph.h, third_party/txt/tests/paragraph_unittests.cc
See https://github.com/flutter/flutter/issues/32332
=> libtxt: add a BoxHeightStyle option based on the height of the strut

shell/platform/darwin/macos/framework/Headers/FLEViewController.h, shell/platform/darwin/macos/framework/Source/FLEViewController.mm, shell/platform/glfw/flutter_glfw.cc, shell/platform/glfw/public/flutter_glfw.h
Fixes https://github.com/flutter/flutter/issues/32835
=> Enable hover by default for desktop shells

shell/platform/fuchsia/dart/BUILD.gn, shell/platform/fuchsia/flutter/BUILD.gn
four_gate -> flutter_runner
dt_rush -> dart_runner
=> Rename Fuchsia Dart and Flutter runners

shell/platform/android/io/flutter/plugin/platform/PlatformViewFactory.java, shell/platform/android/io/flutter/plugin/platform/PlatformViewsController.java, shell/platform/android/io/flutter/plugin/platform/SingleViewPresentation.java, shell/platform/android/io/flutter/plugin/platform/VirtualDisplayController.java
As we're changing the Android embedding to Google Java style.
=> Remove m prefix from fields in the Android PlatformViews code

lib/ui/compositing.dart
It should return void as SceneBuilder::addRetained is returning void.
Thanks yjbanov@ for finding this typo!
=> Correct the return type of addRetained

ci/licenses_golden/licenses_flutter, lib/stub_ui/lib/src/ui/text.dart, lib/ui/natives.dart, lib/ui/painting.dart, lib/ui/text.dart, lib/ui/text/paragraph_builder.cc, lib/ui/text/paragraph_builder.h, third_party/txt/BUILD.gn, third_party/txt/src/txt/font_features.cc, third_party/txt/src/txt/font_features.h, third_party/txt/src/txt/paragraph.cc, third_party/txt/src/txt/paragraph.h, third_party/txt/src/txt/text_style.h, third_party/txt/tests/paragraph_unittests.cc
Fixes https://github.com/flutter/flutter/issues/31691
=> Add font features (such as tabular numbers) as an option in text styles

shell/platform/android/io/flutter/view/FlutterMain.java
Discovered during most recent roll.
=> Removing unused imports

ci/licenses_golden/licenses_flutter, shell/platform/android/BUILD.gn, shell/platform/android/io/flutter/Log.java, shell/platform/android/io/flutter/embedding/engine/FlutterEnginePluginRegistry.java, shell/platform/android/io/flutter/embedding/engine/FlutterJNI.java
Implemented Log proxy that only logs in BuildConfig.DEBUG (#25391).
I also migrated a couple of classes to demonstrate compilation of source.
=> Implemented Log proxy that only logs in BuildConfig.DEBUG (#25391).

shell/platform/android/io/flutter/view/FlutterMain.java
Completely screwed that one.
cc @jason-simmons
=> Revert change by mistake: extract resources

shell/common/shell_unittests.cc, shell/common/switches.cc, shell/platform/android/io/flutter/app/FlutterActivityDelegate.java
Fixes part of https://github.com/flutter/flutter/issues/32176
=> Allow for whitelisted flags to be passed to the Dart VM

ci/licenses_golden/licenses_flutter, third_party/txt/BUILD.gn, third_party/txt/src/txt/platform_fuchsia.cc
This adds a separate default font for fuchsia
=> Add platform_fuchsia.cc for default font on fuchsia

shell/platform/android/io/flutter/app/FlutterPluginRegistry.java, shell/platform/android/io/flutter/embedding/engine/plugins/shim/ShimPluginRegistry.java, shell/platform/android/io/flutter/plugin/platform/PlatformViewsController.java
Reverts flutter/engine#9193
The android_views integration test seems to be broken by this. The issue may be a test bug. Reverting to unblock engine rolls while this is being investigated.
Error log for the failing test:
```
2019-06-05T19:58:35.230791: stdout: [  +36 ms] E/flutter ( 3001): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(error, Unable to add window -- token null is not for an application, null)
2019-06-05T19:58:35.231018: stdout: [        ] E/flutter ( 3001): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:564:7)
2019-06-05T19:58:35.231307: stdout: [        ] E/flutter ( 3001): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:316:33) …
```
=> Revert "Switch PlatformViewsController from Activity ref to Application ref."

shell/platform/android/io/flutter/view/AccessibilityBridge.java
Was reading through this code and noticed the TODO here - updating these.
=> Document AccessibilityBridge.java

lib/ui/semantics/semantics_node.cc, lib/ui/semantics/semantics_node.h
I want to use this in const contexts.
=> Mark semantics functions const

shell/platform/darwin/ios/framework/Headers/FlutterViewController.h
=> Correct typo

shell/platform/android/io/flutter/plugin/editing/TextInputPlugin.java
Fix TextInputPlugin NPE caused by PlatformViewsController ref in new embedding (#34283).
=> Fix TextInputPlugin NPE caused by PlatformViewsController ref in new embedding (#34283).

shell/platform/android/io/flutter/embedding/android/FlutterFragment.java, shell/platform/android/io/flutter/embedding/android/FlutterView.java, shell/platform/android/io/flutter/plugin/editing/TextInputPlugin.java, shell/platform/android/io/flutter/plugin/platform/PlatformPlugin.java
Fixed memory leaks within FlutterFragment and FlutterView (#34268, #34269, #34270).
=> Fixed memory leaks within FlutterFragment and FlutterView (#34268, #34269, #34270).

flow/skia_gpu_object.cc, fml/concurrent_message_loop.cc, fml/message_loop_impl.cc, fml/message_loop_task_queue.cc, fml/synchronization/atomic_object.h, fml/synchronization/waitable_event.cc, lib/ui/isolate_name_server/isolate_name_server.cc, lib/ui/plugins/callback_cache.cc, runtime/dart_service_isolate.cc, runtime/dart_vm_lifecycle.cc, shell/common/persistent_cache.cc, shell/common/pipeline.h, shell/common/vsync_waiter.cc, shell/platform/embedder/embedder_task_runner.cc, testing/test_dart_native_resolver.cc, third_party/txt/src/minikin/FontCollection.cpp, third_party/txt/src/minikin/FontFamily.cpp, third_party/txt/src/minikin/Layout.cpp, third_party/txt/src/minikin/MinikinFont.cpp, third_party/txt/tests/FontCollectionItemizeTest.cpp, third_party/txt/tests/FontFamilyTest.cpp, third_party/txt/tests/FontLanguageListCacheTest.cpp, third_party/txt/tests/HbFontCacheTest.cpp, third_party/txt/tests/old/perftests/FontCollection.cpp
=> Replace lock_guard with scoped_lock and use class template argument deduction.

shell/common/shell_unittests.cc
Had change locally but forgot to `git commit -a` before `git push`...
=> Fix test name typo

shell/platform/android/io/flutter/embedding/engine/FlutterJNI.java
Android Embedding Refactor PR33: Clean up FlutterJNI.
This PR:
- Removes temporary comments intended to help during the embedding refactor
- Groups `FlutterJNI` methods based on their behavior
- Adds some missing JavaDocs
There should not be any behavioral changes in this PR.
=> Android Embedding Refactor PR33: Clean up FlutterJNI.

shell/platform/android/io/flutter/embedding/android/FlutterView.java
`FlutterView`s can attach to/detach from `FlutterEngine`s to render a Flutter UI. This PR adds support for querying the (possibly) attached `FlutterEngine`, as well as listening for future attachments/detachments.
@adazh combining this PR with Jason's recently merged PR (https://github.com/flutter/engine/pull/9324) should provide support for getting from a `FlutterView` to an isolate ID. You can also hopefully build a custom idler that uses the new listener interface to wait for engine attachment.
=> Add APIs for querying FlutterView for a FlutterEngine and listening for attachment/detachment (#29114).

DEPS, shell/gpu/gpu_surface_metal.mm, tools/gn
Also makes it so that folks don't have to patch the buildroot manually when
building for Metal.
=> Update Metal backend to account for Skia updates.

shell/platform/android/io/flutter/embedding/android/AndroidKeyProcessor.java, shell/platform/android/io/flutter/embedding/android/AndroidTouchProcessor.java, shell/platform/android/io/flutter/embedding/android/FlutterActivity.java, shell/platform/android/io/flutter/embedding/android/FlutterFragment.java, shell/platform/android/io/flutter/embedding/android/FlutterSurfaceView.java, shell/platform/android/io/flutter/embedding/android/FlutterTextureView.java, shell/platform/android/io/flutter/embedding/android/FlutterView.java, shell/platform/android/io/flutter/embedding/engine/FlutterEngine.java, shell/platform/android/io/flutter/embedding/engine/FlutterEngineAndroidLifecycle.java, shell/platform/android/io/flutter/embedding/engine/FlutterEnginePluginRegistry.java, shell/platform/android/io/flutter/embedding/engine/FlutterJNI.java, shell/platform/android/io/flutter/embedding/engine/FlutterShellArgs.java, shell/platform/android/io/flutter/embedding/engine/dart/DartExecutor.java, shell/platform/android/io/flutter/embedding/engine/dart/DartMessenger.java, shell/platform/android/io/flutter/embedding/engine/dart/PlatformMessageHandler.java, shell/platform/android/io/flutter/embedding/engine/plugins/activity/ActivityControlSurface.java, shell/platform/android/io/flutter/embedding/engine/renderer/FlutterRenderer.java, shell/platform/android/io/flutter/embedding/engine/systemchannels/AccessibilityChannel.java, shell/platform/android/io/flutter/embedding/engine/systemchannels/LocalizationChannel.java, shell/platform/android/io/flutter/embedding/engine/systemchannels/NavigationChannel.java, shell/platform/android/io/flutter/embedding/engine/systemchannels/PlatformChannel.java, shell/platform/android/io/flutter/embedding/engine/systemchannels/PlatformViewsChannel.java, shell/platform/android/io/flutter/embedding/engine/systemchannels/SettingsChannel.java, shell/platform/android/io/flutter/embedding/engine/systemchannels/TextInputChannel.java, shell/platform/android/io/flutter/plugin/common/BasicMessageChannel.java, shell/platform/android/io/flutter/plugin/common/BinaryMessenger.java, shell/platform/android/io/flutter/plugin/common/MessageCodec.java, shell/platform/android/io/flutter/plugin/common/MethodChannel.java
Android Embedding Refactor PR34: Fill in missing nullability annotations
=> Android Embedding Refactor PR34: Fill in missing nullability annotations

shell/platform/glfw/platform_handler.cc
Fixes https://github.com/flutter/flutter/issues/30713
=> [glfw] Implement SystemNavigator.pop

flow/scene_update_context.cc
=> Clamp when overflowing z bounds

DEPS, ci/licenses_golden/licenses_third_party
Reverts flutter/engine#9406
Breaks Luci engine builds
=> Revert "Update harfbuzz to 2.5.2"

shell/platform/android/io/flutter/Log.java
Resolves embedding log chattyness by disabling verbose, debug, and info logs by default (#34876).
=> Resolves embedding log chattyness by disabling verbose, debug, and info logs by default (#34876).

DEPS, ci/licenses_golden/licenses_third_party
=> Revert "Reland Update harfbuzz to 2.5.2 (#9406)"

DEPS, ci/licenses_golden/licenses_fuchsia, sky/packages/sky_engine/LICENSE
Reverts flutter/engine#9443
Reason: this PR breaks LUCI bots
TBR: @cbracken
=> Revert "Roll fuchsia/sdk/core/linux-amd64 from udf6w... to jQ8aw..."

testing/ios/IosUnitTests/IosUnitTests.xcodeproj/project.pbxproj
Just makes sure we are parametric about what engine we are using.
=> ios-unit-tests: Forgot a usage of a variable in our script.

DEPS, ci/licenses_golden/licenses_third_party
This version includes the minor upstream patches required for this to build properly.
Previous version: https://github.com/flutter/engine/pull/9406
=> Reland Update harfbuzz to 2.5.2

shell/platform/android/io/flutter/Log.java
Fixed logLevel filter bug so that filter now works as expected.
=> Fixed logLevel filter bug so that filter now works as expected.

shell/platform/android/io/flutter/embedding/android/FlutterFragment.java, shell/platform/android/io/flutter/embedding/android/FlutterView.java
Removed unused imports in new embedding.
=> Removed unused imports in new embedding.

testing/ios/IosUnitTests/IosUnitTests.xcodeproj/project.pbxproj
"cp -R" was only working on the second try for some reason.
=> ios-unit-tests: Started using rsync instead of cp -R to copy frameworks.

ci/licenses_golden/licenses_flutter, flow/BUILD.gn, flow/embedded_views.cc, flow/embedded_views.h, flow/layers/clip_rect_layer.cc, flow/layers/clip_rrect_layer.cc, flow/layers/layer.h, flow/layers/layer_tree.cc, flow/layers/performance_overlay_layer_unittests.cc, flow/layers/platform_view_layer.cc, flow/layers/transform_layer.cc, flow/mutators_stack_unittests.cc, flow/raster_cache.cc, flow/scene_update_context.cc, shell/platform/darwin/ios/framework/Source/FlutterPlatformViews.mm, shell/platform/darwin/ios/framework/Source/FlutterPlatformViews_Internal.h, shell/platform/darwin/ios/framework/Source/FlutterPlatformViews_Internal.mm
Recommitting #9075
Fix for the last PR breaking the host test.
=> Reland "IOS Platform view transform/clipping (#9075)" and fix the breakage.

DEPS, ci/licenses_golden/licenses_skia
For https://github.com/flutter/flutter/issues/35142
=> Revert Skia version to d8f79a27b06b5bce7a27f89ce2d43d39f8c058dc

lib/stub_ui/lib/src/ui/painting.dart, lib/ui/painting.dart, lib/ui/painting/paint.cc
Fixes https://github.com/flutter/flutter/issues/35141
I'm not clear on the best way to test this these days - perhaps a golden test in the framework?
=> Support image filter on paint

shell/platform/darwin/ios/framework/Source/FlutterBinaryMessengerRelay.h
(NDEBUG wasn't working for Luci builds).
=> Switched preprocessor logic for exporting symbols for testing.

flow/mutators_stack_unittests.cc
Also enabled the tests previously disabled due to flakiness caused by these
uninitialized variables.
Fixes https://github.com/flutter/flutter/issues/35338
=> Fix uninitialized variables and put tests in flutter namespace.

shell/platform/android/io/flutter/plugin/platform/SingleViewPresentation.java
This cherry-picks the following commit into the `v1.7.8+hotfix.1` branch:
https://github.com/flutter/engine/pull/9581
=> Cherry-pick fix for flutter/flutter#35291

shell/common/persistent_cache.cc, shell/common/persistent_cache.h
Just minor cleanup as I audited the class for thread safety.
=> Made the persistent cache's directory a const pointer.

lib/ui/painting/codec.cc
Fixes https://github.com/flutter/flutter/issues/36312
=> Handle decompressed images in InstantiateImageCodec

tools/fuchsia/build_fuchsia_artifacts.py, tools/fuchsia/gen_package.py, tools/fuchsia/gen_repo.py
porting from flutter/buildroot
=> Build fuchsia artifacts from the engine

shell/platform/android/io/flutter/plugin/editing/TextInputPlugin.java
Removed PlatformViewsController if-statements from TextInputPlugin (#34286).
=> Removed PlatformViewsController if-statements from TextInputPlugin (#34286).

shell/platform/android/io/flutter/view/FlutterView.java
Added hasRenderedFirstFrame() to old FlutterView for Espresso (#36211).
=> Added hasRenderedFirstFrame() to old FlutterView for Espresso (#36211).

tools/fuchsia/build_fuchsia_artifacts.py, tools/fuchsia/fuchsia.cipd.yaml
Also only upload is os is linux
=> [luci] Reference the right fuchsia CIPD and upload only once

tools/fuchsia/.style.yapf, tools/fuchsia/build_fuchsia_artifacts.py, tools/fuchsia/gather_flutter_runner_artifacts.py, tools/fuchsia/gen_package.py, tools/fuchsia/gen_repo.py, tools/gn
1. We gather the fuchsia artifacts to a temporary directory structure.
2. We then package this directory into a far file using `pm` tool.
=> [fuchsia] Use GatherArtifacts to create the requisite dir structure

shell/platform/fuchsia/BUILD.gn, shell/platform/fuchsia/flutter/BUILD.gn, tools/fuchsia/copy_path.py, tools/fuchsia/package_dir.gni
- Added a package_dir gni that copies the dir structure.
- Doesn't support a lot of the existing functionality.
- Added a script to copy paths.
=> Basic structure for flutter_jit_runner far

shell/platform/fuchsia/flutter/BUILD.gn, tools/fuchsia/gather_flutter_runner_artifacts.py
This also adds icu.dat to the data
=> One more luci fix

shell/platform/fuchsia/flutter/BUILD.gn, tools/fuchsia/gen_package.py, tools/fuchsia/package_dir.gni, tools/fuchsia/parse_manifest.py
=> [fuchsia] Use manifest file to better replicate the existing build

testing/scenario_app/ios/Scenarios/Scenarios.xcodeproj/project.pbxproj
I tried to get this in quick without tests to avoid future
conflicts and wasted time reimplementing the same thing.
=> Started linking the test targets against Flutter.

.cirrus.yml
They're failing on Cirrus at setup - see e.g. https://cirrus-ci.com/task/5072715013160960
@liyuqian @chinmaygarde
=> Disable windows tests

.cirrus.yml
Reverts flutter/engine#10143  These look like they might be working agian.
=> Revert "Disable windows tests"

shell/platform/darwin/ios/framework/Source/FlutterDartProject.mm, testing/scenario_app/ios/Scenarios/Scenarios.xcodeproj/project.pbxproj, testing/scenario_app/ios/Scenarios/Scenarios/AppDelegate.m, testing/scenario_app/ios/Scenarios/ScenariosTests/FlutterViewControllerTest.m
related PR: https://github.com/flutter/engine/pull/9952
=> Added integration test that tests that the first frame callback is called

common/fuchsia_config.gni, shell/platform/fuchsia/BUILD.gn, shell/platform/fuchsia/dart_runner/BUILD.gn, shell/platform/fuchsia/flutter/BUILD.gn, tools/fuchsia/build_fuchsia_artifacts.py, tools/fuchsia/dart.gni, tools/fuchsia/package_dir.gni
We now build dart runner as well
=> [dart_runner] dart jit runner and dart jit product runner

.cirrus.yml, DEPS, tools/fuchsia/build_fuchsia_artifacts.py, tools/gn
Note: We do not currently vend the dart arm64 binaries.
=> [fuchsia] Add arm64 builds for flutter and dart runner

tools/fuchsia/build_fuchsia_artifacts.py
This really fixes a bug in the current gensnapshot bundling
mechanism.
=> [fuchsia] Bundle architecture specific gen_snapshots

tools/fuchsia/build_fuchsia_artifacts.py
This way we can easily tell the engine autoroller to look for this file before rolling.
=> Add fuchsia.stamp for roller

tools/fuchsia/build_fuchsia_artifacts.py
=> Fix red build again

tools/fuchsia/build_fuchsia_artifacts.py
TBR @iskakaushik 
I figured out how to test this offline.
=> Make tree green for real this time, I promise.

lib/ui/painting/single_frame_codec.cc
SingleFrameCodec had been holding a persistent handle to the peer Dart object
while waiting for the decoder callback.  However, Dart code could call
Codec.dispose during that interval, which would cause the Dart peer to drop
its reference to the SingleFrameCodec and potentially delete the
SingleFrameCodec.
Fixes https://github.com/flutter/flutter/issues/36631
=> Ensure that the SingleFrameCodec stays alive until the ImageDecoder invokes its callback

flow/scene_update_context.cc
Previous PR missed one final call to AddPart() in scene_update_context.cc that needed to be removed.
=> Remove one last final call to AddPart()

shell/platform/fuchsia/dart-pkg/zircon/sdk_ext/system.cc, shell/platform/fuchsia/dart-pkg/zircon/sdk_ext/system.h
This is a utils method currently not exposed from fuchsia.
Ported over from [garnet fd.cc](https://fuchsia.googlesource.com/fuchsia/+/master/garnet/public/lib/fsl/io/fd.cc).
=> [fuchsia] CloneChannelFromFD fix for system.cc

shell/common/shell_unittests.cc
The rasterizer may only be accessed safely on the GPU task runner. The test was accessing the same on a non-engine known task runner instead (i.e the tests main task runner).
Crashes previously reproducible on all platforms with the following filters: `--gtest_filter="*ShellTest.SetResourceCacheSize*" --gtest_repeat=-1 --gtest_shuffle --gtest_random_seed=1988` at run ~400.
Fixes https://github.com/flutter/flutter/issues/37629
=> Fix threading and re-enable resource cache shell unit-tests.

tools/gn
=> Don't use DBC for hot-reload on iOS.

testing/run_tests.py
Only test the perf overlay if on Linux.
=> Test perf overlay gold on Linux

.cirrus.yml
This is a subset of https://github.com/flutter/engine/pull/10485.
Hopefully this doesn't significantly reduce our coverage since we
have now limited the fuchsia auto-roller frequency.
=> Remove 3 semi-redundant try-jobs

shell/platform/fuchsia/dart-pkg/zircon/sdk_ext/handle.cc, shell/platform/fuchsia/dart-pkg/zircon/sdk_ext/handle.h, shell/platform/fuchsia/dart-pkg/zircon/sdk_ext/handle_waiter.cc
Original Change-Id: I230601acf5de24765737ad81b595fef2c154134c
=> [dart:zircon] Porting Cache re-usable handle wait objects

ci/licenses_golden/licenses_flutter, web_sdk/BUILD.gn, web_sdk/flutter_kernel_sdk.dart
Reverts flutter/engine#10808 . This is breaking on windows LUCI  TBR @yjbanov
=> Revert "Remove flutter_kernel_sdk dart script"

assets/directory_asset_bundle.cc, fml/file_unittest.cc, fml/mapping.cc, fml/mapping.h, fml/platform/posix/mapping_posix.cc, fml/platform/win/mapping_win.cc
Fixes https://github.com/flutter/flutter/issues/36574
=> Return an empty mapping for an empty file asset

third_party/txt/src/txt/font_collection.cc
Fixes https://github.com/flutter/flutter/issues/38543
=> Remove a tracing macro with a dangling pointer

testing/scenario_app/run_ios_tests.sh
Make it easier to run this for people/CI
This script assumes you've built the engine already.
=> Add script for running ios Tests on simulator

.cirrus.yml
This has landed in LUCI as of https://chromium-review.googlesource.com/c/chromium/tools/build/+/1745539
=> Drop firebase test from Cirrus

flow/raster_cache.cc
Fixes https://github.com/flutter/flutter/issues/37988
=> Trace RasterCacheResult::Draw

testing/scenario_app/run_ios_tests.sh
Just let it default ot latest, so that we don't have to worry about it when we update Xcode
/cc @bkonyi @chinmaygarde @cbracken
=> remove OS version

shell/platform/linux/BUILD.gn, shell/platform/windows/BUILD.gn
Part of restructuring the artifacts to support transitioning away from
GLFW embeddings on desktop.
https://github.com/flutter/flutter/issues/38589
=> Add _glfw versions of the GLFW desktop libraries

shell/platform/android/io/flutter/embedding/android/FlutterActivity.java, shell/platform/android/test/io/flutter/embedding/android/FlutterActivityTest.java
Remove dart entrypoint Intent parameter from FlutterActivity. (#38713)
=> Remove dart entrypoint Intent parameter from FlutterActivity. (#38713)

ci/docker/build/Dockerfile
Add Chrome to Dockerfile so we can run Web tests on Cirrus.
=> Add Chrome to Dockerfile

fml/merged_queues_runner.cc, fml/message_loop_impl.cc, fml/message_loop_task_queues.cc
Potential fix for: https://github.com/flutter/flutter/issues/38778
=> Do not add null task observers

testing/scenario_app/run_ios_tests.sh
I broke this on my last commit - fixing for LUCI
TBR @cbracken @jmagman
=> update sim script

tools/android_support/generate_pom_file.py
=> Remove engine hash from pom filename

shell/platform/embedder/tests/embedder_unittests.cc
No functional change. Just makes testing with fixture images easier. Adding a
whole lot more tests that use this path for the embedder surface rotation
patches. Want to land stuff in smaller chunks.
=> Dry up fixture comparison in embedder unit-tests.

web_sdk/BUILD.gn
This can be used by google3 tooling
=> build legacy web SDK

testing/scenario_app/README.md
=> Update scenarios readme

lib/web_ui/lib/src/engine/pointer_binding.dart
Fixes https://github.com/flutter/flutter/issues/32763
=> preventDefault on touchend to show iOS keyboard

shell/common/pipeline.h
Screenshot attached of the new tracing. You can see the depth counter go from 1 to 2 on the "Pipeline Depth" line of the graph when we fall behind by a frame. The exact value is shown in the sample window at the bottom.
=> Add tracing of the number of frames in flight in the pipeline.

shell/platform/darwin/ios/framework/Source/accessibility_bridge.mm
Last skia roll changed this signature.
=> update method for skia

lib/web_ui/lib/src/engine/text/font_collection.dart
(cl/265763028)
Fixes https://github.com/flutter/flutter/issues/39259
=> Don't crash while loading improperly formatted fonts on Safari

DEPS, ci/licenses_golden/licenses_flutter, shell/platform/fuchsia/flutter/BUILD.gn, shell/platform/fuchsia/flutter/sample_unittests.cc
Also updating googletest dep to match fuchsia HEAD.
Coming up: a component with this executable as app/bin
=> Add a sample unit test target to flutter runner

shell/platform/android/io/flutter/embedding/android/FlutterEngineConfigurator.java, shell/platform/android/io/flutter/embedding/android/FlutterEngineProvider.java
Remove un-needed FragmentActivity import statements to facilitate proguard.
=> Remove un-needed FragmentActivity import statements to facilitate proguard.

shell/platform/fuchsia/flutter/component.cc
port of Change-Id: Ibcd4a110b84805af02a436a2a5bcf2cf3d2029a4
=> [flutter_runner] Plumb Flutter component arguments to the Dart entrypoint

.cirrus.yml, tools/fuchsia/build_fuchsia_artifacts.py
=> Only build the x64 variant of Fuchsia on the try-jobs.

shell/platform/darwin/ios/framework/Source/FlutterOverlayView.h, shell/platform/darwin/ios/framework/Source/FlutterOverlayView.mm, shell/platform/darwin/ios/framework/Source/FlutterPlatformViews.mm, shell/platform/darwin/ios/framework/Source/FlutterPlatformViews_Internal.h, shell/platform/darwin/ios/framework/Source/FlutterView.h, shell/platform/darwin/ios/framework/Source/FlutterView.mm, shell/platform/darwin/ios/ios_gl_context.h, shell/platform/darwin/ios/ios_gl_context.mm, shell/platform/darwin/ios/ios_gl_render_target.h, shell/platform/darwin/ios/ios_gl_render_target.mm, shell/platform/darwin/ios/ios_surface_gl.h, shell/platform/darwin/ios/ios_surface_gl.mm, shell/platform/darwin/ios/ios_surface_software.mm, shell/platform/darwin/ios/platform_view_ios.h, shell/platform/darwin/ios/platform_view_ios.mm
Reverts flutter/engine#12078
Tests are failing in LUCI due to this commit.
=> Revert "Manage iOS contexts separately"

testing/scenario_app/ios/Scenarios/Scenarios.xcodeproj/project.pbxproj, testing/scenario_app/ios/Scenarios/Scenarios.xcodeproj/xcshareddata/xcschemes/Scenarios.xcscheme, testing/scenario_app/ios/Scenarios/Scenarios/AppDelegate.h, testing/scenario_app/ios/Scenarios/Scenarios/AppDelegate.m, testing/scenario_app/ios/Scenarios/Scenarios/FlutterEngine+ScenariosTest.h, testing/scenario_app/ios/Scenarios/Scenarios/FlutterEngine+ScenariosTest.m, testing/scenario_app/ios/Scenarios/Scenarios/ScreenBeforeFlutter.h, testing/scenario_app/ios/Scenarios/Scenarios/ScreenBeforeFlutter.m, testing/scenario_app/ios/Scenarios/ScenariosTests/AppLifecycleTests.m, testing/scenario_app/lib/main.dart, testing/scenario_app/lib/src/platform_echo_mixin.dart, testing/scenario_app/lib/src/poppable_screen.dart, testing/scenario_app/lib/src/scenario.dart
=> Reland add some AppLifecycleTests

shell/platform/darwin/macos/framework/Source/FlutterTextInputPlugin.mm
Keeping track of the input models doesn't actually work since the framework generates a new client ID on each new connection.
Continuation of https://github.com/flutter/engine/pull/12234
Fixes https://github.com/flutter/flutter/issues/30659
=> [macos] Stops keeping track of text input models

tools/fuchsia/build_fuchsia_artifacts.py
Just do packaging if this is set. Will be useful for CI.
=> optionally skip builds

lib/snapshot/BUILD.gn
This is to account for fxb/36483
=> [flutter_runner] Change the path to artifacts

frontend_server/BUILD.gn, frontend_server/lib/server.dart, shell/platform/fuchsia/dart/BUILD.gn
Cf. dart-lang/sdk@74cff6c7df3e8f212c7f41a3a25631e007abc0f7
=> Do not assume Platform.script is a Dart source file during training.

shell/platform/android/io/flutter/embedding/android/FlutterActivity.java, shell/platform/android/io/flutter/embedding/android/FlutterFragmentActivity.java
Added javadoc comments to FlutterActivity and FlutterFragmentActivity.
=> Added javadoc comments to FlutterActivity and FlutterFragmentActivity.

shell/platform/fuchsia/flutter/engine_flutter_runner.gni, shell/platform/fuchsia/flutter/loop.cc
Change-Id: I11ca124878d2652798ed49958c42aa10ae019ef9
=> [flutter_runner][async] Migrate dart/flutter to new async-loop APIs

shell/platform/android/io/flutter/embedding/android/FlutterActivityLaunchConfigs.java, shell/platform/android/io/flutter/plugin/platform/PlatformPlugin.java
Taken from recommendations from the Google roll - unused imports and making a static utility class have a private ctor.
=> java lints

testing/scenario_app/ios/Scenarios/ScenariosTests/AppLifecycleTests.m
See flutter/flutter#40817 for context
=> skip flaky test

shell/platform/android/io/flutter/embedding/android/FlutterView.java
Fixes race condition that was reported internally.
=> Fixes race condition that was reported internally.

shell/platform/fuchsia/dart_runner/BUILD.gn, shell/platform/fuchsia/dart_runner/dart_component_controller.cc, shell/platform/fuchsia/dart_runner/embedder/script_runner_snapshot.dart, shell/platform/fuchsia/dart_runner/integration/main.dart, shell/platform/fuchsia/dart_runner/main.cc, shell/platform/fuchsia/flutter/component.cc, shell/platform/fuchsia/flutter/main.cc, shell/platform/fuchsia/runtime/dart/utils/BUILD.gn, shell/platform/fuchsia/runtime/dart/utils/tempfs.cc, shell/platform/fuchsia/runtime/dart/utils/tempfs.h
Contains content from the following commits:
https://fuchsia-review.googlesource.com/c/topaz/+/284871
https://fuchsia-review.googlesource.com/c/topaz/+/313808
https://fuchsia-review.googlesource.com/c/topaz/+/314610
=> Sync dart_runner

ci/licenses_golden/licenses_flutter, shell/platform/darwin/common/framework/Source/FlutterChannelsTest.m, testing/ios/IosUnitTests/IosUnitTests.xcodeproj/project.pbxproj
Added some unit tests for method channels as I was thinking through possibly refactoring them.
=> Added unit tests for method channels.

lib/web_ui/lib/src/engine/window.dart, lib/web_ui/lib/src/ui/window.dart
Now platformBrightness can change to dark in case is the preferred theme of the user browser
Issue related: [40605](https://github.com/flutter/flutter/issues/40605)
=> [Web] Implement dark mode support for web

shell/platform/android/io/flutter/view/AccessibilityBridge.java
This reverts commit c1773f3c57eb957fbc1702b8353b35648c38e372 because it breaks the Flutter framework build.
=> Revert "Send TYPE_VIEW_FOCUSED for views with input focus. (#12410)"

ci/licenses_golden/tool_signature, tools/licenses/lib/filesystem.dart
Fixes https://bugs.chromium.org/p/skia/issues/detail?id=9467
=> Add .mskp file to binary format

shell/platform/windows/win32_flutter_window.cc, shell/platform/windows/win32_flutter_window.h, shell/platform/windows/win32_window.cc, shell/platform/windows/win32_window.h
Adds support for left, right, middle, back and forward buttons. To support more buttons, we need to use the Raw Input api. Filed https://github.com/flutter/flutter/issues/41323 to track that.
https://github.com/flutter/flutter/issues/38598
=> Adds support for 5 mouse buttons

DEPS
Updating the buildroot to account for the same
=> Update linux toolchain for fuchsia

DEPS
This reverts commit 8d9e4411c08b00ee004e55e6ebc344f86383a46b.
=> Revert "Update linux toolchain for fuchsia"

lib/web_ui/lib/src/engine/semantics/text_field.dart, lib/web_ui/lib/src/engine/text_editing.dart, lib/web_ui/test/text_editing_test.dart
Refactoring text_editing.dart to use EditingState more efficiently and removing unused/unimplemented code.
=> Refactoring text_editing.dart

shell/platform/android/io/flutter/plugin/editing/TextInputPlugin.java, shell/platform/android/test/io/flutter/plugin/editing/TextInputPluginTest.java
Fixes https://github.com/flutter/flutter/issues/41557
=> Check for a null input method subtype

DEPS
This reverts commit ff5ccfe772f0eb4b19d23385d8f442ca9a3756e8.
=> Revert "Revert "Update linux toolchain for fuchsia" (#12578)"

lib/web_ui/lib/src/engine/keyboard.dart, lib/web_ui/test/keyboard_test.dart
This PR contains the engine-side change to complement https://github.com/flutter/flutter/pull/41397 in fixing the issue: https://github.com/flutter/flutter/issues/41396.
=> Support correct keymap for web

shell/platform/darwin/ios/ios_surface_metal.mm
Needs https://github.com/flutter/flutter/issues/41816 from Skia. Will work on CI integration next.
=> Fix Metal builds by accounting for the updated SubmitFrame signature.

DEPS
Roll buildroot to remove unnecessary files for Fuchsia builds
flutter/buildroot#316
=> roll buildroot to 01e923507b28e5d1d3fe7597d2db2b30b0a543e9

frontend_server/BUILD.gn, frontend_server/package_incremental.py
* Fixes frontend_server sources not uploading correctly
* Fixes outputs with incorrect paths
* Stop writing each pubspec multiple times
Adds dev_compiler dep in anticipation of web support in incremental compiler
=> Fix bug in package script and add dev_compiler to list

shell/platform/fuchsia/flutter/meta/flutter_aot_product_runner.cmx, shell/platform/fuchsia/flutter/meta/flutter_aot_runner.cmx, shell/platform/fuchsia/flutter/meta/flutter_jit_product_runner.cmx, shell/platform/fuchsia/flutter/meta/flutter_jit_runner.cmx
This is so we can connect to the timezone service.
=> [flutter_runner] Update the cmx files to include TZ support

shell/platform/fuchsia/dart_runner/dart_component_controller.cc
See https://cirrus-ci.com/task/5367628704514048 and https://github.com/flutter/engine/pull/12822
=> Unblock Fuchsia roll

shell/platform/darwin/ios/framework/Headers/FlutterDartProject.h, shell/platform/darwin/ios/framework/Source/FlutterDartProject.mm, shell/platform/darwin/ios/framework/Source/FlutterDartProject_Internal.h
- Removed unused instance variable
- Explicitly listed nullability
=> Refactor: FlutterDartProject

tools/gn
Fixed by https://skia-review.googlesource.com/c/skia/+/245957
Fixes https://github.com/flutter/flutter/issues/41807
=> Don’t bump iOS deployment target for Metal builds.

third_party/txt/src/skia/paragraph_skia.cc, third_party/txt/src/skia/paragraph_skia.h, third_party/txt/src/txt/run_metrics.h
Based on https://github.com/Rusino/engine/tree/temp
=> Integration with more of Skia's SkShaper/SkParagraph APIs

shell/common/switches.cc
Fixes https://github.com/flutter/flutter/issues/39511
=> Allow embedders to disable causal async stacks in the Dart VM

shell/platform/fuchsia/BUILD.gn, shell/platform/fuchsia/dart_runner/embedder/BUILD.gn
This is part of the effort to port over dart_aot_runner
=> [dart_aot_runner] Add support for generating dart_aot snapshots

shell/platform/fuchsia/BUILD.gn, shell/platform/fuchsia/dart_runner/embedder/BUILD.gn
… snapshots (#13071)" (#13075)"
This reverts commit f20c773c5e05a96974d56f230d9edb447f646b98.
=> Reland dart_aot_runner shims

tools/fuchsia/gen_package.py
TBR @iskakaushik  - the last one had a mistake.
=> Gen package output corrected

shell/common/persistent_cache_unittests.cc
This fixes https://github.com/flutter/flutter/issues/42465
=> Remove persistent cache unittest timeout

.cirrus.yml
This fixes https://github.com/flutter/flutter/issues/38848
=> Analyze framework Dart code in presubmit tests

third_party/txt/src/skia/paragraph_builder_skia.cc
* ParagraphBuilderSkia::AddPlaceholder implementation
* StrutStyle height override
=> Integrate more SkParagraph builder patches

sky/packages/sky_engine/BUILD.gn, sky/packages/sky_engine/lib/_embedder.yaml
- add the dart:__interceptors library to the dart sdk
- follow up to https://dart-review.googlesource.com/c/sdk/+/121462
- fix https://github.com/flutter/flutter/issues/41649
@jonahwilliams @yjbanov
=> add the dart:__interceptors library to the dart sdk

.cirrus.yml
https://github.com/flutter/flutter/issues/42024
=> Enable all engine test on windows

DEPS, ci/licenses_golden/licenses_third_party
This is to account for fxb/38540
Will re-land once the above bug is fixed.
This reverts commit 1e89cb54e885da8b1484f2e8c38dcfac4754eb3f.
=> Revert "Upgrades the ICU version to 64.2 (#13123)"

runtime/dart_isolate.h
Related to https://github.com/flutter/flutter/issues/42778
=> Document //flutter/runtime/dart_isolate.h

shell/platform/android/io/flutter/plugin/editing/InputConnectionAdaptor.java
See https://github.com/flutter/flutter/issues/41005
=> Remove redundant call to updateEditingState in sendKeyEvent

lib/web_ui/dev/README.md, lib/web_ui/dev/common.dart, lib/web_ui/dev/felt
This PR also includes:
* Fix a Chrome installation issue on Mac (after the yaml lock file format has changed).
* Update `README.md` with instructions for doing `felt` tool development.
=> [web] Environment variable to disable felt snapshot

shell/platform/embedder/embedder.cc
Will aid debugging issues like b/142778720
=> Add trace events around custom compositor callbacks.

shell/platform/embedder/embedder.cc
Fixes https://github.com/flutter/flutter/issues/42480
=> Specify a human readable reason for an error from the embedder API.

lib/web_ui/dev/chrome_installer.dart, lib/web_ui/dev/common.dart, lib/web_ui/dev/firefox_installer.dart, lib/web_ui/dev/test_platform.dart
It only downloads firefox right now. I'll add the installation in the next PR.
This PR also adds constants for firefox latest urls (linix, mac).
=> Adding firefox_installer.dart

shell/platform/android/io/flutter/embedding/android/FlutterView.java, shell/platform/android/test/io/flutter/embedding/android/FlutterViewTest.java
Adds Dark Mode support to new Android embedding (this was accidentally missed previously).
=> Adds Dark Mode support to new Android embedding (this was accidentally missed previously).

shell/platform/android/io/flutter/embedding/android/FlutterFragmentActivity.java
Forwards Activity result to FlutterFragment in FlutterFragmentActivity.
=> Forwards Activity result to FlutterFragment in FlutterFragmentActivity.

shell/common/engine.cc, shell/common/engine.h, shell/common/shell.cc, shell/common/shell.h, shell/common/shell_unittests.cc
Related issue: https://github.com/flutter/flutter/issues/33099
=> Made restarting the Engine remember the last entrypoint that was used.

lib/web_ui/lib/src/engine/compositor/canvas.dart, lib/web_ui/lib/src/engine/compositor/layer.dart, lib/web_ui/lib/src/engine/compositor/path.dart, lib/web_ui/lib/src/engine/compositor/recording_canvas.dart, lib/web_ui/lib/src/engine/recording_canvas.dart
- Implement `drawOval` and `addOval`
- Use the Canvas's own `getSaveCount`
- Implement `skew`
- Implement `saveLayerWithoutBounds`
- Document things which we don't plan to implement in the Skia backend
=> Flesh out the CanvasKit backend some more

lib/web_ui/lib/src/ui/painting.dart, lib/web_ui/test/color_test.dart
Fixes https://github.com/flutter/flutter/issues/41257
=> [web] Cupertino dynamic color fix.

shell/platform/darwin/macos/framework/Source/FlutterViewController.mm
https://github.com/flutter/flutter/issues/38076
The framework will receive a keyUp/Down event when Shift, CapsLock, and other modifier keys are pressed.
=> Send flag modified events to the framework

lib/web_ui/lib/src/engine/compositor/path.dart, lib/web_ui/lib/src/engine/compositor/recording_canvas.dart, lib/web_ui/lib/src/engine/compositor/util.dart
- add Path.addArc
- add Path.addPath
- add Path.conicTo
- add Path.transform
- use Skia's computeTonalColors to compute shadow colors
=> Expand on CanvasKit backend more

lib/ui/painting.dart, lib/web_ui/dev/goldens_lock.yaml, lib/web_ui/lib/src/ui/canvas.dart, lib/web_ui/test/golden_tests/engine/path_transform_test.dart, lib/web_ui/test/golden_tests/engine/picture_golden_test.dart
Even though this may not be terribly useful in real apps (at least until we learn to render all text on `BitmapCanvas`) it is useful in some framework unit-tests.
=> Implement basic Picture.toImage via BitmapCanvas

tools/fuchsia/build_fuchsia_artifacts.py, tools/fuchsia/gen_package.py
This reverts commit 8cf47d72888336788b1c482dea01dbde68765bc9.
=> Revert "[flutter_runner] Don't build far files twice (#13397)"

fml/message_loop_task_queues_unittests.cc, testing/run_tests.py
fix test filter
https://github.com/flutter/flutter/issues/42024
=> fix fml_unittes is not run during presubmit

shell/platform/darwin/ios/framework/Source/FlutterEngine.mm
Relevant issue: https://github.com/flutter/flutter/issues/38736
=> Made it so we clean up gl resources when view controllers get deleted.

tools/fuchsia/merge_and_upload_debug_symbols.py
This module is not present on the build nodes
=> Remove usage of yaml module from CIPD script

shell/platform/android/BUILD.gn, shell/platform/android/io/flutter/embedding/engine/FlutterEngine.java, shell/platform/android/test/io/flutter/FlutterTestSuite.java, shell/platform/android/test/io/flutter/embedding/engine/FlutterEngineTest.java
Automatically register plugins in FlutterEngine. (#43855)
Proposal here:
https://docs.google.com/document/d/1xNkBmcdVL1yEXqtZ65KzTwfr5UXDD05VVKYXIXGX7p8/edit?usp=sharing
=> Automatically register plugins in FlutterEngine. (#43855)

tools/fuchsia/common_libs.gni
Fixes: https://github.com/flutter/flutter/issues/43926
=> [fuchsia] Bundle stripped SO files in fars

tools/fuchsia/merge_and_upload_debug_symbols.py
go/flutter-fuchsia-packaging contains more details about the layout
=> [fuchsia] [packaging] Fuchsia tree expects nested bz2 archives

lib/web_ui/lib/src/engine/text_editing/input_type.dart, lib/web_ui/lib/src/engine/text_editing/text_editing.dart, lib/web_ui/test/text_editing_test.dart
Fixes https://github.com/flutter/flutter/issues/43935
=> Fix bug where Enter doesn't add new line in multi-line fields

lib/web_ui/dev/build.dart
This prevents the unnecessary rebuild whenever `felt test` runs (the test command always copies `ahem.ttf` into `lib/assets` which triggers the `lib/` watcher).
=> [web] Ignore changes in *.ttf files in felt build watch mode

shell/platform/darwin/ios/framework/Source/accessibility_bridge.mm
Fixes: https://github.com/flutter/flutter/issues/43883
Still not sure how to test this. For Android we at least have the integration tests. We don't appear to have the equivalent for iOS.
=> Fixed the scroll direction for iOS horizontal accessibility scroll events.

shell/platform/android/io/flutter/embedding/engine/FlutterEngine.java
Fix plugin registrant reflection path. (#44161)
=> Fix plugin registrant reflection path. (#44161)

shell/platform/android/io/flutter/embedding/android/FlutterActivity.java
Fix splash screen lookup. (#44131)
=> Fix splash screen lookup. (#44131)

lib/ui/window.dart
This doc update solves our TODO in https://github.com/flutter/flutter/pull/43676/files#diff-6a35a9a692c9af7473ba1a0a74c979c8R223
=> Prefer SchedulerBinding.addTimingsCallback

shell/platform/android/io/flutter/embedding/engine/FlutterEngine.java, shell/platform/android/io/flutter/embedding/engine/FlutterJNI.java, shell/platform/android/io/flutter/embedding/engine/FlutterShellArgs.java, shell/platform/android/io/flutter/embedding/engine/dart/DartMessenger.java, shell/platform/android/io/flutter/embedding/engine/dart/PlatformMessageHandler.java
Removed scary experimental warnings for new embedding. (#44314)
=> Removed scary experimental warnings for new embedding. (#44314)

shell/platform/fuchsia/dart_runner/integration/meta/dart_aot_runner_test.cmx, shell/platform/fuchsia/dart_runner/integration/meta/dart_jit_runner_test.cmx, shell/platform/fuchsia/dart_runner/vmservice/meta/vmservice.cmx, shell/platform/fuchsia/flutter/BUILD.gn, shell/platform/fuchsia/flutter/engine_flutter_runner.gni, shell/platform/fuchsia/flutter/platform_view.cc, shell/platform/fuchsia/flutter/platform_view.h
It is deprecated and will go away.
=> Remove usage of fuchsia.modular.Clipboard.

shell/common/rasterizer.cc
Fixes https://github.com/flutter/flutter/issues/31355
=> Fix RendererContextSwitch result check in Rasterizer::MakeRasterSnapshot

lib/web_ui/dev/goldens_lock.yaml, lib/web_ui/lib/src/engine/bitmap_canvas.dart, lib/web_ui/test/golden_tests/engine/canvas_blend_golden_test.dart
https://github.com/flutter/goldens/pull/65
=> [web] Fix blendmode for images

tools/fuchsia/build_fuchsia_artifacts.py
https://github.com/flutter/flutter/issues/44841 has more details on this.
=> Disable LTO on Fuchsia

shell/platform/android/BUILD.gn, shell/platform/android/io/flutter/embedding/engine/FlutterShellArgs.java, shell/platform/android/test/io/flutter/FlutterTestSuite.java, shell/platform/android/test/io/flutter/embedding/engine/FlutterShellArgsTest.java
Add support for --dart-flags in FlutterShellArgs. (#44855)
=> Add support for --dart-flags in FlutterShellArgs. (#44855)

lib/web_ui/lib/src/engine/text/paragraph.dart, lib/web_ui/test/golden_tests/engine/scuba.dart, lib/web_ui/test/golden_tests/engine/text_style_golden_test.dart
Fixes https://github.com/flutter/flutter/issues/40663
=> [web] Fix selectable text rendering

lib/web_ui/lib/src/engine/bitmap_canvas.dart, lib/web_ui/lib/src/engine/engine_canvas.dart, lib/web_ui/lib/src/engine/util.dart
Reproducable in pie chart of gallery/rally example.
=> [web] Change canvas sibling transforms to 3d with z=0 to get around canvas rendering bug.

lib/web_ui/lib/src/engine/compositor/path.dart, lib/web_ui/lib/src/ui/path.dart
- the relative path methods
- Path.combine
=> Implement the rest of ui.Path methods for CanvasKit

ci/licenses_golden/licenses_flutter, flow/embedded_views.h, shell/platform/embedder/BUILD.gn, shell/platform/embedder/embedder.h, shell/platform/embedder/embedder_external_view_embedder.cc, shell/platform/embedder/embedder_layers.cc, shell/platform/embedder/embedder_layers.h, shell/platform/embedder/fixtures/main.dart, shell/platform/embedder/tests/embedder_assertions.h, shell/platform/embedder/tests/embedder_unittests.cc
This allows custom compositors to affect scene builder modifications made
to the platform view.
Fixes https://github.com/flutter/flutter/issues/44211
Fixes b/143612326
=> Expose the platform view mutator stack to custom compositors.

lib/web_ui/lib/src/engine/browser_detection.dart, lib/web_ui/lib/src/engine/semantics/text_field.dart
Fixes Edge crash on app startup due -moz-selection insertion in dom_renderer.
Fixes: https://github.com/flutter/flutter/issues/45162
=> [web] Fix Edge detection for correct dom_renderer reset

DEPS
Includes better Vulkan conformance (for which I am going to add support for in
the test harness).
=> Update SwiftShader to 5d1e854.

fml/memory/thread_checker.h
related PR: https://github.com/flutter/engine/pull/13908
=> Made the thread checker print out the thread names on Apple platforms.

DEPS
Build reference: https://ci.chromium.org/p/flutter/builders/prod/Linux%20Fuchsia/1685
=> Updated googletest to fix fuchsia build.

shell/platform/fuchsia/dart_runner/BUILD.gn, shell/platform/fuchsia/flutter/BUILD.gn, tools/fuchsia/fuchsia_archive.gni, tools/fuchsia/fuchsia_libs.gni, tools/gn, vulkan/config.gni, vulkan/vulkan_utilities.cc
Enable vulkan validation for Fuchsia in debug mode as well.
=> [vulkan] Bundle vulkan validation layer so files

shell/platform/darwin/ios/framework/Source/FlutterEngine.mm
Speculatively fixes https://github.com/flutter/flutter/issues/45592
Need to figure out a proper test for this.
/cc @PJLX
=> Avoid retaining self in block

shell/platform/android/io/flutter/plugin/platform/PlatformPlugin.java, shell/platform/darwin/ios/framework/Source/FlutterPlatformPlugin.mm
=> fix try to copy null will cause crash on iOS

lib/web_ui/lib/src/engine/text/measurement.dart, lib/web_ui/lib/src/engine/text/paragraph.dart, lib/web_ui/lib/src/engine/text/ruler.dart, lib/web_ui/lib/src/ui/text.dart, lib/web_ui/test/paragraph_test.dart, lib/web_ui/test/text/measurement_test.dart
Part of https://github.com/flutter/flutter/issues/33523
Fixes https://github.com/flutter/flutter/issues/33613
Fixes https://github.com/flutter/flutter/issues/39537
=> [web] Initial support for LineMetrics

shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm
Reverts flutter/engine#13852
See b/145261659
=> Revert "Do not default to downstream affinity on iOS insertText"

fml/BUILD.gn, runtime/BUILD.gn, shell/platform/fuchsia/dart_runner/BUILD.gn
A recent commit (https://github.com/flutter/engine/commit/ca68af252c850ece1cfae10c1a9fc4fec461215a) caused these to stop compiling.
=> Fix fml_unittests on Fuchsia

ci/licenses_golden/licenses_flutter, ci/licenses_golden/licenses_third_party, lib/web_ui/lib/src/engine.dart, lib/web_ui/lib/src/engine/pointer_binding.dart, lib/web_ui/lib/src/engine/pointer_converter.dart, lib/web_ui/test/engine/pointer_binding_test.dart
* 3e6d6bc add pointer data santizing in flutter web engine
=> Cherry-picks for 1.12.13

lib/web_ui/lib/src/engine/browser_detection.dart
Fixes https://github.com/flutter/flutter/issues/45162
=> Fix firefox detection to fix app startup for other browsers

shell/platform/android/io/flutter/embedding/android/FlutterView.java, shell/platform/android/test/io/flutter/embedding/android/FlutterViewTest.java
* 73da385 Disable a11y on detach (#14142)
=> v1.12.13+hotfix.3 cherry-picks

shell/platform/fuchsia/flutter/component.cc
For async_get_default_dispatcher().
=> [shell][fuchsia] Add lib/async/default.h

README.md
* 57afd86 Remove specificity on Android and iOS
=> v1.12.13+hotfix.5 cherry-picks

flow/skia_gpu_object.cc, flow/skia_gpu_object.h, flow/skia_gpu_object_unittests.cc, shell/common/shell_io_manager.cc
Fixes https://github.com/flutter/flutter/issues/19558
This is tested by the devicelab test fast_scroll_large_images__memory
=> Cleanup the IO thread GrContext

lib/web_ui/test/text/font_collection_test.dart
Resending the PR: https://github.com/flutter/engine/pull/14467
after reviewer suggestion.
=> firefox unit tests to font loading structure change

shell/platform/embedder/fixtures/main.dart, shell/platform/embedder/tests/embedder_assertions.h, shell/platform/embedder/tests/embedder_unittests.cc
Add a test to verify behavior discussed in b/143612326
=> Verify embedders can convert clip rects from mutation stack into surface space.

shell/platform/fuchsia/flutter/platform_view.cc, shell/platform/fuchsia/flutter/platform_view.h
Fixes https://bugs.fuchsia.dev/p/fuchsia/issues/detail?id=35050
and https://github.com/flutter/flutter/issues/38811
=> Apply SmoothPointerDataDispatcher to Fuchsia

lib/web_ui/test/text_editing_test.dart
fix leaking problem in tests for text editing. removing skips for firefox
related to: https://github.com/flutter/flutter/issues/46638
=> [web] fix leaking problem in tests for text editing.

lib/web_ui/lib/src/engine/canvas_pool.dart
Fixes https://github.com/flutter/flutter/issues/48441
Was introduced in canvas_pool refactor.
=> Fix devicepixel ratio reset problem when replaying clip stack

DEPS, ci/licenses_golden/licenses_skia
Reverts flutter/engine#15330
Blocking engine build. Fix is in progress.
=> Revert "Roll src/third_party/skia 04e77813f8f4..92ca3baba6a5 (15 commits)"

shell/platform/darwin/ios/framework/Source/FlutterObservatoryPublisher.mm
https://github.com/flutter/flutter/issues/46750
=> Fixes leak of url in FlutterObservatoryPublisher

lib/web_ui/lib/src/engine/compositor/initialization.dart
Fixes https://github.com/flutter/flutter/issues/47023
=> Upgrade to CanvasKit 0.11

analysis_options.yaml, flutter_frontend_server/lib/server.dart, lib/ui/compositing.dart, lib/ui/geometry.dart, lib/ui/hooks.dart, lib/ui/lerp.dart, lib/ui/natives.dart, lib/ui/painting.dart, lib/ui/plugins.dart, lib/ui/text.dart, lib/ui/window.dart, lib/web_ui/lib/src/ui/canvas.dart, testing/dart/channel_buffers_test.dart, testing/dart/compositing_test.dart, testing/dart/isolate_name_server_test.dart, testing/scenario_app/lib/main.dart, testing/symbols/verify_exported.dart
implicit casts is for NNBD
I also added missing docs to a few places.  I'm skipping the ones on window.dart because I'm going to open a separate PR to make those private.
=> implicit casts and add missing docs

lib/web_ui/lib/src/engine/bitmap_canvas.dart, lib/web_ui/lib/src/engine/canvas_pool.dart, lib/web_ui/lib/src/engine/dom_canvas.dart, lib/web_ui/lib/src/engine/dom_renderer.dart, lib/web_ui/lib/src/engine/shader.dart, lib/web_ui/lib/src/engine/surface/clip.dart, lib/web_ui/lib/src/engine/surface/recording_canvas.dart, lib/web_ui/lib/src/engine/text/paragraph.dart, lib/web_ui/lib/src/engine/util.dart, lib/web_ui/lib/src/ui/painting.dart, lib/web_ui/test/golden_tests/engine/path_to_svg_golden_test.dart
Fixes https://github.com/flutter/flutter/issues/40987
=> Fix Color API, move toCss to helper functions

lib/web_ui/lib/src/engine/surface/painting.dart, lib/web_ui/test/path_test.dart
https://github.com/flutter/flutter/issues/44470
https://github.com/flutter/flutter/issues/49034
=> Fix path.contains failure when devicepixelratio != 1.0

shell/platform/android/io/flutter/embedding/android/FlutterActivity.java, shell/platform/android/io/flutter/embedding/android/FlutterActivityAndFragmentDelegate.java, shell/platform/android/io/flutter/embedding/android/FlutterFragment.java, shell/platform/android/io/flutter/embedding/android/FlutterFragmentActivity.java, shell/platform/android/io/flutter/embedding/android/FlutterView.java, shell/platform/android/io/flutter/embedding/engine/FlutterEngine.java, shell/platform/android/io/flutter/embedding/engine/FlutterEnginePluginRegistry.java
Fixes https://github.com/flutter/flutter/issues/48275
=> Reduce default verbosity of Android embedding

shell/platform/android/io/flutter/embedding/android/FlutterActivity.java
Roll fix for flutter/flutter#46172 into stable
=> Raise API level for reportFullyDrawn (#14146)

shell/platform/darwin/ios/framework/Source/FlutterEngine.mm
https://github.com/flutter/flutter/issues/46750
=> Fixes labelPrefix memory leak in FlutterEngine

runtime/dart_isolate.cc
See https://github.com/flutter/flutter/issues/49358
=> Do not reset the child isolate preparer if the isolate group data already has one

shell/platform/darwin/ios/framework/Source/FlutterCallbackCache.mm
https://github.com/flutter/flutter/issues/46750
=> Fixes FlutterCallbackInfomation leaks

lib/web_ui/lib/src/engine/bitmap_canvas.dart
https://github.com/flutter/flutter/issues/49394
=> [web] Reduce canvas allocation when drawing image.

lib/web_ui/dev/browser_lock.yaml
updating the versions of the browsers for flutter web engine unit tests for chrome and firefox.
=> updating the versions of the browsers for flutter web engine unit tests

shell/platform/embedder/tests/embedder_unittests.cc
This is in the same vein as https://github.com/flutter/engine/pull/16081 but
includes holding the mutex when updating all members in the Captures struct
instead of just when tracking thread IDs.
=> Hold a mutex when updating all CanPostTaskToAllNativeThreads::Captures members.

shell/common/switches.cc
Provided in https://dart-review.googlesource.com/c/sdk/+/133434
Work towards  https://github.com/flutter/flutter/issues/46724
=> Allow --enable-service-port-fallback as a white listed arg

shell/platform/embedder/tests/embedder_unittests.cc
This was never thread-safe to shutdown of the concurrent message loop. There is no saving this test. I tried to do it with mutexes in static variables but was righteously punished. Will setup a harness for testing stuff like this separately.
xref https://github.com/flutter/flutter/issues/49745
=> Remove buggy test to check if tasks can be posted on all native threads recursively from the emebdder.

shell/platform/fuchsia/flutter/accessibility_bridge.cc, shell/platform/fuchsia/flutter/accessibility_bridge.h, shell/platform/fuchsia/flutter/accessibility_bridge_unittest.cc
Reverts flutter/engine#15116
TBR @abrush21
=> Revert "Modifies accessibility bridge to populate new node fields in semantic…"

shell/platform/android/BUILD.gn, shell/platform/android/io/flutter/plugin/platform/PlatformPlugin.java, shell/platform/android/test/io/flutter/FlutterTestSuite.java, shell/platform/android/test/io/flutter/plugin/platform/PlatformPluginTest.java
Added API guards to flags in PlatformPlugin that were introduced after Flutter's min SDK version.
=> Added API guards to flags in PlatformPlugin that were introduced after Flutter's min SDK version.

ci/licenses_golden/licenses_flutter, shell/gpu/BUILD.gn, shell/gpu/gpu_surface_delegate.h, shell/gpu/gpu_surface_gl_delegate.cc, shell/gpu/gpu_surface_gl_delegate.h, shell/gpu/gpu_surface_software_delegate.h, shell/gpu/gpu_surface_vulkan.cc, shell/gpu/gpu_surface_vulkan.h, shell/gpu/gpu_surface_vulkan_delegate.cc, shell/gpu/gpu_surface_vulkan_delegate.h, shell/platform/android/android_surface_vulkan.cc, shell/platform/android/android_surface_vulkan.h, vulkan/vulkan_window.cc, vulkan/vulkan_window.h
I'm extracting the Vulkan refactoring from https://github.com/flutter/engine/pull/15864 and hoping to land it separately. This is basically all David's work with some minor modifications by me.
=> Refactor of Vulkan GPUSurface code

ci/licenses_golden/licenses_flutter, third_party/txt/BUILD.gn, third_party/txt/benchmarks/skparagraph_benchmarks.cc
Imported from @Rusino's branch
=> [SkParagraph] Text layout benchmarks using SkParagraph

shell/platform/android/io/flutter/embedding/android/FlutterActivity.java, shell/platform/android/io/flutter/embedding/android/FlutterFragmentActivity.java
Fix safe area reporting with transparent FlutterActivitys. (#46060)
=> Fix safe area reporting with transparent FlutterActivitys. (#46060)

DEPS, ci/format.sh
Uses google-java-format, a tool that's already in place in
flutter/plugins. This should take care of minor style guide issues and
unresolved imports.
=> Check Java formatting in format.sh

fml/message_loop_task_queues.cc, fml/message_loop_task_queues.h, shell/platform/android/io/flutter/view/AccessibilityViewEmbedder.java
C++: std::move has no effect on const
Java: instanceof is preferred in equals for non-final classes
=> Apply lints from internal roll

lib/web_ui/lib/src/engine/window.dart, lib/web_ui/test/engine/navigation_test.dart
Adds a new route announcement method to prepare for framework side changes
https://github.com/flutter/flutter/issues/50027
=> Adds new route annoucement method.

lib/web_ui/test/engine/semantics/semantics_helper_test.dart, lib/web_ui/test/engine/semantics/semantics_test.dart, lib/web_ui/test/paragraph_test.dart, lib/web_ui/test/text/measurement_test.dart, lib/web_ui/test/text_editing_test.dart, lib/web_ui/test/text_test.dart
These tests are failing right now in Safari. We should make more investigation. I added a new projects just for the skips: https://github.com/flutter/flutter/projects/114
This PR is skipping tests in Safari. LUCI recipe for Mac is ready. this is the on…ly step left for stopping us running unit tests in Safari.
Fixes: https://github.com/flutter/flutter/issues/48824
=> [web] skipping unit tests in Safari

lib/web_ui/test/engine/history_test.dart, lib/web_ui/test/engine/semantics/semantics_test.dart
add comment to skipped safari/macos history_test
=> [web] add comment to skipped safari test
