flutter/engine

shell/platform/darwin/ios/platform_message_handler_ios.h, shell/platform/darwin/ios/platform_message_handler_ios.mm, shell/platform/darwin/ios/platform_message_handler_ios_test.mm, shell/platform/darwin/ios/platform_view_ios.mm
Refactor the `platform_message_handler_ios`:
1. Move @FlutterTaskQueue to header
2. Change the constructor only requires the platform task runner instead of the task_runners. Making this change so that we can use `PlatformMessageHandlerIos` while migrating to the embedder api. The embedder won't have access to the task_runners when using embedder api, but will have access to the platform task runner.
3. Minor: move impelmentation of `DoesHandlePlatformMessageOnPlatformThread` to the .mm file. …
=> [ios] refactor platform_message_handler_ios

impeller/entity/shaders/linear_gradient_ssbo_fill.frag, impeller/entity/shaders/radial_gradient_ssbo_fill.frag, impeller/entity/shaders/sweep_gradient_ssbo_fill.frag
While researching https://github.com/flutter/flutter/issues/122324 I saw that this was an easy performance gain, might as well land it while we wait to remove implicit conversions.
[breaking …
=> Switched floats to ints in gradient shaders for better performance

lib/ui/painting/image_decoder_impeller.cc, lib/ui/painting/image_decoder_unittests.cc
=> Fixed crash with images without specified colorspaces in wide gamut test

tools/gn
This flag is being added here in an upcoming dart sdk change:
https://dart-review.googlesource.com/c/sdk/+/288040
=> Do not include wasm-opt with in-tree dart sdk build

.ci.yaml, ci/builders/linux_web_engine.json
We only ever build wasm in this builder, so it never needs goma.
=> Use `no_goma` for the web framework tests.

impeller/renderer/backend/vulkan/allocator_vk.cc, impeller/renderer/backend/vulkan/context_vk.cc, impeller/renderer/compute_unittests.cc, impeller/tools/impeller.gni
Fix build errors for Vulkan in Windows.
I spent some time trying to figure out why `vmaCreateImage` is failing with `ErrorFeatureNotPresent`, but didn't manage to figure it out.
1. First it fails to allocate the 1x1 placeholder texture in the Impeller Scene context:
```cpp
$ ../out/host_debug_unopt/impeller_unittests.exe --gtest_filter="*CanRenderColoredRect/Vulkan"
[INFO:test_timeout_listener.cc(76)] Test timeout of 120 seconds per test case will be enforced.
Note: Google Test filter = *CanRenderColoredRect/Vulkan
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from Play/AiksTest
[ RUN      ] Play/AiksTest.CanRenderColoredRect/Vulkan
UNASSIGNED-khronos-validation-createinstance-status-message(INFO / SPEC): msgNum: -671457468 …
```
=> [Impeller] Build Impeller Vulkan backend on Windows

display_list/display_list_builder.h, display_list/display_list_unittests.cc
Fixes https://github.com/flutter/flutter/issues/122366
=> fix typo in LayerInfo::has_compatible_op

tools/activate_emsdk.py
This ends up basically finding the emsdk directory relative to the gclient checkout, which is different in the monorepo than it is in a engine checkout by itself. So we can find the emsdk directory relative to the script itself.
=> Find the emsdk by relative path so that this works with the monorepo.

lib/web_ui/lib/src/engine/canvaskit/fonts.dart, lib/web_ui/lib/src/engine/text/font_collection.dart, lib/web_ui/test/canvaskit/skia_font_collection_test.dart, runtime/test_font_data.cc, testing/dart/canvas_test.dart, testing/dart/paragraph_builder_test.dart
Make FlutterTest the default test font. Fixes https://github.com/flutter/flutter/issues/62819
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking- …
=> Make FlutterTest the default test font

DEPS
To pick up https://github.com/flutter/buildroot/pull/691
=> Roll buildroot to 287917d342224d34d6fbdf863aee8417a5f2e8b8

lib/web_ui/lib/src/engine/canvaskit/fonts.dart, lib/web_ui/lib/src/engine/text/font_collection.dart, lib/web_ui/test/canvaskit/skia_font_collection_test.dart, runtime/test_font_data.cc, testing/dart/canvas_test.dart, testing/dart/paragraph_builder_test.dart
=> Revert "Make FlutterTest the default test font"

shell/common/BUILD.gn, shell/common/fixtures/shell_test.dart, shell/common/rasterizer.cc, shell/common/shell_unittests.cc
The unconditional `MakeBitmapImage` is no longer necessary on Linux, with or without this context switch change. That fixes https://github.com/flutter/flutter/issues/108835
Might help https://github.com/flutter/flutter/issues/121485
Context switch fixes https://github.com/flutter/flutter/issues/120815. This was figured out by @jason-simmons - without the switch, we might be piggybacking on GDK's GL context/FBO and causing the problems seen in that bug.
I'm not quite sure what to do about the MakeBitmapImage path. It's not entirely safe, for example if you went to background on iOS and have a display_list that contains an SkImage_gpu. We have this problem elsewhere too AFAICT (e.g. in the regular `toImage` path).
~~I'm not sure how to test this. Will try to think on that a bit.~~
=> Make the context current before accessing GL in MakeSkiaGpuImage

shell/platform/darwin/macos/framework/Source/FlutterViewController.mm, shell/platform/darwin/macos/framework/Source/FlutterViewControllerTest.mm
This works around an AppKit bug in which mouseDown/mouseUp events are not correctly forwarded up the responder chain for views nested inside an `NSPopover` if (and only if) the macOS "Reduce Transparency" accessibility setting is enabled in the System Settings.
When the above conditions are satisfied, the nested NSView receives the `mouseDown:`/`mouseUp:` call but if it delegates to the default implementation (implemented in `NSResponder`) `mouseDown:`/`mouseUp:` calls are triggered on containing views (in our case `FlutterViewWrapper`) but not triggered on the view controller and other responders in the responder chain until we an `_NSPopoverWindow` class is hit.
A minimal AppKit-only (non-Flutter) repro shows this bug repros with even a minimal `NSViewController` implementation and an …
=> [macOS] Forward mouseDown/Up to view controller

common/config.gni, tools/gn
This PR adds a flag that allows disabling building host engine artifacts during a host build. This is useful when it is only needed to build the desktop embedder for the host platform during a build. This will allow limiting LTO building/linking to a narrower slice of targets.
This PR also adds a flag that disables building unittests for similar reasons.
=> Add GN arguments that disable building host artifacts and unittests

lib/web_ui/lib/src/engine/canvaskit/canvaskit_api.dart, lib/web_ui/lib/src/engine/canvaskit/text_fragmenter.dart, lib/web_ui/test/canvaskit/text_fragmenter_test.dart
Let CanvasKit do the malloc/copy into linear memory for us.
Doing malloc ourselves and attempting to use a view into the malloced linear memory fails on dart2wasm for the same reasons we get failures in https://github.com/flutter/flutter/issues/118334
I think this is basically equivalent perf-wise anyway, it's just changing who is doing the work (now CanvasKit does the malloc + copy instead of us).
=> Use plain Uint32List objects with the fragmenter APIs.

.ci.yaml
Currently --no-lto is hardcoded in presubmit builds in the ci_yaml starlark file here https://cs.opensource.google/flutter/infra/+/main:config/lib/ci_yaml/ci_yaml.star;l=398?q=lto&ss=flutter%2Finfra:config%2F.
This PR shifts setting the property into the `.ci.yaml` file. Since in general we want LTO in prod builds, and no LTO in try builds, this PR sets the `no_lto` property to `true` in the `platform_properties`, then for each configuration sets `no_lto` to `false` in their respective `postsubmit_properties`. This would be less confusing if `.ci.yaml` supported a `presubmit_properties` that could be set once-and-for-all in the `platform_properties` cc @keyonghan
=> Make no_lto in presubmit explicit in .ci.yaml

tools/gn
Makes it easier to more frequently run malioc build steps locally.
For me, this means adding the following to my .zshrc:
```
export MALIOC_PATH="/Applications/Arm_Mobile_Studio_2023.0/mali_offline_compiler/malioc"
```
=> Let local users specify malioc path via environment

.ci.yaml
Reverts flutter/engine#40254
This didn't work. `--no-lto` was passed to postsubmit builds where it shouldn't have gone. See https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20iOS%20Engine%20Release/19141/overview
@CaseyHillers @keyonghan
=> Revert "Make no_lto in presubmit explicit in .ci.yaml"

display_list/BUILD.gn
Fixes: https://github.com/flutter/flutter/issues/122515
Inconsistent compiler defines were causing crashes when not all modules were compiled with the right 3D flags.
=> fix unittests that depend on DisplayList when Impeller 3D is enabled

.ci.yaml
The flutter_internal version of the package is bad for arm64, whereas the flutter version is not. A recipe change will point the bots to flutter instead of flutter_internal.
=> .ci.yaml: s/flutter_internal/flutter

common/graphics/texture.cc, common/graphics/texture.h, flow/texture_unittests.cc, lib/ui/painting/display_list_deferred_image_gpu_skia.cc, testing/testing.gni
Fixes https://github.com/flutter/flutter/issues/122566
The cause of that bug is that multiple dependent `toImageSync` calls are made such that each successive image depends on the previous one.
In the current implementation, a `std::map` is causing the `OnGrContextCreated` calls to happen in sort-order based on pointer values. This patch adds another map to track the insertion order and a test to make sure that the callbacks respect insertion order.
=> Preserve order when regenerating GPU images

lib/ui/dart_ui.cc, lib/ui/painting.dart, lib/ui/painting/image.cc, lib/ui/painting/image.h, lib/ui/painting/image_encoding.cc, lib/ui/painting/image_encoding_impeller.cc, lib/ui/painting/image_encoding_impeller.h, lib/web_ui/lib/painting.dart, lib/web_ui/lib/src/engine/canvaskit/image.dart, lib/web_ui/lib/src/engine/html_image_codec.dart, lib/web_ui/lib/src/engine/skwasm/skwasm_impl/image.dart, lib/web_ui/test/html/recording_canvas_golden_test.dart, testing/dart/encoding_test.dart
fixes https://github.com/flutter/flutter/issues/121729
[Discord]: …
=> Added wide-gamut color support for `ui.Image.toByteData` and `ui.Image.colorSpace`

impeller/geometry/geometry_unittests.cc, impeller/geometry/rect.h
fix https://github.com/flutter/flutter/issues/122486
Without this patch: if `origin.x` is `-inf` and `size.width` is `+inf`, Then `right` is `std::max(-inf, -inf + +inf)`,  which result is `-inf`. So the result of `GetLTRG()` is `[-inf, -inf, -inf, -inf]`
[CLA]: …
=> [Impeller] Correct the results of 'GetRight()' and 'GetBottom()' for maximum rect

impeller/aiks/aiks_unittests.cc, impeller/aiks/paint.cc, impeller/aiks/paint.h, impeller/display_list/display_list_dispatcher.cc, impeller/display_list/display_list_unittests.cc, impeller/entity/contents/filters/filter_contents.cc, impeller/entity/contents/filters/filter_contents.h, impeller/entity/contents/filters/gaussian_blur_filter_contents.cc, impeller/entity/contents/filters/matrix_filter_contents.cc, impeller/entity/contents/filters/matrix_filter_contents.h, impeller/entity/contents/filters/morphology_filter_contents.cc, impeller/entity/entity_pass.cc, impeller/entity/entity_pass.h
fix https://github.com/flutter/flutter/issues/121893
fix https://github.com/flutter/flutter/issues/120879
This PR tries to distinguish whether it is a subpass scene (aka. save layer) in MatrixImageFilterContents, and do different processing for subpass scenes.
[CLA]: …
=> [Impeller] Make matrix image filter in saving layer work as expected

shell/platform/linux/public/flutter_linux/fl_pixel_buffer_texture.h, shell/platform/linux/public/flutter_linux/fl_texture_gl.h
Use 'MyTexture' naming to match the Linux shell 'MyApplication'.
Show how to connect up the virtual methods.
=> Improve Linux texture examples.

impeller/aiks/paint.cc, impeller/aiks/paint.h, impeller/entity/entity_pass.cc, impeller/entity/entity_pass.h
Get rid of `Paint::WithFilters` `effect_matrix` parameter which should never be used.
Flatten out/simplify some branches in the subpass entity logic to make following it easier.
=> [Impeller] Simplify subpass branches; remove unused effect_matrix param

lib/ui/dart_ui.cc, lib/ui/painting.dart, lib/ui/painting/image.cc, lib/ui/painting/image.h, lib/ui/painting/image_encoding.cc, lib/ui/painting/image_encoding_impeller.cc, lib/ui/painting/image_encoding_impeller.h, lib/web_ui/lib/painting.dart, lib/web_ui/lib/src/engine/canvaskit/image.dart, lib/web_ui/lib/src/engine/html_image_codec.dart, lib/web_ui/lib/src/engine/skwasm/skwasm_impl/image.dart, lib/web_ui/test/html/recording_canvas_golden_test.dart, testing/dart/encoding_test.dart
Reverts flutter/engine#40031
Blocking the engine->flutter roller.
```
ELAPSED TIME: 17.089s for bin/flutter analyze --flutter-repo --watch --benchmark in .
▌18:58:12▐ Snippet code...
RUNNING: cd .; bin/cache/dart-sdk/bin/dart --enable-asserts /b/s/w/ir/x/w/Á flutter sdk/dev/bots/analyze_snippet_code.dart --verbose
bin/cache/pkg/sky_engine/lib/ui/painting.dart:1628:11: A value of type 'dynamic' can't be assigned to a variable of type 'ByteData' (top-level declaration) (invalid_assignment)
bin/cache/pkg/sky_engine/lib/ui/painting.dart:1628:12: The await expression can only be used in an async function (top-level declaration) (await_in_wrong_context)
bin/cache/pkg/sky_engine/lib/ui/painting.dart:1628:18: Method invocation or property access on a 'dynamic' target (top-level declaration) …
```
=> Revert "Added wide-gamut color support for `ui.Image.toByteData` and `ui.Image.colorSpace`"

lib/web_ui/pubspec.yaml, tools/path_ops/dart/pubspec.yaml, web_sdk/pubspec.yaml
To fix problems surfaced by Dart SDK roll https://github.com/flutter/engine/pull/40296
=> Bump pubspecs to unblock Dart SDK roller

ci/licenses_golden/excluded_files, impeller/entity/BUILD.gn, impeller/scene/shaders/BUILD.gn, impeller/tools/impeller.gni, impeller/tools/malioc.gni, impeller/tools/malioc.json, impeller/tools/malioc_cores.py, impeller/tools/malioc_diff.py
This PR adds analysis of shaders that are compiled to SPIR-V 1.3 for the vulkan backend. This allows analyzing shaders that use ssbos and framebuffer fetch.
=> Analyze more shaders

lib/web_ui/lib/src/engine/canvaskit/fonts.dart, lib/web_ui/lib/src/engine/text/font_collection.dart, lib/web_ui/test/canvaskit/skia_font_collection_test.dart, runtime/test_font_data.cc, testing/dart/canvas_test.dart, testing/dart/paragraph_builder_test.dart
Reland #40188, with an additional **temporary** flag (in the form of an env var) to opt-in.  The environment variable does not affect web. DIFF https://github.com/flutter/engine/pull/40245/commits/efe1904c5cc77a059dfcc84270a15ce1549a7677 …
=> Reland "Make FlutterTest the default test font" (#40188)

lib/ui/dart_ui.cc, lib/ui/painting.dart, lib/ui/painting/image.cc, lib/ui/painting/image.h, lib/ui/painting/image_encoding.cc, lib/ui/painting/image_encoding_impeller.cc, lib/ui/painting/image_encoding_impeller.h, lib/web_ui/lib/painting.dart, lib/web_ui/lib/src/engine/canvaskit/image.dart, lib/web_ui/lib/src/engine/html_image_codec.dart, lib/web_ui/lib/src/engine/skwasm/skwasm_impl/image.dart, lib/web_ui/test/html/recording_canvas_golden_test.dart, testing/dart/encoding_test.dart
This PR (https://github.com/flutter/engine/pull/40031) was reverted in https://github.com/flutter/engine/pull/40295 because of analysis errors in the code snippet, the code snippet has been updated.  I've also filed an issue to try to plug this ci hole: https://github.com/flutter/flutter/issues/122714 …
=> Reland: "Added wide-gamut color support for `ui.Image.toByteData` and `ui.Image.colorSpace`"

lib/ui/painting.dart, lib/ui/painting/image_decoder_impeller.cc, lib/ui/painting/image_decoder_unittests.cc, lib/ui/painting/image_descriptor.cc, lib/ui/painting/image_descriptor.h, testing/dart/encoding_test.dart
fixes https://github.com/flutter/flutter/issues/121730
[Discord]: …
=> Added float32 support to decodeImageFromPixels

lib/web_ui/lib/src/engine/browser_detection.dart, lib/web_ui/lib/src/engine/canvaskit/canvaskit_api.dart, lib/web_ui/lib/src/engine/canvaskit/text.dart, lib/web_ui/lib/src/engine/canvaskit/text_fragmenter.dart, lib/web_ui/test/canvaskit/canvaskit_api_test.dart
Reverts flutter/engine#40154
Link to failure:
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Web%20Engine/15924/overview
failure text:
```
05:04 [32m+312[0m[33m ~14[0m[31m -4[0m: test/canvaskit/image_golden_test.dart: CanvasKit Images (webcodecs) the same image can be rendered on difference surfaces[0m                                                           
05:04 [32m+312[0m[33m ~14[0m[31m -4[0m: [1m[90mloading test/ui/path_test.dart[0m[0m                                                                                                                                                      
goldctl imgtest add stdout: Given image with hash efdfae048b059fa1fdd0cd04a046b5a5 for test canvaskit_read_back_decoded_image_webcodecs
Expectation for test: …
```
=> Revert "[web] Better way to detect CanvasKit variant"

shell/platform/darwin/macos/framework/Headers/FlutterViewController.h, shell/platform/darwin/macos/framework/Source/FlutterEngine.mm, shell/platform/darwin/macos/framework/Source/FlutterEngineTest.mm, shell/platform/darwin/macos/framework/Source/FlutterViewController.mm
`id` is a type in Objective-C similar to dynamic in Dart, and while it *can* be used as an identifier, it's bad practice to do so and results in unidiomatic code. `viewId` also more clearly indicates the purpose of this identifier.
Also replaces the use of `@dynamic` (which is meant to indicate properties whose implementation is either added at runtime or stashed away in a superclass) with `@synthesize`, which is an idiomatic way to declare that an ivar `_foo` should be synthesized for property `foo`.
While this is renaming a public property and thus constitutes a breaking change, multi-view support is still under development and thus, practically speaking, this should not be a breaking change. …
=> [macOS] Rename FlutterViewController.id to viewId

shell/platform/linux/fl_pixel_buffer_texture.cc, shell/platform/linux/fl_pixel_buffer_texture_test.cc, shell/platform/linux/fl_texture.cc, shell/platform/linux/fl_texture_gl.cc, shell/platform/linux/fl_texture_gl_test.cc, shell/platform/linux/fl_texture_private.h, shell/platform/linux/fl_texture_registrar.cc, shell/platform/linux/fl_texture_registrar_test.cc, shell/platform/linux/public/flutter_linux/fl_texture.h, shell/platform/linux/testing/mock_engine.cc, shell/platform/linux/testing/mock_texture_registrar.cc
Was making use of the texture API and found there wasn't a method to get the ID as required to pass to Flutter.
=> Add fl_texture_get_id, so textures can be passed to Flutter

shell/platform/darwin/macos/framework/Source/AccessibilityBridgeMacTest.mm, shell/platform/windows/accessibility_bridge_windows_unittests.cc
Fixes a few instances where we were using reinterpret_cast and reinterpret_pointer_cast but could have been using static_cast since the types being cast between are related types in the same hierarchy. …
=> [macOS,Windows] Use static casts where possible

ci/builders/linux_web_engine.json
Web engine builds are not using goma and they need to run on machines with more the 8 cpus.
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-ch …
=> Use 32 cores builder for linux v2 web engine.

shell/platform/darwin/macos/framework/Source/FlutterViewController.mm
Since `view` is a property of `NSViewController`, it's unnecessary for us to declare `@dynamic view` in `FlutterViewController`'s implementation.
No test changes since this change is simply eliminating an unnecessary redeclaration of a property that's part of the `NSViewController` superclass. …
=> [macOS] Eliminate unnecessary dynamic declaration

impeller/entity/entity_unittests.cc
Fixes https://github.com/flutter/flutter/issues/122827
We don't need to check for overlapping geometry unless its text
=> [Impeller] fix opacity inheritance test

impeller/renderer/backend/gles/blit_pass_gles.cc, impeller/renderer/backend/gles/blit_pass_gles.h, impeller/renderer/backend/metal/blit_command_mtl.h, impeller/renderer/backend/metal/blit_command_mtl.mm, impeller/renderer/backend/metal/blit_pass_mtl.h, impeller/renderer/backend/metal/blit_pass_mtl.mm, impeller/renderer/backend/vulkan/blit_pass_vk.cc, impeller/renderer/backend/vulkan/blit_pass_vk.h, impeller/renderer/blit_pass.cc, impeller/renderer/blit_pass.h, impeller/renderer/testing/mocks.h, lib/ui/painting/image_decoder_impeller.cc
Fixes https://github.com/flutter/flutter/issues/122819
Apple performance tips say to do this, so lets do it.
=> [Impeller] mark decoded images as optimized for GPU access

shell/platform/darwin/macos/framework/Source/FlutterEngine.mm, shell/platform/darwin/macos/framework/Source/FlutterEngineTest.mm
This fixes the application exit handler so that it deals more gracefully with errors returned to it from the framework.
In this case, since the framework doesn't yet have support for requesting an application exit, it was returning an error condition, which the previous code tried to convert to an NSDictionary (and failed, causing a crash).
Now it will log the error and quit as requested if an error or unrecognized object type is returned.
- https://github.com/flutter/flutter/issues/122813
- Added a test for the error condition.
=> Handle error more gracefully, add test for same

lib/ui/window.dart
This is no longer true after #35589
Updates docs to include Android support.
=> Update documentation on `AccessibilityFeatures.boldText`

shell/platform/windows/platform_handler.cc, shell/platform/windows/platform_handler_unittests.cc
Currently, the framework allows setting the clipboard to `null`. This was an unintentional mistake from the `null` safety migration and [platforms handle this case incorrectly](https://github.com/flutter/flutter/issues/121976#issuecomment-1464721716). We will update the framework to disallow setting the clipboard's data to `null`: https://github.com/flutter/flutter/pull/122446
In the meantime, this change makes the Windows embedder resilient to unexpected clipboard messages. If your clipboard data's text is unexpected, you will now get an error instead of crashing your app.
Part of https://github.com/flutter/flutter/issues/121976
=> [Windows] Fix crash if clipboard is set to null

impeller/compiler/shader_lib/impeller/gradient.glsl
I accidentally broke this while editing the pr in review.  The test for it is coming in the golden image work I'm doing in https://github.com/flutter/engine/pull/40366 …
=> Fixed the conical gradient.

impeller/entity/contents/texture_contents.cc, impeller/entity/contents/texture_contents.h
Doesn't make a huge difference but helps reduce noise for tracking work the tessellator is doing.
=> [Impeller] dont tessellate rectangles in TextureContents

lib/web_ui/lib/src/engine/dom.dart, lib/web_ui/lib/src/engine/font_change_util.dart, lib/web_ui/lib/src/engine/initialization.dart, lib/web_ui/lib/src/engine/platform_dispatcher.dart, lib/web_ui/test/engine/surface/scene_builder_test.dart, lib/web_ui/test/text/font_collection_test.dart, lib/web_ui/test/text/font_loading_test.dart, web_sdk/sdk_rewriter.dart, web_sdk/test/sdk_rewriter_test.dart, web_sdk/web_engine_tester/lib/static/host.dart
This CL is the first in a small set of CLs to migrate the DOM shim to JS types.
=> [web] Migrate DOM shim to JS types.

impeller/renderer/backend/gles/blit_pass_gles.cc, impeller/renderer/backend/gles/blit_pass_gles.h, impeller/renderer/backend/metal/blit_command_mtl.h, impeller/renderer/backend/metal/blit_command_mtl.mm, impeller/renderer/backend/metal/blit_pass_mtl.h, impeller/renderer/backend/metal/blit_pass_mtl.mm, impeller/renderer/backend/vulkan/blit_pass_vk.cc, impeller/renderer/backend/vulkan/blit_pass_vk.h, impeller/renderer/blit_pass.cc, impeller/renderer/blit_pass.h, impeller/renderer/testing/mocks.h, lib/ui/painting/image_decoder_impeller.cc
Reverts flutter/engine#40356
This change regressed raster thread metrics, see: https://github.com/flutter/flutter/issues/122897
Image upload itself is done from a background thread, so it can't block directly. Unfortunately, that likely means that the optimizeForGpuAccess is causing extra work that the raster thead is blocked on.
=> Revert "[Impeller] mark decoded images as optimized for GPU access"

shell/platform/darwin/ios/platform_message_handler_ios.mm
With background platform isolate channels, the handler can be invoked on threads that are created by Dart and do not already have an autorelease pool.
Fixes https://github.com/flutter/flutter/issues/122792
=> Wrap the iOS platform message handler in an autorelease pool block

web_sdk/pubspec.yaml, web_sdk/test/api_conform_test.dart
Follow-up to https://github.com/flutter/engine/pull/40328.
Just now a new analyzer version was released on pub that has the 3.0 experiments enabled by default (see also https://github.com/dart-lang/sdk/issues/51760). With that version we don't have to manually manage experiment flags in the api_conform_test.
=> Update analyzer for api_conform_test

testing/run_tests.py
This also re-enables the tests.
Related https://github.com/flutter/flutter/issues/117122
=> Ignore some MTLCompiler failures in impeller unit tests

fml/synchronization/semaphore.h, shell/common/pipeline.h
Adds more detailed documentation to the Pipeline class. Also fixes a typo in fml::Semaphore docs.
No tests since this patch makes no semantic changes. …
=> Add doc comment to Pipeline

shell/platform/common/accessibility_bridge.h, shell/platform/darwin/macos/framework/Source/AccessibilityBridgeMac.mm, shell/platform/darwin/macos/framework/Source/AccessibilityBridgeMacTest.mm
Today, the root accessibility semantics node is guaranteed to have ID 0. In a multi-window world, each view will have its own semantics tree, but semantic node IDs will be globally unique. In other words, the semantics tree's root will no longer be guaranteed to have ID 0. As a result, `AccessibilityBridge::kRootNodeId` is deprecated and all uses should be removed.
Part of https://github.com/flutter/flutter/issues/119391
<details>
<summary>Manual test...</summary>
Apply the framework patch below, run an app using your local engine, and verify the accessibility works as expected:
```diff
diff --git a/packages/flutter/lib/src/semantics/semantics.dart b/packages/flutter/lib/src/semantics/semantics.dart
index 969f822f5f..6431b3ed28 100644
--- …
```
=> [macOS] Remove a single accessibility root assumption

runtime/test_font_data.cc
Remove the temporary flag for migrating the font change.
[Discord]: …
=> Remove temporary flag and make FlutterTest the default font for real

display_list/display_list_builder.cc, display_list/display_list_unittests.cc
Technically we've never been able to trust drawTextBlob to be non-overlapping, but in practice it has nearly always been OK with inheriting opacity as most text strings don't have overlapping glyphs, and also in practice most text is drawn over a background fill so it is already involved in an incompatible DisplayList.
Recently, as we try to fix our opacity inheritance implementation code, though, some tests that draw text can have a lot of off-by-1 errors as various paths through the engine start to become capable of distributing the opacity to single-text-blob DisplayList objects, pointing out that there are real world cases where there are differences in rendering text with or without inherited opacity.
So, it is time to bite the bullet and declare that text blobs are incompatible with …
=> drawTextBlob should not be compatible with opacity inheritance

web_sdk/pubspec.yaml
In https://github.com/flutter/engine/pull/40328 it tripped me up that the analyzer used by `tools/api_check` behaved differently than the analyzer used by `web_sdk`. The reason for that mystery was: `tools/api_check` uses the analyzer directly from the dart sources, while `web_sdk` used an (outdated) version from pub. The version from pub will always be slightly behind, which is why `web_sdk` sometimes requires fiddling with experiment flags to get it to behave as expected (see https://github.com/flutter/engine/pull/40386). That's annoying and having to deal with different analyzer versions is confusing. This change migrates `web_sdk` to always use the up-to-date analyzer from the dart sources directly, just like `tools/api_check` does: …
=> Use analyzer from dart source everywhere

impeller/playground/BUILD.gn, impeller/playground/playground.cc, impeller/playground/playground.h, impeller/playground/playground_test.cc, impeller/playground/playground_test.h, impeller/playground/switches.cc, impeller/playground/switches.h, testing/BUILD.gn, testing/run_all_unittests.cc, testing/test_args.cc, testing/test_args.h
The playgrounds respect the usual GTest flags such as --gtest_filter. Now, specific test harnesses can add their own flags. The playgrounds now respect a --playground_timeout_ms flag that renders a playground for a set amount of time. Setting this to zero will mean that the playgrounds render only a single frame.
=> [Impeller] Add playground flag to render for a specific amount of time.

lib/web_ui/README.md, lib/web_ui/dev/canvaskit_lock.yaml, lib/web_ui/dev/canvaskit_roller.dart, lib/web_ui/lib/src/engine/configuration.dart
Reverts flutter/engine#40293
Engine -> framework roll failing starting in https://github.com/flutter/flutter/pull/122933
Example: https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20web_long_running_tests_1_5/32847/overview
=> Revert "Default the CanvasKit base URL to local artifacts."

tools/gn
Previous updates to building the Impeller unit-tests on CI took away the ability to run the Vulkan or OpenGL tests on macOS hosts. Engineers working on those backends now have to supply the flags explicitly.
=> [Impeller] Add flags to enable the Vulkan and OpenGL ES backends.

impeller/entity/inline_pass_context.cc, impeller/entity/inline_pass_context.h
Fixes the `Play/AiksTest.CanRenderClippedLayers/OpenGLES` playground and removes unnecessary restore work when MSAA isn't being used.
=> [Impeller] Load instead of restore drawing for non-MSAA passes

impeller/tessellator/dart/lib/tessellator.dart, lib/web_ui/lib/src/engine/skwasm/skwasm_impl/raw/raw_canvas.dart, lib/web_ui/lib/src/engine/skwasm/skwasm_impl/raw/raw_memory.dart, lib/web_ui/lib/src/engine/skwasm/skwasm_impl/raw/raw_paint.dart, lib/web_ui/lib/src/engine/skwasm/skwasm_impl/raw/raw_path.dart, lib/web_ui/lib/src/engine/skwasm/skwasm_impl/raw/raw_path_metrics.dart, lib/web_ui/lib/src/engine/skwasm/skwasm_impl/raw/raw_picture.dart, lib/web_ui/lib/src/engine/skwasm/skwasm_impl/raw/raw_surface.dart, shell/platform/fuchsia/dart-pkg/zircon_ffi/lib/zircon_ffi.dart, tools/path_ops/dart/lib/path_ops.dart
Following the lead of https://github.com/dart-lang/sdk/commit/1755f8909264330a207a0e0e44d31f5fec9c489a, this adds the `final` class modifier to all subclasses of `Struct`, `Union`, `Opaque`, and `AbiSpecificInteger` to unblock the dart roll (https://github.com/flutter/engine/pull/40426).
=> add final class modifiers to fix dart roll

shell/platform/darwin/ios/framework/Source/FlutterPlatformViews.mm, shell/platform/darwin/ios/framework/Source/FlutterPlatformViewsTest.mm, shell/platform/darwin/ios/framework/Source/FlutterPlatformViews_Internal.h, shell/platform/darwin/ios/framework/Source/FlutterPlatformViews_Internal.mm
Exact Reland https://github.com/flutter/engine/pull/38989
The change in the PR was supposed to be re-landed in https://github.com/flutter/engine/pull/39630 but somehow did not.
PlatformViewMutationClipRectAfterMovedTests that was added in https://github.com/flutter/engine/pull/39630 ensures b/268403088 is not regressed. …
=> Reland "[ios_platform_view] MaskView pool to reuse maskViews" (#39608)"

lib/web_ui/lib/src/engine/canvaskit/fonts.dart, lib/web_ui/lib/src/engine/fonts.dart, lib/web_ui/lib/src/engine/renderer.dart, lib/web_ui/lib/src/engine/skwasm/skwasm_impl/renderer.dart, lib/web_ui/lib/src/engine/skwasm/skwasm_stub/renderer.dart, lib/web_ui/lib/src/engine/text/font_collection.dart
This will avoid name conflicts with the FontCollection API that will be added to CanvasKit.
(see https://skia-review.googlesource.com/c/skia/+/657270)
=> Rename FontCollection to FlutterFontCollection

lib/ui/hooks.dart, lib/ui/platform_dispatcher.dart, lib/ui/window/platform_configuration.cc, lib/ui/window/platform_configuration.h, runtime/runtime_controller.cc, runtime/runtime_controller.h, shell/common/engine.cc
This renames `PlatformConfiguration::UpdateLifecycleState` and `RuntimeController::SetLifecycleState` to `PlatformConfiguration::UpdateInitialLifecycleState` and `RuntimeController::SetInitialLifecycleState`, respectively, and some associated private functions.
This is because calling this function really only updates the initial state that the binding loads when it initializes, it doesn't continuously update the lifecycle state.
- No tests changed. This is a rename of the API, and currently doesn't appear to have any direct test dependencies.
**One note:** These appear to both be deprecated APIs. Perhaps it would be better to just remove them?  The only thing is I'm not sure what the deprecation message means by "persistent isolate data", and what the replacement code would be.
=> Rename setters for lifecycle state

lib/ui/painting/image_decoder_impeller.cc
Fixes https://github.com/flutter/flutter/issues/121547
See more context in https://github.com/flutter/flutter/issues/123058
=> [impeller] serialize texture upload

impeller/aiks/aiks_unittests.cc, impeller/entity/contents/text_contents.cc, impeller/renderer/backend/gles/sampler_gles.cc, impeller/renderer/backend/metal/formats_mtl.h, impeller/renderer/backend/vulkan/formats_vk.h, impeller/renderer/formats.h, impeller/renderer/renderer_unittests.cc, impeller/renderer/sampler_descriptor.h, impeller/scene/geometry.cc
By default we create mipmaps for every decoded image. Choosing the nearest mip level is the only reasonable default.
=> [Impeller] change default sampler descriptor to use nearest mip level and remove kNone

lib/ui/dart_runtime_hooks.cc
Doing so is currently a NOP because `vm-service` isn't available in flutter-release (aka Dart VM product) mode.
So this makes startup time of isolates slightly faster in release mode and allows tree shaking of the relevant code in release mode.
=> Avoid registering service extensions in flutter-release mode

lib/web_ui/dev/test_platform.dart, lib/web_ui/lib/src/engine/canvaskit/canvaskit_api.dart, lib/web_ui/test/canvaskit/canvaskit_api_test.dart
This is the last bit to make CanvasKit Chromium available to our users by default.
Users can always opt-out by `canvasKitVariant: "full"` to their runtime configuration similar to [this](https://docs.flutter.dev/development/platform-integration/web/renderers#runtime-configuration).
```javascript
_flutter.loader.loadEntrypoint({
onEntrypointLoaded: async function(engineInitializer) {
let appRunner = await engineInitializer.initializeEngine({
canvasKitVariant: "full",
});
await appRunner.runApp();
}
});
```
Closes https://github.com/flutter/flutter/issues/122329
=> [web] Turn on CanvasKit Chromium

lib/web_ui/dev/test_platform.dart, lib/web_ui/lib/src/engine/canvaskit/canvaskit_api.dart, lib/web_ui/test/canvaskit/canvaskit_api_test.dart
Reverts flutter/engine#40459
Failing to roll to the framework: https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20web_canvaskit_tests_2/23799/overview
=> Revert "[web] Turn on CanvasKit Chromium"

impeller/aiks/canvas.cc, impeller/entity/entity_pass.cc
This causes rendering issues on wonderous that I missed. I think we're screwing up the stencil depth checks when collapsing
=> [impeller] disable opacity peephole due to stencil issues

impeller/renderer/backend/metal/allocator_mtl.mm, impeller/renderer/texture_descriptor.h
Adds support for but does not use a texture compression enum for Impeller.
=> [impeller] add CompressionType enum to texture descriptor

.ci.yaml
This is to force subbuilds to run on host only bots, avoiding https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Web%20Framework%20tests/14187/overview
=> Add drone_dimension to target `Linux Web Framework tests`

DEPS
Changes since the last roll:
```
b44849e Update matcher contents post bump in dart sdk. (#695)
dd18826 Bump github/codeql-action from 2.2.6 to 2.2.7 (#693)
b7dd546 Bump actions/checkout from 3.3.0 to 3.4.0 (#694)
18ea6ef Bump github/codeql-action from 2.2.5 to 2.2.6 (#692)
```
=> Roll buildroot to b44849ee7d2b080fd5cc699e7fd37d79c13d012d

third_party/txt/src/txt/platform_linux.cc
Prior to this change, the system fonts were being loaded twice, which was affecting application startup performance on Linux.
The first call was being triggered by `Engine::SetupDefaultFontManager` while the second one happened during the first call to `SkFontMgr::RefDefault()` which is usually triggered by [`SkTypeface::MakeFromStream()`](https://github.com/google/skia/blob/0c4a277118d7fd60623e448b1a27eb34d3953e0c/src/core/SkTypeface.cpp#L216). The following stack traces show the code paths leading to these calls:
<details>
<summary>First call to DirectorySystemFontLoader::loadSystemFonts</summary>
```
libflutter_linux_gtk.so!DirectorySystemFontLoader::loadSystemFonts(const DirectorySystemFontLoader * this, const SkTypeface_FreeType::Scanner & scanner, SkFontMgr_Custom::Families * …
```
=> [Linux] Fix duplicate calls to system font loading during startup

third_party/canvaskit/BUILD.gn
Partial revert of https://github.com/flutter/engine/pull/40309
Unfortunately, we can't remove image codecs from CanvasKit at the moment because we still need them when decoding an image to a target width and height (see [here](https://github.com/flutter/engine/blob/5f7df579152edce72d1d11363fda00fa8fe4ca5f/lib/web_ui/lib/src/engine/canvaskit/image.dart#L27-L34)).
=> [web] Put image codecs back into CanvasKit Chromium

lib/ui/window.dart
Migration Guide: https://github.com/flutter/website/pull/8283
To be submitted after https://github.com/flutter/flutter/pull/120998.
=> Deprecate SingletonFlutterWindow and global window singleton

impeller/compiler/shader_lib/impeller/path.glsl, impeller/fixtures/cubic_to_quads.comp, impeller/fixtures/quad_polyline.comp
Also does some refactoring to move code under test to a shared file for future use in the more generalized path polyline generator.
This is another part of addressing https://github.com/flutter/flutter/issues/122828. 
The last piece left is to split invocations up into chunks that fit into the `threadExecutionWidth`.
I don't have a test with this change, but it will be tested when we re-enable the tests from the linked issue on Intel machines. Ideally we'd have some kind of linting or fuzzing for this, but there's no good existing solution for that right now.
=> [Impeller] Refactor Cubic/Quad tests to make sure all threads reach barrier()

shell/platform/common/accessibility_bridge.cc, shell/platform/common/accessibility_bridge.h, shell/platform/embedder/embedder.cc, shell/platform/embedder/embedder.h, shell/platform/embedder/tests/embedder_a11y_unittests.cc, shell/platform/embedder/tests/embedder_config_builder.cc, shell/platform/embedder/tests/embedder_test_context.cc, shell/platform/embedder/tests/embedder_test_context.h
This introduces a new update semantics embedder API that is identical to [the previous update semantics embedder API](https://github.com/flutter/engine/pull/37129), except that its ABI is stable as:
1. The callback uses array of pointers to structs instead of array of structs. This ensures that array indexing does not break if new members are added to the structs.
2. The types `FlutterSemanticsNode` and `FlutterSemanticsCustomAction` were duplicated as `FlutterSemanticsNode2` and `FlutterSemanticsCustomAction2`. This is necessary as `FlutterSemanticsUpdate` has an array of `FlutterSemanticsNode` and an array of `FlutterSemanticsCustomAction`. Adding new members to these structs would break the ABI compatibility of array indexing.
This change does not migrate embedders to this new embedder …
=> [Embedder API] Introduce new update semantics callback

lib/ui/window.dart
To resume the engine roller.
Reverts flutter/engine#39302
=> Revert "Deprecate SingletonFlutterWindow and global window singleton"

lib/ui/painting/image_decoder_impeller.cc
Makes the gifs/webp show up on Pixel 6 running impeller gles
=> [impeller] if not creating mipmaps dont set mip count

impeller/compiler/shader_lib/impeller/path.glsl, impeller/fixtures/cubic_to_quads.comp, impeller/fixtures/quad_polyline.comp, impeller/renderer/compute_subgroup_unittests.cc
Fixes https://github.com/flutter/flutter/issues/122828
On Intel hardware, the subgroup size is coming out as 16 for the quad shader in particular. There are, however, 26 quads to compute. The test works fine on M1 hardware where the subgroup size stays at 32 for this shader, but fails on Intel.
This change makes both the test shaders safe against smaller threadgroup sizes.
=> [Impeller] Take subgroup size into account when prefix summing

impeller/renderer/compute_subgroup_unittests.cc
Currently all the `ComputeTest` tests are run twice because the macro gets called twice with the same name. I missed this when factoring the subgroup related tests into their own TU a ways back.
This also makes it easier to filter so you run only the subgroup tests or you run all tests except subgroup tests.
=> [Impeller] Give ComputeSubgroupTest unique name to avoid running tests twice

lib/ui/window.dart
Straight reland without any changes. The fixes were done downstream in https://github.com/flutter/packages/pull/3512 and https://github.com/flutter/flutter/pull/123176.
=> Reland "Deprecate SingletonFlutterWindow and global window singleton (#39302)"

lib/ui/painting/image_decoder_impeller.cc
In https://skia-review.googlesource.com/c/skia/+/660296 we are cleaning up #includes in our core files.
As a result, we need to fix a file in Flutter which depended on transitive includes which are going away. …
=> Fix includes in image_decoder_impeller

impeller/aiks/canvas.cc, impeller/entity/entity_pass.cc, impeller/entity/entity_pass.h
Also re-enables the opacity peephole optimization by reverting https://github.com/flutter/engine/pull/40497
=> [Impeller] Share stencil coverage stack between subpasses to support pass collapsing

impeller/renderer/backend/gles/blit_command_gles.cc, impeller/renderer/backend/gles/sampler_gles.cc, impeller/renderer/backend/gles/texture_gles.cc, impeller/renderer/backend/gles/texture_gles.h, impeller/renderer/backend/metal/blit_command_mtl.mm, impeller/renderer/backend/metal/render_pass_mtl.mm, impeller/renderer/backend/metal/texture_mtl.h, impeller/renderer/backend/metal/texture_mtl.mm, impeller/renderer/backend/vulkan/blit_command_vk.cc, impeller/renderer/backend/vulkan/render_pass_vk.cc, impeller/renderer/backend/vulkan/texture_vk.cc, impeller/renderer/backend/vulkan/texture_vk.h, impeller/renderer/texture.cc, impeller/renderer/texture.h
Sampling from textures with a mip count > 1 but with no mipmaps generated is not defined by the GLES 2 spec, and drivers may either sample all zeroes in this case or other random data in the heap.
We've already run into a bug caused by not generating mipmaps. This change makes such mistakes easy to catch and prevents unsafe reading of garbage data.
=> [Impeller] Add validation for mipmap generation enforced at binding time

shell/platform/darwin/ios/framework/Source/FlutterDartProject.mm, shell/platform/darwin/ios/framework/Source/FlutterDartProjectTest.mm
This PR causes the `FLTEnableImpeller` flag to be read first out of the application bundle, and next out of the main bundle.
This is not exactly what is described in https://github.com/flutter/engine/blob/e159e35fb29ca1ca29581d4f1c5124f4abd3b29d/shell/platform/darwin/ios/framework/Source/FlutterDartProject.mm#L82 since the command line is still ignored, but I can try that in a follow-up PR.
Fixes https://github.com/flutter/flutter/issues/123046
=> Read the FLTEnableImpeller flag from the right bundle

.ci.yaml
Dart SDK does not exist in beta or stable branches. This PR will limit the execution of this build to main branch only.
Bug: https://github.com/flutter/flutter/issues/123288 …
=> Run windows_arm build only on main branch.

lib/ui/painting/image_decoder_impeller.cc
Fixes issue in application identified by @jason-simmons
=> [impeller] always copy bitmaps when given unencoded data

impeller/aiks/aiks_unittests.cc, impeller/aiks/paint_pass_delegate.cc
Fixes the rendering issues observed on the wide gamut test app (wide gamut was fine, blur was lost).
=> [impeller] dont apply opacity peephole on image/color filters

lib/ui/text/asset_manager_font_provider.cc, lib/ui/text/asset_manager_font_provider.h, third_party/txt/src/txt/asset_font_manager.cc, third_party/txt/src/txt/asset_font_manager.h, third_party/txt/src/txt/test_font_manager.cc, third_party/txt/src/txt/test_font_manager.h, third_party/txt/src/txt/typeface_font_asset_provider.cc, third_party/txt/src/txt/typeface_font_asset_provider.h
Skia is changing `SkFontMgr` and `SkFontStyleSet` methods to consistently return `sk_sp<SkTypeface>` and `sk_sp<SkFontStyleSet>` instead of `SkTypeface*` and `SkFontStyleSet*`. The pointers returned always needed to be `SkSafeUnref`ed but with `sk_sp` this ownership is now explicit.
Flutter subclasses both `SkFontMgr` and `SkFontStyleSet` and overrides affected methods. Normally Skia would roll out this change behind a build flag which would first be set in Flutter (to hold out the change), Skia then rolled into Flutter, then the build flag removed from Flutter (along with updating the subclasses). However, this is made quite difficult and slow because of the need to also be compatible with Flutter in other repositories at the same time. Instead, this change updates the subclasses to …
=> Make SkFontMgr subclasses flexible for sk_sp

impeller/entity/contents/texture_contents.cc, impeller/entity/contents/texture_contents.h, impeller/entity/entity_unittests.cc
We don't actually use the ability to use a path as the destination geometry for the texture contents. Lets remove this and simplify the implementation.
=> [Impeller] remove tessellation from texture contents

impeller/renderer/render_target.cc, lib/ui/painting/image_decoder_impeller.cc
On iOS devices that support this (apple8+), this dramatically reduces memory usage.
Wonderous after swiping through all wonders at ToT:
Wonderous after swiping through all wonders with patch:
=> [Impeller] use lossy texture compression on iOS for decode images and MSAA resolve textures.

impeller/entity/contents/runtime_effect_contents.cc, impeller/entity/contents/runtime_effect_contents.h, impeller/entity/entity_unittests.cc
Noticed while bisecting other issues.
=> [impeller] runtime effect doesnt accept opacity

shell/platform/windows/flutter_windows_engine.cc, shell/platform/windows/flutter_windows_engine_unittests.cc
This moves the Windows embedder to the new update semantics embedder API introduced by https://github.com/flutter/engine/pull/39807. This does not affect functionality hence why existing accessibility integration tests are unaffected.
Part of: https://github.com/flutter/flutter/issues/121176
See [go/flutter-semantics-abi](http://go/flutter-semantics-abi). …
=> [Windows] Use the new update semantics embedder API

shell/platform/windows/flutter_windows_engine.cc, shell/platform/windows/flutter_windows_view.cc, shell/platform/windows/flutter_windows_view_unittests.cc, shell/platform/windows/testing/mock_window_binding_handler.cc, shell/platform/windows/testing/mock_window_binding_handler.h
Reverts flutter/engine#39824
This PR appears to be responsible for the following error upon app shutdown:
[ERROR:flutter/shell/gpu/gpu_surface_gl_skia.cc(97)] Could not make the context current to destroy the GrDirectContext resources.
=> Revert "Unregister the FlutterWindowsView on its destruction"

lib/web_ui/test/canvaskit/font_variation_golden_test.dart, lib/web_ui/test/canvaskit/image_golden_test.dart, web_sdk/web_engine_tester/lib/golden_tester.dart
This fixes https://github.com/flutter/flutter/issues/121906
Skia seems to silently ignore files without an extension, so we should double-check the extension before sending the screenshot.
=> Ensure all golden filenames end in .png.

impeller/renderer/renderer_unittests.cc
This was disabled as I was investigating a write-after-write sync hazard which has already been fixed.
=> [Impeller] Enable RendererTest::TheImpeller for Vulkan.

impeller/entity/contents/atlas_contents.cc, impeller/entity/contents/atlas_contents.h
Fixes crash of `impeller_unittests --timeout=0 --gtest_filter="Play/EntityTest.DrawAtlasWithColorAdvanced/Metal"` and removes double empty states.
Fixes https://github.com/flutter/flutter/issues/122531
=> [Impeller] Fix AtlasContents crash

impeller/aiks/paint.cc, impeller/aiks/paint_pass_delegate.cc, impeller/entity/contents/clip_contents.cc, impeller/entity/contents/clip_contents.h, impeller/entity/contents/color_source_contents.cc, impeller/entity/contents/color_source_contents.h, impeller/entity/contents/conical_gradient_contents.cc, impeller/entity/contents/contents.cc, impeller/entity/contents/contents.h, impeller/entity/contents/linear_gradient_contents.cc, impeller/entity/contents/radial_gradient_contents.cc, impeller/entity/contents/runtime_effect_contents.cc, impeller/entity/contents/runtime_effect_contents.h, impeller/entity/contents/solid_color_contents.cc, impeller/entity/contents/solid_color_contents.h, impeller/entity/contents/sweep_gradient_contents.cc, impeller/entity/contents/text_contents.cc, impeller/entity/contents/text_contents.h, impeller/entity/contents/texture_contents.cc, impeller/entity/contents/texture_contents.h, impeller/entity/contents/tiled_texture_contents.cc, impeller/entity/entity_unittests.cc
EntityPasses can be rendered multiple times (i.e. as Pictures), and so the act of pushing the opacity into the collapsed entities needs to be idempotent.
`impeller_unittests --timeout=0 --gtest_filter="Play/AiksTest.CanSaveLayerStandalone/Metal"`
https://user-images.githubusercontent.com/919017/227769459-f93cb621-f040-4a86-9a46-ba0dbc925cbb.mov
Doubled up the `SetInheritedOpacity` asserts in `Play/EntityTest.InheritOpacityTest/Metal` to catch regressions.
=> [Impeller] Fix accumulating translucency opacity peephole bug

impeller/display_list/display_list_playground.cc, impeller/display_list/display_list_unittests.cc, impeller/entity/geometry.cc, impeller/entity/geometry.h
Also adds wireframe to DisplayList playgrounds. This fix follows up https://github.com/flutter/engine/pull/39481, which fixed cap disconnections for the butt cap.
Before:
https://user-images.githubusercontent.com/919017/227774962-6996c46e-0021-4911-94b8-8e5d8e803433.mov
After:
https://user-images.githubusercontent.com/919017/227774815-919f363f-bc62-4f45-b610-cc22acf66b2c.mov
=> [Impeller] Fix stroke cap disconnection

shell/platform/fuchsia/flutter/meta/common.shard.cml
Removes a forgotten reference to a no longer existing Fuchsia FIDL protocol.
See http://fxbug.dev/8895
Issue: https://github.com/flutter/flutter/issues/123370
=> Remove timezone from flutter

lib/web_ui/lib/src/engine/assets.dart, lib/web_ui/lib/src/engine/configuration.dart, lib/web_ui/lib/src/engine/initialization.dart, lib/web_ui/test/engine/assets_test.dart
Adds `assetBase` as a JS Configuration object that can be pased to initializeEngine, and warns users of the old meta-tag that they should stop doing it, and using the new style.
Adds unit tests for the `getAssetUrl` method with different configuration options.
Fixes: https://github.com/flutter/flutter/issues/122987 …
=> [web] Accepts assetBase through JS config.

lib/web_ui/lib/src/engine/canvaskit/canvaskit_api.dart
Fixes https://github.com/flutter/flutter/issues/123219
=> Return an empty JavaScript object as a replacement for exports/module in patchCanvasKitModule

shell/platform/darwin/ios/ios_surface_metal_impeller.mm
The problem was that the layer isn't configured until after the surface is created (`FlutterView` `layoutSubviews` sets up the layer)
Fixes https://github.com/flutter/flutter/issues/123550
=> [Impeller] Fix Impeller Metal wide gamut

lib/web_ui/lib/src/engine/canvaskit/canvaskit_api.dart
Reverts flutter/engine#40582
To fix possible breakage of engine roll.
=> Revert "Return an empty JavaScript object as a replacement for exports/module in patchCanvasKitModule"

impeller/golden_tests/README.md
=> Improved readme for impeller golden tests.

shell/platform/darwin/macos/framework/Headers/FlutterViewController.h
The style guide actively recommends against calling .init(). See: https://google.github.io/swift/#initializers-1
No additional tests since this is purely a style change (in a comment, no less) with no semantic effect.
Related framework change: https://github.com/flutter/flutter/pull/123571 …
=> [macOS] Eliminate explicit main window init()

impeller/aiks/aiks_unittests.cc, impeller/display_list/display_list_unittests.cc, impeller/entity/entity_pass_target.cc
Re-enables `AiksTest.CanRenderClippedLayers` and `DisplayListTest.CanDrawBackdropFilter` for Vulkan.
- Use the resolve texture descriptor when making the second texture instead of the `texture` field (this was the real bug).
- Removed the non-MSAA logic from `EntityPassTarget::Flip`, as it should only ever be called when MSAA is in use.
=> [Impeller] Fix EntityPass target flip for Vulkan

impeller/aiks/aiks_unittests.cc, impeller/renderer/backend/vulkan/allocator_vk.cc, impeller/renderer/backend/vulkan/context_vk.cc, impeller/renderer/backend/vulkan/swapchain_impl_vk.cc, impeller/renderer/backend/vulkan/texture_source_vk.cc, impeller/renderer/backend/vulkan/texture_source_vk.h, impeller/renderer/renderer_unittests.cc
`CanRenderToTexture` was letting go of the command buffer and then adding to a pass which was tripping an assertion.
=> [Impeller] Cleanup unusued Vulkan APIs and enable more tests.

web_sdk/web_test_utils/lib/image_compare.dart
At [some point](https://github.com/flutter/engine/pull/39984/commits/ba83669072b333ee987a3b88c1ff178327a3688c) in the (large) test reorganization PR, the print statements for screenshot files was put in the wrong spot, making it unreachable.
=> [web] Print screenshot paths at the right spot

DEPS
Updates the commit of ICU pulled from Chromium as a dependency. The new update includes a separate `flutter_desktop` build that includes collation data we can use for a11y purposes. This PR does not yet change the icudlt file used by desktop builds, it only updates the commit of ICU used. I intend to the above in a follow-up commit once we can be sure this can roll out.
Part of https://github.com/flutter/flutter/issues/117013 …
=> Update ICU dependency to updated build

shell/platform/darwin/macos/framework/Source/FlutterEngine.mm, shell/platform/darwin/macos/framework/Source/FlutterEngineTest.mm, shell/platform/darwin/macos/framework/Source/FlutterViewController.mm, shell/platform/darwin/macos/framework/Source/FlutterViewController_Internal.h
This moves the Windows embedder to the new update semantics embedder API introduced by https://github.com/flutter/engine/pull/39807. This does not affect functionality hence why existing accessibility integration tests are unaffected.
Part of: https://github.com/flutter/flutter/issues/121176
`FlutterSemanticsUpdate`'s ABI would break if we add new members to `FlutterSemanticNode` or `FlutterSemanticCustomAction`. As a result, these old types were "frozen" and new members should be added to the new types `FlutterSemanticUpdate2`, `FlutterSemanticNode2`, and `FlutterSemanticCustomAction2` that were introduced by https://github.com/flutter/engine/pull/39807.
For more information, see [go/flutter-semantics-abi](http://go/flutter-semantics-abi) or the background section for this issue: …
=> [macOS] Use the new update semantics embedder API

impeller/golden_tests/metal_screenshoter.mm, impeller/playground/backend/gles/playground_impl_gles.cc, impeller/playground/backend/gles/playground_impl_gles.h, impeller/playground/backend/metal/playground_impl_mtl.h, impeller/playground/backend/metal/playground_impl_mtl.mm, impeller/playground/backend/vulkan/playground_impl_vk.cc, impeller/playground/backend/vulkan/playground_impl_vk.h, impeller/playground/compute_playground_test.cc, impeller/playground/playground.cc, impeller/playground/playground.h, impeller/playground/playground_impl.cc, impeller/playground/playground_impl.h, impeller/playground/playground_test.cc, impeller/playground/playground_test.h, impeller/playground/switches.cc, impeller/playground/switches.h, impeller/renderer/backend/vulkan/capabilities_vk.cc, impeller/renderer/backend/vulkan/capabilities_vk.h, impeller/renderer/backend/vulkan/context_vk.cc, impeller/renderer/backend/vulkan/context_vk.h
The `--enable_vulkan_validation` playground flag controls this instead of needing to patch sources.
=> [Impeller] Allow toggling vulkan validation using a command line test flag.

DEPS
This is to help with the benchmark issues reported here: https://github.com/flutter/flutter/issues/123484 …
=> Roll buildroot to build CanvasKit for speed instead of code size

impeller/tools/malioc_diff.py
This PR adds a `--print-diff` option to `malioc_diff.py` to make it print a unified diff when it finds a difference. After this lands, I'll send a recipe CL to make CI pass the new flag.
=> Add an option to malioc_diff.py to print a unified diff

impeller/aiks/aiks_playground.cc, impeller/display_list/display_list_playground.cc, impeller/docs/faq.md, impeller/entity/entity_playground.cc, impeller/playground/BUILD.gn, impeller/playground/playground.cc, impeller/playground/playground.h, impeller/playground/switches.cc, impeller/playground/switches.h, impeller/tools/impeller.gni, tools/gn
Specify `--enable_playground` to `impeller_unittests` or any playground
enabled test harness.
=> [Impeller] Enable playgrounds using a runtime instead of a build time flag.

shell/platform/darwin/macos/framework/Source/FlutterEngine.mm, shell/platform/darwin/macos/framework/Source/FlutterEngineTest.mm, shell/platform/darwin/macos/framework/Source/FlutterEngine_Internal.h
issue:https://github.com/flutter/flutter/issues/99715
[Discord]: …
=> [macOS]Support SemanticsService.announce

impeller/renderer/backend/BUILD.gn
When `--enable-impeller-*` args write `impeller_enable_*` args, and so `declare_args` in `impeller.gni` are ignored and it'll always attempt to build enabled backends even if they will obviously fail.
I ran into some confusion when accidentally flipping on Vulkan for iOS: https://gist.github.com/bdero/fa11a596ece56055d50e5afecfd4d03d
=> [Impeller] Fail GN when building an enabled Impeller backend is impossible.

impeller/renderer/backend/vulkan/swapchain_impl_vk.cc
The spec says "A value of 0 means that there is no limit on the number of images" and the Radeon driver on linux seems to do this and hang the swapchain.
=> [Impeller] Handle cases where the max swapchain image count can be zero.

shell/platform/darwin/ios/framework/Source/FlutterEngine.mm, shell/platform/darwin/ios/framework/Source/FlutterEngineTest.mm, shell/platform/darwin/ios/framework/Source/FlutterTextInputDelegate.h, shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm
Reverts flutter/engine#40703
I found that since the `connectionClosed` will invoke `_finalizeEditing(TextInputAction.done, shouldUnfocus: true);`.
This will invoke onSubmit.....But actually we do expect just unfocus and do not expect any submit.. This will cause some break change. Need to have further invesigate to reland
=> Revert "[iOS] Send connectionClosed message when resignFirstResponder to ensure framework focus state is correct."

impeller/renderer/backend/vulkan/context_vk.cc
On some devices (for example an Android Pixel 4), a dedicated transfer queue is not available. This should not be considered a fatal error - instead we should use the graphics queue for transfer.
Fixes https://github.com/flutter/flutter/issues/123791
=> [Impeller] Fallback to graphics queue is transfer queue is not available

impeller/compiler/shader_lib/impeller/gaussian.glsl, impeller/compiler/shader_lib/impeller/texture.glsl, impeller/entity/shaders/border_mask_blur.frag, impeller/entity/shaders/border_mask_blur.vert, impeller/entity/shaders/gaussian_blur/gaussian_blur.glsl, impeller/entity/shaders/gaussian_blur/gaussian_blur.vert, impeller/entity/shaders/rrect_blur.frag, impeller/entity/shaders/rrect_blur.vert, impeller/tools/malioc.json
Reverts flutter/engine#40752
This was flagged as regressing raster time performance. needs investigation: https://flutter-flutter-perf.skia.org/e/?begin=1680120153&end=1680150908&keys=X4bde3c482cac430b6985776abb5b2b5d&selected=commit%3D34067%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DiPhone_11%252Cdevice_version%253Dnone%252Chost_type%253Dmac%252Csub_result%253Daverage_frame_rasterizer_time_millis%252Ctest%253Dbackdrop_filter_perf_impeller_ios__timeline_summary%252C&xbaroffset=34067
Potentially something is going wrong with the sampling and/or we're converting too much? Not sure yet.
=> Revert "[Impeller] migrate Gaussian shaders to half precision."

lib/web_ui/lib/src/engine/browser_detection.dart, lib/web_ui/lib/src/engine/canvaskit/text.dart, lib/web_ui/lib/src/engine/canvaskit/text_fragmenter.dart, lib/web_ui/lib/src/engine/util.dart, lib/web_ui/test/canvaskit/text_fragmenter_test.dart, lib/web_ui/test/engine/browser_detect_test.dart, lib/web_ui/test/engine/lru_cache_test.dart
There are a few changes in this PR:
1. Implement an LRU cache for text segmentation results to improve layout operations on repetitive paragraphs (thanks @yjbanov for the initial implementation of the cache).
2. Invoke `ParagraphBuilder.RequiresClientICU()` only once and cache the result.
3. Remove the image codecs check from `browserSupportsCanvaskitChromium`.
=> [web] LRU cache for text segmentation

impeller/compiler/compiler.cc
This somehow seems to have regressed OpenGLES on Android. We can figure out what's going on later.
=> [Impeller] Go back to using MSL compiler backend for Vulkan

lib/ui/semantics.dart, lib/web_ui/lib/semantics.dart
Add temporary API.
cc @chunhtai 
part of https://github.com/flutter/flutter/issues/123346
Steps:
**part 1: [engine] add `valuesAsList`** <-- we are here
part 2: [flutter] use `valuesAsList`
part 3: [engine] convert to enum
part 4: [flutter] use `values` again.
part 5: [engine] remove valuesAsList.
part 6: [flutter] deprecate describeEnum.
=> `SemanticsFlag`/`SemanticsAction` enum migration (part 1)

impeller/entity/entity_pass.cc
Resolves https://github.com/flutter/flutter/issues/123789
=> [Impeller] Always create at least one RenderPass if the clear color has been overridden

shell/platform/fuchsia/runtime/dart/utils/handle_exception.cc
Migrate from the deprecated `fuchsia.feedback/CrashReporter::File` to `fuchsia.feedback/CrashReporter::FileReport`. `FileReport` provides a status once Feedback has finished filing the report, rather than as soon as Feedback has received the request.
Bug: fxbug.dev/122421
=> [fuchsia] Feedback filing migration

display_list/benchmarking/dl_benchmarks.cc, display_list/benchmarking/dl_complexity_unittests.cc, flow/paint_utils.cc, lib/ui/painting/display_list_deferred_image_gpu_skia.cc, lib/ui/painting/image_decoder_skia.cc, lib/ui/painting/image_decoder_unittests.cc, lib/ui/painting/image_encoding_impeller.cc, lib/ui/painting/image_generator.cc, lib/ui/painting/multi_frame_codec.cc, shell/common/serialization_callbacks.cc, shell/platform/android/android_external_texture_gl.cc, shell/platform/darwin/graphics/FlutterDarwinExternalTextureMetal.mm, shell/platform/embedder/embedder_external_texture_gl.cc, shell/platform/embedder/tests/embedder_config_builder.cc, shell/platform/embedder/tests/embedder_unittests_util.cc
In https://skia-review.googlesource.com/c/skia/+/661059, Skia added a new SkImages namespace and deprecated using static functions on SkImage as part of an effort to separate the SkImage class and the GPU backends.
This PR replaces all old calls with the new calls, which should be functionally the same. It makes sure `SkImage.h` and `SkImageGanesh.h` are #included where appropriate. …
=> Use new SkImages namespace instead of legacy SkImage static functions

impeller/compiler/reflector.cc
This got missed in https://github.com/flutter/engine/pull/35166
=> [Impeller] Delete dead code from reflector.cc

impeller/renderer/backend/metal/command_buffer_mtl.mm, impeller/renderer/backend/metal/context_mtl.h, impeller/renderer/backend/metal/context_mtl.mm, impeller/renderer/backend/metal/surface_mtl.h, impeller/renderer/backend/metal/surface_mtl.mm
edit: This was updated to just wait for scheduling in a new command buffer. Similar to how we already do in the macOS embedder, but better because we don't even block on the current thread thanks to presentDrawable.
This patch makes us conform to the docs and sync properly for the drawable present, and gets rid of the excessive `waitUntilScheduled` blocking on iOS sim. Tested on iPhone 12, iPhone 6s, and x64 sim.
Open to ideas for better architecting this. Waiting for the last committed command buffer to be scheduled is the same as waiting for _all_ previously committed command buffers to be scheduled. Command buffers are scheduled in queue order. 
Explanation:
Sleuthing through the Metal docs for all the calls we're making, I found one thing that's unsafe about not doing …
=> [Impeller] iOS/macOS: Only wait for command scheduling prior to present

impeller/aiks/aiks_unittests.cc
This test ends up with small differences depending on which mac host it runs on and will end up blocking rollers.
=> [Impeller] Skip TextRotated golden test.

shell/platform/common/accessibility_bridge.cc, shell/platform/common/accessibility_bridge.h, shell/platform/common/accessibility_bridge_unittests.cc, shell/platform/common/flutter_platform_node_delegate_unittests.cc, shell/platform/darwin/macos/framework/Source/AccessibilityBridgeMacTest.mm, shell/platform/darwin/macos/framework/Source/FlutterPlatformNodeDelegateMacTest.mm, shell/platform/windows/accessibility_bridge_windows_unittests.cc, shell/platform/windows/flutter_windows_view_unittests.cc
The old "update semantics" embedder API was deprecated as it could not guarantee ABI stability (see https://github.com/flutter/flutter/issues/121176). It was replaced by a new embedder API (https://github.com/flutter/engine/pull/39807) and all affected embedders were migrated to this new embedder API (https://github.com/flutter/engine/pull/40072, https://github.com/flutter/engine/pull/40584).
This change:
1. Removes plumbing that was used for the old "update semantics" embedder API
2. Moves all remaining tests to the types used by the new "update semantics" embedder API
Completes: https://github.com/flutter/flutter/issues/121176 …
=> Complete the update semantics embedder API migration

lib/ui/platform_dispatcher.dart, lib/ui/pointer.dart, lib/ui/window/pointer_data.h, lib/web_ui/lib/pointer.dart, shell/platform/android/io/flutter/embedding/android/AndroidTouchProcessor.java, shell/platform/darwin/macos/framework/Headers/FlutterEngine.h, shell/platform/darwin/macos/framework/Headers/FlutterPluginRegistrarMacOS.h, shell/platform/darwin/macos/framework/Headers/FlutterViewController.h, shell/platform/darwin/macos/framework/Source/FlutterCompositor.h, shell/platform/darwin/macos/framework/Source/FlutterCompositor.mm, shell/platform/darwin/macos/framework/Source/FlutterCompositorTest.mm, shell/platform/darwin/macos/framework/Source/FlutterEngine.mm, shell/platform/darwin/macos/framework/Source/FlutterEngineTest.mm, shell/platform/darwin/macos/framework/Source/FlutterEngine_Internal.h, shell/platform/darwin/macos/framework/Source/FlutterPlatformNodeDelegateMacTest.mm, shell/platform/darwin/macos/framework/Source/FlutterRenderer.h, shell/platform/darwin/macos/framework/Source/FlutterRenderer.mm, shell/platform/darwin/macos/framework/Source/FlutterViewController.mm, shell/platform/darwin/macos/framework/Source/FlutterViewController_Internal.h, shell/platform/darwin/macos/framework/Source/FlutterViewEngineProvider.mm, shell/platform/darwin/macos/framework/Source/FlutterViewEngineProviderTest.mm, shell/platform/darwin/macos/framework/Source/FlutterViewProvider.h
Reverts flutter/engine#39958
Failing the roll to the framework starting with https://github.com/flutter/flutter/pull/123893
One example: https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20dart_plugin_registry_test/21819/overview
=> Revert "[macOS] Change view ID to signed"

lib/web_ui/lib/src/engine/canvaskit/canvaskit_api.dart, lib/web_ui/lib/src/engine/canvaskit/native_memory.dart, lib/web_ui/test/canvaskit/canvaskit_api_test.dart
Use `js_util.callConstructor` to initialize `FinalizationRegistry` to make it compatible with `dart2js`.
Fixes b/276167870
=> [web] use callConstructor for FinalizationRegistry due to bug in dart2js

lib/web_ui/test/canvaskit/canvaskit_api_test.dart
Right now we only check for `v8BreakIterator` and we don't check `ImageDecoder` support. So some tests need to be updated.
=> [web] Fix canvasKitVariant test

sky/packages/sky_engine/BUILD.gn
Reverts flutter/engine#40827
This is causing the engine -> framework roll to fail in docs generation
=> Revert "Add ui_web to embedder.yaml so that the analyzer knows about it."

impeller/entity/contents/filters/blend_filter_contents.cc, impeller/entity/contents/framebuffer_blend_contents.cc, impeller/entity/shaders/blending/advanced_blend.glsl, impeller/entity/shaders/blending/blend.frag, impeller/entity/shaders/blending/blend.vert, impeller/entity/shaders/blending/ios/framebuffer_blend.glsl, impeller/tools/malioc.json
* In advanced blend shaders, use native decal sampling where available.
* In framebuffer blend shaders always use native decal sampling.
* Adjust blend.frag to do texture flip computation in vertex shader like other samplers, remove tessellation usage in favor of Rect geometry.
=> [Impeller] take advantage of native decal sampling, blend cleanups

lib/web_ui/lib/src/engine/embedder.dart, lib/web_ui/lib/src/engine/host_node.dart, lib/web_ui/lib/src/engine/platform_dispatcher.dart, lib/web_ui/lib/src/engine/platform_views/content_manager.dart, lib/web_ui/lib/src/engine/pointer_binding/event_position_helper.dart, lib/web_ui/lib/src/engine/semantics/text_field.dart, lib/web_ui/lib/src/engine/text_editing/text_editing.dart, lib/web_ui/test/engine/host_node_test.dart, lib/web_ui/test/engine/semantics/semantics_test.dart, lib/web_ui/test/engine/semantics/semantics_tester.dart, lib/web_ui/test/engine/semantics/text_field_test.dart, lib/web_ui/test/engine/text_editing_test.dart
Reverts flutter/engine#39688
Looks like this is causing the roll to the framework to fail. See https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20web_long_running_tests_4_5/34083/overview
```
00:03 [32m+1[0m[31m -1[0m: Hello World App enable accessibility [1m[31m[E][0m[0m
JavaScriptException (500): javascript error: Cannot read properties of null (reading 'querySelector')
(Session info: headless chrome=96.0.4664.0)
package:webdriver/src/handler/w3c/utils.dart 57:9       parseW3cResponse
package:webdriver/src/handler/w3c/core.dart 59:19       W3cCoreHandler.parseExecuteResponse
package:webdriver/src/async/web_driver.dart 260:37      WebDriver.execute.<fn>
package:webdriver/src/common/request_client.dart 96:32  AsyncRequestClient.send
===== asynchronous gap …
```
=> Revert "[web] Move text editing nodes outside of shadowDOM"

impeller/compiler/compiler.cc
This makes the generated metadata for all backends interchangeable. The Metal backends don't use the this offset at all so it doesn't matter.
This unblocks macOS Vulkan builds.
=> [Impeller] Apply binding base correction to all shader variants.

impeller/base/validation.cc, impeller/base/validation.h, impeller/playground/playground_test.cc
They will still be fatal in tests and no logs will show up in release.
Fixes https://github.com/flutter/flutter/issues/123884
In fixing the linked issue, I didn't want to risk us having a stray validation log tear down the release process. This is safer and gets us the information we need during development.
=> [Impeller] Make validation logs non-fatal by default.

impeller/compiler/compiler.cc, impeller/compiler/compiler_test.cc, impeller/compiler/impellerc_main.cc, impeller/compiler/switches.cc, impeller/compiler/types.cc, impeller/compiler/types.h
TargetPlatformNeedsSL was true for all target platforms.
I believe we reworked this after we started embedding metadata in IPLR files perhaps? In any case, this seemed unused and was making the code harder to read. Just a cleanup that I didn't want to include in the compiler rework for SPIRV.
=> [Impeller] Remove redundant TargetPlatformNeedsSL.

shell/platform/linux/fl_texture_registrar.cc, shell/platform/linux/fl_texture_registrar_private.h, shell/platform/linux/fl_texture_registrar_test.cc
We've encountered some memory corruption when developing `RustDesk`, which is an open-source remote desktop built with Flutter, and it uses the texture API provided by Flutter to provide the remote screen to clients.
Both Windows and macOS work well, except for Linux. Sometimes random crashes will show and print **different** stack traces in these conditions:
- after registering a new texture
- preparing a RGBA data and `markAvaliable`
The runtime often complains `double free or corruption`.
One of the stack traces using lldb-10:
We checked the implementation of calling textures API on Linux several times, but have no luck. 
We've noticed that on Linux, textures are organized by `g_hash_table`, which is not the thread-safe hashtable and we should ensure synchronization on different …
=> [Linux] fix: make textures thread-safe on linux

ci/licenses_golden/licenses_flutter, impeller/compiler/BUILD.gn, impeller/compiler/compiler.cc, impeller/compiler/compiler.h, impeller/compiler/compiler_test.cc, impeller/compiler/impellerc_main.cc, impeller/compiler/logger.h, impeller/compiler/spirv_compiler.cc, impeller/compiler/spirv_compiler.h
We just used to use the output of Stage 1 for Vulkan since it was already SPIRV. But that contained debugging information that bloated the size of the SPIRV and the resulting binaries. This reworks the compiler to add a second stage that strips the debug information.
While stripping the debug information is effectively what happens, I couldn't find an existing utility in the compiler toolbox that does this. So the source files are processed again for stage 2, but this time without generating the debug information.
Just a rudimentary size analysis of the generated SPIRV shows that just gathering all generated shaders in the out directory and applying GZip compression yields a 2.58x size reduction with the total size of all generated shaders being about ~48k. This bring the packaged shader …
=> [Impeller] Add a Stage 2 pass to the Vulkan shader compilation pipeline.

lib/ui/painting/image_decoder_impeller.cc
Fixes https://github.com/flutter/flutter/issues/123027.
Turns out, this isn't an issue with backgrounding. This can only happen if the IO manager is torn down before worker pool has had a chance to process the decompression job, or if the UI manager was never setup. It is hard to imaging how this could happen in a real application. If it does though, we should not crash. This patch makes the change to return an error instead. The linked issue was a test environment and the failure was addressed in https://github.com/flutter/engine/pull/40535.
=> [Impeller] Don't crash in image decompression if the context is unavailable.

impeller/renderer/backend/metal/command_buffer_mtl.mm, impeller/renderer/backend/metal/context_mtl.h, impeller/renderer/backend/metal/context_mtl.mm, impeller/renderer/backend/metal/surface_mtl.h, impeller/renderer/backend/metal/surface_mtl.mm
Reverts flutter/engine#40781
Fixes https://github.com/flutter/flutter/issues/124056
When unmerging threads we appear to get stuck for multiple seconds. Haven't debugged further, but bisected to this commit.
=> Revert "[Impeller] iOS/macOS: Only wait for command scheduling prior to present"

impeller/aiks/aiks_unittests.cc, impeller/geometry/color.cc, impeller/geometry/color.h
Adds a checked macro "loop" for the blend modes in the style of `FOR_EACH_DISPLAY_LIST_OP` + a quick golden for each blend mode that runs the `EntityPass` subpass blending paths.
We should also add Aiks tests to verify the filters in a more comprehensive way (including the blend filter). I can do this in a follow-up. The BlendFilter actually uses different shaders than SaveLayer for the advanced blends on Metal -- the two code paths are wildly different, and we've had serious regressions for both cases.
https://user-images.githubusercontent.com/919017/229463806-c3f20baf-f379-4d14-999b-aab3aec188d7.mov
=> [Impeller] Add subpass blend goldens

ci/licenses_golden/licenses_flutter, impeller/entity/BUILD.gn, impeller/entity/contents/filters/blend_filter_contents.cc, impeller/entity/contents/foreground_blend_contents.cc, impeller/entity/contents/foreground_blend_contents.h, impeller/entity/entity_unittests.cc
Work towards https://github.com/flutter/flutter/issues/124025
This makes Advanced Blends applied via ColorFiltered take one fewer subpass, and Advanced Blends applied directly to contents (via Paint) take no extra subpasses at all.
To test this, I used the flutter codelabs nextgen UI app. Though this uses a ColorFiltered with a pipeline blend, I changed to using ColorDodge to experiment with the costs of the advanced blend filters. While this reduces the number of subpasses significantly, it only has a minor impact on overall performance.
=> [Impeller] reduce advanced blend subpass count for single input with foreground color

shell/platform/android/android_egl_surface.cc
Minimal change to disable partial repaint on Android.
https://github.com/flutter/flutter/issues/123353
=> Disable partial repaint on Android

impeller/entity/contents/filters/gaussian_blur_filter_contents.cc, impeller/entity/shaders/gaussian_blur/gaussian_blur.glsl, impeller/tools/malioc.json
Uses technique outlined in https://rastergrid.com/blog/2010/09/efficient-gaussian-blur-with-linear-sampling to reduce number of texture samples by 2x. Rather than sampling each texture element with nearest neighbor, sample a lerp'd weighted value that should be identical to the previous measure.
* Iteration now works from 0 to radius instead of -radius to radius. This allows reuse of the gaussian integral computation since the function is symmetric. Also solves problem where we'd sometimes chop off one end of the iteration (because we started at some value like -9.33 -> 8.33 (because rounding took us up to 9.4 something)
From local testing on an iPhone 13, this is about ~50% faster on the backdropfilter stress test, though no major difference on the animated backdrop filter benchmark as …
=> [Impeller] reduce gaussian sampling by 2x

shell/common/switches_unittests.cc, shell/platform/darwin/common/command_line.h, shell/platform/darwin/common/command_line.mm, shell/platform/darwin/ios/framework/Source/FlutterDartProject.mm, shell/platform/darwin/ios/framework/Source/FlutterDartProjectTest.mm, shell/platform/darwin/ios/framework/Source/FlutterDartProject_Internal.h
This way developers get what they ask for regardless of what they ship to their users.
I think we should probably do this for all settings, but will hold off on that and filed https://github.com/flutter/flutter/issues/124049 to track.
=> [Impeller] Respect enable-impeller command line setting over info.plist setting

shell/platform/linux/fl_texture_registrar.cc, shell/platform/linux/fl_texture_registrar_test.cc
This stops a regression in code that uses the original method.
Once all new code uses fl_texture_get_id, we could re-enable the more predictable incremental texture IDs.
Fixes https://github.com/flutter/flutter/issues/124009
=> Change back to using the memory address of a texture as its ID.

tools/gn
This isn't really foolproof, but would catch some simple mistakes.
I mistakenly tried to build an arm64 simulator build by doing `./flutter/tools/gn --simulator --unopt --mac-cpu=arm64`. It generated the expected out directory (out/ios_debug_sim_unopt_arm64), but did not set the gn arguments for the simulator build and resulted in linker errors down the line.
Also deletes an otherwise unused function.
fixes https://github.com/flutter/flutter/issues/124067
=> Exit early on invalid gn CPU argument combos for simulators

impeller/aiks/canvas.cc
Fixes https://github.com/flutter/flutter/issues/123834
=> [Impeller] Emulate Skia's SK_LEGACY_IGNORE_DRAW_VERTICES_BLEND_WITH_NO_SHADER in drawVertices

impeller/renderer/pipeline_builder.h, impeller/renderer/vertex_descriptor.cc, impeller/renderer/vertex_descriptor.h
`SetRegisterDescriptorSetLayouts` made it seem like the old setting was replaced. All this call does add new descriptor set registrations.
=> [Impeller] Update API name to indicate descriptor set registrations.

sky/packages/sky_engine/BUILD.gn, sky/packages/sky_engine/lib/_embedder.yaml
The dart sdk is trying to remove this library from public API. We should not include it in sky_engine.
=> The `dart:wasm` library is no longer used directly by user code.

shell/platform/fuchsia/flutter/flatland_connection.cc, shell/platform/fuchsia/flutter/flatland_connection.h
This CL renames params and adds comments to FlatlandConnection to clarify behavior.
Bug: fxb/123838
=> [fuchsia] Rename params and add comments to FlatlandConnection

third_party/canvaskit/BUILD.gn, web_sdk/BUILD.gn
Since the flutter tool now always looks inside the `flutter_web_sdk` artifact for canvaskit/skwasm files, we should copy them to their expected location inside the flutter_web_sdk, so that `--local-web-sdk` works correctly when targeting a local build.
=> Copy canvaskit files directly into `flutter_web_sdk`

impeller/toolkit/egl/display.cc, shell/platform/android/android_surface_gl_impeller.cc
I reviewed the code and I don't think this requirement is necessary.  Offscreen MSAA is already guarded by a flag and looking at the opengles code it doesn't seem to be using multisample buffers.
When removing it the emulator no longer crashes and behaves identically to on device (which is rendering incorrect colors and crashing when pressing a the counter button).
fixes https://github.com/flutter/flutter/issues/105323 …
=> [Impeller] Removed requirement for multisample buffers from egl setup.

web_sdk/BUILD.gn
The HHH bot and dart monorepo still build the web archive in a host build. We can't build wasm artifacts in this mode, so just skip them.
=> Don't build wasm targets for the web sdk archive in host mode.

impeller/entity/shaders/gaussian_blur/gaussian_blur.glsl, impeller/tools/malioc.json
Follow-up to remove the second gaussian sample, which isn't really improving quality.
For both before and after, I don't think we're sampling from the center of texels, and this is causing textures with high frequency info to "ripple" a bit when slowly increasing the blur radius (another issue might be that our texture downsizing is, again, too aggressive too early). I'm currently working out the best way to fix this and may follow-up with something.
=> [Impeller] Sample the gaussian function once per texture sample

common/config.gni, fml/BUILD.gn, tools/gn
This adds a gn flag (--backtrace, --no-backtrace) that defaults to enabling backtraces, which drives a gn variable `enable_backtrace` which is defaulted true for debug builds.
Backtrace collection is supported on Windows, and on POSIX-like operating systems via execinfo.h. execinfo support exists in Android, macOS/iOS, and in glibc and uclibc on Linux. musl libc notably does not include execinfo support, so this provides an escape hatch to build with backtrace_stub.cc for situations in which compile time support doesn't exist.
Proposed as an alternative to
https://github.com/flutter/engine/pull/40958 by @selfisekai.
Issue: https://github.com/flutter/flutter/issues/124285 …
=> Support disabling backtrace support

shell/platform/darwin/ios/framework/Source/FlutterViewController.mm, shell/platform/darwin/ios/framework/Source/FlutterViewControllerTest.mm
Fixes https://github.com/flutter/flutter/issues/124288
[Discord]: …
=> Fix UIWindowSceneGeometryPreferencesIOS leak

shell/platform/fuchsia/flutter/BUILD.gn, shell/platform/fuchsia/flutter/engine.cc, shell/platform/fuchsia/flutter/engine.h, shell/platform/fuchsia/flutter/meta/common.shard.cml
Implement thread priorities using the Fuchsia media profile provider API to enable system / product configuration of host threads.
This change helps to address b/275114261.
=> [Fuchsia] Implement thread priorities.

shell/platform/embedder/tests/embedder_a11y_unittests.cc
No semantic change. This just simplifies converting Dart arguments to C++ types, making it more consistent with the rest of the codebase. …
=> [a11y] Use DartConverter for embedder a11y tests

shell/platform/embedder/fixtures/main.dart, shell/platform/embedder/tests/embedder_a11y_unittests.cc
Applies cleanup/simplification to EmbedderA11yTest unit tests.
* Add numbered breadcrumbs to identify corresponding sections of the C++ and Dart fixture tests.
* Eliminates duplicated native method implementations for notifying:
* whether semantics is enabled
* whether a particular accessibility feature is enabled
* which semantics action was fired
[testing the …
=> [a11y] Improve EmbedderA11yTest, fixture comments

runtime/runtime_controller.cc
Since both android and ios use `SetViewportMetrics` to update the `MediaQuery` in framework side to implement keyboard animation. So adding this trace is better for debugging workflow.
=> Add trace event when updating ViewportMetrics

impeller/aiks/aiks_unittests.cc, impeller/golden_tests/golden_playground_test_mac.cc
Adds a series of goldens that apply a filter to a translated and rotated rectangle to verify that the math in https://github.com/flutter/engine/pull/40973 and https://github.com/flutter/engine/pull/40927 are correct
=> [Impeller] add goldens for filter optimizations.

impeller/playground/playground.cc
Generally this is fine to do regardless of whether or not we're on UMA . However I never finished https://github.com/flutter/flutter/issues/123468 so it will only work on metal.
I don't think we have a way to runtime check if metal, so I added an ifdef for macos. Im not sure if we have vulkan on macos tests on CI, so lets find out.
Fixes https://github.com/flutter/flutter/issues/124428
=> [Impeller] playground upload to device private on macOS

shell/platform/darwin/ios/framework/Source/FlutterEngine.mm, shell/platform/darwin/ios/framework/Source/FlutterEngineTest.mm, shell/platform/darwin/ios/framework/Source/FlutterTextInputDelegate.h, shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm
This is to reland the PR that has been reverted because the framework side is not ready at that time.
- https://github.com/flutter/engine/pull/40703
Now we have merge the pr to let framework behave as expected.
- https://github.com/flutter/flutter/pull/123929
So just reland this.
The code is identical with the original PR
=> Reland [iOS] Send connectionClosed message when resignFirstResponder to ensure framework focus state is correct.

lib/ui/platform_dispatcher.dart, lib/ui/semantics.dart, lib/web_ui/lib/semantics.dart, lib/web_ui/test/engine/semantics/semantics_api_test.dart, testing/dart/semantics_test.dart
These two classes should be an enum, because they work as enum, but they are older than the enhanced enum, so this wasn't possible before. Now it is.
This is kind of breaking because Flutter uses `semanticsFlag.values.values`, but I searched on code search and couldn't find a repo that uses that, so it seems really internal. 
We could do in these ways:
- Add `deserialize`/`indexAt`/`[]` on them, migrate Flutter, convert to enum;
- Convert to enum and land the Flutter change at the same time (is this possible?);
- Don't do anything, lol
=> `SemanticsFlag`/`SemanticsAction` cleanup (part 3)

.ci.yaml
The current execution timeout is set to 30 mins which is not enough for builds running on staging. They usually wait more than 30m in the queue. …
=> Update the timeout to 3h for mac build in staging.

impeller/entity/inline_pass_context.cc, impeller/entity/inline_pass_context.h
Reverts flutter/engine#40436
I believe https://github.com/flutter/engine/pull/41052 fixes the actual problem that was occurring here when the Flip use is present. According to @jason-simmons, this change is actually breaking the Cupertino picker in gallery.
I'm not sure why this is broken in GLES yet. There should be no problem "loading" (doing nothing in GLES) to prepare continued writes to single sample textures when we begin the next pass.
=> Revert "[Impeller] Load instead of restore drawing for non-MSAA passes"

impeller/entity/entity_pass.cc
The texture may change during rendering due to operations such as EntityPassTarget::Flip
=> [Impeller] Obtain the subpass texture after calling OnRender

flow/skia_gpu_object.h, shell/common/shell_io_manager.cc
Using the unref queue can cause frame drops: https://github.com/flutter/flutter/issues/122634
While this does not remove it altogether, it does completely avoid the delayed scheduling and instead immediately unrefs any objects given.
We do not use the texture functionality of unref queue with Impeller.
=> [Impeller] remove unref queue usage on Impeller.

.ci.yaml
Mac_unopt is ready to replace Mac Unopt build. This change promotes the engine v2 build to use prod resources and moves the legacy Mac Unopt to staging.
Note: the failures in staging are related to lack of mac resources on staging to run successfully.
[CLA]: …
=> Promote mac_unopt to prod.

.ci.yaml, ci/builders/mac_ios_engine.json
Reverts flutter/engine#40844
We suspect this may be the cause of https://github.com/flutter/flutter/issues/124572
=> Revert "Migrate ios_builders to engine_v2."

shell/platform/darwin/ios/ios_surface_metal_impeller.mm, shell/platform/darwin/ios/ios_surface_metal_skia.mm
Resolves https://github.com/flutter/flutter/issues/124612.
Doing this would also allow us to remove the final blit on iOS when advanced blends/backdrop filters are present (all of the facilities would remain in place for GLES + Vulkan though).
=> [Impeller] Make Metal layers readable

sky/tools/create_full_ios_framework.py
The arm_64 Flutter binary was not stripping symbols correctly. This PR ensures the binary is stripped before creating the frameworks.
Bug: https://github.com/flutter/flutter/issues/124572 …
=> Fixes to strip symbols correctly.

impeller/renderer/backend/gles/blit_pass_gles.cc, impeller/renderer/backend/gles/blit_pass_gles.h
Without this the BlitPassGLES and its command list can be destructed before the reactor executes the lambda.
=> [Impeller] Keep a reference to BlitPassGLES in the EncodeCommands lambda to prevent use-after-free

DEPS
To pick up https://github.com/flutter/buildroot/commit/48f8487897b7f40e2744c808694535478d06ca47
=> Roll buildroot to 48f8487897b7f40e2744c808694535478d06ca47

shell/platform/windows/angle_surface_manager.h, shell/platform/windows/flutter_windows_engine.h, shell/platform/windows/flutter_windows_view.cc, shell/platform/windows/flutter_windows_view_unittests.cc
Currently, closing the window does the following:
1. The `FlutterWindowsView` [destroys its surface](https://github.com/flutter/engine/blob/df5e055f6aba457f8bee607c9dabccfcff15726c/shell/platform/windows/flutter_windows_view.cc#L52)
2. The `FlutterWindowsView` [destroys the `FlutterWindowsEngine` it owns](https://github.com/flutter/engine/blob/df5e055f6aba457f8bee607c9dabccfcff15726c/shell/platform/windows/flutter_windows_view.h#L349)
3. The `FlutterWindowsEngine` shuts down the real engine ([1](https://github.com/flutter/engine/blob/df5e055f6aba457f8bee607c9dabccfcff15726c/shell/platform/windows/flutter_windows_engine.cc#L234), [2](https://github.com/flutter/engine/blob/df5e055f6aba457f8bee607c9dabccfcff15726c/shell/platform/windows/flutter_windows_engine.cc#L410))
As a result, the …
=> [Windows] Shutdown the engine before destroying the surface

lib/ui/semantics.dart, lib/web_ui/lib/semantics.dart
Final part of https://github.com/flutter/flutter/issues/123346 (before deprecating describeEnum)
Remove temporary variables.
=> `SemanticsAction` / `SemanticsFlag` cleanup part 5

impeller/entity/entity_pass.cc, impeller/renderer/backend/gles/context_gles.cc, impeller/renderer/backend/metal/context_mtl.mm, impeller/renderer/backend/vulkan/capabilities_vk.cc, impeller/renderer/backend/vulkan/capabilities_vk.h, impeller/renderer/capabilities.cc, impeller/renderer/capabilities.h
Removes the "final blit" for Metal because https://github.com/flutter/engine/pull/41085 allows us to read from the onscreen texture.
We can't do this trick when running the Vulkan backend right now because it doesn't have `SupportsReadFromResolve` yet, which means we need to toggle between two textures.
=> [Impeller] Metal: Read from onscreen textures

shell/platform/fuchsia/flutter/flatland_platform_view.cc
This CL changes ERROR to WARNING for the logs when a child disconnects and ChildViewWatcher is closed. This may happen due to other apps and doesn't necessarily indicate a flutter error. 
Bug:fxb/125256
=> [fuchsia] Reduce noise from child view disconnects

lib/web_ui/lib/src/engine/safe_browser_api.dart, lib/web_ui/test/engine/browser_detect_test.dart
This fixes https://github.com/flutter/flutter/issues/124726
Safari 16.4 adds OffscreenCanvas support, but only for 2D rendering. We basically only use `OffscreenCanvas` for WebGL rendering, so we shouldn't consider it "supported".
=> Don't use `OffscreenCanvas` in Safari, it doesn't support WebGL.

impeller/aiks/aiks_unittests.cc, impeller/entity/entity_pass.cc
Resolves https://github.com/flutter/flutter/issues/124658.
Need to add error messages around all failed scenarios in EntityPass since we don't have a recovery and the whole frame fails to render. Will CP this.
Before: Failed rendering.
After:
=> [Impeller] Check coverage after screen clip

lib/web_ui/lib/src/engine/canvaskit/native_memory.dart, lib/web_ui/lib/src/engine/canvaskit/path.dart, lib/web_ui/lib/src/engine/canvaskit/path_metrics.dart, lib/web_ui/test/canvaskit/path_test.dart
Moves all path API (`Path`, `PathMetrics`) from `ManagedSkiaObject` to `UniqueRef`, and clean up all the dead resurrection logic since all browsers support `FinalizationRegistry`.
This is a follow-up to https://github.com/flutter/engine/pull/40862
=> [web:canvaskit] move path API to UniqueRef

ci/builders/mac_host_engine.json, ci/builders/mac_unopt.json
fixes https://github.com/flutter/flutter/issues/124678
those machines do not support compute subgroups. They make up only a relatively small fraction of the pool.
This does not restrict the arm machines, as they're already restricted by the cpu architecture dimension.
=> Do not use Macmini7,1 for host tests

shell/platform/fuchsia/flutter/component_v2.cc, shell/platform/fuchsia/flutter/component_v2.h, shell/platform/fuchsia/flutter/tests/integration/embedder/parent-view/lib/parent_view.dart, shell/platform/fuchsia/flutter/tests/integration/touch-input/embedding-flutter-view/lib/embedding-flutter-view.dart
Prepare Flutter's Fuchsia port for removal of the fuchsia.ui.app.ViewProvider.CreateView() API.
The Flutter engine's implementation of the API, which has long been deprecated, is removed.
Calls to the deprecated CreateView() in tests are replaced with CreateViewWithViewRef().
Bug fxbug.dev/81285
=> [fuchsia] Remove implementations & clients of deprecated CreateView

lib/web_ui/lib/src/engine/skwasm/skwasm_impl/raw/raw_canvas.dart, lib/web_ui/test/ui/canvas_curves_golden_test.dart
The @Native declaration of skwasm's canvasDrawArc was flubbed due to a copy-pasta issue. Fix that and write unit tests that validate that code path (plus a few others).
=> Fix skwasm's canvasDrawArc declaration and write tests.

impeller/entity/entity_pass.cc, impeller/entity/entity_pass_target.cc, impeller/entity/inline_pass_context.cc
This eliminates a lot of surface area when debugging non-recoverable frame failures such as https://github.com/flutter/engine/pull/41129. Every failure case should be covered with at least one log, but without recursive log spam.
=> [Impeller] Print a log on all non-recoverable failure paths in EntityPass

lib/web_ui/lib/src/engine/canvaskit/painting.dart, lib/web_ui/lib/src/engine/canvaskit/shader.dart, lib/web_ui/test/canvaskit/fragment_program_test.dart, lib/web_ui/test/canvaskit/shader_test.dart
Move all classes implementing the `Shader` interface from `ManagedSkiaObject` to `UniqueRef`.
Fix two (probably minor) memory leaks:
* `CkImageShader` was leaking intermediate instances of `SkShader` because those were neither attached to a `FinalizationRegistry`, nor disposed of explicitly through the `dispose()` method.
* `CkFragmentShader` was leaking `SkShader` instances because it never called `CkFragmentInstance.dispose`. Additionally, the `CkFragmentInstance` class isn't really necessary, because `UniqueRef` is fully sufficient to manage instances of `SkShader` objects for fragment shaders.
=> [web:canvaskit] move shaders to UniqueRef; fix minor memory leaks

ci/builders/mac_host_engine.json
This target also runs impeller_unittests that aren't safe to run right now on Macmini7,1
I missed this in https://github.com/flutter/engine/pull/41159
=> Macmini8,1 for another target that runs host tests

.ci.yaml, DEPS, ci/builders/mac_impeller_cmake_example.json, ci/impeller_cmake_build_test.py, tools/gn
To fit in better with the `engine_v2` context, this PR shifts the `cmake` step for the `impeller-cmake-example` to run within the `flutter/tools/gn` script. That way, the recipe will ensure that `GOMA_DIR` is defined, goma is running, etc.. Since we use `cmake` to generate a ninja build for `impeller-cmake-example`, the engine_v2 `ninja` step can build it, and that feature of the python script is no longer needed.
Successful run is here https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20impeller-cmake-example/12/overview
=> [Impeller] Fix the cmake example build.

tools/gn
This fixes https://github.com/flutter/flutter/issues/123629
We were getting a warning when specifying this and not building the dart SDK.
=> Only set `dart_include_wasm_opt` when we are actually building the dart sdk.

.ci.yaml
Impeller tests are hanging on Intel Haswell Iris Graphics 5100 (8086:0a2e)
=> Do not run mac unit tests on macmini7,1

.ci.yaml
`mac_android_aot_engine` orchestrator kicks off Mac swarming tasks, but don't seem to need to run on a Mac.  Swap Linux bots which are more plentiful and have a shorter queue time.
Start by adding new `bringup` builder to see if it passes in staging.  If it passes I will remove the Mac variants ASAP.
Keep `mac_ios_engine` and `mac_host_engine` as Macs since they need to run Xcodes on Macs to create the xcframeworks.
=> Change v2 `mac_android_aot_engine` orchestrator builder to Linux

.ci.yaml
Intel Mac capacity is limited.  Swap the two Mac clang-tidy builders to arm bots.  The clang-tidy linter should run with arm natively.
Prod x64: https://ci.chromium.org/p/flutter/builders/prod/Mac%20Host%20clang-tidy/3318 Execution 35 mins 2 secs
This PR arm: https://ci.chromium.org/p/flutter/builders/try/Mac%20Host%20clang-tidy/8087 Execution 36 mins 30 secs (this hit an Xcode cache miss which added 4 minutes)
Prod x64: https://ci.chromium.org/p/flutter/builders/prod/Mac%20iOS%20clang-tidy/3303 Execution 11 mins 57 secs
This PR arm: https://ci.chromium.org/p/flutter/builders/try/Mac%20iOS%20clang-tidy/8087 Execution 18 mins 10 secs (this hit an Xcode cache miss which added 5 minutes)
=> Run clang tidy builds on arm Macs

.ci.yaml
`Linux mac_android_aot_engine` is passing: https://ci.chromium.org/p/flutter/builders/try/Linux%20mac_android_aot_engine/1
Remove `bringup` and remove `Mac mac_android_aot_engine` in favor of the Linux orchestrator #41181
=> Remove `Mac mac_android_aot_engine` in favor of Linux

shell/platform/android/io/flutter/embedding/engine/systemchannels/TextInputChannel.java, shell/platform/android/io/flutter/plugin/editing/ImeSyncDeferringInsetsCallback.java, shell/platform/android/io/flutter/plugin/editing/TextInputPlugin.java, shell/platform/android/test/io/flutter/plugin/editing/TextInputPluginTest.java
Reverts flutter/engine#40746
Googler bug: b/278174021
Failing on
```
shell/platform/android/io/flutter/plugin/editing/TextInputPlugin.java:239: Error: This method should only be accessed from tests or within private scope [VisibleForTests]
imeSyncCallback.remove();
```
=> Revert "[Android] Send connectionClosed message when keyboard becomes invisible to ensure framework focus state is correct."

testing/testing.gni
Whether we're building an x64 or arm64 macOS host build, always build unit tests.
Issue: https://github.com/flutter/flutter/issues/124840 …
=> [macOS] Build unittests on all macOS host builds

.ci.yaml
Intel Mac capacity is limited. Run the `mac_host_engine` orchestrator builder on Mac arm bots which we have a higher capacity of than the Intel Macs.  It needs Xcode to stitch together the frameworks and therefore to run on Mac, but isn't building anything itself.
Running on arm: https://ci.chromium.org/p/flutter/builders/try/Mac%20mac_host_engine/8593
I wasn't able to get this working on `mac_ios_engine` due to a gem issue, filed https://github.com/flutter/flutter/issues/124833
=> Run mac_host_engine orchestrator on arm Macs

.ci.yaml
Follow up to #41183.  Remove the `cores` dimensions so this builder can run on any arm machine which currently all have 8 cores but there's no reason to specify now that the arch is arm.
Introduced in #38261 to avoid 4-core Intel machines.
=> Remove cores dimension from Mac Host clang-tidy

.ci.yaml
This excludes Macmini7,1.
Fixes https://github.com/flutter/flutter/issues/124877
=> Specify allowed Macmini models

shell/platform/darwin/macos/framework/Source/FlutterMutatorViewTest.mm
FlutterMutatorViewTest.TransformedFrameIsCorrect and FlutterMutatorViewTest.RoundRectClipsToPath both apply transforms then do exact comparisons on the resulting 4x4 matrices of CGFloat values.
There are very small differences between the elements in the resulting matrices, on the order of 1e-15, depending on the CPU architecture on which the floating point operations were run.
Similar to elsewhere in the framework and engine, we now perform floating point equality tests within some small error bound -- I've arbitrarily selected 1e-10.
Issue: https://github.com/flutter/flutter/issues/124840 …
=> [macOS] Fix arm64 floating-point test failure

.ci.yaml
This builder doesn't use or install jazzy or Xcode, remove the properties from the config.
Passing without these properties: https://ci.chromium.org/p/flutter/builders/try/Mac%20impeller-cmake-example/14
=> Remove jazzy and Xcode properties from impeller-cmake-example builder

lib/web_ui/lib/src/engine/canvaskit/canvas.dart, lib/web_ui/lib/src/engine/canvaskit/color_filter.dart, lib/web_ui/lib/src/engine/canvaskit/image.dart, lib/web_ui/lib/src/engine/canvaskit/image_filter.dart, lib/web_ui/lib/src/engine/canvaskit/layer.dart, lib/web_ui/lib/src/engine/canvaskit/mask_filter.dart, lib/web_ui/lib/src/engine/canvaskit/painting.dart, lib/web_ui/lib/src/engine/canvaskit/text.dart, lib/web_ui/test/canvaskit/filter_test.dart, lib/web_ui/test/canvaskit/painting_test.dart
Migrate Paint API to `UniqueRef`. This includes `Paint`, `ImageFilter` (and all subtypes), `ColorFilter` (and all subtypes).
Also fix the following memory leaks:
* `CkPaint` is frequently used by layers where a one-off paint object is created, used, and immediately dropped. `CkPaint` now has a `dispose` method, and all one-off usages now dispose of the paint after they are done.
* `CkColorFilter.initRawImageFilter` was leaking the `SkColorFilter` created by `_initRawColorFilter` inside the expression.
* `CkManagedSkImageFilterConvertible.imageFilter` now takes a closure, which allows the implementation decide on the lifetime of the `SkImageFilter` vended to the caller. Because `CkColorFilter` is a const class it cannot store C++ instances inside its own fields, so it creates a temporary …
=> [web:canvaskit] migrate Paint API to UniqueRef

ci/licenses_golden/excluded_files, impeller/toolkit/egl/display.h, shell/platform/android/BUILD.gn, shell/platform/android/android_surface_gl_impeller.cc, shell/platform/android/android_surface_gl_impeller.h, shell/platform/android/android_surface_gl_impeller_unittests.cc, shell/platform/android/platform_view_android.cc
followup to https://github.com/flutter/engine/pull/40944
issue https://github.com/flutter/flutter/issues/105323 …
=> Adds AndroidSurfaceGLImpeller unit tests

shell/common/snapshot_controller_impeller.cc
In Skia, there is such a timeline event in `SnapshotControllerSkia::DoMakeRasterSnapshot`. Therefore, since Impeller wants to mimic Skia and this event does take a long time sometimes, it seems reasonable to add this. …
=> [Impeller] Make `DoMakeRasterSnapshot` output timeline event.

shell/platform/darwin/ios/framework/Source/FlutterViewController.mm, shell/platform/darwin/ios/framework/Source/FlutterViewControllerTest.mm
The "size interpolation" solution didn't go well (more context [here](https://github.com/flutter/engine/pull/40412#issuecomment-1485938933)). Then a new solution came to my mind, and I call it **"delayed swap"**:
In the originally behavior, we swap the width/height immediately before the rotation, resulting in roughly ~4x distortion in the beginning. With "delayed swap" solution, we **swap the width/height right in the middle of the rotation** (i.e. delay the swap for half of the transition duration).
This new "delayed swap" solution gives us the same benefit as the "snapshot" solution: 
- reducing ~4x distortion to ~2x
- most distorted frames occur in the middle of rotation when it's moving the fastest, making it hard to notice
And it fixes the drawback of "snapshot" solution: 
- it …
=> [rotation_distortion] Use "delayed swap" solution to reduce rotation distortion

.ci.yaml, ci/builders/mac_host_engine.json
Reverts flutter/engine#41233
The issue this PR was reverted was not replicable. On top of that we added extra precautions to ensure global generators are using left over binaries from out folder. https://flutter-review.googlesource.com/c/recipes/+/41960
=> Reland  "Migrate mac_host_engine to engine v2 builds."

impeller/base/base_unittests.cc, impeller/base/strings.cc, impeller/core/formats.cc, impeller/core/formats.h, impeller/core/texture_descriptor.cc, impeller/core/texture_descriptor.h, impeller/geometry/BUILD.gn, impeller/geometry/color.cc, impeller/geometry/color.h, impeller/renderer/render_target.cc, impeller/renderer/render_target.h
Also fixes and issue where SPrintF would only consider strings 64 bytes or smaller.
=> [Impeller] Add debug ToString methods to render targets.

.ci.yaml, ci/builders/mac_unopt.json
`Linux mac_unopt`: https://ci.chromium.org/p/flutter/builders/try/Linux%20mac_unopt/4
Remove `bringup` and remove `Mac mac_unopt` in favor of the Linux orchestrator https://github.com/flutter/engine/pull/41184
Add the `xcode` version to the mac_unopt json file since it's no longer being inherited from `Mac mac_unopt`.
Fixes https://github.com/flutter/flutter/issues/124912
=> Remove 'Mac mac_unopt' in favor of Linux

impeller/typographer/backends/skia/text_frame_skia.cc
A tale of glyph alignment problems:
- This rounding was originally introduced to solve: https://github.com/flutter/flutter/issues/121531. This was to align all of the glyphs to the pixel grid during text frame conversion.
- However, doing so introduced: https://github.com/flutter/flutter/issues/124310.
- When working on fixing https://github.com/flutter/flutter/issues/121887, I reworked the UV handling/rounding in text_contents in a way that normalizes the glyph rounding per-textframe, which actually solves both problems.
..and so we can just get rid of this early rounding now.
Before:
After:
All of the glyphs in a text frame still snap together:
https://user-images.githubusercontent.com/919017/232648307-cc298fd9-603d-4cd6-a927-c44834225303.mov
=> [Impeller] Remove glyph pixel rounding during text frame conversion

DEPS
Changes since last roll:
```
059d155 [dart] Add identifier needed for zlib roll (#718)
459d3e5 Bump github/codeql-action from 2.2.11 to 2.2.12 (#716)
91f1ba5 Bump actions/checkout from 3.5.1 to 3.5.2 (#715)
2e5c483 Bump actions/checkout from 3.5.0 to 3.5.1 (#714)
a5af13d Remove codeql. (#713)
```
=> Roll buildroot to 059d155b4d452efd9c4427c45cddfd9445144869

shell/platform/darwin/macos/framework/Source/FlutterViewController.mm, shell/platform/darwin/macos/framework/Source/FlutterViewControllerTest.mm
This PR fixes Ctrl+Tab shortcut on macOS.
From https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/EventOverview/HandlingKeyEvents/HandlingKeyEvents.html#//apple_ref/doc/uid/10000060i-CH7-SW11, some key events, such as Ctrl+Tab, are notified by calling `performKeyEvent`: instead of `keyDown:`.
The text input plugin already implement this method, this is why the shortcut works only when there is a TextField (TextInputPlugin is then activated), see 'Step 6' of https://github.com/flutter/flutter/issues/122084 description.
I had to implement `performKeyEvent:` on `FlutterViewWrapper` because when adding it to `FlutterView` it was not called (see this similar comment related to setBackgroundColor: https://github.com/flutter/engine/pull/36906#discussion_r1006253709).
I …
=> [macOS] Fix Ctrl+Tab is broken

shell/platform/darwin/ios/framework/Source/FlutterDartProject.mm
After having run a memory audit on Flutter Gallery I believe we can turn on wide gamut support by default for impeller.  Here are the ramifications of this change:
1) If an opaque surface is used and no transparent wide gamut images are used, there should be no change in performance or memory usage.
1) If a transparent surface is used; the surface will take up 2x memory (ex 4MB on iPhone 7) and will have a runtime performance cost.
1) If wide gamut **transparent** images are used, they will take up 2x memory.  Opaque wide-gamut images will take up the same amount of memory.
Steps:
* Tap "Material"
* Scroll down and back to "Cards"
* Tap "Cards"
* Scroll to bottom of "Cards" example
Notice that the card images are wide gamut, AdobeRGB.
**Memory increase:** 10.401 MB (+8.7%)
Steps:
* Just …
=> [Impeller] Turned on wide gamut support by default.

lib/ui/channel_buffers.dart, lib/ui/window/platform_configuration.cc, lib/ui/window/platform_configuration.h, shell/platform/common/client_wrapper/include/flutter/plugin_registrar.h, shell/platform/darwin/ios/framework/Headers/FlutterPlugin.h, shell/platform/darwin/ios/framework/Headers/FlutterPluginAppLifeCycleDelegate.h
Just some minor typos and a small diagnostic enhancement.
- No test changes needed (mainly doc changes).
=> Some minor doc typo and diagnostic fixes.

sky/tools/create_macos_framework.py
This is required to make the artifact consistent with the legacy artifacts while the tool is modified to remove the need of double zipping.
Bug: https://github.com/flutter/flutter/issues/124911 …
=> Double zip FlutterMacOS.framework.zip.

lib/web_ui/lib/src/engine/canvaskit/picture.dart, lib/web_ui/test/canvaskit/native_memory_test.dart
Remove unnecessary instrumentation from picture. `UniqueRef` automatically instruments all allocations, disposals, and garbage collections, which covers `CkPicture`.
=> [web:canvaskit] remove unnecessary instrumentation from picture

ci/licenses_golden/licenses_flutter, impeller/aiks/BUILD.gn, impeller/aiks/aiks_unittests.cc, impeller/aiks/canvas.cc, impeller/aiks/color_source.cc, impeller/aiks/color_source.h, impeller/aiks/paint.cc, impeller/aiks/paint.h, impeller/display_list/display_list_dispatcher.cc, impeller/entity/contents/runtime_effect_contents.h, impeller/entity/contents/solid_color_contents.cc, impeller/entity/contents/solid_color_contents.h, impeller/golden_tests/golden_tests.cc
Part of https://github.com/flutter/flutter/issues/125017.
Pulls ColorSource construction out of the dispatcher and into Aiks.
Cleans up a few design warts we've accumulated over time:
- Removes special exceptions for solid colors in `Paint`.
- Makes `SolidColorContents` a `ColorSourceContents`.
- Removes paint ref capture for kImage.
FYI @iamralpht
=> [Impeller] Provide an opaque interface for color sources in Aiks

impeller/playground/playground.cc, impeller/renderer/backend/gles/context_gles.cc, impeller/renderer/backend/metal/context_mtl.mm, impeller/renderer/backend/vulkan/capabilities_vk.cc, impeller/renderer/backend/vulkan/capabilities_vk.h, impeller/renderer/capabilities.cc, impeller/renderer/capabilities.h
GL/VK playgrounds that load image fixtures are currently broken on macOS.
=> [Impeller] Add buffer-to-texture blit capability check; fix GL+VK playgrounds on macOS

impeller/playground/backend/vulkan/playground_impl_vk.cc
fixes https://github.com/flutter/flutter/issues/125076
[Discord]: …
=> [impeller] added moltenvk notice

impeller/aiks/aiks_unittests.cc, impeller/entity/contents/filters/blend_filter_contents.cc, impeller/entity/contents/filters/border_mask_blur_filter_contents.cc, impeller/entity/contents/filters/color_matrix_filter_contents.cc, impeller/entity/contents/filters/linear_to_srgb_filter_contents.cc, impeller/entity/contents/filters/srgb_to_linear_filter_contents.cc, impeller/entity/contents/filters/yuv_to_rgb_filter_contents.cc, impeller/entity/shaders/color_matrix_color_filter.vert, impeller/entity/shaders/linear_to_srgb_filter.vert, impeller/entity/shaders/srgb_to_linear_filter.vert, impeller/entity/shaders/yuv_to_rgb_filter.vert, impeller/tools/malioc.json
Resolves https://github.com/flutter/flutter/issues/124956.
Fixes some recent transform issues that mainly apply to chained filters (like when both a color + image filter has been set).
- For all filters, the returned entity should just be an identity matrix because the snapshot transform gets fully absorbed.
- For all filters, given entity's transform should be applied in the coverage proc (although this currently makes no difference because of the way coverage is queried when snapshotting).
- For filters drawing with coverage + transforming UVs, the transform handed to the contents of the deferred entity needs to be applied. Otherwise the entity won't get repositioned correctly while snapshotting.
New golden: `Play/AiksTest.TranslucentSaveLayerWithColorFilterAndImageFilterDrawsCorrectly/M …
=> [Impeller] Fix transform regressions for chained filters

impeller/display_list/dl_image_impeller.cc, impeller/entity/contents/atlas_contents.cc, impeller/entity/contents/contents.cc, impeller/entity/contents/contents.h, impeller/entity/contents/filters/blend_filter_contents.cc, impeller/entity/contents/filters/border_mask_blur_filter_contents.cc, impeller/entity/contents/filters/color_matrix_filter_contents.cc, impeller/entity/contents/filters/filter_contents.cc, impeller/entity/contents/filters/filter_contents.h, impeller/entity/contents/filters/gaussian_blur_filter_contents.cc, impeller/entity/contents/filters/inputs/contents_filter_input.cc, impeller/entity/contents/filters/inputs/contents_filter_input.h, impeller/entity/contents/filters/inputs/filter_contents_filter_input.cc, impeller/entity/contents/filters/inputs/filter_contents_filter_input.h, impeller/entity/contents/filters/inputs/filter_input.h, impeller/entity/contents/filters/inputs/texture_filter_input.cc, impeller/entity/contents/filters/inputs/texture_filter_input.h, impeller/entity/contents/filters/linear_to_srgb_filter_contents.cc, impeller/entity/contents/filters/local_matrix_filter_contents.cc, impeller/entity/contents/filters/matrix_filter_contents.cc, impeller/entity/contents/filters/morphology_filter_contents.cc, impeller/entity/contents/filters/srgb_to_linear_filter_contents.cc, impeller/entity/contents/filters/yuv_to_rgb_filter_contents.cc, impeller/entity/contents/framebuffer_blend_contents.cc, impeller/entity/contents/texture_contents.cc, impeller/entity/contents/texture_contents.h, impeller/entity/contents/tiled_texture_contents.cc, impeller/entity/contents/vertices_contents.cc
Makes it much easier to work out where things are going wrong in filter chains.
For example, when capturing the app in https://github.com/flutter/flutter/issues/124956, the chain of RenderPasses gets labeled as follows:
1. Contents to ForegroundPorterDuffBlend Filter Snapshot
2. Contents to GaussianBlur Filter Snapshot
3. Directional Gaussian Blur Filter
4. Directional Gaussian Blur Filter
...and so it's easy to see that the filter chain is ForegroundPorterDuffBlend->DirectionalGaussianBlur->DirectionalGaussianBlur, and the former two are triggering a non-collapsed snapshot of their inputs.
=> [Impeller] Comprehensively label snapshots

impeller/entity/contents/solid_color_contents.cc, impeller/entity/contents/solid_color_contents.h, impeller/entity/entity_unittests.cc
Related to https://github.com/flutter/flutter/issues/114402
At least in the flutter gallery test app, with https://github.com/flutter/gallery/pull/909 reverted - this significantly improves the performance in the Xcode frame debugger. If we wanted to do this for more color sources or filter effects, we need to do much more work to track texture opacity, but this seems like a reasonable and low cost first step.
=> [impeller] convert src over to src for solid color

ci/builders/mac_unopt.json
Add `--force-mac-arm64` to arm gn commands running on Mac ARM bots to compile natively and not with Rosetta.  Sometimes we've seen random slow-downs in CI when lots of Rosetta processes run at the same time.
This will disable goma for these builds but it doesn't seem to be much slower:
`build ios_debug_sim_arm64` step on prod:
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Production%20Engine%20Drone/123894/overview - 1.1 minute
vs this PR:
https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20Engine%20Drone/747210/overview - 1.8 minute
=> Run mac unopt arm builds with arm toolchain

shell/platform/darwin/ios/framework/Source/FlutterDartProject.mm
Reverts flutter/engine#39801
`customer: chalk` hit some rendering issues that was narrowed down to this: b/278976014
=> Revert "[Impeller] Turned on wide gamut support by default."

.ci.yaml, ci/builders/README.md, ci/builders/mac_unopt.json
With https://flutter-review.googlesource.com/c/recipes/+/42160, we are ready to make all tests consistent with xcode 14c18.
Fixes https://github.com/flutter/flutter/issues/125216
=> Update xcode to 14c18

shell/platform/darwin/ios/framework/Source/FlutterView.mm, shell/platform/darwin/ios/ios_surface_metal_impeller.mm
Reopens https://github.com/flutter/flutter/issues/120641.
There are errors blitting from offscreen textures to onscreen textures when wide gamut is enabled due to the mismatching formats.
It looks like we don't currently use a different format when wide gamut is off either.
```
2023-04-21 09:14:39.470 ios_dev[61385/0x1fb959e40] [lvl=1] -[GAMImpressionLogger buildAndQueueImpression:sendInvariants:] Adding impression: event_code 69047, seq_num 41
-[MTLDebugBlitCommandEncoder internalValidateCopyFromTexture:sourceSlice:sourceLevel:sourceOrigin:sourceSize:toTexture:destinationSlice:destinationLevel:destinationOrigin:options:]:388: failed assertion `Copy From Texture Validation
[sourceTexture pixelFormat](MTLPixelFormatBGRA10_XR) must be compatible with [destinationTexture …
```
=> [Impeller] Always use BGRA10_XR for wide gamut

ci/licenses_golden/excluded_files, impeller/renderer/BUILD.gn, impeller/renderer/backend/gles/context_gles.cc, impeller/renderer/backend/metal/context_mtl.mm, impeller/renderer/capabilities.cc, impeller/renderer/capabilities.h, impeller/renderer/capabilities_unittests.cc
I noticed we still weren't going down the blit-less path on iOS, and it turned out that the wrong capability was getting assigned in the builder.
=> [Impeller] Fix SupportsReadFromOnscreenTexture capability check

lib/web_ui/lib/src/engine/navigation/url_strategy.dart, lib/web_ui/test/engine/history_test.dart
During a JS-interop refactor, we introduced a small bug in the `addPopStateListener` method of the `HashUrlStrategy` object (web).
This wasn't caught before because the existing tests were mocking the refactored code.
Fixes: https://github.com/flutter/flutter/issues/125228
[CLA]: …
=> [web] Fix HashUrlStrategy.addPopStateListener

impeller/renderer/backend/vulkan/blit_command_vk.cc
fixes https://github.com/flutter/flutter/issues/125147
[Discord]: …
=> [impeller] fixed flake where blit wasn't tracking its texture

impeller/golden_tests/golden_playground_test_mac.cc
We previously turned this test to `ignore` to see if we could get it to stabilize by accepting the variants and it doesn't seem to have worked.  I'm going to turn it off again.
[breaking …
=> [Impeller] Turned off the TextRotated golden test again

impeller/renderer/backend/gles/command_buffer_gles.cc, impeller/renderer/backend/gles/command_buffer_gles.h, impeller/renderer/backend/gles/proc_table_gles.h, impeller/renderer/backend/metal/command_buffer_mtl.h, impeller/renderer/backend/metal/command_buffer_mtl.mm, impeller/renderer/backend/vulkan/command_buffer_vk.cc, impeller/renderer/backend/vulkan/command_buffer_vk.h, impeller/renderer/command_buffer.cc, impeller/renderer/command_buffer.h, impeller/renderer/testing/mocks.h, lib/ui/painting/image_decoder_impeller.cc
This can be used by IO thread operations such as image decoding to ensure that the results of GPU commands become visible to the raster thread.
=> [Impeller] Add a CommandBuffer::WaitUntilScheduled API

ci/builders/windows_arm_host_engine.json
Reverts flutter/engine#41372
The duplicated artifacts were removed from Windows Host Engine in https://flutter-review.googlesource.com/c/recipes/+/42340. After the recipes change lands and is propagated it will be safe to update the `Windows windows_arm_host_engine` build to upload the artifacts to prod.
Bug: https://github.com/flutter/flutter/issues/125262
=> Reland "Upload windows arm artifacts to production bucket."

ci/builders/linux_android_debug_engine.json, ci/builders/linux_host_engine.json, ci/builders/mac_host_engine.json, ci/builders/mac_unopt.json, ci/builders/windows_host_engine.json
The `"type": "local"` property from local test and generators was never used. Removing from configurations. …
=> [Cleanup] remove type=local from local test/generators.

lib/web_ui/lib/src/engine/navigation/url_strategy.dart, lib/web_ui/test/engine/history_test.dart
This PR cherry-picks: https://github.com/flutter/engine/commit/8d9f17e07633b0f8f2400bf00c95c4fac18f599e
Fixes https://github.com/flutter/flutter/issues/125317
---
During a JS-interop refactor, we introduced a small bug in the `addPopStateListener` method of the `HashUrlStrategy` object (web).
This wasn't caught before because the existing tests were mocking the refactored code.
Fixes: https://github.com/flutter/flutter/issues/125228 …
=> [CP] [web] Fix HashUrlStrategy.addPopStateListener

shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm, shell/platform/darwin/ios/framework/Source/FlutterTextInputPluginTest.mm
Fixes [flutter/flutter#122139](https://github.com/flutter/flutter/issues/122139) with flutter pr [flutter/flutter#122383](https://github.com/flutter/flutter/pull/122383)
=> [ios] Fix hold and drag spacebar does not move cursor when obscureText is true.

lib/web_ui/lib/src/engine/app_bootstrap.dart, lib/web_ui/lib/src/engine/canvaskit/canvaskit_api.dart, lib/web_ui/lib/src/engine/canvaskit/image_web_codecs.dart, lib/web_ui/lib/src/engine/configuration.dart, lib/web_ui/lib/src/engine/dom.dart, lib/web_ui/lib/src/engine/js_interop/js_loader.dart, lib/web_ui/lib/src/engine/js_interop/js_promise.dart, lib/web_ui/lib/src/engine/navigation/js_url_strategy.dart, lib/web_ui/lib/src/engine/profiler.dart, lib/web_ui/lib/src/engine/safe_browser_api.dart, lib/web_ui/lib/src/engine/skwasm/skwasm_impl/raw/js_functions.dart, lib/web_ui/lib/src/engine/svg.dart, lib/web_ui/lib/src/engine/view_embedder/hot_restart_cache_handler.dart, lib/web_ui/lib/src/engine/window.dart, lib/web_ui/test/canvaskit/canvaskit_api_test.dart, lib/web_ui/test/canvaskit/native_memory_test.dart, lib/web_ui/test/engine/browser_detect_test.dart, lib/web_ui/test/engine/embedder_test.dart, lib/web_ui/test/engine/initialization_test.dart, lib/web_ui/test/engine/profiler_test.dart, web_sdk/web_engine_tester/lib/static/host.dart
dart:js_interop and package:js will start conflicting. Eventually, we want people to only use dart:js_interop, so this CL refactors code to do that.
Unblocks https://dart-review.googlesource.com/c/sdk/+/294130/8 and prevents confusing shadowing of dart:js_interop annotations like we do today.
- [Mentioned CL that is unblocked] I listed at least one issue that this PR fixes in the description above.
- [Need test-exemption] I added new tests to check the change I am making, or this PR is [test-exempt].
=> Remove package:js references and move to dart:js_interop

sky/tools/create_macos_framework.py
The flutter tool is expecting FlutterMacOS.dSYM.zip to be double zipped.
Bug: https://github.com/flutter/flutter/issues/124911 …
=> Double zip FlutterMacOS.dSYM.zip.

ci/licenses_golden/excluded_files, impeller/BUILD.gn, impeller/renderer/backend/vulkan/BUILD.gn, impeller/renderer/backend/vulkan/blit_command_vk.cc, impeller/renderer/backend/vulkan/blit_command_vk_unittests.cc, impeller/renderer/backend/vulkan/command_encoder_vk.cc, impeller/renderer/backend/vulkan/command_encoder_vk.h, impeller/renderer/backend/vulkan/test/mock_vulkan.cc, impeller/renderer/backend/vulkan/test/mock_vulkan.h
Adds test for https://github.com/flutter/engine/pull/41347 and adds an extra fix for https://github.com/flutter/flutter/issues/125147.
Testing this is possible because I've mocked out all of vulkan.  We can expand on this in the future we want to be more robust.
[CLA]: …
=> [Impeller] Fixed blit command missing tracking and added mock vulkan for tests

shell/platform/darwin/ios/framework/Source/FlutterDartProject.mm, shell/platform/darwin/ios/framework/Source/FlutterDartProject_Internal.h, shell/platform/darwin/ios/framework/Source/FlutterEngine.mm, shell/platform/darwin/ios/framework/Source/FlutterView.h, shell/platform/darwin/ios/framework/Source/FlutterView.mm, shell/platform/darwin/ios/framework/Source/FlutterViewTest.mm
fixes https://github.com/flutter/flutter/issues/125430
[Discord]: …
=> Made sure not to turn on wide gamut support without impeller.

.ci.yaml, ci/builders/windows_host_engine.json
Windows host engine and windows_engine_host_engine builds are generating the artifacts using gn+ninja. This PR is sending the legacy build to staging and starts uploading the engine v2 artifacts to prod. …
=> Migrate windows host engine to engine v2.

fml/platform/posix/native_library_posix.cc
As the Engine uses `dlopen` to find the `libapp.so`, https://github.com/flutter/flutter/issues/59834 can happen which will prevent `dlopen` from finding the binary. In theory this should be mitigated by https://github.com/flutter/engine/pull/9762, but an internal customer observed errors that could be related. 
The additional logging here can help to rule out that hypothesis. For Googlers, see b/276657840 for more details. …
=> Log dlopen errors in opt builds

impeller/renderer/backend/vulkan/command_pool_vk.cc, impeller/renderer/backend/vulkan/context_vk.cc, impeller/renderer/backend/vulkan/context_vk.h
fixes https://github.com/flutter/flutter/issues/125321
Tests coverage from existing tests (see issue).
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling- …
=> [Impeller] removed collisions of dead command pools between tests.

impeller/renderer/backend/metal/command_buffer_mtl.mm, impeller/renderer/backend/metal/context_mtl.h, impeller/renderer/backend/metal/context_mtl.mm, impeller/renderer/backend/metal/surface_mtl.h, impeller/renderer/backend/metal/surface_mtl.mm, shell/platform/darwin/ios/ios_surface_metal_impeller.mm
Reverts https://github.com/flutter/engine/pull/40895.
Resolves https://github.com/flutter/flutter/issues/120399 (again).
A bunch of frames get pumped on the main thread _without a transaction_ just before unmerging occurs (I don't know why this happens), and so checking the current thread to determine whether we need to present with a transaction or not isn't sufficient. In the prior fix, after the unmerge, the raster thread would hang for one second while waiting for the next drawable to get freed up (happens on the second raster thread frame post-unmerge), and then subsequent presents would just do nothing for a while, but eventually recover.
`presentsWithTransaction` works whether the `CATransaction` stack is empty or not, and so the only difference here is that …
=> [Impeller] iOS/macOS: Only wait for command scheduling prior to present (redux)

impeller/entity/entity_pass.cc, impeller/renderer/backend/metal/surface_mtl.mm, impeller/renderer/backend/vulkan/surface_vk.cc, impeller/renderer/render_target.cc, impeller/renderer/render_target.h
Switch the root RenderPass stencil from transient to device private, add validation logs, and dry the offscreen stencil setup. Also make the multisample root stencil setup valid in Vulkan (the attachment mismatched the texture -- this didn't matter before since we were always replacing it).
Fixes a bug where the stencil gets erased between root render passes -- this issue was introduced when we removed the root blit on iOS.
Before:
https://user-images.githubusercontent.com/919017/234528788-fe6f69a6-b77e-4b36-8db6-b7691e822873.mov
After:
https://user-images.githubusercontent.com/919017/234528755-5bb0d977-a8a0-43f8-8c13-ae048484d36e.mov
=> [Impeller] Store the root stencil on iOS

.ci.yaml, ci/builders/windows_android_aot_engine.json
Both builds are generating artifacts in the same way. This is moving the legacy builder to staging and updating Windows windows_aot_engine build to upload artifacts to prod. …
=> Migrate Windows AOT Engine to Engine V2.

DEPS, tools/gn
In https://github.com/flutter/flutter/issues/125361 we discovered that a new version of clang can require updating goma in order for goma to work properly. This PR adds a dependency on CIPD goma to the DEPS file so that we can update it for use in local builds when needed. Since CI does its own management of the goma client and the compiler proxy, and since goma can only be used by Googlers, the DEPS file download is guarded behind the `use_cipd_goma` gclient var. To use it one would update the engine `.gclient` file to be something like:
```
~/flutter/engine/src $ cat ../.gclient
solutions = [
{
"managed": False,
"name": "src/flutter",
"url": "git@github.com:zanderso/engine.git",
"custom_deps": {},
"custom_vars": {
"use_cipd_goma": True,
},
"deps_file": "DEPS",
"safesync_url": "",
},
] …
```
=> Download and use the goma client from cipd

impeller/renderer/backend/vulkan/command_pool_vk.cc
followup from https://github.com/flutter/engine/pull/41490
[Discord]: …
=> Updated todo with github issue link

impeller/aiks/aiks_unittests.cc, impeller/aiks/color_source.cc, impeller/aiks/paint_pass_delegate.cc, impeller/core/texture.cc, impeller/core/texture.h, impeller/entity/contents/conical_gradient_contents.cc, impeller/entity/contents/conical_gradient_contents.h, impeller/entity/contents/contents.cc, impeller/entity/contents/contents.h, impeller/entity/contents/linear_gradient_contents.cc, impeller/entity/contents/linear_gradient_contents.h, impeller/entity/contents/radial_gradient_contents.cc, impeller/entity/contents/radial_gradient_contents.h, impeller/entity/contents/solid_color_contents.cc, impeller/entity/contents/solid_color_contents.h, impeller/entity/contents/sweep_gradient_contents.cc, impeller/entity/contents/sweep_gradient_contents.h, impeller/entity/contents/tiled_texture_contents.cc, impeller/entity/contents/tiled_texture_contents.h, impeller/entity/entity.cc, impeller/entity/entity.h, impeller/entity/entity_pass.cc, impeller/entity/entity_unittests.cc
This coercion happens when Entities are appended to a pass, which is the moment where we will need to perform depth sorting.
=> [Impeller] Coerce opaque ColorSourceContents to Source

impeller/renderer/backend/metal/context_mtl.mm, impeller/renderer/backend/vulkan/capabilities_vk.cc, impeller/renderer/backend/vulkan/capabilities_vk.h, impeller/renderer/capabilities.cc, impeller/renderer/capabilities.h, impeller/renderer/capabilities_unittests.cc, impeller/typographer/backends/skia/text_render_context_skia.cc, impeller/typographer/backends/skia/text_render_context_skia.h, impeller/typographer/glyph_atlas.cc, impeller/typographer/glyph_atlas.h, impeller/typographer/lazy_glyph_atlas.cc, impeller/typographer/text_render_context.cc, impeller/typographer/text_render_context.h, impeller/typographer/typographer_unittests.cc
Reverts flutter/engine#41374
Breaks on Simulators!
=> Revert "[Impeller] Use a device buffer for SkBitmap allocation, use Linear texture on Metal backend."

DEPS
To pick up https://github.com/flutter/buildroot/pull/722
=> Roll buildroot to 5708f2051772fd02c949e5dc9397e54f8c7a4478

.ci.yaml, ci/builders/mac_host_engine.json
Relands: https://github.com/flutter/engine/pull/41149
GN+Ninja artifacts have been validated manually. The number of files and their content is the same and presubmit tests are passing correctly in the engine and flutter.
The reason of previous reverts are:
* FlutterMacOS.framework.zip required to be double zipped.
* FlutterMacOS.dSYM.zip required to be double zipped.
* GCS cache header needed to be updated during testing.
Full details of what has been fixed can be found in: https://github.com/flutter/flutter/issues/124911
=> reland "Migrate mac_host_engine to engine v2 builds."

ci/builders/mac_android_aot_engine.json
cherry picks https://github.com/flutter/engine/pull/41518
cp issue link: https://github.com/flutter/flutter/issues/125591
context: https://github.com/flutter/flutter/issues/125570#issuecomment-1523823942
Pin xcode version for the six sub builds in mac android aot engine
=> [CP][codesign] Add pinned xcode version to mac android aot engine

impeller/renderer/backend/metal/surface_mtl.mm
This fixes a validation error I see from Xcode running the backdrop filter benchmarks
=> [Impeller] allow shader read for root resolve texture

.github/workflows/scorecards-analysis.yml, .github/workflows/third_party_scan.yml
This removes the vuln scanning action from the scorecards yaml and into its own file. The additional file already existed but was not updated.
Fixes:
b/246821537 …
=> Refactor vuln scan into separate yaml

impeller/renderer/backend/metal/context_mtl.mm, impeller/renderer/backend/metal/device_buffer_mtl.h, impeller/renderer/backend/metal/device_buffer_mtl.mm, impeller/renderer/backend/vulkan/capabilities_vk.cc, impeller/renderer/backend/vulkan/capabilities_vk.h, impeller/renderer/capabilities.cc, impeller/renderer/capabilities.h, impeller/renderer/capabilities_unittests.cc, impeller/typographer/backends/skia/text_render_context_skia.cc, impeller/typographer/backends/skia/text_render_context_skia.h, impeller/typographer/glyph_atlas.cc, impeller/typographer/glyph_atlas.h, impeller/typographer/lazy_glyph_atlas.cc, impeller/typographer/text_render_context.cc, impeller/typographer/text_render_context.h, impeller/typographer/typographer_unittests.cc
Reverts flutter/engine#41538
Playground atlas text is broken for the Vulkan + OpenGLES backends with this change. Maybe something's not getting zero initialized?
Before revert:
After revert:
=> Revert "Reland: [Impeller] Use a device buffer for SkBitmap allocation, use Linear texture on Metal backend. "

impeller/aiks/picture.cc, impeller/entity/entity_pass.cc, impeller/renderer/backend/metal/surface_mtl.mm, impeller/renderer/backend/vulkan/surface_vk.cc
Moves onscreen stencil management from the surface to EntityPass for Metal and Vulkan. EntityPass has enough context to set up the stencil optimally.
Also forces us to fail loudly when the supplied stencil is set up in a way that can't be used for rendering the pass on GLES.
- On Vulkan, when we're blitting, we don't need to set up a onscreen stencil attachment at all.
- And on both Vulkan and Metal, the onscreen stencil can be transient when no pass reads are necessary (fixes the benchmark regressions introduced by https://github.com/flutter/engine/pull/41509).
=> [Impeller] Manage the onscreen stencil in EntityPass

.ci.yaml, ci/builders/linux_arm_host_engine.json
The artifacts from legacy and engine v2 builders are identical. This PR is moving the legacy builder to staging and updates engine v2 build to upload the artifacts to production.
[breaking …
=> Migrate Linux Arm Host Engine to engine v2.

tools/fuchsia/sdk/sdk_targets.gni
Otherwise this causes GN to read JSON files that are irrelevant.
=> fuchsia: do not read version_history.json

impeller/aiks/BUILD.gn, impeller/base/validation.cc, impeller/base/validation.h
Enable validation for release builds of the golden tests. The goldens hit a validation failure but didn't print anything in this PR: https://github.com/flutter/engine/pull/41563
=> [Impeller] Always enable validation for goldens

.ci.yaml
These builds are affected by https://github.com/flutter/flutter/issues/119750
The timeout needs to be increased to avoid the autorollers closing PRs due to timeouts.
=> Increase timeout for clang-tidy on mac

lib/ui/platform_dispatcher.dart, shell/platform/android/io/flutter/app/FlutterActivity.java, shell/platform/android/io/flutter/app/FlutterActivityDelegate.java, shell/platform/android/io/flutter/app/FlutterActivityEvents.java, shell/platform/android/io/flutter/app/FlutterFragmentActivity.java, shell/platform/android/io/flutter/app/FlutterPluginRegistry.java, shell/platform/android/io/flutter/embedding/android/FlutterActivity.java, shell/platform/android/io/flutter/embedding/android/FlutterActivityAndFragmentDelegate.java, shell/platform/android/io/flutter/embedding/android/FlutterFragment.java, shell/platform/android/io/flutter/embedding/engine/FlutterEngineConnectionRegistry.java, shell/platform/android/io/flutter/embedding/engine/plugins/activity/ActivityPluginBinding.java, shell/platform/android/io/flutter/embedding/engine/plugins/shim/ShimRegistrar.java, shell/platform/android/io/flutter/embedding/engine/systemchannels/LifecycleChannel.java, shell/platform/android/io/flutter/plugin/common/PluginRegistry.java, shell/platform/android/test/io/flutter/embedding/android/FlutterActivityAndFragmentDelegateTest.java, shell/platform/android/test/io/flutter/embedding/engine/systemchannels/LifecycleChannelTest.java
This incorporates additional signal from `Activity.onWindowFocusChanged` to help decide if the application is `resumed` or `inactive`.
When the user pulls down the notification shade or opens the app switcher in iOS, then iOS sends a notification to the application that it no longer has input focus (is no longer "active" in Apple terminology). 
However, Android (at least on a Pixel) doesn't send `onPause` and `onResume` events for these things, as one might expect. Instead, this PR changes things so that we listen to `Activity.onWindowFocusChanged` and see if any of the windows still have focus.
If it doesn't have focus, then the lifecycle switches to `inactive` (even if `onPause` hasn't been called), and if it does have focus (and `onResume` hasn't been called) then we should go to …
=> Determine lifecycle by looking at window focus also

shell/platform/darwin/ios/framework/Source/FlutterPlatformViews.mm, shell/platform/darwin/ios/framework/Source/FlutterPlatformViewsTest.mm
DisposeView happens every frame before laying out PlatformViews, with the order specified in `composition_order_`. Because `view_to_dispose_` is determined on UI thread and `composition_order_` is determined on the platform thread, there could be a race if the dart code on the UI thread runs faster than the rasterizer on the Platform thread, causing a view in `view_to_dispose_` is still in the `composition_order_`.
This PR delays the views in the `composition_order_` being disposed and wait for the next frame to dispose them. 
fixes https://github.com/flutter/flutter/issues/125223 …
=> [platform_view] Only dispose view when it is removed from the composition order

DEPS
git log --date=short --format="%ad %ae %s" 5708f2051772fd02c949e5dc9397e54f8c7a4478..c96c9d4641714301fab450a5f3b0f3c42712e1e3 2023-04-28 maruel@gmail.com fuchsia: do not read json unless enabled (#725) 2023-04-28 49699333+dependabot[bot]@users.noreply.github.com Bump github/codeql-action from 2.3.1 to 2.3.2 (#724) 2023-04-27 49699333+dependabot[bot]@users.noreply.github.com Bump github/codeql-action from 2.3.0 to 2.3.1 (#723)"
=> Roll buildroot to c96c9d4641714301fab450a5f3b0f3c42712e1e3

impeller/image/backends/skia/compressed_image_skia.cc, lib/ui/painting/image_decoder_unittests.cc, lib/ui/painting/image_generator.cc, lib/ui/painting/image_generator.h
Reverts flutter/engine#41368
This is blocking rolls into the framework. Let's revert until we sort out whether there's a workaround for the change to the unpremultiplied alpha issue.
=> Revert "Replace deprecated and internal Skia EncodedImage calls with public versions"

impeller/tools/impeller.gni, impeller/tools/xxd.py
FlatBuffer deserialization may segfault if the buffer is based at an unaligned address.
=> [Impeller] Ensure that embedded blobs are placed at aligned addresses.

impeller/aiks/aiks_unittests.cc, impeller/entity/contents/contents.cc, impeller/entity/entity.cc
Resolves https://github.com/flutter/flutter/issues/125717.
The "destructive" check is only relevant for turning off SaveLayer shrinkwrapping (used for the `cover_whole_screen_` property in EntityPass), and shouldn't be used to avoid culling entities.
=> [Impeller] Remove destructive blend mode check from Contents::ShouldRender

lib/ui/window/platform_configuration.cc, lib/ui/window/platform_configuration.h, lib/ui/window/window.cc, lib/ui/window/window.h, runtime/runtime_controller.cc, shell/platform/embedder/fixtures/main.dart, shell/platform/embedder/tests/embedder_unittests.cc
This change removes the assumption that that all pointer events go to the view ID `0`. This change also adds a test for pointer events.
Part of: https://github.com/flutter/flutter/issues/112205
All pointer events are sent to [`PlatformDispatcher.onPointerDataPacket`](https://api.flutter.dev/flutter/dart-ui/PlatformDispatcher/onPointerDataPacket.html). In the future, a `viewId` property will be added [`PointerData`](https://api.flutter.dev/flutter/dart-ui/PointerData-class.html), which the framework (specifically, `GestureBinding`) will use to route the event to the proper view. This `viewId` property's value will be set by the embedders. …
=> Remove single view assumption from pointer events

impeller/image/backends/skia/compressed_image_skia.cc, lib/ui/BUILD.gn, lib/ui/painting/image_decoder_unittests.cc, lib/ui/painting/image_generator.cc, lib/ui/painting/image_generator.h
This is a reland of #41368 with fix for transparent images and a unit test to verify it.
Skia would like to remove `SkImageGenerator::MakeFromEncoded` and this appears to be the only remaining usage. It appears to be easily swapped out for the `SkImages::DeferredFromEncodedData`. (skbug.com/13052)
This also removes the use of the internal `SkCodecImageGenerator` for the public `SkCodec` API (which the image generator had just been deferring to anyway).
While unbreaking some unit tests, I made a few assertions easier to debug and produce nicer error messages. …
=> Reland image encoder

impeller/geometry/path.h
Noticed this while reading some code. I think an IDE plugin I have does this sometimes.
=> [Impeller] Remove duplicate component in path.h

testing/run_tests.py
fixes https://github.com/flutter/flutter/issues/121017
[Discord]: …
=> [Impeller] Turns on the Metal validator for impeller_unittests.

ci/builders/linux_android_aot_engine.json, ci/builders/linux_android_debug_engine.json, ci/builders/linux_host_engine.json, ci/builders/mac_ios_engine.json
Engine V2 builds were missing a step to verify the exported symbols. This PR is adding the step in preparation to migrate the android builds to engine v2. …
=> Add the verify exported symbols to linux builds.

lib/web_ui/lib/src/engine/text/font_collection.dart
@staticInterop members will start disallowing tear-offs, so this member should turn into a closure.
Unblocks a roll in the SDK that disallows tear-offs.
=> Turn @staticInterop tear-off into closure

.ci.yaml
Dimensions are now used to detect the drone to use. Framework tests are using shard_util_v2 but not engine v2 builds and require to pass the drone dimension from the .ci.yaml file.
[breaking …
=> Use os_dimension in framework tests.

ci/licenses_golden/excluded_files, display_list/display_list.cc, display_list/display_list.h, display_list/display_list_unittests.cc, flow/surface_frame.cc, impeller/aiks/BUILD.gn, impeller/aiks/canvas.cc, impeller/aiks/canvas.h, impeller/aiks/canvas_unittests.cc, impeller/display_list/dl_dispatcher.cc, impeller/display_list/dl_dispatcher.h, impeller/entity/entity_pass.h, impeller/geometry/rect.h, impeller/renderer/backend/metal/surface_mtl.h, impeller/renderer/backend/metal/surface_mtl.mm, shell/gpu/gpu_surface_metal_impeller.mm
Switching the calls to dispatch into an Impeller Dispatcher to use a cull rect to enable pre-culling of the out-of-bounds ops.
This change showed an improvement of around 2x on the rendering performance of the non-intersecting platform view benchmark, but that was measured without the recent changes to the destructive blend modes in Impeller renderer.
=> [Impeller] take advantage of DisplayList culling

.ci.yaml
As of https://github.com/flutter/engine/pull/41219 all the .ci.yaml builders will run on either Macmini8,1 (x64) or Macmini9,1 (arm).  Stop specifying `Macmini8,1` on individual builders and let the specified architecture be the deciding factor.
Reverts #41203
=> Stop specifiying Macmini8,1 in ci builders, use inherited mac_model dimension

lib/web_ui/lib/src/engine/text_editing/text_editing.dart, lib/web_ui/test/engine/text_editing_test.dart
This PR fixes cursor jump on Chrome for Android when the user taps in a multiline `TextField`.
Using the following code sample:
<details><summary>Code sample</summary>
```dart
void main() => runApp(const MyApp());
const MyApp({super.key});
@override
return const MaterialApp(
title: 'Text Field Focus',
home: MyCustomForm(),
);
}
}
// Define a custom Form widget.
class MyCustomForm extends StatelessWidget {
const MyCustomForm({super.key});
@override
return Scaffold(
appBar: AppBar(
title: const Text('Text Field Focus'),
),
backgroundColor: Colors.amber,
body: Padding(
padding: const EdgeInsets.all(16.0),
child: TextField(
decoration: const …
```
=> Web - Fix selection jump on Chrome for Android

shell/platform/embedder/tests/embedder_test_backingstore_producer.cc, shell/platform/fuchsia/flutter/vulkan_surface_producer.cc, vulkan/vulkan_swapchain.cc
In https://skia-review.googlesource.com/c/skia/+/687642, Skia moved some gpu-related methods on SkSurface to be static functions in a different header. This updates those callsites in Flutter. …
=> Migrate SkSurface::getBackend* methods to static functions

lib/web_ui/lib/src/engine/embedder.dart, lib/web_ui/lib/src/engine/global_styles.dart, lib/web_ui/test/engine/global_styles_test.dart
The `hasAutofillOverlay` and `cssSelectorPrefix` parameters aren't really used in any useful way. Let's remove them.
=> [web] Remove unused function parameter

lib/web_ui/lib/src/engine/canvas_pool.dart, lib/web_ui/lib/src/engine/html/bitmap_canvas.dart, lib/web_ui/lib/src/engine/html/clip.dart, lib/web_ui/lib/src/engine/html/color_filter.dart, lib/web_ui/lib/src/engine/html/dom_canvas.dart, lib/web_ui/lib/src/engine/html/painting.dart, lib/web_ui/lib/src/engine/html/shaders/shader.dart, lib/web_ui/lib/src/engine/text/paragraph.dart, lib/web_ui/lib/src/engine/util.dart, lib/web_ui/test/engine/platform_dispatcher/application_switcher_description_test.dart, lib/web_ui/test/engine/platform_dispatcher/system_ui_overlay_style_test.dart, lib/web_ui/test/html/path_to_svg_golden_test.dart
Turning `colorToCssString` into an extension method on `ui.Color` improves null safety and developer ergonomics.
=> [web] Improve null safety for color->css

lib/ui/platform_dispatcher.dart, shell/platform/android/io/flutter/app/FlutterActivity.java, shell/platform/android/io/flutter/app/FlutterActivityDelegate.java, shell/platform/android/io/flutter/app/FlutterActivityEvents.java, shell/platform/android/io/flutter/app/FlutterFragmentActivity.java, shell/platform/android/io/flutter/app/FlutterPluginRegistry.java, shell/platform/android/io/flutter/embedding/android/FlutterActivity.java, shell/platform/android/io/flutter/embedding/android/FlutterActivityAndFragmentDelegate.java, shell/platform/android/io/flutter/embedding/android/FlutterFragment.java, shell/platform/android/io/flutter/embedding/engine/FlutterEngineConnectionRegistry.java, shell/platform/android/io/flutter/embedding/engine/plugins/activity/ActivityPluginBinding.java, shell/platform/android/io/flutter/embedding/engine/plugins/shim/ShimRegistrar.java, shell/platform/android/io/flutter/embedding/engine/systemchannels/LifecycleChannel.java, shell/platform/android/io/flutter/plugin/common/PluginRegistry.java, shell/platform/android/test/io/flutter/embedding/android/FlutterActivityAndFragmentDelegateTest.java, shell/platform/android/test/io/flutter/embedding/engine/systemchannels/LifecycleChannelTest.java
This reverts commit 9183bff56244bf8d9700fb1625bb99d8849f31c4 to re-land #41094 because the Google test failures have been fixed. There are no changes to the original PR, since the fixes were in the Google code.
=> Reland: "Determine lifecycle by looking at window focus also" (#41094)

shell/platform/darwin/macos/framework/Headers/FlutterEngine.h, shell/platform/darwin/macos/framework/Headers/FlutterPluginRegistrarMacOS.h, shell/platform/darwin/macos/framework/Headers/FlutterViewController.h, shell/platform/darwin/macos/framework/Source/FlutterViewController_Internal.h
This is a reland of https://github.com/flutter/engine/pull/39958, but only contains the minimal changes that removes all references to viewId from public interfaces, reverting these changes from https://github.com/flutter/engine/pull/39576.
Flutter doesn't really support multi-view anyway. These methods currently only works for view 0. We better remove them until we mark multi-view stable. It was a mistake that I decided to add them to public interfaces.
For the reason why https://github.com/flutter/engine/pull/39958 failed, I'm pretty sure it's the change to [platform_dispatcher.dart](https://github.com/flutter/engine/pull/39958/files#diff-57d6953e215d0e5dd7260ee60b665c812aa730566ef0b30f7ff1e3d661143585) that mysteriously and unintentionally appeared in the change list.
If you need help, …
=> [macOS] Remove view ID from public 

impeller/tools/malioc_diff.py
Relative paths are required for integrating this tool as a test in engine v2. …
=> Add relative path support for malioc_diff.

impeller/aiks/aiks_unittests.cc, impeller/aiks/canvas.cc
Fixes https://github.com/flutter/flutter/issues/125906.
Fixes https://github.com/flutter/flutter/issues/125908.
Going to add this back once I'm able to work out why the clear colors aren't working on GL/Vulkan. Stepping though with a debugger for both GLES and Vulkan, the clear colors seems to be getting piped through as expected. But the frame captures reveal that they're actually not.
=> [Impeller] Remove the DrawPaint->Clear optimization

testing/run_tests.py
This would have helped me figure out why I wasn't getting the same failures as on CI more quickly.
=> Make run_tests.py assert that the ios test dylib is at least as new as libFlutter.dylib

.ci.yaml, ci/builders/linux_host_engine.json
The artifacts generated by legacy and engine v2 are identical. This PR is moving linux host engine to staging and starts uploading engine v2 artifacts to production. …
=> Migrate linux_host_engine to engine v2.

impeller/display_list/dl_dispatcher.cc
This avoids tessellation if the application draws a Rect or RREct with Path.addRect or Path.addRREct.
=> [Impeller] check if path is Rect/RRect/Oval

shell/platform/darwin/common/framework/Source/FlutterChannelsTest.m
I don't know why this is only flaking on arm64 Macs, but instead of mocking out `NSObject` which seems to continue to be mocked on some background thread, instead mock out the more-specific `FlutterTaskQueue` protocol.  My suspicion is that the `no class for metaclass` is complaining when it tries to get the `isa` off an object's metaclass NSObject but the whole `NSObject` class is mocked out at that point?  Something like that.
Turn the tests back on.
Fixes https://github.com/flutter/flutter/issues/126013
Reverts https://github.com/flutter/engine/pull/41740 …
=> Fix flaky FlutterChannelsTests, stop mocking `NSObject`

shell/platform/android/io/flutter/embedding/engine/systemchannels/TextInputChannel.java, shell/platform/android/io/flutter/plugin/editing/ImeSyncDeferringInsetsCallback.java, shell/platform/android/io/flutter/plugin/editing/TextInputPlugin.java, shell/platform/android/test/io/flutter/plugin/editing/TextInputPluginTest.java
Fix:
- https://github.com/flutter/flutter/issues/123523
- https://github.com/flutter/flutter/issues/124890
https://user-images.githubusercontent.com/30322203/228413196-29c57bb0-3220-495b-9e73-f58777de440f.mp4
https://user-images.githubusercontent.com/30322203/228413249-fc06f49d-6579-4476-9788-90f12a53b8c3.mp4
=> Close connection on keyboard close

tools/fuchsia/merge_and_upload_debug_symbols.py
This also allows passing target files as relative to the src folder. This is required for migrating the fuchsia builds to engine_v2. …
=> Allow default out_dir for fuchsia symbols upload.

impeller/renderer/backend/vulkan/command_encoder_vk.cc, impeller/renderer/backend/vulkan/command_pool_vk.cc
Fixes https://github.com/flutter/flutter/issues/125519
=> [Impeller] Do not free a Vulkan command buffer if its command pool has already been destroyed

lib/ui/window.dart
The engine roll is currently failing (https://cirrus-ci.com/task/5475027185827840?logs=main#L172) because of a doc issue introduced by https://github.com/flutter/engine/pull/41685. This fixes the doc issue.
=> Fix doc to fix engine roll

.ci.yaml, ci/builders/standalone/linux_license.json
This adds the initial configuration and its builder as bringup.
[Discord]: …
=> Add linux license engine v2 build.

display_list/effects/dl_image_filter_unittests.cc
These tests break under Skia's new behaviors when evaluating the bounds of ill-defined filtering operations such as ColorFilters that affect even transparent pixels.
The Flutter engine is currently building with a backwards compatibility flag which we should be able to remove with the new versions of these tests.
=> Adjust DL filter bounds tests to not rely on exact Skia results

lib/web_ui/lib/src/engine/global_styles.dart, lib/web_ui/lib/src/engine/text/canvas_paragraph.dart, lib/web_ui/lib/src/engine/text/paint_service.dart, lib/web_ui/test/engine/global_styles_test.dart, lib/web_ui/test/html/text/canvas_paragraph_builder_test.dart, lib/web_ui/test/html/text/layout_fragmenter_test.dart
The CanvasKit renderer doesn't do this, so we should just remove the red text global style.
=> Get rid of "outrageous" default text styles for HTML renderer.

.ci.yaml
Increase timeout of the orchestrator to ensure it has enough time to process the subbuild results with a 1h timeout. …
=> Increase timeout of orchestrator.

impeller/aiks/canvas.cc, impeller/display_list/dl_dispatcher.cc, impeller/display_list/skia_conversions.cc, impeller/entity/entity_unittests.cc, impeller/entity/geometry.cc, impeller/entity/geometry.h, impeller/geometry/path.cc, impeller/geometry/path.h, impeller/geometry/path_builder.cc, impeller/geometry/path_builder.h
We can do this on the GPU, but we'll need a fallback when we don't have polyline compute.
From experimentation, Skia has already computed this value when Impeller gets that path. Additionally, this will allow us to speed up tessellation of known convex shapes like ovals that we don't want to add special cases for in the API.
=> [Impeller] track path convexity and use it to simplify fill tessellation.

.ci.yaml
Both builds have been running successfully. This PR moves Windows Unopt to staging and Windows windows_unopt to prod. …
=> Replace Windows Unopt with the engine v2 version.

.ci.yaml
Linux license v2 builds has been running successfully for a few days and it is ready to get moved to prod. …
=> Move linux_license to engine v2.

ci/licenses_golden/excluded_files, impeller/renderer/backend/vulkan/BUILD.gn, impeller/renderer/backend/vulkan/command_encoder_vk.cc, impeller/renderer/backend/vulkan/command_pool_vk.cc, impeller/renderer/backend/vulkan/context_vk_unittests.cc
fixes https://github.com/flutter/flutter/issues/125571
[Discord]: …
=> [Impeller] started cleaning up pools when devices are deleted

impeller/typographer/backends/skia/text_render_context_skia.cc, impeller/typographer/typographer_unittests.cc
Fixes https://github.com/flutter/flutter/issues/122839
Fixes https://github.com/flutter/flutter/issues/126103
Unlike Skia which starts with 2048x2048, I decreased the size of 1024x1024. Now that we'll never switch this to a color bitmap, the memory impact is dramatically lessened.
=> [Impeller] Increase minimum size of alpha glyph atlas.

ci/licenses_golden/licenses_flutter, lib/web_ui/lib/src/engine.dart, lib/web_ui/lib/src/engine/semantics/dialog.dart, lib/web_ui/lib/src/engine/semantics/semantics.dart, lib/web_ui/test/engine/semantics/semantics_test.dart
Fixes two issues in dialog accessibility:
* Fixes https://github.com/flutter/flutter/issues/45207 by setting `role="dialog"` on nodes that have both `scopesRoute` and `namesRoute` set. There's no guarantee that this combination of flags is an actual dialog, but it's close enough, and it makes the screen reader announce the appearance of the dialog. Note that `scopesRoute` alone is not sufficient, because Flutter uses it for overlays that are not semantically dialogs, such as dismiss barriers.
* Fixes an issue with focus management, where focus fails to transfer to background content after the dialog is dismissed. This happened because `EngineSemanticsOwner._semanticsTree` retained descendants of parents that were removed. This is benign in many cases. However, for focus this is …
=> [web] dialog a11y fixes

.ci.yaml
Reverts flutter/engine#41865
Failing a framework test on presubmit: https://github.com/flutter/flutter/pull/126452
=> Revert "Move linux fuchsia engine v2 build to prod."

display_list/display_list_unittests.cc, display_list/dl_builder.cc, display_list/dl_builder.h, flow/layers/backdrop_filter_layer_unittests.cc, flow/layers/clip_path_layer_unittests.cc, flow/layers/clip_rect_layer_unittests.cc, flow/layers/clip_rrect_layer_unittests.cc, flow/layers/color_filter_layer_unittests.cc, flow/layers/container_layer_unittests.cc, flow/layers/display_list_layer_unittests.cc, flow/layers/image_filter_layer_unittests.cc, flow/layers/layer_state_stack_unittests.cc, flow/layers/opacity_layer_unittests.cc, flow/layers/shader_mask_layer_unittests.cc, flow/layers/transform_layer_unittests.cc, flow/testing/layer_test.h, testing/mock_canvas.h
Part of an ongoing set of efforts to address https://github.com/flutter/flutter/issues/106448
The layer unittests have been using a MockCanvas class to record the painting of trees of layers and then testing for the expected output.
A while back a similar mechanism was created to compare DisplayList output and to print out a human-friendly version of the differences found, but it was only used in a few tests written at the time it was created and a few since then.
This is the first in a series of PRs that will move all the rest of the unit tests onto the new DL comparison mechanism, starting with the layer types that just do basic drawing. Some of the remaining layers will require creating new hooks in, for instance, the Texture registry, the performance overlay TextBlob generation, etc.
=> switch from MockCanvas to DisplayListBuilder in layer unit tests

shell/platform/darwin/ios/framework/Source/FlutterPlatformViewsTest.mm, shell/platform/darwin/ios/framework/Source/FlutterPlatformViews_Internal.mm
The original code creates an internal `class` which is alarming: 
`NSClassFromString(@"_UIVisualEffectBackdropView")`
This PR removes such usage. 
Fixes https://github.com/flutter/flutter/issues/124008 …
=> [backdrop_filter]Avoid relying on internal class details

ci/licenses_golden/licenses_flutter, lib/web_ui/lib/src/engine.dart, lib/web_ui/lib/src/engine/semantics.dart, lib/web_ui/lib/src/engine/semantics/focusable.dart, lib/web_ui/lib/src/engine/semantics/incrementable.dart, lib/web_ui/lib/src/engine/semantics/semantics.dart, lib/web_ui/lib/src/engine/semantics/tappable.dart, lib/web_ui/test/engine/semantics/semantics_test.dart, lib/web_ui/test/engine/semantics/text_field_test.dart
Introduce 2 new classes for a11y focus management:
* `AccessibilityFocusManager`: a generic class that attaches "focus" and "blur" event handlers, and forwards the events to the framework as `SemanticsAction.didGainAccessibilityFocus` and `SemanticsAction.didLoseAccessibilityFocus` respectively. Provides the `changeFocus` method for the framework to move a11y focus to the target element.
* `Focusable`: a role manager that provides generic focus management functionality to `SemanticsObject`s that don't need anything special.
Rewrites focus management using the above two classes as follows:
* All focusable nodes except text fields and incrementables get the `Focusable` role (all custom focus stuff in `Tappable` was removed and delegated to `Focusable`).
* `Incrementable` uses a custom …
=> [web] generalize focusability in semantics

shell/platform/darwin/macos/framework/Source/FlutterEngineTest.mm
These tests are flaky. Until they've been deflaked, disable the following two tests:
* FlutterEngineTest.BackgroundIsBlack
* FlutterEngineTest.CanOverrideBackgroundColor
Issue: https://github.com/flutter/flutter/issues/124677 …
=> [macos] Disable background colour tests

common/graphics/texture.h, display_list/dl_builder.h, flow/layers/texture_layer_unittests.cc, flow/testing/mock_texture.cc, flow/testing/mock_texture.h, flow/testing/mock_texture_unittests.cc
Part of an ongoing set of efforts to address https://github.com/flutter/flutter/issues/106448
MockTexture now executes a call on the supplied DlCanvas object rather than creating its own list of MockCanvas-style draw calls. The TextureLayer tests now no longer use MockCanvas.
=> switch MockTexture off of MockCanvas calls

tools/gn
allows to supply gn args that do not have their cli switches (yet), like this:
```sh
python3 ./tools/gn --gn-args 'use_default_linux_sysroot=false'
```
https://github.com/flutter/flutter/issues/126197 …
=> allow supplying custom gn args in gn wrapper

lib/ui/painting/image_decoder_skia.cc, shell/platform/embedder/embedder_external_texture_gl.cc
Use relocated SkImages context typedefs
In http://review.skia.org/661059, we moved many SkImage related methods, including these typedefs. This updates Flutter to use the moved types. …
=> Use moved SkImage procs

shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.h, shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm, shell/platform/darwin/ios/framework/Source/FlutterTextInputPluginTest.mm
Floating cursor selection hasn't worked as we haven't been returning a real value for `caretRectForPosition:`. If we have the selection rectangles, we can do so. 
Fixes [#30476](https://github.com/flutter/flutter/issues/30476)
Requires selection rects to be turned on for iPhone (https://github.com/flutter/flutter/pull/113048)
=> iPhone floating cursor selection

impeller/renderer/renderer_unittests.cc, impeller/renderer/vertex_buffer_builder.h
Followup from https://github.com/flutter/flutter/issues/126572
=> [Impeller] Dont synthesize fake index buffer if none was provided to VBB

.ci.yaml
The mac clang tidy build has been running successfully on staging for several days. This is also moving the ios and host legacy clang tidy builds to staging. …
=> Move clang tidy v2 build to prod.

lib/web_ui/lib/src/engine/browser_detection.dart, lib/web_ui/test/canvaskit/canvaskit_api_test.dart, lib/web_ui/test/engine/browser_detect_test.dart
`Chrome < v87` have the `v8BreakIterator` API but don't have `Intl.Segmenter`. This caused crashes for some apps (see b/281377168).
This PR enhances our feature detection to take into account this API mismatch.
=> [web] Fix crash on old versions of Chrome (Intl.Segmenter missing)

ci/builders/mac_host_engine.json, impeller/golden_tests/BUILD.gn, impeller/golden_tests/golden_playground_test.h, impeller/golden_tests/golden_playground_test_mac.cc, impeller/golden_tests/golden_playground_test_stub.cc, testing/run_tests.py
fixes https://github.com/flutter/flutter/issues/126022
[Discord]: …
=> [Impeller] starts running vulkan golden image tests with swiftshader

lib/web_ui/lib/src/engine/raw_keyboard.dart, lib/web_ui/test/engine/raw_keyboard_test.dart
This PR fixes Meta keys throwing exception on Chrome Linux.
The assertions throws because the DOM event sent when Meta keys is pressed is not coherent when Meta is the only pressed key.
Fixes https://github.com/flutter/flutter/issues/125672
Adds 1 test.
=> [Web+Linux] Fix pressing Meta keys throws

impeller/display_list/dl_dispatcher.cc, impeller/geometry/geometry_unittests.cc, impeller/geometry/matrix.cc, impeller/geometry/matrix.h
Fixes https://github.com/flutter/flutter/issues/126510.
`GetMaxBasisLength()` includes the Z basis vector, which happens to not be getting scaled down along with the X and Y for this reproduction case. And so given the 2D nature of text and the intent of this scale parameter, it's returning a value that's too large here.
We just haven't encountered this situation before because usually all dimensions of the matrix get scaled down, or point size of the text gets decreased instead
Before:
After:
=> [Impeller] Ignore the Z basis when scaling text

shell/platform/darwin/macos/framework/Source/FlutterTextInputPlugin.mm, shell/platform/darwin/macos/framework/Source/FlutterTextInputPluginTest.mm
This PR updates the macOS text input plugin to avoid adding a new line on a multiline text field when action is not set to `TextInputAction.newline`.
macOS implementation for https://github.com/flutter/flutter/issues/125879.
(similar to the Linux implementation in https://github.com/flutter/engine/pull/41895).
Adds 2 tests.
=> [macOS - TextInput] Insert new line only when TextInputAction.newline

display_list/benchmarking/dl_complexity_unittests.cc, display_list/display_list.cc, display_list/display_list.h, display_list/display_list_unittests.cc, display_list/dl_builder.cc, display_list/dl_builder.h, display_list/dl_color.h, display_list/dl_paint.h, display_list/testing/dl_rendering_unittests.cc, display_list/testing/dl_test_snippets.cc, display_list/testing/dl_test_snippets.h, display_list/utils/dl_matrix_clip_tracker.h, flow/diff_context_unittests.cc, flow/layers/container_layer_unittests.cc, flow/layers/display_list_layer_unittests.cc, flow/layers/opacity_layer_unittests.cc, flow/testing/diff_context_test.cc, flow/testing/diff_context_test.h, impeller/display_list/dl_unittests.cc, shell/common/dl_op_spy.cc, shell/common/dl_op_spy_unittests.cc
This optimization avoids recording unnecessary render operations that will not affect the output and also eliminates the need for "draw detection" mechanisms like `DlOpSpy` and `CanvasSpy` by remembering if any non-transparent operations were included. The `DlOpSpy` unit tests were updated to check if the results from that object match the new `DisplayList::affects_transparent_surface()` method.
Fixes https://github.com/flutter/flutter/issues/125338
In addition, this change will unblock some other Issues:
- https://github.com/flutter/flutter/issues/125318
- https://github.com/flutter/flutter/issues/125403
=> add non-rendering operation culling to DisplayListBuilder

tools/gn
Reverts flutter/engine#41940
See b/282115120
This caused a golden failure on Google Testing where a rectangular avatar became circular.
=> Revert "Remove GN staging flag for save layer bounds"

tools/gn
Reverts flutter/engine#42026
After investigating, this is a bug fix for the scubas.
=> Reland "Remove GN staging flag for save layer bounds"

shell/platform/android/platform_view_android.cc
Fixes b/282290672
Google Testing currently does not support vulkan, and constructors like this need to be behind a flag.
=> [Impeller] Include AndroidSurfaceVulkanImpeller behind a flag

shell/gpu/gpu_surface_metal_impeller.mm, shell/platform/darwin/ios/framework/Source/FlutterView.mm
**requires https://github.com/flutter/flutter/pull/126712 to land first**
fixes https://github.com/flutter/flutter/issues/126620
integration test at: https://github.com/flutter/flutter/pull/126715 …
=> [Impeller] switches the wide gamut surface to f16

testing/run_tests.py, testing/scenario_app/run_ios_tests.sh
Taking over from https://github.com/flutter/engine/pull/41644
fixes: https://github.com/flutter/flutter/issues/125823
Steps to verify …
=> Upload xcresults to LUCI cloud storage

impeller/aiks/aiks_unittests.cc, impeller/golden_tests/golden_playground_test_mac.cc
Made this to help debugging clear color problems and I've had it sitting around in my stage for a few days. Today, it ended up leading me to discover several other issues. For example, advanced blends are doing nothing in this case...
=> [Impeller] Add interactive DrawPaint blend test

.ci.yaml
Release_build property is used to signal that this build produces release artifacts that will eventually be SLSA compliant and will need to run from dart_internal.
The os property is used to select the correct drone based on the platform the build should run on.
Bug: https://github.com/flutter/flutter/issues/126118
Bug: https://github.com/flutter/flutter/issues/125983
Bug: https://github.com/flutter/flutter/issues/126116 …
=> Use release_build and os dimension consistently.

impeller/display_list/display_list_dispatcher.cc, impeller/display_list/display_list_unittests.cc, impeller/entity/contents/rrect_shadow_contents.cc, impeller/entity/contents/rrect_shadow_contents.h
cherry-pick of https://github.com/flutter/engine/pull/41391
=> [Impeller] Fix division by zero for transparent shadows (#41391)

impeller/entity/entity_pass.cc
=> [Impeller] Remove debug print statement from EntityPass

.ci.yaml
CP: 027ca797985f1475857913096f49baec29347f35
[Discord]: …
=> CP: Use release_build and os dimension consistently. (#42012)

.ci.yaml
This is to make the configs easier to use for builders running from a drone. …
=> Add drone_dimensions as top level target property.

shell/platform/darwin/ios/framework/Source/FlutterPlatformViews.mm, shell/platform/darwin/ios/framework/Source/FlutterPlatformViewsTest.mm
Add a class type check during reset when removing the PlatformViews.
Fixes: https://github.com/flutter/flutter/issues/125999 …
=> [ios_platform_view] Only remove platform views from flutter view in reset.

.ci.yaml, ci/builders/linux_clang_tidy.json
This builder run android and host clang tidy in an engine v2 build.
[Discord]: …
=> Add linux_clang_tidy builder.

.ci.yaml
The host engine was using a top level dimension instead of a drone dimension and was causing the dart-internal build to fail. …
=> Fix drone_dimension host_engine_builder.

shell/platform/windows/client_wrapper/flutter_view_controller.cc, shell/platform/windows/client_wrapper/flutter_view_controller_unittests.cc, shell/platform/windows/client_wrapper/include/flutter/flutter_view_controller.h, shell/platform/windows/client_wrapper/testing/stub_flutter_windows_api.cc, shell/platform/windows/client_wrapper/testing/stub_flutter_windows_api.h, shell/platform/windows/public/flutter_windows.h
This change adds a C++ client wrapper to Windows's "force redraw" C API. This API can be used to schedule a frame.
Part of https://github.com/flutter/flutter/issues/119415
The Windows runner has a race at startup:
1. **Platform thread**: creates a hidden window
2. **Platform thread**: launches the Flutter engine
3. **UI/Raster threads**: renders the first frame
4. **Platform thread**: Registers a callback to show the window once the next frame has been rendered.
Steps 3 and 4 happen in parallel and it is possible for step 3 to complete before step 4 starts. In this scenario, the next frame callback is never called and the window is never shown.
The Windows runner will be updated to call the "force redraw" API after it registers the next frame callback. If step 3 hasn't completed yet, the …
=> [Windows] Add force redraw to the C++ client wrapper

shell/platform/linux/fl_platform_plugin.cc, shell/platform/linux/fl_platform_plugin.h, shell/platform/linux/fl_platform_plugin_test.cc
Similar to https://github.com/flutter/engine/pull/41733 and https://github.com/flutter/engine/pull/41753 this causes the linux embedding to wait until it hears that the scheduler binding has registered itself before proceeding to send termination requests to the framework.
This allows applications that don't use the framework (just use `dart:ui` directly) to exit automatically when the last window is closed.  Without this change, the app does not exit when the window is closed.
Depends on framework PR https://github.com/flutter/flutter/pull/126075 landing first.
- https://github.com/flutter/engine/pull/41733
- https://github.com/flutter/engine/pull/41753
- https://github.com/flutter/flutter/issues/126033.
- Added a test to make sure that it doesn't send a termination request if the …
=> [linux] Wait for binding to be ready before requesting exits from framework

shell/platform/darwin/macos/framework/Source/FlutterAppDelegate.mm, shell/platform/darwin/macos/framework/Source/FlutterEngine.mm, shell/platform/darwin/macos/framework/Source/FlutterEngineTest.mm, shell/platform/darwin/macos/framework/Source/FlutterEngine_Internal.h
Similar to https://github.com/flutter/engine/pull/41733 and https://github.com/flutter/engine/pull/41782, this causes the macos embedding to wait until it hears that the scheduler binding has registered itself before proceeding to send termination requests to the framework.
This allows applications that don't use the framework (just use `dart:ui` directly) to exit automatically when the last window is closed.  Without this change, the last window closes, but the app does not exit.
Depends on framework PR https://github.com/flutter/flutter/pull/126075 landing first.
- https://github.com/flutter/engine/pull/41733
- https://github.com/flutter/engine/pull/41782
- https://github.com/flutter/flutter/issues/126033.
- Added a test to make sure that it doesn't send a termination request if the …
=> [macOS] Wait for binding to be ready before requesting exits from framework

impeller/compiler/shader_lib/impeller/gaussian.glsl, impeller/entity/entity_unittests.cc, impeller/entity/shaders/gaussian_blur/gaussian_blur.glsl, impeller/entity/shaders/rrect_blur.frag
Resolves https://github.com/flutter/flutter/issues/126487.
Increases the 2-pass blur quality and distribution limit.
It turns out sigma was breaking down beyond ~255 (moderately high, but not unreasonable for users to rely on). The Gaussian function computes sigma^2, and half precision floats only have 5 bit exponents and overflow for numbers above 65k.
Coincidentally, this also returns us to a state where we look a lot more like Skia's blurs for larger blur sigmas. Medium blurs have much less visual banding (although it's still there if you look closely). I suspect half precision isn't really enough for tracking the integral.
Unfortunately, this means our SIMD pipelining isn't going to be as good. I'll be interested in watching the blur-driven benchmarks for the perf hit.
Before …
=> [Impeller] Use 32 bit Gaussian function in the 2-pass blur

.ci.yaml
CP: 3d645f3d7df274504569da04f9793d052ab7f9e6
[Discord]: …
=> CP: Fix drone_dimension host_engine_builder. (#42068)

shell/platform/darwin/ios/framework/Source/FlutterDartProject.mm
relands flutter/engine#39801
forward fix for internal customers at cl/531288297 …
=> [Impeller] Turned on wide gamut support by default. (#39801)

impeller/aiks/aiks_unittests.cc, impeller/entity/contents/tiled_texture_contents.cc, impeller/entity/geometry.cc
Fixes https://github.com/flutter/flutter/issues/126739
When we're sampling from the texture, we need to sample from its origin regardless of how much offset the stroke width gives to the path.
=> Fix bounds when painting style is stroke width for image shaders

shell/platform/darwin/macos/framework/Source/FlutterEngine.mm, shell/platform/darwin/macos/framework/Source/FlutterEngineTest.mm, shell/platform/embedder/embedder.cc, shell/platform/embedder/embedder.h
https://github.com/flutter/flutter/issues/125939 and https://github.com/flutter/flutter/issues/125938 for macOS
fixes https://github.com/flutter/flutter/issues/121352
=> Report displays for macOS

impeller/renderer/compute_subgroup_unittests.cc
We must wait until the compute command buffer has completed before its safe to use the contents of that buffer. THis fixes the flickering I've observed when running the unit test locally.
Test only change, no impact to shipped code.
=> [Impelller] fix flickering due to synchronization issues in compute tessellator.

shell/platform/darwin/macos/framework/Source/FlutterMutatorView.mm
When applying platform view mutators, the mutations array includes a transform from logical to physical coordinates. Since Cocoa deals only in logical points, we inject a physical to logical coordinate transform to counteract this.
Rather than applying this multiple times throughout the `[FlutterMutatorView applyFlutterLayer]` method we gather a list of transforms that includes the additional physical to logical scale transform.
This change is a cleanup change for readability and makes no semantic changes to how mutator views are applied. Existing unit tests in [FlutterMutatorViewTest.mm](https://github.com/flutter/engine/blob/main/shell/platform/darwin/macos/framework/Source/FlutterMutatorViewTest.mm) are expected to pass without changes.
If you need help, consider asking for advice on …
=> [macOS] Clean up PlatformView mutator scaling

.github/workflows/third_party_scan.yml
The lack of permissions on the vulnerability scanning github actions yaml will cause all runs to fail at the upload SARIF to security tab stage. This change adds the permissions for that stage to succeed.
A successful test run is can be seen here: https://github.com/flutter/engine/actions/runs/5006551387/jobs/8971979211
[C++, …
=> Vuln scan github actions permissions

.github/release.yml
GitHub's automated changelog generation allows teams to setup a configuration file to determine how these changelogs will be generated.  
A similar file is available in flutter/flutter for release note generation.  As tags have been added to flutter/engine, we now have the ability to generate release notes in the same fashion.
=> Add configuration for automating release notes

impeller/aiks/aiks_unittests.cc, impeller/entity/contents/tiled_texture_contents.cc, impeller/entity/geometry.cc
Fixes https://github.com/flutter/flutter/issues/126739
When we're sampling from the texture, we need to sample from its origin regardless of how much offset the stroke width gives to the path.
=> [CP] [Impeller] Fix bounds when painting style is stroke width for image shaders (#42052)

shell/platform/darwin/ios/framework/Source/FlutterAppDelegate.mm, shell/platform/darwin/ios/framework/Source/FlutterAppDelegateTest.mm
related https://github.com/flutter/flutter/issues/100624
[Discord]: …
=> Make iOS embedding to send full uri for deeplinks

shell/platform/android/io/flutter/embedding/android/FlutterActivityAndFragmentDelegate.java, shell/platform/android/io/flutter/view/FlutterView.java, shell/platform/android/test/io/flutter/embedding/android/FlutterActivityAndFragmentDelegateTest.java
related https://github.com/flutter/flutter/issues/100624
[Discord]: …
=> Makes android embedding to send full uri

lib/web_ui/lib/src/engine/semantics/checkable.dart, lib/web_ui/lib/src/engine/semantics/dialog.dart, lib/web_ui/lib/src/engine/semantics/focusable.dart, lib/web_ui/lib/src/engine/semantics/image.dart, lib/web_ui/lib/src/engine/semantics/incrementable.dart, lib/web_ui/lib/src/engine/semantics/label_and_value.dart, lib/web_ui/lib/src/engine/semantics/live_region.dart, lib/web_ui/lib/src/engine/semantics/scrollable.dart, lib/web_ui/lib/src/engine/semantics/semantics.dart, lib/web_ui/lib/src/engine/semantics/tappable.dart, lib/web_ui/lib/src/engine/semantics/text_field.dart, lib/web_ui/test/engine/semantics/semantics_test.dart
Add a new `RouteName` semantic role for nodes with `namesRoute` set without a `scopesRoute`. Such nodes provide a description for the nearest ancestor dialog node. The web equivalent of this is when an element `role="dialog"` is described by pointing to one of its children using `aria-labelledby` and `aria-describedby`. Here's an example:
```
<div
role="dialog"
aria-labelledby="dialog1Title"
aria-describedby="dialog1Desc">
<h2 id="dialog1Title">Your personal details were successfully updated</h2>
<p id="dialog1Desc">
You can change your details at any time in the user account section.
</p>
<button>Close</button>
</div>
```
([Source](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/dialog_role))
Flutter currently does not distinguish between "labelled by" and …
=> [web:a11y] support dialogs described by descendants

shell/platform/android/io/flutter/plugin/common/BasicMessageChannel.java, shell/platform/android/test/io/flutter/plugin/common/MethodChannelTest.java
This PR updates `BasicMessageChannel.resizeChannelBuffer` implementation. Previous implementation builds a wrong `ByteBuffer` and was not tested so it is difficult to know when it stopped working.  
Fixes https://github.com/flutter/flutter/issues/126632
Adds 1 test.
=> [Android] Fix BasicMessageChannel.resizeChannelBuffer

shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm
Many parts of the floating cursor selection feature is pretty tricky. Some took me a while to figure out. So I added some comments to explain a bit for future readers. 
https://github.com/flutter/flutter/issues/30476 …
=> [floating_cursor_selection]add some comments on the tricky part

impeller/aiks/aiks_unittests.cc, impeller/entity/contents/filters/gaussian_blur_filter_contents.cc
Resolves https://github.com/flutter/flutter/issues/127151.
This is the same internal limit that Skia uses.
=> [Impeller] Limit blur kernel to 1000x1000 pixels

shell/platform/darwin/macos/framework/Source/FlutterMutatorView.mm
Extracts `updatePathClipViewsWithPaths:origin:` which updates the stack of AppKit clip views hosting the platform view.
This change is a cleanup change for readability and makes no semantic changes to how mutator views are applied. Existing unit tests in [FlutterMutatorViewTest.mm](https://github.com/flutter/engine/blob/main/shell/platform/darwin/macos/framework/Source/FlutterMutatorViewTest.mm) are expected to pass without changes.
This is refactoring prior to applying a fix for rotation handling.
Issue: https://github.com/flutter/flutter/issues/124490 …
=> [macOS] Extract PlatformView mutator clip updating

shell/platform/darwin/ios/framework/Source/SemanticsObject.mm, shell/platform/darwin/ios/framework/Source/SemanticsObjectTest.mm
fixes https://github.com/flutter/flutter/issues/61624
Observed behavior is that this method is called when an item is swipe-to-focusd in VoiceOver. …
=> Overrides accessibilityScrollToVisible

impeller/aiks/aiks_unittests.cc, impeller/entity/geometry.cc
cp of https://github.com/flutter/engine/pull/42155
=> [CP] [Impeller] Fix the issue that 'coverage_coords' is incorrectly calculated in 'FillPathGeometry::GetPositionUVBuffer' #42155

ci/licenses_golden/tool_signature, tools/licenses/lib/paths.dart
third_party/boringssl/src/rust/bssl-crypto/deny.toml coming in as part of https://dart-review.googlesource.com/c/sdk/+/304210 triggers 'potential license' license script error.
Rust sources of boringssl are not included into flutter, don't need to be scanned for licenses.
=> Skip and ignore boringssl/src/rust when looking for the licenses.

ci/licenses_golden/licenses_flutter, impeller/aiks/aiks_unittests.cc, impeller/entity/BUILD.gn, impeller/entity/contents/content_context.cc, impeller/entity/contents/content_context.h, impeller/entity/geometry.cc, impeller/entity/geometry.h, impeller/entity/shaders/geometry/uv.comp, impeller/tools/malioc.json
Adds a compute shader that computes the UV mapping for an arbitrary geometry. Use it with drawPoints since I didn't realize it was possible to use an image shader with this 😆 .
=> [Impeller] Add UV compute shader.

impeller/entity/contents/color_source_text_contents.cc, impeller/entity/contents/text_contents.cc, impeller/entity/contents/text_contents.h
Previously this was attempting to invert the TransformBounds done by GetCoverage.  TransformBounds computes a bounding box of the transformed rectangle and can not be reversed.
Fixes https://github.com/flutter/flutter/issues/127103
=> [Impeller] Use untransformed text bounds to calculate the size of ColorSourceTextContents

lib/ui/painting/display_list_deferred_image_gpu_impeller.h, lib/ui/painting/display_list_deferred_image_gpu_skia.h
Find this when reading source code today...
Btw, what about introducing a spell checker to Flutter source code? ;) …
=> Again a two-word super tiny typo

lib/ui/fixtures/ui_test.dart, lib/ui/painting.dart, lib/ui/painting/image_decoder.h, lib/ui/painting/image_decoder_impeller.cc, lib/ui/painting/image_decoder_impeller.h, lib/ui/painting/image_decoder_skia.cc, lib/ui/painting/image_decoder_unittests.cc, lib/ui/painting/multi_frame_codec.cc, lib/ui/painting/multi_frame_codec.h, lib/ui/painting/single_frame_codec.cc, shell/common/fixtures/shell_test.dart
Fixes https://github.com/flutter/flutter/issues/127061
See https://github.com/flutter/flutter/issues/126768
=> [Impeller] Return image decoder error messages to the Dart API

shell/platform/fuchsia/flutter/flatland_platform_view.cc
This CL posts ChildViewWatcher calls on platform thread.
Bug: fxb/125256
=> [fuchsia] Bind ChildViewWatcher on platform thread

fml/logging.cc, fml/logging_unittests.cc
I ran into this while trying to get some printing going for places where we're creating thread local keys. 
Supposedly, just including `<iostream>` should statically initialize `std::cout/cerr`, but it gets really hard to reason about whether your statically initialized code is going to be initialized before or after that happens. I tried making sure that the TU for `fml/logging.cc` did that initialization statically, but that also failed in the verison of the test included here (it passed in some other iterations that modified run_all_unittests.cc). We _could_ make sure it happens each and every time we touch `std::cerr` but ... we could also just use `fprintf(stderr, ...)` and it works just fine.
/cc @flar who ran into problems around this a little while back and was asking about it.
=> Make FML_LOG safe from static initialization

DEPS
The package leak_tracker was added to Dart DEPS, and analysis_server now depends on it.
This fixes a breakage when rolling Dart into Flutter engine.
Bug: https://github.com/flutter/devtools/issues/5606
=> Add leak_tracker package from Dart DEPS to DEPS

.pylintrc, ci/builders/mac_host_engine.json, ci/licenses_golden/excluded_files, sky/tools/create_embedder_framework.py
This PR modifies the mac_host_engine build config to build the FlutterEmbedder.framework for arm64, and adds a generator that creates a fat framework containing both the intel and arm64 dylibs. The fat framework is uploaded to the gcs bucket instead of the thin intel-only one.
The script to create the lipo'd embedder framework is different enough from the desktop framework to have a separate script, but this still triggers the pylint duplicate-code check. Due to a bug in our version of pylint (https://github.com/pylint-dev/pylint/issues/214), it isn't possible to disable per-file, so this PR also disables the check globally.
=> Build arm64 FlutterEmbedder.framework and lipo the result

impeller/renderer/backend/vulkan/allocator_vk.cc, impeller/renderer/backend/vulkan/allocator_vk.h, impeller/renderer/backend/vulkan/blit_command_vk_unittests.cc, impeller/renderer/backend/vulkan/command_pool_vk.cc, impeller/renderer/backend/vulkan/context_vk.cc, impeller/renderer/backend/vulkan/context_vk.h, impeller/renderer/backend/vulkan/fence_waiter_vk.cc, impeller/renderer/backend/vulkan/fence_waiter_vk.h, impeller/renderer/backend/vulkan/sampler_library_vk.cc, impeller/renderer/backend/vulkan/sampler_library_vk.h
Removes the last ivars that hold onto a `Device` directly.  This have recently been the cause of crashes, so the safer thing is to remove them all.
For the Allocator and the Sampler library, removing the device ivars is likely just a precaution since they should have only been accessed from the raster thread and killed before the Device.  The fence waiter however was potentially accessing the device from a separate thread, so that was much more risky and likely to cause crashes.
Testing: The existing `impeller_unittests` verify this is setup correctly. …
=> [Impeller] Removed last ivars to raw vk::Device's.

.github/workflows/third_party_scan.yml
Reverts flutter/engine#42247
Reverting in order to find solution which doesn't add a skipped test onto all PRs. Only PRs which address vuln scanning need to have this test showing at all.
=> Revert "Vuln scan on 3p deps triggered by label on PR"

ci/builders/mac_host_engine.json, flow/frame_timings.cc, flow/frame_timings.h, flow/frame_timings_recorder_unittests.cc, fml/macros.h, testing/run_tests.py
I refactored the `EXPECT_EXIT` tests since they are unsafe to execute in a process with multiple threads.
This leaves `flutter_desktop_darwin_unittests` disabled since it has existing issues.
fixes https://github.com/flutter/flutter/issues/103757
[CLA]: …
=> Turned back on debug unit tests

impeller/aiks/aiks_unittests.cc, impeller/entity/entity_pass.cc
Attaches a minimum coverage hint to all rendered entities. This makes ImageFilter blurs do less work when clipped. We can utilize this in a number of other filters as well.
The test I added also demonstrates a sampling issue in the gaussian blur that I'm trying to work out. Here it is without any clipping. This coverage hint change does not introduce the issue:
=> [Impeller] Set the coverage hint on everything

lib/web_ui/lib/src/engine/pointer_binding/event_position_helper.dart, lib/web_ui/test/engine/pointer_binding/event_position_helper_test.dart
This cherry-pick backports flutter/engine#41870 to Flutter 3.10.
* git cherry-pick 4f3f7bb (+ conflict fixes)
Original commit message below:
[web] Fix event offset for transformed widgets (and text input nodes). (#41870)
Text inputs have moved outside of the shadowDOM and are now using the pointer event offset calculation algorithm that platform views use.  However, transforms (e.g. scaling) applied to the input element aren't currently accounted for, which leads to incorrect offsets and clicks being registered inaccurately.
This PR attempts to transform those offset coordinates using the transform matrix data that is included in the geometry information sent over to `text_editing.dart` from the framework.
* Fixes https://github.com/flutter/flutter/issues/125948 (text editing)
* Fixes …
=> [CP][web] Fix event offset on transformed widgets.

impeller/aiks/aiks_unittests.cc
Part of https://github.com/flutter/flutter/issues/127013.
This is a repro to track the mask blur issues. If we accidentally trigger the wrong kind of blur, this golden will make it obvious because the gradient lines will become much more blurry.
Once this problem is fixed, the circle's mask should be fully blurred and the rounded rectangle should have no edge clamping (the diagonal lines should continue as the edges fade to black).
=> [Impeller] Add golden repro for mask blur issues

impeller/entity/contents/contents.cc, impeller/geometry/geometry_unittests.cc, impeller/geometry/rect.h
Everything in Impeller is theoretically treated as if being drawn to layers of infinite size. Without this change, there's a coverage leak that occurs in some filters due to the customizable sampling mode. I should be able to get rid of this 1 pixel padding by refactoring the way we do sampling in the filter inputs (we already have most of this infrastructure in place), but this is a correct, safe, and not-that-expensive solution for the time being.
Also, this fixes a potential segfault due to an unsafe optional access... (would really love if there was a static analysis check for this -- it's by far the number one way I push crashers).
Before:
After:
=> [Impeller] Add 1 pixel border to snapshots of Contents

flow/layers/layer_tree.cc
This function creates a Skia bitmap that can not be rendered by Impeller.
See https://github.com/flutter/flutter/issues/127080
=> [Impeller] Disable the offscreen layer checkerboard drawing function on Impeller.

ci/licenses_golden/licenses_flutter, fml/BUILD.gn, fml/platform/darwin/scoped_nsautorelease_pool.cc, fml/platform/darwin/scoped_nsautorelease_pool.h, impeller/golden_tests/golden_playground_test.h, impeller/playground/playground.cc, impeller/playground/playground_test.h
See https://github.com/flutter/flutter/issues/127358
=> [Impeller] Create an autorelease pool for Impeller tests running on macOS.

impeller/renderer/backend/metal/surface_mtl.mm
This fixed things for me locally. Confirmed frame captures work and this block otherwise doesn't fire when running regularly
=> [Impeller] fix Xcode frame capture.

lib/web_ui/lib/src/engine/semantics/accessibility.dart, lib/web_ui/test/engine/semantics/accessibility_test.dart
This also removes the appended divs after a short time so that screen readers don't navigate to it, especially when users are entering the DOM to enable accessiblity.
Fixes https://github.com/flutter/flutter/issues/127335.
=> [web] Update a11y announcements to append divs instead of setting content.

lib/web_ui/lib/src/engine/text/ruler.dart
Migration has already happened in [this PR](https://github.com/flutter/engine/pull/33370/files#diff-30cfc07b03caec6d1c915b40a9e50a23d1f1a1c54c670d5996199d805b077daeR213) so the comment is not relevant anymore.
=> [web] Remove comment about dart:html migration

impeller/aiks/aiks_unittests.cc
See https://github.com/flutter/engine/pull/42142
=> [Impeller] Golden test for text with a shader and a transform

.ci.yaml
This is removing the legacy builds from recipes testing and adding the engine v2 ones. …
=> Use engine_v2 builds on recipe testing.

DEPS, ci/builders/mac_host_engine.json, impeller/BUILD.gn, impeller/playground/playground.cc, testing/run_tests.py, tools/gn
This uses swiftshader to run the tests on mac.
[Discord]: …
=> [Impeller] Turn on vulkan tests for mac CI.

.ci.yaml
Part of https://github.com/flutter/flutter/issues/127534
=> Append $flutter/osx sdk property to existing platforms/targets relying on xcode

impeller/aiks/paint.cc, impeller/aiks/paint.h
Came across this while working on generic fallbacks for mask blurs. For the unique_ptr case, we always capture ownership and convert to a shared_ptr anyhow. For the shared_ptr case, we always need to capture a copy, and so better to not take a const ref and allow the caller to move if possible.
=> [Impeller] Simplify CreateContentsForGeometry overloads

impeller/aiks/paint.cc, impeller/aiks/paint.h, impeller/entity/contents/color_source_contents.h
Resolves https://github.com/flutter/flutter/issues/127013.
Makes mask blurs work for most color source + geometry combinations. Crucially, this doesn't interfere with the fast paths for solid color RRect blurs (used for shadows).
I'll be addressing mask blurs for text in a follow-up.
Before:
After:
=> [Impeller] Add generic path for mask blurring

lib/web_ui/lib/src/engine/platform_dispatcher.dart, lib/web_ui/lib/src/engine/window.dart, lib/web_ui/test/engine/platform_dispatcher/platform_dispatcher_test.dart
=> Implement PlatformDispatcher.displays on web

shell/platform/darwin/macos/framework/Source/FlutterViewController.mm, shell/platform/darwin/macos/framework/Source/FlutterViewControllerTest.mm
Fixes https://github.com/flutter/flutter/issues/127572
[Discord]: …
=> [macOS] Fix FlutterViewController retain cycle

DEPS, third_party/txt/BUILD.gn
This is the engine counterpart for https://github.com/flutter/buildroot/pull/701. That pull-request contains more context and the main motivation for this change.
This should fix some startup performance issues related to font loading on desktop linux: https://github.com/flutter/flutter/issues/118911. …
=> Dynamically link against system fontconfig

display_list/benchmarking/dl_complexity_helper.h, display_list/display_list_unittests.cc, display_list/dl_builder.cc, display_list/dl_builder.h, display_list/dl_op_receiver.h, display_list/dl_op_records.h, display_list/dl_paint.cc, display_list/dl_paint_unittests.cc, display_list/skia/dl_sk_paint_dispatcher.cc, display_list/skia/dl_sk_paint_dispatcher.h, display_list/testing/dl_test_snippets.cc, display_list/utils/dl_matrix_clip_tracker.cc, display_list/utils/dl_matrix_clip_tracker.h, display_list/utils/dl_receiver_utils.h, flow/layers/checkerboard_layertree_unittests.cc, flow/testing/layer_test.h, impeller/display_list/dl_dispatcher.cc, impeller/display_list/dl_dispatcher.h, testing/display_list_testing.cc, testing/display_list_testing.h
Part of an ongoing set of efforts to address https://github.com/flutter/flutter/issues/106448
Move the checkerboard layer unit tests onto the DisplayList version of the paint contexts and fix some bugs in the reusability of the DisplayListBuilder that this migration uncovered.
=> Move checkerboard unit tests onto DisplayList mechanism

shell/platform/darwin/ios/framework/Source/FlutterDartProject.mm, shell/platform/darwin/ios/framework/Source/FlutterView.mm
Wide gamut is not supported on the iOS simulator, and the iOS platform's FlutterView.isWideGamutSupported checked for this.  However, the ImageDecoder decides whether to enable wide gamut based on the engine's settings, so the flag in the settings needs to be modified for the simulator.
=> [Impeller] Disable the wide gamut settings flag on iOS simulators

ci/licenses_golden/licenses_flutter, lib/web_ui/lib/src/engine/canvaskit/canvaskit_api.dart, lib/web_ui/lib/src/engine/canvaskit/native_memory.dart, lib/web_ui/lib/src/engine/dom.dart, lib/web_ui/lib/src/engine/skwasm/skwasm_impl.dart, lib/web_ui/lib/src/engine/skwasm/skwasm_impl/canvas.dart, lib/web_ui/lib/src/engine/skwasm/skwasm_impl/filters.dart, lib/web_ui/lib/src/engine/skwasm/skwasm_impl/font_collection.dart, lib/web_ui/lib/src/engine/skwasm/skwasm_impl/image.dart, lib/web_ui/lib/src/engine/skwasm/skwasm_impl/memory.dart, lib/web_ui/lib/src/engine/skwasm/skwasm_impl/paint.dart, lib/web_ui/lib/src/engine/skwasm/skwasm_impl/paragraph.dart, lib/web_ui/lib/src/engine/skwasm/skwasm_impl/path.dart, lib/web_ui/lib/src/engine/skwasm/skwasm_impl/path_metrics.dart, lib/web_ui/lib/src/engine/skwasm/skwasm_impl/picture.dart, lib/web_ui/lib/src/engine/skwasm/skwasm_impl/raw/raw_canvas.dart, lib/web_ui/lib/src/engine/skwasm/skwasm_impl/raw/raw_paint.dart, lib/web_ui/lib/src/engine/skwasm/skwasm_impl/raw/raw_path.dart, lib/web_ui/lib/src/engine/skwasm/skwasm_impl/raw/raw_path_metrics.dart, lib/web_ui/lib/src/engine/skwasm/skwasm_impl/raw/raw_picture.dart, lib/web_ui/lib/src/engine/skwasm/skwasm_impl/renderer.dart, lib/web_ui/lib/src/engine/skwasm/skwasm_impl/shaders.dart, lib/web_ui/lib/src/engine/skwasm/skwasm_impl/vertices.dart, lib/web_ui/skwasm/contour_measure.cpp, lib/web_ui/skwasm/paint.cpp, lib/web_ui/skwasm/path.cpp, lib/web_ui/test/canvaskit/canvaskit_api_test.dart
This fixes https://github.com/flutter/flutter/issues/127243.
This ensures that native skwasm objects are cleaned up when their associated dart-side objects are garbage collected.
=> Proper memory management in Skwasm

lib/web_ui/lib/src/engine/shadow.dart, lib/web_ui/test/html/recording_canvas_golden_test.dart
Previously the Flutter framework had been inflating the rectangle computed for the bounds of a drawShadow operation in order to work around potential inaccuracies in the SkPicture's bounds calculation.
That workaround is now obsolete for most platforms and was removed from the framework (see https://github.com/flutter/flutter/pull/127052). But the Web HTML backend is using different code for computing shadow bounds.  This PR restores the workaround for Web HTML for consistency with the old behavior.
=> Apply the drawShadow bounds workaround to the Web HTML backend

.ci.yaml
This is to optimize the caches for builders that require those dependencies.
Bug: https://github.com/flutter/flutter/issues/127627 …
=> Checkout android and emsdk deps in linux.

lib/web_ui/lib/src/engine/canvaskit/native_memory.dart, lib/web_ui/lib/src/engine/dom.dart, lib/web_ui/lib/src/engine/skwasm/skwasm_impl/memory.dart, lib/web_ui/test/canvaskit/canvaskit_api_test.dart
The factory constructor breaks the Google3 build for some reason. See b/284478971
=> Don't use a factory constructor on the finalization registry.

lib/web_ui/lib/src/engine/dom.dart
Now that `js_util.callMethod` can take an `Object` as a method name, we can use it directly for methods that are accessed through a `Symbol`.
=> [web] Use the new js_util.callMethod(Object, Object)

impeller/renderer/backend/metal/render_pass_mtl.mm, lib/ui/painting/image_decoder.cc, lib/ui/painting/image_decoder.h, lib/ui/painting/image_decoder_impeller.cc, lib/ui/painting/image_decoder_impeller.h, lib/ui/painting/image_decoder_unittests.cc, lib/ui/painting/multi_frame_codec.cc, shell/common/engine.cc, shell/common/engine.h, shell/common/engine_unittests.cc, shell/common/shell.cc, shell/common/shell.h
Fixes https://github.com/flutter/flutter/issues/126878
This disables device private upload on iOS when backgrounded, and disables mipmap generation when backgrounded.
We don't have a good way to test the core problem in this repo because it only reproduces on physical iOS hardware - simulators don't really care if you do this stuff in the background.
I'll write a devicelab test in the framework to capture this. In the mean time it can be reviewed.
We could consider making the IOManager a shared_ptr instead of having an fml::WeakPtr and that'd clean up some of the extra arguments to engine construction - or we could consider vending the sync switch from impeller::Context unconditionally, but it's pretty iOS specific...
=> [Impeller] Avoid encoding metal commands while the GPU is unavailable when decoding images.

DEPS, impeller/BUILD.gn, testing/run_tests.py, tools/gn
fixes https://github.com/flutter/flutter/issues/127634
This PR depends on a buildroot change at https://github.com/flutter/buildroot/pull/737 …
=> Started executing vulkan unit tests with validation on macos

lib/web_ui/lib/src/engine/dom.dart, lib/web_ui/test/engine/history_test.dart
Up to this point, whenever users use the `PathUrlStrategy`, they would be using `flutter_web_plugins`'s copy of `BrowserPlatformLocation` which has a [different implementation for `getBaseHref()`](https://github.com/flutter/flutter/blob/9376a2ac6003740c357688a376870dbe84a88883/packages/flutter_web_plugins/lib/src/navigation/url_strategy.dart#L235). So we never hit the [implementation in the engine](https://github.com/flutter/engine/blob/eed12f36f5956a37fb4ba13f1b670a5d41c37edb/lib/web_ui/lib/ui_web/src/ui_web/navigation/platform_location.dart#L138), meaning the bug was invisible.
Now that we are [removing](https://github.com/flutter/flutter/pull/126851) `BrowserPlatformLocation` from `flutter_web_plugins`, we are hitting the engine's implementation which contains the bug being solved in …
=> [web] Correct JS property name for baseUri

shell/platform/darwin/macos/framework/Source/FlutterTextInputPlugin.mm, shell/platform/darwin/macos/framework/Source/FlutterTextInputPluginTest.mm
Some context for this change https://github.com/flutter/flutter/issues/118642#issuecomment-1550864240 and https://github.com/flutter/flutter/issues/118759#issuecomment-1551906489 . Tldr, the use-case that this bouncing was originally introduced for in #13702 is no longer an issue.
This ack response is also not present on other desktop platforms or iOS.
Fixes [#118759](https://github.com/flutter/flutter/issues/118759) and [#118642](https://github.com/flutter/flutter/issues/118642)
=> [macOS] Do not bounce editing state back to framework on setEditState

shell/platform/darwin/macos/framework/Source/FlutterMutatorView.mm
This extracts an extra method from `[FlutterMutatorView applyFlutterLayer:]` to perform the final PlatformViewContainer and PlatformView re-nesting in the view stack, then apply transforms, and finally apply the outer axis-aligned master clip rect around the whole thing.
This is a refactoring for readability (primarily clearer parameterisation) and applies no semantic changes to the code. This is the last in a series of refactoring applied to this method.
Issue: https://github.com/flutter/flutter/issues/124490 …
=> [macOS] Extract more PlatformViewMutator code

impeller/renderer/backend/metal/render_pass_mtl.mm, lib/ui/fixtures/ui_test.dart, lib/ui/painting.dart, lib/ui/painting/image_decoder.cc, lib/ui/painting/image_decoder.h, lib/ui/painting/image_decoder_impeller.cc, lib/ui/painting/image_decoder_impeller.h, lib/ui/painting/image_decoder_skia.cc, lib/ui/painting/image_decoder_unittests.cc, lib/ui/painting/multi_frame_codec.cc, lib/ui/painting/multi_frame_codec.h, lib/ui/painting/single_frame_codec.cc, shell/common/engine.cc, shell/common/engine.h, shell/common/engine_unittests.cc, shell/common/fixtures/shell_test.dart, shell/common/shell.cc, shell/common/shell.h
Issue: https://github.com/flutter/flutter/issues/126878
Picks in https://github.com/flutter/engine/pull/42349 and https://github.com/flutter/engine/pull/42175
The reason for the second is that the first creates many more conflicts without it, and resolving them was a lot easier. The second PR is also very low risk and improves error messaging.
=> Cherry picks for image decoding in Impeller

lib/ui/painting/image_decoder_impeller.cc, lib/ui/painting/image_decoder_impeller.h
This lint started failing on some builders a few hours ago.
https://ci.chromium.org/p/flutter/builders/prod/Linux%20Host%20clang-tidy
=> Fix lint failure in ImageDecoderImpeller

ci/licenses_golden/licenses_flutter, impeller/compiler/shader_lib/impeller/BUILD.gn, impeller/compiler/shader_lib/impeller/constants.glsl, impeller/compiler/shader_lib/impeller/conversions.glsl, impeller/compiler/shader_lib/impeller/texture.glsl, impeller/entity/shaders/blending/advanced_blend.vert, impeller/entity/shaders/blending/blend.vert, impeller/entity/shaders/blending/ios/framebuffer_blend.vert, impeller/entity/shaders/border_mask_blur.vert, impeller/entity/shaders/color_matrix_color_filter.vert, impeller/entity/shaders/gaussian_blur/gaussian_blur.vert, impeller/entity/shaders/linear_to_srgb_filter.vert, impeller/entity/shaders/morphology_filter.vert, impeller/entity/shaders/srgb_to_linear_filter.vert, impeller/entity/shaders/texture_fill.frag, impeller/entity/shaders/texture_fill.vert, impeller/entity/shaders/tiled_texture_fill.vert, impeller/entity/shaders/yuv_to_rgb_filter.vert, impeller/tools/malioc.json
Resolves https://github.com/flutter/flutter/issues/127174.
Sets the same mip bias as Skia uses. Biases towards sampling from lower (larger) mip levels -- the tradeoff is a slightly higher cache miss rate in exchange for sharper/less blurry bilinear min-filtered images.
This makes scaled down images render identically between Impeller and Skia.
=> [Impeller] Bias towards sampling from lower mip levels

.ci.yaml
Now only $flutter/osx_sdk property is being used, and it's safe to remove deprecated entries from ci.yaml.
Part of https://github.com/flutter/flutter/issues/127534
=> Remove legacy xcode properties/dependencies

impeller/typographer/typographer_unittests.cc, testing/run_tests.py
fixes https://github.com/flutter/flutter/issues/127715
[Discord]: …
=> [Impeller] Fixed GlyphAtlasWithLotsOfdUniqueGlyphSize

ci/licenses_golden/licenses_flutter, lib/ui/platform_dispatcher.dart, lib/web_ui/lib/platform_dispatcher.dart, lib/web_ui/lib/src/engine/platform_dispatcher.dart, shell/platform/android/io/flutter/embedding/engine/systemchannels/LifecycleChannel.java, shell/platform/common/BUILD.gn, shell/platform/common/app_lifecycle_state.h, shell/platform/darwin/macos/BUILD.gn, shell/platform/darwin/macos/framework/Headers/FlutterAppDelegate.h, shell/platform/darwin/macos/framework/Headers/FlutterAppLifecycleDelegate.h, shell/platform/darwin/macos/framework/Headers/FlutterEngine.h, shell/platform/darwin/macos/framework/Headers/FlutterMacOS.h, shell/platform/darwin/macos/framework/Headers/FlutterPluginMacOS.h, shell/platform/darwin/macos/framework/Source/FlutterAppDelegate.mm, shell/platform/darwin/macos/framework/Source/FlutterAppLifecycleDelegate.mm, shell/platform/darwin/macos/framework/Source/FlutterAppLifecycleDelegateTest.mm, shell/platform/darwin/macos/framework/Source/FlutterEngine.mm, shell/platform/darwin/macos/framework/Source/FlutterEngineTest.mm, shell/platform/darwin/macos/framework/Source/FlutterEngine_Internal.h, shell/platform/linux/BUILD.gn, shell/platform/linux/fl_engine.cc, shell/platform/linux/fl_engine_private.h, shell/platform/linux/fl_engine_test.cc, shell/platform/linux/fl_view.cc, shell/platform/windows/BUILD.gn, shell/platform/windows/flutter_windows_engine.cc, shell/platform/windows/flutter_windows_engine.h, tools/api_check/test/apicheck_test.dart
This reverts commit 57e491a to re-land #40542 to fix the lint warning which caused the original PR to be reverted (the lint warnings were turned on after the original was landed, which is why it wasn't caught earlier).
=> Reland: "Adding app lifecycle notification for macOS and Linux, add `hidden` state." (#40542)

shell/platform/darwin/ios/framework/Source/FlutterPlatformViews.mm
Empty SkRect needs to be created with `SkRect::MakeEmpty()` otherwise the default value is undefined (and possibly garbage).
[CLA]: …
=> Fix unitialized SkRect

shell/platform/android/io/flutter/embedding/engine/systemchannels/AccessibilityChannel.java, shell/platform/android/io/flutter/view/AccessibilityBridge.java, shell/platform/android/test/io/flutter/embedding/engine/systemchannels/AccessibilityChannelTest.java, shell/platform/android/test/io/flutter/view/AccessibilityBridgeTest.java, shell/platform/darwin/ios/framework/Source/accessibility_bridge.h, shell/platform/darwin/ios/framework/Source/accessibility_bridge.mm, shell/platform/darwin/ios/framework/Source/accessibility_bridge_test.mm
framework change:https://github.com/flutter/flutter/pull/126171
issue: https://github.com/flutter/flutter/issues/94523 …
=> Handle a11y focus event on Ios and android

.ci.yaml
Reverts flutter/engine#42112
Try jobs appear to be running mysteriously slow and timing out: https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20Engine%20Drone/922165/overview
I'm guessing that the sharding might not be working quite right.
=> Revert "Move linux clang tidy to engine_v2."

flow/layers/clip_path_layer_unittests.cc, flow/layers/display_list_raster_cache_item.cc, fml/message_loop_task_queues.cc, impeller/aiks/canvas.cc, impeller/display_list/dl_image_impeller.cc, impeller/entity/contents/contents.cc, impeller/entity/contents/tiled_texture_contents.cc, impeller/playground/imgui/imgui_impl_impeller.cc, impeller/renderer/capabilities.cc, shell/common/rasterizer.cc, shell/platform/embedder/embedder_external_view_embedder.cc
Part of https://github.com/flutter/flutter/issues/127701
=> Enables bugprone-unchecked-optional-access for some files

impeller/entity/contents/text_contents.cc, impeller/entity/shaders/glyph_atlas.vert, impeller/tools/malioc.json
TextContents::Render occassionally shows up in the highest CPU functions. We can actually unload most of this computation into the vertex shader.
=> [Impeller] offload all text computation into vertex shader

shell/common/shell.cc
In http://review.skia.org/689016, Skia added an option to explicitly register codecs to use (instead of relying on #defines set by BUILD.gn rules.
This uses that mechanism to explicitly register all the codecs that Flutter was currently using from Skia (at least by my read of [tools/gn](https://github.com/flutter/engine/blob/195009b91abdc3ff7af598d77cb3ab275145da6d/tools/gn#L292).
I'm not sure if there is another place I need to put this sort of code, e.g. for Fuchsia things.
To really test this out, we would want to add a define of SK_DISABLE_LEGACY_INIT_DECODERS when compiling Skia, but I'm not sure the best place to do this. …
=> Register codecs with Skia explicitly

lib/ui/painting/image_decoder_impeller.cc, lib/ui/painting/image_decoder_impeller.h
Alternative to https://github.com/flutter/engine/pull/42456
@itsjustkevin @zanderso
=> Fix tidy issues

ci/licenses_golden/licenses_flutter, lib/web_ui/lib/src/engine.dart, lib/web_ui/lib/src/engine/initialization.dart, lib/web_ui/lib/src/engine/navigation.dart, lib/web_ui/lib/src/engine/navigation/js_url_strategy.dart, lib/web_ui/lib/src/engine/navigation/url_strategy.dart, lib/web_ui/lib/src/engine/test_embedding.dart, lib/web_ui/lib/src/engine/window.dart, lib/web_ui/lib/ui_web/src/ui_web/navigation/url_strategy.dart, lib/web_ui/test/engine/history_test.dart, lib/web_ui/test/engine/routing_test.dart
Reverts flutter/engine#42134
This is blocking the engine into framework roller:
See: https://cirrus-ci.com/task/5610586755563520
```
Analyzing 3 items...                                            
error • The class 'UrlStrategy' can't be extended outside of its library because it's an interface class • dev/integration_tests/web_e2e_tests/test_driver/url_strategy_integration.dart:48:31 • invalid_use_of_type_outside_library
1 issue found. (ran in 321.8s)
🙙  🙛  
```
=> Revert "[web] Remove the JS API for url strategy"

display_list/benchmarking/dl_complexity_unittests.cc, display_list/display_list.cc, display_list/display_list.h, display_list/display_list_unittests.cc, display_list/dl_builder.cc, display_list/dl_builder.h, display_list/dl_color.h, display_list/dl_paint.h, display_list/testing/dl_rendering_unittests.cc, display_list/testing/dl_test_snippets.cc, display_list/testing/dl_test_snippets.h, display_list/utils/dl_matrix_clip_tracker.h, flow/diff_context_unittests.cc, flow/layers/container_layer_unittests.cc, flow/layers/display_list_layer_unittests.cc, flow/layers/opacity_layer_unittests.cc, flow/testing/diff_context_test.cc, flow/testing/diff_context_test.h, impeller/display_list/dl_unittests.cc, shell/common/dl_op_spy_unittests.cc
The original PR caused some golden test failures down the line, likely due to bad analysis of when the combined BlendMode and color would result in a NOP situation.
This PR adds tests that go through every BlandMode and pair it with a variety of colors and Color/ImageFilters to verify that the operations are only omitted when they actually produce no change in the output. It also checks the validity of the "modifies_transparent_black" property of DisplayLists which can be used in place of the current CanvasSpy/DlOpSpy classes.
The description from the [previous PR](https://github.com/flutter/engine/pull/41463) updated with the new name of the DL property:
---------------------------------
This optimization avoids recording unnecessary render operations that will not affect the output and …
=> Reland "add non-rendering operation culling to DisplayListBuilder" (#41463)

shell/platform/embedder/tests/embedder_gl_unittests.cc
This test sometimes caused assertion failures when running on Windows with ANGLE.  The process may be unable to safely clean up global objects if GL commands are pending when the test exits.
=> Wait for GL command completion in the ExternalTextureGLRefreshedTooOften test

shell/platform/android/io/flutter/plugin/editing/SpellCheckPlugin.java, shell/platform/android/test/io/flutter/plugin/editing/SpellCheckPluginTest.java
On some Samsung devices Flutter with spell-check enabled will crash when typing/moving near the ">" character. 
Stack trace is
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.textservice.SentenceSuggestionsInfo.getSuggestionsCount()' on a null object reference
at io.flutter.plugin.editing.SpellCheckPlugin.onGetSentenceSuggestions(SpellCheckPlugin.java:26)
at android.view.textservice.SpellCheckerSession.lambda$handleOnGetSentenceSuggestionsMultiple$1$android-view-textservice-SpellCheckerSession(SpellCheckerSession.java:224)
at android.view.textservice.SpellCheckerSession$$ExternalSyntheticLambda0.run(:4)
at android.os.Handler.handleCallback(Handler.java:942)
at android.os.Handler.dispatchMessage(Handler.java:99)
at …
```
=> Fix crash getting spell-check suggestions

shell/platform/windows/text_input_plugin.cc, shell/platform/windows/text_input_plugin_unittest.cc
This PR updates the Windows text input plugin to avoid adding a new line on a multiline text field when action is not set to `TextInputAction.newline`.
Fixes https://github.com/flutter/flutter/issues/125879 as Linux and macOS implementations are merged.
Linux PR: https://github.com/flutter/engine/pull/41895
macOS PR: https://github.com/flutter/engine/pull/41977
Adds 2 tests.
=> [Windows - TextInput] Insert new line only when TextInputAction.newline

shell/platform/android/io/flutter/plugin/platform/PlatformViewsController.java, shell/platform/android/io/flutter/plugin/platform/SingleViewPresentation.java, shell/platform/android/test/io/flutter/plugin/platform/PlatformViewsControllerTest.java
- Move some code off of the message handler onto the parent class.
- Call the engine life cycle callbacks on PlatformView regardless of which mode is used.
- Re-enable and fix test that these callbacks are invoked.
Fixes [#120329](https://github.com/flutter/flutter/issues/120329) …
=> Ensure PlatformView engine life cycle callbacks are invoked

impeller/core/host_buffer.cc, impeller/core/host_buffer.h, impeller/entity/contents/text_contents.cc
From local testing, this shaves off about 0.3-4 ms of pure allocation overhead from https://github.com/flutter/flutter/issues/127760
=> [Impeller] Emplace directly into host buffer (avoid VBB) for text data

ci/builders/linux_clang_tidy.json, ci/builders/mac_clang_tidy.json, ci/builders/standalone/linux_license.json
Retries on lints and clang tidy were hiding the issues as timeouts rather than providing the fail signal right away.
Bug: https://github.com/flutter/flutter/issues/128083 …
=> Do not retry lint or clang tidy tests.

shell/common/rasterizer.cc, shell/common/rasterizer.h
Reverts flutter/engine#42001 due to being the likely culprit to flakiness https://github.com/flutter/flutter/issues/127936 .
=> Revert "[Rasterizer] Make resubmit information temporary"

.github/workflows/third_party_scan.yml
This change introduces the ability to allow for the vulnerability scanning workflow to be triggered by the 'vulnerability scan' label on PRs. If the label is not applied, the workflow is skipped completely on PRs. This will allow those working to patch a vulnerability to check for resolution before landing the change.
Testing this change: https://github.com/flutter/engine/actions/runs/5059129544
b/283970087
[Flutter …
=> Allow for optional label to trigger vuln scan on patch PRs

.ci.yaml
This is because they are using jazzy which is not currently supported in our arm64 cipd packages of ruby.
Bug: https://github.com/flutter/flutter/issues/128098 …
=> Add cpu as drone dimension to mac ios build.

testing/scenario_app/run_ios_tests.sh
This ensures that a retry of this script on CI will not collide with the output directory of a previous run.
=> Generate a unique temporary directory name in the iOS scenario test script

lib/ui/fixtures/ui_test.dart, lib/ui/hooks.dart, lib/ui/platform_dispatcher.dart, lib/ui/pointer.dart, lib/ui/window.dart, lib/web_ui/lib/platform_dispatcher.dart, lib/web_ui/lib/pointer.dart, lib/web_ui/lib/src/engine/platform_dispatcher.dart, lib/web_ui/lib/src/engine/window.dart, lib/web_ui/lib/window.dart, shell/platform/embedder/fixtures/main.dart
Fixes https://github.com/flutter/flutter/issues/124991.
Framework tests are failing because I need to do a pre-migration of `flutter_test` for the Object -> int change of viewId. That's in https://github.com/flutter/flutter/pull/128092.
=> MultiView changes for dart:ui

.ci.yaml
With the benchmarks and upload scripts running as tests within Linux_host_engine - host_release we can move this test to staging in preparation for its deprecation.
Example:
https://ci.chromium.org/p/flutter/builders/prod/Linux%20Production%20Engine%20Drone/191822?
Bug: https://github.com/flutter/flutter/issues/127678 …
=> Move benchmarks no upload to staging.

shell/platform/darwin/macos/framework/Source/FlutterMutatorView.mm, shell/platform/darwin/macos/framework/Source/FlutterMutatorViewTest.mm
For consistency with Flutter (and all other platforms), Flutter views in the macOS embedder set `isFlipped` to ensure a co-ordinate system with the origin in the top-left, with y co-ordinates increasing towards the bottom edge of the view.
Previously, we were using a stock NSView as the container, which uses a bottom-left origin by default. Instead we extract the PlatformView container view as its own class with `isFlipped` true.
This doesn't correct the issue of the view anchorpoint/position but does correct rotation direction.
This also applies the transform back to origin prior to other transforms when adjusting the platformview position rather than after.
Issue: https://github.com/flutter/flutter/issues/124490 …
=> [macOS] Top-left origin for PlatformView container

flow/layers/layer_raster_cache_item.cc, impeller/display_list/skia_conversions.cc, impeller/entity/contents/content_context.cc, impeller/entity/contents/filters/filter_contents.cc, impeller/entity/entity_pass.cc, shell/common/shell.cc
Related https://github.com/flutter/flutter/issues/127701
=> Check more optional accesses

impeller/renderer/backend/metal/context_mtl.mm, impeller/renderer/backend/metal/formats_mtl.mm
Clang tidy checks for https://github.com/flutter/engine/pull/42399 are failing for `formats_mtl.mm` and `context_mtl.mm`. Weirdly this happens even though none of these files where modified in the branch.
For `context_mtl.mm` the fix is straightforward, just a missing `std::move`.
For `formats_mtl.mm` clang-tidy actually crashes on the assignments to `des.depthCompareFunction` and `des.depth_write_enabled`. The crash doesn't happen if the assignment is done through a temporary variable. 
I'm not sure if we should have a workaround for the crash or disable clang-tidy on the file completely (FLUTTER_NOLINT). …
=> Fix clang tidy error and crash

BUILD.gn, ci/licenses_golden/excluded_files, ci/licenses_golden/licenses_flutter, display_list/BUILD.gn, display_list/benchmarking/dl_region_benchmarks.cc, display_list/dl_builder.cc, display_list/geometry/dl_region.cc, display_list/geometry/dl_region.h, display_list/geometry/dl_region_unittests.cc, display_list/geometry/dl_rtree.cc, display_list/geometry/dl_rtree.h, flow/rtree.cc, flow/rtree_unittests.cc, testing/scenario_app/ios/Scenarios/ScenariosUITests/UnobstructedPlatformViewTests.m
Fixes https://github.com/flutter/flutter/issues/116070
Fixes https://github.com/flutter/flutter/issues/126202
Introduces `DlRegion` class which implements subset of `SkRegion` required to get non-overlapping rectangles from region.
The implementation is different and faster than `SkRegion` for this particular use-case (`display_list_region_benchmarks`):
Edit: Updated benchmark to latest revision and natively (initial run went through rosetta)
```
----------------------------------------------------------------------------
Benchmark                                  Time             CPU   Iterations
----------------------------------------------------------------------------
BM_RegionBenchmarkDlRegion/Tiny          616 us          616 us          908
BM_RegionBenchmarkSkRegion/Tiny …
```
=> Improve getting non-overlapping rectangles from RTree

shell/platform/darwin/graphics/FlutterDarwinExternalTextureMetal.mm, shell/platform/embedder/embedder.cc, testing/test_metal_context.h
Another follow-on to http://review.skia.org/704942 which removed some #includes that Flutter had been transitively depending on.
Note that SkCFObject is mac-only, so I included it the appropriate #ifdef in embedder.cc, but the other two files are already mac-only so they do not need that guard. …
=> Add missing #include of SkCFObject.h

display_list/display_list_unittests.cc, display_list/dl_builder.cc
Fixes: https://github.com/flutter/flutter/issues/128159
In diagnosing test failures for https://github.com/flutter/engine/pull/42330 we discovered that the DisplayList code was not always backwards compatible with computing the bounds of inverted rectangles (where left > right or top > bottom). Historically such rectangles were always rendered as if they were sorted (i.e. `SkRect::makeSorted()`), but we computed bounds as if the bounds only mattered if the supplied rectangle was ordered. So, we would sometimes render a rectangle for which we mis-computed the bounds.
This would rarely surface in the current code as most rendered rectangles would pass through `SkMatrix::mapRect()` which implicitly orders the rectangle as it transforms it, but any attributes applied to the bounds before that …
=> fix bounds of inverted rendered rectangles

.github/dependabot.yml
https://github.com/flutter/flutter/issues/126002
=> Run dependabot in off peak hours

DEPS, sky/tools/create_embedder_framework.py, sky/tools/create_full_ios_framework.py, sky/tools/create_ios_framework.py, sky/tools/create_macos_framework.py
Use the right binary architectures on scripts running dsymutil.
This is to fix the problem of bad architecture binary for builds running on dart internal: https://github.com/flutter/flutter/issues/128098 …
=> Use the arm64 dsymutil on Mac M1 machines

lib/ui/fixtures/ui_test.dart, lib/ui/platform_dispatcher.dart, lib/ui/semantics.dart, lib/ui/window.dart, lib/web_ui/lib/platform_dispatcher.dart, lib/web_ui/lib/src/engine/platform_dispatcher.dart, lib/web_ui/lib/window.dart, lib/web_ui/test/engine/semantics/semantics_test.dart, lib/web_ui/test/engine/semantics/semantics_tester.dart, lib/web_ui/test/engine/window_test.dart
Follow-up to https://github.com/flutter/engine/pull/42493.
The framework has been migrated to the new onSemanticsActionEvent callback.
=> Remove onSemanticsAction

impeller/aiks/aiks_unittests.cc, impeller/compiler/shader_lib/impeller/gradient.glsl, impeller/entity/contents/conical_gradient_contents.cc, impeller/entity/contents/conical_gradient_contents.h, impeller/entity/entity_unittests.cc, impeller/entity/shaders/conical_gradient_fill.frag, impeller/entity/shaders/conical_gradient_ssbo_fill.frag, impeller/tools/malioc.json
fix https://github.com/flutter/flutter/issues/128012
In many instances (https://github.com/flutter/flutter/issues/128012#issuecomment-1577029031), the current implementation of conical gradient in impeller produces incorrect results. This pull request proposes to migrate the conical gradient algorithm from skia to impeller.
Please see https://github.com/google/skia/blob/ddf987d2ab3314ee0e80ac1ae7dbffb44a87d394/src/sksl/sksl_graphite_frag.sksl#L541-L666
Test result
=> [Impeller] Make conical gradient work as expected

flow/layers/layer_raster_cache_item.cc
Possible fix for https://github.com/flutter/flutter/issues/128308
=> Fix raster cache optional value check logic

lib/web_ui/skwasm/canvas.cpp, lib/web_ui/test/ui/draw_atlas_golden_test.dart
Make Skwasm consistent with the CanvasKit backend's sampling options in `drawAtlas`. Also, fix the atlas rendering tests so the sprites don't bleed into each other.
=> Use proper sampling options in Skwasm's drawAtlas.

lib/web_ui/lib/ui_web/src/ui_web/navigation/url_strategy.dart, lib/web_ui/test/engine/history_test.dart
To make the `HashUrlStrategy` a bit cleaner (at least for the home page), let's get rid of the notorious `/#/` when the app is in the home page.
Non-home pages continue to have a hash in them. After this PR, here are some example URL changes:
- `http://domain.com/#/` => `http://domain.com/`
- `http://domain.com/#/page1` => (remains the same)
This change is backwards compatible, i.e. if you write `http://domain.com/#/` in the address bar, the app will load and open the home page correctly; and flutter will automatically change the URL to `http://domain.com/`.
Fixes https://github.com/flutter/flutter/issues/127608
=> [web] Remove /#/ from home page URL

common/settings.h, shell/common/switches.cc, shell/common/switches.h, shell/platform/android/android_context_gl_impeller.cc, shell/platform/android/android_context_vulkan_impeller.cc, shell/platform/android/io/flutter/embedding/engine/loader/FlutterLoader.java, shell/platform/android/platform_view_android.cc
fixes https://github.com/flutter/flutter/issues/128286
[Discord]: …
=> [Impeller] Added a switch to turn on vulkan

shell/platform/darwin/macos/framework/Source/FlutterPlatformViewController.h, shell/platform/darwin/macos/framework/Source/FlutterPlatformViewController.mm, shell/platform/darwin/macos/framework/Source/FlutterPlatformViewControllerTest.mm, shell/platform/darwin/macos/framework/Source/TestFlutterPlatformView.h, shell/platform/darwin/macos/framework/Source/TestFlutterPlatformView.mm
Previously, when creating native platform views on macOS, we ignored any parameters passed via the framework side "params" argument in the "create" method call, and instead always passed a nil value to the FlutterPlatformViewFactory. This made it impossible for users of macOS platform views to pass constructor arguments to the NSView subclass implementing the platform view.
We now decode the arguments data using the codec specified by the `FlutterPlatformViewFactory` and pass them through to the `[FlutterPlatformViewFactory createWithIdentifier:arguments:]` method where the platform view author can make use of them.
Fixes: https://github.com/flutter/flutter/issues/124723
This is a part of the broader macOS platform view support effort: https://github.com/flutter/flutter/issues/41722
If …
=> [macOS] Add platformview creation parameter support

shell/platform/embedder/embedder.cc
=> [Impeller] fix missing assignment of embedder render target.

shell/platform/darwin/ios/framework/Source/FlutterEngine.mm, shell/platform/darwin/ios/framework/Source/FlutterEngine_Test.h, shell/platform/darwin/ios/framework/Source/FlutterTextInputPluginTest.mm
This PR fixes an issue related to text input plugin, on IOS, sending a wrong action string to the engine for `FlutterTextInputActionContinue`.
Fixes https://github.com/flutter/flutter/issues/126922
Adds 1 test.
=> [iOS] Fix TextInputAction.continueAction sends wrong action to framework

.github/workflows/labeler.yml
Fixes https://github.com/flutter/flutter/issues/128448#issuecomment-1581353250
=> [labeler] Fix to run on flutter/engine

impeller/aiks/aiks_unittests.cc, impeller/entity/geometry/fill_path_geometry.cc, impeller/entity/geometry/geometry.cc
fix https://github.com/flutter/flutter/issues/128328
We need to transform the 'position' first and then divide 'texture_coverage', otherwise the result will be incorrect.
without patch
with patch
=> [Impeller] Corrected the 'texture_coords' computation in 'Geometry::GetPositionUVBuffer'

shell/common/shell_unittests.cc
Sometimes the time point created late will less than the time point create earlier since the CLOCK SOURCE has changed.
We must make sure the  CLOCK SOURCE (fml::TimePoint) is always keep the same while we are testing. 
Corrects the test case is needed before we fix the problem completely.
=> Fix: invalid time-point comparison between each from different clock source

shell/platform/linux/fl_text_input_plugin.cc, shell/platform/linux/fl_text_input_plugin_test.cc
Fixes a few issues with the Linux text editing delta implementation that was causing some issues when composing CJK text.
`im_preedit_changed_cb` dispatches a delta with the delta range set as the current composing region causing a crash when composing because the new composing region range might not yet exist in the `oldText` that the delta is applied to. We should instead send the composing region before the change to the text as that will be the correct range that is being modified in the `oldText`.
`im_preedit_end_cb` dispatches a delta with an empty `oldText`, a not empty `deltaText`, and a delta range of `(-1,-1)` causing a crash when composing ends because the delta range will never be within the range of the text. We should instead send the current text value as the `oldText` and …
=> [Linux] composing delta fixes

impeller/entity/contents/filters/blend_filter_contents.cc, impeller/entity/contents/filters/blend_filter_contents.h, impeller/geometry/color.cc, impeller/geometry/color.h, impeller/geometry/geometry_unittests.cc
Side quest of https://github.com/flutter/flutter/issues/127232.
This is particularly useful for debugging pipeline blend variations of the blend filter, since we otherwise have to look at the raw pipeline blend ops and piece together what the blend mode must've been.
=> [Impeller] Specify blend mode on blend filter commands

.ci.yaml
Master branch is not the default branch in the engine anymore and we should not run any builds on it.
Bug: https://github.com/flutter/flutter/issues/90476 …
=> Remove all the uses of master branch in the .ci.yaml file.

ci/builders/README.md
Add docs for realm propery in the archives of build configuration files.
Bug: https://github.com/flutter/flutter/issues/126121 …
=> Document the use of realm in archives.

impeller/aiks/aiks_unittests.cc
Part of https://github.com/flutter/flutter/issues/127232.
Both of these tests should be rendering as a clipped and blurred green circle. Making mask blurs interact correctly with color filters is not going to be trivial... These bugs extend beyond the filter graph itself. Want to get some goldens in to compare against.
ForegroundPorterDuffBlend:
ForegroundAdvancedBlend:
=> [Impeller] Add tests for foreground blends with mask blurs

impeller/renderer/backend/vulkan/capabilities_vk.cc
This fixes some f'd up ness in the images. Will need to debug this separately on Android. For now, we can just turn it off in the caps.
=> [Impeller] disable buffer to texture blit for Vulkan.

DEPS, shell/config.gni, shell/platform/android/BUILD.gn, shell/platform/android/io/flutter/embedding/engine/loader/FlutterLoader.java, shell/platform/fuchsia/flutter/BUILD.gn, testing/scenario_app/android/gradle.properties, tools/gn, vulkan/config.gni
This builds and links in the validation layers for android.  They then can be turned on or off with a manifest field.
fixes https://github.com/flutter/flutter/issues/123788
depends on https://github.com/flutter/buildroot/pull/741 …
=> [Impeller] Makes validation layers flag work for android

impeller/renderer/backend/vulkan/allocator_vk.cc, impeller/renderer/backend/vulkan/device_buffer_vk.cc
According to my read of the documentation for VMA/Vulkan allocation docs, setting VK_MEMORY_PROPERTY_HOST_COHERENT_BIT means we shouldn't need to flush the memory. nevertheless, this fixes the corruption of host buffers observed in https://github.com/flutter/flutter/issues/124040
Fixes https://github.com/flutter/flutter/issues/124040
> VK_MEMORY_PROPERTY_HOST_COHERENT_BIT bit specifies that the host cache management commands [vkFlushMappedMemoryRanges](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkFlushMappedMemoryRanges.html) and [vkInvalidateMappedMemoryRanges](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkInvalidateMappedMemoryRanges.html) are not needed to flush host writes to the device or make device writes visible to the host, …
=> [Impeller] add explicit VMA flush to device memory writes.

common/settings.h, shell/common/switches.cc, shell/common/switches.h, shell/platform/android/android_context_gl_impeller.cc, shell/platform/android/android_context_vulkan_impeller.cc, shell/platform/android/io/flutter/embedding/engine/loader/FlutterLoader.java, shell/platform/android/platform_view_android.cc
relands https://github.com/flutter/engine/pull/42585
[Discord]: …
=> [Impeller] Reland: Added a switch to turn on vulkan

shell/gpu/gpu_surface_vulkan_impeller.cc, shell/gpu/gpu_surface_vulkan_impeller.h
Should fix https://github.com/flutter/flutter/issues/128618.
This is unused - if it were used we'd have to be careful about deleting the object on the same thread it's created on.
=> Delete WeakPtrFactory from GPUSurfaceVulkanImpeller

ci/builders/windows_host_engine.json
=> Fix an archive name in windows_host_engine config

impeller/renderer/backend/vulkan/BUILD.gn, impeller/renderer/backend/vulkan/context_vk.cc, testing/scenario_app/android/app/build.gradle
Adds some helper messages around using validation layers.
[Discord]: …
=> [Impeller] Added helper messaging around validation usage

impeller/geometry/geometry_unittests.cc, impeller/geometry/path_component.cc
fix https://github.com/flutter/flutter/issues/128532
In this commit, we refined the method for calculating cubic path boundaries in CubicPathBoundingPopulateValues function. By adopting an alternative quadratic formula from Numerical Recipes in C (The code is ported from skia's `SkFindUnitQuadRoots`),  we mitigated numerical errors, hence boosting precision and reliability in handling cubic paths.
=> [Impeller] Improved numerical stability in cubic path boundary calculations

shell/common/input_events_unittests.cc, shell/common/shell_test.cc, shell/common/shell_test.h, shell/common/shell_test_platform_view.cc, shell/common/shell_test_platform_view.h, shell/common/shell_unittests.cc, shell/platform/darwin/ios/platform_message_handler_ios_test.mm
This PR refactors `ShellTest::CreateShell` so that instead of taking a list of optional parameters, it takes a `Config` struct, almost all fields of which have default values. This makes calling this method cleaner, and makes it easier to add more parameters. A short version is also kept that takes `settings` and `task_runners`, since this version is used so often.
Currently `ShellTest::CreateShell`'s full version has 2 mandatory parameters and 5 optional parameters. Many calls to this method have to list a long list of default parameters before going to the single one that needs overwriting, and adding new parameters to this call is even more tedious. …
=> Use ShellTest::Config struct to create Shell

impeller/renderer/backend/vulkan/capabilities_vk.cc
fixes https://github.com/flutter/flutter/issues/128629
Screenshot of the change in action:
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-cha …
=> [Impeller] added debug info to frame debuggers like AGI

impeller/entity/shaders/blending/advanced_blend.vert, impeller/entity/shaders/blending/blend.vert, impeller/entity/shaders/border_mask_blur.vert, impeller/entity/shaders/color_matrix_color_filter.vert, impeller/entity/shaders/gaussian_blur/gaussian_blur.vert, impeller/entity/shaders/glyph_atlas.vert, impeller/entity/shaders/gradient_fill.vert, impeller/entity/shaders/linear_to_srgb_filter.vert, impeller/entity/shaders/position_color.vert, impeller/entity/shaders/rrect_blur.vert, impeller/entity/shaders/solid_fill.vert, impeller/entity/shaders/srgb_to_linear_filter.vert, impeller/entity/shaders/yuv_to_rgb_filter.vert, impeller/tools/malioc.json
Fixes https://github.com/flutter/flutter/issues/128605
f16 doesn't have enough resolution at large pixel values to be safely used for positions. Opt all shaders into highp. I think we might be able to get away with mediump for uv since values from 0-1 should have plenty of precisision, but we can worry about that later.
=> [Impeller] opt all vertex shader position/uvs into highp

lib/ui/snapshot_delegate.h
I was refactoring this class on the Skia side and saw Flutter #included it, but did not appear to actually use it.
This replaces an unnecessary #include with a necessary one.
[breaking …
=> Remove unnecessary #include of SkPromiseImageTexture

shell/platform/fuchsia/dart_runner/dart_component_controller.cc, shell/platform/fuchsia/dart_runner/dart_test_component_controller.cc, shell/platform/fuchsia/flutter/component_v2.cc, shell/platform/fuchsia/flutter/main.cc, shell/platform/fuchsia/runtime/dart/utils/BUILD.gn, shell/platform/fuchsia/runtime/dart/utils/tempfs.cc, shell/platform/fuchsia/runtime/dart/utils/tempfs.h, tools/fuchsia/fuchsia_libs.gni
=> Remove dependency on memfs

impeller/renderer/backend/vulkan/formats_vk.h, impeller/renderer/backend/vulkan/render_pass_vk.cc
Two issues:
1. The resolve texture is created from the same impeller attachment as the msaa attachment, so the store mode was getting set to dont care instead of store.
2. the image layout for the resolve attachment should be ePresentSrcKHR, at least from following the guide at https://vulkan-tutorial.com/Multisampling
Fixing both of these locally fixes all of the weird offscreen cursed rendering.
Fixes https://github.com/flutter/flutter/issues/128600
=> [Impeller] Correct attachment description for offscreen MSAA resolve.

shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm, shell/platform/darwin/ios/framework/Source/FlutterTextInputPluginTest.mm
The `isRTLAtPosition` method had a bug, it used `NSInteger max = [_selectionRects count]` instead of `NSInteger max = [_selectionRects count] - 1`. But I realized we don't even need the function any more, it was used in a few places in previous iterations of #36643, but in the only place remaining, we actually already have the selection rect and don't need to search for it by position.
Btw as an explanation of the crash, I guess there is some mismatch between code point and character count somewhere. UIKit was asking for `caretRectForPosition:2` when we only had 1 character. This could have only crashed when floating cursor selection was used, but actually when switching to CJK keyboard, UIKit turns out to use `caretRectForPosition` to calculate something about the composing rect.
Fixes …
=> Fix crash with CJK keyboard with emoji at end of text field

shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm
This PR gives an overview of how floating cursor feature works (including the new floating cursor selection gesture, and the existing floating cursor move gesture). It can serve as the missing design doc. 
I put it in the engine rather than the framework, since all logics are in one place, and it's closer to the UIKit behavior that I want to cover. 
Thanks @moffatman for helping me understanding it. 
https://github.com/flutter/flutter/issues/30476 …
=> [floating_cursor_selection] a somewhat "design doc" for floating cursor feature

shell/platform/android/io/flutter/embedding/android/FlutterActivity.java, shell/platform/android/io/flutter/embedding/android/FlutterFragment.java, shell/platform/android/io/flutter/embedding/engine/systemchannels/PlatformChannel.java, shell/platform/android/io/flutter/plugin/platform/PlatformPlugin.java, shell/platform/android/test/io/flutter/embedding/android/FlutterAndroidComponentTest.java
This PR attempts to fix breakage(s) caused by https://github.com/flutter/engine/pull/39208.
b/286627757
There were breakages in Google's code where classes that implemented PlatformMessageHandler did not provide an implementation of setFrameworkHandlesBack.
```
... is not abstract and does not override abstract method setFrameworkHandlesBack(boolean) in PlatformMessageHandler
```
I've tried to fix this by adding a default empty implementation to PlatformMessageHandler.  Is that ok to do there, even though other nearby methods don't have default implementations there?
Also, I noticed that I could probably do the same thing to avoid my empty implementation in FlutterFragment, so I added one to PlatformPluginDelegate as well.  That did allow me to remove the implementation in …
=> Predictive back breakage fix

impeller/entity/shaders/glyph_atlas.frag, impeller/entity/shaders/glyph_atlas.vert, impeller/entity/shaders/glyph_atlas_color.frag, impeller/tools/malioc.json
Fixes https://github.com/flutter/flutter/issues/128624
=> [Impeller] Fix text jitter on Vulkan.

impeller/entity/entity_pass.cc, impeller/renderer/backend/vulkan/capabilities_vk.cc, impeller/renderer/backend/vulkan/capabilities_vk.h, impeller/renderer/backend/vulkan/context_vk.cc, impeller/renderer/backend/vulkan/context_vk.h, impeller/renderer/backend/vulkan/swapchain_impl_vk.cc
Fixes https://github.com/flutter/flutter/issues/128604
THe problem was that we were selecting kB8G8R8A8UNormInt for the offscreen and kR8G8B8A8UNormInt for the onscreen, so the blit was swapping the color channels.
=> [Impeller] Ensure vulkan offscreen pixelformat is the same as the onscreen format

ci/builders/linux_android_debug_engine.json
Let's try to make sure the validation layers don't break.
[Discord]: …
=> Added CI step for building with validation layers

shell/common/shell.cc, third_party/txt/BUILD.gn, third_party/txt/src/txt/font_collection.cc, third_party/txt/tests/font_collection_tests.cc
fixes https://github.com/flutter/flutter/issues/123483
Not entirely sure if this really fix the flake as I can't reproduce locally. My guess to the flake is that the setDefaultfontmgr should only be called once during the life time of the app. The setDefaultfontmgr can be remove at the call site, since it is already called during setup …
=> setupDefultFontManager correctly clear out cache

impeller/base/validation.cc
INFO logs do not show up in normal logging unless an extra flag is passed by the tool (and it is a different flag from the "-v" flag).
This means bug reports that include logs about impeller are missing the validation errors, which makes them harder to triage and dedupe.
Fixes https://github.com/flutter/flutter/issues/128808
=> Make validation logs ERROR level

testing/scenario_app/README.md
=> Fix generateLockfiles running directory for documentation

shell/platform/darwin/ios/framework/Source/FlutterPlatformPlugin.h, shell/platform/darwin/ios/framework/Source/FlutterPlatformPlugin.mm, shell/platform/darwin/ios/framework/Source/FlutterPlatformPluginTest.mm, shell/platform/darwin/ios/framework/Source/FlutterViewController.mm, shell/platform/darwin/ios/framework/Source/FlutterViewController_Internal.h
UIApplication based status bar API was deprecated.
This PR makes the ViewController based status bar appearance the default.
Still keep UIApplication based status bar for apps that explicitly sets `UIViewControllerBasedStatusBarAppearance` to NO in info.plist.
Part of https://github.com/flutter/flutter/issues/124289 …
=> [ios] view controller based status bar

tools/gn
Skia codecs depends on Skia's xml libraries which depend on expat, so we must enable expat for non-wasm builds.
See https://github.com/flutter/engine/pull/42857 for an example of a failing build on Skia. …
=> Build skia with expat

shell/platform/linux/fl_basic_message_channel.cc, shell/platform/linux/fl_basic_message_channel_test.cc, shell/platform/linux/fl_standard_message_codec.cc, shell/platform/linux/fl_standard_message_codec_test.cc, shell/platform/linux/public/flutter_linux/fl_basic_message_channel.h
This PR changes how a null message is handled by the Linux engine for a basic message channel.
**Before**:
- when receiving a null message a warning was emitted.
- `fl_binary_messenger_send_response` was called but failed and the application exited.
```
** (bug:9866): WARNING **: 23:13:42.109: Failed to decode message: Unexpected end of data
** (bug:9866): CRITICAL **: 23:13:42.109: gboolean send_response(FlBinaryMessenger *, FlBinaryMessengerResponseHandle *, GBytes *, GError **): assertion 'response_handle->response_handle != nullptr' failed
```
**After**:
- Receiving a null message is handled as expected from the framework side documentation:
https://github.com/flutter/flutter/blob/9287e81d52d69560222c14170a2fd7def613fe61/packages/flutter/lib/src/services/platform_channel.dart#L149-L150 …
=> [Linux] Allow BasicMessageChannel sending and responding to null message

display_list/geometry/dl_rtree.cc, display_list/geometry/dl_rtree.h, flow/layers/display_list_layer_unittests.cc, flow/layers/display_list_raster_cache_item.cc, flow/layers/layer.h, flow/layers/layer_raster_cache_item.cc, flow/layers/platform_view_layer.cc, flow/raster_cache.cc, flow/raster_cache.h, flow/raster_cache_unittests.cc, flow/testing/mock_raster_cache.h
Fixes https://github.com/flutter/flutter/issues/116069
When raster cache paints to a layer over platform view, it will draw the individual rectangles from the content RTree, to ensure that the destination layer RTree is not clobbered. This is necessary for raster cache to not break unobstructed platform views and/or hit testing.
When raster cache paints in the root (bottom-most) layer the behavior it just copies the entire image as it did before. This is to minimise risk of performance regressions.  …
=> Raster cache should preserve RTree for overlay layers

impeller/renderer/backend/vulkan/swapchain_impl_vk.cc
Every frame we submit to the queue a layout transition and a notify to the `acquire` fence.  This joins those together into one `vkQueueSubmit` call.  Thus eliminating a fence that was happening after the layout transition.
issue https://github.com/flutter/flutter/issues/128838
```
Before:
"average_frame_build_time_millis": 1.379130952380952,
"90th_percentile_frame_build_time_millis": 1.965,
"99th_percentile_frame_build_time_millis": 20.246,
"worst_frame_build_time_millis": 29.578,
"missed_frame_build_budget_count": 7,
"average_frame_rasterizer_time_millis": 20.447408955223867,
"90th_percentile_frame_rasterizer_time_millis": 25.398,
"99th_percentile_frame_rasterizer_time_millis": 160.198,
"worst_frame_rasterizer_time_millis": 178.042,
"missed_frame_rasterizer_budget_count": 122, …
```
=> [Impeller] Joined obligatory vulkan swapchain submits

.ci.yaml
release_build property is used to flag that artifacts from the build need to also include provenance. Clang tidy build does not generate any artifacts and it is failing in dart internal.
Bug: https://github.com/flutter/flutter/issues/128981 …
=> Remove release_build from clang_tidy build.

lib/web_ui/dev/test_platform.dart
Context: https://dart-review.googlesource.com/c/sdk/+/309821
=> Fix prefer_final_in_for_each

.ci.yaml, ci/builders/mac_host_engine.json, ci/builders/mac_ios_engine.json
Xcode version needs to be set explicitly for builds running on dart-internal.
Bug: https://github.com/flutter/flutter/issues/128977 …
=> Set xcode explicitly on mac builds with release_build.

flutter_frontend_server/pubspec.yaml, tools/api_check/pubspec.yaml, web_sdk/pubspec.yaml
A dependency to dart_internal was added in https://dart-review.googlesource.com/c/sdk/+/309460/6 and all transitive deps need to have overrides.
=> add dart_internal override where necessary

impeller/entity/contents/content_context.cc, impeller/entity/contents/content_context.h, impeller/renderer/pipeline_descriptor.h, impeller/renderer/renderer_unittests.cc
Despite compiling an initial PSO variant for every shader, in practice these were completely useless as they had a sample count of 1 (instead of 4 for MSAA) and an invalid pixel format.
Correct the defaults so they may be usful.
Not enough to fix https://github.com/flutter/flutter/issues/128963 , because we still have far too much state for Vulkan to handle
=> [Impeller] correct default PSO pixel format and sample count.

tools/clang_tidy/lib/clang_tidy.dart
The analyzer option `prefer_final_in_for_each` has been made the default and this has triggered new warnings.
=> Fix analyzer warnings (prefer_final_in_for_each is now the default)

DEPS, impeller/tools/malioc.gni, impeller/tools/malioc_cores.py
Resolves https://github.com/flutter/flutter/issues/128989.
Also bumps the buildroot to head for: https://github.com/flutter/buildroot/pull/744
Before:
```
[4876/5558] ACTION //flutter/impeller/entity:analyze_gles_entity_shaders_rrect_blur.frag_Mali-G78_malioc(//build/toolchain/android:clang_arm)
FAILED: gen/malioc/flutter/impeller/entity/rrect_blur.frag.gles.Mali-G78.json 
vpython3 ../../build/gn_run_binary.py ../../../../arm-tools/mali_offline_compiler/malioc --format json --fragment --core Mali-G78 --output /b/s/w/ir/cache/builder/src/out/android_debug_unopt/gen/malioc/flutter/impeller/entity/rrect_blur.frag.gles.Mali-G78.json /b/s/w/ir/cache/builder/src/out/android_debug_unopt/gen/flutter/impeller/entity/gles/rrect_blur.frag.gles
[4877/5558] ACTION …
```
=> [Impeller] Print malioc errors on CI

impeller/entity/contents/content_context.cc, impeller/entity/contents/content_context.h, impeller/renderer/pipeline_descriptor.h, impeller/renderer/renderer_unittests.cc
Reverts flutter/engine#42902
This is breaking iOS builds:
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8778085761769326737/+/u/run_platform_views_scroll_perf_non_intersecting_impeller_ios__timeline_summary/test_stdout
=> Revert "[Impeller] correct default PSO pixel format and sample count."

impeller/compiler/shader_lib/impeller/gaussian.glsl, impeller/entity/shaders/rrect_blur.frag
Resolves https://github.com/flutter/flutter/issues/128410.
16 bit floats aren't precise enough for positional computations, like computing SDFs in the case of the RRect blur.
Unfortunately, I haven't been able to repro this particular glitch in a playground -- it seems to be iOS-specific. In macOS desktop frame captures the problem seems to go away.
Before:
After:
=> [Impeller] Use 32 bit for positional stuff in the rrect blur

sky/tools/create_embedder_framework.py, sky/tools/create_full_ios_framework.py, sky/tools/create_ios_framework.py, sky/tools/create_macos_framework.py
Cherry pick into beta branch
[example build failures on beta](https://luci-milo.appspot.com/ui/p/dart-internal/builders/flutter/Mac%20engine_release_builder/232/overview)
Use the right binary architectures on scripts running dsymutil.
This is to fix the problem of bad architecture binary for builds running on dart internal: https://github.com/flutter/flutter/issues/128098
=> [CP] Use the arm64 dsymutil on Mac M1 machines (#42533)

ci/licenses_golden/licenses_flutter, shell/platform/android/BUILD.gn, shell/platform/android/io/flutter/embedding/android/KeyEmbedderResponder.java, shell/platform/android/io/flutter/embedding/android/KeyboardManager.java, shell/platform/android/io/flutter/embedding/engine/systemchannels/KeyboardChannel.java, shell/platform/android/test/io/flutter/embedding/android/KeyboardManagerTest.java, shell/platform/android/test/io/flutter/embedding/engine/systemchannels/KeyboardChannelTest.java, shell/platform/android/test/io/flutter/plugin/platform/PlatformViewsControllerTest.java
This PR updates the Android engine in order to answer to keyboard pressed state queries from the framework (as implemented in https://github.com/flutter/flutter/pull/122885).
This is a rework of https://github.com/flutter/engine/pull/41695 which was reverted in https://github.com/flutter/engine/pull/42346.
This issue with https://github.com/flutter/engine/pull/41695 was that the framework side did not get an answer when the channel was setup in the engine without registering a handler (on the engine side) to handle framework requests. The issue was reproducible when the engine initialization was managed by the app (see https://github.com/flutter/flutter/issues/122441#issuecomment-1582052616 for a repro).
This PR fixes this issue by changing `flutter/keyboard` lifecycle: the engine now …
=> [Android] Return the keyboard pressed state

ci/builders/linux_android_aot_engine.json
Engine V2 was not generating the size treemap. This change will start uploading the size treemap to the test logs.
Bug: https://github.com/flutter/flutter/issues/128482 …
=> Generate treemap.

ci/builders/README.md
Contexts are predefined python contexts that can be dynamically added to the test execution.
Bug: https://github.com/flutter/flutter/issues/129187 …
=> Document the use of contexts on engine_v2 tests.

impeller/geometry/geometry_unittests.cc, impeller/geometry/rect.h
- Utility to project a rectangle onto another rectangle.
- Fix constness for Rect::Expand.
- Add named methods for scaling.
=> [Impeller] Add Rect::Project

impeller/aiks/paint_pass_delegate.cc, impeller/entity/contents/texture_contents.cc, impeller/entity/entity_pass.cc
Makes subpasses easier to identify in frame captures.
=> [Impeller] Uniquely label subpasses and root blit

shell/platform/fuchsia/dart_runner/dart_component_controller.cc, shell/platform/fuchsia/dart_runner/dart_test_component_controller.cc, shell/platform/fuchsia/dart_runner/main.cc, shell/platform/fuchsia/dart_runner/meta/common.shard.cml, shell/platform/fuchsia/flutter/component_v2.cc, shell/platform/fuchsia/flutter/main.cc, shell/platform/fuchsia/runtime/dart/utils/tempfs.cc, shell/platform/fuchsia/runtime/dart/utils/tempfs.h
This was incorrectly made read-only in https://github.com/flutter/engine/commit/77d534c93fd9ab9de239c63f1db2607bef9b81b6; instead of implementing it locally, ask the component manager for the directory.
=> Remove process-local tempfs

impeller/core/allocator.cc, impeller/entity/contents/contents.cc, impeller/entity/contents/filters/blend_filter_contents.cc, impeller/entity/contents/filters/inputs/contents_filter_input.cc, impeller/entity/contents/filters/inputs/filter_input.h, impeller/entity/contents/tiled_texture_contents.cc, impeller/entity/contents/tiled_texture_contents.h, impeller/entity/contents/vertices_contents.cc, impeller/entity/entity.cc, impeller/entity/entity_unittests.cc
Fixes https://github.com/flutter/flutter/issues/128329
Fixes https://github.com/flutter/flutter/issues/128807
The panorama example app is still not quite visually on par with skia - the scaling or filtering or something isn't quite as nice as in the skia backend - but it does render now and no longer tries to create gigantical textures.
=> [Impeller] Fix up coverage hints for blending/vertices, fix TiledTextureContents::RenderToSnapshot

impeller/aiks/paint_pass_delegate.cc, impeller/entity/contents/texture_contents.cc, impeller/entity/contents/texture_contents.h, impeller/entity/entity_unittests.cc, impeller/geometry/geometry_unittests.cc, impeller/geometry/rect.h
Resolves https://github.com/flutter/flutter/issues/128353.
Depends on https://github.com/flutter/engine/pull/43026.
* Maps the texel coordinate space correctly relative to the geometry pixel coordinates.
* Use decal sampling for subpass textures.
* Simplify the computation by using new rect utilities such as `Rect::Project`.
Texture in subpass (the issue was that when copying to the parent pass, this image gets screwed up):
Before Impeller:
After Impeller:
=> [Impeller] Correctly compute UVs in texture fill

impeller/renderer/backend/vulkan/pipeline_cache_vk.cc, impeller/renderer/backend/vulkan/pipeline_cache_vk.h
At least from what I've found online, this API is already safe to call from multiple threads. From testing, at startup the presence of the mutex is adding ~100ms to shader creation time, as all compilations across N threads are fighting for the same lock.
https://github.com/flutter/flutter/issues/129050
=> [Impeller] remove Vulkan pipeline cache mutex.

impeller/renderer/backend/vulkan/fence_waiter_vk.cc
I suspect that some of the worst frame times are caused by submission blocking on adding a fence. Add a trace event that would make that obvious.
=> [Impeller] Add fence waiter trace event.

lib/ui/painting/image_decoder_impeller.cc
Reverts flutter/engine#42944
This didn't improve any of the benchmarks, which I think at least disproves my theory on overloading. Lets go back to the prior strategy and look for improvements elsewhere.
=> Revert "[Impeller] dont use concurrent runner to decode images on Android."

impeller/aiks/picture.cc, impeller/entity/contents/content_context.cc, impeller/entity/contents/content_context.h, impeller/renderer/pipeline_descriptor.h, impeller/renderer/render_target.cc
Also forces the creation of a stencil attachment always on Android to reduce the number of PSO variants.
https://github.com/flutter/flutter/issues/129050
=> [Impeller] default sample count back to 1 (but configure to 4 in defaults).

.github/dependabot.yml
The patches of CodeQL updated by dependabot were causing too many engine PRs. This change updates to allow for dependabot to just use minor versions.
Addresses https://github.com/flutter/flutter/issues/112911 …
=> Use minor version, ignore patches for CodeQL

impeller/renderer/backend/gles/context_gles.cc, impeller/renderer/backend/gles/sampler_library_gles.cc
Fixes uncontrolled crash when kDecal is used (as seen on https://github.com/flutter/engine/pull/43087).
=> [Impeller] Add validation forbidding SamplerAddressMode::kDecal on the OpenGLES backend

impeller/aiks/paint_pass_delegate.cc, impeller/entity/contents/texture_contents.cc, impeller/entity/contents/texture_contents.h, impeller/entity/entity_unittests.cc, impeller/geometry/geometry_unittests.cc, impeller/geometry/rect.h
Resolves https://github.com/flutter/flutter/issues/128353.
Reverts https://github.com/flutter/engine/pull/43087.
Reland without the kDecal usage --  we don't need it after the last iteration of fixes.
=> [Impeller] Reland: Correctly compute UVs in texture fill

shell/platform/common/client_wrapper/include/flutter/encodable_value.h
The code breaks in C++20 mode after libc++ removes comparisons for `std::vector` and replaces them with 'operator <=>'.
See cl/542541552 for context.
=> Workaround a release blocker after libc++ change

shell/platform/android/test/io/flutter/plugin/platform/PlatformViewsControllerTest.java, shell/platform/android/test_runner/src/main/resources/robolectric.properties
Make Robolectric tests work with SDK 33. The Robolectric doesn't support create presentation window now, so this CL also adds a custom presentation shadow to hook showing state to make related tests work. …
=> [android]: Make Robolectric tests work with SDK 33

impeller/aiks/aiks_unittests.cc, impeller/aiks/canvas.cc, impeller/entity/entity_pass.cc, impeller/renderer/render_target.cc
Collapses DrawPaint calls into clear colors when possible.
issue https://github.com/flutter/flutter/issues/129292
relands https://github.com/flutter/engine/pull/41711 …
=> [Impeller] Fix and reland drawPaint collapsing optimization.

lib/ui/painting/canvas.h
=> Removed outdated comment from lib/ui/canvas.h

shell/platform/android/io/flutter/plugin/editing/ImeSyncDeferringInsetsCallback.java
Solely documentation change to explain the reasoning behind the change in https://github.com/flutter/engine/pull/42700. …
=> Add a note in ImeSyncDeferringInsetsCallback explaining the reason behind capturing the latest final inset state

impeller/core/device_buffer.cc, impeller/core/device_buffer.h, impeller/renderer/backend/vulkan/capabilities_vk.cc, impeller/renderer/backend/vulkan/device_buffer_vk.cc, impeller/renderer/backend/vulkan/device_buffer_vk.h, lib/ui/painting/image_decoder_impeller.cc
I was missing the VMA flush.
Because skia is writing directly to the exposed ptr, we don't go through the OnSetContents which makes a flush call. Add a flush API and implement it for Vk DeviceBuffers.
=> [Impeller] re-enable buffer to texture blit Vulkan.

ci/builders/mac_clang_tidy.json
With context, recipes logic should be simplified without checking corresponding platform/property conditions.
With the `osx_sdk` context, it will install xcode accordingly.
=> Add osx_sdk context to mac_clang_tidy

impeller/renderer/blit_pass.cc
Next version of the crosstool will start warning about this (see: https://github.com/llvm/llvm-project/issues/38717)
=> [impeller] Explicitly cast enum class to int before passing it to a formatted string

impeller/renderer/backend/vulkan/fence_waiter_vk.cc, impeller/renderer/backend/vulkan/fence_waiter_vk.h
Moves signaled checks and callbacks out of the wait set mutex critical section.
The signaled checked can apparently be super slow on Qualcomm devices and the callback may hit allocators that could be slow as well.
=> [Impeller] FenceWaiterVK: Move potentially slow calls out of wait set mutex critical section.

impeller/renderer/backend/metal/context_mtl.h, impeller/renderer/backend/metal/context_mtl.mm, impeller/renderer/backend/metal/surface_mtl.mm
Just to curb confusion and make it searchable. I double-take this lingering command buffer in frame captures quite a bit.
=> [Impeller] Label present waiter command buffer in SurfaceMTL

ci/builders/README.md
Adds documentation for env variable substitution in test execution.
Bug: https://github.com/flutter/flutter/issues/129280 …
=> Add docs for magic variables.

impeller/entity/contents/content_context.cc
All of the backends already respect this property for the first color attachment in the pipeline. ~~Our Vulkan backend disables blending for a whole pipeline if the first color attachment has blending turned off.~~ This has been under our nose but I haven't checked it until now.
HSR might not be working on some Vulkan & OpenGLES drivers because of this.
=> [Impeller] Disable blending for Source blend mode

shell/gpu/gpu_surface_gl_impeller.cc, shell/gpu/gpu_surface_vulkan_impeller.cc
Similar to Metal, have the DL cull entities early that lie entirely outside the surface texture.
=> [Impeller] Supply surface cull rect for Vulkan & GLES dispatchers

display_list/benchmarking/dl_region_benchmarks.cc, display_list/geometry/dl_region.cc, display_list/geometry/dl_region.h, display_list/geometry/dl_region_unittests.cc, display_list/geometry/dl_rtree.cc, display_list/geometry/dl_rtree.h, display_list/geometry/dl_rtree_unittests.cc, flow/raster_cache.cc, flow/rtree.cc
Fixes https://github.com/flutter/flutter/issues/128412
Adds 
- `DlRegion DlRegion::MakeUnion(const Region &, const DlRegion &)`
- `DlRegion DlRegion::MakeIntersection(const Region &, const DlRegion &)`
- `bool DlRegion::intersects(const DlRegion &)`
- `bool DlRegion::intersects(const SkIRect &)`
Instead of per span line vector all spans are stored in continuous buffer. 
Complete benchmarks:
```
-----------------------------------------------------------------------------------------------
Benchmark                                                     Time             CPU   Iterations
-----------------------------------------------------------------------------------------------
BM_DlRegion_IntersectsSingleRect/Tiny                      2688 ns         2687 ns       258580 …
```
=> Implement union and intersection for DlRegion

impeller/renderer/backend/vulkan/swapchain_impl_vk.cc, impeller/renderer/backend/vulkan/swapchain_impl_vk.h, impeller/renderer/backend/vulkan/swapchain_vk.cc
If we don't follow the guidelines at https://developer.android.com/games/optimize/vulkan-prerotation , then any presentations while the screen is rotated will result in suboptimalKHR. Use a change in state across presentations from sucess -> suboptimal or suboptimal -> sucess to detect whether the swapchain needs to be recreated.
Fixes https://github.com/flutter/flutter/issues/129459 (mostly)
=> [Impeller] Treat SubOptimalKHR as rotated.

lib/web_ui/lib/src/engine/canvaskit/canvaskit_api.dart, lib/web_ui/lib/src/engine/canvaskit/image.dart, lib/web_ui/lib/src/engine/configuration.dart, lib/web_ui/lib/src/engine/dom.dart, lib/web_ui/lib/src/engine/initialization.dart, lib/web_ui/lib/src/engine/profiler.dart, lib/web_ui/lib/src/engine/safe_browser_api.dart, lib/web_ui/lib/src/engine/skwasm/skwasm_impl/memory.dart, lib/web_ui/lib/src/engine/skwasm/skwasm_impl/surface.dart, lib/web_ui/test/engine/profiler_test.dart
JSNumber.toDart will now be two functions: toDartDouble and toDartInt. Note that some code that looks like `toDart.toInt()` was kept as `toDartDouble.toInt()` instead of `toDartInt`, since `toDartInt` throws if the value is not an integer.
Object.toJS is now Object.toJSBox. An actual box is introduced on all backends now, and is unwrapped in JSBoxedDartObject.toDart. There are many usages of toJSAnyShallow that we should modify, but that's for a later CL.
This is to help land this CL: https://dart-review.googlesource.com/c/sdk/+/309082
https://dart-review.googlesource.com/c/sdk/+/309081 is the CL that added the new methods.
=> Refactor JSNumber.toDart and Object.toJS

impeller/renderer/backend/gles/render_pass_gles.cc
* Always set the color mask even if blending is disabled
* Fix a typo in the check of the mask against each color bit
=> [Impeller] Fixes for GLES color mask setup

impeller/base/timing.h, impeller/renderer/backend/vulkan/capabilities_vk.cc, impeller/renderer/backend/vulkan/capabilities_vk.h, impeller/renderer/backend/vulkan/context_vk.cc, impeller/renderer/backend/vulkan/pipeline_cache_vk.cc, impeller/renderer/backend/vulkan/pipeline_cache_vk.h, impeller/renderer/backend/vulkan/pipeline_library_vk.cc
Piping the feedback to logs is disabled by default but can be enabled by patching the source for now. If reading from logs gets to be useful, we can move it behind a flag. In traces, enabled by default, pipeline cache hits and misses will be shown via counters. The time taken to create a pipeline variant is already covered by existing traces.
This patch also sets up infrastructure in the impeller::CapabilitiesVK to quickly enable optional device extensions.
Pipeline feedback will only be reported if the device supports `VK_EXT_pipeline_creation_feedback`.
Example of logs:
```
E/flutter ( 2011): >>>>>>
E/flutter ( 2011): Pipeline 'GaussianBlurAlphaDecal Pipeline' Time: 48.60ms Cache Hit: 0 Base Accel: 0 Thread: 481449901232
E/flutter ( 2011):  Stage 1: Time: 12.91ms Cache Hit: 0 Base …
```
=> [Impeller] Report pipeline creation feedback to logs and traces.

impeller/renderer/backend/vulkan/allocator_vk.cc
I suspect this is where we're blocking on the texture uploads right now.
=> [Impeller] Add Vulkan allocator traces.

lib/web_ui/lib/src/engine/skwasm/skwasm_impl/renderer.dart, lib/web_ui/test/ui/filters_test.dart, lib/web_ui/test/ui/image_golden_test.dart
Benchmarks were failing because the code was reading the `frameCount` and `repetitionCount` before reading any frames out of the codec. The codec gets implicitly initialized when you read a frame, but we should return it to the user initialized so that `frameCount` and `repetitionCount` work even if you haven't read a frame yet. This is consistent with how CanvasKit's codec works.
Also, modified our unit tests so that they exercise the codecs in this way.
=> Initialize skwasm codecs before handing them back to the user.

lib/web_ui/lib/src/engine/semantics/checkable.dart, lib/web_ui/lib/src/engine/semantics/dialog.dart, lib/web_ui/lib/src/engine/semantics/image.dart, lib/web_ui/lib/src/engine/semantics/incrementable.dart, lib/web_ui/lib/src/engine/semantics/label_and_value.dart, lib/web_ui/lib/src/engine/semantics/live_region.dart, lib/web_ui/lib/src/engine/semantics/scrollable.dart, lib/web_ui/lib/src/engine/semantics/semantics.dart, lib/web_ui/lib/src/engine/semantics/tappable.dart, lib/web_ui/lib/src/engine/semantics/text_field.dart, lib/web_ui/test/engine/semantics/semantics_test.dart, lib/web_ui/test/engine/semantics/semantics_tester.dart, lib/web_ui/test/engine/semantics/text_field_test.dart
This PR fixes https://github.com/flutter/flutter/issues/128468 by changing the relationship between semantics nodes and their roles from this:
```
SemanticsNode one-to-many RoleManager
```
To this:
```
SemanticsNode one-to-one PrimaryRoleManager one-to-many RoleManager
```
Previously a node would simply have multiple role managers, some of which would be responsible for setting the `role` attribute. It wasn't clear which role manager should be doing this. It also wasn't clear which role managers were safe to reuse across multiple types of nodes. This led to the unfortunate situation in https://github.com/flutter/flutter/issues/128468 where `LabelAndValue` ended up overriding the role assigned by `Checkable`.
With this PR, a `SemanticsNode` has exactly one `PrimaryRoleManager`. A primary …
=> [web:a11y] introduce primary role responsible for ARIA roles

display_list/display_list_unittests.cc, display_list/effects/dl_image_filter_unittests.cc, display_list/testing/dl_rendering_unittests.cc, flow/rtree_unittests.cc
Update flutter engine includes to be more specific about use of Skia includes.
These changes are required to unblock the Skia roller that has new streamlined include files.
=> Update skia includes to be more specific

lib/web_ui/lib/src/engine/canvaskit/canvaskit_api.dart, lib/web_ui/lib/src/engine/canvaskit/image.dart, lib/web_ui/lib/src/engine/configuration.dart, lib/web_ui/lib/src/engine/dom.dart, lib/web_ui/lib/src/engine/initialization.dart, lib/web_ui/lib/src/engine/profiler.dart, lib/web_ui/lib/src/engine/safe_browser_api.dart, lib/web_ui/lib/src/engine/skwasm/skwasm_impl/memory.dart, lib/web_ui/lib/src/engine/skwasm/skwasm_impl/surface.dart, lib/web_ui/test/engine/profiler_test.dart
Reverts flutter/engine#43149
Reason for reverting: Broke the roll into the framework.
=> Revert "Refactor JSNumber.toDart and Object.toJS"

impeller/entity/shaders/blending/advanced_blend.glsl, impeller/entity/shaders/blending/ios/framebuffer_blend.glsl, impeller/tools/malioc.json
Investigated as part of https://github.com/flutter/flutter/issues/127232.
This took some time to work out, but:
* The amount of blending applied to the source color needs to be weighted by the destination alpha, which is pretty sensible behavior. This is in addition to applying source-over behavior with the resulting blended color.
* All of the blend functions assume that the color is already premultiplied, so remove the unpremultiply/premultiply surrounding the blend call.
All of the blend modes now visually match up with the [Flutter docs](https://api.flutter.dev/flutter/dart-ui/BlendMode.html), except for ColorBurn and Saturation, which appear to have a slight miscalculation going on with the red channel. Going to investigate and fix in a follow-up.
=> [Impeller] Correct advanced blending behavior.

impeller/entity/shaders/blending/advanced_blend.vert, impeller/entity/shaders/blending/blend.vert, impeller/entity/shaders/border_mask_blur.vert, impeller/entity/shaders/color_matrix_color_filter.vert, impeller/entity/shaders/gaussian_blur/gaussian_blur.vert, impeller/entity/shaders/glyph_atlas.vert, impeller/entity/shaders/gradient_fill.vert, impeller/entity/shaders/linear_to_srgb_filter.vert, impeller/entity/shaders/morphology_filter.vert, impeller/entity/shaders/position_color.vert, impeller/entity/shaders/rrect_blur.vert, impeller/entity/shaders/runtime_effect.vert, impeller/entity/shaders/solid_fill.vert, impeller/entity/shaders/srgb_to_linear_filter.vert, impeller/entity/shaders/texture_fill.vert, impeller/entity/shaders/yuv_to_rgb_filter.vert
Since we've let all vertex shaders opt into highp by default I believe these are redundant (though lets wait for malioc diff to confirm).
=> [Impeller] remove redundant highp modifiers in vertex shaders.

impeller/aiks/aiks_unittests.cc, impeller/geometry/color.cc, impeller/geometry/color.h, impeller/geometry/vector.h
Resolves https://github.com/flutter/flutter/issues/128606.
All CPU blends now match the behavior of Impeller's GPU blends, which (after https://github.com/flutter/engine/pull/43283) closely matches Skia's blends! Now we can finally use these.
https://github.com/flutter/engine/assets/919017/f9dc7323-fd14-4cdc-ba8b-930622be4206
=> [Impeller] Fix advanced CPU blend modes

lib/web_ui/test/canvaskit/fragment_program_test.dart, lib/web_ui/test/engine/channel_buffers_test.dart, testing/dart/channel_buffers_test.dart
To avoid analyzer warnings when utf8.encode() will return the more precise Uint8List type, we use const Utf8Encoder().convert() which already returns Uint8List
See https://github.com/dart-lang/sdk/issues/52801
=> Prepare for utf8.encode() to return more precise Uint8List type

impeller/aiks/aiks_unittests.cc, impeller/aiks/paint.cc, impeller/aiks/paint.h, impeller/aiks/paint_pass_delegate.cc, impeller/display_list/dl_dispatcher.cc, impeller/entity/contents/atlas_contents.cc, impeller/entity/contents/atlas_contents.h, impeller/entity/contents/tiled_texture_contents.cc, impeller/entity/contents/tiled_texture_contents.h, lib/ui/painting/image_decoder_impeller.cc, lib/ui/painting/image_decoder_impeller.h
Unwrap optionals that already have an empty state that must be checked, like `std::optional<std::shared_ptr<T>>` and `std::optional<std::function<T>>`.
=> [Impeller] Remove all double empties

impeller/renderer/backend/gles/context_gles.cc, impeller/renderer/backend/metal/context_mtl.mm, impeller/renderer/backend/vulkan/allocator_vk.cc, impeller/renderer/backend/vulkan/allocator_vk.h, impeller/renderer/backend/vulkan/capabilities_vk.cc, impeller/renderer/backend/vulkan/capabilities_vk.h, impeller/renderer/backend/vulkan/context_vk.cc, impeller/renderer/capabilities.cc, impeller/renderer/capabilities.h, impeller/renderer/capabilities_unittests.cc, impeller/scene/scene_context.cc
Some Android devices do not support the memory type eLazilyAllocated, which we use for MSAA and stencil textures. These textures were falling back to device local in dedicated allocations, which are expensive to both allocate and free. The dedicated allocation is implied by asking for eLazilyAllocated
Instead, perform a check for support for this memory type. Never request dedicated allocations (at least not until we have a compelling use case)
This should fix https://github.com/flutter/flutter/issues/129737
https://github.com/flutter/flutter/issues/129784
=> [Impeller] Check for lazy memory support.

impeller/aiks/canvas.cc, impeller/aiks/canvas.h, impeller/entity/entity_pass.cc, impeller/entity/entity_pass.h
Whoopsies, I missed a spot... Fix a possible crash where an optional nullptr can be provided as the backdrop filter proc. Related: https://github.com/flutter/engine/pull/43345
=> [Impeller] Unwrap optional procs in EntityPass

shell/platform/windows/accessibility_bridge_windows.cc, shell/platform/windows/accessibility_bridge_windows.h, shell/platform/windows/accessibility_bridge_windows_unittests.cc
Fix a typo that inverted an intended condition, and amend a unit test to check for this. This a11y event should target the focused node, but a fallback for when the focus returns null was inverted.
https://github.com/flutter/flutter/issues/127789
[CLA]: …
=> Fix inverted boolean in Windows document selection changed a11y event

impeller/entity/shaders/position_color.vert
The input was a float16 vec4, so the corresponding output must match or else we get a validation error. Not related to platform view issue.
=> [Impeller] Fix validation error in position color shader.

ci/licenses_golden/licenses_flutter, impeller/aiks/BUILD.gn, impeller/aiks/aiks_unittests.cc, impeller/aiks/color_filter.cc, impeller/aiks/color_filter.h, impeller/aiks/color_source.cc, impeller/aiks/paint.cc, impeller/aiks/paint.h, impeller/display_list/dl_dispatcher.cc
Part of https://github.com/flutter/flutter/issues/127232.
Adds an explicit ColorFilter concept to Aiks which wraps the GPU and CPU implementations. We're not using the CPU implementations yet, but I'll be getting it wired up in a follow-up patch.
=> [Impeller] Add explicit color filter types to Aiks.

impeller/aiks/aiks_unittests.cc, impeller/entity/contents/contents.cc, impeller/entity/contents/contents.h, impeller/entity/contents/solid_color_contents.cc, impeller/entity/entity.cc, impeller/entity/entity.h, impeller/entity/entity_pass.cc, impeller/entity/geometry/geometry.cc, impeller/entity/geometry/geometry.h
Now that all of the CPU blend modes work, we can allow back-to-back fullscreen solid color draws to get blended together regardless of their blend mode/color opacity.
=> [Impeller] Remove blend mode restrictions on clear color optimization

shell/platform/windows/flutter_window.cc, shell/platform/windows/flutter_window_unittests.cc
Flutter shouldn't crash if a view's `HWND` receives a `WM_GETOBJECT` message before it is attached to the view.
Fixes https://github.com/flutter/flutter/issues/129791 …
=> [Windows] Fix `FlutterWindow::GetNativeViewAccessible` crash

fml/logging.cc, fml/logging.h, shell/common/shell_unittests.cc
Fixes https://github.com/flutter/flutter/issues/130036
Also fixes a potential issue where the shell wasn't getting destroyed at the end of the test.
Since no log is actually printed ont he second go, the destructor of `LogMessage` never clears the static pointer, and the next test that tries to print a log tries to print to that pointer which is now garbage.
=> Release log capture at end of test

ci/builders/linux_clang_tidy.json, ci/builders/mac_clang_tidy.json
The clang-tidy shards have crept up to 60 minutes on some runs. This PR will bring them back down to around 30 minutes.
It does this by sharding the work for Mac/Linux `host_debug` across 4 shards. The clang-tidy work for ios/Android remains constrained to one shard. Unfortunately, the clang-tidy script sharding isn't smart enough to allow the ios/Android shards to participate in the `host_debug` sharding. This PR leaves that shard as-is, but we could further improve the runtime there if needed.
=> Further shard clang-tidy runs

impeller/display_list/dl_dispatcher.cc, impeller/display_list/dl_unittests.cc
Fixes https://github.com/flutter/flutter/issues/130084
If a display list is drawn into another display list and the child display list establishes a small clip, subsequent drawing operations are discarded when really they should not be.
The test is expected to render both a blue and a red square; before the fix it renders only the blue square since the red square is incorrectly clipped out.
See also https://github.com/dnfield/flutter_svg/issues/938
=> Handle nested display list clips in Impeller dispatcher

shell/platform/common/accessibility_bridge.cc, shell/platform/common/accessibility_bridge.h, shell/platform/common/accessibility_bridge_unittests.cc, shell/platform/common/test_accessibility_bridge.h, shell/platform/darwin/macos/framework/Source/AccessibilityBridgeMac.h, shell/platform/darwin/macos/framework/Source/AccessibilityBridgeMac.mm
This PR removes some dead code for recreating a11y node delegates. These code was used to refresh a11y information when the macOS embedder live swapped view controllers, but have become obsolete since https://github.com/flutter/engine/pull/39145 removed the support for such live swapping. …
=> Remove dead code for recreating a11y node delegates

impeller/aiks/aiks_unittests.cc, impeller/aiks/canvas.cc, impeller/aiks/canvas.h, impeller/entity/entity_pass.cc, impeller/entity/entity_pass.h
Prior to this patch, `DrawPicture` was untested and a no-op.
We needed a new routine to absorb Elements of a cloned pass into another pass, since appending a `Picture` as a subpass would be incorrect behavior for drawing a picture (since subpasses start with a blank image, which gets drawn to and then composited with the parent pass via a separate blending operation).
=> [Impeller] Fix DrawPicture.

.github/labeler.yml
The label was updated per flutter.dev/go/triage-2023-rfc
=> Account for updated Impeller label.

ci/builders/linux_clang_tidy.json
This PR runs the android_debug_arm64 clang-tidy job on a machine with more cores, and reduces the number of files linted that are redundant with the `host_debug` clang-tidy jobs.
=> Reduce redundant Linux clang-tidy work and run on more cores

.github/autosubmit.yml
Remove autosubmit config files that are no longer being used. This was from a previous design and not longer used.
List which issues are fixed by this PR. You must list at least one issue.
Part of https://github.com/flutter/flutter/issues/130182 …
=> Remove unused autosubmit configuration file

impeller/entity/inline_pass_context.cc
This could happen if the pass is immediately ended due to clear color optimization.
Fixes https://github.com/flutter/flutter/issues/130167
=> [Impeller] Check for a null command buffer in InlinePassContext::EndPass

shell/platform/linux/fl_dart_project.cc, shell/platform/linux/fl_dart_project_test.cc, shell/platform/linux/public/flutter_linux/fl_dart_project.h
Support overriding `aot_library_path` in `FLDartProject` on Linux.
Fixes: https://github.com/flutter/flutter/issues/128213 …
=> [linux] Allow overriding aot_library_path

impeller/display_list/display_list_dispatcher.cc, impeller/display_list/display_list_unittests.cc
CP issue: https://github.com/flutter/flutter/issues/130149
Fixes https://github.com/flutter/flutter/issues/130084
If a display list is drawn into another display list and the child display list establishes a small clip, subsequent drawing operations are discarded when really they should not be.
The test is expected to render both a blue and a red square; before the fix it renders only the blue square since the red square is incorrectly clipped out.
See also https://github.com/dnfield/flutter_svg/issues/938
=> Handle nested display list clips in Impeller dispatcher (#43442)

impeller/renderer/backend/vulkan/allocator_vk.cc, impeller/renderer/backend/vulkan/swapchain_impl_vk.cc
This shows up in the the aiks test harness in the color wheel with advanced blends.
Fixes https://github.com/flutter/flutter/issues/129853
=> [Impeller] Fix Vulkan validation error when there is a blit directed at a swapchain image.

display_list/utils/dl_matrix_clip_tracker.cc, display_list/utils/dl_matrix_clip_tracker.h, flow/diff_context.cc, flow/diff_context.h, flow/layers/layer_state_stack.cc, flow/layers/transform_layer.cc, flow/layers/transform_layer.h, flow/layers/transform_layer_unittests.cc, lib/ui/compositing/scene_builder.cc, lib/ui/painting/matrix.cc, lib/ui/painting/matrix.h
Fixes: https://github.com/flutter/flutter/issues/82961
Fixes: https://github.com/flutter/flutter/issues/113346
The fix was a simple fallout from the previous work to add support for SkM44 throughout the DL and Diff mechanisms (see https://github.com/flutter/flutter/issues/82955, https://github.com/flutter/flutter/issues/116198, https://github.com/flutter/engine/pull/37394)
Tested with its own existing and new unit tests as well as the test case from https://github.com/flutter/flutter/issues/113346
=> Use full 4x4 matrix transforms in TransformLayer

ci/licenses_golden/licenses_flutter, impeller/renderer/backend/vulkan/BUILD.gn, impeller/renderer/backend/vulkan/barrier_vk.cc, impeller/renderer/backend/vulkan/barrier_vk.h, impeller/renderer/backend/vulkan/blit_command_vk.cc, impeller/renderer/backend/vulkan/compute_pass_vk.cc, impeller/renderer/backend/vulkan/formats_vk.h, impeller/renderer/backend/vulkan/render_pass_vk.cc, impeller/renderer/backend/vulkan/swapchain_impl_vk.cc, impeller/renderer/backend/vulkan/texture_source_vk.cc, impeller/renderer/backend/vulkan/texture_source_vk.h, impeller/renderer/backend/vulkan/texture_vk.cc, impeller/renderer/backend/vulkan/texture_vk.h
Calling a pipeline barrier a transition seemed odd. Also, the members of the layout transition weren't documented and I always had a tough time remembering how barriers worked. It's hopefully clearer now.
=> [Impeller] Refactor barriers and add documentation.

display_list/testing/dl_rendering_unittests.cc, flow/embedded_views.h, flow/frame_timings_recorder_unittests.cc, flow/layers/layer_tree.cc, flow/raster_cache_unittests.cc, flow/testing/diff_context_test.h, shell/common/shell_test_external_view_embedder.h, shell/platform/android/external_view_embedder/external_view_embedder.h, shell/platform/darwin/ios/framework/Source/FlutterPlatformViews_Internal.h
Addresses most of https://github.com/flutter/flutter/issues/128060
Most of the uses of SkPicture and Recorder are removed from the engine sources. The few that remain are:
- DisplayList <-> Skia consistency testing code
- Legacy code only used from Fuchsia
- Dart CanvasKit uses which aren't actually using the local Skia sources or libraries
These are all comment and include file changes and so the testing is in the building.
=> remove include of SkPicture files from non-Fuchsia sources

shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm, shell/platform/darwin/ios/framework/Source/FlutterViewControllerTest.mm
Cherry-pick https://github.com/flutter/engine/commit/f3297964f2af68797290f3824d58677149c24023
fixes https://github.com/flutter/flutter/issues/130285 …
=> [iOS] Fix FlutterViewController retain cycle (#43379)

impeller/aiks/aiks_unittests.cc, impeller/aiks/color_filter.cc, impeller/aiks/color_filter.h, impeller/aiks/color_source.cc, impeller/aiks/paint.cc, impeller/compiler/shader_lib/impeller/texture.glsl, impeller/display_list/dl_dispatcher.cc, impeller/entity/contents/conical_gradient_contents.cc, impeller/entity/contents/conical_gradient_contents.h, impeller/entity/contents/contents.cc, impeller/entity/contents/contents.h, impeller/entity/contents/linear_gradient_contents.cc, impeller/entity/contents/linear_gradient_contents.h, impeller/entity/contents/radial_gradient_contents.cc, impeller/entity/contents/radial_gradient_contents.h, impeller/entity/contents/solid_color_contents.cc, impeller/entity/contents/solid_color_contents.h, impeller/entity/contents/sweep_gradient_contents.cc, impeller/entity/contents/sweep_gradient_contents.h, impeller/entity/shaders/conical_gradient_fill.frag, impeller/entity/shaders/conical_gradient_ssbo_fill.frag, impeller/entity/shaders/linear_gradient_fill.frag, impeller/entity/shaders/linear_gradient_ssbo_fill.frag, impeller/entity/shaders/radial_gradient_fill.frag, impeller/entity/shaders/radial_gradient_ssbo_fill.frag, impeller/entity/shaders/sweep_gradient_fill.frag, impeller/entity/shaders/sweep_gradient_ssbo_fill.frag, impeller/tools/malioc.json
Apply color filters on the CPU for solid colors and gradients. This fixes https://github.com/flutter/flutter/issues/127232 for the purely color-based color sources.
We still need to make the other special color blending paths respect the geometry mask in order to fully resolve the underlying issue:
* SaveLayers (if they have an interesting matrix filter -- without a matrix filter, it'll always work today)
* TiledTextureContents
* TextContents
* VerticesContents
* AtlasContents
=> [Impeller] Apply color filters on the CPU for solid colors & gradients.

shell/platform/fuchsia/dart_runner/meta/common.shard.cml, shell/platform/fuchsia/flutter/meta/common.shard.cml
Tracing is an optional component that is only included in eng builds, so the usage should be marked optional.
Bug: fxbug.dev/112433
=> [fuchsia][cml] Mark Tracing as Optional

ci/builders/linux_unopt.json, testing/run_all_unittests.cc
The unit tests can run in parallel so running on a bigger machine gives a good speedup. This shaves ~10 minutes off of linux_unopt time. Some of the DisplayList unit tests go over the 120s limit, so this PR also bumps the default limit to 300s.
=> Run linux_unopt on a machine with more cores

fml/message_loop_unittests.cc
If the wake happens while thread_ids_mutex is still held, then the test function may exit and destroy thread_ids_mutex before the pool thread task releases it.
Fixes https://github.com/flutter/flutter/issues/130344
=> Release the mutex in the CanCreateConcurrentMessageLoop test before waking the latch

ci/licenses_golden/licenses_flutter, impeller/renderer/backend/vulkan/BUILD.gn, impeller/renderer/backend/vulkan/allocator_vk.cc, impeller/renderer/backend/vulkan/context_vk.cc, impeller/renderer/backend/vulkan/context_vk.h, impeller/renderer/backend/vulkan/device_buffer_vk.cc, impeller/renderer/backend/vulkan/device_buffer_vk.h, impeller/renderer/backend/vulkan/resource_manager_vk.cc, impeller/renderer/backend/vulkan/resource_manager_vk.h
This also sets up well for a unified resource pooling and deferred collection mechanism.
=> [Impeller] Create a resource manager that batch deallocates resources on a dedicated thread.

impeller/aiks/color_source.cc, impeller/entity/contents/color_source_contents.cc, impeller/entity/contents/color_source_contents.h, impeller/entity/contents/color_source_text_contents.cc, impeller/entity/contents/conical_gradient_contents.cc, impeller/entity/contents/contents.h, impeller/entity/contents/linear_gradient_contents.cc, impeller/entity/contents/radial_gradient_contents.cc, impeller/entity/contents/solid_color_contents.cc, impeller/entity/contents/sweep_gradient_contents.cc, impeller/entity/contents/tiled_texture_contents.cc, impeller/entity/entity_unittests.cc
Someday all the things will be documented and explained intuitively.
=> [Impeller] Document ColorSourceContents

display_list/effects/dl_path_effect.h, display_list/effects/dl_path_effect_unittests.cc, display_list/image/dl_image.h, display_list/skia/dl_sk_conversions_unittests.cc, display_list/testing/dl_test_snippets.h, flow/layers/display_list_raster_cache_item.h, flow/layers/layer_tree.h, flow/raster_cache.cc, flow/raster_cache.h, flow/raster_cache_unittests.cc, flow/testing/mock_raster_cache.h, lib/ui/compositing/scene.h, lib/ui/painting/picture.h, lib/ui/snapshot_delegate.h, shell/common/engine.h, shell/common/persistent_cache_unittests.cc, shell/common/serialization_callbacks.cc, shell/common/serialization_callbacks.h, testing/mock_canvas.cc
Most of the #include directives for SkPicture are removed except where they are still functional. Many comments rewritten to no longer be SkPicture-centric.
- DL unit tests still use it for consistency testing
- rasterizer/engine still use it for screen shot support
- Fuchsia still uses it extensively
=> header file cleanup focusing on removing unnecessary SkPicture includes

flow/layers/transform_layer.cc
Addresses comment in https://github.com/flutter/flutter/issues/130303#issuecomment-1632895439
No tests as this is just a comment.
=> Add comment to use of 3x3 mapRect in TransformLayer

impeller/core/formats.h, impeller/renderer/backend/gles/render_pass_gles.cc, impeller/renderer/renderer_unittests.cc
Fixes for asymmetric stencil descriptors
- Fix GLES implementation to properly set back and front face options in the case that they aren't identical.
- Add write_mask to hash function.
https://github.com/flutter/flutter/issues/129855
=> [Impeller] Fixes for asymmetric stencil descriptors

lib/web_ui/lib/src/engine/canvaskit/canvaskit_api.dart, lib/web_ui/lib/src/engine/canvaskit/image.dart, lib/web_ui/lib/src/engine/configuration.dart, lib/web_ui/lib/src/engine/dom.dart, lib/web_ui/lib/src/engine/initialization.dart, lib/web_ui/lib/src/engine/profiler.dart, lib/web_ui/lib/src/engine/safe_browser_api.dart, lib/web_ui/lib/src/engine/skwasm/skwasm_impl/font_collection.dart, lib/web_ui/lib/src/engine/skwasm/skwasm_impl/memory.dart, lib/web_ui/lib/src/engine/skwasm/skwasm_impl/surface.dart, lib/web_ui/test/engine/profiler_test.dart
This reverts commit dce75ab4cf647eec6699f8a30ba2289a3738b307.
This also makes some small changes to make onBenchmark a JSExportedDartFunction instead of a JSBoxedDartObject. This is for changes in https://github.com/flutter/flutter/pull/129436 and to account for the fact that flutter/packages provides an `allowInterop`'d function. Benchmarks tests pass with this CL.
=> Reland "Refactor JSNumber.toDart and Object.toJS"

lib/ui/channel_buffers.dart, testing/dart/channel_buffers_test.dart
Fixes https://github.com/flutter/flutter/issues/116652
=> Document (and assert) that channel names can't contains nulls

ci/licenses_golden/licenses_flutter, impeller/renderer/backend/vulkan/BUILD.gn, impeller/renderer/backend/vulkan/allocator_vk.cc, impeller/renderer/backend/vulkan/allocator_vk.h, impeller/renderer/backend/vulkan/device_buffer_vk.cc, impeller/renderer/backend/vulkan/device_buffer_vk.h, impeller/renderer/backend/vulkan/formats_vk.h, impeller/renderer/backend/vulkan/pipeline_library_vk.h, impeller/renderer/backend/vulkan/render_pass_vk.cc, impeller/renderer/backend/vulkan/sampler_vk.h, impeller/renderer/backend/vulkan/vk.h, impeller/renderer/backend/vulkan/vma.cc, impeller/renderer/backend/vulkan/vma.h
=> [Impeller] Add RAII wrappers for VMA objects.

impeller/renderer/backend/vulkan/context_vk.cc
I didn't know this when I wrote it initially but structure chains will throw a compile time error if a chain member violates the Vulkan spec. pNext chaining is easy to mess up otherwise and we should use structure chains where possible. We are already doing this during pipeline construction.
=> [Impeller] Remove unactionable error logs and use structure chains for instance creation.

tools/gn
We used to default to force-enabled, which would fail on non-GOMA setups.
=> Make GOMA state automatic by default

lib/web_ui/lib/src/engine/canvaskit/color_filter.dart, lib/web_ui/lib/src/engine/canvaskit/image_filter.dart, lib/web_ui/lib/src/engine/canvaskit/layer.dart, lib/web_ui/test/canvaskit/layer_test.dart
Fixes https://github.com/flutter/flutter/issues/128788
=> Apply the transform of an image filter layer to paint bounds in the CanvasKit backend

impeller/renderer/renderer_unittests.cc
- Add UI to select front and back face comparision functions.
- Fix back face.
=> Improve Stencil Playground test

lib/web_ui/lib/src/engine/semantics/text_field.dart, lib/web_ui/test/engine/semantics/semantics_test.dart, lib/web_ui/test/engine/semantics/text_field_test.dart
fixes https://github.com/flutter/flutter/issues/128709
requires https://github.com/flutter/flutter/pull/129652
The issue is that when textfield focus in framework and web engine a11y are out of sync, the framework keep sending update with textfield focus = true and causes web engine to keep refocusing the textfield. …
=> [web] TextField a11y focus should call didGain/didLose a11y focus action

lib/ui/dart_ui.cc, lib/ui/text.dart, lib/ui/text/paragraph_builder.cc, lib/ui/text/paragraph_builder.h, lib/web_ui/lib/src/engine/canvaskit/canvaskit_api.dart, lib/web_ui/lib/src/engine/canvaskit/renderer.dart, lib/web_ui/lib/src/engine/canvaskit/text.dart, lib/web_ui/lib/text.dart, lib/web_ui/test/canvaskit/text_test.dart, testing/dart/paragraph_test.dart, third_party/txt/src/skia/paragraph_builder_skia.cc, third_party/txt/src/txt/paragraph_style.h
Reverts flutter/engine#43118
The incorrect default value (`true` instead of  `false`) was used in the PR and that caused internal test failures. I'll add a test before trying to reland.
=> Revert "Add a flag to `ParagraphBuilder` for rounding hack migration"

shell/platform/darwin/ios/framework/Source/FlutterDartVMServicePublisher.mm, shell/platform/darwin/ios/framework/Source/FlutterEngine.mm
Adding logs to help debug why VM Service is being published when it shouldn't (https://github.com/flutter/flutter/issues/129987 and https://github.com/flutter/flutter/issues/129836). …
=> Add logs to debug VM Service Publication

impeller/renderer/backend/vulkan/allocator_vk.cc, impeller/renderer/backend/vulkan/device_buffer_vk.cc
Not all devices support the host_coherent + host_visible + device_local combo (though most do). I believe this change was associated with a slight regression in performance, so back it out and go back to flush to see if that improves things.
https://flutter-flutter-perf.skia.org/e/?begin=1687535096&end=1689267073&queries=device_type%3DSM-G973U1%26test%3Dnew_gallery_impeller__transition_perf&requestType=0&selected=commit%3D35596%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DSM-G973U1%252Cdevice_version%253Dnone%252Chost_type%253Dlinux%252Csub_result%253D99th_percentile_frame_rasterizer_time_millis%252Ctest%253Dnew_gallery_impeller__transition_perf%252C
Specifically:
=> [Impeller] Switch back to using explicit flush for device buffers.

impeller/entity/contents/runtime_effect_contents.cc
The framework has switched into mat3 by default, which means the fragment program ink sparkle has replaced the default ink splash. Since this is not implemented, all of the impeller benchmarks are crashign.
No-op this so we at least get benchmark numbers until its implemented.
=> [Impeller] no-op fragment program on Android until it works.

lib/ui/natives.dart, lib/web_ui/lib/natives.dart
Fixes https://github.com/flutter/flutter/issues/59205
=> Remove unimplemented API call saveCompilationTrace

lib/ui/text.dart, lib/web_ui/lib/src/engine/platform_dispatcher.dart, lib/web_ui/lib/src/engine/services/message_codecs.dart, lib/web_ui/lib/src/engine/skwasm/skwasm_impl/raw/raw_memory.dart, lib/web_ui/lib/ui_web/src/ui_web/asset_manager.dart, lib/web_ui/test/canvaskit/fragment_program_test.dart, lib/web_ui/test/common/fake_asset_manager.dart, lib/web_ui/test/engine/channel_buffers_test.dart, lib/web_ui/test/ui/fragment_shader_test.dart, lib/web_ui/test/ui/image_golden_test.dart, shell/common/fixtures/shell_test.dart, shell/platform/fuchsia/dart-pkg/zircon/test/zircon_tests.dart, shell/platform/fuchsia/flutter/tests/integration/embedder/parent-view/lib/parent_view.dart, shell/platform/fuchsia/flutter/tests/integration/mouse-input/mouse-input-view/lib/mouse-input-view.dart, shell/platform/fuchsia/flutter/tests/integration/text-input/text-input-view/lib/text_input_view.dart, shell/platform/fuchsia/flutter/tests/integration/touch-input/embedding-flutter-view/lib/embedding-flutter-view.dart, shell/platform/fuchsia/flutter/tests/integration/touch-input/touch-input-view/lib/touch-input-view.dart, shell/platform/windows/fixtures/main.dart, testing/dart/assets_test.dart, testing/dart/channel_buffers_test.dart, testing/scenario_app/lib/main.dart, testing/scenario_app/lib/src/channel_util.dart
The change in [0] has propagated now everywhere, so we can use 
`utf8.encode()` instead of the longer `const Utf8Encoder.convert()`.
Also it cleans up code like
```
Uint8List bytes;
bytes.buffer.asByteData();
```
as that is not guaranteed to be correct, the correct version would be
```
Uint8List bytes;
bytes.buffer.asByteData(bytes.offsetInBytes, bytes.length);
```
a shorter hand for that is:
```
Uint8List bytes;
ByteData.sublistView(bytes);
```
[0] https://github.com/dart-lang/sdk/issues/52801
=> Use utf8.encode() instead of longer const Utf8Encoder.convert()

display_list/utils/dl_matrix_clip_tracker.cc, display_list/utils/dl_matrix_clip_tracker_unittests.cc
Fixes root cause for https://github.com/flutter/flutter/issues/129816
Logic for reducing the cull_rect for a diff clip had a number of errors. The new test should cover all cases.
=> Fix DisplayListMatrixClipTracker handling of diff clips

impeller/entity/entity_pass.cc, shell/gpu/gpu_surface_gl_impeller.cc, shell/platform/embedder/embedder.cc
https://github.com/flutter/flutter/issues/130619
=> [Impeller] Ensure that missing color attachment 0u does not cause crash in embedder API

impeller/aiks/aiks_unittests.cc, impeller/aiks/canvas.cc, impeller/aiks/canvas.h, impeller/display_list/dl_dispatcher.cc, impeller/entity/contents/color_source_text_contents.cc, impeller/entity/contents/color_source_text_contents.h, impeller/entity/contents/content_context.h, impeller/entity/contents/contents.h, impeller/entity/contents/text_contents.cc, impeller/entity/contents/text_contents.h, impeller/entity/entity.cc, impeller/entity/entity.h, impeller/entity/entity_pass.cc, impeller/entity/entity_pass.h, impeller/entity/entity_unittests.cc, impeller/typographer/backends/skia/text_frame_skia.cc, impeller/typographer/backends/skia/text_frame_skia.h, impeller/typographer/backends/skia/text_render_context_skia.cc, impeller/typographer/backends/skia/text_render_context_skia.h, impeller/typographer/font.h, impeller/typographer/font_glyph_pair.h, impeller/typographer/lazy_glyph_atlas.cc, impeller/typographer/lazy_glyph_atlas.h, impeller/typographer/text_frame.cc, impeller/typographer/text_frame.h, impeller/typographer/text_render_context.cc, impeller/typographer/text_render_context.h, impeller/typographer/typographer_unittests.cc
Alternative to https://github.com/flutter/engine/pull/43662
Records the basis vector of the current CTM into text contents and reuses that rather than trying to get it again at render time. That method breaks if perspective is involved in the CTM and a subpass gets translated, which can modify the scale (and rotation) of the matrix.
We're definitely not doing things quite right with perspective here, but the real fix to that is to either record the fully transformed glyph into the atlas or to use SDF/path based rendering.
Fixes https://github.com/flutter/flutter/issues/130476
I still have some concerns about how `EntityPass::Render` is a mix of mutations and constness but we can try to address that independently. 
I expect this to re-improve the regression noted in …
=> [Impeller] Fix text scaling issues again, this time with perspective when a save layer is involved

lib/web_ui/lib/src/engine/semantics/dialog.dart, lib/web_ui/lib/src/engine/semantics/focusable.dart, lib/web_ui/lib/src/engine/semantics/label_and_value.dart, lib/web_ui/lib/src/engine/semantics/live_region.dart, lib/web_ui/lib/src/engine/semantics/semantics.dart, lib/web_ui/lib/src/engine/semantics/tappable.dart, lib/web_ui/test/engine/semantics/semantics_test.dart
Always add secondary role managers irrespective of the initial state of the semantic node, and have role manager decide whether it applies to the node or not.
Fixes https://github.com/flutter/flutter/issues/130546
=> [web] always add secondary role managers

lib/ui/fixtures/ui_test.dart, lib/ui/platform_dispatcher.dart, lib/ui/window.dart, lib/ui/window/platform_configuration.cc, testing/dart/window_test.dart
This makes the FlutterView object a little bit less brittle by not depending on the PlatformDispatcher so much.
=> Move ViewConfiguration ownership to FlutterView

shell/platform/android/io/flutter/embedding/engine/renderer/FlutterRenderer.java, shell/platform/android/test/io/flutter/embedding/engine/renderer/FlutterRendererTest.java
Fixes: https://github.com/flutter/flutter/issues/130379
[Discord]: …
=> Optimizing performance by avoiding multiple GC operations caused by multiple surface destruction notifications

impeller/renderer/backend/gles/description_gles.cc, impeller/renderer/backend/gles/proc_table_gles.h, shell/platform/embedder/embedder_surface_gl_impeller.cc
Fixes https://github.com/flutter/flutter/issues/130514
The context wasn't current so we couldn't get the GL version.
The extension lookup was throwing an invalid enum error, the desktop opengl docs say to use a different method.
=> [Impeller] fix some OpenGL Linux desktop issues.

impeller/renderer/backend/vulkan/pipeline_library_vk.cc
The trace counter was missing the series name and ID.
=> [Impeller] Fix pipeline stats traced to the timeline.

impeller/aiks/aiks_unittests.cc, impeller/entity/contents/filters/blend_filter_contents.cc
Resolves https://github.com/flutter/flutter/issues/130411.
The remaining difference in appearance is due to https://github.com/flutter/flutter/issues/127770 -- Impeller's blurs skew too large.
Before:
After:
=> [Impeller] Correct coverage hint usage in PipelineBlend

ci/licenses_golden/excluded_files, ci/licenses_golden/licenses_dart, ci/licenses_golden/tool_signature, tools/licenses/lib/main.dart
This will avoid conflicts between Dart rolls and rolls of other third party components such as ANGLE.
=> Move Dart licenses into a separate golden file

shell/platform/windows/accessibility_bridge_windows_unittests.cc, shell/platform/windows/flutter_windows_engine.cc, shell/platform/windows/flutter_windows_engine.h, shell/platform/windows/flutter_windows_view.cc, shell/platform/windows/flutter_windows_view_unittests.cc
The ownership of the accessibility bridge was moved from `FlutterWindowsEngine` to `FlutterWindowsView`. This change moves leftover accessibility bridge helpers/logic from the engine to the view.
Addresses: https://github.com/flutter/flutter/issues/124995
Follow-up to: https://github.com/flutter/engine/pull/41308 …
=> [Windows] Remove accessibility bridge helpers from the engine

lib/ui/painting.dart
Update the blend mode section of the documentation to specify the correct blend modes.
Fixes https://github.com/flutter/flutter/issues/130747
=> Fix drawVertices documentation

tools/gn
And set the level to `-Oz` for iOS and Android.
=> Add a GN flag to set the Dart VM's optimization level

fml/platform/posix/native_library_posix.cc
This reverts commit 321f8015b9c2f9d47585647ce036cc8743966d27.
This didn't seem to help with debugging b/276657840. Fixes https://github.com/flutter/flutter/issues/125523. …
=> Revert "Log dlopen errors in opt builds (#41477)"

shell/common/rasterizer.cc, shell/platform/darwin/ios/framework/Source/FlutterView.mm
Fixes the following errors when building with a C++20 toolchain.
I don't really know C++ that well so any pointers would be appreciated. 
For the change to the lambda, we can't follow the recommendation to capture `*this` explicitly because that wouldn't compile under C++17. This PR changes the semantics slightly to capture `surface_` by reference, which might be still okay?
For b/289776142
```
error: implicit capture of 'this' with a capture default of '=' is deprecated [-Werror,-Wdeprecated-this-capture]
93 |       if (surface_) {
|           ^
note: add an explicit capture of 'this' to capture '*this' by reference
91 |     raster_thread_merger_->SetMergeUnmergeCallback([=]() {
|                                                     ^
| …
```
=> Minor fixes for C++20 compatibility

flow/compositor_context.cc, flow/compositor_context.h, flow/diff_context.cc, flow/diff_context.h, flow/layers/clip_rrect_layer_unittests.cc, flow/layers/clip_shape_layer.h, flow/layers/layer.h, flow/layers/layer_tree.cc, flow/testing/diff_context_test.cc, flow/testing/diff_context_test.h, flow/testing/layer_test.h
Fixes https://github.com/flutter/flutter/issues/130775
On the Skia backend, antiAliasWithSaveLayer is the highest fidelity clipping option. In the Impeller backend, there isn't any difference in how we clip, since the stencil buffer is always used. Nevertheless we were still inserting the save layer, which results in an extra offscreen texture and is wasteful.
Track if impeller is enabled in the diff/preroll/paint context and avoid inserting a save layer.
=> [Impeller] Avoid inserting additional save layers based on clip configuration.

.ci.yaml
CP of https://github.com/flutter/engine/pull/43771
Skip windows arm on release branches. This broke during the migration to the release builders.
=> [CP] [ci.yaml] Skip windows arm on releases

.ci.yaml
These builds have had engine v2 variants running for nearly a quarter or more in most cases, and they are now not serving much of a purpose. Additionally, during MTV peak hours, queue times and therefore overall cycle times are getting too long, and we should be freeing up these resources.
=> Remove obsolete legacy engine builds from staging

.ci.yaml
This PR increases orchestrator timeouts to avoid the case where subjobs that are making progress after a long queue time may be needlessly cancelled if the orchestrator runs over a too-small timeout.
=> Increase engine v2 orchestrator timeouts

shell/platform/embedder/tests/embedder_unittests_util.cc
In https://skia-review.googlesource.com/c/skia/+/671679 Skia updated the calls to SkImage::makeSubset() to always need a `GrDirectContext*`. This updates Flutter's one call that needed it. …
=> Update legacy call to SkImage::makeSubset

flow/layers/image_filter_layer.cc, flow/layers/image_filter_layer_unittests.cc
Fixes https://github.com/flutter/flutter/issues/130318
=> Apply the offset to the child bounds of an ImageFilterLayer with no filter
