.github/labeler.yml
The desktop team uses the [`affects: desktop`](https://github.com/flutter/engine/pulls?q=is%3Aopen+label%3A%22affects%3A+desktop%22+sort%3Aupdated-desc) label to [triage](https://github.com/flutter/flutter/wiki/Triage#desktop-platforms-team-team-desktop) pull requests.
=> Add the 'affects: desktop' label to labeler.yml

lib/web_ui/dev/felt_config.dart, lib/web_ui/dev/test_platform.dart, lib/web_ui/lib/src/engine/configuration.dart, lib/web_ui/lib/src/engine/dom.dart, lib/web_ui/test/canvaskit/configuration_canvaskit_variant_test.dart, lib/web_ui/test/common/test_initialization.dart, lib/web_ui/test/engine/configuration_test.dart, lib/web_ui/test/felt_config.yaml
At some point, we started setting `useColorEmoji` to true in our tests, but we were doing it in a way that resets all other configurations to their defaults. This caused the `canvasKitVariant` config to be lost and always set to the default `auto`.
This PR fixes the issue and adds tests to:
1. Make sure that the CanvasKit suite always runs with a specific variant (not `auto`).
2. Make sure the given CanvasKit variant makes it all the way through to the tests.
The test harness uses a backdoor (a global JS property on `window`) to communicate which canvaskit variant it's using. The test then compares that with `configuration.canvasKitVariant` to make sure they match. If they don't match, then the configuration was lost somewhere on the way.
Fixes …
=> [web] Preserve correct CanvasKit Variant during test initialization

impeller/renderer/backend/vulkan/command_encoder_vk.cc
Helps while investigating https://github.com/flutter/flutter/issues/131001
=> More validation logs for CommandEncoderVK submission

impeller/renderer/backend/vulkan/command_pool_vk.cc
Without this bit, we're holding it wrong. From the docs:
> VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT allows any command buffer allocated from a pool to be individually reset to the initial state; either by calling vkResetCommandBuffer, or via the implicit reset when calling vkBeginCommandBuffer. If this flag is not set on a pool, then vkResetCommandBuffer must not be called for any command buffer allocated from that pool.
This means our reset calls later are getting ignored.
Fixes https://github.com/flutter/flutter/issues/131001
=> [Impeller] [Vulkan] Add reset command buffer bit to command pools.

impeller/docs/read_frame_captures.md, impeller/docs/renderdoc_frame_capture.md, impeller/docs/xcode_frame_capture.md, impeller/playground/backend/vulkan/playground_impl_vk.cc, impeller/playground/playground.cc, impeller/renderer/backend/metal/context_mtl.mm, impeller/renderer/backend/vulkan/context_vk.cc, impeller/renderer/backend/vulkan/queue_vk.cc, impeller/renderer/command_buffer.h, lib/ui/painting/image_decoder_unittests.cc, shell/common/shell.cc, shell/common/shell.h, shell/platform/android/io/flutter/embedding/android/FlutterActivityAndFragmentDelegate.java, shell/platform/android/io/flutter/embedding/engine/plugins/util/GeneratedPluginRegister.java, shell/platform/android/test/io/flutter/embedding/android/FlutterActivityTest.java, shell/platform/darwin/ios/framework/Source/FlutterEngine.mm, shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.h, shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm, shell/platform/darwin/ios/framework/Source/FlutterViewController.mm, shell/platform/darwin/ios/framework/Source/FlutterViewControllerTest.mm, shell/platform/darwin/ios/framework/Source/FlutterViewControllerTest_mrc.mm
There are several places in the engine using the word "setup" incorrectly. I have changed them to "set up" …
=> Refactor: fix typo "setup" -> "set up"

impeller/aiks/testing/context_mock.h, impeller/renderer/backend/gles/context_gles.cc, impeller/renderer/backend/gles/context_gles.h, impeller/renderer/backend/metal/context_mtl.h, impeller/renderer/backend/metal/context_mtl.mm, impeller/renderer/backend/vulkan/context_vk.cc, impeller/renderer/backend/vulkan/context_vk.h, impeller/renderer/context.h, impeller/renderer/testing/mocks.h, lib/ui/painting/image_decoder_unittests.cc
I've been trying to avoid this, but since the context type may vary through runtime decisions, we just need something like this to select which shader data to pull from the Dart GPU bundle at runtime. One alternative would be to add a special omni shader concept to the HAL, but that seems worse than just letting renderers key with a backend enum sometimes.
Cautioned against using it for cap checks in the doc string.
=> [Impeller] Add a way to query the gfx backend type.

impeller/renderer/backend/vulkan/capabilities_vk.cc
This is causing a validation failure on the Vulkan backend at ToT, as discovered by @jonahwilliams.
Need to figure out why this isn't getting hit in the Vulkan goldens.
=> [Impeller] Disable color attachment removal for clips on VK

impeller/entity/entity_pass.cc
The InlinePassContext will not apply the clear color within a parent pass that is already in progress.
Fixes https://github.com/flutter/flutter/issues/130824
=> [Impeller] Do not use clear color optimization if the subpass is being collapsed into its parent

impeller/renderer/backend/vulkan/command_encoder_vk.cc, impeller/renderer/backend/vulkan/command_encoder_vk.h, impeller/renderer/backend/vulkan/compute_pass_vk.cc, impeller/renderer/backend/vulkan/descriptor_pool_vk.cc, impeller/renderer/backend/vulkan/descriptor_pool_vk.h, impeller/renderer/backend/vulkan/render_pass_vk.cc
Also removes pools for eSampledImage and eSampler as they appear to be unused in our generated headers.
This may have a minor impact on performance as from experimentation we will re-allocate fewer command pools.
=> [Impeller] size command pools to npot of command count.

impeller/compiler/switches.cc
This typo was just present in the help text. The actual switch name was correct.
=> [Impeller] Fix typo in help for compiler switches.

display_list/testing/dl_rendering_unittests.cc, lib/web_ui/skwasm/surface.cpp, shell/platform/fuchsia/flutter/flatland_external_view_embedder.cc, shell/platform/fuchsia/flutter/gfx_external_view_embedder.cc
Reverts flutter/engine#43902
Speculative revert for Fuchsia tests that began failing/timing-out on this commit: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Fuchsia%20FEMU/16871/overview
=> Revert "Remove more calls to SkCanvas::flush() and SkSurface::flush()"

ci/licenses_golden/licenses_flutter, impeller/entity/BUILD.gn, impeller/entity/contents/clip_contents.cc, impeller/entity/contents/content_context.cc, impeller/entity/contents/content_context.h, impeller/entity/shaders/clip.frag, impeller/entity/shaders/clip.vert, impeller/renderer/backend/gles/context_gles.cc, impeller/renderer/backend/gles/render_pass_gles.cc, impeller/renderer/backend/metal/context_mtl.mm, impeller/renderer/backend/vulkan/capabilities_vk.cc, impeller/renderer/backend/vulkan/capabilities_vk.h, impeller/renderer/capabilities.cc, impeller/renderer/capabilities.h, impeller/tools/malioc.json
Turns out removing the color attachment is failing Metal validation on iOS due to the pipeline color attachments mismatching the framebuffer (even though it winds up rendering correctly).
So this patch replaces the mechanism with a better default config, including:
* dedicated shaders that are less expensive than Solid Fill
* destination blending
I'll take another swing at trying to get it to work if the iOS benchmarks pop back up a bit from this. For now, this fixes the validation failure and should make clips a tad faster on Vulkan and GLES.
=> [Impeller] Fix clip pipeline validation failure; add dedicated clip shaders.

shell/gpu/gpu_surface_gl_impeller.cc, shell/gpu/gpu_surface_vulkan_impeller.cc
This was missing compared to the metal version. Doesn't matter on flutter/gallery but might matter elsewhere once platform views are working.
=> [Impeller] provide cull rect to Canvas in GL/Vulakn impeller backend.

impeller/aiks/aiks_unittests.cc, impeller/entity/contents/filters/matrix_filter_contents.cc, impeller/entity/entity_pass.cc
Resolves https://github.com/flutter/flutter/issues/130355.
When drawing a backdrop filter, we offset the backdrop entity with `-local_pass_position` in order to align the backdrop texture with the position of the pass it's being drawn to. When rendering the filter, this transform propagates to the filter snapshot. Prior to this change, that offset was being applied within the space of the backdrop filter's matrix, which is wrong! It needs to be applied in screen space.
We didn't notice this prior to the coverage hint optimization because we were previously forcing subpass sizes to match the parent whenever a backdrop filter was present.
This one was very difficult to reason through at first, and so I added a detailed comment to explain the rationale behind the behavioral differences …
=> [Impeller] Fix MatrixFilter multiplication ordering for subpasses.

impeller/aiks/aiks_unittests.cc, impeller/entity/contents/filters/matrix_filter_contents.cc, impeller/entity/entity_pass.cc
Reverts flutter/engine#43943
Closes https://github.com/flutter/flutter/issues/131182.
Opens https://github.com/flutter/flutter/issues/130355.
Regression spotted in https://github.com/flutter/flutter/issues/131182
=> Revert "[Impeller] Fix MatrixFilter multiplication ordering for subpasses."

impeller/renderer/backend/vulkan/swapchain_impl_vk.cc, impeller/renderer/backend/vulkan/swapchain_impl_vk.h
Testing with validation enabled shows no crashes or validation warnings on Pixel 6 or S10. I believe this is safe since we are correctly synchronized in the acquireNextImage via the presentation semaphore. The only loss is that we will finish the raster task before we know that presentation is failed.
Having said that, we can end up waiting multiple ms for the layout transition and presentation, so that doesn't seem worth it.
=> [Impeller] presentKHR from background worker.

ci/licenses_golden/excluded_files, impeller/aiks/aiks_unittests.cc, impeller/aiks/canvas.cc, impeller/aiks/paint_pass_delegate.cc, impeller/aiks/paint_pass_delegate.h, impeller/entity/BUILD.gn, impeller/entity/entity_pass.cc, impeller/entity/entity_pass.h, impeller/entity/entity_pass_delegate.cc, impeller/entity/entity_pass_delegate.h, impeller/entity/entity_unittests.cc, impeller/entity/geometry/fill_path_geometry.cc, impeller/entity/geometry/fill_path_geometry.h, impeller/entity/geometry/geometry.cc, impeller/entity/geometry/geometry.h, impeller/entity/geometry/geometry_unittests.cc
Resolves https://github.com/flutter/flutter/issues/131100
* Skip rect clips that we know won't further restrict the clip shape.
* Don't append clips to enforce subpass bounds. We currently don't collapse passes when subpass clips are added anyhow, so just a restriction to subpass collapsing in order to keep the current behavior intact.
* Small refactor to reduce confusion: Just place the subpass bounds limit into `EntityPass` itself instead of the delegate.
Built on https://github.com/flutter/engine/pull/43946 (because iOS currently fails validation without it).
Gallery home screen before/after:
=> [Impeller] Skip rect clips that do nothing.

impeller/aiks/aiks_unittests.cc, impeller/entity/contents/filters/matrix_filter_contents.cc, impeller/entity/entity_pass.cc
Follow-up/reland of https://github.com/flutter/engine/pull/43943.
Resolves https://github.com/flutter/flutter/issues/130355.
Doesn't regress https://github.com/flutter/flutter/issues/131182.
I've updated the golden to better reproduce the problem at hand; the second circle is a scaled down copy of the backdrop. If the matrix filter is handling the transform correctly, the circle is centered over the bottom-right-most edge (4:30) of the circle:
Before:
https://github.com/flutter/engine/assets/919017/d12d67bd-7e60-4389-87d3-fc4162d9b90e
After:
https://github.com/flutter/engine/assets/919017/a611a0d4-0b2d-4171-8170-b6a3781034e1
=> [Impeller] Use basis of effect transform in MatrixFilter.

display_list/testing/dl_rendering_unittests.cc, lib/web_ui/skwasm/surface.cpp, shell/platform/fuchsia/flutter/flatland_external_view_embedder.cc, shell/platform/fuchsia/flutter/gfx_external_view_embedder.cc
Relanding https://github.com/flutter/engine/pull/43902 without the copy-pasta return statements which did not seem to cause a compile issue, but caused Fuchsia tests to hang.
[breaking …
=> Reland "Remove more calls to SkCanvas::flush() and SkSurface::flush()"

shell/platform/darwin/ios/framework/Source/VsyncWaiterIosTest.mm, shell/platform/darwin/ios/framework/Source/vsync_waiter_ios.mm
Right now framerate when platform views are on screen is capped to 80 fps on iOS devices. I tried uncapping the framerate and ran the test app in https://github.com/flutter/flutter/issues/116640 on my M1 Max MBP and didn't notice any of the same slowdowns. `iOSAppOnMac` is only available on Apple Silicon Macs, so the performance baseline is really high. I think it's safe to remove the cap here.
| Category | Device | SoC | CPU | GPU |
|--|--|--|--|--|
iOS | iPhone 13 Pro | A15 | 2P+4e | 5 EU |
Mac with built-in ProMotion | MacBook Pro 2021 | M1 Pro | 6P+2e |  14 EU |
Mac with external 120Hz display | MacBook Air 2020 | M1 | 4P+4e | 7 EU | …
=> Uncap framerate for `iOSAppOnMac`

impeller/aiks/aiks_unittests.cc, impeller/entity/contents/filters/matrix_filter_contents.cc, impeller/entity/entity_pass.cc
Resolves https://github.com/flutter/flutter/issues/131305.
=> [Impeller] Only strip the translation from backdrop filter effect transforms.

impeller/entity/contents/color_source_contents.cc, impeller/entity/contents/color_source_contents.h, impeller/entity/contents/solid_color_contents.cc, impeller/entity/contents/solid_color_contents.h
Contents::ShouldRender already checks whether the stencil_coverage.has_value.
=> [Impeller] Remove duplicated code.

shell/platform/darwin/macos/framework/Source/FlutterEmbedderKeyResponder.h, shell/platform/darwin/macos/framework/Source/FlutterEmbedderKeyResponder.mm, shell/platform/darwin/macos/framework/Source/FlutterKeyboardManager.h, shell/platform/darwin/macos/framework/Source/FlutterKeyboardManager.mm, shell/platform/darwin/macos/framework/Source/FlutterKeyboardManagerTest.mm, shell/platform/darwin/macos/framework/Source/FlutterKeyboardViewDelegate.h, shell/platform/darwin/macos/framework/Source/FlutterViewController.mm
This PR updates the macOS engine in order to answer to keyboard pressed state queries from the framework (as implemented in https://github.com/flutter/flutter/pull/122885).
macOS engine implementation for https://github.com/flutter/flutter/issues/87391
Similar to:
- Linux: https://github.com/flutter/engine/pull/42346
- Android: https://github.com/flutter/engine/pull/42758
Adds 2 tests.
=> [macOS] Return keyboard pressed state

.ci.yaml, ci/builders/linux_unopt.json, ci/builders/mac_unopt.json, ci/builders/standalone/windows_unopt.json
`unopt` targets are missing from https://github.com/flutter/engine/pull/43982 …
=> Fix unopt targets

ci/licenses_golden/tool_signature, tools/licenses/lib/paths.dart
See https://github.com/flutter/engine/pull/34038
=> Ignore the NOTICE.fuchsia file in the new license script

impeller/typographer/glyph.h
While profiling Impeller I saw that we were allocating ~80MB/s of `GlyphPosition`s.  This should shave off 13MB/s by making Glyphs 20 bytes instead of 24. …
=> [Impeller] trimmed 3 bytes off of each Glyph

flow/layers/platform_view_layer.cc
These lines are appearing in framework tests but do not appear to have significant diagnostic value.
=> Hide some log lines from release builds

lib/ui/semantics.dart, lib/ui/semantics/semantics_node.h, lib/web_ui/lib/semantics.dart, lib/web_ui/test/engine/semantics/semantics_api_test.dart, shell/platform/android/io/flutter/view/AccessibilityBridge.java, shell/platform/common/accessibility_bridge.cc, shell/platform/embedder/embedder.h, shell/platform/windows/flutter_windows_view_unittests.cc, testing/dart/semantics_test.dart
This PR is to add support for the expanded/collapsed-state semantics flag to the engine. After adding another PR to Flutter, we will be able to support the expanded/collapsed state in semantics for submenu buttons.
Related to [#127617](https://github.com/flutter/flutter/issues/127617) in flutter
=> Add Expanded/Collapsed state for `SubmenuButton`

impeller/renderer/backend/vulkan/context_vk.cc, tools/gn
Context:
> @matanlurey:
> Would it make sense for `--unopt` to imply `--enable-vulkan-validation-layers` if `--enable-vulkan` is set?
> The reason I ask is because it does seem to imply `glGetError` checks, which (I could be wrong) is roughly similar?
> @chinmaygarde:
> Makes sense.
... so uh, here it is (let me know if we prefer anything different).
=> [Impeller] Set 'enable_vulkan_validation_layers' if --unopt and Vulkan is enabled.

impeller/display_list/dl_dispatcher.cc, impeller/display_list/dl_unittests.cc, impeller/geometry/matrix.h
Fixes https://github.com/flutter/flutter/issues/130613
Before this patch, the test would fail to render anything because the culling would decide it fell outside the cull rect when the transform has perspective sometimes. We should fix our Rect::TransformBounds implementation, but I can't quite seem to get it happy enough here so I'm just bailing out on culling if there is perspective instead, which is safe. This also makes the patch a bit easier/safer to cherry pick since it's a simple de-optimization when perspective is involved for the sake of fidelity, instead of a larger change that may have other side effects.
Filed https://github.com/flutter/flutter/issues/131445 to track the perspective issue.
=> [Impeller] Avoid culling when the current matrix has perspective.

tools/gn
The Vulkan validation layer headers will not build if the Android API level is 23 or lower.
Currently the engine buildroot's default Android API level is 23.  The API level must be overridden for any configuration where Vulkan validation is enabled.
=> Set the required Android API level when Vulkan validation layers are automatically enabled for android_debug_unopt_arm64 builds

impeller/renderer/backend/metal/surface_mtl.mm
More context is "See also", but this doesn't work for applications with particularly high application load.
Reverts https://github.com/flutter/engine/pull/42160
Fixes https://github.com/flutter/flutter/issues/131490
See also : https://github.com/flutter/flutter/issues/131520
=> [Impeller] revert removal of wait until scheduled.

impeller/docs/renderdoc_frame_capture.md
Fixes https://github.com/flutter/flutter/issues/131461
=> [Impeller] Update documentation on RenderDoc frame capture.

ci/licenses_golden/licenses_flutter, impeller/playground/backend/vulkan/playground_impl_vk.cc, impeller/renderer/backend/vulkan/BUILD.gn, impeller/renderer/backend/vulkan/context_vk.cc, impeller/renderer/backend/vulkan/context_vk.h, impeller/renderer/backend/vulkan/surface_context_vk.cc, impeller/renderer/backend/vulkan/surface_context_vk.h, shell/gpu/gpu_surface_vulkan_impeller.cc, shell/platform/android/android_surface_vulkan_impeller.cc, shell/platform/android/android_surface_vulkan_impeller.h
In https://github.com/flutter/engine/pull/41059 the Android context and surface were changed to share one impeller::ContextVK across all instances of AndroidSurfaceVulkanImpeller.  However, the ContextVK holds a reference to the current swapchain.  If an app uses multiple AndroidSurfaceVulkanImpeller instances (e.g. for platform views), then one surface may overwrite the ContextVK's swapchain while another surface is trying to render.
This patch allows each surface to get its own impeller::Context instance holding a swapchain tied to that surface.  The per-surface contexts will delegate most operations to the shared parent ContextVK.
=> [Impeller] Create a wrapper Impeller context for each Vulkan surface and its swapchain

impeller/README.md
The website was updated in https://github.com/flutter/website/pull/9114/files
=> [Impeller] Update guidance on how to try Impeller on macOS Desktop.

impeller/docs/metal_validation.md
Fixes https://github.com/flutter/flutter/issues/114202
=> [Impeller] Update guidance on how to run with Metal validation without Xcode.

impeller/renderer/backend/vulkan/allocator_vk.cc, impeller/renderer/backend/vulkan/allocator_vk.h
I measured the pool usage while using the wonderous app after having consolidated the pools by printing capturing the pool usage after every call of `vmaCreateBuffer`.  The max number of allocations ever seen in this pool were 1288704 B.  Each of these pools are 32 MB.  So this change removes 64MB from the baseline memory usage of a Vulkan Flutter engine.  Worse case for a swapchain of 3 would be roughly 3 * 1.2 MB which is well within the limits of the 32 MB buffer.
Using one pool also increases the likelihood that a buffer will have been more recently used which leads to better memory performance.
This is safe to do since buffers will only be placed back into the pool after they are disposed of.
```diff
--- a/impeller/renderer/backend/vulkan/allocator_vk.cc
+++ …
```
=> [Impeller] moved to one staging buffer pool

DEPS
This is expected to be good-to-go following the fix in https://github.com/flutter/engine/pull/44157
=> Manual clang roll to ebd0b8a0472b865b7eb6e1a32af97ae31d829033

ci/builders/mac_unopt.json, common/config.gni, shell/platform/darwin/ios/BUILD.gn, shell/platform/darwin/ios/framework/Source/FlutterEngine.mm, shell/platform/darwin/ios/framework/Source/FlutterEngineTest.mm, shell/platform/darwin/ios/framework/Source/FlutterEngine_Test.h, shell/platform/darwin/ios/framework/Source/FlutterPlatformPlugin.mm, shell/platform/darwin/ios/framework/Source/FlutterPlatformPluginTest.mm, shell/platform/darwin/ios/framework/Source/FlutterViewController.mm, shell/platform/darwin/ios/framework/Source/FlutterViewControllerTest.mm, tools/gn
iOS extensions forbids the usage of UIApplication.sharedApplication. This PR refactors the engine to use UISceneAPI when darwin_extension_safe flag is on. Using UISceneAPI can help avoid the usage of `UIApplication.sharedApplication` as much as possible.
This PR also added a new `_extension_safe` variant for the engine build so all the logic with the `darwin_extension_safe` flag is on can be tested separately.
This PR doesn't enable the engine to build for the extension even when darwin_extension_safe is true.
part of https://github.com/flutter/flutter/issues/124289
There are several issues related to UIApplication life cycle and I manually tested they still work with the scene API: …
=> [iOS] Add darwin_extension_safe flag and use UIScene api when building for extensions

lib/web_ui/lib/src/engine/canvaskit/image.dart, lib/web_ui/lib/src/engine/js_interop/js_typed_data.dart
Any user @staticInterop types should only subtype the dart:js_interop types JSObject and or JSAny as user @staticInterop types erase to JSObject.
In the future, the other JS types will be added as extension types, allowing users to implement them with their own extension types.
Allows https://dart-review.googlesource.com/c/sdk/+/316865/1 to be landed.
=> Remove extends JSTypedArray from JSUint8Array1

ci/licenses_golden/licenses_flutter, lib/web_ui/lib/src/engine.dart, lib/web_ui/lib/src/engine/platform_views/content_manager.dart, lib/web_ui/lib/src/engine/platform_views/slots.dart, lib/web_ui/lib/src/engine/semantics.dart, lib/web_ui/lib/src/engine/semantics/platform_view.dart, lib/web_ui/lib/src/engine/semantics/semantics.dart, lib/web_ui/test/engine/platform_views/content_manager_test.dart, lib/web_ui/test/engine/platform_views/slots_test.dart, lib/web_ui/test/engine/semantics/semantics_test.dart, lib/web_ui/test/engine/semantics/semantics_tester.dart
Add `PlatformViewRoleManager`, the primary role manager for platform views. Currently, all it does is manager the `aria-owns` attribute that determines the screen reader traversal order of the platform view w.r.t. surrounding content.
This is a partial fix for https://github.com/flutter/flutter/issues/124765. While it does not address literally using the TAB key as a means for traversing widgets, it does address traversal via screen reader shortcuts.
=> [web:a11y] add platform view role

impeller/renderer/backend/vulkan/swapchain_impl_vk.cc
Fixes https://github.com/flutter/flutter/issues/131610
Since we're not blocking on presentation, we can have multiple images pending. This is generally good, but for the backpressure from acquireNextImageKHR to be valid it needs to have a finite timeout.
Pick a somewhat arbitrary but fairly long ms duration. See also: https://github.com/flutter/flutter/issues/131698
=> [Impeller] Give a fixed timeout for acquireNextImageKHR.

shell/platform/darwin/ios/framework/Source/SemanticsObject.mm, shell/platform/darwin/ios/framework/Source/SemanticsObjectTest.mm
PlatformViewSemanticsContainer did not implement the nativeAccessibility method, leads to a nil object being returned. 
Fixes https://github.com/flutter/flutter/issues/131014
[breaking …
=> [iOS][A11Y] fix hittest with non-SemanticsObject

impeller/renderer/backend/metal/surface_mtl.mm
More context is "See also", but this doesn't work for applications with particularly high application load.
Reverts https://github.com/flutter/engine/pull/42160
Fixes https://github.com/flutter/flutter/issues/131490
See also : https://github.com/flutter/flutter/issues/131520
=> [CP][Impeller] revert removal of wait until scheduled. (#44121)

impeller/entity/contents/runtime_effect_contents.cc
The framework has switched into mat3 by default, which means the fragment program ink sparkle has replaced the default ink splash. Since this is not implemented, all of the impeller benchmarks are crashing.
=> [Impeller] no-op fragment program on Android until it works. (#43657)

flow/frame_timings.h, fml/trace_event.cc, fml/trace_event.h, runtime/dart_vm.cc, runtime/dart_vm_initializer.cc, runtime/dart_vm_initializer.h, shell/common/animator.cc, shell/common/engine.cc, shell/common/pipeline.h, shell/common/pointer_data_dispatcher.cc, shell/common/rasterizer.cc, shell/common/shell.cc, shell/common/skia_event_tracer_impl.cc, shell/common/vsync_waiter.cc, shell/platform/embedder/embedder.cc, shell/testing/tester_main.cc, testing/dart/observatory/tracing_test.dart, testing/dart/pubspec.yaml
This PR changes usages of `Dart_TimelineEvent` to `Dart_RecordTimelineEvent` as `Dart_TimelineEvent` was deprecated in https://dart-review.googlesource.com/c/sdk/+/308721.
=> Handle deprecation of Dart_TimelineEvent Embedder API

DEPS, tools/clang_tidy/lib/clang_tidy.dart
* Add timestamps to process pool status logs
* Log the remaining job names when only a few jobs are pending
See https://github.com/flutter/flutter/issues/131689
=> Improve logging in the clang-tidy script

.ci.yaml
Skip windows arm on release branches. This broke during the migration to the release builders.
=> [CP] Remove windows_arm_host_engine from release builder

shell/platform/darwin/ios/framework/Source/FlutterEngine.mm, shell/platform/darwin/ios/framework/Source/FlutterEngineTest.mm
Previously, when setting the binary messenger to the current binary messenger, we were freeing the current binary messenger before setting the new (current) binary messenger, triggering a use after free. …
=> [iOS] Fix use-after-free in setBinaryMessenger

impeller/tools/malioc_diff.py
Relative paths are required for integrating this tool as a test in engine v2.
=> [CP] Add relative path support for malioc_diff. (#41703)

impeller/aiks/aiks_unittests.cc, impeller/entity/entity_pass.cc
cherry-pick of https://github.com/flutter/engine/pull/44192
[Discord]: …
=> [CP] [Impeller] Made the clear optimization handle backdrop filters. (#44192)

ci/licenses_golden/licenses_flutter, impeller/entity/BUILD.gn, impeller/entity/contents/filters/filter_contents.cc, impeller/entity/contents/filters/filter_contents.h, impeller/entity/contents/filters/inputs/filter_contents_filter_input.cc, impeller/entity/contents/filters/inputs/filter_input.cc, impeller/entity/contents/filters/inputs/filter_input.h, impeller/entity/contents/filters/inputs/filter_input_unittests.cc, impeller/entity/contents/filters/inputs/placeholder_filter_input.cc, impeller/entity/contents/filters/inputs/placeholder_filter_input.h
Resolves https://github.com/flutter/flutter/issues/131632
This is a revival of my patch to add the necessary mechanisms for: https://github.com/flutter/flutter/issues/131632
... since it turns out we need it sooner than later for https://github.com/flutter/flutter/issues/131182.
=> [Impeller] Add placeholder filter input.

ci/licenses_golden/licenses_flutter, common/exported_symbols.sym, common/exported_symbols_mac.sym, lib/gpu/BUILD.gn, lib/gpu/gpu.cc, lib/gpu/gpu.dart, lib/gpu/gpu.h, runtime/BUILD.gn, testing/dart/BUILD.gn, testing/dart/gpu_test.dart, testing/symbols/verify_exported.dart
Part of https://github.com/flutter/flutter/issues/131346
Stubs a minimal test of the FFI utilities that `dart:ui` uses, but using public symbols exported from the engine library. If this goes well, I'll move the stuff from `dart:ui` into here and begin landing parts of the API with test coverage.
=> [Flutter GPU] Export symbols from engine, stub for testing on CI.

ci/licenses_golden/licenses_flutter, shell/platform/darwin/ios/BUILD.gn, shell/platform/darwin/ios/framework/Source/FlutterEngine.mm, shell/platform/darwin/ios/framework/Source/FlutterPlatformPlugin.mm, shell/platform/darwin/ios/framework/Source/FlutterViewController.mm, shell/platform/darwin/ios/framework/Source/FlutterViewControllerTest.mm, shell/platform/darwin/ios/framework/Source/FlutterViewController_Internal.h, shell/platform/darwin/ios/framework/Source/UIViewController+FlutterScreenAndSceneIfLoaded.h, shell/platform/darwin/ios/framework/Source/UIViewController+FlutterScreenAndSceneIfLoaded.mm, shell/platform/darwin/ios/framework/Source/UIViewController_FlutterScreenAndSceneIfLoadedTest.mm
The existing `screenIfViewLoaded` and `windowSceneIfLoaded` functions are private helpers of `FlutterViewController` class. This PR moves the logic to a category of the `UIViewController`, so it can be reused for any `UIViewController`s. 
https://github.com/flutter/engine/pull/43972#discussion_r1282214557 …
=> [ios]make the screenIfViewLoaded and windowSceneIfLoaded helpers reusable

impeller/docs/android_validation_layers.md
=> [Impeller] updated validation layers documentation

shell/gpu/gpu_surface_gl_skia.cc, shell/platform/android/android_external_texture_gl.cc, shell/platform/android/hardware_buffer_external_texture_gl.cc, shell/platform/embedder/embedder.cc, shell/platform/embedder/embedder_external_texture_gl.cc, shell/platform/embedder/tests/embedder_test_backingstore_producer.cc, testing/test_gl_surface.cc
In https://skia-review.googlesource.com/c/skia/+/701398 Skia refactored GrBackend* to not require #ifdefs. This changes
callsites in Flutter to use static functions instead of methods that were conditionally compiled on those classes.
There should be no functional change with these. As I was updating these callsites, I saw uses of the deprecated GrMipMapped enum and used the updated skgpu::Mipmapped (the former is an alias to the latter). …
=> Migrate GL calls of GrBackend*

BUILD.gn, shell/platform/darwin/BUILD.gn, shell/platform/darwin/common/BUILD.gn, shell/platform/darwin/common/framework_common.gni, shell/platform/darwin/graphics/BUILD.gn, shell/platform/darwin/ios/BUILD.gn, shell/platform/darwin/macos/BUILD.gn, testing/run_tests.py
Previously, some common Darwin framework targets existed in: 
//flutter/shell/platform/darwin/BUILD.gn
This moves all targets into:
//flutter/shell/platform/darwin/common/BUILD.gn
We also de-duplicate targets with existing targets.
* The `flutter_channels` target duplicates the existing `framework_shared` target.
* The `common` target already includes the buffer conversions translation units,
which are only used by the iOS embedder.
No test changes since there are no semantic changes, just a restructuring of build targets. …
=> [darwin] Move common targets to common/BUILD.gn

shell/platform/darwin/ios/BUILD.gn
build ios unittest target in unopt builds. 
[Discord]: …
=> Build iOS unittest target in unopt builds

shell/platform/android/platform_view_android_jni_impl.cc
=> Remove WARNINGs from JNI load path as we can't suppress them

lib/web_ui/lib/src/engine/pointer_binding.dart, lib/web_ui/lib/src/engine/semantics/semantics.dart, lib/web_ui/lib/src/engine/semantics/tappable.dart, lib/web_ui/test/common/matchers.dart, lib/web_ui/test/engine/pointer_binding_test.dart, lib/web_ui/test/engine/semantics/semantics_test.dart, lib/web_ui/test/engine/semantics/semantics_tester.dart
This should significantly improve the situation described in https://github.com/flutter/flutter/issues/130162.
When the framework merges semantics trees of multiple widgets into a single node, it can expand the tap area of one of the descendants to the size of the combined node as follows:
When a screen reader taps on the combined node, the pointer events and the click all land in the center. This produces a stalemate resulting in the user action never producing a tap/click gesture in the framework:
* The web engine, seeing `pointerdown`/`pointerup`, switches to the gesture mode ignores the `click`, believing that the framework will interpret the pointer events as one.
* The framework, seeing pointer events landing outside the checkbox, never reacts to the pointer events.
This PR mostly …
=> [web] fix clicks on merged semantic nodes

impeller/renderer/backend/vulkan/command_pool_vk.cc, impeller/renderer/backend/vulkan/command_pool_vk.h
Fixes https://github.com/flutter/flutter/issues/131522
=> [Impeller] Discard invalid command buffer handles after destroying a command pool

impeller/renderer/backend/vulkan/context_vk.cc, impeller/renderer/backend/vulkan/context_vk.h, impeller/renderer/backend/vulkan/debug_report_vk.cc, impeller/renderer/backend/vulkan/descriptor_pool_vk.cc, impeller/renderer/backend/vulkan/device_holder.h, impeller/renderer/backend/vulkan/fence_waiter_vk.cc, impeller/renderer/backend/vulkan/pipeline_cache_vk.cc, impeller/renderer/backend/vulkan/pipeline_cache_vk.h, impeller/renderer/backend/vulkan/vk.h
Many `#include`s, particularly in the `impeller/renderer/backend/vulkan/...` directory, had existing `clangd` lint violations.
The most frequent and easiest to fix appears to be https://clangd.llvm.org/guides/include-cleaner.
---
Note that I used `// IWYU pragma: keep.` in two places where `clangd` wasn't able to tell something was in use. In other cases you'll see additions because files were relying on transitive includes that are removed in this PR, but there should be 0 behavioral changes!
=> [Impeller] Run clangd tidy, opting out in 2 cases.

shell/platform/darwin/ios/BUILD.gn
Reverts flutter/engine#44301
```
Traceback (most recent call last):
File "/Volumes/Work/s/w/ir/cache/builder/src/flutter/testing/run_tests.py", line 1286, in <module>
sys.exit(main())
File "/Volumes/Work/s/w/ir/cache/builder/src/flutter/testing/run_tests.py", line 1269, in main
run_objc_tests(args.ios_variant, args.objc_filter)
File "/Volumes/Work/s/w/ir/cache/builder/src/flutter/testing/run_tests.py", line 721, in run_objc_tests
ensure_ios_tests_are_built(ios_out_dir)
File "/Volumes/Work/s/w/ir/cache/builder/src/flutter/testing/run_tests.py", line 625, in ensure_ios_tests_are_built
assert flutter_dylib_time <= ios_test_lib_time, final_message
AssertionError: /Volumes/Work/s/w/ir/cache/builder/src/out/ios_debug_sim_arm64_extension_safe/libios_test_flutter.dylib is older than …
```
=> Revert "Build iOS unittest target in unopt builds"

DEPS
This roll includes only one commit:
* fluter/buildroot@a067408d923ccf80742571bb7a71705499f5779e
=> Roll buildroot to a067408d923ccf80742571bb7a71705499f5779e

shell/platform/darwin/ios/framework/Source/SemanticsObject.mm, shell/platform/darwin/ios/framework/Source/SemanticsObjectTest.mm
Cherry-pick https://github.com/flutter/engine/pull/44014
Fixes https://github.com/flutter/flutter/issues/131885 …
=> [CP][iOS][A11Y] fix hittest with non-SemanticsObject 

impeller/README.md, impeller/docs/benchmarks.md
My main goal here was to get a more clear picture of how the Vulkan implementation is performing in relation to the OpenGLES implementation.  There is a lot of conventional wisdom about what benchmarks to look at that isn't documented anywhere.  As we come to rely on benchmarks daily this should be updated.
issue: https://github.com/flutter/flutter/issues/131784
issue: https://github.com/flutter/flutter/issues/131782 …
=> [Impeller] Added a doc page to point out important impeller benchmarks

shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.h, shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm, shell/platform/darwin/ios/framework/Source/FlutterTextInputPluginTest.mm
This PR address the movement aspect of the flutter interactive keyboard. It handles pointer movement while a scroll view widget is visible, and the interactive behavior is chosen for keyboardDismissBehavior. This is a desired behavior of the keyboard that has not yet been implemented. 
Design Document:
https://docs.google.com/document/d/1-T7_0mSkXzPaWxveeypIzzzAdyo-EEuP5V84161foL4/edit?pli=1
Issues Address:
https://github.com/flutter/flutter/issues/57609
[C++, …
=> Flutter iOS Interactive Keyboard: Take Screenshot and Handle Pointer Movement 

shell/platform/darwin/common/BUILD.gn, shell/platform/darwin/common/framework/Source/FlutterChannelsTest.m, shell/platform/darwin/common/framework/Source/FlutterNSBundleUtils.mm, shell/platform/darwin/common/framework/Source/flutter_codecs_unittest.mm, shell/platform/darwin/common/framework/Source/flutter_standard_codec_unittest.mm
The end goal is for all Objective-C code to be compiled with ARC enabled. The common framework code is already compiled with ARC enabled; this enables it for the tests as well.
This is prework before migrating FlutterBinaryMessengerRelay to the common Darwin code.
Issue: https://github.com/flutter/flutter/issues/116445 …
=> [Darwin] Enable ARC in darwin/common unit tests

ci/licenses_golden/licenses_flutter, shell/platform/darwin/common/BUILD.gn, shell/platform/darwin/common/framework/Source/FlutterBinaryMessengerRelay.h, shell/platform/darwin/common/framework/Source/FlutterBinaryMessengerRelay.mm, shell/platform/darwin/common/framework/Source/FlutterBinaryMessengerRelayTest.mm, shell/platform/darwin/common/framework/Source/FlutterTestUtils.h, shell/platform/darwin/common/framework/Source/FlutterTestUtils.mm, shell/platform/darwin/ios/BUILD.gn, shell/platform/darwin/ios/framework/Source/FlutterEngine.mm, shell/platform/darwin/ios/framework/Source/FlutterEngineTest.mm, shell/platform/darwin/ios/framework/Source/FlutterTextInputPluginTest.mm, shell/platform/darwin/ios/framework/Source/FlutterViewController.mm
Migrates FlutterBinaryMessengerRelay to
//flutter/shell/platform/darwin/common so that it can be used in a followup patch on macOS, to fix a memory leak due to a retain cycle.
Migrates the unit tests to be compatible with gtest, which is used by the darwin/common unit tests.
Issue: https://github.com/flutter/flutter/issues/116445 …
=> [Darwin] Move FlutterBinaryMessengerRelay to common

lib/web_ui/dev/felt
In the spirit of keeping the happy path's output as clean as possible, let's hide the many lines printed by `pub get` even when it's successful.
If `pub get` fails, its output will be printed on the terminal.
=> [web] Silence `pub get` when it's successful

ci/licenses_golden/licenses_flutter, lib/web_ui/lib/src/engine/profiler.dart, lib/web_ui/lib/src/engine/safe_browser_api.dart, lib/web_ui/lib/ui_web/src/ui_web.dart, lib/web_ui/lib/ui_web/src/ui_web/benchmarks.dart, lib/web_ui/test/engine/profiler_test.dart
Required by https://github.com/flutter/flutter/pull/132087
Part of https://github.com/flutter/flutter/issues/130175
Part of https://github.com/flutter/flutter/issues/126831
=> [web] Expose the benchmark callback through dart:ui_web

shell/platform/darwin/common/framework/Source/FlutterBinaryMessengerRelay.h, shell/platform/darwin/macos/framework/Source/FlutterEngine.mm, shell/platform/darwin/macos/framework/Source/FlutterEngineTest.mm
Previously, FlutterEngine.binaryMessenger returned the FlutterEngine instance itself, which meant that channels/plugins could hold a strong reference to the engine and thus cause a retain cycle, preventing the engine from being deallocated.
We introduce FlutterBinaryMessengerRelay, which implements the FlutterBinaryMessenger protocol, by delegating back to the engine, to which it holds a weak reference, thus avoiding the retain cycle.
This also changes the FlutterBinaryMessengerRelay.parent property from an assign property to a weak property since that code is compiled with ARC enabled as of https://github.com/flutter/engine/pull/44395.
This patch also rearranges the headers to comply with our style guide: related headers for this file, C headers, C++ headers, other Flutter headers, in …
=> [macOS] Fix engine/binaryMessenger retain cycle

impeller/entity/contents/checkerboard_contents.cc, impeller/entity/contents/clip_contents.cc, impeller/entity/contents/filters/blend_filter_contents.cc, impeller/entity/contents/filters/gaussian_blur_filter_contents.cc, impeller/entity/contents/filters/morphology_filter_contents.cc, impeller/entity/contents/framebuffer_blend_contents.cc, impeller/entity/contents/text_contents.cc, impeller/renderer/render_pass.cc, impeller/renderer/render_pass.h, impeller/renderer/renderer_unittests.cc
Each Command is 440 B so copying them when adding them to the RenderPass adds up.  This change represents a 36% speedup in `TextContents::Render` when scrolling around on the main screen of the of the Flutter Gallery.
issue: https://github.com/flutter/flutter/issues/131787
[CLA]: …
=> [Impeller] started std::moving `Command`s instead of copying

impeller/aiks/aiks_unittests.cc, impeller/aiks/color_source.cc, impeller/entity/contents/conical_gradient_contents.cc, impeller/entity/contents/conical_gradient_contents.h, impeller/entity/contents/radial_gradient_contents.cc, impeller/entity/contents/radial_gradient_contents.h, impeller/entity/contents/sweep_gradient_contents.cc, impeller/entity/contents/sweep_gradient_contents.h, impeller/entity/shaders/conical_gradient_fill.frag, impeller/entity/shaders/conical_gradient_ssbo_fill.frag, impeller/entity/shaders/radial_gradient_ssbo_fill.frag, impeller/entity/shaders/sweep_gradient_ssbo_fill.frag, impeller/tools/malioc.json
Partial work towards https://github.com/flutter/flutter/issues/131450 similar to https://github.com/flutter/engine/pull/44181.
---
Run the Playground locally:
```bash
$ENGINE/out/host_debug_unopt/impeller_unittests \
--enable_playground \
--gtest_filter="*CanRender*GradientWithDithering*"
```
=> [Impeller] Add gradient dithering for Radial/Sweep/Conical gradients

impeller/display_list/dl_dispatcher.cc
Closes https://github.com/flutter/flutter/issues/131450 and https://github.com/flutter/flutter/issues/118073.
Example from https://github.com/flutter/flutter/issues/118073:
```diff
void main() {
+ Paint.enableDithering = true;
runApp(const MyApp());
}
const MyApp({super.key});
@override
return MaterialApp(
title: 'Flutter Demo',
theme: ThemeData(
primarySwatch: Colors.blue,
),
home: const MyHomePage(title: 'Flutter Demo Home Page'),
);
}
}
class MyHomePage extends StatefulWidget {
const MyHomePage({super.key, required this.title});
final String title;
@override
State<MyHomePage> createState() => _MyHomePageState();
}
class _MyHomePageState extends State<MyHomePage> {
int …
```
=> [Impeller] Plumb Paint.enableDithering to backend

shell/platform/windows/flutter_windows_engine.cc, shell/platform/windows/keyboard_handler_base.h, shell/platform/windows/keyboard_key_channel_handler.cc, shell/platform/windows/keyboard_key_channel_handler.h, shell/platform/windows/keyboard_key_embedder_handler.cc, shell/platform/windows/keyboard_key_embedder_handler.h, shell/platform/windows/keyboard_key_handler.cc, shell/platform/windows/keyboard_key_handler.h, shell/platform/windows/keyboard_key_handler_unittests.cc
This PR updates the Windows engine in order to answer to keyboard pressed state queries from the framework (as implemented in https://github.com/flutter/flutter/pull/122885).
Windows engine implementation for https://github.com/flutter/flutter/issues/87391.
Similar to:
- Linux: https://github.com/flutter/engine/pull/42346
- Android: https://github.com/flutter/engine/pull/42758
- macOS: https://github.com/flutter/engine/pull/42878
Adds 2 tests.
=> [Windows] Return keyboard pressed state

shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm, shell/platform/darwin/ios/framework/Source/FlutterTextInputPluginTest.mm
This PR addresses an issue with the animation of the keyboard. In iOS 16.0 a delay was included in UIView becomeFirstResponder where the areAnimationsEnabled boolean is no longer immediately read. In response to this issue a delay is added that allows for the animation to be properly disabled. 
Design Document:
https://docs.google.com/document/d/1-T7_0mSkXzPaWxveeypIzzzAdyo-EEuP5V84161foL4/edit?pli=1
Issues Address:
https://github.com/flutter/flutter/issues/57609 …
=> Flutter iOS Interactive Keyboard: Fixing Animation Issue

lib/web_ui/lib/src/engine/canvaskit/native_memory.dart
JSFunction's should only accept and return JS types.
Allows landing of external restrictions here: https://dart-review.googlesource.com/c/sdk/+/316867/9
=> Make toJS'd function use JS types

lib/ui/text.dart, lib/web_ui/lib/text.dart, lib/web_ui/test/canvaskit/text_test.dart, lib/web_ui/test/html/text/canvas_paragraph_test.dart, testing/dart/paragraph_test.dart
This depends on https://github.com/flutter/flutter/pull/132094 and customer_testing migration.
I'll announce this change and add a g3 fix after this lands. …
=> Disable text rounding hack by default

ci/licenses_golden/licenses_flutter, impeller/compiler/BUILD.gn, impeller/compiler/compiler.cc, impeller/compiler/constants.cc, impeller/compiler/constants.h, impeller/compiler/reflector.cc, impeller/compiler/types.h, impeller/compiler/utilities.cc, impeller/compiler/utilities.h, impeller/core/formats.h, impeller/core/texture.cc, impeller/entity/BUILD.gn, impeller/entity/contents/content_context.h, impeller/entity/contents/texture_contents.cc, impeller/entity/shaders/texture_fill_external.frag, impeller/playground/BUILD.gn, impeller/renderer/backend/gles/formats_gles.h, impeller/renderer/backend/gles/texture_gles.cc, impeller/renderer/backend/metal/formats_mtl.h, impeller/renderer/backend/vulkan/formats_vk.h, impeller/tools/malioc.json
Allows for sampling from external textures in the OpenGLES backend. DrawImageRect should Just Work if external textures are wrapped with the new `kTextureExternalOES` type.
=> [Impeller] External OpenGLES texture sampling.

impeller/fixtures/dart_tests.dart, impeller/renderer/BUILD.gn, impeller/renderer/renderer_dart_unittests.cc, lib/gpu/context.cc, lib/gpu/context.h
Adds a way to inject a context override, which allows us to test the API in the Dart playground without spinning up an Engine/Shell.
=> [Impeller] Flutter GPU: Add context override.

shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm, shell/platform/darwin/ios/framework/Source/FlutterTextInputPluginTest.mm
This PR addresses an issue with the behavior of the keyboard. Originally the behavior of the keyboard was to see if the pointer was above or below the middle of the keyboards full size and then animate appropriately. However we found that the behavior is instead based on velocity. This PR adjust the code to match this behavior.
Design Document:
https://docs.google.com/document/d/1-T7_0mSkXzPaWxveeypIzzzAdyo-EEuP5V84161foL4/edit?pli=1
Issues Address:
https://github.com/flutter/flutter/issues/57609 …
=> Flutter iOS Interactive Keyboard: Fixing Behavior Issue 

shell/platform/android/io/flutter/view/AccessibilityBridge.java, shell/platform/android/test/io/flutter/view/AccessibilityBridgeTest.java
The previous pr was reverted due to test failures. The failure was due to API not supported in order android version. The fix is in the second commit. …
=> Reland "Android a11y bridge sets importantness"

shell/platform/android/io/flutter/embedding/android/AndroidTouchProcessor.java, shell/platform/android/test/io/flutter/embedding/android/AndroidTouchProcessorTest.java
Fix issue 129765 and Add test case, see  issue
Fixes https://github.com/flutter/flutter/issues/129765
- [✓] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [✓] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [✓] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [✓] I listed at least one issue that this PR fixes in the description above.
- [✓] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on writing and running engine tests.
- [✓] I updated/added relevant documentation (doc comments with `///`).
- [✓] I signed the [CLA].
- [ ✓] All existing and new tests are passing.
If …
=> Fix unexpected pointer change issue and Add test case

shell/common/vsync_waiter.h
Point users in the direction of VsyncWaiterAndroid, VsyncWaiterEmbedder.
No new tests since this patch introduces no semantic changes. …
=> [shell] Add references to VsyncWaiter docs

ci/licenses_golden/licenses_flutter, shell/platform/embedder/BUILD.gn, shell/platform/embedder/embedder.cc, shell/platform/embedder/embedder_semantics_update.cc, shell/platform/embedder/embedder_semantics_update.h, shell/platform/embedder/tests/embedder_a11y_unittests.cc
This refactors how engine semantic updates are mapped to embedder semantic updates. There are no behavioral changes.
Part of https://github.com/flutter/flutter/issues/119970, https://github.com/flutter/flutter/issues/98948
Next PR: https://github.com/flutter/engine/pull/44616
For https://github.com/flutter/flutter/issues/119970, we will need to update the embedder API to add string attributes to semantic nodes' text values. There are multiple kinds of string attributes, and each text value can have multiple string attributes. This requires gnarly mapping code that's best kept out of `embedder.cc`. …
=> [Embedder] Refactor how semantic updates are mapped

impeller/docs/benchmarks.md
fixes: https://github.com/flutter/flutter/issues/131784
[Discord]: …
=> [Impeller] Added benchmark for advanced blend.

shell/platform/darwin/common/framework/Source/FlutterBinaryMessengerRelay.mm, shell/platform/darwin/macos/framework/Headers/FlutterAppDelegate.h, shell/platform/darwin/macos/framework/Headers/FlutterAppLifecycleDelegate.h, shell/platform/darwin/macos/framework/Headers/FlutterPluginMacOS.h, shell/platform/darwin/macos/framework/Headers/FlutterPluginRegistrarMacOS.h, shell/platform/darwin/macos/framework/Source/FlutterEngine.mm, shell/platform/darwin/macos/framework/Source/FlutterEngineTest.mm
Adds `addApplicationDelegate:` to the macOS plugin registrar, following the corresponding iOS method, and wires it up to the existing app delegation forwarding that was recently added for use at the application level. (The actual delegate is non-trivially different between iOS and macOS, but that's not resolveable without a complex migration on the iOS side, so the APIs currently diverge after the level of the `addApplicationDelegate:` method itself.)
This doesn't add any new methods to the delegation; those will be added in a follow-up PR.
Also fixes a retain cycle in the termination handler that prevented the new test from working.
Most of https://github.com/flutter/flutter/issues/41471 …
=> Allow macOS plugins to register as app delegates

lib/ui/text.dart, lib/web_ui/lib/text.dart, lib/web_ui/test/canvaskit/text_test.dart, lib/web_ui/test/html/text/canvas_paragraph_test.dart, testing/dart/paragraph_test.dart
=> allow `ParagraphBuilder.shouldDisableRoundingHack` to actually be set to false in tests

shell/platform/fuchsia/dart-pkg/fuchsia/BUILD.gn, shell/platform/fuchsia/dart-pkg/fuchsia/sdk_ext/fuchsia.cc, shell/platform/fuchsia/dart-pkg/fuchsia/sdk_ext/fuchsia.h, shell/platform/fuchsia/dart_runner/builtin_libraries.cc, shell/platform/fuchsia/dart_runner/builtin_libraries.h, shell/platform/fuchsia/dart_runner/dart_component_controller.cc, shell/platform/fuchsia/dart_runner/dart_component_controller.h, shell/platform/fuchsia/dart_runner/dart_runner.h, shell/platform/fuchsia/dart_runner/dart_test_component_controller.cc, shell/platform/fuchsia/dart_runner/dart_test_component_controller.h, shell/platform/fuchsia/dart_runner/service_isolate.cc, shell/platform/fuchsia/flutter/BUILD.gn, shell/platform/fuchsia/flutter/accessibility_bridge.h, shell/platform/fuchsia/flutter/component_v2.cc, shell/platform/fuchsia/flutter/component_v2.h, shell/platform/fuchsia/flutter/engine.cc, shell/platform/fuchsia/flutter/engine.h, shell/platform/fuchsia/flutter/focus_delegate.h, shell/platform/fuchsia/flutter/isolate_configurator.cc, shell/platform/fuchsia/flutter/isolate_configurator.h, shell/platform/fuchsia/flutter/platform_view.h, shell/platform/fuchsia/flutter/runner.cc, shell/platform/fuchsia/flutter/runner.h, shell/platform/fuchsia/flutter/tests/integration/mouse-input/mouse-input-test.cc, shell/platform/fuchsia/flutter/tests/integration/text-input/text-input-test.cc
The fuchsia.sys FIDL library, used to implement v1 components, is deprecated in the Fuchsia platform and is being removed.
Flutter now implements Components v2 but still imports the old library.
Bug: https://fxbug.dev/109013 …
=> Remove dependencies on fuchsia.sys.* FIDL protocols

testing/run_tests.py
Reverts flutter/engine#41720
Fixes https://github.com/flutter/flutter/issues/131899
=> Revert "Make run_tests.py assert that the ios test dylib is at least as new as libFlutter.dylib"

shell/platform/embedder/embedder_semantics_update.h
Without the flutter namespace, it breaks Google's build of the engine.
=> Update embedder_semantics_update.h imports to include flutter namespace

ci/licenses_golden/licenses_flutter, shell/platform/darwin/macos/BUILD.gn, shell/platform/darwin/macos/framework/Headers/FlutterAppDelegate.h, shell/platform/darwin/macos/framework/Headers/FlutterAppLifecycleDelegate.h, shell/platform/darwin/macos/framework/Source/FlutterAppDelegate.mm, shell/platform/darwin/macos/framework/Source/FlutterAppDelegateTest.mm, shell/platform/darwin/macos/framework/Source/FlutterAppLifecycleDelegate.mm, shell/platform/darwin/macos/framework/Source/FlutterAppLifecycleDelegate_Internal.h, shell/platform/darwin/macos/framework/Source/FlutterEngine.mm
Wires `application:openURLs:` into the exisiting delegation system, allowing plugins to handle URL callbacks (as on iOS).
Since there is no notification-based version of this delegate method, this adds it directly to the app delegate, restructring the helper class slightly to allow internal sharing of the delegate list.
Fixes https://github.com/flutter/flutter/issues/41471 …
=> Add application:openURLs: forwarding on macOS

AUTHORS, lib/web_ui/lib/src/engine/text_editing/composition_aware_mixin.dart, lib/web_ui/test/engine/composition_test.dart
It fixes an issue in `CompositionAwareMixin` causing wrong deltas being computed and reported to input clients resulting in wrong state when compositing text in rich text editors like [Fleather](https://github.com/fleather-editor/fleather) and possibly others.
Reported deltas on Mac:
```console
TextEditingDeltaInsertion: start: 0, end: 0, data: k
TextEditingDeltaInsertion: start: 1, end: 0, data: y
TextEditingDeltaReplacement: start: 0, end: 2, data: きょ
TextEditingDeltaInsertion: start: 2, end: 0, data: う
TextEditingDeltaInsertion: start: 3, end: 0, data: h
TextEditingDeltaReplacement: start: 0, end: 4, data: きょうは
TextEditingDeltaReplacement: start: 0, end: 4, data: 今日は
```
Reported deltas on Web (Before):
```console
TextEditingDeltaInsertion: start: 0, end: 0, data: k …
```
=> Update CompositionAwareMixin to correctly compute composingBase in Web engine

shell/platform/fuchsia/flutter/vulkan_surface.cc, vulkan/vulkan_swapchain.cc
Sample count is part of GrVkImageInfo (and was already being set in both places).
=> Stop using deprecated GrBackendRenderTarget constructor

lib/web_ui/test/engine/composition_test.dart
Adds missing tests for `CompositionAwareMixin`. Check https://github.com/flutter/engine/pull/44139#discussion_r1288733128 and https://github.com/flutter/engine/pull/44139#discussion_r1288009016 …
=> Add more tests for CompositionAwareMixin

.ci.yaml
Related https://github.com/flutter/flutter/issues/132605
=> Adds runIf to linux_clang_tidy

shell/platform/android/io/flutter/plugin/platform/PlatformViewsController.java
This reverts commit 12cafaeb9e3113149e5d9fdfd136ee7cca9e91b2.
The https://github.com/flutter/flutter/tree/master/dev/integration_tests/abstract_method_smoke_test test was not rendering the platform view with that change.
=> Revert "Conditionally enable HardwareBuffer backed platform views (#44744)"

tools/clang_tidy/lib/clang_tidy.dart
Required to actually see the results of the profile :)
=> Passthrough stderr results of clang_tidy when --enable-check-profile.

shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm, shell/platform/darwin/ios/framework/Source/FlutterTextInputPluginTest.mm
Fix native auto-correction highlight region on top left corner. 
This PR uses the system auto-correction highlight on iOS 17, which was disabled by https://github.com/flutter/engine/pull/44354
Fixes https://github.com/flutter/flutter/issues/131622
Fixes https://github.com/flutter/flutter/issues/131695
Fixes https://github.com/flutter/flutter/issues/130818 …
=> [ios][ios17]fix auto correction highlight on top left corner

.ci.yaml, ci/builders/linux_clang_tidy_presubmit.json, ci/builders/mac_clang_tidy_presubmit.json
This is the first in a sequence of PRs which will lint only changed files on presubmit. The process is the following:
1. Add new `bringup: true` builders that lint only changed files. `bringup: true` builders don't run in presubmit, and since after landing this no files will be detected as changed, these builders will not do anything yet.
1. Remove `bringup: true`. This will allow the new builders to run in presubmit.
1. Ask the team to monitor the new checks on PRs to make sure they are doing the right thing.
1. When we're reasonably sure that the checks are doing the right thing, add `presubmit: false` to `mac_clang_tidy` and `linux_clang_tidy` so that we no longer needlessly lint all files in presubmit.
Related https://github.com/flutter/flutter/issues/105068
=> Adds new builders for partial clang-tidy checks.

impeller/entity/contents/content_context.cc, impeller/entity/contents/scene_contents.cc, impeller/entity/entity_pass.cc, impeller/entity/render_target_cache.cc
I haven't investigated if there are more occurrences or if it's worth enforcing turning the check on generally.
(They were flagged on the Google roll, ironically)
---
[`readability-redundant-smartptr-get`](https://clang.llvm.org/extra/clang-tidy/checks/readability/redundant-smartptr-get.html)
> Find and remove redundant calls to smart pointer’s `.get()` method
[`performance-for-range-copy`](https://clang.llvm.org/extra/clang-tidy/checks/performance/for-range-copy.html)
> Finds C++11 for ranges where the loop variable is copied in each iteration but it would suffice to obtain it by reference.
=> Implement 2 suggested Clang Tidy fixes we don't look for yet.

shell/platform/darwin/ios/ios_surface_metal_impeller.mm
Testing the potential fix for iOS scheduling issues.
=> [Impeller] unconditionally present with transaction.

shell/platform/android/io/flutter/plugin/common/BasicMessageChannel.java, shell/platform/android/io/flutter/plugin/common/MethodChannel.java, shell/platform/android/test/io/flutter/plugin/common/MethodChannelTest.java
This PR updates the Android engine in order to provide a more efficient implementation for `BasicMessageChannel.resizeChannelBuffer` (helper to call the `resize` control command).
It also adds a new helper called`BasicMessageChannel.allowChannelBufferOverflow` to call the `overflow` control command.
Fixes https://github.com/flutter/flutter/issues/132048
Android implementation for https://github.com/flutter/flutter/issues/132386
Adds 2 tests.
=> [Android] Expose channel buffer resize and overflow calls

flow/skia_gpu_object.h, flow/skia_gpu_object_unittests.cc
See https://github.com/flutter/flutter/issues/131524
=> Flush pending graphics commands when the unref queue is drained on the IO thread

tools/font-subset/main.cc, tools/font-subset/test.py
This is the engine side change to fix https://github.com/flutter/flutter/issues/132711. There will be a subsequent framework change to express the space character as an "optional" character.
=> Allow optional codepoints to be expressed to the font subset generator.

shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm, shell/platform/darwin/ios/framework/Source/FlutterTextInputPluginTest.mm
CP for https://github.com/flutter/engine/pull/44779
Tested the stable branch with the fix on iPhone and iPad, with hardware and software keyboards, and with and without IME languages, iOS 16 and iOS 17
Fixes https://github.com/flutter/flutter/issues/131622
Fixes https://github.com/flutter/flutter/issues/131695
Fixes https://github.com/flutter/flutter/issues/130818 …
=> [cp][ios][ios17]fix auto correction highlight on top left corner on iOS 17 (again)

lib/ui/semantics/string_attribute.h, shell/platform/embedder/embedder.h, shell/platform/embedder/embedder_semantics_update.cc, shell/platform/embedder/embedder_semantics_update.h, shell/platform/embedder/fixtures/main.dart, shell/platform/embedder/tests/embedder_a11y_unittests.cc
Flutter's `SemanticNode`s use [`StringAttribute`](https://api.flutter.dev/flutter/dart-ui/StringAttribute-class.html)s to provide additional information on text values for assistive technologies. This exposes the string attributes on the embedder API so that embedders can apply string attributes to their semantics trees.
Addresses https://github.com/flutter/flutter/issues/119970
Part of https://github.com/flutter/flutter/issues/98948
Previous pull request: https://github.com/flutter/engine/pull/44553 …
=> [Embedder API] Add semantic string attributes

impeller/aiks/aiks_unittests.cc, impeller/aiks/canvas.cc, impeller/entity/entity_pass.cc, impeller/entity/entity_pass.h
Solves two problems:
1. Fix the debug crash by restoring the clip after the `EntityPass` merge. I initially surrounded the merge with a `Save` and `Restore`, which was a mistake and is a no-op in this situation. This should have no excess impact on performance, since we ignore clips in `EntityPass` when we detect that they won't do anything.
2. Picture subpasses weren't getting their stencil depth adjusted during the merge, which can result in subpass entities potentially receiving a clip depth that's too high.
Before:
```
[ RUN      ] Play/AiksTest.DrawPictureClipped/Metal
2023-08-17 19:23:34.204 impeller_unittests[83313:21896481] Metal API Validation Enabled
2023-08-17 19:23:34.204 impeller_unittests[83313:21896481] Metal GPU Validation Enabled …
```
=> [Impeller] Fix clip management for DrawPicture.

impeller/renderer/backend/metal/command_buffer_mtl.mm
Adding back the waitUntilScheduled introduced a regression with this sync switch behavior. Because we block on all previous cmd buffer submission, if the sync switch fires partially through the raster thread workload, then some of our cmd buffers won't be submitted and waitUntilScheduled won't terminate.
But since we added back the waitUntilScheduled, we don't actually need these guards, as this ensures that the raster thread doesn't finish until all worker threads have finished.
=> [Impeller] Remove sync switch

.ci.yaml, ci/builders/mac_clang_tidy_presubmit.json
Instead, this PR runs clang_tidy only on files that have been changed.
Related https://github.com/flutter/flutter/issues/105068
=> Don't run clang_tidy --lint-all in presubmit

ci/builders/mac_android_aot_engine.json, ci/builders/mac_host_engine.json, ci/builders/mac_ios_engine.json, ci/builders/mac_unopt.json
Running builds and tests on x64 machines is causing long queue times even when there is plenty of arm64 machines. This PR is removing most of the cpu pinned dimensions and it is separating some of the test to global tests to allow to select x64 machines only for the tests part.
=> Remove explicit mac cpu dimensions

testing/test_vulkan_surface.cc
IWYU fix to be able to use GrVkImageInfo. An incoming Skia change will otherwise fail to compile here.
=> Include GrVkTypes where necessary

ci/builders/mac_unopt.json
The test is failing when running on a x64 machine and we are pinning this test to use arm64.
Bug: https://github.com/flutter/flutter/issues/132993 …
=> Use arm64 machines for ios_debug_sim_arm64 test.

impeller/renderer/backend/vulkan/command_pool_vk.cc, impeller/renderer/backend/vulkan/command_pool_vk.h
Recycles command buffers instead of deleting them when they are done being used.
@jonahwilliams profiled the Gallery on the Pixel 7 pro and saw that sometimes `RenderPassVK::OnEncodeCommands` takes a long time in https://github.com/flutter/flutter/issues/132690.  After adding adding more tracing it was found that the culprit was deleting the CommandBuffers on the raster thread.  This PR removes the deletion of the CommandBuffers and instead resets and recycles them.
> where GARBO2 is
> ```c++
> void CommandPoolVK::GarbageCollectBuffersIfAble() {
>   TRACE_EVENT0("impeller", "CommandPoolVK::GARBO2");
>    if (std::this_thread::get_id() != owner_id_) {    
>      return;  
>    }
>    buffers_to_collect_.clear();
> }
> ```
This approach matches the guidances from ["Vulkan Best Practice for …
=> [Impeller] Added recycled command buffers.

impeller/tools/impeller.gni
In some build variations, `is_mac` or `is_linux` is true, but `target_os == "fuchsia"`.
We should explicitly disable Impeller in those variants.
Fixes https://github.com/flutter/flutter/issues/132793
=> [Impeller] Disable Impeller on Fuchsia

shell/platform/linux/BUILD.gn, shell/platform/linux/fl_binary_messenger.cc, shell/platform/linux/fl_binary_messenger_test.cc, shell/platform/linux/fl_keyboard_manager_test.cc, shell/platform/linux/public/flutter_linux/fl_binary_messenger.h, shell/platform/linux/testing/mock_binary_messenger.cc, shell/platform/linux/testing/mock_binary_messenger.h
This PR adds two helper functions to invoke the 'resize' and 'overflow' commands exposed by the control channel.
See:
https://github.com/flutter/engine/blob/93e8901490e78c7ba7e319cce4470d9c6478c6dc/lib/ui/channel_buffers.dart#L302-L309
Linux implementation for https://github.com/flutter/flutter/issues/132386
Adds two tests.
=> [Linux] Expose channel buffers 'resize' and 'overflow' control commands

shell/platform/embedder/tests/embedder_test_backingstore_producer.cc
IWYU fix for an incoming Skia change. This header is needed for GrVkImageInfo.
=> Add missing GrVkTypes include

shell/platform/android/surface_texture_external_texture.cc
The simpler version I committed last week doesn't work correctly when the texture has been transformed. This CL restores the old painting code that properly handles this case.
Fixes internal b/296916021
=> Restore old SurfaceTextureExternal drawing code

ci/licenses_golden/licenses_flutter, impeller/fixtures/dart_tests.dart, impeller/renderer/renderer_dart_unittests.cc, lib/gpu/BUILD.gn, lib/gpu/context.cc, lib/gpu/context.h, lib/gpu/host_buffer.cc, lib/gpu/host_buffer.h, lib/gpu/lib/gpu.dart, lib/gpu/lib/src/buffer.dart, lib/gpu/lib/src/context.dart
Resolves https://github.com/flutter/flutter/issues/132516.
Add `impeller::HostBuffer` wrapper to Flutter GPU.
* Allows for lazy batch uploads of sparse host data to the GPU.
* Handles platform alignment requirements.
* API returns buffer view handles that will be fed to commands.
=> [Impeller] Flutter GPU: Add HostBuffer.

impeller/core/resource_binder.h, impeller/renderer/backend/gles/buffer_bindings_gles.cc, impeller/renderer/backend/metal/compute_pass_mtl.mm, impeller/renderer/backend/metal/render_pass_mtl.mm, impeller/renderer/backend/vulkan/compute_pass_vk.cc, impeller/renderer/backend/vulkan/render_pass_vk.cc, impeller/renderer/command.cc, impeller/renderer/command.h, impeller/renderer/compute_command.cc, impeller/renderer/compute_command.h
Simplify command encoding and reduce binding size by placing all texture/sampler data in a single map instead of 3. We don't currently (nor do we plan to) support separate textures and samplers.
The vulkan backend is particularly bad, because there are 3 map lookups to pull all of the texture and sampler data out of the bindings.
Also see [go/impeller-vulkan-cmd-recording-performance](http://goto.google.com/impeller-vulkan-cmd-recording-performance)
=> [impeller] combine sampler and texture maps.

shell/platform/android/surface_texture_external_texture.cc
[CP]
The simpler version I committed last week doesn't work correctly when the texture has been transformed. This CL restores the old painting code that properly handles this case.
Fixes internal b/296916021
=> [CP] Restore old SurfaceTextureExternal drawing code (#44979)

lib/ui/text.dart, lib/web_ui/lib/text.dart, testing/dart/text_test.dart
This should aid with implementing the framework side of https://github.com/flutter/flutter/issues/105120.
This should also address https://github.com/flutter/flutter/issues/28543.
This is a reland of https://github.com/flutter/engine/pull/43750 with two changes, one to fix a typo mentioned in https://github.com/flutter/engine/pull/43750#issuecomment-1689299114, and one to fix the analysis error found when rolling this to the framework (https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20analyze/62845/overview). The latter change is temporary and can be relaxed when FontVariations is reexported from dart:ui. I plan to do that when fixing https://github.com/flutter/flutter/issues/105120.
=> FontVariation.lerp, custom FontVariation constructors, and more documentation

testing/dart/image_filter_test.dart
The expected color values appear to match the output of Skia's raster backend's blur. Historically, that doesn't support any tile mode other than decal, so while the `makeBlur()` function defaulted to clamp tiling, the output was decal and thus showed the blur fading to transparent.
The test draws a 1x1 green rectangle in the center of a 3x3 image. Clamp tiling would actually cause the output of the blur to just copy the central green color to the remaining 8 pixels. This is the output of Skia's GPU blur. I am working to land changes in Skia that make the raster backend handle all tile modes, which then has it match the existing GPU blur's behavior of a constant output for clamp tiling in this test (so it then fails).
Decal tiling appears to be more useful for this test case anyways …
=> Use decal TileMode in blur image_filter_test.dart

shell/platform/android/test/io/flutter/embedding/android/FlutterActivityAndFragmentDelegateTest.java, shell/platform/android/test/io/flutter/embedding/android/FlutterAndroidComponentTest.java, shell/platform/android/test/io/flutter/embedding/android/FlutterFragmentTest.java, shell/platform/android/test/io/flutter/embedding/android/KeyboardManagerTest.java, shell/platform/android/test/io/flutter/embedding/android/SplashShadowResources.java, shell/platform/android/test/io/flutter/embedding/engine/FlutterEngineGroupCacheTest.java, shell/platform/android/test/io/flutter/embedding/engine/deferredcomponents/PlayStoreDeferredComponentManagerTest.java, shell/platform/android/test/io/flutter/embedding/engine/loader/ApplicationInfoLoaderTest.java, shell/platform/android/test/io/flutter/embedding/engine/plugins/shim/ShimPluginRegistryTest.java, shell/platform/android/test/io/flutter/embedding/engine/systemchannels/KeyboardChannelTest.java, shell/platform/android/test/io/flutter/embedding/engine/systemchannels/SettingsChannelTest.java, shell/platform/android/test/io/flutter/plugin/editing/InputConnectionAdaptorTest.java, shell/platform/android/test/io/flutter/plugin/editing/SpellCheckPluginTest.java, shell/platform/android/test/io/flutter/plugin/editing/TextInputPluginTest.java, shell/platform/android/test/io/flutter/plugin/mouse/MouseCursorPluginTest.java, shell/platform/android/test/io/flutter/plugin/platform/PlatformPluginTest.java, shell/platform/android/test/io/flutter/plugin/platform/PlatformViewsControllerTest.java, shell/platform/android/test/io/flutter/plugin/platform/SingleViewPresentationTest.java, shell/platform/android/test/io/flutter/view/AccessibilityBridgeTest.java, shell/platform/android/test_runner/build.gradle
Set gradle to treat warnings as errors and suppress or fix all warnings in engine android tests. 
Fixes flutter/flutter#133070
After doing this work I was disappointed to realized that the only lint turned on was deprecration but this is still a step in the right direction. 
- Remove usages of deprecated junit.framework and replace with org.junit in KeyboardManagerTest, PlatformViewsControllerTest and SinglePresentationViewTest
- Annotate deprecated usages of Registrar
- Suppress warnings for getSystemWindowInsets and ensure roboletric config consistant with targetApi lint annotation, bump itDescribesTextFieldsWithTextAndHint to 28 because test actually fails on api 26
- Suppress warnings for DartExecutor.send
- Suppress warnings for ClipboardManager.set/hasText
- Suppress warnings for …
=> Eliminate android test log spam

impeller/typographer/backends/stb/text_frame_stb.cc
Not sure why we didn't catch this on presubmits. I think there was a merge order problem.
=> [Impeller] Dat rvalue reference (fix engine head)

lib/ui/text.dart, lib/web_ui/lib/text.dart, testing/dart/text_test.dart
Reverts flutter/engine#44996
Analysis failures on rolling to the framework https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20analyze/62884/overview
=> Revert "FontVariation.lerp, custom FontVariation constructors, and more documentation"

DEPS, ci/licenses_golden/licenses_flutter, shell/platform/darwin/common/BUILD.gn, shell/platform/darwin/common/availability_version_check.cc, shell/platform/darwin/macos/framework/Source/FlutterAppDelegateTest.mm
In the change here https://github.com/llvm/llvm-project/commit/b653a2823fe4b4c9c6d85cfe119f31d8e70c2fa0, an intentional ABI breaking change was introduced to the clang runtime library for macOS and iOS. That change caused a symbol requiring dynamic linkage to be exposed that triggers iOS App Store checks for usage of private API.
This PR resolves that issue by rolling clang forward and introducing a definition of `_availability_version_check`. The declaration with weak linkage in the clang runtime library [here](https://github.com/llvm/llvm-project/blob/b653a2823fe4b4c9c6d85cfe119f31d8e70c2fa0/compiler-rt/lib/builtins/os_version_check.c#L89) will then be resolved against the definition introduced in this PR. Since the declaration in the clang runtime library will now be resolved by static …
=> Roll clang with fix for ABI change

tools/clang_tidy/test/clang_tidy_test.dart
This can take a lot of time or be overly dependent on configuration details of the local git repository.
=> Remove a clang-tidy test that launches a full run of clang-tidy

ci/licenses_golden/licenses_flutter, impeller/BUILD.gn, impeller/aiks/BUILD.gn, impeller/aiks/aiks_playground.cc, impeller/aiks/aiks_playground.h, impeller/aiks/aiks_playground_inspector.cc, impeller/aiks/aiks_playground_inspector.h, impeller/aiks/aiks_unittests.cc, impeller/core/BUILD.gn, impeller/core/capture.cc, impeller/core/capture.h, impeller/entity/contents/solid_color_contents.cc, impeller/entity/contents/texture_contents.cc, impeller/entity/entity.cc, impeller/entity/entity.h, impeller/entity/entity_pass.cc, impeller/entity/entity_pass.h, impeller/golden_tests/golden_playground_test.h, impeller/golden_tests/golden_playground_test_mac.cc, impeller/golden_tests/golden_playground_test_stub.cc, impeller/renderer/context.h
Weekend project! Press `C` to capture in the Aiks playground.
Decided to finally give this a go and attempt to relieve some of the print debugging/mindfuck around investigation of coverage-related issues lately. :)
Captures:
* Capture documents from anywhere in Impeller.
* Easily implement inspectors for those documents.
* Replay documents with live editing.
* No overhead when capturing is build time disabled (that's the idea, anyway).
* Low overhead when capturing is runtime disabled.
Aiks inspector:
* Outline passes and rendered entities.
* Identify collapsed passes.
* Visibly highlight coverage.
* Live edit scene properties.
Possible future work:
* Filters!
* Blend mode property.
* Pointer + release proc property.
* Support captures in the DL playground.
* Text atlas visualization.
* …
=> [Impeller] Add debug captures and inspector.

tools/font-subset/main.cc, tools/font-subset/test.py
CP of https://github.com/flutter/engine/pull/44864
CP request https://github.com/flutter/flutter/issues/132978
=> [CP] fix icon tree-shaking on web for fonts with no space char v3.14

impeller/core/buffer_view.h, impeller/renderer/backend/gles/buffer_bindings_gles.cc, impeller/renderer/backend/metal/render_pass_mtl.mm, impeller/renderer/backend/vulkan/render_pass_vk.cc, impeller/renderer/command.cc, impeller/renderer/command.h
The metal backend is the only backend that doesn't treat binding the vertex buffer specially. For the GLES and Vulkan backend, we can instead pull it out of the cmd map entirely.
This will make it easier to partially inline the map into the bindings object.
https://github.com/flutter/flutter/issues/133199
=> [Impeller] Don't place vertex buffer bindings in the Binding map.

DEPS
The linter package has been moved into the Dart SDK repo. It no longer needs to be checked out into
third_party/dart/third_party/pkg/linter.
Bug: https://github.com/dart-lang/linter/issues/4411
=> Remove package linter from DEPS

tools/gn
This flag removes some code from CanvasKit to reduce size by a little bit. I went ahead and did a run of the benchmarks (https://github.com/flutter/flutter/pull/133208) to see if it negatively affected anything, and there was no difference beyond noise between the current benchmark numbers and the benchmarks with this flag enabled.
The size differences are as follows:
Before the change:
```
total 30616
drwxr-xr-x  11 jacksongardner  primarygroup      352 Aug 23 14:33 .
drwxr-xr-x   7 jacksongardner  primarygroup      224 Aug 10 18:14 ..
-rw-r--r--@  1 jacksongardner  primarygroup     6148 May 12 17:41 .DS_Store
-rw-r--r--   2 jacksongardner  primarygroup    94899 Aug 23 14:23 canvaskit.js
-rwxr-xr-x   2 jacksongardner  primarygroup  6631693 Aug 23 14:23 canvaskit.wasm
-rwxr-xr-x   1 …
```
=> Turn on the `skia_enable_optimize_size` flag to save a bit of binary size

tools/gn
Reverts flutter/engine#45029
It appears this is causing a regression in the length of time some of our integration tests are taking, causing them to take twice as long, which is causing timeouts in CI. We should revert while we investigate.
=> Revert "Turn on the `skia_enable_optimize_size` flag to save a bit of binary size"

impeller/renderer/backend/vulkan/render_pass_vk.cc
This refactor makes recycling render passes easier since it starts to split out setting the layout of textures with creating the render pass description.
I didn't fully implement the split since it would technically be slower.  Until we get caching of render passes working it would require us to calculate the attachment descriptions twice, once to make the render pass and once to set the texture layout.
teases out some of the work from: https://github.com/flutter/engine/pull/44527
in the service of implementing: https://github.com/flutter/engine/pull/44861
issue: https://github.com/flutter/flutter/issues/133182
The final split will have this function for recycled render passes:
```c++
void SetTextureLayouts(const RenderTarget& render_target,
const std::shared_ptr<CommandBufferVK>& …
```
=> [Impeller] Refactor: Create attachment descriptions without setting layouts

ci/builders/mac_android_aot_engine.json, ci/builders/mac_host_engine.json, ci/builders/mac_ios_engine.json, ci/builders/mac_unopt.json
This was related to using tests property which is expected for tests running within a build and tasks property used for global tests.
Bug: flutter/flutter#133301 …
=> Fix global tests doing nothing.

shell/platform/darwin/ios/BUILD.gn
Ignore ungarded-availability for unit test
fixes https://github.com/flutter/flutter/issues/128958
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-break …
=> Ignore unguarded-availability for unit test

ci/builders/mac_android_aot_engine.json, ci/builders/mac_host_engine.json, ci/builders/mac_ios_engine.json, ci/builders/mac_unopt.json
Reverts flutter/engine#45097
Many failures on CI like:
```
ld: warning: ignoring file ../../../../out/ios_debug_sim_arm64_extension_safe/libocmock_shared.dylib, building for iOS Simulator-x86_64 but attempting to link with file built for iOS Simulator-arm64
ld: warning: ignoring file ../../../../out/ios_debug_sim_arm64_extension_safe/libios_test_flutter.dylib, building for iOS Simulator-x86_64 but attempting to link with file built for iOS Simulator-arm64
```
https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20Production%20Engine%20Drone/131188/overview
Not sure if there are also other tests failing in different ways.
=> Revert "Fix global tests doing nothing."

impeller/renderer/backend/vulkan/swapchain_impl_vk.cc, impeller/renderer/backend/vulkan/texture_source_vk.cc, impeller/renderer/backend/vulkan/texture_source_vk.h, impeller/renderer/backend/vulkan/texture_vk.cc, impeller/renderer/backend/vulkan/texture_vk.h
Just some documentation and cleanup while i'm trying to get render pass recycling working.
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-cha …
=> [Impeller]  Updated TextureSourceVK docs and deleted unused ivars

shell/platform/darwin/common/framework/Source/FlutterNSBundleUtils.h, shell/platform/darwin/common/framework/Source/FlutterNSBundleUtils.mm, shell/platform/darwin/ios/BUILD.gn, shell/platform/darwin/ios/framework/Headers/FlutterPlugin.h, shell/platform/darwin/ios/framework/Source/FlutterDartProject.mm, shell/platform/darwin/ios/framework/Source/FlutterDartProjectTest.mm, shell/platform/darwin/ios/framework/Source/FlutterEngine.mm, shell/platform/darwin/ios/framework/Source/FlutterPlatformPlugin.mm, shell/platform/darwin/ios/framework/Source/FlutterPlatformPluginTest.mm, shell/platform/darwin/ios/framework/Source/FlutterPluginAppLifeCycleDelegate.mm, shell/platform/darwin/ios/framework/Source/FlutterPluginAppLifeCycleDelegateTest.mm, shell/platform/darwin/ios/framework/Source/FlutterViewController.mm
This PR turns on the flag to support engine to build app extension. 
When building for app extension, the usage of sharedApplication API is removed.
fixes https://github.com/flutter/flutter/issues/124286 and https://github.com/flutter/flutter/issues/124289
[CLA]: …
=> ios: remove shared_application and support app extension build

impeller/aiks/aiks_unittests.cc, impeller/aiks/canvas.cc, impeller/aiks/paint.cc, impeller/aiks/paint.h, impeller/entity/contents/color_source_contents.cc, impeller/entity/contents/color_source_contents.h, impeller/entity/contents/filters/gaussian_blur_filter_contents.cc, impeller/entity/contents/solid_color_contents.cc, impeller/entity/contents/solid_color_contents.h, impeller/golden_tests/golden_playground_test_mac.cc
Resolves https://github.com/flutter/flutter/issues/132936.
* In some cases, mask blurs were getting applied twice.
* Coverage hint clipping was too aggressive on the second pass of the gaussian blur.
* Rework the mask blur applicator to support gracefully falling back to GPU-based color filters when necessary.
This fix requires us to cherry-pick: https://github.com/flutter/engine/pull/43519
Going a revert-based route to fix all of these problems would also be pretty complex.
I've been testing this against 3.13 and still need to cross reference the other issues. I haven't rigorously tested this against HEAD yet.
https://github.com/flutter/engine/assets/919017/9ee5e856-af7a-42b9-b135-ea268c2ba53f
=> [Impeller] Fix mask blurs and the Gaussian blur coverage hint.

ci/licenses_golden/licenses_flutter, impeller/BUILD.gn, impeller/aiks/BUILD.gn, impeller/aiks/aiks_playground.cc, impeller/aiks/aiks_playground.h, impeller/aiks/aiks_playground_inspector.cc, impeller/aiks/aiks_playground_inspector.h, impeller/aiks/aiks_unittests.cc, impeller/core/BUILD.gn, impeller/core/capture.cc, impeller/core/capture.h, impeller/entity/contents/solid_color_contents.cc, impeller/entity/contents/texture_contents.cc, impeller/entity/entity.cc, impeller/entity/entity.h, impeller/entity/entity_pass.cc, impeller/entity/entity_pass.h, impeller/golden_tests/golden_playground_test.h, impeller/golden_tests/golden_playground_test_mac.cc, impeller/golden_tests/golden_playground_test_stub.cc, impeller/renderer/context.cc, impeller/renderer/context.h
Resolves https://github.com/flutter/flutter/issues/133257.
Original PR: https://github.com/flutter/engine/pull/43764
This reverts commit 54c64a41a6294fe8cb4602aaffc5e77d096b9bf3.
The cause of the issue was that we were initializing an _active_ capture context by default, causing us to capture and playback documents all the time in debug builds.
Added a test to verify that the capture is inactive by default, turning off all recording and playback.
=> [Impeller] Reland debug captures and inspector.

.clang-tidy
Partial (safe) re-land of https://github.com/flutter/engine/pull/44936.
=> Use YAML >- to avoid strange formatting.

impeller/BUILD.gn, impeller/tools/impeller.gni
Disable Impeller captures on profile builds.
So that we can verify it doesn't have any overhead when build-time disabled in the benchmarks: https://github.com/flutter/flutter/issues/133440
=> [Impeller] Only enable captures in debug builds.

shell/platform/embedder/fixtures/README.md
Closes https://github.com/flutter/flutter/issues/133375.
=> Explain how to update the embedder/fixtures golden outputs.

lib/web_ui/lib/src/engine/dom.dart, lib/web_ui/lib/src/engine/skwasm/skwasm_impl/image.dart, lib/web_ui/skwasm/surface.cpp, third_party/canvaskit/BUILD.gn
This allows us to remove libpng from skia entirely, which saves us about 25kb brotli compressed.
Note, this should not change any functionality. The existing functionality is covered by the unit tests here: https://github.com/flutter/engine/blame/bd2132a0814f6df95471e97f7d5efaca515506bd/lib/web_ui/test/ui/image_golden_test.dart#L197-L197
=> [skwasm] encode PNGs using browser APIs

shell/platform/darwin/ios/framework/Source/FlutterViewController.mm, shell/platform/darwin/ios/framework/Source/FlutterViewControllerTest.mm
Fixed https://github.com/flutter/flutter/issues/130055.
We can cancel the `resumed` life cycle notification if we received `inactive` notification in the same runloop. …
=> [iOS] Don't call App lifecycle resumed when device is locked

shell/platform/darwin/ios/ios_surface_metal_impeller.mm
Sad Trombone. Because Flutter runs from a background thread, if we touch a CATransaction while there is a main thread transaction occuring then we'll trigger a framework error.
Fixes https://github.com/flutter/flutter/issues/133147
=> [Impeller] its not safe to presentWithTransaction from a background thread.

impeller/renderer/backend/gles/context_gles.cc, impeller/renderer/backend/metal/context_mtl.mm, impeller/renderer/backend/vulkan/capabilities_vk.cc, impeller/renderer/backend/vulkan/capabilities_vk.h, impeller/renderer/capabilities.cc, impeller/renderer/capabilities.h, impeller/renderer/capabilities_unittests.cc
Noticed this while working through documenting all of the capabilities. I guess we don't need this one anymore?
=> [Impeller] Remove unused HasThreadingRestrictions capability.

impeller/renderer/backend/gles/context_gles.cc, impeller/renderer/backend/metal/context_mtl.mm, impeller/renderer/backend/vulkan/capabilities_vk.cc, impeller/renderer/backend/vulkan/capabilities_vk.h, impeller/renderer/capabilities.cc, impeller/renderer/capabilities.h, impeller/renderer/capabilities_unittests.cc, impeller/scene/scene_context.cc, impeller/scene/scene_context.h
Resolves https://github.com/flutter/flutter/issues/133194.
And use it for building the Impeller Scene pipelines.
=> [Impeller] Add GetDefaultDepthStencil to capabilities.

shell/platform/darwin/common/framework/Source/FlutterNSBundleUtils.h, shell/platform/darwin/common/framework/Source/FlutterNSBundleUtils.mm, shell/platform/darwin/ios/BUILD.gn, shell/platform/darwin/ios/framework/Headers/FlutterPlugin.h, shell/platform/darwin/ios/framework/Source/FlutterDartProject.mm, shell/platform/darwin/ios/framework/Source/FlutterDartProjectTest.mm, shell/platform/darwin/ios/framework/Source/FlutterEngine.mm, shell/platform/darwin/ios/framework/Source/FlutterPlatformPlugin.mm, shell/platform/darwin/ios/framework/Source/FlutterPlatformPluginTest.mm, shell/platform/darwin/ios/framework/Source/FlutterPluginAppLifeCycleDelegate.mm, shell/platform/darwin/ios/framework/Source/FlutterPluginAppLifeCycleDelegateTest.mm, shell/platform/darwin/ios/framework/Source/FlutterViewController.mm
Reverts flutter/engine#44732
context: b/297654739
Synced with Chris and the error message is related to the PR
=> [flutter roll] Revert "ios: remove shared_application and support app extension build"

impeller/core/formats.h, impeller/entity/contents/atlas_contents.cc, impeller/entity/contents/filters/blend_filter_contents.cc, impeller/entity/contents/filters/gaussian_blur_filter_contents.cc, impeller/entity/contents/filters/morphology_filter_contents.cc, impeller/entity/contents/framebuffer_blend_contents.cc, impeller/entity/contents/tiled_texture_contents.cc, impeller/renderer/backend/gles/context_gles.cc, impeller/renderer/backend/metal/allocator_mtl.mm, impeller/renderer/backend/metal/context_mtl.mm, impeller/renderer/backend/vulkan/allocator_vk.cc, impeller/renderer/backend/vulkan/capabilities_vk.cc, impeller/renderer/backend/vulkan/capabilities_vk.h, impeller/renderer/capabilities.cc, impeller/renderer/capabilities.h, impeller/renderer/capabilities_unittests.cc
Add docstrings for the capabilities. Include examples/extra detail for the more confusing concepts.
Also renames a couple of capabilities for consistency with format terminology:
* SupportsDecalTileMode -> SupportsDecalSamplerAddressMode
* SupportsMemorylessTextures -> SupportsDeviceTransientTextures
PR is built on https://github.com/flutter/engine/pull/45240 (waiting for tree to reopen).
=> [Impeller] Document the capabilities.

impeller/entity/contents/text_contents.cc, impeller/typographer/backends/skia/typographer_context_skia.cc, impeller/typographer/backends/skia/typographer_context_skia.h, impeller/typographer/backends/stb/typographer_context_stb.cc, impeller/typographer/backends/stb/typographer_context_stb.h, impeller/typographer/font_glyph_pair.h, impeller/typographer/glyph.h, impeller/typographer/glyph_atlas.cc, impeller/typographer/glyph_atlas.h, impeller/typographer/lazy_glyph_atlas.cc, impeller/typographer/lazy_glyph_atlas.h, impeller/typographer/text_frame.cc, impeller/typographer/text_frame.h, impeller/typographer/typographer_context.h, impeller/typographer/typographer_unittests.cc
The atlas will now store a separate map of glyph positions for each font/scale pair.  This avoids the cost of repeated hashing and copying of font objects for each glyph in a text run.
See https://github.com/flutter/flutter/issues/133201
=> [Impeller] Reorganize the glyph atlas to improve efficiency when looking up runs of glyphs in the same font

lib/web_ui/lib/src/engine/canvaskit/canvaskit_api.dart, lib/web_ui/lib/src/engine/canvaskit/image_web_codecs.dart, lib/web_ui/lib/src/engine/canvaskit/renderer.dart, lib/web_ui/lib/src/engine/dom.dart, lib/web_ui/lib/src/engine/html/renderer.dart, lib/web_ui/lib/src/engine/renderer.dart, lib/web_ui/lib/src/engine/safe_browser_api.dart, lib/web_ui/lib/src/engine/skwasm/skwasm_impl/codecs.dart, lib/web_ui/lib/src/engine/skwasm/skwasm_impl/raw/raw_image.dart, lib/web_ui/lib/src/engine/skwasm/skwasm_impl/renderer.dart, lib/web_ui/lib/src/engine/skwasm/skwasm_stub/renderer.dart, lib/web_ui/lib/ui_web/src/ui_web/images.dart, lib/web_ui/skwasm/image.cpp, lib/web_ui/skwasm/library_skwasm_support.js, lib/web_ui/skwasm/skwasm_support.h, lib/web_ui/skwasm/surface.cpp, lib/web_ui/skwasm/surface.h, lib/web_ui/test/engine/scene_view_test.dart, lib/web_ui/test/ui/image_golden_test.dart
This API will help with situations in which the user has a browser resource that they want to transform into a `ui.Image` and render directly into the layer tree. Most browser resources can be converted to an `ImageBitmap` via the `createImageBitmap` API.
=> Add an API in `ui_web` to create a `ui.Image` from an `ImageBitmap`

.pylintrc
Unblocks https://github.com/flutter/engine/pull/45243, which adds the function:
```py
def `gather_build_bucket_golden_scraper_tests`():
```
=> Increase maximum length of function names from 30 to 60.

impeller/aiks/aiks_unittests.cc, impeller/entity/geometry/cover_geometry.cc, impeller/fixtures/BUILD.gn, impeller/fixtures/gradient.frag
Thanks to @bdero 😎 
Fixes https://github.com/flutter/flutter/issues/132802
Fixes https://github.com/flutter/flutter/issues/123142
=> [Impeller] CoverGeometry transforms its bounds.

shell/platform/darwin/macos/framework/Source/FlutterCompositor.mm, shell/platform/darwin/macos/framework/Source/FlutterSurfaceManager.h, shell/platform/darwin/macos/framework/Source/FlutterSurfaceManager.mm, shell/platform/darwin/macos/framework/Source/FlutterSurfaceManagerTest.mm, shell/platform/embedder/embedder.h, shell/platform/embedder/embedder_external_view.cc, shell/platform/embedder/embedder_external_view.h, shell/platform/embedder/embedder_external_view_embedder.cc, shell/platform/embedder/embedder_layers.cc, shell/platform/embedder/embedder_layers.h, shell/platform/embedder/tests/embedder_assertions.h, shell/platform/embedder/tests/embedder_gl_unittests.cc, shell/platform/embedder/tests/embedder_metal_unittests.mm, shell/platform/embedder/tests/embedder_unittests.cc
Fixes https://github.com/flutter/flutter/issues/129073
Introduced `FlutterRegion` to represent arbitrary region:
```cpp
typedef struct {
/// The size of this struct. Must be sizeof(FlutterRegion).
size_t struct_size;
/// Number of rectangles in the region.
size_t rects_count;
/// The rectangles that make up the region.
FlutterRect* rects;
} FlutterRegion;
```
Note that this is identical to struct `FlutterDamage` with more generic naming. Maybe down the line we could deprecate `FlutterDamage` and use `FlutterRegion` instead.
Introduced `FlutterBackingStorePresentInfo`:
```cpp
typedef struct {
size_t struct_size;
/// The area of the backing store that contains Flutter contents. Pixels
/// outside of this area are transparent and the embedder may choose not
/// to render them. Coordinates …
```
=> [macOS] Implement unobstructed platform views

DEPS, tools/gn
This PR lands changes to `tools/gn` to use Flutter's RBE instance instead of Goma. It is initially supported only for builds from a Linux host.
1. Authenticate with `gcloud`
```
engine/src$ ./buildtools/linux-x64/gcloud/bin/gcloud auth application-default login --disable-quota-project
```
2. GN
```
engine/src$ ./flutter/tools/gn --android --android-cpu arm64 --no-lto --runtime-mode debug --rbe
```
3. Build
```
engine/src$ ninja -C out/android_debug_arm64 -j200
```
=> Adds an --rbe option to tools/gn that works on Linux hosts

shell/platform/darwin/common/BUILD.gn, shell/platform/darwin/macos/BUILD.gn
Links in an implementation of _availability_version_check on macOS.                
This is required due to an upstream compiler builtin (runtime) change              
that marked this function as weakly-linked via `__attribute__((weak import))`   
As such, no linking failure occurs when the function is unavailable at             
link time.                                                                         
By providing an implementation, the linker picks up our implementation,            
which looks up symbol in question at runtime (via dlsym) on the first              
invocation, caches it for later invocations, then invokes it. This is,             
in fact, precisely what the original clang builtin implementation did.             
Upstream clang change: …
=> [macOS] Link __availability_version_check

shell/common/shell_unittests.cc
Fix an unnecessary util function that I created not knowing there's already `PostSync`. …
=> Replace an unnecessary util function with PostSync

tools/const_finder/lib/const_finder.dart
The arguments no longer seem to be all required and non-null. Updated the doc comment to reflect this.
=> Update comment const_finder.dart

flow/layers/cacheable_layer.cc, flow/layers/cacheable_layer.h, flow/layers/clip_path_layer_unittests.cc, flow/layers/clip_rect_layer_unittests.cc, flow/layers/clip_rrect_layer_unittests.cc, flow/layers/clip_shape_layer.h, flow/layers/color_filter_layer.cc, flow/layers/color_filter_layer_unittests.cc, flow/layers/display_list_layer.cc, flow/layers/display_list_layer.h, flow/layers/display_list_layer_unittests.cc, flow/layers/image_filter_layer.cc, flow/layers/image_filter_layer_unittests.cc, flow/layers/layer_raster_cache_item.h, flow/layers/opacity_layer.cc, flow/layers/opacity_layer_unittests.cc, flow/layers/shader_mask_layer.cc, flow/layers/shader_mask_layer_unittests.cc, flow/raster_cache_item.h, flow/testing/mock_layer.cc, flow/testing/mock_layer.h, flow/testing/mock_raster_cache.cc
Fixes https://github.com/flutter/flutter/issues/133377
The default allocation of RasterCacheItems in the layer tree was showing up in profiles of apps running on Impeller which don't actually use the raster cache.
In order to eliminate the overhead of those allocations, RasterCacheItems are now lazily allocated only when the layers encounter an actual raster_cache during the Preroll phase.
=> Lazily allocate RasterCacheItems only when caching is enabled

BUILD.gn, shell/platform/darwin/ios/BUILD.gn
Reverts flutter/engine#44821
clang-tidy failures https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20Production%20Engine%20Drone/137227/overview
=> Revert "Reland "Build iOS unittest target in unopt builds" (#44356)""

impeller/display_list/dl_dispatcher.cc, impeller/display_list/dl_vertices_geometry.cc, impeller/display_list/dl_vertices_geometry.h, impeller/entity/geometry/vertices_geometry.cc, impeller/entity/geometry/vertices_geometry.h
The implementation of DLVerticesGeometry is holding onto a raw ptr that it doesn't own nor does it know that the lifecycle is deterministic. My bad!
This mostly worked (ehhh) until the stopwatch visualizer change. I've confirmed that going back to copying the data fixes the issue with the stopwatch visualizer.
Fixes https://github.com/flutter/flutter/issues/133813
=> [Impeller] copy data out of DlVertices.

flow/stopwatch_dl.cc
Man this is a sharp 🔪 
I literally pointed this out in the review and failed to notice the wrong parameter had the blend mode.
=> [Impeller] use correct blend mode for performance overlay

shell/platform/linux/fl_binary_messenger.cc, shell/platform/linux/fl_binary_messenger_test.cc
This PR fixes a mistake I made on https://github.com/flutter/engine/pull/44636 where the error handling code wrongly relied on `fl_method_channel_invoke_method_finish` instead of  `fl_binary_messenger_send_on_channel_finish`.
The error handling code was not called when running the tests added in https://github.com/flutter/engine/pull/44636 so this mistake did not pop up.
@robert-ancell I added a test that simulates an error response and I had to rely on `g_idle_add` to make it works. Is this approach ok?
Linux implementation for https://github.com/flutter/flutter/issues/132386
Adds one test.
=> [Linux] Fix channel buffers control commands error handling

shell/platform/darwin/common/framework/Source/FlutterNSBundleUtils.h, shell/platform/darwin/common/framework/Source/FlutterNSBundleUtils.mm, shell/platform/darwin/ios/BUILD.gn, shell/platform/darwin/ios/framework/Headers/FlutterPlugin.h, shell/platform/darwin/ios/framework/Source/FlutterDartProject.mm, shell/platform/darwin/ios/framework/Source/FlutterDartProjectTest.mm, shell/platform/darwin/ios/framework/Source/FlutterEngine.mm, shell/platform/darwin/ios/framework/Source/FlutterPlatformPlugin.mm, shell/platform/darwin/ios/framework/Source/FlutterPlatformPluginTest.mm, shell/platform/darwin/ios/framework/Source/FlutterPluginAppLifeCycleDelegate.mm, shell/platform/darwin/ios/framework/Source/FlutterPluginAppLifeCycleDelegateTest.mm, shell/platform/darwin/ios/framework/Source/FlutterViewController.mm
Relands https://github.com/flutter/engine/pull/44732 with fix. 
The original PR returns nil when the assets is not reachable, in some cases, the assets are not loaded yet but will be loaded later, so we should return the asset URL regardless. 
Also added a fallback to main bundle to match the previous implementation. 
The original PR was failed in internal tests in b/297654739
Now with the fix, all tests passed: cl/561449914
fixes https://github.com/flutter/flutter/issues/124289 …
=> Reland "ios: remove shared_application and support app extension build #44732"

impeller/aiks/aiks_unittests.cc, impeller/aiks/canvas.cc, impeller/entity/entity_pass.cc, impeller/entity/entity_pass.h
Fixes https://github.com/flutter/flutter/issues/133731
=> [Impeller] EntityPass::Clone needs to clone harder

shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm, shell/platform/darwin/ios/framework/Source/FlutterTextInputPluginTest.mm
Design doc with more details: https://docs.google.com/document/d/1sM3HMv-SQin39yX1aPUU7vtGv7Hcef1Quc3QhRXBl6A/edit?resourcekey=0-SFYD8vmOIkXiXCZvB1Wlcw#heading=h.tul5o3hopauh
Just to be safe, for now we only change for iOS 17. However, the same logic should apply to older iOS as well. So will update in a separate PR. 
Basically we were using `firstRectForRange` incorrectly. According to [the API doc](https://developer.apple.com/documentation/uikit/uitextinput/1614570-firstrectforrange), `firstRectForRange` should return **the rect for the queried range, or a subrange through the end of line, if the range encompasses multiple lines**.
For LTR language: 
```
0,  1,  2,  3
4,  5,  6,  7
```
Query: `[1, 2, 3, 4]`
Returns the following rect denoted by `[ ]`: 
```
0,  [1,  2,  3]
4,  5,   6, …
```
=> [ios][ios17][text_input]fix text input system highlight in iOS 17 Beta 7 with firstRectForRange

shell/platform/windows/angle_surface_manager.cc, shell/platform/windows/flutter_windows_engine.h, shell/platform/windows/flutter_windows_view.cc, shell/platform/windows/flutter_windows_view_unittests.cc
If the Windows system compositor is enabled, the Windows embedder disables the swap interval so that presenting to a surface does not block until the v-blank. If the Windows system compositor is disabled (which is possible on Windows 7), the Windows embedder enables swap interval to prevent screen tearing.
Updating the swap interval requires making the GL surface current, which we currently do on the platform thread. However, the raster thread also needs the GL surface for rendering. Our current version of ANGLE allows making a GL surface current on multiple threads. However, the latest version of ANGLE errors if a GL context is made current on multiple threads. This is causing the ANGLE roll to fail ([example](https://ci.chromium.org/ui/p/flutter/builders/try/Windows%20Engine%20Drone/2037 …
=> [Windows] Update vsync on raster thread

DEPS, shell/platform/android/BUILD.gn, shell/platform/android/android_context_vulkan_impeller.cc, shell/platform/android/io/flutter/embedding/engine/loader/FlutterLoader.java, tools/gn
fixes https://github.com/flutter/flutter/issues/133794
This adds the following shared libraries to the flutter.jar for debug builds on arm64:
```
lib/arm64-v8a/libVkLayer_khronos_validation.so
lib/arm64-v8a/libc++_shared.so
``` …
=> [Impeller] turned on validations for all debug builds

impeller/display_list/dl_unittests.cc, impeller/display_list/dl_vertices_geometry.cc
Lost this after the transition.
=> [impeller] premultiply vertices colors.

display_list/dl_builder.cc
Fixes https://github.com/flutter/flutter/issues/133437
With this fix, the [benchmarks](https://github.com/flutter/flutter/pull/133434) for pictures with huge bounds become runnable under more conditions. Currently those benchmarks only run on platforms where we don't run into this issue. The performance on those platforms/conditions will not change much, but with this fix we can run them on Impeller and add a variant that has a platform view on the display.
=> Cull the RTree bounds when they are forwarded in DrawDisplayList

impeller/display_list/dl_dispatcher.cc, impeller/display_list/skia_conversions.cc, impeller/display_list/skia_conversions.h, impeller/geometry/geometry_unittests.cc, impeller/geometry/path.h, impeller/geometry/path_builder.cc, impeller/geometry/path_builder.h
This is a design problem in the Flutter API, that in general you can't assume a Path hasn't changed from the last time you used it. We're so close, so just move the mutation methods to PathBuilder :)
Fixes https://github.com/flutter/flutter/issues/133880
=> [Impeller] Make paths externally immutable, update all tests to use PathBuilder to create Path.

impeller/entity/contents/text_contents.cc
Fixes builds against some STLs (detected in impeller-cmake [ubuntu build](https://github.com/bdero/impeller-cmake/actions/runs/6020031888/job/16330726595)).
=> [Impeller] Import cstring for memcpy.

shell/platform/linux/fl_accessible_text_field.cc
This version added the autoptr macros which we no longer need to define.
https://github.com/flutter/flutter/issues/132881
=> Fix building on Pango 1.49.4

ci/builders/linux_unopt.json, ci/builders/mac_android_aot_engine.json, ci/check_build_configs.sh, testing/run_tests.py, tools/pkg/engine_build_configs/analysis_options.yaml, tools/pkg/engine_build_configs/bin/check.dart, tools/pkg/engine_build_configs/lib/engine_build_configs.dart, tools/pkg/engine_build_configs/lib/src/build_config.dart, tools/pkg/engine_build_configs/lib/src/build_config_loader.dart, tools/pkg/engine_build_configs/pubspec.yaml, tools/pkg/engine_build_configs/test/build_config_loader_test.dart, tools/pkg/engine_build_configs/test/build_config_test.dart, tools/pub_get_offline.py
Also adds a test that the build configs in the repo are valid json that matches the spec.
Fleshed out @christopherfujino's code from here https://github.com/christopherfujino/flutter-engine-runner/blob/main/main.dart
=> Adds a Dart library for loading and parsing build configs

impeller/display_list/skia_conversions.cc, impeller/geometry/geometry_unittests.cc, impeller/geometry/path.cc, impeller/geometry/path.h, impeller/geometry/path_builder.cc, impeller/geometry/path_builder.h
Now that Paths are externally immutable, we can compute the bounds once at construction. This also allows the Skia conversions to set the already computed bounds.
=> [Impeller] compute path bounds once, use Skia computed bounds where possible.

shell/platform/darwin/ios/framework/Source/FlutterPlatformPluginTest.mm
Fixes https://github.com/flutter/flutter/issues/133776
"The crash is due to testShareScreenInvoked presents the activityViewController, which prevents the engineViewController to be dealloc'd in the test: https://github.com/flutter/engine/blob/main/shell/platform/darwin/ios/framework/Source/FlutterPlatformPlugin.mm#L161C4-L161C24"
This fix stubbing the presentViewController call, which prevents the viewController being alloc'd, thus preventing the leak. It is probably sufficient for this test.
[test-exempt]: …
=> Fix iOS unittests leak in shared.invoke method channel that causes crash

testing/scenario_app/ios/Scenarios/ScenariosUITests/GoldenTestManager.m, testing/scenario_app/ios/Scenarios/ScenariosUITests/LocalizationInitializationTest.m
1. New Mac version seems to have updated the locale data, to match the mac change, we can dynamically read the data when testing instead of hard coding.
2. "we are sending a UIImage type as parameter to `XCTAttachment attachmentWithScreenshot:`, which takes a `XCUIScreenshot` as parameter, this is not supposed to pass in old iOS versions." In this PR we updated the parameter to use the `XCUIScreenshot` type.
Fixes https://github.com/flutter/flutter/issues/133783
[Flutter Style …
=> [iOS ] Fix errors in unittest and scenario tests running against iOS 17 simulators (details in the description)

shell/platform/android/BUILD.gn
Companion comment to the one in https://github.com/flutter/buildroot/pull/761
=> Adds a comment on clang_arm64_apilevel26 toolchain usage

impeller/typographer/font_glyph_pair.h
Fixes the following in G3 (b/299185514):
```
impeller/typographer/font_glyph_pair.h:27:27: error: no template named 'unordered_map' in namespace 'std'; did you mean 'unordered_set'?
using FontGlyphMap = std::unordered_map<ScaledFont, std::unordered_set<Glyph>>;
~~~~~^
```
I don't really know why the lack of this import only breaks the g3 build, but not here. My guess is that it's being imported transitively in some other import that's being ifdef-ed out in g3. 
But since we're already using it in https://github.com/flutter/engine/blob/93635e75d1838b349d9b868a7e9f7a70f4b732bd/impeller/typographer/font_glyph_pair.h#L27, we probably want to use the import in this file anyway. …
=> Add import for `<unordered_map>` to fix the g3 build

tools/gn
not necessary after: https://github.com/flutter/engine/pull/45350 …
=> Remove android API 26 bump for validation layers

DEPS
Also rolls buildroot to pick up flags to silence new warnings.
=> Roll clang to 576b184d6e3b633f51b908b61ebd281d2ecbf66f

shell/platform/darwin/macos/framework/Headers/FlutterPluginRegistrarMacOS.h, shell/platform/darwin/macos/framework/Source/FlutterEngine.mm, shell/platform/darwin/macos/framework/Source/FlutterEngineTest.mm, shell/platform/darwin/macos/framework/Source/FlutterViewController.mm
These directly copy the iOS APIs, to minimize the branching needed in plugins with shared implementation code, and to facilitate the long-term goal of merging the iOS and macOS plugin headers. This does mean replicating the unfortunately non-idiomatic behavior of having `valuePublishedByPlugin:` sometimes return `nil` and sometimes return `NSNull`, instead of distinguishing between `nil` cases (if that's actually even necessary here) via a more specific API. In isolation I would definitely not design the API with this behavior, but consistency with iOS is the more important factor.
(Eventually I think we'll need a sort of "v2" of iOS plugin APIs since there are a number of strange behaviors that we're currently stuck with, but migrating iOS and macOS together to a new set of APIs won't be …
=> Add macOS support for plugin value publishing

impeller/entity/shaders/gaussian_blur/gaussian_blur.glsl, impeller/entity/shaders/gaussian_blur/gaussian_blur.vert, impeller/tools/malioc.json
Follow-up for https://github.com/flutter/engine/pull/45520.
Missed a few things... These were getting defaulted thanks to impeller's header gen but don't have any purpose now that we've removed the old blur style impl.
=> [Impeller] Gaussian blur: Remove lingering BlurStyle vertex data/uniforms.

shell/common/rasterizer.cc
Skia plans to stop the default behavior of encoding SkImages in SkPictures using a PNG encoder. To preserve that behavior, clients need to explicitly set an SkSerialProc to do so.
This was the only location I could find in Flutter which serialized an skp. …
=> Explicitly encode SkImages in SkPictures as PNG

shell/platform/fuchsia/flutter/engine.cc, shell/platform/fuchsia/flutter/flatland_connection.cc, shell/platform/fuchsia/flutter/flatland_connection.h, shell/platform/fuchsia/flutter/flutter_runner_product_configuration.cc, shell/platform/fuchsia/flutter/flutter_runner_product_configuration.h, shell/platform/fuchsia/flutter/tests/external_view_embedder_unittests.cc, shell/platform/fuchsia/flutter/tests/flatland_connection_unittests.cc, shell/platform/fuchsia/flutter/tests/flutter_runner_product_configuration_unittests.cc
This CL restructures Flatland vsync loop to fire for each vsync instead of each OnNextFrameBegin. As shown in the traces attached to the bug, the current implementation of firing callbacks on each OnNextFrameBegin causes skips when Flutter has longer draw calls. By scheduling frames in between, we are increasing the chance of sending one before the latch point. OnNextFrameBegin is now used to keep track of present credits and future presentation times as well as when to start frame, replacing the need for max_frames_in_flight and vsync_offset fields.
Bug: b/296272449
=> [fuchsia] Restructure Flatland vsync loop

shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm, shell/platform/darwin/ios/framework/Source/FlutterTextInputPluginTest.mm
This reverts part of https://github.com/flutter/engine/pull/44779. Verified this to be the regression for https://github.com/flutter/flutter/issues/133908. 
This pair of `textWill/DidChange` calls was added in Beta 1, in order to fix highlight region missing last character (more details [here](https://docs.google.com/document/d/1sM3HMv-SQin39yX1aPUU7vtGv7Hcef1Quc3QhRXBl6A/edit?resourcekey=0-SFYD8vmOIkXiXCZvB1Wlcw#heading=h.ddlvu2i2epyl)). 
However, that fix doesn't work anymore for Beta 7 - it turns out that in Beta 7, the system doesn't rely on the `selectionRects` to determine the highlight region anymore. Instead, the system relies on `firstRectForRange` API. So we fixed the system highlight in `firstRectForRange` in Beta 7. 
So even after reverting this change, the system highlight …
=> Reverts part of "fix auto-correction highlight on top left corner (Again)" 

ci/licenses_golden/excluded_files, impeller/renderer/backend/vulkan/BUILD.gn, impeller/renderer/backend/vulkan/command_encoder_vk.cc, impeller/renderer/backend/vulkan/command_encoder_vk_unittests.cc, impeller/renderer/backend/vulkan/resource_manager_vk.h, impeller/renderer/backend/vulkan/test/mock_vulkan.cc
issue: https://github.com/flutter/flutter/issues/133506
This fixes one of the issues seen in https://github.com/flutter/flutter/issues/133506.  There were multiple ones though.
[breaking …
=> [Impeller] Started tracking the pool with the command buffer.

ci/licenses_golden/licenses_flutter, impeller/aiks/BUILD.gn, impeller/aiks/aiks_unittests.cc, impeller/aiks/canvas.cc, impeller/aiks/canvas.h, impeller/aiks/color_filter.cc, impeller/aiks/color_filter.h, impeller/aiks/image_filter.cc, impeller/aiks/image_filter.h, impeller/aiks/paint.cc, impeller/aiks/paint.h, impeller/display_list/dl_dispatcher.cc, impeller/entity/contents/filters/filter_contents.cc, impeller/entity/contents/filters/filter_contents.h, impeller/entity/contents/filters/inputs/filter_contents_filter_input.cc, impeller/entity/contents/filters/inputs/filter_contents_filter_input.h, impeller/entity/contents/filters/inputs/filter_input.cc, impeller/entity/contents/filters/inputs/filter_input.h, impeller/entity/contents/filters/inputs/filter_input_unittests.cc, impeller/entity/contents/filters/matrix_filter_contents.cc, impeller/entity/contents/filters/matrix_filter_contents.h, impeller/entity/entity_pass.cc, impeller/entity/entity_unittests.cc
These are API improvements on the way to solving https://github.com/flutter/flutter/issues/131182.
* Remove `effect_transform` and `is_subpass` from the static `FilterContents` factories. These are for internal use only.
* Replace `impeller::Paint` filter procs with Aiks `ImageFilter` factories similar to `ColorFilter`. This gives Aiks a simple interface for constructing filters and prevents possible state cloning bugs when copying filters into `EntityPass`.
* Allow for setting filter inputs, setting the effect transform, and enabling subpass mode on a filter chain after it has been instantiated. This will allow us to sample coverage in `EntityPass` without rendering any snapshots using rect filter inputs.
=> [Impeller] Aiks image filters; allow setting effect transforms after FilterContents instantiation.

flutter_frontend_server/pubspec.yaml
The change
https://dart-review.googlesource.com/c/sdk/+/323000 added a dependency on dart2wasm to the frontend_server package.
Flutter engine has all dependencies in its source checkout, and paths to their locations hardcoded in the dependency_ovedrrides of flutter_frontend_server's pubspec.yaml.
Add the dart2wasm package location to pubspec.yaml. Add the transitive dependency wasm_builder package lcoation to pubspec.yaml.
=> Add dart2wasm dependency to flutter_frontend_server

lib/web_ui/lib/src/engine/dom.dart, lib/web_ui/lib/src/engine/text_editing/text_editing.dart, lib/web_ui/test/engine/text_editing_test.dart
Fixes issue where the delta range would be calculated wrong when the selection is inverted.
=> [Web] Fix insertions/deletions at inverted selection for TextEditingDeltas

impeller/renderer/backend/vulkan/command_pool_vk.cc, impeller/renderer/backend/vulkan/command_pool_vk.h
I was reviewing this code for the first time before implementing https://github.com/flutter/flutter/issues/133198.
- Removed unused public method `GetGraphicsCommandPool()`.
- Removed forward references by including the right references [^1].
- Tried to document the contracts of various methods that return invalid or disconnected objects.
If I made any mistakes, please feel free to point them out as this is how I'm learning how this stuff works 😄 
/cc @jonahwilliams 
[^1]: [Avoid using forward declarations where possible](https://google.github.io/styleguide/cppguide.html#Forward_Declarations). Instead, include the headers you need.
=> Document and provide small cleanups to `CommandPoolVk`.

display_list/benchmarking/dl_benchmarks.cc, display_list/testing/dl_rendering_unittests.cc, flow/skia_gpu_object.h, flow/skia_gpu_object_unittests.cc, shell/common/rasterizer.cc, shell/common/rasterizer_unittests.cc, shell/platform/fuchsia/flutter/engine.cc
In http://review.skia.org/750403 and http://review.skia.org/751523, Skia modified some `GrDirectContext` APIs to make them less error-prone in response to https://crbug.com/1475906. This updates Flutter to call those modified APIs. …
=> Use safer GrDirectContext APIs

lib/web_ui/lib/src/engine/app_bootstrap.dart, lib/web_ui/lib/src/engine/canvaskit/image_web_codecs.dart, lib/web_ui/lib/src/engine/js_interop/js_loader.dart, lib/web_ui/lib/src/engine/js_interop/js_promise.dart, lib/web_ui/lib/src/engine/safe_browser_api.dart, lib/web_ui/test/engine/app_bootstrap_test.dart, lib/web_ui/test/engine/window_test.dart
Our JSPromise hackery is causing some issues with the new dart roll. We should just use the `JSPromise` and `JSFunction` support to simplify this. Note that I still have to do *some* hackery to construct `JSPromise` objects and to invoke `JSFunction` objects, and eventually we'll probably be able to simplify this even more once those APIs are baked into `dart:js_interop`
=> Remove some of our hacks around JSPromise now that we have better APIs.

lib/web_ui/lib/src/engine/app_bootstrap.dart, lib/web_ui/lib/src/engine/canvaskit/image_web_codecs.dart, lib/web_ui/lib/src/engine/js_interop/js_loader.dart, lib/web_ui/lib/src/engine/js_interop/js_promise.dart, lib/web_ui/lib/src/engine/safe_browser_api.dart, lib/web_ui/test/engine/app_bootstrap_test.dart, lib/web_ui/test/engine/window_test.dart
Reverts flutter/engine#45591
This is somehow causing some issues with the hot reload tests and blocking engine -> framework rolls. See https://github.com/flutter/flutter/pull/134455
=> Revert "Remove some of our hacks around JSPromise now that we have better APIs."

flutter_vma/BUILD.gn, flutter_vma/flutter_vma.cc
These are still only enabled in unopt modes (we can tweak this later). Asserts sometimes may not get piped to the loggers Flutter engine developers usually use. This now brings assertions back in the control of the engine.
=> Pipe VMA asserts to FML.

lib/web_ui/lib/src/engine/dom.dart, lib/web_ui/lib/src/engine/text_editing/text_editing.dart, lib/web_ui/test/engine/text_editing_test.dart
Fixes https://github.com/flutter/flutter/issues/131906
[CLA]: …
=> [Web] Properly report inverted selection

impeller/renderer/backend/vulkan/resource_manager_vk.cc, impeller/renderer/backend/vulkan/resource_manager_vk.h, impeller/renderer/backend/vulkan/resource_manager_vk_unittests.cc
Fixes https://github.com/flutter/flutter/issues/134482.
I wish I knew how to create the thread in `::Create()`, but given the constructor is private I feel less bad about reverting part of https://github.com/flutter/engine/pull/45474. Added a test that consistently fails before this PR and passes after.
(Unblocks https://github.com/flutter/flutter/issues/133198)
=> [Impeller] Fix thread leak in ResourceManagerVK.

shell/platform/darwin/ios/framework/Source/FlutterEngineTest.mm
Moving the code block to autorelease pool to ensure the FlutterEngine is released in the test.
Fixes: https://github.com/flutter/flutter/issues/134388 …
=> [ios] Fix testDeallocated failing locally. 

lib/web_ui/lib/src/engine/app_bootstrap.dart, lib/web_ui/lib/src/engine/canvaskit/image_web_codecs.dart, lib/web_ui/lib/src/engine/js_interop/js_loader.dart, lib/web_ui/lib/src/engine/js_interop/js_promise.dart, lib/web_ui/lib/src/engine/safe_browser_api.dart, lib/web_ui/test/canvaskit/canvaskit_api_test.dart, lib/web_ui/test/engine/app_bootstrap_test.dart, lib/web_ui/test/engine/browser_detect_test.dart, lib/web_ui/test/engine/initialization_test.dart, lib/web_ui/test/engine/window_test.dart
This prepares for some upcoming changes to dart2js which will be more strict about what types can be used in a JS interop declaration.
=> Fix JS interop signatures to use only JS types.

.ci.yaml, BUILD.gn, shell/platform/darwin/ios/BUILD.gn, shell/platform/darwin/ios/framework/Source/FlutterChannelKeyResponderTest.mm, shell/platform/darwin/ios/framework/Source/FlutterEmbedderKeyResponderTest.mm, shell/platform/darwin/ios/framework/Source/FlutterEngineGroupTest.mm, shell/platform/darwin/ios/framework/Source/FlutterEngineTest_mrc.mm, shell/platform/darwin/ios/framework/Source/FlutterFakeKeyEvents.h, shell/platform/darwin/ios/framework/Source/FlutterFakeKeyEvents.mm, shell/platform/darwin/ios/framework/Source/FlutterKeyboardManagerTest.mm, shell/platform/darwin/ios/framework/Source/FlutterPlatformViewsTest.mm, shell/platform/darwin/ios/framework/Source/FlutterTextureRegistryRelayTest.mm, shell/platform/darwin/ios/framework/Source/FlutterUndoManagerPluginTest.mm, shell/platform/darwin/ios/framework/Source/FlutterViewControllerTest.mm, shell/platform/darwin/ios/framework/Source/FlutterViewControllerTest_mrc.mm, shell/platform/darwin/ios/framework/Source/FlutterViewTest.mm, shell/platform/darwin/ios/framework/Source/SemanticsObjectTest.mm, shell/platform/darwin/ios/framework/Source/VsyncWaiterIosTest.mm, shell/platform/darwin/ios/framework/Source/accessibility_bridge_test.mm, shell/platform/darwin/ios/platform_message_handler_ios_test.mm
Reland https://github.com/flutter/engine/pull/44821 …
=> Reland "Build iOS unittest target in unopt builds" (#44356)"" (#45346)"

impeller/renderer/backend/vulkan/capabilities_vk.cc, impeller/renderer/backend/vulkan/capabilities_vk.h, impeller/renderer/backend/vulkan/context_vk_unittests.cc, impeller/renderer/backend/vulkan/test/mock_vulkan.cc, impeller/renderer/backend/vulkan/test/mock_vulkan.h, shell/platform/android/android_context_vulkan_impeller.cc
Fixes https://github.com/flutter/flutter/issues/131714
=> [Impeller] If validations are enabled but not found, still create the VK context.

shell/platform/embedder/BUILD.gn, shell/platform/embedder/embedder.h, shell/platform/embedder/tests/embedder_config_builder.cc, shell/platform/embedder/tests/embedder_config_builder.h, shell/platform/embedder/tests/embedder_test_context_vulkan.cc, shell/platform/embedder/tests/embedder_test_context_vulkan.h, shell/platform/embedder/tests/embedder_vk_unittests.cc
fixes https://github.com/flutter/flutter/issues/133933 …
=> Added test to assert the vulkan embedder threadsafe vkqueue usage

ci/builders/mac_ios_engine.json, tools/gn_test.py
Uploads the artifacts for extension safe build. These artifacts need to be codesigned.
part of https://github.com/flutter/flutter/issues/124291 …
=> [ios] upload extension safe artifacts

impeller/renderer/backend/vulkan/surface_context_vk.cc, impeller/renderer/backend/vulkan/swapchain_impl_vk.cc
Earlier, there was no recovery from vk::Result::eSuboptimalKHR. This made the playground be stuck with a swapchain image size of 1x1 with suboptimal error code on acquisition indefinitely.
Towards fixing the playgrounds. There are still some validation errors.
=> [Impeller] Fix swapchain recreation for non-polling cases.

impeller/aiks/aiks_unittests.cc, impeller/compiler/code_gen_template.h, impeller/compiler/compiler.cc, impeller/compiler/compiler_backend.cc, impeller/compiler/reflector.cc, impeller/core/shader_types.h, impeller/playground/backend/vulkan/playground_impl_vk.cc, impeller/renderer/backend/vulkan/descriptor_pool_vk.cc, impeller/renderer/backend/vulkan/formats_vk.h, shell/platform/embedder/embedder_surface_metal_impeller.mm
Towards https://github.com/flutter/flutter/issues/128911
Drive by fixes https://github.com/flutter/flutter/issues/123795
=> [Impeller] Patch the compiler to account for subpass inputs and PSO metadata.

flow/layers/cacheable_layer.cc, flow/layers/cacheable_layer.h, flow/layers/clip_path_layer_unittests.cc, flow/layers/clip_rect_layer_unittests.cc, flow/layers/clip_rrect_layer_unittests.cc, flow/layers/clip_shape_layer.h, flow/layers/color_filter_layer.cc, flow/layers/color_filter_layer_unittests.cc, flow/layers/display_list_layer.cc, flow/layers/display_list_layer.h, flow/layers/display_list_layer_unittests.cc, flow/layers/image_filter_layer.cc, flow/layers/image_filter_layer_unittests.cc, flow/layers/layer_raster_cache_item.h, flow/layers/opacity_layer.cc, flow/layers/opacity_layer_unittests.cc, flow/layers/shader_mask_layer.cc, flow/layers/shader_mask_layer_unittests.cc, flow/raster_cache_item.h, flow/testing/mock_layer.cc, flow/testing/mock_layer.h, flow/testing/mock_raster_cache.cc
Reverts flutter/engine#45211
b/298583505
=> Revert "Lazily allocate RasterCacheItems only when caching is enabled"

shell/platform/fuchsia/flutter/engine.cc, shell/platform/fuchsia/flutter/flatland_connection.cc, shell/platform/fuchsia/flutter/flatland_connection.h, shell/platform/fuchsia/flutter/flutter_runner_product_configuration.cc, shell/platform/fuchsia/flutter/flutter_runner_product_configuration.h, shell/platform/fuchsia/flutter/tests/external_view_embedder_unittests.cc, shell/platform/fuchsia/flutter/tests/flatland_connection_unittests.cc, shell/platform/fuchsia/flutter/tests/flutter_runner_product_configuration_unittests.cc
This CL restructures Flatland vsync loop to fire for each vsync instead of each OnNextFrameBegin. As shown in the traces attached to the bug, the current implementation of firing callbacks on each OnNextFrameBegin causes skips when Flutter has longer draw calls. By scheduling frames in between, we are increasing the chance of sending one before the latch point. OnNextFrameBegin is now used to keep track of present credits and future presentation times as well as when to start frame, replacing the need for max_frames_in_flight and vsync_offset fields.
Bug: b/296272449
(cherry picked from commit https://github.com/flutter/engine/commit/633ba427c498d9a5d096ac4979ecaa83ace4deaa)
=> [fuchsia] Restructure Flatland vsync loop (#45531)

tools/clang_tidy/lib/clang_tidy.dart, tools/clang_tidy/lib/src/git_repo.dart, tools/clang_tidy/pubspec.yaml, tools/clang_tidy/test/clang_tidy_test.dart, tools/clang_tidy/test/process_fakes.dart
Partial work towards https://github.com/flutter/flutter/issues/133190.
Some context, from @zanderso on chat:
@matanlurey:
> For [`clang_tidy_test.dart`](https://github.com/flutter/engine/blob/c020936303cb0646cd10593e6e427d8c5aa6ce52/tools/clang_tidy/test/clang_tidy_test.dart), what is your vision there? I remember we ran into problems with it actually executing `clang.run()` in too many of the test cases, but I don't remember (or seem to have written down) what we decided to do 🙂
@zanderso:
> The existing tests are calling `computeFilesOfInterest` and `getLintCommandsForFiles` and inspecting the results for positive tests instead of hitting a real clang-tidy invocation. Tests of command line flags that call `clangTidy.run()` are also testing cases that short-circuit or fail before making …
=> Do not run real processes in `clang_tidy_test.dart`

impeller/aiks/aiks_unittests.cc, impeller/core/formats.h, impeller/entity/geometry/stroke_path_geometry.cc, impeller/geometry/path.cc, impeller/geometry/path.h, impeller/geometry/path_component.h
Fixes https://github.com/flutter/flutter/issues/133032
The issue is that when we draw a line we always try to draw a complete rectangle from point 1 to point2 before drawing the join and the next line
This becomes a problem if there is a sharp turn
Notice there will be a slight over drawing at the bottom.
The solution then is to not draw the rect first before drawing the join. It will be the join's responsibility to draw the complete the rect from the line start to the join.
This should also save a lot of repeatedly drawing during the join
[Flutter Style …
=> [Impeller] Fixes stroke path geometry that can draw outside of path if the path ends at sharp turn.

impeller/renderer/backend/vulkan/BUILD.gn, impeller/renderer/backend/vulkan/allocator_vk.cc, impeller/renderer/backend/vulkan/allocator_vk.h, impeller/renderer/backend/vulkan/context_vk.cc
Fixes https://github.com/flutter/flutter/issues/121947
=> [Impeller] Remove dependency on //flutter/vulkan and use a single proc table.

impeller/aiks/aiks_unittests.cc, impeller/compiler/code_gen_template.h, impeller/compiler/compiler.cc, impeller/compiler/compiler_backend.cc, impeller/compiler/reflector.cc, impeller/core/shader_types.h, impeller/playground/backend/vulkan/playground_impl_vk.cc, impeller/renderer/backend/vulkan/descriptor_pool_vk.cc, impeller/renderer/backend/vulkan/formats_vk.h, shell/platform/embedder/embedder_surface_metal_impeller.mm
Reverts flutter/engine#45739
fixes https://github.com/flutter/flutter/issues/134666
=> Revert "[Impeller] Patch the compiler to account for subpass inputs and PSO metadata."

shell/platform/windows/text_input_plugin.cc, shell/platform/windows/text_input_plugin_unittest.cc
When composing with the IME in a text edit, we should add the `start` of the composition range to the in-composition `cursor_pos` rather than its `extent`. When using `extent`, the cursor position would always be outside of the composition range, resulting in the linked bug. Add a test to check cursor position.
https://github.com/flutter/flutter/issues/123749 …
=> Use `start` instead of `extent` for Windows IME cursor position

web_sdk/BUILD.gn
This continues work on https://github.com/flutter/flutter/issues/133467
We still need a change on the tool side to consume this platform dill file after this lands.
=> Compile a platform dill for dart2wasm

sky/tools/create_macos_framework.py
Makes mac framework readable and executable by all.
Bug: https://github.com/flutter/flutter/issues/132725
[breaking …
=> Fix script

impeller/aiks/aiks_unittests.cc, impeller/aiks/paint.cc, impeller/aiks/paint.h, impeller/aiks/paint_pass_delegate.cc, impeller/aiks/paint_pass_delegate.h, impeller/entity/contents/contents.cc, impeller/entity/contents/contents.h, impeller/entity/contents/filters/filter_contents.cc, impeller/entity/contents/filters/filter_contents.h, impeller/entity/contents/filters/inputs/filter_contents_filter_input.cc, impeller/entity/contents/filters/inputs/filter_contents_filter_input.h, impeller/entity/contents/filters/inputs/filter_input.cc, impeller/entity/contents/filters/inputs/filter_input.h, impeller/entity/contents/filters/matrix_filter_contents.cc, impeller/entity/contents/filters/matrix_filter_contents.h, impeller/entity/entity_pass.cc, impeller/entity/entity_pass.h, impeller/entity/entity_pass_delegate.cc, impeller/entity/entity_pass_delegate.h, impeller/entity/entity_unittests.cc
Resolves https://github.com/flutter/flutter/issues/131182.
I adjusted the size of the matrix filtered circle in both SaveLayer Matrix filter test variants (post-filter and backdrop filter) to move the transformed circle outside the coverage area that would be computed if subpass filters aren't being accounted for. Further, we need to avoid intersecting with the pass coverage hint when the transformation being applied by the paint's filter graph causes the Entity's space basis to deviate from the parent pass basis. We're still able to apply it for simple translations, though.
Before:
After:
=> [Impeller] Incorporate filters in subpass coverage.

lib/web_ui/dev/webdriver_browser.dart, lib/web_ui/pubspec.yaml
This is to be able to update the webdriver dependency. …
=> Update webdriver imports.

lib/web_ui/lib/src/engine/skwasm/skwasm_impl/surface.dart, lib/web_ui/skwasm/library_skwasm_support.js
Declaring this as non-nullable causes breakage with an incoming JS interop change from the SDK. Marking this as nullable fixes the issue.
This doesn't actually change any behavior. The breakages were in `test/ui/image_golden_test.dart`. No changes to the test are required (they did catch the issue when the dart roll happened).
=> Declare the js context as nullable in skwasm surface callback

impeller/aiks/aiks_unittests.cc, impeller/entity/contents/scene_contents.h
Noticed we had a residual unguarded import of scene_contents.h while investigating https://github.com/flutter/flutter/issues/134745.
=> [Impeller] Assert IMPELLER_ENABLE_3D when importing scene_contents.h.

impeller/aiks/canvas.cc, impeller/aiks/canvas.h, impeller/aiks/paint.cc, impeller/aiks/paint.h, impeller/aiks/paint_pass_delegate.cc, impeller/entity/contents/filters/filter_contents.cc, impeller/entity/contents/filters/filter_contents.h, impeller/entity/contents/filters/inputs/filter_contents_filter_input.cc, impeller/entity/contents/filters/inputs/filter_contents_filter_input.h, impeller/entity/contents/filters/inputs/filter_input.cc, impeller/entity/contents/filters/inputs/filter_input.h, impeller/entity/contents/filters/matrix_filter_contents.cc, impeller/entity/contents/filters/matrix_filter_contents.h, impeller/entity/entity.h, impeller/entity/entity_pass.cc, impeller/entity/entity_pass.h
Resolves https://github.com/flutter/flutter/issues/134681.
For the various places where we track if a rendered entity is a subpass or not. After landing this, I think the next winning move is to make this an Entity field and remove the `SetRenderingMode` junk from the filter graph. That refactor is a bit more risky, so I plan to do that separately.
=> [Impeller] Add Entity::RenderingMode enum.

shell/platform/windows/flutter_windows_engine_unittests.cc, shell/platform/windows/windows_lifecycle_manager.cc, shell/platform/windows/windows_lifecycle_manager.h
Handle the close messages from non-Flutter windows similarly to how we handle our own, for graceful app exit purposes.
https://github.com/flutter/flutter/issues/131497
[CLA]: …
=> Handle external window's `WM_CLOSE` in lifecycle manager

.ci.yaml, ci/builders/standalone/linux_android_emulator.json, ci/builders/standalone/linux_benchmarks.json
Part of https://github.com/flutter/flutter/issues/132701.
=> Switch goma to reclient fro standalone targets

lib/ui/compositing.dart, lib/ui/geometry.dart, lib/ui/painting.dart, lib/ui/semantics.dart, lib/ui/text.dart
The `@pragma('vm:entry-point')` annotation serves as an annotation telling our AOT compiler that the member is needed and cannot be tree-shaken because it may be accessed from the outside (i.e. C++).
There are seemingly entry-point annotations on members that aren't actually used from C++.
=> We remove the annotation from those members in this CL.
=> Remove @pragma('vm:entry-point') annotations on members that aren't accessed from C++

ci/builders/linux_web_engine.json, ci/builders/mac_clang_tidy.json, ci/builders/mac_clang_tidy_presubmit.json
We recently upgraded a bot in the try pool to macOS 13 and I noticed a couple of tests have leaked through to it and we're not ready for tests to run on macOS 13 yet. …
=> Set tests to run on macOS 12

shell/common/animator.cc
Minor changes that reduce unnecessary Dart_TimelineGetMicros calls. …
=> Reduce unnecessary Dart_TimelineGetMicros call

impeller/renderer/backend/vulkan/blit_command_vk_unittests.cc, impeller/renderer/backend/vulkan/command_encoder_vk_unittests.cc, impeller/renderer/backend/vulkan/context_vk_unittests.cc, impeller/renderer/backend/vulkan/pass_bindings_cache_unittests.cc, impeller/renderer/backend/vulkan/test/mock_vulkan.cc, impeller/renderer/backend/vulkan/test/mock_vulkan.h, impeller/renderer/backend/vulkan/test/mock_vulkan_unittests.cc
This allows us to have better control over the mock context and allows us to test situations like having the validations available, versus not available. …
=> [Impeller] Introduce mock vulkan context builder

lib/web_ui/skwasm/image.cpp, shell/common/rasterizer.cc, shell/gpu/gpu_surface_metal_skia.mm, shell/platform/darwin/graphics/FlutterDarwinExternalTextureMetal.mm, shell/platform/embedder/embedder.cc, shell/platform/embedder/tests/embedder_metal_unittests.mm, shell/platform/embedder/tests/embedder_test_backingstore_producer.cc, testing/test_metal_surface_impl.mm
Skia's Graphite and Ganesh backend coalesced two enums regarding mipmaps into one and deprecated the public Ganesh version. This migrates Flutter to use the preferred type.
No functional changes expected. See also https://skia-review.googlesource.com/c/skia/+/753567 …
=> Migrate GrMipmapped->skgpu::Mipmapped

testing/run_tests.py
This PR changes run_tests.py to use the python logging library to report results instead of direct prints or writes to stdout/stderr. This change simplifies adding a `--quiet` flag that causes the script to only generate output if a log is emitted at WARNING or above.
Overall this is a bit of progress toward landing something like https://github.com/flutter/engine/pull/45595
=> Adds a --quiet flag to run_tests.py

impeller/entity/render_target_cache.cc, impeller/entity/render_target_cache_unittests.cc
Otherwise we'll null de-ref when trying to create a texture with the same descriptor later on.
=> [Impeller] dont cache failed render target allocations.

impeller/aiks/aiks_unittests.cc, impeller/display_list/dl_dispatcher.cc, impeller/display_list/dl_unittests.cc
Fixes https://github.com/flutter/flutter/issues/134816.
---
Confirmed this only happens when utilizing `DisplayListBuilder`. Consider:
```cc
TEST_P(DisplayListTest, CanDrawAnOpenPath) {
flutter::DisplayListBuilder builder;
flutter::DlPaint paint;
paint.setColor(flutter::DlColor::kRed());
paint.setDrawStyle(flutter::DlDrawStyle::kStroke);
paint.setStrokeWidth(10);
builder.Translate(300, 300);
// Move to (50, 50) and draw lines from:
// 1. (50, height)
// 2. (width, height)
// 3. (width, 50)
SkPath path;
path.moveTo(50, 50);
path.lineTo(50, 100);
path.lineTo(100, 100);
path.lineTo(100, 50);
builder.DrawPath(path, paint);
ASSERT_TRUE(OpenPlaygroundHere(builder.Build()));
}
```
---
The bug is in `dl_dispatcher.cc`:
```cc
// |flutter::DlOpReceiver|
void DlDispatcher::drawPath(const SkPath& …
```
=> Do not convert an open path to a closed rect.

impeller/playground/backend/vulkan/playground_impl_vk.cc, testing/run_tests.py
Closes https://github.com/flutter/flutter/issues/133708.
Will track why it's (a) blank and (b) times out in async presentation in https://github.com/flutter/flutter/issues/134852.
=> Add a single MacOS+Vulkan+SwiftShader CI test

shell/platform/darwin/ios/framework/Source/FlutterUndoManagerPlugin.mm, shell/platform/darwin/ios/framework/Source/FlutterUndoManagerPluginTest.mm
Fixes https://github.com/flutter/flutter/issues/133424
The `-[TextInputDelegate selectionDidChange:]` call actually triggers some unwanted keyboard NLP actions that generate a bunch of candidates and automatically accept the first candidate. This causes `-[UITextInput setMarkedText:selection]` to be called with the first candidate and that inserts extraneous characters after the user types certain characters on the iPad software keyboard. …
=> [iOS] Remove selectionDidChange call in UndoManager

ci/builders/mac_ios_engine.json, sky/tools/create_full_ios_framework.py
Generates the fat framework for extension safe variants and add them to the code sign list.
Also reverts part of https://github.com/flutter/engine/pull/45664 where the variants are uploaded in separate archive. Now with this change, the extension safe is inside a "extension_safe" folder under existing archive. 
fixes https://github.com/flutter/flutter/issues/124291
The destination folder after this change:
- An extension_safe folder is added, which includes the extension safe Flutter.frameworks and dsym
- The artifacts.zip now includes the `extension_safe` except the dysm
- A extension_safe_Flutter.dsym.zip is created (under ios/release/) , which includes the extension_safe/Flutter.dsym
[Contributor …
=> [ios] use python script to generate extension safe frameworks and code sign them

shell/platform/android/hardware_buffer_external_texture.cc, shell/platform/android/io/flutter/embedding/engine/renderer/FlutterRenderer.java, shell/platform/android/io/flutter/plugin/platform/ImageReaderPlatformViewRenderTarget.java
- Fix a missing Image close in an error path.
- Ensure we close the Image when the TextureEntry is finalized.
- Fix an inconsistency in the maxImages when running on Android < 33.
- Wrap acquireLatestImage in a try block and return a null image instead of crashing the application.
=> Tighten up ImageReaderPlatformViewRenderTarget code

shell/platform/android/io/flutter/plugin/platform/PlatformViewsController.java
Necessary to unblock the GPay release
=> Disable HardwareBuffer backed Platform Views temporarily

ci/builders/mac_ios_engine.json, sky/tools/create_full_ios_framework.py
Reverts flutter/engine#45781
Issue with engine roll https://github.com/flutter/flutter/pull/134964.
We need to update the conductor and performa manual roll.
We also need to remove the Flutter.framework from the artifact.zip
=> Revert "[ios] use python script to generate extension safe frameworks and code sign them"

DEPS, ci/licenses_golden/excluded_files, shell/platform/windows/angle_surface_manager.cc, shell/platform/windows/flutter_windows_engine.h, shell/platform/windows/flutter_windows_view.cc, shell/platform/windows/flutter_windows_view_unittests.cc
This also reverts the ANGLE roll (for which the original fix was landed) to 48e2c605adcd5bcc1622b18f357c7a73ebfb3543.
fixes: https://github.com/flutter/flutter/issues/134262
This reverts commit 708d82dc8a95a58c0f44b5c5e6758048aeff192e. …
=> Revert "[Windows] Update vsync on raster thread (#45310)"

impeller/typographer/backends/skia/typographer_context_skia.cc
The earlier limit of 4096u was pessimistically small on some backends and too big on others (like older versions of OpenGL ES). The former would stop glpyhs from rendering when they got sufficiently large or numerous. The latter would cause errors on texture allocation.
The full fix is tracked in https://github.com/flutter/flutter/issues/133092
=> [Impeller] Respect max supported texture size when allocating glyph atlas texture.

impeller/renderer/backend/vulkan/command_pool_vk_unittests.cc
Fixes https://github.com/flutter/flutter/issues/134982.
I could never reproduce the flakes locally, but this should prevent `pool1 == pool2`.
=> [Impeller] Hold the CommandPoolVK at a higher scope.

impeller/typographer/backends/stb/typographer_context_stb.cc
Gets rid of the hardcoded 2048 px size.
Followup from review comment left unaddressed in https://github.com/flutter/engine/pull/45992.
Missing this will be less easy after https://github.com/flutter/flutter/issues/133029.
=> [Impeller] Fix STB backend to account for max texture sizes.

display_list/skia/dl_sk_paint_dispatcher.h, display_list/skia/dl_sk_types.h
Ran into compile errors when refactoring Skia's #includes. This addresses those …
=> Add more missing Skia #includes

lib/web_ui/lib/src/engine/canvaskit/canvaskit_api.dart, lib/web_ui/lib/src/engine/dom.dart, lib/web_ui/lib/src/engine/skwasm/skwasm_impl/codecs.dart, lib/web_ui/lib/src/engine/skwasm/skwasm_impl/renderer.dart, lib/web_ui/test/engine/scene_view_test.dart, lib/web_ui/test/ui/image_golden_test.dart
Instead of doing `as JSAny` for DOM objects that are defined in static JS interop, let's make them `implements JSObject`?
cc @eyebrowsoffire @srujzs thoughts?
=> [web] DOM objects implement JS object

shell/platform/darwin/macos/framework/Source/FlutterKeyboardManager.mm, shell/platform/darwin/macos/framework/Source/KeyCodeMap.g.mm, shell/platform/darwin/macos/framework/Source/KeyCodeMap_Internal.h
This is required to eventually land https://github.com/flutter/flutter/issues/134969 (lint header files).
=> Rename `layoutGoals` to `kLayoutGoals` to enforce lints on headers.

testing/scenario_app/ios/Scenarios/Scenarios/AppDelegate.m, testing/scenario_app/ios/Scenarios/ScenariosUITests/BogusFontTextTest.m, testing/scenario_app/ios/Scenarios/ScenariosUITests/GoldenImage.h, testing/scenario_app/ios/Scenarios/ScenariosUITests/GoldenImage.m, testing/scenario_app/ios/Scenarios/ScenariosUITests/GoldenPlatformViewTests.h, testing/scenario_app/ios/Scenarios/ScenariosUITests/GoldenPlatformViewTests.m, testing/scenario_app/ios/Scenarios/ScenariosUITests/GoldenTestManager.h, testing/scenario_app/ios/Scenarios/ScenariosUITests/GoldenTestManager.m, testing/scenario_app/ios/Scenarios/ScenariosUITests/PlatformViewUITests.m, testing/scenario_app/ios/Scenarios/ScenariosUITests/SpawnEngineTest.m
TwoPlatformViewsWithOtherBackDropFilterTests is failing on macOS 13 with the same simulator version used in macOS 12. The image diff looks identical and slightly above the threshold. This PR adjusts the threshold for this test temporarily so our CI can run on both macOS 13 and 12. This change can be reverted when we move all our CI to macOS 13
Fixes https://github.com/flutter/flutter/issues/134740 …
=> [ios]Adjust golden test threshold for TwoPlatformViewsWithOtherBackDropFilterTests based on current macOS version

shell/platform/darwin/macos/framework/Headers/FlutterEngine.h, shell/platform/darwin/macos/framework/Headers/FlutterPluginRegistrarMacOS.h
Partial work towards https://github.com/flutter/flutter/issues/134969.
=> Add TODO(name) to comply with Clang Tidy.

lib/web_ui/lib/src/engine/js_interop/js_loader.dart
JSObject will have a factory constructor to create an object literal, so you can't extend it as it will no longer have a generative constructor (@staticInterop types can't have generative constructors).
=> Implement JSObject instead of extending

analysis_options.yaml, ci/bin/format.dart, lib/ui/hooks.dart, lib/web_ui/test/canvaskit/surface_test.dart, lib/web_ui/test/engine/pointer_binding_test.dart, testing/scenario_app/bin/utils/logs.dart
Avoids that dynamic accidentally sneaks in, see https://dart.dev/tools/analysis#enabling-additional-type-checks
=> Enable strict-inference

testing/scenario_app/ios/Scenarios/Scenarios/AppDelegate.m
The parent view controller of FlutterViewController in `non_full_screen_flutter_view_platform_view` does not explicitly set the status bar hidden. iOS 17 will show the status bar causing the golden to be no deterministic. 
Part of https://github.com/flutter/flutter/issues/133207
[testing …
=> [ios] scenario test make parent view controller hide status bar

lib/ui/painting/image_encoding.cc, lib/ui/painting/image_encoding.h, lib/ui/painting/image_encoding_unittests.cc
fixes https://github.com/flutter/flutter/issues/133942
This is current blocked on the skia bug: https://g-issues.skia.org/issues/300986800
Depends on skia fix: https://skia-review.googlesource.com/c/skia/+/757816 …
=> [Impeller] Adds unit test to make sure we can encode bgr101010xr to png.

shell/platform/darwin/ios/framework/Source/FlutterView.mm
fixes https://github.com/flutter/flutter/issues/135033 …
=> Made the warning about downgrading wide gamut happen at the correct time

lib/web_ui/skwasm/library_skwasm_support.js, lib/web_ui/test/ui/image_golden_test.dart
We need to make sure to add objects to the transfer list when we send them across the ui thread/web worker boundary. Otherwise, they get copied, which is very expensive.
On my M1 MacBook Pro, I took measurements of scrolling in the material 3 demo. Before this change, the work on the web worker thread was taking about 25-40ms per frame. After the change, it's around 2ms.
=> Properly transfer objects between the main thread and web worker.

shell/platform/darwin/ios/framework/Source/FlutterDartProject.mm
fixes https://github.com/flutter/flutter/issues/133015 …
=> [Impeller] adds hardware gate for wide gamut

impeller/renderer/backend/vulkan/pipeline_library_vk.cc, impeller/renderer/renderer_unittests.cc
Vulkan validation was tripping on the fact that renderer tests were rendering to the root render pass. This root render pass doesn't contain a stencil buffer. However, `MakeDefaultPipelineDescriptor` assumes a stencil and color attachment. The other backends are resilient to this mismatch since there is no compat render pass created upfront. But Vulkan was sad. This should only happen in the low level tests. In the higher levels of the framework, we have variants that make sure there is a pipeline pass and render pass compatibility.
Fixes validations of the kind:
```
--- Vulkan Debug Report  ----------------------------------------
|                Severity: Error
|                    Type: { Validation }
|                 ID Name: VUID-vkCmdDraw-renderPass-02684
|               ID …
```
=> [Impeller] Fix validation errors in RendererTest.

fml/cpu_affinity.cc, fml/cpu_affinity.h, fml/cpu_affinity_unittests.cc, fml/platform/android/cpu_affinity.cc, fml/platform/android/cpu_affinity.h, impeller/renderer/backend/vulkan/context_vk.cc, impeller/renderer/backend/vulkan/fence_waiter_vk.cc, impeller/renderer/backend/vulkan/resource_manager_vk.cc, runtime/dart_vm.cc, shell/platform/android/android_shell_holder.cc
Runs the waiter threads with efficiency affinity and the worker thread with "not performance" affinity.
=> [Impeller] Affinity adjustments for Vulkan backend.

impeller/renderer/backend/vulkan/texture_vk.cc
This shows up when we try to set the contents of a depth of stencil image. The aspect was assumed to be color only because typical Impeller workloads have device-transient depth and stencil images. But the "stencil mask" test apparently does set the context directly. Besides, this is perfectly valid usage. This makes Vulkan resilient to said usage.
=> [Impeller] Fix validation error about incorrect aspect on buffer to texture copies.

impeller/aiks/aiks_unittests.cc, impeller/entity/entity_pass.cc
Fix for https://github.com/flutter/flutter/issues/135053.
We already duck out of the Entity absorbing part of the optimization, but we also need to duck here when computing clear colors, otherwise we end up double-applying the effect of clearing entities at the beginning of a pass in some cases.
Wondrous with all fixes applied:
https://github.com/flutter/engine/assets/919017/37b49b77-b0ec-42d4-964a-c61b9a2cca8f
=> [Impeller] Use BlackTransparent clear color when backdrop filters are present.

impeller/aiks/aiks_unittests.cc, impeller/entity/entity_pass.cc
Fix for https://github.com/flutter/flutter/issues/135053.
I'm going to try and optimize out this case later, since Wondrous is inadvertently paying for a backdrop filter that contributes nothing to the final image.
Wondrous with all fixes applied:
https://github.com/flutter/engine/assets/919017/37b49b77-b0ec-42d4-964a-c61b9a2cca8f
=> [Impeller] Ensure that reused textures are cleared before getting sampled by backdrop textures

ci/builders/mac_ios_engine.json, sky/tools/create_full_ios_framework.py
Relands https://github.com/flutter/engine/pull/45781
The Flutter.framework and the sim folders are mistakenly added to the artifact, this PR removed those files along with re-landing the original changes 
https://github.com/flutter/flutter/pull/134966 should pass with this change.  …
=> [ios] Reland "[ios] use python script to generate extension safe frameworks and code sign them" #46004"

.clang-tidy, common/graphics/texture.cc, common/graphics/texture.h, display_list/display_list.h, display_list/dl_canvas.h, display_list/geometry/dl_rtree.cc, display_list/geometry/dl_rtree.h, display_list/image/dl_image.h, display_list/image/dl_image_skia.h, fml/base32.h, fml/endianness.h, fml/math.h, fml/math_unittests.cc, fml/memory/ref_ptr.h, fml/message_loop_task_queues.cc, fml/message_loop_task_queues.h, fml/message_loop_task_queues_unittests.cc, fml/platform/darwin/scoped_block.h, shell/platform/darwin/ios/framework/Source/FlutterViewController.mm, shell/platform/darwin/ios/framework/Source/platform_message_response_darwin.mm, shell/platform/darwin/ios/platform_message_handler_ios.mm
These are all self-contained, so I bundled them all together.
All fixes are generated by `clang-tidy --fix`, and manual search/replace if that wasn't sufficient.
=> Make a variety of low-impact Clang tidy fixes.

shell/platform/darwin/common/framework/Source/FlutterNSBundleUtils.h, shell/platform/darwin/common/framework/Source/FlutterNSBundleUtils.mm, shell/platform/darwin/ios/framework/Source/FlutterDartProject.mm, shell/platform/darwin/ios/framework/Source/FlutterDartProjectTest.mm
In https://github.com/flutter/engine/commit/9446392af6a26a715c6db50a56b23d46c141d834, I refactored the assetsPath to use NSURL. It turns out that when the app bundle is not loaded (during launching app exgtension), the assetURL will return nil using the `URLForResource`, but the `pathForResource` successfully returns the raw path.
This PR reverts back to the raw path solution.
part of https://github.com/flutter/flutter/issues/124287 …
=> [ios] fix asset url not found when loading app extension

impeller/base/thread.h, impeller/base/version.h, impeller/geometry/color.h, impeller/geometry/matrix.h, impeller/golden_tests/metal_screenshot.h, impeller/golden_tests/metal_screenshot.mm, impeller/renderer/pool.h, impeller/scene/importer/importer_unittests.cc
These are all self-contained, so I bundled them all together.
All fixes are generated by `clang-tidy --fix`, and manual search/replace if that wasn't sufficient.
=> Make a variety of low-impact Clang tidy fixes in Impeller.

display_list/effects/dl_image_filter.h, display_list/effects/dl_mask_filter.h, display_list/effects/dl_path_effect.h
Closes https://github.com/flutter/flutter/issues/135064.
Closes https://github.com/flutter/flutter/issues/135063.
Closes https://github.com/flutter/flutter/issues/135062.
I bundled a few of these together because they didn't have side-effects across the repo (self-contained).
**NOTE**: All changes were auto-generated by `clang-tidy --fix`.
=> Make `dl_(image|mask|path)_(filter|effect).h` tidy!

display_list/effects/dl_color_filter.cc, display_list/effects/dl_color_filter.h, display_list/effects/dl_color_filter_unittests.cc, display_list/effects/dl_color_source.h, display_list/testing/dl_rendering_unittests.cc, display_list/testing/dl_test_snippets.cc, flow/layers/color_filter_layer_unittests.cc, impeller/display_list/dl_unittests.cc, lib/ui/painting/color_filter.cc
Closes https://github.com/flutter/flutter/issues/135060.
Closes https://github.com/flutter/flutter/issues/135061.
Bundled these two together as they are similar. Pretty boring `instance` -> `kInstance`, and `explicit`/`std::move`.
=> Make `dl_color_(filter|source)` tidy.

flow/layers/clip_rrect_layer_unittests.cc, flow/layers/clip_shape_layer.h, flow/layers/layer.h, flow/layers/layer_tree.cc, flow/testing/layer_test.h
Fixes https://github.com/flutter/flutter/issues/134705
The save layer is observable so it isn't safe to optimize out.
=> [Impeller] Remove removal of save layer from clip.

display_list/dl_paint.cc, display_list/dl_paint.h
Closes https://github.com/flutter/flutter/issues/135058.
All fixes are generated by `clang-tidy --fix`, and manual search/replace if that wasn't sufficient.
=> Tidy up `DlPaint` and friends.

impeller/renderer/backend/vulkan/surface_context_vk.cc, impeller/renderer/backend/vulkan/swapchain_impl_vk.cc
I'm not able to reproduce most validation errors in the macrobenchmark app with this change. THe real fix seems to be to track this last cmd buffer but I'm struggling to find a way to do this.
=> [Impeller] temp work around for cmd pool validation issues.

lib/ui/fixtures/ui_test.dart, lib/ui/platform_dispatcher.dart, lib/ui/window.dart, lib/ui/window/platform_configuration_unittests.cc, shell/common/shell.cc, shell/common/shell.h, testing/dart/platform_view_test.dart
This PR relands #45300 which was reverted in https://github.com/flutter/engine/pull/45525 due to hanging on a windows startup test. The culprit test still calls `FlutterView.render` in the illegal way, which is ignored, causing no frame being ever produced. This has been fixed in https://github.com/flutter/flutter/pull/134245. I've also searched through the framework repo for `render(` to ensure there are no other cases. …
=> Reland: Enforce the rule of calling FlutterView.Render (#45300)

display_list/benchmarking/dl_benchmarks.h, display_list/benchmarking/dl_complexity_gl.h, display_list/benchmarking/dl_complexity_helper.h, display_list/benchmarking/dl_complexity_metal.h, display_list/dl_op_flags.cc, display_list/dl_op_flags.h, display_list/dl_op_records.h, display_list/effects/dl_image_filter.h, display_list/skia/dl_sk_paint_dispatcher.h, display_list/testing/dl_rendering_unittests.cc, display_list/testing/dl_test_equality.h, display_list/testing/dl_test_surface_gl.h, display_list/testing/dl_test_surface_metal.cc, display_list/testing/dl_test_surface_metal.h, display_list/testing/dl_test_surface_provider.cc, display_list/testing/dl_test_surface_provider.h, display_list/testing/dl_test_surface_software.h, display_list/utils/dl_matrix_clip_tracker.h, fml/log_level.h, fml/memory/ref_counted_internal.h, lib/ui/painting/image.h, testing/display_list_testing.h, testing/test_metal_context.h, testing/test_metal_context.mm
More work towards https://github.com/flutter/flutter/issues/134969.
I decided not to touch the `LOG_X` variables since they are just used in macro expansion.
=> More Clang Tidy --fix[es] to header files

impeller/renderer/backend/vulkan/command_pool_vk.cc, impeller/renderer/backend/vulkan/surface_context_vk.cc, impeller/renderer/backend/vulkan/swapchain_impl_vk.cc
Closes https://github.com/flutter/flutter/issues/135086.
Reverts https://github.com/flutter/engine/pull/46131.
This PR bundles together 3 changes that removes all validation errors on the `macrobenchmark` apps I could manually find:
1. Reverts https://github.com/flutter/engine/pull/46131, which did not fix the original issue.
2. Added `kResetOnBackgroundThread = false`, which drops performance benefits, but doesn't cause threading issues.
3. Stop tracking `image` for Swapchain presentation (was hitting Vulkan assertion errors about acquired images).
/cc @gaaclarke I'd love to talk about how we could run the macrobenchmarks app on CI, with validation errors, after landing.
=> Revert #46131, don't store `vkImage`, reset `vkComandPool` synchronously

shell/platform/darwin/ios/framework/Source/FlutterEnginePlatformViewTest.mm, shell/platform/darwin/ios/framework/Source/FlutterPlatformViewsTest.mm, shell/platform/darwin/ios/framework/Source/accessibility_bridge_test.mm, shell/platform/darwin/ios/ios_context.mm
Fixes https://github.com/flutter/flutter/issues/127408
This is also related to https://github.com/flutter/engine/pull/44346, which made it fatal to explicitly request both impeller and the software backend.
Before landing this, we need to update some google internal tests that end up in this state to explicitly request Skia (or to get into a mode where they can actually use metal).
=> [Impeller] fail if software backend is chosen and Impeller is enabled on iOS

shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm, shell/platform/darwin/ios/framework/Source/FlutterTextInputPluginTest.mm
This iOS PR disables spellchecking when auto correction is disabled.
Fixes https://github.com/flutter/flutter/issues/134881.
Adds 1 test.
=> [iOS] Disable spelling corrections when auto correction is disabled

DEPS
A partial roll of the Dart SDK removed a manually added third-party dependency on package tar, since the roll was to an earlier SDK version that didn't have the new package.
Relanding the package addition from
https://github.com/flutter/engine/pull/46140
that was partially reverted by autoroll
https://github.com/flutter/engine/pull/46176
This should not happen again, because the next Dart SDK dev version should include the new package.
Manual addition of new packages from Dart SDK DEPS to Flutter engine DEPS is needed because the autoroller cannot add new packages.  An early signal that this needs done is failures on the monorepo builders that build the main branches of Dart SDK, Flutter engine, and Flutter framework together. This PR will fix those failures, and allow the next autoroll …
=> Re-add package tar to DEPS

impeller/entity/entity_pass.cc
Resolves https://github.com/flutter/flutter/issues/134775.
Before:
After:
=> [Impeller] Incorporate backdrop filters in subpass coverage.

impeller/aiks/aiks_unittests.cc, impeller/display_list/dl_dispatcher.cc
We were going down this branch for all closed paths, but we should only be taking it for closed paths that are also rectangles.
=> [Impeller] dont treat non-rects as rects.

shell/platform/darwin/ios/framework/Source/FlutterEnginePlatformViewTest.mm, shell/platform/darwin/ios/framework/Source/FlutterPlatformViewsTest.mm, shell/platform/darwin/ios/framework/Source/accessibility_bridge_test.mm, shell/platform/darwin/ios/ios_context.mm
Reverts flutter/engine#46124
See b/301660190. This is breaking a few Google iOS tests due to test bed configurations. We'll need more time to investigate fixing those tests before relanding.
=> Revert "[Impeller] fail if software backend is chosen and Impeller is enabled on iOS"

shell/platform/darwin/common/framework/Source/FlutterNSBundleUtils.mm, shell/platform/darwin/ios/framework/Source/FlutterDartProjectTest.mm
When reverting the default asset url code, the old "flutter_assets" path was also copied in https://github.com/flutter/engine/pull/46073
This PR uses the correct URL. Although I'm unsure why the video player test passed before my change for the asset urls. 
I'm going to take another look at it but meanwhile this PR can unblock the roll once rolled into the framework.
fixes of https://github.com/flutter/flutter/issues/135323 …
=> [ios] Fix default assets url

ci/builders/linux_android_debug_engine.json, ci/builders/linux_fuchsia.json, ci/builders/linux_host_engine.json, ci/builders/linux_unopt.json, ci/builders/mac_android_aot_engine.json, ci/builders/mac_clang_tidy.json, ci/builders/mac_host_engine.json, ci/builders/mac_unopt.json, ci/builders/standalone/linux_android_emulator.json, ci/builders/standalone/linux_license.json, ci/builders/standalone/windows_unopt.json, ci/builders/windows_host_engine.json, testing/run_tests.py, tools/pkg/engine_repo_tools/test/engine_repo_tools_test.dart
This PR creates a new test type for `run_tests.py` called `dart-host`. The tests remaining under the `dart` type are tests that run in `flutter_tester`. The `dart-host` tests run in the Dart CLI. This allows `run_tests.py` to be simplified a bit, and while doing this I spotted a couple of mistakes that were causing some tests not to run.
This PR also makes a couple of small style fixes to the build config json files, converting tabs to spaces, and moving some "script" fields before the "parameters" fields.
=> In run_tests.py, separate Dart package unit tests from other tests

.ci.yaml, ci/builders/linux_clang_tidy.json, ci/builders/linux_clang_tidy_presubmit.json
Part of https://github.com/flutter/flutter/issues/132701
=> Switch goma to reclient for Linux clang_tidy targets

shell/platform/darwin/ios/framework/Source/FlutterEngine.mm
Hint to the CPU scheduler which of our threads are more important. This change should result in more stable rendering times on CI, but likely doesn't have any other observable effects.
=> [Engine] use QoS classes in iOS engine.

shell/platform/fuchsia/dart_runner/fidl/echo.fidl
This is part of a language change in FIDL. This should have no effect.
See: [https://fxbug.dev/88366](https://fxbug.dev/88366)
=> fuchsia: Update FIDL for unknown interactions

impeller/aiks/aiks_unittests.cc, impeller/entity/geometry/vertices_geometry.cc
Fixes https://github.com/flutter/flutter/issues/135441
This check was lost in some refactor, I added a test for it.
=> [Impeller] fallback to position data if texture coordinates are undefined.

ci/builders/linux_android_aot_engine.json, ci/builders/linux_android_debug_engine.json, ci/builders/linux_arm_host_engine.json, ci/builders/linux_fuchsia.json, ci/builders/linux_host_desktop_engine.json, ci/builders/linux_host_engine.json
This is a revert of targets that generate artifacts for framework:
```
Linux linux_fuchsia
Linux linux_android_aot_engine
Linux linux_android_debug_engine
Linux linux_arm_host_engine
Linux linux_host_desktop_engine
Linux linux_host_engine
```
=> Restore goma from rbe before 3.16 branching

impeller/aiks/aiks_unittests.cc, impeller/entity/contents/solid_rrect_blur_contents.cc, impeller/entity/contents/solid_rrect_blur_contents.h
Resolves https://github.com/flutter/flutter/issues/133354.
Fixes and speeds up blended rrect blurs.
Before:
After:
=> [Impeller] Support applying color filters on the CPU for the RRect fast path.

.ci.yaml, ci/builders/README.md, ci/builders/linux_fuchsia.json, tools/fuchsia/build_fuchsia_artifacts.py, tools/fuchsia/merge_and_upload_debug_symbols.py
Prepares fuchsia scripts to work correctly when both v1 and v2 of the fuchsia build are running in their respective environments.
Bug: https://github.com/flutter/flutter/issues/126461
Bug: https://github.com/flutter/flutter/issues/135189 …
=> Prepare fuchsia script to coexist with v1 and v2 of fuchsia builders.

display_list/display_list_unittests.cc, display_list/dl_builder.cc, display_list/testing/dl_rendering_unittests.cc, display_list/utils/dl_matrix_clip_tracker.cc, display_list/utils/dl_matrix_clip_tracker.h
Cherry pick
…r (#43787)
When a saveLayer is rendered with an ImageFilter that modifies the bounds of the rendered pixels, and some of the content of that saveLayer did not intersect the clip, but the filtered output of that content did intersect the clip, we might not accumulate the bounds of those rendering operations into the DisplayList bounds.
This bug was not encountered during practical testing, but showed up on some testing with the new NOP culling code.
For now, this bug only affects the accuracy of the reported bounds of the DisplayList, but that can affect raster caching and potentially the layer culling done in the LayerTree. It might also affect the accuracy of the RTree associated with the DisplayList, which would only show up in rare circumstances when the indicated …
=> [CP]  Imagefilter blur

impeller/aiks/aiks_unittests.cc, impeller/entity/contents/content_context.cc, impeller/entity/contents/content_context.h, impeller/entity/contents/solid_rrect_blur_contents.cc
fixes: https://github.com/flutter/flutter/issues/132849
I decided to mimic skia's blend function for clear only in the case for blurred rounded rects since that fixes the listed issue.  I'm not sure if there are are other cases where we'd want this behavior.  I've added golden tests for the other clear cases too to make sure we didn't break them. …
=> [Impeller] fixes behavior for blurred rounded rect clear

lib/web_ui/lib/src/engine/canvaskit/util.dart
Use the DirectionalLight_Shadow flag when drawing shadows in CanvasKit. This fixes bugs with drawing shadows in tests with different device pixel ratios. …
=> [canvaskit] Use DirectionalLight_Shadow flag for drawing shadows

shell/platform/android/io/flutter/plugin/editing/TextInputPlugin.java, shell/platform/android/test/io/flutter/plugin/editing/TextInputPluginTest.java
This PR fixes an issue where setting `TextField.enableSuggestions` to false was not honored on Android.
Several Android devices (Samsung) and/or IMEs (including GBoard) does not disabled suggestions when `InputType.TYPE_TEXT_FLAG_NO_SUGGESTIONS `flag is set. The common solution is to rely on the following flag:  ~~`InputType.TYPE_TEXT_VARIATION_PASSWORD`~~ `InputType.TYPE_TEXT_VARIATION_VISIBLE_PASSWORD`.
Reference:
- https://issuetracker.google.com/issues/36934423#comment4
- https://stackoverflow.com/questions/33148168/inputtype-type-text-flag-no-suggestions-in-samsung/33227237#33227237
- Existing comment on the codebase:
https://github.com/flutter/engine/blob/53430c7c96a3ef1fc78d63ea6b0c35e5ff46c45e/shell/platform/android/io/flutter/plugin/editing/TextInputPlugin.java#L270
Fixes …
=> [Android] Fix enableSuggestions set to false not honored

lib/gpu/lib/src/context.dart, lib/ui/experiments/gpu.dart
This prohibits other implementations of the class interface that can not act as native wrappers.
See https://github.com/flutter/flutter/issues/123756
=> Declare native wrapper classes in the GPU package as base classes

impeller/entity/geometry/fill_path_geometry.cc, impeller/geometry/geometry_benchmarks.cc, impeller/renderer/renderer_unittests.cc, impeller/tessellator/c/tessellator.cc, impeller/tessellator/tessellator.cc, impeller/tessellator/tessellator.h, impeller/tessellator/tessellator_unittests.cc
See example app in https://github.com/flutter/flutter/issues/135458
Because tessellation is generally nlogn best case (with allocation complexity as well), we can actually make it faster by breaking it into smaller pieces. For non zero fill modes, the contours can be tessellated individually without  losing fidelity.
In cases where this isn't possible, we need to check if we exceed the max uint16 index and fall back to no index buffer.
Fixes https://github.com/flutter/flutter/issues/135458
I Benchmarked signing my name.
worst raster time 3+ seconds. Visual glitches
worst raster time 30 ms, looks correct (though my signature is still wrong)
=> [Impeller] Fallback to no index buffer when tesselation count is large, split up nonZero contours.

shell/platform/windows/angle_surface_manager.cc, shell/platform/windows/angle_surface_manager.h, shell/platform/windows/flutter_windows_engine.cc, shell/platform/windows/flutter_windows_engine.h, shell/platform/windows/flutter_windows_view.cc, shell/platform/windows/flutter_windows_view_unittests.cc
This relands https://github.com/flutter/engine/pull/45310 to unblock the ANGLE roll with the fix for https://github.com/flutter/flutter/issues/134262.
If the Windows system compositor is enabled, the Windows embedder disables the swap interval so that presenting to a surface does not block until the v-blank. If the Windows system compositor is disabled (which is possible on Windows 7), the Windows embedder enables swap interval to prevent screen tearing.
Our current version of ANGLE allows making a GL context current on multiple threads. However, the latest version of ANGLE errors if a GL context is made current on multiple threads. This is causing the ANGLE roll to fail ([example](https://ci.chromium.org/ui/p/flutter/builders/try/Windows%20Engine%20Drone/203788/overview)).
The Windows …
=> [Windows] Improve logic to update swap intervals

impeller/renderer/backend/vulkan/command_pool_vk.cc, impeller/renderer/backend/vulkan/command_pool_vk.h, impeller/renderer/backend/vulkan/context_vk.cc, impeller/renderer/backend/vulkan/context_vk_unittests.cc
Vulkan requires that all objects created using a device be destroyed before the device is destroyed.  The CommandPoolRecyclerVK maintains a thread-local map of each context's currently active command pool. Before the context deletes the device, it must force cleanup of all such command pools associated with that context.
This PR reinstates a mechanism that was used prior to the refactoring that introduced command pool recycling.
=> [Impeller] Destroy all per-thread command pools tied to a context before deleting the context

lib/web_ui/lib/src/engine/canvaskit/layer.dart, lib/web_ui/test/ui/filters_test.dart
Fixes an issue seen in the "widgets.image_filter_matrix" golden here: https://flutter-gold.skia.org/search?crs=github&issue=135249&patchsets=3 …
=> [canvaskit] Do not double-apply ImageFilter transform to children

shell/platform/darwin/macos/framework/Source/FlutterViewController.mm, shell/platform/darwin/macos/framework/Source/FlutterViewControllerTest.mm
https://github.com/flutter/engine/pull/40706 added a duplicate `NSEvent (KeyEquivalentMarker)` category. This PR removes it. It also removes the call to `markAsKeyEquivalent` from `FlutterViewController`. That call is internal to `FlutterTextInputPlugin` and classes outside should not be calling it. …
=> [macOS] performKeyEquivalent cleanup

shell/platform/darwin/macos/framework/Source/FlutterViewController.mm, shell/platform/darwin/macos/framework/Source/FlutterViewControllerTest.mm
This broke some keyboard shortcut handling (e.g. cmd-a to select all).
This reverts commit 0087948c0f843c5d18952ec0b2fbb0ad12f54dc9. …
=> Revert "[macOS] performKeyEquivalent cleanup (#45946)"

shell/platform/darwin/macos/framework/Source/FlutterTextInputPlugin.h, shell/platform/darwin/macos/framework/Source/FlutterTextInputPlugin.mm, shell/platform/darwin/macos/framework/Source/FlutterTextInputPluginTest.mm
Fixes https://github.com/flutter/flutter/issues/135219
(formerly https://github.com/flutter/flutter/issues/128956) …
=> [macOS] FlutterTextInputPlugin should clip to bounds

shell/gpu/gpu_surface_gl_delegate.h, shell/platform/android/android_surface_gl_skia.cc, shell/platform/embedder/embedder.cc, shell/platform/embedder/fixtures/main.dart, shell/platform/embedder/tests/embedder_gl_unittests.cc
This PR fixes the `gl_populate_existing_damage` in embedder.cc, which currently returns an empty rectangle when a full repaint is needed. This leads to the `frame_damage` being considered empty in rasterizer.cc, causing incorrect partial repaint within Flutter when `gl_populate_existing_damage` is not provided by the embedder.
https://github.com/flutter/flutter/issues/119601
Add a new test. Also fixes damage calculation related tests in EmbedderTest by
* Use a new Dart embedder fixture entry point `render_gradient_retained` which retains the old layer to make sure layer tree diff happens.
* Add `latch.Wait()` after `SetGLPresentCallback` to make sure assertions have been executed.
* Make `existing_damage_rects` static since it should be valid after `populate_existing_damage` returns.
=> Fix damage calculation when not providing populate_existing_damage for gl embedder

shell/platform/embedder/embedder_surface_gl_impeller.cc
On Linux setting the EGL context from one thread, then setting from another thread will trigger a EGL_BAD_ACCESS error.  The resolution is to clear the context after use on the thread that set it.
https://github.com/flutter/flutter/issues/130619
=> [Impeller] Fix OpenGLES EGL_BAD_ACCESS due to context being current on multiple threads.

display_list/dl_canvas.h
Small performance tweak.
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-brea …
=> Removed unnecessary dynamic dispatch

shell/platform/darwin/macos/framework/Source/FlutterTextInputPlugin.h, shell/platform/darwin/macos/framework/Source/FlutterTextInputPlugin.mm, shell/platform/darwin/macos/framework/Source/FlutterTextInputPluginTest.mm
Fixes https://github.com/flutter/flutter/issues/134699
Because of NSTextInputContext API limitations it is not straightforward to determine whether `TextInputPlugin` has handled a text equivalent event or whether it should pass it on. Previously we marked all event  that didn't result in a TextInputClient action as unhandled, but that's does not work for arrow key events while the IME popover is active.
This PR will mark arrow keys event as handled if there is active composition.
[Tree …
=> [macOS] TextInputPlugin should mark navigation events in IME popover as handled

shell/platform/darwin/macos/framework/Source/FlutterViewController.mm, shell/platform/darwin/macos/framework/Source/FlutterViewControllerTest.mm
Fixes the issue in original PR where `FlutterViewWrapper` does not pass the key equivalent to subviews thus prevents `TextInputPlugin` from receiving it. Also adds a regression test for this scenario.
Note that key equivalent flow does not respect the regular responder chain. It is passed from root view to down to subviews and if unhandled will be forwarded to menus.
Original message: 
https://github.com/flutter/engine/pull/40706 added a duplicate `NSEvent (KeyEquivalentMarker)` category. This PR removes it. It also removes the call to `markAsKeyEquivalent` from `FlutterViewController`. That call is internal to `FlutterTextInputPlugin` and classes outside should not be calling it.
*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the …
=> Reland: [macOS] performKeyEquivalent cleanup

impeller/renderer/backend/gles/gles.h, impeller/renderer/backend/gles/proc_table_gles.h, impeller/renderer/backend/gles/render_pass_gles.cc, impeller/renderer/backend/gles/texture_gles.cc, impeller/renderer/backend/gles/texture_gles.h
Initial support _towards_ https://github.com/flutter/flutter/issues/130045.
This updates the `PROC_TABLE`, and adds (and supports) `Type::kRenderBufferMultisampled`.
The type remains unused in the actual engine, and will be in a follow-up PR once we like this one!
/cc @chinmaygarde
=> Add initial support for 4x MSAA in OpenGLES backend.

flow/layers/opacity_layer.cc, flow/layers/opacity_layer_unittests.cc
In https://github.com/flutter/flutter/issues/132849 it was found that rendering happens fine when this dcheck is removed. …
=> Remove opacity layer dcheck.

impeller/aiks/picture.cc, impeller/entity/contents/content_context.cc, impeller/renderer/render_target.cc
This was an experiment that didn't really pan out. Revert the changes to simplify rendering logic.
=> [Impeller] revert stencil config changes.

shell/platform/darwin/macos/framework/Source/FlutterTextInputPlugin.mm, shell/platform/darwin/macos/framework/Source/FlutterTextInputPluginTest.mm, shell/platform/darwin/macos/framework/Source/FlutterView.h, shell/platform/darwin/macos/framework/Source/FlutterView.mm, shell/platform/darwin/macos/framework/Source/FlutterViewController.mm, shell/platform/darwin/macos/framework/Source/FlutterViewTest.mm
Fixes https://github.com/flutter/flutter/issues/134906
Fixes https://github.com/flutter/flutter/issues/133832
This ensures that there are only two first responder widgets - `FlutterView` when text input is not active and `TextInputPlugin` when text input is active. The PR also prevents `FlutterView` stealing first responder status on mouse click events during text input.
Previously when `TextInputClient` resigned it made `nextResponder` the first responder, but that was incorrect - `nextResponder` being the superview (`FlutterViewWrapper`). …
=> [macOS] Ensure first responder is consistent during and after text input

impeller/aiks/aiks_unittests.cc, impeller/aiks/canvas.cc, impeller/aiks/color_filter.cc, impeller/aiks/color_filter.h, impeller/aiks/paint.cc, impeller/aiks/paint.h, impeller/display_list/dl_dispatcher.cc
Fixes https://github.com/flutter/flutter/issues/135699
To avoid the ugly complicated code for conditionally applying both colorfilters, make the dl dispatcher handle merging these filters together in a defined order. The original bug is caused by not checking for invert colors in a CPU fast path.
=> [Impeller] simplify invert colors flag by supporting composed color filters.

lib/web_ui/dev/test_dart2wasm.js, lib/web_ui/lib/src/engine/skwasm/skwasm_impl/raw/raw_image.dart, lib/web_ui/lib/src/engine/skwasm/skwasm_impl/raw/skwasm_module.dart, lib/web_ui/lib/src/engine/skwasm/skwasm_impl/surface.dart, web_sdk/sdk_rewriter.dart, web_sdk/test/sdk_rewriter_test.dart
Use the newly exposed functionality in `dart:_wasm` to fix up two different hacks we have:
1) When creating an image from an image source, use `wasm:import` instead of `@Native` and pass the image source directly as an externref. (Direct wasm binding instead of a JS interop shim, yay).
2) When binding the surface callback, previously we were wrapping the callback in a JS function, and then using `WebAssembly.Function` to create a wasm function wrapper around that. Now, we can create a `WasmFuncRef` that is a direct reference to a dart function and pass that over. Now there are no intermediary JavaScript layers when skwasm calls back to us, and we no longer are dependent on the type reflection flag in Chrome.
This fixes https://github.com/flutter/flutter/issues/134556
=> Use `dart:_wasm` constructs to avoid dependence on `WebAssembly.Function`

common/settings.h, shell/common/switches.cc, shell/common/switches.h, shell/common/switches_unittests.cc, shell/platform/android/io/flutter/embedding/engine/FlutterEngine.java, shell/platform/android/io/flutter/embedding/engine/FlutterJNI.java, shell/platform/android/io/flutter/embedding/engine/FlutterShellArgs.java, shell/platform/android/io/flutter/embedding/engine/loader/FlutterLoader.java, shell/platform/android/io/flutter/plugin/platform/PlatformViewsController.java, shell/platform/android/platform_view_android_jni_impl.cc
An internal customer is seeing flickering on some high FPS phones.
While we try and reproduce / gain more knowledge of this problem this PR adds a AndroidManifest.xml flag to disable their usage.
The boolean flag is:
```
"io.flutter.embedding.android.DisableImageReaderPlatformViews"
```
Adding the following to your manifest will disable their usage:
```
<meta-data
android:name="io.flutter.embedding.android.DisableImageReaderPlatformViews"
android:value="true" />
```
=> Add an AndroidManifest.xml flag to disable ImageReader backed Platform Views

impeller/aiks/aiks_unittests.cc, impeller/entity/entity_pass.cc
fixes: https://github.com/flutter/flutter/issues/135777
fixes: https://github.com/flutter/flutter/issues/135766
fixes: https://github.com/flutter/flutter/issues/135212
[CLA]: …
=> [Impeller] fixed subpass filter coverage with image filters

impeller/BUILD.gn, impeller/renderer/backend/gles/proc_table_gles.cc, impeller/renderer/backend/gles/proc_table_gles.h, impeller/tools/impeller.gni
Closes https://github.com/flutter/flutter/issues/135767.
=> [Impeller] Make some Open GL errors non-fatal, check in debug mode (not unopt).

impeller/renderer/backend/gles/context_gles.cc
These are failing with a GL_INVALID_OPERATION.
=> [Impeller] disable texture to texture blit in GLES.

impeller/aiks/aiks_unittests.cc, impeller/entity/contents/framebuffer_blend_contents.cc
Fixes b/303120488.
There's no need to use the `GetCoverageUVs` utility in this case. Correct usage here would require the geometry to match the coverage rectangle of the snapshot in pass space with no further transformations to the geometry.
We should just render the snapshot texture as-is with simple 0/1 UVs and the snapshot's transform.
Before:
https://github.com/flutter/engine/assets/919017/2908573e-b7cf-430f-9317-92c8aac6ade4
After:
https://github.com/flutter/engine/assets/919017/74901c9d-cb26-43c8-b963-a28bffbd5a44
=> [Impeller] Fix framebuffer blend UVs.

ci/licenses_golden/excluded_files, third_party/.clang-tidy
See https://github.com/flutter/flutter/issues/134969.
/cc @zanderso
=> Opt out `flutter/third_party/**` from clang-tidy checks explicitly.

impeller/aiks/canvas_recorder.h
Internal bug: b/303067268
https://github.com/flutter/engine/pull/46376 is causing a breakage to the internal engine build because of https://github.com/flutter/engine/blob/150d1b6ab51f34c07e21fc32ef76e4842edd4d04/impeller/aiks/canvas_recorder.h#L58-L62. Internally, we do not set `IMPELLER_TRACE_CANVAS`.
It looks like the cause is that the internal toolchain causes the `static_assert` to be compiled even though the template is not instantiated.
@chingjun helped me to figure out the following:
https://stackoverflow.com/questions/5246049/c11-static-assert-and-template-instantiation points us to the spec. In the later version (ISO/IEC 14882:2017(E)):
> The program is ill-formed, no diagnostic required, if ... no valid specialization can be generated for a template or a substatement of a …
=> [Impeller] Don't define `CanvasRecorder` if `IMPELLER_TRACE_CANVAS` is not set.

impeller/entity/contents/contents.h, impeller/entity/entity.h
Update the coverage docstrings to clarify which space the coordinates are given in. Up until now, I've been using the phrase "screen space" to convey that coverage is counted in framebuffer pixels and is unaffected by the subpass transform basis. But a more accurate way to describe this would be "pass space", since it counts pixels relative to the top left corner of the framebuffer that the Entity is being drawn to during rendering.
=> [Impeller] Clarify coverage space.

shell/platform/linux/fl_key_event.cc, shell/platform/linux/fl_scrolling_manager.cc, shell/platform/linux/fl_view.cc
This should have no effect on the current implementation, and will be one less thing needed when we migrate to GTK4.
=> Use GdkEvent methods to access values, direct access is removed in GTK4.

impeller/aiks/aiks_unittests.cc, impeller/entity/contents/filters/matrix_filter_contents.cc, impeller/entity/entity_pass.cc, impeller/entity/entity_pass.h
Resolves https://github.com/flutter/flutter/issues/135916.
Big credits to @gaaclarke for the repros and investigation around this.
Moves back to tracking clip coverage per-pass when not collapsing. This is especially important for SaveLayers with MatrixImageFilters, which can transform the rendered layer texture and thereby move elements inside or outside of existing parent clips.
This should have little to no performance impact, since we should already be generating correct minimal subpass textures based on correct subpass coverage computation.
Before:
https://github.com/flutter/engine/assets/919017/9284f055-bee1-40cd-8b7e-f478b00d01da
After:
https://github.com/flutter/engine/assets/919017/0fbd1f96-8920-472c-bb0e-4414187fc72d
=> [Impeller] Track clip coverage per-pass when not collapsing.

impeller/renderer/backend/gles/BUILD.gn, impeller/renderer/backend/gles/capabilities_gles.cc, impeller/renderer/backend/gles/capabilities_gles.h, impeller/renderer/backend/gles/context_gles.cc, impeller/renderer/backend/gles/context_gles.h, impeller/renderer/backend/gles/proc_table_gles.cc, impeller/renderer/backend/gles/proc_table_gles.h, impeller/renderer/backend/gles/test/capabilities_unittests.cc
From https://github.com/flutter/engine/pull/46585
For Framebuffer fetch and other changes we should refactor the CapabilitiesGLES into a regular capabilities.
=> [Impeller] Refactor CapabilitiesGLES into a Capabilties.

impeller/aiks/canvas.cc, impeller/display_list/dl_unittests.cc
Computing the bounds of an RRect can be really slow if you don't actually know that it is an RRect, and shows up in the traces for flutter gallery on wembly. This change should be semantically equivalent and is only an optimization to avoid recomputing the same value we already know.
=> [Impeller] Ensure known geometry has simple bounds computation.

flow/layers/performance_overlay_layer_unittests.cc, shell/common/base64.cc, shell/common/base64.h, shell/common/base64_unittests.cc, shell/common/rasterizer.cc, shell/common/shell.cc
As a follow-up to #46543, this adds a dedicated function to compute the size of the buffer needed to encode data using Base64 instead of calling the encode function with nullptr.
[CLA]: …
=> Add Base64::EncodedSize to tidy up allocations

impeller/entity/contents/atlas_contents.cc, impeller/entity/contents/filters/blend_filter_contents.cc, impeller/entity/contents/filters/morphology_filter_contents.cc, impeller/entity/shaders/blending/advanced_blend.glsl, impeller/entity/shaders/blending/porter_duff_blend.frag, impeller/entity/shaders/morphology_filter.frag, impeller/renderer/backend/gles/capabilities_gles.cc, impeller/renderer/backend/gles/capabilities_gles.h, impeller/renderer/backend/gles/context_gles.cc, impeller/renderer/backend/gles/gles.h, impeller/renderer/backend/gles/sampler_gles.cc, impeller/renderer/backend/gles/sampler_library_gles.cc, impeller/renderer/backend/gles/sampler_library_gles.h, impeller/renderer/backend/gles/test/capabilities_unittests.cc, impeller/renderer/backend/gles/test/mock_gles.cc, impeller/renderer/backend/gles/test/mock_gles.h, impeller/tools/malioc.json
fix https://github.com/flutter/flutter/issues/129358
=> [Impeller] Optionally support SamplerAddressMode::kDecal on the OpenGLES backend

ci/licenses_golden/licenses_flutter, display_list/testing/BUILD.gn, display_list/testing/dl_rendering_unittests.cc, display_list/testing/dl_test_surface_metal.cc, display_list/testing/dl_test_surface_metal.h, display_list/testing/dl_test_surface_provider.cc, display_list/testing/dl_test_surface_provider.h, impeller/golden_tests/BUILD.gn, impeller/golden_tests/golden_playground_test_mac.cc, impeller/golden_tests/golden_tests.cc, impeller/golden_tests/metal_screenshot.h, impeller/golden_tests/metal_screenshot.mm, impeller/golden_tests/metal_screenshotter.h, impeller/golden_tests/metal_screenshotter.mm
Revisiting this project as it may help with [attribute] X [rendering op] matrix testing of Impeller. It's not an exhaustive combinatorial test of all combinations of rendering attributes, but it attempts each op with each attribute both default and non-default.
For Impeller it only tests that the rendering produced output (i.e wasn't a NOP due to missing implementation), that the output changed if the given attribute was supposed to change the output, and that it rendered within the computed bounds that the rest of the engine will be assuming.
These changes will not result in any automatic CI testing of Impeller as is since they are only run on the Metal backend which is not enabled by default. Running `out/host_[variant]/display_list_rendertests --enable-metal` manually on a Mac host, …
=> [Impeller] Run DisplayList render tests.

impeller/golden_tests/golden_playground_test.h, impeller/golden_tests/golden_playground_test_mac.cc, impeller/golden_tests/golden_playground_test_stub.cc, impeller/playground/playground.h
In https://github.com/flutter/flutter/issues/136058#issuecomment-1751507094 it was seen that some bugs manifest only with viewports of certain sizes.  This allows writers of tests to adjust the window size for playgrounds and golden image tests. …
=> [Impeller] made window size parametric in playground/golden tests

display_list/BUILD.gn, display_list/testing/dl_rendering_unittests.cc, testing/display_list_testing.cc, third_party/txt/src/skia/paragraph_skia.cc
Switch the impeller testing in rendertests to use TextFrame objects rather than TextBlob objects when drawing to an Impeller-managed destination.
Previously the DrawText tests would generate over 200 errors because none of the attribute variants would render anything at all. After this fix the number of failures in the DrawText calls is down to 1 which points out that wrapping a DrawTextFrame call in a nothing saveLayer somehow affects the glyph positioning (in a not very appealing manner).
=> use TextFrame calls for Impeller in rendertests

fml/message_loop_unittests.cc
We don't use the MSVC frontend now anyway. And haven't for a while.
=> Remove workaround for older versions of MSVC.

shell/platform/android/hardware_buffer_external_texture.cc, shell/platform/android/hardware_buffer_external_texture.h, shell/platform/android/hardware_buffer_external_texture_gl.cc, shell/platform/android/hardware_buffer_external_texture_gl.h, shell/platform/android/hardware_buffer_external_texture_vk.cc, shell/platform/android/hardware_buffer_external_texture_vk.h, shell/platform/android/io/flutter/embedding/engine/renderer/FlutterRenderer.java, shell/platform/android/io/flutter/plugin/platform/ImageReaderPlatformViewRenderTarget.java, shell/platform/android/io/flutter/plugin/platform/PlatformViewsController.java, shell/platform/android/platform_view_android.cc
The root bug (b/300627634) was that we were holding onto HardwareBuffers after the owning Image was closed. This CL refactors the C++ code to properly hold a reference to the Image until it is safe to dispose of.
This CL also refactors the Impeller GL and Skia GL code paths to share more code.
=> Fix high FPS screen flicker of Platform Views when using ImageReaderPlatformViewRenderTarget

ci/builders/mac_ios_engine.json
This is to workaround rosetta not being installed in dart-internal machines and to unblock beta releases.
Bug: https://github.com/flutter/flutter/issues/136219
=> [flutter release cp] Use x86 machines for ios builds. (#46726)

impeller/renderer/backend/gles/BUILD.gn, impeller/renderer/backend/gles/formats_gles.cc, impeller/renderer/backend/gles/formats_gles.h, impeller/renderer/backend/gles/render_pass_gles.cc, impeller/renderer/backend/gles/test/formats_gles_unittests.cc
This is much easier to debug if we know the actual error code.
=> [Impeller] log specific framebuffer incomplete error.

flutter_frontend_server/test/to_string_test.dart, lib/ui/painting.dart, lib/web_ui/lib/painting.dart, testing/dart/canvas_test.dart
Work towards https://github.com/flutter/flutter/issues/112498.
No behavioral changes to existing code, except `Paint.enableDithering = false` will no longer be an option.
=> Remove support for `Paint.enableDithering=false` in `dart:ui`.

impeller/entity/contents/content_context.cc, impeller/entity/contents/content_context.h
Track default prototype options along side pipeline variant sets, allowing differing defaults to be assigned during ContentContext construction.
=> [Impeller] Allow pipeline variant sets to have differing defaults.

ci/builders/linux_web_engine.json, ci/builders/mac_host_engine.json, lib/web_ui/dev/generate_builder_json.dart
For https://github.com/flutter/flutter/issues/135620
=> Roll goldctl forward

impeller/renderer/backend/gles/render_pass_gles.cc
The macOS desktop driver doesn't support ES profiles, and `glClearDepthf` + `glDepthRangef` are throwing `GL_INVALID_OPERATION` and doing nothing. Noticed this while updating impeller-cmake past @matanlurey's recent changes to make `GL_INVALID_OPERATION` fatal. Impeller-cmake-example uses a depth buffer, whereas Impeller's 2D renderer currently does not.
Added a follow-up bug to make these calls work on macOS desktop: https://github.com/flutter/flutter/issues/136322.
Both Impeller Scene and the impeller-cmake-example currently just rely on the default state for clearing depth.
=> [Impeller] Avoid invalid GL depth calls on macOS desktop.

DEPS, lib/web_ui/dev/roll_fallback_fonts.dart, lib/web_ui/lib/src/engine/font_fallback_data.dart, lib/web_ui/test/ui/fallback_fonts_golden_test.dart
Adds `Noto Music` font as a fallback font, and updates DEPS and font definitions after running the font roller script.
Fixes: https://github.com/flutter/devtools/issues/6149
----
I used [the developer API](https://developers.google.com/fonts/docs/developer_api?apix_params=%7B%22family%22%3A%5B%22Noto%20Music%22%5D%7D) to make sure the api works with this font. …
=> [web] Adds Noto Music fallback font

ci/binary_size_treemap.sh, ci/builders/linux_android_aot_engine.json
This will produce a treemap where navigation starts from the buildroot and the flutter and third_party source directories are shown as siblings.
=> Run the binary size treemap script from the buildroot directory

impeller/entity/contents/content_context.cc, impeller/entity/contents/filters/blend_filter_contents.cc, impeller/entity/contents/filters/border_mask_blur_filter_contents.cc, impeller/entity/contents/filters/color_matrix_filter_contents.cc, impeller/entity/contents/filters/gaussian_blur_filter_contents.cc, impeller/entity/contents/filters/linear_to_srgb_filter_contents.cc, impeller/entity/contents/filters/morphology_filter_contents.cc, impeller/entity/contents/filters/srgb_to_linear_filter_contents.cc, impeller/entity/contents/filters/yuv_to_rgb_filter_contents.cc, impeller/entity/contents/framebuffer_blend_contents.cc, impeller/entity/contents/solid_rrect_blur_contents.cc
Remove a couple of duplicate verts in a bunch of situations.
Pedantic improvements: "Brandon, why are you like this" edition.
=> [Impeller] Use triangle strips to dedupe rectangle vertices.

shell/platform/fuchsia/flutter/vulkan_surface.cc, vulkan/procs/vulkan_interface.h
This CL changes vkWaitForFences to cause a FATAL failure as we can't recover from these errors.
Bug: b/297198565
=> [fuchsia] Add fatal error for Vulkan failure

testing/run_tests.py
These tests are sometimes hanging when the flutter_tester deletes the ContextVK and ConcurrentMessageLoop during shutdown.
=> Temporarily remove the runs of the engine Dart tests with Impeller enabled

build/dart/rules.gni, common/config.gni, flutter_frontend_server/BUILD.gn, flutter_frontend_server/README.md, flutter_frontend_server/bin/starter.dart, flutter_frontend_server/lib/server.dart, flutter_frontend_server/pubspec.yaml, testing/dart/BUILD.gn, testing/dart/compile_test.gni, testing/dart/observatory/BUILD.gn, testing/smoke_test_failure/BUILD.gn, testing/testing.gni, tools/gn
Reverts flutter/engine#46440
For b/305121780
=> Revert "Remove the frontend server wrapper"

shell/common/shell_test_platform_view_vulkan.cc, shell/platform/embedder/embedder_surface_vulkan.cc, shell/platform/fuchsia/flutter/vulkan_surface_producer.cc, testing/test_vulkan_context.cc, vulkan/vulkan_window.cc
In http://review.skia.org/764516, Skia moved the way to make a Vulkan context. This updates Flutter to use that new way. …
=> Update to use GrDirectContexts::MakeVulkan

shell/common/shell_io_manager.cc, shell/common/shell_io_manager.h, shell/platform/android/platform_view_android.cc, shell/platform/embedder/embedder_surface_gl.cc
There was a compile error when trying to roll in http://review.skia.org/764970, and this addresses that.
While I was here, I noticed some uses of the old-named `GrBackend` enum and updated it to the non-deprecated enum class. …
=> Fix forward declare and some deprecated enums

runtime/dart_vm.cc, shell/platform/fuchsia/dart_runner/dart_runner.cc
`--systrace_timeline` is redundant and makes the `getFlagList` VM Service RPC not return `timeline_recorder=systrace` (https://github.com/flutter/devtools/issues/6524#issuecomment-1760090526), so we would like to deprecate and remove it.
=> Use --timeline_recorder=systrace instead of --systrace_timeline

shell/testing/tester_main.cc
Follows up on #46389 
That patch was too permissive in cases where a build system enables impeller but not vulkan. This change makes the build succeed in such systems.
=> [Impeller] Only allow Impeller in flutter_tester if vulkan is enabled.

third_party/.gitignore, third_party/README.md
Closes https://github.com/flutter/flutter/issues/136551.
=> Oops, allow files in opted-in third_party directories.

impeller/aiks/aiks_unittests.cc, impeller/entity/entity_pass.cc
Fixes https://github.com/flutter/flutter/issues/136507 .
The cause of this bug is that we use different sizes to compute the clear color value when constructing the render target and when skipping entities:
https://github.com/flutter/engine/blob/main/impeller/entity/entity_pass.cc#L632
https://github.com/flutter/engine/blob/main/impeller/entity/entity_pass.cc#L731 and
https://github.com/flutter/engine/blob/main/impeller/entity/entity_pass.cc#L900C3-L900C3
Either the former should use the root pass size or the later should use the subpass size. This usually isn't an issue because if something covers the root pass size it generally always covers the subpass size. But during the page transition, the scaled subpass ends up slightly bigger than the root pass size and so these conditions are …
=> [Impeller] fix clear color optimization for large subpasses.

impeller/entity/entity_pass.cc
https://github.com/flutter/engine/pull/46597 creates a new clip coverage stack for each subpass.  This PR updates some clip coverage operations and assertions in EntityPass::OnRender to reflect that the current clip coverage stack only contains the range of depths within the current subpass.
=> [Impeller] Adjust clip coverage operations to handle per-pass clip stacks

ci/builders/mac_ios_engine.json
Fix issue with x86 ios builds failing due to wrong arch specified in swarming
b/305605364
=> [CP] Use x86 machines for ios builds (#46726)

shell/platform/android/io/flutter/embedding/engine/renderer/FlutterRenderer.java, shell/platform/android/io/flutter/plugin/platform/ImageReaderPlatformViewRenderTarget.java, shell/platform/android/test/io/flutter/plugin/platform/ImageReaderPlatformViewRenderTargetTest.java, shell/platform/android/test/io/flutter/plugin/platform/PlatformPluginTest.java, shell/platform/android/test/io/flutter/plugin/platform/PlatformViewWrapperTest.java, shell/platform/android/test/io/flutter/plugin/platform/PlatformViewsControllerTest.java, shell/platform/android/test/io/flutter/plugin/platform/SingleViewPresentationTest.java, shell/platform/android/test/io/flutter/plugin/platform/SurfaceTexturePlatformViewRenderTargetTest.java
- Refactor the fence waiting code to only wait on Android >= 33.
- Log a warning message once per image rendering target on Android >= 29 && < 33.
- Add a simple unit test of ImageReaderPlatformViewRenderTargets.
=> Allow Image backed platform view rendering target on Android >= 29 again

ci/licenses_golden/licenses_flutter, shell/platform/darwin/macos/framework/Source/FlutterMutatorView.mm, shell/platform/darwin/macos/framework/Source/FlutterMutatorViewTest.mm, shell/platform/darwin/macos/framework/Source/FlutterTextInputPlugin.h, shell/platform/darwin/macos/framework/Source/FlutterTextInputPlugin.mm, shell/platform/darwin/macos/framework/Source/FlutterTextInputPluginTest.mm, shell/platform/darwin/macos/framework/Source/NSView+ClipsToBounds.h
=> [macOS] FlutterMutatorView should clip to bounds

shell/testing/tester_main.cc, testing/dart/BUILD.gn, testing/dart/platform_test.dart
This addresses the problem in https://github.com/flutter/flutter/issues/12847 which changed slightly over time.
Today, `Platform.script` does not give an empty `file` URI, it gives something like `file://path/to/package/main.dart` _regardless of how the file is actually named_.
After this change, it will give the absolute path to the file being run under test.
So before this change, the new test would have a URI like
```
file:///Users/dnfield/src/flutter/engine/src/main.dart
```
And now it has
```
file:///Users/dnfield/src/flutter/engine/src/out/host_debug_unopt_arm64/gen/platform_test.dart.dill
```
This is going to be helpful in generating relative paths from the test file.
=> Fix `Platform.script` for flutter_tester

impeller/aiks/aiks_unittests.cc, impeller/entity/contents/framebuffer_blend_contents.cc
CP for https://github.com/flutter/flutter/issues/136371
=> [CP][Impeller] Fix framebuffer blend UVs. (#46489)

shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm, shell/platform/darwin/ios/framework/Source/FlutterTextInputPluginTest.mm
Fixes https://github.com/flutter/flutter/issues/132548 …
=> Don't respond to the `insertionPointColor` selector on iOS 17+

fml/cpu_affinity.cc
The newly rolled version of clang-tidy is warning about some accesses to std::optional values.  The function does a has_value check before accessing the values, but the analyzer does not detect that.
=> Workaround for a clang-tidy warning in CPUSpeedTracker

fml/memory/thread_checker.h
Developers working their app's runner code or in the native parts of                                                                    
plugins are often required to call methods from the platform thread, or            
face a crash.                                                                      
Makes a minor improvement to fml::ThreadChecker's                                  
IsCreationThreadCurrent log message.                                               
This patch originally proposed to emit a much more specific error                  
message when calling methods that must be called on the platform thread            
(typically originating in calls from plugins), however, given that we              
don't ship debug engines as part of the SDK, this is really only going …
=> [fml][embedder] Improve thread-check logging

impeller/renderer/backend/vulkan/BUILD.gn, impeller/renderer/backend/vulkan/command_encoder_vk.cc, impeller/renderer/backend/vulkan/command_encoder_vk.h, impeller/renderer/backend/vulkan/context_vk.cc, impeller/renderer/backend/vulkan/gpu_tracer_vk.cc, impeller/renderer/backend/vulkan/gpu_tracer_vk.h, impeller/renderer/backend/vulkan/swapchain_impl_vk.cc, impeller/renderer/backend/vulkan/test/gpu_tracer_unittests.cc, impeller/renderer/backend/vulkan/test/mock_vulkan.cc
Switches the GPU tracing implementation to work more like the metal version, where we decorate individual cmd buffers with start/end time queries and then min/max the final result. Hopefully this stabilizes the values on CI
=> [Impeller] Rework Vulkan GPUTracker to decorate existing cmd buffers.

DEPS, build/secondary/flutter/third_party/imgui/BUILD.gn, ci/licenses_golden/excluded_files, ci/licenses_golden/tool_signature, impeller/playground/BUILD.gn, impeller/playground/imgui/BUILD.gn, tools/licenses/lib/paths.dart
As part of eliminating the Flutter buildroot (#67373), we are moving all third-party dependencies from //third_party to //flutter/third_party.
Once all third-party dependencies have been migrated, tooling and config will be moved and the buildroot will be eliminated altogether.
Issue: https://github.com/flutter/flutter/issues/136284
No tests changed because there is no semantic change to this PR. This is simply relocating a dependency. …
=> Move imgui from buildroot to flutter third_party

impeller/renderer/backend/vulkan/test/gpu_tracer_unittests.cc
This is failing on CI but didn't fail locally on the PR. Not sure why.
=> Disable threading test that fails on CI

DEPS, ci/licenses_golden/excluded_files
None of these except remove_stale_pyc_files seems to be used. But we have the
pyc files in the .gitignore and I couldn't find any existing checked in pyc
files. So this check has never made sense for the Flutter. Removing instead of
migrating.
Buildroot patch https://github.com/flutter/buildroot/pull/784
=> Roll buildroot to pull in removal of //tools.

shell/platform/darwin/macos/framework/Source/FlutterKeyboardManagerTest.mm, shell/platform/darwin/macos/framework/Source/FlutterViewControllerTest.mm
1. Using arbitrary struct passed as const reference  to `OCMStub` now fails in OCMock. Down the line this will result with `object_getClass` being called in [`OCMArg.m`](https://github.com/erikdoe/ocmock/blob/master/Source/OCMock/OCMArg.m#L129-L133) with the address of the reference, which is not a valid class instance. This seems to have worked pre-sonoma, but it seems like a weird thing to rely on.
2. `NSResponder` mock can not be set to view controller anymore. The controller will try to access an ivar of the `NSResponder`, but mocked responder does not have the ivar of original objects which will result on invalid selector being called on a `NSMutableArray` one of the ivar of mock objects. Solution for this is to inherit from `NSResponder` and forward calls to mocked object.
3. Adding …
=> [macOS] Fix tests failing on Sonoma

DEPS, ci/licenses_golden/excluded_files
Reverts flutter/engine#47032
This is causing the Dart -> Engine roll to fail because one of the removed scripts is used by the autoroller.
=> Revert "Roll buildroot to pull in removal of //tools."

shell/platform/embedder/BUILD.gn
Maybe I'm missing something here. It seems like we include this file below:
https://github.com/flutter/engine/blob/c9c9684e03a3e1f745cbd4f8de762f42aa01ae77/shell/platform/embedder/pixel_formats.cc#L5
But it isn't mentioned in the gn file. Not sure how it is actually working today.
=> Add missing source file

shell/common/shell.cc, shell/common/shell.h
This PR relands part of https://github.com/flutter/engine/pull/45300, which was reverted in https://github.com/flutter/engine/pull/46919 due to performance regression. 
Due to how little and trivial production code the original PR touches, I really couldn't figure out the exact line that caused it except through experimentation, which requires changes to be officially landed on the main branch. After this PR lands, I'll immediately fire a performance test.
This PR contains the `Shell` refactor of the original PR. I made a slight change where the isolate snapshot is no longer returned through return value, but the parameter, in order to avoid the overhead of assigning.
It is intentional to not contain any unit tests or other changes of the original PR. They will be landed shortly after …
=> Reland 2 (part 1): Enforce the rule of calling `FlutterView.Render`

lib/web_ui/lib/src/engine/keyboard_binding.dart, lib/web_ui/lib/src/engine/raw_keyboard.dart, lib/web_ui/test/common/keyboard_test_common.dart, lib/web_ui/test/engine/raw_keyboard_test.dart, lib/web_ui/test/engine/text_editing_test.dart, third_party/web_locale_keymap/lib/web_locale_keymap/locale_keymap.dart
Fixes [136460](https://github.com/flutter/flutter/issues/136460)
Changes:
- Raw keyboard event is handled during capture phase. This is to ensure that the framework processes the event before reaching to IME text area and raw keyboard can stop the propagation for handled events.
- `RawKeyboard` event handler is invoked from `KeyboardBinding` event handler. This is to prevent race condition because both handlers now run in capture phase and `KeyboardBinding` needs to process the event first. …
=> [web] Ensure handled key event is not propagated to IME

impeller/renderer/backend/gles/reactor_gles.cc, impeller/renderer/backend/gles/reactor_gles.h
Both the raster and IO threads can flush the ops queue.  The reactor must ensure that execution of queued ops is serialized.
Fixes https://github.com/flutter/flutter/issues/135524
=> [Impeller] Guard execution of ReactorGLES operations with a mutex

lib/web_ui/lib/src/engine/keyboard_binding.dart, lib/web_ui/lib/src/engine/raw_keyboard.dart, lib/web_ui/test/common/keyboard_test_common.dart, lib/web_ui/test/engine/raw_keyboard_test.dart, lib/web_ui/test/engine/text_editing_test.dart, third_party/web_locale_keymap/lib/web_locale_keymap/locale_keymap.dart
Reverts flutter/engine#46829
Fixes https://github.com/flutter/flutter/issues/136857
Speculative fix for The builds breaking on the web text tests as seen here: https://github.com/flutter/flutter/runs/17840697842
=> Revert "[web] Ensure handled key event is not propagated to IME"

shell/platform/darwin/macos/framework/Source/FlutterRenderer.mm
There was an internal global change which turned `-Wc99-designator`. This causes the following error:
```
error: nested designators are a C99 extension [-Werror,-Wc99-designator]
65 |       .metal.struct_size = sizeof(FlutterMetalRendererConfig),
|       ^~~~~~~~~~~~~~~~~~
```
This seems like a trivial (?) fix, so perhaps we can fix it properly and possibly remove https://github.com/flutter/buildroot/blob/b9fbd310d6fa68f888738d5236ea2f6caa2d2bfc/build/config/compiler/BUILD.gn#L667 after this PR lands.
b/300573112
If you need help, consider asking for advice on the #hackers-new …
=> Fix use of nested designators

shell/gpu/gpu_surface_gl_impeller.h
This is required for platform view scenarios that merge the raster task runner into the platform thread.
=> [Impeller] Use a weak pointer factory in GPUSurfaceGLImpeller that supports the raster thread merger

shell/platform/darwin/macos/framework/Source/AccessibilityBridgeMacTest.mm
In the SendsAccessibilityCreateNotificationToWindowOfFlutterView test in AccessibilityBridgeMacTest, we look for an accessibility notification by name in a map stored in the test accessibility bridge. If there is no such notification, bail out immediately.
Previously we got a crash since we called `second` to retrieve the value associated with the map entry we find, without actually checking that we'd actually found an entry. …
=> [macOS] Fail early when no a11y notification

impeller/renderer/backend/gles/blit_command_gles.cc, impeller/renderer/backend/gles/render_pass_gles.cc, impeller/renderer/backend/gles/texture_gles.cc, impeller/renderer/backend/gles/texture_gles.h
Trivial change that removes an unused parameter.
=> Remove unused `fbo` parameter in GLES `SetAsFramebufferAttachment()`.

ci/licenses_golden/licenses_flutter, common/settings.h, impeller/playground/backend/gles/playground_impl_gles.cc, impeller/renderer/backend/gles/BUILD.gn, impeller/renderer/backend/gles/context_gles.cc, impeller/renderer/backend/gles/context_gles.h, impeller/renderer/backend/gles/gpu_tracer_gles.cc, impeller/renderer/backend/gles/gpu_tracer_gles.h, impeller/renderer/backend/gles/proc_table_gles.h, impeller/renderer/backend/gles/render_pass_gles.cc, impeller/renderer/backend/gles/surface_gles.cc, impeller/renderer/backend/gles/test/gpu_tracer_gles_unittests.cc, impeller/renderer/backend/gles/test/mock_gles.cc, impeller/renderer/backend/metal/gpu_tracer_mtl.h, shell/common/switches.cc, shell/common/switches.h, shell/platform/android/android_context_gl_impeller.cc, shell/platform/android/android_context_gl_impeller.h, shell/platform/android/android_context_gl_impeller_unittests.cc, shell/platform/android/android_context_vulkan_impeller.h, shell/platform/android/io/flutter/embedding/engine/loader/FlutterLoader.java, shell/platform/android/platform_view_android.cc, shell/platform/embedder/embedder_surface_gl_impeller.cc
Trace GPU execution time on GLES using GL_EXT_disjoint_timer_query. This requires a per-app opt in from the Android Manifest with the key `"io.flutter.embedding.android.EnableOpenGLGPUTracing` set to true.
=> [Impeller] GPU Tracer for GLES.

shell/platform/darwin/macos/framework/Source/AccessibilityBridgeMacTest.mm
Eliminate unnecessary calls to [NSViewController loadView]. To quote the [documentation][loadview] for this method: "Do not call this method. If you require this method to be called, access the view property."
In several of the existing tests, we do read viewController.view, and the other tests pass without this line regardless.
[loadView]: https://developer.apple.com/documentation/appkit/nsviewcontroller/1434405-loadview?language=objc# …
=> [macOS] Eliminate extraneous loadView calls

display_list/testing/dl_rendering_unittests.cc
The rendering tests currently always save the impeller failure images into a temporary directory in /tmp which is out of the way and might accumulate over time.
The images are now only saved when `--save-impeller-failures` is specified on the command line and they are now saved into a local sub-directory with multiple runs saving into new sub-directories to keep the failure images from getting confused with each other over time. The new image directories are named `./impeller_failure_images/NNNN/*.png`
=> Add option to save Impeller failure images in rendertests

lib/web_ui/lib/src/engine/scene_view.dart, lib/web_ui/skwasm/image.cpp, lib/web_ui/skwasm/library_skwasm_support.js, lib/web_ui/skwasm/skwasm_support.h, lib/web_ui/skwasm/surface.cpp, lib/web_ui/skwasm/surface.h, lib/web_ui/test/engine/scene_view_test.dart
This fixes https://github.com/flutter/flutter/issues/134045
There were a few different issues here:
* We need to do our own message passing for rendering pictures. The async methods provided by emscripten have their own queue that can drain synchronously, so basically it's not guaranteed to be FIFO with other messages sent to the web worker or main thread.
* When we drop frames, we should only drop intermediate frames, so that when the rendering flurry stops that the frame that is displayed is the last one that was actually requested.
* We need to reset the GL context after lazy image creation, otherwise skia's renderer gets into a bad state for that frame.
=> Fix async image loading issues in skwasm.

ci/licenses_golden/licenses_flutter, lib/web_ui/lib/src/engine.dart, lib/web_ui/lib/src/engine/semantics.dart, lib/web_ui/lib/src/engine/semantics/checkable.dart, lib/web_ui/lib/src/engine/semantics/dialog.dart, lib/web_ui/lib/src/engine/semantics/focusable.dart, lib/web_ui/lib/src/engine/semantics/image.dart, lib/web_ui/lib/src/engine/semantics/incrementable.dart, lib/web_ui/lib/src/engine/semantics/label_and_value.dart, lib/web_ui/lib/src/engine/semantics/link.dart, lib/web_ui/lib/src/engine/semantics/live_region.dart, lib/web_ui/lib/src/engine/semantics/platform_view.dart, lib/web_ui/lib/src/engine/semantics/scrollable.dart, lib/web_ui/lib/src/engine/semantics/semantics.dart, lib/web_ui/lib/src/engine/semantics/tappable.dart, lib/web_ui/lib/src/engine/semantics/text_field.dart, lib/web_ui/test/engine/semantics/semantics_test.dart
fixes https://github.com/flutter/flutter/issues/134795 …
=> Add link support in web accessibility

lib/web_ui/lib/src/engine/platform_views/content_manager.dart, lib/web_ui/test/engine/platform_views/content_manager_test.dart
Now that we want to support multi-view, we need to either:
1. Remove the workaround to safely remove slot elements in Safari, or
2. Fix it to support multi-view (can't use `flutterViewEmbedder.glassPaneShadow` anymore).
According to [this comment](https://github.com/flutter/flutter/issues/85816#issuecomment-1122638147), this is the right time to remove the workaround 😄 I tested on Desktop Safari and iOS Safari and wasn't able to reproduce the crash reported in https://github.com/flutter/flutter/issues/84832.
Fixes https://github.com/flutter/flutter/issues/85816
Part of https://github.com/flutter/flutter/issues/134443
=> [web] Remove workaround for safely removing slots on Safari

shell/platform/android/image_external_texture.cc
This log message can print on the first frame of a platform view and is not an error.
=> Lower the severity of a log message

impeller/aiks/aiks_unittests.cc, impeller/entity/contents/solid_rrect_blur_contents.cc
fixes https://github.com/flutter/flutter/issues/119974
This duplicates the math found in skia at https://skia.googlesource.com/skia/+/cf2131f85d57f938472e50b6643c3c2348709a55/gm/blurrect.cpp#484
[CLA]: …
=> [Impeller] increased padding for blurs

impeller/renderer/backend/vulkan/command_pool_vk.cc
Make sure to clear the buffers before assigning to the recycler, as the dtor was racing with the raster thread usage.
=> [Impeller] Fix cmd pool reset from background thread.

flow/layers/layer_tree.h, shell/common/shell.cc, shell/common/shell_unittests.cc
As far as I can tell, this functionality has _always_ been falling back to software rendering with Skia when Impeller was enabled. This is at best extremely misleading. Since I started putting Impeller specific objects in the display list it introduced crashes, and must be disabled.
Fixes https://github.com/flutter/flutter/issues/136847
=> [Impeller] Disable raster stats service protocol.

lib/ui/painting/image_decoder_impeller.cc
Testing locally I cant see any impact from this. Its possible the problem this "fixed" was instead fixed by affinity changes and now its no longer necessary.
See https://github.com/flutter/engine/pull/43493 .
=> [Impeller] remove image upload workarounds.

impeller/aiks/aiks_unittests.cc
fixes: https://github.com/flutter/flutter/issues/126391
It turns out certain cases listed in the issue already render correctly.  This adds tests to assert that we maintain that behavior.
[CLA]: …
=> [Impeller] Added tests to assert empty saveLayer behaviors.

flow/frame_timings.cc, flow/frame_timings.h, impeller/entity/contents/filters/gaussian_blur_filter_contents.cc, lib/ui/dart_ui.cc, lib/ui/painting/image_dispose_unittests.cc, lib/ui/window.dart, lib/ui/window/platform_configuration.cc, lib/ui/window/platform_configuration.h, lib/ui/window/platform_configuration_unittests.cc, runtime/dart_vm.cc, runtime/runtime_controller.cc, runtime/runtime_controller.h, runtime/runtime_delegate.h, shell/common/animator.cc, shell/common/animator.h, shell/common/animator_unittests.cc, shell/common/engine.cc, shell/common/engine.h, shell/common/engine_unittests.cc, shell/common/fixtures/shell_test.dart, shell/common/input_events_unittests.cc, shell/common/rasterizer.cc, shell/common/shell_test.cc, shell/common/shell_test.h, shell/common/shell_unittests.cc, shell/platform/fuchsia/flutter/vulkan_surface_producer.cc, shell/testing/tester_main.cc, testing/dart/platform_view_test.dart
This PR relands https://github.com/flutter/engine/pull/44473.
The previous PR was immediately reverted after merging because we found that the PR could cause illegal renders to be skipped on debug builds but crash the app on release builds. This PR makes the `Animator::Render` skip illegal renders as well. This should not be the final shape of this feature, and thus a TODO is added.
[C++, …
=> Reland: Multiview pipeline 

flow/frame_timings.cc, flow/frame_timings.h, impeller/entity/contents/filters/gaussian_blur_filter_contents.cc, lib/ui/dart_ui.cc, lib/ui/painting/image_dispose_unittests.cc, lib/ui/window.dart, lib/ui/window/platform_configuration.cc, lib/ui/window/platform_configuration.h, lib/ui/window/platform_configuration_unittests.cc, runtime/dart_vm.cc, runtime/runtime_controller.cc, runtime/runtime_controller.h, runtime/runtime_delegate.h, shell/common/animator.cc, shell/common/animator.h, shell/common/animator_unittests.cc, shell/common/engine.cc, shell/common/engine.h, shell/common/engine_unittests.cc, shell/common/fixtures/shell_test.dart, shell/common/input_events_unittests.cc, shell/common/rasterizer.cc, shell/common/shell_test.cc, shell/common/shell_test.h, shell/common/shell_unittests.cc, shell/platform/fuchsia/flutter/vulkan_surface_producer.cc, shell/testing/tester_main.cc, testing/dart/platform_view_test.dart
The last attempt https://github.com/flutter/engine/pull/47234 was reverted because there was another test merged in the meantime that violates the rule added in this PR.
[CLA]: …
=> Reland 2: Multiview Pipeline 

impeller/renderer/backend/vulkan/context_vk.cc, impeller/renderer/backend/vulkan/context_vk.h, impeller/renderer/backend/vulkan/gpu_tracer_vk.cc, impeller/renderer/backend/vulkan/swapchain_impl_vk.cc, impeller/renderer/context.h
Removes the rest of the validation errors by increasing the size of the query ring buffer. Because we rely on callbacks fired from the fence waiter, when the phone is under load these can be substantially delayed from the frame finishing.
Adjusts presentation to use a dedicated default priority/slow core affinity/single threaded task runner. From the ARM video guide, submitKHR will block until all previously submitted work has been scheduled. This needs to happen in order, and doesn't need to run at high priority or even on medium speed cores.
=> [Impeller] Adjustments to SubmitKHR and queries.

lib/ui/fixtures/ui_test.dart, lib/ui/platform_dispatcher.dart, shell/platform/fuchsia/dart-pkg/zircon/test/zircon_tests.dart
=> Migrated away from UnmodifiableUint8ListView

ci/licenses_golden/licenses_flutter, impeller/renderer/backend/gles/shader_library_gles.cc, impeller/renderer/backend/vulkan/shader_library_vk.cc, impeller/shader_archive/BUILD.gn, impeller/shader_archive/multi_arch_shader_archive.cc, impeller/shader_archive/multi_arch_shader_archive.fbs, impeller/shader_archive/multi_arch_shader_archive.h, impeller/shader_archive/multi_arch_shader_archive_writer.cc, impeller/shader_archive/multi_arch_shader_archive_writer.h, impeller/shader_archive/shader_archive.cc, impeller/shader_archive/shader_archive.h, impeller/shader_archive/shader_archive_types.h, impeller/shader_archive/shader_archive_unittests.cc
Existing shader archive ctors have been made private. Instead a factory is used to check to see if the blob is a single or multi-archive and do the right thing. This allows us to keep the existing code the same. But, when multi-archives are encountered, the right shaders libraries will be picked.
Creating multi-archives will be done in ImpellerC in an upcoming patch.
Towards https://github.com/flutter/flutter/issues/123741
=> [Impeller] Add support for multi-rendering-backend fat shader archives.

impeller/renderer/backend/gles/texture_gles.cc
Closes https://github.com/flutter/flutter/issues/137094.
=> OpenGL <4.x does not support stencil-only formats, so delete the TODO

.clang-tidy, flow/stopwatch_dl.cc, impeller/entity/contents/filters/filter_contents.cc, shell/common/shell.cc, shell/platform/darwin/graphics/FlutterDarwinExternalTextureMetal.mm, shell/platform/darwin/ios/framework/Source/FlutterPlatformViews.mm, shell/platform/darwin/ios/framework/Source/FlutterViewController.mm, shell/platform/embedder/embedder.cc
=> Adds lint for checking argument commments

.ci.yaml, impeller/display_list/dl_unittests.cc, shell/platform/android/external_view_embedder/external_view_embedder.cc
=> Missed linter argument comment violations

DEPS, ci/licenses_golden/excluded_files, ci/pubspec.yaml, impeller/golden_tests_harvester/pubspec.yaml, testing/scenario_app/pubspec.yaml, testing/skia_gold_client/pubspec.yaml, tools/android_lint/pubspec.yaml, tools/api_check/pubspec.yaml, tools/clang_tidy/pubspec.yaml, tools/githooks/pubspec.yaml, tools/licenses/pubspec.yaml, tools/pkg/engine_build_configs/pubspec.yaml, tools/pkg/git_repo_tools/pubspec.yaml, tools/pkg/process_fakes/pubspec.yaml, web_sdk/pubspec.yaml
Removes package:quiver, and an older second copy of package:file
=> Cleanup Dart package dependencies a bit

ci/licenses_golden/licenses_flutter, shell/platform/windows/BUILD.gn, shell/platform/windows/accessibility_bridge_windows_unittests.cc, shell/platform/windows/flutter_windows.cc, shell/platform/windows/flutter_windows_engine_unittests.cc, shell/platform/windows/flutter_windows_view.cc, shell/platform/windows/flutter_windows_view.h, shell/platform/windows/flutter_windows_view_controller.h, shell/platform/windows/flutter_windows_view_unittests.cc, shell/platform/windows/keyboard_unittests.cc, shell/platform/windows/public/flutter_windows.h, shell/platform/windows/testing/windows_test_config_builder.h, shell/platform/windows/window_state.h
This change begins the migration to the Windows embedder's new ownership model:
1. Renames `FlutterDesktopViewControllerState` to `FlutterWindowsViewController`
2. Moves ownership of the `FlutterWindowsEngine` from the `FlutterWindowsView` to the `FlutterWindowsViewController`
For more information, refer to: [flutter.dev/go/windows-multi-view-ownership-updates](https://flutter.dev/go/windows-multi-view-ownership-updates)
Part of https://github.com/flutter/flutter/issues/137267 …
=> [Windows] Introduce FlutterWindowsViewController

impeller/entity/entity_pass.cc, impeller/entity/entity_pass.h
I find it difficult to track what parts of this method are part of the closure and which aren't. Lets hoist this data into a private method and remove some unused imports.
=> [Impeller] remove giant closure in EntityPass.

impeller/aiks/aiks_unittests.cc, impeller/entity/contents/tiled_texture_contents.cc, impeller/entity/geometry/geometry.cc, impeller/entity/geometry/geometry.h, impeller/entity/geometry/rect_geometry.cc, impeller/entity/geometry/rect_geometry.h
TiledTextureContents::RenderToSnapshot should only create a snapshot directly from the texture if the geometry is an axis-aligned rectangle.
Fixes https://github.com/flutter/flutter/issues/136504
=> [Impeller] Fix the transform and geometry criteria for an optimization in TiledTextureContents

shell/platform/windows/flutter_window.cc, shell/platform/windows/flutter_window.h, shell/platform/windows/flutter_window_unittests.cc, shell/platform/windows/flutter_windows.cc, shell/platform/windows/flutter_windows_engine.cc, shell/platform/windows/flutter_windows_engine.h, shell/platform/windows/flutter_windows_engine_unittests.cc, shell/platform/windows/flutter_windows_unittests.cc, shell/platform/windows/flutter_windows_view.cc, shell/platform/windows/flutter_windows_view.h, shell/platform/windows/testing/flutter_windows_engine_builder.cc, shell/platform/windows/testing/flutter_windows_engine_builder.h, shell/platform/windows/testing/mock_window_binding_handler.h, shell/platform/windows/testing/mock_window_binding_handler_delegate.h, shell/platform/windows/testing/mock_windows_proc_table.h, shell/platform/windows/window_binding_handler.h, shell/platform/windows/window_binding_handler_delegate.h, shell/platform/windows/windows_proc_table.cc, shell/platform/windows/windows_proc_table.h
This refactors how high contrast is implemented on Windows:
1. Added a test to verify accessibility features are updated when a view is created. This prevents staleness issues as the Windows embedder isn't notified of accessibility changes while in headless mode.
1. Moved high contrast mode detection to `WindowsProcTable` from `FlutterWindow` to remove engine to view to window plumbing.
1. `FlutterWindow` and `FlutterWindowsEngine` now share their `WindowsProcTable` (which is used for mocking and polyfilling win32 APIs) to reduce redundant dynamic loading.
This pull request contains no functional changes. …
=> [Windows] Refactor high contrast mode detection

fml/base32.cc, fml/hex_codec.cc
This PR is to address an issue we're seeing compiling flutter+impeller in certain configurations. Specifically:
1. Compiling with `clang-15`
2. using the GCC 13 backend to provide headers and cstdlib.
Via the `clang-15` version flag:
```
clang-15 -v
Debian clang version 15.0.7
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/11
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/12
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/13
Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/13
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64
```
We were building using the gcc 12 backend for …
=> Fix for undefined `uint8_t` seen on Clang-15+GCC13

shell/platform/darwin/macos/BUILD.gn, shell/platform/darwin/macos/framework/Source/AccessibilityBridgeMacTest.mm, testing/BUILD.gn, testing/autoreleasepool_test.h
Adds a gtest test fixture mixin and convenience class that instantiates an NSAutoreleasePool at the beginning of each test and flushes it at the end; this allows Objective-C tests using ARC to free  allocations at the end of each test.
Adds a subclass for the macOS accessibility bridge tests that instantiates and re-uses an NSWindow* across any tests that use it. This is because instantiating, closing, and immediately collecting an NSWindow results in a crash.
Prior to this patch, tests started failing (on my machine) around the 855th iteration, and issued the following warning on the 101st iteration:
```
2023-10-26 13:02:45.390829-0700 flutter_desktop_darwin_unittests[40837:1509026] [Window] WARNING: NSWindow has detected an excessive live window count of 101. Window 0x1423 of class …
```
=> [macOS] Reuse NSWindow instance across unit tests

shell/common/shell.cc, shell/platform/android/io/flutter/embedding/android/FlutterImageView.java, shell/platform/android/io/flutter/embedding/android/FlutterSurfaceView.java, shell/platform/android/io/flutter/embedding/android/FlutterTextureView.java, shell/platform/android/io/flutter/embedding/android/FlutterView.java, shell/platform/android/io/flutter/embedding/engine/renderer/FlutterRenderer.java, shell/platform/android/io/flutter/embedding/engine/renderer/RenderSurface.java, shell/platform/android/platform_view_android.cc, shell/platform/android/test/io/flutter/embedding/engine/renderer/FlutterRendererTest.java
When we enter hybrid composition mode we 'pause' the default RenderSurface (implemented by SurfaceView or TextureView) and swap to an ImageReader based RenderSurface.
When we return from hybrid composition mode we recreate and re-initialize the real RenderSurface as if it was being used for the first time.
This broke Platform Views in an internal app b/306122497 because we would incorrectly tell the texture to attach when it was never detached.
This CL changes the protocol so that when we return from hybrid composition mode we only swap the RenderSurface and do not re-create it. This avoids doing a bunch of unnecessary work and fixes the logic error of re-attaching textures that were never detached.
*Replace this paragraph with a description of what this PR is changing or adding, and why. …
=> Don't re-initialize the default RenderSurface when returning from hybrid composition mode

impeller/aiks/aiks_unittests.cc, impeller/entity/contents/filters/border_mask_blur_filter_contents.cc, impeller/entity/contents/filters/border_mask_blur_filter_contents.h, impeller/entity/contents/filters/color_filter_contents.cc, impeller/entity/contents/filters/color_filter_contents.h, impeller/entity/contents/filters/directional_gaussian_blur_filter_contents.cc, impeller/entity/contents/filters/directional_gaussian_blur_filter_contents.h, impeller/entity/contents/filters/filter_contents.cc, impeller/entity/contents/filters/filter_contents.h, impeller/entity/contents/filters/inputs/filter_contents_filter_input.cc, impeller/entity/contents/filters/inputs/filter_contents_filter_input.h, impeller/entity/contents/filters/inputs/filter_input.cc, impeller/entity/contents/filters/inputs/filter_input.h, impeller/entity/contents/filters/local_matrix_filter_contents.cc, impeller/entity/contents/filters/local_matrix_filter_contents.h, impeller/entity/contents/filters/matrix_filter_contents.cc, impeller/entity/contents/filters/matrix_filter_contents.h, impeller/entity/contents/filters/morphology_filter_contents.cc, impeller/entity/contents/filters/morphology_filter_contents.h, impeller/entity/contents/filters/yuv_to_rgb_filter_contents.cc, impeller/entity/contents/filters/yuv_to_rgb_filter_contents.h, impeller/entity/entity_pass.cc, impeller/geometry/geometry_unittests.cc, impeller/geometry/rect.h
The new method allows a caller to ask for the coverage of the input pixels required to produce an output that spans a given area. This allows the code to clip a saveLayer that has an image filter applied to it.
=> [Impeller] Add FilterContents::GetSourceCoverage to enable filtered saveLayer clipping.

impeller/renderer/backend/gles/capabilities_gles.cc
The GLES MSAA implementation may need to call FramebufferTexture2DMultisampleEXT for the stencil attachment.
See https://github.com/flutter/flutter/issues/137252
=> [Impeller] Enable GLES MSAA only if the multisampled_render_to_texture2 extension is available

impeller/renderer/backend/vulkan/swapchain_impl_vk.cc
It turns out the fixing https://github.com/flutter/engine/pull/47249 revealed further bugs: we were actually overwriting previous presents and dropping frames, which was what the forward progress error was hinting. Once this problem is fixed, we started hitting present timeouts or overdraw of swapchain images.
The fix for this is that we shouldn't even ask for a swapchain image until after we've called present, which actually wasn't tracked with anything.
The error:
```
A Dart VM Service on Pixel 6 Pro is available at: http://127.0.0.1:62491/_N4PSEPUtA0=/
The Flutter DevTools debugger and profiler on Pixel 6 Pro is available at: http://127.0.0.1:9102?uri=http://127.0.0.1:62491/_N4PSEPUtA0=/
W/OnBackInvokedCallback(19160): OnBackInvokedCallback is not enabled for the application. …
```
=> [Impeller] Add present wait latch.

ci/licenses_golden/licenses_flutter, shell/platform/darwin/common/framework/Headers/FlutterBinaryMessenger.h, shell/platform/darwin/common/framework/Headers/FlutterChannels.h, shell/platform/darwin/common/framework/Source/FlutterBinaryMessengerRelayTest.mm, shell/platform/darwin/common/framework/Source/FlutterChannelsTest.m, shell/platform/darwin/ios/flutter_task_queue_dispatch.h, shell/platform/darwin/ios/platform_message_handler_ios.h, shell/platform/darwin/ios/platform_message_handler_ios.mm
fixes https://github.com/flutter/flutter/issues/118832
This makes the `FlutterTaskQueue` protocol visible, but keeps the `dispatch:` selector private.  Under the covers there are runtime checks to make sure `dispatch:` is available since we can't have compile time checks anymore.
[testing …
=> Made FlutterTaskQueue visible for Swift.

DEPS, ci/licenses_golden/excluded_files, testing/run_tests.py
As part of eliminating the Flutter buildroot (https://github.com/flutter/flutter/issues/67373), we are moving all third-party dependencies from //third_party to //flutter/third_party.
Once all third-party dependencies have been migrated, tooling and config will be moved and the buildroot will be eliminated altogether.
No tests changed because there is no semantic change to this PR. This is simply relocating a dependency.
=> Move gtest-parallel to flutter/third_party

DEPS, ci/licenses_golden/excluded_files
It was introduced for a Linux/GTK component in https://github.com/flutter/engine/pull/17634.  But it looks like that dependency was later removed.
=> Remove //third_party/khronos

impeller/entity/contents/filters/directional_gaussian_blur_filter_contents.cc
fixes https://github.com/flutter/flutter/issues/127770
This will help performance as well since our kernels will be smaller.  The justification for scaling the sigma is that we need to account in the math the scaling down that we are doing of the input.
Here are the side-by-side comparisons with this math and skia, impeller is always on the right: …
=> [Impeller] started scaling the gaussian blur sigma to match skia output

ci/licenses_golden/excluded_files, impeller/geometry/BUILD.gn, impeller/geometry/rect.h, impeller/geometry/rect_unittests.cc
This is a precursor change that will allow us to migrate all of the Impeller sources off of accessing the `origin` and `size` fields in preparation for improving the implementation of `Rect`.
No code has been migrated to use the new fields yet, and so this code should be completely benign as is, but there will be a number of follow-on PRs that all share this PR as a pre-requisite and so it needs to be landed independently of any of the PRs that will modify code currently in use.
=> [Impeller] Rect getters

lib/ui/painting/image_decoder_impeller.cc
Reverts flutter/engine#47209
This actually did regress things, I benchmarked poorly!
see https://flutter-flutter-perf.skia.org/e/?queries=device_type%3DPixel_7_Pro%26sub_result%3D90th_percentile_frame_rasterizer_time_millis%26sub_result%3D99th_percentile_frame_rasterizer_time_millis%26sub_result%3Daverage_frame_rasterizer_time_millis%26sub_result%3Dworst_frame_rasterizer_time_millis%26test%3Dnew_gallery_impeller__transition_perf
I did check https://developer.arm.com/documentation/101897/0301/CPU-overheads/Vulkan-CPU-memory-mapping and we're following the expected advice there. Without a much deeper investigation though we may not have any idea what to do
=> Revert "[Impeller] remove image upload workarounds."

shell/platform/darwin/macos/framework/Source/FlutterEmbedderExternalTextureTest.mm
Wraps all FlutterExternalTexture tests in an autorelease pool to ensure resources are cleaned up between tests.
Prior to this change, running these tests via:
../out/host_debug_unopt_arm64/flutter_desktop_darwin_unittests \
--gtest_filter='FlutterEmbedderExternalTextureUnittests.*'
Resuling in a segfault:
[ERROR:flutter/shell/platform/darwin/graphics/FlutterDarwinContextMetalSkia.mm(35)]
Could not create Metal command queue.
zsh: segmentation fault
../out/host_debug_unopt_arm64/flutter_desktop_darwin_unittests
Issue: https://github.com/flutter/flutter/issues/104789
Issue: https://github.com/flutter/flutter/issues/127441
Issue: https://github.com/flutter/flutter/issues/124840 …
=> [macOS] Wrap external texture tests in autorelease pool

.ci.yaml, ci/builders/linux_web_engine.json, ci/builders/mac_host_engine.json, lib/web_ui/README.md, lib/web_ui/dev/generate_builder_json.dart
Related to https://github.com/flutter/flutter/issues/137177 …
=> Bump goldctl

impeller/renderer/backend/gles/render_pass_gles.cc
This got dropped during merging in the MSAA patches.
=> [Impeller] Restore GLES GPU query times.

impeller/aiks/aiks_unittests.cc, impeller/aiks/canvas_unittests.cc, impeller/entity/entity_unittests.cc, impeller/geometry/geometry_unittests.cc, impeller/geometry/rect.h, impeller/geometry/rect_unittests.cc
This is a pre-requisite step to deleting the un-named Constructors for Rect and moving to named factories. The intention is both to improve code readability and so that the underlying storage information is not implied or exposed.
This PR only modifies the unit tests which will not affect actual running apps, but migrates >95% of the concrete Rect construction to the named factory methods. Use of these constructors in the rest of the code is very rare since most methods get their Rect instances from data they compute or are delivered from elsewhere. Those other instances will be eliminated more on a file by file basis to reduce the surface area of errors arising due to typos or porting mistakes.
=> [Impeller] Migrate unit tests to named Rect factories

impeller/renderer/backend/gles/capabilities_gles.cc, impeller/renderer/backend/gles/proc_table_gles.h, impeller/renderer/backend/gles/texture_gles.cc, impeller/renderer/backend/gles/texture_gles.h
Closes https://github.com/flutter/flutter/issues/137569.
Closes https://github.com/flutter/flutter/issues/137095.
As of the latest commit, it works on both the Moto G4 and Pixel 5.
=> [Impeller] OpenGLES MSAA Render Buffers (i.e. for stencils)

impeller/aiks/aiks_unittests.cc, impeller/aiks/paint.cc
Fixes https://github.com/flutter/flutter/issues/137484
=> [Impeller] Do not return a null Contents if a Paint's blur filter yields an empty coverage rect

ci/clang_tidy.sh, shell/common/shell.cc, tools/clang_tidy/lib/src/command.dart, tools/clang_tidy/lib/src/options.dart, tools/clang_tidy/test/clang_tidy_test.dart
fixes https://github.com/flutter/flutter/issues/137260 …
=> Made clang tidy use arm64 if on an arm64 mac.

impeller/entity/contents/filters/filter_contents.cc, impeller/entity/entity_pass.cc, impeller/geometry/geometry_unittests.cc, impeller/geometry/rect.h
`Rect::Intersection(a, b)` instead of `Intersection(a, b)`, etc.
Make them usable with other Rect variants, although `RoundOut` is not useful for integer rectangles, for example.
=> [Impeller] Place Rect statics under the Rect template.

impeller/renderer/backend/gles/buffer_bindings_gles.cc, impeller/renderer/backend/gles/buffer_bindings_gles.h
The fragment shader texture bindings will smash into the texture units used for the vertex shader bindings if the vertex and fragment shaders both have textures.
Entities doesn't use any pipelines that tickle this case.
=> [Impeller] OpenGLES: Ensure frag/vert textures are bound with unique texture units.

impeller/entity/entity_pass.cc
Follow up for comments in https://github.com/flutter/engine/pull/46130.
This case shouldn't actually be possible today, but we should be able to make this reasonably testable without goldens... added an issue to follow-up here: https://github.com/flutter/flutter/issues/137356
This branch noise will also melt away with: https://github.com/flutter/flutter/issues/137306
=> [Impeller] Fix nullopt access and simplify coverage computation in GetSubpassCoverage.

ci/firebase_testlab.py
Changes the FTL tests to use a high capacity device
Similar PR from packages repo: https://github.com/flutter/packages/pull/5224
The list of devices (and their capacity) is visible through the [3rd option here "Google APIs Explorer"](https://firebase.google.com/docs/test-lab/android/available-testing-devices), without a login to any project. …
=> Change FTL test to high capacity device

impeller/aiks/canvas.cc, impeller/entity/contents/clip_contents.cc, impeller/entity/contents/filters/border_mask_blur_filter_contents.cc, impeller/entity/contents/filters/directional_gaussian_blur_filter_contents.cc, impeller/entity/contents/filters/morphology_filter_contents.cc, impeller/entity/contents/tiled_texture_contents.cc, impeller/entity/entity_pass.cc, impeller/entity/geometry/cover_geometry.cc, impeller/entity/geometry/stroke_path_geometry.cc, impeller/geometry/geometry_unittests.cc, impeller/geometry/path.cc, impeller/geometry/path_builder.cc, impeller/geometry/rect.h, impeller/geometry/rect_unittests.cc, impeller/golden_tests/golden_tests.cc, impeller/playground/imgui/imgui_impl_impeller.cc, impeller/renderer/blit_pass.cc, impeller/renderer/render_pass.cc, impeller/renderer/snapshot.cc, impeller/typographer/backends/stb/text_frame_stb.cc, impeller/typographer/text_frame.cc
The named factories provide better readability and do not imply an internal storage format (which will be changing soon).
=> [Impeller] Move all remaining Rect construction to named factories

impeller/entity/contents/filters/filter_contents.h
Fixes https://github.com/flutter/flutter/issues/137703
Also clarified and fixed indentation on docstring comment for the public method `FilterContents::GetSourceCoverage`
=> Add some important comments to some of the FilteContents methods

display_list/BUILD.gn, display_list/benchmarking/dl_benchmarks.cc, display_list/benchmarking/dl_complexity_unittests.cc, display_list/display_list_unittests.cc, display_list/testing/dl_test_snippets.cc, display_list/testing/dl_test_snippets.h, flow/BUILD.gn, shell/platform/fuchsia/flutter/BUILD.gn
Skia is removing the API for constructing a default typeface (see https://issues.skia.org/issues/305780908)
Fixes https://github.com/flutter/flutter/issues/137565
=> Update DisplayList tests to explicitly select the Roboto font

testing/scenario_app/lib/src/platform_view.dart
Fixes race condition in Platform View Scenario tests, see https://github.com/flutter/flutter/issues/126627 for description of issue.
Fixes https://github.com/flutter/flutter/issues/137547 and https://github.com/flutter/flutter/issues/126627. …
=> Fix race condition in Platform View Scenario tests

impeller/aiks/aiks_unittests.cc, impeller/entity/entity_pass.cc
Fixes https://github.com/flutter/flutter/issues/136507 .
The cause of this bug is that we use different sizes to compute the clear color value when constructing the render target and when skipping entities:
https://github.com/flutter/engine/blob/main/impeller/entity/entity_pass.cc#L632 https://github.com/flutter/engine/blob/main/impeller/entity/entity_pass.cc#L731 and https://github.com/flutter/engine/blob/main/impeller/entity/entity_pass.cc#L900C3-L900C3
Either the former should use the root pass size or the later should use the subpass size. This usually isn't an issue because if something covers the root pass size it generally always covers the subpass size. But during the page transition, the scaled subpass ends up slightly bigger than the root pass size and so these conditions are …
=> [CP][Impeller] fix clear color optimization for large subpasses. (#46887)

flow/layers/layer_tree.h, shell/common/shell.cc, shell/common/shell_unittests.cc
As far as I can tell, this functionality has _always_ been falling back to software rendering with Skia when Impeller was enabled. This is at best extremely misleading. Since I started putting Impeller specific objects in the display list it introduced crashes, and must be disabled.
Fixes https://github.com/flutter/flutter/issues/136847
=> [CP][Impeller] Disable raster stats service protocol. (#47206)

.ci.yaml, ci/builders/mac_android_aot_engine.json, ci/builders/mac_clang_tidy.json, ci/builders/mac_clang_tidy_presubmit.json, ci/builders/mac_host_engine.json, ci/builders/mac_impeller_cmake_example.json, ci/builders/mac_ios_engine.json, ci/builders/mac_unopt.json
In preparation for migrating our fleet to macOS 13, we're updating tests to run on either macOS 12 or macOS 13.
I have run all tests on macOS 13: https://docs.google.com/spreadsheets/d/1-KOSOSF7uVA4KuqSMn9xz3IIJW78u8SXLYK2OAfe_Qg/edit?usp=sharing&resourcekey=0-df8Bj5PRS1IPBccPDdvRCQ
Note: I'm leaving subtests of `Linux linux_web_engine` on Mac-12 since they're currently incompatible with MacOS 13. …
=> Run tests on either macOS 12 or 13

impeller/geometry/geometry_asserts.h, impeller/geometry/geometry_unittests.cc, impeller/geometry/rect.h
The exposed Rect fields prevent future optimizations which will depend on changing the internal storage format.
=> [Impeller] Deprecate the exposed Rect fields

lib/ui/BUILD.gn, lib/ui/dart_ui.cc, lib/ui/text.dart, lib/ui/text/paragraph.cc, lib/ui/text/paragraph.h, lib/web_ui/lib/src/engine/canvaskit/canvaskit_api.dart, lib/web_ui/lib/src/engine/canvaskit/text.dart, lib/web_ui/lib/src/engine/skwasm/skwasm_impl/paragraph.dart, lib/web_ui/lib/src/engine/text/canvas_paragraph.dart, lib/web_ui/lib/src/engine/text/layout_service.dart, lib/web_ui/lib/text.dart, lib/web_ui/skwasm/text/paragraph.cpp, lib/web_ui/test/canvaskit/text_test.dart, lib/web_ui/test/html/text_test.dart, testing/dart/paragraph_test.dart, third_party/txt/src/skia/paragraph_skia.cc, third_party/txt/src/skia/paragraph_skia.h, third_party/txt/src/txt/paragraph.h
The diff is in [this commit](https://github.com/flutter/engine/commit/305d930fe166cf02f71a6c1c1794b0bfe9f3ba5a). …
=> Reland "Expose more methods on ui.Paragraph: lines" (#47584)

lib/web_ui/lib/src/engine/keyboard_binding.dart, lib/web_ui/lib/src/engine/raw_keyboard.dart, lib/web_ui/test/common/keyboard_test_common.dart, lib/web_ui/test/engine/raw_keyboard_test.dart, lib/web_ui/test/engine/text_editing_test.dart, third_party/web_locale_keymap/lib/web_locale_keymap/locale_keymap.dart
This PR relands https://github.com/flutter/engine/pull/46829, which got reverted in https://github.com/flutter/engine/pull/47086 because of https://github.com/flutter/flutter/issues/136857.
There are no changes in the PR compared to the reverted one. The issue are missing `keyup` events in the integration test, which triggers assertion in `KeyboardBindings` and which should be fixed by https://github.com/flutter/flutter/pull/136874.
Changes:
- Raw keyboard event is handled during capture phase. This is to ensure that the framework processes the event before reaching to IME text area and raw keyboard can stop the propagation for handled events.
- `RawKeyboard` event handler is invoked from `KeyboardBinding` event handler. This is to prevent race condition because both handlers now run in …
=> Reland: [web] Ensure handled key event is not propagated to IME

ci/licenses_golden/excluded_files, impeller/entity/BUILD.gn, impeller/entity/contents/checkerboard_contents.h, impeller/entity/contents/checkerboard_contents_unittests.cc, impeller/entity/entity_playground.cc, impeller/entity/entity_playground.h, impeller/entity/entity_unittests.cc
As a response to my comments in https://github.com/flutter/engine/pull/47621
=> [Impeller] add example of testing entity with "real" HAL instead of mocking.

impeller/aiks/canvas.cc, impeller/aiks/color_source.cc, impeller/aiks/picture.cc
These changes move any code in `impeller/aiks` that accessed the internal fields of `Rect` to using either the appropriate convenience methods for the operation or the getters for those properties.
This is a simple code refactoring and should be covered by existing tests.
=> [Impeller] Remove Rect field accesses from aiks subdirectory

lib/ui/painting/picture.cc, lib/ui/painting/picture.h, lib/ui/painting/picture_recorder.cc, lib/ui/painting/picture_recorder.h
The Dart code has the following declaration:
```dart
@Native<Void Function(Pointer<Void>, Handle)>(symbol: 'PictureRecorder::endRecording')
external void _endRecording(_NativePicture outPicture);
```
=> Dart doesn't expect to get a return value, so C++ shouldn't return anything.
=> Fix incorrect C++ return value of PictureRecorder::endRecording()

.ci.yaml, ci/builders/linux_fuchsia.json, tools/fuchsia/upload_to_symbol_server.py
There were a couple of issues with the script. The first one is it was always trying to upload the entire .buil_id folder rather than individual files and the second one is that it could not find depot_tools on path. …
=> Fix symbols upload

third_party/tonic/dart_args.h, third_party/tonic/dart_wrappable.h
Flutter makes use of C++ multiple inheritence in it's C++ classes that have corresponding Dart objects attached. An example is e.g.
```
class Canvas : public RefCountedDartWrappable<Canvas>, DisplayListOpFlags { }
template <typename T>
class RefCountedDartWrappable : public fml::RefCountedThreadSafe<T>,
public tonic::DartWrappable { }
```
When a C++ class has multiple base classes, the C++ compiler has the liberty to decide the order in which they get layed out in memory. (It doesn't necessarily follow declaration order, in fact it has a preference for having classes with
vtables before classes without vtables.)
Two casts to consider (with multiple inheritance in mind):
* upcasts: Those are done by C++ automatically but can modify the actual address (i.e. pointer value)
* downcasts: Those …
=> Fix FFI-based tonic layer to use proper C++ static_cast<>()s

ci/licenses_golden/excluded_files, impeller/entity/BUILD.gn, impeller/entity/contents/test/contents_test_helpers.cc, impeller/entity/contents/test/contents_test_helpers.h, impeller/entity/contents/vertices_contents.cc, impeller/entity/contents/vertices_contents_unittests.cc
Part of https://github.com/flutter/flutter/issues/118914
When drawing vertices with a destination blend mode, we need to make sure to forward any alpha component. I introduced some test helpers to allow verification of recorded cmds without goldens.
=> [Impeller] fix drawVertices dest fast path to apply alpha.

ci/licenses_golden/excluded_files, impeller/geometry/BUILD.gn, impeller/geometry/geometry_asserts.h, impeller/geometry/matrix_unittests.cc
=> [Impeller] added tests for matrices

ci/licenses_golden/excluded_files, impeller/core/texture_descriptor.h, impeller/geometry/BUILD.gn, impeller/geometry/rect.h, impeller/geometry/rect_unittests.cc, impeller/geometry/size.h, impeller/geometry/size_unittests.cc, impeller/image/decompressed_image.cc, impeller/renderer/snapshot.cc
Removes unused or redundant overloads and fixes the IsEmpty method on Size to be both simpler (2 comparisons vs. 4) and NaN-aware. Rect automatically uses the new code via delegation to the Size object.
=> [Impeller] Make IsEmpty methods on Rect and Size NaN-aware

shell/platform/windows/angle_surface_manager.h, shell/platform/windows/flutter_window_unittests.cc, shell/platform/windows/flutter_windows_engine_unittests.cc, shell/platform/windows/flutter_windows_view_unittests.cc, shell/platform/windows/system_utils_unittests.cc
This PR contains no functional changes but improves existing unit tests to reduce the number of warnings output when the tests are ran:
1. Replaced `ON_CALL` with `EXPECT_CALL` for expected method calls
2. Added some missing mocks …
=> [Windows] Reduce warnings produced by unit tests

impeller/base/base_unittests.cc, impeller/base/thread.h
Fixes https://github.com/flutter/flutter/issues/134843
=> [Impeller] Support static thread safety analysis with condition variables.

ci/licenses_golden/tool_signature, tools/licenses/lib/paths.dart
Incoming dart roll with https://dart.googlesource.com/sdk/+/4d308f39115a2969fb9908055b37a93969d4fc8d moves `runtime/third_parry` in dart to `third_party`, so license script ignore-list have to be updated to accommodate new location.
Once the roll lands, old locations should be cleaned up from the ignore-list.
=> Include updated locations for dart third_party components into license ignore-list.

shell/platform/darwin/macos/framework/Source/FlutterEngineTest.mm, shell/platform/windows/flutter_windows_unittests.cc, testing/BUILD.gn, testing/stream_capture.cc, testing/stream_capture.h
Factors out an RAII-based class that can be used to capture std::cout, std::cerr, or technically any other std::ostream, though that's unlikely to be useful.
This makes the logic reusable but more importantly, ensures the capture is cleaned up at the end of the test. …
=> [testing] Extract StreamCapture test utility

shell/platform/darwin/macos/framework/Source/FlutterEngineTest.mm
In engine tests where we require a running engine to proceed with the test, immediately fail if the engine isn't running rather than carrying on with the test. In most cases, the fixture test proceeds to block the main thread on a latch until it's released from the UI thread, so this results in quicker test failures. …
=> [macOS] Bail out of tests if engine not running

shell/platform/android/io/flutter/plugin/platform/PlatformViewsController.java
Internally we have a lint that surfaces this as a warning. Googlers, please refer to go/al-rule/NarrowingConversion.
Related: b/309552840
When we do:
```
coords.toolMajor = (float) (double) coordsList.get(3) * density;
```
`coordsList.get(3)` is casted to a `double`, then a `float`, before the multiplication happens. 
I don't think this is intentional. The intention of the code here seems to be:
- Cast to a `double`: `coordsList` is a `List<Object>` so the cast narrows the value
- Cast to a `float`: To fit the resulting value into [`coords.toolMajor`](https://developer.android.com/reference/android/view/MotionEvent.PointerCoords#toolMajor), which is a `float`.
As such, add parenthesis to address this. …
=> Fix narrowing conversion lint

lib/web_ui/lib/src/engine/pointer_binding.dart, lib/web_ui/lib/src/engine/semantics/semantics.dart, lib/web_ui/lib/src/engine/semantics/tappable.dart, lib/web_ui/test/common/matchers.dart, lib/web_ui/test/engine/pointer_binding_test.dart, lib/web_ui/test/engine/semantics/semantics_test.dart, lib/web_ui/test/engine/semantics/semantics_tester.dart
This relands https://github.com/flutter/engine/pull/43620 with a fix for nested tappable nodes. The first PR introduced this regression: https://github.com/flutter/flutter/issues/134842.
This PR includes the original PR and a fix for the regression. The fix is to call `stopPropagation` on the "click" event so that it is not handled by the ancestor if the child has already decided to send a `SemanticsAction.tap` to the framework. This ensures that there cannot be more than one `SemanticsAction.tap` sent to the framework.
Fixes https://github.com/flutter/flutter/issues/134842
=> [web] fix clicks on merged semantic nodes (attempt #2)

impeller/aiks/aiks_unittests.cc, impeller/entity/geometry/fill_path_geometry.cc, impeller/entity/geometry/geometry.cc, impeller/entity/geometry/vertices_geometry.cc, impeller/geometry/rect.h, impeller/geometry/rect_unittests.cc
Three places in the code were manually computing the UV coordinates relative to a texture coverage rectangle while also transforming the points. This change will make it easier both to compute the UV conversion matrix and also to consolidate it with the transform that was already being applied to streamline the total computations.
=> [Impeller] Add Rect::GetNormalizingTransform to handle UV coordinate conversion

shell/platform/darwin/macos/framework/Source/FlutterEngineTestUtils.h, shell/platform/darwin/macos/framework/Source/FlutterEngineTestUtils.mm, shell/platform/darwin/macos/framework/Source/FlutterViewControllerTest.mm
Wraps all FlutterViewController tests in an autorelease pool to ensure resources are cleaned up.
Adds a MockFlutterEngineTest subclass of AutoreleasePoolTest that creates an OCPartialMock FlutterEngine and shuts it down at the end of the test. Previously we were not shutting down any FlutterEngine instances we allocated, resulting in potentially thousands of threads and graphics contexts being allocated.
Prior to this change, running these tests via:
../out/host_debug_unopt_arm64/flutter_desktop_darwin_unittests \
--gtest_filter='FlutterViewController.*' --gtest_repeat=1000
resulted in test failures and sometimes segfaults. This ensures resources are cleaned up
Eventually all unit tests should configure their FlutterEngine via either FlutterEngineTest (which should be an …
=> [macOS] Clean up resources in ViewController tests

impeller/entity/entity_pass.cc, impeller/renderer/backend/gles/capabilities_gles.cc, impeller/renderer/backend/gles/capabilities_gles.h, impeller/renderer/backend/gles/test/capabilities_unittests.cc, impeller/renderer/backend/metal/context_mtl.mm, impeller/renderer/backend/vulkan/capabilities_vk.cc, impeller/renderer/backend/vulkan/capabilities_vk.h, impeller/renderer/capabilities.cc, impeller/renderer/capabilities.h, impeller/renderer/capabilities_unittests.cc
As discovered by @knopp in https://github.com/flutter/flutter/issues/131567#issuecomment-1678210475, this is actually reducing performance substantially when there are multiple blurs. In the case of https://github.com/flutter/flutter/issues/132735 , removing this capbility improves GPU performance from 400ms per frame to ~100 ms per frame.
Fixes https://github.com/flutter/flutter/issues/131567#issuecomment-1678210475
-----
  | Macrobench | Example App
-- | -- | --
TOT | 250 | 450
W/Out OnScreen | 203-187 | 125-109
W/Out Onscreen and Resolve | 203 | 125
=> [Impeller] remove capability to read from onscreen.

impeller/aiks/aiks_unittests.cc, impeller/aiks/canvas.cc, impeller/aiks/canvas.h, impeller/aiks/canvas_recorder.h, impeller/aiks/canvas_recorder_unittests.cc, impeller/aiks/canvas_unittests.cc, impeller/display_list/dl_dispatcher.cc, impeller/display_list/dl_dispatcher.h, impeller/display_list/dl_unittests.cc, impeller/geometry/path_builder.cc, impeller/geometry/path_builder.h
Fixes https://github.com/flutter/flutter/issues/133793
=> [Impeller] add support for Skia concept of RRect::isSimple needed for DL dispatching

impeller/playground/backend/vulkan/playground_impl_vk.cc, impeller/playground/backend/vulkan/playground_impl_vk.h
Libcxx is leaking a thread-local storage key each time SwiftShader is loaded and unloaded.  If a test's Vulkan instance is the only one in the process, then SwiftShader will be unloaded after the test ends.  If many Vulkan playground tests run in a suite, then eventually the leak will cause the process to exceed its limit of TLS keys and the suite will fail.
The process can ensure that SwiftShader remains loaded by holding another Vulkan instance that persists across all tests in the suite.
Fixes https://github.com/flutter/flutter/issues/138028
=> [Impeller] Create a global Vulkan instance in PlaygroundImplVK to prevent SwiftShader from being unloaded after a test completes

impeller/entity/shaders/gaussian_blur/gaussian_blur.glsl
=> [Impeller] Documented the 2 step in the gaussian blur.

impeller/aiks/aiks_unittests.cc, impeller/aiks/canvas.cc, impeller/aiks/canvas.h, impeller/aiks/canvas_recorder.h, impeller/aiks/canvas_recorder_unittests.cc, impeller/aiks/canvas_unittests.cc, impeller/display_list/dl_dispatcher.cc, impeller/display_list/dl_dispatcher.h, impeller/display_list/dl_unittests.cc, impeller/geometry/path_builder.cc, impeller/geometry/path_builder.h
Reverts flutter/engine#47821
The original PR was reverted because the Vulkan backends couldn't handle the extra tests, but they've since been patched to fix the problem.
=> Reland "[Impeller] add support for Skia concept of RRect::isSimple needed for DL dispatching"

shell/platform/darwin/macos/framework/Source/FlutterEmbedderExternalTextureTest.mm
This cleans up several places where instead of allocating a std::unique_ptr immediately, we were making allocations with the new operator, then later wrapping in a unique_ptr. The previous code was correct but there was no reason not to allocate a unique_ptr immediately.
This code makes no semantic changes; just applies a stylistic improvement that makes the code very slightly safer.
[C++, …
=> [macOS] Allocate textures as unique_ptr earlier

lib/web_ui/lib/src/engine/platform_dispatcher.dart, lib/web_ui/lib/src/engine/window.dart, lib/web_ui/lib/window.dart
- Provide a non-singleton implementation of `EngineFlutterView`.
- Move all common "view" logic into `EngineFlutterView`.
- Remove the unused `windowConfigurations` map from `EnginePlatformDispatcher`.
=> [web] Non-singleton implementation of ui.FlutterView

DEPS
Reverted as it broke the engine->flutter autoroller as it included this file. It was removed in https://skia-review.googlesource.com/c/skia-autoroll-internal-config/+/775817 and can now be removed from the engine.
https://github.com/flutter/flutter/issues/138087
=> Reland "Remove Fuchsia Mac SDK from DEPS"

.ci.yaml, .clang-tidy, display_list/geometry/dl_rtree_unittests.cc, display_list/testing/dl_rendering_unittests.cc, fml/memory/ref_counted_unittest.cc, fml/memory/weak_ptr_unittest.cc, fml/message_loop_task_queues_benchmark.cc, impeller/aiks/paint_pass_delegate.cc, impeller/compiler/uniform_sorter.cc, impeller/display_list/dl_unittests.cc, impeller/entity/contents/filters/filter_contents.cc, impeller/entity/contents/runtime_effect_contents.cc, impeller/entity/contents/vertices_contents_unittests.cc, impeller/entity/entity_pass.cc, impeller/renderer/backend/gles/buffer_bindings_gles.cc, impeller/renderer/pool_unittests.cc, lib/ui/painting/fragment_program.cc, lib/ui/painting/path_measure.cc, lib/ui/ui_benchmarks.cc, runtime/dart_isolate.cc, runtime/service_protocol.cc, shell/common/resource_cache_limit_calculator.cc, shell/common/serialization_callbacks.cc, shell/common/shell.cc, shell/common/shell_unittests.cc, shell/common/switches.cc, shell/platform/common/accessibility_bridge.cc, shell/platform/darwin/macos/framework/Source/AccessibilityBridgeMac.mm, shell/platform/darwin/macos/framework/Source/FlutterMutatorViewTest.mm, shell/platform/embedder/tests/embedder_test_context.cc
fixes https://github.com/flutter/flutter/issues/137372 …
=> Expanded the performance lints

lib/web_ui/lib/src/engine/canvaskit/canvaskit_api.dart, lib/web_ui/lib/src/engine/canvaskit/surface.dart, lib/web_ui/lib/src/engine/dom.dart, lib/web_ui/lib/src/engine/js_interop/js_loader.dart, lib/web_ui/lib/src/engine/skwasm/skwasm_impl/codecs.dart, lib/web_ui/lib/src/engine/skwasm/skwasm_impl/renderer.dart, lib/web_ui/lib/src/engine/view_embedder/hot_restart_cache_handler.dart, lib/web_ui/test/engine/scene_view_test.dart, lib/web_ui/test/ui/image_golden_test.dart
JS types are going to become extension types and as such, @staticInterop types cannot implement these types. When we migrate these classes to extension types, we can add back the subtyping.
Enables https://github.com/dart-lang/sdk/issues/52687.
=> Remove implements of JS types on @staticInterop classes

ci/licenses_golden/licenses_flutter, impeller/aiks/aiks_unittests.cc, impeller/aiks/canvas.cc, impeller/aiks/canvas.h, impeller/display_list/dl_dispatcher.cc, impeller/entity/BUILD.gn, impeller/entity/geometry/geometry.cc, impeller/entity/geometry/geometry.h, impeller/entity/geometry/geometry_unittests.cc, impeller/entity/geometry/line_geometry.cc, impeller/entity/geometry/line_geometry.h
Impeller implements the DrawLine primitive as DrawPath on a path containing a single line. Benchmarks show that this can cost 30% overhead on apps that use a lot of DrawLine primitives. This PR creates a more direct Entity that can tesselate the geometry of a line directly.
The reduced overhead should help with https://github.com/flutter/flutter/issues/138004
The current code will back off to Path rendering for round caps. When the circle geometry work is finished (https://github.com/flutter/engine/pull/47845) we can come back and implement round caps using the code refactored in that PR.
=> [Impeller] implement Canvas::DrawLine to tesselate lines directly

ci/licenses_golden/licenses_flutter, impeller/fixtures/dart_tests.dart, impeller/renderer/backend/gles/texture_gles.cc, impeller/renderer/renderer_dart_unittests.cc, lib/gpu/BUILD.gn, lib/gpu/device_buffer.cc, lib/gpu/device_buffer.h, lib/gpu/lib/gpu.dart, lib/gpu/lib/src/buffer.dart, lib/gpu/lib/src/context.dart, lib/gpu/lib/src/formats.dart, lib/gpu/lib/src/smoketest.dart
Part of http://flutter.dev/go/impeller-dart
Resolves https://github.com/flutter/flutter/issues/130924.
Resolves https://github.com/flutter/flutter/issues/130925.
Create and upload data to host visible device buffers. Commands should allow for binding either HostBuffers (which eventually resolve to DeviceBuffers) or DeviceBuffers. There's a `Buffer` mixin to allow for expressing this in `BufferView`, but this may end up changing once I actually add Commands and need to solve the puzzle.
=> [Flutter GPU] Add DeviceBuffer.

tools/android_sdk/create_cipd_packages.sh
Reverts
* https://github.com/flutter/engine/pull/47454
and adds documentation
The NDK folder shuffling in the DEPS is to simplify the build files and enable building with different NDK versions between Dart and Flutter while sharing the build files.
Closes: https://github.com/flutter/flutter/issues/136666 …
=> Revert "[deps] Stop moving NDK folder inside Android SDK (#47454)"

flow/stopwatch.cc, flow/stopwatch.h, flow/stopwatch_dl.cc, flow/stopwatch_sk.cc, flow/stopwatch_unittests.cc
With the current stopwatch design, we request the frame rate multiple times per frame. On Android this calls into JNI which is pretty slow. If we cache the value at construction of the StopwatchVisualizer, then we will only compute it once per frame (because the StopwatchVisualizer is reconstructed each frame).
Fixes https://github.com/flutter/flutter/issues/137797
So the issue isn't that we're checking the fresh rate every frame, its that we were checking N times on each frame.
=> [engine] request frame rate once per frame.

impeller/geometry/geometry_benchmarks.cc
Since most shapes are convex, we should benchmark this too.
=> [Impeller] Add convex tess benchmark.

lib/web_ui/lib/src/engine/text_editing/text_editing.dart, lib/web_ui/test/engine/text_editing_test.dart
In order to fix Safari autofill, we've had to give inactive elements non-zero size because Safari does not respect offscreen or 0-sized inputs, and this leads to broken autofill behavior (see: https://github.com/flutter/engine/pull/43058).
As part of these changes, we needed to disable pointer events for the parent `<form>` element so that we don't have pointer event collisions if users hover over or click into the invisible autofill elements within that form.
This led to an issue where offsets weren't being calculated correctly for "active" inputs because they relied on pointer events bubbling up and being caught by the form.  The fix is to explicitly set pointer events on the active inputs, so that we can correctly discern when our pointer event target is actually the input and …
=> [web] - fix Safari textfield selection bug

fml/memory/ref_counted_internal.h, fml/memory/weak_ptr_internal.h, fml/message_loop_task_queues.h, fml/platform/android/message_loop_android.h, fml/shared_thread_merger.h, fml/synchronization/semaphore.cc, fml/synchronization/semaphore.h
All changes were made automatically (i.e. with `--fix`).
=> Make `fml/...` compatible with `.clang_tidy`.

common/settings.h, shell/common/switches.cc, shell/common/switches.h, shell/common/switches_unittests.cc, shell/platform/android/io/flutter/embedding/engine/FlutterEngine.java, shell/platform/android/io/flutter/embedding/engine/FlutterJNI.java, shell/platform/android/io/flutter/embedding/engine/FlutterShellArgs.java, shell/platform/android/io/flutter/embedding/engine/loader/FlutterLoader.java, shell/platform/android/io/flutter/plugin/platform/PlatformViewsController.java, shell/platform/android/platform_view_android_jni_impl.cc
This reverts commit 87c3bf12b1ab51a70afe564589f828ec1758feeb. It is no longer needed as we have resolved the flickering issue in the ImageReader backend.
=> Revert "Add an AndroidManifest.xml flag to disable ImageReader backend Platform Views (#46430)"

shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm, shell/platform/darwin/ios/framework/Source/FlutterTextInputPluginTest.mm
After close examination of the UIKit's default string tokenizer, when querying the line enclosing the end of doc position **in forward direction**, we should return nil (regardless whether the position is forward or backward affinity). 
This aligns with the [API doc](https://developer.apple.com/documentation/uikit/uitextinputtokenizer/1614464-rangeenclosingposition?language=objc): 
> If the text position is at a text-unit boundary, it is considered enclosed only if the next position in the given direction is entirely enclosed.
Will cherry pick this soon. Otherwise it will be less and less important as users upgrade to iOS 17.1. 
It turns out my previous workaround PR https://github.com/flutter/engine/pull/46591 works only because our misuse of text affinity in our text input. …
=> [ios17][text_input]fix ios 17.0 keyboard freeze when switching languages (without relying on text affinity)

shell/platform/darwin/macos/framework/Source/FlutterEmbedderKeyResponderTest.mm, shell/platform/darwin/macos/framework/Source/FlutterSurfaceManagerTest.mm, shell/platform/darwin/macos/framework/Source/FlutterTextInputSemanticsObjectTest.mm, shell/platform/darwin/macos/framework/Source/FlutterThreadSynchronizerTest.mm
As part of the broader quest to reduce our dependence on OCMock in macOS embedder tests, this removes #includes of OCMock into files where OCMock is not actually used.
[CLA]: …
=> [macOS] Eliminate unused OCMock includes

lib/web_ui/lib/src/engine/configuration.dart, lib/web_ui/test/canvaskit/initialization/stores_config_test.dart, lib/web_ui/test/engine/configuration_test.dart
This change:
* Adds a boolean to `multiViewEnabled` (defaults to `false`).
* Removes unused `canvasKitMaximumSurfaces` value.
Part of: https://github.com/flutter/flutter/issues/137377
[CLA]: …
=> [web] JSConfig: Add multiViewEnabled value.

impeller/geometry/constants.h, impeller/geometry/half.h, impeller/geometry/scalar.h, impeller/geometry/vector.h, impeller/image/compressed_image.h
Usage of Scalar/Vector/Half types is desgned around implicit conversions today: we don't specifically convert to the correct generated header types, since that will depend on the target platform. Instead we rely on implicit conversions to handle this - any mistake there would still lead to a compilation error.
=> [Impeller] some clang tidies in impeller

shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm, shell/platform/darwin/ios/framework/Source/FlutterTextInputPluginTest.mm
This PR hides the system highlights in iOS 16 (except when scribble is enabled). 
Note that auto correction highlight is still drawn by flutter, so it still works. 
I don't think we need to CP this, since it's iOS 16 only, and iOS 17 is already out. 
Unlike iOS 17, the iOS 16 system highlight only respect the width provided by `firstRectForRange`, but not the height. I have audited all sizing related APIs in UITextInput (doc [here](https://developer.apple.com/documentation/uikit/uitextinput#1653155)), specifically, `firstRect(for:)`, `caretRect(for:)` and `selectionRects(for:)`, and they all return the correct height. 
The initial implementation of `firstRectForRange` (that returns the first selection rect) was introduced for the scribble feature on iPad (code …
=> [ios]fix ios 16 auto correction highlight showing on top left corner

.ci.yaml
The fuchsia v2 build is working correctly and we are ready to remove the v1 version.
Bug: https://github.com/flutter/flutter/issues/132600 …
=> Remove the linux fuchsia v1 build.

impeller/aiks/aiks_unittests.cc, impeller/aiks/testing/context_mock.h, impeller/aiks/testing/context_spy.cc, impeller/entity/contents/content_context.cc, impeller/entity/entity_pass.cc, impeller/entity/inline_pass_context.cc, impeller/renderer/backend/metal/command_buffer_mtl.h, impeller/renderer/backend/metal/command_buffer_mtl.mm, impeller/renderer/command_buffer.cc, impeller/renderer/command_buffer.h
This is a requirement for the "Remove Drawable Acquisition Latency" Change, but is otherwise a harmless improvement.
---
Submitting a command buffer causes the backend specific encoding logic to run. Metal is unique in that it is fairly easy to move this work into a background thread, allowing the engine to move onto creating the next command buffer. This improves throughput of the engine, at the cost of needing two slightly different APIs. Currently the GLES and Vulkan versions of this method still submit synchronously - for now that is out of scope as doing background work with those APIs has proved more challenging.
See also:
* https://github.com/flutter/engine/pull/42028
* https://github.com/flutter/flutter/issues/131698
Separately, as a requirement for the design in "Remove Drawable …
=> [Impeller] add async command submission for blit pass.

ci/licenses_golden/excluded_files, ci/licenses_golden/licenses_flutter, fml/BUILD.gn, fml/platform/darwin/weak_nsobject.h, fml/platform/darwin/weak_nsobject.mm, fml/platform/darwin/weak_nsobject_arc_unittests.mm, fml/platform/darwin/weak_nsobject_unittests.mm, shell/platform/darwin/ios/BUILD.gn, shell/platform/darwin/ios/framework/Source/FlutterEngine.mm, shell/platform/darwin/ios/framework/Source/FlutterKeyboardManager.h, shell/platform/darwin/ios/framework/Source/FlutterKeyboardManager.mm, shell/platform/darwin/ios/framework/Source/FlutterPlatformPlugin.h, shell/platform/darwin/ios/framework/Source/FlutterPlatformPlugin.mm, shell/platform/darwin/ios/framework/Source/FlutterPlatformPluginTest.mm, shell/platform/darwin/ios/framework/Source/FlutterViewController.mm, shell/platform/darwin/ios/framework/Source/FlutterViewController_Internal.h, shell/platform/darwin/ios/framework/Source/accessibility_bridge_test.mm, shell/platform/darwin/ios/platform_view_ios.h, shell/platform/darwin/ios/platform_view_ios.mm
Introduce weak_nsobject from chromium. 
There are some usages of weak_ptr wrapping Objective-C ids, weak_ptr is not really designed for ids and such usages are blocking the arc migration. 
This PR mostly copies the weak_nsobject from chromium, at the same hash that we copied the ARC/MRC compatible scoped_nsobject: https://chromium.googlesource.com/chromium/src/+/fd625125b8a6a3aceaf09993a5f74cfe5368b17f
To match how we used weak_ptr for those ids, I made some changes to the weak_nsobject:
- WeakNSObjects needs to be generated by a WeakNSObjectFactory. The WeakNSObjectFactory is owned by the objc class and acts as the generator of the WeakNSObjects. All the WeakNSObjects' derefing thread should be the same of the WeakNSObjectFactory's creation thread.
- chromuim's WeakNSObjects can be …
=> [ios] introduce weak_nsobject

shell/platform/darwin/macos/framework/Source/FlutterMenuPluginTest.mm
Runs all FlutterMenuPlugin tests in an AutoReleasepoolTest, which                   
ensures all allocations are cleaned up.                                             
Also extracts out some hackery into the FlutterMenuPluginTest fixture to            
ensure that NSApplication instantiates everything necessary to do menu              
bar manipulation.                                                                   
Also replaces the use of OCMock in FlutterMenuPluginTest.mm with a fake             
FakePluginRegistrar class. This avoids unnecessary use of OCMock in the             
tests, which has been responsible for flakiness in some tests, in                   
particular where the mock is used across threads. This test was not                 
problematic, but the fake makes …
=> [macOS] Clean up allocations in menu plugin test

shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm, shell/platform/darwin/ios/framework/Source/FlutterTextInputPluginTest.mm
CP for https://github.com/flutter/engine/pull/47566
https://github.com/flutter/flutter/issues/134716 …
=> [CP (beta)] [ios17][text_input]fix ios 17.0 keyboard freeze when switching languages

lib/ui/painting/color_filter.h, lib/ui/painting/engine_layer.h, lib/ui/painting/image_encoding_impl.h, lib/ui/painting/image_filter.h, lib/ui/painting/multi_frame_codec.cc, lib/ui/painting/multi_frame_codec.h, lib/ui/painting/single_frame_codec.cc, lib/ui/painting/single_frame_codec.h
All changes were made automatically (i.e. with `--fix`).
=> Make `lib/ui/painting/...` compatible with `.clang_tidy`.

shell/platform/darwin/macos/framework/Source/AccessibilityBridgeMacTest.mm, shell/platform/darwin/macos/framework/Source/FlutterEmbedderExternalTextureTest.mm, shell/platform/darwin/macos/framework/Source/FlutterViewControllerTest.mm
In cases where we subclassed gtest fixtures purely to get better naming for test output (i.e. displaying/filtering on AccessibilityBridgeMacTest instead of AutoreleasePoolTest, replace these with `using` declarations, which is equally effective and avoids actually subclassing.
This applies no semantic changes to the code or tests. …
=> [macOS] Replace fixture subclasses with usings

impeller/base/base_unittests.cc, impeller/base/thread.h
Had not used std::adopt_lock before and didn't realize that the unique lock destructor unlocks the mutex even when the mutex is adopted (which I suppose makes sense when you think about it). But I had added the annotations assuming the lock will remain if adopted. Found after a painful round of debugging the "safe" condition variables.
=> [Impeller] Fix issue where the lock was not re-acquired when the wait exits on CV.

.ci.yaml
See https://github.com/flutter/flutter/issues/138559.
I'll assign this as an infra bug after merging.
/cc @zanderso @dnfield for FYI.
=> Disable the `runIfNot` clauses in `.ci.yaml`, as they are unsafe.

flow/embedded_views.h, flow/testing/mock_embedder.cc, flow/testing/mock_embedder.h, shell/common/rasterizer_unittests.cc, shell/common/shell_test_external_view_embedder.cc, shell/common/shell_test_external_view_embedder.h, shell/platform/android/external_view_embedder/external_view_embedder.cc, shell/platform/android/external_view_embedder/external_view_embedder.h, shell/platform/darwin/ios/ios_external_view_embedder.h, shell/platform/darwin/ios/ios_external_view_embedder.mm, shell/platform/embedder/embedder_external_view_embedder.cc, shell/platform/embedder/embedder_external_view_embedder.h, shell/platform/fuchsia/flutter/external_view_embedder.cc, shell/platform/fuchsia/flutter/external_view_embedder.h, shell/platform/fuchsia/flutter/tests/platform_view_unittest.cc, shell/testing/tester_main.cc
Reverts flutter/engine#48130.
Now that the `runIf` clauses are omitted, CI should be a reliable source of truth.
=> Re-land "Make `flow/embedded_views.h` compatible with `.clang_tidy`."

lib/web_ui/lib/src/engine/canvaskit/layer_scene_builder.dart, lib/web_ui/lib/src/engine/canvaskit/layer_tree.dart, lib/web_ui/test/canvaskit/layer_test.dart
When calling `flatten()` to produce a `Picture` of a `Scene`, size the `PictureRecorder` to be the same size as the final image.
Fixes https://github.com/flutter/flutter/issues/138009
[CLA]: …
=> [canvaskit] Size the PictureRecorder when calling Scene.toImage

.ci.yaml, ci/builders/linux_android_emulator.json, testing/android_systrace_test.py
The emulator tests I added yesterday are failing because the systrace python test script uses features introduced in API 29, which causes the `perfetto` invocation to fail.
It's not essential that we run this test on lower API levels, so instead I'm making the script bail out in this case.
Other than that, the shard seems to be consistently passing, so I'm removing bringup.
=> Only run systrace test on API 29+, avoid building scenario app for 28

ci/licenses_golden/licenses_flutter, impeller/fixtures/dart_tests.dart, impeller/renderer/renderer_dart_unittests.cc, lib/gpu/BUILD.gn, lib/gpu/context.cc, lib/gpu/context.h, lib/gpu/device_buffer.cc, lib/gpu/device_buffer.h, lib/gpu/host_buffer.cc, lib/gpu/host_buffer.h, lib/gpu/lib/gpu.dart, lib/gpu/lib/src/context.dart, lib/gpu/lib/src/formats.dart, lib/gpu/lib/src/texture.dart, lib/gpu/texture.cc, lib/gpu/texture.h, lib/ui/painting.dart, lib/ui/painting/image.cc, lib/ui/painting/image.h
Going light on the docstrings so we can get to experimenting faster.
Textures! They can be written to by the host with `Texture.overwrite` and used as a `ui.Image` with `Texture.asImage`.
Right now we need to capture the "texture coordinate system" concept in order for Impeller to handle drawing textures in the right orientation on a `Canvas`. The user of the API may switch from host authoring to render target usage at any time. Similar to Unity, users targeting GLES will need to use this information to handle the texture flip when sampling from shaders -- this will be important to document comprehensively.
Flutter GPU textures being drawn with a CustomPainter:
https://github.com/flutter/engine/assets/919017/f0aed213-38a5-4e58-8160-0e956df1781e
=> [Flutter GPU] Add Textures.

shell/platform/common/accessibility_bridge.cc, shell/platform/common/accessibility_bridge_unittests.cc, shell/platform/windows/flutter_windows_view_unittests.cc
We have previously been using the `kToggleButton` role for any widget that has a toggled state. Our AX library does not expect this role to be used for switches, and so would not assign the checked state to switches for MSAA. As far as I can tell, the `Switch` is the only widget that uses the `toggled` semantic property (`ToggleButtons`, ironically, does not), so we ought to be able to swap in the `kSwitch` role, for which the proper states are presented. This will allow screen readers to announce the state of a switch.
https://github.com/flutter/flutter/issues/138500 …
=> Assign mojom `kSwitch` role to switches

shell/platform/darwin/ios/framework/Source/FlutterEnginePlatformViewTest.mm, shell/platform/darwin/ios/framework/Source/FlutterPlatformViewsTest.mm, shell/platform/darwin/ios/framework/Source/accessibility_bridge_test.mm, shell/platform/darwin/ios/ios_context.mm
Reverts flutter/engine#46217
cl/568091248 makes this safe to land again.
fyi @jonahwilliams @chinmaygarde
=> Reland "[Impeller] Fail if software backend is chosen and Impeller is enabled on iOS."

impeller/image/backends/skia/compressed_image_skia.h, impeller/playground/compute_playground_test.h, impeller/renderer/backend/metal/context_mtl.h, impeller/renderer/backend/metal/context_mtl.mm, impeller/renderer/backend/metal/sampler_library_mtl.h, impeller/renderer/backend/vulkan/blit_pass_vk.h, impeller/renderer/backend/vulkan/shared_object_vk.h, impeller/renderer/backend/vulkan/swapchain_impl_vk.cc, impeller/renderer/backend/vulkan/swapchain_impl_vk.h, impeller/renderer/context.h, impeller/renderer/renderer.h, impeller/renderer/testing/mocks.h, impeller/scene/scene_context.h, impeller/typographer/backends/skia/typeface_skia.h, impeller/typographer/backends/stb/typeface_stb.cc, impeller/typographer/backends/stb/typeface_stb.h
I moved [`scene_context.h` to another PR](https://github.com/flutter/engine/pull/48194), and here are the boring remains.
=> Make `impeller/...` compatible with `.clang-tidy`.

impeller/typographer/BUILD.gn, impeller/typographer/typographer_unittests.cc, lib/web_ui/skwasm/BUILD.gn, lib/web_ui/skwasm/fonts.cpp, shell/platform/android/BUILD.gn, shell/platform/android/flutter_main.cc, shell/platform/android/io/flutter/embedding/engine/FlutterJNI.java, third_party/txt/src/txt/platform.h
Skia is removing this API, so clients must track a default FontMgr if they want one. See https://issues.skia.org/issues/305780908 …
=> Replace calls to SkFontMgr::RefDefault

lib/web_ui/lib/src/engine/platform_dispatcher.dart, lib/web_ui/lib/src/engine/view_embedder/dimensions_provider/custom_element_dimensions_provider.dart, lib/web_ui/lib/src/engine/view_embedder/dimensions_provider/dimensions_provider.dart, lib/web_ui/lib/src/engine/view_embedder/dimensions_provider/full_page_dimensions_provider.dart, lib/web_ui/lib/src/engine/window.dart, lib/web_ui/test/engine/platform_dispatcher/platform_dispatcher_test.dart, lib/web_ui/test/engine/window_test.dart
- New `EngineFlutterView.dispose()` to cleanup when the view is removed (and in hot restart).
- `EnginePlatformDispatcher.dispose()` now disposes of all of its registered views.
=> [web] EngineFlutterView.dispose()

testing/dart/BUILD.gn, testing/dart/canvas_test.dart
Closes https://github.com/flutter/flutter/issues/138501.
---
It would be nice to turn this into a test-fixture, and create a better local environment.
Here is how to run it locally:
```bash
cd $ENGINE_SRC
out/host_debug_unopt_arm64/flutter_tester \
--force-multithreading \
--disable-observatory \
--use-test-fonts \
--icu-data-file-path=out/host_debug_unopt_arm64/icudtl.dat \
--flutter-assets-dir=out/host_debug_unopt_arm64/gen/flutter/lib/ui/assets \
--disable-asset-fonts \
--enable-impeller \
out/host_debug_unopt_arm64/gen/canvas_test.dart.dill
open out/host_debug_unopt_arm64/gen/skia_gold_canvas_test.dart
```
=> [Impeller] Write a text-decoration test at the `dart:ui` layer

vulkan/vulkan_debug_report.cc, vulkan/vulkan_debug_report.h
Missed this straggler in a previous PR. Ezpz.
=> Make `vulkan/...` compatible with `.clang_tidy`.

common/settings.h
See https://github.com/flutter/flutter/issues/138750.
=> Silence a lint in `common/settings.h` in order to turn on `clang_tidy`.

impeller/scene/scene_context.cc, impeller/scene/scene_context.h
Some discussion here: https://discord.com/channels/608014603317936148/1175215129135153202.
In short, `*<std::optional>` is [undefined behavior](https://en.cppreference.com/w/cpp/utility/optional/operator*). After talking to @bdero we are considering that this should never happen.
I thought of a few different approaches here, none of them are great. However given that this class is used quite minimally, this seems to jive with similar patterns we're using in scene/scene_context.
---
Feel free to push back or suggest alternatives, mostly proposing this to get brain juices flowing.
=> [Impeller] Try replacing `*desc` with value/is_valid checks.

impeller/entity/contents/filters/filter_contents.cc, impeller/entity/contents/filters/gaussian_blur_filter_contents.cc, impeller/entity/contents/filters/gaussian_blur_filter_contents_unittests.cc
This makes the blurred item have a halo effect that is rendered outside of the bounds of the original thing that was rendered.
issue: https://github.com/flutter/flutter/issues/131580
[CLA]: …
=> [Impeller] implements gaussian "blur halo"

impeller/entity/entity_pass.cc, impeller/entity/inline_pass_context.cc, impeller/entity/inline_pass_context.h, impeller/renderer/command.h, impeller/renderer/render_pass.h, impeller/renderer/renderer_unittests.cc
Commands are massive 500 byte objects, re-allocating this vector while recording them can actually add a substantial amount of overhead to applications with lots of drawing commands. Sizing to npot so that underestimating by a few commands doesn't force us to immediately copy all command objects.
This is still a herustic driven approach. An alternative exact approach would have entities/contents describe how many commands they would add. This may be more important for stencil then cover (depending on how we do it) since some contents would need to create two commands.
=> [Impeller] preallocate command buffer to next power of two of entity list.

skia/modules/skcms/BUILD.gn
This should address https://github.com/flutter/flutter/issues/138838 which is blocking the skia roll.
This basically ports over the build rule changes from https://skia-review.googlesource.com/c/skia/+/777538
=> Update skia build file to account for new skcms changes.

impeller/renderer/testing/mocks.h, shell/platform/linux/fl_engine_private.h, shell/platform/linux/fl_renderer.h, shell/platform/linux/fl_settings.h, shell/platform/linux/public/flutter_linux/fl_json_message_codec.h, shell/platform/linux/public/flutter_linux/fl_message_codec.h, shell/platform/linux/public/flutter_linux/fl_method_response.h, shell/platform/linux/testing/mock_binary_messenger.cc, shell/platform/linux/testing/mock_binary_messenger.h, shell/platform/linux/testing/mock_im_context.h, shell/platform/linux/testing/mock_settings.h, vulkan/vulkan_application.cc, vulkan/vulkan_application.h
Based off the [failures](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8763786250936903249/+/u/test:_test:_lint_host_debug/stdout) in https://github.com/flutter/engine/pull/48145.
Nothing particularly interesting.
=> Yet more compliance with `.clang_tidy`, stragglers edition.

build/secondary/third_party/vulkan_validation_layers/BUILD.gn, shell/platform/android/BUILD.gn
fixes https://github.com/flutter/flutter/issues/138535
test coverage: existing integration tests in flutter repo which look for validation layers
I also verified locally that the `libc++.so` is no longer present and that it runs correctly.
```
$ find lib/arm64-v8a/
lib/arm64-v8a/
lib/arm64-v8a//libflutter.so
lib/arm64-v8a//libVkLayer_khronos_validation.so
``` …
=> [Impeller] Switched to static linked libc++ in vulkan validation layers.

impeller/aiks/canvas.cc
Extremely minor micro optimization. Dont copy the paint too early.
Before
13/269 = ~5%
After:
3/262 = ~1%
=> [Impeller] Dont copy the paint until we're sure that the RRect blur optimization will apply.

impeller/base/allocation.cc, impeller/base/allocation.h, impeller/core/host_buffer.cc, impeller/core/host_buffer.h, impeller/renderer/host_buffer_unittests.cc
std::shared_from_this is actually incredibly slow, and dominates the cost of host buffer allocation at 20x more expensive than the memcpy. We can remove the usage of shared_from_this by making an internal class hold the actual allocation/buffer state instead.
146 ms / 647ms = ~20%
33 ms / 540 ms = ~6%
=> [Impeller] make host buffer state internally ref counted.

impeller/compiler/code_gen_template.h, impeller/compiler/reflector.cc
No point in passing by value and moving, just pass a const ref through. Trivial performance improvement.
```cpp
/// Bind uniform buffer for resource named FragInfo.
static bool BindFragInfo(ResourceBinder& command, BufferView view) {
return command.BindResource(ShaderStage::kFragment, kResourceFragInfo, kMetadataFragInfo, std::move(view));
}
/// Bind combined image sampler for resource named texture_sampler.
static bool BindTextureSampler(ResourceBinder& command, std::shared_ptr<const Texture> texture, std::shared_ptr<const Sampler> sampler) {
return command.BindResource(ShaderStage::kFragment, kResourceTextureSampler, kMetadataTextureSampler, std::move(texture), std::move(sampler));
}
```
```cpp
/// Bind uniform buffer for resource named FragInfo.
static bool BindFragInfo(ResourceBinder& …
```
=> [Impeller] pass const ref to binding helpers.

impeller/entity/contents/contents.cc, impeller/renderer/render_pass.cc, impeller/renderer/render_pass.h, impeller/renderer/renderer_unittests.cc
Otherwise we do three hashmap lookups everything we call OptionsFromPass(AndEntity) in a contents.
16 / 392 = 4%
6/ 458 = 1.3%
=> [Impeller] cache render target properties on Render Pass.

lib/web_ui/lib/src/engine/app_bootstrap.dart, lib/web_ui/lib/src/engine/platform_dispatcher.dart, lib/web_ui/lib/src/engine/view_embedder/flutter_view_manager.dart, lib/web_ui/lib/src/engine/window.dart, lib/web_ui/test/engine/platform_dispatcher/platform_dispatcher_test.dart, lib/web_ui/test/engine/routing_test.dart, lib/web_ui/test/engine/surface/platform_view_test.dart, lib/web_ui/test/engine/view_embedder/flutter_view_manager_test.dart, lib/web_ui/test/engine/window_test.dart
- Auto-generate view IDs.
- Views don't auto-register/auto-unregister anymore.
- Remove `EnginePlatformDispatcher.registerView/unregisterView` methods.
- Add `FlutterViewManager.createAndRegisterView/disposeAndUnregisterView/dispose` methods.
- Hook the `addView`/`removeView` JS APIs to `FlutterViewManager`.
=> [web] Hook the new JS API to the FlutterViewManager

shell/platform/darwin/ios/framework/Source/FlutterPlatformPlugin.mm, shell/platform/darwin/ios/framework/Source/FlutterPlatformPluginTest.mm
Fix https://github.com/flutter/flutter/issues/138604 and https://github.com/flutter/flutter/issues/138671
Related PR https://github.com/flutter/engine/pull/45351 …
=> Fix not being able to hide iOS status bar via setEnabledSystemUIMode

impeller/renderer/backend/gles/capabilities_gles.cc, impeller/renderer/backend/gles/test/capabilities_unittests.cc
This extension only implies decal support for OES textures. Remove it from the check for generic decal support.
In practice i think it would be unlikely that a driver supports this and not regular decal, but that would only make the bugs this may cause even harder to track down.
=> [Impeller] OES extension does not apply to regular textures for decal support

impeller/tessellator/tessellator.cc, impeller/tessellator/tessellator.h, impeller/tessellator/tessellator_unittests.cc
Forgot about the winding order. partially reverts https://github.com/flutter/engine/pull/46282
See https://github.com/flutter/flutter/issues/138598
Reopens https://github.com/flutter/flutter/issues/135458
=> [Impeller] revert non-zero tessellation optimization.

impeller/entity/contents/filters/directional_gaussian_blur_filter_contents_unittests.cc, impeller/entity/contents/filters/gaussian_blur_filter_contents_unittests.cc
fixes https://github.com/flutter/flutter/issues/138955 …
=> [Impeller] updated gaussian blur tests to use device private textures

lib/ui/platform_dispatcher.dart, lib/ui/window.dart, lib/ui/window/platform_configuration.cc, lib/ui/window/platform_configuration.h, lib/web_ui/lib/platform_dispatcher.dart, lib/web_ui/lib/src/engine/window.dart, lib/web_ui/lib/window.dart, runtime/runtime_controller.cc, runtime/runtime_controller.h, testing/dart/BUILD.gn, testing/dart/platform_dispatcher_test.dart
Towards https://github.com/flutter/flutter/issues/134501.
This PR makes the following changes to the public dart:ui API:
* It adds the `FlutterView.pysicalConstraints` property that describes max and min width and height for a view. The framework is allowed to size the `FlutterView` to any `Size` that meets these constraints.
* It adds an optional `size` argument to `FlutterView.render`. The framework provides the chosen `Size` that meets the aforementioned constraints to the `render` method. If the `FlutterView.pysicalConstraints` are tight (minHeight == maxHeight and minWidth == maxWidth) the argument is optional to remain backwards compatible. In all other cases, a `Size` must be provided.
* It adds a `ViewConstraints` class, which is basically the `dart:ui` version of `BoxConstraints` …
=> Dynamic view sizing [dart:ui]

display_list/display_list.cc, flow/embedded_views.cc, flow/surface_frame.cc, flow/surface_frame_unittests.cc, lib/ui/painting/picture_recorder.cc
The root slice of a surface frame was requesting the construction of an RTree from its DisplayList when it was built from a layer tree, but since the layer tree already does branch culling, it would not benefit from any further culling during `DisplayList::Dispatch`. Further, if there are platform views present in the layer tree then they will need an RTree to accurately convey "pixel ownership" information to the platform, but the root slice lives below any and all platform views, so it is the only slice that doesn't need an RTree for that case.
The cost of having an RTree in that slice was the accumulation of information and lists of rects that would never prove useful.
=> SurfaceFrame root DisplayLists will no longer prepare an RTree

display_list/BUILD.gn, display_list/testing/BUILD.gn, display_list/testing/dl_rendering_unittests.cc, display_list/testing/dl_test_snippets.cc, flow/BUILD.gn, flow/layers/performance_overlay_layer.cc, impeller/aiks/BUILD.gn, impeller/aiks/aiks_unittests.cc, impeller/display_list/BUILD.gn, impeller/display_list/dl_playground.cc, impeller/typographer/typographer_unittests.cc, lib/ui/text/asset_manager_font_provider.cc, lib/ui/text/font_collection.cc, runtime/BUILD.gn, runtime/test_font_data.cc
Similar to https://github.com/flutter/engine/pull/48179, Flutter needs to stop depending on the default font manager, which the `SkTypeface::Make*` calls do implicitly
[CLA]: …
=> Replace all calls to SkTypeface::Make with SkFontMgr ones

impeller/aiks/aiks_unittests.cc, impeller/aiks/canvas.cc, impeller/entity/contents/solid_rrect_blur_contents.cc
<0 sigma render incorrectly with wide gamut, but these shouldn't produce shadows at all as far as I can tell.
https://github.com/flutter/flutter/issues/138842
=> [Impeller] Skip mask blur with 0 sigma.

display_list/benchmarking/dl_complexity_helper.h, flow/layers/display_list_layer_unittests.cc, lib/ui/hooks_unittests.cc, vulkan/vulkan_application.cc, vulkan/vulkan_backbuffer.cc, vulkan/vulkan_device.cc
The variable length array extension will be disabled by default in the next roll of Clang.
=> Remove use of variable length arrays

ci/licenses_golden/excluded_files, third_party/tonic/file_loader/file_loader.cc, third_party/tonic/file_loader/file_loader.h, third_party/tonic/file_loader/file_loader_fuchsia.cc, third_party/tonic/file_loader/file_loader_posix.cc, third_party/tonic/file_loader/file_loader_unittests.cc, third_party/tonic/file_loader/file_loader_win.cc, third_party/tonic/tests/BUILD.gn
The tonic method currently returns `///Users/test/foo` instead of `file:///Users/test/foo`.
Found while looking into making isolate spawning for flutter_tester work.
=> Fix CanonicalizeURL for file schema

shell/platform/linux/fl_platform_plugin.cc, shell/platform/linux/fl_platform_plugin_test.cc
GtkApplication windows contain a reference back to the application. This means the MyApplication object in the Flutter application never disposes. We workaround this by removing these references before we quit. This occurs for all GTK applications that quit using this method, see https://gitlab.gnome.org/GNOME/gtk/-/issues/6190. This may be fixed upstream at some point but the proposed workaround should solve the problem for all versions and not conflict with any upstream solution.
Fixes https://github.com/flutter/flutter/issues/136582
=> Fix the application not disposing by breaking circular references on quit

impeller/entity/contents/filters/filter_contents.cc, impeller/renderer/backend/vulkan/descriptor_pool_vk_unittests.cc
This test worked by 1) releasing an item to be destructed on a background thead 2) adding a second item to this queue with a waitable event.
The idea being you could wait for the event and that would tell you when 1) was complete. Unfortunately these items are released by being placed into a std::vector, which destroyed in _reverse_ order. Somtimes when the test state was queried the work was done and sometimes it wasn't
To fix this, add a second waitable event that guarantees that both the first event and the original event have finished - because we do not add these event until the first is destructed and we do not add items to the destroy list while it is in progress.
=> [Impeller] fix descriptor pool recycler test flake.

impeller/compiler/compiler_test.cc, impeller/compiler/compiler_test.h, impeller/compiler/compiler_unittests.cc, impeller/compiler/spirv_sksl.cc, impeller/fixtures/BUILD.gn, impeller/fixtures/texture_lookup.frag
Fixes https://github.com/flutter/flutter/issues/139017
When multiplying by the texture size we need to add parens in case the texture argument is actually an expression and not a single value.
=> [Impeller] fix order of operations in SkSL generated texture lookup.

lib/web_ui/lib/src/engine/browser_detection.dart, lib/web_ui/lib/src/engine/dom.dart, lib/web_ui/test/canvaskit/no_create_image_bitmap_test.dart
On Chrome 110 or older, there is a bug where an ImageBitmap will be read back upside down if it is stored upside down on the GPU. This only happens on Windows. So if we are on Windows and running on Chrome 110 or older, then fall back to `drawImage` based rendering.
Fixes https://github.com/flutter/flutter/issues/138827 …
=> [canvaskit] Disable createImageBitmap support on Chrome 110 or older on Windows.

DEPS, shell/platform/android/BUILD.gn
CP of the flutter/engine part of https://github.com/flutter/engine/pull/48290.
=> [CP][Impeller] Switched to static linked libc++ in vulkan validation layers.

lib/web_ui/lib/src/engine/canvas_pool.dart, lib/web_ui/lib/src/engine/canvaskit/canvas.dart, lib/web_ui/lib/src/engine/canvaskit/embedded_views.dart, lib/web_ui/lib/src/engine/canvaskit/layer_tree.dart, lib/web_ui/lib/src/engine/canvaskit/rasterizer.dart, lib/web_ui/lib/src/engine/canvaskit/render_canvas.dart, lib/web_ui/lib/src/engine/canvaskit/renderer.dart, lib/web_ui/lib/src/engine/html/bitmap_canvas.dart, lib/web_ui/lib/src/engine/html/scene_builder.dart, lib/web_ui/lib/src/engine/initialization.dart, lib/web_ui/lib/src/engine/platform_dispatcher.dart, lib/web_ui/lib/src/engine/scene_view.dart, lib/web_ui/lib/src/engine/skwasm/skwasm_impl/canvas.dart
- No implicit view in mult-view mode.
- `window.devicePixelRatio` => `EngineFlutterDisplay.instance.devicePixelRatio`.
- `window.physicalSize` => `view.physicalSize`.
- Remove `LayerTree.frameSize`.
- `defaultRouteName` is set to `/` when there's no implicit view.
- All routing operations are noops in multi-view mode.
With these changes, I was able to run all examples in https://github.com/goderbauer/mvp without an implicit view.
=> [web] No implicit view in multi-view mode

impeller/entity/contents/filters/filter_contents.cc, impeller/entity/contents/filters/gaussian_blur_filter_contents.cc
fixes https://github.com/flutter/flutter/issues/139317
test: AiksTest.CanRenderClippedBlur
This works by double padding.  First it applies the padding to clip region, then it add a transparent gutter around the snapshot to account for any of the expanded clip region that was ignored.  This is suboptimal since there maybe a considerable region for which blur is calculated that is clipped.  That can be optimized in the future by adjusting the UVs in the blur phases to match the clip region.
[test-exempt]: …
=> [Impeller] Started expanding the blur clip region

shell/platform/darwin/ios/framework/Source/FlutterPlatformPlugin.mm, shell/platform/darwin/ios/framework/Source/FlutterPlatformPluginTest.mm, shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.h
Fixes https://github.com/flutter/flutter/issues/138550
Original PR: https://github.com/flutter/engine/pull/48220
=> [CP] Fix crash on choosing share in selection controls on ipad

runtime/dart_isolate.cc, runtime/dart_isolate.h, runtime/dart_isolate_unittests.cc, runtime/isolate_configuration.cc, runtime/isolate_configuration.h
Found by @mraleph while looking at flutter_tester related things with me.
I took some suggestions from him and added a test. This should eventually help speed up running large multi-file test suites.
The test is a little bit wonky because we don't have great inspection points (e.g. something to mock or examine from a test). It should break if we change the way we load kernel assets in the test harness, and is verifying that we only ask for the test asset once where we used to ask for it twice.
=> Avoid reloading the kernel snapshot when spawning an isolate in the same group

lib/web_ui/lib/src/engine/canvaskit/image_filter.dart, lib/web_ui/lib/src/engine/canvaskit/renderer.dart, lib/web_ui/test/canvaskit/filter_test.dart, lib/web_ui/test/ui/filters_test.dart
Adds ImageFilter.compose support in CanvasKit. Previously this would crash.
Fixes https://github.com/flutter/flutter/issues/120123 …
=> [canvaskit] Add ImageFilter.compose

impeller/entity/geometry/point_field_geometry.cc
Fixes: https://github.com/flutter/flutter/issues/138877
The existing golden tests were already showing this bug, but we didn't see it. With this fix the size of the squares should be the same as the circle for the round caps in the DrawPoints playground goldens.
Test exemption request: This fix is covered by existing golden tests.
=> [Impeller] Fix size of squares in DrawPoints(PointMode).

impeller/aiks/aiks_unittests.cc, impeller/aiks/canvas.cc, impeller/entity/geometry/ellipse_geometry.cc, impeller/entity/geometry/ellipse_geometry.h, impeller/entity/geometry/geometry.cc, impeller/entity/geometry/geometry.h, impeller/entity/geometry/line_geometry.cc, impeller/entity/geometry/line_geometry.h, impeller/tessellator/circle_tessellator.cc, impeller/tessellator/circle_tessellator.h, impeller/tessellator/circle_tessellator_unittests.cc
Similar work as done for filled circles in https://github.com/flutter/engine/pull/48103, stroked circles can also be directly tessellated using the same internal data structures used for filled circles.
=> [Impeller] Directly tessellate stroked circles.

lib/web_ui/dev/felt
The ulimit logic has been failing for me for months now and felt still ran fine. I think we don't need it any more.
Also add the `-i` option for incremental runs of `felt`. It causes felt to start faster because it doesn't run `pub get`. In the future, we can also run felt from the snapshot for even faster start-up.
=> [web] remove ulimit and add -i to felt

impeller/aiks/aiks_context.h, impeller/aiks/canvas.h, impeller/aiks/paint_pass_delegate.h, impeller/core/allocator.h, impeller/core/sampler.h, impeller/core/sampler_descriptor.h, impeller/renderer/context.h, impeller/renderer/sampler_library.h
Towards https://github.com/flutter/flutter/issues/133417#issuecomment-1839273553
I'll request a test exemption for this as it's a semantics-only refactor.
There are still a bunch of other forward declares in Impeller that make things confusing for tooling, but some of those will require less trivial changes to interfaces.
=> Remove some trivial forward declares from Impeller

impeller/core/resource_binder.h, impeller/renderer/command.cc, impeller/renderer/command.h, impeller/renderer/compute_command.cc, impeller/renderer/compute_command.h
Most of the time we are passing an rvalue into this functions anyway, so in theory moving should be faster. Right?
=> [Impeller] Move BufferView/Texture/Sampler when binding.

impeller/aiks/aiks_unittests.cc, impeller/aiks/canvas.cc, impeller/aiks/canvas.h, impeller/aiks/canvas_recorder.h, impeller/aiks/canvas_recorder_unittests.cc, impeller/aiks/canvas_unittests.cc, impeller/aiks/paint.cc, impeller/aiks/paint.h, impeller/display_list/dl_dispatcher.cc, impeller/entity/contents/solid_color_contents.cc, impeller/entity/contents/solid_color_contents.h, impeller/entity/entity_unittests.cc, impeller/entity/geometry/fill_path_geometry.cc, impeller/entity/geometry/fill_path_geometry.h, impeller/entity/geometry/geometry.cc, impeller/entity/geometry/geometry.h, impeller/entity/geometry/geometry_unittests.cc, impeller/entity/geometry/stroke_path_geometry.cc, impeller/entity/geometry/stroke_path_geometry.h, impeller/geometry/geometry_benchmarks.cc, impeller/geometry/path.cc, impeller/geometry/path.h, impeller/geometry/path_builder.cc, impeller/geometry/path_unittests.cc
From looking at profiles, we're always copying paths at least once when recording commands. By deleting the copy constructor, I cna ensure that we're always either moving or explicitly cloning the Path object.
Or, now that I fixed all the moves I could add the copy constructor back.
=> [Impeller] Remove impeller::Path copy constructor.

impeller/entity/contents/checkerboard_contents_unittests.cc, impeller/entity/contents/tiled_texture_contents_unittests.cc, impeller/entity/contents/vertices_contents_unittests.cc, impeller/playground/playground_test.h
And make it illegal to do so in the future. Now, making such a mistake will lead to a linker error complaining about duplicate definitions of `kYouInstantiatedEntityTestMultipleTimes`.
Fixes https://github.com/flutter/flutter/issues/139090
=> [Impeller] Remove duplicate entity test suite instantiations.

impeller/aiks/aiks_unittests.cc, impeller/aiks/canvas.cc, impeller/entity/contents/text_contents.cc, impeller/entity/contents/text_contents.h, impeller/entity/shaders/glyph_atlas_color.frag, impeller/tools/malioc.json
Fixes https://github.com/flutter/flutter/issues/138819
Emoji glyphs normally ignore their text color (except for alpha channel). Text shadows are created by rendering the font with the shadow color as the text color and then applying a blur. If this is done to an emoji, we need to apply the text color so that the shadow has the correct color.
=> [Impeller] Render emoji shadows with correct colors.

impeller/aiks/aiks_unittests.cc, impeller/aiks/canvas.cc, impeller/entity/contents/solid_rrect_blur_contents.cc
<0 sigma render incorrectly with wide gamut, but these shouldn't produce shadows at all as far as I can tell.
https://github.com/flutter/flutter/issues/138842
=> [CP][Impeller] Skip mask blur with 0 sigma. (#48457)

shell/platform/darwin/ios/framework/Source/FlutterPlatformViews_Internal.mm, third_party/accessibility/ax/platform/ax_unique_id_unittest.cc
I was shocked this was even legal earlier. But a new Clang roll makes this an a warning which gets converted into an error.
I attempted to roll to the Clang roll the roller did and fixed the issues I found. Hopefully, the next roll is unblocked.
Original failure: https://github.com/flutter/engine/pull/48563
=> Avoid non-const sizes in VLAs.

impeller/docs/specialization_constants.md, impeller/entity/contents/content_context.cc, impeller/entity/contents/content_context.h, impeller/entity/entity_unittests.cc, impeller/entity/shaders/blending/advanced_blend.frag, impeller/entity/shaders/blending/framebuffer_blend.frag, impeller/entity/shaders/blending/porter_duff_blend.frag, impeller/entity/shaders/morphology_filter.frag, impeller/renderer/backend/gles/proc_table_gles.cc, impeller/renderer/backend/gles/proc_table_gles.h, impeller/renderer/backend/gles/test/specialization_constants_unittests.cc, impeller/renderer/backend/metal/shader_function_mtl.h, impeller/renderer/backend/metal/shader_function_mtl.mm, impeller/renderer/backend/vulkan/pipeline_library_vk.cc, impeller/renderer/pipeline_builder.h, impeller/renderer/pipeline_descriptor.cc, impeller/renderer/pipeline_descriptor.h
This provides more flexibility and works around issues seen when using int constants in GLSL on some devices.
Fixes https://github.com/flutter/flutter/issues/139408
=> [Impeller] Declare specialization constants as floats.

shell/platform/windows/angle_surface_manager.cc, shell/platform/windows/angle_surface_manager.h, shell/platform/windows/flutter_window.cc, shell/platform/windows/flutter_window.h, shell/platform/windows/flutter_windows_engine.cc, shell/platform/windows/flutter_windows_engine.h, shell/platform/windows/flutter_windows_view.cc, shell/platform/windows/flutter_windows_view_unittests.cc, shell/platform/windows/testing/mock_window_binding_handler.h, shell/platform/windows/window_binding_handler.h
The EGL context can only be used by a single thread at a time. Currently:
1. The platform thread uses the EGL context to configure the render surface when a `FlutterViewController` is created
2. The raster thread uses the EGL context to render
In a multi-view world, a `FlutterViewController` can be created in parallel to a rendering operation. This results in multiple threads attempting to use the EGL context in parallel, which can crash (see https://github.com/flutter/flutter/issues/137973).
This change configures the render surface on the raster thread if the raster thread exists (aka the engine is running).
Addresses https://github.com/flutter/flutter/issues/137973 …
=> [Windows] Set swap interval on raster thread after startup

impeller/aiks/aiks_unittests.cc, impeller/entity/entity_pass.cc, impeller/entity/entity_unittests.cc
If all previous elements were skipped due to clear color optimization, then the clear color must be rendered as an input to the advanced blend if framebuffer fetch is not available.
=> [Impeller] Provide the clear color to an advanced blend if it was optimized out

impeller/compiler/code_gen_template.h, impeller/core/resource_binder.h, impeller/core/shader_types.h, impeller/entity/contents/checkerboard_contents.cc, impeller/entity/contents/filters/border_mask_blur_filter_contents.cc, impeller/entity/contents/filters/color_matrix_filter_contents.cc, impeller/entity/contents/filters/directional_gaussian_blur_filter_contents.cc, impeller/entity/contents/filters/gaussian_blur_filter_contents.cc, impeller/entity/contents/filters/linear_to_srgb_filter_contents.cc, impeller/entity/contents/filters/morphology_filter_contents.cc, impeller/entity/contents/filters/srgb_to_linear_filter_contents.cc, impeller/entity/contents/filters/yuv_to_rgb_filter_contents.cc, impeller/entity/contents/runtime_effect_contents.cc, impeller/entity/contents/test/contents_test_helpers.h, impeller/entity/contents/texture_contents.cc, impeller/entity/geometry/geometry.h, impeller/renderer/backend/gles/buffer_bindings_gles.cc, impeller/renderer/backend/metal/compute_pass_mtl.mm, impeller/renderer/backend/metal/render_pass_mtl.mm, impeller/renderer/backend/vulkan/binding_helpers_vk.cc, impeller/renderer/backend/vulkan/compute_pass_vk.cc, impeller/renderer/backend/vulkan/render_pass_vk.cc, impeller/renderer/command.cc, impeller/renderer/command.h, impeller/renderer/compute_command.cc, impeller/renderer/compute_command.h, lib/gpu/render_pass.cc
Places the binding data in a vector, since they key was only meaningful on metal but not used anywhere. I don't think that we need to specificially handle the case where our own contents bind the same contents multiple times, but interested to discuss if folks disagree.
=> [Impeller] Store Buffer/Texture bindings in vector instead of map.

build/secondary/flutter/third_party/glfw/BUILD.gn, display_list/testing/dl_rendering_unittests.cc, flow/layers/performance_overlay_layer.cc, impeller/entity/BUILD.gn, impeller/entity/entity_unittests.cc, impeller/typographer/BUILD.gn, impeller/typographer/typographer_unittests.cc, shell/common/BUILD.gn, shell/common/dl_op_spy_unittests.cc, shell/platform/fuchsia/flutter/BUILD.gn, skia/BUILD.gn, skia/flutter_defines.gni, third_party/txt/src/txt/platform.cc, third_party/txt/src/txt/platform_android.cc, third_party/txt/src/txt/platform_fuchsia.cc, third_party/txt/src/txt/platform_linux.cc, third_party/txt/src/txt/platform_mac.mm
This reverts commit ab89510f4e1eeea49ec01dd55656b126a4b06b19.
The flutter/tests/skp_generator test (running in flutter_tester on Linux) was failing, along with some customer tests.
=> Revert "Replace use of Fontmgr::RefDefault with explicit creation calls"

build/secondary/flutter/third_party/glfw/BUILD.gn, display_list/testing/dl_rendering_unittests.cc, flow/layers/performance_overlay_layer.cc, impeller/entity/BUILD.gn, impeller/entity/entity_unittests.cc, impeller/typographer/BUILD.gn, impeller/typographer/typographer_unittests.cc, shell/common/BUILD.gn, shell/common/dl_op_spy_unittests.cc, shell/platform/fuchsia/flutter/BUILD.gn, skia/BUILD.gn, skia/flutter_defines.gni, third_party/txt/src/txt/platform.cc, third_party/txt/src/txt/platform_android.cc, third_party/txt/src/txt/platform_fuchsia.cc, third_party/txt/src/txt/platform_linux.cc, third_party/txt/src/txt/platform_mac.mm
Relands https://github.com/flutter/engine/pull/48571 with a patch that uses the directory-based SkFontMgr as a default font manager on Linux
=> Reland "Replace use of Fontmgr::RefDefault with explicit creation calls"

DEPS
See https://github.com/flutter/flutter/wiki/Engine-pre‐submits-and-post‐submits#post-submit.
=> Add a note that rolling clang_version manually is dangerous.

impeller/aiks/aiks_unittests.cc, impeller/entity/contents/filters/filter_contents.cc, impeller/entity/contents/filters/gaussian_blur_filter_contents.cc, impeller/entity/contents/filters/gaussian_blur_filter_contents.h, impeller/entity/contents/filters/gaussian_blur_filter_contents_unittests.cc
fixes https://github.com/flutter/flutter/issues/139165 …
=> [Impeller] implements new blur tile mode

shell/platform/android/android_shell_holder_unittests.cc, shell/platform/android/image_external_texture.cc, shell/platform/android/io/flutter/embedding/engine/FlutterJNI.java, shell/platform/android/io/flutter/embedding/engine/renderer/FlutterRenderer.java, shell/platform/android/io/flutter/view/FlutterView.java, shell/platform/android/io/flutter/view/TextureRegistry.java, shell/platform/android/jni/jni_mock.h, shell/platform/android/jni/platform_view_android_jni.h, shell/platform/android/platform_view_android_jni_impl.cc, shell/platform/android/platform_view_android_jni_impl.h, shell/platform/android/test/io/flutter/embedding/engine/renderer/FlutterRendererTest.java, shell/platform/android/test/io/flutter/plugin/platform/PlatformViewsControllerTest.java
The `SurfaceProducer` interface exposes only exposes a Surface to render on, abstracting away the consumer side of the external texture.
The `ImageReaderSurfaceProducer` implementation of this interface is included as well as a basic test of that code.
Also, a small refactor so that `ImageTexture` and `ImageReaderSurfaceProducer` can use the same native C++ code in the engine.
Subsequent CLs will need to address the following:
- A SurfaceTextureSurfaceProducer (your eyes are probably bleeding from that name) implementation is needed so we can support GL based systems.
- Update Platform Views to use this new SurfaceProducer type instead of the legacy types.
- Deprecate SurfaceTexture and ImageTexture external texture types.
Related issue …
=> Add a new external texture type to Android embedder

impeller/core/capture.cc, impeller/core/capture.h
I'm not exactly sure why, but this seems to stop the allocation of capture labels in release mode.
Fixes https://github.com/flutter/flutter/issues/138908
=> [Impeller] dont allocate capture strings in release mode.

impeller/renderer/backend/vulkan/allocator_vk.cc, impeller/renderer/backend/vulkan/command_pool_vk.cc, impeller/renderer/backend/vulkan/descriptor_pool_vk.cc, impeller/renderer/backend/vulkan/fence_waiter_vk.cc
Dart timeline tracing events are surprisingly expensive. Lets remove events we're not using to track anything, in favor of CPU profiles.
=> [Impeller] remove trace events that have outlived their usefulness.

BUILD.gn, ci/licenses_golden/excluded_files, ci/licenses_golden/licenses_flutter, shell/platform/darwin/common/BUILD.gn, shell/platform/darwin/common/availability_version_check.cc, shell/platform/darwin/common/availability_version_check.h, shell/platform/darwin/common/availability_version_check_unittests.cc, shell/platform/darwin/ios/BUILD.gn, shell/platform/darwin/ios/framework/Source/availability_version_check_test.mm, testing/run_tests.py
This PR ports more of the implementation of availability checking from clang-rt into the Engine. In particular, when the call to look up the symbol `_availability_version_check` fails, this PR falls back on reading the platform version information out of a plist file at a well-known location, as is done [here](https://github.com/llvm/llvm-project/blob/2fd66e6eb659701b9d4c88708d55d5854a246815/compiler-rt/lib/builtins/os_version_check.c#L163).
This change fixes a mistake in https://github.com/flutter/engine/pull/44711, which didn't account for `_availability_version_check` not being available on iOS 11 and 12.
Fixes https://github.com/flutter/flutter/issues/138711
=> Fix _availability_version_check for iOS 11 and 12

ci/builders/README.md, ci/builders/linux_android_aot_engine.json
Fixes https://github.com/flutter/flutter/issues/138835
=> [CP] Only run firebase tests on HEAD (#48548)

shell/platform/darwin/ios/framework/Source/SemanticsObject.mm, shell/platform/darwin/ios/framework/Source/SemanticsObjectTest.mm
This PR is a sibling of #47961 but for iOS
=> Add support for exposing accessibility identifier as accessibilityIdentifier on iOS

lib/ui/fixtures/ui_test.dart, lib/ui/semantics.dart, lib/web_ui/lib/semantics.dart, lib/web_ui/test/engine/semantics/semantics_test.dart, shell/platform/embedder/fixtures/main.dart, testing/scenario_app/lib/src/locale_initialization.dart
This PR adds `String? identifier` to `SemanticsUpdateBuilder` (currently it's only available in the temproary `SemanticsUpdateBuilderNew` API.
This is mainly targeted at https://github.com/flutter/flutter/issues/17988
Steps:
part 1: [engine] add `SemanticsUpdateBuilderNew` https://github.com/flutter/engine/pull/47961
part 2: [flutter] use `SemanticsUpdateBuilderNew`  https://github.com/flutter/flutter/pull/138331
**part 3: [engine] update `SemanticsUpdateBuilder` to be the same as `SemanticsUpdateBuilderNew`** <-- we are here
part 4: [flutter] use (now updated) `SemanticsUpdateBuilder` again.
part 5: [engine] remove `SemanticsBuilderNew`
=> SemanticsUpdateBuilder migration: introduce `identifier`

lib/web_ui/lib/src/engine/embedder.dart, lib/web_ui/lib/src/engine/window.dart, lib/web_ui/test/engine/window_test.dart
Currently, in multi-view mode, when the user resizes the window, Flutter views don't respond to the resize. This is because `FlutterViewEmbedder` is the one responding to resize events. But `FlutterViewEmbedder` only works with the implicit view, so multi views didn't respond to resize events.
This PR moves the responsibility of responding to resize events from `FlutterViewEmbedder` to `EngineFlutterView`. Also, tests.
Part of https://github.com/flutter/flutter/issues/134443
=> [web] Handle resizes at the view level

DEPS, ci/licenses_golden/excluded_files
The only reference to `libxml` was deleted in https://github.com/flutter/buildroot/pull/801.
This PR updates the buildroot, and removes the library.
=> Roll `buildroot` and delete `libxml`.

ci/licenses_golden/licenses_flutter, impeller/aiks/aiks_unittests.cc, impeller/aiks/canvas.cc, impeller/aiks/canvas.h, impeller/aiks/canvas_recorder.h, impeller/display_list/dl_dispatcher.cc, impeller/display_list/skia_conversions.cc, impeller/display_list/skia_conversions.h, impeller/display_list/skia_conversions_unittests.cc, impeller/entity/BUILD.gn, impeller/entity/geometry/geometry.cc, impeller/entity/geometry/geometry.h, impeller/entity/geometry/geometry_unittests.cc, impeller/entity/geometry/round_rect_geometry.cc, impeller/entity/geometry/round_rect_geometry.h, impeller/geometry/path_builder.cc, impeller/geometry/path_builder.h, impeller/geometry/path_unittests.cc, impeller/geometry/rect.h, impeller/geometry/rect_unittests.cc, impeller/geometry/size.h, impeller/geometry/size_unittests.cc, impeller/tessellator/tessellator.cc, impeller/tessellator/tessellator.h
Simple round rects with the same width and height at each corner are tessellated directly for fill operations, but not yet for stroke operations.
=> [Impeller] Direct tessellation of simple filled round rects

shell/platform/darwin/macos/framework/Source/FlutterEmbedderKeyResponderTest.mm, shell/platform/embedder/embedder_external_view.cc
See https://github.com/flutter/engine/pull/48928
=> Workarounds for clang-tidy warnings in the next roll of Clang

shell/platform/windows/BUILD.gn, shell/platform/windows/flutter_windows_engine_unittests.cc, shell/platform/windows/flutter_windows_view_unittests.cc, shell/platform/windows/testing/engine_modifier.h, shell/platform/windows/testing/mock_angle_surface_manager.h
See: https://github.com/flutter/engine/pull/48849#discussion_r1424535869
=> [Windows] Refactor surface manager mocking

impeller/aiks/aiks_unittests.cc, impeller/aiks/canvas.cc, impeller/aiks/canvas.h, impeller/display_list/dl_dispatcher.cc
This work leverages the recent work to directly tessellate the simple primitives for rendering and uses their geometry classes for equivalent clip primitives.
=> [Impeller] Use direct tessellation geometry for simple clip shapes

impeller/aiks/aiks_unittests.cc, impeller/entity/contents/filters/filter_contents.cc, impeller/entity/contents/filters/gaussian_blur_filter_contents.cc, impeller/golden_tests/golden_playground_test.h, impeller/golden_tests/golden_playground_test_mac.cc, impeller/golden_tests/golden_playground_test_stub.cc, impeller/golden_tests/metal_screenshotter.h, impeller/playground/backend/gles/playground_impl_gles.cc, impeller/playground/backend/gles/playground_impl_gles.h, impeller/playground/backend/metal/playground_impl_mtl.h, impeller/playground/backend/metal/playground_impl_mtl.mm, impeller/playground/backend/vulkan/playground_impl_vk.cc, impeller/playground/backend/vulkan/playground_impl_vk.h, impeller/playground/playground.cc, impeller/playground/playground.h, impeller/playground/playground_impl.h, impeller/renderer/backend/metal/context_mtl.h, impeller/renderer/backend/metal/context_mtl.mm
This also adds a new mechanism of override the device capabilities.
fixes https://github.com/flutter/flutter/issues/139773 …
=> [Impeller] Made the new blur work on devices without the decal address mode

BUILD.gn, ci/licenses_golden/excluded_files, ci/licenses_golden/licenses_flutter, shell/platform/darwin/common/BUILD.gn, shell/platform/darwin/common/availability_version_check.cc, shell/platform/darwin/common/availability_version_check.h, shell/platform/darwin/common/availability_version_check_unittests.cc, shell/platform/darwin/ios/BUILD.gn, shell/platform/darwin/ios/framework/Source/availability_version_check_test.mm, testing/run_tests.py
CP of https://github.com/flutter/engine/commit/5587d26aa2d4b2b239a5f2ce8f231c97ab1d36db into 3.16 for https://github.com/flutter/flutter/issues/138711.
=> [CP] Fix _availability_version_check for iOS 11 and 12

ci/licenses_golden/excluded_files, ci/licenses_golden/licenses_flutter, impeller/renderer/backend/gles/description_gles.cc, impeller/renderer/backend/gles/description_gles.h, shell/platform/linux/fl_backing_store_provider.cc, shell/platform/windows/BUILD.gn, shell/platform/windows/compositor.h, shell/platform/windows/compositor_opengl.cc, shell/platform/windows/compositor_opengl.h, shell/platform/windows/compositor_opengl_unittests.cc, shell/platform/windows/compositor_software.cc, shell/platform/windows/compositor_software.h, shell/platform/windows/compositor_software_unittests.cc, shell/platform/windows/flutter_windows_engine.cc, shell/platform/windows/flutter_windows_engine.h, shell/platform/windows/flutter_windows_view.h
This migrates the Windows embedder to `FlutterCompositor` so that the engine renders off-screen to a framebuffer instead of directly onto the window's surface. This will allow us to support platform views and multiple views on Windows.
<details>
<summary>Tests...</summary>
* Verify OpenGL compositor's raster time isn't regressed and memory increase is reasonable
* Software compositor's raster time and memory isn't regressed
Test device configurations
</details>
Addresses https://github.com/flutter/flutter/issues/128904
[test-exempt]: …
=> [Windows] Move to `FlutterCompositor` for rendering

impeller/aiks/aiks_unittests.cc
This is a simple golden intended to smoketest potential issues when applying the coverage hint in the blur. Expected results:
=> [Impeller] Add golden for clipped+transformed blur.

impeller/aiks/aiks_unittests.cc, impeller/entity/contents/filters/filter_contents.cc, impeller/entity/contents/filters/gaussian_blur_filter_contents.cc, impeller/entity/contents/filters/gaussian_blur_filter_contents.h, impeller/entity/contents/filters/gaussian_blur_filter_contents_unittests.cc, impeller/entity/entity_unittests.cc
issue: https://github.com/flutter/flutter/issues/131580 …
=> [Impeller] Made the new blur support 1D blurs

ci/licenses_golden/licenses_flutter, shell/platform/darwin/ios/BUILD.gn, shell/platform/darwin/ios/framework/PrivacyInfo.xcprivacy
Create a `PrivacyInfo.xcprivacy` (this name is required) plist and move it to the top-level of the iOS framework bundle.  `NSPrivacyTracking*` and `NSPrivacyCollectedDataTypes` keys are required, but the values are blank.
Apple [now requires](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files) that third-party frameworks must include this manifest to document usage of particular APIs and [how they are used](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api).
> Starting in fall 2023, when you upload a new app or app update to App Store Connect that uses an API (including from third-party SDKs) that requires a reason, you’ll receive a notice if you haven’t provided an approved reason in your …
=> Add xcprivacy privacy manifest to iOS framework

impeller/aiks/aiks_unittests.cc, impeller/tessellator/tessellator.cc, impeller/tessellator/tessellator_unittests.cc
Fixes https://github.com/flutter/flutter/issues/140118
A bad test caused round rects with completely rounded sides to become ellipses.
=> [Impeller] Round rects with circular ends should not generate ellipses

shell/platform/windows/flutter_key_map.g.cc
No tests as this is a refactoring with no semantic changes.
The generator was updated by https://github.com/flutter/flutter/pull/140082
=> [Windows] Remove header guard from generated key map

shell/platform/darwin/ios/framework/PrivacyInfo.xcprivacy
In https://github.com/flutter/engine/pull/48951 `NSPrivacyCollectedDataTypes` is an array with an empty dictionary, but the privacy report wants an empty array or it errors:
When this is fixed the privacy report is blank, but that seems to be an Xcode bug?  Will investigate.
[testing the …
=> Fix `NSPrivacyCollectedDataTypes` array in privacy manifest

lib/web_ui/lib/src/engine/text/layout_service.dart, lib/web_ui/lib/src/engine/text/paragraph.dart, lib/web_ui/test/html/text_test.dart
`closestFragmentAtOffset` takes a horizontal offset from the start of the line, not the start of the paragraph.  …
=> Fix a bug in the HTML render's `getClosestGlyphInfo` implementation

impeller/entity/contents/filters/directional_gaussian_blur_filter_contents.h, impeller/entity/contents/filters/filter_contents.cc
This new blur should perform faster since it scales down the image before blurring it.  Jonah did early testing of it and found it to be faster.  Scrolling around with the blur perf bug it seems faster.  It also has a wider test bed and is hopefully easier to maintain since it contains all of its logic for both directions.
testing: There are existing blur tests and we've backfilled more as we've added features to this blur.
fixes https://github.com/flutter/flutter/issues/131580
fixes https://github.com/flutter/flutter/issues/138259
[test-exempt]: …
=> [Impeller] Turned on new blur.

impeller/aiks/aiks_unittests.cc, impeller/aiks/paint_pass_delegate.cc, impeller/entity/entity_pass.cc, impeller/entity/entity_pass.h
If we clear to transparent black, we're not forcing the pass to be constructed. Change the entity pass API so that we can tell the difference between clearing transparent black and not having a clear color.
In https://github.com/flutter/flutter/issues/139571 , the app is creating a layer that is clearing to a transparent color, which is getting skipped. That invalid texture is fed into a blend which produces either black or magenta error texture.
Fixes https://github.com/flutter/flutter/issues/139571
=> [Impeller] distinguish between no clear color and transparent black clear color.

impeller/entity/contents/filters/directional_gaussian_blur_filter_contents.h, impeller/entity/contents/filters/filter_contents.cc
Reverts flutter/engine#48472
This is causing memory crashes in the device lab: https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_ios%20backdrop_filter_perf_ios__timeline_summary/14324/overview
```
[2023-12-14 15:55:20.660354] [STDOUT] stdout: [+1764 ms] Process 611 stopped
[2023-12-14 15:55:20.662620] [STDOUT] stdout: [   +2 ms] * thread #12, name = 'io.flutter.1.raster', stop reason = EXC_RESOURCE (RESOURCE_TYPE_MEMORY: high watermark memory limit exceeded) (limit=2098 MB)
[2023-12-14 15:55:20.662686] [STDOUT] stdout: [        ]     frame #0: 0x0000000106705e78 Flutter`void std::_LIBCPP_ABI_NAMESPACE::allocator<impeller::Command>::construct[abi:v15000]<impeller::Command, impeller::Command>(impeller::Command*, impeller::Command&&) + 8
[2023-12-14 15:55:20.662784] [STDOUT] stdout: [ …
```
=> Revert "[Impeller] Turned on new blur."

impeller/aiks/aiks_unittests.cc, impeller/entity/entity_pass.cc, impeller/entity/entity_unittests.cc
This reverts commit c32eb048d55b5efb2d49ca6afc0644c021102558.
That PR was outputting incorrect colors on the Play/AiksTest.BlendMode advanced blend tests.
=> Revert "[Impeller] Provide the clear color to an advanced blend if it was optimized out"

.ci.yaml, ci/builders/mac_android_aot_engine.json, ci/builders/mac_clang_tidy.json, ci/builders/mac_host_engine.json, ci/builders/mac_impeller_cmake_example.json, ci/builders/mac_ios_engine.json, ci/builders/mac_unopt.json
Release team wants engine tests running exclusively on macOS 13 in main for a while before CP'ing to beta.
[breaking …
=> Run tests on macOS 13 exclusively

impeller/aiks/canvas.cc, impeller/aiks/canvas_unittests.cc
Resolves https://github.com/flutter/flutter/issues/139294.
We use this bounds rect for querying the DisplayList rtree when culling. But when sub-DisplayLists are being dispatched, the DisplayList's rtree is local and doesn't incorporate parent layer filters. So sub-DisplayLists are getting culled as if no filters are being applied.
Technically our local bounds tracking in Aiks is actually correct here, but this is a quick fix to alleviate the problem. I don't know what the best longterm solution for this is.
=> [Impeller] Turn off Aiks bounds tracking for filtered SaveLayers.

DEPS
In support of https://github.com/flutter/flutter/issues/138169. This revision adds a static library build rule for SwiftShader which flutter_tester can consume, see https://github.com/flutter/engine/pull/48708
=> Roll SwiftShader to 2fa7e9b99ae4e70ea5ae2cc9c8d3afb43391384f

impeller/tools/impeller.gni
Shader bundles only produce the flat buffer output and do not write a depfile.
=> [Impeller] Do not pass the depfile flag when creating a shader bundle in ImpellerC

ci/licenses_golden/licenses_flutter, impeller/renderer/backend/metal/surface_mtl.mm, shell/platform/darwin/ios/BUILD.gn, shell/platform/darwin/ios/framework/Source/FlutterMetalLayer.h, shell/platform/darwin/ios/framework/Source/FlutterMetalLayer.mm, shell/platform/darwin/ios/framework/Source/FlutterMetalLayerTest.mm, shell/platform/darwin/ios/framework/Source/FlutterView.mm, shell/platform/darwin/ios/rendering_api_selection.mm, testing/ios/IosUnitTests/IosUnitTests.xcodeproj/project.pbxproj
This PR implements `FlutterMetalLayer`, a drop-in (as far as Flutter is concerned) replacement for `CAMetalLayer`. The biggest difference is that `FlutterMetalLayer` can present frames from background thread within a `CATransaction`.
`FlutterMetalLayer` is disabled by default. To opt-in, add the following item to `Info.plist`:
```xml
<key>FLTUseFlutterMetalLayer</key>
<true/>
```
The performance seems quite good, consistent 120hz on iPhone 13 Pro.
Benefits
- presenting with transaction from background thread, which, down the line, would allow for platform views without thread merging.
- fine control over how the surface is displayed - we can display single surface on multiple `CALayers`, each showing different part, allowing for performant implementation of unobstructed platform views. …
=> Add FlutterMetalLayer as optional alternative to CAMetalLayer

lib/web_ui/lib/src/engine/pointer_binding.dart, lib/web_ui/test/engine/pointer_binding_test.dart
This has been previously done for Safari in Firefox in https://github.com/flutter/engine/pull/35428. I'm not entirely sure since which release, but for past couple of months Chromium seems to be reporting logical pixels during scroll events as well, which now makes scrolling on Chrome / macOs 2x slower. …
=> Convert chromium wheel delta to physical pixels on macOS

impeller/aiks/canvas.cc, impeller/aiks/canvas_unittests.cc
Cherry-pick for https://github.com/flutter/engine/pull/49076.
For issue: https://github.com/flutter/flutter/issues/139294
=> [CP] [Impeller] Turn off Aiks bounds tracking for filtered SaveLayers.

.ci.yaml
This is to prevent builds from timing out during the experiment to disable goma on mac post submit builds.
Bug: https://github.com/flutter/flutter/issues/140342 …
=> Double timeout on mac builds.

DEPS, shell/platform/darwin/ios/framework/Source/FlutterEmbedderKeyResponderTest.mm
We're on a version of clang that crashes a lot on macOS. This PR rolls clang forward to a new release from the Fuchsia toolchain team. If it does not fix the crash, we can roll back with https://github.com/flutter/engine/pull/49249. Both rolling forward and back require the fixes to the `.mm` file in this PR.
=> Rolls clang to 725656bdd885483c39f482a01ea25d67acf39c46

testing/run_tests.py
Today the default renderer on hosts is Skia, but if we ever change the default then we will be testing on Impeller+default(Impeller) rather than both Skia and Impeller. Change the flutter_tester launch arguments to explicitly disable Impeller when we want to test Skia so that we will always test on both platforms.
=> Make sure run_tests.py runs dart tests on Skia

testing/ios/IosUnitTests/README.md
I wish this info was there, that'd save me from looking inside the script.
=> [Docs] Add more info about running tests on iOS

lib/web_ui/lib/platform_dispatcher.dart, lib/web_ui/lib/src/engine/canvaskit/embedded_views.dart, lib/web_ui/lib/src/engine/canvaskit/rasterizer.dart, lib/web_ui/lib/src/engine/canvaskit/renderer.dart, lib/web_ui/lib/src/engine/canvaskit/surface.dart, lib/web_ui/lib/src/engine/dom.dart, lib/web_ui/lib/src/engine/html/renderer.dart, lib/web_ui/lib/src/engine/platform_dispatcher.dart, lib/web_ui/lib/src/engine/renderer.dart, lib/web_ui/lib/src/engine/skwasm/skwasm_stub/renderer.dart, lib/web_ui/test/canvaskit/backdrop_filter_golden_test.dart, lib/web_ui/test/canvaskit/canvas_golden_test.dart, lib/web_ui/test/canvaskit/common.dart, lib/web_ui/test/canvaskit/embedded_views_test.dart, lib/web_ui/test/canvaskit/image_golden_test.dart, lib/web_ui/test/canvaskit/layer_test.dart, lib/web_ui/test/canvaskit/multi_view_test.dart, lib/web_ui/test/canvaskit/render_canvas_test.dart, lib/web_ui/test/common/frame_timings_common.dart, lib/web_ui/test/common/rendering.dart, lib/web_ui/test/common/test_initialization.dart, lib/web_ui/test/engine/scene_view_test.dart, lib/web_ui/test/engine/semantics/semantics_test.dart, lib/web_ui/test/engine/surface/scene_builder_test.dart, lib/web_ui/test/html/text/canvas_paragraph_test.dart, lib/web_ui/test/ui/image_golden_test.dart, lib/web_ui/test/ui/platform_view_test.dart, lib/web_ui/test/ui/scene_builder_test.dart, lib/web_ui/test/ui/utils.dart
Also update tests to conform to the render rule.
The render rule is that the call to `render` should only occur in the scope of an `onDrawFrame` or `onBeginFrame` call. As a side effect, this change also fixes a memory leak which occurs in tests using FakeAsync in the `flutter_test` environment (because they don't render anymore).
Fixes https://github.com/flutter/flutter/issues/137073
Fixes https://github.com/flutter/flutter/issues/137669 …
=> [web] Enforce onDrawFrame/onBeginFrame render rule

testing/scenario_app/ios/Scenarios/ScenariosUITests/AppExtensionTests.m
Fixes https://github.com/flutter/flutter/issues/140181.
Example of fix working on macOS 13 with Xcode 15 and iOS 17 simulator: https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20Engine%20Drone/586366/overview …
=> Fix testAppExtensionLaunching for Xcode 15/iOS 17

DEPS
According to https://github.com/flutter/flutter/issues/139370#issuecomment-1862652535, this check is now safe to remove.
=> Don't guard Windows arm64 Dart SDK download on the release candidate flag

impeller/aiks/aiks_unittests.cc, impeller/entity/entity_unittests.cc, impeller/golden_tests/golden_playground_test_mac.cc
I used this interactive toy to inspect the change in https://github.com/flutter/engine/pull/49206. Perhaps this can become our "kitchen sink" interactive toy for debugging blurs in Aiks (where we can easily form clips and add options for other paint state interactions as they become relevant).
Video of `GaussianBlurRotatedAndClippedInteractive`:
https://github.com/flutter/engine/assets/919017/e5be5f38-3644-43c4-a3d0-d08b03fcb7b0
Video of `GaussianBlurFilter` with the "Combined sigma" checkbox to make playing with the new blur easier:
https://github.com/flutter/engine/assets/919017/65bd6567-83be-4337-8827-03e6a3dee9b1
=> [Impeller] Add interactive Blur+Clip AiksTest.

impeller/aiks/aiks_unittests.cc, impeller/entity/contents/filters/gaussian_blur_filter_contents.cc, impeller/entity/contents/filters/gaussian_blur_filter_contents.h, impeller/entity/contents/filters/gaussian_blur_filter_contents_unittests.cc
=> Revert "[Impeller] new blur: refactored math and fixed expanded padding size"

impeller/geometry/rect.h, impeller/geometry/rect_unittests.cc
fixes https://github.com/flutter/flutter/issues/140464 …
=> [Impeller] fixed Rect::Contains

shell/common/animator.cc, shell/common/animator_unittests.cc
This is one of a series of changes to reland https://github.com/flutter/engine/pull/47239.
This PR changes `Animator` so that if `Render` is not called after a `BeginFrame`, this call is ignored.
Note that this is slightly different from https://github.com/flutter/engine/pull/47239. Instead of saying that we should ultimately change this skip to an assertion, this PR aims to keep the skip as the final shape. This is because a while ago we (with @goderbauer and @loic-sharma) decided that `PlatformDispatcher` should contain as little logic as possible to allow testing, and instead serve as a minimal native function binding, which means that we should eventually move the code that validates calling convention to the engine. 
If you need help, consider asking for advice on the #hackers-new …
=> Multiview pipeline Pt. 1: Skip illegal render calls

impeller/aiks/aiks_unittests.cc, impeller/entity/contents/filters/gaussian_blur_filter_contents.cc, impeller/entity/contents/filters/gaussian_blur_filter_contents.h, impeller/entity/contents/filters/gaussian_blur_filter_contents_unittests.cc
https://github.com/flutter/engine/pull/49206 had to reland because it had integration failures.  The changes are in a separate commit below. …
=> Reland `[Impeller] new blur: refactored math and fixed expanded padding size`

lib/ui/painting.dart, testing/dart/canvas_test.dart
Fixes https://github.com/flutter/flutter/issues/140490
=> Ensure sorted rects in ui.Canvas for legacy compatibility

lib/web_ui/lib/src/engine/semantics/checkable.dart, lib/web_ui/lib/src/engine/semantics/dialog.dart, lib/web_ui/lib/src/engine/semantics/focusable.dart, lib/web_ui/lib/src/engine/semantics/image.dart, lib/web_ui/lib/src/engine/semantics/incrementable.dart, lib/web_ui/lib/src/engine/semantics/link.dart, lib/web_ui/lib/src/engine/semantics/platform_view.dart, lib/web_ui/lib/src/engine/semantics/scrollable.dart, lib/web_ui/lib/src/engine/semantics/semantics.dart, lib/web_ui/lib/src/engine/semantics/tappable.dart, lib/web_ui/lib/src/engine/semantics/text_field.dart, lib/web_ui/test/engine/semantics/semantics_test.dart
Fixes https://github.com/flutter/flutter/issues/138371
When a new route pops up the expectation is that the screen reader focuses on something in the new route. Since routes typically result in DOM nodes being replaced, the current effect is that the screen reader simply unfocuses from the page, causing the user to have to refocus on back on the page and look for elements to interact with, which is a poor user experience. The current workaround is to use `autofocus`, but that doesn't scale as it's easy to forget, and if the route in question is maintained by a different person you may not even have enough control over it to set `autofocus` on anything. For example, this is the case with Flutter's default date picker. All you have is `showDatePicker` and there's no way to control the …
=> [web] autofocus in new routes

shell/platform/windows/angle_surface_manager.cc
https://github.com/flutter/engine/pull/24428 attempted to make surface resizing less expensive by using ANGLE's automatic resizing instead of manually destroying and then re-creating the surface. This caused some issues:
1. Flutter's surface size synchronization logic broke: https://github.com/flutter/engine/pull/24682
2. Resizing frameless windows caused the content to wiggle: https://github.com/flutter/flutter/issues/76465
The second issue caused the automatic resizing change to be reverted. However, the first fix was not reverted resulting in an incorrect comment.
Relanding this resizing performance improvement is tracked by https://github.com/flutter/flutter/issues/79427
=> [Windows] Fix incorrect surface manager comment

impeller/aiks/aiks_unittests.cc, impeller/aiks/canvas.cc
The original fix had a bad return value that caused the rendering to abort rather than proceed normally without the blurring.
I also changed the color being used so that the contents would show up in golden diffs which use a white background for unrendered pixels.
=> [Impeller] Do not skip rendering when mask blur is zero

impeller/aiks/aiks_unittests.cc, impeller/geometry/path_builder.cc, impeller/geometry/rect.h
This change removes the last usages of the Rect internal fields from outside the class, allowing the removal of a `friend` declaration and paving the way to reimplement the Rect methods with ltrb fields.
=> [Impeller] Remove use of private Rect fields from PathBuilder

shell/common/BUILD.gn, shell/common/shell_test_platform_view_gl.cc, shell/common/shell_test_platform_view_gl.h, shell/common/shell_unittests.cc
I tried to do this for Vulkan too but hit the limit of my patience for today on debugging why the Vulkan backend was segfaulting on shutdown.
Half of https://github.com/flutter/flutter/issues/140419
=> Fix GetImpellerContext for ShellTestPlatformViewGL

shell/platform/windows/angle_surface_manager.cc, shell/platform/windows/angle_surface_manager.h, shell/platform/windows/compositor_opengl_unittests.cc, shell/platform/windows/compositor_software_unittests.cc, shell/platform/windows/cursor_handler_unittests.cc, shell/platform/windows/flutter_platform_node_delegate_windows.cc, shell/platform/windows/flutter_window.cc, shell/platform/windows/flutter_window.h, shell/platform/windows/flutter_window_unittests.cc, shell/platform/windows/flutter_windows.cc, shell/platform/windows/flutter_windows_engine_unittests.cc, shell/platform/windows/flutter_windows_view.cc, shell/platform/windows/flutter_windows_view.h, shell/platform/windows/platform_handler.cc, shell/platform/windows/testing/mock_angle_surface_manager.h, shell/platform/windows/testing/mock_window_binding_handler.h, shell/platform/windows/text_input_plugin_unittest.cc, shell/platform/windows/window_binding_handler.h
The Windows embedder has three ways to get an `HWND`:
1. `GetWindowHandle` which returns the `HWND`
2. `GetPlatformWindow` which returns the `HWND` wrapped as a `PlatformWindow`
3. `GetRenderTarget` which returns the `HWND` wrapped as a `RenderTarget`
These abstractions are no longer useful now that we removed the UWP embedder. This change removes `PlatformWindow` and `RenderTarget` and uses `HWND` directly.
This change is a refactoring with no semantic changes.
=> [Windows] Remove `PlatformWindow` and `RenderTarget` abstractions

shell/platform/windows/flutter_window.cc, shell/platform/windows/flutter_window.h, shell/platform/windows/flutter_windows.cc, shell/platform/windows/flutter_windows_view.cc, shell/platform/windows/flutter_windows_view.h, shell/platform/windows/flutter_windows_view_unittests.cc, shell/platform/windows/testing/mock_window_binding_handler.h, shell/platform/windows/testing/mock_windows_proc_table.h, shell/platform/windows/window_binding_handler.h, shell/platform/windows/windows_proc_table.cc, shell/platform/windows/windows_proc_table.h
The `FlutterWindowsView` needs the `DwmIsCompositionEnabled` win32 API to check whether it should block presents until the v-blank to prevent screen tearing.
Currently, the view used the `FlutterWindow` to allow mocking this win32 API. However, the window is a complex type with lots of other responsibilities. The `WindowsProcTable` is the new preferred type for mocking win32 API.
Part of https://github.com/flutter/flutter/issues/140626 …
=> [Windows] Move DWM composition status to Windows proc table for mocking

shell/platform/windows/flutter_window.cc, shell/platform/windows/flutter_window.h, shell/platform/windows/flutter_windows_view.cc, shell/platform/windows/testing/mock_window_binding_handler.h, shell/platform/windows/testing/mock_windows_proc_table.h, shell/platform/windows/window_binding_handler.h, shell/platform/windows/windows_proc_table.cc, shell/platform/windows/windows_proc_table.h
The `FlutterWindowsView` uses the `DwmFlush` win32 API to prevent artifacts during window resizing.
Currently, the view used the `FlutterWindow` to allow mocking this win32 API. However, the window is a complex type with lots of other responsibilities. The `WindowsProcTable` is the new preferred type for mocking win32 API.
Part of https://github.com/flutter/flutter/issues/140626
[C++, …
=> [Windows] Move DWM flush to Windows proc table for mocking

shell/platform/android/io/flutter/embedding/engine/FlutterEngineConnectionRegistry.java, shell/platform/android/io/flutter/embedding/engine/dart/DartExecutor.java, shell/platform/android/io/flutter/embedding/engine/dart/DartMessenger.java, shell/platform/android/io/flutter/embedding/engine/loader/FlutterLoader.java, shell/platform/android/io/flutter/util/TraceSection.java
This PR adds a new way to define scoped trace events in Java, using the try-with-resource construct. This makes code simpler to read, and less error-prone.
Before:
```java
try {
TraceSection.begin("name");
// ....
} finally {
TraceSection.end();
}
```
Now:
```java
try (TraceSection e = TraceSection.scoped("name")) {
// ...
}
``` …
=> Add try-with-resource support to TraceSection

impeller/entity/contents/content_context.cc, impeller/entity/contents/content_context.h, impeller/entity/contents/contents.cc, impeller/entity/contents/filters/blend_filter_contents.cc, impeller/entity/contents/filters/directional_gaussian_blur_filter_contents.cc, impeller/entity/contents/filters/gaussian_blur_filter_contents.cc, impeller/entity/contents/filters/morphology_filter_contents.cc
This will reuse the downsample texture for the blur pass.
issue: https://github.com/flutter/flutter/issues/140189
Testing: This has golden image coverage for the refactoring.  There is a slight performance difference which will show up in benchmarks.  Ideally there would also be a memory test for the blur.  I don't think there is one yet. …
=> [Impeller] new blur: implemented ping ponging

shell/platform/android/io/flutter/embedding/android/AndroidTouchProcessor.java, shell/platform/android/io/flutter/embedding/android/MotionEventTracker.java, shell/platform/android/io/flutter/plugin/platform/PlatformViewsController.java
Android Platform Views process MotionEvents in a complicated way:
1. MotionEvent is captured and delivered to PlatformViewWrapper.onTouchEvent (TLHC) or FlutterMutatorView.onTouchEvent (HC)
2. MotionEvent is transformed by the AndroidTouchProcessor into a PointerEvent
3. AndroidTouchProcessor sends the PointerEvent over the PlatformViewChannel
4. Framework processes the PointerEvent
5. Framework sends the PointerEvent over the PlatformViewChannel.
6. in PlatformViewsController.onTouch a new MotionEvent is synthesized
7. The MotionEvent is delivered to the platform view
After step (6) the MotionEvent will fail Verification (`android.hardware.input.InputManager.verifyInputEvent`).
The fix requires that in step (6) we use the original motion event delivered in step (1) instead of …
=> Android Platform Views support Verified Input Events

lib/web_ui/lib/src/engine/canvaskit/text.dart, lib/web_ui/lib/src/engine/html/renderer.dart, lib/web_ui/lib/src/engine/skwasm/skwasm_impl/paragraph.dart, lib/web_ui/lib/src/engine/text/canvas_paragraph.dart, lib/web_ui/lib/src/engine/text/paragraph.dart, lib/web_ui/test/html/text/layout_fragmenter_test.dart, lib/web_ui/test/ui/text_style_test.dart
Make TextStyle implementations consistent across web renderers and consistent with the mobile implementation. This will allow us to unskip `test/painting/text_style_test.dart` on the framework side.
=> [web] make TextStyle implementations consistent

impeller/compiler/impellerc_main.cc, impeller/compiler/reflector.cc, impeller/compiler/reflector.h, impeller/compiler/runtime_stage_data.cc, impeller/compiler/runtime_stage_data.h, impeller/compiler/shader_bundle.cc, impeller/compiler/shader_bundle.h, impeller/compiler/switches.cc, impeller/compiler/switches.h, impeller/fixtures/BUILD.gn, impeller/runtime_stage/runtime_stage_unittests.cc, impeller/tools/impeller.gni, lib/ui/fixtures/shaders/BUILD.gn, lib/ui/fixtures/shaders/general_shaders/BUILD.gn, lib/ui/fixtures/shaders/supported_glsl_op_shaders/BUILD.gn, lib/ui/fixtures/shaders/supported_op_shaders/BUILD.gn
This patch will be important for Android/Vulkan, where we'll need to bundle GLES, Vulkan, and SkSL (at least for now).
I've refactored impellerc_main to break up some of the larger methods into more granular ones.
I've also changed the way that the `IPLR` output works so that we create as many compilers as runtime stages requested.
We still are in a weird situation where we create one "Default" compiler for the reflection data and depfile. I don't think that needs to be addressed in this patch, but we should do something about this. I've talked a little with @bdero and @jonahwilliams - it will probably involve something like making the generated reflection data a bit more flexible than it currently is so that it can more ergonomically capture different platform anomalies - we could do …
=> [Impeller] Allow multiple --runtime-stage-* parameters to impellerc

lib/ui/platform_dispatcher.dart, lib/ui/window.dart, shell/common/animator.cc, shell/common/animator.h, shell/common/animator_unittests.cc
This PR reverts the following two PRs:
* https://github.com/flutter/engine/pull/47323
* https://github.com/flutter/engine/pull/49266
Effectively, 
| Illegal renders are... | in debug build | in release build |
|----|----|----|
| Before revert | Skipped in Dart | Skipped in Dart |
| After revert | Skipped in Dart | Passed in Dart and rendered in native |
which means that the illegal renders will take effect in release mode, the mode that the benchmarks are performed in.
This is due to a discovery that the revert https://github.com/flutter/engine/pull/49238 did not bring back the performance. We suspect that some other changes after the culprit (https://github.com/flutter/engine/pull/47239) is also responsible for the regression, which narrows down to just one PR, …
=> Revert skiping illegal render in Dart
