fml/cpu_affinity.cc, fml/cpu_affinity.h, fml/cpu_affinity_unittests.cc, shell/platform/android/android_shell_holder.cc
For devices with 1 fast core, the current affinity set is less idea because it forces UI and raster on the same thread. Widen this to exclude slow cores instead of including only the fast core.
=> Widen CPU affinity set.

ci/builders/mac_host_engine.json
This is a follow up to https://github.com/flutter/engine/pull/53163, where I deleted the ninja target to build the golden tests, however I forgot to delete the commands to actually run the tests. In post-submit, the tests ran again and failed: https://ci.chromium.org/ui/p/dart-internal/builders/flutter/Mac%20Production%20Engine%20Drone/12733/infra
This PR actually deletes the scripts to run the tests.
=> [flutter_releases] beta 3.23 release engine - actually delete impeller tests

display_list/BUILD.gn, display_list/display_list_unittests.cc, display_list/dl_builder.cc, display_list/testing/dl_test_snippets.cc, display_list/testing/dl_test_snippets.h
A single glyph can be opacity peepholed, this is common in the case of Icons.
=> [display_list] allow applying opacity peephole to single glyph.

shell/platform/linux/fl_renderer_gdk.cc
Fix rendering corruption by Flutter and GDK sharing the same OpenGL context
Solved by having three contexts - one for GDK and two for Flutter.
Regression introduced in https://github.com/flutter/engine/pull/50754
Fixes https://github.com/flutter/flutter/issues/148653
=> Fix rendering corruption by Flutter and GDK sharing the same OpenGL context

ci/licenses_golden/excluded_files, display_list/BUILD.gn, display_list/dl_builder.cc, display_list/dl_builder.h, display_list/geometry/dl_geometry_types.h, display_list/geometry/dl_geometry_types_unittests.cc, display_list/utils/dl_accumulation_rect.cc, display_list/utils/dl_accumulation_rect.h, display_list/utils/dl_accumulation_rect_unittests.cc, display_list/utils/dl_matrix_clip_tracker_unittests.cc, impeller/geometry/rect.h
Previously the SaveInfo structure contained data for both a regular Save and a SaveLayer call for each entry in the stack. This was not optimal in that it meant that data for the layers had to be copied back and forth on Save and Restore calls even if a layer was not involved.
Now Save stack entries share the data for their most recent enclosing layer and so updating that information does not require (error-prone and time-wasting) copying of the data between save stack entries. This should make new code that tracks new information for layers easier to add in the future.
=> Separate layer-specific data in DisplayListBuilder::SaveInfo

lib/web_ui/README.md, lib/web_ui/dev/chrome_installer.dart, lib/web_ui/dev/firefox_installer.dart
PR #47573 renamed the version-lock file from `browser_lock.yaml` to `package_lock.yaml`. This PR adjusts sources to changes. …
=> [web] update version-lock file location

impeller/display_list/dl_dispatcher.cc, impeller/display_list/dl_dispatcher.h, impeller/display_list/dl_playground.cc, shell/gpu/gpu_surface_metal_impeller.mm, shell/gpu/gpu_surface_vulkan_impeller.cc, shell/platform/embedder/embedder_external_view.cc
Use the flags in https://github.com/flutter/engine/pull/53104 + context capabilities to determine if we need to begin the first pass as an offscreen.
Part of https://github.com/flutter/flutter/issues/142054
=> [Impeller] wire up bdf and blend detection in experimental canvas.

DEPS, ci/licenses_golden/tool_signature, tools/licenses/lib/main.dart, tools/licenses/lib/patterns.dart
Manual roll of the ICU library. This normally happens automatically, but this
time around, ICU folks changed their license, so that needs to be fixed up.
I wish they would stop doing that. :)
This manual change should enable us to turn the auto-roller back on.
https://github.com/flutter/flutter/issues/149684 …
=> [icu] Manual roll of icu

CONTRIBUTING.md, analysis_options.yaml, lib/ui/analysis_options.yaml
Based on the (internal) discussion around converging on using the official Dart style guide, the design discussion https://flutter.dev/go/use-dart-style-in-flutter-engine, and with the exception of the code that gets published under `dart:ui` (as that is user-facing, and we'd like to evolve the code style in conjunction with the framework), we're going to be (gradually) adopting the Dart style guide in `flutter/engine`.
For now, we:
- Remove `always_specify_types` (except for `lib/ui`, i.e. `dart:ui`)
- Re-enable `type_annotate_public_apis` (which is now relevant since the above is disabled)
- Announce our _intent_ to re-format and apply the Dart formatter (which we'll land in the near future)
---
I also took the opportunity to specify more about our style guide use in general, mostly to …
=> Re-land #52859: Revamp the engine style guide, remove `always_specify_types`

lib/web_ui/analysis_options.yaml
`always_specify_types: false` and `avoid_dynamic_calls: false` is a dangerous combination. Let's clean up `avoid_dynamic_calls` before disabling `always_specify_types`.
=> [web] enable always_specify_types for web_ui

impeller/core/sampler_descriptor.h, impeller/display_list/dl_dispatcher.cc
Match DL/Skia sampling defaults. This does not change the default SamplerDescriptor value, but that is irrelevant as any draws from the framework will pass through DL conversion.
The SamplerDescriptor default of nearest is generally a good idea.
Fixes https://github.com/flutter/flutter/issues/148253
=> [Impeller] correctly map DL non-mipmap sample mode to non-mipmap sample mode.

display_list/utils/dl_matrix_clip_tracker.cc, display_list/utils/dl_matrix_clip_tracker.h, display_list/utils/dl_matrix_clip_tracker_unittests.cc, flow/diff_context.cc, flow/diff_context.h, flow/layers/layer_state_stack.cc, testing/mock_canvas.cc, testing/mock_canvas.h
The MatrixClipTracker was nothing more than a vector of MatrixClipState objects and a whole lot of duplicate delegation methods. It provided little value since nearly every use of it already had a state stack that was kept in synch with it's internal stack and so it was just adding an extra layer of delegation and extra allocations.
=> [DisplayList] remove legacy DisplayListMatrixClipTracker

third_party/txt/BUILD.gn, third_party/txt/src/skia/paragraph_skia.cc, third_party/txt/tests/paragraph_unittests.cc
Fixes https://github.com/flutter/flutter/issues/142974
If a text is drawn with a color source but lacks a path, just draw the original text. This ensures emojis render like Skia.
=> [Impeller] fix emojis with non-solid color sources.

lib/web_ui/analysis_options.yaml, lib/web_ui/dev/roll_fallback_fonts.dart, lib/web_ui/dev/steps/run_suite_step.dart, lib/web_ui/lib/src/engine/app_bootstrap.dart, lib/web_ui/lib/src/engine/clipboard.dart, lib/web_ui/lib/src/engine/platform_dispatcher.dart, lib/web_ui/lib/src/engine/services/message_codecs.dart, lib/web_ui/lib/src/engine/text_editing/text_editing.dart, lib/web_ui/test/canvaskit/initialization/services_vs_ui_test.dart, lib/web_ui/test/engine/app_bootstrap_test.dart, lib/web_ui/test/engine/routing_test.dart
Remove the `avoid_dynamic_calls` exception in `web_ui`, and clean up all dynamic calls.
=> [web] clean up dynamic calls, remove always_specify_types

.ci.yaml, ci/builders/linux_web_engine.json, ci/builders/local_engine.json, ci/builders/mac_android_aot_engine.json, ci/builders/mac_clang_tidy.json, ci/builders/mac_host_engine.json, ci/builders/mac_impeller_cmake_example.json, ci/builders/mac_ios_engine.json, ci/builders/mac_unopt.json, ci/builders/mac_unopt_debug_no_rbe.json, lib/web_ui/dev/generate_builder_json.dart
In preparation of upgrading our fleet to macOS 14, allow tests to run on either macOS 13 or 14.
Fixes https://github.com/flutter/flutter/issues/148879. …
=> Run tests on macOS 13 or 14

impeller/entity/contents/color_source_contents.h, impeller/entity/contents/linear_gradient_contents.cc
Part of https://github.com/flutter/flutter/issues/148651
allows the fast gradient to apply to non-rect shapes where the start/end are still on the coverage rect. Goldens are slightly different but seem close enough?
=> [Impeller] Expand fast gradient to all shapes.

fml/cpu_affinity.cc, fml/cpu_affinity.h, fml/cpu_affinity_unittests.cc, shell/platform/android/android_shell_holder.cc
Reverts flutter/engine#53136
b/345642546 shows some massive performance regressions on this patch. i'll rework it so the conditions are only loosened on phones with one fast core.
=> Revert "Widen CPU affinity set."

lib/web_ui/test/canvaskit/embedded_views_test.dart
Adding a test that demonstrates https://github.com/flutter/flutter/issues/149863. When the issue is fixed, this test can be adjusted to verify the optimal behavior.
=> [web] add test for inefficient overlay allocation

impeller/entity/geometry/stroke_path_geometry.cc, impeller/geometry/BUILD.gn, impeller/geometry/geometry_unittests.cc, impeller/geometry/separated_vector.cc, impeller/geometry/separated_vector.h
Follow-up for https://github.com/flutter/engine/pull/53210.
Also rename from `Ray` to `SeparatedVector2`, which is a more accurate name for what it is.
=> [Impeller] Move SeparatedVector2 to impeller/geometry.

lib/web_ui/lib/src/engine/renderer.dart, lib/web_ui/lib/ui_web/src/ui_web/browser_detection.dart, lib/web_ui/test/ui/utils.dart, web_sdk/sdk_rewriter.dart, web_sdk/test/sdk_rewriter_test.dart
Users of packages that have specialized code for the VM (which supports FFI) use conditional imports based on `dart.library.ffi`. We don't want the VM-specific code to be used for web in dart2wasm.
As a result we're going to make `dart.library.ffi` be false in conditional imports (as well as in
`const bool.fromEnvironment('dart.library.ffi')`).
Issue https://github.com/dart-lang/sdk/issues/55948
Issue https://github.com/flutter/flutter/issues/149984
=> Use dart.library.html to distinguish dart2wasm from dart2js/ddc in conditional imports

.ci.yaml, ci/builders/mac_host_engine.json
Temporary solution for https://github.com/flutter/flutter/issues/150011. …
=> Temporarily run Mac mac_host_engine on only Mac-13 

shell/platform/linux/fl_engine.cc, shell/platform/linux/fl_engine_private.h, shell/platform/linux/fl_engine_test.cc, shell/platform/linux/fl_scrolling_manager.cc, shell/platform/linux/fl_scrolling_manager_test.cc, shell/platform/linux/fl_scrolling_view_delegate.cc, shell/platform/linux/fl_scrolling_view_delegate.h, shell/platform/linux/fl_view.cc
Before all mouse clicks were set to `PointerDeviceKind.mouse` on Linux. Now use the proper type according to the source `GdkEvent`.
Fixes https://github.com/flutter/flutter/issues/147277
=> Map mouse pointer type on Linux

shell/common/shell.cc
From the issue, it looks like an NPE in this closure, we're not sure what else it could be besides the weak ptr - which could be null.
Fixes https://github.com/flutter/flutter/issues/149895
=> [engine] null check texture registry in OnPlatformViewMarkTextureFrameAvailable.

lib/gpu/render_pipeline.cc, lib/gpu/shader.cc, lib/gpu/shader.h, lib/gpu/shader_library.cc, shell/platform/android/android_exports.lst, testing/symbols/verify_exported.dart
Part of https://github.com/flutter/flutter/issues/145011.
This gets Flutter GPU working on Android.
=> [Flutter GPU] Generate DescriptorSetLayouts for pipelines & export symbols on Android.

lib/web_ui/lib/src/engine/dom.dart, lib/web_ui/lib/src/engine/semantics/focusable.dart, lib/web_ui/lib/src/engine/semantics/text_field.dart, lib/web_ui/test/engine/semantics/semantics_test.dart, lib/web_ui/test/engine/semantics/semantics_tester.dart, lib/web_ui/test/engine/semantics/text_field_test.dart
Stop using `SemanticsAction.didGain/LoseAccessibilityFocus` on the web, start using `SemanticsAction.focus`. This is because on the web, a11y focus is not observable, only input focus is. Sending `SemanticsAction.focus` will guarantee that the framework move focus to the respective widget. There currently is no "unfocus" signal, because it seems to be already covered: either another widget gains focus, or an HTML DOM element outside the Flutter view does, both of which have their respective signals already.
More details in the discussion in the issue https://github.com/flutter/flutter/issues/83809.
Fixes https://github.com/flutter/flutter/issues/83809
Fixes https://github.com/flutter/flutter/issues/148285
Fixes https://github.com/flutter/flutter/issues/143337
=> [web] switch from .didGain/LoseAccessibilityFocus to .focus

impeller/aiks/experimental_canvas.cc
This was missing when I wired up subpixel alignment for the regualr canvas, causing glyphs to not be found with experimental canvas.
Part of https://github.com/flutter/flutter/issues/142054
=> [Impeller] add missing position to exp canvas text.

lib/ui/BUILD.gn, lib/ui/painting/image_encoding_unittests.cc
fixes https://github.com/flutter/flutter/issues/149946
depends on:
- https://skia-review.googlesource.com/c/skcms/+/864516
- https://skia-review.googlesource.com/c/skia/+/864536
[CLA]: …
=> [Impeller] makes bgra10xr test more comprehensive

impeller/entity/contents/content_context.cc
Otherwise should be semantically equivalent/no-op.
=> [Impeller] disabling the color write mask seems to improve performance on iOS compared to just the blend options.

.ci.yaml, ci/builders/mac_host_engine.json
Allow Mac mac_host_engine tests to run for up to 90 minutes (previously assumed 60) and allow the tests to run on Mac-14. This should give the test more time when it needs to do additional tasks like install Xcode.
Timeout was recently added in https://flutter-review.googlesource.com/c/recipes/+/57980.
Timeout tested in https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20Engine%20Drone/941415/infra (timeout set to 4 minutes).
Fixes https://github.com/flutter/flutter/issues/150011.
[test-exempt]: …
=> Give mac_host_engine tests a longer timeout and allow to run on Mac-14

testing/scenario_app/ios/Scenarios/ScenariosUITests/AppExtensionTests.m
Instead of waiting for the first cell in the share sheet to appear, wait for the first cell matching the predicate to appear. It seems that on macOS 14 it [occasionally doesn't find any matches](https://github.com/flutter/flutter/issues/150117#issuecomment-2163493564), presumably a race condition - so this will wait up to 10 seconds for the desired elements to appear.
Attempting to fix https://github.com/flutter/flutter/issues/150117. I wasn't able to recreate locally and it only happens flakily in CI so hard to guarantee it will fix.
[test-exempt]: …
=> Change element to wait for in AppExtensionTests testAppExtensionLaunching

display_list/display_list_unittests.cc, display_list/dl_builder.cc, display_list/dl_builder.h, display_list/testing/dl_test_snippets.cc, display_list/utils/dl_matrix_clip_tracker.cc, display_list/utils/dl_matrix_clip_tracker.h, display_list/utils/dl_matrix_clip_tracker_unittests.cc, flow/layers/backdrop_filter_layer_unittests.cc, impeller/geometry/rect.h, impeller/geometry/rect_unittests.cc
This mechanism pulls some clip-reduction logic from Impeller Entities up into DisplayListBuilder to simplify the work that Impeller has to do and also amortize the work if the DisplayList is reused from frame to frame. Since the DisplayList does not have access to information such as surface sizes, there will still be cases that Impeller can catch that must be conservatively included by the recording process in the Builder, so this mechanism does not replace the same code in Impeller, it merely catches some cases earlier, while recording widget output, to avoid the same work on every frame down in Impeller.
In this first pass only the most conservative and straightforward cases are handled - a clip on a layer which has a previous clip that the new clip fully contains (and which was not …
=> [DisplayList] cull clip operations that can be trivially and safely ignored

shell/platform/android/test/io/flutter/embedding/engine/renderer/FlutterEngineRule.java, shell/platform/android/test/io/flutter/embedding/engine/renderer/FlutterRendererTest.java, shell/platform/android/test_runner/src/main/AndroidManifest.xml
In https://github.com/flutter/engine/pull/53280, I'm adding lifecycle-aware methods to `SurfaceProducer`.
That means, in order to test that it WAI, we'll need to be running in a simulated activity, and be able to switch scenario states (i.e. to `RESUMED`). This was mentioned as well in https://github.com/flutter/flutter/issues/133151 as being something we want to do.
This PR adds a `FlutterEngineRule`, which allows the creation of a "real" `FlutterEngine` and an `Intent` that can power `AndroidScenarioRule<FlutterActivity>`. I felt bad doing all of this work for a single `@Test`, so I also refactored the rest of the file and cleaned things up a bit.
That said, I'm happy to revert or make changes if we liked how things were setup before.
=> Add a `FlutterEngineRule` (JUnit `TestRule`) and use it in `FlutterRendererTest`

impeller/geometry/geometry_benchmarks.cc
These benchmark invocations were accidentally deleted when the invocations of the "UV" versions were eliminated.
No unit tests because only benchmark code is changed.
=> [Impeller] restore accidentally deleted Cap/Join benchmarks

ci/builders/linux_web_engine.json, lib/web_ui/dev/generate_builder_json.dart, lib/web_ui/dev/webdriver_browser.dart
Safari actually pauses execution of our unit tests if the window becomes occluded or non-visible. As such, I am inserting this egregious hack which just makes the Safari window frontmost every 2 seconds so that the unit tests don't get stalled out.
This should fix https://github.com/flutter/flutter/issues/150023
=> Hack to prevent Safari from being backgrounded during unit tests.

lib/web_ui/pubspec.yaml, web_sdk/web_test_utils/pubspec.yaml
Dart has removed the UnmodifiableXXXView classes, which were used by older versions of the archive package.
See https://dart.googlesource.com/sdk/+/18994e6e46ec9fb2fac8368c43d448119abd579f
=> Roll web_ui dependencies to enable the next roll of the Dart SDK

shell/platform/fuchsia/flutter/flatland_connection.cc, shell/platform/fuchsia/flutter/flatland_connection.h, shell/platform/fuchsia/flutter/tests/fakes/scenic/fake_flatland.cc, shell/platform/fuchsia/flutter/tests/flatland_connection_unittests.cc, tools/fuchsia/devshell/run_unit_tests.sh
flatland_connection.cc used to allow an arbitrary number of acquire and release fences to be scheduled for each frame.
Sadly, Fuchsia has a limitation of (1) the number of total handles that can be sent per a FIDL call, but also (2) the Flatland protocol only supports sending up to 16 fences per each fence type.
Now, normally there should be very few scheduled fences per frame. But if frames get skipped, we could amass many fences which would then crash our attempts to send all of them to the Flatland `Present` endpoint.
This change introduces two fence multiplexer, which allow us to signal more than 16 fences per type, at a performance penalty. We expect to be able *not* to crash the FIDL subsystem using this approach, and may even be able to hobble along for a bit, until the fences …
=> [flatland] Handle fence overflow in flatland_connection.cc

impeller/docs/android_cpu_profile.md
* Highlighting the section that says you can profile using a blank project. This saved me as I couldn't find the Profiler anywhere in the project for the Wondrous app.
* Added a section that shows how you can mark a release app as debuggable.
* Added tooltips for images.
* Cleanups for readability (subjective).
=> [Impeller] Update Android CPU profiling instructions.

impeller/docs/ios_cpu_profile.md
Adds more instructions on how to setup `FlameGraph`. Some other subjective improvements to readability.
=> [Impeller] Update iOS CPU profiling instructions.

runtime/BUILD.gn, runtime/dart_isolate.cc
This initializes the `NativeAssetsApi` for native assets resolution in the isolate group creation callback.
* https://github.com/dart-lang/sdk/issues/55523
The DartIO initialization lives in its own GN target. This doesn't work for the native assets initialization due to it having to look up the `script_uri` in one of the callbacks. Since the callbacks are function pointers, we can't have a lambda that captures the script uri. So instead, the native assets initialization lives in the flutter/runtime target.
The import from dart should probably be `runtime/include/bin/native_assets_api.h` to mirror what we're doing with dart IO, rather than directly importing from `runtime/bin/native_assets.h`.
All native asset testing is in flutter_tools, so those tests will only run once this rolls into …
=> Setup `NativeAssetsApi` during isolate group creation

lib/web_ui/lib/src/engine/canvaskit/renderer.dart, lib/web_ui/lib/src/engine/html/renderer.dart, lib/web_ui/lib/src/engine/renderer.dart, lib/web_ui/lib/src/engine/skwasm/skwasm_impl/renderer.dart, lib/web_ui/lib/src/engine/skwasm/skwasm_stub/renderer.dart, lib/web_ui/lib/ui_web/src/ui_web/images.dart, lib/web_ui/test/ui/image_golden_test.dart
Adds createImageFromTextureSource for flutter web, exposed in dart:web_ui.
```dart
final ui.Image uiImage = renderer.createImageFromTextureSource(bitmap,
width: 150, height: 150, transferOwnership: false);
```
In canvaskit renderer, this will use MakeLazyImageFromTextureSource. In SkWasmRenderer, it will call imageCreateFromTextureSource, which was already implemented in SkWasm for createImageFromImageBitmap to use, but was not exposed in a way that it could be taken advantage of.
By default, createImageFromTextureSource will create a copy of the object it is passed, but transferOwnership: true may be specified to allow transferable objects to be transferred to the renderer, avoiding the copy.
Fixes: https://github.com/flutter/flutter/issues/150479
Fixes: …
=> Add createImageFromTextureSource method to ui_web

ci/builders/linux_web_engine.json, lib/web_ui/dev/generate_builder_json.dart
https://github.com/flutter/engine/pull/53402 didn't work. Run these Safari tests on macOS 13 only until it can be fixed for macOS 14.
=> Run safari-dart2js-html tests on macOS 13

display_list/display_list_unittests.cc, display_list/utils/dl_matrix_clip_tracker.cc, display_list/utils/dl_matrix_clip_tracker_unittests.cc
The clipRect culling in DisplayListBuilder can sometimes fail to cull a clip due to round-off error in the math and this case happens to trigger when trying to cull against the initial frame bounds of a Pixel 6a with its uncommon 2.625 DPR as a scaling transform. An optimization in the culling tests for axis-aligned transforms (very common in Flutter) happens to do the right thing for this odd case, likely due to less math to incur round-off errors.
=> Better clipRect culling accuracy under scaling transforms

build/config/fuchsia/gn_configs.gni, tools/fuchsia/build_fuchsia_artifacts_test.py
Update Fuchsia API level to 19
b/347290402
Tests: cl/645133515 …
=> [fuchsia] Update Fuchsia API level to 19

impeller/entity/contents/filters/gaussian_blur_filter_contents.cc, impeller/entity/contents/filters/gaussian_blur_filter_contents.h, impeller/entity/contents/filters/gaussian_blur_filter_contents_unittests.cc
issue: https://github.com/flutter/flutter/issues/150462
This makes that usage never crash.  I would like to reevaluate for a better fix later though.  Something like:
1) Rework the downsample logic to make sure this gap doesn't exist.
1) Simply increase the kernel size.  We already did that before and technically we should be clamped to the 500 sigma so we won't have to do it forever.
[C++, …
=> [Impeller] added a fallback that will make sure the blur fragment shader doesn't overflow

lib/web_ui/lib/src/engine/canvaskit/canvaskit_api.dart, lib/web_ui/lib/src/engine/canvaskit/painting.dart, lib/web_ui/skwasm/shaders.cpp, lib/web_ui/test/canvaskit/canvaskit_api_test.dart, lib/web_ui/test/ui/fragment_shader_test.dart
This fixes an issue where in CanvasKit builds, uniforms set in setFloat function in the Paint class don't get updated after the initial render.
For example, like in the issue linked below, having a shader that animates a value over time and you want to reuse the Paint object that the shader is set to.
I'm no expert with CanvasKit nor with the Flutter Engine, but from what I could tell it seemed that the uniforms were only being sent to Skia on creation of the shader via _makeEffect.
However, any uniforms set afterwords were just stored in a local dart-side List<double> and forgotten about.
This PR changes the List<double> to use a WASM backed SkFloat32List to keep the references to the uniforms linked to dart-side.
fixes https://github.com/flutter/flutter/issues/149800
=> fix: web canvaskit fragment shaders were not using updated uniform values

lib/web_ui/skwasm/library_skwasm_support.js, lib/web_ui/skwasm/skwasm_support.h, lib/web_ui/skwasm/surface.cpp, lib/web_ui/skwasm/surface.h, lib/web_ui/skwasm/wrappers.h, lib/web_ui/test/ui/image_golden_test.dart
There were two issues here:
1) We have to stop using the emscripten thread scheduling APIs, as they can be invoked out of order from the rest of the messages that are posted. In some cases, out of order message handling can cause the request for reading pixels in an image to be serviced before some of the texture sources have been transfered to the web worker.
2) Skia's `readPixels` fails if there is is a lazy picture image made from a picture that contains a lazy texture image. The pertinent bug is here: https://g-issues.skia.org/issues/349201915
To work around the Skia bug, we just render the image itself onto our scratch canvas and pull the pixels out with `glReadPixels`.
This fixes https://github.com/flutter/flutter/issues/141326
=> [skwasm] Fixes for getting pixels from an image.

lib/web_ui/lib/src/engine/canvaskit/native_memory.dart, lib/web_ui/lib/src/engine/skwasm/skwasm_impl/memory.dart
https://dart-review.googlesource.com/c/sdk/+/370663 makes ExternalDartReference generic. By doing so, it triggers two cast_nullable_to_non_nullable lints that need to be silenced for it to land. Once the above SDK changes land, this can be refactored to utilize the generic and avoid the manual cast altogether.
=> Ignore lints that will be triggered by ExternalDartReference changes

DEPS
This version does not use the deprecated UnmodifiableInt32ListView API.
=> Roll the archive package to version 3.6.1

DEPS, tools/gn
... as part of buildmoot.
I _think_ this is all that is needed but am not confident.
=> Move impeller-cmake-example to flutter/third_party.

shell/platform/android/io/flutter/embedding/engine/renderer/FlutterRenderer.java
Closes https://github.com/flutter/flutter/issues/150849.
(Almost all of these are mechanical auto-fix changes from Android Studio/Best Practices).
=> Replace `Log.w` with `Log.d`, and tidy the file up a bit.

DEPS, ci/licenses_golden/tool_signature, tools/licenses/lib/paths.dart
There are no usages other than the reference in the LICENSE checker.
=> Remove otherwise unused third_party/web_dependencies.

impeller/entity/contents/filters/gaussian_blur_filter_contents.cc
This should be no functional change, just makes the case of clipped backdrop filters take up less memory.
fixes: https://github.com/flutter/flutter/issues/150713
test coverage:
- the framework's "backdrop filter" test
- GaussianBlurAnimatedBackdrop …
=> [Impeller] blur - cropped the downsample pass for backdrop filters

shell/platform/android/image_external_texture_gl.cc
Previously CreateEGLImage had been failing an assertion if an EGL display is not active on the calling thread.  CreateEGLImage should not assert here because it could be called from a deferred task that runs after the raster thread has lost its EGL state.
See https://github.com/flutter/flutter/issues/149396
=> Return a null image from ImageExternalTextureGL::CreateEGLImage if an EGL display is not available

shell/platform/android/io/flutter/view/AccessibilityBridge.java, shell/platform/android/test/io/flutter/view/AccessibilityBridgeTest.java
This PR fixes the problem where Flutter would not respect the "remove animation" accessibility setting on Android 12+.
Please see this issue for details: https://github.com/flutter/flutter/issues/130976
As [mentioned](https://github.com/flutter/flutter/issues/130976#issuecomment-1931388665) by [horsemankukka](https://github.com/horsemankukka), the problem has to do with reading `Settings.Global.TRANSITION_ANIMATION_SCALE` as a string instead of a float. Flutter would compare it to the string "0" to determine if animations should be disabled. Presumably, this worked because the settings app did indeed use the string "0" or "1" for this setting. But as of Android 12 it's instead written using float representation ("0.0" or "1.0"), at least on Samsung devices. [The …
=> Fix AccessibilityFeatures.disableAnimations flag on Android 12+

display_list/display_list.h, display_list/display_list_unittests.cc, display_list/dl_builder.cc, display_list/dl_builder.h, display_list/dl_canvas.h, display_list/dl_op_receiver.h, display_list/dl_op_records.h, display_list/skia/dl_sk_canvas.cc, display_list/skia/dl_sk_canvas.h, display_list/skia/dl_sk_dispatcher.cc, display_list/skia/dl_sk_dispatcher.h, display_list/testing/dl_rendering_unittests.cc, display_list/testing/dl_test_snippets.cc, display_list/testing/dl_test_snippets.h, display_list/utils/dl_matrix_clip_tracker.cc, display_list/utils/dl_matrix_clip_tracker.h, display_list/utils/dl_receiver_utils.h, impeller/display_list/dl_dispatcher.cc, impeller/display_list/dl_dispatcher.h, testing/display_list_testing.cc, testing/display_list_testing.h, testing/mock_canvas.cc, testing/mock_canvas.h
Impeller supports `ClipOval` and will detect oval paths and rrects and use that call instead when appropriate. Adding support for `ClipOval` to DisplayList allows that optimization code to be moved up into the recording process.
=> [DisplayList] Add support for clipOval to leverage Impeller optimization

display_list/display_list.h, display_list/display_list_unittests.cc, display_list/dl_builder.cc, display_list/dl_builder.h, display_list/dl_canvas.h, display_list/dl_op_receiver.h, display_list/dl_op_records.h, display_list/skia/dl_sk_canvas.cc, display_list/skia/dl_sk_canvas.h, display_list/skia/dl_sk_dispatcher.cc, display_list/skia/dl_sk_dispatcher.h, display_list/testing/dl_rendering_unittests.cc, display_list/testing/dl_test_snippets.cc, display_list/testing/dl_test_snippets.h, display_list/utils/dl_matrix_clip_tracker.cc, display_list/utils/dl_matrix_clip_tracker.h, display_list/utils/dl_receiver_utils.h, impeller/display_list/dl_dispatcher.cc, impeller/display_list/dl_dispatcher.h, testing/display_list_testing.cc, testing/display_list_testing.h, testing/mock_canvas.cc, testing/mock_canvas.h
Reverts flutter/engine#53622
There were some golden changes which might be minor, but they weren't expected. Also, I noticed a problem in reducing drawPath down to drawRect and drawOval - that should not be done if the path has the inverse fill flag set...
=> Revert "[DisplayList] Add support for clipOval to leverage Impeller optimization"

display_list/display_list.h, display_list/display_list_unittests.cc, display_list/dl_builder.cc, display_list/dl_builder.h, display_list/dl_canvas.h, display_list/dl_op_receiver.h, display_list/dl_op_records.h, display_list/skia/dl_sk_canvas.cc, display_list/skia/dl_sk_canvas.h, display_list/skia/dl_sk_dispatcher.cc, display_list/skia/dl_sk_dispatcher.h, display_list/testing/dl_rendering_unittests.cc, display_list/testing/dl_test_snippets.cc, display_list/testing/dl_test_snippets.h, display_list/utils/dl_matrix_clip_tracker.cc, display_list/utils/dl_matrix_clip_tracker.h, display_list/utils/dl_receiver_utils.h, impeller/display_list/dl_dispatcher.cc, impeller/display_list/dl_dispatcher.h, testing/display_list_testing.cc, testing/display_list_testing.h, testing/mock_canvas.cc, testing/mock_canvas.h
Reland of https://github.com/flutter/engine/pull/53622 that checks the inverse fill flag of the paths.
=> Reland [DisplayList] Add support for clipOval to leverage Impeller optimization

lib/web_ui/lib/src/engine/dom.dart, lib/web_ui/lib/src/engine/pointer_binding.dart, lib/web_ui/test/engine/pointer_binding_test.dart
When Flutter web runs embedded in a page, scrolling by dragging is interrupted very early by the browser.
It turns out that our `pointer` events receive a `pointercancel` + `pointerleave` by the browser because they happen in an area (the flutter glasspane) that is not really scrollable. [See documentation](https://developer.mozilla.org/en-US/docs/Web/API/Element/pointercancel_event).
> [!NOTE]
> After the pointercancel event is fired, the browser will also send [pointerout](https://developer.mozilla.org/en-US/docs/Web/API/Element/pointerout_event) followed by [pointerleave](https://developer.mozilla.org/en-US/docs/Web/API/Element/pointerleave_event).
(Firefox is a good browser to test this, because the browser will cancel our events **only if there's scrollable areas around the embedded …
=> [web] Fixes drag scrolling in embedded mode.

impeller/renderer/backend/metal/surface_mtl.mm
See also: https://github.com/flutter/flutter/issues/148660
Intel iOS simulators do not seem to enforce any backpressure on drawable acquisition. Fix this via blocking on completion in the surface_mtl.
=> [CP][Impeller] Intel iOS Simulators must block on GPU completion. (#53073)

impeller/entity/geometry/stroke_path_geometry.cc
Resolves https://github.com/flutter/flutter/issues/147139.
Added an explanation inline for why we need to use different direction values depending on whether or not we're capping off the last component of the contour.
Before:
After:
=> [CP][Impeller] Fix stroke curves. (#52978)

impeller/entity/entity_pass.cc
Resolves https://github.com/flutter/flutter/issues/146967
I added a detailed comment inline explaining why we need this. The visual issues in the reported issue were due to nearest sampling while straddling a half pixel offset.
Before:
After:
=> [CP][Impeller] Round out subpass coverage. (#52973)

impeller/tessellator/tessellator.cc, impeller/tessellator/tessellator_unittests.cc
While this is fixed on ToT, the stable channel is far behind so cherry picking all the tessellation changes is infeasible. Instead, we can land a small fix to avoid the segfault. Atttached unit test crashes without patch.
Fixes https://github.com/flutter/flutter/issues/149646
Fixes https://github.com/flutter/flutter/issues/149309
=> [Impeller][CP] dont segfault when tessellating empty polygons.

shell/platform/linux/fl_binary_messenger.cc, shell/platform/linux/fl_binary_messenger_private.h, shell/platform/linux/fl_binary_messenger_test.cc, shell/platform/linux/fl_engine.cc, shell/platform/linux/fl_renderer_gdk.cc, shell/platform/linux/fl_renderer_gdk.h, shell/platform/linux/fl_task_runner.cc, shell/platform/linux/fl_texture_registrar.cc, shell/platform/linux/fl_texture_registrar_private.h, shell/platform/linux/fl_view.cc, shell/platform/linux/fl_view_test.cc, shell/platform/linux/public/flutter_linux/fl_binary_messenger.h, shell/platform/linux/public/flutter_linux/fl_texture_registrar.h, shell/platform/linux/testing/mock_binary_messenger.cc
Due to changes in the renderer in 6b857de the engine was created once a widget is realized, not when the widget is created. If a Flutter application changed the default my_application.cc template to show the Flutter widget after plugins are run then these plugins would not be able to access the engine.
Solved by removing the GdkWindow from the renderer constructor and setting in later when the widget is realized. This works because the renderer is not used until the widget is realized.
Fixes https://github.com/flutter/flutter/issues/144873
=> Restore creation of engine before Linux widget is realized.

skia/BUILD.gn
In http://review.skia.org/862177 (and to a lesser extent, http://review.skia.org/862416), Skia added more .gni file lists for code in src/ports. This updates Flutter to use those lists instead of hard-coding those file paths directly, making it easier for upstream changes in Skia (e.g. file renames or relocations) to be pulled into Flutter without a Flutter-side change. …
=> [skia] Use more GNI file lists

lib/ui/semantics.dart, lib/web_ui/lib/src/engine/dom.dart, lib/web_ui/lib/src/engine/semantics/focusable.dart, lib/web_ui/lib/src/engine/semantics/semantics.dart, lib/web_ui/lib/src/engine/semantics/text_field.dart, lib/web_ui/lib/src/engine/text_editing/text_editing.dart, lib/web_ui/test/engine/semantics/semantics_test.dart, lib/web_ui/test/engine/semantics/semantics_tester.dart, lib/web_ui/test/engine/semantics/text_field_test.dart
Reverts flutter/engine#53360
Breaking google3 in b/350131288.
There is a test that does something like the following, to check if a radio button is selected.
```dart
// Send a bunch of tabs to focus on the correct radio button
await tester.sendKeyEvent(LogicalKeyboardKey.tab);
await tester.pump();
await tester.sendKeyEvent(LogicalKeyboardKey.tab);
await tester.pump();
await tester.sendKeyEvent(LogicalKeyboardKey.tab);
await tester.pump();
// Toggle the radio button with space
await tester.sendKeyEvent(LogicalKeyboardKey.space);
await tester.pump();
final selectedRadio =
tester.widget<Radio<bool>>(find.byType(Radio<bool>).at(1));
expect(selectedRadio.value, isTrue);
```
After this commit, the above test fails. See the linked bug above for more details.
=> Revert "[web] switch from .didGain/LoseAccessibilityFocus to .focus"

shell/platform/darwin/ios/framework/Source/FlutterAppDelegate.mm, shell/platform/darwin/ios/framework/Source/FlutterAppDelegateTest.mm, shell/platform/darwin/ios/framework/Source/FlutterViewController.mm, shell/platform/darwin/ios/framework/Source/FlutterViewController_Internal.h
follow up on comments on https://github.com/flutter/engine/pull/52350
framework pr : https://github.com/flutter/flutter/pull/147901 …
=> [deep link][ios] Update openURL method to reflect the result from framework 

impeller/renderer/backend/metal/allocator_mtl.mm, impeller/renderer/backend/metal/allocator_mtl_unittests.mm, impeller/renderer/backend/vulkan/allocator_vk.cc
=> [Impeller] fixed units for memory measurement

display_list/display_list.h, display_list/display_list_unittests.cc, display_list/dl_builder.cc, display_list/dl_builder.h, display_list/dl_canvas.h, display_list/dl_op_receiver.h, display_list/dl_op_records.h, display_list/skia/dl_sk_canvas.cc, display_list/skia/dl_sk_canvas.h, display_list/skia/dl_sk_dispatcher.cc, display_list/skia/dl_sk_dispatcher.h, display_list/testing/dl_rendering_unittests.cc, display_list/testing/dl_test_snippets.cc, display_list/testing/dl_test_snippets.h, display_list/utils/dl_matrix_clip_tracker.cc, display_list/utils/dl_matrix_clip_tracker.h, display_list/utils/dl_receiver_utils.h, impeller/display_list/dl_dispatcher.cc, impeller/display_list/dl_dispatcher.h, testing/display_list_testing.cc, testing/display_list_testing.h, testing/mock_canvas.cc, testing/mock_canvas.h
Reverts flutter/engine#53642
This change causes 10k golden updates internally and we need to land this out of band (go/lssc). There is also an existing issue with one particular client screenshot test - see b/350129213 for more details.
=> Revert "Reland [DisplayList] Add support for clipOval to leverage Impeller optimization"

testing/scenario_app/bin/run_ios_tests.dart, testing/scenario_app/ios/README.md, testing/scenario_app/run_ios_tests.sh
Part of https://github.com/flutter/flutter/issues/143953.
Because there are so many boundary cases, i.e. tests failed uploading artifacts to LUCI, I  was _not_ planning on atomically deleting and replacing `run_ios_tests.sh`, and want to give a chance for the iOS team to try the converted code and verify it works the way they expect.
I'm also happy to just slam it on, but defer to y'all. _It works on my machine_.
---
```sh
dart run testing/scenario_app/bin/run_ios_tests.dart
```
=> Convert `run_ios_tests.sh` to `run_ios_tests.dart`.

ci/licenses_golden/excluded_files, impeller/base/BUILD.gn, impeller/base/allocation.h, impeller/base/allocation_size.cc, impeller/base/allocation_size.h, impeller/base/allocation_size_unittests.cc, impeller/core/allocator.h, impeller/renderer/backend/metal/allocator_mtl.h, impeller/renderer/backend/metal/allocator_mtl.mm, impeller/renderer/backend/metal/allocator_mtl_unittests.mm, impeller/renderer/backend/vulkan/allocator_vk.cc, impeller/renderer/backend/vulkan/allocator_vk.h, impeller/renderer/backend/vulkan/allocator_vk_unittests.cc
This is similar to our handling of degrees and radians or really any of the stuff in chrono.
Storage is always in bytes. Before being displayed, it can be converted into any of unit that makes the most sense. Conversions are non-truncating and everything is constexpr safe.
=> [Impeller] Make storage sizes typed.

shell/platform/embedder/embedder.h
Doesn't rename the field to maintain API compatibility. But adds a bug annotation.
Fixes https://github.com/flutter/flutter/issues/148637
=> [Embedder] Document incorrectly named field in FlutterOpenGLFramebuffer.

lib/web_ui/lib/src/engine/semantics/label_and_value.dart, lib/web_ui/test/engine/semantics/semantics_text_test.dart
A semantic node may be tappable without having a more concrete role set on it, such as "button". It will just have a tap handler. This could lead to the sized span to be chosen as the label representation. However, when pointer events land on the span the DOM `target` becomes the span rather than the tappable element, and that breaks the debouncing logic in `pointer_binding.dart`.
This PR removes pointer event handling from inert text spans. This fixes the click debounce logic.
Fixes https://github.com/flutter/flutter/issues/151265
=> [web] ignore pointer events on plain text spans

flow/surface_frame.h, shell/gpu/gpu_surface_gl_impeller.cc, shell/gpu/gpu_surface_metal_impeller.mm, shell/gpu/gpu_surface_metal_impeller_unittests.mm, shell/gpu/gpu_surface_vulkan_impeller.cc, shell/platform/darwin/ios/framework/Source/FlutterPlatformViews.mm
Fixes https://github.com/flutter/flutter/issues/151274
This is only an issue on iOS (so far) because of the platform view rendering strategy that involves submitting multiple impeller frames per compositor frame.
FYI @bdero
=> [Impeller] mark the end of a frame boundary for system compositor interop.

lib/web_ui/lib/src/engine/semantics/heading.dart, lib/web_ui/test/common/matchers.dart, lib/web_ui/test/engine/semantics/semantics_test.dart, lib/web_ui/test/engine/semantics/semantics_tester.dart
Switch to using semantic heading tags (h1, h2, etc).
Fix missing secondary roles: focus, live region, route name, and label.
Improves indexability (https://github.com/flutter/flutter/issues/46789)
=> [web] use semantic tags for headings (h1, h2, etc), and fix missing secondary roles

impeller/golden_tests/golden_playground_test_mac.cc, impeller/golden_tests/metal_screenshotter.h, impeller/golden_tests/metal_screenshotter.mm, impeller/golden_tests/screenshotter.h, impeller/golden_tests/vulkan_screenshotter.h, impeller/golden_tests/vulkan_screenshotter.mm
Fixes https://github.com/flutter/flutter/issues/150993
This change allows testing the experimental canvas dispatcher in the playgrounds, which is important for golden testing. The plan to enable requires demonstrating that the goldens are the same.
=> [Impeller] add experimental canvas support to screenshotter.

impeller/fixtures/BUILD.gn, impeller/fixtures/spec_constant.frag, impeller/fixtures/spec_constant.vert, impeller/renderer/backend/gles/BUILD.gn, impeller/renderer/backend/gles/handle_gles.h, impeller/renderer/backend/gles/pipeline_gles.cc, impeller/renderer/backend/gles/pipeline_gles.h, impeller/renderer/backend/gles/pipeline_library_gles.cc, impeller/renderer/backend/gles/pipeline_library_gles.h, impeller/renderer/backend/gles/test/pipeline_library_gles_unittests.cc, impeller/renderer/backend/gles/unique_handle_gles.cc, impeller/renderer/backend/gles/unique_handle_gles.h
Fixes https://github.com/flutter/flutter/issues/145125
=> [Impeller] Exploit dynamic state in OpenGL for fewer program links.

shell/platform/fuchsia/flutter/software_surface.cc, shell/platform/fuchsia/flutter/software_surface.h, shell/platform/fuchsia/flutter/software_surface_producer.cc, shell/platform/fuchsia/flutter/software_surface_producer.h, shell/platform/fuchsia/flutter/surface_producer.h, shell/platform/fuchsia/flutter/tests/integration/embedder/flutter-embedder-test.cc, shell/platform/fuchsia/flutter/tests/integration/utils/portable_ui_test.cc, shell/platform/fuchsia/flutter/tests/integration/utils/portable_ui_test.h, shell/platform/fuchsia/flutter/vulkan_surface.cc, shell/platform/fuchsia/flutter/vulkan_surface.h, shell/platform/fuchsia/flutter/vulkan_surface_pool.cc, shell/platform/fuchsia/flutter/vulkan_surface_pool.h
Switch flutter from sysmem(1) protocols to sysmem2 protocols.
This is part of the overall sysmem(1) to sysmem2 migration.
fixes flutter/flutter#151154
=> [fuchsia][sysmem2] move to sysmem2 protocols

impeller/renderer/backend/gles/render_pass_gles.cc
My expectation was that all toggles were disabled with OpenGL. But the specification states: "The initial value for each capability with the exception of GL_DITHER is GL_FALSE. The initial value for GL_DITHER is GL_TRUE."
The kind of dithering is implementation dependent and our layered OpenGL implementations choose to do nothing when this is enabled (unless extensions like VK_EXT_legacy_dithering are supported). Since, again, per the spec: "As far as OpenGL layering is concerned, no dithering is technically an acceptable algorithm".
But it does have a cost of older hardware where dithering is supported.
This sets the default to match our other backends and get some performance on hardware that does do dithering.
=> [Impeller] Disable OpenGL dithering by default.

common/config.gni, impeller/display_list/dl_playground.cc, shell/common/snapshot_controller_impeller.cc, shell/gpu/gpu_surface_metal_impeller.mm, shell/gpu/gpu_surface_vulkan_impeller.cc
Fixes https://github.com/flutter/flutter/issues/150994
This ensures that the dart:ui API toImage and toImageSync use the experimental canvas API when the define is set. No other changes.
=> [Impeller] implement experimental canvas in snapshot controller.

impeller/fixtures/BUILD.gn, impeller/playground/BUILD.gn, impeller/playground/backend/gles/playground_impl_gles.cc, impeller/playground/backend/metal/playground_impl_mtl.mm, impeller/playground/backend/vulkan/playground_impl_vk.cc, impeller/renderer/renderer_unittests.cc
The texel fetch fallback used in place of framebuffer fetch isn't supported on ES 100. And this test is explicitly about framebuffer fetch.
Fixes https://github.com/flutter/flutter/issues/144181
=> [Impeller] Enable framebuffer fetch tests disabled on OpenGL ES.

impeller/aiks/aiks_blur_unittests.cc, impeller/compiler/compiler_unittests.cc, impeller/entity/contents/tiled_texture_contents_unittests.cc, impeller/entity/entity_unittests.cc, impeller/golden_tests/golden_playground_test_mac.cc, impeller/golden_tests/golden_playground_test_stub.cc, impeller/playground/compute_playground_test.cc, impeller/playground/playground_test.cc, impeller/renderer/renderer_unittests.cc, impeller/scene/scene_unittests.cc
I admit to using this private macro initially without realizing that the documented way to do this is to use the stream the other macro returns. The non-private variant is actually more powerful since it allows for easier customization of the reason for the skip.
No change in functionality. Just removes the use of the private macros.
=> Avoid using a private GTest macro to skip tests.

impeller/base/validation.cc, impeller/base/validation.h
Earlier, all validation logs originated from validation.cc which was not useful at all since you had to find the string in the source.
=> [Impeller] Validation logs indicate where in code the validation error happened.

impeller/base/validation.cc, impeller/base/validation.h, impeller/playground/playground_test.cc
Earlier, this used to take down the entire process. Now, the entire set of failures will be listed instead.
=> [Impeller] Validation errors in tests cause GTest failures.

impeller/docs/opengles_development_setup.md
In the previous patch, I had used the incorrect markdown syntax.
Followup for https://github.com/flutter/engine/pull/53671
=> [Impeller] Fix markdown formatting for blocks with tips.

impeller/renderer/backend/vulkan/allocator_vk.cc, impeller/renderer/backend/vulkan/capabilities_vk.cc, impeller/renderer/backend/vulkan/capabilities_vk.h, impeller/renderer/backend/vulkan/context_vk.cc
Fixes https://github.com/flutter/flutter/issues/129501
=> [Impeller] Enable fixed-rate compression support in Vulkan.

lib/web_ui/lib/src/engine/platform_dispatcher/view_focus_binding.dart
This PR addresses an issue where autocompleting a text field, even without direct keyboard input, unexpectedly triggers keydown events. To resolve this, the code now relaxes the casting assumptions to accommodate a wider range of event types, not just keyboard events.
By just adding the following script to the console, and filling the text field using autocomplete, you can see that indeed the fired event is not of type `KeyboardEvent` but `Event`. 
```javascript
document.body.addEventListener('keydown', console.log)
```
Fixes https://github.com/flutter/flutter/issues/149968 …
=> Relax the event assumptions for keydown events.

lib/web_ui/lib/src/engine/layers.dart, lib/web_ui/lib/src/engine/scene_view.dart, lib/web_ui/test/engine/scene_builder_test.dart, lib/web_ui/test/engine/scene_view_test.dart, lib/web_ui/test/ui/platform_view_test.dart
Previously, each platform view contained styling/placement information from the entire stack of the layer builder. This caused issues when using `addRetained`, since it would contain stale styling/placement information from its old parent layers. I have changed it so that platform views only contain local styling information, and that styling is combined with the parent only when the layers are merged.
=> [skwasm] Fix platform view placement.

lib/ui/hash_codes.dart, lib/web_ui/lib/hash_codes.dart
Towards https://github.com/flutter/flutter/issues/151679
=> Drop self-references to hash functions from doc comments

lib/ui/semantics.dart, lib/web_ui/lib/src/engine/dom.dart, lib/web_ui/lib/src/engine/semantics/focusable.dart, lib/web_ui/lib/src/engine/semantics/semantics.dart, lib/web_ui/lib/src/engine/semantics/text_field.dart, lib/web_ui/lib/src/engine/text_editing/text_editing.dart, lib/web_ui/test/engine/semantics/semantics_test.dart, lib/web_ui/test/engine/semantics/semantics_tester.dart, lib/web_ui/test/engine/semantics/text_field_test.dart
This relands https://github.com/flutter/engine/pull/53679.
The difference from the previous attempt is in the last commit, which prevents synthetic focus requests from echoing back into the framework. That part broke too many tests in g3 and needs to be revisited.
Stop using `SemanticsAction.didGain/LoseAccessibilityFocus` on the web, start using `SemanticsAction.focus`. This is because on the web, a11y focus is not observable, only input focus is. Sending `SemanticsAction.focus` will guarantee that the framework move focus to the respective widget. There currently is no "unfocus" signal, because it seems to be already covered: either another widget gains focus, or an HTML DOM element outside the Flutter view does, both of which have their respective signals already.
More details in the …
=> [web] switch to SemanticsAction.focus (attempt 3)

.ci.yaml
Address https://github.com/flutter/flutter/issues/151695, which describes https://github.com/flutter/flutter/issues/151249 happening post-submit on this release branch.
=> extend timeouts of all targets in .ci.yaml

lib/web_ui/lib/src/engine/clipboard.dart, lib/web_ui/lib/src/engine/dom.dart, lib/web_ui/lib/src/engine/platform_dispatcher/view_focus_binding.dart, lib/web_ui/lib/src/engine/semantics/focusable.dart, lib/web_ui/lib/src/engine/semantics/incrementable.dart, lib/web_ui/lib/src/engine/semantics/label_and_value.dart, lib/web_ui/lib/src/engine/semantics/scrollable.dart, lib/web_ui/lib/src/engine/semantics/text_field.dart, lib/web_ui/lib/src/engine/text_editing/text_editing.dart, lib/web_ui/test/engine/platform_dispatcher/view_focus_binding_test.dart, lib/web_ui/test/engine/semantics/semantics_test.dart, lib/web_ui/test/engine/semantics/text_field_test.dart, lib/web_ui/test/engine/view_embedder/dom_manager_test.dart
Always mark scrollable containers with `role="group"` to prevent the browser from merging all child elements into one giant string. Default to `preventScroll` to true across the web engine code, because it's a better default for Flutter than otherwise.
Fixes https://github.com/flutter/flutter/issues/130950
=> [web] fix unexpected scrolling in semantics

sky/tools/create_ios_framework.py, sky/tools/create_macos_gen_snapshots.py
We dropped support for armv7 iOS devices in:
* Framework: flutter/flutter#97342.
* Buildroot: flutter/buildroot#569
* Engine: https://github.com/flutter/engine/pull/32664
* Recipes:
* https://flutter-review.googlesource.com/c/recipes/+/29060
* https://flutter-review.googlesource.com/c/recipes/+/29060 (revert)
* https://flutter-review.googlesource.com/c/recipes/+/29582 (reland)
* Issue: flutter/flutter#97345
This eliminates the code (and an unused flag) to deal with producing zip archives including components for the armv7 architecture.
[test-exempt]: …
=> [iOS] Delete gen_snapshot_armv7 support

build/archives/BUILD.gn, ci/builders/mac_host_engine.json
This target produced an unused zipfile named `gen_snapshot.zip` containing the `gen_snapshot_${target_arch}` binary for the current build's target architecture.
The macOS recipe JSON produces the real `gen_snapshot.zip` that gets uploaded to the cloud bucket and pulled down by the tool. See: https://github.com/flutter/engine/blob/e5215e6854bc61cf8d5bae48715d73293bc1f91c/ci/builders/mac_host_engine.json#L555-L592
The recipe did, however, rely on the `archive_gen_snapshot` rule to ensure that the underlying `gen_snapshot` targets were actually built. See, for example:
https://github.com/flutter/engine/blob/e5215e6854bc61cf8d5bae48715d73293bc1f91c/ci/builders/mac_host_engine.json#L45
A few benefits:
* Eliminates an unnecessary zip operation.
* Eliminates confusion from grepping for …
=> [macOS] Eliminate archive_gen_snapshot target

lib/web_ui/lib/src/engine/pointer_binding.dart, lib/web_ui/lib/src/engine/view_embedder/embedding_strategy/custom_element_embedding_strategy.dart, lib/web_ui/test/engine/pointer_binding_test.dart, lib/web_ui/test/engine/view_embedder/embedding_strategy/custom_element_embedding_strategy_test.dart
This PR adds `touch-action:none` to `flutter-view` elements, so the browser lets the flutter engine fully handle all touch gestures.
This fix is more delicate than the first approach, which broke some merged taps when accessibility/semantics are enabled. 
* Found while testing: https://github.com/flutter/flutter/issues/130950
* "More correct" fix for: https://github.com/flutter/engine/pull/53647
* Flutter scroll: https://dit-multiview-scroll.web.app
* Semantics: https://dit-tests.web.app
* Scrollable platform views: https://dit-multiview-tests.web.app …
=> [web] Set touch-action:none in embedded views.

ci/builders/mac_host_engine.json, ci/builders/mac_ios_engine.json, sky/tools/create_macos_gen_snapshots.py
This patch updates `create_macos_gen_snapshots.py` to take the path to the input `gen_snapshot` binaries rather than just the path to the buildroot, and hardcoding the binary names and buildroot-relative paths internally.
This has a couple advantages:
* Those grepping the source for gen_snapshot to see where it's bundled will immediately find it in the recipe JSON as a parameter to this script.
* In future (the next patch I send out) we can pass different input paths that point to gen_snapshot binaries that are universal binaries. The current binaries are single-architecture x64 host binaries.
This is a refactoring with no semantic change, therefore no tests have changed.
Background
----------
`create_macos_gen_snapshot.py` is used to:
* Generate a named copy of gen_snapshot for the …
=> Clean up create_macos_gen_snapshots.py options

ci/builders/mac_host_engine.json
In #53524, we started producing universal `gen_snapshot_arm64` and `gen_snapshot_x64` binaries. This migrates away from bundling `gen_snapshot` binaries with x64-only host architecture to universal binaries that bundle both x64 and arm64 host architectures.
Also adds a dependency on `flutter/lib/snapshot:create_macos_gen_snapshots` to the profile build, where it was previously missing. Presumably, `gen_snapshot` was being built as a side-effect of one of the other targets.
Issue: https://github.com/flutter/flutter/issues/69157 …
=> [macOS] Archive universal gen_snapshot binaries

testing/dart/image_filter_test.dart
Fixes https://github.com/flutter/flutter/issues/151973
=> Fix race in image_filter_test.dart

tools/engine_tool/lib/src/commands/query_command.dart, tools/engine_tool/lib/src/commands/test_command.dart, tools/engine_tool/lib/src/gn.dart, tools/engine_tool/test/build_command_test.dart, tools/engine_tool/test/fixtures.dart
Closes https://github.com/flutter/flutter/issues/151990.
This is just a nice QOL change, since the `//` format we're using is not "native" to GN or Ninja.
=> Gracefully fail when `gn desc` returns no targets.

lib/web_ui/lib/src/engine/layers.dart, lib/web_ui/lib/src/engine/scene_view.dart, lib/web_ui/test/engine/scene_view_test.dart, lib/web_ui/test/ui/platform_view_test.dart
Our treatment of the interaction between offset and transform was incorrect. Modified our platform view unit tests to cover more cases of nested offsets and transforms.
=> [skwasm] Combine offset and transform properly.

DEPS, tools/fuchsia/dart/gen_dart_package_config.py, tools/pub_get_offline.py
We were using a very old version of this library that broke with Python3.12. This updates to a Python 3.12 compatible SHA.
The specific breakage at the former commit was that `collections.Hashable` was deprecated and moved to `collections.abc.Hashable` in Python 3.7. It was removed in Python 3.8. For anyone on newer versions of Python3, such as Python 3.9.6 which ships with macOS 15 Sequoia, this is broken.
The error on versions of Python newer than 3.8 is:
```
________ running 'python3 src/flutter/tools/pub_get_offline.py' in '/Users/chris/Developer/flutter/engine'
Traceback (most recent call last):
File "/Users/chris/Developer/flutter/engine/src/flutter/tools/pub_get_offline.py", line 167, in <module>
sys.exit(main())
^^^^^^
File …
```
=> Upgrade third_party/pyyaml to 03c67afd452cdff45b41bfe65e19a2fb5b80a0e8

tools/engine_tool/lib/src/build_utils.dart, tools/engine_tool/lib/src/commands/build_command.dart, tools/engine_tool/lib/src/commands/command.dart, tools/engine_tool/lib/src/commands/flags.dart, tools/engine_tool/lib/src/commands/run_command.dart, tools/engine_tool/lib/src/commands/test_command.dart, tools/engine_tool/test/build_command_test.dart, tools/engine_tool/test/run_command_test.dart, tools/engine_tool/test/utils.dart, tools/pkg/engine_build_configs/lib/src/build_config_runner.dart, tools/pkg/engine_build_configs/test/build_config_runner_test.dart
Also computes a better `-j` when RBE is enabled.
Fixes https://github.com/flutter/flutter/issues/147667
=> [et] Plumb -j to ninja

build/archives/BUILD.gn, common/config.gni
The `//flutter/build/archives:artifacts` target is used to build a zip archive (artifacts.zip) of host tools such as flutter_tester, the Dart kernel compiler, the impellerc shader compiler, and other tooling that is bundled in debug-mode host builds.
This moves the `!is_android` to the definition of `build_engine_artifacts`. This is required because of the way that we produce 32-bit arm gen_snapshot for Android on Windows hosts, which relies on the regular x64 host toolchain due to us having no 32-bit arm toolchain for Windows. As such, `current_toolchain == host_toolchain` on that platform.
```
build_engine_artifacts =
flutter_build_engine_artifacts &&
(current_toolchain == host_toolchain ||
(is_linux && !is_chromeos && current_cpu != "arm") || is_mac || is_win)
```
On iOS builds, we …
=> Move !is_android to build_engine_artifacts declaration

sky/tools/create_full_ios_framework.py
This is only ever used for gen_snapshot_arm64 where the value will only ever be 'clang_x64'. If we were to migrate builds to arm64 hosts, the gen_snapshot_x64 target would be broken as the script stands today.
This flag is never passed by recipe infra or outside callers, and can thus be safely inlined. The same refactoring was performed for generating universal gen_snapshots in #53954.
A followup patch will update the location where this gen_snapshot binary is generated (and adds an arm64 host binary build), and the merged universal gen_snapshot_${target_cpu} will be written to the root output directory.
This is minor pre-factoring to simplify the followup patch, which migrates to universal binaries for iOS.
Issue: …
=> [iOS] Eliminate --clang-dir flag

impeller/toolkit/android/surface_transaction.cc
Enabling the ahb backpressure has increased frame times - probably because this is now WAI and delaying the HB readyness. Lets try disabling it before we back out the AHB swapchain again.
See https://flutter-flutter-perf.skia.org/e/?begin=1721400948&end=1721487348&queries=device_type%3DPixel_7_Pro%26sub_result%3D90th_percentile_frame_rasterizer_time_millis%26sub_result%3D99th_percentile_frame_rasterizer_time_millis%26sub_result%3Daverage_frame_rasterizer_time_millis%26sub_result%3Dworst_frame_rasterizer_time_millis%26test%3Dnew_gallery_impeller__transition_perf&selected=commit%3D41656%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DPixel_7_Pro%252Cdevice_version%253Dnone%252Chost_type%253Dlinux%252Csub_result%253D90th_percentile_frame_rasterize …
=> [Impeller] try disabling backpressure in AHB swapchain.

impeller/display_list/aiks_dl_unittests.cc, impeller/display_list/dl_dispatcher.cc
Fixes https://github.com/flutter/flutter/issues/151785
if the bounds given to impeller SaveLayer is kMaxCullRect, treat this as unbounded.
=> [Impeller] detect max cull rect on bounds.

impeller/renderer/backend/vulkan/swapchain/swapchain_vk.cc
Fixes  https://github.com/flutter/flutter/issues/147533
This works now that the backpressure issue is fixed. Maybe the wait semaphore didn't work, but the CPU wait on the fence does.
=> [Impeller] enable ahb swapchain on emulators.

impeller/renderer/backend/gles/proc_table_gles.h
This many explicit calls are all but useless unless you are doing bringup. And we do that in unopt modes anyway. Having this on in even the debug and profile opt modes was turning out to be pretty egregious.
=> [Impeller] Remove implicit calls to glGetError in opt modes.

tools/fuchsia/dart/gen_dart_package_config.py, tools/pub_get_offline.py
Previously we were appending Flutter's fork of third_party/pyyaml to the Python sys.path. In the case where a bot image or local install already has pyyaml installed elsewhere on the path, ours will fail to be picked up. Instead prepend to the path.
Issue spotted by jsimmons@.
Related: https://github.com/flutter/engine/pull/54001 …
=> Prepend third_party/pyyaml to python sys.path

impeller/entity/contents/text_contents.cc
Dividing then multipliying can lead to position values like 432.99987 which end up losing a pixel.
=> [Impeller] ensure fp rounding errors don't cause us to lose a row of pixels when computing text positions.

impeller/toolkit/android/proc_table.h, impeller/toolkit/android/surface_control.cc, impeller/toolkit/android/surface_transaction.cc
Revert 0c417292c6bdac750ffede38998426fd6e825554
This was a partial revert. See explanation in https://github.com/flutter/engine/pull/54012#issuecomment-2243812137
=> [Impeller] Cleanly revert requiring backpressure for AHB swapchains.

.ci.yaml
Work around https://github.com/flutter/flutter/issues/151249.
This is similar to the change https://github.com/flutter/engine/pull/53912 I made on the 3.22 branch.
=> extend timeouts of all targets

ci/builders/mac_host_engine.json
Delete Impeller tests on beta branch due to the following failure:
`The GOLDCTL environment variable is not set. This is required for Skia Gold tests.`
=> Delete impeller tests on beta branch

shell/platform/linux/BUILD.gn, shell/platform/linux/fl_engine.cc, shell/platform/linux/fl_engine_private.h, shell/platform/linux/fl_engine_test.cc, shell/platform/linux/fl_view.cc, shell/platform/linux/fl_window_state_monitor.cc, shell/platform/linux/fl_window_state_monitor.h, shell/platform/linux/fl_window_state_monitor_test.cc, shell/platform/linux/testing/mock_window.cc, shell/platform/linux/testing/mock_window.h
Split window state monitor out of FlView and FlEngine to make it easier to handle different API when using GTK4. It also allows better tests.
=> Make FlWindowStateMonitor

shell/platform/linux/fl_engine.cc, shell/platform/linux/fl_engine_private.h, shell/platform/linux/fl_engine_test.cc, shell/platform/linux/fl_view.cc
Follow up to https://github.com/flutter/engine/pull/54018.
=> Set the view ID for FlView

shell/platform/linux/fl_renderer.cc, shell/platform/linux/fl_renderer_test.cc, shell/platform/linux/testing/mock_epoxy.cc, shell/platform/linux/testing/mock_epoxy.h
Workaround for https://github.com/flutter/flutter/issues/152099
=> Temporarily disable use of glBlitFramebuffer on NVIDIA

display_list/BUILD.gn, display_list/display_list.cc, display_list/display_list.h, display_list/display_list_unittests.cc, display_list/dl_builder.cc, display_list/dl_builder.h, testing/display_list_testing.cc
New flags on SaveLayerOptions will report if a saveLayer result is unbounded because a rendering operation within its contents did not have a definable bounds and there was no clip installed at the time (consider DrawPaint for example). A similar flag is found on DisplayList objects which reports if their top level had an unbounded operation.
=> [DisplayList] track unbounded state on save layers and DisplayLists

impeller/aiks/experimental_canvas.cc
Refactors flip backdrop into a shared method and adds supported for emulated advanced blends in exp canvas. Last missing feature (AFAIK).
=> [Impeller] add emulated advanced blend support for exp canvas.

shell/platform/darwin/ios/framework/Source/FlutterPlatformViews.mm, shell/platform/darwin/ios/framework/Source/FlutterPlatformViews_Internal.h
Since this method isn't mutating the pool, we should mark it const.
Cleanup spotted while working on https://github.com/flutter/engine/pull/54056.
No test because no semantic change. The compiler is the test. …
=> [iOS] Mark EmbeddedViewCount const

shell/platform/darwin/ios/framework/Source/FlutterPlatformViews.mm, shell/platform/darwin/ios/framework/Source/FlutterPlatformViewsTest.mm, shell/platform/darwin/ios/framework/Source/FlutterPlatformViews_Internal.h
`FlutterPlatformViewLayerPool` is a pool of iOS layers used for rendering platform views on iOS. When layers are no longer needed, we currently mark them available for re-use but we never actually flush them and thus recover the memory associated with these layers once we know that the layers are no longer needed.
We now flush the layer pool on `SubmitFrame` if a previously-used layer is no longer used in the current frame. In theory, this could cause a performance regression in the case where an additional layer is needed every second or third frame, but we should keep it simple on the first pass and only complicate things later if warranted.
Fixes: https://github.com/flutter/flutter/issues/152053 …
=> [iOS] Flush layer pool after platform view dispose

display_list/display_list_unittests.cc, testing/display_list_testing.h
Fixes 2 problems recently uncovered in the DisplayList verbose comparison test mechanism:
- The verbose compare methods never asserted a test failure, relying on the caller to do so from their return value - but they also did not prompt the caller to check the return value. So a `[[nodiscard]]` is added to remind test writers that they need to assert on the return value
- As a result of the above, some bad tests were recently added to the tree that were failing but did not assert a test failure. Now that the `[[nodiscard]]` is added, they failed to compile and had to have asserts added.
A secondary problem is that those non-failing tests were inadvertently cherry-picked from a reverted PR that is being reintroduced in incremental sections so as to avoid large scale golden image failures. …
=> [DisplayList] Fix assertions on DisplayList verbose comparison tests

lib/web_ui/lib/src/engine/dom.dart, lib/web_ui/test/engine/view_embedder/hot_restart_cache_handler_test.dart
This is in preparation for
https://dart-review.googlesource.com/c/sdk/+/373884, which will add length to the extension type itself. This will shadow the extension member, so we should make sure the type signatures match.
=> Change JSArray.length to return int

lib/web_ui/lib/src/engine/layers.dart, lib/web_ui/lib/src/engine/scene_builder.dart, lib/web_ui/test/engine/scene_builder_test.dart, lib/web_ui/test/engine/scene_builder_utils.dart
The occlusion rectangle for platform views was going through this `inverseMapRect` code path, which actually was giving us the wrong results. The operations should just be doing the normal transformation on the rectangles to get the right result. It actually turns out we don't need the inverse mapping function, so I removed it, and I renamed the somewhat confusingly named `cullRect` function to `mapRect` which I think makes a bit more sense.
This should resolve https://github.com/flutter/flutter/issues/152139
=> [skwasm] Fix platform view occlusion logic.

.gitignore, .vscode/extensions.json, ci/licenses_golden/excluded_files, tools/clang_tidy/test/header_filter_regex_test.dart
For example, without the markdown preview, files in `docs/**/*.md` don't all render.
=> Suggest a few common vscode extensions.

impeller/display_list/dl_dispatcher.cc
Impeller had been disabling a save layer bounds optimization under certain conditions that were meant to imply that the layer was unbounded.
The DisplayList now includes a flag indicating exactly when the layer is unbounded so we will now use that flag instead of an assumed implication to check for this condition.
=> [Impeller] Use new DisplayList SaveLayer unbounded flag

pubspec.yaml, shell/platform/fuchsia/dart-pkg/zircon/BUILD.gn, testing/litetest/pubspec.yaml, tools/fuchsia/dart/gen_dart_package_config.py
More incremental version of https://github.com/flutter/engine/pull/53997.
=> Move testing/litetest to pub workspaces.

ci/builders/mac_ios_engine.json, lib/snapshot/BUILD.gn, sky/tools/create_full_ios_framework.py
This merges the macOS and iOS rules for creating the `gen_snapshot_arm64` and `gen_snapshot_x64` used to build for iOS devices, as well as for iOS simulators on both arm64 hosts (`gen_snapshot_arm64`) and x64 hosts (`gen_snapshot_x64`). The macOS rules have already been updated to generate universal binaries for each of these that can be run on both Apple Silicon and Intel Mac hosts.
This also updates `create_full_ios_framework.py` to bundle the newly-generated universal gen_snapshot binaries and produce the artifacts.zip archive that is uploaded via the build config in `mac_ios_engine.json`.
The `create_arm_gen_snapshot` rule remains until I'm 100% convinced it's not used for macOS host Android target builds.
Issue: …
=> [iOS] Build universal gen_snapshots for iOS

impeller/renderer/backend/metal/context_mtl.h, impeller/renderer/backend/metal/context_mtl.mm, impeller/renderer/backend/metal/surface_mtl.h, impeller/renderer/backend/metal/surface_mtl.mm, shell/gpu/gpu_surface_metal_impeller.mm, shell/gpu/gpu_surface_metal_impeller_unittests.mm, shell/platform/darwin/ios/framework/Source/FlutterMetalLayer.mm
For this to work, we need to provide our own capture scope otherwise the default scope won't capture our commands.
This is required as part of the work to switch to unmerged threads for PVs (https://github.com/flutter/engine/pull/53826), as I can confirm @knopp 's observations that the performance is much worse with the default CAMetalLayer.
Fixes https://github.com/flutter/flutter/issues/140901
=> [iOS] Switch to FlutterMetalLayer by default.

shell/platform/android/io/flutter/embedding/android/KeyEmbedderResponder.java, shell/platform/android/test/io/flutter/embedding/android/KeyboardManagerTest.java, shell/platform/android/test/io/flutter/util/FakeKeyEvent.java
Removes a line that shadows setting the device type correctly for keyboard events.
- Fixes https://github.com/flutter/flutter/issues/151308
=> Remove incorrect line

shell/platform/darwin/ios/framework/Source/FlutterMetalLayer.mm
Backing textures aren't getting deallocated, which is causing memory leaks and crashing devicelab.
=> Disable FlutterMetalLayer by default.

lib/web_ui/lib/src/engine/semantics/checkable.dart, lib/web_ui/lib/src/engine/semantics/dialog.dart, lib/web_ui/lib/src/engine/semantics/focusable.dart, lib/web_ui/lib/src/engine/semantics/heading.dart, lib/web_ui/lib/src/engine/semantics/image.dart, lib/web_ui/lib/src/engine/semantics/incrementable.dart, lib/web_ui/lib/src/engine/semantics/label_and_value.dart, lib/web_ui/lib/src/engine/semantics/link.dart, lib/web_ui/lib/src/engine/semantics/live_region.dart, lib/web_ui/lib/src/engine/semantics/platform_view.dart, lib/web_ui/lib/src/engine/semantics/scrollable.dart, lib/web_ui/lib/src/engine/semantics/semantics.dart, lib/web_ui/lib/src/engine/semantics/tappable.dart, lib/web_ui/lib/src/engine/semantics/text_field.dart, lib/web_ui/test/engine/semantics/semantics_test.dart, lib/web_ui/test/engine/semantics/semantics_tester.dart, lib/web_ui/test/engine/semantics/semantics_text_test.dart, lib/web_ui/test/engine/semantics/text_field_test.dart
A few non-functional clean-ups in semantics:
* Rename `RoleManager` to `SemanticBehavior`.
* Rename `PrimaryRoleManager` to `SemanticRole`.
* Remove the `Role` enum. Move the enum docs into the respective classes.
Previous naming was confusing. It's not clear what the difference is between a "role manager" and a "primary role manager". The word "manager" is a meaningless addition; the `Semantic*` prefix is much more meaningful. The `Role` enum was only used for tests, but tests can just use `SemanticRole.runtimeType`.
After this PR the semantics system has "objects" (class `SemanticsObject`), "roles" (class `SemanticRole`), and "behaviors" (class `SemanticBehavior`).
- A semantic _object_ is an object attached to the framework-side `SemanticNode`. It lives as long as the semantic node …
=> [web] better class names for semantics

shell/platform/linux/fl_engine.cc, shell/platform/linux/fl_engine_private.h, shell/platform/linux/fl_event_channel_test.cc, shell/platform/linux/fl_view.cc, shell/platform/linux/public/flutter_linux/fl_engine.h, shell/platform/linux/public/flutter_linux/fl_view.h, shell/platform/linux/testing/fl_test.cc
While only one view works at this point in the future this will allow a runner to create multiple views.
To make use of this the runner template would have the following changes:
```diff
diff --git a/linux/my_application.cc b/linux/my_application.cc
index 7083591..e56f6d8 100644
--- a/linux/my_application.cc
+++ b/linux/my_application.cc
@@ -10,6 +10,8 @@
struct _MyApplication {
GtkApplication parent_instance;
char** dart_entrypoint_arguments;
+
+  FlEngine* engine;
};
G_DEFINE_TYPE(MyApplication, my_application, GTK_TYPE_APPLICATION)
@@ -53,7 +55,9 @@ static void my_application_activate(GApplication* application) {
g_autoptr(FlDartProject) project = fl_dart_project_new();
fl_dart_project_set_dart_entrypoint_arguments(project, self->dart_entrypoint_arguments);
-  FlView* view = …
```
=> Allow creating views from an external engine

shell/platform/darwin/ios/framework/Source/FlutterMetalLayer.mm, shell/platform/darwin/ios/framework/Source/FlutterMetalLayerTest.mm
=> Fix retain cycle in FlutterMetalLayer

lib/web_ui/lib/src/engine/dom.dart
This only addresses the following:
- Removes `JSVoid` in favor of `void`. `JSVoid`, which is just a typedef, should be deprecated and removed eventually.
- Removes extra interop methods that were needed to make sure arity was correct. These are no longer needed as interop methods are invocation-sensitive and calls to them do not forward more arguments than were passed by the user.
- Removes unnecessary annotations on extensions.
Still left to do (not comprehensive):
- Migrate to extension types.
- Remove forwarding methods that are only used to convert primitives in favor of changing the interop method to include the Dart primitive type. It might be a bit slower in dart2wasm to do this, but will need to verify and fix it if that's the case.
- Remove usage of `js_util`.
- See if we can …
=> Initial pass to cleanup dom.dart to use newer JS interop styles

shell/platform/android/android_shell_holder_unittests.cc, shell/platform/android/jni/jni_mock.h, shell/platform/android/jni/platform_view_android_jni.h, shell/platform/android/platform_view_android_jni_impl.cc, shell/platform/android/platform_view_android_jni_impl.h, shell/platform/android/surface_texture_external_texture.cc, shell/platform/android/surface_texture_external_texture.h, shell/platform/android/surface_texture_external_texture_vk_impeller.cc
SurfaceTextureGetTransformMatrix returns a col-major 4x4 matrix. We used to convert it to a 3x3 matrix. Then when applying the transformation in the shader, I'd convert it back to a 4x4 matrix.
Instead of all this (potentially lossy) flip-flopping, store the matrix just as we get it in 4x4 form and perform the conversion just once if necessary. Today, it is necessary only in the Skia backend. SkM44 already has a converter to convert to and from a 3x3 SkMatrix. So, use that instead of rolling our own.
I spent a lot of time debugging these conversions and transformations because we had rolled our own and the printers seemed to dump in row-major order irrespective of storage order. This caused a lot of confusion.
No change in functionality. Hopefully, the next person debugging …
=> Directly use 4x4 matrices with surface textures instead of converting to and from the 3x3 variants.

shell/platform/linux/fl_renderer.cc, shell/platform/linux/fl_view.cc
GLArea.has-alpha defaults to false, which makes it impossible for a Flutter app to be transparent.
The additional change to glClearColor is to prevent a black flash when the application starts, before Flutter widgets become visible. This will also affect applications that aren't transparent, by showing the default GTK background color instead of black. This will not make the window transparent, because the developer currently has to add some code to their `linux/my_application.cc` to support transparency.
Fixes flutter/flutter#152154
Transparent windows were possible before #50754. Would it be ok to add a test for this to prevent breaking transparency again in the future? …
=> Set GLArea.has-alpha = true

display_list/display_list_unittests.cc, display_list/dl_builder.cc, display_list/testing/dl_test_snippets.cc
Fixes: https://github.com/flutter/flutter/issues/151850
Re-adding an optimization originally included in https://github.com/flutter/engine/pull/53642 that detects when ClipRRect and ClipPath operations are actually ovals and redirects them to the ClipOval path during recording to save space and reduce the need for dispatchers to do the same detections and optimizations.
=> [DisplayList] Optimize ClipRRect and ClipPath to ClipOval when appropriate

impeller/display_list/BUILD.gn, impeller/display_list/dl_golden_blur_unittests.cc, impeller/display_list/dl_playground.cc, impeller/display_list/dl_playground.h, impeller/golden_tests/BUILD.gn, impeller/golden_tests/golden_playground_test.h, impeller/golden_tests/golden_playground_test_mac.cc, impeller/golden_tests/golden_playground_test_stub.cc, impeller/golden_tests/metal_screenshotter.mm
fixes https://github.com/flutter/flutter/issues/152195
Part of a series of gaussian blur changes:
1) https://github.com/flutter/engine/pull/54148
1) https://github.com/flutter/engine/pull/54116
1) https://github.com/flutter/engine/pull/54150
1) https://github.com/flutter/engine/pull/54149
Note: this test won't pass until https://github.com/flutter/engine/pull/54148 lands. …
=> [impeller] adds test for catching shimmer in gaussian blur

ci/builders/mac_host_engine.json, ci/builders/mac_ios_engine.json, ci/builders/mac_unopt.json, tools/gn
This PR does a few things. Mainly it makes the builds in mac_host_engine.json each build fewer targets to increase parallelism for post-submit and release builds. To ensure that increasing parallelism doesn't lead to capacity issues, this change also allows the mac_host_engine.json builds to run on either intel or arm64 macOS hosts. Finally, when building on an arm64 macOS host to target macOS, this PR changes the `gn` script to ensure that the arm64 native clang toolchain will be used.
To keep mac_host_engine.json focused on builds that produce artifacts, this PR also moves tests from that file into the ill-named mac_unopt.json. In a subsequent PR, I'll rename all the *_unopt.json files to *_tests.json or something similar.
The artifacts produced by these builds are passing framework …
=> Split up mac_host_engine builds

lib/ui/BUILD.gn, shell/platform/fuchsia/dart_runner/BUILD.gn, shell/platform/fuchsia/runtime/dart/utils/BUILD.gn, shell/testing/BUILD.gn
The concurrent_api/concurrent_api_product targets were made obsolete by https://github.com/dart-lang/sdk/commit/95f5efc6976c4645db5fbad9e501e755579a58eb
=> Remove obsolete dependency

build/dart/rules.gni, ci/licenses_golden/excluded_files, ci/pubspec.yaml, pubspec.yaml, testing/smoke_test_failure/BUILD.gn, testing/smoke_test_failure/pubspec.yaml, tools/android_lint/pubspec.yaml, tools/api_check/pubspec.yaml, tools/build_bucket_golden_scraper/pubspec.yaml, tools/clang_tidy/pubspec.yaml, tools/clangd_check/pubspec.yaml, tools/compare_goldens/pubspec.yaml, tools/const_finder/BUILD.gn, tools/const_finder/pubspec.yaml, tools/dir_contents_diff/pubspec.yaml, tools/find_pubspecs_to_workspacify.sh, tools/gen_web_locale_keymap/pubspec.yaml, tools/githooks/pubspec.yaml, tools/header_guard_check/pubspec.yaml, tools/licenses/pubspec.yaml, tools/path_ops/dart/pubspec.yaml, tools/pkg/engine_build_configs/pubspec.yaml, tools/pkg/engine_repo_tools/pubspec.yaml, tools/pkg/git_repo_tools/pubspec.yaml
Part of https://github.com/flutter/flutter/issues/147883.
Excluding Fuchsia and the Web SDK, the remaining scripts are:
```sh
$ ./tools/find_pubspecs_to_workspacify.sh
/Users/matanl/Developer/engine/src/flutter/impeller/tessellator/dart/pubspec.yaml
/Users/matanl/Developer/engine/src/flutter/sky/packages/sky_engine/pubspec.yaml
/Users/matanl/Developer/engine/src/flutter/shell/vmservice/pubspec.yaml
/Users/matanl/Developer/engine/src/flutter/lib/snapshot/pubspec.yaml
/Users/matanl/Developer/engine/src/flutter/lib/gpu/pubspec.yaml
/Users/matanl/Developer/engine/src/flutter/lib/web_ui/pubspec.yaml
/Users/matanl/Developer/engine/src/flutter/flutter_frontend_server/pubspec.yaml
```
These could be the trickiest, so I'm doing them separately.
=> Migrates the bulk of flutter/engine to pub workspaces.

tools/pkg/engine_build_configs/test/build_config_runner_test.dart
This test failure had been seen in some recent auto-roller jobs on CI.
=> Fix a race in file I/O done by a BuildRunner test

common/settings.h, shell/platform/android/io/flutter/embedding/engine/FlutterShellArgs.java, shell/platform/android/io/flutter/embedding/engine/loader/FlutterLoader.java, shell/platform/android/test/io/flutter/embedding/engine/loader/FlutterLoaderTest.java, shell/platform/darwin/ios/framework/Source/FlutterDartProject.mm, testing/scenario_app/android/app/src/androidTest/java/dev/flutter/TestRunner.java, testing/scenario_app/bin/run_android_tests.dart
Developers can control the backend in the following ways:
* **Do nothing**: Impeller with Vulkan is used where Vulkan is available with a fallback to Skia with OpenGL.
* **In `AndroidManifest.xml`, specify `io.flutter.embedding.android.EnableImpeller` as `false`**: Skia with OpenGL is used.
* **On the command line, specify `--no-enable-impeller`**: Skia with OpenGL is used.
Manifest options will take priority command line options when there is a conflict. This matches iOS behavior per https://github.com/flutter/flutter/issues/124049 (closed as WAI).
Fixes https://github.com/flutter/flutter/issues/149360
=> [Impeller] Enable on-by-default on Android.

lib/io/BUILD.gn, shell/platform/embedder/BUILD.gn
Follow-up to b0d1df5cfb98241fa8a881df0796a6046acf860a - remove obsolete dependency from few more places that were missed.
=> Remove obsolete dependency from few more targets.

shell/platform/linux/fl_renderer.cc, shell/platform/linux/fl_view.cc
Reason for revert: Regression + no tests. Must have been at the end of a long day, cause I missed the missing test and glaring warning about that.
This reverts commit 0844c0a31d82ddd66dad8c564665d48c0b7118bc.
Re-opens https://github.com/flutter/flutter/issues/152154 …
=> Revert "Set GLArea.has-alpha = true (#54053)"

impeller/entity/contents/filters/gaussian_blur_filter_contents.cc
This removes jitter in the gaussian blur.
Previous version of the shimmer test show this drops the average RMSE 30%.
testing:
- positive change shown in average RMSE in ShimmerTest
- existing golden tests
Part of a series of gaussian blur changes:
1) https://github.com/flutter/engine/pull/54148
1) https://github.com/flutter/engine/pull/54116
1) https://github.com/flutter/engine/pull/54150
1) https://github.com/flutter/engine/pull/54149 …
=> [Impeller] makes the gaussian down sample scalar fixed by adjusting the downsample padding

flow/diff_context.cc, flow/diff_context.h, flow/layers/container_layer.cc, flow/layers/platform_view_layer.cc, flow/layers/platform_view_layer.h, flow/layers/platform_view_layer_unittests.cc, flow/layers/texture_layer.cc, flow/paint_region.h, shell/common/rasterizer.cc
Currently we force full repaint when thread merging is detected, but that is not a good way to determine whether platform view is in hierarchy when thread merging is no longer needed. Alternative solution here makes the PlatformViewLayer  force full repaint when diffing.
[testing the …
=> Do not disable partial repaint based on thread merging state

sky/tools/create_full_ios_framework.py, sky/tools/create_macos_gen_snapshots.py
Our executables are no longer built with bitcode enabled and thus `bitcode_strip -r SOURCE -o DEST` is just copying the file in question to the output location.
Use of Bitcode was eliminated in Flutter in 2022. See linked issue for details.
Issue: https://github.com/flutter/flutter/issues/107884 …
=> [iOS][macOS] Eliminate use of bitcode_strip

shell/common/fixtures/shell_test.dart
=> Cleanup the shell test, removing unused code

lib/web_ui/lib/src/engine/canvaskit/image.dart, lib/web_ui/lib/src/engine/image_decoder.dart, lib/web_ui/test/canvaskit/image_test.dart
Fixes https://github.com/flutter/flutter/issues/147066
=> [web] Dispose a temporary image that may be created by instantiateImageCodecWithSize

shell/platform/android/io/flutter/plugin/editing/TextInputPlugin.java, shell/platform/android/test/io/flutter/plugin/editing/TextInputPluginTest.java
This PR reverts two commits https://github.com/flutter/engine/pull/49829 and https://github.com/flutter/engine/pull/53662.
The main change was in https://github.com/flutter/engine/pull/49829. https://github.com/flutter/engine/pull/53662 was a follow-up to mitigate the impact of https://github.com/flutter/engine/pull/49829.
Fixes https://github.com/flutter/flutter/issues/148530
Fixes https://github.com/flutter/flutter/issues/152620
Reopens https://github.com/flutter/flutter/issues/70546.
Reopens https://github.com/flutter/flutter/issues/51478
=> [Android] Revert "Reset IME state on clear text input client"

testing/scenario_app/android/app/src/androidTest/java/dev/flutter/scenariosui/ScreenshotUtil.java
This is just better anyway, and will work around an Android 35 failure we're investigating.
=> Use `InetAddress.getLoopback()` versus a string.

impeller/core/host_buffer.cc, impeller/core/host_buffer.h, impeller/entity/contents/host_buffer_unittests.cc
Fixes https://github.com/flutter/flutter/issues/151084
If allocating a host buffer fails, log a validation error but don't cause an NPE by inserting a nullptr into the host buffer set.
=> [Impeller] check allocation failures.

display_list/benchmarking/dl_builder_benchmarks.cc, display_list/testing/dl_test_snippets.cc
We will be updating the DisplayList dispatching to support random access iteration through the records so we need a benchmark to set a baseline to track any impact on the default way to dispatch a DisplayList.
=> [DisplayList] benchmark DisplayList dispatch method

shell/platform/common/accessibility_bridge.cc, shell/platform/common/accessibility_bridge.h, shell/platform/common/flutter_platform_node_delegate.h, shell/platform/darwin/macos/framework/Source/AccessibilityBridgeMac.mm, shell/platform/darwin/macos/framework/Source/FlutterPlatformNodeDelegateMac.h, shell/platform/darwin/macos/framework/Source/FlutterPlatformNodeDelegateMac.mm, shell/platform/darwin/macos/framework/Source/FlutterPlatformNodeDelegateMacTest.mm, shell/platform/darwin/macos/framework/Source/FlutterTextInputSemanticsObject.mm, shell/platform/darwin/macos/framework/Source/FlutterViewController.mm
Fixes https://github.com/flutter/flutter/issues/151428
[CLA]: …
=> macOS: Update platform node when AXNodeData role changes

impeller/entity/shaders/gradients/fast_gradient.vert, impeller/tools/malioc.json
This is another precision mismatch bug - WHICH IS NOT AN ERROR AT ALL BUT THE PowerVR Drivers ARE BUGGY BUGGY BUGGY
Fixes https://github.com/flutter/flutter/issues/152951
=> [Impeller] ensure precision matches for buggy vulkan drivers.

impeller/entity/contents/content_context.cc, impeller/renderer/backend/vulkan/pipeline_vk.cc
Fixes the regression to the first-frame time on the Mokey.
Also add a trace that should allow for easier identification of problematic pipelines.
A more involved job-queue that allows construction jobs to skip the queue was written in https://github.com/flutter/engine/pull/54355. But the Mokey case is not important enough for the additional complexity. See the context in the linked patch.
[start_up_timeline.json.zip](https://github.com/user-attachments/files/16515389/start_up_timeline.json.zip)
=> [Impeller] Reorder pipeline construction in content context.

flow/diff_context.cc, flow/diff_context.h, flow/layers/container_layer.cc, flow/layers/platform_view_layer.cc, flow/layers/platform_view_layer.h, flow/layers/platform_view_layer_unittests.cc, flow/layers/texture_layer.cc, flow/paint_region.h, shell/common/rasterizer.cc
Relands https://github.com/flutter/engine/pull/54219 reverted in https://github.com/flutter/engine/pull/54230.
The tracked area of `PlatformViewLayer` now covers entire frame ensuring full repaint when platform view is removed. 
Added `FullRepaintAfterRemovingLayer` test.
[testing the …
=> Reland: Partial repaint platform views

impeller/typographer/backends/skia/typographer_context_skia.cc
Fixes https://github.com/flutter/flutter/issues/152977
When creating a new glyph atlas texture, write glyphs in bulk. Additionally uses this operation to clear the glyph atlas, removing the need for the other blit pass.
=> [Impeller] bulk update fresh glyph atlas.

impeller/aiks/paint.cc, impeller/geometry/matrix.cc, impeller/geometry/matrix.h, impeller/geometry/vector.h
Vector2 has `GetLength()` but Vector3 had `Length()`.  This unifies the naming. …
=> [Impeller] made Vector3 naming match Vector2 naming.

impeller/compiler/code_gen_template.h, impeller/renderer/shader_stage_compatibility_checker.h
Also removes the workarounds and updates the docstring to talk about the PowerVR hack. I came across this while fixing https://github.com/flutter/engine/pull/54375.
Fixes https://github.com/flutter/flutter/issues/146852
=> [Impeller] Make stage compatibility checker work with stages that have no inputs or outputs.

sky/tools/create_full_ios_framework.py, sky/tools/create_xcframework.py
As of Xcode 16, App Store validation requires dSYMs for frameworks in app archives. Bundling dSYMs also significantly simplifies stack trace symbolification, so we should be doing this regardless.
This adds both framework and simulator framework dSYMs to the Flutter.xcframework bundle. …
=> [iOS] Bundle dSYM packages in Flutter.xcframework

shell/platform/darwin/ios/framework/Source/FlutterMetalLayerTest.mm
Fixes https://github.com/flutter/flutter/issues/152990 …
=> Fix FlutterMetalLayer testDealloc flakiness on iOS 18

shell/platform/embedder/embedder.cc, shell/platform/embedder/embedder.h, shell/platform/embedder/embedder_external_view.cc, shell/platform/embedder/embedder_render_target.h, shell/platform/embedder/embedder_render_target_skia.cc, shell/platform/embedder/embedder_render_target_skia.h, shell/platform/embedder/tests/embedder_assertions.h, shell/platform/embedder/tests/embedder_config_builder.cc, shell/platform/embedder/tests/embedder_gl_unittests.cc, shell/platform/embedder/tests/embedder_test_backingstore_producer.cc, shell/platform/embedder/tests/embedder_test_backingstore_producer.h, shell/platform/embedder/tests/embedder_test_compositor_gl.cc, shell/platform/embedder/tests/embedder_test_compositor_software.cc, shell/platform/embedder/tests/embedder_test_context.h, shell/platform/embedder/tests/embedder_test_context_gl.cc, shell/platform/embedder/tests/embedder_test_context_gl.h, shell/platform/embedder/tests/embedder_unittests.cc, testing/test_gl_surface.cc, testing/test_gl_surface.h
Allows using an EGL surface as a flutter backing store. Way more convenient for GBM than hacking gbm bo's into GL FBOs.
This resolves https://github.com/flutter/flutter/issues/58363
Currently, the embedder API assumes that the compositor (if it exists) will let flutter render into FBOs or Textures and then composite the whole thing onto the actual (EGL) window surface. I think this assumption is also documented a bit in https://github.com/flutter/flutter/issues/38466
However, in my case, I want let the hardware do the composition (using the linux KMS API), and render each flutter layer into it's own EGL surface.
It's possible to hack around this by creating your own GBM BOs, importing those as EGL images, then importing those as GL Render Buffers and attaching those to GL FBOs and that …
=> Add EGL Surface backing store

impeller/renderer/backend/metal/surface_mtl.h, impeller/renderer/backend/metal/surface_mtl.mm, shell/gpu/gpu_surface_metal_impeller.mm
Fixes the reported GPU time regression when rendering platform views. The problem was that we delayed the tracing of the end of the frame until the CATransaction, which artificially stretches out GPU frame time. Instead add a new method SurfaceMTL::PreparePResent which performs the final blit and tracing, call this in the encode callback.
Fixes: https://flutter-flutter-perf.skia.org/e/?queries=sub_result%3Daverage_gpu_frame_time%26test%3Dplatform_views_scroll_perf_ios__timeline_summary&selected=commit%3D41853%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DiPhone_11%252Cdevice_version%253Dnone%252Chost_type%253Dmac%252Csub_result%253Daverage_gpu_frame_time%252Ctest%253Dplatform_views_scroll_perf_ios__timeline_summary%252C
Test: benchmarks.
=> [Impeller] perform final blit and gpu end frame tracing earlier.

sky/tools/create_full_ios_framework.py
Renames our Flutter framework dSYM to `Flutter.framework.dSYM` for consistency with all other dSYM bundle names. In iOS release archives, all other dSYM files are:
* `App.framework`: `App.framework.dSYM`
* `Runner.app`: `Runner.app.dSYM`
We continue to archive the dSYM to `Flutter.dSYM.zip` for backward compatibility with the existing instructions for manual symbolification in `docs/Crashes.md` and to remain compatible with dart-lang/dart-ci's symbolizer which expects `Flutter.dSYM` in [`Symbolizer._symbolizeIosFrames`][symbolizer].
Followup to: flutter/engine#54414
Motto: [Embrace the yak shave][yak_shave].
[symbolizer]: https://github.com/dart-lang/dart_ci/blob/e9fd9884a2c76184f4d20eb8a1cb48f92ec63ab5/github-label-notifier/symbolize …
=> [iOS] Rename Flutter.dSYM to Flutter.framework.dSYM

impeller/docs/faq.md
Fixes https://github.com/flutter/flutter/issues/153120
=> [Impeller] Add FAQ entries.

ci/builders/mac_ios_engine.json, sky/tools/create_full_ios_framework.py
As of the following three patches, we now bundle Flutter.framework.dSYM as part of Flutter.xcframework and bundle them in the .xcarchive bundles produced by `flutter build ipa` / Xcode Product > Archive for upload to the iOS App Store.
* https://github.com/flutter/engine/pull/54414
* https://github.com/flutter/engine/pull/54458
* https://github.com/flutter/flutter/pull/153215
The .dSYM bundle is now available both in the uploaded .xcarchive and in the xcframework in Flutter's internal artifact cache. For developers with CI toolchains that do additional manual handling or local archiving of .dSYMs, the dSYMs no longer need to be downloaded from cloud storage as previously detailed in `docs/Crashes.md`, but can instead be copied up from the appropriate dSYM subdirectory in the framework …
=> [iOS] Do not archive/upload Flutter.dSYM to cloud

docs/Crashes.md
As of flutter/flutter#153215, end user app archives now include symbols for the Flutter framework by default. So manual symbolication is no longer required.
For engine developers and others who still need to deal with manual symbols, they can now be found in the Flutter tool cache and can thus be obtained from there if required.
[C++, …
=> iOS,docs: Update iOS symbolication docs

impeller/display_list/dl_dispatcher.cc
Fixes issue where we don't detect unbounded contents in Impeller
https://github.com/flutter/flutter/issues/152955
=> [CP][Impeller] detect max cull rect on bounds. (#54013)

flow/surface_frame.h, shell/gpu/gpu_surface_gl_impeller.cc, shell/gpu/gpu_surface_metal_impeller.mm, shell/gpu/gpu_surface_metal_impeller_unittests.mm, shell/gpu/gpu_surface_vulkan_impeller.cc, shell/platform/darwin/ios/framework/Source/FlutterPlatformViews.mm
Fixes https://github.com/flutter/flutter/issues/151274
This is only an issue on iOS (so far) because of the platform view rendering strategy that involves submitting multiple impeller frames per compositor frame.
FYI @bdero
=> [CP][Impeller] mark the end of a frame boundary for system compositor interop. (#53722)

shell/platform/embedder/embedder.cc, shell/platform/windows/compositor_opengl.cc, shell/platform/windows/compositor_opengl.h
This improves Flutter Window's texture format logic:
1. **If the device has extension `GL_EXT_texture_format_BGRA8888`**: backing stores' texture will be created with format `GL_BGRA_EXT` instead of `GL_RGBA8`. This is what fixes https://github.com/flutter/flutter/issues/150546.
2. **Otherwise**: backing stores' texture will be created with format `GL_RGBA` and the engine will use the color type `kRGBA_8888_SkColorType` when creating the `SkSurface`.
Previously the engine always used color type `kN32_SkColorType`, which could be either RGBA or BGRA depending on the machine that compiled the engine. This caused Skia validation errors as the texture's format did not match the Skia surface's color type.
I tested this by editing Flutter Windows to force it down this code path.
Huge kudos to …
=> [Windows] Improve texture format logic

shell/platform/darwin/macos/framework/Source/FlutterTextInputPlugin.mm, shell/platform/darwin/macos/framework/Source/FlutterTextInputPluginTest.mm
Fixes https://github.com/flutter/flutter/issues/153157
[CLA]: …
=> macOS: Fix crash in attributedSubstringForProposedRange with out of bounds range

shell/platform/darwin/ios/framework/Source/platform_views_controller.h, shell/platform/darwin/ios/framework/Source/platform_views_controller.mm, shell/platform/darwin/ios/ios_external_view_embedder.mm
Potential fix for money crasher.
=> [iOS] keep threads merged when using Skia renderer on iOS

shell/platform/darwin/ios/framework/Source/FlutterPlatformViewsTest.mm, shell/platform/darwin/ios/framework/Source/platform_views_controller.mm
Fixes https://github.com/flutter/flutter/issues/153335
When platform views are present, we always repaint entire frame. We must pass the buffer damage all the way to `GPUSurfaceMetalSkia/GPUSurfaceMetalImpeller` so that they know that the other two surfaces are lagging behind front surface and need to be repainted.
This is currently not being done with platform view present, that's why we miss full frame repaint when removing platform view.
With this merged in, it should be safe to reland https://github.com/flutter/engine/pull/54537 without any changes. …
=> Preserve background frame damage

sky/tools/create_macos_framework.py, sky/tools/sky_utils.py
Over time, this script and others in sky/tools have accumulated a lot of additional and sometimes duplicate code.
This is a first pass cleanup of create_macos_framework.py to extract common utility code to utils.py and refactor for better readability.
The iOS analogue of this patch was flutter/engine#54500. …
=> macOS: Clean up create_ios_framework.py

lib/gpu/lib/gpu.dart
Update dartdoc for package:flutter_gpu with:
1) details on how to use the sdk dep
2) the current docs link
[breaking …
=> Update dartdoc for gpu.dart

display_list/benchmarking/dl_builder_benchmarks.cc, display_list/display_list.cc, display_list/display_list.h, display_list/display_list_unittests.cc, display_list/dl_builder.h, display_list/dl_op_records.h, testing/display_list_testing.cc, testing/display_list_testing.h
Being able to reorder rendering commands leads to optimization opportunities in the graphics package. A graphics package being fed from a DisplayList either has to take the commands in the order given or implement their own storage format for the rendering data.
With this new dispatching mechanism, the graphics package can both query basic information about the recorded ops and even dispatch them by the index into the list. Query information includes either the "category" of the op (clip/transform/render, etc.) or a specific op type enum. The package can dispatch some categories (or ops) immediately and remember other categories (or ops) along with their state for dispatching later.
=> [DisplayList] Allow random access to ops through indexing

sky/tools/create_macos_framework.py, sky/tools/sky_utils.py
This is a refactoring with no semantic changes.
This refactors the macOS framework creation code to be more readable, and extracts it to sky_utils.py.
While I was pulling this out, also generalised the code to not hardcode FlutterMacOS.framework in case we one day manage to generate the iOS and macOS frameworks with the same name. …
=> macOS: refactor create_macos_framework.py

sky/tools/create_macos_framework.py, sky/tools/sky_utils.py
Over time, this script and others in `sky/tools` have accumulated a lot of additional and sometimes duplicate code.
This is a first pass cleanup of `create_macos_framework.py` to extract common utility code to `sky/utils.py` and refactor for better readability.
The iOS analogue of this patch was flutter/engine#54500.
This is a reland of flutter/engine#54543 (reverted in flutter/engine#54550), which failed to set the `-y` option (preserve symlinks) when zipping `FlutterMacOS.xcframework` but did so for the other zip steps where required. Since there is no case where we *want* to archive dereferenced symlinks, and because it's required for macOS frameworks, we now set this option for all callers in the `sky_tools.create_zip()` function to avoid future cases where someone working on this …
=> macOS: Clean up create_macos_framework.py (#54543)

flow/diff_context.cc, flow/diff_context.h, flow/layers/container_layer.cc, flow/layers/platform_view_layer.cc, flow/layers/platform_view_layer.h, flow/layers/platform_view_layer_unittests.cc, flow/layers/texture_layer.cc, flow/paint_region.h, shell/common/rasterizer.cc, shell/platform/darwin/ios/framework/Source/platform_views_controller.h, shell/platform/darwin/ios/framework/Source/platform_views_controller.mm, shell/platform/darwin/ios/ios_external_view_embedder.mm
=> [CP] PR #54514 and #54537 onto the release branch

docs/rbe/rbe.md
Add `could not get valid Application Default Credentials token` troubleshooting
=> Update RBE troubleshooting

lib/ui/platform_dispatcher.dart
Fixes small typo in AppLifecycleState enum documentation. Documentation to enum references iOS article about managing app lifecycle in UIKit. So, "IOKit" is a misspelled word "UIKit"
I found out Apple has [IOKit framework](https://developer.apple.com/documentation/iokit) but it is not related to app lifecycle …
=> Fix typo in AppLifecycleState documentation

common/config.gni
Revert due to framework crashes: https://github.com/flutter/flutter/pull/153521
=> [Impeller] revert experimental canvas.

sky/tools/create_full_ios_framework.py
In flutter/engine#54414, we added dSYM files for physical and simulator binaries in both regular and extension-safe framework builds, but did not add the dSYMs to the without_entitlements.txt list.
This passed all engine pre/post-submit tests, as well as framework tests, but failed during release codesigning in Cocoon in a test here: https://github.com/flutter/cocoon/blob/d849b14bab90e0f90e2f7667e37c9f9a5696b918/cipd_packages/codesign/lib/src/file_codesign_visitor.dart#L305-L313
This adds the missing files to without_entitlements.txt. …
=> iOS: Add dSYM binaries to without_entitlements.txt

.ci.yaml, ci/builders/linux_fuchsia.json, ci/builders/linux_fuchsia_tests.json
Temporary workaround for https://github.com/flutter/flutter/issues/152186.
=> Move Fuchsia tests to a separate config file

sky/tools/create_macos_framework.py, sky/tools/sky_utils.py
This refactors `create_mac_framework.py` to extract framework creation to `sky_utils.py`. The only other changes are minor variable renaming and extraction of functions to make the code more readable/easier to work with.
The resulting zip archives have been verified to be identical before and after.
This is refactoring to support embedding dSYM debug information in a follow-up patch.
[C++, …
=> macOS: Extract framework creation to sky_utils

impeller/docs/faq.md
Fixes https://github.com/flutter/flutter/issues/153316
Other than one question that pointed to outdated links, its just the same as the old FAQ. Will submit the updates based on recent conversations in a followup patch.
It should now be possible to link to specific questions in the FAQ.
=> [Impeller] use paragraphs instead of bullet points in the FAQ.

sky/tools/create_full_ios_framework.py
Fixes https://github.com/flutter/flutter/issues/153532
Cherrypicks https://github.com/flutter/engine/pull/54573 (from flutter-3.24-candidate.1 branch) to the 3.24 stable candidate branch.
=> Cherrypick entitlements file fix to 3.24 branch

impeller/docs/faq.md
Action item from go/impeller-faq-followups.
=> [Impeller] Add a note about Graphite to the FAQ.

lib/web_ui/pubspec.yaml, web_sdk/pubspec.yaml
Also removed two unused dev dependencies
Enables usage of `Since` in dart:js_interop
=> web_ui: bump min Dart SDK to 3.6.0-0

display_list/BUILD.gn, display_list/display_list_unittests.cc, display_list/dl_builder.h, display_list/dl_color.cc, display_list/dl_color.h, display_list/dl_color_unittests.cc, display_list/dl_vertices.cc, display_list/dl_vertices.h, display_list/effects/dl_color_source.cc, display_list/effects/dl_color_source.h, display_list/skia/dl_sk_canvas.cc, display_list/skia/dl_sk_conversions.cc, display_list/skia/dl_sk_conversions.h, display_list/skia/dl_sk_dispatcher.cc, display_list/testing/dl_rendering_unittests.cc, display_list/testing/dl_test_snippets.cc, impeller/display_list/dl_dispatcher.cc, impeller/display_list/skia_conversions.cc, lib/ui/painting/gradient.cc, testing/display_list_testing.cc
integration test: https://github.com/flutter/engine/pull/54415
This is the engine side changes required for wide gamut framework support.  It changes the internal representation of DlColor to be floats.  It will be married with https://github.com/flutter/engine/pull/54415 when it lands in https://github.com/flutter/engine/pull/54567. …
=> Changes DlColor to support wide gamut colors

impeller/geometry/matrix.h, impeller/geometry/matrix_unittests.cc
Otherwise we get funky negative scales that break tessellation.
=> [Impeller] account for negative scale in max basis xy.

display_list/display_list_unittests.cc, display_list/dl_builder.cc, display_list/geometry/dl_region.cc, flow/diff_context.cc, flow/diff_context_unittests.cc, flow/view_slicer.cc
The `SkRect::intersect` and `SkIRect::intersect` methods return values that must be handled or the calling code might end up with a non-empty answer for non-intersecting rectangles. There were 3 or 4 places in our code that we weren't doing this so now we check them all, in some cases even if we believe that the answer will not be empty.
This is prep work so that Skia can add `[[nodiscard]]` directives to these 2 methods so that nobody else makes that mistake.
=> Check return values for Sk[I]Rect::intersect

shell/platform/android/BUILD.gn, shell/platform/android/io/flutter/embedding/android/FlutterView.java, shell/platform/android/io/flutter/embedding/android/FlutterViewDelegate.java, shell/platform/android/io/flutter/embedding/engine/renderer/FlutterRenderer.java
Original Title: Add FlutterViewDelegate and BoundingRect methods
Check the bounding rect for caption bar when sending viewport metrics to Flutter to account for freeform mode. Use the more recent `getBoundingRects` over `getInsets`.
Tests will need to be kept separate until Robolectric publishes a version that supports API level 35.
Roboletric tests for this pr will be part of google testing until then. 
Pr for tests here https://critique.corp.google.com/cl/657302386. 
https://github.com/flutter/flutter/issues/146658
=> Use getBoundingRects to add support inset MediaQuery/SafeArea when in freeform mode controls are shown. 

display_list/BUILD.gn, display_list/display_list_unittests.cc, display_list/dl_builder.h, display_list/dl_color.cc, display_list/dl_color.h, display_list/dl_color_unittests.cc, display_list/dl_vertices.cc, display_list/dl_vertices.h, display_list/effects/dl_color_source.cc, display_list/effects/dl_color_source.h, display_list/skia/dl_sk_canvas.cc, display_list/skia/dl_sk_conversions.cc, display_list/skia/dl_sk_conversions.h, display_list/skia/dl_sk_dispatcher.cc, display_list/testing/dl_rendering_unittests.cc, display_list/testing/dl_test_snippets.cc, impeller/display_list/aiks_dl_blend_unittests.cc, impeller/display_list/dl_dispatcher.cc, impeller/display_list/skia_conversions.cc, lib/ui/painting/gradient.cc, testing/display_list_testing.cc
relands https://github.com/flutter/engine/pull/54473
integration test: https://github.com/flutter/engine/pull/54415
This is the engine side changes required for wide gamut framework support.  It changes the internal representation of DlColor to be floats.  It will be married with https://github.com/flutter/engine/pull/54415 when it lands in https://github.com/flutter/engine/pull/54567.
1) The default color is now opaque black, not transparent black (not the issue for revert)
1) Updated a test to send in valid numbers when constructing a color and added asserts to avoid those problems in the future. …
=> Changes DlColor to support wide gamut colors (#54473)

.ci.yaml, ci/builders/linux_fuchsia.json, ci/builders/linux_fuchsia_tests.json
CP of https://github.com/flutter/engine/pull/54591
=> Flutter 3.25 beta split out fuchsia tests to separate shard to avoid timeouts

sky/tools/create_macos_framework.py, sky/tools/sky_utils.py
This refactors `create_fat_macos_framework`, `_regenerate_symlinks` and
`_set_framework_permissions` to be more generic and not hardcode "FlutterMacOS"
as a framework name. Further, it reuses several utility functions from the iOS
code in `sky_utils` to improve readability and eliminate duplication.
This is refactoring prior to embedding dSYMs in FlutterMacOS.xcframework in a
followup patch. …
=> Clean up macOS framework creation scripts

sky/tools/sky_utils.py
By default, zip archives don't just archive the files themselves, but also bundle extra metadata such as unix owner/group and unix timestamps. None of these is particularly important in the case of Flutter: owner/group information is likely to differ across machines and thus be overridden on the unarchiver's end. The tool checks for file presence and occasionally content hashes.
This change results in more reproducible zip archives across runs/machines. …
=> iOS,macOS: Don't archive extra framework metadata

display_list/benchmarking/dl_builder_benchmarks.cc, display_list/display_list.cc, display_list/display_list.h, display_list/display_list_unittests.cc, display_list/dl_builder.h, display_list/dl_op_records.h, testing/display_list_testing.cc, testing/display_list_testing.h
Now also fixes: https://github.com/flutter/flutter/issues/153737
Being able to reorder rendering commands leads to optimization opportunities in the graphics package. A graphics package being fed from a DisplayList either has to take the commands in the order given or implement their own storage format for the rendering data.
With this new dispatching mechanism, the graphics package can both query basic information about the recorded ops and even dispatch them by the index into the list. Query information includes either the "category" of the op (clip/transform/render, etc.) or a specific op type enum. The package can dispatch some categories (or ops) immediately and remember other categories (or ops) along with their state for dispatching later.
=> Reland "[DisplayList] Allow random access to ops through indexing"

docs/Testing-presubmit-Engine-PRs-with-the-Flutter-framework.md
Rather than editing `.ci.yaml` to enable the `linux_web_engine` shard, instead suggest tagging with the `test: all` label, which avoids the risk of accidentally committing an unwanted change to `.ci.yaml` and having to revert the change before landing.
This is also more future-proof against further `runIf` additions to `.ci.yaml`. …
=> docs: use test: all rather than editing .ci.yaml

shell/platform/android/io/flutter/embedding/android/FlutterView.java
@matanlurey:
> As of https://github.com/flutter/engine/commit/d6bc4dc6e59d2d97d0326350c351bff99f845078, we are now printing a `W/FlutterView( 7775): API level 34 is too low to query bounding rects.` message which is not user actionable. Was this intended to stay in the merged PR? What value is it supposed to have?
@yaakovschectman:
> You might be right about that
=> Remove spammy warning message on `FlutterView`

shell/platform/darwin/ios/ios_context_software.mm
We don't have an OpenGL backend on iOS.
=> [iOS] Tweak note about OpenGL support on mac in a user facing log.

ci/builders/linux_android_debug_engine.json, ci/builders/linux_unopt.json
Towards https://github.com/flutter/flutter/issues/145842.
Mostly a note to self: I'll need to write a lint at some point that this does not regress. Possibly part of https://github.com/flutter/engine/blob/main/tools/pkg/engine_build_configs/bin/check.dart, but it will also need to query the ci.yaml to ask whether a build config json is part of a `release_build: "true"` build.
=> Split tests out of Linux Android artifact creation builds

sky/tools/create_ios_framework.py, sky/tools/create_macos_framework.py, sky/tools/sky_utils.py
Separates dSYM creation from archiving, consistent with iOS tooling. This
introduces no semantic changes, but simply adjusts `create_fat_macos_framework`
and `process_framework` for consistency with the equivalent iOS tooling in
`create_ios_framework.py`.
Related issue: https://github.com/flutter/flutter/issues/153879 …
=> macOS: Make framework creation consistent with iOS

examples/glfw/main.dart, examples/glfw/run.sh, shell/platform/embedder/embedder_exports.lst
This PR exports GPU symbols for the embedder library.
https://github.com/flutter/flutter/issues/153196 …
=> Export GPU symbols for embedder

examples/vulkan_glfw/run.sh, examples/vulkan_glfw/src/main.cc
This PR enables printing validation output when the Vulkan validation layer is enabled.  Without this change no messages are printed which provides a false positive for the Vulkan Embedder API health.
https://github.com/flutter/flutter/issues/153663 …
=> vulkan_glfw validation layer logging

sky/tools/create_ios_framework.py, sky/tools/create_macos_framework.py, sky/tools/sky_utils.py
As of Xcode 16, App Store validation requires dSYMs for frameworks in app archives. Bundling dSYMs also significantly simplifies stack trace symbolification, so we should be doing this regardless.
This adds both framework and simulator framework dSYMs to the FlutterMacOS.xcframework bundle.
Issue: https://github.com/flutter/flutter/issues/153879 …
=> macOS: Bundle dSYM packages in FlutterMacOS.xcframework

ci/builders/mac_host_engine.json, ci/builders/mac_ios_engine.json
For https://github.com/flutter/flutter/issues/153925.
This limits these builds to using a little under 60% of mac capacity. If the queue times go up, we can trade intel and arm machines between the prod and try pool.
=> Pin mac host and iOS builds to arm64 builders

lib/web_ui/lib/src/engine/pointer_binding.dart, lib/web_ui/test/engine/pointer_binding_test.dart
Remember the timestamp of _all_ `pointerup` events, not just those that were flushed. Clicks should be deduplicated after a `pointerup` even when not debouncing anything. This is because when not debouncing the engine already forwards all the pointer events to the framework, and sending click events on top only causes double-clicks.
Fixes https://github.com/flutter/flutter/issues/147050
=> [web:semantics] fix double click due to long-press

shell/platform/darwin/macos/framework/Source/FlutterEngineTest.mm
Assert that running the macOS engine does not log anything unexpected 
See also issue https://github.com/flutter/flutter/issues/111577
Similar Windows check in https://github.com/flutter/engine/pull/47774 …
=> Test running the macOS engine has no stray logging

lib/gpu/lib/src/render_pass.dart, lib/ui/lerp.dart, lib/ui/painting.dart, lib/ui/painting/paint.cc, lib/web_ui/lib/painting.dart, testing/dart/color_test.dart
Reverts flutter/engine#54415
Reverting for failures in the engine roll: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8738846858081700577/+/u/run_test.dart_for_customer_testing_shard_and_subshard_None/stdout
=> Revert "Framework wide color"

.ci.yaml
`properties` gets routed to the build properties json that gets handed to the recipe. `dimensions` gets routed to the common_pb2.RequestedDimension buildbucket protobuf field. See:
https://flutter.googlesource.com/recipes/+/refs/heads/main/recipe_modules/shard_util/api.py#368
=> Set cores in 'dimensions' instead of 'properties'

sky/tools/create_ios_framework.py, sky/tools/create_macos_framework.py, sky/tools/create_xcframework.py
While we do produce a simulator slice in our iOS release framework binaries, this is actually an unsupported runtime mode, therefore there is no need to bundle dSYMs for this mode.
This saves roughly 1GB of cached debug info.
Fixes: https://github.com/flutter/flutter/issues/154019
Related issue: https://github.com/flutter/flutter/issues/11754 …
=> iOS: don't bundle simulator dSYMs in xcframework

shell/platform/darwin/macos/framework/Source/FlutterViewController.mm
In https://github.com/flutter/engine/pull/40241, I added a workaround for an AppKit bug wherein mouseDown/Up events were ignored when the *Reduced Transparency* accessibility setting was enabled, and the view was hosted in an `NSPopover`.
I filed a Radar and Apple reported the bug fixed in macOS 13.3.1.
When we drop support for macOS 12 in Flutter, we should remove the workaround.
So long as nothing else has been added to these methods at that time, the method overrides themselves should be removed, so that we fall back to the default behaviour.
See: http://www.openradar.me/FB12050037
See: https://developer.apple.com/documentation/appkit/nsresponder/1535349-mouseup
Issue: https://github.com/flutter/flutter/issues/154063
Issue: https://github.com/flutter/flutter/issues/115015
No tests …
=> [macOS] Add TODOs to remove AppKit bug workaround

lib/ui/painting/canvas.cc, testing/dart/canvas_test.dart
Ensure that int32 ui colors are correctly converted to Dl Colors (convert instead of reinterpret cast).
=> [ui] fix missing color conversion in drawAtlas.

shell/platform/android/io/flutter/embedding/engine/FlutterJNI.java, shell/platform/android/test/io/flutter/embedding/engine/FlutterJNITest.java
Is seems automatic test may send a11y query before the engine is attached. Add a guard to guard against it. …
=> [Android] Drops semantics query when app is not attached

shell/platform/darwin/macos/framework/Source/FlutterEngineTest.mm
This reverts commit 5aed693f87b5a77bc7b3aa7e6e411f12f7deb921.
Revert https://github.com/flutter/engine/pull/54716. This new check is flaking and isn't very high-value.
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8738562907128595441/+/u/test:_Host_Tests_for_host_profile/stdout …
=> Revert "Test running the macOS engine has no stray logging"

lib/web_ui/lib/src/engine/semantics/route.dart, lib/web_ui/test/engine/semantics/semantics_test.dart
Previously the "dialog" ARIA role was only set if the route or any of its descendants had the `namesRoute` flag. This PR sets the ARIA role unconditionally. Although it's always a good idea to have a label on the route, a missing label doesn't change the fact that the route is a route, so the ARIA role should still be set.
Fixes https://github.com/flutter/flutter/issues/153791
=> [web] set the "dialog" ARIA role unconditionally

.ci.yaml
https://github.com/flutter/engine/pull/54747 worked, so I'm going to apply that change to all builders on main, and then we can CP it into the release branches.
For https://github.com/flutter/flutter/issues/152186
=> Ensure orchestrators aren't assigned to 32 core machines

shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm, shell/platform/darwin/ios/framework/Source/FlutterTextInputPluginTest.mm, shell/platform/darwin/ios/framework/Source/SemanticsObjectTest.mm, shell/platform/darwin/ios/framework/Source/TextInputSemanticsObject.mm
Fixes text input edit rotor accessibility missing edit actions.
It also fixes a few edit items that is displayed where it's not supposed to. (e.g. displaying select item while nothing to select).
Fixes https://github.com/flutter/flutter/issues/151029 …
=> [ios] Fix text input edit rotor accessibility

skia/BUILD.gn
Fixes https://issues.skia.org/issues/362267329.  The indirection introduced by this PR insulates Flutter from source-file-list changes in Skia.  See the linked bug for more details.
[CLA]: …
=> Use GNI group instead of hardcoding PNG codecs source files.

ci/builders/mac_host_engine.json, docs/Crashes.md, sky/tools/create_macos_framework.py
As of the following patches, we now bundle FlutterMacOS.framework.dSYM as part of FlutterMacOS.xcframework. The dSYM is automatically copied into the release build products directory, and bundled in the .xcarchive produced by Xcode's *Product > Archive* feature which produces bundles for upload to the App Store.
* https://github.com/flutter/engine/pull/54696
* https://github.com/flutter/flutter/pull/153975
The .dSYM bundle is now available both in the uploaded .xcarchive and in the xcframework in Flutter's internal artifact cache. For developers with CI toolchains that do additional manual handling or local archiving of .dSYMs, the dSYMs no longer need to be downloaded from cloud storage as previously detailed in `docs/Crashes.md`, but can instead be copied up from the appropriate dSYM …
=> macOS: Do not archive/upload FlutterMacOS.dSYM to cloud

shell/platform/darwin/macos/framework/Source/FlutterViewController.mm, shell/platform/darwin/macos/framework/Source/FlutterViewControllerTest.mm
Use default mouse event handling behaviour on macOS 13.3.1 onwards. This has two positive effects:
* Avoids the workaround on newer macOS versions where it's unnecessary, thereby giving us confidence that the underlying AppKit issue is fixed and the whole method can later be removed.
* Will be caught by tooling when we drop support for versions of macOS prior to the fixed version.
Issue: https://github.com/flutter/flutter/issues/154063
Issue: https://github.com/flutter/flutter/issues/115015
No tests modified since there is no semantic change, either on versions of macOS where the issue is fixed (and thus the default event handler is correct) or on versions where it is not (and we still use the workaround).
Re-tested manually with the reduced transparency setting on macOS 14.6.1.
If you …
=> macOS: Add @available check at macOS 12 workaround

shell/platform/linux/fl_accessible_text_field.cc, shell/platform/linux/fl_gnome_settings.cc, shell/platform/linux/fl_renderer.cc, shell/platform/linux/fl_settings_portal.cc, shell/platform/linux/fl_view_accessible.cc
Some code was using stbool true/false - use the gboolean values consistently.
=> Use TRUE/FALSE consistently for gboolean values.

impeller/renderer/backend/vulkan/swapchain/khr/khr_swapchain_impl_vk.cc
The initial timeout of 1 second was chosen to model the Metal backend where the [default drawable timeout is the same](https://developer.apple.com/documentation/quartzcore/cametallayer/2887086-allowsnextdrawabletimeout?language=objc).
=> [Impeller] Use infinite swapchain present timeouts to avoid logspam.

impeller/docs/android_validation_layers.md
I made the mistake of putting it under the activity tag and was surprised it didn't hold.
=> [Impeller] Clarify where to put the metadata in the manifest.

impeller/renderer/backend/vulkan/context_vk.cc
This overrides the documented behavior silently but only in unopt. Make opt and unopt modes behave the same. Disabling validation is frequently necessary to test behavior on simulators or when connecting to Renderdoc.
=> [Impeller] Don't override user specification on Vulkan validation in unopt.

docs/contributing/Compiling-the-engine.md, docs/contributing/Setting-up-the-Engine-development-environment.md, docs/testing/Testing-the-engine.md
Fixes some links that were broken as a part of https://github.com/flutter/engine/pull/53595, because it was pointed out on discord
Specifically, replaces `../../` with `https://github.com/flutter/flutter/blob/master/docs/` in the places that `grep` surfaced it. …
=> Fix broken links in `docs/`

display_list/dl_op_records.h, display_list/testing/dl_test_snippets.cc, impeller/aiks/canvas.h, impeller/display_list/dl_dispatcher.cc
Experimental Canvas was getting depth assertion errors while trying to use the depth values supplied by DisplayList. This was mainly due to a difference in understanding as to how many depth values to allocate to a drawImageNine operation. 
n case there are additional discrepancies, debugging code is added to assert the understanding of how many depth values the experimental canvas uses on each rendering operation. The depth debugging can be turned on and off with a #define
=> Synchronize accounting for render op depths

impeller/core/host_buffer.h, impeller/entity/contents/host_buffer_unittests.cc, impeller/renderer/backend/vulkan/swapchain/ahb/ahb_swapchain_impl_vk.cc
It seems like on some ANdroid devices we can actually get 4 pending frames even with the 3 frame wait. I thought about this a lot but too hard. Lets bump it up one.
Also minor comment fixes in ahb swapchain.
=> [Impeller] Increase host buffer arena count to 4.

third_party/txt/src/skia/paragraph_skia.cc, third_party/txt/tests/paragraph_unittests.cc
For very thin stroked text we switch to skia font rasterization for higher fidelity. However and very large stroke widths, the fidelity loss doesn't matter and may be much slower due to software rasterization.
As several users have noticed, there is a maximum size limit of skia stroked text that we hit as well. This only seems to happen on large stroke widths.
Fixes https://github.com/flutter/flutter/issues/153784
=> [Impeller] fall back to path rendering on thick paths.

.gitignore
After using `testing/run_tests.py`, these artifacts are left in the source tree.
It is probably better _not_ to do that (i.e. use sandboxing), but we don't sandbox across the engine today.
```txt
Untracked files:
(use "git add <file>..." to include in what will be committed)
tools/const_finder/test/fixtures/box_web.dill.deps
tools/const_finder/test/fixtures/consts_and_non_web.dill.deps
tools/const_finder/test/fixtures/consts_web.dill.deps
tools/const_finder/test/fixtures/static_icon_provider_web.dill.deps
```
=> Ignore generated fixture `.dill.deps` files.

testing/run_tests.py, tools/header_guard_check/pubspec.yaml, tools/header_guard_check/test/header_file_test.dart, tools/header_guard_check/test/header_guard_check_test.dart
Work towards https://github.com/flutter/flutter/issues/133569.
I also augmented the `run_tests.py` script to support an incremental migration to `package:test`, PTAL.
=> Migrate`header_guard_check` to `package:test`.

lib/web_ui/lib/src/engine/layers.dart, lib/web_ui/test/ui/scene_builder_test.dart
This is a partial fix for https://github.com/flutter/flutter/issues/152026
We are still blocked on https://g-issues.skia.org/issues/362552959 for things to be completely working.
=> [skwasm] Always do backdrop filter operation even if empty.

lib/gpu/lib/src/render_pass.dart, lib/ui/lerp.dart, lib/ui/painting.dart, lib/ui/painting/paint.cc, lib/web_ui/lib/painting.dart, testing/dart/color_test.dart
[This PR](https://github.com/flutter/engine/pull/54415) was reverted because it requires a manual roll into the framework.
integration test: https://github.com/flutter/engine/pull/54415
This does the preliminary work for implementing wide gamut colors in the Flutter framework. Here are the following changes: 1) colors now specify a colorspace with which they are to be interpreted 1) colors now store their components as floats to accommodate bit depths more than 8
The storage of this Color class is weird with float/int storage but that is a temporary solution to support a smooth transition. Here is the plan for landing this:
1) Land this PR
1) Wait for it to roll into the Framework
1) Land …
=> Reland: Framework wide color (#54415)

lib/gpu/lib/src/render_pass.dart, lib/ui/lerp.dart, lib/ui/painting.dart, lib/ui/painting/paint.cc, lib/web_ui/lib/painting.dart, testing/dart/color_test.dart, testing/dart/geometry_test.dart
[This PR](https://github.com/flutter/engine/pull/54415) was reverted because it required customer testing updates.
integration test: https://github.com/flutter/engine/pull/54415
This does the preliminary work for implementing wide gamut colors in the Flutter framework. Here are the following changes: 1) colors now specify a colorspace with which they are to be interpreted 1) colors now store their components as floats to accommodate bit depths more than 8
The storage of this Color class is weird with float/int storage but that is a temporary solution to support a smooth transition. Here is the plan for landing this: 1) Land this PR
1) Wait for it to roll into the Framework
1) Land https://github.com/flutter/flutter/pull/153938 which …
=> Reland: Framework wide color (#54415) (#54737)

lib/web_ui/lib/painting.dart, lib/web_ui/lib/src/engine/canvaskit/canvas.dart, lib/web_ui/lib/src/engine/canvaskit/canvaskit_api.dart, lib/web_ui/lib/src/engine/canvaskit/color_filter.dart, lib/web_ui/lib/src/engine/canvaskit/image.dart, lib/web_ui/lib/src/engine/canvaskit/image_filter.dart, lib/web_ui/lib/src/engine/canvaskit/layer.dart, lib/web_ui/lib/src/engine/canvaskit/mask_filter.dart, lib/web_ui/lib/src/engine/canvaskit/painting.dart, lib/web_ui/lib/src/engine/canvaskit/text.dart, lib/web_ui/lib/src/engine/html/painting.dart, lib/web_ui/test/canvaskit/filter_test.dart, lib/web_ui/test/canvaskit/painting_test.dart, lib/web_ui/test/ui/paint_test.dart
Do not eagerly create an `SkPaint` object that's strongly referenced by `CkPaint`. Instead, when a `Canvas.draw*` is called, create a temporary `SkPaint` object, pass it to Skia, then immediately delete it. This way there are no persistent `SkPaint` handles lurking in the system that transitively hold onto expensive native resources.
Addresses the `Paint` issue in https://github.com/flutter/flutter/issues/153678 in CanvasKit
Spot checking some benchmarks. Here's the effect of this PR on `draw_rect_variable_paint`. It's a bit of a stress test as it creates 300K distinct `Paint` objects to render 600 pictures (a typical ratio does not normally exceed ten paints to one picture). Even so, the effect of creating an extra `SkPaint` on every `draw*` command does not look significant. However, …
=> [web:canvaskit] switch to temporary SkPaint objects

impeller/renderer/backend/vulkan/driver_info_vk.cc, impeller/renderer/backend/vulkan/driver_info_vk.h, impeller/renderer/backend/vulkan/driver_info_vk_unittests.cc, impeller/renderer/backend/vulkan/test/mock_vulkan.cc, impeller/renderer/backend/vulkan/test/mock_vulkan.h, shell/platform/android/android_context_vk_impeller.cc
Fixes https://github.com/flutter/flutter/issues/154103
From local testing, the Adreno 630 returns VK_INCOMPLETE when compiling certain shaders with no other error messages. That is not a valid return code from vkCreateGraphicsPipeline and likely indicates severe problems with the driver.
=> [Impeller] disable Adreno 630 vulkan and add mechanism for android driver denylisting.

impeller/typographer/backends/skia/typographer_context_skia.cc, impeller/typographer/typographer_unittests.cc
TypographerContextSkia::CreateGlyphAtlas calculates the set of requested glyphs that are not already in the current atlas and then tries to add those glyphs to that atlas.  But if that is not possible and a new atlas must be allocated, then CreateGlyphAtlas must populate the new atlas with every glyph.
Fixes https://github.com/flutter/flutter/issues/153392
=> [Impeller] Add all requested glyphs if TypographerContextSkia needs to create a new atlas

shell/platform/android/android_context_vk_impeller.cc
context can be null here which is causing https://github.com/flutter/flutter/issues/154622
=> [Impeller] fix NPE when checking known bad driver.

impeller/display_list/skia_conversions.cc, lib/ui/painting.dart, lib/ui/painting/gradient.cc, lib/ui/painting/gradient.h
This implements wide gamut color support for gradients in the engine.
integration test: https://github.com/flutter/flutter/pull/153976
[CLA]: …
=> Framework wide color linear gradients

lib/web_ui/lib/src/engine/html_image_element_codec.dart, lib/web_ui/lib/src/engine/safe_browser_api.dart, lib/web_ui/test/canvaskit/image_golden_test.dart
Adds the `crossOrigin` property to the `<img>` tag used for decoding. This allows us to use cross-origin images in CanvasKit as if it were loaded from the same origin, as long as the CORS headers are properly set on the server hosting the image.
In the case where the image doesn't have proper CORS headers, this change causes an error to occur while attempting to decode, rather than later on in Skia when the image is converted into a texture. Hitting the cross-origin error later causes Skia to behave in undefined ways.
Progress towards https://github.com/flutter/flutter/issues/149843  …
=> Add `crossOrigin` property to <img> tag used for decoding

display_list/display_list_unittests.cc
Fixes https://github.com/flutter/flutter/issues/144070
There is a mechanism by which you can access a DisplayListBuilder as if it were a DlOpReceiver for dispatching one DisplayList into another.
This mechanism also resembles the legacy way in which one would write graphics snippets prior to the creation of the DlCanvas interface and so we have dozens of old unit tests which were written to test the Builder class by filling it with commands in the Receiver/Dispatcher format. This type of access is obsolete and maintaining the ability for arbitrary code to talk to a Builder in that manner is getting in the way of future work.
This PR rewrites over 100 of such unit tests to use the standard DlCanvas-style interface to record operations into a Builder, leaving only a dozen or so cases of …
=> [DisplayList] Remove unnecessary DisplayListBuilder as DlOpReceiver accesses

lib/web_ui/lib/src/engine/dom.dart, lib/web_ui/lib/src/engine/platform_dispatcher/view_focus_binding.dart, lib/web_ui/test/engine/platform_dispatcher/view_focus_binding_test.dart
In [some cases][1], text editing utilities re-focus the `<input />` element during a blur event. This causes an unusual sequence of `focusin` and `focusout` events, leading to the engine sending unintended events.
Consider the following HTML code:
```html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title></title>
</head>
<body>
<div id="container">
<input type="" value="1" id="input1">
<input type="" value="2" id="input2">
<input type="" value="3" id="input3">
</div>
<script>
container.addEventListener('focusin', (ev) => {
console.log('focusin: focus was gained by', ev.target);
});
container.addEventListener('focusout', (ev) => {
console.log('focusout: focus is leaving', ev.target, 'and it will go to', ev.relatedTarget);
});
</script>
</body>
</html>
```
Clicking …
=> Fix unexpected ViewFocus events when Text Editing utilities change focus in the middle of a blur call.

shell/common/shell.cc
If we use runNowOrPostTask on platform channel responses, then we may not wake up the dart message loop. If nothing else wakes it up, then the embedder may hang on platform channel responses.
This fixes several google3 integration tests when run in merged thread mode.
=> [engine] always force platform channel responses to schedule a task.

lib/web_ui/lib/src/engine/canvaskit/layer.dart, lib/web_ui/test/ui/scene_builder_test.dart
Fixes calculation of `ImageFilter` bounds by taking into account the offset.
Fixes https://github.com/flutter/flutter/issues/154303 …
=> [canvaskit] Fix incorrect calculation of ImageFilter paint bounds

DEPS, ci/licenses_golden/excluded_files, ci/licenses_golden/licenses_skia, skia/BUILD.gn
Includes a build script update required for a new source file added on Windows
=> Manual Skia roll to 809f868ded1c

sky/tools/create_ios_framework.py, sky/tools/create_macos_framework.py, sky/tools/sky_utils.py
There are three categories of binaries produced as part of the framework artifacts:
* Those that use APIs that require entitlements and must be code-signed; e.g. gen_snapshot
* Those that do not use APIs that require entitlements and must be code-signed; e.g. Flutter.framework dylib.
* Those that do not need to be code-signed; e.g. Flutter.dSYM symbols.
Until now, our signing infrastructure has assumed that all mach-o binaries in the artifacts we produce require a signature. dSYM files are not required to be codesigned, although the xcframework containing them are, and as such they cannot be removed or tampered with.
The framework code-signing tests in `dev/bots/suite_runners/run_verify_binaries_codesigned_tests.dart` are only run on post-submit on release branches, and thus, this issue …
=> iOS,macOS: add unsigned_binaries.txt

sky/tools/sky_utils.py
When duplicates are found in the input lists, log them to stderr. For the case of duplicates across list, we print the whole list, sorted, rather than three separate lists, as it makes it simpler to spot the duplicate, at which point the file will be easy to spot in either `create_ios_framework.py` or `create_macos_framework.py`. …
=> iOS,macOS: Add logging of duplicate codesign binaries

lib/ui/painting.dart, lib/web_ui/lib/painting.dart
This depends on https://github.com/flutter/flutter/pull/153938 being landed. …
=> Removes the int storage from Color

docs/impeller/Flutter-GPU.md
Changed the word "there" to "their" in Flutter GPU doc... which I think is correct, but I could be wrong. Thanks!
- [] I listed at least one issue that this PR fixes in the description above.
- [] I added new tests to check the change I am making or feature I am adding, or the PR is [test-exempt]. See [testing the engine] for instructions on writing and running engine tests.
[C++, …
=> Change "there own" to "their own" in Flutter-GPU docs

display_list/image/dl_image.h, impeller/display_list/dl_image_impeller.cc, impeller/display_list/dl_image_impeller.h, lib/ui/painting/image.cc, lib/ui/painting/image_encoding.cc, lib/ui/painting/picture.cc, shell/common/snapshot_controller_impeller.cc, shell/platform/darwin/ios/rendering_api_selection.mm
Simulator only change to allow toImage and toByteData to not fail when there is no metal context w/ impeller.
=> [impeller] fake image for fake tests.

lib/web_ui/lib/src/engine/skwasm/skwasm_impl/canvas.dart, lib/web_ui/lib/src/engine/skwasm/skwasm_impl/paint.dart, lib/web_ui/lib/src/engine/skwasm/skwasm_impl/paragraph.dart, lib/web_ui/lib/src/engine/skwasm/skwasm_impl/raw/raw_paint.dart, lib/web_ui/skwasm/paint.cpp
Same as https://github.com/flutter/engine/pull/54818, but for Skwasm.
Addresses the `Paint` issue in https://github.com/flutter/flutter/issues/153678 in Skwasm
=> [skwasm] use temporary RawPaint objects

lib/web_ui/lib/src/engine/canvaskit/color_filter.dart, lib/web_ui/lib/src/engine/canvaskit/embedded_views.dart, lib/web_ui/lib/src/engine/html/bitmap_canvas.dart, lib/web_ui/lib/src/engine/html/shaders/shader.dart, lib/web_ui/lib/src/engine/text/paragraph.dart, lib/web_ui/lib/src/engine/text_editing/text_capitalization.dart
The Dart analyzer will soon be changed so that if the `default` clause of a `switch` statement is determined to be unreachable by the exhaustiveness checker, a new warning of type
`unreachable_switch_default` will be issued. This parallels the behavior of the existing `unreachable_switch_case` warning, which is issued whenever a `case` clause of a `switch` statement is determined to be unreachable.
Before adding the new warning to the analyzer, code in the engine needs to first be updated to eliminate these unreachable `default` clauses, so that the warning won't cause builds to break.
For more information, see
https://github.com/dart-lang/sdk/issues/54575. …
=> [multiple] Avoid new `unreachable_switch_default` warning.

shell/common/engine.cc, shell/common/engine_unittests.cc, shell/common/shell.cc, shell/platform/darwin/ios/framework/Source/FlutterEngine.mm, shell/platform/darwin/ios/framework/Source/FlutterEngineTest.mm
Reland of https://github.com/flutter/engine/pull/54975
Fixes the initial route behavior for iOS. Previously the initial route setting would _always_ be posted as a task, which after merging the threads would fire after isolate creation, thus it would not actually update the initial route setting. Fixed Engine constructor so that it reads the initial route from the settings.
=> [engine] reland: always post tasks for platform channel responses.

common/config.gni
Speculative revert for current devicelab failures.
=> [Impeller] Disable exp canvas.

runtime/runtime_controller.cc, runtime/runtime_controller.h, shell/common/engine_unittests.cc, shell/common/shell.cc, shell/common/shell_unittests.cc
This is a re-land of https://github.com/flutter/engine/pull/55006, except that we special case the navigation channel to immediately dispatch its message if the isolate is not yet running.
This preserves the existing behavior relied upon by several iOS add2app tests, as well as the still used embedder v1 - and potentially undicovered future embedders.
=> [engine] dispatch platform channel messages through event loop, except navigation on start.

lib/web_ui/lib/src/engine/html_image_element_codec.dart, lib/web_ui/lib/src/engine/safe_browser_api.dart, lib/web_ui/test/canvaskit/image_golden_test.dart
This reverts commit 4844cb489b3fa599cad5b0e499fb709ac490f5ed.
Reason for revert: We broke users (including a Google internal customer) that depend on credentialed image requests. See https://github.com/flutter/flutter/issues/154809
Fixes https://github.com/flutter/flutter/issues/154809
=> Revert "Add `crossOrigin` property to <img> tag used for decoding (#54961)"

shell/gpu/gpu_surface_gl_impeller.cc, shell/gpu/gpu_surface_metal_impeller.mm, shell/gpu/gpu_surface_metal_impeller_unittests.mm, shell/gpu/gpu_surface_vulkan_impeller.cc
Fixes https://github.com/flutter/flutter/issues/154549
Each overlay surface gets its own content context and each cc gets its own transient buffer. So not reseting the overlay surfaces causes a memory leak. The overlay surfaces would just continue to allocate into the same buffer which would allocate endlessly
=> [Impeller] fix obvious memory leak.

lib/web_ui/lib/src/engine/skwasm/skwasm_impl/canvas.dart, lib/web_ui/lib/src/engine/skwasm/skwasm_impl/filters.dart, lib/web_ui/lib/src/engine/skwasm/skwasm_impl/paint.dart, lib/web_ui/lib/src/engine/skwasm/skwasm_impl/paragraph.dart, lib/web_ui/lib/src/engine/skwasm/skwasm_impl/raw/raw_paint.dart, lib/web_ui/skwasm/paint.cpp
Relands https://github.com/flutter/engine/pull/54917. The change is the same as before, except now the native resources for `SkwasmColorFilter` and `SkwasmImageFilter` classes are no longer GC'd. Instead, we use manually managed native handles (vended and scoped by `withRawColorFilter` and `withRawImageFilter`). The bug in the previous PR was that filter objects were disposed with the paint while the framework continued holding onto them. When GC kicked the finalization registry, it attempted to double-free the filters.
=> [skwasm] use temporary RawPaint objects (attempt #2)

lib/web_ui/lib/src/engine/layers.dart, lib/web_ui/lib/src/engine/scene_builder.dart, lib/web_ui/test/engine/scene_builder_test.dart, lib/web_ui/test/engine/scene_builder_utils.dart
Cherry-pick of https://github.com/flutter/engine/pull/54061
=> [CP] [skwasm] Fix platform view occlusion logic.

DEPS
- Report the exit code for failed build-time executions.
Bug: https://github.com/dart-lang/sdk/issues/56529
=> Roll buildroot to f85c3be4bf808add6ba867b8ff7943fd235b7b5e.

ci/licenses.sh
`dart -enable-asserts` should be `--enable-asserts` with two `-`s.
License script is complaining:
```
Could not find an option with short name "-e".
```
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8737159074465654417/+/u/test:_licenses_check/stdout
Typo from:
https://github.com/flutter/engine/pull/54845/files#diff-0845c01add635bd6976b8aefd761c14899002c53f9d0ff596cc7f4667cd49f71R84
Fixes https://github.com/flutter/flutter/issues/154942 …
=> Fix 'dart --enable-asserts' typo in license check script

testing/benchmark/pubspec.yaml, testing/benchmark/test/parse_and_send_test.dart, testing/run_tests.py, tools/api_check/pubspec.yaml, tools/api_check/test/apicheck_test.dart
Partial work towards https://github.com/flutter/flutter/issues/133569.
=> Move more of the tests in the engine to `package:test`

DEPS, pubspec.yaml
package:web now uses mono_repo and now the path is in web/web instead of just web. In order to change the version of package:web used in the Dart SDK and google3, Flutter needs to be updated first.
=> Update package:web to use new path and latest revision

flutter_frontend_server/pubspec.yaml, flutter_frontend_server/test/to_string_test.dart, testing/run_tests.py
Work towards https://github.com/flutter/flutter/issues/133569.
After another PR, `run_tests.py` `extra_args` can be deleted entirely.
=> Move `flutter_frontend_server` and tweak `run_tests.py` to allow env variables.

impeller/entity/contents/filters/gaussian_blur_filter_contents.cc
https://github.com/flutter/flutter/issues/154564
=> [CP][Impeller] Use multiple command buffers to submit blur encode.

shell/gpu/gpu_surface_metal_impeller.mm, shell/gpu/gpu_surface_metal_impeller_unittests.mm
Always resets host buffer, since each overlay context has its own host buffer
=> [CP] fix memory leak in host buffer reset.

testing/scenario_app/bin/run_ios_tests.dart, testing/scenario_app/ios/Scenarios/ScenariosUITests/SpawnEngineTest.m
The `FLUTTER_ENGINE` has a `/` in it: `ci/ios_debug_unopt_sim`.  
```
path.join(storePath, '$iosEngineVariant.zip');
```
was resolving to `path_to_output/ci/ios_debug_unopt_sim.zip`.  `path_to_output` existed, but the `ci` directory didn't:
> zip error: Could not create output file (/Volumes/Work/s/w/ir/x/w/rc/flutter_logs_dir/ci/ios_debug_unopt_sim.zip)
Change the output zip path to `path_to_output/ci_ios_debug_unopt_sim.zip` with an underscore instead.
Fixes https://github.com/flutter/flutter/issues/154956
[test-exempt]: …
=> Zip and upload Xcode xcresults on scenario test failure

DEPS, shell/platform/android/BUILD.gn, shell/platform/android/build.gradle, shell/platform/android/io/flutter/embedding/engine/FlutterJNI.java, shell/platform/android/io/flutter/embedding/engine/loader/FlutterLoader.java, shell/platform/android/test/io/flutter/embedding/engine/loader/FlutterLoaderTest.java, tools/androidx/README.md, tools/androidx/files.json
Could fix? https://github.com/flutter/flutter/issues/83596
The communication on https://issuetracker.google.com/issues/346717090#comment2 recommends using [ReLinker](https://github.com/KeepSafe/ReLinker) to avoid a bug in how library loading interacts with the [Play delivery feature](https://developer.android.com/guide/playcore/feature-delivery) (used in turn by Flutter's deferred components).
The ReLinker docs also suggest that if you have `minSdk` less than `23`, then you should be using ReLinker regardless, as `System.loadLibrary` is unreliable for other reasons.
I don't have any strong evidence to suggest that either one of these two root causes is the definitive cause of https://github.com/flutter/flutter/issues/83596, but it probably wouldn't hurt 🤷 
If you need help, consider …
=> Replace `System.loadLibrary` with `ReLinker.loadLibrary()` in `FlutterJNI.loadLibrary()`

shell/platform/linux/fl_engine.cc, shell/platform/linux/fl_engine_private.h, shell/platform/linux/fl_engine_test.cc, shell/platform/linux/fl_view.cc
With multiple FlViews a callback doesn't scale.
=> Use a signal for the pre-engine restart event

shell/platform/linux/fl_platform_handler.cc
Detected as the FlPlatformHandlerTest.ExitApplicationDispose was crashing sometimes, valgrind showed invalid memory access.
=> Fix crash quitting application due to iterating over a changing list.

lib/web_ui/flutter_js/src/entrypoint_loader.js
This removes usages of the deprecated top-level `instantiate` and `invoke` methods and replaces it by method calls to the embedder objects.
See [0] for the change that introduce this embedder API.
[0] https://dart-review.googlesource.com/c/sdk/+/383242/6
=> [dart2wasm] Move web wasm embedder to new dart2wasm embedder API

shell/platform/embedder/embedder.cc, shell/platform/embedder/tests/embedder_test_backingstore_producer.cc
Skia is changing how it handles its internal copy of Vulkan headers to prevent them from accidentally leaking to users and potentially overriding the user's Vulkan headers. Users of Skia are responsible for providing the Vulkan headers when including Skia's public Vk headers. This change only includes Skia's public Vk headers when Flutter is providing the Vulkan headers.
=> Ensure Vulkan when including Skia Vulkan headers

testing/run_tests.py, tools/const_finder/pubspec.yaml, tools/const_finder/test/const_finder_test.dart
... instead of some home-grown framework.
This is the last test in the engine that uses custom command line arguments to start. As of this PR, `dart test` including full debugging in an IDE works across all Dart tooling code.
I tried to make this idiomatic as much as possible without changing the logic.
=> Migrate `const_finder_test` to use `package:test`

flutter_frontend_server/test/to_string_test.dart, lib/ui/lerp.dart, lib/ui/painting.dart, lib/web_ui/lib/lerp.dart, lib/web_ui/lib/painting.dart, lib/web_ui/test/ui/color_test.dart, lib/web_ui/test/ui/filters_test.dart, lib/web_ui/test/ui/paint_test.dart, lib/web_ui/test/ui/text_style_test.dart, testing/dart/color_test.dart, testing/dart/image_filter_test.dart, testing/dart/text_test.dart
This transforms the rest of Color to use the floating point parameters.  This will likely break existing tests very subtly.  For example, colors will be slightly different in golden tests if `lerp` was ever used.
[testing the …
=> Update Color to do all calculations with floating point components

skia/BUILD.gn
Skia has its own set of Vulkan headers which Skia Vulkan sources expect to be compiled against. This internal set of Vulkan headers should not be seen by any users. Instead, users provide their own set of Vulkan headers and Skia's public Vk headers will use the user's Vulkan headers when included in user sources. Unfortunately, this has not been well enforced and Skia is making changes to ensure that Skia's set of Vulkan headers does not leak. This change updates Flutter's build of Skia to be compatible with these Skia changes.
Skia-Change: https://skia-review.googlesource.com/c/skia/+/898139
=> Update Skia build for Vulkan headers

tools/cipd/android_embedding_bundle/README.md
Adds a note that Gradle lockfile generation is necessary when updating the android embedding dependencies bundle. …
=> Add a note about re generating Gradle lockfiles

shell/platform/fuchsia/dart-pkg/zircon/BUILD.gn, shell/platform/fuchsia/dart-pkg/zircon/test/zircon_tests.dart, shell/platform/fuchsia/dart/BUILD.gn
The engine has historically used `package:litetest`, a home grown invention that is a wrapper around the Dart SDK.
In https://github.com/flutter/flutter/issues/133569, we've moved over to the heavier weight `package:test`, which has been simplified since first evaluated by the Dart SDK vending the dependencies we need. The last user of `package:litetest` is a single test in the Fuchsia SDK, `zircon_tests`.
This PR migrates the test from `litetest` (which will be deleted) to the Dart SK vendored `async_minittest`. For this simple test case, there is only a 1-line behavioral change (`notEquals(foo)` becomes `!= foo, true`), and it allows us to remove dependencies from the tree.
=> Move `zircon_tests` from `package:litetest` to `package:async_helper`.

shell/platform/linux/fl_engine.cc, shell/platform/linux/fl_engine_test.cc
We're seeing issues with and "und" (undefined) locale and exceptions in applications (see https://github.com/ubuntu/app-center/issues/1659). It seems the GLib method for getting the language names doesn't clean up invalid values, so we should do that.
=> Filter out bad locales returned by g_get_language_names

lib/ui/painting.dart, testing/dart/canvas_test.dart, testing/dart/channel_buffers_test.dart, testing/dart/compositing_test.dart, testing/dart/fragment_shader_test.dart, testing/dart/geometry_test.dart, testing/dart/gradient_test.dart, testing/dart/image_dispose_test.dart, testing/dart/image_resize_test.dart, testing/dart/painting_test.dart, testing/dart/paragraph_test.dart
Closes https://github.com/flutter/flutter/issues/155054, where we decided this was correct to do.
As a bonus I improved an `assert` message :)
=> Remove `assert(() {... })` and other unnecessary patterns in `dart:ui` tests

common/settings.h, impeller/renderer/backend/vulkan/context_vk.cc, impeller/renderer/backend/vulkan/context_vk.h, impeller/renderer/backend/vulkan/swapchain/swapchain_vk.cc, shell/common/switches.cc, shell/common/switches.h, shell/platform/android/android_context_vk_impeller.cc, shell/platform/android/android_context_vk_impeller.h, shell/platform/android/context/android_context.h, shell/platform/android/flutter_main.cc, shell/platform/android/io/flutter/embedding/engine/loader/FlutterLoader.java, shell/platform/android/platform_view_android.cc, shell/platform/android/test/io/flutter/embedding/engine/loader/FlutterLoaderTest.java
I've found a few instances where Vulkan worked correctly but surface control did not. lets add a debugging flag we can ask folks to try to narrow down the issue.
=> [impeller] add Android flag for disabling surface control for debugging.

shell/platform/darwin/macos/BUILD.gn, shell/platform/darwin/macos/framework/PrivacyInfo.xcprivacy
Create a `PrivacyInfo.xcprivacy` (this name is required) plist and move it to the top-level of the macOS framework bundle.  `NSPrivacyTracking*` and `NSPrivacyCollectedDataTypes` keys are required, but the values are blank.  macOS explicitly does not need the `NSPrivacyAccessedAPITypes` (see more info in https://github.com/flutter/flutter/issues/143381)
You can see on this PR it's copied to the correct path in the framework https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8737163270670636097/+/u/Global_generators/Release-FlutterMacOS.framework/stdout:
```
adding: FlutterMacOS.xcframework/macos-arm64_x86_64/FlutterMacOS.framework/PrivacyInfo.xcprivacy (deflated 35%)
```
There's no way to test this except to submit a macOS app with this framework to TestFlight.
I can't find …
=> Add xcprivacy privacy manifest to macOS framework

.gitignore
https://github.com/flutter/engine/pull/53974 stopped ignoring the .vscode directory, this created a situation where people's vscode settings are prone to getting checked in or nuked.  I added a specific exception for the one file we did check in. …
=> Added .vscode back to being ignored

ci/licenses_golden/excluded_files, shell/platform/embedder/embedder.cc
Today, only a generic "internal inconsistency" error returned. But custom builds that selectively disable rendering backends may find this error to be too vague.
=> [Embedder] Warn when embedders try to enable an unsupported renderer.

shell/platform/android/test/io/flutter/embedding/android/FlutterViewTest.java
- **Add light and dark test back to FlutterView.java**
- **Migrate some but not all usages of Robolectric.setupActivity in FlutterViewTest.java**
- **Remove suppress warnings on tests that no longer need it, update documentation for ones that still need the suppression**
Fixes https://github.com/flutter/flutter/issues/154746 
Partial work on https://github.com/flutter/flutter/issues/133151
=> FlutterViewTest add back part 4 and 5

lib/ui/fixtures/shaders/BUILD.gn, testing/dart/gpu_test.dart
Resolves https://github.com/flutter/flutter/issues/144640.
New golden:
=> [Flutter GPU] Add golden test for rendering a triangle.

lib/gpu/context.cc, lib/gpu/context.h, lib/gpu/device_buffer.cc, lib/gpu/device_buffer.h, lib/gpu/lib/src/buffer.dart, lib/gpu/lib/src/context.dart, testing/dart/gpu_test.dart
Part of https://github.com/flutter/flutter/issues/150953.
Provide a way to get the required minimum uniform byte alignment when referencing uniform blocks in a device buffer. Allow the user to explicitly flush DeviceBuffers (necessary for devices without shared memory).
=> [Flutter GPU] Add DeviceBuffer.flush & GpuContext.getMinimumUniformByteAlignment.

docs/impeller/Impeller-Scene.md
Remove instructions for setting up Impeller Scene, and link to the continued Dart package.
=> Update the Impeller Scene doc

shell/platform/darwin/ios/framework/Source/FlutterViewController.mm, shell/platform/darwin/ios/framework/Source/FlutterViewControllerTest.mm
Previously, gesture origin position relied on hover events. But iOS 18 screen mirroring feature sends only pan/scale gestures, but doesn't hover. So we need to check the gesture location every time.
Fixes https://github.com/flutter/flutter/issues/153897
=> [ios] Update gesture position on every event

flutter_frontend_server/test/to_string_test.dart, lib/ui/lerp.dart, lib/ui/painting.dart, lib/web_ui/lib/lerp.dart, lib/web_ui/lib/painting.dart, lib/web_ui/test/ui/color_test.dart, lib/web_ui/test/ui/filters_test.dart, lib/web_ui/test/ui/paint_test.dart, lib/web_ui/test/ui/text_style_test.dart, testing/dart/color_test.dart, testing/dart/image_filter_test.dart, testing/dart/text_test.dart
Reason for revert: Broke customer tests
Reland depends on https://github.com/flutter/flutter/issues/155113
This transforms the rest of Color to use the floating point parameters.  This will likely break existing tests very subtly.  For example, colors will be slightly different in golden tests if `lerp` was ever used. …
=> Reland: Update Color to do all calculations with floating point components

docs/contributing/Compiling-the-engine.md
Behavior of `gclient config --custom-var` got changed, modifying the instruction to edit the raw `.gclient` file to avoid unexpected gclient behavior.
Rich diff: https://github.com/flutter/engine/pull/55365/files?short_path=355a854#diff-355a854159c6f6da4e4e296d0cceb1e7e32ef26af1598aa6cdfaafbdbc656b57
Or rendered md: https://github.com/flutter/engine/blob/b375b805f9bbf478c1618dd0d03a02a11d4e65ab/docs/contributing/Compiling-the-engine.md#compiling-for-fuchsia
Bug: http://b/368770157 …
=> [fuchsia] Update fuchsia instruction in Compiling-the-engine.md

impeller/entity/contents/clip_contents.cc, impeller/entity/contents/filters/blend_filter_contents.cc, impeller/entity/contents/filters/border_mask_blur_filter_contents.cc, impeller/entity/contents/filters/color_matrix_filter_contents.cc, impeller/entity/contents/filters/gaussian_blur_filter_contents.cc, impeller/entity/contents/filters/linear_to_srgb_filter_contents.cc, impeller/entity/contents/filters/morphology_filter_contents.cc, impeller/entity/contents/filters/srgb_to_linear_filter_contents.cc, impeller/entity/contents/filters/yuv_to_rgb_filter_contents.cc, impeller/entity/contents/framebuffer_blend_contents.cc, impeller/entity/contents/solid_rrect_blur_contents.cc, impeller/entity/contents/texture_contents.cc, impeller/renderer/vertex_buffer_builder.h
The VertexBufferBuilder (VBB) always does a heap allocation of its vertices before copying them into the host buffer. This is unecessary when uploading a fixed set of vertices, like many filters do. Instead create a helper function that uploads from a  std::array. In most cases this is the same or less code.
We could go template madness to emplace directly but that doesnt seem necessary.
=> [Impeller] remove usage of VBB when allocating vertices of a fixed size.

impeller/core/allocator_unittests.cc, impeller/core/range.h, impeller/renderer/backend/gles/device_buffer_gles.cc, impeller/renderer/backend/gles/device_buffer_gles.h, impeller/renderer/backend/gles/proc_table_gles.h
Measures as substantially faster on windows. See the bufferSubData docs:
> When replacing the entire data store, consider using glBufferSubData rather than completely recreating the data store with glBufferData. This avoids the cost of reallocating the data store.
Tracks invalidated ranges and only updates those ranges using the Flush API.
Fixes https://github.com/flutter/flutter/issues/104447
=> [Impeller] use BufferSubData to update gles device buffer.

engine.code-workspace, testing/scenario_app/android/app/build.gradle, tools/vscode_workspace/README.md, tools/vscode_workspace/engine-workspace.yaml, tools/vscode_workspace/merge.sh, tools/vscode_workspace/refresh.sh
In https://github.com/flutter/engine/pull/55291 we added a vscode workspace to help with running tests and sharing settings.  However, VSCode does not support a config format that has the ability to reduce redundancy and it will get quite unwieldy as we add in all of the engines test runners.  To combat that I've added instead a YAML config that can converted to JSON for VSCode.
This also adds 2 more test runners: display_list_unittests and impeller_golden_tests
[Flutter Style …
=> Made YAML version of vscode workspace to avoid redundancy

shell/platform/darwin/graphics/FlutterDarwinExternalTextureMetal.h, shell/platform/darwin/graphics/FlutterDarwinExternalTextureMetal.mm, shell/platform/darwin/macos/framework/Source/FlutterEmbedderExternalTextureTest.mm, shell/platform/embedder/embedder_external_texture_gl.cc, shell/platform/embedder/embedder_external_texture_gl.h, shell/platform/embedder/embedder_external_texture_metal.h, shell/platform/embedder/embedder_external_texture_metal.mm
Fixes https://github.com/flutter/flutter/issues/135898
Note that the macOS embedder is still using the apple texture cache object from the SkiaMetalContext. it can't initialize an equivalent ImpellerMetalContext without creating a second copy of the content context and all that jazz, so I'm leaving that as is for now.
=> [Impeller] finish wiring up external textures for macOS embedder.

lib/gpu/lib/src/render_pass.dart, lib/gpu/render_pass.cc, lib/gpu/render_pass.h, testing/dart/gpu_test.dart
Resolves https://github.com/flutter/flutter/issues/142731.
We're missing the pipeline stencil state as well. Will add in a follow-up.
=> [Flutter GPU] Add setStencilReference to RenderPass.

.ci.yaml, ci/builders/linux_android_emulator_34.json, ci/builders/linux_android_emulator_opengles_34.json, impeller/aiks/canvas.cc
Fixes https://github.com/flutter/flutter/issues/141636 by ensuring that oes textures create a tiled texture contents. This needs a real test though. probably an intergration test with camera.
=> [Impeller] fix OES texture usage.

impeller/renderer/backend/gles/blit_command_gles.cc
The trace event in the blit pass is firing potentially hundreds of times per frame when we incremental update the glyph atlas. This takes significantly more time than the blit itself.
=> [Impeller] delete expensive trace event.

lib/gpu/lib/src/render_pass.dart, lib/gpu/render_pass.cc, lib/gpu/render_pass.h, testing/dart/gpu_test.dart
Also adds a golden that depends on https://github.com/flutter/engine/pull/55270.
Resolves https://github.com/flutter/flutter/issues/142731.
Allow setting the stencil compare function, pass/fail operations, and read/write masks.
Flutter GPU has light "shader object" style programs, so all of the stencil configuration state can be set on the `RenderPass` at any time.
New simple golden that exercises stencil ops:
=> [Flutter GPU] Add pipeline stencil config.

impeller/renderer/backend/vulkan/context_vk.cc, impeller/renderer/backend/vulkan/context_vk.h, impeller/renderer/backend/vulkan/context_vk_unittests.cc, impeller/renderer/backend/vulkan/surface_context_vk.cc, impeller/renderer/backend/vulkan/surface_context_vk.h, impeller/renderer/context.h, lib/ui/painting/image_decoder_impeller.cc, lib/ui/painting/image_encoding_impeller.cc
In the Vulkan backend, the CommandPoolRecyclerVK stores command pools that can be reused while rendering a frame.  For each frame, SurfaceContextVK::AcquireNextSurface calls CommandPoolRecyclerVK::Dispose to clear the cached pools.
However, the CommandPoolRecyclerVK's cache of pools is placed in thread-local storage.  So command pools used on the IO thread will not be cleaned up if frame rendering calls Dispose on the raster thread.
This PR adds a Context API that the IO thread can call after using a command pool in order to ensure that cached resources are disposed.
Fixes https://github.com/flutter/flutter/issues/155519
=> [Impeller] Delete command pools held by the CommandPoolRecyclerVK after decoding an image on the IO thread

fml/macros.h, lib/ui/fixtures/ui_test.dart, lib/ui/window/platform_configuration.cc, lib/ui/window/platform_configuration.h, lib/ui/window/platform_configuration_unittests.cc, shell/platform/android/vsync_waiter_android.cc
Address bad developer experience in https://github.com/flutter/flutter/issues/106277
Leave as an error log and hope for more repro reports
```mermaid
sequenceDiagram
Animator ->> Animator: AwaitVSync
Animator ->> VsyncWaiter: AsyncWaitForVsync(callback)
VsyncWaiter -> VsyncWaiterAndroid: AwaitVSync
note over VsyncWaiterAndroid: GetUITaskRunner
VsyncWaiterAndroid -> Choreographer: PostFrameCallback
Choreographer -> NDK: AChoreographer_postFrameCallback64
note over Choreographer,NDK: The time that the frame is being<br/>rendered as nanoseconds in the <br/>CLOCK_MONOTONIC time base
NDK --> Choreographer: callback(nanos)
Choreographer -> VsyncWaiterAndroid: callback
note over VsyncWaiterAndroid: // Rollback suspicion<br/>if (frame_time > now) frame_time = now;
VsyncWaiterAndroid -> …
```
=> Disallow time traveling frame times

shell/platform/embedder/embedder.cc, shell/platform/windows/compositor_opengl.cc, shell/platform/windows/compositor_opengl.h, shell/platform/windows/compositor_opengl_unittests.cc, shell/platform/windows/egl/manager.cc, shell/platform/windows/egl/manager.h, shell/platform/windows/flutter_windows_engine.cc, shell/platform/windows/flutter_windows_unittests.cc, shell/platform/windows/testing/egl/mock_manager.h
Fixes https://github.com/flutter/flutter/issues/141482
Since the introduction of the flutter compositor, the windows embedder will create an offscreen framebuffer and then blit this to the onscreen framebuffer. Therefore, the onscreen framebuffer should not be constructed as a multisample framebuffer - and the EGL config can match skia.
Also cleans up selection of the impeller PixelFormat, which might not have matched the selected compositor format because it was hardcoded to RGBA_8888
=> [Impeller] fix Impeller on windows.

lib/gpu/formats.h, lib/gpu/lib/src/formats.dart, lib/gpu/lib/src/render_pass.dart, lib/gpu/render_pass.cc, lib/gpu/render_pass.h, testing/dart/gpu_test.dart
Part of https://github.com/flutter/flutter/issues/155636.
New golden `flutter_gpu_test_cull_mode` will draw a red triangle if the CullMode isn't working:
=> [Flutter GPU] Add CullMode.

engine.code-workspace, tools/vscode_workspace/engine-workspace.yaml
- host_debug_unopt_arm64
- android_debug_unopt_arm64
- ios_debug_unopt_arm64 (missed in previous change)
[breaking …
=> adds more tasks to the engine workspace

lib/gpu/lib/gpu.dart, lib/gpu/lib/src/render_pass.dart, lib/gpu/pubspec.yaml, lib/gpu/render_pass.cc, lib/gpu/render_pass.h, testing/dart/gpu_test.dart
Resolves https://github.com/flutter/flutter/issues/155627.
Allow setting the clear directly as floats without conversion work. vector_math already has convenient `Colors.[color]` factories and such. Also, `ui.Color` has a color space now, which does not apply here.
Adds a simple golden to verify that clear colors work:
=> [Flutter GPU] Use vm.Vector4 for clear color instead of ui.Color.

shell/platform/android/io/flutter/embedding/engine/renderer/FlutterRenderer.java, shell/platform/android/io/flutter/embedding/engine/renderer/SurfaceTextureSurfaceProducer.java, shell/platform/android/io/flutter/view/TextureRegistry.java, shell/platform/android/test/io/flutter/embedding/engine/renderer/FlutterRendererTest.java, shell/platform/android/test/io/flutter/plugin/platform/PlatformViewsControllerTest.java
Closes https://github.com/flutter/flutter/issues/144407.
Closes https://github.com/flutter/flutter/issues/155633.
=> Add a boolean that exposes rotation/crop metadata capability.

shell/platform/android/io/flutter/embedding/android/FlutterView.java, tools/android_lint/baseline.xml
I think you just had the lint identifier wrong?
Closes https://github.com/flutter/flutter/issues/155712.
=> Move lint suppression from `baseline.xml` to `@SuppressLint`.

tools/cipd/mobileprovision/.gitignore, tools/cipd/mobileprovision/README.md, tools/cipd/mobileprovision/mac-amd64.yaml, tools/cipd/mobileprovision/mac-arm64.yaml
Adds instructions for creating updated CIPD packages containing a new provisioning profile that goes with an updated signing certificate, for use on Chromium CI bots.
These are part of a broader set of steps required to renew our development signing certificate annually, as described in [cl/678826297](http://cl/678826297) (Google-internal).
Issue: https://github.com/flutter/flutter/issues/152888
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-r …
=> cipd: add mobileprovision CIPD package

build/dart/internal/application_snapshot.gni, build/dart/rules.gni, sky/packages/sky_engine/BUILD.gn
Removes imports unused after https://github.com/flutter/engine/pull/55404, inlines a constant unused elsewhere.
=> Remove and inline dependencies on `build_root` for a constant.

lib/web_ui/lib/src/engine.dart, lib/web_ui/lib/src/engine/canvaskit/embedded_views.dart, lib/web_ui/lib/src/engine/canvaskit/layer.dart, lib/web_ui/lib/src/engine/canvaskit/layer_tree.dart, lib/web_ui/lib/src/engine/canvaskit/layer_visitor.dart, lib/web_ui/lib/src/engine/canvaskit/overlay_scene_optimizer.dart, lib/web_ui/lib/src/engine/canvaskit/rasterizer.dart, lib/web_ui/test/canvaskit/embedded_views_test.dart, lib/web_ui/test/ui/scene_builder_test.dart
This enhances the overlay optimization by delaying combining pictures to get tighter bounds for the pictures that make up the scene, enabling more sophisticated optimization since we can determine if they intersect with platform views on a per-picture basis.
Fixes https://github.com/flutter/flutter/issues/149863
On a Macbook in Chrome in an example app with an infinite scrolling grid of platform views, this brings the ratio of dropped frames from 93% to 55% (roughly 4 fps to 30 fps).
This is a reland of https://github.com/flutter/engine/pull/54878 with a fix for scenes with pictures and shader masks that are eventually entirely clipped out. …
=> Reland "[canvaskit] Further improve overlay optimization by splitting pictures"

impeller/typographer/backends/skia/text_frame_skia.cc
Use a faster approximation for finding out axis alignment that skips opening the font file, which is slow!
=> [Impeller] avoid reading font while parsing sktextblob.

shell/platform/embedder/embedder.cc, shell/platform/embedder/embedder.h, shell/platform/embedder/tests/embedder_assertions.h, shell/platform/embedder/tests/embedder_gl_unittests.cc, shell/platform/embedder/tests/embedder_test_backingstore_producer.cc
Trying to use the `GL_BGRA8_EXT` format for the EGL surface backing store on *desktop* OpenGL platforms would fail at: https://github.com/flutter/engine/blob/bde314b856850155d0678632b62c23c84f49afab/shell/platform/embedder/embedder.cc#L869
This seems to be a known issue and both the Linux and Windows embedders have some logic to pick a different format depending on the OpenGL context information:
https://github.com/flutter/engine/blob/088dcfa6cf934088413c5d8af754de1ef7b0d1ca/shell/platform/windows/compositor_opengl.cc#L23-L34
https://github.com/flutter/engine/blob/088dcfa6cf934088413c5d8af754de1ef7b0d1ca/shell/platform/linux/fl_framebuffer.cc#L81-L104
This pull-request gets rid of the hard-coded `GL_BGRA8_EXT` format and makes it configurable by adding a `format` field to the …
=> Add `format` field to EGL surface backing store

.ci.yaml
This is passing consistently now.
=> [ci] make opengles impeller scenario app non-bringup

lib/web_ui/dev/generate_builder_json.dart, lib/web_ui/dev/test_runner.dart
Recent [changes](https://github.com/flutter/engine/pull/54584) affected our builder configs, but the script that generates those builder configs wasn't updated.
=> [web] Update builder json generator to reflect recent changes

lib/web_ui/dev/browser.dart, lib/web_ui/dev/chrome.dart, lib/web_ui/dev/test_platform.dart
Without this the test runner will hang if the compiled test is invalid and unable to execute.
=> Listen for uncaught exceptions during loading of a web test suite in Chrome

docs/README.md
Fix broken links in docs/, specifically replaces ../ with https://github.com/flutter/flutter/blob/master/docs/ …
=> [docs] Fix broken links in docs/

ci/builders/local_engine.json
Most iOS embedder developers rely on two simulator builds:
* ios_debug_sim_unopt (for simulators on x64 hosts)
* ios_debug_sim_unopt_arm64 (for simulators on arm64 hosts)
We specify these two builds, for example, in our iOS unit test Xcode project `testing/ios/IosUnitTests/Tests/FlutterEngineConfig.xcconfig`.
Currently `local_engine.json` specifies two simulator builds:
* ios_debug_sim_unopt (for simulators on x64 hosts)
* ios_debug_sim_arm64 (for simulators on arm64 hosts)
While the x64 build specifies the `--unoptimized` flag, the arm64 build does not, which is problematic for those wanting to use both `et` and run the iOS unit tests.
This adds the `--unoptimized` flag for consistency with prevailing practice among iOS embedder developers.
If you need help, consider asking for advice on …
=> Make arm64 iOS simulator local engine build unopt

shell/platform/darwin/ios/BUILD.gn, shell/platform/darwin/ios/framework/Source/FlutterAppDelegate.mm
Migrates the FlutterAppDelegate.mm translation unit to be compiled with the `-fobjc-arc` compiler flag.
No test changes since no this change includes no semantic changes, and thus covered by existing tests such as [`testReleasesWindowOnDealloc`](https://github.com/flutter/engine/blob/3dfb4622de88abb48ce65be56ff29422ab43805f/shell/platform/darwin/ios/framework/Source/FlutterAppDelegateTest.mm#L139-L153). …
=> iOS: Migrate FlutterAppDelegate to ARC

tools/engine_tool/test/build_command_test.dart, tools/engine_tool/test/gn_test.dart, tools/engine_tool/test/query_command_test.dart, tools/engine_tool/test/test_command_test.dart, tools/engine_tool/test/utils_test.dart
I also removed other no-longer-enforced cruft. No behavioral changes.
=> Migrate `try/finally` calls to `addTearDown`.

display_list/skia/dl_sk_dispatcher.cc, testing/dart/canvas_test.dart
Colors are optionally provided, so make sure to null check the array.
Fixes https://github.com/flutter/flutter/issues/155783
=> Fix npe during skia dispatch of drawAtlas

shell/platform/darwin/ios/BUILD.gn, shell/platform/darwin/ios/framework/Headers/FlutterEngineGroup.h, shell/platform/darwin/ios/framework/Source/FlutterEngineGroup.mm
This migrates FlutterEngineGroup to automatic reference counting. It also migrates `enginesCreatedCount` from an ivar to property syntax.
I'll look at migrating engine from `NSMutableArray<NSValue*>` to a weak pointer array in a followup patch since it's orthogonal to ARC migration. …
=> iOS: Migrate FlutterEngineGroup to ARC

engine.code-workspace, tools/vscode_workspace/engine-workspace.yaml
This turns on Metal validation for launching impeller_unittests from the tests panel.  This matches the default behavior of launching tests from XCode.  Without these assertions errors in Metal are completely silent.  In my case I just got a black screen until I tried running the tests through xcode. …
=> Added metal validation for `impeller_unittests

build/dart/internal/gen_dartcli_call.gni
Follow-up to https://github.com/flutter/engine/pull/55475
Test: `flutter/tools/gn --no-prebuilt-dart-sdk --unoptimized --runtime-mode debug && ninja -C out/host_debug_unopt`
=> Fix gen_dartcli_call in --no-prebuilt-dart-sdk.

tools/engine_tool/test/build_command_test.dart, tools/engine_tool/test/lint_command_test.dart, tools/engine_tool/test/src/test_build_configs.dart, tools/engine_tool/test/utils.dart
Partial work towards https://github.com/flutter/flutter/issues/148420, unblocks https://github.com/flutter/engine/pull/55537.
These tests can now be more precise, and changing the fixtures no longer has side-effects on tests across the entire repository. There are about 11 other usages (there were ~50 in these) after this PR that I'll get to, as well as the hard-coded `gn desc` output, before retiring `fixtures.dart`
=> Migrate off a global test fixture for `build` and `lint`.

vulkan/vulkan_application.cc, vulkan/vulkan_application.h
Log Vulkan loader errors if the instance failed creation on Fuchsia
The vulkan loader can output logs to help us debug why instance creation
fails. To catch these logs, we need to pass a debug report callback to
vkCreateInstance (since the only other debug report callback is set up
after the instance is created).
Outputting logs is currently only enabled on Fuchsia, since other
platforms may have fallbacks and wouldn't want the error logspam.
Fixes https://github.com/flutter/flutter/issues/82928 …
=> Log Vulkan loader errors if the instance failed creation on Fuchsia

shell/platform/linux/fl_engine.cc, shell/platform/linux/fl_engine_private.h, shell/platform/linux/fl_engine_test.cc, shell/platform/linux/fl_view.cc, shell/platform/linux/fl_view_test.cc, shell/platform/linux/public/flutter_linux/fl_view.h, shell/platform/linux/testing/mock_engine.cc
Allocate view IDs for secondary Flutter views - another step towards full multi-view support.
=> Allocate a view ID for secondary views

shell/platform/darwin/ios/BUILD.gn, shell/platform/darwin/ios/framework/Source/accessibility_bridge.h, shell/platform/darwin/ios/framework/Source/accessibility_bridge.mm
Keeps fml::scoped_* wrappers used in C++ class declarations in headers, since those are injected into both ARC and non-ARC translation units and these classes are ARC-safe. Once we've migrated all users of those headers to ARC, we can use the underlying classes directly.
No semantic changes, therefore not changes to tests.
[C++, …
=> iOS: Migrate accessibility_bridge to ARC

tools/engine_tool/test/query_command_test.dart
The logical "part 2" of the work started in https://github.com/flutter/engine/pull/55540.
Test output does not change, the tests just no longer rely on the global `fixtures.dart` data.
=> Use localized config data for `et query` tests.

tools/engine_tool/test/test_command_test.dart
The logical "part 2.5" of the work started in https://github.com/flutter/engine/pull/55540.
Test output does not change, the tests just no longer rely on the global `fixtures.dart` data.
=> Use localized config data for `et test` tests.

ci/builders/linux_android_emulator.json, ci/builders/standalone/linux_android_emulator_skia.json
https://chrome-infra-packages.appspot.com/p/chromium/tools/android/avd/linux-amd64/+/build_id:8735216702926189361
Update android emulator version to latest available on cipd to rule out old emulator versions as an issue for stability. 
Related to https://b.corp.google.com/issues/371020223 
Note these tests are in bringup so should not impact pre/post submit stability.
=> Check stability against most recent cipd emulator artifact

ci/builders/linux_android_aot_engine.json, ci/builders/linux_android_debug_engine.json, ci/builders/linux_arm_host_engine.json, ci/builders/linux_fuchsia.json, ci/builders/linux_host_desktop_engine.json, ci/builders/linux_host_engine.json, ci/builders/linux_unopt.json, ci/builders/mac_android_aot_engine.json, ci/builders/mac_ios_engine.json
This is my bad for not having this documented better/at-all, but since this build does not produce artifacts, it should not go under a builder that is marked as `release_build: "true"` in the .ci.yaml. This PR moves the build to `linux_unopt.json`.
=> Shift --no-prebuilt-dart-sdk build to linux_unopt

shell/platform/darwin/ios/ios_surface_noop_unittests.mm
Previously, we were passing `nullptr` to the `IOSSurfaceNoop` constructor:
https://github.com/flutter/engine/blob/de1762dbc5cc3483631c5e511a3496998ec6cf65/shell/platform/darwin/ios/ios_surface_noop.mm#L23-L24
which calls the IOSSurface constructor:
https://github.com/flutter/engine/blob/de1762dbc5cc3483631c5e511a3496998ec6cf65/shell/platform/darwin/ios/ios_surface.mm#L55-L58
Which calls `FML_DCHECK(ios_context_)`, which really doesn't like it when `ios_context_` is null.
I will later follow up with the next question of... "what exactly is going on with our CI here?", but this unbreaks my local dev testing workflow for the moment :) …
=> iOS: Fix IOSSurfaceNoopTest

impeller/toolkit/interop/BUILD.gn, impeller/toolkit/interop/dl_builder.cc, impeller/toolkit/interop/dl_builder.h, impeller/toolkit/interop/formats.h, impeller/toolkit/interop/impeller.cc, impeller/toolkit/interop/impeller.h, impeller/toolkit/interop/impeller_unittests.cc, impeller/toolkit/interop/paragraph.cc, impeller/toolkit/interop/paragraph.h, impeller/toolkit/interop/paragraph_builder.cc, impeller/toolkit/interop/paragraph_builder.h, impeller/toolkit/interop/paragraph_style.cc, impeller/toolkit/interop/paragraph_style.h, impeller/toolkit/interop/typography_context.cc, impeller/toolkit/interop/typography_context.h, third_party/txt/src/skia/paragraph_builder_skia.cc, third_party/txt/src/skia/paragraph_builder_skia.h, third_party/txt/src/txt/paragraph_builder.h
This uses the same shaper as the rest of Flutter. The minimal ICU data configuration comes embedded in the dylib so there are no out-of-band packaging concerns.
Fixes https://github.com/flutter/flutter/issues/156015
=> [Impeller] A text layout and shaping API for the standalone library.

build/dart/internal/dart_test.gni, build/dart/internal/gen_dartcli_call.gni, build/dart/internal/gen_executable_call.gni, build/dart/rules.gni, tools/engine_tool/BUILD.gn
Work towards https://github.com/flutter/flutter/issues/147013.
I think I still need applicable metadata about the output, and then make sure `et test` understands everything:
```sh
% et test //flutter/tools/engine_tool/...
[2024-10-03 13:26:42.657137] ERROR: No test targets found
```
=> Add and use a `dart_test` rule.

shell/platform/darwin/ios/BUILD.gn, shell/platform/darwin/ios/framework/Source/FlutterEngine.mm, shell/platform/darwin/ios/framework/Source/FlutterPlatformPlugin.h, shell/platform/darwin/ios/framework/Source/FlutterPlatformPlugin.mm, shell/platform/darwin/ios/framework/Source/FlutterPlatformPluginTest.mm
Migrates `FlutterEnging` from manual reference counting to ARC. Migrates properties from `retain` to strong and `assign` to `weak` (where referencing an Obj-C object).
No semantic changes, therefore no changes to tests.
[testing the …
=> iOS: Migrate FlutterEngine to ARC

impeller/display_list/dl_dispatcher.cc, impeller/display_list/dl_dispatcher.h, shell/common/snapshot_controller_impeller.cc, testing/dart/painting_test.dart
Fixes https://github.com/flutter/flutter/issues/156161
Mips must be eagerly generated for Picture.toImage and friends so that filter quality (mip sampling) works as expected.
=> [Impeller] generate mipmaps for toImage.

build/dart/internal/dart_test.gni, build/dart/internal/gen_dartcli_call.gni, build/dart/internal/gen_executable_call.gni, tools/engine_tool/lib/src/gn.dart, tools/engine_tool/lib/src/typed_json.dart, tools/engine_tool/test/external_tools/gn_test.dart, tools/engine_tool/test/typed_json_test.dart
Closes https://github.com/flutter/flutter/issues/147013.
Closes https://github.com/flutter/flutter/issues/147071.
/cc @reidbaker who I know wants to do this for the Java rules soon TM.
/cc @jtmcdole, @zanderso for visibility.
=> Add support for `et test //flutter/path/to/dart_test`

impeller/entity/geometry/fill_path_geometry.cc, impeller/entity/geometry/stroke_path_geometry.cc, impeller/geometry/geometry_unittests.cc, impeller/geometry/matrix.cc, impeller/geometry/matrix.h
MaxBasisXYZ prevents usage of scaling factors less than one since Z is almost always 1.
Fixes https://github.com/flutter/flutter/issues/153451
=> [Impeller] remove usage of MaxBasisLength in favor of XY variant.

lib/gpu/formats.h, lib/gpu/lib/src/formats.dart, lib/gpu/lib/src/render_pass.dart, lib/gpu/render_pass.cc, lib/gpu/render_pass.h, testing/dart/gpu_test.dart
Resolves https://github.com/flutter/flutter/issues/155636.
(Extends test in https://github.com/flutter/engine/pull/55409)
=> [Flutter GPU] Add WindingOrder.

display_list/skia/dl_sk_canvas.cc, display_list/skia/dl_sk_dispatcher.cc, display_list/testing/dl_rendering_unittests.cc, testing/dart/painting_test.dart
The blur ImageFilter has a tile mode that describes how to sample pixels near the edge of the source. When used as a BackdropFilter this behavior is important as the wrong tile mode can cause distracting flashing as app content is scrolled under foreground widgets that blur their background. Unfortunately the Skia backend used to default the tile mode for all backdrop filters to `clamp` mode with no way to update it and that mode was the one that produced the most distracting flashing.
Recently Skia opened up control over the tile mode used for backdrop filters and we now take advantage of that capability so that app developers can now set the tile mode to a nicer value.
=> Honor blur tile mode in BackdropFilter widget on Skia backend

docs/monorepo/history_strategy.md
AKA "Dude Where's My Files?"
Document the history editing that will occur during the monorepo merge. `flutter/engine` will remain the source of truth of revisions older than the merge.
=> La Grande Fusion Notes - History Editing

shell/platform/darwin/ios/BUILD.gn, shell/platform/darwin/ios/framework/Source/FlutterEngine.mm, shell/platform/darwin/ios/framework/Source/FlutterPlatformPlugin.h, shell/platform/darwin/ios/framework/Source/FlutterPlatformPlugin.mm, shell/platform/darwin/ios/framework/Source/FlutterPlatformPluginTest.mm
Causing flakes on the _Mac mac_unopt (Cocoon)_ shard.
This reverts commit 449df252a2f13a10aced5ea1d7000cf4e276d71a.
Issue: https://github.com/flutter/flutter/issues/156177
[CLA]: …
=> Revert "iOS: Migrate FlutterEngine to ARC (#55590)"

impeller/toolkit/android/surface_control.cc
Fixes https://github.com/flutter/flutter/issues/155877
Technically SurfaceControl is supported on API 29 but I've observed enough reported bugs that I'm bumping the constraint to 30. If  we had more time to test all of these older devices maybe we could figure out if the problem is something that can be worked around.
=> [Impeller] disable surface control on API 29.

impeller/renderer/backend/metal/context_mtl.mm, lib/ui/fixtures/ui_test.dart, lib/ui/painting/image_decoder_impeller.cc, lib/ui/painting/image_encoding_unittests.cc
b/371512414
This issue had no reproduction but the stacktrace was provided.  The theory of this fix is that the `ImageResult` type is capturing something that doesn't handle being copied and deallocated twice so instead of copying it, we std::move it into a shared_ptr so that it will only be deallocated once.
Also, I just avoid using a `std::move` when overflowing.  The idea here is maybe sometimes deleting the std::move'd item isn't kosher.  We know from the stacktrace that it has something to do with overflowing because that would be the only case where something is being deleted.
I've added 2 integration tests that exercises the code where the crash appears to be happening.  This is good coverage to have but neither of them reproduced the issue, even with MallocScribble enabled. …
=> Speculative fix for memory issues related to retrying image decompression

lib/web_ui/lib/src/engine/color_filter.dart, lib/web_ui/lib/src/engine/layers.dart, lib/web_ui/lib/src/engine/scene_builder.dart, lib/web_ui/lib/src/engine/scene_painting.dart, lib/web_ui/lib/src/engine/scene_view.dart, lib/web_ui/lib/src/engine/skwasm/skwasm_impl/filters.dart, lib/web_ui/test/engine/scene_builder_test.dart, lib/web_ui/test/engine/scene_builder_utils.dart, lib/web_ui/test/engine/scene_view_test.dart, lib/web_ui/test/ui/scene_builder_test.dart
This reverts commit def85c709fa1239df33147189769c67ae8185be0 (https://github.com/flutter/engine/pull/55468)
Reason for revert, devtools has been having rendering issues since this commit. See https://github.com/flutter/devtools/issues/8401
=> Revert "Reland [skwasm] Scene builder optimizations for platform view placement (#55468)"

lib/web_ui/lib/src/engine/configuration.dart, lib/web_ui/lib/src/engine/renderer.dart, lib/web_ui/test/html/deprecation_test.dart
Warn users when they pick a deprecated renderer for the web, and point them to the appropriate /go/ link.
* Part of https://github.com/flutter/flutter/issues/145954
* Fixes https://github.com/flutter/flutter/issues/154879 …
=> [web] Warn users when picking a deprecated renderer.

engine.code-workspace, tools/vscode_workspace/engine-workspace.yaml
=> added shell_unittests and ui_unittests to the testing menu

impeller/renderer/backend/metal/context_mtl.h, impeller/renderer/backend/metal/context_mtl.mm
b/371513051
The tasks are already capturing their target thread.  I had just missed guarding the deque that is storing the tasks.  This has been seen in the flaking of the newly added `ShellTest.EncodeImageRetryOverflows`.
Example: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8734621687934134433/+/u/test:_Host_Tests_for_host_debug_unopt/stdout …
=> Added mutex to the pending gpu tasks deque.

shell/platform/android/io/flutter/embedding/engine/renderer/FlutterRenderer.java, shell/platform/android/test/io/flutter/embedding/engine/renderer/FlutterRendererTest.java
Fixes https://github.com/flutter/flutter/issues/156434.
A better fix for the workaround in https://github.com/flutter/flutter/issues/156158.
This should likely be cherrypicked, as it's a memory leak, safe, and avoids workaround code in plugins.
=> Release`onTrimMemoryListener` after `ImageReaderSurfaceProducer` released.

impeller/playground/playground.cc, impeller/renderer/backend/vulkan/test/swapchain_unittests.cc, impeller/renderer/surface.cc, impeller/renderer/surface.h, impeller/toolkit/interop/surface.cc, shell/gpu/gpu_surface_gl_impeller.cc, shell/gpu/gpu_surface_metal_impeller.mm, shell/gpu/gpu_surface_vulkan_impeller.cc
Closes https://github.com/flutter/flutter/issues/154799.
=> Rename `GetTargetRenderPassDescriptor` to `GetRenderTarget`.

impeller/toolkit/interop/color_source.cc, impeller/toolkit/interop/color_source.h, impeller/toolkit/interop/impeller.cc, impeller/toolkit/interop/impeller.h
Fixes https://github.com/flutter/flutter/issues/156360
This was missed in the earlier bringup.
cc @lyceel I did not expose the solid color source since (as @jonahwilliams [pointed out](https://github.com/flutter/flutter/issues/156360#issuecomment-2398005436)) all it does it [clear the current color source and set the color on the paint](https://github.com/flutter/engine/blob/72dca1bca3abe9e74ff74b35404f5c0f0dffe3bb/display_list/dl_builder.cc#L206).
=> [Impeller] libImpeller: Allow creating image color sources.

lib/web_ui/lib/src/engine.dart, lib/web_ui/lib/src/engine/semantics.dart, lib/web_ui/lib/src/engine/semantics/header.dart, lib/web_ui/lib/src/engine/semantics/semantics.dart, lib/web_ui/test/engine/semantics/semantics_test.dart
Now that we have [proper headings](https://github.com/flutter/engine/blob/main/lib/web_ui/lib/src/engine/semantics/heading.dart), headers should become proper headers.
Fixes https://github.com/flutter/flutter/issues/152268
=> [web:a11y] make header a proper <header>

common/settings.h, shell/common/switches.cc, shell/platform/android/android_shell_holder.cc, shell/platform/android/android_shell_holder_unittests.cc
When I removed the configration, I neglected the line that overrode the default from settings. This opted everyone back out. :(
=> [engine] remove merge thread setting and fix default value.

display_list/display_list_unittests.cc, display_list/dl_builder.cc, display_list/dl_builder.h, display_list/dl_canvas.cc, display_list/dl_canvas.h, display_list/geometry/dl_geometry_types.h, display_list/skia/dl_sk_canvas.cc, display_list/skia/dl_sk_canvas.h, display_list/testing/dl_rendering_unittests.cc, display_list/utils/dl_matrix_clip_tracker.cc, display_list/utils/dl_matrix_clip_tracker.h, flow/layers/display_list_layer_unittests.cc, flow/raster_cache.cc, flow/stopwatch_sk.cc, impeller/display_list/aiks_dl_basic_unittests.cc, impeller/display_list/aiks_dl_blend_unittests.cc, impeller/display_list/aiks_dl_blur_unittests.cc, impeller/display_list/aiks_dl_gradient_unittests.cc, impeller/display_list/aiks_dl_path_unittests.cc, impeller/display_list/aiks_dl_unittests.cc, impeller/display_list/dl_unittests.cc, shell/platform/android/surface_texture_external_texture.cc, shell/platform/android/surface_texture_external_texture_vk_impeller.cc, shell/platform/embedder/embedder_external_texture_gl.cc, shell/platform/embedder/embedder_external_texture_metal.mm, shell/platform/fuchsia/flutter/canvas_spy_unittests.cc, testing/mock_canvas.cc, testing/mock_canvas.h
This is the beginning of the bulk of de-skia-fication work in the engine. All of the standard types in the DlCanvas API now have overloads that specify the corresponding Dl type, mainly for Dl*Rect and DlPoint types. This enables further work to switch from SkFoo types to DlFoo types in the various engine modules culminating in the elimination of the old methods that use the Sk types.
All of the former methods that used the basic Sk types are now implemented as inlinable translation overloads and the underlying implementations of DlCanvas now implement only the newer style interfaces so that they don't need to be further modified as we eliminate the old Skia types from the interface.
There are still a couple of Skia types remaining in the DlCanvas API without any DL type variants which …
=> [DisplayList] Create DlFoo type variants to start moving away from Skia types in API

shell/platform/darwin/ios/framework/Source/FlutterPlatformViewsTest.mm, shell/platform/darwin/ios/framework/Source/FlutterPlatformViews_Internal.mm
I came across our the "gesture recognizer delegate" implementation and it is quite odd (see below). After fixing it, the problem is resolved. However, it's hard to reason about how it's related to iPad pencil, since it's internal logic that we don't know (see my research below). 
- shouldBeRequiredToFailByGestureRecognizer: 
`otherGestureRecognizer != self` is always YES because the delegate set to self, hence `gestureRecognizer` must be self, hence `otherGestureRecognizer` must not be self. 
- shouldRequireFailureOfGestureRecognizer: 
`otherGestureRecognizer == self` is always NO, for the same reason described above. 
After digging into various PRs, the idea seems to be that we want to have a precedence of "Forwarding recognizer >  Delaying recognizer > Other recognizers in platform …
=> [ios][platform_view] Fix Platform view gesture recognizer with iPad pencil getting stuck

impeller/toolkit/interop/impeller.cc
cc @lyceel. I'll followup with a linker script to to verify this later.
=> [Impeller] libImpeller: Fix missing exports on some paint methods.

DEPS
This change switches from using `xcodebuild` to `xcrun` for discovering the paths of installed Apple SDKs. `xcrun` tries reading this information from a cache first, which may help avoid timeouts in CI.
Related https://github.com/flutter/flutter/issues/155106
=> Roll buildroot for flutter/buildroot#912

impeller/entity/geometry/point_field_geometry.cc, impeller/entity/geometry/point_field_geometry.h
Remove the extra host -> host copy performed by the VertexBufferBuilder. Instead, write the drawPoint geometry right into the transients buffer.
https://github.com/flutter/flutter/issues/152702
=> [Impeller] remove extra copy from drawPoints.

common/settings.h, shell/common/switches.cc, shell/platform/darwin/ios/framework/Source/FlutterDartProject.mm, shell/platform/darwin/ios/framework/Source/FlutterEngineTest.mm
Addresses https://github.com/flutter/flutter/issues/155541
This does **not** remove Skia itself from the build. I'll stage that in a followup. Want to keep the scope of this patch small.
This is the new behavior:
* Impeller is the default on iOS devices **and** simulators.
* On iOS devices **only**, all flags and plist options are ignored.
* On iOS simulators **only**, Flutter will used Impeller's Metal backend by default and fallback to the Null backend if Metal device access is not available.
* On iOS simulators **only**, Flutter can pick Skia using the command line flags or plist flags. This is to allow users one more month to migrate as communicated by @zanderso.
The settings objects `enable_impeller` field is now `static constexpr` to avoid accidentally disabling the flag while it …
=> [Impeller] Ignore opt-outs on iOS devices.

impeller/toolkit/interop/impeller.cc, impeller/toolkit/interop/impeller_unittests.cc, impeller/toolkit/interop/paragraph_builder.cc, impeller/toolkit/interop/paragraph_builder.h, impeller/toolkit/interop/paragraph_style.cc, impeller/toolkit/interop/paragraph_style.h
Thanks to the @lyceel for the failing test case.
=> [Impeller] libImpeller: Initialize the base paragraph style lazily.

impeller/entity/contents/filters/gaussian_blur_filter_contents.cc, impeller/geometry/matrix.h, impeller/geometry/matrix_unittests.cc, impeller/geometry/scalar.h
fixes https://github.com/flutter/flutter/issues/156871
testing: performance change covered by existing benchmarks. …
=> Starts looking for the bdf fast path in relation to the snapshot_entity's transform

lib/ui/painting/image_decoder_impeller.cc, lib/ui/painting/image_decoder_unittests.cc
Fixes https://github.com/flutter/flutter/issues/156728
Need to periodically flush the TLS command buffer pools in multiframe codec just like single frame codec.
=> [Impeller] fix memory leak during gif upload.

tools/yapf.sh
fixes https://github.com/flutter/flutter/issues/156993 …
=> Started using a specific python for yapf

lib/ui/semantics.dart, lib/ui/semantics/semantics_node.h, lib/web_ui/lib/semantics.dart, lib/web_ui/test/engine/semantics/semantics_api_test.dart, shell/platform/android/io/flutter/view/AccessibilityBridge.java, shell/platform/embedder/embedder.h, testing/dart/semantics_test.dart
Introduce `SemanticsFlag.hasSelectedState` to the engine API. At this point the flag is not backed by any engine functionality. See also: https://github.com/flutter/flutter/issues/66673#issuecomment-2402903402
| :warning: WARNING           |
|:----------------------------|
| Submit _AFTER_ https://github.com/flutter/flutter/pull/157017 and https://github.com/flutter/flutter/pull/157061 land in the framework     |
A step towards https://github.com/flutter/flutter/issues/66673
=> Introduce SemanticsFlag.hasSelectedState to the engine API

impeller/entity/contents/text_contents.cc, impeller/renderer/backend/gles/buffer_bindings_gles.cc, impeller/renderer/backend/gles/render_pass_gles.cc, impeller/renderer/backend/metal/render_pass_mtl.h, impeller/renderer/backend/metal/render_pass_mtl.mm, impeller/renderer/backend/vulkan/render_pass_vk.cc, impeller/renderer/backend/vulkan/render_pass_vk.h, impeller/renderer/command.cc, impeller/renderer/command.h, impeller/renderer/render_pass.cc, impeller/renderer/render_pass.h, impeller/renderer/renderer_unittests.cc, lib/gpu/render_pass.cc, lib/gpu/render_pass.h, testing/dart/gpu_test.dart
Resolves https://github.com/flutter/flutter/issues/156764.
Resolves https://github.com/flutter/flutter/issues/155335.
- Remove Command/VertexBuffer from Flutter GPU.
- Separate vertex/index count into `impeller::RenderPass::SetElementCount(size_t count)` & accurately document its behavior.
- Make Flutter GPU uniform/texture bindings re-assignable.
- Remove unnecessary templates.
=> [Flutter GPU] Remove Command/VertexBuffer usage from Flutter GPU.

shell/platform/darwin/ios/BUILD.gn, shell/platform/darwin/ios/framework/Source/FlutterEngine.mm, shell/platform/darwin/ios/framework/Source/FlutterPlatformPlugin.h, shell/platform/darwin/ios/framework/Source/FlutterPlatformPlugin.mm, shell/platform/darwin/ios/framework/Source/FlutterPlatformPluginTest.mm, shell/platform/darwin/ios/framework/Source/FlutterViewControllerTest.mm
This reverts commit 2484ae11b5eed2632658081f6d877911517dde2c.
This relands commit 449df252a2f13a10aced5ea1d7000cf4e276d71a.
Migrates `FlutterEngine` from manual reference counting to ARC. Migrates properties from `retain` to strong and `assign` to `weak` (where referencing an Obj-C object).
Includes two additional fixes on top of the original:
* In `waitForFirstFrame:callback:` we ensure FlutterEngine isn't released on a background thread, but instead is always freed on the platform thread.
* In `testViewControllerIsReleased` we call loadView prior to calling `viewDidLoad`. `viewDidLoad` calls `[FlutterEngine attachView]` which calls `[PlatformViewIOS::attachView]` which asserts that the view is loaded.
No semantic changes, therefore no changes to tests.
Issue: …
=> Reland "iOS: Migrate FlutterEngine to ARC"

shell/platform/linux/fl_keyboard_manager.cc, shell/platform/linux/fl_keyboard_manager.h, shell/platform/linux/fl_keyboard_manager_test.cc, shell/platform/linux/fl_keyboard_view_delegate.cc, shell/platform/linux/fl_keyboard_view_delegate.h, shell/platform/linux/fl_view.cc
Events can only be redispatched using gdk_event_put which is not dependent on the view.
Ideally the tests would mock gdk_event_put, but I wasn't able to get it working so I've added fl_keyboard_manager_set_redispatch_handler for now.
=> Move redispatch_event from FlKeyboardViewDelegate to FlKeyboardManager

impeller/renderer/backend/vulkan/render_pass_builder_vk.cc, impeller/renderer/backend/vulkan/render_pass_builder_vk_unittests.cc, impeller/renderer/backend/vulkan/render_pass_vk.cc
From local testing:
1. This is slightly faster
2. This still renders correctly even on old phones (S10)
3. This is validation error clean.
---------------
The vk RenderPass has a built in mechanism to transition the attachments between layout states. Since we expect the images to be in eGeneral layout, we can configure the render pass to do an eUnderfined -> eGeneral  transition. eUnderfined means "we don't care what was here before". This is OK because we're about to clear the texture anyway.
Since the RenderPass is doing the transition, we don't need an explicit barrier. All we have to do is update our own state tracking mechanism that the image attachments should behave as if they were in eGeneral layout  - because they are once the render pass is started.
=> [Impeller] use render pass to transition attachments to eGeneral instead of barriers.

impeller/core/texture.h, impeller/entity/inline_pass_context.cc, impeller/renderer/backend/gles/reactor_gles.cc, impeller/renderer/backend/gles/reactor_gles.h, impeller/renderer/backend/gles/texture_gles.cc, impeller/renderer/backend/gles/texture_gles.h, impeller/renderer/backend/metal/texture_mtl.h, impeller/renderer/backend/metal/texture_mtl.mm, impeller/renderer/backend/vulkan/context_vk.h, impeller/renderer/backend/vulkan/texture_vk.cc, impeller/renderer/backend/vulkan/texture_vk.h, impeller/renderer/render_target.cc, impeller/renderer/testing/mocks.h, lib/ui/painting/image_decoder_no_gl_unittests.h
Avoid Sprintf'ing labels for textures/cmd buffers/render passes. For the render target textures, defer combined label construction until we know the label will be used.
=> [Impeller] simpler labels for render target textures and cmd buffers.

shell/common/shell.cc
Shell::OnPlatformViewDispatchPlatformMessage is called on the platform thread and must invoke the message handler on the UI thread.  If the platform and UI threads are merged, then the handler can be run immediately.  The shell can then post an empty task to the UI thread to make the UI message loop run the task observer that drains the microtask queue.
Fixes https://github.com/flutter/flutter/issues/156595
=> On a merged UI/platform thread, immediately execute platform message handlers and then run microtasks

shell/platform/darwin/macos/BUILD.gn
We were copying the macOS privacy manifest to the wrong path, which led to codesigning failing.
See https://github.com/flutter/flutter/issues/157016#issuecomment-2420786225 for more context.
=> Beta fix macos xcprivacy manifest copy location

common/settings.h, shell/common/switches.cc, shell/common/switches.h, shell/platform/android/android_shell_holder.cc, shell/platform/android/android_shell_holder_unittests.cc, shell/platform/android/io/flutter/embedding/engine/loader/FlutterLoader.java
Add back opt out for merged threads for customer money.
=> [engine] add back opt out for merged threads.

shell/platform/darwin/ios/BUILD.gn, shell/platform/darwin/ios/framework/Source/FlutterEngine.mm, shell/platform/darwin/ios/framework/Source/FlutterPlatformPlugin.h, shell/platform/darwin/ios/framework/Source/FlutterPlatformPlugin.mm, shell/platform/darwin/ios/framework/Source/FlutterPlatformPluginTest.mm, shell/platform/darwin/ios/framework/Source/FlutterViewControllerTest.mm
There are still a couple closures where on engine shutdown, the last live reference to FlutterEngine may be on a thread other than the platform thread.
Specifically, the profiling data capture callback can result in the last live reference to a FlutterEngine being on a profiling thread, resulting in an assertion failure in the destructor of the PlatformViewsController held by FlutterEngine, because PlatformViewsController holds a WeakPtrFactory whose destructor asserts that it be on the platform thread.
See:
https://github.com/flutter/engine/blob/ad9e4fef451a73427285826455db5fbdde502bd7/shell/platform/darwin/ios/framework/Source/FlutterEngine.mm#L511-L515
Backtrace of such a crash:
```
=================================================================
Main Thread Checker: UI API called on …
```
=> Revert "Reland "iOS: Migrate FlutterEngine to ARC" (#55937)"

shell/platform/darwin/ios/framework/Source/FlutterEngine.mm
iOS profiling is implemented in ProfileMetricsIOS, which has a default constructor, no member fields, and no superclass. i.e. it's roughly zero cost to create and holds no state. There's therefore no reason to make it an ivar on FlutterEngine.
Further, making it an ivar on FlutterEngine means that the profiling sampler lambda needs to capture self which, in the case where all other FlutterEngine references go out of scope during sampling, means that the last FlutterEngine reference exists on a profiling thread, and when the sampling lambda block completes, the engine is dealloc'ed.
The engine *must* be deallocated on the platform (main in Apple terminology) thread because FlutterEngine holds a reference to a PlatformViewsController, which owns a WeakPtrFactory. WeakPtrFactory's dtor …
=> iOS: Eliminate needless profiler metrics ivar

shell/platform/darwin/ios/BUILD.gn, shell/platform/darwin/ios/framework/Source/FlutterEngine.mm, shell/platform/darwin/ios/framework/Source/FlutterPlatformPlugin.h, shell/platform/darwin/ios/framework/Source/FlutterPlatformPlugin.mm, shell/platform/darwin/ios/framework/Source/FlutterPlatformPluginTest.mm, shell/platform/darwin/ios/framework/Source/FlutterViewControllerTest.mm
This reverts commit 752565630d5b8e51590e437da04279320846d0fc.
This relands commit 02fc8a455d0c4b70a70d36e7f4329f5ad706596d.
That commit was a reland of 449df252a2f13a10aced5ea1d7000cf4e276d71a.
Migrates `FlutterEngine` from manual reference counting to ARC. Migrates properties from `retain` to strong and `assign` to `weak` (where referencing an Obj-C object).
This has the following change from the previous patch:
* startProfiler was updated to eliminate the self-capture in https://github.com/flutter/engine/pull/55957 which prevents the possibility of dealloc on the profiling thread.
No semantic changes, therefore no changes to tests.
Issue: https://github.com/flutter/flutter/issues/156177
If you need help, consider asking for advice …
=> Re-reland "iOS: Migrate FlutterEngine to ARC"

impeller/toolkit/interop/impeller.cc, impeller/toolkit/interop/impeller.h, impeller/toolkit/interop/impeller_unittests.cc, impeller/toolkit/interop/typography_context.cc, impeller/toolkit/interop/typography_context.h
Fixes https://github.com/flutter/flutter/issues/156361
cc @lyceel. A bit of miscommunication on the priority of this one. I thought the default font factories were sufficient for the next release. But it turns out that was not true on the board which is a custom platform.
In any case, this should unblock custom font registrations. See the `CanCreateParagraphsWithCustomFont` case for an example. If you don't provide the family name alias for the custom font, the name will be read from the font data. This example uses the custom "WhatTheFlutter" custom font family in "wtf.otf".
=> [Impeller] libImpeller: Allow custom font registrations.

shell/platform/darwin/ios/framework/Source/FlutterEngineTest.mm
When run repeatedly, some of the iOS unit tests can relatively easily blow their test timeouts. Since we're testing behaviour and not performance in these tests there's no need to enforce a particular timeout.
The bots will fail if the tests timeout, regardless. …
=> iOS: Fix flaky tests (remove timeouts)

shell/platform/darwin/ios/framework/Source/FlutterEngine.mm
Previously, we dispatched a task to a background thread to wait for the first frame to be ready. In the background task, we then throw a task on the main thread that invokes that user-provided callback to notify them that the first frame is ready.
During ARC migration, we ensured that self was strongly-captured in the task that runs on the main thread, in order to prevent the possibility that the last remaining reference to the FlutterEngine instance be the one on the background thread.
However, with the previous code, it's possible that the callback is dispatched to the main thread, executes, and completes before the block on the background thread finishes. In that case, the last remaining FlutterEngine reference may *still* be the one on the background thread.
In order to prevent this …
=> iOS: Improve thread safety of first frame callback

lib/ui/compositing/scene_builder.cc
This is reponsible for the bdf golden breaking shader mask.
=> [UI] fix scene builder parameter naming.

shell/platform/linux/BUILD.gn, shell/platform/linux/fl_keyboard_manager.cc, shell/platform/linux/fl_keyboard_manager.h, shell/platform/linux/fl_keyboard_manager_test.cc, shell/platform/linux/fl_keyboard_view_delegate.cc, shell/platform/linux/fl_keyboard_view_delegate.h, shell/platform/linux/fl_view.cc, shell/platform/linux/testing/mock_keymap.cc, shell/platform/linux/testing/mock_keymap.h
Ideally the tests would mock gdk_keymap_lookup_key, but I wasn't able to get it working so I've added fl_keyboard_manager_set_lookup_key_handler for now.
=> Move keymap from FlKeyboardViewDelegate to FlKeyboardManager

shell/platform/android/io/flutter/embedding/engine/renderer/FlutterRenderer.java, shell/platform/android/test/io/flutter/embedding/engine/renderer/FlutterRendererTest.java
ImageReaderSurfaceProducer will request a frame when an image is enqueued. But there is no guarantee that each request will produce an additional frame.
Multiple requests happening within one vsync interval could be merged into one frame.  If no other frame is scheduled, then some images will remain in the queue and the image shown on screen will not be the latest image.
With this change, ImageReaderSurfaceProducer will continue requesting frames after consuming an image if the queue is not empty.
Fixes https://github.com/flutter/flutter/issues/156903
Fixes https://github.com/flutter/flutter/issues/155787
=> Request another frame in ImageReaderSurfaceProducer.dequeueImage if more images are pending in the queue

.ci.yaml, ci/builders/mac_unopt_debug_no_rbe.json
This build does not come in under the default 30 minute timeout when the caches are cold and the bot_update steps take too long: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20mac_clangd/2928/overview
=> Increase timeout for Linux mac_clangd

lib/web_ui/lib/src/engine/semantics/checkable.dart, lib/web_ui/lib/src/engine/semantics/heading.dart, lib/web_ui/lib/src/engine/semantics/image.dart, lib/web_ui/lib/src/engine/semantics/semantics.dart, lib/web_ui/test/engine/semantics/semantics_test.dart, lib/web_ui/test/engine/semantics/semantics_tester.dart
Implement `SemanticsFlag.hasSelectedState` and `SemanticsFlag.isSelected` for web in terms of `aria-selected`.
Fixes https://github.com/flutter/flutter/issues/66673
=> [web] implement selectable semantics

DEPS, pubspec.yaml
This PR updates the SoT location for `package:http_parser`; it's moved from dart-lang/http_parser to dart-lang/http (in pkgs/http_parser).
Issues:
- https://github.com/dart-lang/sdk/issues/56591 …
=> update the SoT location for package:http_parser

lib/gpu/context.cc, lib/gpu/context.h, lib/gpu/lib/src/command_buffer.dart, lib/gpu/lib/src/context.dart, lib/gpu/lib/src/render_pass.dart, lib/gpu/render_pass.cc, lib/gpu/render_pass.h, testing/dart/gpu_test.dart
Resolves https://github.com/flutter/flutter/issues/144264.
=> [Flutter GPU] Add missing MSAA stuff.

ci/licenses_golden/excluded_files, lib/snapshot/BUILD.gn, sky/tools/cp.py
Default implementation of copy does it via hardlink, which seems to be causing issues with Gatekeeper on mac.
BUG=https://github.com/flutter/flutter/issues/154437
=> Copy gen_snapshots using python's shutil.copy, avoid links

impeller/display_list/canvas.cc, impeller/display_list/canvas.h, impeller/display_list/canvas_unittests.cc, impeller/display_list/dl_dispatcher.cc, impeller/display_list/dl_dispatcher.h, impeller/entity/contents/content_context.cc
Fixes https://github.com/flutter/flutter/issues/157112
We currently track the number of backdrop filters in a frame. When the end of the frame is reached, we do a blit from the offscreen texture to the onscreen texture. Howeever, this extra blit is unecessary once we know we've rendered the last backdrop - and we can instead start the last render pass with the onscreen. This cuts out a fairly expensive blit.
this can only be done on iOS physical devices, vulkan, and some GLES - as emulated blends also use the backdrop.
Shader time is lower but timeline claims about 2.8ms and about ~800ms of blit pass.
Timeline is ~2.1 ms with no blit pass. Tracks with numbers above.
=> [Impeller] eagerly flip backdrop back to onscreen.

impeller/toolkit/interop/BUILD.gn, impeller/toolkit/interop/impeller.h
I believe I got the entire API other than the enum values. Though most a straightforward, some could use some clarification.
The typography stuff should now be easier to use. The README describes the object model and reference counting conventions.
=> [Impeller] libImpeller: Document the entire API.

testing/run_tests.py
Just fix the spelling of `warning`. …
=> Fix typo in testing script

lib/web_ui/lib/src/engine/canvaskit/surface.dart, lib/web_ui/test/canvaskit/surface_test.dart
Handles exceptions coming from `MakeSWCanvasSurface` and `MakeOffscreenSWCanvasSurface`.
Also makes surface size a member of `CkSurface` to make sure that it's always in sync with `surface`.
Fixes https://github.com/flutter/flutter/issues/154402 …
=> [canvaskit] Makes access to CkSurface null-safer

impeller/display_list/dl_dispatcher.cc
I suspect not flushing is related to occassionaly timeouts on flutter tester --enable impelller. because the flutter_tester never actually pumps a frame, it won't naturally flush these resources.
It shouldn't be harmful to otherwise flush.
=> [Impeller] flush thread local resources during toImage/toImageSync.

ci/licenses_golden/excluded_files, lib/snapshot/BUILD.gn, sky/tools/cp.py
Copy gen_snapshots using python's shutil.copy, avoid links
Default implementation of copy does it via hardlink, which seems to be causing issues with Gatekeeper on mac.
This is reland of 6c4f05c42aad0ea109df7bcdf4e175caaafc8bd7 with the fix for the case when target is a link to the source, that was the cause for revert 78f4ffab5c18aeb1e7a5dde2830c436ac0e16647
BUG=https://github.com/flutter/flutter/issues/154437
=> Reland copy gen snapshot

impeller/display_list/canvas.cc, impeller/display_list/canvas.h, impeller/display_list/dl_dispatcher.cc, impeller/entity/clip_stack_unittests.cc, impeller/entity/entity_pass_clip_stack.cc, impeller/entity/entity_pass_clip_stack.h, impeller/geometry/rect.h
For non-aa axis aligned difference clip rects or aa axis aligned difference clips that are very nearly integral, just use the scissor update and don't perform the depth write at all.
=> [Impeller] optimize clip rects by checking if integral coverage is sufficient.

shell/platform/darwin/ios/framework/Source/FlutterPlatformViewsTest.mm, shell/platform/darwin/ios/framework/Source/FlutterPlatformViews_Internal.mm
This PR force reset forwarding recognizer state when it's stuck at failed state, by recreating the recognizer (we are not able to reset the state back to possible - it has to be reset by UIKit). 
This is a tricky one since pencil and finger triggers exactly the same callbacks. It turns out that when pencil is involved after finger interaction, the platform view's "forwarding" gesture recognizer is stuck at failed state. This seems to be an iOS bug, because according to [the API doc](https://developer.apple.com/documentation/uikit/uigesturerecognizerstate/uigesturerecognizerstatefailed?language=objc), it should be reset back to "possible" state:
> No action message is sent and the gesture recognizer is reset to [UIGestureRecognizerStatePossible](https://developer.apple.com/documentation/uik …
=> [ios][platform_view]force reset forwarding recognizer state when its stuck

impeller/toolkit/interop/dl_builder.cc, impeller/toolkit/interop/dl_builder.h, impeller/toolkit/interop/impeller.cc, impeller/toolkit/interop/impeller.h, impeller/toolkit/interop/impeller_unittests.cc
Currently @lyceel has a workaround where they get the transform, create a new one, and call SetTransform. They would like to avoid this.
Fixes https://github.com/flutter/flutter/issues/156604
=> [Impeller] libImpeller: Allow appending to the transformation stack.

shell/platform/android/platform_view_android_jni_impl.cc
See failures in https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8733165720607371809/+/u/step_is_flaky:_run_platform_views_scroll_perf__timeline_summary/stdout
If we fail to acquire the next image from the image reader, its ok to return null from this method as the engine already handles displaying nothing.
THe crashes are due to us ... choosing to crash, which isn't really meaningful.
=> [android] make failing to acquire a java image non-fatal.

lib/web_ui/dev/steps/copy_artifacts_step.dart
A recent Skia commit added a test image that is used to check handling of invalid input.  This is causing some web tests to fail because Firefox rejects the image.
(see https://skia.googlesource.com/skia.git/+/ff59ce65022d71f883b7e3be146bbd32facadaf8)
=> [web] Do not copy invalid images in the Skia test image collection

impeller/toolkit/interop/impeller.h, impeller/toolkit/interop/impeller_unittests.cc, impeller/toolkit/interop/paragraph_style.cc
=> [Impeller] libImpeller: Respect the paragraph style line height specification.

shell/platform/linux/fl_view.cc
Add/update comments for clarity and ensure naming matches other code conventions.
=> Clean up comments and names in FlView

impeller/renderer/backend/vulkan/command_buffer_vk.cc, impeller/renderer/backend/vulkan/command_buffer_vk.h, impeller/renderer/backend/vulkan/tracked_objects_vk.cc, impeller/renderer/backend/vulkan/tracked_objects_vk.h
issue: https://github.com/flutter/flutter/issues/157538
This removes multiple instances of copying std::shared_ptr and hashing. …
=> Faster vulkan buffer tracking

impeller/renderer/backend/vulkan/context_vk.cc, impeller/renderer/backend/vulkan/context_vk.h
Speculative fix for https://github.com/flutter/flutter/issues/157565 which looks like the kind of error that might happen if we concurrently mutate this hashmap.
=> [Impeller] Lock access to descriptor pool map.

shell/platform/darwin/ios/BUILD.gn, shell/platform/darwin/ios/framework/Source/FlutterViewController.mm, shell/platform/darwin/ios/framework/Source/FlutterViewController_Internal.h
Migrates `FlutterViewController` from manual reference counting to ARC. Eliminates use of scoped_nsobject and scoped_nsprotocol, and migrates ivars to property syntax where possible.
No semantic changes, therefore no changes to tests. …
=> Migrate FlutterViewController to ARC

impeller/renderer/backend/vulkan/command_buffer_vk.cc, impeller/renderer/backend/vulkan/command_buffer_vk.h, impeller/renderer/backend/vulkan/tracked_objects_vk.cc, impeller/renderer/backend/vulkan/tracked_objects_vk.h
By passing the shared_ptrs to TrackedObjectsVK by value, we will always require at least a decrement of the shared_ptr count, and possibly an increment too. 
Since for most cases the tracked object has already been tracked, passing by const ref results in no increment or decrement.
Ignoring the time value, since this is a flamegraph, we can see almost all time spent tracking is spent on shared_ptr decrement:
=> [Impeller] dont increment shared_ptr when tracked object is already tracked.

DEPS, ci/licenses_golden/excluded_files
Changes since last roll
```
3f1a1f0 Revert "For --time'd failed gn_run_binary.py runs repeat failed command (#910)" (#914)
e256f5c Remove github actions from buildroot (#913)
```
=> Roll buildroot to pick up revert of debugging gen_snapshot prints

shell/platform/darwin/common/BUILD.gn, shell/platform/darwin/common/buffer_conversions.mm, shell/platform/darwin/common/command_line.mm
Migrates //flutter/shell/platform/darwin/common` targets to ARC. Most of these were already ARC compatible.
This does add use of the `FLUTTER_ASSERT_ARC` define since that is defined in a public framework header, but this code has no dependency on the framework.
This removes `flutter_cflags_objc` and `flutter_cflags_objcc` compile configs from `availability_version_check_unittests` since that target is pure C++ and contains no Objective-C code.
No test changes since this there is no semantic change to the code. …
=> iOS/macOS: migrate darwin/common to ARC

impeller/playground/imgui/imgui_impl_impeller.cc, impeller/playground/playground.cc, impeller/renderer/backend/vulkan/render_pass_builder_vk.cc, impeller/renderer/backend/vulkan/render_pass_builder_vk.h, impeller/renderer/backend/vulkan/render_pass_builder_vk_unittests.cc, impeller/renderer/backend/vulkan/render_pass_vk.cc
Both changes were required to get playground tests validation free with moltenvk. becuase an initial state of undefined means "I don't care what was in this texture before" but that doesn't make sense if we're setting "kLoad" since that explicitly asks vulkan to load the previous contents.
Fixes https://github.com/flutter/flutter/issues/157557
=> [Impeller] fix initial layout for loadOp load and incorrect usage of host visible textures.

impeller/toolkit/android/shadow_realm.cc, impeller/toolkit/android/shadow_realm.h, impeller/toolkit/android/toolkit_android_unittests.cc
Uses `ro.product.first_api_level` to disable AHBs on devices that began life pre 29.
Fixes https://github.com/flutter/flutter/issues/157113
=> [Impeller] disable AHBs on devices that were upgraded to 29.

impeller/renderer/backend/vulkan/driver_info_vk.cc, impeller/renderer/backend/vulkan/driver_info_vk_unittests.cc
Fixes https://github.com/flutter/flutter/issues/156623
using info from https://vulkan.gpuinfo.org/displayreport.php?id=23730 . I dont believe these vulkan drivers are working correctly.
=> [Impeller] disable Maleoon GPU from using Vulkan.

lib/snapshot/BUILD.gn
'--time'-runs were done to investigate https://github.com/flutter/flutter/issues/154437, which was fixed.
=> Remove --time run of gen_snapshot.

impeller/toolkit/android/shadow_realm.cc, impeller/toolkit/android/shadow_realm.h, impeller/toolkit/android/toolkit_android_unittests.cc
Uses ro.product.first_api_level to disable AHBs on devices that began life pre 29.
Fixes https://github.com/flutter/flutter/issues/157113
=> [Impeller] Reland: disable AHBs on devices that were upgraded to 29.

lib/gpu/lib/src/buffer.dart, lib/gpu/lib/src/render_pass.dart, lib/gpu/render_pass.cc, testing/dart/gpu_test.dart
- Align HostBuffer emplacements properly (fix Metal validation failures).
- Correctly set the pipeline sample size.
- Throw an error when attempting to bind `deviceTransient` textures.
=> [Flutter GPU] Fix MSAA sample size and HostBuffer alignment.

DEPS, lib/web_ui/dev/roll_fallback_fonts.dart, lib/web_ui/lib/src/engine/font_fallback_data.dart, lib/web_ui/test/ui/fallback_fonts_golden_test.dart
Moves "split" font fallbacks (woff2) over "monolythic" ones (ttf) when resolving fonts.
Fixes https://github.com/flutter/flutter/issues/157763
It makes flutter web prefer "Noto Color Emoji" over "Noto Sans Symbols" when rendering emoji, for example.
This also changes the methods that process the font lists so they *return* the fonts they processed, instead of causing a side effect on an incoming array.
---
CIPD Upload log
```
398 sets covering 22287 ranges
Uploading fallback fonts to CIPD with hash 0570a0ea824083da79de07b131fc5df7f55dad4d6cba2ee704912ce7e4ce812a
Enumerating files to zip...
Instance: flutter/flutter_font_fallbacks:6jWhR90elvOjT1bwCe57CrNWbsGrvOzMONf9_bS8w5IC
Setting new fallback fonts deps version to 0570a0ea824083da79de07b131fc5df7f55dad4d6cba2ee704912ce7e4ce812a
```
Link …
=> [web] Prioritize split font fallbacks over monolythic ones.

DEPS, ci/licenses_golden/excluded_files
Changes since last roll:
```
3f1a1f0 Revert "For --time'd failed gn_run_binary.py runs repeat failed command (#910)" (#914)
e256f5c Remove github actions from buildroot (#913)
```
=> Roll buildroot to 3f1a1f0.

impeller/entity/geometry/circle_geometry.cc, impeller/entity/geometry/geometry.cc, impeller/entity/geometry/geometry.h, impeller/entity/geometry/line_geometry.cc, impeller/entity/geometry/line_geometry.h, impeller/entity/geometry/stroke_path_geometry.cc
Based on https://github.com/flutter/engine/pull/55230
Fixes https://github.com/flutter/flutter/issues/156438
=> [Impeller] Remove the use of a subpixel minimum stroke size for MSAA

shell/platform/darwin/ios/framework/Source/FlutterDartProject.mm, shell/platform/darwin/ios/framework/Source/FlutterEngine.mm, shell/platform/darwin/ios/framework/Source/FlutterEngineTest.mm
Leave an opt out in the engine for iOS as well. This will give developers an escape hatch in case there are problems we miss...
=> [engine] add back opt out for merged thread mode.

testing/scenario_app/ios/Scenarios/ScenariosTests/FlutterViewControllerTest.m
`FlutterViewControllerTest testDrawLayer` created a callback which strongly referenced itself in its own body as part of an asynchronous recursive loop. The recursion was unnecessary and the test consistently passes, even if run on repeat > 100 times without it.
Now that there's only one call, eliminates the unnecessary local and inlines it into the `dispatch_after` call.
This was originally introduced in https://github.com/flutter/engine/pull/50072. …
=> iOS: Eliminate strong retain loop in Scenario tests

impeller/entity/contents/content_context.cc, impeller/entity/contents/content_context.h, impeller/entity/geometry/circle_geometry.cc, impeller/entity/geometry/ellipse_geometry.cc, impeller/entity/geometry/fill_path_geometry.cc, impeller/entity/geometry/line_geometry.cc, impeller/entity/geometry/point_field_geometry.cc, impeller/entity/geometry/round_rect_geometry.cc, impeller/entity/geometry/stroke_path_geometry.cc
All geometries were incrementing the shared_ptr usage count which shows up in profiles. Instead expose a Tessellator reference like we do with HostBuffer.
=> [Impeller] expose reference to tessellator instead of shared_ptr.

tools/engine_tool/test/build_plan_test.dart
Part of https://github.com/flutter/flutter/issues/157870.
I figured I'd tackle a theme of tests at a time - easier for me to do in little spurts between other tasks.
=> Refactor `ArgParser.usage` tests for `BuildPlan` to reduce duplication.

testing/BUILD.gn, testing/test_metal_context.h, testing/test_metal_context.mm, testing/test_metal_surface_impl.mm
This migrates Flutter's TestMetalContext and TestMetalSurface to ARC.
Also migrates to using `sk_cfp::retain` (which retains the passed in pointer) rather than `sk_cfp::reset`, which only releases the previous pointer but doesn't retain the incoming pointer.
No changes to tests since no semantic changes. …
=> iOS: migrate Metal testing types to ARC

ci/builders/mac_unopt.json
The quiet flag filters out most of the script's output.  In particular, it excludes the output of child processes launched by the script.
=> Remove the quiet flag from invocations of run_tests.py on macOS CI builders

testing/run_tests.py
Users of this script typically expect that the normal output of the tests will be written to stdout.  However, the logging.StreamHandler writes to stderr by default unless another stream is specified.
=> Write run_tests console logs to stdout instead of stderr

ci/builders/linux_web_engine.json, lib/web_ui/test/felt_config.yaml
When dart2wasm was still in early stages and unstable, we wanted to run dart2wasm on as many unit tests and code paths as possible. However, dart2wasm is much more stable now, and there are some configurations that users simply cannot not use and are not worth testing. Specifically, users cannot use renderers other than skwasm with dart2wasm, so we should avoid running test suites specific to those renderers.
* `dart2wasm-html-html` and `dart2wasm-canvaskit-canvaskit` bundles and their associated suites are removed. These are tests specifically for the `html` and `canvaskit` renderers, which are run with those renderers. Users can't use these renderers in dart2wasm mode, so it's not useful to run these tests.
* `dart2wasm-html-ui` and `dart2wasm-canvaskit-ui` and their associated suites …
=> Remove superfluous dart2wasm test suites/bundles.

impeller/entity/contents/content_context.cc, impeller/entity/contents/filters/gaussian_blur_filter_contents.cc, impeller/entity/shaders/texture_downsample.frag, impeller/tools/malioc.json
Fixes https://github.com/flutter/flutter/issues/157956
Fixes https://github.com/flutter/flutter/issues/157959
Decal tile mode needs to be emulated on platforms that don't support it.
=> [Impeller] fix downsample with decal tile mode.

impeller/renderer/backend/gles/BUILD.gn, impeller/renderer/backend/gles/reactor_gles.cc, impeller/renderer/backend/gles/reactor_gles.h, impeller/renderer/backend/gles/test/reactor_unittests.cc, shell/platform/embedder/embedder_external_texture_gl.cc, shell/platform/embedder/embedder_external_texture_gl.h
Fixes https://github.com/flutter/flutter/issues/143809
=> [Impeller] implement external texture gl for embedder.

tools/engine_tool/BUILD.gn, tools/engine_tool/lib/src/build_plan.dart, tools/engine_tool/lib/src/build_utils.dart, tools/engine_tool/lib/src/commands/command_runner.dart, tools/engine_tool/test/build_plan_test.dart, tools/engine_tool/test/commands/build_command_test.dart
Closes https://github.com/flutter/flutter/issues/156591.
Closes https://github.com/flutter/flutter/issues/156355.
I also moved some functions only used as implementation details :)
=> Refactor `BuildPlan`, better document and explain `--config`.

ci/licenses_golden/excluded_files, impeller/core/shader_types.h, impeller/renderer/backend/vulkan/BUILD.gn, impeller/renderer/backend/vulkan/formats_vk.h, impeller/renderer/backend/vulkan/formats_vk_unittests.cc
This is a dumb performance optimization. because we only use the DescriptorType enum to represent vk descriptor types, lets just make the enum values match. Then we can static cast instead of switch.
I do see this function showing up in profiles, though a very small slice.
=> [Impeller] faster descriptor type mapping.

.ci.yaml
While we mitigate https://github.com/flutter/flutter/issues/157636.
=> Retry mac_unopt one time in presubmit

impeller/entity/entity.cc, impeller/geometry/matrix.h, impeller/geometry/matrix_unittests.cc
For each draw we do 4 matrix multiplications, which isn't slow but does show up in CPU profiles at a few % of a frame. We can cut the number of multiplications down to 3 by constructing the translate*scale matrix in one go. The translate * scale matrix construction is much simpler than a full multiplication as we can ignore all of the known zero values.
=> [Impeller] combine translate* scale mat mul when computing shader transform.

build_overrides/angle.gni, ci/licenses_golden/excluded_files, flutter_vma/include/README.md
fixes: https://github.com/flutter/flutter/issues/151353
Before this PR, angle would not build on linux, now it does.
example:
```
./flutter/bin/et build -c host_debug_unopt //flutter/third_party/angle:libGLESv2
```
There isn't a CI step that builds this today to verify it keeps working, I implemented this as part of the work to see if i could get the golden test runner working on linux. …
=> Made it so angle builds on linux

impeller/renderer/backend/vulkan/allocator_vk.cc, impeller/renderer/backend/vulkan/allocator_vk_unittests.cc, impeller/renderer/backend/vulkan/device_buffer_vk.cc, impeller/renderer/backend/vulkan/device_buffer_vk.h
Fixes https://github.com/flutter/flutter/issues/137454
Host coherent memory does not need to be flushed. Almost all mobile devices will have host coherent memory for us to write to, but we still need check because of swiftshader and/or desktop at some point.
=> [Impeller] check if memory type is host coherent, avoid flush.

impeller/renderer/backend/vulkan/allocator_vk_unittests.cc
This test is flakey despite using the mocked vulkan backend. This likely indicates that VMA is still performing some real initialization work in a way that is not consistently passing or failing.
It may not be safe to use VMA with mock vulkan.
=> remove mock vulkan memory test.

lib/ui/painting/image_decoder_impeller.cc, lib/ui/painting/image_decoder_unittests.cc
Cherry pick of https://github.com/flutter/engine/pull/55920
Issues: https://github.com/flutter/engine/pull/55928
=> [CP-beta] Fix memory leak during gif upload on Android/Impeller

shell/common/BUILD.gn, shell/common/shell_test_platform_view_metal.h, shell/common/shell_test_platform_view_metal.mm
Migrates DarwinContextMetal to a plain C struct, eliminating the need for constructor, getters, etc. since it's only used in this translation unit. The fields themselves cannot be inlined as fields on ShellTestPlatformViewMetal because the header in which that class is defined is included in plain C++ (non-Obj-C++) translation units and therefore cannot contain Obj-C types.
This simplifies the code and simultaneously fixes complicated ARC behaviour in which the const "DarwinContextMetal::context()" getter caused retainCount to be incremented on the underlying context_ pointer, but not decremented even if never unassigned. In particular the line
```objc
FML_CHECK([metal_context->context() mainContext]));
```
appeared to cause refcount to be incremented but never decremented.
Regardless of …
=> iOS: Refactor ShellTestPlatformViewMetal

impeller/entity/contents/content_context.cc, impeller/entity/contents/content_context.h, impeller/entity/entity_unittests.cc
The content context options hash function is pefect - meaning a distinct hash guarantees a distinct value and vice versa. We can replace the hashing entirely with an equality check of the hash function.
Additionally, we can remove the hashmap. As most of these maps have fewer than a dozen entries (often just 2 or 3) and the linear search is much faster.
=> [Impeller] exploit content context options' perfect hash function.

shell/platform/darwin/ios/framework/Source/FlutterEngine.mm, shell/platform/darwin/ios/framework/Source/FlutterEngineTest.mm
Remove the thread merging behavior on iOS for the 3.27 release branch as its not yet fully baked.
=> [CP] Disable thread merging for 3.27 release branch.

impeller/toolkit/android/shadow_realm.cc, impeller/toolkit/android/shadow_realm.h, impeller/toolkit/android/toolkit_android_unittests.cc
Uses `ro.product.first_api_level` to disable AHBs on devices that began life pre 29.
Fixes https://github.com/flutter/flutter/issues/157113
=> [CP][Impeller] disable AHBs on devices that were upgraded to 29. (#56202)

impeller/renderer/backend/vulkan/driver_info_vk.cc, impeller/renderer/backend/vulkan/driver_info_vk_unittests.cc
Fixes https://github.com/flutter/flutter/issues/156623
using info from https://vulkan.gpuinfo.org/displayreport.php?id=23730 . I dont believe these vulkan drivers are working correctly.
=> [CP][Impeller] disable Maleoon GPU from using Vulkan. (#56203)

impeller/renderer/backend/gles/reactor_gles.cc, impeller/renderer/backend/gles/test/mock_gles.cc, impeller/renderer/backend/gles/test/reactor_unittests.cc
At shutdown time the ReactorGLES may still be holding handles of GL objects.  These objects should be cleaned up when the reactor is deleted.
This leak can be seen by running DlGoldenTest.ShimmerTest, which takes a series of screenshots.  Each screenshot creates an AiksContext. Without this change, the textures in the AiksContext's ReactorGLES will be leaked after the AiksContext is destroyed.
=> [Impeller] Delete any remaining GL objects during destruction of the ReactorGLES

shell/platform/linux/fl_engine.cc, shell/platform/linux/fl_engine_private.h, shell/platform/linux/fl_engine_test.cc
This method simply wrapped a common method, which is simpler to use directly. The test only tested this common method, which already has tests in common/.
=> Remove unnecessary method for getting engine switches (command line).

shell/platform/darwin/ios/BUILD.gn, shell/platform/darwin/ios/framework/Source/FlutterTextInputPluginTest.mm, shell/platform/darwin/ios/framework/Source/FlutterUndoManagerPluginTest.mm
Previously, we had not enabled standard iOS cflags for `ios_test_flutter`, though ARC had been manually added to the cflags. This meant that the following flags were not enabled:
* -Werror=overriding-method-mismatch
* -Werror=undeclared-selector
Both of these existed in the code within this target:
* undeclared-selector: `insertionPointColor` was a non-public selector on UITextInput prior to iOS 17.
* overriding-method-mismatch: `FakeFlutterUndoManagerDelegate`, which implements the `FlutterUndoManagerDelegate` protocol, declared `initWithUndoManager:activeInputView:` with a different type for `activeInputView`. This was a hack to jam in a test mock object that didn't match the required type for the property. Conveniently we have a class (`FlutterTextInputView`) that implements the …
=> iOS: Use standard Obj-C cflags for ios_test_flutter

.ci.yaml
These builders have recently been timing out due to LUCI scheduling delays.
=> Increase timeouts for Linux Fuchsia and Linux Web Framework Tests builders

impeller/entity/BUILD.gn, impeller/entity/contents/content_context.cc, impeller/entity/contents/content_context.h, impeller/entity/contents/filters/gaussian_blur_filter_contents.cc, impeller/entity/shaders/downsample.glsl, impeller/entity/shaders/texture_downsample_gles.frag, impeller/tools/malioc.json
This fixes a crash reported on a moto g4 where the on device shader compiler fails to process the ifdef.
=> [Impeller] split downsample shader into GLES variant.

impeller/toolkit/interop/impeller.cc
Fixes https://github.com/flutter/flutter/issues/158285
=> [Impeller] Do not capture the temporary ImpellerMapping struct pointer when storing release callbacks in libImpeller

impeller/entity/entity_unittests.cc, impeller/entity/geometry/geometry_unittests.cc, impeller/entity/geometry/stroke_path_geometry.cc, impeller/entity/geometry/stroke_path_geometry.h, impeller/geometry/geometry_benchmarks.cc, impeller/renderer/renderer_unittests.cc, impeller/tessellator/tessellator.cc, impeller/tessellator/tessellator.h
Heap allocation is extremely expensive on Android.
We can speed up the stroke tessellation by allocation a large arena and using that to write vertices. If the vertices would overflow, we switch to a dynamically allocated vector.
=> [Impeller] generate stroke vertices into point arena.

impeller/playground/imgui/imgui_impl_impeller.cc, impeller/playground/imgui/imgui_impl_impeller.h, impeller/playground/playground.cc, impeller/playground/playground.h, testing/run_tests.py
Fixes https://github.com/flutter/flutter/issues/158275
We are now counting on the content context to keep the host buffer alive. the imgui overlay does not use a content context, so it has to manage the lifetime of the host buffer correctly, keeping it alive for as many frames as needed and destroying it in the correct order (before context destruction).
=> [Impeller] keep imgui hostbuffer alive.

impeller/renderer/backend/metal/render_pass_mtl.mm, impeller/renderer/backend/vulkan/render_pass_vk.cc, impeller/renderer/renderer_unittests.cc
Fixes https://github.com/flutter/flutter/issues/158074
binding a nullptr texture should fail but not crash.
=> [Impeller] make sure binding nullptr texture does not crash.

lib/web_ui/lib/src/engine.dart, lib/web_ui/lib/src/engine/semantics.dart, lib/web_ui/lib/src/engine/semantics/header.dart, lib/web_ui/lib/src/engine/semantics/heading.dart, lib/web_ui/lib/src/engine/semantics/semantics.dart, lib/web_ui/test/engine/semantics/semantics_test.dart
This relands the [reverted](https://github.com/flutter/engine/pull/55993) [original PR](https://github.com/flutter/engine/pull/55747) with one important adjustment: if the header is empty and has a label, it is rendered as a heading (`<h1>`, `<h2>`, etc) instead of a `<header>`. This is to be consistent with mobile, where headers are frequently used as headings, and screen readers do indeed read it as "heading". Changing all headers to the `<header>` tag turned to out to be too disruptive to existing usages of `SemanticsProperties.header`.
Long-term, when https://github.com/flutter/flutter/issues/155928 is implemented, we could migrate the framework to use `SemanticsProperties.headingLevel` to communicate that something is a heading, and encourage our users to move from `header` to …
=> [web:a11y] make header a <header> when non-empty and heading when empty

shell/platform/darwin/macos/BUILD.gn, shell/platform/darwin/macos/framework/Source/FlutterViewControllerTest.mm
Previously, in `mouseAndGestureEventsAreHandledSeparately:` we were using `CGEventRef cgEventStart` after it had been `CFRelease`d. Twice. This migrates to use fml::CFRef and avoids the issue altogether. …
=> macOS: Fix use after free in FlutterViewControllerTests

impeller/entity/contents/color_source_contents.h
Overdraw prevention prevents overlapping triangles in the stroke tessellator from being visible with partially opaque draws. For fully opaque draws (or usage of src blend mode) I do not believe this will be an issue - so we can disable this to speed things up a tiny bit.
This code runs after we covert opaque draws to src blend mode, so checking for src blend mode should be sufficient.
=> [Impeller] disable overdraw prevention for source draws.

lib/web_ui/skwasm/library_skwasm_multi_threaded.js
This change doesn't have unit tests, because it doesn't actually change the functional behavior of the renderer, it only changes its performance characteristics. If the transfer list is not included, the browser copies the image bitmaps instead of transfers them, which is slow, but does actually work. I am going to be adding some additional benchmarking in the framework to ensure that we detect if we regress something like this again.
=> [skwasm] Make sure to include the transfer list when using postMessage.

shell/platform/embedder/embedder.cc
Fixes https://github.com/flutter/flutter/issues/158000
=> In the embedder Impeller render target, use a multisample texture for the depth buffer only if MSAA is supported

shell/platform/darwin/macos/framework/Source/FlutterEngine.mm, shell/platform/embedder/embedder.h, shell/platform/embedder/embedder_task_runner.cc, shell/platform/embedder/embedder_task_runner.h, shell/platform/embedder/embedder_thread_host.cc, shell/platform/embedder/tests/embedder_unittests.cc, shell/platform/embedder/tests/embedder_unittests_util.h
Adds a `destruction_callback` member to `FlutterTaskRunnerDescription` that provides embedder developers a means of performing any cleanup of resources tied to the lifetime of the task runner.
In the case of the macOS embedder, the task runner holds a reference to the engine itself that is used in the `post_task_callback` and whose lifetime needs to match/exceed that of the task runner. This refactoring allows us to centralise all related retain count manipulation around task runner setup.
This is a refactor of the lifecycle bits of https://github.com/flutter/engine/pull/13300. …
=> Add FlutterTaskRunnerDescription.destruction_callback

tools/yapf.sh
The yapf Python formatter is abandoned and only works with Python versions up to and including Python 3.11. upgraded, this will become more and more problematic. On some Linux distributions side-by-side python installations are unsupported, for example.
Issue: https://github.com/flutter/flutter/issues/158384 …
=> yapf: Add more detailed error message and TODO

fml/platform/darwin/cf_utils.h, fml/platform/darwin/cf_utils_unittests.mm, impeller/golden_tests/BUILD.gn, impeller/golden_tests/metal_screenshot.h, impeller/golden_tests/metal_screenshot.mm, shell/platform/darwin/graphics/FlutterDarwinContextMetalSkia.mm, shell/platform/darwin/graphics/FlutterDarwinExternalTextureMetal.mm, shell/platform/darwin/ios/framework/Source/FlutterView.mm, shell/platform/darwin/macos/framework/Source/FlutterSurface.mm, shell/platform/darwin/macos/framework/Source/FlutterViewControllerTest.mm
Document where CFRef takes over or hands back ownership of the underlying CoreFoundation object memory.
Migrates manual CoreFoundation object management to CFRef in:
* impeller/golden_tests/metal_screenshot.mm
* shell/platform/darwin/graphics/FlutterDarwinContextMetalSkia.mm
* shell/platform/darwin/graphics/FlutterDarwinExternalTextureMetal.mm
* shell/platform/darwin/ios/framework/Source/FlutterView.mm
* shell/platform/darwin/macos/framework/Source/FlutterSurface.mm
Adds a `Retain()` method to take shared ownership of the underlying object, as opposed to Reset, where ownership is transferred to the CFRef wrapper.
Adds a `Get()` method to make dealing with bridged Objective-C casts more convenient:
```objc
fml::CFRef<CFStringRef> cfString(...);
NSString* aString = (__bridge …
```
=> fml: Use CFRef where possible and add docs

shell/platform/darwin/ios/framework/Source/platform_views_controller.mm
We need to track all previous platform views, even if some component of the hierarchy is missing.
=> [iOS] fix tracking of previous platform views.

shell/platform/linux/fl_application_test.cc
Fixes this compile error:
```
[211/451] CXX obj/flutter/shell/platform/linux/flutter_linux_unittests.fl_application_test.o
FAILED: obj/flutter/shell/platform/linux/flutter_linux_unittests.fl_application_test.o
../../flutter/buildtools/linux-arm64/clang/bin/clang++ -MMD -MFobj/flutter/shell/platform/linux/flutter_linux_unittests.fl_application_test.o.d -DFLUTTER_ENGINE_NO_PROTOTYPES -DFLUTTER_LINUX_COMPILATION -DUSE_OPENSSL=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_LIBCPP_DISABLE_AVAILABILITY=1 -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DSK_FONTMGR_ANDROID_AVAILABLE -DSK_TYPEFACE_FACTORY_FREETYPE …
```
=> [Linux] Replace deprecated macros in fl_application_test.cc

fml/platform/darwin/cf_utils.h, fml/platform/darwin/cf_utils_unittests.mm, impeller/golden_tests/metal_screenshot.h, shell/platform/darwin/ios/framework/Source/profiler_metrics_ios.mm
`fml::CFRef` implements the bulk of the operations implemented in the one-off `Scoped` class except with better safety guarantees such as `[[nodiscard]]` on the `Release` method. It doesn't implement the `handle()` method that allows direct writing into the internal storage of the wrapper, but that method is effectively an escape hatch for all the safety guarantees provided by the wrapper, so it seems safer to avoid adding it.
No changes to tests since this includes no semantic changes. …
=> iOS: Use fml::CFRef in place of Scoped

analysis_options.yaml
This rule was deleted from the Dart SDK.
See https://dart.googlesource.com/sdk/+/cb5c73e06fba5f9a795df532480e3d02028696bd
=> Remove the unsafe_html analysis rule

lib/ui/ui_dart_state.cc, lib/ui/ui_dart_state.h, runtime/runtime_controller.cc, runtime/runtime_controller.h, shell/common/engine.cc, shell/common/engine.h, shell/common/shell.cc, shell/common/shell.h, shell/testing/tester_main.cc
Flutter_tester has a task observer that checks whether the test's Dart code has finished execution.  If Dart no longer has live ports but does have pending microtasks, then flutter_tester should continue running and force a drain of the microtask queue.
Fixes https://github.com/flutter/flutter/issues/158129
=> Do not stop flutter_tester if microtasks are still pending

testing/test_metal_context.h, testing/test_metal_context.mm
`TestMetalContext` cannot include any Objective-C types in its header file since that header is included in pure C++ translation units. Previously, we declared these fields as `void*`, which then requires manual `__bridge_retained` and `__bridge_transfer` casts to perform the necessary retain/relase manipulation while opting the object in and out of ARC management.
Instead, we extract these to a struct in the implementation file and allow the fields to be managed by ARC. This is an interim measure consistent with the approach we've taken [elsewhere][1] until we implement the proper long-term solution.
The proper long-term solution is to refactor `EmbedderTest` (see: https://github.com/flutter/flutter/issues/157942) and other related code to split out backends into separate translation …
=> iOS,macOS: Refactor TestMetalContext for ARC

.github/dependabot.yml
`.github/dependabot.yml` configures dependabot to update the `uses` dependencies needed to run github actions.  
For example, dependabot opened https://github.com/flutter/engine/pull/56191 and updated all the `.github/workflows/` yaml files to point to the latest version of `actions/checkout`
Add a dependabot `group` so all github action dependencies are updated in the same PR, instead of one-per-dependency.  For example, if there were an update for `actions/checkout` and `actions/setup-python`, dependabot will send out one PR updating both instead of one PR per dependency.
https://github.com/flutter/engine/blob/35041f11874434233b98c095c591d85dd7772c5e/.github/workflows/third_party_scan.yml#L23-L28
New PRs from dependenabot will look like:
__________
__________
See also …
=> Add dependabot github-actions group

impeller/renderer/backend/gles/proc_table_gles.cc, impeller/renderer/backend/gles/proc_table_gles.h
* CheckFramebufferStatus needs to be called with the enum for the target type and not the target itself.
* Fix dumping the framebuffer type and object name.
The results should be the following for the default FBO0.
```
[IMPORTANT:flutter/impeller/renderer/backend/gles/render_pass_gles.cc(281)] The default framebuffer (FBO0) was bound.
```
and the following for an offscreen framebuffer:
```
[IMPORTANT:flutter/impeller/renderer/backend/gles/render_pass_gles.cc(281)] The default framebuffer (FBO0) was bound.
[IMPORTANT:flutter/impeller/renderer/backend/gles/render_pass_gles.cc(281)] FBO 1: GL_FRAMEBUFFER_COMPLETE
Framebuffer is complete.
Description: 
Color Attachment: GL_TEXTURE(5)
Depth Attachment: GL_RENDERBUFFER(1)
Stencil Attachment: GL_RENDERBUFFER(1)
```
cc @lyceel
=> [Impeller] Add OpenGL debugging utilities.

shell/platform/darwin/ios/framework/Source/SemanticsObject.mm, shell/platform/darwin/ios/framework/Source/SemanticsObjectTest.mm
iOS fix [[A11y] Double Tap brings the Slider thumb to the center of the widget.](https://github.com/flutter/flutter/issues/156427) per instruction from https://github.com/flutter/flutter/pull/157601#discussion_r1829992890
I don't have a physical iOS device to double check, but using the iOS Simulator and accessibility tools, the behavior seems ok. Without this PR, the slider thumb goes to the center when clicking 'Activate', with this PR it does not :
https://github.com/user-attachments/assets/697acadd-7fb1-40a5-ba5a-b549cac381a1
iOS fix for [[A11y] Double Tap brings the Slider thumb to the center of the widget.](https://github.com/flutter/flutter/issues/156427)
Adds 1 test.
=> [iOS] Fix slider semantics node answer to accessibility activate

lib/ui/painting/image_decoder_impeller.cc, lib/ui/painting/multi_frame_codec.cc
This preveents errors reported in some g3 test cases.
=> [Impeller] prevent no-op backend from throwing exceptions during image  decoding

shell/platform/darwin/macos/framework/Source/FlutterSurface.mm
In `[FlutterSurface asFlutterMetalTexture]` we return a `FlutterMetalTexture` whose `user_data` field holds a `void*` reference to the associated `FlutterSurface`.
For conistency with other parts of the codebase, this now uses ARC bridge casts to perform the additional retain and release of the associated surface rather than CoreFoundation functions `CFBridgingRetain` and `CFBridigingRelease`. In FlutterEngine, for example:
https://github.com/flutter/engine/blob/a672f971c65930f620c7542be58e15669372e16f/shell/platform/darwin/macos/framework/Source/FlutterEngine.mm#L648-L664
Also migrates the code to initialise and immediately return the struct using field designators, and reorders the assignments to be in the declaration order specified in embedder.h as required by the C++ spec.
No changes …
=> macOS: ARC bridge casts for FlutterMetalTexture.user_data

impeller/renderer/backend/gles/BUILD.gn, impeller/renderer/backend/gles/surface_gles.cc, impeller/renderer/backend/gles/test/surface_gles_unittests.cc, impeller/renderer/backend/gles/texture_gles.cc, impeller/renderer/backend/gles/texture_gles.h, impeller/toolkit/interop/impeller.cc, shell/platform/android/image_external_texture_gl_impeller.cc, shell/platform/android/surface_texture_external_texture_gl_impeller.cc, shell/platform/embedder/embedder.cc, shell/platform/embedder/embedder_external_texture_gl.cc
Previously, the FBO argument was dropped on the floor.
The API was also confusing as the Android subsystems were using the IsWrapped call to sidestep texture contents initialization without actually performing any wrapping.
Now, there are separate and documented calls to wrap a texture, wrap a framebuffer (as a texture), and to create a placeholder texture.
Callers can also mark any texture as being initialized out of band instead of depending on overloading the meaning of IsWrapped.
Fixes https://github.com/flutter/flutter/issues/158486
=> [Impeller] Wrap provided FBO instead of defaulting to FBO0 and cleanup/document the texture API.

shell/platform/embedder/BUILD.gn, shell/platform/embedder/tests/embedder_test.cc, shell/platform/embedder/tests/embedder_test.h, shell/platform/embedder/tests/embedder_test_gl.cc, shell/platform/embedder/tests/embedder_test_metal.mm, shell/platform/embedder/tests/embedder_test_vulkan.cc
Extracts creation of graphics backend specfic EmbedderTestContext creation to their own translation units. In particular, this allows for less conditional header includes, and more specifically, for code relating to the Metal backend to include headers that include Objective-C types -- today we cast these all to void* to avoid declaring them in headers, which requires special handling for ARC.
An alternative approach would have been to extract backend-specific subclasses, but there are test suites such as `EmbedderTestMultiBackend` that are executed against multiple backends, which make that approach impractical.
No test changes since this patch makes no semantic changes.
If you need help, consider asking for advice on the …
=> Embedder: Refactor EmbedderTestContext creation

impeller/toolkit/egl/config.h, shell/platform/android/android_context_gl_impeller.cc, shell/platform/android/android_context_gl_impeller_unittests.cc
Fixes https://github.com/flutter/flutter/issues/158531
Make sure the onscreen framebuffer has a depth attachment that matches the depth24_s8 format expected.
=> [Android] choose 24 bit depth buffer.

shell/platform/embedder/tests/embedder_test_context.h, shell/platform/embedder/tests/embedder_test_context_vulkan.h
In flutter/engine#29391 we extracted EmbedderTestContextVulkan, but didn't move the vulkan_context_ to that class. Since it's no longer used in the base class, we push it down to avoid the ifdef guards. …
=> Move Vulkan context to EmbedderTestContextVulkan

display_list/testing/BUILD.gn, display_list/testing/dl_test_surface_metal.mm, shell/platform/embedder/BUILD.gn, shell/platform/embedder/tests/embedder_test_compositor_metal.mm, shell/platform/embedder/tests/embedder_test_context_metal.mm, testing/BUILD.gn, testing/test_metal_surface.mm, testing/test_metal_surface_unittests.mm
Since Metal code frequently uses Objective-C types like id<MTLTexture> etc. this migrates Metal translation units to Obj-C++. In particular, this allows transitively including headers that include such types. This in turn helps with refactoring `EmbedderTest`, `TestMetalContext`, `TestMetalSurface` to avoid specifying `void*` types in headers and manually refcounting via ARC bridge casts.
Reformats the source, since Objective-C files are linted to 100 columns rather than the 80 column limit we impose on C++ files.
This change introduces no semantic changes.
[Tree …
=> Migrate Metal translation units to Obj-C++

shell/platform/embedder/BUILD.gn, shell/platform/embedder/tests/embedder_config_builder.cc, shell/platform/embedder/tests/embedder_config_builder.h, shell/platform/embedder/tests/embedder_config_builder_gl.cc, shell/platform/embedder/tests/embedder_config_builder_metal.mm, shell/platform/embedder/tests/embedder_config_builder_vulkan.cc, shell/platform/embedder/tests/embedder_test_context.cc, shell/platform/embedder/tests/embedder_test_context.h
Extracts backend-specific code in EmbedderConfigBuilder to separate translation units. In particular, this allows for less conditional header includes, and more specifically, for code relating to the Metal backend to include headers that include Objective-C types -- today we cast these all to void* to avoid declaring them in headers, which requires special handling for ARC.
An alternative approach would have been to extract backend-specific subclasses, but there are test suites such as EmbedderTestMultiBackend that are executed against multiple backends, which currently make that approach impractical, though that should likely be the long-term goal. …
=> Embedder: Refactor EmbedderConfigBuilder by backend

impeller/entity/contents/test/contents_test_helpers.cc, impeller/entity/contents/test/contents_test_helpers.h, impeller/entity/contents/test/recording_render_pass.cc, impeller/entity/contents/test/recording_render_pass.h
Minor change for clarity. I went looking for how we used the recording render pass since it was not in the testing namespace.
=> [Impeller] Put test components in the testing namespace.

impeller/renderer/backend/gles/context_gles.cc, impeller/renderer/backend/gles/context_gles.h, impeller/renderer/backend/gles/render_pass_gles.cc, impeller/renderer/backend/gles/render_pass_gles.h, impeller/renderer/context.cc, impeller/renderer/context.h, impeller/toolkit/interop/impeller_unittests.cc, impeller/toolkit/interop/surface.cc
Impeller is resilient to OpenGL state being trampled upon when accessing the GL context. But the embedder may not necessarily be. Ideally, we'd be using saving the state and restoring it. But that might be too involved. For now, this sets the GL state to a sane "clean" state.
We could, in theory, do this after each render pass but that unnecessarily increases API traffic. For now, I have added it at the transition of the embedder boundary.
=> [Impeller] libImpeller: Reset the GL state when transitioning control back to the embedder.

impeller/renderer/backend/gles/description_gles.cc
All it does it log the calls and overwhelms the output for no utility.
=> [Impeller] Don't enable KHR_debug on Angle.

impeller/renderer/backend/gles/command_buffer_gles.cc, impeller/renderer/backend/gles/command_buffer_gles.h, impeller/renderer/backend/gles/proc_table_gles.h, impeller/renderer/backend/gles/reactor_gles.cc, impeller/renderer/backend/gles/reactor_gles.h, impeller/renderer/backend/gles/test/reactor_unittests.cc, impeller/renderer/backend/metal/command_buffer_mtl.h, impeller/renderer/backend/metal/command_buffer_mtl.mm, impeller/renderer/backend/vulkan/command_buffer_vk.cc, impeller/renderer/backend/vulkan/command_buffer_vk.h, impeller/renderer/command_buffer.cc, impeller/renderer/command_buffer.h, impeller/renderer/testing/mocks.h, lib/ui/painting/image_decoder_impeller.cc
Threads that add operations to the ReactorGLES assume that those operations will be executed serially.
But prior to this change, the ReactorGLES added all operations into one queue.  The reactor would then execute those operations on any thread that can react. This could cause operations that were added to the reactor on the raster thread to be submitted to the GPU on the IO thread (or vice versa).
The reactor does not wait for the GPU to finish execution of those operations.  So other operations added on the raster thread could be submitted by a reaction before the GPU has completed the operation that was submitted on the IO thread.
This PR ensures that operations added to the reactor on a given thread will be executed during a reaction on that same thread.  If the thread can not …
=> [Impeller] Maintain separate queues of GLES operations for each thread in the reactor

impeller/renderer/backend/gles/proc_table_gles.cc, impeller/renderer/backend/gles/proc_table_gles.h
This assert would have blocked the following bug: https://github.com/flutter/flutter/issues/158535
This shouldn't be landed until https://github.com/flutter/engine/pull/56573 lands.
[CLA]: …
=> Added assert for opengles thread safety

shell/platform/fuchsia/flutter/flatland_connection.cc, shell/platform/fuchsia/flutter/flatland_connection.h
Currently, flutter keeps calling MaybeRunInitialVsyncCallback() until 1 OnNextFrameBegin() called from Fuchsia which maybe problem when display is off.
Tested manually.
Bug: http://fxbug.dev/376079469
=> [fuchsia] MaybeRunInitialVsyncCallback should only called once

shell/platform/darwin/macos/framework/Source/FlutterChannelKeyResponder.mm
If we disable the NSAssert during release mode, this code will continue after NSAssert failure, which will then pass a `nil` value into a dictionary (which cannot have a nil value), hence the clang-tidy warning here https://github.com/flutter/engine/pull/53005#issuecomment-2140975126
https://github.com/flutter/flutter/issues/148279
https://github.com/flutter/flutter/issues/157837 …
=> [macos] early return to suppress clang-tidy warning

lib/web_ui/lib/src/engine/platform_dispatcher.dart, lib/web_ui/lib/src/engine/pointer_binding.dart, lib/web_ui/lib/src/engine/semantics/focusable.dart, lib/web_ui/lib/src/engine/semantics/incrementable.dart, lib/web_ui/lib/src/engine/semantics/scrollable.dart, lib/web_ui/lib/src/engine/semantics/semantics.dart, lib/web_ui/lib/src/engine/semantics/tappable.dart, lib/web_ui/lib/src/engine/semantics/text_field.dart, lib/web_ui/lib/src/engine/window.dart, lib/web_ui/test/engine/pointer_binding_test.dart, lib/web_ui/test/engine/window_test.dart
Currently, all semantics actions that we send to the framework contain `viewId: 0`. This leads to issues such as https://github.com/flutter/flutter/issues/158530 because the framework routes the pointer event to the wrong view.
Let's send the correct view ID with semantics actions.
Fixes https://github.com/flutter/flutter/issues/158530
=> [web] Send the correct view ID with semantics actions

shell/platform/android/io/flutter/embedding/engine/systemchannels/TextInputChannel.java, shell/platform/android/io/flutter/plugin/editing/TextInputPlugin.java, shell/platform/android/test/io/flutter/plugin/editing/TextInputPluginTest.java, shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm, shell/platform/darwin/ios/framework/Source/FlutterTextInputPluginTest.mm
This PR adds the engine part to add `TextInputType.webSearch` that allows to show a keyboard with ready access to a "." key on iOS. On Android this is re-mapped to `url` which shows the same behaviour as `webSearch` on iOS. This fixes issue https://github.com/flutter/flutter/issues/157562.
The flutter PR: https://github.com/flutter/flutter/pull/158323
=> [TextInput] Add TextInputType.webSearch (#15762)

shell/platform/embedder/tests/embedder_config_builder.cc, shell/platform/embedder/tests/embedder_test_compositor.cc, shell/platform/embedder/tests/embedder_test_compositor.h, shell/platform/embedder/tests/embedder_test_compositor_gl.cc, shell/platform/embedder/tests/embedder_test_compositor_gl.h, shell/platform/embedder/tests/embedder_test_compositor_metal.h, shell/platform/embedder/tests/embedder_test_compositor_metal.mm, shell/platform/embedder/tests/embedder_test_compositor_software.cc, shell/platform/embedder/tests/embedder_test_compositor_software.h, shell/platform/embedder/tests/embedder_test_compositor_vulkan.cc, shell/platform/embedder/tests/embedder_test_compositor_vulkan.h, shell/platform/embedder/tests/embedder_test_context.cc, shell/platform/embedder/tests/embedder_test_context_gl.cc
SetRenderTargetType is used to configure the backingstore producer on the compositor, but the backingstore types available to any given compositor are limited to the specific graphics backend in use: Software, GL, Metal, or Vulkan.
This moves SetRenderTargetType to EmbedderTestCompositor and its subclasses and adds RenderTargetType validation. A follow-up patch will refactor EmbedderTestBackingStoreProducer into backend-specific subclasses.
For OpenGL backingstore producers, the egl_context_ from EmbedderTestContext (which is actually set in the EmbedderTestContextGL subclass and should live there, but that's a separate cleanup) is required in SetRenderTargetType, so we now inject it into EmbedderTestCompositor in the constructor so it's available when needed.
Issue: …
=> Move SetRenderTargetType to EmbedderTestCompositor

ci/builders/linux_android_debug_engine.json, ci/builders/linux_unopt.json, docs/JIT-Release-Modes.md
Reverts flutter/engine#56548
Failing roll to the framework, the tool is still looking for these artifacts.
=> Revert "Remove `android_jit_release_x86`."

shell/platform/darwin/ios/framework/Source/FlutterTextInputPluginTest.mm
Spot another clang-tidy linter failure from: https://github.com/flutter/engine/pull/56631
In release mode, if we remove NSAssert, then weakFlutterEngine is not used at all. This should have been an XCTAssert rather than NSAssert in the first place. 
```
❌ Failures for clang-tidy on /Volumes/Work/s/w/ir/cache/builder/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterTextInputPluginTest.mm:
/Volumes/Work/s/w/ir/cache/builder/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterTextInputPluginTest.mm:239:5: error: Value stored to 'weakFlutterEngine' is never read [clang-analyzer-deadcode.DeadStores,-warnings-as-errors]
239 |     weakFlutterEngine = flutterEngine;
|     ^                   ~~~~~~~~~~~~~
/Volumes/Work/s/w/ir/cache/builder/src/flutter/shell/platform/darwin/i …
```
=> [ios]fix unused variable clang tidy warning

shell/platform/darwin/ios/framework/Source/FlutterEngine.mm, shell/platform/darwin/ios/framework/Source/FlutterEngineGroup.mm, shell/platform/darwin/ios/framework/Source/FlutterEngineGroupTest.mm, shell/platform/darwin/ios/framework/Source/FlutterEngineTest.mm, shell/platform/darwin/ios/framework/Source/FlutterEngine_Internal.h, shell/platform/darwin/ios/framework/Source/FlutterEngine_Test.h
FlutterEngineGroup keeps an array of all live FlutterEngine instances it has created such that after the first engine, it can spawn further engines using the first.
Previously we manually managed this array by adding engines to it upon creation, then having [FlutterEngine dealloc] emit a notification such that FlutterEngineGroup can listen for it, and remove instances from the array upon reception of the notification.
Instead, we now use an NSPointerArray of of weak pointers such that pointers are automatically nilled out by ARC after the last strong reference is collected. This eliminates the need for the manual notification during dealloc.
Unfortunately, NSPointerArray is "clever" and assumes that if the array has not been mutated to store a nil pointer since its last compact call, it …
=> iOS: Eliminate FlutterEngine dealloc notification

shell/platform/darwin/ios/framework/Source/FlutterMetalLayer.mm, shell/platform/darwin/ios/framework/Source/IOKit.h, shell/platform/darwin/macos/framework/Source/FlutterSurface.mm
Three changes related to string constants:
1. Uses the kIOSurfaceColorSpace constant, which is a CFStringRef pointing to the string "IOSurfaceColorSpace"
2. Uses the kCVPixelFormatType_32BGRA enum value from the CoreVideo headers (which is equal to 'BGRA') in place of hardcoding the string.
From the headers:
```
kCVPixelFormatType_32BGRA         = 'BGRA',     /* 32 bit BGRA */
```
3. Declares kIOServicePlane as a `constexpr const char*` rather than `static const char*`, this ensures only a single instance is created, rather than one per translation unit into which the header is included. This string is part of IOKit, but see the comment at the top of the header as to why it's apparently needed.
No test changes since there are no semantic changes.
If you need help, consider asking for …
=> iOS: Clean up uses of string literal constants

shell/platform/darwin/ios/framework/Headers/FlutterViewController.h, shell/platform/darwin/ios/framework/Source/FlutterViewController.mm
Previously, FlutterViewController.engine was declared as a weak readonly property, but we explicitly declared the `FlutterEngine* _engine` ivar as a strong reference in the implementation. This changes the property declaration to be strong and eliminates the now unnecessary ivar.
There is also no semantic change to FlutterViewController itself, since the `_engine` ivar had been manually declared as a strong reference.
There is no semantic change for users of FlutterViewController.engine since whether a user acquires a strong or weak reference to the engine is determined by whether they declare the pointer to which they assign it as strong or weak.
This also eliminates the need for the `engine` getter, which was only present to prevent a warning that the strong ivar didn't match the weak …
=> iOS: Make FlutterViewController.engine a strong ref

shell/platform/darwin/graphics/FlutterDarwinExternalTextureMetal.mm
This replaces a few ARC bridged retain casts to regular bridge casts to CoreFoundation types, which are then CFRetained via `sk_cfp::retain` calls.
This eliminates the last remaining unnecessary __bridge_retained casts in the codebase. The remaining casts have been manually vetted and are reasonable.
Issue: https://github.com/flutter/flutter/issues/155943 …
=> iOS: Eliminate unnecessary bridged retain casts

shell/platform/darwin/ios/framework/Source/FlutterOverlayView.mm, shell/platform/darwin/ios/framework/Source/FlutterPlatformViewsTest.mm, shell/platform/darwin/ios/framework/Source/FlutterPlatformViews_Internal.h, shell/platform/darwin/ios/framework/Source/FlutterPlatformViews_Internal.mm, shell/platform/darwin/ios/framework/Source/FlutterView.mm, shell/platform/darwin/ios/framework/Source/FlutterViewTest.mm
When performing `isKindOfClass` checks, we were occasionally looking up the class in question using `NSClassFromString()`, instead we now check against the class directly, which has the added benefit of being type-safe, and not succeptible to string typos.
Moves the declaration of ForwardingGestureRecognizer and FlutterDelayingGestureRecognizer to the FlutterPlatfomViews_Internal.h header, which is non-public. …
=> iOS: Eliminate unnecessary use of NSClassFromString

shell/platform/darwin/ios/framework/Source/FlutterViewControllerTest.mm, shell/platform/darwin/ios/framework/Source/VsyncWaiterIosTest.mm, shell/platform/darwin/ios/framework/Source/vsync_waiter_ios.h, shell/platform/darwin/ios/framework/Source/vsync_waiter_ios.mm
In our vsync waiter and related tests, we hardcode the "CADisableMinimumFrameDurationOnPhone" key in several places. This pulls those into a constant kCADisableMinimumFrameDurationOnPhoneKey declared in the vsync waiter header, which is non-public, and uses that instead.
[testing the …
=> iOS: Extract constant for CADisableMinimumFrameDurationOnPhone

shell/platform/darwin/ios/framework/Source/FlutterMetalLayer.h, shell/platform/darwin/ios/framework/Source/FlutterMetalLayer.mm, shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm, shell/platform/darwin/ios/framework/Source/FlutterViewController.mm, shell/platform/darwin/ios/framework/Source/FlutterViewControllerTest.mm, shell/platform/darwin/ios/framework/Source/TextInputSemanticsObject.mm, shell/platform/darwin/macos/framework/Source/FlutterChannelKeyResponder.mm, shell/platform/darwin/macos/framework/Source/FlutterEmbedderKeyResponder.mm, shell/platform/darwin/macos/framework/Source/FlutterMenuPluginTest.mm, shell/platform/darwin/macos/framework/Source/FlutterThreadSynchronizerTest.mm, shell/platform/darwin/macos/framework/Source/FlutterVSyncWaiterTest.mm, shell/platform/darwin/macos/framework/Source/FlutterViewController.mm
In modern Objective-C, `@property` directives automatically generate a backing ivar (property name prefixed with an underscore), the getter, and (for readwrite properties) the setter. `@synthesize` directives are generally only required if the backing ivar has a different name from the property.
Also updates the FlutterMetalLayer API to match CAMetalLayer:
* Adds API_AVAILABLE declaration to match that on CAMetalLayer.
* Eliminates wantsExtendedDynamicRangeContent property as it's also part of CALayer's interface and unused in our implementation.
Also eliminates unnecessary ivars where they're being synthesized by `@property` declarations.
Previously, we were overriding the behaviour of
UIViewController.prefersStatusBarHidden by synthesizing _flutterPrefersStatusBarHidden as a backing …
=> iOS: Clean up @synthesize directives / ivars

skia/BUILD.gn
In https://skia-review.googlesource.com/c/skia/+/884096, Skia broke up this gni file list into Ganesh and Graphite specific code. Since Flutter only needs Ganesh sources, this can be made more precise.
- [ x ] I added new tests to check the change I am making or feature I am adding, or the PR is [test-exempt]. See [testing the engine] for instructions on writing and running engine tests.
- [ x ] I updated/added relevant documentation (doc comments with `///`).
- [ x ] All existing and …
=> Use updated gni source list

impeller/renderer/backend/gles/proc_table_gles.cc
test: exists in https://github.com/flutter/engine/pull/56596
fixes: https://github.com/flutter/flutter/issues/158995 …
=> Started only loading gles3 functions if we have a gles3 context

shell/platform/embedder/tests/embedder_test_backingstore_producer.h, shell/platform/embedder/tests/embedder_test_backingstore_producer_gl.cc, shell/platform/embedder/tests/embedder_test_backingstore_producer_gl.h, shell/platform/embedder/tests/embedder_test_backingstore_producer_metal.h, shell/platform/embedder/tests/embedder_test_backingstore_producer_metal.mm, shell/platform/embedder/tests/embedder_test_backingstore_producer_software.cc, shell/platform/embedder/tests/embedder_test_backingstore_producer_software.h, shell/platform/embedder/tests/embedder_test_backingstore_producer_vulkan.cc, shell/platform/embedder/tests/embedder_test_backingstore_producer_vulkan.h, shell/platform/embedder/tests/embedder_test_compositor.cc, shell/platform/embedder/tests/embedder_test_compositor.h, shell/platform/embedder/tests/embedder_test_compositor_gl.cc, shell/platform/embedder/tests/embedder_test_compositor_software.cc, shell/platform/embedder/tests/embedder_test_compositor_vulkan.cc, shell/platform/embedder/tests/embedder_unittests.cc
Replace the top-level public EmbedderBackingStoreProducer::UserData struct with backend-specific UserData classes, and make them internal to those backends. UserData internals shouldn't be visible to/manipulated by unit tests and compositors, but instead constrained to the backing store producer itself. …
=> EmbedderTest: Extract backend-specific user_data

common/config.gni, fml/BUILD.gn, impeller/tools/component.gni, shell/common/BUILD.gn, shell/gpu/BUILD.gn, shell/platform/darwin/common/BUILD.gn, shell/platform/darwin/graphics/BUILD.gn, shell/platform/darwin/ios/BUILD.gn, shell/platform/darwin/macos/BUILD.gn, shell/platform/embedder/BUILD.gn, testing/BUILD.gn, third_party/accessibility/BUILD.gn, third_party/accessibility/ax/BUILD.gn, third_party/accessibility/gfx/BUILD.gn
Enables the `-fobjc-arc` compiler flag for Objective-C and Objective-C++ translation units.
Eliminates the flutter_cflags_objc[c]_arc settings, since they're now redundant.
All Obj-C/Obj-C++ code in our codebase has now been migrated to ARC. …
=> iOS,macOS: Enable ARC in flutter_cflags_objc[c]

skia/BUILD.gn
Skia is reorganizing some font managers, and the Flutter engine's build scripts need to match the changes made to Skia.
See https://skia-review.googlesource.com/c/skia/+/915316
=> Update the Skia build scripts for a refactoring of the Fontconfig font manager

shell/platform/embedder/tests/embedder_test_backingstore_producer_gl.h, shell/platform/embedder/tests/embedder_test_compositor_gl.h, shell/platform/embedder/tests/embedder_test_context_gl.h, testing/BUILD.gn, testing/test_gl_context.cc, testing/test_gl_context.h, testing/test_gl_surface.cc, testing/test_gl_surface.h, testing/test_gl_utils.cc, testing/test_gl_utils.h
For consistency with the Test.*Context classes for other backends, which live in their own implementation file with their own header, extract TestEGLContext to its own header and TU so that in cases where only a TestEGLContext is required (e.g. EmbedderTestBackingStoreProducerGL), we don't need to include all the various test GL surface classes as well.
GetEGLError is used by both TestEGLContext and the TestGLSurface classes, so moves to its own utils file.
No tests because this is a refactoring with no semantic changes, and the code itself is test code.
[Tree …
=> Extract TestGLContext to separate translation unit

lib/web_ui/lib/src/engine/skwasm/skwasm_impl/codecs.dart, lib/web_ui/test/ui/image_golden_test.dart
This addresses https://github.com/flutter/flutter/issues/159088
If the image is rotated in its exif data, the coded width/height may differ from the display width/height. It's important to use the display width/height so that `texImage2D` does the right thing with the `VideoFrame`.
=> [skwasm] Use `displayWidth`/`displayHeight` instead of `codedWidth`/`codedHeight`

shell/platform/darwin/ios/BUILD.gn
Eliminates the opt-out of `-Wunguarded-availability-new` in the `ios_test_flutter` target.
Xcode 15 beta XCTest framework headers contained unguarded usage of iOS 17 API. This bug resulted in engine build failures.
This was fixed in a later XCTest framework release.
```
/Applications/Xcode_15-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/Frameworks/XCTest.framework/Headers/XCUIAccessibilityAuditTypes.h:19:30: error: 'XCUIAccessibilityAuditType' is only available on iOS 17.0 or newer [-Werror,-Wunguarded-availability-new]
19 | typedef NS_OPTIONS(uint64_t, XCUIAccessibilityAuditType) {
|                              ^
/Applications/Xcode_15-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/Frameworks/XCTest.framework/Headers/X …
```
=> iOS: Eliminate unguarded-availability opt-out

shell/platform/embedder/tests/embedder_test_backingstore_producer.h, shell/platform/embedder/tests/embedder_test_context_gl.h
Eliminates an unused ifdef'ed include in embedder_test_backingstore_producer.h and adds it to embedder_test_context_gl.h, where it's needed. The need for this include was eliminated in https://github.com/flutter/engine/pull/56638.
No test changes since the patch introduces no semantic changes. …
=> EmbedderTest: Eliminate unused include

display_list/testing/BUILD.gn, display_list/testing/dl_test_surface_provider.cc, display_list/testing/dl_test_surface_provider.h, display_list/testing/dl_test_surface_provider_gl.cc, display_list/testing/dl_test_surface_provider_metal.mm, display_list/testing/dl_test_surface_provider_software.cc
Extracts backend-specific code in DlSurfaceProvider to separate translation units. In particular, this allows for less conditional header includes, and more specifically, allows code relating to the Metal backend to include headers that include ARC-managed Objective-C types. Today we cast these all to void* (and manage refcounting manually) since these headers are included in dl_surface_provider.cc, which is a pure C++ translation unit.
No test changes since this patch includes no semantic changes. …
=> display_list: Extract backend-specific surface providers

shell/platform/embedder/tests/embedder_a11y_unittests.cc, shell/platform/embedder/tests/embedder_gl_unittests.cc, shell/platform/embedder/tests/embedder_metal_unittests.mm, shell/platform/embedder/tests/embedder_test.cc, shell/platform/embedder/tests/embedder_test.h, shell/platform/embedder/tests/embedder_test_gl.cc, shell/platform/embedder/tests/embedder_test_metal.mm, shell/platform/embedder/tests/embedder_test_vulkan.cc, shell/platform/embedder/tests/embedder_unittests.cc, shell/platform/embedder/tests/embedder_vk_unittests.cc
In many embedder tests, we want to get at the appropriate backend-specific `EmbedderTestContext` subclass (`EmbedderTestContextGL`, etc.) in order to make backend-specific setup calls such as `SetGLFBOCallback()` or others. Formerly, this required casting the returned `EmbedderTestContext&` to the appropriate subclass in each test.
This templatises the `GetEmbedderContext()` method to return the appropriate backend-specific subclass directly.
[test-exempt]: …
=> EmbedderTest: templatise GetEmbedderContext

impeller/renderer/backend/gles/context_gles.cc, impeller/renderer/backend/gles/context_gles.h, impeller/renderer/backend/gles/reactor_gles.cc, impeller/renderer/backend/gles/reactor_gles.h, impeller/renderer/backend/gles/render_pass_gles.cc, impeller/renderer/backend/gles/test/reactor_unittests.cc
Locally this gives much better performance, about doubling frame time on the Pixel 4. This avoids multiple glbuffersubdata calls that seems to perform particularly bad on mobile devices.
Thinking about it more, I'm not sure that having a separate EncodeCommands API is useful for RenderPass/BlitPass. instead they should probably just use submit. but that is a refactor for another day.
https://github.com/flutter/flutter/issues/159177
=> [Impeller] flush all GLES cmd buffers together.

ci/builders/local_engine.json
Closes: https://github.com/flutter/flutter/issues/156598
=> [et] Add Android x64 configurations

impeller/renderer/backend/gles/proc_table_gles.cc, impeller/renderer/backend/gles/proc_table_gles.h
This reverts commit 79fe6b466041648b2241a6fc17af406c3ab10226.
The implementation of the assert assumes that there is a single raster thread ID that will remain constant throughout the lifetime of the process.  That is not true for scenarios like recreating the engine after suspending and resuming an Android app, or instantiating multiple engines within one process.
=> Revert "Added assert for opengles thread safety (#56585)"

impeller/entity/entity_unittests.cc
Fixes https://github.com/flutter/flutter/issues/159213
I've went through all `static` in the file and removed the ones that I think are incorrect.
I've experimented with all entity playgrounds to make sure their controllers work, except for `BlendingModeOptions`, which doesn't change whatsoever and I can't figure out.
This PR should not need tests, as it fixes the tests. …
=> Fix: Impeller playground's shapes should react to controllers

lib/web_ui/lib/src/engine/pointer_binding.dart, lib/web_ui/lib/src/engine/pointer_binding/event_position_helper.dart, lib/web_ui/test/engine/pointer_binding_test.dart
In iOS 18.2, Safari [added support](https://developer.apple.com/documentation/safari-release-notes/safari-18_2-release-notes#Web-API) for the [`getCoalescedEvents`](https://developer.mozilla.org/en-US/docs/Web/API/PointerEvent/getCoalescedEvents) API.
That being said, the API seems to be incomplete (or at least doesn't match other browsers' behavior). The coalesced events lack a [`pointerId`](https://developer.mozilla.org/en-US/docs/Web/API/PointerEvent/pointerId) and [`target`](https://developer.mozilla.org/en-US/docs/Web/API/Event/target) properties.
I'm not sure if this issue will be fixed in the stable release of iOS 18.2, so in the meantime, this PR implements a workaround to avoid this issue.
Fixes https://github.com/flutter/flutter/issues/158299
Fixes …
=> [web] Work around wrong pointerId in coalesced events in iOS Safari 18.2

shell/platform/darwin/ios/framework/Source/FlutterEngineTest.mm, shell/platform/darwin/ios/ios_context.mm, testing/ios/IosUnitTests/App/Info.plist
The Info.plist override was missed earlier.
The main changes to the tests are due to the UI thread merge with the platform thread. The amendment to the "spawn" API are due to the fact that the assertions checked for the presence of GrDirectContext which will never exist with Impeller.
Unblocks https://github.com/flutter/engine/pull/56706
=> [Impeller] Run simulator tests with Impeller enabled.

impeller/toolkit/interop/BUILD.gn, impeller/toolkit/interop/impeller.hpp, impeller/toolkit/interop/impeller_cc.cc, impeller/toolkit/interop/impeller_unittests.cc, impeller/toolkit/interop/playground_test.cc
_`impeller.hpp` is to `impeller.h` what `vulkan.hpp` is to `vulkan.h`_
* A single header C++ 17 library that only depends on impeller.h and standard libc++ utilities.
* The C++ library proc. table is setup at runtime (via dlsym and related methods). Impeller users don't need to link against libimpeller.so as long as they can discover it at runtime.
* RAII wrappers for all opaque objects.
* Namespaces are configurable depending on target.
* Included in the distributed SDK next to impeller.h.
=> [Impeller] libImpeller: A C++ wrapper to the Impeller API.

shell/common/animator_unittests.cc, shell/common/shell_test_platform_view.cc, shell/common/shell_test_platform_view.h, shell/common/shell_unittests.cc
`kDefaultBackendType` is intended to make life easier for authors of tests, but in any switch statement where it's used (currently just a single location), we rely on ordering it first and `#ifdef`ing out all backends that aren't available.
Instead, we define a static function that returns the default that callers can invoke instead. This avoids reliance on case ordering and fallthrough.
In https://github.com/flutter/engine/pull/56722 we split backends out into separate translation units, and should remove the `#ifdef`s, which means we can't rely on this trick anymore. …
=> Eliminate ShellTestPlatformView::BackendType::kDefaultBackendType

shell/common/shell_test_platform_view.cc, shell/common/shell_test_platform_view.h, shell/common/shell_test_platform_view_gl.cc, shell/common/shell_test_platform_view_metal.h, shell/common/shell_test_platform_view_metal.mm, shell/common/shell_test_platform_view_vulkan.cc, shell/common/shell_test_platform_view_vulkan.h
Moves code specific to each graphics backend into the (existing) translation unit associated with that backend.
Previously, we could not include any Objective-C types in `shell_test_platform_view_metal.h`, since that file was included into `shell_test_platform_view.cc`, which is pure C++. To work around this, we had encapsulated Objective-C Metal types in a `DarwinContextMetal` struct hidden in the implementation file with a pointer to it forward-declared in the header.
We now use Metal types directly in the header, without the workarounds. …
=> Extract backend-specific code in ShellTestPlatformView

impeller/renderer/backend/gles/render_pass_gles.cc, impeller/renderer/backend/gles/texture_gles.cc, impeller/renderer/backend/gles/texture_gles.h
Creating and attaching textures/render buffers to a FBO is an expensive operation. Similar to how we cache vulkan framebuffers/render passes, we can cache the FBO object on the color0 texture to avoid extra state invalidation.
Part of https://github.com/flutter/flutter/issues/159177
=> [Impeller] cache and reuse openGL framebuffer attachments.

impeller/renderer/backend/gles/render_pass_gles.cc
This can have at most 3 entries so just use an array to avoid heap allocation.
=> [Impeller] dont create temp vec for discard.

impeller/toolkit/interop/README.md
Also adds references to the C++ wrapper and examples.
=> [Impeller] libImpeller: Tinker on the README.

shell/common/snapshot_controller_impeller.cc, shell/platform/android/android_surface_gl_impeller.cc, shell/platform/embedder/fixtures/main.dart, shell/platform/embedder/tests/embedder_gl_unittests.cc
The Skia snapshot controller will activate the delegate's surface render context on the current thread.  If the delegate has no surface, then it will use the snapshot surface producer to create a temporary surface.
The Impeller snapshot controller needs to do the same in order to support OpenGL/GLES scenarios where the thread does not currently have an EGL context.
=> [Impeller] Ensure that SnapshotControllerImpeller has a rendering context before creating the snapshot

shell/platform/darwin/ios/framework/Source/FlutterPlatformViewsTest.mm
Ran into this typo during a separate refactoring. Breaking it out to avoid an already large patch getting any bigger.
If you need hilp, consadder asking for avduice on the #hackers-new channel on [Discord].
[Contibutor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview …
=> iOS: Fix typo in fluttterViewController

impeller/renderer/backend/gles/reactor_gles.cc
This reduces the amount of work that is happening inside the read/write mutex for tracking handles in the Reactor.
1) Now gl cleanup calls happen outside of the write lock
1) Now setting gl debug texts are out of the write lock
1) Now creating objects with CreateHandle are out of the write lock
Jonah was seeing considerable time in the rwmutex, this should alleviate some of that.
issue: https://github.com/flutter/flutter/issues/159177
tests: no functional change, just performance …
=> Smaller reactor handle locks

impeller/renderer/command.h
A non-inconsequential amount of time is spent in ~shared_ptr for no reason in ~Resource …
=> Replaces Resource's shared_ptr with unique_ptr

shell/platform/android/build.gradle, shell/platform/android/test/io/flutter/embedding/engine/systemchannels/KeyEventChannelTest.java, shell/platform/android/test_runner/build.gradle, shell/platform/android/test_runner/src/main/resources/robolectric.properties
Bumps the version of AGP used in the IDE-support `build.gradle`, as well as the robolectric version in both the IDE-support `build.gradle` and test-runner-`build.gradle`. 
This is the current latest robolectric: https://github.com/robolectric/robolectric/releases/tag/robolectric-4.14.1.
Also 
1. configures robolectric to use API 35, and 
2. removes the use of a deprecated class which (from what I could tell) looked like it was just used for setup, and the test still passes without it.
[test-exempt]: …
=> Bump versions of agp and robolectric, and configure to use SDK 35

impeller/renderer/backend/gles/reactor_gles.cc, impeller/renderer/backend/gles/reactor_gles.h
I saw in profiles that we were spending a lot of time in push_back_slow_path.  Reserving + emplacing removes that.
test-except: no functional change, performance increase
[CLA]: …
=> [impeller] gles: started storing the number of handle deletions to avoid reallocation

shell/platform/darwin/ios/framework/Source/platform_views_controller.h, shell/platform/darwin/ios/framework/Source/platform_views_controller.mm
In flutter/engine#35501, handling was added to log a debug message to the console in the case where a platform view with a non-zero origin was identified.
Unfortunately:
* In unopt builds, the first thing we do in that block is to call FML_DCHECK asserting that the origin is zero, so we never actually emit the log statement.
* In opt builds, FML_DCHECK is a no-op, so users are unlikely to actually ever notice the crash.
The proper fix is to eliminate this restriction, but in the meantime, this eliminates this block entirely and leaves the TODO. We've had only two comments on that bug in the 2.5 years since it was added.
Issue: https://github.com/flutter/flutter/issues/109700 …
=> iOS: Eliminate logging of non-zero origin platformviews

impeller/entity/save_layer_utils.cc, impeller/entity/save_layer_utils_unittests.cc
For https://github.com/flutter/flutter/pull/158881
The new Android m3 page transition animates a saveLayer w/ opacity + slide in animation. See example video from linked PR:
https://github.com/user-attachments/assets/1382374a-4e0c-4a0e-9d70-948ce12e6298
On each frame, we intersect the coverage rect of this saveLayer contents with the screen rect, and shrink it to a partial rectangle. But this changes each frame, which forces us to re-allocate a large texture each frame, causing performance issues.
Why not ignore the cull rect entirely? We sometimes ignore the cull rect for the image filter layer for similar reasons, but from observation, the sizes of these saveLayer can be slightly larger than the screen for flutter gallery. Instead, I attempted to use the cull rect size to shrink the …
=> [Impeller] better handle allocation herustics of Android slide in page transition.

impeller/renderer/backend/gles/handle_gles.h, impeller/renderer/backend/gles/reactor_gles.cc, impeller/renderer/backend/gles/reactor_gles.h, impeller/renderer/backend/gles/test/pipeline_library_gles_unittests.cc, impeller/renderer/backend/gles/test/texture_gles_unittests.cc, impeller/renderer/backend/gles/texture_gles.cc
https://github.com/flutter/flutter/issues/159177
test exempt: no functional change, performance …
=> Started caching HandleGLES's hash and made them immutable

shell/platform/darwin/ios/framework/Source/FlutterPlatformViewsController.h, shell/platform/darwin/ios/framework/Source/FlutterPlatformViewsController.mm
This field is unused in the codebase/tests. …
=> iOS: Delete FlutterPlatformViewsController.layerPoolSize

shell/platform/darwin/ios/framework/Source/FlutterPlatformViewsController.mm
This is a minor refactoring that moves a global bool to a boolean ivar in FlutterPlatformViewsController. The purpose of this variable is simply to avoid the overhead of trying to create backdrop filters if we've ever failed to create one in the past.
Given that this class will only ever have the one instance created and held by per engine with the same duration, and that most apps only ever have one engine, the performance win will be identical for most apps. For the few add-to-app cases with multiple engines either at once or over the course of an app's lifetime, the costs associated with firing up an engine are already a far bigger hit than those being saved by this bool.
Also migrates from C++ style namespace { ... } to Obj-C style static functions. These are entirely equivalent as …
=> iOS: Eliminate global in platformviews controller

impeller/display_list/dl_dispatcher.cc, impeller/entity/contents/text_contents.cc, impeller/entity/entity_unittests.cc, impeller/typographer/backends/skia/typographer_context_skia.cc, impeller/typographer/font_glyph_pair.h, impeller/typographer/glyph_atlas.cc, impeller/typographer/glyph_atlas.h, impeller/typographer/text_frame.cc, impeller/typographer/text_frame.h, impeller/typographer/typographer_unittests.cc
Every text frame must inform the glyph atlas about the glyphs + scale it contains. When this happens, the glyph atlas will populate the glyph and then tell teh text frame about the location in the atlas, so that the text contents shader can sample it correctly.
Once this has been done once for a given text frame + scale + offset, we can actually just keep reusing the same data provided 1) the atlas itself hasn't changed and 2) the scale/offset/properties are the same.
This constitutes a nice CPU usage reduction in places where there is a lot of text that isn't being invalidated, like scrolling on the flutter gallery.
=> [Impeller] cache even more text frame data to skip lookups.

impeller/core/sampler_descriptor.cc, impeller/core/sampler_descriptor.h, impeller/display_list/canvas.cc, impeller/renderer/backend/metal/sampler_library_mtl.mm, impeller/renderer/backend/vulkan/sampler_vk.cc
I believe these are always const strings anyway, so remove the copy associated with using std::string.
=> [Impeller] make sampler use string_view instead of std::string.

shell/platform/darwin/ios/framework/Source/FlutterPlatformViewsController.h, shell/platform/darwin/ios/framework/Source/FlutterPlatformViewsController.mm
This field is unused in the codebase/tests.
This is a reland of https://github.com/flutter/engine/pull/56806, which was reverted as part of https://github.com/flutter/engine/pull/56790.
[CLA]: …
=> Reland: iOS: Delete FlutterPlatformViewsController.layerPoolSize

shell/platform/darwin/ios/framework/Source/FlutterPlatformViewsController.mm
This is a minor refactoring that moves a global bool to a boolean ivar in FlutterPlatformViewsController. The purpose of this variable is simply to avoid the overhead of trying to create backdrop filters if we've ever failed to create one in the past.
Given that this class will only ever have the one instance created and held by per engine with the same duration, and that most apps only ever have one engine, the performance win will be identical for most apps. For the few add-to-app cases with multiple engines either at once or over the course of an app's lifetime, the costs associated with firing up an engine are already a far bigger hit than those being saved by this bool.
Also migrates from C++ style namespace { ... } to Obj-C style static functions. These are entirely equivalent as …
=> Reland: iOS: Eliminate global in platformviews controller

shell/platform/darwin/ios/framework/Source/FlutterPlatformViewsController.h, shell/platform/darwin/ios/framework/Source/FlutterPlatformViewsController.mm, shell/platform/darwin/ios/framework/Source/FlutterPlatformViewsTest.mm
Applies non-null by default annotations to
FlutterPlatformViewsController with opt-outs where necessary. Updates unit tests to create graphics contexts where requried.
[CLA]: …
=> iOS: Apply nullability annotations to FlutterPlatformViewsController

impeller/typographer/font_glyph_pair.h
This allows a quick out when the simple parameters fail to be equal without even looking at optional properties.  In the case where they both have properties there is now one less `has_value()`.
[CLA]: …
=> Sped up SubpixelGlyph::Equal

ci/licenses_golden/excluded_files, impeller/renderer/backend/gles/BUILD.gn, impeller/renderer/backend/gles/buffer_bindings_gles.cc, impeller/renderer/backend/gles/buffer_bindings_gles.h, impeller/renderer/backend/gles/buffer_bindings_gles_unittests.cc, impeller/renderer/backend/gles/render_pass_gles.cc, impeller/renderer/backend/gles/test/mock_gles.cc
issue: https://github.com/flutter/flutter/issues/159177
The improvements come from using absl::flat_hash_map.
measurements with std vs absl (`host_profile_arm64`):
```
0.041124
0.0398002
0.0396546
0.0405552
0.0397742
0.0353708
0.0336834
0.0338616
0.033050
0.0331976
```
Benchmark used
```c++
TEST(BufferBindingsGLESTest, BindUniformDataMicro) {
BufferBindingsGLES bindings;
absl::flat_hash_map<std::string, GLint> uniform_bindings;
uniform_bindings["SHADERMETADATA.FOOBAR"] = 1;
bindings.SetUniformBindings(std::move(uniform_bindings));
std::shared_ptr<MockGLES> mock_gl = MockGLES::Init();
MockAllocator allocator;
Bindings vertex_bindings;
ShaderMetadata shader_metadata = {
.name = "shader_metadata",
.members = {ShaderStructMemberMetadata{.type = ShaderType::kFloat,
.name = "foobar",
.offset = …
```
=> [impeller] makes UniformBindData 15% faster and adds unit test

ci/bin/format.dart, ci/format.sh
Fixes running x64 binaries on arm64 hosts, this fixes systems like Raspberry Pi's, Apple Silicon, and Ampere.
Before, I would get something like:
```
Checking GN formatting...
Completed checking 0 GN files with no formatting problems.
Checking Java formatting...
No Java files with changes, skipping Java format check.
Checking Python formatting...
All python files formatted correctly.
Checking for trailing whitespace on 1 source file...
No trailing whitespace found.
No header files with changes, skipping header guard check.
Checking C++/ObjC/Shader formatting...
ERROR: Formatter command '/home/ross/flutter-engine/src/flutter/buildtools/linux-x64/clang/bin/clang-format --style=file shell/platform/linux/fl_application_test.cc' failed with exit code 255. Command output follows:
qemu-x86_64: …
```
=> [ci] use env for format and support arm64 hosts

shell/platform/linux/fl_basic_message_channel.cc, shell/platform/linux/fl_binary_messenger.cc, shell/platform/linux/fl_method_channel.cc
This could occur if a request is cancelled, without this it might not chain up to the original caller correctly.
=> Always check for errors when propagating task values.

impeller/renderer/backend/gles/render_pass_gles.cc, impeller/renderer/render_pass.cc
Small cleanups to render_pass_gles to only set the viewport once or when it cahnges, instead of each draw. Removes scissor validation and pipeline unbind (which is slow due to hash table lookup).
=> [Impeller] set GLES viewport once, remove extra unbind/validation.

DEPS, impeller/typographer/BUILD.gn, impeller/typographer/font_glyph_pair.h, impeller/typographer/glyph_atlas.cc, impeller/typographer/glyph_atlas.h
In https://github.com/flutter/engine/pull/56844 we saw a 15% increase in performance by switching to absl::flat_hash_map.  I suspect we say see even better results ([source](https://martin.ankerl.com/2022/08/27/hashmap-bench-01)).  The absl guidance is to default to using this.
test exempt: no intentional functional change, just performance …
=> Moved font glyph atlas to flat_hash_map

impeller/typographer/backends/skia/typographer_context_skia.cc, impeller/typographer/text_frame.cc, impeller/typographer/text_frame.h, impeller/typographer/typographer_unittests.cc
Fixes https://github.com/flutter/flutter/issues/159704, but for real this time.
=> [Impeller] invalidate cached atlas data, take 2.

shell/platform/linux/fl_basic_message_channel.cc, shell/platform/linux/fl_basic_message_channel_test.cc, shell/platform/linux/fl_method_channel.cc, shell/platform/linux/fl_method_channel_test.cc
Fix error not being copied in this case.
Follow up to https://github.com/flutter/engine/pull/56856
=> Add tests for errors encoding message channel request and method calls.

skia/modules/canvaskit/BUILD.gn
Confirmed that a sample Flutter app starts with a 32MB memory allocation for CanvasKit instead of 128MB.
| Before | After|
|-|-|
| ![image](https://github.com/user-attachments/assets/5f6f2d4d-9155-499e-b20e-a15e3d8b53ab) | ![image](https://github.com/user-attachments/assets/bf1956c4-2d2a-44a8-b781-b110be93bc6a) |
Fixes https://github.com/flutter/flutter/issues/159499
<hr>
Relevant emscripten settings:
- [`INITIAL_MEMORY`](https://emscripten.org/docs/tools_reference/settings_reference.html#initial-memory)
- [`ALLOW_MEMORY_GROWTH`](https://emscripten.org/docs/tools_reference/settings_reference.html#allow-memory-growth)
- [`MEMORY_GROWTH_GEOMETRIC_STEP`](https://emscripten.org/docs/tools_reference/settings_reference.html#memory-growth-geometric-step)
- …
=> [web] Start with a smaller memory allocation for CanvasKit

impeller/renderer/backend/gles/render_pass_gles.cc
We're already doing a check if the pipeline is valid in RenderPass::AddCommand. The index checks are validated during binding, and the check for instancing is unecessary given that we don't expose.
While I'm at it do some minor cleanups.
=> [Impeller] remove extra validation checks in GLES backend.

impeller/renderer/backend/gles/proc_table_gles.cc, impeller/renderer/backend/gles/proc_table_gles.h, impeller/renderer/backend/gles/reactor_gles.cc, impeller/renderer/backend/gles/reactor_gles.h, impeller/renderer/backend/gles/test/mock_gles.cc, impeller/renderer/backend/gles/test/reactor_unittests.cc
issue: https://github.com/flutter/flutter/issues/159745
https://github.com/flutter/engine/pull/56927 introduced untracked handles, but naming them didn't work.  This adds a test to make sure they work.  I kept naming thread-safe since it isn't happening often anyways.
[C++, …
=> Implements the naming of untracked gles handles

impeller/renderer/backend/gles/render_pass_gles.cc
Winding order and cull mode almost never change, so avoid re-binding them over and over again. Minor performance improvement.
=> [Impeller] avoid re-binding winding order and cull mode.

ci/licenses_golden/excluded_files, impeller/renderer/backend/gles/BUILD.gn, impeller/renderer/backend/gles/pipeline_library_gles.cc, impeller/renderer/backend/gles/unique_handle_gles.cc, impeller/renderer/backend/gles/unique_handle_gles.h, impeller/renderer/backend/gles/unique_handle_gles_unittests.cc
issue: https://github.com/flutter/flutter/issues/159745
[CLA]: …
=> Moved gles pipelines to untracked handles.

impeller/renderer/backend/gles/allocator_gles.cc, impeller/renderer/backend/gles/allocator_gles.h, impeller/renderer/backend/gles/blit_pass_gles.cc, impeller/renderer/backend/gles/blit_pass_gles.h, impeller/renderer/backend/gles/command_buffer_gles.cc, impeller/renderer/backend/gles/command_buffer_gles.h, impeller/renderer/backend/gles/context_gles.cc, impeller/renderer/backend/gles/context_gles.h, impeller/renderer/backend/gles/device_buffer_gles.cc, impeller/renderer/backend/gles/device_buffer_gles.h, impeller/renderer/backend/gles/pipeline_gles.cc, impeller/renderer/backend/gles/pipeline_gles.h, impeller/renderer/backend/gles/pipeline_library_gles.cc, impeller/renderer/backend/gles/pipeline_library_gles.h, impeller/renderer/backend/gles/reactor_gles.h, impeller/renderer/backend/gles/render_pass_gles.cc, impeller/renderer/backend/gles/render_pass_gles.h, impeller/renderer/backend/gles/texture_gles.cc, impeller/renderer/backend/gles/texture_gles.h, impeller/renderer/backend/gles/unique_handle_gles.cc, impeller/renderer/backend/gles/unique_handle_gles.h
This typedef really wasn't making the codebase any easier to work with.  We don't do this for other std::shared_ptr's
test-exempt: just removes typedef …
=> Removes ReactorGLES::Ref

display_list/display_list_unittests.cc, display_list/dl_builder.cc, display_list/dl_builder.h, display_list/dl_paint.h, display_list/dl_paint_unittests.cc
Fixes https://github.com/flutter/flutter/issues/158500
Impeller does not support group opacity for RuntimeEffects so we disable the optimization with a flag when it is detected.
=> [DisplayList] Disable group opacity when a RuntimeEffect is in use

impeller/renderer/backend/gles/capabilities_gles.cc, impeller/renderer/backend/gles/test/capabilities_unittests.cc
Offscreen MSAA needs the ability to create multisample depth and stencil attachments.
=> [Impeller] Require the GLES multisampled_render_to_texture2 extension for offscreen MSAA

impeller/renderer/backend/gles/buffer_bindings_gles_unittests.cc, impeller/renderer/backend/gles/test/capabilities_unittests.cc, impeller/renderer/backend/gles/test/gpu_tracer_gles_unittests.cc, impeller/renderer/backend/gles/test/mock_gles.cc, impeller/renderer/backend/gles/test/mock_gles.h, impeller/renderer/backend/gles/test/mock_gles_unittests.cc, impeller/renderer/backend/gles/test/reactor_unittests.cc, impeller/renderer/backend/gles/unique_handle_gles_unittests.cc
=> Replaces bespoke call captures from mock gles with gmock

shell/platform/darwin/graphics/FlutterDarwinContextMetalImpeller.mm
In the case where `CreateImpellerContext` encounters an error while creating an `impeller::ContextMTL`, we logged an error, returned nullptr, then immediately dereferenced the null pointer. Now, rather than crash due to a segfault, we now intentionally abort with an appropriate error message.
This adds checks in the `FlutterDarwinContextMetalImpeller` initialiser that aborts with an appropriate error message if impeller context creation fails, Metal device creation fails, or texture cache creation fails.
Rather than bailing out and returning nil from the initialiser to pass the buck to the caller, we terminate since without a graphics context, the app won't be able to render anything to begin with.
Issue: https://github.com/flutter/flutter/issues/157489
Issue: …
=> iOS: add null check on create impeller context

impeller/renderer/backend/gles/buffer_bindings_gles_unittests.cc, impeller/renderer/backend/gles/test/capabilities_unittests.cc, impeller/renderer/backend/gles/test/gpu_tracer_gles_unittests.cc, impeller/renderer/backend/gles/test/mock_gles.cc, impeller/renderer/backend/gles/test/mock_gles.h, impeller/renderer/backend/gles/test/mock_gles_unittests.cc, impeller/renderer/backend/gles/test/reactor_unittests.cc, impeller/renderer/backend/gles/unique_handle_gles_unittests.cc
relands https://github.com/flutter/engine/pull/56995
It previously landed with stale presubmits, this should be up to date now.  I have the fix in a separate commit.
[testing …
=> Reland: Replaces bespoke call captures from mock gles with gmock

shell/platform/darwin/ios/BUILD.gn, shell/platform/darwin/ios/framework/Source/FlutterPlatformViews.mm, shell/platform/darwin/ios/framework/Source/FlutterPlatformViewsTest.mm
This is pretty tricky bug - I suspect that because Apple's internal recognizer caching an outdated state of our delaying recognizer. 
The conflict happens between WebKit and platform view's recognizers. It happens to all plugins that uses a WKWebView, or any view that has a similar (unknown) gesture setup. 
This fix has to be in the engine (rather than the plugin), because the plugin itself knows nothing about the existence of our delaying recognizer. 
Here are the steps of my research for future reference: 
1. The bug only happens when the overlay flutter widgets blocks the gestures for the platform view (e.g. tap on the platform view area when a flutter context menu is displayed). When the bug happens, WKWebView's link doesn't work anymore, however, the link can still be highlighted …
=> [ios][platform_view] workaround for non-tappable webview

impeller/entity/render_target_cache.cc, impeller/entity/render_target_cache.h, impeller/entity/render_target_cache_unittests.cc
Improve cache usage by keeping textures alive for 4 frames after the last usage. This improves cache usage in scenarios such as repeatidly dragging the android overscroll functionality.
THis isn't expected to have a negative impact on memory, because a texture cannot be _immediately_ deleted anyway.
=> [Impeller] Add keep alive for 4 frames in render target cache.

impeller/entity/contents/test/recording_render_pass.cc, impeller/renderer/backend/gles/render_pass_gles.cc, impeller/renderer/command.cc, impeller/renderer/command.h, impeller/renderer/render_pass.cc, impeller/renderer/render_pass.h
Move vertex buffer storage off of the command object. Because we can bind up to 16 (but usually 1) vertex buffers per cmd, storing it on the command requires allocating storage for the full 16 buffers. MOving this to a secondary vector decreases the size of the command object from ~800 bytes to ~200 bytes.
=> [Impeller] store vertex buffers in render pass for gles.

shell/platform/darwin/ios/framework/Source/platform_views_controller.mm
Ensures that all platform views items are tracked in the previous_composition_order_ set. Without this, they can occasionally be left on screen.
=> [CP][iOS] fix tracking of prev platform view items.

shell/platform/linux/fl_keyboard_manager.cc, shell/platform/linux/fl_keyboard_pending_event.cc, shell/platform/linux/fl_keyboard_pending_event.h
Remove pending keyboard event ID and use the object directly.
Use references to make sure FlKeyboardManagerData is freed.
Refactor marking events as handled
=> Cleanup refactoring in FlKeyboardManager

impeller/compiler/compiler.cc
The shader language level is 300 or more we need to use GL_OES_EGL_image_external_essl3 instead of GL_OES_EGL_image_external
=> [Impeller] use ES3 extension for external images.

DEPS, ci/licenses_golden/excluded_files, ci/licenses_golden/licenses_skia, skia/BUILD.gn, tools/gn
Resolves https://github.com/flutter/engine/pull/57068.
Set args `skia_use_libpng_decode=true` and `skia_use_rust_png_decode=false`.
https://skia.googlesource.com/skia.git/+log/e78dd0265002..14f8f6d984ff
2024-12-09 kjlubick@google.com Update GN build to allow for rust PNG decoding only
2024-12-09 lukasza@chromium.org [rust png] Update Skia => `png` dependency to version 0.17.15.
2024-12-09 kjlubick@google.com Add placeholder files for jsonreader
=> Roll Skia to 14f8f6d984ff

impeller/renderer/backend/vulkan/driver_info_vk.cc, impeller/renderer/backend/vulkan/driver_info_vk_unittests.cc
Fixes https://github.com/flutter/flutter/issues/159834
Disable all older Adreno GPUs
=> [Impeller] disable all Adrenos older than 630

impeller/core/BUILD.gn, impeller/core/raw_ptr.cc, impeller/core/raw_ptr.h, impeller/entity/contents/color_source_contents.h, impeller/entity/contents/content_context.cc, impeller/entity/contents/content_context.h, impeller/entity/contents/filters/blend_filter_contents.cc, impeller/entity/contents/test/recording_render_pass.cc, impeller/entity/contents/test/recording_render_pass.h, impeller/entity/entity_unittests.cc, impeller/playground/imgui/imgui_impl_impeller.cc, impeller/renderer/backend/metal/render_pass_mtl.h, impeller/renderer/backend/metal/render_pass_mtl.mm, impeller/renderer/backend/vulkan/render_pass_vk.cc, impeller/renderer/backend/vulkan/render_pass_vk.h, impeller/renderer/command.h, impeller/renderer/pipeline.h, impeller/renderer/render_pass.cc, impeller/renderer/render_pass.h, impeller/renderer/renderer_dart_unittests.cc, impeller/renderer/renderer_unittests.cc, lib/gpu/render_pass.cc
Fixes https://github.com/flutter/flutter/issues/159566
We don't need recorded commands to keep pipelines alive as the context does that already.
=> [Impeller] switch Pipeline to use raw ptr instead of shared ptr for recorded references.

shell/platform/darwin/ios/BUILD.gn, shell/platform/darwin/ios/framework/Source/FlutterPlatformViewsTest.mm, shell/platform/darwin/ios/framework/Source/FlutterPlatformViews_Internal.h, shell/platform/darwin/ios/framework/Source/FlutterPlatformViews_Internal.mm
Manual version of https://github.com/flutter/engine/pull/57030#issuecomment-2524607775
Since I can't push it to the original branch. 
This pull request is created by [automatic cherry pick workflow](https://github.com/flutter/flutter/blob/main/docs/releases/Flutter-Cherrypick-Process.md#automatically-creates-a-cherry-pick-request)
Please fill in the form below, and a flutter domain expert will evaluate this cherry pick request.
What is the link to the issue this cherry-pick is addressing?
https://github.com/flutter/flutter/issues/158961
Explain this cherry pick in one line that is accessible to most Flutter developers. See [best practices](https://github.com/flutter/flutter/blob/main/docs/releases/Hotfix-Documentation-Best-Practices.md) for examples
Fix an issue on iOS 18.2 where web …
=> [CP-beta][MANUAL][ios][platform_view] workaround for non-tappable webview #57030

ci/licenses_golden/excluded_files, impeller/renderer/backend/gles/BUILD.gn, impeller/renderer/backend/gles/device_buffer_gles.cc, impeller/renderer/backend/gles/device_buffer_gles.h, impeller/renderer/backend/gles/device_buffer_gles_unittests.cc, impeller/renderer/backend/gles/test/mock_gles.cc, impeller/renderer/backend/gles/test/mock_gles.h
fixes: https://github.com/flutter/flutter/issues/159745
[CLA]: …
=> moved device buffer to an untracked handle

impeller/entity/save_layer_utils.cc, impeller/entity/save_layer_utils_unittests.cc
Remove the over-engineered "slide around round up" herusistic for the same heuristic used by the image filters: if the coverage size is within 30% of the cull rect size, just use the cull rect size.
This stabilizes allocations for the new android slide in page transition, but in a less complicated way than the old herustic.
=> [Impeller] simplify render target size rounding up heuristics.

lib/web_ui/lib/src/engine/pointer_binding.dart, lib/web_ui/lib/src/engine/pointer_binding/event_position_helper.dart, lib/web_ui/test/engine/pointer_binding_test.dart
Manual cherry pick for https://github.com/flutter/engine/pull/56719
Cherrypick request: https://github.com/flutter/flutter/issues/159692
=> [cp:beta][web] Work around wrong pointerId in coalesced events in iOS Safari 18.2 (#56719)

shell/platform/fuchsia/dart-pkg/zircon/sdk_ext/system.cc, shell/platform/fuchsia/dart_runner/dart_component_controller.cc, shell/platform/fuchsia/flutter/component_v2.cc, shell/platform/fuchsia/flutter/file_in_namespace_buffer.cc, shell/platform/fuchsia/runtime/dart/utils/mapped_resource.cc, shell/platform/fuchsia/runtime/dart/utils/vmo.cc, shell/platform/fuchsia/runtime/dart/utils/vmservice_object.h
Migrate the use of fuchsia.io open functions to the new open3 replacements (which also requires transitioning from OpenFlags -> Flags). Likewise, we update all uses of the SDK VFS library to use the new set of flags.
This work is being done as part of the ongoing io2 migration in https://fxbug.dev/378924259 …
=> [engine] Migrate fuchsia.io Open functions to Open3

shell/platform/linux/fl_key_embedder_responder_test.cc
Remove global variable.
Rename function so doesn't look like provided by GLib.
Use g_autoptr to remove explicit unref.
Move type definition inline.
=> Clean up key embedder responder tests

ci/bin/format.dart, ci/test/format_test.dart
Currently it is off by default since we haven't migrated any files over to the new format. To try it out, run `dart ci/bin/format.dart -c dart -f`.
Once we turn it on by default `et` will automatically format dart files as it calls into `format.dart`.
=> Add support for dart formatter

display_list/effects/color_sources/dl_gradient_color_source_base.h, display_list/effects/color_sources/dl_linear_gradient_color_source.cc, display_list/effects/color_sources/dl_linear_gradient_color_source.h, display_list/effects/dl_color_source.cc, display_list/effects/dl_color_source.h, display_list/effects/dl_color_source_unittests.cc, display_list/skia/dl_sk_conversions_unittests.cc, lib/ui/painting/gradient.cc
issue: https://github.com/flutter/flutter/issues/154650
[CLA]: …
=> Removed linear gradient heap allocation for color conversions between dart and display list

impeller/renderer/backend/gles/buffer_bindings_gles.cc
gl.UniformBlockBinding only needs to be set once when the pipeline is linked, and not on every draw.
=> [Impeller] set UniformBlockBinding once.

impeller/renderer/backend/vulkan/texture_vk.cc, impeller/renderer/backend/vulkan/texture_vk.h
Labelling textures shows up in all of our profiles because of the cost to lock the context weak ptr and then call into both the image and image view. remove this if no layers are present that would read the label.
=> [Impeller] avoid expensive texture labeling w/ no validation layers.

lib/web_ui/dev/chrome_installer.dart
The Web Felt script downloads a Chrome zip archive, extracts it to a temporary directory, and then moves the files to a location expected by the script.
Previously Felt used a temporary directory based on io.Directory.systemTemp.  This may not work because the FileSystemEntity.rename operation used to move the files can fail if the system temp directory is located in a different filesystem from the destination directory.
=> Make Felt unzip Chrome into a temporary directory next to the final location of the files

impeller/renderer/backend/vulkan/render_pass_builder_vk.cc, impeller/renderer/backend/vulkan/render_pass_builder_vk.h, impeller/renderer/backend/vulkan/render_pass_vk.cc
Remove std::vector usage in vulkan render pass. Fixed size array + offsets, should be faster than heap allocations.
=> [Impeller] remove std::vector usage in render pass vk.

display_list/effects/color_sources/dl_conical_gradient_color_source.cc, display_list/effects/color_sources/dl_conical_gradient_color_source.h, display_list/effects/color_sources/dl_linear_gradient_color_source.cc, display_list/effects/color_sources/dl_linear_gradient_color_source.h, display_list/effects/color_sources/dl_radial_gradient_color_source.cc, display_list/effects/color_sources/dl_radial_gradient_color_source.h, display_list/effects/color_sources/dl_sweep_gradient_color_source.cc, display_list/effects/color_sources/dl_sweep_gradient_color_source.h, display_list/effects/dl_color_source.cc, display_list/effects/dl_color_source.h, display_list/effects/dl_color_source_unittests.cc, lib/ui/painting/gradient.cc
fixes https://github.com/flutter/flutter/issues/154650
[CLA]: …
=> Removed heap allocations for conical, radial and sweep gradients

impeller/renderer/backend/gles/test/reactor_unittests.cc
Pass a flag to AddOperation to ensure that ReactorGLES does not immediately execute the operation on the second thread.
=> [Impeller] Fix a race in the ReactorGLES.PerThreadOperationQueues test

shell/platform/darwin/ios/framework/Source/FlutterAppDelegate.mm, shell/platform/darwin/ios/framework/Source/FlutterEngine.mm, shell/platform/darwin/ios/framework/Source/FlutterEnginePlatformViewTest.mm, shell/platform/darwin/ios/framework/Source/FlutterEngineTest.mm, shell/platform/darwin/ios/framework/Source/FlutterEngine_Internal.h, shell/platform/darwin/ios/framework/Source/FlutterEngine_Test.h, shell/platform/darwin/ios/framework/Source/FlutterPlatformViewsTest.mm, shell/platform/darwin/ios/framework/Source/FlutterViewController.mm, shell/platform/darwin/ios/framework/Source/FlutterViewControllerTest.mm, shell/platform/darwin/ios/platform_view_ios.h
Eliminates some cases where `FlutterViewController` was relying on `FlutterEngine` internals:
* `[FlutterEngine shell]`
* `[FlutterEngine platformView]`
* `[FlutterEngine iosPlatformView]`
Instead, `FlutterEngine` now exposes:
* `installFirstFrameCallback:`
* `enableSemantics:withFlags:`
* `notifyViewCreated`
* `notifyViewDestroyed`
* `waitForFirstFrameSync:callback:`
Also fixes a couple cases where we were relying on transitive header includes:
* `FlutterAppController` relied on `FlutterViewController_Internal.h` for `sendDeepLinkToFramework:completionHandler:`
This is a refactoring followup to https://github.com/flutter/engine/pull/57099 that introduces no semantic changes. …
=> iOS: Reduce engine/view controller coupling

shell/platform/linux/fl_basic_message_channel_test.cc, shell/platform/linux/testing/fl_mock_binary_messenger.cc, shell/platform/linux/testing/fl_mock_binary_messenger.h
Use FlMockBinaryMessenger instead of mocking the whole engine.
=> Migrate FlBasicMessageChannel tests to FlMockBinaryMessenger

shell/platform/linux/fl_engine.cc, shell/platform/linux/fl_engine_private.h, shell/platform/linux/fl_engine_test.cc, shell/platform/linux/fl_keyboard_manager.cc
Add missing tests for this function.
Note this makes FlKeyboardManager a bit more complex, but this is planned to be simplified in a future refactor.
=> Make fl_engine_send_key_event into a standard async function.

impeller/renderer/backend/gles/proc_table_gles.cc, impeller/renderer/backend/gles/proc_table_gles.h, impeller/renderer/backend/gles/test/reactor_unittests.cc
fixes https://github.com/flutter/flutter/issues/160180
I'm unable to reproduce the problem locally but this is the most likely cause. …
=> Reenabled labelling test with a capabilities check.

shell/platform/darwin/ios/framework/Source/FlutterPlatformViews.mm, shell/platform/darwin/ios/framework/Source/FlutterPlatformViewsTest.mm
The original workaround ([PR](https://github.com/flutter/engine/pull/56804)) works for the official web view plugin, but it doesn't work for a third party plugin `flutter_inappwebview` ([issue](https://github.com/pichillilorenzo/flutter_inappwebview)). Upon discussion with the author of that plugin, it turns out that their platform view is not a WKWebView, but rather a wrapper of WKWebView. 
This PR performs a DFS search of the view hierarchy, and enable the workaround as long as there's a WKWebView inside. 
TODO: pending sample project:
I am quite positive that it should work, but **I haven't tried it since I don't have a sample project yet**. I have requested a sample project with them so I can verify the solution. 
*List which issues are fixed by this PR. You must list at least one …
=> [ios]enable the webview non tappable workaround by checking subviews recursively

display_list/benchmarking/dl_builder_benchmarks.cc, display_list/benchmarking/dl_region_benchmarks.cc, display_list/display_list.cc, display_list/display_list.h, display_list/display_list_unittests.cc, display_list/dl_builder.cc, display_list/dl_builder.h, display_list/dl_vertices.h, display_list/geometry/dl_geometry_types.h, display_list/geometry/dl_path.h, display_list/geometry/dl_region.cc, display_list/geometry/dl_region.h, display_list/geometry/dl_region_unittests.cc, display_list/geometry/dl_rtree.cc, display_list/geometry/dl_rtree.h, display_list/geometry/dl_rtree_unittests.cc, display_list/utils/dl_matrix_clip_tracker.cc, display_list/utils/dl_matrix_clip_tracker.h, flow/embedded_views.h, flow/layers/display_list_layer_unittests.cc, flow/layers/display_list_raster_cache_item.cc, flow/raster_cache.cc, flow/view_slicer.cc, impeller/geometry/rect.h, shell/platform/android/surface_texture_external_texture_gl_skia.cc, shell/platform/darwin/ios/ios_surface_software.mm, shell/platform/embedder/embedder_external_view_embedder.cc, shell/platform/embedder/embedder_layers.cc, shell/platform/embedder/embedder_layers.h, shell/platform/fuchsia/flutter/rtree.cc
Continuing the migration of engine code to the new geometry classes. Only DlRTree and DlRegion are converted in this pass, plus a small amount of associated code.
=> Migrate DlRTree and DlRegion to DisplayList/Impeller geometry classes

shell/platform/darwin/ios/framework/Source/FlutterPlatformViews.mm, shell/platform/darwin/ios/framework/Source/FlutterPlatformViewsTest.mm
This PR limits the search depth, because we don't want to enable this workaround for AdMob banner, which has a WKWebView in the depth of 7. See the previous PR for more context: https://github.com/flutter/engine/pull/57168
I was able to confirm that this returns YES for the 3P plugin, and NO for AdMob. 
https://github.com/flutter/flutter/issues/158961 …
=> [ios]limit web view not tappable workaround to a limited depth

lib/web_ui/lib/src/engine/renderer.dart, web_sdk/sdk_rewriter.dart, web_sdk/test/js_access_test.dart, web_sdk/test/sdk_rewriter_test.dart
We are about to `dart format` all the Dart code in the repo, which line-breaks some of our imports.
This PR updates `sdk_rewriter.dart` to support line-broken imports.
=> [web] allow imports to line-break

shell/platform/darwin/ios/framework/Source/FlutterPlatformViewsTest.mm, shell/platform/darwin/ios/framework/Source/FlutterPlatformViews_Internal.mm
CP for https://github.com/flutter/engine/pull/57168 and https://github.com/flutter/engine/pull/57193
https://github.com/flutter/flutter/issues/158961 …
=> [CP][3.27][ios]enable the webview non tappable workaround by checking subviews recursively #57168

impeller/renderer/backend/vulkan/swapchain/swapchain_vk.cc
Cherry pick for https://github.com/flutter/flutter/issues/160206
FYI @zanderso  / @chinmaygarde
=> [CP][Android] Disable SurfaceControl based swapchains.

tools/pkg/engine_build_configs/lib/src/build_config_runner.dart, tools/pkg/engine_build_configs/test/build_config_runner_test.dart
fixes https://github.com/flutter/flutter/issues/147931
environment variable documented in github issue: https://github.com/ninja-build/ninja/issues/2196 …
=> Made compilation error colors come through et.

lib/web_ui/lib/src/engine/skwasm/skwasm_impl/path.dart, lib/web_ui/test/ui/path_test.dart
Fixes https://github.com/flutter/flutter/issues/157161
=> [skwasm] Fix implementation of SkwasmPath.relativeLineTo

impeller/renderer/backend/vulkan/driver_info_vk.cc, impeller/renderer/backend/vulkan/driver_info_vk_unittests.cc
Cherry pick for https://github.com/flutter/flutter/issues/160041
=> [CP][Impeller] disable all Adrenos older than 630 (#57069)

tools/pub_get_offline.py
On the bots there were old and stale `package_config.json` files hanging around that confuse the `dart format` command. This PR adds a step to the `pub_get_offline.py` glcient sync hook to delete all of these files that are not under version control.
=> Delete stale package_config.json in gclient sync hook

ci/licenses_golden/excluded_files, shell/platform/fuchsia/dart-pkg/fuchsia/analysis_options.yaml, shell/platform/fuchsia/dart-pkg/zircon/analysis_options.yaml, shell/platform/fuchsia/dart_runner/vmservice/analysis_options.yaml, shell/platform/fuchsia/flutter/kernel/analysis_options.yaml
The old path doesn't exist.
`dart format` stumbles over this non-existent include.
`analysis_options.yaml` files that just imported something non-existent were deleted.
I am surprised that this never caused any other issues. Is this all dead code that isn't actually analyzed?
=> Fix include path in fuchsia's analysis_options.yaml files

lib/ui/hooks.dart, lib/web_ui/lib/src/engine/services/message_codecs.dart, lib/web_ui/test/engine/view/view_constraints_test.dart, testing/dart/image_filter_test.dart, testing/scenario_app/lib/src/platform_view.dart, tools/const_finder/test/fixtures/lib/box.dart
When running `dart format` over these lines the `// ignore` ended up on a line where it wasn't properly ignoring the lint. This adjusts the placement of `// ignore`s so they will continue to ignore the right thing even after the code is auto formatted.
I am hoping that if we do this now the large PR that formats the entire repo will go in smoother without manual intervention.
=> Adjust some ignores for 'dart format'

ci/builders/linux_web_engine.json
RBE is not supported for this build.  Starting the RBE proxy adds unnecessary overhead, and the attempt to use RBE will cause the build recipe to request too many parallel jobs in Ninja.
=> Disable RBE in the GN flags for wasm_release builds in the linux_web_engine builder

impeller/entity/shaders/downsample.glsl, impeller/tools/malioc.json
Fixes observed sampling problems on the adreno series where slightly different mediump/lowp behavior, resulting in the downsample shader showing "chunky" rendeering.
=> [Impeller] fix Adreno precision issue in gaussian downsample.

impeller/renderer/backend/vulkan/swapchain/swapchain_vk.cc
Disabling until we figure out if we can even use this.
=> [Impeller] disable AHB swapchains on all platforms.

shell/platform/embedder/embedder.h
The RGB565 format documentation in embedder.h incorrectly stated that the red component uses the least significant bits. Unit tests in embedder/testdefs/embedder_unittests.cc demonstrate this is incorrect, showing:
- Red test (0xF800): Uses bits [15:11]
- Green test (0x07E0): Uses bits [10:5]
- Blue test (0x001F): Uses bits [4:0]
This commit fixes the documentation to correctly reflect the actual bit layout:
- Red uses 5 MSBs [15:11]
- Green uses 6 middle bits [10:5]
- Blue uses 5 LSBs [4:0]
Also fixes the example bit extraction code to use correct masks, matching the test expectations.
Impact: This change helps prevent potential developer confusion about RGB565 bit ordering and ensures the documentation matches the actual implementation as verified by the test suite.
=> docs: Fix RGB565 format documentation and bit masks

tools/pub_get_offline.py
https://github.com/flutter/engine/pull/57195 was reverted because it tried to delete non-existing files. This adds a check to only attempt to delete the file if it exists.
=> Reland 'Delete stale package_config.json in gclient sync hook'

lib/web_ui/lib/src/engine/canvaskit/image.dart, lib/web_ui/lib/src/engine/dom.dart, lib/web_ui/test/canvaskit/image_test.dart
A `CkImage` instance holds a reference to `ImageSource?`. When that `CkImage` gets cloned, the `ImageSource` instance becomes shared between the original `CkImage` and its new clone. Then when one of the `CkImage`s gets disposed of, it closes the shared `ImageSource` leaving other live `CkImage`s holding on to a closed `ImageSource`.
The quick solution to this is to have a ref count on the `ImageSource` to count how many `CkImage`s are referencing it. The `ImageSource` will only be closed if its ref count reaches 0.
Fixes https://github.com/flutter/flutter/issues/160199
Fixes https://github.com/flutter/flutter/issues/158093
=> [web] Don't close image source too early

shell/platform/linux/fl_binary_messenger.cc, shell/platform/linux/fl_binary_messenger_private.h, shell/platform/linux/fl_binary_messenger_test.cc, shell/platform/linux/testing/mock_engine.cc
This allows us to remove most of the remaining mock engine code.
=> Migrate FlBinaryMessenger using embedder API instead of mock engine.

ci/bin/format.dart, ci/test/format_test.dart
`dart format` can fail (e.g. if a file contains invalid dart code). Previously, those failures were swallowed. This change adds logic to properly print those failures to the terminal.
=> Properly report `dart format` errors

ci/licenses_golden/tool_signature, tools/licenses/lib/filesystem.dart, tools/licenses/lib/formatter.dart, tools/licenses/lib/licenses.dart, tools/licenses/lib/main.dart, tools/licenses/lib/paths.dart, tools/licenses/lib/patterns.dart, tools/licenses/lib/regexp_debug.dart, tools/licenses/test/formatter_test.dart
The license script has load-baring formatting: Changing its format makes signature checks fail. To ensure the formatting change goes in smoothly later this week I am taking it off the critical path by pre-formatting it. 
The script itself is fairly stable, so I am not expecting any changes to it between now and when we actually enforce formatting.
Edit: The issue that surfaced with `ci/licenses_golden/licenses_dart` is another reason to take this off the critical path of enforcing formatting.
=> Pre-format licenses script

.ci.yaml
The motivation is described in https://github.com/flutter/flutter/issues/160405. This is just one step towards cleaning everything up. More PRs to follow.
=> [monorepo] remove Linux Web Framework tests

shell/platform/embedder/embedder.h
The order of the components for packed software pixel formats is incorrectly documented as being the order in the native type, least-significant-bit first. In reality it's the other way around. For example, for `RGB565`, the `R` is the 5 most significant bits in the 2-byte pixel value, rather than the least significant bits. The test even verify it is that way:
https://github.com/flutter/engine/blob/main/shell/platform/embedder/tests/embedder_unittests.cc#L2782-L2785
I assume noone used the software pixel formats until @sodiboo did, that's why it's gone unnoticed for so long.
Also contains some other minor documentation improvements.
- Issue: https://github.com/flutter/flutter/issues/160149
[Contributor Guide]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.m …
=> embedder: fix bit-order in software pixel format description

lib/web_ui/lib/src/engine/pointer_binding.dart, lib/web_ui/lib/src/engine/pointer_binding/event_position_helper.dart, lib/web_ui/test/engine/pointer_binding_test.dart
Manual cherry pick for https://github.com/flutter/engine/pull/56719
Cherrypick request: https://github.com/flutter/flutter/issues/159691
=> [cp:stable][web] Work around wrong pointerId in coalesced events in iOS Safari 18.2 (#56719)
