flutter/engine

sky/sdk/lib/animation/forces.dart
Forgot to add this file to the repo.
=> Add forces.dart

ui/gfx/BUILD.gn, ui/gfx/android/java/src/org/chromium/ui/gfx/BitmapHelper.java, ui/gfx/android/java/src/org/chromium/ui/gfx/DeviceDisplayInfo.java, ui/gfx/android/java/src/org/chromium/ui/gfx/ViewConfigurationHelper.java, ui/gl/BUILD.gn, ui/gl/android/java/src/org/chromium/ui/gl/SurfaceTextureListener.java, ui/gl/android/java/src/org/chromium/ui/gl/SurfaceTexturePlatformWrapper.java
Apparently these files are needed to build for Android.
=> Add back ui Java files for android

sky/tools/gn
Typo from a previous commit of mine.
R=abarth@google.com
=> Fix sky/tools/gn --debug to not expect an argument

sky/tests/examples/stocks-expected.txt, travis/build.sh
Also, turn on testing in Travis.
=> Rebaseline stocks test to account for transitions

travis/build.sh
Maybe this will work now that we have less code.
=> Try building Release with -j 2

travis/build.sh
Try building faster on Travis now that we're using Release and have less code.
=> Increase j to 4

sky/sdk/lib/widgets/variable_height_scrollable.dart
Use didMount(), didUnmount() to manage the layoutState listener.
=> Fix variable height scrollable

sky/sdk/BUILD.gn, sky/sdk/example/stocks/lib/stock_home.dart, sky/sdk/example/widgets/card_collection.dart, sky/sdk/lib/animation/animated_value.dart, sky/sdk/lib/animation/animation_performance.dart, sky/sdk/lib/rendering/flex.dart, sky/sdk/lib/widgets/animated_container.dart, sky/sdk/lib/widgets/animation_builder.dart, sky/sdk/lib/widgets/dismissable.dart, sky/sdk/lib/widgets/drawer.dart, sky/sdk/lib/widgets/ink_well.dart, sky/sdk/lib/widgets/navigator.dart, sky/sdk/lib/widgets/popup_menu.dart, sky/sdk/lib/widgets/toggleable.dart
Renamed AnimatedType to AnimatedValue.
=> Renamed AnimatedType to AnimatedValue

sky/sdk/example/rendering/interactive_flex.dart, sky/sdk/example/widgets/container.dart, sky/sdk/lib/rendering/box.dart, sky/sdk/lib/widgets/basic.dart, sky/sdk/lib/widgets/icon.dart
This change makes it easier to defined only the width or the height of an image
and let the other value be filled in from the image's intrinsic aspect ratio.
Fixes #175
=> Separate width and height parameters for Image widgets

sky/sdk/lib/sky_tool
Instead, just use a normal http URL.
=> Update sky_tool now that sky:// isn't a thing

sky/sdk/example/widgets/card_collection.dart, sky/sdk/lib/widgets/dismissable.dart
Dismissing causes two animations in sequence: fade out and then resize to zero.
A onResized callback is provided for items that need to notify their BlockViewport about the size change.
=> Dismissable provides intrinsic support for resize animation

sky/sdk/lib/widgets/tool_bar.dart
=> Make center part of toolbar optional.

sky/engine/bindings/scripts/dart_types.py, sky/engine/core/painting/Canvas.cpp, sky/engine/core/painting/Canvas.h, sky/engine/core/painting/Canvas.idl, sky/engine/tonic/float32_list.cc, sky/engine/tonic/float32_list.h, sky/tests/painting/canvas-expected.txt, sky/tests/painting/canvas.dart
Part of fixing issue #138.
R=abarth@google.com
=> Add support for Canvas.setMatrix and getTotalMatrix

sky/tools/gn, sky/tools/gn_test.py
=> Fix gn --ios --simulator to use the right out directory.

sky/tools/gn, sky/tools/gn_test.py
=> Fix sky/tools/gn to not crash

sky/sdk/example/address_book/lib/main.dart
=> Add a dialog to the address book app to test scoped focus.

sky/dist/BUILD.gn, sky/packages/material_design_icons/BUILD.gn, sky/sdk/BUILD.gn, sky/sdk/lib/sky_tool
We now just symlink the lib directory into the packages directory in the output
directory.
=> Remove the magic from the Sky package

DEPS, skia/ext/analysis_canvas.cc, skia/ext/analysis_canvas.h, skia/ext/benchmarking_canvas.cc, skia/ext/benchmarking_canvas.h, skia/ext/pixel_ref_utils.cc, sky/engine/core/painting/Canvas.cpp, sky/engine/platform/graphics/GraphicsContext.cpp, sky/engine/platform/graphics/filters/FilterEffect.cpp
Another patch towards fixing issue #138
R=chinmaygarde@google.com
=> Roll Skia to the latest revision to pick up drawAtlas fix

sky/sdk/example/game/lib/particle_system.dart
Roll was ff8bbe4e1674ae57f2ea3a2841a37a9c099beac8
This is another step in fixing #138
R=viktork@google.com
=> Use Skia's drawAtlas now that we've rolled to a newer Skia

BUILD.gn, sky/dist/BUILD.gn
=> Make the Mac target deps look similar to iOS

.gitignore, AUTHORS, sky/sdk/example/address_book/lib/main.dart, sky/sdk/example/demo_launcher/lib/main.dart, sky/sdk/example/fitness/lib/feed.dart, sky/sdk/example/fitness/lib/fitness_item.dart, sky/sdk/example/fitness/lib/fitness_types.dart, sky/sdk/example/fitness/lib/main.dart, sky/sdk/example/fitness/lib/meal.dart, sky/sdk/example/fitness/lib/measurement.dart, sky/sdk/example/fitness/lib/settings.dart, sky/sdk/example/hello_world/lib/main.dart, sky/sdk/example/mine_digger/lib/main.dart, sky/sdk/example/stocks/lib/main.dart, sky/sdk/example/stocks/lib/stock_arrow.dart, sky/sdk/example/stocks/lib/stock_data.dart, sky/sdk/example/stocks/lib/stock_home.dart, sky/sdk/example/stocks/lib/stock_list.dart, sky/sdk/example/stocks/lib/stock_menu.dart, sky/sdk/example/stocks/lib/stock_row.dart, sky/sdk/example/stocks/lib/stock_settings.dart, sky/sdk/example/stocks/lib/stock_types.dart
Examples converted:
* address_book
* demo_launcher
* fitness
* hello_world
* mine_digger
* stocks
Examples NOT converted:
* game
* raw
* rendering
* widgets
=> Examples as libraries

sky/sdk/example/address_book/lib/main.dart, sky/sdk/example/fitness/lib/feed.dart, sky/sdk/example/stocks/lib/stock_settings.dart, sky/sdk/lib/widgets/dialog.dart, sky/sdk/lib/widgets/navigator.dart, sky/sdk/lib/widgets/widget.dart
Provides a much neater way of handling dialogs. Still some boilerplate (navigator navigator), but one step at a time.
=> pushDialog(navigator, (navigator) => new Dialog(...)).then((result) => process(result));

sky/sdk/lib/widgets/dialog.dart
@abarth doesn't like Futures that explicitly point out they're type-unsafe. :-P
TBR @abarth
=> Fix review feedback from previous checkin.

sky/sdk/example/game/lib/color_secuence.dart, sky/sdk/example/game/lib/particle_system.dart, sky/sdk/example/game/lib/sprite_box.dart, sky/sdk/example/game/lib/util.dart
Refactors randomization of color sequences.
Optimizes particles systems by using a single Paint instance, doesn't compute accelerations in the update method unless neccessary, reduces the number of created objects, faster color calculations, optimizes lookup in fast version of atan2.
Fixes indentation in some places.
=> Optimizations for Particle Systems

DEPS
Fixes #306
TBR=johnmccutchan@google.com
=> Work around pub get going crazy

sky/tools/shelldb, sky/tools/skyanalyzer, sky/tools/webkitpy/layout_tests/run_webkit_tests.py, travis/build.sh
Hopefully this will make Travis green again.
=> Teach skyanalyzer about workbench

sky/packages/sky/lib/widgets/animated_container.dart, sky/packages/sky/lib/widgets/material.dart, sky/packages/sky/lib/widgets/snack_bar.dart
Refactor AnimationContainer to support drop-in Intentions.
This lets us be flexible in how to animate the properties of the container. Currently used by SnackBar with a SlideIn intention.
=> Refactor AnimationContainer to support drop-in Intentions

sky/dist/BUILD.gn, sky/shell/BUILD.gn, sky/shell/mac/platform_service_provider_mac.cc, sky/tools/webkitpy/layout_tests/port/android.py, sky/tools/webkitpy/layout_tests/port/base.py, sky/tools/webkitpy/layout_tests/port/linux.py, sky/tools/webkitpy/layout_tests/port/mac.py
We still have a few tests failing, I believe
due to different font metrics.  Otherwise this works!
R=abarth@google.com
=> Make test_sky work on Mac!

sky/packages/sky/example/game/lib/node.dart, sky/packages/sky/example/game/lib/sprite.dart, sky/packages/sky/example/game/lib/sprite_box.dart
Optimizes sprites by replacing save/restore by caching the total matrix
Optimizes sprite performance by reusing Paint objects
Optimizes sprite performance by minimizing the number of calls to action controllers
=> Optimizations for sprite code

sky/shell/ios/Info.plist, sky/shell/mac/platform_service_provider_mac.cc
=> Fix iOS build

sky/packages/sky/example/game/lib/game_demo_world.dart, sky/packages/sky/example/game/lib/node.dart, sky/packages/sky/example/game/lib/sprite.dart
Also adds optional auto scrolling to star fields
=> Fixes analyzer warnings in sprites

sky/packages/sky/example/game/main.dart
Adds star field to game start screen and it looks great!
=> Adds star field to game start screen

sky/packages/sky/lib/mojo/net/fetch.dart, sky/packages/sky/lib/mojo/net/image_cache.dart
=> Add more logging for the NetworkService unavailable case

services/sky/runtime_flags.cc, services/sky/runtime_flags.h, services/sky/viewer.cc, sky/engine/core/script/dart_init.cc, sky/engine/platform/RuntimeEnabledFeatures.in, sky/engine/public/web/WebRuntimeFeatures.h, sky/engine/web/WebRuntimeFeatures.cpp
This flag will let clients who use release builds enable checked mode.
Fixes #22
=> Add a flag to sky_viewer to enable checked mode

sky/packages/sky/lib/mojo/embedder.dart, sky/packages/sky/lib/mojo/shell.dart, sky/packages/sky/pubspec.yaml, sky/packages/sky_engine/pubspec.yaml, sky/packages/sky_services/BUILD.gn, sky/packages/sky_services/pubspec.yaml
Also, update imports to account for new mojom.dart locations.
=> Rev Dart packages

sky/packages/sky/lib/animation/animated_value.dart, sky/packages/sky/lib/animation/animation_performance.dart, sky/packages/sky/lib/animation/forces.dart, sky/packages/sky/lib/animation/scroll_behavior.dart, sky/packages/sky/lib/widgets/animation_intentions.dart, sky/packages/sky/lib/widgets/drawer.dart, sky/packages/sky/lib/widgets/snack_bar.dart
This required some changes to AnimationPerformance to better understand
animating with forces.
=> Use SnackBar's SlideInIntention for Drawer animation.

sky/shell/android/sky_main.cc, sky/shell/linux/main.cc, sky/shell/mac/platform_mac.mm, sky/shell/shell.cc
Also, make the initialization order the same on every platform.
=> Refactor common startup code into shell.cc

sky/shell/linux/platform_service_provider_linux.cc, sky/shell/mac/platform_service_provider_mac.cc
This was likely a race which caused occasional timeouts.
R=abarth@google.com
=> Fix the service providers to be able to be called more than once.

sky/tools/roll_versions.py
=> Teach roll_versions about sky_services and add mising CHANGELOG.md files

sky/packages/sky/example/demo_launcher/apk/AndroidManifest.xml, sky/packages/sky/example/demo_launcher/apk/release_notes/0.0.21.txt
=> Bump APK version in prep for release

sky/shell/gpu/rasterizer.cc, sky/shell/ui/animator.cc
=> Fix two crashes when resuming apps

sky/shell/shell.cc
Apparently this can cause a crash when when we try to render an emoji at a
different size than the emoji font's native bitmap size. I'm not sure how to
reproduce the issue. I'll ask Hixie when he gets back.
Currently we just use regular memory. In the future, we should actually use
discarable memory.
Fixes #203
=> Call DiscardableMemoryAllocator::SetInstance()

sky/shell/mac/platform_mac.mm
=> Fix Mac/iOS builds

sky/packages/sky/lib/widgets/navigator.dart
Also fix a bug with dismissable.
=> Simplify Navigator's Transition code a bit.

sky/shell/linux/main.cc, sky/shell/mac/main_mac.mm, sky/shell/switches.cc, sky/shell/switches.h, sky/shell/ui/engine.cc
We need a way for developers to use release builds in checked mode.
Progress on #400
=> Add --enable-checked-mode to sky_shell

sky/services/ns_net/url_loader_impl.mm, sky/shell/mac/sky_window.mm
This is a precursor to making shelldb or sky_tool work with the Mac port.
@chinmaygarde
=> Make it possible to pass a URL via command line to Mac SkyShell.app

DEPS
@abarth 
FYI @vlidholt - fixes profiler bug.
=> Bump Dart runtime dependency

sky/tools/big_red_button.py
=> Add a --stage-two to big_red_button.py

sky/tools/big_red_button.py
=> Don't upload things again in stage two

sky/packages/sky/lib/painting/text_style.dart, sky/packages/sky/lib/rendering/paragraph.dart
We were applying the style to the RenderInline but we actually needed to apply
it to the RenderParagraph. The lineHeight property had the same problem.
=> Fix TextAlign.right

sky/engine/core/painting/Canvas.cpp, sky/engine/core/painting/Canvas.h, sky/engine/core/painting/Canvas.idl, sky/engine/core/painting/Rect.dart, sky/packages/sky/example/widgets/block_viewport.dart, sky/packages/sky/example/widgets/sector.dart, sky/packages/sky/lib/painting/box_painter.dart, sky/tests/resources/display_list.dart, sky/tests/widgets/rounded_border-expected.txt, sky/tests/widgets/rounded_border.dart
Currently we support only borders with uniform color and width.
=> Support borders with borderRadius

sky/engine/core/loader/CanvasImageDecoder.cpp, sky/engine/core/painting/Canvas.cpp, sky/engine/core/painting/CanvasImage.cpp, sky/engine/core/painting/CanvasImage.h
Apparently SkImage is the new hotness.
=> Use SkImage instead of SkBitmap

sky/packages/sky/lib/animation/animation_performance.dart, sky/packages/sky/lib/widgets/dismissable.dart, sky/packages/sky/lib/widgets/transitions.dart
=> Use transitions for Dismissable

sky/packages/sky/example/address_book/lib/main.dart, sky/packages/sky/example/demo_launcher/lib/main.dart, sky/packages/sky/example/fitness/lib/main.dart, sky/packages/sky/example/hello_world/lib/main.dart, sky/packages/sky/example/mine_digger/lib/main.dart, sky/packages/sky/example/stocks/lib/main.dart, sky/packages/sky/lib/widgets.dart
Now you can import 'package:sky/widgets.dart' to get all the widgets.
=> Add a widgets.dart uber library

sky/packages/sky/example/game/lib/node.dart
Makes it possible for subclasses to use a custom transform matrix
=> Refactors matrix handling in sprites

sky/packages/sky/example/game/lib/node.dart, sky/packages/sky/example/game/lib/sprite.dart, sky/packages/sky/example/game/lib/sprite_box.dart
Minimizes the number of set/get matrix calls to Skia through the C++ bridge
=> Refactors the sprite matrix handling to do most calculations in Dart

sky/packages/sky/example/game/lib/sprite.dart, sky/packages/sky/example/game/lib/texture.dart
Disables anti alias for sprite drawing
Optimizes texture drawing by removing a canvas.translate call
=> Optimizes drawing performance in sprites

sky/packages/sky/lib/animation/animated_value.dart, sky/packages/sky/lib/animation/animation_performance.dart, sky/packages/sky/lib/animation/curves.dart, sky/packages/sky/lib/animation/direction.dart, sky/packages/sky/lib/animation/forces.dart, sky/packages/sky/lib/rendering/toggleable.dart, sky/packages/sky/lib/widgets/animated_container.dart, sky/packages/sky/lib/widgets/navigator.dart, sky/packages/sky/lib/widgets/popup_menu.dart, sky/packages/sky/lib/widgets/transitions.dart
This ensures we don't run into discontinuities when reversing an
animation halfway through. I refactored AnimationValue to have knowledge
of the reverse curves and intervals.
=> When animating, use the same curve until it completes.

sky/tools/skydoc.py
=> Fix skydoc to work again

sky/tests/examples/stocks-expected.txt, sky/tests/examples/tabs-expected.txt
=> Updated expected.txt files for stocks, tabs

sky/shell/ios/Info.plist, sky/shell/ios/sky_surface.mm
- Make space for the iOS status bar.
- Set the iOS status bar to use white text.
=> A couple of pieces of polish for iOS.

sky/packages/sky/example/widgets/big_switch.dart, sky/packages/sky/lib/base/hit_test.dart, sky/packages/sky/lib/painting/radial_reaction.dart, sky/packages/sky/lib/widgets/basic.dart, sky/packages/sky/lib/widgets/framework.dart, sky/packages/sky/lib/widgets/switch.dart
We still need to tune the various parameters, but this patch is a start.
=> Add a basic radial reaction to the switch

sky/packages/sky/lib/rendering/block.dart
We'll need this for horizontally scrolling lists.
=> Teach Block how to layout horizontally

sky/packages/sky/example/widgets/horizontal_scrolling.dart, sky/packages/sky/lib/rendering/box.dart, sky/packages/sky/lib/widgets/basic.dart, sky/packages/sky/lib/widgets/scrollable.dart, sky/packages/sky/lib/widgets/tabs.dart
Now ScrollableBlock can combine a horizontally scrolling viewport with a
horizontal block.
Also rename ViewportScrollDirection to just ScrollDirection for less verbosity.
=> Teach ScrollableBlock how to scroll horizontally

sky/packages/sky/example/widgets/horizontal_scrolling.dart, sky/packages/sky/lib/rendering/box.dart
Add operator+ and operator- to EdgeDims
... and use them to improve the horizontal_scrolling example.
=> Add operator+ and operator- to EdgeDims

sky/packages/sky/example/game/test_performance.dart
Adds 2 new cases for testing sprite curl performance.
=> Improvements to game performance tests

sky/services/activity/activity.mojom, sky/services/activity/src/org/domokit/activity/ActivityImpl.java
I'll use them in Fitness App in a follow-up patch.
@abarth
=> Add getCacheDir and getFilesDir to Activity.mojom

sky/packages/sky/lib/sky_tool, sky/shell/android/org/domokit/sky/shell/SkyActivity.java, sky/shell/android/org/domokit/sky/shell/SkyMain.java, sky/shell/android/sky_main.cc, sky/shell/ui/engine.cc
The --checked argument runs SkyShell in checked mode, which turns on type
checking and asserts.
=> Add a --checked argument to sky_tool start

sky/packages/sky_engine/pubspec.yaml, sky/packages/sky_services/pubspec.yaml, sky/tools/big_red_button.py
Also, teach big_red_button how to make a REVISION file in sky_engine/lib.
=> Rev pub packages

examples/game/lib/particle_system.dart
Makes sure doubles in particles never are null. Particle performance test shows gain of 5%.
=> Improves particle performance

sky/packages/sky/lib/animation/animation_performance.dart, sky/packages/sky/lib/animation/forces.dart, sky/packages/sky/lib/widgets/dismissable.dart, sky/packages/sky/lib/widgets/drawer.dart
Just infer it from the sign of the velocity. That's what odeon does.
=> Get rid of the Direction parameter for animation Forces.

services/sky/compositor/layer.cc, services/sky/compositor/layer.h, services/sky/document_view.cc, sky/engine/public/sky/sky_view.cc, sky/engine/public/sky/sky_view.h, sky/shell/gpu/ganesh_surface.cc, sky/shell/gpu/ganesh_surface.h, sky/shell/gpu/rasterizer.cc, sky/shell/gpu/rasterizer.h, sky/shell/gpu_delegate.h, sky/shell/ui/animator.cc, sky/shell/ui/engine.cc, sky/shell/ui/engine.h
Now that we can use WTF everywhere, we don't need to use skia::RefPtr.
=> Swith from skia::RefPtr to RefPtr

examples/game/lib/game_demo_world.dart, examples/game/lib/layer.dart, examples/game/lib/node_with_size.dart, examples/game/lib/sprite.dart, examples/game/lib/sprites.dart
- Adds a new Layer class that uses Skia's saveLayer, this is useful for applying effects to a sub-tree of the sprite tree.
- Refactors sprite class to use SpritePaint mix-in to avoid duplication of code with the new Layer class.
- Updates demo game with changes to Sprites and Nodes.
=> Adds new Layer class to sprites

examples/fitness/lib/fitness_item.dart, examples/fitness/lib/main.dart, examples/fitness/lib/measurement.dart, examples/fitness/lib/user_data.dart, examples/fitness/pubspec.yaml, sky/packages/sky/lib/mojo/activity.dart
This required me wrapping the new Activity APIs
as well as adding the missing pubspec.yaml
@abarth
=> Make it possible to save/load fitness measurements

examples/fitness/lib/feed.dart
Fixes https://github.com/domokit/sky_engine/issues/540
@abarth
=> Fix typo in feed icon in drawer

examples/fitness/lib/measurement.dart
Fixes https://github.com/domokit/sky_engine/issues/548
@collinjackson
=> Reduce precision shown for measurements

examples/fitness/lib/settings.dart
Fixes https://github.com/domokit/sky_engine/issues/547
@collinjackson
=> Remove non-working Height setting

sky/packages/sky/lib/mojo/activity.dart, sky/services/activity/activity.mojom, sky/services/activity/src/org/domokit/activity/ActivityImpl.java
=> Add support for immersive mode on Android

DEPS
Includes Dart_TimelineGetTrace API refactor.
=> Roll Dart forward

examples/fitness/lib/date_utils.dart, examples/fitness/lib/fitness_item.dart, examples/fitness/lib/main.dart, examples/fitness/lib/measurement.dart
Moved from Cards to Tiles and made the printing
of the dates nicer by using some code from a Dart SDK example:
https://github.com/dart-lang/sdk/blob/master/samples-dev/swarm/swarm_ui_lib/util/DateUtils.dart
I also built a UserData class to help keep saving/sorting
consistent as well as fixed the sort order to have most
recent at the top.
@abarth
=> Make Fitness tiles nicer

sky/packages/sky/lib/rendering/box.dart, sky/packages/sky/lib/rendering/object.dart
In refactoring the way we generate the SkPicture, I accidentially made us
generate the SkPicture twice. This CL causes us to generate it only once.
=> Don't paint twice

examples/stocks/lib/stock_row.dart, sky/packages/sky/lib/theme/theme_data.dart, sky/packages/sky/lib/widgets/ink_well.dart
And also Material Design of course.
Also removed the splashes from the Stocks List since those made no UX sense.
@abarth
=> Attempt to make our splashes closer to other Android apps

examples/widgets/ensure_visible.dart, sky/packages/sky/lib/widgets/scrollable.dart, sky/packages/sky/lib/widgets/tabs.dart
Adds ensureWidgetIsVisible() function to scrollable.dart
Set the scrollOffset of a widget's Scrollable ancestor so that the
widget is centered within the scrollable. A future CL will add
support for specifying exactly where the widget appears. The scroll
can be animated by specifying the animation: parameter.
Changed the duration Scrollable.scrollTo() parameter from a Duration
to an AnimationPerformance so that one can configure all aspects of
the animation. The caller may also listen to the animation to schedule
other work while it updates or when its status changes.
=> Adds ensureWidgetIsVisible() function to scrollable.dart

examples/game/lib/sprite_box.dart, examples/rendering/sector_layout.dart, examples/rendering/touch_demo.dart, sky/packages/sky/lib/rendering/auto_layout.dart, sky/packages/sky/lib/rendering/block.dart, sky/packages/sky/lib/rendering/box.dart, sky/packages/sky/lib/rendering/flex.dart, sky/packages/sky/lib/rendering/object.dart, sky/packages/sky/lib/rendering/paragraph.dart, sky/packages/sky/lib/rendering/stack.dart, sky/packages/sky/lib/widgets/checkbox.dart, sky/packages/sky/lib/widgets/ink_well.dart, sky/packages/sky/lib/widgets/scaffold.dart, sky/packages/sky/lib/widgets/switch.dart, sky/packages/sky/lib/widgets/tabs.dart, sky/tests/resources/display_list.dart
We'll need this for compositing because we need to switch out the sky.Canvas
when we switch compositing layers.
=> Add PaintingContext which has-a sky.Canvas instead of is-a sky.Canvas

sky/packages/sky/lib/rendering/object.dart
This patch prepares for introducing the compositing system by repurposing the
relevant parts of the createsNewDisplayList system. This patch also removes the
no-longer-relevant parts of that system.
=> Rename createsNewDisplayList to requiresCompositing

examples/game/lib/game_demo_world.dart, examples/game/lib/main.dart, examples/game/lib/sound.dart, examples/game/lib/sprites.dart
First pass on a sound API, still lots of todos.
=> Adds rough sound support for sprites

sky/packages/sky/lib/rendering/box.dart, sky/packages/sky/lib/rendering/layer.dart, sky/packages/sky/lib/rendering/object.dart, sky/tests/resources/display_list.dart
Currently we have a single PictureLayer that everyone draws into. A future
patch will teach the system to use multiple PictureLayers.
=> Switch painting over to using PictureLayer

sky/engine/core/painting/Picture.cpp, sky/engine/core/painting/Picture.h, sky/engine/core/painting/Picture.idl, sky/engine/core/painting/Rect.dart, sky/packages/sky/lib/rendering/box.dart, sky/packages/sky/lib/rendering/layer.dart, sky/packages/sky/lib/rendering/object.dart, sky/packages/sky/lib/rendering/sky_binding.dart, sky/tests/resources/display_list.dart
Now we have the ability to draw multiple PictureLayers. We still squash all the
pictures together into a single SkPicture for simplicity. In the future, we'll
submit them to C++ separately and composite them on the GPU thread.
=> Add a compositing step to the lifecycle

examples/game/lib/game_demo_world.dart, examples/game/lib/main.dart, examples/game/lib/sound.dart
Removes the ability to jump to different positions in sound effects (not supported on Andriod)
Renames sound effect classes
Renames sound callbacks
Adds a SoundTrackPlayer class for playing background music that is streamed
Unifies the interface for SoundTrackPlayer and SoundEffectPlayer
Adds background music to demo game
=> Updates to game sound API

examples/widgets/ensure_visible.dart, sky/packages/sky/lib/animation/animation_performance.dart, sky/packages/sky/lib/widgets/scrollable.dart, sky/packages/sky/lib/widgets/tabs.dart
Used for AnimationPerformance with a single AnimatedValue<T> variable.
=> Add a ValueAnimation helper class for AnimationPerfomance.

sky/packages/sky/lib/base/debug.dart, sky/packages/sky/lib/rendering/layer.dart
This patch makes it easier to debug layerization issues.
=> Add debug painting for layer borders

examples/mine_digger/lib/main.dart, sky/packages/sky/lib/mojo/activity.dart, sky/services/activity/BUILD.gn, sky/services/activity/activity.mojom, sky/services/activity/src/org/domokit/activity/ActivityImpl.java, sky/services/activity/src/org/domokit/activity/UserFeedbackImpl.java
And use the service in mine_digger to notify the user when they flag a bomb.
=> Add haptic and aural feedback service

examples/game/lib/sound.dart, examples/game/lib/sound_manager.dart, examples/game/lib/sprites.dart
Adds class for playing sound events and background music. Not yet tested as work still remains for the sound bindings before this can actually be used.
=> Adds SoundManager class

sky/tools/roll_apk_version.py, sky/tools/roll_pub_versions.py
Also fixed the url in roll_pub_versions CHANGELOG.md message.
@abarth
=> Remove more dead code from roll_apk_version

sky/packages/material_design_icons/README.md, sky/packages/material_design_icons/pubspec.yaml
Update the readme for the material design package; fix https://github.com/domokit/sky_engine/issues/634.
=> update the readme for the material design package

DEPS, sky/engine/core/script/dart_controller.cc
Tracking issue https://github.com/domokit/sky_engine/issues/654
=> Roll back dart dependency to work around build errors

examples/raw/hello_world.dart, examples/raw/painting_node.dart, examples/raw/shadow.dart, examples/raw/spinning_image.dart, examples/rendering/align_items.dart, examples/rendering/baseline.dart, examples/rendering/interactive_flex.dart, examples/rendering/justify_content.dart, examples/rendering/render_paragraph.dart, examples/rendering/touch_demo.dart, examples/widgets/progress_indicator.dart
We had a remarkable number of analyzer failures.
I'll fix the bots to analyze across the whole project
in a follow-up patch, that should prevent this
in the future.
@abarth
=> Fix analyzer warnings

examples/game/lib/main.dart, examples/game/lib/sound.dart, examples/game/lib/sound_manager.dart, examples/game/lib/sprites.dart, sky/packages/sky/lib/mojo/asset_bundle.dart, sky/packages/sky/lib/mojo/net/fetch.dart
=> Teach Asteroids Sounds how to load from AssetBundle

DEPS, sky/engine/core/script/dart_controller.cc
=> Fix iOS build breaks due to recent dart roll

sky/tools/skyanalyzer, travis/build.sh
I didn't understand what was going on before. Now I do. This is a better fix that making the path absolute.
=> Fix analyzer to not change the working directory.

examples/demo_launcher/lib/main.dart, sky/packages/sky/lib/painting/box_painter.dart, sky/packages/sky/lib/rendering/box.dart
These properties should apply to foreground images as well as background
images. Also, rename these types from BackgroundFit and BackgroundRepeat
because they apply to things other than backgrounds.
=> Apply ImageFit and ImageRepeat to RenderImage

sky/packages/sky/lib/rendering/proxy_box.dart, sky/packages/sky/lib/widgets/basic.dart
This feature lets you create effects similar to the "outline" property in CSS.
=> Add the ability to draw a foreground box decoration

examples/widgets/tabs.dart, sky/packages/sky/lib/editing/input.dart, sky/packages/sky/lib/widgets/framework.dart, sky/tests/widgets/syncs1.dart
For great constness.
Fixes #693
=> Key should be const

sky/packages/sky/lib/widgets/block_viewport.dart, sky/packages/sky/lib/widgets/framework.dart, sky/packages/sky/lib/widgets/scaffold.dart
This function just calls remove(). Also, have Widget do the recursive remove
walk by calling walkChildren.
=> Remove Widget.removeChild

examples/widgets/big_circle.dart, sky/packages/sky/lib/painting/box_painter.dart
We now support uniform borders on circular box decorations.
Fixes #741
=> Add the ability to draw borders on circles

examples/address_book/lib/main.dart, examples/fitness/lib/feed.dart, examples/fitness/lib/meal.dart, examples/fitness/lib/measurement.dart, examples/fitness/lib/settings.dart, examples/stocks/lib/stock_settings.dart, examples/widgets/card_collection.dart, examples/widgets/ensure_visible.dart, examples/widgets/horizontal_scrolling.dart, examples/widgets/mixed_viewport.dart, examples/widgets/overlay_geometry.dart, examples/widgets/pop_out_and_expand.dart, sky/packages/sky/lib/widgets.dart, sky/packages/sky/lib/widgets/basic.dart, sky/packages/sky/lib/widgets/dialog.dart, sky/packages/sky/lib/widgets/drawer.dart, sky/packages/sky/lib/widgets/mixed_viewport.dart, sky/packages/sky/lib/widgets/popup_menu.dart, sky/packages/sky/lib/widgets/scrollable.dart, sky/packages/sky/lib/widgets/widgets.md
Block -> BlockBody
ScrollableBlock -> Block
FixedHeightScrollable -> ScrollableWidgetList
VariableHeightScrollable -> ScrollableMixedWidgetList
BlockViewport -> MixedViewport
=> Rename all the scrollable classes

examples/fitness/lib/feed.dart, examples/fitness/lib/main.dart, sky/packages/sky/lib/widgets/framework.dart
=> Don’t flash a message while fitness data is loading

sky/tools/run_tests, travis/build.sh
Hopefully this will reduce the flakiness we're seeing on the bot.
=> Run tests one-at-a-time on Travis

examples/fitness/lib/settings.dart, examples/stocks/lib/stock_home.dart, examples/stocks/lib/stock_settings.dart
Mostly formating and removing arguments with default values.
=> Address review comments from #767

services/sky/BUILD.gn, services/sky/document_view.cc, services/sky/document_view.h, services/sky/internals.cc, services/sky/internals.h, sky/shell/ui/engine.cc
=> Add support for skyx to sky_viewer.mojo

examples/widgets/pop_out_and_expand.dart, sky/packages/sky/lib/widgets/mimic.dart, sky/packages/sky/lib/widgets/mimic_overlay.dart
We now have Mimic tracking Mimicable through tree structure changes and while
moving around the screen.
Fixes #751 and #756
=> Mimic should track Mimicable more completely

sky/packages/sky/lib/widgets/framework.dart
...rather than the stack trace at the time the RenderObjectWrapper updates the RenderObject.
Also, hide some of the debug-only fields behind "debug" prefixes and assert()s.
=> Track the last component to build

sky/packages/sky/lib/widgets/README.md, sky/packages/sky/lib/widgets/basic.dart, sky/packages/sky/lib/widgets/dialog.dart, sky/packages/sky/lib/widgets/drawer_header.dart, sky/packages/sky/lib/widgets/drawer_item.dart, sky/packages/sky/lib/widgets/snack_bar.dart, sky/packages/sky/lib/widgets/tabs.dart, sky/packages/sky/lib/widgets/tool_bar.dart, sky/packages/sky/lib/widgets/widgets.md
I updated everything in widgets/, but didn't update any examples.
=> Add `Row` and `Column` widgets so you don't have to use Flex.

examples/game/lib/constraint.dart, examples/game/lib/game_demo.dart, examples/game/lib/game_demo_node.dart, examples/game/lib/sprites.dart, examples/game/lib/virtual_joystick.dart
Adds virtual joystick to sprites library
Adds base rotation property to rotate-to-movement constraint
Removes custom joystick code from demo game and adds new moving enemy to demo game
=> Additions to demo game

sky/packages/sky/lib/widgets/scrollable.dart
Added Scrollable named parameter initializeScrollOffset. If unspecified, then the initial value of scrollOffset is 0.0 as before.
=> Enable initializing scroll offset

examples/fitness/lib/feed.dart, examples/fitness/lib/main.dart
I'm not sure this is the correct approach, but it
at least mitigates https://github.com/domokit/sky_engine/issues/804
for now.
I also made it not crash if you haven't set a goalWeight.
@collinjackson
=> Hack around Fitness.app crashing if it can't load data

examples/fitness/pubspec.yaml
=> Move Fitness.app to the latest playfair

sky/engine/core/compositing/Scene.cpp, sky/engine/core/compositing/Scene.h, sky/engine/core/compositing/Scene.idl, sky/engine/core/compositing/SceneBuilder.cpp, sky/engine/core/compositing/SceneBuilder.h, sky/engine/core/compositing/SceneBuilder.idl, sky/engine/core/core.gni, sky/engine/core/painting/Canvas.cpp, sky/engine/core/painting/CanvasPath.cpp, sky/engine/core/painting/CanvasPath.h, sky/engine/core/painting/Matrix.cpp, sky/engine/core/painting/Matrix.h, sky/engine/core/painting/Path.idl, sky/engine/core/painting/RRect.cpp, sky/engine/core/painting/RRect.h, sky/engine/core/view/View.h, sky/engine/core/view/View.idl, sky/engine/public/sky/sky_view.cc, sky/packages/sky/lib/rendering/layer.dart, sky/packages/sky/lib/rendering/view.dart
We still use SkPicture as our rasterization backend, but now we're uploading
our layer tree to C++. A future patch will push the layer tree deeper into the
system and we'll eventually switch backends.
=> Use sky.SceneBuilder to upload Layer tree to C++

sky/tools/webkitpy/layout_tests/run_webkit_tests.py
If we want to run the analyzer, we should do that as a separate step.
=> test_sky shouldn't run skyanalyzer

examples/demo_launcher/apk/AndroidManifest.xml, examples/demo_launcher/apk/release_notes/0.0.24.txt, examples/fitness/apk/AndroidManifest.xml, examples/fitness/apk/release_notes/0.0.4.txt
=> Roll APK versions in preparation for releases

examples/game/lib/action_spline.dart, examples/game/lib/constraint.dart, examples/game/lib/game_demo.dart, examples/game/lib/game_demo_node.dart, examples/game/lib/util.dart
Removes old code from demo game
Makes the spline tension editable in sprite animations
Adds constraint for rotating a node towards another node
Adds swarms of enemies to demo game
=> Updates to demo game

sky/unit/test/widget/align_test.dart
This test just exercises Align to make sure it can sync.
=> Add a test for #833

.gitignore, DEPS
=> Pull in mojo/devtools via DEPS

examples/game/lib/game_demo_node.dart, examples/game/lib/game_objects.dart
Adds power ups to demo game (just coins so far)
Refactorings to support the addition
=> Adds power ups to demo game

sky/packages/sky/lib/sky_tool
=> Automatically update apk on device.

sky/packages/sky/lib/rendering/box.dart, sky/packages/sky/lib/rendering/flex.dart, sky/packages/sky/lib/widgets/sizing.md
This hopefully explains things well enough that it helps with the Block case in #846.
=> Update the documentation on sizing, make another assert point to it.

sky/packages/sky/lib/widgets/date_picker.dart, sky/tools/run_tests, sky/unit/test/widget/build_utils.dart, sky/unit/test/widget/date_picker_test.dart
Most of this work in this patch is building out the test framework to the point
where we can write this test.
=> Add a basic test for DatePicker

examples/rendering/flex.dart, examples/rendering/render_grid.dart, sky/packages/sky/lib/rendering.dart, sky/packages/sky/lib/rendering/grid.dart
I'll write the Widget wrapper in the next CL, including adding
support for padding at the Widget layer.
@Hixie
=> Add support for RenderGrid

sky/packages/sky/lib/rendering/block.dart, sky/packages/sky/lib/rendering/proxy_box.dart, sky/packages/sky/lib/widgets/basic.dart, sky/unit/test/rendering/shrink_wrap_test.dart
- add debugDescribeSettings to a few classes that were missing it
- fix some minor bugs in RenderShrinkWrapWidth and ShrinkWrapWidth
- introduce RenderShrinkWrapHeight and ShrinkWrapHeight
=> ShrinkWrapHeight widget

sky/packages/sky/lib/widgets/progress_indicator.dart, sky/unit/test/widget/build_utils.dart, sky/unit/test/widget/progress_indicator_test.dart
Set the the ProgressIndicator's CustomPaint token to the ProgressIndicator's value.
=> Fix ProgressIndicators

sky/unit/test/rendering/shrink_wrap_test.dart, sky/unit/test/widget/build_utils.dart, sky/unit/test/widget/progress_indicator_test.dart
We can make all the test pass by removing more of the mocks and using the real
code.
=> Merge pumpPaintFrame and pumpFrame in WidgetTester

sky/packages/sky/lib/base/image_resource.dart, sky/packages/sky/lib/widgets/basic.dart
=> Add logging to help diagnose image loading failures

sky/packages/sky/pubspec.yaml
=> Update version of mojo and mojo_services to 0.0.23 for sky dart.

sky/packages/sky/lib/widgets/scrollable.dart, sky/unit/pubspec.yaml, sky/unit/test/widget/pageable_list_test.dart, sky/unit/test/widget/widget_tester.dart
Also includes changes to widget_tester sufficient to
test scrolling.
@abarth
=> Add a pageChanged callback to PageableList

sky/packages/sky/lib/rendering/object.dart
Previously, if you used a layout callback, you could not have a parent
that did parentUsesSize, or if you did, you had to be marked
sizedByParent. With this patch, we allow the parent to depend on your
layout, even if you modify your child list during your layout using a
layout callback, by checking that the parent is still actively being
laid out in this scenario.
=> Allow parents of RenderObjects that have layout callbacks to depend on those objects' sizes.

sky/packages/sky/lib/rendering/grid.dart, sky/packages/sky/lib/widgets/basic.dart, sky/unit/test/rendering/grid_test.dart
Happy to add tests with some explanation as to how.
@abarth
=> Add basic Grid widget and test RenderGrid

sky/packages/sky/lib/gestures/arena.dart, sky/unit/test/gestures/arena_test.dart
In the GestureArena, gestures will fight it out to see which is the real
ultimate gesture.
=> Add GestureArena

ui/gl/BUILD.gn
=> Fix build on Mac

sky/unit/test/rendering/grid_test.dart
=> Fix analyzer warning

sky/services/engine/sky_engine.mojom, sky/services/pointer/BUILD.gn, sky/services/pointer/pointer.mojom, sky/shell/ui/engine.cc, sky/shell/ui/engine.h
We don't use this interface yet.
=> Add a mojom for delivering pointer events in packets

examples/demo_launcher/lib/main.dart, examples/fitness/lib/feed.dart, examples/fitness/lib/meal.dart, examples/fitness/lib/measurement.dart, examples/mine_digger/lib/main.dart, examples/widgets/ensure_visible.dart, examples/widgets/mixed_viewport.dart, examples/widgets/pop_out_and_expand.dart, examples/widgets/progress_indicator.dart, sky/packages/sky/lib/widgets.dart, sky/packages/sky/lib/widgets/date_picker.dart, sky/packages/sky/lib/widgets/dialog.dart, sky/packages/sky/lib/widgets/drawer.dart, sky/packages/sky/lib/widgets/drawer_item.dart, sky/packages/sky/lib/widgets/floating_action_button.dart, sky/packages/sky/lib/widgets/icon_button.dart, sky/packages/sky/lib/widgets/material_button.dart, sky/packages/sky/lib/widgets/modal_overlay.dart, sky/packages/sky/lib/widgets/popup_menu_item.dart, sky/packages/sky/lib/widgets/radio.dart, sky/packages/sky/lib/widgets/snack_bar.dart, sky/packages/sky/lib/widgets/tabs.dart, sky/unit/test/widget/widget_tester.dart
We're now using it at the widget layer for everything except scrolling and
flinging.
=> Use GestureDetector in the framework and examples

sky/packages/sky/lib/gestures/recognizer.dart, sky/packages/sky/lib/gestures/scroll.dart, sky/packages/sky/lib/gestures/show_press.dart, sky/packages/sky/lib/gestures/tap.dart, sky/packages/sky/lib/widgets/gesture_detector.dart, sky/packages/sky/lib/widgets/scrollable.dart, sky/unit/test/gestures/scroll_test.dart, sky/unit/test/widget/widget_tester.dart
This patch replaces the scroll gestures used by Scrollable with ones detected
by the ScrollGestureDetector.
=> Add scroll gestures and use them in Scrollable

sky/packages/sky/lib/gestures/scroll.dart, sky/packages/sky/lib/widgets/scrollable.dart, sky/unit/test/gestures/scroll_test.dart
Instead, we pump a onScrollUpdate with the offset if there is an offset.
=> onScrollStart shouldn't have an offset

sky/packages/sky/lib/widgets/mixed_viewport.dart
...and not when we mount and dismount.
Turns out that when we dismount, it's too late -- we've already set renderObject to null.
We also mark the mixed viewport as dirty when it is removed from its parent.
Without this, we try to reuse the child nodes in subsequent syncs, which is a disaster.
This also moves the ownership of the actual list of children back into MixedViewport. It scares me that the MixedViewport owner controls the lifetime of the MixedViewport child list.
=> Set and remove the callbacks on the RenderObject when we create and remove it.

sky/unit/test/widget/mixed_viewport_test.dart
=> Remove unused import to make analyzer happy

sky/packages/sky/lib/painting/box_painter.dart
We just need to enforce some finite clamp and Skia will do the rest.
Fixes #939
=> BoxDecoration's borderRadius should be able to handle a value of double.INFINITY

sky/packages/sky/lib/rendering/flex.dart, sky/unit/test/widget/flex_test.dart
We were setting the main axis extent to zero because we had a sign error.
Fixes #918
=> onPressed not called when in a Positioned Flex

sky/packages/sky/lib/painting/box_painter.dart, sky/packages/sky/lib/painting/radial_reaction.dart, sky/packages/sky/lib/painting/shadows.dart, sky/packages/sky/lib/painting/text_painter.dart, sky/packages/sky/lib/painting/text_style.dart, sky/packages/sky/lib/widgets/README.md, sky/packages/sky/lib/widgets/animated_container.dart
=> Add dartdoc for the painting code

sky/packages/sky/lib/rendering/proxy_box.dart, sky/packages/sky/lib/widgets/basic.dart, sky/unit/test/widget/transform_test.dart, sky/unit/test/widget/widget_tester.dart
This parameter makes it easier to do math when you don't want to center your
tranform at (0, 0).
=> Add an origin parameter to transforms

sky/packages/sky/lib/widgets/basic.dart
=> Basic widgets should validate their parameters with asserts

sky/packages/sky/lib/widgets/card.dart, sky/packages/sky/lib/widgets/popup_menu_item.dart
These constants aren't useful outside these files and are cause noise in the
dartdoc.
=> Make these constants private

examples/address_book/lib/main.dart
=> Remove the silly dialog.

sky/packages/sky/lib/rendering.dart, sky/packages/sky/lib/rendering/object.dart, sky/packages/sky/lib/widgets.dart
... and other code in object.dart.
=> Add dartdocs for RenderObject

examples/fitness/apk/AndroidManifest.xml, sky/build/sky_app.gni, sky/shell/BUILD.gn, sky/shell/android/AndroidManifest.xml, sky/shell/android/library_loader.cc, sky/shell/android/org/domokit/sky/shell/SkyApplication.java, sky/shell/android/org/domokit/sky/shell/UpdateService.java, sky/shell/android/update_service_android.cc, sky/shell/android/update_service_android.h
Very simple so far. This schedules an alarm to fire once a day, kicking off a service that downloads a new app.skyx from a hardcoded URL. The new skyx replaces the current one.
=> Introduce an UpdateService for android

sky/tools/skyx/bin/skyx.dart
=> Fix a type error being triggered when this is being run as a snapshot.

services/sky/compositor/BUILD.gn, services/sky/compositor/layer_host.cc, services/sky/compositor/layer_host.h, services/sky/compositor/resource_manager.cc, services/sky/compositor/resource_manager.h, services/sky/compositor/texture_layer.cc, services/sky/compositor/texture_layer.h, services/sky/document_view.cc, services/sky/document_view.h
This prepares for adding `//sky/compositor`
=> Rename sky::Layer to sky::TextureLayer

examples/game/lib/game_demo_node.dart, examples/game/lib/game_objects.dart, examples/game/lib/player_state.dart
Adds speed boost power up
Improves laser upgrade
=> Improvements to demo game

sky/compositor/BUILD.gn, sky/compositor/layer.cc, sky/compositor/layer.h, sky/engine/core/BUILD.gn, sky/engine/core/compositing/Scene.cpp, sky/engine/core/compositing/Scene.h, sky/engine/core/compositing/SceneBuilder.cpp, sky/engine/core/compositing/SceneBuilder.h, sky/engine/public/sky/sky_view.cc
We now build a layer tree before squashing the draw command down to an
SkPicture.
=> SceneBuilder should build a tree of layers

examples/game/lib/game_objects.dart, skysprites/lib/constraint.dart, skysprites/lib/util.dart
Adds coins when a boss explodes
Adds new constraint for aligning a node with another node
Refactors boss power bar to use new constraint
=> Demo game improvements

examples/widgets/card_collection.dart, sky/packages/sky/lib/src/widgets/dismissable.dart
Add Dismissable support for DismissDirection
```
enum DismissDirection {
vertical,
horizontal,
left,
right,
up,
down
}
```
To only enable dismissing to the right create the `Dismissable` with `direction: DismissDirection.right`. By default direction is `DismissDirection.horizontal` (left or right). 
Updated the card_collection "Swipe Away" demo with a drawer that can be used to select one of the three X axis dismiss directions. Currently the MixedViewport class doesn't support horizontal scrolling, so the demo doesn't support the X axis dismiss directions.
=> Add Dismissable support for DismissDirection

sky/packages/sky/lib/painting/box_painter.dart, sky/packages/sky/lib/src/rendering/shifted_box.dart, sky/packages/sky/lib/src/widgets/basic.dart
They're just as crazy in this system as they are in the web.
=> Disallow negative padding and margins

examples/widgets/card_collection.dart, sky/unit/test/widget/dismissable_test.dart, sky/unit/test/widget/widget_tester.dart
Add coverage for the DismissDirection paramter.
=> Add Dismissable unit tests

.travis.yml, sky/packages/sky/.gitignore, sky/packages/sky/doc/firebase.json, sky/packages/sky/lib/rendering.dart, sky/packages/sky/lib/src/widgets/framework.dart, sky/packages/sky/lib/widgets.dart, sky/tools/skydoc.py, travis/build.sh, travis/setup.sh
- working on generating docs as part of the build
I created this PR to see how happy travis is with the changes; not yet ready for review :)
=> working on generating docs as part of the build

examples/rendering/sector_layout.dart, examples/widgets/styled_text.dart, sky/packages/sky/lib/src/rendering/block.dart, sky/packages/sky/lib/src/rendering/box.dart, sky/packages/sky/lib/src/rendering/image.dart, sky/packages/sky/lib/src/rendering/proxy_box.dart, sky/packages/sky/lib/src/rendering/stack.dart, sky/packages/sky/lib/src/widgets/basic.dart, sky/unit/test/rendering/box_test.dart
Turns out many of the functions on BoxConstraints weren't used or had callers
that could easily be updated to other functions. I've added dartdoc to all the
public functions as well as renamed some functions that had similar names but
did different things.
=> Document and bring sanity to BoxConstraints

sky/compositor/layer.h, sky/shell/gpu/rasterizer.cc
We'll need to make this fancier as the compositor gets smarter.
=> Add a sketchy function for serializing SkPictures

sky/packages/sky/lib/src/widgets/framework.dart
...which I accidentally changed in a previous commit.
=> Fix signature of toStringName()

sky/tools/skyx/bin/skyx.dart
=> The skyx tool shouldn't crash if an icon variant doesn't exist

examples/mine_digger/lib/main.dart
@cpu-chromium onLongPress handler wasn't getting added when state == flagged.
=> mine_digger: Fix not being able to de-flag on Android

examples/fitness/sky.yaml, sky/shell/BUILD.gn, sky/shell/android/org/domokit/sky/shell/UpdateService.java, sky/shell/android/update_service_android.cc, sky/shell/android/update_service_android.h, sky/shell/updater/manifest.cc, sky/shell/updater/manifest.h, sky/shell/updater/update_task.cc, sky/shell/updater/update_task.h
The version and update URL are stored in the app's manifest (sky.yaml).
=> Compare versions before updating an app bundle.

sky/shell/updater/update_task.h
Remove JNI junk from platform-independent code.
=> Fix the build

sky/shell/updater/update_task.h
=> Fix Linux build

examples/widgets/spinning_mixed.dart, sky/packages/sky/lib/src/rendering/layer.dart, sky/packages/sky/lib/src/rendering/object.dart, sky/packages/sky/lib/src/rendering/paragraph.dart, sky/packages/sky/lib/src/rendering/sky_binding.dart, sky/packages/sky/lib/src/rendering/stack.dart, sky/packages/sky/lib/src/rendering/view.dart, sky/packages/sky/lib/src/rendering/viewport.dart
The docs will continue until morale improves
@Hixie
=> Add some more docs to the rendering library

examples/widgets/sector.dart, sky/packages/sky/lib/src/rendering/error.dart, sky/packages/sky/lib/src/rendering/grid.dart, sky/packages/sky/lib/src/rendering/proxy_box.dart, sky/packages/sky/lib/src/widgets/basic.dart, sky/packages/sky/lib/src/widgets/dialog.dart, sky/packages/sky/lib/src/widgets/popup_menu.dart, sky/unit/test/rendering/intrinsic_width_test.dart
Almost done adding dartdoc to the rendering layer.
=> Add dartdoc for proxy_box.dart and other code in rendering

sky/packages/sky/lib/src/rendering/proxy_box.dart
=> Address more comments from #1153

sky/packages/sky/lib/src/animation/animated_value.dart, sky/packages/sky/lib/src/animation/animation_performance.dart, sky/packages/sky/lib/src/animation/curves.dart
Surface all the constructor arguments of AnimationTiming in all its subclasses.
Remove some pointless casts.
Fix some typos.
Put constructors first in class declarations.
Remove some blank lines where they just confused the structure of the code.
=> Clean up animation-related files.

sky/packages/sky/lib/src/widgets/framework.dart
This specifically improves the reporting of exceptions in syncChild(),
and makes the way we've been adding information to toStringName() less
ad-hoc and easier to extend.
=> Improve exception reporting in Widgets framework

sky/packages/sky/lib/src/widgets/framework.dart
If a StatefulComponent marks itself dirty, gets rebuilt, then its parent
gets rebuilt, its parent will find that its child is from a newer
generation and hasn't changed. Previously, we considered two stateful
nodes to not be syncable even if they were the same; combined with the
way the "old" node looks like it's been put elsewhere (since it's
already been synced), we end up confused as to why the new node is
already mounted.
This fixes the problem by making the canSync logic consider two
identical nodes as syncable (since they are; syncChild() short-circuits
that case), and by changing syncChildren to consider identical nodes as
matches even if they are already synced.
=> "newChild == oldChild || !newChild.mounted" assert

sky/packages/sky/lib/src/widgets/dismissable.dart
Move _activeCardDragEndPoint near build() so it's more obvious that it
is part of the build state.
Make a couple of functions use setState() since they modify variables
that are used by build().
Add a more detailed comment to the empty setState() call, since those
are dubious in general and need explaining when they occur, lest people
start using them as magic incantations to Make Things Work.
=> Be more explicit about what's state in dismissable

sky/packages/sky/lib/src/widgets/framework.dart, sky/packages/sky/lib/src/widgets/scrollable.dart
Please use GestureDetector instead.
=> Remove support for onGestureFoo from Listener

sky/packages/sky/lib/src/animation/animation_performance.dart
- Reorder the methods so they are closer to run order.
- Reindent the code to match style guide.
=> Minor clean up of animation_performance.dart

sky/packages/sky/lib/src/widgets/framework.dart
Especially duplicate keys.
cc @apwilson
=> Improve debugging aids in framework.dart

sky/shell/mac/sky_window.mm
Previously we defaulted to loading from URLs, but its
more common to want to load files off the local machine
on the command line.
=> Teach SkyShell.app to run local files

sky/engine/bindings/scripts/dart_types.py, sky/engine/core/core.gni, sky/engine/core/rendering/RenderView.cpp, sky/engine/core/text/FontStyle.dart, sky/engine/core/text/FontStyle.h, sky/engine/core/text/FontWeight.h, sky/engine/core/text/Paragraph.cpp, sky/engine/core/text/Paragraph.h, sky/engine/core/text/TextDecoration.cpp, sky/engine/core/text/TextDecoration.h, sky/engine/core/text/TextDecorationStyle.h, sky/engine/core/text/TextStyle.cpp, sky/engine/core/text/TextStyle.h
Previously layout was exiting early because the frame view
was null. Now we actually compute some layout and paint the
text. This patch makes paragraph_builder_test pass.
=> Teach sky.Paragraph how to actually compute layout

examples/stocks/lib/stock_home.dart, examples/stocks/lib/stock_list.dart, examples/widgets/progress_indicator.dart, sky/packages/sky/lib/src/animation/animated_value.dart, sky/packages/sky/lib/src/animation/animation_performance.dart, sky/packages/sky/lib/src/widgets/animated_component.dart, sky/packages/sky/lib/src/widgets/dialog.dart, sky/packages/sky/lib/src/widgets/dismissable.dart, sky/packages/sky/lib/src/widgets/drawer.dart, sky/packages/sky/lib/src/widgets/global_key_watcher.dart, sky/packages/sky/lib/src/widgets/navigator.dart, sky/packages/sky/lib/src/widgets/popup_menu.dart, sky/packages/sky/lib/src/widgets/progress_indicator.dart, sky/packages/sky/lib/src/widgets/snack_bar.dart, sky/packages/sky/lib/src/widgets/tabs.dart, sky/packages/sky/lib/src/widgets/transitions.dart
This fixes #1103, and is a prerequisite to fixing the popup menu logic in the stocks demo.
=> Require that you pass transitions a performance.

examples/game/example_effect_line.dart, skysprites/lib/effect_line.dart, skysprites/lib/textured_line.dart
- Correctly adjusts offsets when deleting points
- Adds rocket trail example
- Fixes error with too sharp angles
- Adds support for custom start value for scrolling textures
- Adds rocket trail example
=> Improvements to EffectLine in sprites

sky/packages/sky/lib/src/fn3/framework.dart, sky/unit/test/fn3/stateful_component_test.dart, sky/unit/test/fn3/widget_tester.dart
- adds dartdocs
- replaces config setter with didUpdateConfig() so that you can't replace
the config outside of the system
- renames didUnmount() with destroy().
- rename Component to StatelessComponent, ComponentConfiguration to
StatefulComponent
- move debug dump to end of file
- renamed _holder to _element
=> fn3 review

sky/packages/sky/lib/src/fn3/framework.dart, sky/unit/test/fn3/stateful_component_test.dart
Add a LeafRenderObjectElement, fix a test to use the new contract.
=> Fix fn3 build errors

sky/packages/sky/lib/src/widgets/editable_text.dart, sky/unit/test/widget/input_test.dart
Previously EditableText would render a text widget with no cursor if the text
value was empty.
Also adjust the height of the cursor widget to reflect the style's line
height, and update the cursor painting to match.
=> Ensure that EditableText always shows a cursor

sky/packages/sky/lib/src/fn3/framework.dart
The buildDirtyElements() method now enforces that we only build deeper
nodes and never go back to build higher nodes during a frame.
=> More dartdocs for fn3, refactor buildDirtyElements

sky/packages/sky/lib/src/fn3/basic.dart
There are some TODOs in this file that I'll address in the next patch.
=> Add a number of basic widgets to fn3

sky/packages/sky/lib/src/fn3/basic.dart, sky/packages/sky/lib/src/fn3/framework.dart
We'll need tag nodes before finishing Flex and Stack.
=> Add CustomPaint and few other basic widgets to fn3

sky/packages/sky/lib/src/fn3/basic.dart, sky/packages/sky/lib/src/fn3/binding.dart, sky/packages/sky/lib/src/fn3/framework.dart
Fixes errors and review comments from #1285 and warnings from #1281.
=> fn3: Fix warnings and build errors

sky/packages/sky/lib/src/fn3/basic.dart, sky/packages/sky/lib/src/fn3/framework.dart, sky/unit/test/fn3/multichild_test.dart, sky/unit/test/fn3/stateful_component_test.dart, sky/unit/test/fn3/test_widgets.dart
=> Add tests for MultiChildRenderWidget

sky/packages/sky/lib/src/fn3/framework.dart, sky/unit/test/fn3/coordinates_test.dart, sky/unit/test/fn3/widget_tester.dart
This allows people to use localToGlobal and company.
=> Expose _descendantRenderObject as 'renderer'

sky/packages/sky/lib/src/fn3/dismissable.dart, sky/packages/sky/lib/src/fn3/focus.dart, sky/packages/sky/lib/src/fn3/framework.dart, sky/packages/sky/lib/src/fn3/navigator.dart, sky/packages/sky/lib/src/fn3/progress_indicator.dart, sky/packages/sky/lib/src/fn3/radio.dart, sky/packages/sky/lib/src/fn3/switch.dart, sky/packages/sky/lib/src/fn3/transitions.dart
=> Port transitions.dart to fn3

sky/packages/sky/lib/src/fn3/framework.dart
Remove the "update" notification logic.
Hook the register/unregister functions. We're still not notifying.
=> fn3: GlobalKey registration progress

examples/mine_digger/lib/main.dart, sky/packages/updater/.gitignore
=> Port MineDigger to fn3

examples/address_book/lib/main.dart, examples/hello_world/lib/main.dart
=> Fn3 address book

examples/fitness/lib/feed.dart, examples/widgets/navigation.dart, sky/packages/sky/lib/src/fn3.dart
=> Update navigation example

sky/packages/sky/lib/src/fn3/tabs.dart
I accidentally updated the fn2 version of tabs.dart instead of the fn3 verison.
TBR=chinmay
=> -straggler- Rename ScrollBehavior release() to createFlingScrollSimulation()

sky/packages/sky/lib/src/fn3/editable_text.dart, sky/unit/test/engine/append_child_test.dart
* Unused import in editable_text.dart
* Type mismatch in append_child_test.dart
=> Fix a couple of analyzer warnings

examples/stocks/lib/main.dart, examples/stocks/lib/stock_home.dart, examples/stocks/lib/stock_list.dart, examples/stocks/lib/stock_row.dart, sky/packages/sky/lib/src/fn3/editable_text.dart, sky/packages/sky/lib/src/fn3/tabs.dart
Not having them clickable was making it hard to notice InkSplash bugs.
Also, this paves the way to having a stock page.
=> Make Stocks demo list rows clickable

sky/packages/sky/lib/src/widgets/scrollable.dart, sky/packages/sky/lib/widgets_next.dart
Also, fix analyzer warning in fn2.
=> Add widgets_next.dart to help folks transition to fn3

sky/packages/sky_services/BUILD.gn, sky/services/activity/activity.mojom, sky/services/updater/BUILD.gn, sky/services/updater/update_service.mojom, sky/shell/BUILD.gn
These will be used by the updater package.
=> Add new mojom interfaces PathService and UpdateService.

examples/demo_launcher/lib/main.dart, examples/fitness/lib/feed.dart, examples/fitness/lib/fitness_item.dart, examples/fitness/lib/main.dart, examples/fitness/lib/meal.dart, examples/fitness/lib/measurement.dart, examples/fitness/lib/settings.dart, sky/packages/sky/lib/src/fn3/dialog.dart
=> Port demo_launcher and fitness to fn3

sky/services/activity/activity.mojom, sky/services/activity/src/org/domokit/activity/ActivityImpl.java
This is part 3 of my 3 part change to add the udpater sky package.
=> Remove old methods from Activity mojom interface after they were moved.

sky/packages/sky/lib/src/fn3/basic.dart
=> Keep the two ConstrainedBox classes together

sky/packages/sky/lib/src/rendering/box.dart
=> BoxConstraints trivial cleanup

DEPS, sky/engine/core/script/dart_init.cc, sky/tools/sky_snapshot/vm.cc
This is not ready to be landed until I land a fixup CL to the Dart VM. This will happen tomorrow.
=> Roll the Dart runtime forward

examples/widgets/overlay_geometry.dart, sky/packages/sky/lib/src/widgets/framework.dart, sky/packages/sky/lib/src/widgets/mixed_viewport.dart
This removes GlobalKey.currentElement in favour of GlobalKey.currentContext.
Also fixes an assert in MixedViewport.
=> Port overlay_geometry.dart demo.

sky/packages/sky/lib/src/widgets/binding.dart, sky/packages/sky/lib/src/widgets/framework.dart
This patch prepares us to move these elements around in the tree.
=> Delay unmounting elements until the end of the frame

examples/stocks/lib/stock_home.dart, examples/stocks/lib/stock_list.dart, examples/stocks/lib/stock_row.dart
Identify specific parts of a Stock row with a Global Key that can be
regenerated later, and pass that key back to event handlers so they can
use them to do the transition.
=> Groundwork for heroes transition in Stocks app

examples/game/pubspec.yaml, examples/game/test_bed.dart, examples/game/test_physics.dart, skysprites/lib/node.dart, skysprites/lib/physics_body.dart, skysprites/lib/physics_node.dart, skysprites/lib/physics_shape.dart, skysprites/lib/skysprites.dart, skysprites/lib/sprite_box.dart, skysprites/pubspec.yaml
- Adds physics shapes
- Adds physics node (a wrapper for the Box2D world)
- Adds contact callbacks
=> First pass on sprite physics

sky/packages/sky/lib/src/gestures/recognizer.dart, sky/packages/sky/lib/src/widgets/gesture_detector.dart, sky/unit/test/widget/fractionally_sized_box_test.dart, sky/unit/test/widget/gesture_detector_test.dart, sky/unit/test/widget/widget_tester.dart
=> Detecting just Pan events causes an exception in GestureDetector

sky/packages/sky/lib/src/rendering/box.dart, sky/packages/sky/lib/src/widgets/animated_container.dart, sky/packages/sky/lib/src/widgets/basic.dart, sky/packages/sky/lib/src/widgets/drawer.dart, sky/packages/sky/lib/src/widgets/material.dart, sky/packages/sky/lib/widgets.dart, sky/unit/test/widget/animated_container_test.dart
This widget is used in Material and Drawer. We don't currently support
animating towards null, but we can add that in a future patch.
=> Add AnimatedContainer

sky/packages/sky/lib/src/widgets/app.dart
This is probably a sign that you're using fn2 still.
=> Assert that App(routes) is not null.

examples/address_book/lib/main.dart, examples/widgets/drag_and_drop.dart, sky/packages/sky/lib/src/widgets/app.dart, sky/packages/sky/lib/src/widgets/basic.dart, sky/packages/sky/lib/src/widgets/checkbox.dart, sky/packages/sky/lib/src/widgets/dialog.dart, sky/packages/sky/lib/src/widgets/drag_target.dart, sky/packages/sky/lib/src/widgets/input.dart, sky/packages/sky/lib/src/widgets/mixed_viewport.dart, sky/specs/pointer.md
=> Use `}) : super` consistently

examples/stocks/lib/stock_row.dart, sky/packages/sky/lib/src/gestures/long_press.dart, sky/packages/sky/lib/src/gestures/show_press.dart, sky/packages/sky/lib/src/gestures/tap.dart, sky/packages/sky/lib/src/widgets/drawer_item.dart, sky/packages/sky/lib/src/widgets/floating_action_button.dart, sky/packages/sky/lib/src/widgets/gesture_detector.dart, sky/packages/sky/lib/src/widgets/ink_well.dart
* Rename GestureTapListener (and friends) To GestureTapCallback to match the
other gesture callbacks.
* Replace "ensureFoo" pattern with ??= operator.
=> Clean up some style in GestureDetector

sky/packages/sky/lib/src/animation/animated_value.dart, sky/packages/sky/lib/src/widgets/dismissable.dart
We already forced hitting end on 1.0.
Fixes #1358
=> Force AnimatedVariables to hit begin on 0.0

examples/rendering/spinning_flex.dart, examples/widgets/spinning_mixed.dart, sky/packages/sky/lib/src/animation/animated_simulation.dart, sky/packages/sky/lib/src/animation/animation_performance.dart, sky/packages/sky/lib/src/animation/scheduler.dart, sky/packages/sky/lib/src/animation/timeline.dart, sky/packages/sky/lib/src/rendering/binding.dart, sky/packages/sky/lib/src/widgets/binding.dart, sky/packages/sky/lib/src/widgets/scrollable.dart, sky/unit/test/animation/scheduler_test.dart, skysprites/lib/sprite_box.dart
@Hixie @mpcomplete 
I'm starting down the path of simplifying the animation code.  I have a plan, but I'm going to break down the change into a bunch of small steps.
=> Simplify animation

examples/fitness/lib/feed.dart, examples/stocks/lib/stock_home.dart, examples/widgets/progress_indicator.dart, sky/packages/sky/lib/animation.dart, sky/packages/sky/lib/src/animation/animated_value.dart, sky/packages/sky/lib/src/animation/performance.dart, sky/packages/sky/lib/src/animation/simulation_stepper.dart, sky/packages/sky/lib/src/painting/radial_reaction.dart, sky/packages/sky/lib/src/rendering/toggleable.dart, sky/packages/sky/lib/src/widgets/animated_component.dart, sky/packages/sky/lib/src/widgets/animated_container.dart, sky/packages/sky/lib/src/widgets/dialog.dart, sky/packages/sky/lib/src/widgets/dismissable.dart, sky/packages/sky/lib/src/widgets/drag_target.dart, sky/packages/sky/lib/src/widgets/drawer.dart, sky/packages/sky/lib/src/widgets/ink_well.dart, sky/packages/sky/lib/src/widgets/navigator.dart, sky/packages/sky/lib/src/widgets/popup_menu.dart, sky/packages/sky/lib/src/widgets/progress_indicator.dart, sky/packages/sky/lib/src/widgets/snack_bar.dart, sky/packages/sky/lib/src/widgets/tabs.dart, sky/packages/sky/lib/src/widgets/transitions.dart
=> Improves names of animation classes

examples/widgets/progress_indicator.dart, sky/packages/sky/lib/src/animation/animated_value.dart, sky/packages/sky/lib/src/animation/curves.dart, sky/packages/sky/lib/src/widgets/animated_container.dart, sky/packages/sky/lib/src/widgets/dismissable.dart, sky/packages/sky/lib/src/widgets/popup_menu.dart
This patch simplifies AnimationTiming and all the AnimatedValue base classes.
Also, make PopupMenu a stateless component because it has no state.
Fixes #1168
=> Give Interval a Curve to apply between start and end

sky/packages/sky/lib/src/widgets/basic.dart, sky/packages/sky/lib/src/widgets/framework.dart, sky/packages/sky/lib/src/widgets/scrollable.dart
Also, fix comment mentioning syncConstructorArguments.
=> Add more debugging information to Widgets.

sky/packages/sky/lib/src/widgets/drawer.dart, sky/packages/sky/lib/src/widgets/navigator.dart
Ensure that if a route's performance is dismissed before the route is
popped, that we pop the route.
=> Handle a route being dismissed before being popped

sky/packages/sky/lib/src/widgets/navigator.dart
Instead of waiting until build(), we now create the performance for a route in
its constructor.
=> Create the Performance for a Route earlier

sky/packages/sky/lib/src/widgets/animated_container.dart, sky/packages/sky/lib/src/widgets/app.dart, sky/packages/sky/lib/src/widgets/basic.dart, sky/packages/sky/lib/src/widgets/date_picker.dart, sky/packages/sky/lib/src/widgets/dialog.dart, sky/packages/sky/lib/src/widgets/dismissable.dart, sky/packages/sky/lib/src/widgets/drag_target.dart, sky/packages/sky/lib/src/widgets/drawer_item.dart, sky/packages/sky/lib/src/widgets/flat_button.dart, sky/packages/sky/lib/src/widgets/floating_action_button.dart, sky/packages/sky/lib/src/widgets/gesture_detector.dart, sky/packages/sky/lib/src/widgets/homogeneous_viewport.dart, sky/packages/sky/lib/src/widgets/icon.dart, sky/packages/sky/lib/src/widgets/ink_well.dart, sky/packages/sky/lib/src/widgets/input.dart, sky/packages/sky/lib/src/widgets/material.dart, sky/packages/sky/lib/src/widgets/material_button.dart, sky/packages/sky/lib/src/widgets/mimic.dart, sky/packages/sky/lib/src/widgets/mixed_viewport.dart, sky/packages/sky/lib/src/widgets/popup_menu.dart, sky/packages/sky/lib/src/widgets/progress_indicator.dart, sky/packages/sky/lib/src/widgets/radio.dart, sky/packages/sky/lib/src/widgets/raised_button.dart, sky/packages/sky/lib/src/widgets/scaffold.dart, sky/packages/sky/lib/src/widgets/snack_bar.dart, sky/packages/sky/lib/src/widgets/tabs.dart, sky/packages/sky/lib/src/widgets/transitions.dart
In the vast majority of cases, folks should be interacting with the Widget
rather than its State.
Fixes #267
=> Mark most State subclasses private

sky/packages/sky/lib/src/widgets/scrollable.dart
=> PageableList should take initialPage instead of initialScrollOffset

examples/address_book/lib/main.dart, examples/demo_launcher/lib/main.dart, examples/fitness/lib/feed.dart, examples/fitness/lib/meal.dart, examples/fitness/lib/measurement.dart, examples/fitness/lib/settings.dart, examples/mine_digger/lib/main.dart, examples/stocks/lib/stock_home.dart, examples/stocks/lib/stock_settings.dart, examples/stocks/lib/stock_symbol_viewer.dart, examples/widgets/card_collection.dart, examples/widgets/date_picker.dart, examples/widgets/drag_and_drop.dart, examples/widgets/ensure_visible.dart, examples/widgets/overlay_geometry.dart, examples/widgets/pageable_list.dart, examples/widgets/progress_indicator.dart, examples/widgets/scale.dart, examples/widgets/sector.dart, examples/widgets/styled_text.dart, examples/widgets/tabs.dart, sky/packages/sky/lib/src/material/constants.dart, sky/packages/sky/lib/src/widgets/scaffold.dart, sky/packages/sky/lib/src/widgets/snack_bar.dart
Rather than using a custom render object, we can just use a Stack.
=> Simplify Scaffold

sky/packages/sky/lib/src/animation/performance.dart, sky/packages/sky/lib/src/widgets/dialog.dart, sky/packages/sky/lib/src/widgets/drag_target.dart, sky/packages/sky/lib/src/widgets/navigator.dart, sky/packages/sky/lib/src/widgets/popup_menu.dart, sky/packages/sky/lib/src/widgets/snack_bar.dart
This patch prepares us to create routes that control their performances more
closely.
=> Separate Route and PerformanceRoute

sky/packages/sky/lib/src/widgets/drawer_item.dart, sky/packages/sky/lib/src/widgets/floating_action_button.dart, sky/packages/sky/lib/src/widgets/ink_well.dart, sky/packages/sky/lib/src/widgets/material_button.dart
Now we trigger the highlight from the InkWell so that it matches the tap.
Fixes #1525
=> FlatButton highlights but doesn't tap around edge

sky/packages/sky/lib/src/widgets/drawer.dart, sky/packages/sky/lib/src/widgets/navigator.dart, sky/unit/test/widget/drawer_test.dart
Also:
- Make drawer not crash.
- Provide Routes with a setState() method.
=> Drawer test.

sky/engine/core/loader/CanvasImageDecoder.cpp, sky/engine/core/painting/Rect.dart
=> Add an isEmpty property to Rect

examples/stocks/lib/stock_home.dart, examples/stocks/lib/stock_menu.dart, sky/packages/sky/lib/src/material/colors.dart, sky/packages/sky/lib/src/material/theme_data.dart, sky/packages/sky/lib/src/material/typography.dart, sky/packages/sky/lib/src/widgets/date_picker.dart, sky/packages/sky/lib/src/widgets/dialog.dart, sky/packages/sky/lib/src/widgets/flat_button.dart, sky/packages/sky/lib/src/widgets/framework.dart, sky/packages/sky/lib/src/widgets/material.dart, sky/packages/sky/lib/src/widgets/material_button.dart, sky/packages/sky/lib/src/widgets/raised_button.dart
Also, have dialog buttons use the accent colour.
Also, generally rationalise some of this stuff to match Material better.
=> Have Flat buttons set their default text styles.

sky/packages/sky/lib/src/painting/text_painter.dart, sky/packages/sky/lib/src/painting/text_style.dart
This patch makes it easier to experiment with work on ParagraphBuilder.
=> Add a flag to TextPainter to use ParagraphBuilder

sky/packages/sky/lib/src/widgets/navigator.dart
...once the animation is done.
=> Avoid painting previous routes redundantly

sky/shell/BUILD.gn, sky/shell/android/org/domokit/sky/shell/SkyApplication.java, sky/shell/ios/sky_surface.mm, sky/shell/mac/sky_window.mm
This is needed for coordination with sky_tools development.
=> Rename skyx to flx in sky.

examples/raw/painting.dart, examples/stocks/lib/stock_home.dart
We changed IconButton to require a ColorFilter to filter the color of the icon.
=> Update arrow in stocks search to use ColorFilter

examples/demo_launcher/lib/main.dart, examples/fitness/lib/feed.dart, examples/fitness/lib/meal.dart, examples/fitness/lib/measurement.dart, examples/fitness/lib/settings.dart, examples/stocks/lib/stock_list.dart, examples/stocks/lib/stock_settings.dart, examples/stocks/lib/stock_symbol_viewer.dart, examples/widgets/scale.dart, examples/widgets/sector.dart, sky/packages/sky/lib/src/material/dialog.dart, sky/packages/sky/lib/src/material/material.dart, sky/packages/sky/lib/src/material/snack_bar.dart
Canvas is by far the most popular type of material by call site (and makes for
a faster default because it doesn't have a RRect clip).
=> Change the default MaterialType to canvas

sky/engine/core/painting/Canvas.cpp, sky/engine/core/painting/Canvas.h, sky/engine/core/painting/Canvas.idl
This patch is the first step towards supporting nine-patch images. See #1309.
=> Expose Canvas.drawImageNine

examples/widgets/nine_patch.dart, sky/packages/sky/lib/src/painting/box_painter.dart, sky/packages/sky/lib/src/rendering/image.dart, sky/packages/sky/lib/src/widgets/basic.dart, skysprites/lib/label.dart
This lets you draw nine-patch images.
Fixes #1309
=> Add a centerSlice parameter to images

sky/packages/sky/lib/src/rendering/proxy_box.dart, sky/packages/sky/lib/src/widgets/basic.dart, sky/unit/test/widget/transform_test.dart
For those times where you want to spin something around a point relative
to the size of your box, but you don't know the size of your box.
=> Transform alignment

sky/packages/sky/lib/src/material/input.dart, sky/packages/sky/lib/src/services/keyboard.dart, sky/packages/sky/lib/src/widgets/editable_text.dart, sky/unit/test/widget/input_test.dart
Also add an input widget API for the keyboard submit button
=> Implement better synchronization between the state of the input widget and the keyboard IME

sky/specs/style-guide.md
=> Describe conventions around exporting APIs

sky/services/activity/activity.mojom
It was moved to update_service.mojom.
=> Remove UpdateService from activity.mojom

sky/engine/core/painting/Rect.dart, sky/packages/sky/lib/src/rendering/stack.dart
Introduce a class that can describe the metrics used in a Positioned
widget, to enable easier manipulation and storage of the values, e.g.
for animation purposes.
=> RelativeRect

sky/tools/roll/patch.py, sky/tools/roll/roll.py
* Make the paths absolute
* Using filter to remove tonic from mojo/dart/embedder/BUILD.gn instead of a
patch
=> Improve roll.py

examples/address_book/lib/main.dart, examples/fitness/lib/feed.dart, examples/fitness/lib/meal.dart, examples/fitness/lib/measurement.dart, examples/fitness/lib/settings.dart, examples/stocks/lib/stock_list.dart, examples/stocks/lib/stock_settings.dart, examples/stocks/lib/stock_symbol_viewer.dart, examples/widgets/date_picker.dart, examples/widgets/drag_and_drop.dart, examples/widgets/indexed_stack.dart, examples/widgets/overlay_geometry.dart, examples/widgets/pageable_list.dart, examples/widgets/progress_indicator.dart, examples/widgets/scale.dart, examples/widgets/scrollbar.dart, examples/widgets/sector.dart, examples/widgets/tabs.dart, sky/packages/sky/lib/src/material/scaffold.dart
=> Scaffold should wrap its body in a Material

examples/game/lib/game_objects.dart, examples/game/lib/power_bar.dart, examples/raw/baseline.dart, examples/raw/painting.dart, examples/rendering/baseline.dart, examples/stocks/lib/stock_arrow.dart, examples/widgets/overlay_geometry.dart, sky/engine/core/painting/Paint.dart, sky/packages/sky/lib/src/painting/box_painter.dart, sky/packages/sky/lib/src/rendering/object.dart, skysprites/lib/src/particle_system.dart, skysprites/lib/src/physics_debug.dart, skysprites/lib/src/textured_line.dart, skysprites/lib/src/virtual_joystick.dart
We now just use Dart properties, which is more idiomatic.
=> Remove old setFoo functions on Paint

sky/packages/sky/lib/src/animation/scheduler.dart, sky/packages/sky/lib/src/painting/box_painter.dart, sky/packages/sky/lib/src/widgets/animated_container.dart, sky/packages/sky/lib/src/widgets/framework.dart, sky/unit/test/widget/animated_container_test.dart
It turns out that an AnimatedContainer with a BoxDecoration would
start animating every single time it was built, whether or not the
container's decoration had changed.
=> Stop AnimatedContainer from animating every build

examples/widgets/card_collection.dart, sky/packages/sky/lib/src/rendering/box.dart, sky/packages/sky/lib/src/rendering/proxy_box.dart, sky/packages/sky/lib/src/rendering/shifted_box.dart, sky/packages/sky/lib/src/widgets/basic.dart, sky/unit/test/widget/align_test.dart
It was confusing as to whether these were fractions or pixels.
Fixes #1622
=> Convert Align to use FractionalOffset instead of two doubles

examples/stocks/lib/stock_home.dart, sky/packages/sky/lib/src/material/drawer_item.dart, sky/packages/sky/lib/src/material/icon.dart, sky/packages/sky/lib/src/material/icon_button.dart, sky/packages/sky/lib/src/material/tabs.dart, sky/packages/sky/lib/src/painting/basic_types.dart, sky/packages/sky/lib/src/painting/box_painter.dart, sky/packages/sky/lib/src/rendering/basic_types.dart, sky/packages/sky/lib/src/rendering/image.dart, sky/packages/sky/lib/src/widgets/basic.dart, skysprites/lib/src/sprite.dart
Instead of requiring clients to use ui.ColorFilter, we show show the
ColorFilter class, similar to what we do for Color.
=> Show ColorFilter

examples/game/test_physics.dart, examples/widgets/progress_indicator.dart, sky/packages/sky/lib/src/animation/curves.dart, sky/packages/sky/lib/src/animation/simulation_stepper.dart, sky/packages/sky/lib/src/material/dialog.dart, sky/packages/sky/lib/src/material/drawer.dart, sky/packages/sky/lib/src/material/ink_well.dart, sky/packages/sky/lib/src/material/material.dart, sky/packages/sky/lib/src/material/progress_indicator.dart, sky/packages/sky/lib/src/material/radial_reaction.dart, sky/packages/sky/lib/src/material/scrollbar_painter.dart, sky/packages/sky/lib/src/material/snack_bar.dart, sky/packages/sky/lib/src/material/tabs.dart, sky/packages/sky/lib/src/rendering/toggleable.dart, sky/packages/sky/lib/src/widgets/animated_container.dart, sky/packages/sky/lib/src/widgets/dismissable.dart, sky/packages/sky/lib/src/widgets/navigator.dart, sky/packages/sky/lib/src/widgets/scrollable.dart, sky/unit/test/widget/positioned_test.dart
=> Move animation curves into a Curves namespace

sky/packages/sky/lib/src/rendering/viewport.dart, sky/unit/test/rendering/offstage_test.dart
Also, give RenderViewport a default offset.
=> RenderOffStage test

sky/packages/sky/lib/src/services/fetch.dart
=> Close the UrlLoaderProxy on error.

examples/widgets/smooth_resize.dart, sky/packages/sky/lib/src/rendering/overflow.dart, sky/packages/sky/lib/src/rendering/proxy_box.dart, sky/packages/sky/lib/src/widgets/basic.dart, sky/packages/sky/lib/src/widgets/enter_exit_transition.dart, sky/packages/sky/lib/widgets.dart
This widget smoothly resizes as its child changes and lets you provide entrance and exit transitions for its children.
=> Adds EnterExitTransition widget

sky/packages/sky/lib/src/rendering/box.dart
=> Improve comments describing FractionalOffset

sky/packages/sky/lib/src/widgets/transitions.dart
A transition that rotates its contents.
=> RotationTransition

examples/stocks/lib/stock_home.dart, examples/stocks/lib/stock_row.dart, examples/stocks/lib/stock_symbol_viewer.dart
Also, clean up the row build function.
=> Use a card for the stock symbol viewer page.

sky/shell/android/tracing_controller.cc
We now use the same trace controller on Android as other platforms.
=> Switch Android over to the shared TraceController

sky/packages/flx/lib/bundle.dart, sky/packages/flx/lib/signing.dart, sky/packages/flx/pubspec.yaml
This will be shared by sky/updater and flutter_tools. Currently
bundle.dart and signing.dart are unmodified copies of the files from
updater and flutter_tools, respectively. This is so future changes are
easier to see.
=> Create new 'flx' package. Just a copy for now.

sky/shell/android/org/domokit/sky/shell/SkyActivity.java
We'll use this to run app bundles off the device's file system.
=> Teach SkyShell.apk how to respond to the RUN intent

sky/engine/core/painting/Offset.dart
=> Offset constructor is missing types

examples/address_book/lib/main.dart, examples/fitness/lib/feed.dart, examples/fitness/lib/measurement.dart, examples/fitness/lib/settings.dart, examples/stocks/lib/main.dart, examples/stocks/lib/stock_home.dart, examples/stocks/lib/stock_menu.dart, examples/stocks/lib/stock_settings.dart, examples/stocks/lib/stock_symbol_viewer.dart, examples/widgets/card_collection.dart, examples/widgets/indexed_stack.dart, examples/widgets/pageable_list.dart, examples/widgets/scrollbar.dart, sky/packages/sky/lib/src/material/dialog.dart, sky/packages/sky/lib/src/material/drawer.dart, sky/packages/sky/lib/src/material/popup_menu.dart, sky/packages/sky/lib/src/material/snack_bar.dart, sky/packages/sky/lib/src/widgets/heroes.dart, sky/packages/sky/lib/src/widgets/navigator.dart, sky/unit/test/widget/drawer_test.dart, sky/unit/test/widget/snack_bar_test.dart
Now you don't need to pass the navigator around everywhere.
=> Add Navigator.of

examples/widgets/piano.dart
Fixes #1696. Also fixes handles leaking on error.
=> Fix slow sound init in piano sample app

sky/packages/sky/lib/src/widgets/heroes.dart
By default now heroes won't animate if they don't find a matching hero
on the target page. You can make them animate by setting 'alwaysAnimate:
true' on the Hero constructor.
=> Unmatched heroes don't need to animate

sky/engine/core/painting/CanvasPath.h, sky/engine/core/painting/Path.idl
=> Add reset to Path

examples/fitness/BUILD.gn
=> Avoid building the fitness app on iOS due to build errors

sky/engine/core/script/dart_init.cc
RTLD_SELF doesn't appear to be defined on Android.
=> Fix Android build

sky/packages/sky/lib/src/services/keyboard.dart
This is intended to eliminate the flicker that occurs when one widget hides
the keyboard and then another shows it within the same update cycle.
=> Hide the keyboard in a deferred task.

examples/game/test_physics.dart, skysprites/lib/src/node.dart, skysprites/lib/src/physics_body.dart, skysprites/lib/src/physics_world.dart
Still has a few todo items, but working for most part
=> Working node to physics world conversions

DEPS
=> Update Mojo SDK revision

sky/packages/sky/lib/src/widgets/framework.dart, sky/packages/sky/lib/src/widgets/scrollable.dart
=> better feedback for null child to a Block or Column

examples/stocks/lib/stock_home.dart
Back button wasn't reliably working in checked mode.
=> Fix Stocks search mode back button.

sky/packages/sky/lib/src/material/typography.dart, sky/packages/sky/lib/src/painting/text_style.dart, sky/packages/sky/lib/src/widgets/basic.dart
Now TextStyle has a boolean "inherit" value, which controls whether null values
should use should inherit from the current default text style or whether they
should use their initial values.
=> Be explicit about whether text styles inherit

examples/widgets/card_collection.dart, sky/packages/sky/lib/src/material/colors.dart, sky/packages/sky/lib/src/material/radio.dart, sky/packages/sky/lib/src/widgets/gesture_detector.dart
Also:
- give card_collection an option to turn on or off the edit widgets
- give card_collection an option to control text alignment (when not editing)
- give card_collection a "dump" option to aid debugging
- make the gesture detector report which gestures it is listening to
=> Radio button 'disabled' state.

sky/packages/sky/lib/src/rendering/binding.dart
=> Handle mouseover events in pointer event conversion

examples/game/lib/main.dart, sky/packages/sky/lib/src/gestures/tap.dart, sky/packages/sky/lib/src/material/ink_well.dart, sky/packages/sky/lib/src/widgets/gesture_detector.dart, sky/tools/skyanalyzer
=> Add a position to the onTap callback

sky/packages/sky/lib/src/gestures/drag.dart, sky/packages/sky/lib/src/material/drawer.dart, sky/packages/sky/lib/src/widgets/dismissable.dart, sky/packages/sky/lib/src/widgets/scrollable.dart, sky/unit/test/gestures/scroll_test.dart, sky/unit/test/widget/gesture_detector_test.dart
=> Add the position at which drags start

sky/packages/sky/lib/src/rendering/binding.dart
The Rendering layer binding now multiplexes the dart:ui metrics change
notification so that multiple consumers can all listen to the change.
=> Notification of metrics changes.

sky/engine/core/painting/CanvasImageDecoder.cpp
CanvasImageDecoder is instantiated with a callback into a Dart closure.
That closure was holding references to the ImageDecoder and the returned
Image.  The circular reference between the ImageDecoder and the callback
prevented the objects from being GCed, resulting in leakage of the image
buffer.
CanvasImageDecoder will now destroy the callback after it is invoked,
thus releasing its handle to the Dart closure.
=> Fix a memory leak in CanvasImageDecoder

examples/address_book/pubspec.yaml, examples/fitness/pubspec.yaml, examples/game/pubspec.yaml, examples/hello_world/pubspec.yaml, examples/mine_digger/pubspec.yaml, examples/raw/pubspec.yaml, examples/rendering/pubspec.yaml, examples/stocks/pubspec.yaml, examples/widgets/pubspec.yaml, sky/packages/flx/pubspec.yaml, sky/packages/sky/pubspec.yaml, sky/packages/sky_engine/pubspec.yaml, sky/packages/sky_services/pubspec.yaml, sky/packages/updater/pubspec.yaml, sky/packages/workbench/pubspec.yaml, sky/unit/pubspec.yaml, skysprites/pubspec.yaml
sky_engine is now at 0.0.44
sky_services is now at 0.0.44
flx is now at 0.0.3
flutter is now at 0.0.14
flutter_sprites is now at 0.0.11
=> Rev package versions for release.

examples/widgets/navigation.dart, sky/packages/sky/lib/src/material/material_app.dart, sky/packages/sky/lib/src/widgets/navigator2.dart, sky/packages/sky/lib/src/widgets/overlay.dart
This navigator can handle simple page navigation. I'll add more features in
subsequent CLs.
=> Add an initial implementation of Navigator2

sky/packages/sky/lib/src/widgets/drag_target.dart, sky/packages/sky/lib/src/widgets/overlay.dart
This patch makes it so drag-and-drop doesn't thrash the overlay list.
=> Teach OverlayEntry how to rebuild in place

DEPS
This pulls in the arm64 profiling fixes made in https://github.com/dart-lang/sdk/commit/6d3bb00887537bf21e262344e7a36b3e3b0b1ff5
=> Update Dart revision

DEPS
=> Update dart revision to fix CPU profiling crashes on armv7

examples/address_book/lib/main.dart, examples/fitness/lib/feed.dart, examples/stocks/lib/stock_home.dart, examples/stocks/lib/stock_menu.dart, examples/widgets/card_collection.dart, sky/packages/sky/lib/src/material/drawer_item.dart, sky/packages/sky/lib/src/material/dropdown.dart, sky/packages/sky/lib/src/material/icon.dart, sky/packages/sky/lib/src/material/icon_button.dart, sky/packages/sky/lib/src/material/tabs.dart
The name of the parameter wasn't consistent with IconButton or DrawerItem, etc.
Fixes #1871
=> Rename Icon's type paramter to icon

sky/engine/core/painting/Paint.cpp, sky/engine/core/painting/Paint.dart, sky/engine/core/painting/Paint.h
=> Add Paint#strokeCap

sky/packages/sky/lib/widgets.dart
Somehow we missed this one file.
=> Export overlay.dart

sky/packages/sky/lib/src/rendering/flex.dart, sky/unit/test/widget/flex_test.dart
Fixes https://github.com/flutter/engine/issues/1725.
=> Adds FlexJustifyContent.collapse

sky/packages/flx/lib/bundle.dart, sky/packages/flx/lib/signing.dart, sky/unit/test/flx/bundle_test.dart, sky/unit/test/flx/signing_test.dart
Also cleaned up the flx code a bit. Replaced custom KeyPair class with
cipher's AsymmetricKeyPair.
=> Add tests for flx Bundle.

sky/packages/sky/lib/src/widgets/basic.dart
RawImage component which takes in raw bytes in the form of a Uint8List and decodes and renders
the bytes as an image.
=> Adding RawImage component

sky/tools/release_engine.py, sky/tools/release_packages.py
- sky/tools/release_engine.py, which releases sky_engine and sky_services
- sky/tools/release_packages.py, which releases flutter and flutter_sprites
=> Split big_red_button into two scripts:

sky/packages/sky/lib/src/material/dropdown.dart, sky/packages/sky/lib/src/painting/box_painter.dart
Previously the horizontal padding on each menu item didn't response to taps.
Fixes https://github.com/flutter/engine/issues/1916
=> Widen the dropdown menu item InkWells

sky/packages/flx/lib/signing.dart, sky/packages/flx/pubspec.yaml, sky/unit/test/flx/signing_test.dart
Add a test for signing/verifying with a random generated key pair.
=> flx: Support for seeding the RNG for package signing.

sky/unit/test/gestures/arena_test.dart
...and clean them up so it's easier to understand them.
=> Add more Gesture Arena tests

sky/packages/sky/lib/src/material/drawer.dart, sky/packages/sky/lib/src/rendering/shifted_box.dart
This patch paves the path for refactoring the Drawer into the Scaffold to
support edge swipes and peeks.
=> Factor DrawerController out of Drawer

examples/address_book/flutter.yaml
=> Add flutter.yaml for address_book example

sky/shell/mac/sky_window.mm
=> Move to the service/pointer Mojo interface for input events on Mac

sky/BUILD.gn, sky/shell/BUILD.gn, sky/shell/platform/android/sky_main.cc, sky/shell/platform/linux/main_linux.cc, sky/shell/platform/mac/platform_mac.mm, sky/shell/platform/mojo/BUILD.gn, sky/shell/platform/mojo/main_mojo.cc, sky/shell/platform/mojo/platform_service_provider_mojo.cc, sky/shell/platform/mojo/platform_view_mojo.cc, sky/shell/platform/mojo/platform_view_mojo.h, sky/shell/shell.cc
Currently sky_shell.mojo can't load any Flutter apps or draw to the screen, but
that will come in later patches.
=> Add a basic sky_shell.mojo

sky/shell/BUILD.gn, sky/shell/gpu/direct/ganesh_context.cc, sky/shell/gpu/direct/ganesh_context.h, sky/shell/gpu/direct/ganesh_surface.cc, sky/shell/gpu/direct/ganesh_surface.h, sky/shell/gpu/direct/rasterizer.cc, sky/shell/gpu/direct/rasterizer.h, sky/shell/shell_view.cc
I'll add another subdirectory to GPU for Mojo soon.
=> Move GPU code into direct

sky/packages/sky_engine/pubspec.yaml, sky/packages/sky_services/pubspec.yaml
=> Bump sky_engine and sky_services package versions

sky/packages/sky_engine/pubspec.yaml, sky/packages/sky_services/pubspec.yaml
=> Rev packages again and this time update the mojo_sdk dependency

sky/services/engine/sky_engine.mojom, sky/shell/platform/android/org/domokit/sky/shell/SkyActivity.java, sky/shell/platform/ios/Info.plist, sky/shell/platform/mac/Info.plist, sky/shell/platform/mac/sky_window.mm, sky/shell/ui/engine.cc, sky/shell/ui/engine.h
We weren't using the network service for anything.
=> Remove sky::shell::Engine's dependency on network_service

sky/shell/ui/engine.cc
There's no vsync service in MojoShell, so we shouldn't try to connect to it.
Feature request for MojoShell is in https://github.com/domokit/mojo/issues/535.
=> Make sky_shell.mojo work on Android

sky/services/engine/BUILD.gn, sky/services/engine/sky_engine.mojom, sky/shell/platform/mojo/main_mojo.cc, sky/shell/platform/mojo/platform_view_mojo.cc, sky/shell/platform/mojo/platform_view_mojo.h, sky/shell/platform/mojo/sky_application_impl.cc, sky/shell/platform/mojo/sky_application_impl.h, sky/shell/shell.cc, sky/shell/shell.h, sky/shell/ui/engine.cc, sky/shell/ui/internals.cc, sky/shell/ui/internals.h
I believe this patch implements all the remaining features from
sky_viewer.mojo.
=> Bring sky_shell.mojo up to feature parity with sky_viewer.mojo

sky/shell/platform/android/org/domokit/sky/shell/PlatformViewAndroid.java, sky/shell/platform/ios/sky_surface.mm, sky/shell/platform/mac/sky_window.mm, sky/shell/platform/mojo/platform_view_mojo.cc, sky/shell/shell.cc
The time_stamp is supposed to be in microseconds. Previously we were using
milliseconds.
=> Fix the units for Pointer events

sky/engine/core/painting/RRect.dart
=> Fix RRect#shift

mojo/services/native_viewport/interfaces/native_viewport.mojom, sky/shell/platform/mojo/BUILD.gn, sky/shell/platform/mojo/platform_view_mojo.cc, sky/shell/platform/mojo/platform_view_mojo.h
Ready for integration now that the mojo dependencies are sorted.
=> Add support for Linux IME

services/keyboard/src/org/chromium/mojo/keyboard/KeyboardServiceImpl.java, sky/services/raw_keyboard/src/org/domokit/raw_keyboard/RawKeyboardServiceImpl.java, sky/shell/platform/android/org/domokit/sky/shell/PlatformServiceProvider.java, sky/shell/platform/android/org/domokit/sky/shell/PlatformViewAndroid.java, sky/shell/platform/android/org/domokit/sky/shell/ServiceRegistry.java, sky/shell/platform/android/org/domokit/sky/shell/SkyApplication.java
=> Remove static data from Java keyboard-related service implementations

sky/engine/core/painting/Rect.dart, sky/engine/core/painting/Size.dart
...and provide Size.isEmpty and Size.shortestSide for consistency.
=> Fix Rect.isEmpty

sky/services/engine/sky_engine.mojom, sky/shell/platform/android/org/domokit/sky/shell/SkyActivity.java, sky/shell/platform/android/org/domokit/sky/shell/SkyApplication.java, sky/shell/platform/mac/sky_window.mm, sky/shell/switches.cc, sky/shell/switches.h, sky/shell/testing/test_runner.cc, sky/shell/testing/test_runner.h, sky/shell/testing/testing.cc, sky/shell/ui/engine.cc, sky/shell/ui/engine.h
Also, remove the --snapshot flag because using FLX files is the path we're
paving.
=> Add --flx flag to load FLX files

sky/engine/core/script/dart_controller.cc, sky/engine/core/script/dart_init.cc, sky/engine/web/Sky.cpp, sky/shell/platform/android/org/domokit/sky/shell/SkyActivity.java, sky/shell/ui/engine.cc
=> Add various trace events for tracing startup

sky/shell/platform/android/sky_main.cc
=> Give the java ui thread a name in trace files

sky/engine/core/script/dart_init.cc
Saves about 600ms at startup on iOS
Images are scaled. Look at the timeline for the actual savings.
Before:
After (the before trace did not have markers for the isolate create callback. Thats what is being waited on):
=> Instrument dart_init.cc and remove the idle wait on the service load port

sky/engine/core/painting/CanvasPath.h, sky/engine/core/painting/Path.idl
=> Add a bunch of missing Path functions

sky/tools/roll/roll.py
=> Don't copy mojo keyboard service now that they have diverged.

sky/packages/sky_engine/pubspec.yaml, sky/packages/sky_services/pubspec.yaml
=> Revving engine

sky/build/PackagerInvoke, sky/build/sdk_xcode_harness/FlutterApplication.xcodeproj/project.pbxproj
Fixes https://github.com/flutter/flutter/issues/840
=> Require the user to specify the DART_SDK_PATH manually in Xcode

sky/engine/core/dart/hooks.dart, sky/engine/core/dart/text.dart, sky/engine/core/dart/window.dart
This adds some dartdocs to dart:ui, specifically for Window and friends.
=> Remove old 'back' callback, and add dartdocs.

sky/engine/core/dart/hooks.dart, sky/engine/core/dart/window.dart
=> Make defaultRouteName immutable.

sky/services/media/media.mojom, sky/services/media/src/org/domokit/media/SoundPoolImpl.java
=> In SoundPool, have the client provide stream IDs

DEPS, skia/BUILD.gn, skia/skia_gn_files.gypi, skia/skia_library.gypi, sky/compositor/picture_serializer.cc
This reverts commit eeafe3a576d7f647b347ba9e8de6f2af6c565cca. https://github.com/flutter/engine/pull/2176
=> Revert "Roll Skia"

sky/engine/core/dart/text.dart, sky/engine/core/text/ParagraphBuilder.cpp, sky/engine/core/text/ParagraphBuilder.h
Change line-height to use percentages rather than pixels.
=> Hook up wordSpacing and per-inline lineHeight.

sky/engine/core/dart/painting.dart, sky/engine/core/painting/Canvas.cpp, sky/engine/core/painting/Canvas.h, sky/engine/core/painting/Matrix.cpp, sky/engine/core/painting/Matrix.h
Canvas.transform is the same as Canvas.concat, just with a better name.
Fixes #1080
=> Introduce Canvas.transform

sky/packages/sky_engine/pubspec.yaml, sky/packages/sky_services/BUILD.gn, sky/packages/sky_services/pubspec.yaml
=> Add gcm to sky_services package. Rev engine.

sky/compositor/picture_layer.cc
This patch uses some fancier Skia APIs to simplify how PictureLayer
paints.
=> Simplify painting PictureLayer

DEPS
https://codereview.chromium.org/1571343003
=> Update Dart revision to pull in iOS fixes

sky/compositor/BUILD.gn, sky/compositor/clip_path_layer.cc, sky/compositor/clip_rect_layer.cc, sky/compositor/clip_rrect_layer.cc, sky/compositor/color_filter_layer.cc, sky/compositor/shader_layer.cc, sky/compositor/shader_layer.h, sky/compositor/transform_layer.cc, sky/engine/core/compositing/SceneBuilder.cpp, sky/engine/core/compositing/SceneBuilder.h, sky/engine/core/dart/compositing.dart
We need this to implement RenderShaderMask properly. See #1155.
=> Add ShaderLayer to Flutter compositor

sky/engine/bindings/BUILD.gn, sky/engine/bindings/jni/dart_jni.cc, sky/engine/bindings/jni/dart_jni.h, sky/engine/bindings/jni/jni.dart
Also adopt a standard pattern for handling exceptions in JNI APIs
=> Implement simple method calls in the Dart/JNI bridge

sky/compositor/raster_cache.cc
The raster cache show some significant speedups in some situations.
Let's turn it on by default and learn more.
In this patch, I've also switched us away from using the
SkPictureImageGenerator because the preroll patches haven't landed in
Skia yet. Once those have landed, we might want to switch back.
=> Enable raster cache in compositor

sky/engine/core/dart/text.dart
Also, fix FontWeight.toString and add some type annotations on the constants.
=> FontWeight.lerp

sky/services/oknet/src/org/domokit/oknet/UrlLoaderImpl.java
Fixes https://github.com/flutter/flutter/issues/1343
=> Support for setting Content-Type of POST requests

sky/build/sdk_xcode_harness/FlutterApplication.xcodeproj/project.pbxproj, sky/shell/platform/ios/sky_surface.mm
Also asserts on there being an FLX bundle at all
=> iOS: Add an explicit FLX resource copy phase to the framework target

sky/engine/bindings/dart_vm_entry_points.txt, sky/engine/core/dart/text.dart, sky/engine/core/painting/Paint.dart, sky/engine/core/painting/Rect.cpp, sky/engine/core/painting/Rect.h, sky/engine/core/text/Paragraph.cpp, sky/engine/core/text/Paragraph.h, sky/engine/tonic/dart_class_library.cc, sky/engine/tonic/dart_class_library.h, sky/engine/tonic/dart_converter.h
We can use getRectsForRange to implement selection painting in the
framework.
=> Add getRectsForRange to Paragraph

sky/engine/bindings/dart_vm_entry_points.txt, sky/engine/core/core.gni, sky/engine/core/dart/text.dart, sky/engine/core/text/Paragraph.cpp, sky/engine/core/text/Paragraph.h, sky/engine/core/text/TextBox.cpp, sky/engine/core/text/TextBox.h
TextBox is a rect that understands TextDirection.
=> Introduce TextBox

sky/engine/core/rendering/RenderText.cpp, sky/engine/core/rendering/RenderText.h, sky/engine/core/text/Paragraph.cpp
We need this in order to draw the cursor correctly.
Fixes #1491
=> Add the TextDirection to getRectsForRange

sky/shell/platform/ios/sky_surface.mm
In the future, we'll probably want to plumb through the keyboard animation
parameters, but for now we match the behavior on Android where we move the
widgets out of the way of the keyboard without animation.
=> Teach flutter how to avoid the iOS keyboard

sky/shell/ui/animator.cc
=> Reset all animator state when restarting a paused animator

sky/shell/platform/ios/sky_dynamic_service_loader.mm
Instead, the entry point is well known. The service name is passed as an argument to the service.
=> Service vendors no longer specify the service entry point

sky/shell/platform/android/org/domokit/sky/shell/FlutterSemanticsToAndroidAccessibilityBridge.java, sky/shell/platform/android/org/domokit/sky/shell/PlatformViewAndroid.java
This exposes the actions on AccessibilityNodeInfo nodes.
It also tries to make the code that handles reloads more correct.
=> Make AccessibilityNodeInfos interactive.

sky/shell/platform/android/org/domokit/sky/shell/FlutterSemanticsToAndroidAccessibilityBridge.java, sky/shell/platform/android/org/domokit/sky/shell/PlatformViewAndroid.java
- Correctly enable accessibility on startup if it's already enabled.
- Avoid using deprecated APIs.
- Map FORWARD/BACKWARD scrolling actions to up/down even when left/right
is also possible.
- Clear the accessibility focus when removing a focused semantics node.
- Unregister listeners when view goes away.
- Call setWillNotDraw(false) if accessibility is enabled.
- Clean the handling of hover events.
- Work around an Android bug where the system focus rect isn't drawn
the first time.
=> Accessibility fixes

sky/services/firebase/ios/firebase_impl.h, sky/services/firebase/ios/firebase_impl.mm
Note: I'm in the middle of refactoring this API to not leak handles, but this is using the old (pre-refactoring) way of doing things. It should work but leaks memory.
=> Implement remaining methods of Firebase class on iOS

sky/shell/testing/observatory/empty_main.dart, sky/shell/testing/observatory/launcher.dart, sky/shell/testing/observatory/service_client.dart, sky/shell/testing/observatory/test.dart, travis/test_observatory.sh
- Test accessing service protocol over http
- Test accessing service protocol over ws
- Test accessing an Observatory UI asset.
=> Add heart beat integration tests for Observatory in sky_shell

DEPS
Fixes in https://codereview.chromium.org/1673423004/
=> Update Dart revision to include fixes to precompilation in gen_snapshot

DEPS
=> Roll Dart forward to b9b0649b9cfe11c8dc62edfd5606c4790c793d3a

sky/services/dynamic/dynamic_service_definition.cc, sky/shell/platform/ios/sky_dynamic_service_loader.mm
=> Add error logging when a dynamic service fails to load

sky/services/vsync/src/org/domokit/vsync/VSyncProviderImpl.java
It's possible for multiple calls to AwaitVSync to be pending while reloading
an application.  The Animator may get an AwaitVSync, a Reset, and then another
AwaitVSync before the first vsync completes.
If this happens, invoke both callbacks.  If we close the pipe, then the
Animator will no longer make progress.
=> Allow multiple callbacks in the VSyncProvider

sky/BUILD.gn
This was breaking the build with gcm enabled.
=> Remove reference to non-existent directory

sky/engine/core/dart/painting.dart
=> Add a toString to ui.Image

sky/services/editing/ios/keyboard_impl.mm
The Dart code uses -1 to signal that there is no current selection. If
we get text input in this state, we need to do something reasonable.
This patch teach us to treat that case as if the selection was zero.
This patch also improves how we convert from NSString to string16 and
makes it so we don't leak keyboard subviews.
Fixes https://github.com/flutter/flutter/issues/1878
=> Make iOS keyboard robust to selection of -1

sky/engine/bindings/mojo_services.cc, sky/services/engine/BUILD.gn, sky/services/engine/sky_engine.mojom, sky/shell/platform/mojo/BUILD.gn, sky/shell/platform/mojo/application_impl.cc, sky/shell/platform/mojo/application_impl.h
We don't need this anymore now that we have Mozart.
=> Remove ServiceRegistry

sky/shell/ui/flutter_font_selector.cc, sky/shell/ui/flutter_font_selector.h
=> Add explicit destructor to appease clang plugin

DEPS, sky/engine/core/script/dart_init.cc, sky/tools/sky_snapshot/vm.cc
=> Update the Dart VM and wire in the extra kDataSnapshot symbol for the precompiler

sky/shell/tracing_controller.cc
=> use the mandatory "ext." prefix in VM service extensions

sky/engine/core/painting/Size.dart
Fixes https://github.com/flutter/flutter/issues/2275
=> Add new Size.fromRadius()

sky/engine/core/painting/Color.dart
Fixes https://github.com/flutter/flutter/issues/2277
=> Add Color#withOpacity

sky/engine/core/painting/RRect.dart
Fixes https://github.com/flutter/flutter/issues/1502
=> Add a license header to RRect.dart

sky/engine/core/painting/Rect.dart
=> Add Rect.fromCircle

sky/shell/ui/engine.cc
This was authored by @jason-simmons.
=> Fix startup crash caused by mojo roll.

sky/packages/sky_engine/lib/_embedder.yaml
The other half of the PRs for https://github.com/flutter/flutter/issues/2468.
- move the analyzer `language` settings from the flutter embedder file
- add the errors and lints settings from the flutter analyze command
@pq @Hixie @johnmccutchan
=> update the embedder file

sky/shell/platform/ios/sky_surface.mm
Fixes https://github.com/flutter/flutter/issues/2282
=> Wire up locale notifications to ios.

sky/engine/core/dart/window.dart
Also, add some dartdocs for AppLifecycleState values.
=> Hide implementation comment we leaked into docs

sky/shell/BUILD.gn, sky/shell/platform/ios/framework/Info.plist, sky/shell/platform/ios/framework/module.modulemap, sky/shell/platform/ios/public/Flutter.h, sky/tools/change_install_name.py
cc @jamesr for the install_name update
=> Prepare a framework providing an embeddable Flutter view controller

sky/tools/sky_snapshot/loader.cc, sky/tools/sky_snapshot/loader.h, sky/tools/sky_snapshot/main.cc, sky/tools/sky_snapshot/switches.cc, sky/tools/sky_snapshot/switches.h
=> Depfile support for sky_snaphot.

sky/shell/shell.cc
=> [shell] fix missing header in shell.cc

flow/layers/child_scene_layer.cc
We need to adjust the transform matrix to undo the device scale.
=> Fix device pixel ratios in Mozart for reals

sky/engine/wtf/Assertions.cpp
Fixes https://github.com/flutter/flutter/issues/2692
@Hixie
=> Update ASSERTs in flutter engine to use flutter

sky/engine/core/dart/painting.dart, sky/engine/core/painting/Canvas.cpp, sky/engine/core/painting/Canvas.h
=> Add Canvas#drawParagraph

sky/engine/core/dart/painting.dart, sky/engine/core/dart/text.dart, sky/engine/core/text/Paragraph.cpp
We now use Canvas#drawParagraph.
=> Remove Paragraph#paint

sky/engine/core/script/dart_init.cc, sky/services/engine/sky_engine.mojom, sky/shell/platform/android/org/domokit/sky/shell/PlatformViewAndroid.java, sky/shell/platform/mac/sky_window.mm, sky/shell/platform/mojo/application_impl.cc, sky/shell/platform/mojo/application_impl.h, sky/shell/platform/mojo/view_impl.cc, sky/shell/platform/mojo/view_impl.h, sky/shell/ui/engine.cc, sky/shell/ui/engine.h
Previously this value was the temp directory that we used to store the FLX
bundle. Now it's the URL given to us by MojoShell.
=> Flutter apps in Mozart should have reasonable Uri.base

sky/shell/BUILD.gn, sky/shell/platform/android/org/domokit/sky/shell/PlatformViewAndroid.java, sky/shell/platform/android/org/domokit/sky/shell/ServiceProviderImpl.java, sky/shell/platform/ios/FlutterViewController.mm, sky/shell/platform/mac/platform_service_provider.cc, sky/shell/platform/mac/platform_service_provider.h, sky/shell/platform/mac/sky_window.mm, sky/shell/platform/mac/view_service_provider.cc, sky/shell/platform/mac/view_service_provider.h
These services are relative to the current view, which means they should come
in through the view services.
=> Move Keyboard and RawKeyboard to view services

sky/shell/platform/mojo/view_impl.cc
It's confusing to send two key press events. Instead, just send the
lower-level, non-char event.
The real fix will be to define a sensible key event protocol for Mozart, but
this patch unblocks people who are experimenting at higher layers of the stack.
=> Skip char key events

sky/dist/BUILD.gn, sky/packages/sky_services/BUILD.gn, sky/tools/dist_dart_pkg.py
* Add some missing dependecies to sky_services
* Create a script that excludes unnecessary files when preparing the package for release
=> Build fixes for the sky_engine and sky_services Dart packages

build/toolchain/mac/BUILD.gn
=> Remove unused toolchain definitions.

build/config/BUILD.gn, build/config/ui.gni, third_party/glfw/BUILD.gn, ui/gfx/native_widget_types.h, ui/gl/BUILD.gn, ui/gl/gl_bindings.h, ui/gl/gl_context_glfw.cc, ui/gl/gl_context_glfw.h, ui/gl/gl_implementation_glfw.cc, ui/gl/gl_implementation_osmesa.cc, ui/gl/gl_surface_glfw.cc, ui/gl/gl_surface_glfw.h
This patch is the first step towards getting the GLFW configuration up and
running.
=> Add GLFW support to //ui/gl

sky/engine/tonic/parsers/BUILD.gn, sky/engine/tonic/parsers/packages_map.cc, sky/engine/tonic/parsers/packages_map.h, sky/tools/sky_snapshot/BUILD.gn, sky/tools/sky_snapshot/loader.cc, sky/tools/sky_snapshot/main.cc, sky/tools/sky_snapshot/switches.cc, sky/tools/sky_snapshot/switches.h
The sky_snapshot tool now understands the --packages command-line flag.
Progress on https://github.com/flutter/flutter/issues/1351
=> Teach sky_snapshot about .packages

sky/build/PackagerInvoke, sky/build/sdk_xcode_harness/FlutterApplication.xcodeproj/xcshareddata/xcschemes/Application.xcscheme, sky/services/engine/sky_engine.mojom, sky/shell/dart/BUILD.gn, sky/shell/dart/dart_library_provider_files.cc, sky/shell/dart/dart_library_provider_files.h, sky/shell/platform/ios/FlutterAppDelegate.mm, sky/shell/platform/ios/FlutterDartProject.mm, sky/shell/platform/ios/FlutterDartSource.h, sky/shell/platform/ios/FlutterDartSource.mm, sky/shell/platform/ios/public/FlutterDartProject.h, sky/shell/platform/mac/platform_mac.mm, sky/shell/platform/mac/sky_window.mm, sky/shell/switches.cc, sky/shell/switches.h, sky/shell/testing/test_runner.cc, sky/shell/testing/test_runner.h, sky/shell/testing/testing.cc, sky/shell/ui/engine.cc, sky/shell/ui/engine.h, sky/tools/sky_snapshot/loader.cc
SkyShell now supports --packages instead of --package-root.
=> Teach SkyShell about .packages files

CONTRIBUTING.md
These commands are the same, but `run` is the new hotness.
=> Update `flutter start` to `flutter run`

sky/engine/core/dart/text.dart, sky/engine/core/text/ParagraphBuilder.cpp, sky/engine/core/text/ParagraphBuilder.h
Also, rename TextStyle#lineHeight to height.
=> Add font styles to ParagraphStyle

sky/engine/core/compositing/Scene.cpp, sky/shell/gpu/direct/rasterizer_direct.cc
Fixes https://github.com/flutter/flutter/issues/2511
=> Don't crash if the scene has no root layer set.

flow/BUILD.gn, flow/layers/backdrop_filter_layer.cc, flow/layers/backdrop_filter_layer.h, sky/engine/bindings/dart_ui.cc, sky/engine/core/compositing/SceneBuilder.cpp, sky/engine/core/compositing/SceneBuilder.h, sky/engine/core/core.gni, sky/engine/core/dart/compositing.dart, sky/engine/core/dart/painting.dart, sky/engine/core/painting/ImageFilter.cpp, sky/engine/core/painting/ImageFilter.h, sky/engine/core/rendering/FilterEffectRenderer.cpp, sky/engine/platform/graphics/GraphicsContext.cpp, sky/engine/platform/graphics/GraphicsContext.h, sky/engine/platform/graphics/ImageFilter.cpp, sky/engine/platform/graphics/ImageFilter.h, sky/engine/tonic/dart_wrappable.cc
Particularly, add support for blur filters to implement backdrop blur effects.
=> Add support for backdrop filters in the compositor

sky/shell/ui/engine.cc
=> Fix Mozart crash

sky/tools/sky_snapshot/loader.cc
=> Fix Loader::Fetch to use the file path and not the uri.

sky/shell/platform/mac/platform_mac.mm
Fixes https://github.com/flutter/flutter/issues/3151
=> Dont destroy the platform message loop on the Mac because the message pump is still not collected when the embedder state goes away.

build/android/gyp/create_flutter_jar.py
Fixes https://github.com/flutter/flutter/issues/3234
=> Enable compression when building flutter.jar

sky/shell/platform/android/io/flutter/view/AccessibilityBridge.java
- Default to accessibility being disabled rather than enabled. This
fixes Now-on-Tap, because Now-on-Tap probes your accessibility tree
without first turning on accessibility, and then later when we get
accessibility updates we try to notify Android and Android has a cow
because it never told us to turn accessibility on.
- Fix a typo in "mAccessilibilyEnabled".
- Wrap all uses of PersistentAccessibilityNode.children with a
null-check since the convention is that when the list is empty, the
field is null. Also, make the field null when receiving an empty list
of children. This fixes LastPass and DashLane (and Talkback, probably,
though for some reason I never hit that crash during testing before).
Fixes https://github.com/flutter/flutter/issues/3177.
=> Fix crashes with LastPass, Now-on-Tap, DashLane

sky/shell/BUILD.gn, sky/shell/platform/glfw/window_impl.cc, sky/shell/platform/glfw/window_impl.h
This patch maps glfw's keyboard input to the raw keyboard Mojo interface.
=> Add raw keyboard support to glfw

DEPS
@chinmaygarde @jason-simmons @johnmccutchan
=> Roll dart to ccfd19bfd775c7cfc400aeda2c08fd821616cc82.

sky/shell/gpu/mojo/rasterizer_mojo.cc
Related to https://github.com/domokit/mojo/issues/684
=> Use MGLEcho to provide back pressure for Mozart

flow/instrumentation.cc, flow/instrumentation.h, flow/layers/layer.h, flow/layers/layer_tree.cc, flow/layers/performance_overlay_layer.cc, flow/layers/performance_overlay_layer.h, flow/layers/picture_layer.cc, flow/paint_context.cc, flow/paint_context.h, sky/shell/gpu/direct/rasterizer_direct.cc, sky/shell/gpu/mojo/rasterizer_mojo.cc
This patch makes these files better match Google C++ style.
Also, add the engine lap time when running on Mojo.
=> Fix style in //flow/instrumentation

sky/shell/gpu/mojo/rasterizer_mojo.cc, sky/shell/ui/animator.cc
Async traces must have the same string to work, also improves and adds some more traces.
=> Improve tracing in graphics stack, esp on Mojo

sky/shell/BUILD.gn, sky/tools/gn
=> [ios] libdart_precompiled_runtime is gone; fix ios build

sky/engine/core/dart/window.dart
This would have answered a question we received on flutter-dev.
Fixes https://github.com/flutter/flutter/issues/3517
=> Improve docs for window.size

sky/engine/bindings/dart_ui.dart
closes https://github.com/flutter/flutter/issues/3119
=> Explicit import instructions for dart:ui

sky/engine/core/dart/text.dart, sky/engine/core/text/Paragraph.cpp, sky/engine/core/text/Paragraph.h
All the clients of migrated to the new ParagraphConstraints API.
=> Remove the old Paragraph API

sky/services/editing/src/org/domokit/editing/InputConnectionAdaptor.java
BUG=https://github.com/flutter/flutter/issues/3567
=> Fix handling of backspace in text input.

CONTRIBUTING.md
Fixes #https://github.com/flutter/flutter/issues/3689
=> provide link to instructions for building for iOS

sky/shell/platform/android/io/flutter/view/FlutterView.java
Fixes https://github.com/flutter/flutter/issues/2950
=> Explicitly close Mojo proxies during destruction of a FlutterView

sky/shell/BUILD.gn, sky/shell/platform/ios/framework/Headers/Flutter.h, sky/shell/platform/ios/framework/Headers/FlutterAsyncMessageListener.h, sky/shell/platform/ios/framework/Headers/FlutterMessageListener.h, sky/shell/platform/ios/framework/Headers/FlutterViewController.h, sky/shell/platform/ios/framework/Source/FlutterViewController.mm, sky/shell/platform/ios/framework/Source/application_messages_impl.h, sky/shell/platform/ios/framework/Source/application_messages_impl.mm, sky/shell/platform/mac/sky_window.mm, sky/shell/platform/mac/view_service_provider.cc, sky/shell/platform/mac/view_service_provider.h
Fixes https://github.com/flutter/flutter/issues/3256
=> Add support for app messages to iOS

sky/tools/create_ios_sdk.py
Hosting this script inside the repo will let us change the contents of the SDK
without having to synchronize a change on the infrastructure and in the repo.
=> Add a script for creating the iOS SDK

sky/build/sdk_xcode_harness/FlutterApplication.xcodeproj/project.pbxproj, sky/build/sdk_xcode_harness/Runner/main.m, sky/build/sky_precompilation_sdk.gni, sky/shell/BUILD.gn, sky/shell/platform/ios/framework/Headers/FlutterViewController.h, sky/shell/platform/mac/sky_window.mm, sky/tools/copy_dir.py, sky/tools/create_ios_sdk.py
This patch switches us to building Runner.app on the end-developer's machine,
which will eventually let them customize their app.
=> Make iOS Flutter apps extensible

sky/shell/platform/ios/framework/Source/accessibility_bridge.mm
=> Correctly report accessibilityFrame as screen coordinates

sky/shell/platform/ios/framework/Source/FlutterView.mm, sky/shell/platform/ios/framework/Source/accessibility_bridge.h, sky/shell/platform/ios/framework/Source/accessibility_bridge.mm
=> Wire up accessibility scrolling

sky/engine/core/painting/painting.cc, sky/engine/platform/mojo/data_pipe.cc, sky/engine/platform/mojo/data_pipe.h
We were all set up for this but for some reason we were actually decoding the
images on the main thread.
Fixes #3803
=> Decode images on a background thread

CONTRIBUTING.md
=> Updating CONTRIBUTING.md to mention latest paths

sky/engine/core/dart/text.dart, sky/engine/core/text/Paragraph.cpp, sky/engine/core/text/Paragraph.h
Used by text selection to select a word.
=> Expose a Paragraph.getWordBoundary method to dart.

sky/build/PackagerInvoke
- pass in --suppress-analytics for mac flx builds (fix https://github.com/flutter/flutter/issues/3862)
=> pass in --suppress-analytics for mac flx builds

sky/build/sdk_xcode_harness/Tools/common/BuildFlutterApp
https://github.com/flutter/flutter/issues/4186
=> Plumb LOCAL_ENGINE Local.xcconfig flag through to flutter build

sky/shell/platform/ios/framework/Source/FlutterDartProject.mm
=> The app.flx is now present in the main application bundle. Look for it in there.

DEPS
This is expected to fix the VM service in `--profile` mode
/cc @chinmaygarde
=> update Dart to get https://github.com/dart-lang/sdk/commit/6b6d363900373a56caa971b5610b3a0050ed55f6

sky/engine/core/compositing/SceneBuilder.cpp, sky/engine/core/compositing/SceneBuilder.h, sky/engine/core/dart/compositing.dart, sky/engine/core/dart/painting.dart, sky/engine/core/painting/Canvas.cpp, sky/engine/core/painting/Canvas.h, sky/engine/core/painting/CanvasColor.h, sky/engine/core/painting/CanvasGradient.cpp, sky/engine/core/painting/CanvasGradient.h, sky/engine/core/painting/ImageShader.cpp, sky/engine/core/painting/ImageShader.h, sky/engine/core/painting/Matrix.cpp, sky/engine/core/painting/Matrix.h, sky/engine/core/painting/Paint.h, sky/engine/core/painting/Picture.cpp, sky/engine/core/painting/RRect.cpp, sky/engine/core/painting/RSTransform.cpp, sky/engine/core/painting/Rect.cpp, sky/engine/core/painting/TransferMode.h
This patch removes spurious dependences on other parts of the engine.
=> Cleanup dependencies of core/painting

flutter/tonic/dart_library_loader.cc, sky/shell/platform/glfw/init_glfw.cc, sky/shell/platform/glfw/window_impl.cc, sky/shell/platform/glfw/window_impl.h
=> Support for hot source reloading in the Linux glfw sky_shell

sky/packages/sky_engine/lib/_embedder.yaml
These files are generated to different paths now.
=> Fix paths in embedder.yaml

DEPS
- Fixes related to source reloading
=> Roll Dart forward to 9040d8f478be20e9709328c067422930a999b6cf

DEPS
Roll Dart forward to b2c755c59a8b2db8bfefbd922ab9ddd1a973e3bf
=> Roll Dart forward to b2c755c59a8b2db8bfefbd922ab9ddd1a973e3bf

sky/shell/platform/android/io/flutter/view/FlutterView.java, sky/shell/platform/android/org/domokit/sky/shell/SkyActivity.java
It's empty and is easily confused with onPostResume
=> Remove FlutterView.onResume

flutter/lib/ui/painting.dart
=> Add operator== to ColorFilter

DEPS
- clustered serialization (dart-lang/sdk@524fbc1e0f9d61ff5da69bbed2b35745528de945)
- background finalization (flutter/flutter#3804)
=> Roll Dart to pick up:

sky/services/semantics/semantics.mojom, sky/shell/platform/android/io/flutter/view/AccessibilityBridge.java, sky/shell/platform/ios/framework/Source/FlutterView.mm, sky/shell/platform/ios/framework/Source/accessibility_bridge.h, sky/shell/platform/ios/framework/Source/accessibility_bridge.mm
These classes now use the same terminology and work in the same way.
Also, change semantics.mojom to use an enumeration of actions instead of
having a separate method per action. This will hopefully scale better.
=> Harmonize Android and iOS accessibility bridges

DEPS
- Pick up fix for 64-bit AOT/caching-JIT snapshots.
@abarth
=> Roll Dart.

sky/shell/platform/android/io/flutter/view/FlutterMain.java, sky/shell/platform/android/org/domokit/sky/shell/SkyActivity.java
Also provide an API for obtaining the path where the app bundle was extracted
=> Allow multiple Android resource names for the app bundle

DEPS
Fixes https://github.com/flutter/flutter/issues/4894
=> Roll Dart forward to e6e61332d6ec7c3bd6c92fa7496282174db521a7

flutter/lib/ui/geometry.dart
Fixes https://github.com/flutter/flutter/issues/4926
=> Add Rect.fromPoints

DEPS, sky/engine/core/script/dart_init.cc, sky/engine/public/platform/sky_settings.h, sky/shell/platform/android/io/flutter/view/FlutterMain.java, sky/shell/shell.cc, sky/shell/switches.cc, sky/shell/switches.h
Fixes https://github.com/dart-lang/sdk/issues/26904
@jason-simmons @abarth @Hixie
=> Fix DevFS on Android devices

sky/shell/platform/android/io/flutter/view/FlutterView.java, sky/shell/platform/android/org/domokit/sky/shell/SkyActivity.java
Needed for hot reloading support
@jason-simmons
=> Add intent for running from a script file

DEPS
=> Roll Dart forward to c373aa760af720ec095b9a4293b74ef991d93bc8

DEPS
=> Revert "Roll Dart to 136c3ddf47fd5c000b7ab536250276783e1422e1"

DEPS
=> Revert "Roll Dart forward to c373aa760af720ec095b9a4293b74ef991d93bc8"

DEPS
=> Roll Dart forward to 8dc35ba47ee5f43e0f6ed8d9b6a3914a2c4d9577

flow/layers/picture_layer.cc, flow/layers/picture_layer.h, flow/raster_cache.cc, flow/raster_cache.h, flutter/lib/ui/compositing.dart, flutter/lib/ui/compositing/scene_builder.cc, flutter/lib/ui/compositing/scene_builder.h
The code that draws the picture knows more about the picture (and the future)
than we do. This patch gives them a way to hint us about what's going to
happen with the picture in the future.
=> Add a way to hint the compositor

sky/shell/gpu/direct/ganesh_canvas.cc, sky/shell/gpu/direct/ganesh_canvas.h, sky/shell/gpu/direct/rasterizer_direct.cc
Fixes https://github.com/flutter/flutter/issues/4972
=> Disable rendering if the rasterizer can not create a GL/EGL context

skia/BUILD.gn
=> Compile in SIMD related files on x86 and arm64. Fixes iOS simulator/device builds.

flutter/lib/ui/geometry.dart
RRect.fromLTRBCustom -> RRect.fromLTRBAndCorners
RRect.fromRectCustom -> RRect.fromRectAndCorners
=> Renamed 2 RRect constructors.

DEPS, flutter/tonic/dart_isolate_reloader.cc, flutter/tonic/dart_library_loader.cc, flutter/tonic/dart_library_loader.h, flutter/tonic/dart_library_provider.h, sky/engine/core/script/dart_init.cc, sky/engine/core/script/dart_service_isolate.cc, sky/shell/dart/dart_library_provider_files.cc, sky/shell/diagnostic/diagnostic_server.cc, sky/tools/sky_snapshot/loader.cc
- Roll Dart to 59e67cc36d0877949719160de8959a11db4a8027
- Pass in resolved uri to Dart_LoadScript, Dart_LoadLibrary, and Dart_LoadSource API calls.
- Register a FileModifiedCallback with the VM.
=> Initial support for detecting modified libraries

DEPS, build/config/BUILDCONFIG.gn
This patch starts the process of porting Flutter to run on Fuchsia by
adding FTL to DEPS. We will eventually replace //base with //lib/ftl.
=> Add //lib/ftl

DEPS
We will eventually remove our version of tonic and use this one instead.
=> Add Fuchsia's tonic to DEPS

sky/engine/bindings/dart_mojo_internal.h, sky/engine/bindings/dart_runtime_hooks.cc, sky/engine/bindings/dart_runtime_hooks.h, sky/engine/bindings/dart_ui.h, sky/engine/bindings/mojo_services.h, sky/engine/core/script/dart_controller.h, sky/engine/core/script/dart_service_isolate.cc, sky/engine/core/script/embedder_resources.cc, sky/engine/core/text/TextBox.cpp, sky/engine/platform/exported/sky_settings.cc, sky/engine/platform/fonts/FontFallbackList.cpp, sky/engine/platform/fonts/apple/FontCacheIOS.mm, sky/engine/platform/mojo/data_pipe.cc, sky/engine/public/sky/sky_view.cc, sky/engine/public/sky/sky_view.h, sky/engine/wtf/BUILD.gn, sky/engine/wtf/dtoa/bignum.h, sky/engine/wtf/dtoa/double-conversion.h, sky/engine/wtf/dtoa/utils.h
Reverts flutter/engine#2856 to fix bot breakage.
=> Revert "Remove more //base dependencies"

sky/engine/core/BUILD.gn, sky/engine/core/core.gni, sky/engine/core/script/directory_asset_bundle.cc, sky/engine/core/script/directory_asset_bundle.h, sky/shell/ui/engine.h
@abarth @jason-simmons 
NOTE: This isn't wired up yet
=> Add DirectoryAssetBundleService to engine

DEPS, flutter/tonic/dart_message_handler.cc, sky/engine/core/script/dart_controller.cc, sky/engine/core/script/dart_init.cc, sky/engine/core/script/directory_asset_bundle.h, sky/shell/platform_view.h, sky/shell/platform_view_service_protocol.cc, sky/shell/shell.cc, sky/shell/shell.h, sky/shell/ui/engine.cc, sky/shell/ui/engine.h
=> Enable cold restart and assets in hot mode

DEPS, sky/shell/gpu/mojo/rasterizer_mojo.cc
Fixes https://github.com/flutter/flutter/issues/4957
=> Unblock the Mojo main thread during rasterizer setup

flutter/lib/ui/painting/image_decoding.cc, flutter/tonic/dart_message_handler.cc, flutter/tonic/dart_message_handler.h, glue/BUILD.gn, glue/movable_wrapper.h, glue/task_runner_adaptor.cc, glue/task_runner_adaptor.h, sky/engine/core/script/dart_controller.cc, sky/engine/core/text/Paragraph.cpp, sky/engine/core/text/ParagraphBuilder.cpp, sky/engine/platform/SharedBuffer.cpp, sky/engine/platform/mojo/data_pipe.cc, sky/engine/platform/mojo/data_pipe.h, sky/engine/public/platform/Platform.h, sky/shell/BUILD.gn, sky/shell/shell.cc, sky/shell/shell.h, sky/shell/ui/engine.cc, sky/shell/ui/platform_impl.cc, sky/shell/ui/platform_impl.h
The ftl::TaskRunner is still based on a base::MessageLoop, but this patch paves
the way to replace the message loop on Fuchsia.
=> Switch //sky/engine to ftl::TaskRunner

sky/shell/platform/android/platform_view_android.cc
Previously we had created a resource context for each PlatformView which would
be destroyed when the PlatformView lost its surface.
Fixes https://github.com/flutter/flutter/issues/5200
=> On Android, create a global resource context that is shared with all PlatformViews

DEPS, sky/tools/sky_snapshot/main.cc
Also pick up some needed fixes to FTL and Tonic
=> sky_snapshot: fix the types of Dart snapshot buffer symbols

.gn, flow/texture_image.cc, flutter/lib/ui/BUILD.gn, flutter/lib/ui/painting/image_decoding.cc, flutter/lib/ui/painting/resource_context.cc, flutter/lib/ui/painting/resource_context.h, flutter/tonic/BUILD.gn, sky/shell/BUILD.gn, sky/shell/platform_view.cc, sky/shell/platform_view.h
This required us to fix a backwards dependency from flutter/lib/ui to
sky/shell.
=> Enable gn --check for more directories

DEPS
=> Roll tonic to 25b9fe6c5dfb0925794e754b7dc80d9c320e5082

flow/BUILD.gn, flow/gl_connection.cc, flow/gl_connection.h, sky/shell/gpu/direct/ganesh_canvas.cc
Something like the following will be dumped to the logs. The dumps should work on both desktop and mobile GL setups.
```
Vendor: Apple Inc.
Renderer: Apple A8 GPU
Version: 2.0 Apple ES
Shader Version: 1.0 ES
Extensions: 43 Available
GL_APPLE_clip_distance
GL_APPLE_color_buffer_packed_float
GL_APPLE_copy_texture_levels
GL_APPLE_framebuffer_multisample
GL_APPLE_rgb_422
GL_APPLE_sync
GL_APPLE_texture_format_BGRA8888
GL_APPLE_texture_max_level
GL_APPLE_texture_packed_float
GL_EXT_blend_minmax
GL_EXT_color_buffer_half_float
GL_EXT_debug_label
GL_EXT_debug_marker
GL_EXT_discard_framebuffer
GL_EXT_draw_instanced
GL_EXT_instanced_arrays
GL_EXT_map_buffer_range
GL_EXT_occlusion_query_boolean
GL_EXT_pvrtc_sRGB
GL_EXT_read_format_bgra
GL_EXT_sRGB
GL_EXT_separate_shader_objects …
```
=> If GrGLContext setup fails, log OpenGL platform specific information.

sky/packages/sky_engine/LICENSE
Applies https://github.com/flutter/buildroot/pull/2
@abarth
=> Update sky_engine LICENSE file

BUILD.gn, assets/BUILD.gn, lib/snapshot/toolchain.gni, snapshotter/BUILD.gn
Doesn't quite work yet, but close. Fuchsia is on a newer Dart and will need a
couple patches before this will fully work.
=> Teach sky_snapshot how to build on Fuchsia

lib/ui/compositing/scene_builder.cc, lib/ui/compositing/scene_builder.h
Ignore attempts to add picture layers that lie outside the current clip boundary.
=> Added SceneBuilder culling

sky/dist/BUILD.gn
We only need this target for preparing the Dart packages for distribution now.
=> Clean up :dist target

sky/engine/config.gni, sky/engine/core/BUILD.gn, sky/engine/core/script/dart_init.cc, sky/shell/shell.cc, tools/gn
https://github.com/flutter/flutter/issues/4866
=> Pass `runtime_mode` gn arg through to `ShouldEnableCheckedMode()`

BUILD.gn, content_handler/BUILD.gn, content_handler/application_impl.cc, content_handler/application_impl.h, content_handler/content_handler_impl.cc, content_handler/content_handler_impl.h, content_handler/main.cc, flow/BUILD.gn, flow/bitmap_image.cc, flow/bitmap_image.h, flow/texture_image_gles2.cc, flow/texture_image_none.cc, lib/ui/painting/image_decoding.cc, runtime/dart_init.cc
We're now producing a flutter_content_handler binary for Fuchsia that
builds and links.
=> Add //flutter/content_handler

content_handler/BUILD.gn, content_handler/application_impl.cc, content_handler/application_impl.h, content_handler/framebuffer_skia.cc, content_handler/framebuffer_skia.h, content_handler/main.cc, content_handler/rasterizer.cc, content_handler/rasterizer.h, content_handler/runtime_holder.cc, content_handler/runtime_holder.h, runtime/dart_controller.h
This patch should contain all the code we need to run Flutter on
Fuchsia's software framebuffer (without text). I haven't actually tried
running the code, so I'm sure it doesn't work yet.
=> //flutter/content_handler code complete

BUILD.gn, content_handler/application_impl.cc, content_handler/main.cc, content_handler/runtime_holder.cc, content_handler/runtime_holder.h
After this patch, we're able to run spinning_square on Fuchsia. I've
left some TODO comments about some shortcuts I've taken that we'll need
to improve in the future.
=> Get spinning square working on Fuchsia

.gitignore, BUILD.gn, build/flx.gni, build/package.py, examples/BUILD.gn, examples/spinning_square/.packages, examples/spinning_square/BUILD.gn, examples/spinning_square/lib/main.dart
Also, teach gn how to build application bundles.
=> Add spinning_square example

sky/shell/ui/engine.cc, sky/shell/ui/engine.h
Regression introduced in https://github.com/flutter/engine/commit/cee7fef7
=> Don't initialize the ZIP asset bundle as a directory.

sky/shell/ui/engine.cc, sky/shell/ui/engine.h
=> Depending on the type of bundle path specified, initialize either the zip or directory asset bundle.

content_handler/main.cc
We can actually use multiple threads now that they work properly.
=> Actually use threads on Fuchsia

services/vsync/BUILD.gn, services/vsync/fallback/vsync_provider_fallback_impl.cc, services/vsync/fallback/vsync_provider_fallback_impl.h
Will only be used by Linux Desktop for now.
=> `VSyncProviderFallbackImpl` for platforms that lack the ability to provide real VSync callbacks.

sky/shell/platform/android/io/flutter/view/FlutterView.java, sky/shell/platform/android/org/domokit/sky/shell/SkyActivity.java, sky/shell/platform/android/platform_view_android.cc, sky/shell/platform/android/platform_view_android.h, sky/shell/platform/ios/platform_view_ios.h, sky/shell/platform/ios/platform_view_ios.mm, sky/shell/platform/mac/platform_view_mac.h, sky/shell/platform/mac/platform_view_mac.mm, sky/shell/platform_view.h, sky/shell/platform_view_service_protocol.cc, sky/shell/shell.cc, sky/shell/testing/platform_view_test.cc, sky/shell/testing/platform_view_test.h
=> Fix Android keyboard in hot mode

lib/ui/BUILD.gn, sky/BUILD.gn, sky/engine/platform/BUILD.gn
Also, clean out some unneeded dependencies from engine/platform.
=> Build WTF on Fuchsia

sky/tools/create_ios_framework.py
This reverts commit 26f8970835335a3723509d1b04a39c4b4c2b963e.
Used by the buildbot apparently :(
=> Revert "Remove the create_ios_framework.py tool. (#2946)"

services/vsync/BUILD.gn, sky/shell/BUILD.gn, sky/shell/ui/animator.cc, sky/shell/ui/animator.h
cc @Hixie @jason-simmons @tvolkert
=> Make the animator host an implicit fallback VSync provider in case platforms cant provide their own.

sky/shell/platform/ios/framework/Source/FlutterViewController.mm, sky/shell/platform/ios/platform_view_ios.h, sky/shell/platform/ios/platform_view_ios.mm, sky/shell/platform/mac/platform_view_mac.h, sky/shell/platform/mac/platform_view_mac.mm, sky/shell/platform/mac/sky_window.mm
As discussed, I have moved most of the common stuff into the platform view. Haven't made it shared between iOS and Mac just yet though. On it next. @johnmccutchan, can you verify this works for the hot mode reloading on iOS?
cc @abarth
=> In hot mode, allow reloading platform views that are already running.

sky/shell/platform_view_service_protocol.cc
=> Register _flutter.listViews in profile mode

flow/layers/layer_tree.h, sky/shell/ui/animator.cc, sky/shell/ui/animator.h
=> Keep track on the layer tree construction time in the animator.

sky/shell/platform/android/platform_view_android.cc, sky/shell/platform/android/platform_view_android.h
Noticed this while looking at https://github.com/flutter/flutter/issues/5594
=> Ensure that the rasterizer is shut down before the PlatformView is deleted

common/settings.h, runtime/dart_init.cc, sky/shell/shell.cc, sky/shell/switches.cc, sky/shell/switches.h
See discussion in https://github.com/flutter/engine/pull/2986
=> Remove support for the —enable-checked-mode flag from the engine.

DEPS
Pulls in fixes related to incremental builds of Dart sources that end up in the snapshotter.
=> Update Dart revision.

DEPS, sky/shell/ui/flutter_font_selector.cc
This removes another //base dependency and will let us reuse this code
on Fuchsia.
=> Switch JSON parsing from //base to //third_party/rapidjson

DEPS
=> Update buildroot revision.

sky/engine/platform/fonts/skia/FontCustomPlatformDataSkia.cpp
(skia change 42943c8aa9c611c18ad0f1a30a27669f3d82239c)
=> use sk_sp<SkData> instead of SkData*

snapshotter/main.cc
=> Mark libraries as loaded before creating the script snapshot.

lib/ui/text.dart
We were off by one on, uh, everything.
=> Fix the encoding of TextStyle and ParagraphStyle

lib/ui/text.dart
=> Fix even more problems with ParagraphStyle.toString

README.md
closes https://github.com/flutter/flutter/issues/289
=> say what the engine is

sky/engine/web/BUILD.gn, sky/engine/web/Sky.cpp
This patch teachs us how to observe tasks on Fuchsia and kick off the
microtask queue.
=> Wire up microtasks on Fuchsia

content_handler/framebuffer_skia.cc
Previously we were swapping the wrong color channels. This change makes it
correct.
=> Fix color swapping on Fuchsia

lib/ui/painting.dart
Apparently Skia would like to remove these enum values.
Fixes https://github.com/flutter/flutter/issues/5912
=> Remove deprecated Skia enums

DEPS
=> Update flutter/DEPS to point to latest buildroot.

content_handler/BUILD.gn, content_handler/main.cc, glue/BUILD.gn, glue/trace_event.h
Depends on https://fuchsia-review.googlesource.com/#/c/9801/. Putting it up for review now to collect feedback.
=> Wire up mojo tracing

lib/ui/text.dart, lib/ui/text/paragraph_builder.cc, sky/engine/core/rendering/BidiRun.h, sky/engine/core/rendering/InlineBox.h, sky/engine/core/rendering/InlineTextBox.cpp, sky/engine/core/rendering/InlineTextBox.h, sky/engine/core/rendering/RenderParagraph.cpp, sky/engine/core/rendering/line/BreakingContextInlineHeaders.h, sky/engine/core/rendering/line/LineBreaker.cpp, sky/engine/core/rendering/line/LineBreaker.h, sky/engine/platform/text/BidiCharacterRun.h
See https://github.com/flutter/flutter/issues/4478
=> Implement ellipsizing of text in the engine

DEPS, sky/engine/web/BUILD.gn, sky/engine/wtf/BUILD.gn
This will require also rolling buildroot to include https://github.com/flutter/buildroot/pull/13
=> Mojo public roll to 6339f38605d63548a976cd1a629dde0b0bafc77c

DEPS, flow/layers/clip_rrect_layer.cc, shell/common/diagnostic/diagnostic_server.cc, skia/BUILD.gn, sky/engine/platform/graphics/GraphicsContext.cpp, sky/engine/platform/graphics/GraphicsContext.h
/cc @abarth 
It compiles on Linux for desktop and for Android after making a few changes to the build scripts and sources.  I'm not able to verify whether it compiles for iOS.
=> Update skia to e038489a743d6c0ab1cb208862c305180815bc8e.

lib/ui/text.dart
Previously we got some punctuation wrong.
=> Fix ParagraphStyle toString

lib/ui/hooks.dart, lib/ui/window.dart, lib/ui/window/window.cc, lib/ui/window/window.h, runtime/dart_vm_entry_points.txt, runtime/runtime_controller.cc, runtime/runtime_controller.h, shell/common/engine.cc
Long live pointer data packets.
=> Stop dispatching pointer packets

lib/ui/lerp.dart
Fixes https://github.com/flutter/flutter/issues/5783
=> lerpDouble return value should be "double"

examples/hello_flutter/lib/main.dart, examples/spinning_square/lib/main.dart
Now the engine always gives values in physical pixels.
=> Update examples for window.physicalSize

shell/common/platform_view_service_protocol.cc, shell/common/platform_view_service_protocol.h
This is intended for use in flutter_driver tests
=> Service protocol extension for grabbing screenshots

assets/directory_asset_bundle.cc, assets/zip_asset_store.cc, glue/data_pipe_utils.cc, glue/data_pipe_utils.h
=> Update uses of mtl::MessageLoop::task_runner() accessor.

lib/ui/dart_ui.cc, lib/ui/window/window.cc
Previously the Dart entry points weren't wired up.
=> Add more wiring for new semantics backend

runtime/runtime_controller.cc, shell/common/engine.cc, shell/common/engine.h, shell/platform/android/io/flutter/view/AccessibilityBridge.java, shell/platform/android/io/flutter/view/FlutterView.java
TalkBack still isn't fully working, but this patch gets us much closer.
=> Improve new semantics backend

content_handler/BUILD.gn, content_handler/rasterizer.cc, content_handler/runtime_holder.cc, content_handler/runtime_holder.h
=> Add support for Mozart input events

lib/ui/window.dart, shell/platform/android/BUILD.gn, shell/platform/android/io/flutter/plugin/common/JSONMessageListener.java, shell/platform/android/io/flutter/plugin/platform/PlatformPlugin.java, shell/platform/android/io/flutter/view/FlutterView.java, shell/platform/android/platform_view_android.cc
The PlatformPlugin is the first of the built-in plugins that will replace the
mojom platform services.
=> Add PlatformPlugin.java

shell/platform/android/io/flutter/plugin/platform/PlatformPlugin.java
After this patch, the PlatformPlugin has all the required functionality on Android.
=> Complete PlatformPlugin.java

flow/layers/clip_path_layer.cc, flow/layers/clip_rrect_layer.cc, lib/ui/painting/canvas.cc
The Skia team tells us that these go faster.
=> Use antialiased clips

services/editing/src/org/domokit/editing/KeyboardViewState.java
Fixes https://github.com/flutter/flutter/issues/6152
=> Set the initial selection range when creating an InputConnection

shell/platform/android/io/flutter/plugin/platform/PlatformPlugin.java, shell/platform/android/org/domokit/sky/shell/SkyActivity.java
Fixes https://github.com/flutter/flutter/issues/6303
=> Don't start in fullscreen mode on Android

shell/platform/android/io/flutter/plugin/platform/PlatformPlugin.java, shell/platform/darwin/ios/framework/Source/FlutterPlatformPlugin.mm
This method will let us remove the activity service.
=> Add SystemNavigator.pop

lib/ui/pointer.dart, lib/ui/window/pointer_data.cc, lib/ui/window/pointer_data.h, shell/platform/android/io/flutter/view/FlutterView.java
To make the default state all zeros.
Fixes https://github.com/flutter/flutter/issues/6236
=> PointerChange.cancel should have a zero index

shell/platform/android/io/flutter/plugin/platform/PlatformPlugin.java, shell/platform/darwin/ios/framework/Source/FlutterPlatformPlugin.mm
This will eventually replace the clipboard mojom.
=> Add clipboard functionality to platform plugin

shell/platform/android/io/flutter/view/FlutterView.java, shell/platform/android/platform_view_android.cc, shell/platform/android/platform_view_android.h
This patch completes the routing for Java-to-Dart platform messages.
=> Complete routing for Java-to-Dart messages

shell/platform/android/io/flutter/view/FlutterView.java
This will replace raw_keyboard.mojom.
=> Route key events through platform messages

shell/platform/android/BUILD.gn, shell/platform/android/io/flutter/plugin/editing/InputConnectionAdaptor.java, shell/platform/android/io/flutter/plugin/editing/TextInputPlugin.java, shell/platform/android/io/flutter/view/FlutterView.java
This plugin will eventually replace keyboard.mojom.
=> Implement TextInputPlugin on Android

shell/testing/observatory/launcher.dart
This patch is an attempt to fix a mysterious failure on the buildbot.
=> Run observatory tests in --non-interactive

glue/drain_data_pipe_job.h, glue/drain_data_pipe_job_base.cc, glue/drain_data_pipe_job_fuchsia.cc, lib/ui/painting/image_decoding.cc, lib/ui/window/platform_message.cc, lib/ui/window/platform_message.h, lib/ui/window/platform_message_response.h, lib/ui/window/platform_message_response_dart.cc, lib/ui/window/platform_message_response_dart.h, lib/ui/window/pointer_data_packet.cc, lib/ui/window/pointer_data_packet.h, lib/ui/window/window.cc, lib/ui/window/window.h, shell/common/engine.cc, shell/platform/android/platform_view_android.cc, shell/platform/android/platform_view_android.h, shell/platform/darwin/ios/framework/Source/FlutterViewController.mm, shell/platform/darwin/ios/framework/Source/application_messages_impl.mm
Previously we had a mix of the two.
=> Switch from char to uint8_t to represent memory

DEPS, assets/directory_asset_bundle.cc, assets/directory_asset_bundle.h, assets/zip_asset_bundle.h, shell/common/engine.cc, shell/common/engine.h
This plugin is implemented internally by the engine to integrate with the asset
system.
=> Add assets plugin

DEPS, glue/task_runner_adaptor.cc, glue/task_runner_adaptor.h
=> Implement ftl::TaskRunner::PostTaskForTime function.

content_handler/application_impl.cc
Depends on: https://fuchsia-review.googlesource.com/c/12243/
=> Update flutter to the new URL(Request|Response) interfaces

DEPS, lib/snapshot/snapshot.c.tmpl, runtime/dart_controller.cc, runtime/dart_init.cc, runtime/dart_init.h, snapshotter/main.cc
(For after a clean build with https://github.com/flutter/flutter/pull/6464)
=> Roll Dart VM.

lib/ui/text.dart, lib/ui/text/paragraph_builder.cc, lib/ui/text/paragraph_builder.h, sky/engine/core/rendering/line/BreakingContextInlineHeaders.h
This enables text span styles to inherit attributes from the paragraph style
=> Provide the paragraph style at ParagraphBuilder construction time

runtime/dart_init.cc
Temporary until precompiled code works on Fuchsia
=> Don't enable checked mode for Fuchsia release builds

content_handler/runtime_holder.cc, lib/ui/hooks.dart, lib/ui/window.dart, lib/ui/window/window.cc, lib/ui/window/window.h, runtime/dart_vm_entry_points.txt, runtime/runtime_controller.cc, runtime/runtime_controller.h, services/engine/sky_engine.mojom, shell/common/BUILD.gn, shell/common/engine.cc, shell/common/engine.h, shell/platform/android/io/flutter/view/FlutterView.java, shell/platform/darwin/ios/framework/Source/FlutterViewController.mm
Previously, these signals were sent over Mojo. Now we send them through
platform messages.
=> Move lifecycle, navigation, and localization to platform messages

sky/engine/core/rendering/line/BreakingContextInlineHeaders.h
Fixes https://github.com/flutter/flutter/issues/6450
=> Improvements to the text ellipsizer

content_handler/runtime_holder.cc, content_handler/runtime_holder.h, lib/ui/BUILD.gn, lib/ui/window/viewport_metrics.h, lib/ui/window/window.cc, lib/ui/window/window.h, runtime/runtime_controller.cc, runtime/runtime_controller.h, services/engine/sky_engine.mojom, shell/common/engine.cc, shell/common/engine.h, shell/platform/android/io/flutter/view/FlutterView.java, shell/platform/android/platform_view_android.cc, shell/platform/android/platform_view_android.h, shell/platform/darwin/desktop/sky_window.mm, shell/platform/darwin/ios/framework/Source/FlutterViewController.mm, shell/platform/linux/platform_view_glfw.cc, shell/testing/BUILD.gn, shell/testing/test_runner.cc, shell/testing/test_runner.h
Now we just pass the data directly.
=> Migrate ViewportMetrics away from Mojo

shell/common/engine.cc, shell/common/engine.h
Now they all flow through some common routines.
=> Unify the various run methods on engine

shell/platform/android/io/flutter/plugin/editing/TextInputPlugin.java
We had a typo in our decoding logic.
Fixes https://github.com/flutter/flutter/issues/6564
=> Number keyboard does not work on Android

sky/engine/platform/fonts/fuchsia/FontCacheFuchsia.cpp
=> Remove use of magenta/process.h.

runtime/dart_init.cc
Fixes https://github.com/flutter/flutter/issues/6496
=> Fix profile and release mode isolate spawning

DEPS
=> Roll tonic to d171be8076dc3310f43ee67ac49e87765688c3d7

shell/platform/android/io/flutter/plugin/common/JSONMessageListener.java, shell/platform/android/io/flutter/plugin/editing/TextInputPlugin.java
(JSONObject.getString() will return the string "null" for a JSON null value)
Fixes https://github.com/flutter/flutter/issues/6643
=> Set the IME action label to null if the label is null in the configuration JSON object

DEPS
=> Roll Dart VM to pick fix for JITing on the Pixel.

content_handler/application_controller_impl.cc
=> Update to new way of passing application environment.

DEPS
Fixes https://github.com/flutter/flutter/issues/6725
@Hixie
=> Roll Tonic to 36142e27c6765301a4122dd85045c565b2d8b33f

content_handler/rasterizer.cc, content_handler/runtime_holder.cc, content_handler/runtime_holder.h, lib/io/dart_io.h, lib/snapshot/BUILD.gn, lib/snapshot/snapshot_fuchsia.dart
=> Add support for child view on Fuchsia

flow/layers/picture_layer.cc
The picture may hold references to images backed by GPU textures that must
be deleted on the IO thread.
=> Move destruction of PictureLayer's SkPicture to the IO thread

content_handler/runtime_holder.cc
Previously we treated everything as touch.
=> Recognize Mozart event kinds

content_handler/BUILD.gn, content_handler/runtime_holder.cc
Fixes https://github.com/flutter/flutter/issues/6631
=> Add support for raw key events on Fuchsia

content_handler/runtime_holder.cc, content_handler/runtime_holder.h, lib/ui/hooks.dart, lib/ui/pointer.dart, lib/ui/window/pointer_data.h, shell/platform/android/io/flutter/view/FlutterView.java, shell/platform/darwin/desktop/sky_window.mm, shell/platform/darwin/ios/framework/Source/FlutterViewController.mm
These are implemented on macOS and Fuchsia.
=> Add support for hover pointer events

content_handler/application_controller_impl.cc
=> Update to new ApplicationStartupInfo changes.

shell/platform/android/io/flutter/view/FlutterView.java
I updated the C++ and Dart sides but forgot to update the Java side.
Fixes https://github.com/flutter/flutter/issues/6891
=> Update pointer change constants in Java

lib/ui/hash_codes.dart
Mask the intermediate values when computing composite
hash codes.
=> Faster hash codes.

DEPS
=> Revert "Roll Dart and Tonic forward"

DEPS
I've built debug, profile, and release locally.
@abarth @Hixie
=> Roll Dart and Tonic forward (take 2)

build/dart/rules.gni, build/dart/tools/dart_package_name.py, build/dart/tools/dart_pkg.py, sky/packages/sky_engine/BUILD.gn, sky/packages/sky_services/BUILD.gn
This also removes a reference to mojo_gni.
=> Import Dart rules from buildroot, to make them available in Fuchsia.

DEPS
=> Roll Dart runtime to deafdbf978d1128dde83b9779bdae6633d484d96

snapshotter/main.cc
=> Add --compile-all to sky_snapshot

DEPS, snapshotter/main.cc
=> Bug fixes for `sky_snapshot --compile-all` mode

content_handler/runtime_holder.cc, content_handler/runtime_holder.h
This interface has been replaced with HandleWaiter, which is the new hotness.
=> Remove HandleWatcher

lib/ui/compositing/scene_builder.cc
There's no reason to present offscreen child views to Mozart.
=> Cull offscreen child views

DEPS, shell/common/picture_serializer.cc, shell/common/platform_view_service_protocol.cc, shell/gpu/gpu_surface_gl.cc
Fixed in https://skia-review.googlesource.com/c/5212/
Fixes https://github.com/flutter/flutter/issues/6997
Regressed in https://github.com/flutter/flutter/pull/6969
=> Update Skia revision to pull in GL native interface construction fixes on iOS.

build/flutter_app.gni, build/package.py
This will ensure the flx file is rebuilt whenever the manifest is modified.
=> Add a manifest parameter to flutter_app.

content_handler/rasterizer.cc, flow/layers/child_scene_layer.cc, flow/layers/child_scene_layer.h, flow/scene_update_context.cc, lib/ui/compositing.dart, lib/ui/compositing/scene_builder.cc, lib/ui/compositing/scene_builder.h
Also, change the hit testing geometry so that we get our hits at the root.
=> Add prune to child scene layers

flow/layers/child_scene_layer.cc, flow/layers/child_scene_layer.h, lib/ui/compositing.dart, lib/ui/compositing/scene_builder.cc, lib/ui/compositing/scene_builder.h
Apparently hittable is not politically correct.
=> Rename hittable to hitTestable

shell/platform/darwin/ios/BUILD.gn, shell/platform/darwin/ios/framework/Source/FlutterView.mm
Fixes https://github.com/flutter/flutter/issues/6711
=> Allow platform frameworks to snapshot FlutterView contents.

shell/platform/android/io/flutter/plugin/editing/InputConnectionAdaptor.java, shell/platform/android/io/flutter/plugin/editing/TextInputPlugin.java
Fixes https://github.com/flutter/flutter/issues/7033
=> Initialize the InputConnection with the text plugin's most recent state (either incoming or outgoing)

CONTRIBUTING.md
I always forget how to do this...
=> Mention updating the buildroot git remotes

shell/platform/darwin/ios/framework/Source/vsync_waiter_ios.mm
This schedules the display link on the correct thread once and avoids the per frame switch to the UI thread. This way, the platform thread does not need to wake up at all.
=> [iOS] Don’t perform a per frame platform to UI thread switch.

DEPS
=> roll buildroot

shell/common/platform_view_service_protocol.cc
Fixes https://github.com/flutter/flutter/issues/7174
=> Fix invalid JSON in listViews RPC response when a view does not have an isolate

shell/platform/android/io/flutter/view/FlutterView.java
FlutterView's host message processing methods are invoked from native code,
and the JNI wrappers will abort the process if the Java side has an uncaught
exception.
=> Catch and log exceptions thrown in message listeners provided by apps

flow/layers/picture_layer.cc, lib/ui/BUILD.gn, lib/ui/painting/image.cc, lib/ui/painting/mask_filter.cc, lib/ui/painting/picture.cc, lib/ui/painting/shader.cc, lib/ui/painting/utils.h
Fixes https://github.com/flutter/flutter/issues/7182
=> Null check before queueing deletion of Skia objects

sky/engine/platform/fonts/fuchsia/FontCacheFuchsia.cpp
The mx_process_{map,unmap}_vm interface is deprecated.
=> Fuchsia: Switch to new VM interface

CONTRIBUTING.md
Fixes https://github.com/flutter/flutter/issues/7294
=> Update editor recommendation

lib/ui/compositing.dart, lib/ui/compositing/scene_builder.h, lib/ui/painting.dart, lib/ui/painting/paint.cc
Fixes https://github.com/flutter/flutter/issues/7200
=> Rename TransferMode to BlendMode

sky/engine/core/BUILD.gn
Okay. This is what I meant to do.
=> Include Observatory on Fuchsia

tools/licenses/lib/main.dart
Add a couple missing newlines.
=> Fix exception message formatting

shell/platform/darwin/ios/framework/Source/vsync_waiter_ios.mm
Fixes https://github.com/flutter/flutter/issues/7433.
Investigation: This is caused by a subtle difference between the way in which iOS and Android manage VSync pulses. On Android, the platform main thread wakes up (using the Choreographer) on each VSync pulse. Then, it posts a task to the UI thread to finally service a callback. On iOS however, the CADisplayLink (Choreographer equivalent) is directly scheduled onto the UI thread. This way, on each VSync pulse, only one thread ever gets woken up. The side effect if that no tasks need to posted and the callback run directly. However, the callback itself may have side effects that are usually resolved using a task observer. This is what was happening in the issue linked. So, no task, no task observer invocation. This patch makes it so that …
=> iOS: Ensure that task observers for VSync callbacks are not bypassed in VSyncWaiterIOS.

common/settings.h, lib/ui/dart_runtime_hooks.cc, shell/common/shell.cc, shell/common/switches.h, shell/platform/android/io/flutter/view/FlutterMain.java
Fixes https://github.com/flutter/flutter/issues/7226
=> An API for setting the tag for Flutter log messages on Android

lib/ui/geometry.dart, lib/ui/painting.dart
See https://github.com/flutter/flutter/issues/7431
=> Check if the canvas bounds rect contains infinite or NaN values

lib/ui/text.dart, lib/ui/text/paragraph_builder.cc, lib/ui/text/paragraph_builder.h, sky/engine/core/rendering/RenderParagraph.cpp, sky/engine/core/rendering/line/BreakingContext.cpp, sky/engine/core/rendering/line/BreakingContextInlineHeaders.h, sky/engine/core/rendering/line/LineInfo.h, sky/engine/core/rendering/style/RenderStyle.h, sky/engine/core/rendering/style/StyleRareNonInheritedData.cpp, sky/engine/core/rendering/style/StyleRareNonInheritedData.h
Also fix 'ellipsis' overflow handling to work for multiline text.
Fixes https://github.com/flutter/flutter/issues/7271
=> Add support for a maxLines property on Paragraph.

tools/licenses/lib/main.dart
Previously, search by license type only searched the contents of the
chain of direct ancestor subdirectories. This change broadens the search
to the full subtree of the current license root when no license is found
in the chain of direct ancestor directories.
=> Search full license root subtree in search by type

shell/platform/android/io/flutter/plugin/editing/TextInputPlugin.java
This was causing exceptions on Jellybean
=> Do not pass negative selection indexes to InputConnection.setSelection

lib/ui/text.dart
=> Expose justify TextAlign option

.gitignore
Generated by pub in tools/licenses for license aggregation.
=> Add .packages to .gitignore

common/settings.h, shell/common/diagnostic/diagnostic_server.cc, shell/common/diagnostic/diagnostic_server.dart, shell/common/diagnostic/diagnostic_server.h, shell/common/shell.cc, shell/common/switches.h
Fixes https://github.com/flutter/flutter/issues/7557
=> Add flags for disabling the diagnostic server or setting its port

DEPS, common/settings.h, lib/snapshot/snapshot.c.tmpl, runtime/dart_controller.cc, runtime/dart_init.cc, runtime/dart_init.h, shell/common/shell.cc, shell/common/switches.h, shell/platform/android/io/flutter/view/FlutterMain.java, snapshotter/main.cc
To be landed with a roll to https://chromiumcodereview.appspot.com/2622053002/
=> Adapt to refactoring of snapshot APIs in the Dart VM.

DEPS, runtime/dart_controller.cc, runtime/dart_controller.h, runtime/runtime_controller.cc, runtime/runtime_controller.h, shell/common/engine.cc, shell/common/engine.h, shell/platform/linux/BUILD.gn, shell/platform/linux/main_linux.cc
This is intended to match the exit codes returned by the Dart command line tool
=> Return an exit code from sky_shell representing what kind of error occurred

testing/dart/.gitignore, testing/dart/color_test.dart, testing/dart/paragraph_builder_test.dart, testing/dart/pubspec.yaml, testing/dart/rect_test.dart, testing/fail_test.dart, testing/run_tests.sh
The Dart tests were migrated from the flutter/test/engine suite in the
framework repository
=> Travis script that runs engine unit tests and Dart tests of engine APIs

DEPS
Includes some fixes for gen_snapshot on Windows
=> Roll Dart SDK to a7eb2f45c3a0ed935c049bae805fe76ecdd95a22

lib/ui/text.dart, lib/ui/text/paragraph_builder.cc, lib/ui/text/paragraph_builder.h
Fixes https://github.com/flutter/flutter/issues/7723
=> Remove ParagraphStyle.lineCount, which has been superseded by maxLines

shell/platform/darwin/ios/framework/Info.plist
Added:
* UIRequiredDeviceCapabilities=[arm64]
* MinimumOSVersion=8.0
=> Add min OS version and architecture keys to Framework Info.plist

runtime/test_font_selector.cc
Fixes https://github.com/flutter/flutter/issues/7724
=> Obtain test font attributes from the font description

shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm
Ensure that the text input keyboard is reloaded if the view keyboardType
changes.
=> Switch iOS keyboard type if required

content_handler/BUILD.gn, content_handler/app.h, content_handler/application_controller_impl.cc, content_handler/application_controller_impl.h, content_handler/runtime_holder.cc, content_handler/runtime_holder.h
Landing this needs to be coordinated with these:
https://fuchsia-review.googlesource.com/#/q/topic:application+(status:open+OR+status:merged)
=> Updates for application extraction from //apps/modular

lib/ui/geometry.dart
See https://github.com/flutter/flutter/issues/7979#issuecomment-278697182
=> Added a point about Point&Size to the Rect dartdoc

lib/ui/painting.dart, lib/ui/painting/mask_filter.cc, lib/ui/painting/mask_filter.h
See https://github.com/flutter/flutter/issues/6807
=> Export the Skia ShadowMaskFilter API

CONTRIBUTING.md
=> Add CONTRIBUTING instructions for simulator

runtime/dart_init.cc
Fixes https://github.com/flutter/flutter/issues/7579
=> Enable some new Dart VM features

DEPS, sky/packages/sky_engine/LICENSE, tools/licenses/pubspec.lock
Picks up changes to include inlined frames and line numbers in AOT stack traces.
=> Roll Dart VM to cfe5e5f075431641642a8e3be2fbd4414eaca1fd.

content_handler/app.cc, content_handler/app.h, content_handler/application_controller_impl.cc, content_handler/application_controller_impl.h, content_handler/runtime_holder.cc, content_handler/runtime_holder.h
This needs to be landed concurrently with https://fuchsia-review.googlesource.com/#/c/20842/
=> Updates for modular->app rename of //application interfaces

lib/ui/painting/image_decoding.cc
Previously we had passed a local generator to flow::BitmapImageCreate /
SkImage::MakeFromGenerator, which takes ownership of the generator.
That generator in turn referenced an SkData backed by a local vector.
The result was an SkImage backed by a deleted buffer.
=> Transfer ownership of the buffer in the image decoder bitmap fallback path

runtime/dart_controller.cc, runtime/dart_controller.h
=> modify RunFrom<X> methods to return error code rather than call exit

content_handler/runtime_holder.cc, content_handler/runtime_holder.h
=> New mozart input events.

snapshotter/main.cc
Required for simplification in https://github.com/flutter/flutter/pull/8414.
/cc @johnmccutchan
=> --print-deps returns resolved paths

DEPS, snapshotter/main.cc
Bug causing roll-back #3454 has been resolved upstream in tonic.
=> Roll-forward #3454 and roll tonic

lib/ui/painting/image_decoding.cc
Fixes https://github.com/flutter/flutter/issues/8431
=> Do a glFlush after creating textures on the IO thread before they are used by the GPU thread

content_handler/BUILD.gn, content_handler/app.cc
Should be submitted alongside https://fuchsia-review.googlesource.com/c/22338/.
This pull request seems to have multiple commits.  Should i be rebasing, or will it get squashed or something?
=> Flutter content handler initializes ICU data when it starts up

tools/licenses/lib/main.dart
=> whitespace fix

DEPS, travis/licenses_golden/licenses_dart
To pull in @johnmccutchan's changed which makes the VM service accept real URIs.
=> roll dart to a6804167162f230bf8498289a61dc7efebf32b0c

shell/platform/android/io/flutter/app/FlutterActivity.java, shell/platform/android/io/flutter/view/FlutterView.java
See https://github.com/flutter/flutter/issues/7561
=> Send an event to signal memory pressure

shell/platform/darwin/ios/framework/Source/FlutterViewController.mm
iOS counterpart of https://github.com/flutter/engine/pull/3475
=> Wire up memory warning notifications on iOS.

flow/layers/physical_model_layer.cc
See https://github.com/flutter/flutter/issues/8635
=> Update the PhysicalModelLayer child paint bounds to account for the shadow

fml/platform/android/jni_util.cc, fml/platform/android/jni_util.h, fml/platform/android/jni_weak_ref.cc, fml/platform/android/jni_weak_ref.h, fml/platform/android/message_loop_android.cc, fml/platform/android/message_loop_android.h, fml/platform/android/scoped_java_ref.cc, fml/platform/android/scoped_java_ref.h, travis/licenses_golden/licenses_flutter
Includes JNI utilities used by manual bindings. The |ScopedJavaRef| is ported from base.
=> The Android FML backend.

shell/platform/darwin/ios/framework/Source/FlutterChannels.mm, shell/platform/darwin/ios/framework/Source/FlutterStandardCodec.mm, shell/platform/darwin/ios/framework/Source/flutter_standard_codec_unittest.mm
=> Revert "Improved value coverage of Flutter standard codec. Added unit tests."

lib/ui/painting.dart, testing/dart/color_test.dart
Fixes: https://github.com/flutter/flutter/issues/8938
=> Color operator== should compare runtimeTypes

tools/licenses/lib/main.dart
Fixes https://github.com/flutter/flutter/issues/8115
=> Exclude a generated .pyc file from the Dart licenses file tree

flow/layers/physical_model_layer.cc
See https://github.com/flutter/flutter/issues/8929
=> Improve the shadow drawing parameters

content_handler/runtime_holder.cc
Updating SetListener to SetEventListener which comes with a new SetHitViewTester
/cc abarth
=> [flutter] Mozart API changed

lib/ui/BUILD.gn, lib/ui/dart_ui.cc, lib/ui/painting.dart, lib/ui/painting/canvas.cc, lib/ui/painting/canvas.h, lib/ui/painting/vertices.cc, lib/ui/painting/vertices.h, travis/licenses_golden/licenses_flutter
Fixes https://github.com/flutter/flutter/issues/8809
=> Update Canvas.drawVertices to match Skia's latest interface

tools/licenses/lib/main.dart
Fixes https://github.com/flutter/flutter/issues/8968
=> Add .DS_Store to the license script's file name filter

shell/platform/android/BUILD.gn, shell/platform/android/io/flutter/util/PathUtils.java, shell/platform/android/io/flutter/view/FlutterMain.java
This requires a change in the tools. But that has to be applied only when the next engine roll is performed.
=> Rename libsky_shell.so to libflutter.so.

shell/platform/linux/BUILD.gn, sky/engine/platform/BUILD.gn, sky/engine/platform/fonts/FontCacheEmpty.cpp, travis/licenses_golden/licenses_flutter
The also makes font resolution on Mac and Linux desktop shells equivalent.
=> Remove dependency on FontConfig.

tools/licenses/lib/main.dart
android_tools contains a toolchain that is specific to each host platform
Fixes https://github.com/flutter/flutter/issues/8969
=> Skip third_party/android_tools when computing signatures for the license roots

DEPS, lib/ui/painting/vertices.cc, sky/packages/sky_engine/LICENSE
Roll Skia and convert to the new SkVertices factory API (Make & MakeIndexed are no longer supported).
Compile-tested.
=> Roll Skia revision to 342977ced701d06df2b3d2eedd8b64aeae1eb5c5

shell/platform/android/BUILD.gn, shell/platform/android/io/flutter/app/FlutterActivity.java
Customers are reporting issues gradle builds; I'd like to revert this to unblock them while we work on a long term solution.
flutter/flutter#9102
flutter/flutter#9120
flutter/flutter#9121
=> Make FlutterActivity extend from Activity instead of FragmentActivity

shell/platform/darwin/ios/framework/Headers/FlutterViewController.h, shell/platform/darwin/ios/framework/Source/FlutterViewController.mm
Verified no users in the examples.
=> Remove deprecated FlutterInit.

DEPS, sky/packages/sky_engine/LICENSE, travis/licenses_golden/licenses_lib
This makes FTL compilable on Windows.
=> Roll FTL to 77f430179ddc1ad82e9ad3c056b708f583804151

content_handler/BUILD.gn, content_handler/rasterizer.cc, content_handler/runtime_holder.cc, content_handler/runtime_holder.h, content_handler/software_rasterizer.cc, content_handler/software_rasterizer.h, content_handler/vulkan_native_rasterizer.cc, content_handler/vulkan_native_rasterizer.h, content_handler/vulkan_rasterizer.cc, content_handler/vulkan_rasterizer.h, flow/scene_update_context.cc, flow/scene_update_context.h, travis/licenses_golden/licenses_flutter, vulkan/vulkan_proc_table.cc
This version does not recycle buffers. It is meant only as an initial solution,
and the proper buffer recycling logic has been broken out into a separate change
=> Back Vulkan Rasterizer with Mozart View

lib/ui/window/platform_message.cc, lib/ui/window/platform_message.h, lib/ui/window/platform_message_response.h, lib/ui/window/platform_message_response_dart.cc, lib/ui/window/platform_message_response_dart.h, lib/ui/window/window.cc, lib/ui/window/window.h, shell/common/engine.cc, shell/common/platform_view.cc, shell/platform/android/io/flutter/plugin/common/StandardMessageCodec.java, shell/platform/android/io/flutter/view/FlutterView.java, shell/platform/android/platform_view_android.cc, shell/platform/android/platform_view_android.h, shell/platform/android/platform_view_android_jni.cc, shell/platform/darwin/common/buffer_conversions.mm, shell/platform/darwin/ios/framework/Headers/FlutterBinaryMessenger.h, shell/platform/darwin/ios/framework/Source/FlutterChannels.mm, shell/platform/darwin/ios/framework/Source/FlutterCodecs.mm, shell/platform/darwin/ios/framework/Source/FlutterStandardCodec.mm, shell/platform/darwin/ios/framework/Source/FlutterViewController.mm, shell/platform/darwin/ios/framework/Source/platform_message_router.mm
Solves https://github.com/flutter/flutter/issues/9050
=> Distinguish between null platform message and one with zero-byte payload

DEPS, content_handler/BUILD.gn, fml/BUILD.gn, lib/io/BUILD.gn, runtime/BUILD.gn, shell/common/BUILD.gn, shell/platform/android/BUILD.gn, shell/platform/darwin/BUILD.gn, shell/platform/darwin/common/BUILD.gn, shell/platform/darwin/desktop/BUILD.gn, shell/platform/darwin/ios/BUILD.gn, shell/platform/linux/BUILD.gn, sky/engine/core/BUILD.gn, tools/gn, travis/licenses_golden/licenses_dart
=> Adjust GN for removal of libdart.

DEPS, content_handler/BUILD.gn, fml/BUILD.gn, lib/io/BUILD.gn, runtime/BUILD.gn, shell/common/BUILD.gn, shell/platform/android/BUILD.gn, shell/platform/darwin/BUILD.gn, shell/platform/darwin/common/BUILD.gn, shell/platform/darwin/desktop/BUILD.gn, shell/platform/darwin/ios/BUILD.gn, shell/platform/linux/BUILD.gn, sky/engine/core/BUILD.gn, sky/engine/wtf/BUILD.gn, synchronization/BUILD.gn, tools/gn, travis/licenses_golden/licenses_dart
Update targets only included in host_debug_unopt.
=> Adjust GN for removal of libdart, take two.

examples/hello_flutter/lib/main.dart, examples/spinning_square/lib/main.dart, lib/ui/geometry.dart, lib/ui/painting.dart, travis/analyze.sh
@abarth 
This is the engine side. Please do not commit until the framework side is ready.
=> Remove the Point class.

build/flutter_app.gni
This allows tools to locate them more easily.
A copy step was added to make the files available at their previous location as well.
=> Generate flx files in the gen directory.

shell/platform/darwin/ios/ios_surface_software.mm
Also, adds trace events so profiling the software backend is easier.
=> Avoid creating a CGContextRef when generating a CGImageRef from a Skia pixmap.

build/aot_snapshot.py, build/script_snapshot.py
Makes it much easier to get it runnning under gdb.
=> Print gen_snapshot invocation on failure.

shell/gpu/gpu_surface_vulkan.cc
The submit callback now takes an extra argument that is a reference to the surface frame itself.
=> Fix Android Vulkan build.

shell/platform/android/io/flutter/plugin/common/BasicMessageChannel.java, shell/platform/android/io/flutter/plugin/common/BinaryMessenger.java, shell/platform/android/io/flutter/plugin/common/EventChannel.java, shell/platform/android/io/flutter/plugin/common/JSONMethodCodec.java, shell/platform/android/io/flutter/plugin/common/MethodChannel.java, shell/platform/android/io/flutter/view/FlutterView.java
As requested in https://github.com/flutter/flutter/issues/8991.
Android API.
=> Clarify semantics of channel-related errors

vulkan/vulkan_device.cc, vulkan/vulkan_swapchain.cc
=> Account for updated GrVkFormatToPixelConfig signature.

lib/ui/ui.dart
=> Revert "Remove unused import"

build/flutter_app.gni, examples/BUILD.gn, examples/hello_flutter/BUILD.gn
- Fix flutter_aot_app template for moved Flutter tool GN label.
- Add missing dart:io tree-shaking roots.
- Add example AOT app to catch future breakage.
=> Fuchsia AOT:

shell/platform/darwin/BUILD.gn, shell/platform/darwin/desktop/BUILD.gn
The flutter_tester executable works just fine.
=> Don't build the full FlutterTester bundle on Fuchsia.

lib/ui/hooks.dart, lib/ui/window.dart, lib/ui/window/window.cc, runtime/dart_vm_entry_points.txt
See https://github.com/flutter/flutter/issues/7626
=> Add a second per-frame callback that is invoked after the microtask queue is drained

shell/platform/android/io/flutter/plugin/common/BinaryCodec.java, shell/platform/android/io/flutter/plugin/common/JSONMessageCodec.java, shell/platform/android/io/flutter/plugin/common/JSONMethodCodec.java, shell/platform/android/io/flutter/plugin/common/StandardMessageCodec.java, shell/platform/android/io/flutter/plugin/common/StandardMethodCodec.java, shell/platform/android/io/flutter/plugin/common/StringCodec.java, shell/platform/darwin/ios/framework/Headers/FlutterCodecs.h
Partial fix of https://github.com/flutter/flutter/issues/8973.
Companion flutter/flutter PR: https://github.com/flutter/flutter/pull/9635.
=> Document channel message value conversions

DEPS, travis/licenses_golden/licenses_lib
=> Update tonic to fix build

content_handler/vulkan_rasterizer.cc
We now wait for 1 second for the display driver to appear on Fuchsia. This
approach is a stopgap until Vulkan is required for graphics.
=> Wait for Vulkan display driver on Fuchsia

lib/ui/painting.dart, lib/ui/painting/picture.cc, lib/ui/painting/picture.h
Fixes https://github.com/flutter/flutter/issues/6774
=> Add Picture.toImage

vulkan/vulkan_interface.cc
=> Include new Vulkan enum values only on Fuchsia

shell/platform/darwin/ios/framework/Headers/FlutterPlugin.h, shell/platform/darwin/ios/framework/Source/FlutterAppDelegate.mm
Seems the current one is too new for our flutter/engine build setup.
=> Use older openURL signature

shell/platform/darwin/ios/framework/Headers/FlutterPlugin.h
Partial documentation, mainly to get a new github rev and trigger build bots.
=> Add documentation to iOS plugin registry

vulkan/vulkan_debug_report.cc, vulkan/vulkan_utilities.cc, vulkan/vulkan_utilities.h
Disable info debug messages from the layers to cut down log spam.
=> Enable Vulkan validation layers on Fuchsia in debug mode.

content_handler/runtime_holder.cc, content_handler/runtime_holder.h
This patch wires Mozart's text input system to flutter/textinput. This patch
doesn't fully work yet because the Mozart side isn't fully implemented.
=> Wire up Mozart's text input interface

flow/BUILD.gn, flow/layers/backdrop_filter_layer.cc, flow/layers/clip_path_layer.cc, flow/layers/clip_rrect_layer.cc, flow/layers/color_filter_layer.cc, flow/layers/layer.cc, flow/layers/layer.h, flow/layers/layer_tree.cc, flow/layers/layer_tree.h, flow/layers/opacity_layer.cc, flow/layers/physical_model_layer.cc, flow/layers/shader_mask_layer.cc, flow/paint_utils.cc, flow/paint_utils.h, flow/raster_cache.cc, flow/scene_update_context.cc, lib/ui/compositing.dart, lib/ui/compositing/scene.cc, lib/ui/compositing/scene.h, lib/ui/compositing/scene_builder.cc, lib/ui/compositing/scene_builder.h, travis/licenses_golden/licenses_flutter
Fixes https://github.com/flutter/flutter/issues/9473
=> Add a flag that checkerboards offscreen render targets created by SkCanvas.saveLayer

content_handler/runtime_holder.cc, content_handler/runtime_holder.h
Adapting to the IME API changes.
=> Adapting to Mozart API changes for the IME.

lib/ui/window.dart
=> Better onDrawFrame docs

lib/ui/painting/image_decoding.cc
Fixes https://github.com/flutter/flutter/issues/9439
=> Use a new Skia API for safe passing of images across threads and GrContexts

shell/platform/darwin/ios/framework/Source/FlutterAppDelegate.mm
=> Fix a typo

lib/ui/painting.dart
Fixes https://github.com/flutter/flutter/issues/10087
Fixes https://github.com/flutter/flutter/issues/10233
=> Add faster entry points for drawPoints and friends

content_handler/runtime_holder.cc, content_handler/runtime_holder.h
=> Updating to take into account the new Mozart IME Action API

common/settings.h, shell/common/shell.cc, shell/common/switches.h, shell/platform/android/BUILD.gn, shell/platform/android/android_surface.h, shell/platform/android/android_surface_gl.cc, shell/platform/android/android_surface_gl.h, shell/platform/android/android_surface_software.cc, shell/platform/android/android_surface_software.h, shell/platform/android/android_surface_vulkan.cc, shell/platform/android/android_surface_vulkan.h, shell/platform/android/io/flutter/view/FlutterView.java, shell/platform/android/platform_view_android.cc, shell/platform/android/platform_view_android.h, shell/platform/android/platform_view_android_jni.cc, shell/platform/android/platform_view_android_jni.h, travis/licenses_golden/licenses_flutter
Allow Software rendering on Android.
=> Allow switching to the software rendering backend on Android.

shell/platform/android/io/flutter/plugin/editing/TextInputPlugin.java, shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm
Adds support for requesting a platform keyboard optimised for entering
email addresses.
=> Add support for TextInputType.emailAddress

shell/platform/android/io/flutter/plugin/editing/TextInputPlugin.java, shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm
Adds support for requesting a platform keyboard optimised for entering
URLs.
=> Add support for TextInputType.url

DEPS, travis/licenses_golden/licenses_dart
=> Roll dart to 64ce51ce4bc3aa4248dba87c44775c9b84bd2b5d 

flow/layers/layer.h, flow/layers/layer_tree.cc, flow/layers/picture_layer.cc, flow/raster_cache.cc, flow/raster_cache.h, lib/ui/painting/image_decoding.cc, shell/gpu/gpu_surface_gl.cc, shell/gpu/gpu_surface_gl.h, shell/platform/android/android_context_gl.cc, shell/platform/android/android_context_gl.h, shell/platform/android/android_surface_gl.cc, shell/platform/android/android_surface_gl.h, shell/platform/darwin/ios/ios_gl_context.h, shell/platform/darwin/ios/ios_gl_context.mm, shell/platform/darwin/ios/ios_surface_gl.h, shell/platform/darwin/ios/ios_surface_software.mm
Reverts flutter/engine#3716. We also need to upgrade the buildbots to use the iOS 10 SDK.
=> Revert "Run Flutter on iOS and Android with color correct Skia"

lib/ui/window.dart
=> Add breadcrumbs from dart:ui to other docs.

content_handler/runtime_holder.cc, content_handler/runtime_holder.h
Add missing method on RuntimeHolder.
=> Add missing method on RuntimeHolder.

content_handler/BUILD.gn, content_handler/application_controller_impl.cc, content_handler/application_controller_impl.h
This patch adds support for the new way of exposing services from applications.
=> Add support for PA_SERVICE_REQUEST

DEPS, sky/packages/sky_engine/LICENSE, travis/licenses_golden/licenses_dart
This is to pick up assert in constructor initializers support in Frontend.
=> Roll Dart dependency in Flutter engine.

shell/platform/darwin/ios/framework/Headers/FlutterViewController.h, shell/platform/darwin/ios/framework/Source/FlutterViewController.mm
Engine and Android part already done, so this fixes https://github.com/flutter/flutter/issues/10452
=> Add setInitialRoute on FlutterViewController

shell/platform/darwin/ios/framework/Headers/FlutterPlugin.h, shell/platform/darwin/ios/framework/Source/FlutterAppDelegate.mm
I am not sure what else is needed. This is primarily a copy paste.
=> Expose performActionForShortcutItem call to all registered plugins so we can handle quick actions

shell/platform/android/io/flutter/plugin/common/StandardMessageCodec.java
See https://github.com/flutter/flutter/issues/10701
=> Align doubles to 8 bytes in the StandardMessageCodec

shell/common/switches.cc, shell/common/switches.h
See https://fuchsia-review.googlesource.com/#/c/31931/.
=> Update switches to use StringView.
